### ISSUE TITLE
`dotnet nuget` does not support verbosity

### ISSUE THREAD

**Issue by colejohnson66** [NuGet/Home#13966] opened 2024-11-26 21:02 UTC
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

Under `dotnet nuget`, the `--verbosity x` command line flag is unsupported.

### Desired Behavior

It should be supported, and NuGet should be updated to log more.

### Additional Context

The lack of verbosity is very unhelpful when trying to diagnose failures such as #13965

```
Specify --help for a list of available options and commands.
error: Unrecognized option '--verbosity'


Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  -h|--help                      Show help information
  --force-english-output         Forces the application to run using an invariant, English-based culture.
  -s|--source <source>           Package source (URL, UNC/folder path or package source name) to use. Defaults to DefaultPushSource if specified in NuGet.Config.
  -ss|--symbol-source <source>   Symbol server URL to use.
  -t|--timeout <timeout>         Timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  -k|--api-key <apiKey>          The API key for the server.
  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
  --no-service-endpoint          Does not append "api/v2/package" to the source URL.
  --interactive                  Allow the command to block and require manual action for operations like authentication.
  --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.
```

**Comment by jeffkl** [comment] 2024-12-02 21:50
Duplicate of https://github.com/NuGet/Home/issues/6374

**Closed as not planned by jeffkl** 2024-12-02 21:50 UTC
Labels: Resolution:Duplicate, Type:DCR
