### ISSUE TITLE
Clearing cache

### ISSUE THREAD

**Issue by newclaus** [NuGet/Home#8204] opened 2019-06-06 04:23 UTC
There is a button "Clear All Nuget Cache(s)" in the NuGet Package Manager options dialog. By clicking on it all packages are removed from cache. But in most of cases we need remove only previous versions of each package. Could you add an extra button with desired behavior?

**Comment by nkolev92** [comment] 2019-12-31 20:24
Duplicate of https://github.com/NuGet/Home/issues/5713

**Closed as completed by nkolev92** 2019-12-31 20:24 UTC
Labels: Type:Feature, Functionality:VisualStudioUI
