### ISSUE TITLE
Nuget.exe update solution.sln does not use projects from solution but from directory hierarchy

### ISSUE THREAD

**Issue by JanSoundhouse** [NuGet/Home#6166] opened 2017-11-13 15:15 UTC
## Problem

NuGet product used: NuGet.exe
NuGet version (4.3.0.4406)

Nuget.exe does not use the projects from the solution file when updating nuget packages, it only updates projects that are on the same directory level as the .sln file or below.

## Steps to reproduce

To reproduce see the archive attached.
It contains a Visual Studio solution and two projects. Both projects have the package GitVersion v3.6.0 installed. Extract it to some %directory%.
The solution file is under ClassLibrary1\ClassLibrary1.sln, next to it is the first project file ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj.
The second project is at the top level of the zip: ClassLibrary2\ClassLibrary2.csproj.

Now you run '%directory%\ClassLibrary1>nuget update ClassLibrary1.sln -Id GitVersion -Version 3.6.5' on the command line.
Nuget states is has found one project with a packages.config file:
'Found 1 project with a packages.config file. (ClassLibrary1.csproj)'

As another test I removed all the project entries from the solution file, creating an empty solution.
Running the update command on that solution produces the same result as before! ClassLibrary1.csproj gets a new version of GitVersion installed.

This raises the question if this behavior is desired and when so, why do I have to specify a solution if the content does not matter?

### Sample Project
[nugetupdate.zip](https://github.com/NuGet/Home/files/1467299/nugetupdate.zip)

**Comment by nkolev92** [comment] 2017-11-13 23:00
@JanSoundhouse Thanks for creating this issue. 
I can reproduce it. 

This is a bug with the update command and has been there as early as 2.8. ( < 2015) 
When searching for the projects, it just looked at all the children directories, under the solution file. 

Relevant code [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/UpdateCommand.cs#L121-L129)

Ideally it should use the [MsBuildUtility](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L434) like restore. 

Note that this ONLY occurs with the update command, and restore is working as expected. So using a solution is still valid. 

As this a super old bug, not sure about our fix timeline, but we'd welcome a PR.

**Comment by JanSoundhouse** [comment] 2017-11-14 09:46
@nkolev92 Thanks for your quick response.

Unfortunately fixing this is totally out of my scope.. Also I wonder how this works if PackageReference is used in .csproj files?

**Comment by JanSoundhouse** [comment] 2017-11-14 09:47
Sorry, wrong button pressed - just wanted to comment..

**Comment by nkolev92** [comment] 2017-11-14 18:27
The NuGet.exe update command is not implemented for PackageReference at this point.

**Comment by andrewducker** [comment] 2017-11-20 14:36
This is also affecting us - we have solutions dating from VS2002 which were created with the Solution in its own folder in parallell to the projects rather than at the top of a hierarchy.

As a workaround I'm having to iterate over the projects and call the following:
`nuget update .\Myproject\Myproject.csproj -repositorypath .\Solution\packages\`
This works fine - but obviously it would be better if the client coped with it correctly.

**Comment by rrelyea** [comment] 2017-11-21 23:43
As @nkolev92 mentioned, our team is unlikely to get to this. However, marking up for grabs.

**Comment by vdachev** [comment] 2018-01-04 10:33
A side effect of the difference between the behavior of the "update" and the "restore" command is that the "update" command does not process any "packages.**ProjectName**.config" files which makes it impossible to update projects in a solution.

**Comment by andrewducker** [comment] 2018-01-04 10:37
@vdachev - check my comment from 20th November for the workaround I'm using.

**Comment by vdachev** [comment] 2018-01-04 10:54
@andrewducker , there's a something that didn't show up in my previous comment - I meant a "packages.**ProjectName**.config" file that is discovered by the "install" and "restore" commands, as well as recognized by Visual Studio tooling.
Unfortunately, there is no way to specify which "packages.config" file to use for which project. And it happens so that in my case these should be different for each project.

**Comment by vdachev** [comment] 2018-01-17 16:49
I believe this a duplicate of #5241 .

**Comment by anirudhbagri** [comment] 2018-10-04 06:11
Facing the same issue...any update on this?

**Comment by nkolev92** [comment] 2018-10-04 07:29
@anirudhbagri
The status is up to date. 

It's not a difficult fix, we'd welcome a PR.

**Comment by kellyelton** [comment] 2018-11-07 16:57
It appears as though restoring inside of visual studio suffers from this same problem.

**Comment by nkolev92** [comment] 2018-11-07 20:13
@kellyelton 
That's very unlikely. 

NuGet communicates with the project-system to understand which projects are in the solution and loaded, we don't do any custom project discovery. 

What are you seeing?

**Comment by toanbkmt** [comment] 2019-09-20 08:03
Please support command:  **nuget update ProjectName or SolutionName** 
For update all package lastest version in project or solution of .net core.  Because  .net core goodbyte packages.config , all packages dependency have been define in **.csproj**
Many thanks.

**Comment by nkolev92** [comment] 2019-10-01 23:33
Duplicate of https://github.com/NuGet/Home/issues/2747 & #5241

**Closed as completed by nkolev92** 2019-10-01 23:33 UTC
Labels: Priority:3, Type:Bug, Product:NuGet.exe, help wanted, Functionality:Update, Style:Packages.Config
