### ISSUE TITLE
NuGet should install package from local package sources even if disconnected from other feeds.

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5035] opened 2017-04-14 22:54 UTC
Repro steps:
1. Disconnect from Internet
2. dotnet.exe new console
3. dotnet.exe add package <PackagePresentInLocalCache>

Expected: add package and subsequent restores should be able to work off the local package source
Actual: This errors out as NuGet tries to connect to the sources mentioned in nuget.config

This works though if the local package source is provided as:
dotnet add package <PackagePresentInLocalCache> -s "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages"

May be we should provide an **easier** option or configuration in nuget.config for users here to use offline package source first and not error out if the package is found in the offline local package sources.

**Comment by nkolev92** [comment] 2017-09-29 16:54
This is a package source diagnostics related issue. 

We don't allow stuff like this in the Package Reference case because it can lead to inconsistent resolution, so non-repeatable builds. 

Currently the user can do -ignoreFailedSource in nuget.exe/dotnet.exe (or something along those with dashes instead of camelcase)

**Comment by mishra14** [comment] 2017-10-17 18:50
Closing as by design after offline discussion with @emgarten.

**Closed as completed by mishra14** 2017-10-17 18:50 UTC
Labels: Product:VS.Client
