### ISSUE TITLE
Failed to resolve dotnet packages on some machines because feed defined in local NuGet.Config is ignored 

### ISSUE THREAD

**Issue by hongdai** [NuGet/Home#4906] opened 2017-03-28 00:00 UTC
I'm not able to provide a repro because this only happens on some customer machines that I do not have access. However the log shows what has happened.

Failed to resolve dotnet packages on some machines **because feed defined in local NuGet.Config is ignored**
For example, the below output **shows the local config file is used, however the local feed is missing**:
Unable to resolve 'dotnet-svcutil (>= 0.5.10306-preview)' for '.NETCoreApp,Version=v1.1'.
NuGet Config files used:
C:\Users\pennerg\AppData\Roaming\NuGet\NuGet.Config
C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
**C:\Users\pennerg\AppData\Local\Temp\WCFConnectedService\2017_Mar_21_06_41_30\svcutil_bootstrap\NuGet.Config**
**Feeds used:
https://api.nuget.org/v3/index.json
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages**

I can use **dotnet add package -s to restore the package successfully**. The problem is I need to create a process for this operation in the runtime and it's pretty expensive**. Is there an equivalent API I could use?**
**Any recommendation I can reliably resolve the package?** It's a pretty bad experience for our customers.
Thanks,
Hong

**Comment by emgarten** [comment] 2017-03-28 06:33
Dupe of https://github.com/NuGet/Home/issues/4906 which contains more info. @hongdai I'm going to close this one and continue in https://github.com/NuGet/Home/issues/4906

**Closed as completed by emgarten** 2017-03-28 06:33 UTC
Labels: Resolution:Duplicate

**Comment by OskarKlintrot** [comment] 2017-06-09 06:26
I'm having the same issue and I can't find the other issue. Which one are you referring to @emgarten? #4906 is this issue :)

**Comment by OskarKlintrot** [comment] 2017-06-09 06:37
#4907 maybe?

**Comment by emgarten** [comment] 2017-06-09 07:45
@OskarKlintrot yes, #4907 is actually the dupe
