### ISSUE TITLE
The type initializer for 'NuGet.ConfigurationDefaults' threw an exception.

### ISSUE THREAD

**Issue by tvperez** [NuGet/Home#834] opened 2015-06-23 00:48 UTC
Hi All,

I just installed the latest version of the Nuget Console Manager and it appears that no matter what command I use on the Nuget.exe command line app, I get the following exception: The type initializer for 'NuGet.ConfigurationDefaults' threw an exception.

Any ideas on how I can resolve this issue?  Thanks.

Sincerely,
Tony

**Comment by yishaigalatzer** [comment] 2015-06-23 23:01
Hey Tony, can you please provide us with more details?

Are you using visual studio extension or nuget.exe (Console Manager is in visual studio, and nuget.exe is on the command line).

What version are you using? Where did you get it from? What do you mean by installing it.

Are you able to provide a call stack, and a reproducible scenario?

**Comment by tvperez** [comment] 2015-06-24 17:10
Hi Yishai,

I am using both the Visual Studio Extension and the Nuget.exe.  Neither one is working at the moment.

The version is the Nuget.exe is 2.8.5.  I downloaded both the VS Extension and Nuget.exe from http://docs.nuget.org/consume/installing-nuget.

As for the call stack, this is what I get from Nuget.exe:

The type initializer for 'NuGet.ConfigurationDefaults' threw an exception.
     at NuGet.ConfigurationDefaults.InitializeInstance()
     at NuGet.ConfigurationDefaults..cctor()
     --- End of inner exception stack trace ---
     at NuGet.ConfigurationDefaults.get_Instance()
     at NuGet.PackageSourceBuilder.CreateSourceProvider(ISettings settings)
     at NuGet.Commands.Command.Execute()
     at NuGet.Program.Main(String[] args)

Thank you for your time and expertise.

Sincerely,
Tony V Perez

**Comment by yishaigalatzer** [comment] 2015-06-24 19:03
What version of visual studio are you usng?

And can you attach a debugger and get more info on the exception? I can't tell what is the inner exception

**Comment by tvperez** [comment] 2015-06-24 19:06
I am using Visual Studio 2013 Update 4.

As for attaching a debugger, the error occurs the moment I execute the Nuget.exe app.

**Comment by yishaigalatzer** [comment] 2015-06-29 16:05
Here is how to do it, run nuget.exe from visual studio,

Use File->Open project and select Exe Project File from the bottom right drop down

![image](https://cloud.githubusercontent.com/assets/1238711/8412259/8b8875fc-1e3d-11e5-8eef-76c4da9c2149.png)

Then set all the parameters you need on the properties page

![image](https://cloud.githubusercontent.com/assets/1238711/8412318/ece66f7a-1e3d-11e5-86bc-8c51eb0ce498.png)

**Comment by tvperez** [comment] 2015-06-29 16:43
Hi Yishai,

When I loaded the Nuget.exe as a project, I received the following message:
[cid:image001.jpg@01D0B250.15584AA0]

As for debugging, the executable terminates even if I tried to use the Debug “Step into new process”.  As for the activity log, this is what was logged:
…
<entry>
    <record>1348</record>
    <time>2015/06/29 16:36:39.446</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [IntegrationPackage]</description>
    <guid>{D209E4D9-0F58-4BC3-A529-FDCF20967DC0}</guid>
  </entry>
  <entry>
    <record>1349</record>
    <time>2015/06/29 16:36:40.399</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function VBDispatch::GetTypeLib</description>
  </entry>
  <entry>
    <record>1350</record>
    <time>2015/06/29 16:36:40.399</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Leaving function VBDispatch::GetTypeLib</description>
    <guid>{80CC9F66-E7D8-4DDD-85B6-D9E6CD0E93E2}</guid>
  </entry>
  <entry>
    <record>1351</record>
    <time>2015/06/29 16:36:40.461</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [IntegrationPackage]</description>
    <guid>{D209E4D9-0F58-4BC3-A529-FDCF20967DC0}</guid>
    <hr>80131509</hr>
    <errorinfo>GetExportedValue cannot be called before prerequisite import 'NuGet.VisualStudio.VsPackageSourceProvider..ctor (Parameter="settings", ContractName="NuGet.ISettings")' has been set.</errorinfo>
  </entry>
  <entry>
    <record>1352</record>
    <time>2015/06/29 16:36:40.477</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [IntegrationPackage]</description>
    <guid>{D209E4D9-0F58-4BC3-A529-FDCF20967DC0}</guid>
    <hr>80131509</hr>
    <errorinfo>Object reference not set to an instance of an object.</errorinfo>
  </entry>


Sincerely,
Tony V Perez

**Comment by yishaigalatzer** [comment] 2015-07-01 16:40
The log doesn't seem related to nuget.exe, and the image didn't come through.

Can you try again to share the image? Perhaps use github.com directly instead of by email?

**Comment by tvperez** [comment] 2015-07-01 17:15
I’ve attached the image.

The log was generated when attempting to use the Nuget package from VS2013.  So far, it appears that this issue is due to the Nuget application inability to load a configuration file.  My questions are:

1.       Which configuration file or registry entry is consumed when the Nuget application initializes?

2.       Is it possible to force the Nuget.exe to start in verbose mode?

**Comment by tvperez** [comment] 2015-07-01 17:45
Hi Yishai,

Here’s a stack trace generated from Nuget.exe:

     at NuGet.ConfigurationDefaults.InitializeInstance()
     at NuGet.ConfigurationDefaults..cctor()
     --- End of inner exception stack trace ---
     at NuGet.ConfigurationDefaults.get_Instance()
     at NuGet.PackageSourceBuilder.CreateSourceProvider(ISettings settings)
     at NuGet.Commands.Command.Execute()
     at NuGet.Program.Main(String[] args)

Does this help?

Sincerely,
Tony V Perez
From: Tony Perez
Sent: Wednesday, July 1, 2015 10:15 AM
To: NuGet/Home <reply@reply.github.com>; NuGet/Home <Home@noreply.github.com>
Subject: RE: [Home] The type initializer for 'NuGet.ConfigurationDefaults' threw an exception. (#834)

I’ve attached the image.

The log was generated when attempting to use the Nuget package from VS2013.  So far, it appears that this issue is due to the Nuget application inability to load a configuration file.  My questions are:

1.      Which configuration file or registry entry is consumed when the Nuget application initializes?

2.      Is it possible to force the Nuget.exe to start in verbose mode?

**Comment by tvperez** [comment] 2015-07-01 17:50
Hi Yishai,

Here’s a stack trace generated from Nuget.exe:

     C:\UStoreLoadTesting_Main_Perm>nuget restore "C:\UStoreLoadTesting_Main_Perm\nup
kgs\packages.config" -Verbosity Detailed
System.TypeInitializationException: The type initializer for 'NuGet.Configuratio
nDefaults' threw an exception. ---> System.Xml.XmlException: '.', hexadecimal va
lue 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, I
nt32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, LoadOptions options)
   at NuGet.XmlUtility.GetDocument(IFileSystem fileSystem, String path)
   at NuGet.XmlUtility.GetOrCreateDocument(XName rootName, IFileSystem fileSyste
m, String path)
   at NuGet.Settings.<>c__DisplayClass1.<.ctor>b__0()
   at NuGet.Settings.ExecuteSynchronized(Action ioOperation)
   at NuGet.Settings..ctor(IFileSystem fileSystem, String fileName, Boolean isMa
chineWideSettings)
   at NuGet.ConfigurationDefaults..ctor(IFileSystem fileSystem, String path)
   at NuGet.ConfigurationDefaults.InitializeInstance()
   at NuGet.ConfigurationDefaults..cctor()
   --- End of inner exception stack trace ---
   at NuGet.ConfigurationDefaults.get_Instance()
   at NuGet.PackageSourceBuilder.CreateSourceProvider(ISettings settings)
   at NuGet.Commands.Command.Execute()
  at NuGet.Program.Main(String[] args)
Does this help?

Sincerely,
Tony V Perez
From: Tony Perez
Sent: Wednesday, July 1, 2015 10:15 AM
To: NuGet/Home <reply@reply.github.com>; NuGet/Home <Home@noreply.github.com<mailto:Home@noreply.github.com>>
Subject: RE: [Home] The type initializer for 'NuGet.ConfigurationDefaults' threw an exception. (#834)

I’ve attached the image.

The log was generated when attempting to use the Nuget package from VS2013.  So far, it appears that this issue is due to the Nuget application inability to load a configuration file.  My questions are:

1.      Which configuration file or registry entry is consumed when the Nuget application initializes?

2.      Is it possible to force the Nuget.exe to start in verbose mode?

**Comment by yishaigalatzer** [comment] 2015-07-01 19:18
Look for nuget.config files in your folder and up the tree, and also in XXX\AppData\Roaming\NuGet

**Comment by yishaigalatzer** [comment] 2015-07-09 23:54
ping, any updates?

**Comment by yishaigalatzer** [comment] 2015-11-17 23:22
This looks like a duplicate of an issue we have for throwing proper exception when configuration is corrupt. The error should throw the file name that is introducing the problem.

**Closed** 2015-11-17 23:23 UTC
