### ISSUE TITLE
App.xaml as contentFiles doesn't work

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#1980] opened 2016-01-23 20:05 UTC
I am trying to provide an App.xaml as a contentFile. When trying this though, despite the pp renames appearing to work, I get the following error:

```
1>Target "GetXamlCppIncludeDirectories" skipped, due to false condition; ('$(ManagedAssembly)'=='false' and '$(XamlCppIncludeDirectories)' == '') was evaluated as (''=='false' and '' == '').
1>Target "MarkupCompilePass1" in file "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets" from project "C:\Users\oren\Source\Git\devices.xunit\integration\integration.uwp\integration.uwp.csproj" (target "PrepareResources" depends on it):
1>Task "MakeDir"
1>Done executing task "MakeDir".
1>Using "CompileXaml" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.Build.Tasks.dll".
1>Task "CompileXaml"
1>C:\Users\oren\Source\Git\devices.xunit\integration\integration.uwp\integration.uwp.csproj : XamlCompiler error WMC1008: Application main file must be named App.xaml
1>Done executing task "CompileXaml" -- FAILED.
1>Done building target "MarkupCompilePass1" in project "integration.uwp.csproj" -- FAILED.
```

This might be related to #1979 as this could be caused by a missing `<Generator>MSBuild:Compile</Generator>` on the `ApplicationDefinition` Item.

When I look at the `obj\debug\nuget\...\xunit.runner.devices\2.0.0-rc2-build0003\` dir, I do see the correctly transformed files. I also do not see the generated .g.cs or .i.g.cs files for the app.xaml.

**Comment by yishaigalatzer** [comment] 2016-01-26 01:22
Did you define the build action as `ApplicationDefinition` ? It's hard to tell from the report (I'm assuming you did).

Assuming the root cause is the build task - Assigning to CC @jasonmalinowski 

Aside - It is kinda weird to include an app.xaml as part of contentfiles given that it is current immutable.

**Comment by clairernovotny** [comment] 2016-01-26 01:30
Yes, I did. 

I have a reason for including it -- it's for the xUnit device runner where it's provided:

https://github.com/xunit/devices.xunit/tree/master/src/xunit.runner.uwp/NuGet

The idea is that user creates new app, adds xunit device runner, deleted existing app.xaml and is all ready to go.

If they need additional customization, it's enabled with a partial method in a partial class.

**Comment by jasonmalinowski** [comment] 2016-01-26 02:17
@onovotny, can you provide a full build log of the project with /v:diag passed to MSBuild?

**Comment by yishaigalatzer** [comment] 2016-02-23 00:16
This issue has gone stale, @onovotny @jasonmalinowski can we close it, or can it be revived?

**Comment by clairernovotny** [comment] 2016-02-23 04:23
This is still an issue, there's no way to properly usea xaml file as content because you can't set the right metadata.

**Comment by yishaigalatzer** [comment] 2016-02-23 04:24
Can you please share what Jason was asking for?

**Comment by clairernovotny** [comment] 2016-02-23 13:59
Here it is:
https://gist.github.com/onovotny/ae9e9fbff3a3f7b61137#file-integration-uwp-build-log-L2248-L2257

You can see in the highlighted lines that the App.xaml and app.xaml.cs are getting included and that the item type should be correct. However, there's no way to set the Generator metadata as MSBuild:Compile. This would be needed for any XAML file. The other item type, for a regular XAML page is Page, but it'd still need the generator set.

Here's the item from the csproj in a diff project:

``` XAML
  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
  </ItemGroup>
```

**Comment by yishaigalatzer** [comment] 2016-02-23 15:39
Oren - thinking about this out loud. At this point you are looking for a full msbuild projection into content files. since this a very specific use case AND we do have a way to represent msbuild in nuget (using targets), why won't you use targets here?

**Comment by clairernovotny** [comment] 2016-02-23 15:44
I cannot use targets here because I need the pp transformation. This is really a manifestation of https://github.com/NuGet/Home/issues/1979. In there, you could specify metadata that each build task could implement as needed.

I don't need full msbuild projections, just control over the additional item metadata.

There are other instances too -- like `.tt` files. Need to set item specific metadata.

**Comment by yishaigalatzer** [comment] 2016-02-23 15:48
Thanks for the reminder, out of curiosity how did you do it before nuget 3?

**Comment by clairernovotny** [comment] 2016-02-23 15:49
I couldn't, I used a content as a text file that the user saw in their project and could copy/paste. Since these content files don't show up in the project, I can't have them do that....they'll never see the template to copy/paste from.

**Comment by jasonmalinowski** [comment] 2016-02-25 00:52
One possible workaround: instead of creating this directly into the ApplicationDefinition group, create it under your own group, and then also include a .targets in your package that finds that item and adds it to ApplicationDefinition with the metadata you want. I really don't want to go down the rats nest of NuGet having to know about each type of metadata that you need (but I admit that's probably best to play whack-a-mole rather than giving everybody the workaround.)

**Comment by clairernovotny** [comment] 2016-02-25 01:09
I would not suggest that NuGet should know about any metadata. I would suggest that there be a generalized key/value mechanism where the package author can specify arbitrary metadata that the build system can transform into an appropriate format.

**Comment by yishaigalatzer** [comment] 2016-02-25 01:15
That is what targets are for, the generalozed settings discussed only work in msbuild. From what you are saying you are just need support for transforming a pp file as input to your target

**Comment by clairernovotny** [comment] 2016-02-25 01:20
Yes, sorta, sure. 

Point being is that Page and ApplicationDefinition were already put as supported item types, but they can't work without that extra metadata.

**Comment by yishaigalatzer** [comment] 2016-02-25 01:23
Jason that's in your field. I would say that we want default stuff to work at least

**Comment by jasonmalinowski** [comment] 2016-02-25 01:25
Well we have to be careful with "default stuff" here. I just pass through the value unchanged from the lock file. Did we document a list of types that we expect to really work?

**Comment by clairernovotny** [comment] 2016-02-25 01:39
Btw,  I'm referring to that whitelist for validating the item types on restore.

**Comment by rrelyea** [comment] 2016-12-09 00:34
@onovotny - ApplicationDefinition and Page need this in UWP and/or WPF? (don't think WPF strictly needs)

**Comment by clairernovotny** [comment] 2016-12-09 00:51
Yes, they are needed in UWP. Ditto with Xam Forms for their XAML. I don't think much has changed since I filed the issue in terms of scenarios.

**Comment by ChrisMaddock** [comment] 2016-12-28 22:35
I believe we've just encountered the same issue with the NUnit Xamarin project. We wanted to use a .pp file to replace MainPage.xaml. Pretty much exactly the same use-case, it sounds like. 😄

**Comment by clairernovotny** [comment] 2017-02-20 21:07
Ping? @rrelyea @emgarten ?

**Comment by emgarten** [comment] 2017-11-09 22:34
@onovotny is this still an issue?

**Comment by nkolev92** [comment] 2018-02-22 20:28
Closing this issue, as we haven't had any activity on it. 

Please open another issue if you're facing similar problems.

**Closed as completed by nkolev92** 2018-02-22 20:28 UTC
