### ISSUE TITLE
[Pack] The option “--version-suffix” is not respected when using “--version-suffix” and “-p:PackageVersion” meanwhile in command “dotnet pack”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11188] opened 2021-08-27 10:44 UTC
## Details about Problem
VS Version: Main\31625.270
NuGet Version: Dev\6.0.0.213
OS Version: Windows-10-Enterprise-21H1

## Repro steps
1. Launch VS and create a new C# Class Library (.NET 6.0).
2. Open the Developer Command Prompt and cd to the project path.
3. Run command “dotnet pack -c Release --version-suffix "Jamie" -p:PackageVersion=3.0.0”.

## Expected
Both two options  “--version-suffix” and “-p:PackageVersion” should be respected.

## Actual
The option “--version-suffix” is not respected when using “--version-suffix” and “-p:PackageVersion” meanwhile in command “dotnet pack” as below. 
![image](https://user-images.githubusercontent.com/20632625/131115158-3f2debd8-7ca4-4410-bc3e-03e556936495.png)

## Note:
1.It doesn’t repro on “nuget pack” command when using “-Suffix” and “-Version” meanwhile since both two options will be respected as below.
![image](https://user-images.githubusercontent.com/20632625/131114430-4f79b126-23b5-438d-9793-a111125a5a1b.png)
2.It is not a regression bug.
3.The package doesn't even pack on .net sdk 5.0.
```
dotnet pack -c Release --version-suffix "Jamie" -p:PackageVersion=3.0.0
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Determining projects to restore...
Restored C:\NuGetProj\IssueRepro\11105\11105.csproj (in 55 ms).
11105 -> C:\NuGetProj\IssueRepro\11105\bin\Release\net5.0\11105.dll
```

**Comment by kartheekp-ms** [comment] 2021-08-30 21:10
@v-luzh - This looks by design to me. As per docs https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack, `If Version has a value and you pass --version-suffix to dotnet pack, the value specified for --version-suffix is ignored. ` In the repro steps you have mentioned, `-p:PackageVersion` is passed to the command line which I assume is equivalent to `Version` property in the project file.

**Comment by zkat** [comment] 2021-09-01 01:16
This seems to be working as intended, as per @kartheekp-ms, so I'm closing this.

**Closed as completed by zkat** 2021-09-01 01:16 UTC
Labels: Type:Bug, Functionality:Pack, Product:dotnet.exe, Resolution:NotABug, Found:ManualTests
