### ISSUE TITLE
error MSB4018: System.ArgumentException: Invalid framework version '4.7.2/win'

### ISSUE THREAD

**Issue by tom-englert** [NuGet/Home#13015] opened 2023-11-15 14:33 UTC
### NuGet Product Used

NuGet.exe

### Product Version

6.8.0.131

### Worked before?

6.7

### Impact

I'm unable to use this version

### Repro Steps & Context

After build pipeline had updated nuget.exe to 6.8, the build fails reproducible with:

`...Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: System.ArgumentException: Invalid framework version '4.7.2/win'`

The projects target frameworks did not change: `<TargetFrameworks>net472;netstandard2.0</TargetFrameworks>`

After pinning nuget to 6.7, build succeeded again.

The build output can be observed here: https://dev.azure.com/tom-englert/Open%20Source/_build?definitionId=35

The sources of the project can be found here:  https://github.com/dotnet/ResXResourceManager

A similar issue has been reported here: https://github.com/dotnet/sdk/issues/16666

### Verbose Logs

```shell
"D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj" (default target) (3:8) ->
(ResolvePackageAssets target) -> 
  C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: System.ArgumentException: Invalid framework version '4.7.2/win'. [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at NuGet.Frameworks.NuGetFramework.ParseFrameworkNameParts(IFrameworkNameProvider mappings, String[] parts, String& framework, Version& version, String& profile) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at NuGet.Frameworks.NuGetFramework.ParseFrameworkName(String frameworkName, IFrameworkNameProvider mappings) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at NuGet.Frameworks.NuGetFramework.Parse(String folderName, IFrameworkNameProvider mappings) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.<>c__DisplayClass59_0.<WritePackageDependenciesDesignTime>b__6(String tg) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.<>c__DisplayClass59_0.<WritePackageDependenciesDesignTime>b__4(IAssetsLogMessage log) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at System.Linq.Enumerable.WhereListIterator`1.MoveNext() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.<WritePackageDependenciesDesignTime>g__GetPackageDiagnosticLevel|59_2(LockFileLibrary package) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WritePackageDependenciesDesignTime() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroup(Action writeItems) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroups() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.Write() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteToCacheFile() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task) [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\a\1\s\src\ResXManager.Infrastructure\ResXManager.Infrastructure.csproj::TargetFramework=netstandard2.0]
```

**Comment by nkolev92** [comment] 2023-11-20 21:41
Hey @tom-englert, 


2 ideas: 

- Any reason why you can't use `dotnet restore` or `msbuild -t:restore`? Looks like all of your projects are SDK based and we recommend that restore & build tooling have equivalent versions and in your build that's not the case. 6.8 aligns to 8.0.100 version of the SDK.  
- Any chance you can provide us an assets file generated with 6.7 and one generated with 6.8?

**Comment by tom-englert** [comment] 2023-11-21 09:47
Attached the assets (obj folders) generated from 6.7 and 6.8 nuget.exe:
[6.8.zip](https://github.com/NuGet/Home/files/13424551/6.8.zip)
[6.7.zip](https://github.com/NuGet/Home/files/13424552/6.7.zip)

**Comment by tom-englert** [comment] 2023-11-21 10:00
Looks like an unlucky combination of tools: Now that the Microsoft-hosted agents have been updated to dotnet 8, it works also with nuget 6.8

**Comment by nkolev92** [comment] 2023-11-21 18:32
Looking at the 6.7 and 6.8 assets file and they're equivalent. 
Given that, I think we need to close it as the duplicate of https://github.com/dotnet/sdk/issues/16666, as that's the right repo for the changes.

**Closed as not planned by nkolev92** 2023-11-21 18:32 UTC
Labels: Type:Bug, Resolution:External, Functionality:Restore
