### ISSUE TITLE
"License Acceptence" window should be extended by "changed from ... to ..." and "new not known license model for package ..."

### ISSUE THREAD

**Issue by Aldebaran91** [NuGet/Home#13984] opened 2024-12-04 10:17 UTC
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

Some software vendors change the licence model of their nuget after a new version. For example, Extended.Wpf.Toolkit has changed its licence model several times.

From Version 3.6.0 with MS-PL to 3.7.0 to "Xceed Software License" (for non-commercial use).

I want a big red call sign to indicate that the licence has changed from the previous version. I only want to check/read the licence once when installing. This extension would help companies avoid using nuget versions that are not allowed because they have changed the licence to non-commercial use.

For "Extended.Wpf.Toolkit" it didn't even showed me the "License Acceptence" window when I updated the nuget.

My second suggestion is that Visual Studio allows me to white list license models like "MS-PL" or "MIT" which I checked for my company. The "License Acceptence" window should show me that there is a non accepted new license model.

![nugetlicenseacceptance](https://github.com/user-attachments/assets/326cd5f6-c310-400b-ba6e-c59605b5ef9a)

**Comment by nkolev92** [comment] 2024-12-16 21:47
Duplicate of https://github.com/NuGet/Home/issues/11520

**Closed as not planned by nkolev92** 2024-12-16 21:47 UTC
Labels: Resolution:Duplicate, Type:Feature, Functionality:VisualStudioUI, Functionality:Install
