### ISSUE TITLE
dotnet list package looking for nuget.config on the wrong place?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [NuGet/Home#13017] opened 2023-11-15 23:58 UTC
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 8.0.100

### Worked before?

don't know...

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Im on a MAC, Sonoma 14.0 (23A344).

I'm at the root folder of my solution. if I run
`dotnet list MySolution.MyApiProject package --outdated`
it spits back
`error: Unexpected failure reading NuGet.Config. Path: '/Users/MyUser/Projects/MySolution/MySolution.MyApiProject/MySolution.MyApiProject.csproj/NuGet.Config'.`

but if I `cd MySolution.MyApiProject` and `dotnet list package --outdated` it works as expected...

### Verbose Logs

```shell
error: Unexpected failure reading NuGet.Config. Path: '/Users/myUser/Projects/MySolution/MySolution.MyApiProject/MySolution.MyApiProject.csproj/NuGet.Config'.
error:   The file '/Users/myUser/Projects/MySolution/MySolution.MyApiProject/MySolution.MyApiProject.csproj' already exists.
trace: System.AggregateException: One or more errors occurred. (Unexpected failure reading NuGet.Config. Path: '/Users/myUser/Projects/MySolution/MySolution.MyApiProject/MySolution.MyApiProject.csproj/NuGet.Config'.)
trace:  ---> NuGet.Configuration.NuGetConfigurationException: Unexpected failure reading NuGet.Config. Path: '/Users/myUser/Projects/MySolution/MySolution.MyApiProject/MySolution.MyApiProject.csproj/NuGet.Config'.
trace:  ---> System.IO.IOException: The file '/Users/myUser/Projects/MySolution/MySolution.MyApiProject/MySolution.MyApiProject.csproj' already exists.
trace:    at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
trace:    at System.IO.Directory.CreateDirectory(String path)
trace:    at NuGet.Configuration.FileSystemUtility.AddFile(String fullPath, Action`1 writeToStream)
trace:    at NuGet.Configuration.FileSystemUtility.GetOrCreateDocument(XDocument content, String fullPath)
trace:    at NuGet.Configuration.SettingsFile.<>c__DisplayClass23_0.<.ctor>b__0()
trace:    at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
trace:    --- End of inner exception stack trace ---
trace:    at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
trace:    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
trace:    at NuGet.Configuration.SettingsFile..ctor(String directoryPath, String fileName, Boolean isMachineWide, Boolean isReadOnly)
trace:    at NuGet.Configuration.Settings.ReadSettings(String settingsRoot, String settingsPath, Boolean isMachineWideSettings, Boolean isAdditionalUserWideConfig, SettingsLoadingContext settingsLoadingContext)
trace:    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
trace:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
trace:    at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
trace:    at NuGet.Configuration.Settings.LoadSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
trace:    at NuGet.CommandLine.XPlat.ListPackageCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext()
trace:    --- End of inner exception stack trace ---
trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
trace:    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
trace:    at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)
```

**Comment by jeffkl** [comment] 2023-11-16 00:43
Team triage:  Looks like a duplicate of https://github.com/NuGet/Home/issues/12954
Please add a 👍 reaction to upvote that issue.

**Closed as not planned by jeffkl** 2023-11-16 00:43 UTC
Labels: Resolution:Duplicate, Type:Bug

**Comment by Leonardo-Ferreira** [comment] 2023-11-16 12:14
Hey @jeffkl thanks for the input but I don't believe this is a duplicate... you see, the command in question is the same but the parameters and scopes are completely different, along with the error message... can you please reopen this one?

**Comment by zivkan** [comment] 2023-11-16 12:58
@Leonardo-Ferreira the error messages look the same to me.

In this issue you copied the error:

> error: Unexpected failure reading NuGet.Config. Path: '/Users/myUser/Projects/MySolution/MySolution.MyApiProject/MySolution.MyApiProject.csproj/NuGet.Config'.
> error:   The file '/Users/myUser/Projects/MySolution/MySolution.MyApiProject/MySolution.MyApiProject.csproj' already exists.

From the other issue:

> error: Unexpected failure reading NuGet.Config. Path: 'PATH TO SLN DIRECOTRY\XXX.sln\NuGet.Config'.
> error:   Cannot create 'PATH TO SLN DIRECOTRY\XXX.sln' because a file or directory with the same name already exists.

Both issues are using the syntax `dotnet list <target> package <args>`, and the first error line says `Path: '<target>\NuGet.Config'` and the second error says `the file '<target>' already exists`.

So, I certainly have the impression that the root cause is the same and one code fix will resolve both issues.
