### ISSUE TITLE
[Question] Update NuGet package dependencies with VS2017 PackageReference 

### ISSUE THREAD

**Issue by alex-zyl** [NuGet/Home#6185] opened 2017-11-14 20:06 UTC
NuGet package may reference other packages that are not up-to-date at the moment of adding to the project.
Example: 

Latest Microsoft.Azure.Search 3.0.4
--> Microsoft.Rest.ClientRuntime 2.3.7
      ... other dependencies

Latest Microsoft.Rest.ClientRuntime --2.3.10

With packages.config all dependent packages are installed along with initial package and can be updated to latest on Update tab all at once.

With PackageReference developer has to traverse dependency graph and install desired latest dependent packages manually.
With packages that bring dozens of dependent packages (like AspNetCore or EFCore) this actions are tedious.

Is it in plans to support updating dependent packages like we currently have with packages.config?

**Comment by emgarten** [comment] 2017-11-14 20:36
Duplicate of https://github.com/NuGet/Home/issues/5887

**Comment by alex-zyl** [comment] 2017-11-14 20:39
@emgarten  
I was trying to find similar threads. That's what i was looking for. Thanks!
Closing this one

**Closed as completed** 2017-11-14 20:39 UTC
Labels: Resolution:Duplicate
