### ISSUE TITLE
contentFiles feature issue

### ISSUE THREAD

**Issue by rzaitov** [NuGet/Home#3996] opened 2016-11-22 15:11 UTC
[Nugetizer]

https://github.com/rzaitov/selfContained/tree/master/Nugetizer3000/SingleLibrary

I want to use `contenFiles` feature. In other words I want to create a package with some content files (for example some txt or json file with settings or cs file with code) which should be included into consuming project.

The [NuGetizer-Core-Features](https://github.com/NuGet/Home/wiki/NuGetizer-Core-Features#package-files) describes this:
```
Since content files have particular requirements on placement (code language and target framework are required), support for None items is also provided: just annotate them with IncludeInPackage=true item metadata, and they will be included as package files in the relative target path they have within the project. So you can, for example, define your own None items under a contentFiles\cs\any\ folder to get them included in consuming C# projects of any target framework.
```

I created a [test arrangement](https://github.com/rzaitov/selfContained/tree/master/Nugetizer3000/SingleLibrary) for this scenario. There are `Important.cs` and `mySettings.txt` which have `Build action` set to `None` and `Include  in Package` is toggled:
```
    <None Include="contentFiles\cs\any\TopFolder\NestedFolder\mySettings.txt">
      <IncludeInPackage>true</IncludeInPackage>
    </None>
    <None Include="contentFiles\cs\any\TopFolder\NestedFolder\Important.cs">
      <IncludeInPackage>true</IncludeInPackage>
    </None>
```
When I create a package and then inspect it everything looks good (content files are under contentFiles folder in nupkg archive), but when I try to consume this package I couldn't find `mySettings.txt` and `Important.cs` within consuming project.

Here is about XS:  https://gist.github.com/3f22048060b4a7eac3144a03b31fa58c
Test arrangement's commit (self contained project) is bfc40d420c4ca9702c2ab50a85d35f7da6188c1b.

**Comment by mrward** [comment] 2016-11-22 15:28
If the .nupkg looks OK and works in Visual Studio then the problem is more likely to be with Xamarin Studio.

**Comment by mrward** [comment] 2016-11-22 17:55
OK so this is not a Xamarin Studio problem.

First, contentFiles are only supported with projects that use a project.json file. To support projects that use a packages.config file then the files would need to be added to a Content folder inside the .nupkg.

If you have a project.json file then both Xamarin Studio and Visual Studio will add the contentFiles into the project.lock.json file.

```
  "targets": {
    ".NETFramework,Version=v4.5": {
      "SelfContained.SingleLibrary/1.0.13": {
        "type": "package",
        "frameworkAssemblies": [
          "System",
          "System.Core"
        ],
        "compile": {
          "lib/net45/JustSingleLibrary.dll": {}
        },
        "runtime": {
          "lib/net45/JustSingleLibrary.dll": {}
        },
        "contentFiles": {
          "contentFiles/cs/any/TopFolder/NestedFolder/Important.cs": {
            "buildAction": "Compile",
            "codeLanguage": "cs",
            "copyToOutput": false
          },
          "contentFiles/cs/any/TopFolder/NestedFolder/mySettings.txt": {
            "buildAction": "Compile",
            "codeLanguage": "cs",
            "copyToOutput": false
          }
        }
```

Now a problem occurs with building since Mono's MSBuild and xbuild seem to ignore any files in the project.lock.json file. Visual Studio will try to compile these contentFiles and it fails since the .txt file is added as a C# file.

So the only problem I can see is with Mono's MSBuild. Neither xbuild nor msbuild 15 in Mono 4.8 seem to work.

I suspect that since project.json is being replaced with the new .NET Core style projects that this will not be fixed in Mono. There is an existing problem with generated MSBuild imports (.nuget.targets) not being used when using project.json file which has been marked as not on roadmap in Mono.

**Comment by rzaitov** [comment] 2016-11-22 20:09
@mrward, thank for clarifying this. Since Mono has troubles with project.json then this could be used only on Windows (VS or XS).

I tried to build a package (JustSingleLibrary) and then consume it in PCL (PCL support project.json) on Windows via VS. When I install the package `mySettings.txt` and `Inportant.cs` are not added to the project. This contradicts with our spec:

> So you can, for example, define your own None items under a contentFiles\cs\any\ folder to get them included in consuming C# projects of any target framework.

When I create a package and then check nuspec inside I am able to observe the following

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>SelfContained.SingleLibrary</id>
    <version>1.0.13</version>
    <title></title>
    <authors>Rustam Zaitov</authors>
    <owners>Rustam Zaitov</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>test for single library template</description>
    <summary></summary>
    <releaseNotes></releaseNotes>
    <copyright></copyright>
    <language></language>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
    </frameworkAssemblies>
  </metadata>
</package>
```

There is no `contentFiles` tag, but I believe it should be here

**Comment by yishaigalatzer** [comment] 2016-11-22 21:22
The files are added but are not visible in the tree. This is being addressed in visual studio 2017. You should be able to see them in the compilation results (note they are not designed to be editable, that will come at a later release)

**Comment by mrward** [comment] 2016-11-22 22:43
The .nuspec file may or may not have contentFiles information in the .nuspec. It depends on whether you need to specify things like the buildAction. For None items then no information in the .nuspec looks OK to me. To specify the buildAction it looks like you would need to add a PackageFile item and add the extra metadata there.

**Comment by kzu** [comment] 2016-12-06 15:27
You can specify all the contentFile metadata on the items themselves. See https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Build/NuGet.Build.Packaging.Tasks/CreatePackage.cs#L150-L153

i.e.:
```
<None Include="contentFiles\cs\any\TopFolder\NestedFolder\mySettings.txt">
      <IncludeInPackage>true</IncludeInPackage>
      <BuildAction>Content</BuildAction>
      <CopyToOutput>...</CopyToOutput>
      <Flatten>true</Flatten>
</None>
```

**Comment by kzu** [comment] 2016-12-06 18:48
@rzaitov the files node in the nuspec are used to construct the nupkg, they aren't needed in the nuspec inside the nupkg because whatever is inside the nupkg, is whatever files made it in ;).

Closing this since it's neither a targets nor a VS issue.

**Closed as completed by kzu** 2016-12-06 18:48 UTC
Labels: Product:NuGetizer
