### ISSUE TITLE
Feature Request: Add tree structr back into project selection in VS Ad-in

### ISSUE THREAD

**Issue by ravensorb** [NuGet/Home#2873] opened 2016-06-01 00:36 UTC
In the VS 2013 nuget package manager it was possible to manage projects based on their folder structure taken from the solution.  This was extremely useful in solutions with a large number of projects.  Please consider bringing this feature back -- either that or provide a way to "filter" the list of projects.

**Comment by donnie-msft** [comment] 2020-11-03 05:55
I'm assuming this is referring to the Projects list with checkboxes over in the Details pane on the right.
Dupe of https://github.com/NuGet/Home/issues/9081

**Closed as completed by donnie-msft** 2020-11-03 05:55 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Priority:3, Type:Feature, Functionality:VisualStudioUI
