### ISSUE TITLE
Package Manager displaying error

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#4756] opened 2017-03-06 17:41 UTC
**Repro steps**

•	Create a .net core console project;
•	Right click the solution and add a new standard class library project;
•	Add the reference from console to standard class. Build it succeeded.
	But if close the solution and reopen it. if choosing the “Package Manager” in Output window, an error message is shown as below:
Error occurred while restoring NuGet packages: The operation failed as details for project ConsoleApp2 could not be loaded.
Restoring NuGet packages...
Time Elapsed: 00:00:00.6876145
========== Finished ==========
         Right click the solution and click “Restore NuGet Packages” and restore completed with no error message. But if closing the solution and reopen it, the error message above is still shown.

**Build**
d15rel.15.1.26304.0 preview

**Comment by emgarten** [comment] 2017-03-06 18:57
@jinujoseph thanks for the report, this looks like a dupe of https://github.com/NuGet/Home/issues/4577 https://github.com/NuGet/Home/issues/4307

Let me know if you disagree

**Closed as completed** 2017-03-06 18:57 UTC
Labels: Resolution:Duplicate
