### ISSUE TITLE
Specify exact version of a project dependency

### ISSUE THREAD

**Issue by Necroskillz** [NuGet/Home#5525] opened 2017-07-03 13:07 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

dotnet.exe --version (if appropriate): 2.0.0-preview2-006497 / 1.0.4

OS version (i.e. win10 v1607 (14393.321)): win10 enterprise

Worked before? If so, with which NuGet version: works with .nuspec files

## Detailed repro steps so we can see the same problem

Right now we have `.nuspec` files that reference a package built from the same solution. We set the version to be an exact version.

Example:

```
Solution.sln
 | - Project.Web.csproj
 \ - Project.Core.csproj
```

Old `Project.Web.nuspec`:
```
<package xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <metadata xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <id>Project.Web</id>
    <version>$version$</version>
    <dependencies>
      <dependency id="Project.Core" version="[$version$]" />
    </dependencies>
  </metadata>
</package>
```

**Is there a way to specify this in csproj with a project included via `ProjectReference`?**

E.g. using `Project.Web.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <DebugType>full</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Project.Core\Project.Core.csproj" />
  </ItemGroup>
</Project>
```

when we `dotnet pack Solution.sln /p:Version=1.2.3`, we want the generated `Project.Web.nuspec` (inside `Project.Web.nupkg`) to have:
```
    <version>1.2.3</version>
    <dependencies>
      <dependency id="Project.Core" version="[1.2.3]" />
    </dependencies>
```

but currently it has:
```
    <version>1.2.3</version>
    <dependencies>
      <dependency id="Project.Core" version="1.2.3" />
    </dependencies>
```

**Comment by Necroskillz** [comment] 2017-07-04 12:50
I have a very dirty workaround to achieve what I want. It involves hooking into msbuild and rewriting `project.assets.json` before `GenerateNuspec` target.

I set `Directory.Build.props` so all projects have this target:
```
  <Target Name="_SetExactVersionsOfProjects" BeforeTargets="GenerateNuspec">
    <Exec Condition="'$(IsPackable)' == 'true'" Command="gulp hack-nuget-exact-versions --silent --project $(MSBuildProjectName)" />
  </Target>
```

I use a command before the nuspec is generated (in my case a gulp task), to change `project.assets.json` with following:
 - find all projects for which i want to set custom version in `libraries` element, and change their `type` from `project` to `package`
 - add all of these projects to `project.frameworks[<all_frameworks>].dependencies` with the desired version (in my case `"[<version>]"` where the `<version>` is parsed from the previous step
 - remove `project.restore.frameworks[<all_frameworks>].projectReferences` not sure if its necessary, but just to avoid any collisions

This is obviously not ideal. Would it be possible to have an options for this in `ProjectReference`? I imagine something like this (it's very flexible, so you can set the version to whatever range/version you need):

```
<ProjectReference Include="..\Project.Core\Project.Core.csproj" PackVersion="[$(Version)]" />
```

**Comment by nkolev92** [comment] 2017-11-10 00:25
//cc
@rohit21agrawal Any ideas?

**Comment by clairernovotny** [comment] 2018-02-05 13:09
Bump?

**Comment by rohit21agrawal** [comment] 2018-02-05 19:08
@emgarten does the P2P ref version take a version range like  ``` [1.2.3] ``` ? What is needed to enable that?

**Comment by clairernovotny** [comment] 2018-02-05 19:11
@rohit21agrawal it shouldn't take a specific version on the ref, but it should have an option like `ExactVersion=true` or something, so that whatever the calculated/generated version that the reference is at time of build is used in the `[]` exact version syntax.

**Comment by emgarten** [comment] 2018-02-05 19:18
We need a generic way to override the version range put into the nuspec for a project reference. This shouldn't be specific to exact versions.

Project to project reference versions are ignored by restore for the most part since we aren't going to fail restore if you link to an exact project path but also specified that you want a different version of it.

**Comment by Necroskillz** [comment] 2018-02-05 20:04
Sounds like my proposal is pretty close to what you want. Would be nice to remove this workaround after half a year 👍 .

**Comment by clairernovotny** [comment] 2018-02-05 20:31
@Necroskillz the issue is that the version needs to come from the target project, not what your project.

I.e., it's not "your" `$(Version)` that's needed, but the referenced project's `$(Version)`. They may not be the same and they may be calculated. One way to get that is by using the `MSBuild` task on the referenced project to invoke the new "GetTargetVersion" stub that was just added in to fix calculated versions. Logic that does the calculations hooks into that and would run in that project's context. You'd then return the version you need.

**Comment by Necroskillz** [comment] 2018-02-05 20:34
Well `$(Version)` can be any MSBuild variable, that you are free to calculate however you want. This was just an example that it would take the version from the command line parameter `/p:Version` that is passed to `pack`.

**Comment by clairernovotny** [comment] 2018-02-05 20:39
@Necroskillz my point here is that the verisons in a project dependency graph may not all align intentionally. That can work, but the underlying mechanism still needs to "query" the target project for its version. The ask here is to make it a fixed version in the nuspec not a `>=`

**Comment by jam40jeff** [comment] 2019-03-26 18:49
Any movement on this?  I have the same need (to use the `=` constraint on project reference dependencies rather than `>=`).

**Comment by jam40jeff** [comment] 2019-03-28 02:06
Is this duplicated by #7213?

**Comment by jwosty** [comment] 2020-01-07 23:12
I am also running into this problem. Can't find a way to remedy it, so for now my library is forced to use a ">=" constraint on itself which is potentially bad.

**Comment by aortiz-msft** [comment] 2020-04-02 22:17
https://github.com/NuGet/Home/issues/7213 closed as duplicate of this issue.

**Comment by JensNordenbro** [comment] 2021-03-18 12:44
Any solution to this problem?
I was expecting there to be "dotnet pack --exact-versions-on-dependencies" or something :)

**Comment by dotMorten** [comment] 2021-06-02 23:13
I have this need too, but for a version range. I'd like to be able to specify a range, like for instance `[1.0.0,1.1.0)`, as listed here: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning

**Comment by kelthar** [comment] 2021-06-04 11:41
Bump?

**Comment by Fabman08** [comment] 2021-06-09 15:07
Any news?

**Comment by atykhyy** [comment] 2022-07-09 11:10
It's easy to hack up a solution. It relies on a couple implementation details of NuGet `PackTask`, but it's much better than nothing.
```xml
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  ...
  <ItemGroup>
    <ProjectReference Include="..\MyOtherProject1\MyOtherProject1.csproj" PackageVersion="[1.1.0, 2.0.0)" />
    <ProjectReference Include="..\MyOtherProject2\MyOtherProject.2csproj" ExactVersion="true" />
  </ItemGroup>
  ...
  <Target Name="UseExplicitPackageVersions" BeforeTargets="GenerateNuspec">
    <ItemGroup>
      <_ProjectReferenceWithExplicitPackageVersion Include="@(ProjectReference->'%(FullPath)')" Condition="'%(ProjectReference.PackageVersion)' != ''" />
      <_ProjectReferenceWithExactPackageVersion Include="@(ProjectReference->'%(FullPath)')" Condition="'%(ProjectReference.ExactVersion)' == 'true'" />
      <_ProjectReferenceWithReassignedVersion Include="@(_ProjectReferencesWithVersions)" Condition="'%(Identity)' != '' And '@(_ProjectReferenceWithExplicitPackageVersion)' == '@(_ProjectReferencesWithVersions)'">
        <ProjectVersion>@(_ProjectReferenceWithExplicitPackageVersion->'%(PackageVersion)')</ProjectVersion>
      </_ProjectReferenceWithReassignedVersion>
      <_ProjectReferenceWithReassignedVersion Include="@(_ProjectReferencesWithVersions)" Condition="'%(Identity)' != '' And '@(_ProjectReferenceWithExactPackageVersion)' == '@(_ProjectReferencesWithVersions)'">
        <ProjectVersion>[@(_ProjectReferencesWithVersions->'%(ProjectVersion)')]</ProjectVersion>
      </_ProjectReferenceWithReassignedVersion>
      <_ProjectReferencesWithVersions Remove="@(_ProjectReferenceWithReassignedVersion)" />
      <_ProjectReferencesWithVersions Include="@(_ProjectReferenceWithReassignedVersion)" />
    </ItemGroup>
  </Target>
  ...
</Project>
```
This useful target can be put into Directory.Build.targets to cover all projects in your solution.

**Comment by nkolev92** [comment] 2022-07-29 00:46
Hey all, 

The ask in this issue is equivalent to https://github.com/NuGet/Home/issues/5556.

**Closed as completed by nkolev92** 2022-07-29 00:46 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Feature, Functionality:Pack
