### ISSUE TITLE
Version Token in NuSpec file not being replaced properly when using version flag with csproj

### ISSUE THREAD

**Issue by ChristopherHaws** [NuGet/Home#1795] opened 2015-12-01 07:17 UTC
When using the `-Version` flag, `nuget pack` fails to set `$version$` properly in all locations other than the `<version>` element when running against a csproj file.

For example, if I had the following nuspec

``` xml
<?xml version="1.0"?>
<package >
    <metadata>
        <id>Test</id>
        <version>$version$</version>
        <title>Test Title</title>
        <authors>Test Author</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>The version is $version$</description>
        <dependencies>
            <dependency id="OtherProjectInSolution" version="$version$" />
        </dependencies>
    </metadata>
</package>
```

If I execute the following command

```
nuget pack ".\Project.csproj" -Version "1.0.0-beta1" -Verbosity detailed
```

The output would be a nuget package called `Test.1.0.0-beta1.nupkg` which is correct, however the nuspec file that gets generated and placed in the package is:

``` xml
<?xml version="1.0"?>
<package >
    <metadata>
        <id>Test</id>
        <version>1.0.0-beta1</version>
        <title>Test Title</title>
        <authors>Test Author</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>The version is 1.0.0.10</description>
        <dependencies>
            <dependency id="OtherProjectInSolution" version="1.0.0.10" />
        </dependencies>
    </metadata>
</package>
```

It looks like the $version$ token is being replaced correctly in the version element, however in all other places it is using the `[assembly: AssemblyVersion("1.0.0.*")]` version.

**Comment by yishaigalatzer** [comment] 2015-12-01 10:56
Can you share what version of nuget.exe are you using?

**Comment by csharpfritz** [comment] 2015-12-01 12:22
According to the docs, the -Version switch overrides the package version
number and is not a replacement for the $version$ token.

http://docs.nuget.org/Consume/Command-Line-Reference#pack-command

http://docs.nuget.org/Create/NuSpec-Reference#replacement-tokens

The $version$ token is always a replacement from the assembly version that
was built.  In specifying the -Version switch, you are overriding the
content of the version element and not providing a new value for the
$version$ token.

Jeff

**Comment by ChristopherHaws** [comment] 2015-12-01 17:38
@yishaigalatzer I am using version 3.3.0.212
@csharpfritz Those two links seem contradictory to me. I am able to get all other tokens to replace properly from other locations in the file. The behaviour seems inconsistent if that is the case though. If you were to tell nuget to pack the nuspec file instead of the csproj file, it does in fact replace the version properly. It is only when running with a csproj that this issue occurs.

**Comment by yishaigalatzer** [comment] 2015-12-01 18:01
I can see how we will be ok with taking a change here. This is not going to fit in one of the immediate releases, so I'm marking us up for grabs and moving to vNext

if someone is interested in taking a stab at a fix, I would wait for the dependency on nuget.core to drop from nuget.exe first to simplify the build process.

**Comment by csharpfritz** [comment] 2015-12-01 18:13
The docs dictate that the -Version switch replaces the contents of the <version></version> element, not the $version$ token.  

The $version$ token is substituted based on the value found in the csproj file you are packing with.

**Comment by yishaigalatzer** [comment] 2015-12-01 18:29
I'm suggesting that we can change the docs, or add a token replacement flag to the command itself.

**Comment by csharpfritz** [comment] 2015-12-01 18:32
I like the idea of providing a token-replacement feature from the command-line

**Comment by yishaigalatzer** [comment] 2015-12-01 19:54
I guess I wasn't the first to think about it. It is already supported :)

see: http://docs.nuget.org/Consume/Command-Line-Reference#pack-command

e.g. nuget pack foo.csproj -Build -Symbols -Properties Configuration=Release

**Comment by ChristopherHaws** [comment] 2015-12-01 21:18
I suppose that I can do the following and use %PackageVersion% in the nuspec file:

```
nuget pack .\Project.csproj -Version "1.0.0-beta1" -Properties "PackageVersion=1.0.0-beta1"
```

It is still weird that the behaviour is inconsistent between csproj and nuspec. I think that if anything, the documentation should be changed so that it is known that $version$ will only be replaced with the passed version parameter when packing a nuspec file.

**Comment by yishaigalatzer** [comment] 2015-12-01 21:30
>  If you were to tell nuget to pack the nuspec file instead of the csproj file, it does in fact replace the version properly. It is only when running with a csproj that this issue occurs.

I think that is because in the csproj case it has a data source for the version, and in the nuspec is doesn't and it then replaces the version tag completely (so if you had a `<version>$version$-beta1</version>` still the whole version tag will get replaced.

I agree that the inconsistency is evil, and it should be fixed. I'm happy you have a workaround for now, and we can re-open this to track fixing the inconsistency.

**Comment by emgarten** [comment] 2017-11-10 00:00
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Closed as completed by emgarten** 2017-11-10 00:00 UTC
Labels: Priority:3, Type:DCR, Resolution:NotRepro, help wanted, Functionality:Pack
