### ISSUE TITLE
NuGet package manager icons look poor on dark theme

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9847] opened 2020-07-27 16:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1123992/nuget-package-manager-icons-look-poor-on-dark-them.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
Icons on the dark theme are pixelated and clipped. They should use the VS image service. See attached screenshot.

---
#### Feedback Bot on 7/23/2020, 08:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by zkat** [comment] 2020-08-06 17:56
@chgill-MSFT could you take a look at the screenshot in the dev community ticket and come up with a plan for us to improve the situation? They do look kinda gnarly :P

**Comment by donnie-msft** [comment] 2020-08-31 18:44
Dupe of https://github.com/NuGet/Home/issues/5937

**Closed as completed by donnie-msft** 2020-08-31 18:44 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Priority:2, Type:Bug, Functionality:VisualStudioUI
