### ISSUE TITLE
Null ref exception when calling nuget.exe update with packages not present under Packages folder

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1495] opened 2015-09-30 23:17 UTC
c:\school>nuget.exe update WebApplication4\WebApplication4\WebApplication4.csproj
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86
)\MSBuild\14.0\bin'.
Attempting to gather dependencies information for multiple packages with respect
 to project 'c:\school\WebApplication4\WebApplication4\WebApplication4.csproj',
targeting '.NETFramework,Version=v4.0'
Object reference not set to an instance of an object.

Packages are not present under "Packages" folder, which is very common for TFS scenarios. 

In this case, we may need to perform a package restore first.

**Comment by deepakaravindr** [comment] 2015-10-01 01:26
Couple of quick points on this issue
- Same issue exists with nuget.exe 2.8.6, in that, the old nuget.exe does not do anything
- In addition, if the packages folder is not present, there is an error message, both on 2.8.6 and 3.2.*. So, default TFS scenario should not be a problem per se. However, there is a problem when there is a packages folder, yes.

**Comment by deepakaravindr** [comment] 2015-10-01 02:12
@yishaigalatzer  @johnataylor 

This problem does not happen on the UI, because, UI always restores packages before performing any action such as Install, Uninstall or Restore.

The null ref comes from https://github.com/NuGet/NuGet.PackageManagement/blob/dev/src/PackageManagement/NuGetPackageManager.cs#L577. I believe that it is not a simple fix to simply handle when packageInfo is null, because of comments at https://github.com/NuGet/NuGet.PackageManagement/blob/dev/src/PackageManagement/NuGetPackageManager.cs#L567. That code fragment handles multiple other scenarios and any change must test those scenarios as well.

Assigning to @johnataylor

**Comment by johnataylor** [comment] 2015-10-08 22:58
The command line should be consistent with the other scenarios (UI and PowerShell) and first restore the packages. When that happens first this shouldn't happen. Regarding the scenarios referred to in the comment in the Update package code (see references in previous comments). Basically if the package has gone from the feed or the sources have been reconfigured then the restore would fail which might be a more informative error.

**Comment by yishaigalatzer** [comment] 2015-10-31 02:00
@johnataylor can you get back to looking at this for 3.3?

**Comment by johnataylor** [comment] 2015-11-23 22:24
This looks good to me. My test scenario is: a simple Console application with a single old package and a missing Packages folder.

With 2.8.6 I get:

Unable to locate the packages folder. Try specifying it using the repositoryPath switch.

With 3.1.0 and 3.2.0 I get:

MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
The project file could not be loaded. Access to the path 'C:\Users\johtaylo\Documents\Visual Studio 2015\Projects\ConsoleApplication30\ConsoleApplication30' is denied.  C:\Users\johtaylo\Documents\Visual Studio 2015\Projects\ConsoleApplication30\ConsoleApplication30

Which is, incidentally a regression in the error message. But note that I don't see the null exception.

And then with the latest 3.3.0 bits (build 194) I see the error message:

MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Unable to locate the packages folder. Verify all the packages are restored before running 'nuget.exe update'.

And this seems like a good and helpful message.

**Comment by johnataylor** [comment] 2015-11-23 22:26
Stepping through this code, the exception is thrown from here:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/UpdateCommand.cs#L351

**Closed as completed by johnataylor** 2015-11-23 22:26 UTC
Labels: Priority:2, Type:Bug

**Comment by feiling** [comment] 2015-11-26 00:35
Verified with nuget.exe 3.3.0.208 that the correct error message is shown.
