### ISSUE TITLE
UninstallPackageFromUI is flaky

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#10412] opened 2020-12-23 18:51 UTC
NuGetUITestCase.UninstallPackageFromUI is extremely flaky. 

It fails because of loading the PM UI control. Instictively this sounds like something that *should not* be specific to this test, but it's always the same one, despite the fact that many tests do the same thing.

**Comment by donnie-msft** [comment] 2020-12-23 19:29
> System.TimeoutException : The package manager control did not load within 00:01:00
> 
> **Stack trace**
>    at NuGet.PackageManagement.UI.TestContract.NuGetApexUITestService.GetApexTestUIProject(String project, TimeSpan timeout, TimeSpan interval) in E:\A\_work\1\s\test\NuGet.Tests.Apex\NuGet.PackageManagement.UI.TestContract\NuGetApexUITestService.cs:line 45
>    at NuGet.Tests.Apex.NuGetApexTestService.GetUIWindowfromProject(ProjectTestExtension project) in E:\A\_work\1\s\test\NuGet.Tests.Apex\NuGet.Tests.Apex\Apex\NuGetApexTestService.cs:line 204
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

**Comment by sbanni** [comment] 2021-01-20 19:59
@nkolev92  I am attempting to address this with [this PR](https://github.com/NuGet/NuGet.Client/pull/3791)
It looked to me that the DTE command was not available when we tried to call it, so I am adding a loop to wait for it to be available first, in my local testing this fixed the flakiness and I no longer get the stack that Donnie linked above.

**Comment by nkolev92** [comment] 2021-01-20 22:32
@sbanni That's awesome! Left a comment on the PR.

**Comment by sbanni** [comment] 2021-01-22 17:48
This is caused by a [race condition](https://github.com/NuGet/NuGet.Client/blob/85f17f0525048c36cdd080324019729884b1d998/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/IDE/VSSolutionManager.cs#L810), we are checking if the cache is initialized but it is in the process of being initialized so we fail.  I have a proposed fix for this in the PR I linked above.

**Closed as completed** 2021-01-23 00:22 UTC
Labels: Priority:2, Type:Test
