### ISSUE TITLE
MSBuild targets are not applied to generated project.assets.json for project references when packaging from Visual Studio 2017

### ISSUE THREAD

**Issue by soen** [NuGet/Home#6037] opened 2017-10-16 13:55 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI

NuGet version (x.x.x.xxx):
4.3.0.4406
4.4.0

dotnet.exe --version (if appropriate):
2.0.0
2.0.2

VS version (if appropriate):
Visual Studio 2017 15.3.5
Visual Studio 2017 15.4.0

OS version (i.e. win10 v1607 (14393.321)):
win10 (10.0.15063 Build 15063)

Worked before? If so, with which NuGet version:
N/A

## Detailed repro steps so we can see the same problem

1. Open the sample project [TestSetVersion.zip](https://github.com/NuGet/Home/files/1387252/TestSetVersion.zip)

2. Pack the project named ``ProjectC`` from VS, by right-clicking on the project in the Solution Explorer and selecting *Pack*

3. Once packed, open the file ``TestSetVersion\ProjectC\bin\Debug\ProjectC.1.2.3-r12345.nupkg`` (i.e. using NuGet Package Explorer)

4. Verify that the package contains two dependencies with the following versions; ``ProjectA >= 1.2.3.r12345`` and ``ProjectB >= 1.2.3.r12345``

5. Remove the ``\bin`` and ``\obj`` output folders from ``TestSetVersion\ProjectC\``

6. Open the file ``TestSetVersion\Directory.Build.props``, and comment out the target named ``BeforeGenerateNuspec``

7. Pack the project named ``ProjectC`` from VS

8. Once packed, open the file ``TestSetVersion\ProjectC\bin\Debug\ProjectC.1.2.3-r12345.nupkg`` (i.e. using NuGet Package Explorer)

9. Verify that the package contains two dependencies with the following (incorrect) versions; ``ProjectA >= 1.0.0`` and ``ProjectB >= 1.0.0``

Based on the above it seems that when a project (``ProjectC``) is referencing other projects (``ProjectA`` and ``ProjectB``), in the same solution, the versions of the referenced projects will not be set to the version provided by the given ``SetVersion`` target. This behaviour only seem to occur when packaging the project from inside VS, as calling either MSBuild (``msbuild \t:restore \t:pack``) or the .NET Core CLI (``dotnet pack``) directly will produce a package for ``ProjectC`` that contains dependencies to ``ProjectA`` and ``ProjectB`` with the version set via the ``SetVersion`` target.

It is expected that the file ``project.assets.json`` is generated with the correct version for the project it belongs to, and also with correct versions for ``PackageReferences``.

Do note that the target ``BeforeGenerateNuspec`` and the inline task ``FixProjectAssetsJson`` is indeed a workaround, since it is not fully clear how to use MSBuild targets, since the Restore Target from NuGet doesn’t seem to be executed from VS, and there seems to be no clear public targets available for before or after generating the ``project.assets.json`` file.

**Comment by jainaashish** [comment] 2017-10-21 05:18
even `project.assets.json` also has 1.0.0 version for both packageA and packageB and if i'm not wrong `pack` is picking these versions for dependencies. I think `SetVersion` is not being called with target.

@emgarten do you have any comment here?

**Comment by emgarten** [comment] 2017-11-09 20:32
Duplicate of https://github.com/NuGet/Home/issues/4790

**Closed as completed by emgarten** 2017-11-09 20:32 UTC
Labels: Resolution:Duplicate, Triage:Investigate, Functionality:Pack
