### ISSUE TITLE
Unhandled exceptions in Restore should generate assets file to capture error messages

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10424] opened 2021-01-04 18:11 UTC
## Details about Problem

NuGet product used VS 16.8

When an unhandled exception occurs in Restore, for SDK style projects, we have no way of reporting that error in the Error List since there's no assets file. This leads to other arbitrary (and wrong) messages being shown, such as an unknown TFM. 

The scenario I propose we handle for now is a non-existent package source (FatalProtocolException).

## Detailed repro steps so we can see the same problem

1. Create a `config` file pointing to a non-existent package source
2. Open a new SDK style project (without an existing assets file) (I used net5.0-windows)
3. Build, and some errors will occur.
`NETSDK1005    Assets file <proj>\obj\project.assets.json' doesn't have a target for 'net5.0-windows'. Ensure that restore has run and that you have included 'net5.0-windows' in the TargetFrameworks for your project.  `

or perhaps

`NETSDK1004	Assets file '<proj>\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	
<proj>	C:\Program Files\dotnet\sdk\5.0.200-preview.20614.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	195`

## Other suggested things
Related: https://github.com/NuGet/Home/issues/7012

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by aortiz-msft** [comment] 2021-01-21 18:40
This seems like a duplicate of https://github.com/NuGet/Home/issues/7245

**Comment by donnie-msft** [comment] 2021-01-21 19:50
@aortiz-msft & @nkolev92  I don't see any evidence that this is a dupe. The linked issue is showing Project System errors that aren't in the Error list. This issue's scenario is that the project.assets.json file doesn't exist, therefore there's no way to propagate errors.

**Comment by nkolev92** [comment] 2021-01-21 20:33
> The linked issue is showing Project System errors that aren't in the Error list

NuGet writes the assets file with the errors, the project system uses the SDK tasks to read the assets and generate log items. Said items are used to populate the error list + solution explorer.

**Closed as completed by nkolev92** 2021-01-21 20:33 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug, Area:ErrorHandling, Functionality:Restore
