### ISSUE TITLE
Dependency packages missing from the template was added to packages to be installed list

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#817] opened 2015-06-18 21:03 UTC
Repro steps:
1. create a new Razor 3 website
2. start package manager dialog, go to all tab
3. select bootstrap

Expected: When review changes pops up, only bootstrap is shown.

Actual: Antlr and Newtonsoft.json is also listed.

Turns out these two packages are dependencies of packages listed on the project template.

**Comment by danliu** [comment] 2015-06-18 21:04
![3](https://cloud.githubusercontent.com/assets/1087852/8242238/e9aca154-15c2-11e5-81af-98d05fe73962.PNG)

**Comment by emgarten** [comment] 2015-06-18 21:30
NuGet is correctly resolving the full closure of packages here, the issue is that the template for this project type does not install the dependencies for webgrease (newtonsoft.json and antlr).

It looks like what may have happened here is that the template was upgraded from WebGrease 1.3.0 which has 0 dependencies, to WebGrease 1.5.2 without adding in the new dependencies to the template.

https://www.nuget.org/packages/WebGrease/1.5.2
https://www.nuget.org/packages/WebGrease/1.3.0

By default packages in WizardData do not install dependencies unless the include dependencies flag is set.

The best fix for this is to add newtonsoft.json and antlr to the list of packages to install in the template.

From RazorStarterSiteProjectTemplate.cshtml.vstemplate:
```
<WizardData>
    <packages repository="registry" keyName="AspNetWebFrameworksAndTools5" isPreunzipped="true">
      <package id="jQuery" version="1.10.2" skipAssemblyReferences="true" />
      <package id="jQuery.Validation" version="1.11.1" skipAssemblyReferences="true" />
      <package id="jQuery.UI.Combined" version="1.10.3" skipAssemblyReferences="true" />
      <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" skipAssemblyReferences="true" />
      <package id="Modernizr" version="2.6.2" skipAssemblyReferences="true" />
      <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" skipAssemblyReferences="true" />
      <package id="Microsoft.AspNet.Razor" version="3.2.3" skipAssemblyReferences="true" />
      <package id="Microsoft.AspNet.WebPages" version="3.2.3" skipAssemblyReferences="true" />
      <package id="Microsoft.SqlServer.Compact" version="4.0.8876.1" skipAssemblyReferences="true" />
      <package id="Microsoft.AspNet.WebPages.Data" version="3.2.3" skipAssemblyReferences="true" />
      <package id="Microsoft.AspNet.WebPages.WebData" version="3.2.3" skipAssemblyReferences="true" />
      <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" skipAssemblyReferences="true" />
      <package id="WebGrease" version="1.5.2" skipAssemblyReferences="true" />
      <package id="knockoutjs" version="2.3.0" skipAssemblyReferences="true" />
      <package id="DotNetOpenAuth.AspNet" version="4.1.4.12333" skipAssemblyReferences="true" />
      <package id="DotNetOpenAuth.Core" version="4.1.4.12333" skipAssemblyReferences="true" />
      <package id="DotNetOpenAuth.OAuth.Consumer" version="4.1.4.12333" skipAssemblyReferences="true" />
      <package id="DotNetOpenAuth.OAuth.Core" version="4.1.4.12333" skipAssemblyReferences="true" />
      <package id="DotNetOpenAuth.OpenId.Core" version="4.1.4.12333" skipAssemblyReferences="true" />
      <package id="DotNetOpenAuth.OpenId.RelyingParty" version="4.1.4.12333" skipAssemblyReferences="true" />
      <package id="Microsoft.AspNet.WebPages.OAuth" version="3.2.3" skipAssemblyReferences="true" />
    </packages>
  </WizardData>
```

**Closed** 2015-06-24 01:33 UTC
Labels: ClosedAs:External
