### ISSUE TITLE
Package restore in VS reports "Failed to resolve all project references"..., builds sometimes fail

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1860] opened 2015-12-19 01:00 UTC
VS2015 Update 1 (with NuGet 3.3 client)

Although all projects are loaded in this solution, I'm getting errors about being unable to resolve project references. This works fine from the command line with nuget.exe 3.3.

**Repro steps**

```
git clone https://github.com/aarnott/PInvoke
cd PInvoke
src\PInvoke.sln
```

Right-click on the BCrypt.Tests project and click Rebuild. 

The build output window shows many package restore failures:

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
Failed to resolve all project references for 'AdvApi32'. The package restore result for 'AdvApi32' may be incomplete.
Failed to resolve all project references for 'Kernel32'. The package restore result for 'AdvApi32' may be incomplete.
Failed to resolve all project references for 'Psapi'. The package restore result for 'Psapi' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'Psapi' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'Psapi.Tests' may be incomplete.
Failed to resolve all project references for 'Psapi'. The package restore result for 'Psapi.Tests' may be incomplete.
Failed to resolve all project references for 'DbgHelp'. The package restore result for 'DbgHelp.Tests' may be incomplete.
Failed to resolve all project references for 'DbgHelp'. The package restore result for 'DbgHelp' may be incomplete.
Failed to resolve all project references for 'DbgHelp'. The package restore result for 'ImageHlp.Tests' may be incomplete.
Failed to resolve all project references for 'ImageHlp'. The package restore result for 'ImageHlp.Tests' may be incomplete.
Failed to resolve all project references for 'ImageHlp'. The package restore result for 'ImageHlp' may be incomplete.
Failed to resolve all project references for 'DbgHelp'. The package restore result for 'ImageHlp' may be incomplete.
Failed to resolve all project references for 'BCrypt'. The package restore result for 'NCrypt.Tests' may be incomplete.
Failed to resolve all project references for 'NCrypt'. The package restore result for 'NCrypt.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32'. The package restore result for 'NCrypt.Tests' may be incomplete.
Failed to resolve all project references for 'NCrypt'. The package restore result for 'NCrypt' may be incomplete.
Failed to resolve all project references for 'BCrypt'. The package restore result for 'NCrypt' may be incomplete.
Failed to resolve all project references for 'Kernel32'. The package restore result for 'NCrypt' may be incomplete.
Failed to resolve all project references for 'AdvApi32.Desktop'. The package restore result for 'AdvApi32.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'AdvApi32.Tests' may be incomplete.
Failed to resolve all project references for 'AdvApi32.Desktop'. The package restore result for 'AdvApi32.Desktop' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'AdvApi32.Desktop' may be incomplete.
Failed to resolve all project references for 'BCrypt.Tests'. The package restore result for 'BCrypt.Tests' may be incomplete.
Failed to resolve all project references for 'BCrypt'. The package restore result for 'BCrypt.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'BCrypt.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32'. The package restore result for 'BCrypt.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32.Tests.Portable'. The package restore result for 'Kernel32.Tests.Portable' may be incomplete.
Failed to resolve all project references for 'Windows.Core.Tests'. The package restore result for 'Windows.Core.Tests' may be incomplete.
Failed to resolve all project references for 'SetupApi.Desktop'. The package restore result for 'SetupApi.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'SetupApi.Tests' may be incomplete.
Failed to resolve all project references for 'SetupApi.Desktop'. The package restore result for 'SetupApi.Desktop' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'SetupApi.Desktop' may be incomplete.
Failed to resolve all project references for 'Hid.Desktop'. The package restore result for 'Hid.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'Hid.Tests' may be incomplete.
Failed to resolve all project references for 'Hid.Desktop'. The package restore result for 'Hid.Desktop' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'Hid.Desktop' may be incomplete.
Failed to resolve all project references for 'Hid'. The package restore result for 'Hid' may be incomplete.
Failed to resolve all project references for 'Kernel32'. The package restore result for 'Hid' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'Kernel32.Desktop' may be incomplete.
Failed to resolve all project references for 'Kernel32.Tests'. The package restore result for 'Kernel32.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32.Desktop'. The package restore result for 'Kernel32.Tests' may be incomplete.
Failed to resolve all project references for 'Kernel32'. The package restore result for 'Kernel32' may be incomplete.
Failed to resolve all project references for 'Gdi32.Desktop'. The package restore result for 'Gdi32.Desktop' may be incomplete.
Failed to resolve all project references for 'User32.Desktop'. The package restore result for 'User32.Desktop' may be incomplete.
Failed to resolve all project references for 'BCrypt'. The package restore result for 'BCrypt' may be incomplete.
Failed to resolve all project references for 'Kernel32'. The package restore result for 'BCrypt' may be incomplete.
1>------ Rebuild All started: Project: Windows.Core, Configuration: Debug Any CPU ------
1>  Windows.Core -> C:\git\PInvoke\bin\Debug\Profile92\PInvoke.Windows.Core.dll
2>------ Rebuild All started: Project: Kernel32, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: Kernel32.Desktop, Configuration: Debug Any CPU ------
2>  Kernel32 -> C:\git\PInvoke\bin\Debug\Profile92\PInvoke.Kernel32.dll
4>------ Rebuild All started: Project: BCrypt, Configuration: Debug Any CPU ------
4>  BCrypt -> C:\git\PInvoke\bin\Debug\Profile92\PInvoke.BCrypt.dll
3>  Kernel32.Desktop -> C:\git\PInvoke\bin\Debug\Desktop\PInvoke.Kernel32.dll
5>------ Rebuild All started: Project: BCrypt.Tests, Configuration: Debug Any CPU ------
5>  BCrypt.Tests -> C:\git\PInvoke\bin\Debug\Tests\BCrypt.Tests\PInvoke.BCrypt.Tests.dll
========== Rebuild All: 5 succeeded, 0 failed, 0 skipped ==========
```

**Comment by yishaigalatzer** [comment] 2015-12-19 04:30
Do you have the same issue, if you build at the solution level?

**Comment by AArnott** [comment] 2015-12-19 05:10
Yes, it fails rebuilding the solution or rebuilding a project. Incremental build doesn't usually show the errors I guess because package restore doesn't usually happen then. But incremental build will still fail when a prior nuget restore failure led to incompletely written project.lock.json or msbuild import files.

**Comment by yishaigalatzer** [comment] 2015-12-22 21:47
@emgarten can you please investigate?

**Comment by emgarten** [comment] 2016-03-25 21:25
These warnings are shown when the `Reference3.Resolved` property is false. NuGet is unable to walk these references which could be a project that is missing from disk, and potentially the project could contain packages which will not flow up to the parent projects.

@AArnott I am going to close this bug, but please let me know if you have any suggestions on how NuGet could improve finding project references.

**Comment by AArnott** [comment] 2016-03-26 04:37
@emgarten Thanks for investigating.
There are no projects missing from disk, as you should be able to verify if you'd like.
I do see warning indicators in Solution Explorer on some references which might coincide with your `Reference3.Resolved` issue, so I suspect a project system bug is causing this to report a problem where none exists. @jasonmalinowski might have an idea.

What if you ignored this property for project references and queried for the project path anyway, and then searched the solution for that path (which you'd find) and continue on?

**Comment by yishaigalatzer** [comment] 2016-03-26 04:40
Now we are diverging from using dte to figure out references and starting to mix in msbuild direct calls. I'm not sure what other side effects that might bring, I would investigate the project system issue first and only then look for further steps down this path

**Comment by jasonmalinowski** [comment] 2016-03-26 17:53
@AArnott Do you have any of the design time build logs handy? If you delete your .vs folder, set TRACEDESIGNTIME=true as an environment variable, and then open your solution it'll dump all the design time build logs under %TEMP% with "designtime" in the name.  I'm happy to take a look at those.

**Comment by rrelyea** [comment] 2016-05-11 16:39
This looks like discussion is still going on.
Set as build task bug, no milestone, assigned to @jasonmalinowski .
Please fix, if I made a mistake there.
If we are going to close it, let's give the reason (by design, etc...)

**Comment by AArnott** [comment] 2016-05-11 17:33
@jasonmalinowski I have uploaded the design-time logs [here](https://onedrive.live.com/redir?resid=63D0C265F96E43D!2694858&authkey=!AFYmdmqOrRJTBSE&ithint=file%2czip).

**Comment by nkolev92** [comment] 2018-02-22 20:25
It's been almost 2 years and we haven't had any progress on this issue. 

As a lot of things have changed since then, and we're not planning on shipping updates to VS 2015, I'll close this. 

Please create another issue if this still a problem.

**Closed as completed by nkolev92** 2018-02-22 20:25 UTC
Labels: Type:Bug

**Comment by chipplyman** [comment] 2021-08-23 18:34
Looks like this issue is currently being tracked as https://github.com/NuGet/Home/issues/7297, with some additional nuance.
