### ISSUE TITLE
Fakes assembly is not generating with PackageReference

### ISSUE THREAD

**Issue by SowmyaDantuluri** [NuGet/Home#9305] opened 2020-03-13 05:13 UTC
I have created one nuget package. Name of that nuget package is MyFirstOne. Inside that package one dll is there named abc.dll

I have created 2 WPF projects. One with packages.config(WPFPackageConfigProject) and the other one with PackageReference((WPFPackageReferenceProject).

I have added MyFirstOne package to both projects. I tried to create fakes assembly for that in WPFPackageConfigProject. Fakes assembly created successfully. I tried to create fakes assembly in WPFPackageReferenceProject. Fakes assembly didn't created. It failed stating that Fakes doesnot support this assembly.

Now I renamed my nuget package to abc. Which means both package and dll names are same. Now I referred this in both projects. Now fakes assembly is created fine in both projects.

Is there any issue with PackageReference to create fakes assembly? When my package name and dll name are different it is failing to create fakes assembly with package reference.
![FakesIssue](https://user-images.githubusercontent.com/49900591/76591825-759b8100-6517-11ea-8f53-e2f5f4d7f8ee.PNG)

**Comment by kartheekp-ms** [comment] 2020-03-20 15:24
Found another [thread](https://social.msdn.microsoft.com/Forums/en-US/8a01867d-4cf2-4a7d-9cfb-c2500668d2c4/fakes-assembly-is-not-generating-with-packagereference) that refers the same issue.

**Comment by kartheekp-ms** [comment] 2020-03-20 16:38
As per [NuGet doc](https://docs.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects#packagesconfig-support), Projects using `packages.config` to manage NuGet packages normally add references to all assemblies in the `lib\<tfm>\ directory`. That is the reason why `Fakes` assembly are generated in your `WPF-PackageConfig-Project`. 
The `project.assets.json file under obj\ folder` maintains a project's dependency graph when using the `PackageReference` management format. 

This behavior is by design. If I am missing something here then please feel free to comment on this issue with your specific use case so that we can discuss next steps.

**Comment by nkolev92** [comment] 2020-04-17 01:35
Closing per @kartheekp-ms's comment.

**Closed as completed by nkolev92** 2020-04-17 01:35 UTC
Labels: Resolution:Question, Resolution:ByDesign
