### ISSUE TITLE
Cannot update package X when package Y is installed as pre-release package

### ISSUE THREAD

**Issue by mbp** [NuGet/Home#1571] opened 2015-10-14 07:21 UTC
With Visual Studio 2015 / NuGet Package Manager 3.2.60914.10516, I get problems when my solution contains pre-release packages. It is not possible to update a package without getting an error. The same works in Visual Studio 2013 / NuGet Package Manager 2.8.60318.734.

Steps to reproduce:
1. `Install-Package FluentAssertions -Version 3.5.0` 

Output:

```
Attempting to gather dependencies information for package 'FluentAssertions.3.5.0' with respect to project 'MvcExtensionsTest', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'FluentAssertions.3.5.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FluentAssertions.3.5.0'
Resolved actions to install package 'FluentAssertions.3.5.0'
Adding package 'FluentAssertions.3.5.0' to folder 'd:\sandbox\MvcExtensionsTest\packages'
Added package 'FluentAssertions.3.5.0' to folder 'd:\sandbox\MvcExtensionsTest\packages'
Added package 'FluentAssertions.3.5.0' to 'packages.config'
Successfully installed 'FluentAssertions 3.5.0' to MvcExtensionsTest
```
1. `Install-Package MvcExtensions -Pre`

Output:

```
Attempting to gather dependencies information for package 'MvcExtensions.3.0.0-alpha1034' with respect to project 'MvcExtensionsTest', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'MvcExtensions.3.0.0-alpha1034' with DependencyBehavior 'Lowest'
Resolving actions to install package 'MvcExtensions.3.0.0-alpha1034'
Resolved actions to install package 'MvcExtensions.3.0.0-alpha1034'
Adding package 'MvcExtensions.FluentMetadata.3.0.0-alpha1010' to folder 'd:\sandbox\MvcExtensionsTest\packages'
Added package 'MvcExtensions.FluentMetadata.3.0.0-alpha1010' to folder 'd:\sandbox\MvcExtensionsTest\packages'
Added package 'MvcExtensions.FluentMetadata.3.0.0-alpha1010' to 'packages.config'
Successfully installed 'MvcExtensions.FluentMetadata 3.0.0-alpha1010' to MvcExtensionsTest
Adding package 'MvcExtensions.3.0.0-alpha1034' to folder 'd:\sandbox\MvcExtensionsTest\packages'
Added package 'MvcExtensions.3.0.0-alpha1034' to folder 'd:\sandbox\MvcExtensionsTest\packages'
Added package 'MvcExtensions.3.0.0-alpha1034' to 'packages.config'
Successfully installed 'MvcExtensions 3.0.0-alpha1034' to MvcExtensionsTest
```
1. `Update-Package FluentAssertions`

Output:

```
Attempting to gather dependencies information for multiple packages with respect to project 'MvcExtensionsTest', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for multiple packages
Update-Package : Unable to find package 'MvcExtensions'. Existing packages must be restored before performing an install or update.
At line:1 char:1
+ Update-Package FluentAssertions
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

**Comment by yishaigalatzer** [comment] 2015-10-14 20:53
Thanks for reporting it, this looks like a duplicate of https://github.com/NuGet/Home/issues/1370

We are working on fixing it for 3.3

@johnataylor - Please validate my assumption and re-open if this is similar but not identical

**Closed as completed by yishaigalatzer** 2015-10-14 20:53 UTC
