### ISSUE TITLE
Need better error message when the feed is not available.

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1268] opened 2015-08-26 22:16 UTC
Repro steps:
- run `nuget list -source abc` (assuming there's no source called abc). 

The output is

```
WARNING: This version of nuget.exe does not support listing packages from package source 'abc'.
No packages found.
```

We get the same message if the index.json on the server does not contain the ListCommandResource. I think we should have different messages for these two scenarios.

BTW, using nuget.exe 2.8, the error message is `Invalid URI: The format of the URI could not be determined.`

**Comment by deepakaravindr** [comment] 2015-08-27 18:50
@yishaigalatzer, This is a commandline bug and should be in 3.2-commandline. Once you agree, I will mark this as a duplicate to https://github.com/NuGet/Home/issues/1238

**Comment by yishaigalatzer** [comment] 2015-08-27 19:01
Sure

**Comment by deepakaravindr** [comment] 2015-08-27 19:23
This is a duplicate of https://github.com/NuGet/Home/issues/1238

**Closed as completed by deepakaravindr** 2015-08-27 19:23 UTC
Labels: Resolution:Duplicate, Priority:2
