### ISSUE TITLE
NuGet.exe complains about "repository" element!

### ISSUE THREAD

**Issue by pedrolamas** [NuGet/Home#5099] opened 2017-04-21 14:01 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe

NuGet version (x.x.x.xxx):
3.5.0.1996

OS version (i.e. win10 v1607 (14393.321)):
win10 v1703 (15063.138)

## Detailed repro steps so we can see the same problem

1. Create a new nuspec file with all the defaults and inside it add a `repository` element inside the `metadata` element. Example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <repository type="git" url="https://github.com/user/repo" />
  </metadata>
</package>
```

2. Run `nuget.exe pack`; the following error will be shown:

> The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has invalid child element 'repository' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. List of possible elements expected: 'dependencies, frameworkAssemblies, tags, summary, copyright, packageTypes, contentFiles, developmentDependency, references, iconUrl, releaseNotes, serviceable, title, language' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. This validation error occurred in a 'repository' element.

3. The tag is present at the [nuspec.xsd](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd), so this error makes no sense at all...

**Comment by derigel23** [comment] 2017-06-23 14:47
@rohit21agrawal any comments? you've added that tag in commit #9b899f5542d51507520eb358bdc1e5c325b57576 without bumping nuspec scheme version. Of course previous versions of clients are not compatible with it.
Now, I can't install this https://www.nuget.org/packages/protobuf-net/2.2.1 package

**Comment by mishra14** [comment] 2017-10-17 23:41
@rohit21agrawal  please investigate.

**Comment by nkolev92** [comment] 2019-01-03 19:33
@derigel23 

Can you try using a 4.x version  of nuget.exe.

The repository element was added in 4.0, so you can't pack it with an older nuget.exe. 

Furthermore, extra metadata should not block you from installing the package. 
The nuspec schema is not strictly validated on consumption of these packages.

**Comment by derigel23** [comment] 2019-01-03 21:29
Ehh, 1.5 years later? ;)
No, I can't use 4.x. Environment restrictions.
I've provided exact version of package which is not being able to be installed by older NuGet, so extra metadata is blocking installation process.

**Comment by nkolev92** [comment] 2019-01-03 23:04
> No, I can't use 4.x. Environment restrictions.
Unfortunately there's nothing that can be done here then. 

> I've provided exact version of package which is not being able to be installed by older NuGet, so extra metadata is blocking installation process.

I have not been able to reproduce that. 

> nuget.exe install protobuf-net -Version 2.2.1 

worked fine on my end. 

Same with installing it from VS 2015.

How did you try installing it that failed?

When installing packages, nuget does not strictly validate the nuspec.

**Comment by derigel23** [comment] 2019-01-09 13:55
@nkolev92 Sorry, I can't reproduce the problem either. Fell free to close the issue.

**Comment by nkolev92** [comment] 2019-01-09 19:08
@derigel23  Thanks for following up.

**Closed as completed by nkolev92** 2019-01-09 19:08 UTC
Labels: Functionality:Pack
