### ISSUE TITLE
[Test Failure]Confusing warning and error occur when building the UWP project after installing the package “Blend.Interactivity.Wpf”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8832] opened 2019-11-18 10:45 UTC
## Details about Problem
NuGet version: NuGet Client Release-5.4.x\5.4.0.6314
VS Version: D16.4\29516.08
OS: Windows-10-Enterprise-19H1-04-05-2019 ENU
## Detailed repro steps 
1. Create a C# Blank App (Universal Windows) template via VS.
2. Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Search the package “Blend.Interactivity.Wpf” in Browse tab and install it.
4. Warning NU1701 show in the Error List dialog and build the solution.
## Expected
Warning NU1701 will still show in the Error List dialog when building/rebuilding the solution. (Same with the result of installing the same package into C# .Net Core Console App as below screenshot)
![CorrectWarning](https://user-images.githubusercontent.com/20632625/69046216-6c038000-0a33-11ea-9e86-f167a938d1c1.png)

## Actual
Confusing warning PRI257 and file not found error show in the Error List dialog when building/rebuilding the solution as below screenshot.
![ConfusingWarning](https://user-images.githubusercontent.com/20632625/69046223-6efe7080-0a33-11ea-884c-829d0f2aab34.png)

## Note
1.It  repro on the C# UWP template in Blend for VS and not repro on .NET Core templates.
2.It is not a regression bug since it repro on 16.1 GA (D16.1\28916.193) with implicit NuGet 5.1.0.6013.

**Comment by v-luzh** [comment] 2019-11-22 09:19
Not repro on D16.5\29521.150 with implicit NuGet 5.5.0.6293.

**Comment by v-luzh** [comment] 2019-12-20 07:14
@zivkan, seems this bug is fixed on Master\29619.96+NuGet Client Dev\5.5.0.6353. NU1202 can stop the incompatible package installing as below.
![image](https://user-images.githubusercontent.com/20632625/71236985-4bcd2680-233b-11ea-982e-4cf8954096db.png)

**Comment by v-luzh** [comment] 2020-02-03 09:27
Hi @zivkan , it repro on Master\29802.14+NuGet Dev\5.5.0.6411. Please help to reactivate this issue, thanks.

**Comment by v-luzh** [comment] 2020-02-04 10:45
Error messages are a little different from previous ones. PRI257 is gone bug below errors are still there on Master\29803.141 + NuGet Client Dev\5.5.0.6412.
![image](https://user-images.githubusercontent.com/20632625/73737648-fc717700-477d-11ea-856a-6b8f50d660b2.png)

**Comment by v-luzh** [comment] 2020-02-14 11:55
Same error as the original bug on D16.5\29813.226 as below.
![image](https://user-images.githubusercontent.com/20632625/74529953-e45edc00-4f63-11ea-9e4d-d6948fcf82d3.png)

**Comment by nkolev92** [comment] 2020-04-17 01:54
Hey @v-luzh Any particular reason why you are using this package for testing? 

The package only supports .NET Framework and is behaving differently for UAP projects, for .NET Core projects by design, because they both have a different fallback for .NET Framework based assemblies. 

To me this looks like not a bug, but I just wanted to make sure why this particular package is interesting.

**Comment by v-luzh** [comment] 2020-04-20 06:24
Hey @nkolev92 This issue is found in an adhoc testing. We just want to test if our error message can response correctly. Yes, the package "Blend.Interactivity.Wpf" is not compatible with UWP/.NET Core projects. The point is the error message below is confusing.
![image](https://user-images.githubusercontent.com/20632625/79719554-688d6100-8311-11ea-9e3c-f86704484f58.png)

And the below error message is expected. Fortunatly, this is what we see in VS Master+NuGet Dev testing in most cases. But we can still found the wrong message on particular build in my above comments. That's weird.
![image](https://user-images.githubusercontent.com/20632625/79719497-4a276580-8311-11ea-97c6-10ed85cbf431.png)

**Comment by nkolev92** [comment] 2020-04-20 18:25
* The warning message is something that we don't control. (PRI257)
* The installation error from a NuGet perspective is good enough. (NU1202)
* The could not copy the file is a UWP error, and if anything it should be a UWP bug. 

So based on that I'm gonna close this issue, because there's nothing actionable from NuGet side. 

Thanks for the detailed repro though!

**Closed as completed by nkolev92** 2020-04-20 18:25 UTC
Labels: Type:Bug, Functionality:Restore, Resolution:NotABug

**Comment by v-luzh** [comment] 2020-04-30 08:31
@nkolev92, We found that the package can be installed successfully (just have warning NU1701 after installing the package instead of before) into the UWP template on Master\30029.156 + NuGet Client Dev\5.7.0.6598 as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/80688975-38a74000-8aff-11ea-8a6a-151e88149b0d.png)
Is the expected behavior to prevent installing the .NET Framework package into the UWP template as below?
![image](https://user-images.githubusercontent.com/20632625/80689057-570d3b80-8aff-11ea-8680-3c07951f5221.png)
So we consider to reactive this bug (after modifying the bug content) since it is not the expected result today.

**Comment by nkolev92** [comment] 2020-04-30 19:23
The asset target fallback is something that we don't control (the NuGet team), so I wouldn't necessarily worry about it. 

It'll be challenging to keep this test up to date, so I'd say we keep it closed.

**Comment by v-luzh** [comment] 2020-05-06 08:41
@nkolev92. Ok, keep it closed, thanks.
