### ISSUE TITLE
nuget list can show multiple version of same project

### ISSUE THREAD

**Issue by drache42** [NuGet/Home#8446] opened 2019-08-12 17:23 UTC
## Details about Problem

NuGet product used (NuGet.exe):

NuGet version (x.x.x.xxx):5.1.0.6013

Worked before? If so, with which NuGet version: unknown

## Detailed repro steps so we can see the same problem

1. nuget.exe list -source <link>

According to nuget help list, list should only display the latest version of each package
Actual: some packages are listed multiple times with different version
...

## Other suggested things
If I run the above command with verbose, I can see that nuget list does a GET on pages vs the entire thing. This means that it lists the latest version on page n, then list the latest version on page n+1 which may include the same package name

### Verbose Logs
```
...
PowerToolsPresentation
 1.25.5
 Common UI/Presentation logic between different Power Tools applications

  GET https://artifactory.prod.tableautools.com/artifactory/api/nuget/power-tools-nuget-local/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=30&$top=30&semVerLevel=2.0.0
  OK https://artifactory.prod.tableautools.com/artifactory/api/nuget/power-tools-nuget-local/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=30&$top=30&semVerLevel=2.0.0 15ms
PowerToolsPresentation
 2019.3.18
 Common UI/Presentation logic between different Power Tools applications
...
```

**Comment by nkolev92** [comment] 2019-08-13 05:31
Any chance you can try this with 3.5.0?

Can you please tell us how many sources you have and what they are? 
Details we'd be interested in knowing: 
3 ADO, 2 MyGet/ 1 NuGet.Server/1 file feed etc.

**Comment by drache42** [comment] 2019-08-13 14:55
Do you mean with Nuget 3.5.0? isn't that really old?

How do I check the for the following? 3 ADO, 2 MyGet/ 1 NuGet.Server/1 file
feed etc.

-Steffen

**Comment by rrelyea** [comment] 2019-08-13 16:03
Using nuget.exe, you can run "nuget sources" from the directory with the solution file in it.
(or project file, if you aren't using a solution)

**Comment by drache42** [comment] 2019-08-13 21:04
This works in nuget 3.5.0

`nuget sources` output
```
Registered Sources:

  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  power-tools-nuget-locals [Enabled]
      https://artifactory.prod.tableautools.com/artifactory/api/nuget/v3/power-tools-nuget-local
  3.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  4.  tab-nuget [Enabled]
      https://artifactory.prod.tableautools.com/artifactory/api/nuget/v3/tab-nuget
```

**Comment by Desarc** [comment] 2019-10-29 12:52
We're experiencing something similar to this, but it seems to depend on which artifact repository we use. We have two different on-premise repositories set up:

- Artifactory 6.13.1
- Proget 4.7.11

When testing this, I was using NuGet Version: 5.3.1.6268, with the following command:

```
nuget list somepackage -source <repository>
```

With the Proget repository we see the expected output (single package version), but with Artifactory, it lists a seemingly random selection of the available version, like this:

```
somepackage 1.2.5
somepackage 2.4.1
somepackage 2.5.13
```

It seems to depend on how many versions are available for that specific package. If only a few versions are available in the repository, it will only list one.

I don't know if this is actually a NuGet issue or an Artifactory issue, but at least it might provide some context here.

**Comment by nkolev92** [comment] 2020-07-09 17:23
@v-luzh 

Can you please try to see if this repros with nuget.org? 

Thanks. 

cc @aortiz-msft @zkat

**Comment by v-luzh** [comment] 2020-07-16 07:57
@nkolev92 It doesn't repro on Master\30315.165 + NuGet Client Dev\5.8.0.6721. No different versions are listed for a same package in both NuGet server source and Devops source. And the sources provided by customer (https://artifactory.prod.tableautools.com/artifactory/api/nuget/v3/power-tools-nuget-local and https://artifactory.prod.tableautools.com/artifactory/api/nuget/v3/tab-nuget) are unable to load anymore.

**Comment by nkolev92** [comment] 2020-07-16 19:10
Thanks @v-luzh. 

Given the above, we'd like to close this as not a bug. 

Please reach out to the package source vendor. 

Thanks!

**Closed as completed by nkolev92** 2020-07-16 19:10 UTC
Labels: Type:Bug, Product:NuGet.exe, Resolution:External, Functionality:List(Search)

**Comment by chipplyman** [comment] 2024-09-19 21:29
I have a repro for this issue and I think it should be reopened.  There does appear to be a bug in Nuget, exacerbated by a bug in Artifactory.

Artifactory bug: given `Search()?$filter=IsLatestVersion&orderby=Id&searchTerm=foo`, Artifactory ignores the IsLatestVersion filter and returns all packages matching Foo.  Given a sufficiently large repository, this can span multiple pages.  This appears to be a similar issue to https://github.com/PowerShell/PowerShellGallery/issues/273, as `Search()?$filter=%20IsLatestVersion&orderby=Id&searchTerm=foo` works as expected.

When nuget encounters multiple pages of results given an IsLatestVersion query, it returns the latest entry from each page, even if that entry has IsLatestVersion=false.

I can see value in returning an IsLatestVersion=false match if a feed query returns no entry with IsLatestVersion=true, but that logic needs to be aggregated across all pages.  The bug here is that nuget performs this logic for each page of a multi-page query result, returning (at least) one result per page.

Tested on nuget 6.4.0.

**Comment by chipplyman** [comment] 2024-09-19 23:09
It looks like this behavior is baked into the design of PackageSearchResource.SearchAsync.  IPackageSearchMetadata does not indicate whether an entry was marked IsLatestVersion or IsAbsoluteLatestVersion, so there's no way to filter results in aggregate across multi-page queries.
