### ISSUE TITLE
[Mono Issue] NuGet.exe pack will add duplicate files to nuget package

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#4073] opened 2016-12-08 20:01 UTC
Repro Step:
Unit test failed with mono on mac
https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/ProjectFactoryTest.cs#L361

the issue is During packing csproj with nuspec, if there is a file exist in both, that file will be added to package twice on mono.

the bug is we check the target path to exclude duplicate.
csproj dll target path is using Pach.Combine, so the path on mac will be lib/net45/test.dll.
For nuspec, nuget will use the path in Nuspec file as target path, so the path on mac will be lib\net45\test.dll.

then same file will be added twice.

**Comment by rrelyea** [comment] 2016-12-13 23:56
discussed with @zhili1208 -- this should be addressed as part of fixing #3584 

For now, when you pack on Linux on mono, if you use forward slashes it works ideally.
When you pack on Windows, if you use backward slashes, it works ideally.
Not a great situation -- and it likely impacts dotnet pack also.

**Comment by rrelyea** [comment] 2016-12-13 23:58
@zhili1208  - as I think about this more...
How badly impacted is Pack with dotnet.exe? Could we fix this one bug and be in good xplat shape for dotnet Pack and nuget pack on mono?
If it would be smallish fix to address just pack, we should consider before 4.0 ships.
/cc: @rohit21agrawal

**Comment by endeffects** [comment] 2017-01-17 10:35
Hi,

i have the same problem when i try to create a nuget package as bundle from different c# projects

**Nuspec**
```
<?xml version="1.0"?>
<package>
  <metadata minClientVersion="3.3.0">
    <id>WebApp.Basket.Data.ErpConnect</id>
    <description>WebApp.Basket.Data.ErpConnect</description>
    <version>1.0.0</version>
    <authors>Topmotive</authors>
    <owners>Topmotive</owners>
  </metadata>
  <files>
    <file src="WebApp.ErpConnect.Common\bin\Release\**" target="lib\net461" />
    <file src="WebApp.ErpConnect.Data.Wsvc\bin\Release\**" target="lib\net461" />
    <file src="WebApp.ErpConnect.Portal.ApplicationServices\bin\Release\**" target="lib\net461" />
  </files>
</package>

```

**Nuget Output**
> d:\01\52\s\Build\NuGet.exe pack "d:\01\52\s\WebApp.Services\WebApp.ErpConnect\WebApp.Basket.Data.ErpConnect.nuspec" -OutputDirectory "d:\01\52\s\Drop" -Properties Configuration=Release -Symbols -IncludeReferencedProjects -Version 1.0.87 -Verbosity detailed
> NuGet Version: 4.0.0.2217
> Attempting to build package from 'WebApp.Basket.Data.ErpConnect.nuspec'.
> Id: WebApp.Basket.Data.ErpConnect
> Version: 1.0.87
> Authors: Topmotive
> Description: WebApp.Basket.Data.ErpConnect
> Dependencies: None
> Added file '[Content_Types].xml'.
> Added file '_rels/.rels'.
> Added file 'lib/net461/Autofac.dll'.
> Added file 'lib/net461/Autofac.dll'.
> Added file 'lib/net461/Autofac.xml'.
> Added file 'lib/net461/Autofac.xml'.
> Added file 'lib/net461/cs/FluentValidation.resources.dll'.
> Added file 'lib/net461/da/FluentValidation.resources.dll'.
> Added file 'lib/net461/de/FluentValidation.resources.dll'.
> Added file 'lib/net461/es/FluentValidation.resources.dll'.
> Added file 'lib/net461/fa/FluentValidation.resources.dll'.
> Added file 'lib/net461/fi/FluentValidation.resources.dll'.
> Added file 'lib/net461/FluentValidation.dll'.
> Added file 'lib/net461/FluentValidation.xml'.
> Added file 'lib/net461/fr/FluentValidation.resources.dll'.
> Added file 'lib/net461/it/FluentValidation.resources.dll'.
> Added file 'lib/net461/ko/FluentValidation.resources.dll'.
> Added file 'lib/net461/mk/FluentValidation.resources.dll'.
> Added file 'lib/net461/nl/FluentValidation.resources.dll'.
> Added file 'lib/net461/pl/FluentValidation.resources.dll'.
> Added file 'lib/net461/pt/FluentValidation.resources.dll'.
> Added file 'lib/net461/ru/FluentValidation.resources.dll'.
> Added file 'lib/net461/sv/FluentValidation.resources.dll'.
> Added file 'lib/net461/WebApp.ErpConnect.Common.dll'.
> Added file 'lib/net461/WebApp.ErpConnect.Common.dll'.
> Added file 'lib/net461/WebApp.ErpConnect.Common.dll'.
> Added file 'lib/net461/WebApp.ErpConnect.Data.Wsvc.dll'.
> Added file 'lib/net461/WebApp.ErpConnect.Data.Wsvc.dll'.
> Added file 'lib/net461/WebApp.ErpConnect.Data.Wsvc.dll.config'.
> Added file 'lib/net461/WebApp.ErpConnect.Data.Wsvc.XmlSerializers.dll'.
> Added file 'lib/net461/WebApp.ErpConnect.Data.Wsvc.XmlSerializers.dll'.
> Added file 'lib/net461/WebApp.ErpConnect.Portal.ApplicationServices.dll'.
> Added file 'lib/net461/WebApp.Shared.ApplicationServices.Abstractions.dll'.
> Added file 'lib/net461/WebApp.Shared.DependencyInjection.Abstractions.dll'.
> Added file 'lib/net461/WebApp.Shared.DependencyInjection.Abstractions.dll'.
> Added file 'lib/net461/tr/FluentValidation.resources.dll'.
> Added file 'lib/net461/zh-CN/FluentValidation.resources.dll'.
> Added file 'package/services/metadata/core-properties/76017ddab8864391970e8e4286c92139.psmdcp'.
> Added file 'WebApp.Basket.Data.ErpConnect.nuspec'.
> Successfully created package 'd:\01\52\s\Drop\WebApp.Basket.Data.ErpConnect.1.0.87.nupkg'.

**Comment by nkolev92** [comment] 2017-10-17 18:34
Duplicate of https://github.com/NuGet/Home/issues/3584

**Closed as completed by nkolev92** 2017-10-17 18:34 UTC
Labels: Resolution:Duplicate, Platform:Xplat, Functionality:Pack, Platform:Mono
