### ISSUE TITLE
Pack targets don't include Summary

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#4357] opened 2017-01-22 17:29 UTC
Looking at the Pack targets in RC2, there doesn't seem to be a way to specify the "Summary" tag of the Nuspec in the csproj.

**Comment by rohit21agrawal** [comment] 2017-01-23 18:15
dupe of https://github.com/NuGet/Home/issues/4150

**Closed as completed by rohit21agrawal** 2017-01-23 18:15 UTC
Labels: Resolution:Duplicate
