### ISSUE TITLE
NU5123 (possibly other warnings) are not treated correctly with TreatWarningsAsErrors

### ISSUE THREAD

**Issue by tompazourek** [NuGet/Home#9373] opened 2020-04-01 14:46 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): **The "Pack" target from Microsoft.NET.Sdk** (dotnet\sdk\3.1.200\Sdks\NuGet.Build.Tasks.Pack)

NuGet version (x.x.x.xxx): **5.5.0-rtm.6473+4ba7bfa82f894ec32a554ca8d2df143675c85735.4ba7bfa82f894ec32a554ca8d2df143675c85735**

dotnet.exe --version (if appropriate): **3.1.200**

VS version (if appropriate): n/a

OS version (i.e. win10 v1607 (14393.321)): n/a

Worked before? If so, with which NuGet version: n/a

## Detailed repro steps so we can see the same problem

- Have `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` in an SDK-style csproj.
- Simulate a `NU5123` warning (should be turned into error).
- You can do so by using a code like this (create the `some-file.txt`, and then use this csproj snippet):

```xml
<PropertyGroup>
  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
</PropertyGroup>

<ItemGroup>
  <None Include="some-file.txt">
    <Pack>true</Pack>
    <PackagePath>content\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\very-long-path\</PackagePath>
  </None>
</ItemGroup>
```

- Run `dotnet pack` on the project
- The NU5123 will be propagated to error. But the package will **still be generated** and the `dotnet pack` **call will be successful**. The errors will be reported as errors though -- that makes it strange -- it's successful, but there are errors?
- I expect that the package will not be generated, or at the very least that the result will be an error, not a success. Otherwise, even if an error happens, everything appears to be green (e.g. in CI environment). Basically the warning is still not treated as an error, it's only displayed in red and appears in the error section, but everything else still looks green and successful (program exit code is 0 to be specific).

**Comment by nkolev92** [comment] 2020-04-06 21:27
Hey @tompazourek 

Thanks for filing this issue. This is a duplicate of https://github.com/NuGet/Home/issues/7404

**Closed as completed by nkolev92** 2020-04-06 21:27 UTC
Labels: Resolution:Duplicate, Functionality:Pack, Area:ErrorHandling, Product:dotnet.exe

**Comment by tompazourek** [comment] 2020-04-07 05:46
Hey @nkolev92. I tried searching before, but didn't find that one, it probably didn't have all the keywords.

I added some more comments for discussion to the original.

Thanks
