### ISSUE TITLE
Changes to nuget.config in directory of .sln should invalidate the cache

### ISSUE THREAD

**Issue by taori** [NuGet/Home#7237] opened 2018-08-24 10:41 UTC
I suppose the correct repo for this issue would be https://github.com/NuGet/NuGet.Services.Platform, but it does not allow issues.

I changed the nuget.config (placed besides a solutions .sln-file) contents to update the location of a local repo. This config change apparently did not invalidate the cache, since i had to restart Visual Studio for packages to load from the correct source.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):
4.6.0

dotnet.exe --version (if appropriate):

VS version (if appropriate):
15.8.1
OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:
Unknown if it worked at some point

## Detailed repro steps so we can see the same problem

1. Use local repo, pull packages
2. change nuget.config file to point to different location
3. pull packages again
4. check output log - if it still points to the old repo path it's wrong

**Comment by nkolev92** [comment] 2018-08-28 22:21
Duplicate of https://github.com/NuGet/Home/issues/1538

**Closed as completed by nkolev92** 2018-08-28 22:21 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Area:Settings
