### ISSUE TITLE
Migration Throws "Object reference Exception" in NuGet.PackageManagement.VisualStudio.SolutionRestoreWorker

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4067] opened 2016-12-07 18:56 UTC
Port of https://github.com/dotnet/roslyn-project-system/issues/896

**Repro Steps**
Copy the project from \scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip
Unzip to your machine
open the VSMigrationDemo\VSMigrationDemo.sln file
Accept all the migration notification.
Expected
Project migrated successfully
Actual

Log says
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<<get_IsSolutionFullyLoaded>b__67_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at Microsoft.VisualStudio.Threading.JoinableTask1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func1 asyncMethod, JoinableTaskCreationOptions creationOptions)
at NuGet.PackageManagement.VisualStudio.VSSolutionManager.get_IsSolutionFullyLoaded()
at NuGet.PackageManagement.VisualStudio.SolutionRestoreWorker.d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.b__0()
at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.b__0()
at GuardMethodClass.GuardMethod(Func1 , Func2 , Func2 ) --- End of inner exception stack trace --- ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object. at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<<get_IsSolutionFullyLoaded>b__67_0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTask1.CompleteOnCurrentThread()
at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func1 asyncMethod, JoinableTaskCreationOptions creationOptions) at NuGet.PackageManagement.VisualStudio.VSSolutionManager.get_IsSolutionFullyLoaded() at NuGet.PackageManagement.VisualStudio.SolutionRestoreWorker.<ScheduleRestoreAsync>d__27.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex) at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0() at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0() at GuardMethodClass.GuardMethod(Func1 , Func2 , Func2 )<---
Found in Build
d15rel/15.0.26006.0

**Comment by rrelyea** [comment] 2016-12-07 18:57
Assuming RC2 for now. have question out to @Srivatsn to understand RC2 v RC3

**Comment by alpaix** [comment] 2016-12-07 21:33
The root cause of the issue is incomplete initialization of NuGet components at the time of the migration as the solution is not fully loaded yet. @jainaashish's fix NuGet/NuGet.Client#1047 will resolve this as well.

**Comment by jainaashish** [comment] 2016-12-13 18:48
Fixed with #PR https://github.com/NuGet/NuGet.Client/pull/1047

**Closed as completed by jainaashish** 2016-12-13 18:48 UTC
Labels: Product:VS.Client, Type:Bug
