### ISSUE TITLE
Update all packages in NetCore projects updates for every TFM instead of ones that pacakge supports

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#3774] opened 2016-10-26 01:56 UTC
Please read the following information before posting the issue.
## Before posting the issue...
- If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
- If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropirate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:
## Detailed repro steps so we can see the same problem

1.

2.

...
### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)
### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by rrelyea** [comment] 2016-10-27 18:26
consider UI solution and scenarios

**Comment by jainaashish** [comment] 2017-11-09 22:36
Dupe of https://github.com/NuGet/Home/issues/4681

**Closed as completed by jainaashish** 2017-11-09 22:36 UTC
Labels: Product:VS.Client, Resolution:ByDesign, Style:PackageReference
