### ISSUE TITLE
NU1011 Centrally defined floating package versions are not allowed

### ISSUE THREAD

**Issue by omghb** [NuGet/Home#12300] opened 2022-12-06 14:39 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS 2022 17.4.2

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I have enabled central package management as described in this blog post: https://devblogs.microsoft.com/nuget/introducing-central-package-management/

I was looking forward to this feature as we have to manage a huge amount of C# projects with lots of NuGet dependencies. Unfortunately, I run into a limitation of this feature:
```
Error	NU1011	Centrally defined floating package versions are not allowed.
```

We reference our own developed packages via floating versions:
```xml
<PackageVersion Include="OurCompany.SomePackage" Version="*-*" />
```

This allows us to use always the latest version (e.g. from last night) within our solutions during development stage. When we create a release of our products we change those floating versions to fixed versions. The central package management would simplify the transition from development to release stage but unfortunately, it is not supported.

**My request:** Please, support floating package versions for central package versions as well.

### Verbose Logs

```shell
Error	NU1011	Centrally defined floating package versions are not allowed.
```

**Comment by jeffkl** [comment] 2022-12-06 16:16
Closing as a duplicate of https://github.com/NuGet/Home/issues/9384

**Closed as not planned by jeffkl** 2022-12-06 16:16 UTC
Labels: Resolution:Duplicate, Type:Bug

**Comment by stenretni** [comment] 2024-10-16 03:29
See #12919 for someone who came across this issue like me.
