### ISSUE TITLE
Why project.assert.json file is different between VS IDE restore and msbuild restore?

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10482] opened 2021-01-25 18:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Why-projectassertjson-file-is-differen/1242086?preview=true)._

---
<p>[severity:It bothers me. A fix would be nice]<br>
I created a <code>Net Framework 4.7.2</code> console project called <strong>Common</strong> with a PackageReference nuget package <code>Antlr</code>. Then, I changed the <code>assemblyname</code> to <code>Common.xyz</code> for the output file by right-click on the <strong>Project Properties</strong>–&gt;<strong>Application</strong>–&gt;change <strong>Assembly Name</strong> to <code>Common.xyz</code>.</p><p>For the first step,  I build the <strong>Common</strong> project in VS IDE and in <code>obj</code> folder, I checked the restore file <code>project.assert.json</code> and found the <code>projectName</code> is <code>Common</code>.</p><p><a href="https://developercommunity2.visualstudio.com/storage/attachments/162970-capture.png"> Image:162970-capture.png</a></p><p><strong>However</strong>, I delete the <code>bin</code> and <code>obj</code> folder, and then use msbuild command line, <code>msbuild -t:restore</code>, and then check the <code>project.assert.json</code> file, I found that the <code>projectname</code> is <code>Common.xyz</code>. And <code>nuget restore</code> command also set the <code>projectname</code> to <code>Common.xyz</code>.</p><p><a href="https://developercommunity2.visualstudio.com/storage/attachments/162969-capture1.png"> Image:162969-capture1.png</a></p><p>So I am confused and want to know which one is right. And what is the reason for this difference? What is the difference between msbuild restore and vs ide restore?</p>

---
#### good man on 11/3/2020, 00:07 AM: 

<p>I hope someone could give you some suggestions about this.</p>

#### Kharitonov, Mark on 11/3/2020, 06:50 AM: 

<p>The differences for big solutions are beyond just "bothering". As https://stackoverflow.com/questions/64576860/why-does-console-build-generate-radically-different-project-assets-json-than-tha/64658887#64658887 shows the project.assets.json produced by VS IDE can lack many libraries and can even report dependency versions that are different from those reported by msbuild. Unfortunately, I do not have a minimal reproduction yet. Our solution is +100 projects strong.</p>

#### Feedback Bot on 11/3/2020, 07:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Benjamin Villalobos [MSFT] on 1/20/2021, 09:28 AM: 

<p>Does running <code>msbuild /restore</code> instead of <code>msbuild -t:restore</code> result in different behavior?</p>

#### Kharitonov, Mark on 1/20/2021, 04:43 PM: 

<p><a target='_blank' href="https://aka.ms/dc/u?aid=218570">Benjamin Villalobos [MSFT]</a> - no. The generated project.assets.json are the same.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment] 2021-02-04 03:30
Duplicate of https://github.com/NuGet/Home/issues/8272.

**Closed as completed by nkolev92** 2021-02-04 03:30 UTC
Labels: Product:VS.Client, Type:Bug, Functionality:Restore
