### ISSUE TITLE
Enable updating packagereference versions from the command line (for csproj)

### ISSUE THREAD

**Issue by brgrz** [NuGet/Home#4358] opened 2017-01-22 19:33 UTC
Currently the .NET Core CLI does not support automatic package updates to the the new .NET Core .csproj format (reading the file, updating the packages and updating the references within the file) as per 
https://github.com/dotnet/cli/issues/5425 (that is using `dotnet restore` or any other command/means)

Is there a plan for nuget.exe to support the missing functionality like it does for the old (Visual Studio) .csproj?

**Comment by emgarten** [comment] 2017-01-22 20:07
@brgrz 4.0.0 will support PackageReferences. Try https://dist.nuget.org/win-x86-commandline/v4.0.0-rc3/NuGet.exe

**Comment by brgrz** [comment] 2017-01-22 20:30
What's the correct way to use this? I tried and got this:

PS C:\Users\brgrz\Documents\testApp> .\nuget update testapp.csproj
MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
Exception has been thrown by the target of an invocation. The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\brgrz\Documents\testApp\testapp.csproj

**Comment by clairernovotny** [comment] 2017-01-22 20:43
This raises an interesting question .... what if `nuget.exe` isn't run from a developer command prompt or where msbuild 15 isn't in the path?

**Comment by brgrz** [comment] 2017-01-22 20:53
My setup here is a new .NET Core RC4 (latest bits from CLI's GitHub) project and I have the nuget (3.5.0) in my path but I copied the Nuget.exe @emgarten linked to the root of my app and it picks up the right one when I run .\nuget update testapp.csproj:

PS C:\Users\brgrz\Documents\testApp> .\nuget
NuGet Version: 4.0.0.2215

oh and btw I do not have VS 2017 RC installed here

**Comment by emgarten** [comment] 2017-01-22 21:38
> what if nuget.exe isn't run from a developer command prompt or where msbuild 15 isn't in the path?

You can specify ``-MSBuildPath`` and give the bin folder of MSBuild to override. nuget.exe can auto detect and find MSBuild 15.0, but it favors the version on your path. 

> .\nuget update testapp.csproj

There is no PackageReference replacement for ``update`` yet, the command to modify references is only in ``dotnet``.  I suggest using floating versions such as ``1.0.*`` or ``1.0.0-beta-*`` to automatically update packages each time you run ``nuget.exe restore`` for your development scenarios.

**Comment by brgrz** [comment] 2017-01-23 07:20
> You can specify -MSBuildPath and give the bin folder of MSBuild to override. nuget.exe can auto detect and find MSBuild 15.0, but it favors the version on your path.

I don't know which MSBuild I have installed. As said, I only installed the .NET Core SDK and VS Code.

> There is no PackageReference replacement for update yet, the command to modify references is only in dotnet. I suggest using floating versions such as 1.0.* or 1.0.0-beta-* to automatically update packages each time you run nuget.exe restore for your development scenarios.

I don't quite understand what you're saying. How do I actually solve the issue I'm having by using the `nuget.exe` you provided?

**Comment by emgarten** [comment] 2017-01-23 19:11
> How do I actually solve the issue I'm having by using the nuget.exe you provided?

Would you provide more details on the issue you are having and what you expect?

**Comment by brgrz** [comment] 2017-01-23 20:15
My issue is simple, really. Discover new updates for packages referenced through PackageReferences, update them (cherry picking would be nice but at this time it is not mandatory) and then update the PackageReferences to reflect the changes. VS Code/nuget.exe/CLI only.

**Comment by stevenscreek** [comment] 2017-03-23 01:52
We're also hoping to see this.  Floating versions do not work for us, as we want reproducible builds, no matter what package version updates have happened since the last build.

We've ended up writing a tool that parses csproj files, looks for PackageReference, queries our nuget server, and updates the versions.  We'd love to throw this away.

**Comment by steve-torchia** [comment] 2017-05-11 18:38
@stevenscreek  We're in the same boat.  Is your tool on GitHub by any chance?  Was about to roll my own when I came across your post

**Comment by stevenscreek** [comment] 2017-05-12 03:10
@steve-torchia Unfortunately, it's not (and there's not much I can do to make that change).

**Comment by haugan** [comment] 2017-05-28 16:35
So weird that this functionality isn't available in VS Code. Are we supposed to track and update each package reference in .csproj manually?

**Comment by jahmai-ca** [comment] 2017-05-29 02:58
I slapped this together over the weekend, because doing updates with Visual Studio 2017 is agony (takes 10 minutes just to calculate the updates, 20 mins to execute them, and then half the time doesn't properly update everything).

https://gist.github.com/jahmai/6868dbaeb9032eabb1cd0c6b6a2088e8

Disclaimer: Works for me, might not work for you.

**Comment by pbelousov** [comment] 2017-10-25 16:01
Hi All, are there any news or expectations on this feature?

**Comment by zhili1208** [comment] 2017-11-09 22:47
close as dupe of https://github.com/NuGet/Home/issues/4103

**Closed as completed by zhili1208** 2017-11-09 22:47 UTC
Labels: Resolution:Duplicate, Type:Feature, Product:NuGet.exe

**Comment by AraHaan** [comment] 2021-02-01 17:23
@jahmai nice, but what about on your gist on allowing updates for imported props that contains ``PackageReference``s too?
