### ISSUE TITLE
[Test Failure] Package Reference executing delay

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4263] opened 2017-01-12 09:27 UTC
**NuGet Version:** NuGet 4.0.0-rtm-2205
**VS Version:** D15Rel 26111.00
**OS Version:** Windows 10 RS1_Release 14393.723.170109-1801

**Repro Steps:**
1.	New a Visual C#->Windows Classic Desktop->Console App (.NET Framework) template.
2.	Right-click on the project and click ‘Manage NuGet Packages…’.
3.	Try to install package 'Newtonsoft.Json 9.0.1'.
4.	Select ‘PackageReference in project file’ as package management format and click 'OK'.
5.	Clicking ‘Reference’ expender to check if the package ‘Newtonsoft.Json’ exist.
6.	Then uninstall package 'Newtonsoft.Json 9.0.1' and check if the package is removed from ‘Reference’ node .

**Expected Result:**
The installed package is added under the ‘References’ node in step 5 and the uninstalled package is removed from the ‘References’ node in step 6.

**Actual Result:**
The installed package is not added under the ‘References’ node in step 5 and the uninstalled package is not removed from the ‘References’ node in step 6 as below screenshot.
![888](https://cloud.githubusercontent.com/assets/20632775/21883833/ce4afdb4-d8eb-11e6-86d9-6bb1df1c3019.png)
![999](https://cloud.githubusercontent.com/assets/20632775/21883836/d0044bba-d8eb-11e6-9b03-a9dadff457d4.png)

 
 
**Notes:**
The issue repro on D15Rel 26111.00 + NuGet release-4.0.0-rc3 2206.
The issue repro on WPF (.NET Framework) project.

**Comment by rrelyea** [comment] 2017-01-12 16:50
Dupe of #4232 which is being tracked as an external issue, and fixed in the csharp project system or related (Roslyn-ish)

**Closed as completed by rrelyea** 2017-01-12 16:50 UTC
Labels: Resolution:External
