### ISSUE TITLE
nuget.exe should be renamed to NuGet.exe to have the correct casing and consistent with older releases

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1041] opened 2015-07-28 23:25 UTC
Now we generated nuget.exe and NuGet-Signed.exe.

Should rename nuget.exe to NuGet.exe

**Comment by deepakaravindr** [comment] 2015-08-10 04:30
Looks like the nuget.exe published to nuget.org is nuget.exe. However, the exe shipped as part of NuGet.CommandLine package is NuGet.exe

**Comment by deepakaravindr** [comment] 2015-08-12 23:14
Duplicate of https://github.com/NuGet/Home/issues/873

**Closed** 2015-09-01 21:49 UTC
Labels: 2 - Working

**Comment by deepakaravindr** [comment] 2015-09-02 01:46
We will use the same casing for nuget.exe both the exe and NuGet.CommandLine package. It will be simply nuget.exe
