### ISSUE TITLE
Improve documentation for the $references$ replacement token

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#3366] opened 2016-08-23 21:04 UTC
_From @StevenLiekens on March 27, 2015 13:55_

The Nuspec Reference page describes the existence of a `$references$` replacement token, but the documentation is not very useful.

The Nuspec Reference should be updated to contain a sample that demonstrates the `$references$` token, and a description of what it replaces and how it is replaced.

http://docs.nuget.org/Create/Nuspec-Reference#replacement-tokens

_Copied from original issue: NuGet/NuGetDocs#329_

**Comment by sliekens** [comment] 2016-08-23 21:15
Thanks for taking a look at this.

**Comment by karann-msft** [comment] 2016-09-27 23:09
@kraigb

**Comment by kraigb** [comment] 2016-10-17 22:47
Just to note, Steven, I'm investigating how this is supposed to be used, because so far as I can tell from tests, $references$ token doens't do anything. In the meantime I'll be removing it from the docs altogether.

**Comment by kraigb** [comment] 2016-12-01 19:36
@karann-msft -- we can close this issue; $references$ (not functional) is removed from the docs so the issue is no longer relevant.

**Closed as completed** 2016-12-06 22:05 UTC
Labels: Type:Docs
