### ISSUE TITLE
The project dependencies in project.assets.json are named in an inconsistent manner

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#10255] opened 2020-11-11 17:05 UTC
---
**Issue moved from dotnet/msbuild#5860**
- Please respond to @MarkKharitonov.

---

_From @MarkKharitonov on Thursday, November 5, 2020 6:11:33 PM_

### Issue Description
We are talking about .Net Framework projects using **ProjectReference**.

Some project entries in project.assets.json are named after the project name and some are named after the respective assembly name. The logic behind selecting one or another is unclear and makes it hard to write custom processing of this file. For example, to deal with the binding redirect hell.

### Steps to Reproduce
https://github.com/MarkKharitonov/PackageAssetsJsonAnomaly#the-anomaly - this repository contains 3 tiny projects and describes the repro steps in README.

### Expected Behavior
The names of project entries follow a consistent scheme - either project or assembly names, but not mixed.

### Actual Behavior
On a sample solution with 3 tiny projects, the project.assets.json file names one project dependency after the project name and another - after the assembly name.

### Analysis
I do not have an idea, but I am afraid it is related to https://stackoverflow.com/questions/64576860/why-does-console-build-generate-radically-different-project-assets-json-than-tha

### Versions & Configurations
https://github.com/MarkKharitonov/PackageAssetsJsonAnomaly#the-anomaly

### Attach a binlog
https://github.com/MarkKharitonov/PackageAssetsJsonAnomaly/blob/master/msbuild.binlog

**Comment by MarkKharitonov** [comment] 2020-11-18 13:13
Anyone to comment?

**Comment by zivkan** [comment] 2020-11-18 19:42
My guess is that it's probably the same root cause as https://github.com/NuGet/Home/issues/9417 and https://github.com/NuGet/Home/issues/5261. In other words, VS project systems give NuGet different information compared to when NuGet reads project properties directly from MSBuild on the command line.

**Comment by MarkKharitonov** [comment] 2020-11-18 20:06
The reproduction in github (https://github.com/MarkKharitonov/PackageAssetsJsonAnomaly) does not involve the Visual Studio at all. Everything is done using msbuild. 
The SO question does talk about the difference between VS and msbuild, but it is not the subject of this issue.

**Comment by zivkan** [comment] 2020-11-18 20:10
We prioritize work based on a number of factors, including customer impact and upvotes.

Regarding customer impact, what actual problem is this causing you? Your issue just says the contents of the assets file has a different value, which makes it sound like using a different tool to restore will cause a slightly slower restore than a no-op restore. But if that's the case there's no errors, just a minor performance issue.

**Comment by MarkKharitonov** [comment] 2020-11-18 20:19
I am writing a tool that would be useful to anyone who uses non SDK style projects with PackageReferences. The tool solves the problem of binding redirects by automatically generating them. It uses projects.assets.json. But because of this problem it is not clear whether the entries are named after the project name or assembly name. That inconsistency makes it harder to write robust tooling.

Plus, I believe it can be a source of other problems, like difference between VS and msbuild generated project.assets.json.

I am pretty certain it is a symptom of deeper problems with the NuGet framework.

**Comment by zivkan** [comment] 2020-11-18 20:31
The tool you're writing sounds like [MSBuild's `ResolveAssemblyReference` task](https://docs.microsoft.com/en-us/visualstudio/msbuild/resolveassemblyreference-task?view=vs-2019) (it has the `AppConfigFile` parameter). It should run automatically as part of the build, so I'm surprised the binding redirects aren't already correct. But in case you're not aware of it, I suggest investigating to see if it can save you time from reinventing what it does.

**Comment by MarkKharitonov** [comment] 2020-11-18 21:01
Could you elaborate? For example, I can see this task running for our web application and it does pass AppConfigFile. However, it does not update the config file automatically. I suspect it just outputs the bindings for us to modify manually. 
But there is more to it. The current process does not tell to remove irrelevant binding redirects. We tried to rely on the output produced by this task and as a result our binding redirects just grow monotonically. It becomes a mess. When you have a monolithic application with more than 300 projects, about 20 web applications and 60 unit test projects (which must run after the build) - it is really not fun.

But there is more - some NuGet packages simply "lie". They claim dependency on a NuGet package with a dll of assembly version X whereas the actual depency is on assembly version Y. Case in point - https://stackoverflow.com/questions/64793562/how-to-deal-with-microsoft-aspnet-web-optimization-1-1-3-nuget-package

My tool (which I have already implemented) identifies all these cases and generates correct redirects. But the standard task does it too, so I suppose I could wrap it with our additions.

Also, it makes sure the actual dlls are copied to the bin folder at the end of the build, thus ensuring that the binding redirects produced on the developer machine are actually valid on the CI build where a difference in project build order could result in a mismatching dll placed in the bin folder. It has special treatment for unit test projects, which are not published like web applications and hence are especially sensitive (I generate `<codebase.../>` elements for the unit test binding redirects).

So right now I suppress all the messages about missing binding redirects and just generate them automatically with the tool.

**Comment by MarkKharitonov** [comment] 2020-11-19 02:01
I suppose that I could have wrapped the standard task in order to leverage the already existing logic.

**Comment by zivkan** [comment] 2020-11-19 18:03
> Could you elaborate?

Console apps, WPF app, WinForms app, basically anything other than an ASP.NET projects, when using PackageReference, do not need any binding redirects in the app.config file. As part of the build process, the SDK will copy `app.config` from the project root, to `$(OutputDir)\<assemblyname>.config` (`OutputDir` is usually `bin\Debug` or `bin\Release`). Additionally, as it copies all the referenced dlls into the same directory, it will do an assembly level analysis and write binding redirects.

ASP.NET is an exception, because that project system doesn't copy the `web.config` file to the bin directory, and the "SDK"/build system/whatever you want to call it, doesn't use `ResolveAssemblyReferences` to update the web.config file's binding redirects. Why? I don't know. I understand not wanting to change customer files (like web.config) that are checked into source control, during a build. But I suspect that it's also because ASP.NET projects existed for 5+ years before NuGet ever did, so the project system couldn't have been designed to work nicely with a package manager.  Anyway this is one reason why NuGet's "migrate from packages.config to PackageReference" is not enabled in Visual Studio for ASP.NET projects.

I haven't worked on ASP.NET applications for many years, and at the time my team only had one monolith app, so managing binding redirects wasn't unbearable for us. So, I don't know of any existing tools to do this.

> They claim dependency on a NuGet package with a dll of assembly version X whereas the actual depency is on assembly version Y

Assembly and package versions are independent. All I can say is don't expect them to be the same. There are many System.* packages where they are not the same, none of the NuGet.* packages (at least from the NuGet.Client team) on nuget.org have matching assembly & package versions, I wouldn't be surprised if many Microsoft.* packages also do not have matching package and assembly versions. Any tooling should expect the versions to be different. When you need to get assembly versions, you need to do an assembly file analysis.

It's difficult to get started, because there are no docs, but `System.Reflection.Metadata` is the "official" low level to read assembly metadata without actually loading it into managed memory, which avoids problems with trying to load different assembly versions of the same assembly name, and avoids needing to use app domains or AssemblyLoadContext to unload assemblies. You might also have better luck (more docs, easier to use APIs) with Roslyn or Mono.Cecil.  Although you said you already wrote the tool, so perhaps you've already solved this problem.

**Comment by MarkKharitonov** [comment] 2020-11-19 20:02
SDK style projects are great. But we are not using them yet. We have 300+ projects that were migrated to PackageReference, but not SDK, because it is a major chunk of work.

So, is this process relevant for non SDK style projects? My feeling, it is not, because we deal with binding redirects all the time and we do use PackageReference.

(I use Mono.Cecil and NuGet framework NuGet libraries to process project.assets.json and assemblies. Totally aware of the difference between NuGet and Assembly versions. Major pain in the behind)

**Comment by nkolev92** [comment] 2021-12-07 00:54
Fixed in NuGet/NuGet.Client#4172.

Try out Visual Studio 2022, dotnet SDK 6.0.100 and/or NuGet.exe 6.0 for the matching tooling.

Please ensure all your tooling is updated (consider using msbuild and VS since they ship together for best results).

**Closed as completed by nkolev92** 2021-12-07 00:54 UTC
Labels: Priority:3, Type:Bug, Functionality:Restore, Partner:MSBuild
