### ISSUE TITLE
nuget.exe v5.8.1 cannot get the value from assemblyinfo.cs by $version$

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10481] opened 2021-01-25 18:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/nugetexe-v581-cannot-get-the-value-fr/1316506)._

---
[severity:It bothers me. A fix would be nice]
I used **VS2019** and **nuget.exe v5.8.1**. I created a net framework 4.7.2 class library project and add `version`, `description`, `company`..... any info under `assemblyinfo.cs` file.

! [image.png] (https://aka.ms/dc/image?name=Be38d15bf8e2e42c2b37181394f9c3a82637468060642747112_20210121-140743-image.png&tid=e38d15bf8e2e42c2b37181394f9c3a82637468060642747112)

Then, use this nuspec file to pack the project.

```
<?xml version="1.0" encoding="utf-8"?>
<package >
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <title>$title$</title>
    <authors>me</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <projectUrl>http://project_url_here_or_delete_this_line/</projectUrl>
    <iconUrl>http://icon_url_here_or_delete_this_line/</iconUrl>
    <description>me</description>
    <releaseNotes>Summary of changes made in this release of the package.</releaseNotes>
    <copyright>$copyright$</copyright>
    <tags>Tag1 Tag2</tags>
  </metadata>
</package>
```

From [this document](https://docs.microsoft.com/en-us/nuget/reference/nuspec#replacement-tokens), it said that `$version$` will be replaced with `assemblyversion's` value under `AssemblyInfo.cs` file. 

But I did not get the value under `nuget.exe v5.8.1`, also, happens under `nuget.exe v5.7.0`. But it works well under `nuget.exe v5.6.0`.

Is it an issue under `v5.7.0` and `v5.8.1`?

---
#### Feedback Bot on 1/20/2021, 11:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Perry004** [comment] 2021-01-26 09:17
I also faced the issue.

**Comment by Perry004** [comment] 2021-01-29 07:00
Could anyone have any ideas?

**Comment by nkolev92** [comment] 2021-02-04 03:23
Duplicate of https://github.com/NuGet/Home/issues/9954

Please refer to the below for workaround.
https://github.com/NuGet/Home/issues/9954#issuecomment-754952859

**Closed as completed by nkolev92** 2021-02-04 03:23 UTC
