### ISSUE TITLE
No events from IVsPackageInstallerEvents and IVsPackageInstallerProjectEvents for SDK projects

### ISSUE THREAD

**Issue by sergeyQx** [NuGet/Home#7804] opened 2019-02-15 12:22 UTC
here's the Visual Studio extension that obtains the IVsPackageInstallerEvents and listens to it https://drive.google.com/open?id=1oKqUYEUg_gCcBhkbDcjVIp7gUU_2vspa
It receives events for old-fashioned projects but does not for SDK-based projects.

**Comment by debonte** [comment] 2019-05-13 22:55
Dupe of issue #6872?

**Comment by nkolev92** [comment] 2019-05-28 22:08
Yeah, duplicate of https://github.com/NuGet/Home/issues/6872. 

Thanks @debonte

**Closed as completed by nkolev92** 2019-05-28 22:08 UTC
Labels: Resolution:Duplicate, Type:Bug
