### ISSUE TITLE
nuget update from internal source NullReferenceException

### ISSUE THREAD

**Issue by wbradney** [NuGet/Home#2249] opened 2016-03-04 15:46 UTC
I have an update that goes something like this:

`nuget.exe update MySolution.sln -Source "https://internalrepos/app/nuget/;\\sharedserver\LocalPrereleases"`

I get:

```
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Scanning for projects...
Found 1 project with a packages.config file. (MyProj.csproj)
Feeds used:
  https://internalrepos/app/nuget/
  \\sharedserver\LocalPrereleases

Attempting to gather dependencies information for multiple packages with respect to project 'C:\blah\MyProj.csproj', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for multiple packages
WARNING: Object reference not set to an instance of an object.
```

**Comment by wbradney** [comment] 2016-03-04 15:56
Actually, after I moved all of the prerelease packages from the network share repo into the internal repo, the following also fails the same way:

`nuget.exe update MySolution.sln -Source "https://internalrepos/app/nuget/"`

The internal repo is being fed by TeamCity. I can do a `nuget.exe list` just fine to see all our packages in there.

Any ideas?

**Comment by wbradney** [comment] 2016-03-04 16:40
Oh, and I guess I should have pointed out that we have zero problems updating solutions from our internal feed in Visual Studio. We have a lot of solutions, however, so we need a way to update from the command-line.

**Comment by yishaigalatzer** [comment] 2016-03-04 21:04
@wbradney we are not familiar with your specific case, so it will be super helpful if you can share a small repro (I noticed you are trying to build yourself - Awesome!, I hope you get through it).

Also note we have an RC release of NuGet 3.4 available on http://dist.nuget.org/index.html never hurts to try, "maybe" it will fix your issues.

**Comment by yishaigalatzer** [comment] 2016-03-04 22:15
1st what version of NuGet are you using (looks like it is some sort of 3.X, but which one specifically are you using?)

Not sure, but if you can setup a repro scenario, I'll had someone work on it first thing Monday morning

**Comment by wbradney** [comment] 2016-03-05 02:27
I did a `nuget update -self` just today so should be bang up to date. I'll try the RC and if no luck I'll have another go at debugging the sources. I suspect the problem is related to our internal TeamCity repository, but it works fine in every other use case we've tried thus far.

UPDATE: version 3.3.0.212 was what I had. The 3.4 RC didn't fix it.

Thanks

**Comment by wbradney** [comment] 2016-03-05 02:28
Can you give me a clue as to where in the codebase I'd need to be looking to spot this?

**Comment by yishaigalatzer** [comment] 2016-03-05 02:47
Here is what I do - compile and run until you get the repro. The run with --debug flag.

Attach and turn on first chance exceptions, unchecked everything except nullref, you should drop right there

**Comment by wbradney** [comment] 2016-03-05 13:27
Ah. I hadn't realized that `-Verbosity detailed` shows the full error stack - cool.

```
WARNING: System.InvalidOperationException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PackageManagement.PrunePackageTree.<>c__DisplayClass13_0.<PruneByUpdateConstraints>b__0(SourcePackageDependencyInfo p)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at NuGet.Resolver.PackageResolver.RemoveImpossiblePackages(IEnumerable`1 packages, ISet`1 mustKeep)
   at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForClassicAsync>d__37.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForClassicAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.CommandLine.UpdateCommand.<UpdatePackagesAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.UpdateCommand.<UpdateAllPackages>d__36.MoveNext()
```

**Comment by wbradney** [comment] 2016-03-07 14:34
It looks like `DependencyInfoResourceV2.ResolvePackage()` ends up adding a `null` to the `combinedList` of all packages, because it fails to `FindPackage`on the package that is currently being referenced by the csproj. The package it's looking for is indeed in the repository, however...
[A `nuget list -AllVersions` shows it and I can `nuget install` that specific version without a problem]
Where's the code for `PackageRepositoryExtensions`, I wonder?

**Comment by wbradney** [comment] 2016-03-07 14:36
Should the failure to find the current package be fatal here? If not it's always going to cause an obscure `NullReferenceException`later on...

**Comment by wbradney** [comment] 2016-03-07 14:52
Note that the package in question is a prerelease version (`Blah.0.1.1-alpha9`). In the debugger it seems that `PackageRepositoryExtensions.FindPackage()` returns null for all versions of this prerelease package except the latest one.

**Comment by yishaigalatzer** [comment] 2016-03-07 16:07
Can you compose a repro scenario?

**Comment by wbradney** [comment] 2016-03-07 21:00
I am unable to reproduce it with test packages in a local folder. I need to be able to step into `PackageRepositoryExtensions.FindPackage()` - where does that code live?

**Comment by yishaigalatzer** [comment] 2016-03-07 21:05
https://github.com/NuGet/NuGet2/blob/2.11/src/Core/Repositories/PackageRepositoryExtensions.cs

**Comment by yishaigalatzer** [comment] 2016-03-10 19:54
@TimBarham if this makes it to RTM, we need it checked in by 5pm our time (Thursday PST)

**Comment by TimBarham** [comment] 2016-03-10 22:38
Thanks @yishaigalatzer - I've opened a PR with a fix. Note that this fix is just for the NRE, not for the issue where `FindPackage()` returns `null` for this particular package. Thanks for the stack trace, @wbradney - made it easy to track down :smile:.

**Closed as completed** 2016-03-10 22:57 UTC
Labels: Type:Bug, Product:NuGet.exe

**Comment by wbradney** [comment] 2016-03-10 23:34
Thanks, Tim. I'd actually made the same change locally to get past this, and when I get a chance I'll try to figure out why the package is not being found in the first place. I think it must be something about the way TeamCity offers up its feed, because I can't seem to reproduce it with the same packages in a local folder.

One thing I was wondering is what is the easiest way to step into FindPackage from Nuget3, since it seems to be in the legacy Nuget2 repo?

Sent from my Windows Phone

**Comment by yishaigalatzer** [comment] 2016-03-10 23:39
Shouldn't be anymore in 3.4

Sent from Outlook Mobilehttp://aka.ms/xp9y6l

On Thu, Mar 10, 2016 at 3:34 PM -0800, "Wayne Bradney" <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks, Tim. I'd actually made the same change locally to get past this, and when I get a chance I'll try to figure out why the package is not being found in the first place. I think it must be something about the way TeamCity offers up its feed, because I can't seem to reproduce it with the same packages in a local folder.

One thing I was wondering is what is the easiest way to step into FindPackage from Nuget3, since it seems to be in the legacy Nuget2 repo?

Sent from my Windows Phone
