### ISSUE TITLE
Package content is not restored correctly when installing a package from a nuget v3.3+ feed with the argument -NoCache when the package contains *.nupkg files

### ISSUE THREAD

**Issue by simonejsing** [NuGet/Home#2354] opened 2016-03-17 19:28 UTC
I have a Nuget package which itself contains other Nuget packages (*.nupkg files). When I install this package, the contained *.nupkg files are missing from the output location.

The issue only occurs when installing packages from nuget v3.3+ feeds. If I install the package from a local file share or a nuget v2 feed it works as expected and the output location has the contained *.nupkg files in it.

When I install a package from a nuget v3.3+ feed it is first copied and extracted to a machine cache which normally is under %appprofile%, but can be changed with the environment variable NUGET_PACKAGES. In this temporary location the package content is correct (it contains the *.nupkg files). It is when the package content is copied from the temporary location to the output directory that contained *.nupkg files end up missing.

Furthermore, the broken behavior is influenced by the use of the –NoCache switch to nuget.exe. If I don’t specify –NoCache, then the package content correctly contains all the .nupkg files.

To repro create a Nuget package that contains *.nupkg files, upload it to a nuget v3.3+ feed and restore it from there using the -NoCache argument to nuget.exe.

**Comment by yishaigalatzer** [comment] 2016-03-23 00:18
For prioritizing purposes: Can you explain the scenario?

**Comment by simonejsing** [comment] 2016-03-23 18:33
We are a Microsoft team that runs the Engineering Systems for development of Microsoft Dynamics AX. The team is large, and we rely on Nuget to pull down packages for build dependencies in our internal Engineering Systems (based on CoreXt and VSTS if that is familiar to you). One of these packages happens to contain .nupkg files. When it is installed the content is incorrectly missing these .nupkg files causing build errors in our Continuous Integration system. This affects our CI builds as well as local developer builds.

As a temporary workaround we have switched to consume packages from the v2 Nuget endpoints which does not show this bug.

**Comment by yishaigalatzer** [comment] 2016-03-23 18:39
That sounds like a design gone wrong, packages should be packages and not shipped inside other packages. I would advise changing your design.

In the meantime we figure out how to prioritize he fix here, you can also contribute it if you'd like to unblock yourself quickly (though ID still recommend not relying on nupkg inside nupkg)

**Comment by simonejsing** [comment] 2016-03-23 23:01
Well I would tend to agree with you on a design gone wrong, but sometime you inherit something that you just have to live with.

That being said, I would strongly expect Nuget to treat the content of any package the same way, be it .nuspec, .nupkg, or any other file extension for that matter.

Btw. I also tested this with Nuget 3.4 and the bug still exists.

**Comment by yishaigalatzer** [comment] 2016-03-23 23:11
Feel free to contact me offline.

**Comment by plequere** [comment] 2016-04-05 21:46
We (VSEng) are also hitting this issue and had to downgrade our feed to v2. While I agree that the package isn't well formed, unfortunately we have no direct control over our packages since we're consuming packages from various sources in the VS build environment.

**Comment by yishaigalatzer** [comment] 2016-04-05 21:55
I suggest pushing back on the package owners to remove the nupkg's from the package, but we will take a look at a fix for 3.5. If you'd like to speed it up, feel free to jump in and suggest a pull request.

**Comment by simonejsing** [comment] 2016-04-06 18:45
The bug is in PackageFolderReader in the GetFiles() method:

``` c#
        public override IEnumerable<string> GetFiles()
        {
            var searchFolder = new DirectoryInfo(_root.FullName);

            foreach (var file in searchFolder.GetFiles("*", SearchOption.AllDirectories).
                Where(p => !p.FullName.EndsWith(PackagingCoreConstants.NupkgExtension, StringComparison.OrdinalIgnoreCase)))
            {
                yield return GetRelativePath(_root, file);
            }

            yield break;
        }
```

which excludes all .nupkg files

**Comment by simonejsing** [comment] 2016-04-06 18:51
will have a suggested fix out shortly

**Comment by yishaigalatzer** [comment] 2016-04-06 18:51
Thanks for pointing out where the code filters out the nupkg files. It is obviously an intended behavior with a side effect for your scenario, I don't think that is where the bug/fix actually is. We don't want the nupkg to flow from the global package folder out to the target, and it is hard to tell what is the nupkg file exactly (because the filename might vary)

So a fix would be a lot more specific to your scenario, and will require careful examination of all the other scenarios.

**Comment by simonejsing** [comment] 2016-04-06 18:52
my suggested fix is to exclude only .nupkg files that are in the root of the package

**Comment by yishaigalatzer** [comment] 2016-04-06 19:08
That should work

**Comment by simonejsing** [comment] 2016-04-06 19:09
The change that introduced the filter was related to this issue:
https://github.com/NuGet/Home/issues/1387

which talks about duplicate .nupkg files at the root of the package, so I don't think this should cause unintended side effects.

**Comment by simonejsing** [comment] 2016-04-06 19:12
Which branch should I be requesting to be pulled into? I can't get the dev branch to build (some missing DotNet under msbuild folder), so I'm currently working in head detached mode from this tag: v3.4.0-rc-VSIX.

**Comment by rrelyea** [comment] 2016-06-07 00:43
@zhili1208 , @simonejsing - sounds like this issue should be closed, right?

**Comment by zhili1208** [comment] 2016-06-07 17:40
Yes, I merged this PR.

**Closed as completed by zhili1208** 2016-06-07 17:40 UTC
Labels: Type:Bug, help wanted
