### ISSUE TITLE
nuget.exe should set $(SolutionDir)

### ISSUE THREAD

**Issue by johnkoerner** [NuGet/Home#4645] opened 2017-02-17 18:41 UTC
NuGet product used: nuget.exe

NuGet version : **3.5.0.1996**

VS version (if appropriate): **VS 2015 Update 3 is installed**

OS version: **Win 10 v1511 (10586.713)**

## Detailed repro steps so we can see the same problem

1. Have a csproj project in a solution that imports shared properties using the `$(SolutionDir)` variable

```
<Import Project="$(SolutionDir)\Shared.props" />
```

2. Run nuget update on the solution
```
nuget update .\NugetRestoreTestApp.sln NewtonSoft.Json
```

3. Receive the following error
```
Scanning for projects...
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Exception has been thrown by the target of an invocation.
  The imported project "D:\Shared.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\dev\temp\NugetRestoreTestApp\FolderA\FolderB\ClassLibrary1\ClassLibrary1.csproj
```
### Verbose Logs

```
NuGet Version: 3.5.0.1996
Scanning for projects...
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
System.AggregateException: One or more errors occurred. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "D:\Shared.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\dev\temp\NugetRestoreTestApp\FolderA\FolderB\ClassLibrary1\ClassLibrary1.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, String importExpressionEscaped, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NuGet.Common.MSBuildProjectSystem.GetProject(String projectFile)
   at NuGet.Common.MSBuildProjectSystem..ctor(String msbuildDirectory, String projectFullPath, INuGetProjectContext projectContext)
   at NuGet.CommandLine.UpdateCommand.GetMSBuildProject(String packageReferenceFilePath, INuGetProjectContext projectContext)
   at NuGet.CommandLine.UpdateCommand.GetProject(String path, INuGetProjectContext projectContext)
   at NuGet.CommandLine.UpdateCommand.<>c__DisplayClass40_0.<UpdateAllPackages>b__1(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.CommandLine.UpdateCommand.<UpdateAllPackages>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.UpdateCommand.<ExecuteCommandAsync>d__39.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "D:\Shared.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\dev\temp\NugetRestoreTestApp\FolderA\FolderB\ClassLibrary1\ClassLibrary1.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, String importExpressionEscaped, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at NuGet.Common.MSBuildProjectSystem.GetProject(String projectFile)
   at NuGet.Common.MSBuildProjectSystem..ctor(String msbuildDirectory, String projectFullPath, INuGetProjectContext projectContext)
   at NuGet.CommandLine.UpdateCommand.GetMSBuildProject(String packageReferenceFilePath, INuGetProjectContext projectContext)
   at NuGet.CommandLine.UpdateCommand.GetProject(String path, INuGetProjectContext projectContext)
   at NuGet.CommandLine.UpdateCommand.<>c__DisplayClass40_0.<UpdateAllPackages>b__1(String s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.CommandLine.UpdateCommand.<UpdateAllPackages>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.UpdateCommand.<ExecuteCommandAsync>d__39.MoveNext()<---
```

**Comment by emgarten** [comment] 2017-02-17 18:56
nuget.exe parses the solution itself and then loads the projects through msbuild. It looks like nuget.exe should set the SolutionDir property and pass it to msbuild when calling it.

**Comment by emgarten** [comment] 2017-11-09 18:42
This would be an easy fix that we would accept a PR for.

The solution directory needs to be passed to msbuild here: https://github.com/NuGet/NuGet.Client/blob/2aad8d25e66e9c3737b220631f3661bb6235d14b/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L110

**Comment by xen2** [comment] 2018-01-17 04:18
Ideally, $(SolutionName) should also be set.

**Comment by nkolev92** [comment] 2018-01-17 22:23
Duplicate of https://github.com/NuGet/Home/issues/5649, already fixed in https://github.com/NuGet/NuGet.Client/pull/1656

**Closed as completed by nkolev92** 2018-01-17 22:23 UTC
Labels: Resolution:Duplicate, Priority:3, Type:DCR, Product:NuGet.exe, help wanted
