### ISSUE TITLE
nuget pack doesn't ignore .git folder

### ISSUE THREAD

**Issue by oDn** [NuGet/Home#9646] opened 2020-06-04 08:57 UTC
## Details about Problem

NuGet product used : NuGet.exe

NuGet version : 5.5.1

OS version : Windows Server 2016 (14393.3686) and Windows 10 1709 (16299.904)

## Detailed repro steps so we can see the same problem

1. Clone a git repository containing files directly at the root

2. Use `nuget pack`

3. Notice that the _.git_ directory is included in the produced package

## Other details

The output of nuget.exe specifically mentions that folders starting with a dot will be ignored, so the .gitattributes file is properly ignored but the _.git_ directory is systematically included in the nupkg file.

**Comment by zkat** [comment] 2020-08-27 17:39
Closing as a duplicate of https://github.com/NuGet/Home/issues/8798, which is fixed. Please try it with the latest NuGet client and open a new issue if you can still repro this.

**Closed as completed by zkat** 2020-08-27 17:39 UTC
Labels: Priority:2, Type:Bug, Functionality:Pack
