### ISSUE TITLE
NuGet UI in VS displays the wrong available versions of nuget packages.

### ISSUE THREAD

**Issue by husainaloos** [NuGet/Home#5738] opened 2017-08-10 12:58 UTC
I am connecting my nuget in VS to artifactory, an internal nuget source, and disconnected it from nuget.org.

But suprisingly, the versions displayed for all the packages are from nuget.org, and not from artifactory. For example, log4net in artifactory does not have v2.0.8. But the VS UI displays v2.0.8.

I wonder if anyone else has the same problem.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

Using the Visual Studio UI for NuGet.

NuGet version (x.x.x.xxx):
[admin edited] Not relevant for this issue.

dotnet.exe --version (if appropriate):
1.0.4

VS version (if appropriate):
 VS 17. Version 15.2 (26430.16)

OS version (i.e. win10 v1607 (14393.321)):
win10 Version 1703 Build 15063.540

Worked before? If so, with which NuGet version:
No

## Detailed repro steps so we can see the same problem

1. Connect Nuget UI to a different NuGet source
2. Disconnect it from nuget.org
3. You will notice that the available versions of packages displayed do not necessarly represents the versions available in the new nuget source.

## Other suggested things
NA

### Verbose Logs
No logs since I am using the UI.

### Sample Project
Any project should suffice.

**Comment by nkolev92** [comment] 2017-08-10 20:56
@husainaloos 
Can you please share some information so we can understand your problem better. 

Can you post images of what you're articulating?
How are you disconnecting from nuget.org? Do you have the source disabled? 
Does the NuGet dialog refresh when once you have disabled/enabled a source.

Thank you.

**Comment by husainaloos** [comment] 2017-08-11 11:56
@nkolev92 Thank you for the response. And I am sorry I should have been clearer and should have posted some images.

This image shows that I am disabling nuget.org and only using artifactory (internal nuget server).
![image](https://user-images.githubusercontent.com/4754802/29211951-a991da26-7e61-11e7-9a11-eed40a0135b7.png)

Now notice that for log4net, nuget UI thinks that all these versions are available.
![image](https://user-images.githubusercontent.com/4754802/29211982-db895356-7e61-11e7-8810-555cb9af7fa2.png)

But in reality, artifactory only has two versions:
![image](https://user-images.githubusercontent.com/4754802/29212027-1872795a-7e62-11e7-9cb6-bc7386229c6c.png)

So there is a mismatch between what nuget UI thinks of the versions available, and what is actually available on the nuget server.

**Comment by PhilipDaniels** [comment] 2017-08-31 13:52
I believe you are experiencing exactly the issue I logged in Feb 2016 in issue #2138 It was noted as a Priority 1 bug but has not been actioned :-(

**Comment by nkolev92** [comment] 2017-09-05 17:13
@PatoBeltran Is this related to any of your UI work?

**Comment by nkolev92** [comment] 2017-09-05 22:19
@husainaloos Are you able to reproduce this consistently?

I played around a little bit and did not have any luck.

**Comment by husainaloos** [comment] 2017-09-08 20:38
@nkolev92 Yes. I am able to reproduce this consistently. What is the other package repository host do you use to test this?

**Comment by rrelyea** [comment] 2017-10-17 23:38
Dupe of https://github.com/NuGet/Home/issues/2138

**Closed as completed by rrelyea** 2017-10-17 23:38 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug
