### ISSUE TITLE
nuget pack fails if path has double backslash

### ISSUE THREAD

**Issue by chwarr** [NuGet/Home#4729] opened 2017-03-01 22:18 UTC
## Details about Problem

NuGet product used: nuget.exe

NuGet version: 3.5.0.1938 and 3.4.4.1321

OS version: Windows 10 Version 1607 (OS Build 15004.1000) amd64

Worked before? If so, with which NuGet version: unknown

## Detailed repro steps: double slash in non-glob pattern

1. Unzip the [sample project][sample-proj]
1. cd into the sample project directory
1. Run `nuget pack`

### Expected results

A package laid out with

```
build\native\foo.props
lib\native\sub-dir1\bar.txt
lib\native\sub-dir1\baz.txt
lib\native\sub-dir2\bar.txt
lib\native\sub-dir2\baz.txt
```

### Actual results

```
PS D:\temp\double-slash-bug > D:\chwarr\Downloads\nuget.exe pack -Verbosity detailed
NuGet Version: 3.5.0.1938
Attempting to build package from 'double-slash-bug.nuspec'.
System.IO.FileNotFoundException: File not found: 'build\\native\foo.props'.
   at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)
   at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
   at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvider)
   at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories)
   at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

## Detailed repro steps: double slash in glob patterns

1. Unzip the [sample project][sample-proj]
1. cd into the sample project directory
1. Edit the nuspec and remove the `<file src="build\\native\foo.props" target="build\native\" />` line
1. Run `nuget pack`

### Expected results

A package laid out with

```
lib\native\sub-dir1\bar.txt
lib\native\sub-dir1\baz.txt
lib\native\sub-dir2\bar.txt
lib\native\sub-dir2\baz.txt
```

### Actual results

A package laid out with

```
lib\native\sub-dir1\bar.txt
lib\native\sub-dir1\baz.txt
```

Here's the verbose logs:

```
PS D:\temp\double-slash-bug > D:\chwarr\Downloads\nuget.exe pack -Verbosity detailed
NuGet Version: 3.5.0.1938
Attempting to build package from 'double-slash-bug.nuspec'.

Id: double-slash-bug
Version: 1.0.0
Authors: chwarr@microsoft.com
Description: This package demonstrates various packing bugs when a path contains
      two slashes in a row. These sort of paths are common when
      pragmatically assembling paths.
Dependencies: None

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'double-slash-bug.nuspec'.
Added file 'lib/native/sub-dir1/bar.txt'.
Added file 'lib/native/sub-dir1/baz.txt'.
Added file 'package/services/metadata/core-properties/f2af38373753456990ab02686bc9694d.psmdcp'.

Successfully created package 'D:\temp\double-slash-bug\double-slash-bug.1.0.0.nupkg'.
```

## Inline nuspec file for easy reference

```
<?xml version="1.0"?>
<package >
  <metadata>
    <id>double-slash-bug</id>
    <version>1.0.0</version>
    <authors>chwarr@microsoft.com</authors>
    <description>
      This package demonstrates various packing bugs when a path contains
      two slashes in a row. These sort of paths are common when
      pragmatically assembling paths.
    </description>
  </metadata>
  <files>
    <!-- This line causes an error when running nuget pack: File not found:
         'build\\native\foo.props'. -->
    <file src="build\\native\foo.props" target="build\native\" />

    <!-- The following are different tests. However, you need to delete the
         line above to see what they do, otherwise nuget pack fails. -->

    <!-- This works as expected: the two files under sub-dir1 are included
         in the package. -->
    <file src="lib\\native\sub-dir1\*" target="lib\native\sub-dir1\" />
    <!-- This does not work as expected: nothing from sub-dir2 is included
         in the package. -->
    <file src="lib\native\sub-dir2\\*" target="lib\native\sub-dir2\" />
  </files>
</package>
```

## What about forward slashes?

They seem even more broken.

* `<file src="build/native/foo.props" target="build\native\" />` works.
* `<file src="build//native/foo.props" target="build\native\" />` fails.
* `<file src="lib//native/sub-dir1/*" target="lib\native\sub-dir1\" />` copies nothing.
* `<file src="lib/native//sub-dir1/*" target="lib\native\sub-dir1\" />` copies nothing.
* `<file src="lib/native/sub-dir1//*" target="lib\native\sub-dir1\" />` copies nothing.

## Sample Project

[double-slash-bug.zip][sample-proj]

[sample-proj]: https://github.com/NuGet/Home/files/812164/double-slash-bug.zip

**Comment by chwarr** [comment] 2017-04-25 23:14
Are any more details needed? I haven't heard anything in almost two months.

**Comment by zhili1208** [comment] 2017-04-25 23:39
I can repro this issue, looks like nuget don't handle double slash here @rohit21agrawal

**Comment by nkolev92** [comment] 2017-10-17 18:35
Duplicate of https://github.com/NuGet/Home/issues/3584

**Closed as completed by nkolev92** 2017-10-17 18:35 UTC
