### ISSUE TITLE
[DCR]: dotnet list package --outdated exit code

### ISSUE THREAD

**Issue by cosminstirbu** [NuGet/Home#11781] opened 2022-04-28 13:43 UTC
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

We'd like to check for outdated packages as part of our PR pipeline.

We would like to use `dotnet list package --outdated`, however there is no way to tell (without parsing the output), if there are any outdated packages.

Would it be possible to opt into returning a non-zero exit code if there are outdated packages, so we can then fail our pipeline / report on it?

### Desired Behavior

Have an additional argument to `dotnet list package --outdated` to have it return a non-zero exit code if there are outdated packages (e.g., then number of outdated packages)

### Additional Context

Original issue https://github.com/dotnet/sdk/issues/25091

We're currently using [dotnet-outdated/dotnet-outdated](https://github.com/dotnet-outdated/dotnet-outdated), however sometimes it is a hit or miss, because it fails to load the .sln.

**Comment by erdembayar** [comment] 2022-04-28 16:09
Related issues: 

- https://github.com/dotnet/sdk/issues/16852
- https://github.com/NuGet/Home/pull/11549#issuecomment-1094976531

> Have an additional argument to dotnet list package --outdated to have it return a non-zero exit code if there are outdated packages (e.g., then number of outdated packages)

I like the idea of additional argument so it wouldn't break existing users.

**Comment by nkolev92** [comment] 2022-05-05 18:40
Marking as duplicate of https://github.com/NuGet/Home/issues/11315.

**Closed as completed by nkolev92** 2022-05-05 18:40 UTC
Labels: Resolution:Duplicate, Type:DCR, Product:dotnet.exe, Functionality:ListPackage
