### ISSUE TITLE
New EnableCentralPackageVersions property breaks Microsoft.Build.CentralPackageVersions

### ISSUE THREAD

**Issue by dfederm** [NuGet/Home#9232] opened 2020-02-28 21:17 UTC
This change: https://github.com/NuGet/NuGet.Client/commit/08ded6ff38ec67e25c094d28e77cb23c15ee674b#diff-3b0018f61173d0adf1ba163a23821381 is causing incompatibility with [Microsoft.Build.CentralPackageVersions](https://github.com/microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions). Both use the `$(EnableCentralPackageVersions)` property and so conflict.

Specifically, this line in NuGet.targets:
```xml
    <EnableCentralPackageVersions Condition="'$(EnableCentralPackageVersions)' == ''">false</EnableCentralPackageVersions>
```

This disables the feature in the `Microsoft.Build.CentralPackageVersions` SDK.

**Comment by dfederm** [comment] 2020-02-28 21:18
FYI @cristinamanum @jeffkl @AndyGerlicher

**Comment by rrelyea** [comment] 2020-03-04 22:33
fyi: @zivkan @aortiz-msft

**Comment by cristinamanum** [comment] 2020-03-05 16:35
Duplicate of https://github.com/NuGet/Home/issues/9235

**Closed as completed by cristinamanum** 2020-03-05 16:35 UTC
Labels: Type:Bug
