### ISSUE TITLE
Removing a package with lots of files takes ages 

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1284] opened 2015-08-28 22:58 UTC
@brgrz

We have an internal Nuget package about 3 MB in size, containing one ASP.NET MVC site area. The package holds about 600 files (mostly small, for instance CKEditor buid) in some 300 folders. 

When initiating package update from within VS, NuGet starts to remove the old version and it is this step that takes "forever" (about 10-15 minutes on a modern highend machine with SSD drive).

Once the package is removed the new version is installed pretty quickly (but still much slower than unzipping it manually).

What does the NuGet team need from me to debug this?

This issue was moved from https://github.com/NuGet/NuGet.CommandLine/issues/6

**Comment by yishaigalatzer** [comment] 2015-08-31 16:46
My guess is that these are calls to Visual Studio DTE that is making it slow.
A compounding factor would be if the files are checked in under source control, particularly TFS.

Can you confirm?

**Comment by brgrz** [comment] 2015-09-04 14:20
The files are placed under DCVS but we use Mercurial (Hg), not TFS.

**Comment by LinuxDoku** [comment] 2015-09-16 08:12
We have the same issue with projects which are under TFS source control, but the Sysinternals Process Explorer shows no network activity (even when you go offline it is very slow) while removal.

Our package has 12mb (35mb extracted) with 700 hundred files and 160 folders and it takes up to 5 hours to remove it. A few weeks ago removing the same package took 1 minute with ssd and up to 5 minutes on a hdd.

We have multiple machines with VS 2013 and a few with VS 2015. Nuget is the version 2.8.6 and with the new visual studio we have 3.1.6.

**Comment by yishaigalatzer** [comment] 2015-09-16 13:48
So to confirm, 2013 is much faster than 2015?

**Comment by LinuxDoku** [comment] 2015-09-17 08:23
No, they are both slow.

Machines we have tested:
Intel Core i5 with 2 Cores, 8GB RAM, SSD, Windows 7 and VS 2013 with Update 5 (Nuget 2.8.6)
Intel XEON with 8 Cores, 16GB RAM, SSD, Windows 7 and VS 2013 with Update 5 (Nuget 2.8.6), VS 2015 (Nuget 3.1.6)

We have uninstalled the virus scanner (ESET) on both machines the have a clear picture of the performance issue. This makes the process a bit faster, but not acceptable. It takes hours.

When we moved the solution out of the tfs workspace and uninstall the package without any binding to the tfs it is faster but also takes nearly an hour. A few weeks before this took only up to 5 minutes.

The package is exactly the same, even old versions of our nuget package are slow to install and uninstall. What i noticed while testing is, the performance impact on the machine. On the i5 devenv.exe takes 100% load. On my XEON with 8 Cores it only takes 12 to 15% load.

Can I provide you further informations or a log file?

**Comment by yishaigalatzer** [comment] 2015-09-17 16:15
Thanks for sharing all this info

Can you tell me what the difference is between a “few weeks ago” and “today”?
Are you using a different version of visual studio? A different version of NuGet?

We should probably start looking into this right away, but many a times it is a bit hard to pinpoint the differences without a good before/after setup.

**Comment by yishaigalatzer** [comment] 2015-09-17 20:47
One thing I forgot is to try 3.2, there are some improvements with 3.2 for this. Not guaranteeing its going to fix your issue or not, just been talking to @pranavkm in passing and he thought this should be improved. @zhili1208 is going to do more investigation on this.

**Comment by zhili1208** [comment] 2015-09-17 20:59
@LinuxDoku what's your package? is it in nuget.org? I want to do some investigation on it. thanks

**Comment by LinuxDoku** [comment] 2015-09-17 21:18
@zhili1208 it's a internal package containing an ASP.NET app with a lot of html and javascript. If you can provide me an microsoft.com mail adress, I could sent you a package with some mixed up binaries.

@yishaigalatzer Tomorrow I will test 3.2 on our machines. We also have some workstations with Visual Studio 2013 Express Update 3, maybe they are performing better. I will test and report.

A few weeks ago means the upgrade process which our developers do every day took only a few minutes and since this week they are complaining that they cannot update in under an hour. Maybe visual studio 2013 update 5 or the latest updates of vs 2015 are the root of the problem, but I will trace this tomorrow.

**Comment by zhili1208** [comment] 2015-09-17 21:23
@LinuxDoku thanks, lzhi@microsoft.com

**Comment by LinuxDoku** [comment] 2015-09-18 08:07
Today I have tested a bit. Same package as before - 700 files and 180 folders (35mb unpacked).

Fresh installed Machine with Windows 10, VS 2015 and Nuget 3.1 and no source control integration:
Install: 5 minutes
Uninstall: 8 minutes

Same machine with upgrade to Nuget 3.2:
Install: 30 seconds
Uninstall: 1 minute

Works fine with nuget 3.2!

---

Machine with Windows 7, VS 2013 and VS 2015 installed and no source control using VS 2015 with Nuget 3.2:
Install: 3 minutes
Uninstall: 5 minutes

Same machine with tfs integration using vs 2015 (created a folder insde a team collection and a new solution):
Install: 40 minutes
Uninstall: don't know, it's still running...

The TFS throws a lot of errors: "TF204018: Could not check the file's encoding because the file XXX is in use.". Maybe this is a lock problem with TFS and nuget. I would have switched it to offline mode, but it seems like this feature was dropped in VS2015. When I disconnect my network to simulate "offline" visual studio crashes (I copied the nuget repo to a local disk before ;-)).

I will have a look at our tfs configuration and play with some settings. Seems like the big package performance issue is fixed and our problem is the TFS. Thanks for your help so far!

**Comment by zhili1208** [comment] 2015-10-02 18:48
it's fixed in 3.2, close this bug

**Comment by stewart-r** [comment] 2016-03-10 10:55
I am seeing a similar issue with version 3.3.0.167 - very slow to install and TF204018 errors (for every file?) appearing in the output window from Package Manager.

Symptoms exactly the same as reported above. Is it possible that this bug has been re-introduced? 

Package in question is CKEditor. It's been installing for around 45 mins so far

**Comment by yishaigalatzer** [comment] 2016-03-10 16:00
I made some fixes in this area in 3.4, I can try later today but you can also grab it from our download link on nuget.org. if it still repros for you, please open a new item and link to this one.

Last (not a copout, we will address this) consider using git as there are lots of advantages in speed of local operations (no need to go online and check out a file)

**Comment by zhili1208** [comment] 2016-03-10 21:10
I got repro, reopen it

**Comment by yishaigalatzer** [comment] 2016-03-10 21:14
Can we fix today and add a test

**Comment by LinuxDoku** [comment] 2016-03-10 21:19
We are also still having this bug. At the moment we update the packages at night, to be able to work at days.

Switching to another VCS is not possible at the moment for our teams. Before doing this we would evaluate another way to package our stuff and deliver to the devs.

**Comment by zhili1208** [comment] 2016-03-10 21:23
I'm still investigating it, not sure can we fix this today

**Comment by yishaigalatzer** [comment] 2016-03-10 21:34
Let me know how it goes and ask for help from another dev to speed it up (if that helps)

**Comment by zhili1208** [comment] 2016-03-11 00:39
the problem is we add content files to TFS twice, looks like when solution is bound to TFS, adding files to project will add those files to TFS automatically, we add those content files to TFS and then VS add them again during adding files to project. I just not add content files to TFS from nuget, it works well and all files are added by VS automatically

**Comment by yishaigalatzer** [comment] 2016-03-11 00:40
Does this work in all scenarios?

**Comment by zhili1208** [comment] 2016-03-11 01:24
tested most of scenarios, install works well, but uninstall still be very slow, we didn't call TFS for uninstall, we just call dte to delete project item then it will be deleted from TFS automatically, but when bounding to TFS, project item delete is really slow, I'm trying to make it faster

**Comment by deepakaravindr** [comment] 2016-03-11 02:15
Perhaps, we should batch process project file operations?

Is this not used in this scenario? Just curious https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectManagement/Utility/MSBuildNuGetProjectSystemUtility.cs#L187

**Comment by zhili1208** [comment] 2016-03-11 02:31
it's used in this scenario, but only one dte project item delete operation almost takes 3-5 second

**Comment by brgrz** [comment] 2016-03-11 08:29
Just a note, this is not isolated to TFS, I happen to be using Mercurial with most projects and experience the same 'slowness'

**Comment by yishaigalatzer** [comment] 2016-03-11 08:37
The fix is not related to tfs either so that's good news.

We are still investigating removal, that seems to be expensive but currently looks like out of our control. Will work with the owners in visual studio to get to a better place

**Comment by yishaigalatzer** [comment] 2016-03-16 01:51
@zhili1208 why is this thing not in the dev branch?

**Comment by zhili1208** [comment] 2016-03-16 04:04
@yishaigalatzer will grab Deepak to sign off the PR then Check into dev soon

**Closed as completed** 2016-03-17 17:52 UTC
Labels: Priority:2, Type:Bug, Tenet:Performance
