### ISSUE TITLE
Provide cross platform API for downloading

### ISSUE THREAD

**Issue by KathleenDollard** [NuGet/Home#6629] opened 2018-03-01 17:41 UTC
NuGet.exe (Core)

`dotnet install tool` is using a temp project to download packages from NuGet because there isn't a .NET Core client that can do this. 

We have found it difficult to hide this detail (hack) within the user experience (see https://github.com/dotnet/cli/issues/8707 for example). 

It would be great to remove the temporary project in the near-ish future (sometime after 2.1.300) and explicitly download the required packages.

**Comment by nkolev92** [comment] 2018-03-01 19:28
Duplicate of https://github.com/NuGet/Home/issues/5919. 
It got de-prioritized at some point. 

Compatibility checking would be a challenge here. 
Not going to be straightforward to make the proj go away. 

Now that I understand the background better, I'll look into https://github.com/NuGet/Home/issues/6630  to clean it up.

**Closed as completed by nkolev92** 2018-03-01 19:28 UTC
Labels: Resolution:Duplicate, Type:Feature, Platform:Xplat
