### ISSUE TITLE
Dependencies inside of nuspec do not float to highest version

### ISSUE THREAD

**Issue by charris123** [NuGet/Home#6015] opened 2017-10-11 14:15 UTC
Attached is a simple nuspec file with the following dependency
<dependency id="Newtonsoft.Json" version="10.0.*" />

When installing this package using package reference format, Nuget chooses the lowest version of Newtonsoft (10.0.1) instead of the highest floating version (10.0.3).  When installing this using packages.config, Nuget chooses the highest version (10.0.3).  

Package Manager Console Host Version 4.3.1.4445
NuGet Version: 4.3.0.4406
VS Version 15.3.5
OS win 10.0.14393 Build 14393

Steps to reproduce:

Create a new .NET Framework classlibrary project in VS
Add a local directory that contains the attached NoFloat.1.2.2.nupkg as a package source
Choose PackageReference as the default package management format

Add a reference to NoFloat.1.2.2 choosing Dependency behavior Highest
As of 10/11/2017 the Highest version of Newtonsoft.Json is 10.0.3

Expected behavior
Nuget installs  Newtonsoft.Json 10.0.3
Actual behavior
Nuget installs  Newtonsoft.Json 10.0.1

If you choose Packages.config as the Default package management format, Nuget installs  Newtonsoft.Json 10.0.3

[verbose.log](https://github.com/NuGet/Home/files/1375869/verbose.log)
[nofloat.zip](https://github.com/NuGet/Home/files/1375876/nofloat.zip)

**Comment by emgarten** [comment] 2017-11-09 19:57
Duplicate of https://github.com/NuGet/Home/issues/5553

**Closed as completed by emgarten** 2017-11-09 19:57 UTC
Labels: Resolution:Duplicate
