### ISSUE TITLE
Better error handling for the nomination API

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3870] opened 2016-11-03 19:03 UTC
.NET Core .csproj file may contain various types of syntax and logical errors detectable by NuGet especially when a file was edited manually. In this case the nomination API will fail creating the project restore info and as a result triggering a restore operation.

Among properties where error values are possible:
`PrivateAssets`, `IncludeAssets`, `ExcludeAssets`, `Version`, some others.

### Proposal

Analyze the input, collect all errors information and throw an exception with explanatory message. 
Alternatively, consider different channel to deliver error info to the end user, e.g. assets file where the rest of restore errors would land.

Internal bugs: 378897, 378902

**Comment by nkolev92** [comment] 2019-10-26 01:35
Closing as duplicate of https://github.com/NuGet/Home/issues/7717. 

This is technically the older one, but the newer has more engagement (albeit all internal).

**Closed as completed by nkolev92** 2019-10-26 01:35 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Priority:2, Type:Feature, Platform:Xplat, Area:ErrorHandling, Functionality:Restore, Style:PackageReference
