### ISSUE TITLE
VS package install does not respect version constraints of installed package

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5756] opened 2017-08-14 22:24 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):  VS UI

NuGet version (x.x.x.xxx): 4.3.0.4339

VS version (if appropriate): 15.3.0 and 15.4 Preview1

## Detailed repro steps so we can see the same problem

•	Create a new netstandard class library project or a package reference net461 class library project.
•	Install the package Microsoft.Data.OData, version is 5.8.1
•	Note that it has a max version on the dependency Microsoft.Data.Edm (= 5.8.1)
•	Install Microsoft.Data.Edm 5.8.2.
•	Expected behavior: install is refused. Actual behavior: nuget installs the package.

Try the same steps on a packages.config net461 class library project, and Microsoft.Data.OData is also updated to version 5.8.2.

**Comment by emgarten** [comment] 2017-08-14 23:05
Dupe of https://github.com/NuGet/Home/issues/2358

**Comment by rrelyea** [comment] 2017-08-17 23:39
Met with Azure Functions team about this issue via Skype today. Will consider issue as part of next sprint planning.

**Closed as completed** 2017-08-23 04:17 UTC
Labels: Priority:1, Resolution:Duplicate, Product:VS.Client, Functionality:Install, Triage:NeedsTriageDiscussion, Style:PackageReference
