### ISSUE TITLE
Command line option to list out of date packages

### ISSUE THREAD

**Issue by mike-ward** [NuGet/Home#1634] opened 2015-10-26 13:35 UTC
Maybe I'm being stupid, but I can't seem to find a command line option to show which packages are out of date in a solution. I know I can do this in the IDE.

My preferred way to do this would be

```
nuget check
```

Another option would be

```
nuget update --dry-run
```

.

**Comment by yishaigalatzer** [comment] 2015-10-26 17:54
We would probably go with some sort of `nuget update`

**Comment by davidvedvick** [comment] 2017-12-28 13:29
I don't think this is stupid - this would be very useful in a CI environment.

**Comment by DanWallaceAdslot** [comment] 2018-02-02 01:27
This would be a great addition to CI environments. Something like nuget update --outdated would be perfect

**Comment by anangaur** [comment] 2018-06-04 21:25
Closing this as duplicate of https://github.com/NuGet/Home/issues/5762 where more discussions have taken place.

**Closed as completed by anangaur** 2018-06-04 21:25 UTC
Labels: Resolution:Duplicate, Priority:3, Type:Feature, Product:NuGet.exe
