### ISSUE TITLE
Error occurred while restoring Nuget Packages: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#3767] opened 2016-10-25 19:28 UTC
![image](https://cloud.githubusercontent.com/assets/12449387/19701007/6e301afc-9aae-11e6-821a-94953cf0701c.png)

**Comment by jinujoseph** [comment] 2016-10-25 19:29
@rrelyea, creating this for tracking purpose.

**Comment by rrelyea** [comment] 2016-10-25 21:14
this was fixed by @jainaashish  - find the right issue to dupe too.

**Comment by rrelyea** [comment] 2016-10-25 23:20
Dupe of #3724  - had to do with no Guid in the .csproj. Fixed in Dev. Will be checked in mega-insertion.

**Closed as completed by rrelyea** 2016-10-25 23:20 UTC

**Comment by kwaazaar** [comment] 2017-10-12 10:12
Getting this error now on VS 2017, patch 15.4 on a project that was created using dotnet new webapi. Nuget worked for a while and now gives this error. It keeps doing so after restarting VS.

**Comment by kwaclaw** [comment] 2017-10-13 19:58
Same here, with VS 2017, patch 15.4.

**Comment by waghpravin14** [comment] 2017-10-16 04:25
Same error me too with VS2017 15.4. Could someone please update.

**Comment by waghpravin14** [comment] 2017-10-16 05:56
Track this issue @ https://github.com/NuGet/Home/issues/6020

**Comment by patroza** [comment] 2017-11-05 11:38
What a PITA, the whole nuget process is a mess recently. Especially solutions that mix csproj of .NET Framework, .NET Standard and  .NET Core. And now this..

**Comment by ghost** [comment] 2017-11-11 23:19
Still actual... Please reopen!

**Comment by sayfulloev** [comment] 2017-11-16 15:33
~Having this with VS 2017 15.4.3~ Update to VS 15.4.4 which has the fix 
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes https://developercommunity.visualstudio.com/content/problem/128974/error-occured-while-restoring-nuget-packages-1.html

**Comment by OsirisTerje** [comment] 2017-11-24 12:30
Got the same now,  also see this: 
"Error: Assets file 'myproject\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.",  This happens even after having done a restore.  	
Happens in C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	323	

Restoring reports all is fine:
Restoring NuGet packages...
All packages are already installed and there is nothing to restore.

Except that it also gives this 
Error occurred while restoring NuGet packages: The given key was not present in the dictionary.
which comes after it has said it has finished.......

Some screenshots:
![image](https://user-images.githubusercontent.com/203432/33210601-373dff9c-d11b-11e7-94fd-3d1fbeeed636.png)

![image](https://user-images.githubusercontent.com/203432/33210679-755eea70-d11b-11e7-80bc-322d7bbd3e2d.png)

**Comment by AmiNadimi** [comment] 2018-02-09 06:32
I had the same problem and updating VS 2017 solved it.
