### ISSUE TITLE
Provide option to upload packages for verification and be staged but unpublished.

### ISSUE THREAD

**Issue by mbranscomb** [NuGet/Home#8556] opened 2019-09-06 00:32 UTC
## Details

We would like to be able to upload packages to NuGet.org for signature validation / virus scanning / verification but such that they could be deleted if necessary before publishing and listing. Effectively we would like to stage the NuGet packages ready for release but know that we could take them down if any last minute showstopper issues were discovered.

We want to do this because we have a coordinated release of multiple products across different platforms and wherever possible we want these all to go live within the same time window. 

The proposed workflow would be:
1. Upload/push updated packages
2. Signature validation, virus scanning, verification
3. Stage (but can delete at this point)
4. Publish (with option not to list)
5. List (publicly visible)

**Comment by nkolev92** [comment] 2020-01-16 20:47
Thanks for creating this issue. 

This issue is better suited for the NuGetGallery. 

Duplicate of https://github.com/NuGet/NuGetGallery/issues/3931.

**Closed as completed by nkolev92** 2020-01-16 20:47 UTC
Labels: Resolution:Duplicate, Type:Feature
