### ISSUE TITLE
NuGet needs to let users know that upgrading/installing in a dotnet tfm based PCL could cause issues

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#3138] opened 2016-07-15 00:15 UTC
1)  The NuGet team will be a check in place to detect the use of the dotnet TFM during Install and Update. We will show a warning dialog that will point users to a document that will be authored by the .NET Core team that will lay out the steps required to move to .NET Standard. We will not prevent the update/install if the user needs to but we will make clear that this could cause issues. This change will be made to the 3.5 RTM release and will ship on ~ 8/2

**Comment by rrelyea** [comment] 2016-07-15 16:50
dupe of #3137

**Closed as completed by rrelyea** 2016-07-15 16:50 UTC
Labels: Type:DCR
