### ISSUE TITLE
Feature: Clickable URL to NuGet.org package details page

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1772] opened 2015-11-25 14:49 UTC
For packages that are displayed from NuGet.org or some other repository that provides package details pages, show that URL as a clickable link in the package details

**Comment by yishaigalatzer** [comment] 2016-01-12 19:25
Duplicate of https://github.com/NuGet/Home/issues/1823

**Closed as completed by yishaigalatzer** 2016-01-12 19:25 UTC
Labels: Type:DCR, Functionality:VisualStudioUI
