### ISSUE TITLE
Retrieve only listed versions of a package

### ISSUE THREAD

**Issue by AndyButland** [NuGet/Home#12370] opened 2023-01-18 09:09 UTC
### NuGet Product(s) Involved

NuGet SDK

### The Elevator Pitch

I might be missing something here, but it doesn't seem that I can use the SDK to retrieve only listed versions of a package.

Using `FindPackageByIdResource.GetAllVersionsAsync` you can retrieve all versions of a package, which includes listed and unlisted versions.

That would be OK if there was a property on the returned list of `NuGetVersion` objects, that could be used to determine if the version is listed.  For example there's an `IsPrerelease` that can be used to determine which versions are pre-releases, and filter on that if you needed to.  However I don't see anything that can be used to distinguish listed and unlisted versions.

**Comment by aortiz-msft** [comment] 2023-01-30 21:31
Triage: Thanks for the suggestion. Please take a look at https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk#get-package-metadata for an example on how to do this.

**Comment by AndyButland** [comment] 2023-01-31 05:27
Thanks for checking @aortiz-msft - but what you've linked to isn't quite what I asked about.  You've shown how to get a list of packages, which does have an option for retrieving listed only or all packages.

However I'm asking about getting versions of a package (and similarly being able to filter to only get listed versions).  I'm using this code: https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk#list-package-versions

And as far as I can see that doesn't have a similar `includeUnlisted` parameter.

**Comment by zivkan** [comment] 2023-01-31 12:59
@AndyButland from one Andy to another, NuGet.Protocol has a slightly unusual design I don't fully understand. But there's a chance it was designed back in NuGet 1.0 days, when there was only an OData server API, which is radically different to now. Maybe it feels weird because some of the "resources" map neatly to V3 HTTP API endpoints, so the ones that don't feel out of place, rather than understanding their historical context.

In this case, the `FindPackageByIdResource` is a strangely named "wrapper" for what [the Server API](https://learn.microsoft.com/en-us/nuget/api/overview) calls the [Package Content resource](https://learn.microsoft.com/en-us/nuget/api/package-base-address-resource) (well, when using a V3 HTTP feed. V2 feeds compose a suitable OData query, which I don't know much about). As we can see in [the sample response](https://learn.microsoft.com/en-us/nuget/api/package-base-address-resource#sample-response), there is no listed/unlisted metadata. This json file was designed to optimize restore performance, where by design it ignores listed/unlisted status, so as not to break existing projects using a specific package version when the owner unlists the package. My biggest gripe is that the name `FindPackageByIdResource` doesn't make any of this clear. "Find package by id" sounds generic, like an abstraction as a layer that sits above the "raw" HTTP json responses.

However, what the NuGet Server API calls the [Package Metadata resource](https://learn.microsoft.com/en-us/nuget/api/registration-base-url-resource) has unlisted metadata in the result, as well as a parameter to say if you want unlisted versions returned. This time NuGet.Client's name for the resource is the same as the server API, [PackageMetadataResource](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/PackageMetadataResource.cs#L11).

untested code:
```csharp
SourceRepository source = GetSource(); // however you set this up
var packageMetadataResource = await source.GetResourceAsync<PackageMetadataResource>(cancellationToken);
var packageMetadata = packageMetadataResource.GetMetadataAsync(packageId,
    includePrerelease: true,
    includeUnlisted: false,
    sourceCacheContext,
    logger,
    cancellationToken);

// or if includeUnlisted: true is used above
foreach (var package in packageMetadata)
{
    var listed = packageMetadata.IsListed;
}
```

**Comment by AndyButland** [comment] 2023-01-31 13:33
Thanks @zivkan for the suggestion and useful background.  Isn't what you've provided though similar to the sample that @aortiz-msft linked above?  If so, it's not quite what I was after.

What you have provided will as you say allow the retrieval of listed or unlisted packages.

But I was looking to be able to get listed or unlisted _versions_ of a listed package.

For example [this one](https://www.nuget.org/packages/Vokseverk.KeyValueEditor) has two listed versions.  But it also has [two](https://www.nuget.org/packages/Vokseverk.KeyValueEditor/3.0.0) [unlisted](https://www.nuget.org/packages/Vokseverk.KeyValueEditor/3.0.1) versions too.

I'm looking for an API call that will get me all listed versions of the package, but the [one I'm using](https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk#list-package-versions) will get listed and unlisted (as you explained above).  And there's no `IsListed` property to filter them after I've retrieved them from the API.

**Comment by zivkan** [comment] 2023-01-31 13:36
A package ID can't be wholly listed or unlisted, only specific versions. If every version of a package ID is unlisted, then that package will no longer be discoverable via the search service, but it will continue to work with the package metadata endpoint.

**Comment by nkolev92** [comment] 2023-02-01 02:08
> What you have provided will as you say allow the retrieval of listed or unlisted packages.

@AndyButland That's not really true. If you test Andy's code you'll see that it returns both, and it's exactly what was provided in the original closing comment. 

Taking the code from: https://learn.microsoft.com/en-us/nuget/reference/nuget-client-sdk#get-package-metadata and plugging in your parameters (wanting unlisted and your specific package id). 

```cs
// See https://aka.ms/new-console-template for more information
using NuGet.Common;
using NuGet.Protocol;
using NuGet.Protocol.Core.Types;

ILogger logger = NullLogger.Instance;
CancellationToken cancellationToken = CancellationToken.None;

SourceCacheContext cache = new SourceCacheContext();
SourceRepository repository = Repository.Factory.GetCoreV3("https://api.nuget.org/v3/index.json");
PackageMetadataResource resource = await repository.GetResourceAsync<PackageMetadataResource>();

IEnumerable<IPackageSearchMetadata> packages = await resource.GetMetadataAsync(
    "Vokseverk.KeyValueEditor",
    includePrerelease: true,
    includeUnlisted: true,
    cache,
    logger,
    cancellationToken);

foreach (IPackageSearchMetadata package in packages)
{
    Console.WriteLine($"Version: {package.Identity.Version}");
    Console.WriteLine($"Listed: {package.IsListed}");
}
```

The output is 

```console
Version: 3.0.0
Listed: False
Version: 3.0.1
Listed: False
Version: 3.0.2
Listed: True
Version: 3.0.3
Listed: True
```

which is exactly what you want.

**Closed as completed** 2023-02-01 02:09 UTC
Labels: Functionality:SDK, Type:Feature, Resolution:Question, Area:Versioning

**Comment by AndyButland** [comment] 2023-02-01 05:36
Ah, I've got you finally... and sorry for wasting your time.  I've been working with the same resource and the `GetMetadataAsync` method - but the one that returns `IPackageSearchMetadata`.  I'd missed that there was an overload that returns `IEnumerable<IPackageSearchMetadata>` and gives the versions.  Thanks again for your help.

**Comment by WeihanLi** [comment] 2024-06-23 00:45
The metadata API would not more info than versions, considering for performance, is it possible to support a parameter like `excludeUnlistedPackages` for the `GetAllVersions` API?
