### ISSUE TITLE
[Bug]: `dotnet add "x.csproj" package y` adds NuGet package instead of updating existing `<PackageReference>`

### ISSUE THREAD

**Issue by Saibamen** [NuGet/Home#11792] opened 2022-05-04 23:49 UTC
### NuGet Product Used

dotnet.exe

### Product Version

6.0.202

### Worked before?

Don't know

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Moved from https://github.com/dotnet/sdk/issues/25209

### Describe the bug
`dotnet add "your.csproj" package SimpleInjector.Packaging` command does not update `<PackageReference><Version></Version></PackageReference>` template:

![image](https://user-images.githubusercontent.com/905878/166697188-755190a6-a5eb-4675-861f-7d278c8dab57.png)

But `dotnet remove "your.csproj" package SimpleInjector.Packaging` works with both templates:

![image](https://user-images.githubusercontent.com/905878/166697574-2f548167-c48b-44ef-9887-76b38fd5c4fa.png)

It also doesn't update NuGet packages for "new" template. See https://github.com/dotnet/sdk/issues/25209#issuecomment-1117613201
![image](https://user-images.githubusercontent.com/905878/166819341-65dc60f0-4a10-4a28-9866-60409650af98.png)

### To Reproduce

1. Your `csproj` file must contain this:
```
<PackageReference Include="SimpleInjector.Packaging">
  <Version>4.10.2</Version>
</PackageReference>
```
2. Run `dotnet add "your.csproj" package SimpleInjector.Packaging`

### Further technical details
- Include the output of `dotnet --info`:
```
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Srodowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: **CLI**

### Verbose Logs

There is no `--verbosity` option for `dotnet add package`...

Here is standard output:

Running command first time (with deleted `bin` and `obj` folders):
```shell
dotnet add "bbb.csproj" package SimpleInjector.Packaging
  Trwa okreslanie projektów do przywrócenia...
  Writing C:\Users\Adam\AppData\Local\Temp\tmp8AB8.tmp
info : Dodawanie elementu PackageReference dla pakietu ,SimpleInjector.Packaging" do projektu ,bbb.csproj".
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/simpleinjector.packaging/index.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/simpleinjector.packaging/page/1.4.2.12140/3.1.2.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/simpleinjector.packaging/page/3.1.3/4.8.0-alpha1.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/simpleinjector.packaging/page/4.8.0-alpha2/5.0.0.json
info : Trwa przywracanie pakietów dla elementu C:\xxx\yyy\Source\Client\Client-Addons\bbb\bbb.csproj...
info : Pakiet ,SimpleInjector.Packaging" jest zgodny ze wszystkimi strukturami okreslonymi w projekcie ,bbb.csproj".
info : Element PackageReference dla pakietu ,SimpleInjector.Packaging" w wersji ,5.0.0" zostal dodany do pliku ,C:\xxx\yyy\Source\Client\Client-Addons\bbb\bbb.csproj".
info : Generowanie pliku programu MSBuild C:\xxx\yyy\Source\Client\Client-Addons\bbb\obj\bbb.csproj.nuget.g.props.
info : Generowanie pliku programu MSBuild C:\xxx\yyy\Source\Client\Client-Addons\bbb\obj\bbb.csproj.nuget.g.targets.
info : Zapisywanie pliku zasobów na dysk. Sciezka: C:\xxx\yyy\Source\Client\Client-Addons\bbb\obj\project.assets.json
log  : Przywrócono element C:\xxx\yyy\Source\Client\Client-Addons\bbb\bbb.csproj (w 314 ms).
```

Running second time:
```shell
dotnet add "bbb.csproj" package SimpleInjector.Packaging
  Trwa okreslanie projektów do przywrócenia...
  Writing C:\Users\Adam\AppData\Local\Temp\tmpBD1E.tmp
info : Dodawanie elementu PackageReference dla pakietu ,SimpleInjector.Packaging" do projektu ,bbb.csproj".
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/simpleinjector.packaging/index.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/simpleinjector.packaging/page/1.4.2.12140/3.1.2.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/simpleinjector.packaging/page/3.1.3/4.8.0-alpha1.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/simpleinjector.packaging/page/4.8.0-alpha2/5.0.0.json
info : Trwa przywracanie pakietów dla elementu C:\xxx\yyy\Source\Client\Client-Addons\bbb\bbb.csproj...
info : Pakiet ,SimpleInjector.Packaging" jest zgodny ze wszystkimi strukturami okreslonymi w projekcie ,bbb.csproj".
info : Element PackageReference dla pakietu ,SimpleInjector.Packaging" w wersji ,5.0.0" zostal dodany do pliku ,C:\xxx\yyy\Source\Client\Client-Addons\bbb\bbb.csproj".
info : Plik zasobów nie ulegl zmianie. Zapisywanie pliku zasobów jest pomijane. Sciezka: C:\xxx\yyy\Source\Client\Client-Addons\bbb\obj\project.assets.json
log  : Przywrócono element C:\xxx\yyy\Source\Client\Client-Addons\bbb\bbb.csproj (w 133 ms).
```

**Comment by martinrrm** [comment] 2022-05-09 05:49
Hi! I can repro that the template is not being updated, but I see in your images that there is a `<PackageReference>` tag created. For me the version from the existing `PackageReference` is updated and doesn't create a new one, is that something you are experiencing or was just for showing the differnce?

**Comment by Saibamen** [comment] 2022-05-09 13:06
> is that something you are experiencing

Yes, I'm experiencing this. From documentation (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package), `dotnet add package` should ` Adds or updates a package reference in a project file`, but for me (you can see it in my screenshots) - it adds new line into csproj without deleting already existing one package from csproj, so I can't commit this file into git repo, because it is wrong.

I need to execute two commands before pushing my changes (instead of one):

1. `dotnet remove package`
2. `dotnet add package`

**Comment by heng-liu** [comment] 2022-05-23 21:16
Hi @Saibamen , I tried to repro with the following steps but it worked correctly. Could help check if the following works for you? Or if there is anything different from your repro steps? Thanks!

1.Install dotnet sdk version 6.0.202 with nopath and set `DOTNET_MULTILEVEL_LOOKUP` to 0, to make sure the 6.0.202 is used for repro.
```
C:\repos\NuGet.Client\cli\dotnet-install.ps1 -InstallDir "C:\test\" -Version 6.0.202 -Nopath
$env:DOTNET_MULTILEVEL_LOOKUP=0
```
2.Create a new classlib Test11792
`C:\test\dotnet.exe new classlib -n Test11792`

3.Add package SimpleInjector.Packaging of version 4.10.2 to Test11792
`C:\test\dotnet.exe add .\Test11792.csproj package SimpleInjector.Packaging --version 4.10.2`

4.Check the Test11792.csproj file and the content is as following
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SimpleInjector.Packaging" Version="4.10.2" />
  </ItemGroup>

</Project>
```
5.Add package SimpleInjector.Packaging of version (default latest version 5.0.0)  to Test11792
`C:\test\dotnet.exe add .\Test11792.csproj package SimpleInjector.Packaging`

6.Check the Test11792.csproj file and the content is as following:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SimpleInjector.Packaging" Version="5.0.0" />
  </ItemGroup>

</Project>
```

I also tried to change the csproj file in step4, into the following:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SimpleInjector.Packaging">
      <Version>4.10.2</Version>
    </PackageReference>
  </ItemGroup>

</Project>
```
But it also worked correctly:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SimpleInjector.Packaging">
      <Version>5.0.0</Version>
    </PackageReference>
  </ItemGroup>

</Project>
```

**Comment by Saibamen** [comment] 2022-05-23 23:53
@heng-liu:

Where I can download `dotnet-install.ps1`?

I see the differences now:

For new `csproj` (SDK-style) template (`<Project Sdk="Microsoft.NET.Sdk">`) it works as expected -> update existing `<PackageReference>`.

But for old `csproj` template (`<?xml version="1.0" encoding="utf-8"?><Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`) it adds new line next to already existing `SimpleInjector.Packaging`.

Tested on dotnet `6.0.300`

`csproj` file for testing:

```csproj
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SimpleInjector.Packaging" Version="5.0.0" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by heng-liu** [comment] 2022-05-24 00:58
Thanks @Saibamen ! I could repro for non-SDK style project.
>Where I can download dotnet-install.ps1?

You don't have to do step1 :) I added this step just to use the same dotnet version with you

**Comment by heng-liu** [comment] 2022-05-24 01:01
1.If run `add  package SimpleInjector.Packaging --version 4.10.2` to a newly created non-sdk project, it will fail with:
`error: Error while adding package 'SimpleInjector.Packaging' to project 'C:\Repos\ClassLibrary5\ClassLibrary5\ClassLibrary5.csproj'. The project does not support adding package references through the add package command.`
 
2.If I install a package SimpleInjector.Packaging (4.10.2), using PMUI, then run `add  package SimpleInjector.Packaging` with a newer version, it won't fail, but add an extra package reference entry with the newer version, but without removing the previous old version. So it's not right.

 
3.If there are multiple package references, run dotnet remove package first, then run dotnet add package would work

4.If there is only one package reference, run dotnet remove package first, then run dotnet add package won't work. And the error is the same with scenario 1.

**Comment by heng-liu** [comment] 2022-05-24 19:37
Duplicate of: https://github.com/NuGet/Home/issues/8561

**Comment by zivkan** [comment] 2022-05-26 18:47
Team triage:  Looks like a duplicate of https://github.com/NuGet/Home/issues/8561
Please add a 👍 reaction to upvote that issue.

**Closed as completed by zivkan** 2022-05-26 18:47 UTC
Labels: Resolution:Duplicate, Type:Bug, Triage:NeedsTriageDiscussion, Style:PackageReference, Product:dotnet.exe
