### ISSUE TITLE
Package Manager Console fails with "install-package : Sequence contains more than one matching element"

### ISSUE THREAD

**Issue by bkoelman** [NuGet/Home#5775] opened 2017-08-18 15:51 UTC
## Details about Problem

NuGet product used: Package Manager in Visual Studio 2017 Update 3 (fresh install)

OS version: Windows 8.1N x64

## Repro steps
1. Clone the repo at https://github.com/bkoelman/CSharpGuidelinesAnalyzer
2. Open solution in Visual Studio
3. From the package manager console:
    ```install-package csharpguidelinesanalyzer```

Results:
* Running install on the Vsix project: package is installed, References looks good and References\Analyzer lists the various analyzer rules.
* Running install on the Test project: package is installed. References\NuGet contains a yellow-ish icon. References\Analyzers does not list any rules.
* Running install on the Analyzer project fails with:

```
PM> install-package csharpguidelinesanalyzer -verbose
  GET https://dotnet.myget.org/F/roslyn/api/v3/registration1/csharpguidelinesanalyzer/index.json
  GET https://api.nuget.org/v3/registration3-gz-semver2/csharpguidelinesanalyzer/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/csharpguidelinesanalyzer/index.json 444ms
  NotFound https://dotnet.myget.org/F/roslyn/api/v3/registration1/csharpguidelinesanalyzer/index.json 755ms
  GET https://api.nuget.org/v3/registration3-gz-semver2/csharpguidelinesanalyzer/index.json
  GET https://dotnet.myget.org/F/roslyn/api/v3/registration1/csharpguidelinesanalyzer/index.json
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\csharpguidelinesanalyzer\2.0.0\csharpguidelinesanalyzer.2.0.0.nupkg
  OK https://api.nuget.org/v3/registration3-gz-semver2/csharpguidelinesanalyzer/index.json 103ms
  NotFound https://dotnet.myget.org/F/roslyn/api/v3/registration1/csharpguidelinesanalyzer/index.json 209ms
Running restore with 4 concurrent jobs.
Reading project file E:\Bart\Source\Repos\CSharpGuidelinesAnalyzer\src\CSharpGuidelinesAnalyzer\CSharpGuidelinesAnalyzer\CSharpGuidelinesAnalyzer.csproj.
Restoring packages for E:\Bart\Source\Repos\CSharpGuidelinesAnalyzer\src\CSharpGuidelinesAnalyzer\CSharpGuidelinesAnalyzer\CSharpGuidelinesAnalyzer.csproj...
Restoring packages for .NETStandard,Version=v1.3...
Resolving conflicts for .NETStandard,Version=v1.3...
install-package : Sequence contains more than one matching element
At line:1 char:1
+ install-package csharpguidelinesanalyzer -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.8696230
PM> $error.Exception.StackTrace
PM> 
```

**Comment by emgarten** [comment] 2017-08-21 21:33
Dupe of https://github.com/NuGet/Home/issues/5630

You can workaround this by giving your project a name that isn't exactly the same as the package you are installing.

**Closed as completed by emgarten** 2017-08-21 21:33 UTC
Labels: Resolution:Duplicate

**Comment by KelsonBall** [comment] 2017-10-15 21:56
My project (KelsonBall.Transforms) is not named the same as my package (KelsonBall.Vectors) and I am getting this error - so the proposed workaround won't work for me.
