### ISSUE TITLE
Lock file integrity is lost when using floating version in project references

### ISSUE THREAD

**Issue by shibayan** [NuGet/Home#10458] opened 2021-01-15 16:56 UTC
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): dotnet.exe

Product version: .NET SDK 5.0.102

Worked before? If so, with which NuGet version: None

## Repro steps and/or sample project

Full sample project is here: https://github.com/shibayan/nuget-lock-demo

```xml
<!-- ClassLibrary1.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- Use floating version -->
    <PackageReference Include="Newtonsoft.Json" Version="12.0.*" />
  </ItemGroup>

</Project>

<!-- FunctionApp1.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.2.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
  </ItemGroup>
  <ItemGroup>
    <!-- Use project reference -->
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

```
> dotnet restore --use-lock-file
> dotnet restore --locked-mode

error NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.
```

When using floating version in `ClassLibrary1`, it seems that the correct version is not written to the lock file of `FunctionApp1`.

It will be easier to understand if you check the following diffs. `ClassLibrary1` is still at version **12.0.3**, but `FunctionApp1` has updated its lock file to version **12.0.0**.

https://github.com/shibayan/nuget-lock-demo/pull/1/files

### Verbose Logs

https://github.com/shibayan/nuget-lock-demo/pull/1/checks?check_run_id=1709907720

**Comment by nathanaw** [comment] 2021-08-18 13:57
I am also experiencing this issue. We are using floating versions, and it prevents using lock files in our release process unless we alter the versions to remove the floats.

Any updates on if/when this might be worked on?

**Comment by nathanaw** [comment] 2021-08-18 14:02
If attempting a repro locally, I find that the NU1004 doesn't always trigger unless I wipe the /obj folders.

This is important for an automated build pipeline, since such pipelines are (usually) doing a clean build (git clone, restore, build, publish). In those cases, there is no /obj folder.

**Comment by michaelzillhart** [comment] 2021-08-18 14:47
I was able to reproduce this locally using this simple batch script:

:: Create Projects
mkdir ConsoleApp
cd ConsoleApp
dotnet new console
cd ..
mkdir Library
cd Library
dotnet new classlib --framework "netstandard2.0"
:: Add Package with floating version to Library
dotnet add package Newtonsoft.Json -v 12.*
cd ../ConsoleApp
:: Add Library to ConsoleApp
dotnet add ConsoleApp.csproj reference ../Library/Library.csproj
:: Create LockFile
dotnet restore --use-lock-file
:: Delete obj folders
cd ../Library
rmdir obj /s /q
cd ../ConsoleApp
rmdir obj /s /q
:: Restore
dotnet restore --locked-mode

**Comment by nkolev92** [comment] 2022-02-09 01:37
Hey all, 

This looks like a duplicate of https://github.com/NuGet/Home/issues/8465. 

cc @martinrrm when you're working on https://github.com/NuGet/Home/issues/8465, please verify that your fix addresses this issue as well.

**Closed as completed by nkolev92** 2022-02-09 01:37 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Bug, Area:RestoreRepeatableBuild
