### ISSUE TITLE
Package redirects

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1590] opened 2015-10-16 06:31 UTC
_From @SimonCropp on October 16, 2015 5:0_

In many cases people want to rename a package. ATM there is no easy way to do this, you basically have to release a broken version of the old package with some kind of message to move to the new package. It would be nice to have this handled in a more seamless way by nuget. 

If you are willing to hack many things in the nuget toolset then you can handle it yourself, but it is painful. Here is the work we had to do to move users to a new package https://github.com/Particular/NServiceBus/issues/2113

_Copied from original issue: NuGet/NuGetGallery#2736_

**Comment by maartenba** [comment] 2015-10-16 06:31
_From @yishaigalatzer on October 16, 2015 5:4_

That's something I've been wanting for a while for a few more scenarios. 

This issue should go to the home repo, as it is not a server issue.

Worth a good discussion to cover all the scenarios (both tooling and user scenarios).

Thanks!

**Comment by maartenba** [comment] 2015-10-16 06:31
_From @SimonCropp on October 16, 2015 5:9_

@yishaigalatzer is there an existing issue tracking it? or should i move this to the home repo?

**Comment by maartenba** [comment] 2015-10-16 06:31
_From @yishaigalatzer on October 16, 2015 5:15_

Move it. This is something I wanted as a nuget customer. But I don't believe it is tracked on github

**Comment by yishaigalatzer** [comment] 2015-10-16 19:03
Here is a strawman for user scenarios

### User Scenarios for redirect
1. A package name has changed, and as a package owner I want the users to know where to get the new package
2.  A package was deleted (e.g. infringement of rights), and an alternate official package is available
3. An unofficial package wants to retire because an official package was introduced
4. A package is no longer relevant, and we want to remove it, but perhaps lift one of its dependencies to be a top level package.
5. Ability to redirect one package to two or more packages (so instead of install package A, you will now need both B & C instead). - This is questionable

### Tooling scenarios for redirect
1. When I install a new package from the UI - I'd like to get notified that some swapping is going to happen
2. When restore happens to a package with redirects (e.g. you deleted a package and pushed a redirect instead), I'd like to get an actionable error message rather than auto fix it by default

### Server scenarios
1. The server should surface the fact that this is a redirecting package

CC @davidfowl

**Comment by Jogai** [comment] 2016-01-07 12:23
+1
And in addition to what @yishaigalatzer said: Some packages move to other platforms, especially front-end packages with the support for npm/bower/.. tooling available now in VS2015

**Comment by yishaigalatzer** [comment] 2016-01-07 15:56
Indiction for other platforms like bower was introduced in nuget 3.3, the notification is currently curated and managed by the ASP.net web tools team.

**Comment by jdom** [comment] 2017-11-07 22:31
Is there any progress in this or a similar feature?

**Comment by anangaur** [comment] 2017-11-08 00:05
Related feature proposal/discussion happening here: https://github.com/NuGet/Home/issues/2867

**Comment by emgarten** [comment] 2017-11-10 01:40
Duplicate of https://github.com/NuGet/Home/issues/2867

**Closed as completed by emgarten** 2017-11-10 01:40 UTC
Labels: Resolution:Duplicate, Type:Feature
