### ISSUE TITLE
Tokens are not being replaced when pacakging NETStandard libraries

### ISSUE THREAD

**Issue by nickverschueren** [NuGet/Home#4052] opened 2016-12-02 15:41 UTC
## Details about Problem
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe
NuGet version (x.x.x.xxx): 3.5.0.1938
dotnet.exe --version (if appropirate):
VS version (if appropriate):
OS version (i.e. win10 v1607 (14393.321)): win2012r2 v9600
Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem
1. Create a NETStandard 1.5 library in VS2015
2. Add a .nuspec file using tokens like $id$, $title$, $description$, $version$, $author$
3. Fill out the appropriate attributes (AssemblyTitle, ...) in AssemblyInfo.cs
4. Build the project in Release
5. Create package using something like:
  nuget.exe pack ClassLibrary1.csproj -OutputDirectory "\temp" -Properties Configuration=Release -IncludeReferencedProjects -Verbosity detailed

## Other suggested things
We do use a shared file for some assembly info called GlobalAssemblyInfo.cs, but that does not seem to matter.

### Verbose Logs
Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)

NuGet Version: 3.5.0.1938
Attempting to build package from 'ClassLibrary1.csproj'.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86
)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to use a specific
 version of MSBuild.
Packing files from 'C:\Projects\ClassLibrary1\ClassLibrary1\bin\Release'.
Add file 'C:\Projects\ClassLibrary1\ClassLibrary1\bin\Release\ClassLibrary1.dll'
 to package as 'lib\netstandard1.5\ClassLibrary1.dll'
WARNING: Description was not specified. Using 'Description'.
WARNING: Author was not specified. Using 'Nick'.

Id: ClassLibrary1
Version: 1.0.0
Authors: Nick
Description: Description
Dependencies: Microsoft.NETCore.Portable.Compatibility [1.0.1, ), NETStandard.Li
brary [1.6.0, )

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'ClassLibrary1.nuspec'.
Added file 'lib/netstandard1.5/ClassLibrary1.dll'.
Added file 'package/services/metadata/core-properties/37ce14818efa492f9593bff283
74710a.psmdcp'.

Successfully created package '\temp\ClassLibrary1.1.0.0.nupkg'.

### Sample Project

Very helpful if you can zip a project and paste into this issue!

[ClassLibrary1.zip](https://github.com/NuGet/Home/files/627547/ClassLibrary1.zip)

**Comment by rohit21agrawal** [comment] 2016-12-14 17:23
@nickverschueren properties like $version$ need to be passed on the command line using the Properties flag if you want them to be replaced in the nuspec file.

**Comment by nickverschueren** [comment] 2016-12-14 21:26
@rohit21agrawal: I disagree: [The documentation](https://docs.nuget.org/ndocs/quickstart/create-and-publish-a-package#create-the--nuspec-package-manifest-file) states that:
> tokens in the form $\<token\>$ will be replaced during the packaging process with values from the project's Properties/AssemblyInfo.cs file

This works for normal .NET and PCL-libraries, but not for NETStandard libraries. Although you are right that the version etc. _can_ be passed from the command line, that is not the specific use case.

**Comment by rohit21agrawal** [comment] 2016-12-14 22:19
@nickverschueren my bad, i thought you were packing using the nuspec file. giving this a try on my end.

**Comment by rohit21agrawal** [comment] 2016-12-15 00:04
@nickverschueren upon further investigation, it turns out that if building a project targeting netstandard, asssembly metadata extraction fails,  because nuget.exe tries to load system.runtime version 4.1.0 which is not present in the local path or the gac.

As a workaround , you could try gac'ing that version of system.runtime. Other alternative would be to use command line to pass the appropriate properties or pack using a nuspec or project.json instead of csproj.

**Comment by nickverschueren** [comment] 2016-12-15 09:54
@rohit21agrawal Thanks for the hint. That seems to have solved the issue for now. Although I didn't add the System.Runtime dll to the GAC on our build server, I created a nuget.exe.config with a probing/privatePath and bindingRedirect instead. 
It would be nice to have an option on the CLI to allow me to specify a location for the System.Runtime assembly so that I can have that as a parameter in my build definition.

**Comment by rohit21agrawal** [comment] 2016-12-15 16:25
Feel free to file an issue for the same. Closing this issue for now

**Comment by Trolldemorted** [comment] 2017-01-23 01:00
@rohit21agrawal may i ask what you mean with gac'ing the library?

And shouldn't nuget at least print out a warning/error when it fails to extract the metadata?

**Comment by rohit21agrawal** [comment] 2017-01-26 16:26
@Trolldemorted gac'ing the library simply means installing the library in the Global Assembly Cache (or GAC) . For more details, see https://msdn.microsoft.com/en-us/library/dkkx7f79(v=vs.110).aspx

And yes, nuget should print out a warning/error if it fails to extract metadata. Have created a tracking issue for the same : https://github.com/NuGet/Home/issues/4406

**Comment by Trolldemorted** [comment] 2017-01-26 19:01
@rohit21agrawal that's nice! Is there already an issue for failing to extract metadata in the first place?

**Comment by jeremyVignelles** [comment] 2017-04-19 08:39
@nickverschueren : Could you explain the procedure you have made to make it work on you build server? I have the same issue with my build on my VSTS build pipeline, with NuGet 3.5 and .NET standard 1.6

For now on, I'm adding a copy task that copies the `System.Runtime.dll` from `C:\Windows\Microsoft.NET\Framework\v4.0.30319\` to my output folder. Will do the trick for now.

**Comment by nickverschueren** [comment] 2017-04-19 22:42
@jeremyVignelles : So basically Nuget.exe needs to find the System.Runtime.dll file. That means like any .NET assembly it will search in the execution path, the probing paths and the gac. These are the options you have to place it. 
I chose to use a probing path by creating a nuget.exe.config file, which I placed in the directory where I have nuget.exe. I use a custom nuget.exe location in my build step for this. 
By doing this I can have the System.Runtime.dll file anywhere on the server as long as I configure the right probing path in the config I mentioned before.
Hope this helps.

**Comment by jeremyVignelles** [comment] 2017-04-21 15:48
I finally upgraded to Visual studio 2017, and am using the new csproj-based metadata.
The issue is now gone for me, because I am packaging the nupkg with `dotnet pack` rather than `nuget.exe`.

**Comment by ryno1234** [comment] 2019-04-07 13:52
Any target date for this? It has been open quite a while.

**Comment by nkolev92** [comment] 2020-02-04 20:40
Closing this issue as redundant/lower priority. 
Some of the questions have already been addressed and the additional scenario is capture in #4406

**Closed as completed by nkolev92** 2020-02-04 20:40 UTC
Labels: Type:Bug, Product:NuGet.exe, Functionality:Pack
