### ISSUE TITLE
NU5030 error when pack package with NuGet.exe

### ISSUE THREAD

**Issue by yanshouwang** [NuGet/Home#8470] opened 2019-08-20 03:51 UTC
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
- NuGet.exe

NuGet version (x.x.x.xxx):
- 5.1.0.6013

dotnet.exe --version (if appropriate):
- 2.2.401

VS version (if appropriate):
- VS 2019 16.2.2

OS version (i.e. win10 v1607 (14393.321)):
- Windows 10, V18362.295

Worked before? If so, with which NuGet version:
No

## Detailed repro steps so we can see the same problem

1. My .nuspec use embeded license like this, which the licence file is located in the parent folder
```
<?xml version="1.0"?>
<package>
  <metadata>
    ...
    <license type="file">LICENSE</license>
    ...
  </metadata>
  <files>
    <file src="..\LICENSE" target=""/>
    ...
  </files>
</package>
```

2. run nuget pack command, and throw the NU5030 error:
Error NU5030: The license file 'LICENSE' does not exist in the package.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment] 2019-08-20 03:56
If you are packing extensionless files can you please try https://github.com/NuGet/Samples/blob/master/PackageLicenseFileNuspecExample/PackageLicenseFileNuspecExample.nuspec

Duplicate of https://github.com/NuGet/Home/issues/7601.

**Comment by yanshouwang** [comment] 2019-08-20 04:35
Yes, I tried it and no error occured.
![image](https://user-images.githubusercontent.com/24455689/63317597-09241f00-c346-11e9-9915-53de306241bb.png)
![image](https://user-images.githubusercontent.com/24455689/63317632-26f18400-c346-11e9-87a9-1fde7b3d7333.png)
And after I changed the "LICE*" to "LICENSE", the error occured agian

**Comment by nkolev92** [comment] 2019-08-20 04:44
At this point, I'd have to call that by design. 
The specific issue is about the handling of extensionless files in NuGet pack. 
Paths have worked a certain way for a very long time and it'd be a significant breaking change to try to alter that.

**Comment by yanshouwang** [comment] 2019-08-20 04:47
I think maybe the official should give us a best way to handle this error in the Doc?

**Comment by nkolev92** [comment] 2019-08-20 04:54
I think the sampels repo is linked from the docs, https://github.com/NuGet/Samples, but we can look into making that more apparent.

**Comment by nkolev92** [comment] 2020-01-03 22:50
The docs have undergone some changes that make samples more obvious. 
The samples repo is also a pinned repo in the nuget org.

**Closed as completed by nkolev92** 2020-01-03 22:50 UTC
Labels: Resolution:Duplicate, Resolution:ByDesign, Type:Docs, Functionality:Pack
