### ISSUE TITLE
Perf: ManagedLangs_CS_DDRIT.0800.Close Solution regressed VM_ImagesInMemory_Total_devenv by 4.333 Count (0.9%). Baseline 26104.03

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4352] opened 2017-01-21 02:08 UTC
internal bug: 365041

**Comment by jainaashish** [comment] 2017-01-30 19:21
dupe of 373767

**Closed as completed by jainaashish** 2017-01-30 19:21 UTC
Labels: Tenet:Performance
