### ISSUE TITLE
Need a Standard Way for Distributing Licenses

### ISSUE THREAD

**Issue by Grauenwolf** [NuGet/Home#6801] opened 2018-04-10 02:46 UTC
When adding an open source library to an application, we are usually required to include the library's license along with the DLL when distributing the application.

Currently there is no standard way of handling this, which means there is an often overlooked manual step necessary for any project which distributes the application.

**Comment by Grauenwolf** [comment] 2018-04-10 02:51
Proposal 1:

In the package definition, the library publisher can include a "License File" tag.

When an application takes a dependency on a library, the license file is copied to the project's "\licenses" folder with "None/Copy if Newer" set as the build action. 

The filename will be prefixed with the package name and version.

**Comment by mishra14** [comment] 2018-04-10 15:34
Related to https://github.com/NuGet/Home/issues/4628

**Comment by nkolev92** [comment] 2018-11-30 17:27
Duplicate of that.

**Closed as completed by nkolev92** 2018-11-30 17:27 UTC
Labels: Priority:2, Type:Feature, Functionality:Pack
