### ISSUE TITLE
VisualStudio can't browse nightly .NET Core NuGet feed while it works perfectly in Rider

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#8763] opened 2019-10-29 13:46 UTC
## Detailed repro steps so we can see the same problem

1. Create a new console application.
2. Add a NuGet.Config file with the following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-core"
         value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
  </packageSources>
</configuration>
```
3. Open it in Visual Studio and try to search for some NuGet packages.

Usually, I have one of the three following outcomes:
a) VS shows the loading icon forever (I waited for several hours without any updates)
b) VS crashes and restarts itself
c) VS consumes 2.7GM memory, becomes almost unresponsible, and prints the following error: `[dotnet-core] Exception of type 'System.OutOfMemoryException' was thrown.` It looks like this:

<img width="1827" alt="2019-10-29_15-51-32" src="https://user-images.githubusercontent.com/2259237/67769671-f294f500-fa65-11e9-81c0-29d0131a3a1f.png">

At first, I thought that something is wrong with the feed. So, I decided to check how it works in [Rider](https://www.jetbrains.com/rider/):

![2019-10-29_15-58-47](https://user-images.githubusercontent.com/2259237/67769935-6800c580-fa66-11e9-9c3b-9b7f0050d983.gif)

As you can see, it works perfectly (apart from the fact that Rider consumes several GB to keep the feed data).

I guess, we have such a situation because Visual Studio is a 32-bit process and it has [RAM limitations](https://en.wikipedia.org/wiki/3_GB_barrier) and can't fetch all the data from this feed. In Rider, there is no such limitation because it's a 64-bit process.

Also, I tried to fetch the list of the packages with the help of [nuget.exe 5.3.1](https://dist.nuget.org/win-x86-commandline/v5.3.1/nuget.exe), but it displays this message:

```
λ nuget.exe list
WARNING: This version of nuget.exe does not support listing packages from package source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json'.
No packages found.
```

Do you have any workaround that allows browsing "huge" NuGet feeds in Visual Studio? Is Rider the only way to browse such feeds for now?

## Origin of the problem

Originally, I tried to work with Roslyn dev16.3 (you can download the source code from here: https://github.com/dotnet/roslyn/tree/release/dev16.3). It has the [following NuGet.Config](https://github.com/dotnet/roslyn/blob/release/dev16.3/NuGet.config) file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c)  Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information. -->
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="system-commandline" value="https://dotnet.myget.org/F/system-commandline/api/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="myget-dotnet-coreclr" value="https://dotnet.myget.org/F/dotnet-coreclr/api/v3/index.json" />
    <add key="myget-dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="dotnet-corefxtestdata" value="https://dotnet.myget.org/F/dotnet-corefxtestdata/api/v3/index.json" />
    <add key="dotnet-buildtools" value="https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json" />
    <add key="experimental-vs-packages" value="https://dotnet.myget.org/F/experimental-vs-packages/api/v3/index.json" />
    <add key="symreader" value="https://dotnet.myget.org/F/symreader/api/v3/index.json" />
    <add key="symreader-portable" value="https://dotnet.myget.org/F/symreader-portable/api/v3/index.json" />
    <add key="symreader-converter" value="https://dotnet.myget.org/F/symreader-converter/api/v3/index.json" />
    <add key="symreader-native" value="https://dotnet.myget.org/F/symreader-native/api/v3/index.json" />
    <add key="metadata-tools" value="https://dotnet.myget.org/F/metadata-tools/api/v3/index.json" />
    <add key="interactive-window" value="https://dotnet.myget.org/F/interactive-window/api/v3/index.json" />
    <add key="roslyn-master-nightly" value="https://dotnet.myget.org/F/roslyn-master-nightly/api/v3/index.json" />
    <add key="roslyn-tools" value="https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json" />
    <add key="roslyn-analyzers" value="https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json" />
    <add key="roslyn" value="https://dotnet.myget.org/F/roslyn/api/v3/index.json" />
    <add key="sourcelink" value="https://dotnet.myget.org/F/sourcelink/api/v3/index.json" />
    <add key="vs-devcore" value="https://myget.org/F/vs-devcore/api/v3/index.json" />
    <add key="vs-editor" value="https://myget.org/F/vs-editor/api/v3/index.json" />
    <add key="roslyn_concord" value="https://myget.org/F/roslyn_concord/api/v3/index.json" />
    <add key="vssdk" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json" />
    <add key="vs-impl" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json" />
    <add key="system-commandline" value="https://dotnet.myget.org/F/system-commandline/api/v3/index.json" />
    <add key="dotnet-coreclr" value="https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json" />
  </packageSources>
  <disabledPackageSources>
    <clear />
  </disabledPackageSources>
</configuration>
```

It contains 26 NuGet feeds, but it's almost impossible to browse even the first one in Visual Studio. 

## Details about Problem

My environment:

Microsoft Visual Studio Community 2019
Version 16.2.0
VisualStudio.16.Release/16.2.0+29123.88
Microsoft .NET Framework
Version 4.7.03190

JetBrains Rider 2019.2.3
Build #RD-192.7317.11, built on October 16, 2019

Windows 10.0.17763.805

Repro solution: [NuGetProblem.zip](https://github.com/NuGet/Home/files/3783737/NuGetProblem.zip)

**Comment by zivkan** [comment] 2019-10-29 22:02
Duplicate of #8478

**Closed as completed by zivkan** 2019-10-29 22:02 UTC
Labels: Resolution:Duplicate
