### ISSUE TITLE
Custom solution configurations don't work with NuGet packages

### ISSUE THREAD

**Issue by karikera** [NuGet/Home#10489] opened 2021-01-27 08:40 UTC
## Details about Problem

NuGet product used Visual Studio: Visual Studio

Product version:  5.8.1

Custom solution configurations don't work with NuGet packages.
I guess NuGet needs the mapper for custom configuration names in the user project.

## Repro steps and/or sample project

Use the NuGet package with custom configuration names
ex) debug_static/release_static instead of Debug/Release

**Comment by nkolev92** [comment] 2021-02-04 03:37
Duplicate of https://github.com/NuGet/Home/issues/5895. 


At this point we don't recommend conditions based on the configuration, and the recommended way of conditioning PackageReference are `TargetFramework`. 

Given that the reasons for this are technical(has to do with how MSBuild works) there are workarounds you can consider, by using Choose\When. Note that there's no tooling support for this.

**Comment by zkat** [comment] 2021-02-08 21:34
Closing as duplicate.

**Closed as completed by zkat** 2021-02-08 21:34 UTC
Labels: Resolution:Duplicate, Type:Feature, Resolution:ByDesign, Style:PackageReference
