### ISSUE TITLE
Nuget Download Count for Template Type Not Updating when Installing via .NET CLI

### ISSUE THREAD

**Issue by proudmonkey** [NuGet/Home#8658] opened 2019-10-03 02:02 UTC
Hi,

I apologize if this has been asked before. I tried to look for an existing issue related to this here but I can't seem to find any. I've also searched the web but to no avail.

I have uploaded a new Nuget Template package 4 days ago, and when I install it via .NET CLI, the downloads isn't counting even if the template was successfully installed. I've tried it may times and tried using different machines to install and still I see 0 downloads to date. 

## Details about Problem

NuGet product used (`dotnet.exe`):

NuGet version (`5.3.0`):

dotnet.exe --version (`.NET Core 3.0.100`):

VS version (if appropriate): `Visual Studio Pro 2019`

OS version (`Windows 10.0.17763.737`):

## Detailed repro steps so we can see the same problem

1. Run `dotnet new -i apiboilerplate.aspnetcore` This will install the latest template in your machine.
2. Run `dotnet new apiboilerplate --name "myapi" -o samples`. This will generate the project template within the samples directory.

Note that the template was installed successfully, it's just that the count wont reflect on the site. Here's my nuget template: https://www.nuget.org/packages/ApiBoilerPlate.AspNetCore

Perhaps I may have just missed something here?

Thank you,
Vince

**Comment by nkolev92** [comment] 2019-10-03 21:01
Thanks for the filing the issue. 

This is better suited for the NuGetGallery as that's where nuget.org issues are handled. 

Duplicate of https://github.com/NuGet/NuGetGallery/issues/7592

**Closed as completed by nkolev92** 2019-10-03 21:01 UTC
Labels: Resolution:Duplicate, Type:Bug
