### ISSUE TITLE
Toolkit.Services nupkg does not install with packages.config

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#7124] opened 2018-07-17 21:07 UTC
From https://github.com/Microsoft/WindowsCommunityToolkit/issues/2303

@rido-min wrote:

I tried to install Microsoft.Toolkit.Services 3.0.0 nuget package in my WinForms 4.7 project, but the install fails with:

`Unable to resolve dependency 'Microsoft.Identity.Client'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.`

Because of Identity.Client is in preview I also tried with "Include Prerelease" checked, but it didn't work neither.

If I install directly Identity.Client first, then I can install Toolkit.Services.

I'm using VS 2017 Update 15.7.5.

> Note that the same package installs with no problem when using PackageReference.

**Comment by anangaur** [comment] 2018-07-17 21:08
This installs just fine with `PackageReference`. Not sure where the bug is. IMO, this package should just install fine.

**Comment by nkolev92** [comment] 2018-07-18 06:13
This is a duplicate of #2944

**Closed as completed by nkolev92** 2018-07-18 06:13 UTC
Labels: Resolution:Duplicate, Style:Packages.Config
