### ISSUE TITLE
dotnet list package returns error if config option is not specified.

### ISSUE THREAD

**Issue by voroninp** [NuGet/Home#13239] opened 2024-02-13 08:51 UTC
### NuGet Product Used

dotnet.exe

### Product Version

dotnet 8.0.1 

### Worked before?

I do not know, never used.

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I have a `NuGet.Config` file in the root of my repository.

If I run :
```
dotnet list .\src\CubeCreator.DataAccess.Shared\CubeCreator.DataAccess.Shared.csproj package --format json
```
I get this error:
> error: Unexpected failure reading NuGet.Config. Path: 'CubeCreator.DataAccess\src\CubeCreator.DataAccess.Shared\CubeCreator.DataAccess.Shared.csproj\NuGet.Config'.
error:   Cannot create 'CubeCreator.DataAccess\src\CubeCreator.DataAccess.Shared\CubeCreator.DataAccess.Shared.csproj' because a file or directory with the same name already exists.

> trace: System.AggregateException: One or more errors occurred. (Unexpected failure reading NuGet.Config. Path: 'CubeCreator.DataAccess\src\CubeCreator.DataAccess.Shared\CubeCreator.DataAccess.Shared.csproj\NuGet.Config'.)
trace:  ---> NuGet.Configuration.NuGetConfigurationException: Unexpected failure reading NuGet.Config. Path: 'CubeCreator.DataAccess\src\CubeCreator.DataAccess.Shared\CubeCreator.DataAccess.Shared.csproj\NuGet.Config'.
trace:  ---> System.IO.IOException: Cannot create 'CubeCreator.DataAccess\src\CubeCreator.DataAccess.Shared\CubeCreator.DataAccess.Shared.csproj' because a file or directory with the same name already exists.
trace:    at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
trace:    at System.IO.Directory.CreateDirectory(String path)
trace:    at NuGet.Configuration.FileSystemUtility.AddFile(String fullPath, Action`1 writeToStream)
trace:    at NuGet.Configuration.FileSystemUtility.GetOrCreateDocument(XDocument content, String fullPath)
trace:    at NuGet.Configuration.SettingsFile.<>c__DisplayClass23_0.<.ctor>b__0()
trace:    at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
trace:    --- End of inner exception stack trace ---
trace:    at NuGet.Configuration.SettingsFile.<>c__DisplayClass32_0.<ExecuteSynchronized>b__0()
trace:    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
trace:    at NuGet.Configuration.SettingsFile..ctor(String directoryPath, String fileName, Boolean isMachineWide, Boolean isReadOnly)
trace:    at NuGet.Configuration.Settings.ReadSettings(String settingsRoot, String settingsPath, Boolean isMachineWideSettings, Boolean isAdditionalUserWideConfig, SettingsLoadingContext settingsLoadingContext)
trace:    at NuGet.Configuration.Settings.<>c__DisplayClass29_0.<LoadSettings>b__0(String f)
trace:    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
trace:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
trace:    at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
trace:    at NuGet.Configuration.Settings.LoadSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
trace:    at NuGet.Configuration.Settings.LoadDefaultSettings(String root)
trace:    at NuGet.CommandLine.XPlat.ListPackageCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext()
trace:    --- End of inner exception stack trace ---
trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
trace:    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
trace:    at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)

However, if I specify `--config ./NuGet.Config` option, it works fine:
```
dotnet list .\src\CubeCreator.DataAccess.Shared\CubeCreator.DataAccess.Shared.csproj package --format json --config .\NuGet.config
```

**Comment by nkolev92** [comment] 2024-02-14 21:33
Duplicate of https://github.com/NuGet/Home/issues/12954. 

@voroninp The issue is that relative paths were broken. 

If you use a full path, it should work then.

**Closed as not planned** 2024-02-14 21:33 UTC
Labels: Resolution:Duplicate, Type:Bug, RegressionFromPreviousRTM, Product:dotnet.exe, Functionality:ListPackage
