### ISSUE TITLE
vsfeedback - NuGet restore of Packages.config project fails with RC4. Cannot build .NET Standard Class Library.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4560] opened 2017-02-10 17:11 UTC
vsfeedback 803478 - https://developercommunity.visualstudio.com/content/problem/18548/nuget-restore-fails-cannot-build-net-standard-clas-1.html
See photo/etc in feedback item.

**Comment by zhili1208** [comment] 2017-02-10 18:50
this is dupe of https://github.com/NuGet/Home/issues/4533

**Closed as completed by zhili1208** 2017-02-10 18:50 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Restore, Style:Packages.Config
