### ISSUE TITLE
Nuget restore infinite loop

### ISSUE THREAD

**Issue by jnothstine** [NuGet/Home#1402] opened 2015-09-18 14:59 UTC
1. I try to update a package in a project.
2. I get prompted for a username and password for my on premises ProGet server (this does not happen with VS 2013)
3. After a long wait, I get a 503 error
4. NuGet tries again and step 3 repeats
5. Step 4 keeps repeating.  I hit the cancel button in the dialog box and it keeps trying again and again.
6. I have to kill Visual Studio
7. I go to update the package again.  Nuget identifies the package as not installed so I have to install it.  So nuget pretty much broke the integrity of my project by uninstalling my package and failing to reinstall it.

The problems with the 503 error are persistent and have occurred ever since I installed Visual Studio 2015.  I never had these problems with Visual Studio 2013 and still don't have them.  This indicates a problem with Visual Studio 2015 and not my ProGet server.  It makes dealing with Nuget on Visual Studio 2015 very frustrating and pretty much a shot in the dark as to whether I get successful updates on my packages.  Please do us a favor and try to release a version that works!

**Comment by yishaigalatzer** [comment] 2015-09-18 18:13
What version of NuGet are you using? Did you update to 3.2?

**Comment by yishaigalatzer** [comment] 2015-09-21 21:47
1. Is "kinda" expected, the update process is to uninstall the package then install a new version. You killed visual studio (I get it is not your fault, and you had no choice), but that means NuGet has no chance to roll things back.

**Comment by csharpfritz** [comment] 2015-09-22 21:14
Investigating

**Comment by yishaigalatzer** [comment] 2015-10-23 01:14
@csharpfritz any updates? We haven't heard back from the user what version he is using, and if we can't learn anything new I suggest we close this bug.

**Comment by csharpfritz** [comment] 2015-10-23 15:43
Unable to reproduce... closing for now.  If we get a reliable repro we can re-open later

**Closed as completed by csharpfritz** 2015-10-23 15:43 UTC
