### ISSUE TITLE
[Test Failure][Doc] Clicking error link NU3037 in VS Error List window goes to the wrong page

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7643] opened 2018-12-17 09:23 UTC
## Details about Problem
NuGet version: NuGet Client Dev\5.0.0.5728
VS Version: D16.0\28414.68
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps
1. Create a new test certificate:  .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -NotAfter "2018-12-16 23:32:00" (one minute after current time)
2. Before the test certificate expires, sign a package:  `NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>` (e.g. certificate SHA256 fingerprint="AAAAA")
3. Wait for the author signature certificate to expire
4. Create a project in VS, add required mode in nuget.config file with trusted signers list:
```
   <config>
     <add key="signatureValidationMode" value="require" />
  </config>
  <trustedSigners>
     <author name="JamieZhang">       
         <certificate fingerprint="AAAAA" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
     </author>
  </trustedSigners>
```
5. Reload the solution in VS, update the package source to the above package (in step2) path and install the package into the project in PM UI
## Expected
Clicking error link NU3037 in VS Error List window goes to the correct document of error NU3037.
## Actual
Clicking error link NU3037 in VS Error List window goes to the wrong page as below screenshot.
![clickingnu3037](https://user-images.githubusercontent.com/20632625/50077721-238a8380-0220-11e9-82e2-01c331398fde.png)

**Comment by rrelyea** [comment] 2019-02-14 19:18
@heng-liu - please go add a doc page to https://github.com/NuGet/docs.microsoft.com-nuget/tree/master/docs/reference/errors-and-warnings for nu3037.
Look at error message, etc...

**Comment by nkolev92** [comment] 2019-02-20 01:31
Isn't this a duplicate of https://github.com/NuGet/Home/issues/6498? 

That issue already calls out 3037 as a gap.

**Comment by nkolev92** [comment] 2019-02-20 23:42
Closign as dup of #6498 as per the above comment.

**Closed as completed by nkolev92** 2019-02-20 23:42 UTC
Labels: Resolution:Duplicate, Type:Docs, Functionality:Signing
