### ISSUE TITLE
How to resolve "Could not create SSL/TLS secure channel." error when using NuGet Installer step in TeamCity

### ISSUE THREAD

**Issue by gebai** [NuGet/Home#5883] opened 2017-09-13 16:05 UTC
[REmoved all original text as it was just the default template with no other data] -@rrelyea

**Comment by zhili1208** [comment] 2017-09-13 17:19
Could you provide more information about your issue? NuGet team doesn't own nuget installer in teamcity, but if you have any issue related to nuget.exe, we can take a look.

Please provide the version of nuget.exe and the repro steps for issue

**Comment by gebai** [comment] 2017-09-14 13:05
Hi Zhi,

Thanks for the response!

This has been an issue across all our TeamCity projects. JebBrains (The TeamCity vendor) suggest us to consult NuGet team regarding this problem.

Our TeamCity is behind a proxy. When we use NuGet Installer build step, only NuGet.exe v3.3.0 works. All other versions, v3.4.3, v3.5.0, and v4.1.0 will throw "Could not create SSL/TLS secure channel." error.

We tried to add proxy setting in the nuget.config (as showing below), but it does not take any effect.

<config>
<add key="http_proxy" value="http://proxyserver:80" />
<add key="http_proxy.user" value="user" />
<add key="http_proxy.password" value="password" />
</config>


Is there anything else we can try to get NuGet.exe working properly with the proxy?

Thanks,

Ge

**Comment by zhili1208** [comment] 2017-09-14 17:10
Could you provide the http log? It might not related to proxy authorization. From the error message "Could not create SSL/TLS secure channel", it looks like a secure protocol issue, it can be server provide one version of secure protocol and client needs another version. Or certificate issue. Need full log to understand what's going on.

**Comment by rrelyea** [comment] 2017-09-21 21:51
@gebai - Fiddler is one tool to get an http log. Are you still having a problem here? Please work with @zhili1208

**Comment by nkolev92** [comment] 2017-10-17 22:46
Thanks for reporting this issue. 

Since we have not received more information we are closing this issue. 
Please reopen if you can still reproduce this problem.

**Closed as completed by nkolev92** 2017-10-17 22:46 UTC
Labels: Resolution:Question, Triage:Investigate
