### ISSUE TITLE
-Reinstall with a Package ID re-installs ALL packages.

### ISSUE THREAD

**Issue by OliverRC** [NuGet/Home#6133] opened 2017-11-02 12:38 UTC
## Details about Problem

NuGet product used (Package Manager Console):
NuGet version: 4.3.0.4406
Command: ```Update-Package -Id <packageName> -reinstall```
VS version: VS 2017 (15.4.1)

## Issue

It does not respect the package Id and re-installs everything.

**Comment by emgarten** [comment] 2017-11-02 18:28
@OliverRC does it help to add `-IgnoreDependencies`?

Are the other packages being re-installed dependencies of the package you referenced?

**Comment by OliverRC** [comment] 2017-11-03 12:27
it was as if I ran Update-Package -Reinstall with no package name

**Comment by emgarten** [comment] 2017-11-03 14:33
@OliverRC does it help to add -IgnoreDependencies?

Are the other packages being re-installed dependencies of the package you referenced?

**Comment by OliverRC** [comment] 2017-11-06 08:03
The other packages that were reinstalled were not dependencies on the package I wanted to reinstall.

**Comment by Rob-Houweling** [comment] 2018-04-16 06:53
I can confirm that this is still a (very time consuming) bug. 
Today I tried to reinstall a package in my web project and it reinstalled all of the packackeg in my web and other projects in my solution as well. Please fix this asap. Sometimes it takes half an hour to reinstall the packages so this is very annoying, time-consuming and thus expensive!

**Comment by rohit21agrawal** [comment] 2018-06-12 22:32
closing as dupe of #737 , will track there.

**Closed as completed by rohit21agrawal** 2018-06-12 22:32 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug, Product:VS.PMConsole

**Comment by rohit21agrawal** [comment] 2018-06-12 23:36
as a workaround for now, please pass the -Projectname parameter to specify the project explicitly. I have a PR out to fix this.
