### ISSUE TITLE
Nuget 2.8.5.207 can't install PowerShell modules

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#3495] opened 2016-09-22 05:20 UTC
_From @swernli on September 21, 2016 19:5_

I'm working on the Docker PowerShell project (https://github.com/Microsoft/Docker-PowerShell) and we recently starting having issues with our automatic appveyor builds because of the new Nuget 2.8.5.207.  It seems that installing packages via PowerShell's `Install-Module` command fails if the client machine has the latest version, but succeeds with version 2.8.5.205.  This fails for 207 in our local testing as well, and happens regardless of which version produced the package.  This means that any new clients will be unable to use our module at all.  I tried dotnet packages, and those seem to work fine, so it has something to do with the way the PowerShell module packages get unpacked.

This is a major blocking issue for any PowerShell users who want to distribute modules via nupkgs.

_Copied from original issue: NuGet/NuGetGallery#3249_

**Comment by maartenba** [comment] 2016-09-22 05:20
_From @swernli on September 21, 2016 19:5_

@jterry75 @jstarks for FYI

**Comment by rrelyea** [comment] 2016-09-22 23:20
When you say new Nuget 2.8.5.207, can you be more specific. Who shipped that version? When? What worked before you moved to that version?

**Comment by swernli** [comment] 2016-09-23 16:09
@rrelyea Previously, our appveyor build environment had Nuget 2.8.5.206 on it, but each run gets a new instance that installs Nuget by running `Install-PackageProvider NuGet -Force` so it automatically picks up the latest version.  After building our PowerShell module and packaging it via `nuget pack` we then set the folder containing the nupkg files as a local PSRepository and try to perform an `Install-Module` from that location.  This cmdlet uses Nuget to locate and unpack the requested module for PowerShell, and fails with version 2.8.5.207 and succeeds with 2.8.5.206.  I've included some links to the appveyor output below.  I can confirm that the same issue occurs on my local machine if I upgrade to a newer version of Nuget, and goes away when I roll back to the previous version.
- Failed import using 2.8.5.207: https://ci.appveyor.com/project/WindowsVirtualization/docker-powershell/build/99-bbbeaanj
- Successful import using 2.8.5.206 (exact same product code): https://ci.appveyor.com/project/WindowsVirtualization/docker-powershell/build/100-yyjbudch

For now, we are avoiding this issue by explicitly installing the older version of Nuget as part of our appveyor build script, but this could definitely affect customers who try to install our PowerShell module (and presumably other modules as well) and don't know they need to avoid the latest Nuget.

**Comment by yishaigalatzer** [comment] 2016-09-23 19:49
This looks like a powershell team issue, rather than a nuget team issue. Looping in the appropriate team - CC @krishna_msft

**Comment by yishaigalatzer** [comment] 2016-09-23 19:51
Correcting the id - @KrishnaV-msft

**Comment by jianyunt** [comment] 2016-09-23 20:55
Are you running Nano server TP5? What's your OS?

**Comment by jianyunt** [comment] 2016-09-23 21:05
In addition, to help us diagnosis the issue, can you add "Get-PackageProvider -debug -verbose", "Get-PackageSource -debug -verbose"  and "Find-Package  -Name Docker  -debug -verbose" before calling install-module.

Also are there any ways to help us to repro it locally?

**Comment by swernli** [comment] 2016-09-26 18:48
@jianyunt I added the debug statements you suggested (and reverted my workaround that pinned us to 2.8.5.206).  We can see the results from the run as it happens here:
https://ci.appveyor.com/project/WindowsVirtualization/docker-powershell/build/101-trwbyqyk

**Comment by yishaigalatzer** [comment] 2016-09-26 21:31
@jianyunt where should this issue move to? I'd hate to close it here without a follow-up public issue tracking it.

**Comment by jianyunt** [comment] 2016-09-26 21:52
There is a dup one in their repo. NP to close it. thx

**Closed as completed** 2016-09-26 22:56 UTC
Labels: Resolution:External

**Comment by swernli** [comment] 2016-09-26 23:38
Looks like the official recommendation from the PowerShell team is to use `Publish-Module` and not package the module directly via nuget (https://github.com/Microsoft/Docker-PowerShell/issues/145#issuecomment-249682862).  Closing this issue as we can resolve this in our package production.
