### ISSUE TITLE
vsfeedback -- Xml documentation not packed for netstandard class libraries 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4389] opened 2017-01-24 18:11 UTC
see vsfeedback item: 745986

1. Create netstandard class library
2. Enable XML documentation in project settings
3. Right click on project -> Pack

Expected:
.xml documentation file next to .dll in lib folder inside nuget package

Actual:
No .xml documentation file included in package.

**Comment by emgarten** [comment] 2017-01-25 00:15
I know this was working in RC.2 for my own packages, but I had issues with getting msbuild to output the .XML file to the correct location.

**Comment by pakrym** [comment] 2017-01-25 23:06
I tried to reproduce this issue again and see that `.xml` file being packed. I think what it was is that VS sets xml file location to `\ClassLibrary1.xml` by default (note the slash in beginning) and that caused build to fail because of `Access denied` to root of drive `C:` which I didn't notice.

**Comment by rrelyea** [comment] 2017-01-25 23:17
So a dotnet/sdk bug perhaps? 
/cc @srivatsn

**Comment by emgarten** [comment] 2017-01-25 23:17
@pakrym that sounds like what I was seeing too, xml files kept showing up at the root of the drive the project was on. ``$(OutputPath)`` wasn't being set somehow. Changing to ``bin\$(Configuration)\$(TargetFramework)`` worked.

This behavior was with RC.2 so I don't know how the latest builds handle this.

**Comment by rohit21agrawal** [comment] 2017-01-26 19:12
closing this in favor of a bug in SDK : https://github.com/dotnet/sdk/issues/738

**Closed as completed by rohit21agrawal** 2017-01-26 19:12 UTC
Labels: Resolution:NotRepro, Functionality:Pack
