### ISSUE TITLE
ProjectSystem bug: Nuget Packages getting auto removed

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8017] opened 2019-04-18 16:54 UTC
Update: FIXED IN VS 16.1 - SEE FEEDBACK ISSUE HERE: https://developercommunity.visualstudio.com/content/problem/443877/assembly-reference-is-removed-from-project-after-r.html

----

With the VS2019 Preview 2.2, every time I add a nuget package to my application, it stays for a bit but it seems like after I start a debug and end it, the nuget package gets removed or if it was an upgrade, it gets reverted back down to the previous version.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/447942/nuget-packages-getting-auto-removed.html
VSTS ticketId: 788339_
_These are the original issue comments:_

Brad on 2/11/2019, 04:41 PM (65 days ago): Also experiencing this.<br><br>Package reference added via Package Manager window.<br><br>Subsequently, I am also unable to double-click the project file or use the context menu command "Edit .csproj" to open the netstandard2.0 csproj.<br><br>I have attached the output from the Package Manager output window.<br>
Brad on 2/11/2019, 04:56 PM (65 days ago): <p>Upon restarting VS, when attempting to edit the project files, the following error is displayed <br><br>An exception has been encountered. This may be caused by an extension.<br><br>You can get more information by examining the file 'C:\Users\removed\AppData\Roaming\Microsoft\VisualStudio\16.0_eeb51662\ActivityLog.xml'.<br><br><br>ActivityLog.xml shared in subsequent comment (privately)</p>

Brad on 2/11/2019, 05:15 PM (65 days ago): <p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/59029-activitylogxml.txt">activitylogxml.txt</a></p>

Russ Painter on 3/20/2019, 06:56 AM (29 days ago): It doesn't matter if I add from the Package Manager Console or from the Package Manager UI, the changes don't get applied to my csproj.  I switch back to VS2017 on the same project, and either of those methods work perfectly to add packages to my project.<br><br>Once the packages are added to the csproj, I can return to VS2019 and evertying works fine, until I need to add another package.
Russ Painter on 3/20/2019, 06:57 AM (29 days ago): Restarting VS2019 does not fix the problem in my case.
Brent Robinson on 3/29/2019, 11:49 PM (19 days ago): Agreed. It looks like the csproj file is being reverted to an earlier state when adding a NuGet package. In my case I added a NuGet package, and couldn't open the csproj in VS2019. I closed VS, made other changes to the csproj outside of VS, then commited to source control. I noticed the package wasn't added, so added it via VS2019. It didn't add the package, but it did revert my csproj file to the state before VS2019 was opened.<br><br>I was able to work around this by<br>1. Close VS2019<br>2. Delete the ".vs" folder<br>3. Open VS2019, add the NuGet package<br>4. Save all<br><br>I suspect "Save all" after adding a NuGet package might be key here.
Ben Rothermel on 4/15/2019, 04:02 AM (3 days ago): <p>Experiencing this in the latest stable VS2019 release</p>

Alexander Witkowski on 4/17/2019, 00:39 PM (21 hours ago): Have the same issue with:<br>Microsoft Visual Studio Enterprise 2019<br>Version 16.0.1<br>VisualStudio.16.Release/16.0.1+28803.156<br>Microsoft .NET Framework<br>Version 4.7.03190<br><br>Installed Version: Enterprise<br><br>Azure App Service Tools v3.0.0   16.0.12311.10635<br>Azure App Service Tools v3.0.0<br><br>C# Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8<br>C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.<br><br>Common Azure Tools   1.10<br>Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.<br><br>Extensibility Message Bus   1.1.77 (master@24013d5)<br>Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.<br><br>Microsoft JVM Debugger   1.0<br>Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines<br><br>Microsoft MI-Based Debugger   1.0<br>Provides support for connecting Visual Studio to MI compatible debuggers<br><br>Mono Debugging for Visual Studio   16.0.300 (573eda3)<br>Support for debugging Mono processes with Visual Studio.<br><br>NuGet Package Manager   5.0.0<br>NuGet Package Manager in Visual Studio. For more information about NuGet, visit  http://docs.nuget.org/ .<br><br>ProjectServicesPackage Extension   1.0<br>ProjectServicesPackage Visual Studio Extension Detailed Info<br><br>ResourcePackage Extension   1.0<br>ResourcePackage Visual Studio Extension Detailed Info<br><br>ResourcePackage Extension   1.0<br>ResourcePackage Visual Studio Extension Detailed Info<br><br>Visual Basic Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8<br>Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.<br><br>Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 809f41207b74a1356208f11b8fa3a15233734050.<br>Microsoft Visual F# Tools 10.4 for F# 4.6<br><br>Visual Studio Code Debug Adapter Host Package   1.0<br>Interop layer for hosting Visual Studio Code debug adapters in Visual Studio<br><br>VisualStudio.Mac   1.0<br>Mac Extension for Visual Studio<br><br>Xamarin   16.0.0.515 (d16-0@a3502d929)<br>Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.<br><br>Xamarin Designer   4.17.4.418 (remotes/origin/d16-0@3d086e814)<br>Visual Studio extension to enable Xamarin Designer tools in Visual Studio.<br><br>Xamarin Templates   16.1.47 (31f664d)<br>Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.<br><br>Xamarin.Android SDK   9.2.0.5 (HEAD/292d27fa)<br>Xamarin.Android Reference Assemblies and MSBuild support.<br>    Mono: mono/mono/2018-08-rc@5ad371dab1b<br>    Java.Interop: xamarin/java.interop/d16-0@c987483<br>    LibZipSharp: grendello/LibZipSharp/master@44de300<br>    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f<br>    MXE: xamarin/mxe/xamarin@b9cbb535<br>    ProGuard: xamarin/proguard/master@905836d<br>    SQLite: xamarin/sqlite/3.26.0@325e91a<br>    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6<br><br><br>Xamarin.iOS and Xamarin.Mac SDK   12.8.0.0 (0aa8452)<br>Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
Rob Relyea [MSFT] on 4/18/2019, 09:52 AM (2 min ago): <p>Nobody mentions what type of projects that they are seeing this problem with? </p><p>Sounds like PackageReference, but are you using NetCore/NetStandard projects or NetFramework based projects (with PackageReference turned on).</p>
_These are the original issue solutions:_

Brad solved on 2/11/2019, 05:31 PM (65 days ago), 0 votes: 
<p>Restarting VS seems to fix the issue of disappearing package references.</p>

**Comment by rrelyea** [comment] 2019-04-18 16:55
5.1 for now, but would consider 5.0.x depending on what we learn.

**Comment by binaryn3xus** [comment] 2019-04-18 16:58
@rrelyea You asked in the MS Community issue what project it was originally experienced with. My project was a .Net Core Console application.

**Comment by GeekyMonkey** [comment] 2019-04-18 17:09
Mine was ASP.NET Core 2.2 web app with Angular

**Comment by nkolev92** [comment] 2019-04-18 17:22
This sounds like something project-system related. 

@zivkan was recently dealing with a similar bug, maybe he has an idea?

//cc @davidwengier Does this sound like that bug?

**Comment by zivkan** [comment] 2019-04-18 17:27
If the bug happens when the csproj is open in another tab, it could be a duplicate of this bug: https://developercommunity.visualstudio.com/content/problem/443877/assembly-reference-is-removed-from-project-after-r.html

**Comment by davidwengier** [comment] 2019-04-18 22:55
There is nothing in the issue that rules out this being a duplicate of the bug @zivkan linked to, and in particular the comment about not being able to use the "Edit .csproj" menu item points strongly to the same issue.

**Comment by DanielRBowen** [comment] 2019-04-23 15:33
This is frusturating. It keeps on deleteting Microsoft.AspNetCore.Authentication.JwtBearer and then I have to add the package again.

**Comment by zivkan** [comment] 2019-04-23 16:05
@DanielRBowen Do you have the csproj open in another tab?

**Comment by DanielRBowen** [comment] 2019-04-23 16:21
@zivkan It stopped removing the package. I think it was after I commented out the code that needed the the package but I left the using statement and then added the nuget package to the project and then built the project. I don't know if commenting out the code did the trick or it was something else entirely. 

I don't know what you mean by having the csproj in another tab. I did have another instance of VS open with another solution that I was looking at.

**Comment by dannoh** [comment] 2019-04-25 14:28
I was having the same issue. I had the .csproj file open in a tab, closing it fixed the issue.

**Comment by profan** [comment] 2019-04-26 18:10
Also running into the very same issue, however the csproj file being open in another tab does not seem to be the issue here, as I'd first restarted VS with the csproj file still there and tried again, afterwards restarted VS and then also closed the open csproj file and tried adding the packages again and building at that point, still the packages get removed upon build.

**Comment by jmrnilsson** [comment] 2019-04-29 18:41
I'm experiencing this as well. Auto-removed on build or even before that it seems. Saving "before build" didn't change this behavior. 

In Visual Studio 19.0.2 and before with the following combination in the solution:
- PackageReference
- .NetStandard2.0
- .NetFramework
- .NetCore 2.1

First with a package called Optional and now with Moq. Eventually Optional got installed. But I'm clueless to as what happened to mitigate it for that package.

**Comment by jmrnilsson** [comment] 2019-04-29 19:19
If I open "Manage Nuget package" then this happens on save and appends the following to the "Package Manager"-output. *I've cleared out project names*

```
Failed to resolve all items referenced by 'XYZ\XYZ.csproj'. This message can typically be ignored. The issue may be resolved by fully restoring and building the solution. If the unresolved item is a project reference this can lead to an incomplete NuGet restore result and missing package references. To ensure that restore is able to find all projects verify that all projects are referenced correctly and exist on disk.
Restoring NuGet packages...
Running restore with 16 concurrent jobs.
Reading project file XYZ
Reading project file XYZ
Reading project file XYZ.csproj.
Reading project file XYZ
Persisting no-op dg to XYZ.nuget.dgspec.json
Persisting no-op dg to XYZ.nuget.dgspec.json
The restore inputs for 'XYZ.Core' have not changed. No further actions are required to complete the restore.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: XYZ
No-Op restore. The cache will not be updated. Path: XYZ.nuget.cache
Restore completed in 2,37 ms for XYZ
The restore inputs for 'XYZ.ABC' have not changed. No further actions are required to complete the restore.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: XYZ
No-Op restore. The cache will not be updated. Path: XYZ.nuget.cache
Restore completed in 20,95 ms for XYZ
Persisting no-op dg to XYZ.Tests.csproj.nuget.dgspec.json
The restore inputs for 'XYZ.ABC.Tests' have changed. Continuing restore.
Restoring packages for XYZ.csproj...
Restoring packages for .NETCoreApp,Version=v2.1...
Persisting no-op dg to XYZ.nuget.dgspec.json
The restore inputs for 'XYZ.Api' have not changed. No further actions are required to complete the restore.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: XYZ
No-Op restore. The cache will not be updated. Path: XYZ.nuget.cache
Restore completed in 51,9 ms for XYZ
Resolving conflicts for .NETCoreApp,Version=v2.1...
Checking compatibility of packages on .NETCoreApp,Version=v2.1.
All packages and projects are compatible with .NETCoreApp,Version=v2.1.
Committing restore...
Writing assets file to disk. Path: XYZ.json
Writing cache file to disk. Path: XYZ.Tests.csproj.nuget.cache
Restore completed in 671,37 ms for XYZ.csproj.
NuGet package restore finished.
Time Elapsed: 00:00:01.1113456
========== Finished ==========
```

**Comment by jmrnilsson** [comment] 2019-04-29 19:44
I my case it was fixed by remove all the Nuget packages in .NetFramework-project, WinForms that didn't need any.

**Comment by jmrnilsson** [comment] 2019-05-01 10:02
Additionally I also experienced Uninstal, of TinyIoC in this case, getting rolled back when edit is open for a project in Sln.

**Comment by dominoFire** [comment] 2019-05-01 17:29
Apologies for the late response.

I was unable to get a stable reproduction of this bug in Visual Studio. The closest problem I encountered was related to a ASP.NET core App that does not update the package reference in a project reference. This problem happens in VS 16.0.1 but not in our internal preview.

Inside the NuGet Package Manager, we interact with some Project System libraries to *nominate* changes in the project structure. That way, the Project System evaluates when it is a good time to update the .csproj and the project itself.

Sorry for the inconveniences that this bug caused @jmrnilsson @DanielRBowen @GeekyMonkey  @JoshuaGarrison27  and others that are in the previous VS Feedback thread.

I will close the issue for now awaiting for VS release with the fix linked below. If the problem arises again, we'll follow-up on this issue.

https://developercommunity.visualstudio.com/content/problem/443877/assembly-reference-is-removed-from-project-after-r.html

**Closed as completed by dominoFire** 2019-05-01 17:29 UTC
Labels: Type:Bug, Style:PackageReference, Partner:Project-System

**Comment by jmrnilsson** [comment] 2019-05-02 21:14
I believe this to be resolved in v.19.0.3. This no longer happens for the believed reproduction I had before.

**Comment by JohanSellberg** [comment] 2019-05-14 08:23
I had this problem in VS2019 16.0.3 but closing the project file solved the issue.

**Comment by dscottie** [comment] 2019-05-14 16:02
I'm seeing this issue in 16.0.3.  Also happening when I attempt to consolidate packages across projects in the solution; update takes effect initially, then reverts back to previous version.

**Comment by zivkan** [comment] 2019-05-14 16:36
The Project System team made fixes for some issues that are available in 16.1 preview 3, see the Developer Community link posted in previous comments. 16.0.3 certainly does not have these improvements. If the problem was just related to having an "uninitialised" project file open (single click a project in Solution Explorer that opens the csproj in a window that disappears when you single click a different file), then you won't see it if the "uninitialised" window is closed or on a different file.

If the issue continues with 16.1 preview 3 or later, I'm sure the project system team would appreciate more information. Consider using the Visual Studio feedback tool and use the record feature while you reproduce the issue, so more information is collected. Also consider recording your screen into a video so we can see what tabs you have open in the background. As David wrote in the Developer Community issue, we can't reproduce the issue with the instructions given to us, so if it keeps happening after you use a version of VS with his fixes, we need to learn how to get into this problem state.

**Comment by rrelyea** [comment] 2019-05-15 18:45
According to this twitter thread...looks like this was fixed in 16.0.4 (shipped on 5/14/2019)

https://twitter.com/satyajitsumeru/status/1128676881706901504

**Comment by dmitrykarnitski** [comment] 2019-05-21 10:13
Hi, it seems that the issue is reproducible with 16.0.4. A project file is not getting updated when installing a new package in the project. The error occurs after Save All or Build operation is executed. Hopefully, everything works by adding the package reference manually in csproj file.

**Comment by baskan** [comment] 2019-05-25 11:48
closing and re-opening works but this made me lose hours figuring out who removes my nuget packages 🤦‍♂️

btw this issue still occurs in 16.0.4

**Comment by PhilippElhaus** [comment] 2020-04-27 09:58
i can confirm that this is still a bug in VS2019... (16.4.5)

**Comment by PhilippElhaus** [comment] 2020-05-01 07:42
This is such a pain in the ass bug...holy shit when will this be fixed

**Comment by davidwengier** [comment] 2020-05-01 07:55
@PhilippElhaus if you're still seeing this after installing a fixed version then I would recommend reporting a new issue, ideally with the inbuilt recording feature of Visual Studio, as whilst you might be seeing the same outcome, it's likely there is a different root cause.

**Comment by PhilippElhaus** [comment] 2020-05-01 08:00
Yes i just did exactly this. I have this now here for every build i create, VS becomes absolutely unworkable due to this.

**Comment by rrelyea** [comment] 2020-05-01 17:39
@PhilippElhaus  - can you please provide a link here to your newly filed feedback issue...so other people who come here with a similar problem can follow that issue?

**Comment by PhilippElhaus** [comment] 2020-05-01 17:51
> @PhilippElhaus - can you please provide a link here to your newly filed feedback issue...so other people who come here with a similar problem can follow that issue?

https://developercommunity.visualstudio.com/content/problem/1014815/compilation-deletes-nuget-packages.html

**Comment by rrelyea** [comment] 2020-05-01 19:11
Thanks @PhilippElhaus  - it is definitely a similar effect...but a very different reason for the problem. See my replies in the feedback issue.

Update: that issue turned out to be the squirrel.windows nupkg, according to @philippElhaus. See https://github.com/Squirrel/Squirrel.Windows/issues/1622 and the devcommunity issue it links to.
