### ISSUE TITLE
Nuget restore symbolic or hard links to nuget cach

### ISSUE THREAD

**Issue by vbjay** [NuGet/Home#12782] opened 2023-07-31 18:35 UTC
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### The Elevator Pitch

![image](https://github.com/NuGet/Home/assets/3629489/ebfb40d2-5754-40ba-b64d-d6e017ef9da0)
Why can't restoring packages create hard/symbolic links and build systems understand the link and use the resolved data?  Why am I required to have package cache files and local project files?  The cache has the files and nuget restore could fixup symbolic links as needed if I copied repo for example.

**Comment by jeffkl** [comment] 2023-07-31 21:58
@vbjay it looks like your package cache is located inside of the same directory as a particular repository.  Are you able to use the user-wide package cache instead which would cut down on duplication of packages?

Unfortunately, using symbolic links or hard links is unlikely to happen.  In order for this to be performant, there would need to be a user-wide location where all files are stored, laid out in a manner to make it easy to do a lookup.  Then when NuGet was unpacking a `.nupkg`, it would need to see if that file already existed and create a link to it instead of extracting it.  I could see that whole process being very complicated and error prone.  Not to mention that not every platform/file system supports symbolic and/or hard links.  So for your case I think at least using the user-wide global package cache would still be an improvement.  I'm not sure if other package managers support using links.

**Comment by vbjay** [comment] 2023-07-31 22:28
No. I am showing the project folder's packagees folder that is consuming 3GB+. Yes I am aware that it is using a lot of packages. My problem is that the same packages are also located in my nuget cache in my user profile.  At the moment when I do a local build and even add the run of publish cms which copies other items like kentico ci repository data and cms bulld output my project folder sits at 7.7GB with the nuget packages folder in the project is 3.2GB.  If I  `git clean -xdf`  the project the repo sits at ~ 1.1GB. I understand build output takes up room.  But my issue is we have another website following same template and using same packages so ~ 3.2*2 GB and that is just those 2 projects. 

I know storage is cheap but it just feels silly to have package x 100 times in project folders.  If it is in package cache then a hard/soft link would minimize copies killing hardrive. I have gotten very familiar with nuget locals command to clear my cache and just feel like it could be better where there is a common machine wide store that can be pruned as needed with locals or other tools and if nuget detects system supports hard/symbolic links then it can use that to eliminate splatting same files all over the place.

**Comment by jeffkl** [comment] 2023-07-31 22:37
@vbjay if the entire set of projects in your repository are using `<PackageReference />`, every package will be in the user-wide global packages folder by default.  If one or more projects are using `packages.config`, then you will get a local package folder.  This was a major improvement in PackageReference and if possible, can you migrate projects away from `packages.config`?  Or does you repository's `NuGet.config` specify to use a local folder for PackageReference projects?

**Comment by vbjay** [comment] 2023-07-31 22:44
I wish I could but the CMS side is a framework 4.8 asp.net Kentico 13 site. The other side is an mvc 6.0 kentico 13 site which does have package references. Kentico has not made the CMS portion of the app .net yet. I most definitely tried to migrate the projects but visual studio says no to that type of project.

**Comment by jeffkl** [comment] 2023-08-03 21:06
Team Triage:  We've decided to close this issue as By Design.  For `packages.config`, the design was always that packages are unzipped under the solution directory.  We will not be investing in `packages.config` as we're encouraging users to migrate to `PackageReference`.  For `PackageReference`, there is a concept of a "global" packages folder which is very similar to having symbolic links.

**Closed as not planned by jeffkl** 2023-08-03 21:06 UTC
Labels: Type:Feature, Resolution:ByDesign

**Comment by vbjay** [comment] 2023-08-03 22:37
Thanks. At least now it's documented and others should find when searching for similar issue.

**Comment by vbjay** [comment] 2023-08-03 22:45
@jeffkl then can you help point to the right place to support package reference migration of asp.net framework project nuget packages.config files. Being able to migrate those projects to package reference would be a great help. Not sure if that is visual studio feedback or nuget or asp net.  If you can point me to right place I can link this issue to one I create wherever you point me.
