### ISSUE TITLE
nuget verify -All and -Signatures option has no differences in implementation

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10028] opened 2020-09-13 20:20 UTC
As per [doc](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-verify#nuget-verify--all), nuget.exe has two switches, `-All` to perform all the possible verifications on the package(s) and `-Signatures` option to verify signatures based on values passed for `-CertificateFingerprint` option. However, looking at the [implementation](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/VerifyCommand/VerifyCommandRunner.cs#L38), there is no difference in the behavior and by default all the possible verifications on the package are performed.

**Comment by nkolev92** [comment] 2020-09-15 23:56
Pretty sure this is by design. 

We wanted to allow ourselves the flexibility of adding more validations that are run which people run verify. 

The command is not supposed to be constrained to signature verification only.

**Comment by aortiz-msft** [comment] 2020-09-21 20:19
Closing as dupe of https://github.com/NuGet/Home/issues/8298

**Closed as completed by aortiz-msft** 2020-09-21 20:19 UTC
Labels: Product:NuGet.exe, Functionality:Signing
