### ISSUE TITLE
Unable to load service index for api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/Home#6195] opened 2017-11-17 19:00 UTC
@biourja-ajain commented on [Mon Nov 13 2017](https://github.com/NuGet/NuGetGallery/issues/4989)

I am unable to open the page where (manage nuget pachages). its just showing error occured, 
I need to browse some packages and install it in my system
actually the error occured when i mistakenly deleted the nuget.config file from users/ appdata/local/nuget

can you please help me in this- i am using VS2017

---

@biourja-ajain commented on [Mon Nov 13 2017](https://github.com/NuGet/NuGetGallery/issues/4989#issuecomment-343874888)

![capture](https://user-images.githubusercontent.com/33622024/32720751-79afa536-c88a-11e7-8214-eb7f2abded79.JPG)

---

@biourja-ajain commented on [Fri Nov 17 2017](https://github.com/NuGet/NuGetGallery/issues/4989#issuecomment-345253971)

its urgent can you please reply ASAP

---

@scottbommarito commented on [Fri Nov 17 2017](https://github.com/NuGet/NuGetGallery/issues/4989#issuecomment-345334135)

Sorry for the late response. This looks like a client issue to me--this is the repository for issues with the server. Moving to NuGet/Home.

**Comment by nkolev92** [comment] 2017-11-17 20:09
We haven't changed anything in this area. 
@biourja-ajain
Which exact version of VS are you using?
Does it happen with older versions of Visual Studio?
Can you reproduce it with other sources?

**Comment by rrelyea** [comment] 2017-11-21 23:58
@biourja-ajain -- is this still urgent? If so, please give us more details.

**Comment by biourja-ajain** [comment] 2017-11-28 08:56
Hello

I am unable to use *Manage Nuget packages * and use the browse opton to
download from website. i am getting this error

" *An error occurred while sending the request.*
*  Unable to connect to the remote server*
*  A connection attempt failed because the connected party did not properly
respond after a period of time, or established connection failed because
connected host has failed to respond 72.21.81.200:443
<http://72.21.81.200:443>*"

Please provide me details how should i work on it


Thanks & Regards,

AMIT JAIN (AJ)
Software Developer
BioUrja Trading, LLC
905, Airen Heights, Sch - 54,
A B Road,
Indore - 452010
ICE: AJain12
www.biourja.com

**Comment by nkolev92** [comment] 2017-11-30 03:52
@scottbommarito He's having trouble accessing nuget.org. 
Can you please route to the on-call person ? 

@biourja-ajain Are you using a vpn?
Can you access api.nuget.org/v3/index.json in your browser?

**Comment by jainaashish** [comment] 2018-01-10 22:38
No further updates here assuming that was some intermittent issue which has resolved by now.

**Closed as completed by jainaashish** 2018-01-10 22:38 UTC
Labels: Resolution:NotRepro, Functionality:VisualStudioUI
