### ISSUE TITLE
Adding two trusted-signer of the same domain fails for one index

### ISSUE THREAD

**Issue by kobelobster** [NuGet/Home#10174] opened 2020-10-22 10:45 UTC
dotnet version: 3.1
nuget version: 5.7.0.6726

We have a custom NuGet feed hosted on Nexus SonaType. It's set up that we have one feed for our own repositories and one "feed" which acts as a proxy to NuGet. Now, we want to use this feed in Docker as well to automatically run tests, build the image etc.

Since we have our own certificate and our services are behind a proxy, I am doing this in the `Dockerfile`

```
ARG proxy

RUN dotnet nuget add source "https://sonatype-nexus.ourdomain.com/repository/releases/" --name "Digital Repository" --username "digital" --password $NUGET_USER_PASSWORD --store-password-in-clear-text
RUN dotnet nuget add source "https://sonatype-nexus.ourdomain.com/repository/nuget.org-proxy/" --name "NuGet Proxy"

RUN mono /usr/local/bin/nuget.exe config -set http_proxy="${proxy}"

RUN mono /usr/local/bin/nuget.exe trusted-signers add -Name "Digital Repository" -ServiceIndex "https://sonatype-nexus.ourdomain.com/repository/releases/index.json"
RUN mono /usr/local/bin/nuget.exe trusted-signers add -Name "NuGet Proxy" -ServiceIndex "https://sonatype-nexus.ourdomain.com/repository/nuget.org-proxy/index.json"
```

Adding both services as a sourc works without problem, however, as soon as I want to add the trusted signer, I get the error 

`Invalid certificate information from the service index 'https://sonatype-nexus.ourdomain.com/repository/releases/index.json'.`

However, when I uncomment this and there's only the one for the `nuget.org-proxy` it works without ANY problems. It's just that the one is failing.

But they are on the same domain. How can the one fail with a certificate error, but the other does not? 

**Update**

What is double weird is that a `wget` to both `index.json` works without problems. It's really only nuget having problems with the certificate :/

**Comment by heng-liu** [comment] 2020-10-23 23:25
Hi, since you're using dotnet 3.1 which doesn't have package signing/verification, I guess you don't need package signature verification during restore. (package signing/verification is also not supported on Mono)
If so, there is no need to add trust-signers. Trust-signers are for [configuring trusted package repositories](https://devblogs.microsoft.com/nuget/lock-down-your-dependencies-using-configurable-trust-policies/#configure-trusted-package-repositories). If you only need to add source in NuGet.Config, you can just use dotnet nuget add source command.

If my guess is wrong and you would like to have package signature verification during restore, pls use dotnet 5. 
And for [adding trusted-signers based on ServiceIndex](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-trusted-signers#options-for-add-based-on-a-service-index), you have to make sure this repository support the repository signatures resource. 

Pls let me know if you have any further questions. Thanks.

**Comment by kobelobster** [comment] 2020-10-26 07:37
Hi @heng-liu,

thanks for your answer. I removed the `trusted-signers` now and after a few adjustments and caveats it seems to work. 

The main problem seems to be that I used both `mono /usr/local/bin/nuget.exe` and `dotnet nuget`. I had to do this, since setting the proxy does only work on `nuget.exe` but not on `dotnet nuget` so far.

However, I found this issue https://github.com/NuGet/Home/issues/4413#issuecomment-275770731 which says

> the problem here is ~/.config is defined by mono not us, we use .net framework Environment variable Appdata Folder for ,net framework(mono) and use ~/.nuget for .net core(this is defined in nuget).
>
> we can't change mono to /.nuget, it will break mono restore for existing user.

It seems, for mac/osx the pathes are correct: https://docs.microsoft.com/de-de/nuget/reference/cli-reference/cli-ref-config#options
And indeed, I added these two commands to my `Makefile` test

```
cat ~/.nuget/NuGet/NuGet.Config
cat ~/.config/NuGet/NuGet.Config
```

And what I saw was that

* The first file contained the repositories etc, however
* The second file contained the proxy settings 

So the problem was, that my proxy settings were saved in a different config file than the one being used by the `dotnet command`. So this has multiple solutions

1. Use `mono` on every occasion, however, I think using the `dotnet nuget` command is the way forward, especially when working on a linux environment, so this would just force us to upgrade in the near future anyway
2. Tell the nuget.exe to use the same config file as `dotnet nuget` 

So I went with the 2nd solution and used this command

`RUN mono /usr/local/bin/nuget.exe config -configfile ~/.nuget/NuGet/NuGet.Config -set http_proxy="${proxy}"`

And when I run `cat ~/.nuget/NuGet/NuGet.Config` I get the configuration values for the proxy and the sources. So it seems that both `dotnet nuget` and `mono /usr/local/bin/nuget.exe` now wrote in the same file.

However, in my pipeline, with this code

```
    - mono /usr/local/bin/nuget.exe config http_proxy -configfile ~/.nuget/NuGet/NuGet.Config
    - export PACKAGE_VERSION=0.0.0-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
    - dotnet pack -p:PackageVersion=${PACKAGE_VERSION}
```

it fails because of an ssl error. The first command, AGAIN, shows me that the http proxy is set, so `dotnet nuget` should have no problem using it. However, it fails anyway, so I even tried it with

`dotnet pack -p:PackageVersion=${PACKAGE_VERSION} --configfile ~/.nuget/NuGet/NuGet.Config` and it still fails.

So what I had to do was to change my pipeline to this

```
    - dotnet pack -p:PackageVersion=${PACKAGE_VERSION}
    - mono /usr/local/bin/nuget.exe push Common/bin/Debug/Common.${PACKAGE_VERSION}.nupkg -Source https://sonatype-nexus.ourdomain.com/repository/releases
```

And now it works, but, this is really confusing. Why is the setting with the http proxy not used by `dotnet push`? 

This was the config file after using both `mono nuget.exe` and `dotnet nuget` in combination

```
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Digital Repository" value="https://sonatype-nexus.ourdomain.com/repository/releases/" />
    <add key="NuGet Proxy" value="https://sonatype-nexus.ourdomain.com/repository/nuget.org-proxy/" />
  </packageSources>
  <config>
    <add key="http_proxy" value="http://xxx.xx.xx.xxx:xxxx" />
  </config>
  <packageSourceCredentials>
    <Digital_x0020_Repository>
        <add key="Username" value="digital" />
        <add key="ClearTextPassword" value="[MASKED]" />
      </Digital_x0020_Repository>
  </packageSourceCredentials>
```

So it should've worked, and like I said, even using `mono /usr/local/bin/nuget.exe config http_proxy -configfile ~/.nuget/NuGet/NuGet.Config` worked and showed me the proxy settings, but it seems it was unable to use this file somehow?

**Comment by heng-liu** [comment] 2020-10-26 19:04
Yes, the NuGet.Config file has different paths on Linux/Mac for different commands(using mono or dotnet) https://github.com/NuGet/docs.microsoft.com-nuget/issues/1878#issuecomment-585443310

For now, manually editing the NuGet.Config would be a workaround.
We have a tracking issue https://github.com/NuGet/Home/issues/10059 for adding missing commands/arguments for dotnet.
Pls vote for it if you'd like it to be finished. Thanks!

**Comment by heng-liu** [comment] 2020-10-26 19:13
Close it as a duplicate of https://github.com/NuGet/Home/issues/4413

**Closed as completed by heng-liu** 2020-10-26 19:13 UTC
Labels: Platform:Xplat, Area:Settings

**Comment by kobelobster** [comment] 2020-10-29 05:40
@heng-liu The question, however, would be, why does it not work when using `mono -configfile {configfile from dotnet command}` in combination with `dotnet nuget` commands? I posted the NuGet.config that resulted from the combination of the commands and the file had all necessary settings but still failed until I used `mono` for every command.

**Comment by aortiz-msft** [comment] 2020-10-30 21:58
@kobelobster - Would you please create a new issue for your last question? It seems quite different from the original problem tracked by this issue: "Adding two trusted-signer of the same domain fails for one index"

**Comment by kobelobster** [comment] 2020-11-06 08:31
@aortiz-msft I created a new issue https://github.com/dotnet/runtime/issues/44346 
Think it fits there more than it does here, right?
