### ISSUE TITLE
There are error messages after an MVC application is created

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#661] opened 2015-05-28 18:12 UTC
Repro steps:
- create a new mvc application
- delete the packages folder
- start package manager, go to installed tab
	
Expected: the packages listed in packages.config should be shown as installed.
Actual: no items found.

**Comment by emgarten** [comment] 2015-05-29 17:42
Duplicate of https://github.com/NuGet/Home/issues/664

**Closed by emgarten** 2015-05-29 17:42 UTC
