### ISSUE TITLE
Cannot sign a nupkg because the Pack target leaves the file locked

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#6638] opened 2018-03-03 00:03 UTC
I'm trying to sign a nupkg and it fails to modify the file because the file is evidently open somewhere with a write lock. I verified this by writing an MSBuild Task that runs after the Pack target and tries to _move_ the nupkg file, and the build fails with this output:

```
2018-03-02T23:58:32.9487453Z      3>GenerateNuspec:
2018-03-02T23:58:32.9487767Z          Successfully created package 'E:\A\_work\7\s\src\VS2017\..\..\bin\SingleTargetNetSDK\Debug\SingleTargetNetSDK.1.0.0.nupkg'.
2018-03-02T23:58:32.9741335Z        TestFileLocks:
2018-03-02T23:58:32.9741655Z          Moving package to test file locks...
2018-03-02T23:58:32.9928384Z          Moving file from "E:\A\_work\7\s\src\VS2017\..\..\bin\SingleTargetNetSDK\Debug\SingleTargetNetSDK.1.0.0.nupkg" to "E:\A\_work\7\s\bin\SingleTargetNetSDK\Debug\SingleTargetNetSDK.1.0.0.nupkg.bak".
2018-03-02T23:58:32.9931114Z      3>E:\A\_work\7\s\src\VS2017\Directory.Build.props(17,5): error MSB3677: Unable to move file "E:\A\_work\7\s\src\VS2017\..\..\bin\SingleTargetNetSDK\Debug\SingleTargetNetSDK.1.0.0.nupkg" to "E:\A\_work\7\s\bin\SingleTargetNetSDK\Debug\SingleTargetNetSDK.1.0.0.nupkg.bak". The process cannot access the file because it is being used by another process. [E:\A\_work\7\s\src\VS2017\SingleTargetNetSDK\SingleTargetNetSDK.csproj]
```

Does the NuGet pack task not close file handles appropriately?

[Build log](https://devdiv-test.visualstudio.com/DevDiv/_build/index?buildId=2276&_a=summary)

**Comment by AArnott** [comment] 2018-03-03 00:13
BTW, this may be a non-deterministic problem. I just had a successful build after two failures.
If the Pack task is leaking file handles though, it makes sense that a non-deterministically scheduled finalizer would close the handle. So the bug may be to close your FileStream before returning from your MSBuild Task.Execute method.

**Comment by AArnott** [comment] 2018-03-03 00:22
The next attempt failed so we have 3 out of 4 builds failed with this.

**Comment by nkolev92** [comment] 2018-03-03 00:26
I thought there'll be an extra microbuild task to sign with?

//cc
@dtivel @PatoBeltran @rohit21agrawal

**Comment by AArnott** [comment] 2018-03-03 00:27
There is. I'm writing it. And can't publish it because it leads to build failures due to this locking issue.

**Comment by AArnott** [comment] 2018-03-03 00:28
BTW this doesn't repro for me locally. So I wonder if this may have already been fixed in 15.6? The cloud build machines that repro the lock issue are running 15.5.

**Comment by nkolev92** [comment] 2018-03-03 00:38
I think you might be hitting https://github.com/NuGet/Home/issues/6165 fixed by https://github.com/NuGet/NuGet.Client/pull/1808.

**Comment by AArnott** [comment] 2018-03-03 00:45
Thanks, @nkolev92. That seems very likely. What version of .... something... do I have to update the build agents to in order to get this fix?

**Comment by nkolev92** [comment] 2018-03-03 00:48
15.6 has this fix. 

Yeah, updating the build agents would be the best option. 

Would that work?

**Comment by AArnott** [comment] 2018-03-03 00:48
MicroBuild agents usually don't update till at least a week after RTW for a given release. Is there a nuget package carrying an SDK that we can reference in the interim, perhaps?

**Comment by rohit21agrawal** [comment] 2018-03-03 00:52
I believe NuGet.org has a vesion of NuGet.Build.Tasks.Pack (the latest one) which carries this fix .

**Comment by nkolev92** [comment] 2018-03-03 00:55
I recently published the matching version of the pack targets that go into the CLI. 

https://www.nuget.org/packages/NuGet.Build.Tasks.Pack/4.6.0-rtm-4825

**Comment by AArnott** [comment] 2018-03-03 01:25
Sweet. @nkolev92  Is it as simple as referencing that package, or do I have to set any special property to activate the Tasks defined within that package?

**Comment by nkolev92** [comment] 2018-03-03 01:27
Just referencing the package should do the trick.

**Comment by AArnott** [comment] 2018-03-03 01:29
Awesome. Thanks.

**Comment by nkolev92** [comment] 2018-03-03 01:48
Closing this as duplicate of #6165

**Closed as completed by nkolev92** 2018-03-03 01:48 UTC
Labels: Resolution:Duplicate, Functionality:Pack, Functionality:Signing

**Comment by rrelyea** [comment] 2018-03-03 02:41
Great stuff. Thanks Andrew and Nikolche.
