### ISSUE TITLE
Facade: Not possible to install Nuget.Configuration package to .NETFramework 4.5 project

### ISSUE THREAD

**Issue by JakubLinhart** [NuGet/Home#2193] opened 2016-02-26 11:33 UTC
Nuspec file of NuGet.Configuration package (https://www.nuget.org/packages/NuGet.Configuration/) contains:

```
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Globalization" targetFramework=".NETFramework4.5" />
```

System.Globalization assembly is not a part of .NETFramework4.5, attempt to install the package ends with an error message: "Failed to add reference to 'System.Globalization'. Please make sure that it is in the Global Assembly Cache."

**Comment by yishaigalatzer** [comment] 2016-02-26 23:41
Hmm works just fine for me

![image](https://cloud.githubusercontent.com/assets/1238711/13368454/4bd3b8f6-dc9f-11e5-8d71-ab49e6acf950.png)

![image](https://cloud.githubusercontent.com/assets/1238711/13368466/6a0eed0e-dc9f-11e5-8ec0-3e7362c62cd9.png)

**Comment by yishaigalatzer** [comment] 2016-03-12 21:38
We concluded that this is a bug in the package, I can't promise that it will be fixed for 3.4 (due to the current timeline). Your workaround is to add the reference directly or use project.json instead of packages.config in your project.

The issue is that the package was designed for project.json scenarios where it will just work, when it is used in a packages.config scenario a framework reference cannot be found because System.Globalization is indeed not part of the .NET 4.5 framework and is not GAC'd (it is instead a portable contract, but visual studio can't add it).

We discussed at length with @Pilchie and @ericstj and that's going to be the way forward for asp.net and .net core packages. In this case this is our own package, but it can only be fixed after the .NET CLI projects can deal with, so we are in a bind for now

**Comment by ericstj** [comment] 2016-03-13 01:15
> System.Globalization is indeed not part of the .NET 4.5 framework and is not GAC'd  

It's part of the framework and indeed in the GAC...  The error message from NuGet is wrong, and the failure is due to the assembly already being part of the project, added automatically like all other facades.  NuGet doesn't see that it's added automatically and tries to add it, which fails.

**Comment by yishaigalatzer** [comment] 2016-03-13 01:23
@ericstj we still agreed that we are not making facades a nuget fx reference. This pattern never worked, and we agreed not to enable it. Did I get it wrong?

**Comment by ericstj** [comment] 2016-03-13 01:27
We agreed that NuGet could fix it but it didn't make sense to enable it since it never worked. 

Still seems odd that we'd delay fixing the shipping package and ask folks to workaround the problem in a shipping product.  Seems like it would make more sense to have a workaround when consuming CLI, the pre-release product that didn't implement the existing precedent (auto-ref facades).

**Comment by yishaigalatzer** [comment] 2016-03-13 04:09
The fix is in the package to stop adding the ref. However it is used in our build that depends on the CLI, so we got not much choice as far as I can see.

**Comment by yishaigalatzer** [comment] 2016-03-13 04:09
Or perhaps we can add a package ref to system.glob instead?

**Comment by niemyjski** [comment] 2016-07-12 22:15
Any timeline for a fix, the story is kind of horrible right now as end users don't know what's going on an even worse package owners don't expect this behavior or know what the fix is.. I came across the fix after sheer luck.

**Comment by yishaigalatzer** [comment] 2016-07-13 01:06
@rob can we please remove this framework dependency from the package?

Blake - what specific package breaks you?

**Comment by niemyjski** [comment] 2016-07-13 03:48
@yishaigalatzer any package... https://github.com/NuGet/Home/issues/3103

**Comment by yishaigalatzer** [comment] 2016-07-13 03:52
Got you, thanks!

The official stance is that it is not going to be supported, and that these packages are invalid and bugs should be opened against the package owners to remove facades as framework references.

**Comment by niemyjski** [comment] 2016-07-13 13:28
@yishaigalatzer tooling shouldn't let you make these mistakes.... This is still biting me in the ass on a few customer machines and I'm 100% sure I have no more framework/facade dependencies..

**Comment by davidfowl** [comment] 2016-07-13 13:29
Where is the package?

**Comment by yishaigalatzer** [comment] 2016-07-13 13:31
Tooling shouldn't understand it when you pack, framework assembly just means add from GAC, which can vary from machine to machine.

Like David suggests, help us see a sample failure

**Comment by niemyjski** [comment] 2016-07-13 13:50
I'm having some reports with https://www.nuget.org/packages/exceptionless of `'Exceptionless' already has a dependency defined for 'System.Collections'` on full framework...

But you'd see this general failure with a lot of libs like this specific version: https://www.nuget.org/packages/Nito.Collections.Deque/1.0.0-delta-8 

The issue is we are defining our assemblies we want imported using "system.runtime": "" when the package is installed. But this causes the GAC issue, so we need to have it be a build time dependency.

**Comment by niemyjski** [comment] 2016-07-13 13:52
@davidfowl no one really understands why this is happening in the community. Just talk to the #elasticsearch guys or package owner.. This bit them pretty hard and I think they have a different issue out around this..

**Comment by gmarz** [comment] 2016-07-13 14:18
Yea, we hit this a while ago.  We've been using the workaround mentioned in #3103 and https://github.com/aspnet/Home/issues/1157 to get around this by making our frameworkAssemblies [build-time dependencies](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/project.json#L68).

**Comment by yishaigalatzer** [comment] 2016-07-13 14:46
The issue really comes from the differences between nuget + msbuild and the dotnet build system. So for now the build flag seems to be the right thing as essentially it works exact the same as a csproj + nuget would have done it.

We do need to look at two aspects here:
1. Do we allow (and we couldn't find a good way to do it) visual studio to detect that add from GAC failed but it can be added as a facade @xavierdecoster was working on this and Eric st. John might be able to assist further 
2. How does this translate to the new world in msbuild. Namely how to fx references go from the project into the package

**Comment by dtivel** [comment] 2016-10-06 16:40
System.Globalization was [removed](https://github.com/NuGet/NuGet.Client/commit/c9a1ca1364202a80183deabc229d5fbab8166a76#diff-b23d69f408e97e2b49d722d1760cdaf3L33) as a framework assembly from NuGet.Configuration on April 21 via commit jainaashish/NuGet.Client@c9a1ca1.  The first release of NuGet.Configuration to have this change is [3.4.3](https://www.nuget.org/packages/NuGet.Configuration/3.4.3).

**Comment by dtivel** [comment] 2016-10-06 16:44
We're still working on the general scenario.

**Closed as completed** 2016-10-20 18:18 UTC
Labels: Type:DCR, Platform:Xplat
