### ISSUE TITLE
Target net47 versus net472 causes "Cannot resolve dependency..." error

### ISSUE THREAD

**Issue by sam-wheat** [NuGet/Home#7590] opened 2018-12-05 04:24 UTC
Unknown build error, 'Cannot resolve dependency to assembly 'OtherDll.dll' because it has not been preloaded.   When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.'

Project configuration:

MyApp.exe - net472
depends on
MyDll.dll - net472
depends on
OtherDll.dll

I am creating a nuget package for MyDll.dll, which depends on OtherDll.dll.  When I add the nuget to MyApp, I expect a reference to OtherDlll to be added.  
The reference is not added if target="lib\net47"
The reference is added if target="lib\net472"

Build command:
NuGet.exe pack MyDll.csproj -Outputdirectory bin\release -properties Configuration=Release

Works:

	<files>
		<file src="bin\$configuration$\*.dll" target="lib\net472" />
	</files>
	
	
Causes the error above:

	<files>
		<file src="bin\$configuration$\*.dll" target="lib\net47" /> 
	</files>
	

NuGet Version: 4.7.1.5393
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100-preview3-009430\

Host (useful for support):
  Version: 2.2.0-preview3-27014-02
  Commit:  525082ca3e

**Comment by nkolev92** [comment] 2018-12-28 19:40
@sam-wheat 
I was not able to reproduce this issue based on your description. 
Would you mind trying it out again with nuget.exe 4.9.2?

**Comment by sam-wheat** [comment] 2018-12-29 00:40
@nkolev92 
Thanks for looking at this issue.  I see the same problem on 4.9.2.

**Comment by nkolev92** [comment] 2018-12-29 01:59
@sam-wheat Would you be able to attach a repro project?

Thanks!

**Comment by zivkan** [comment] 2019-01-25 01:30
Closing as we can't repro this issue. Please add a comment if it's still an issue and if you can add more information or ideally a sample project that shows the error.

**Closed as completed by zivkan** 2019-01-25 01:30 UTC
Labels: Resolution:NotRepro, Functionality:Pack, WaitingForCustomer
