### ISSUE TITLE
Need to make NuGet.VisualStudioExtension and NuGet.PackageManagement work with Dev10 and Dev11

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#463] opened 2015-04-21 00:08 UTC
Need to make NuGet.VisualStudioExtension and NuGet.PackageManagement work with VS 2010 and VS 2012. Microsoft.VisualStudio.Threading and JoinableTaskFactory is only available since VS 2013. Several changes were made to NuGet.VisualStudioExtension to use JoinableTaskFactory. This meant support for VS 2010 and VS 2012 went away. Need to bring it back

For example, JoinableTaskFactory was introduced to the NuGet codebase with the following commit
https://github.com/NuGet/NuGet.VisualStudioExtension/commit/023ef221e00e4b84054643ff77b59ec4ceadedb3. And, more commits were made, which used the new API which is only compatible with VS 2013+

**Comment by yishaigalatzer** [comment] 2015-04-21 17:24
This work depends on making a decision if we are taking NuGet 3.0 downlevel below VS2013. It is very unlikely we do so, but keeping it here so we can retriage once we start planning 3.1.0 Beta

**Comment by csharpfritz** [comment] 2015-04-21 17:26
This is a duplicate of #201 and #200.  We may want to re-open those so that we can track the two down-level migrations as separate work items.

**Comment by yishaigalatzer** [comment] 2015-04-21 19:14
Its a detailed work item, not a duplicate.

**Closed** 2015-11-21 06:45 UTC
Labels: ClosedAs:WontFix
