### ISSUE TITLE
nt

### ISSUE THREAD

**Issue by amir4q** [NuGet/Home#12205] opened 2022-10-30 06:52 UTC
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe, NuGet SDK, Other/NA

### The Elevator Pitch

ad

### Additional Context and Details

ad

**Comment by nkolev92** [comment] 2022-11-03 18:37
Closing as the issue is incomplete.

**Closed as completed by nkolev92** 2022-11-03 18:37 UTC
Labels: Type:Feature
