### ISSUE TITLE
[Bug]: Create PMC install -source tests for PackageReferenence type projects

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11187] opened 2021-08-27 03:32 UTC
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

n/a

### Worked before?

n/a

### Impact

Other

### Repro Steps & Context

If we execute below command on PR type project
`install-package SolutionLevelPkg -source C:\NuGetProj\NuGet.Client\test\EndToEnd\Packages`
Then it should show below warning.
`The 'Source' parameter is not respected for the transitive package management based project(s) ConsoleApp. The enabled sources in your NuGet configuration will be used.`

Test in not created yet.

**Comment by kartheekp-ms** [comment] 2021-08-30 19:34
Given that this issue a tracking issue to add missing test coverage, I have removed `Type:Bug` and added `Type:Test`.

I created a simple `.NET Core App` and tried to install a package passing a source option in PMC. The ouput text in the package manager window contains the expected message.

```
PM> Install-Package NUnit -Source `source uri` 
The 'Source' parameter is not respected for the transitive package management based project(s) ConsoleApp5. The enabled sources in your NuGet configuration will be used.  
```

**Comment by erdembayar** [comment] 2021-09-18 03:09
@nkolev92 @kartheekp-ms 
Today I learned all End2end tests need to move Apex test. Same reason as https://github.com/NuGet/Home/issues/11038#issuecomment-921302220 this one need another solution [maybe using dartlab](https://github.com/NuGet/Home/issues/11038#issuecomment-922168917).

**Comment by nkolev92** [comment] 2021-09-20 17:11
Apex and End2End tests are both different approaches to adding an end to end test. 
Please don't focus on the name of the test type.

The goal is to cover the scenario. 

https://github.com/NuGet/Home/issues/11187#issuecomment-908630430

Yes, the test needed here is basically that it's not respected.

**Comment by nkolev92** [comment] 2021-10-01 20:28
Package Source Mapping triage: Close this, there's sufficient coverage that `-source` does not work. This is by design currently.

**Closed as completed by nkolev92** 2021-10-01 20:28 UTC
Labels: Priority:2, Functionality:Install, Style:PackageReference, Type:Test, Area:PackageSourceMapping
