### ISSUE TITLE
nuget restore/install from unc share behaves differently from nuget install from nuget feed.

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#3297] opened 2016-08-10 23:02 UTC
Using nuget 3.5.0.1737

set tempinstall=D:_t\tmpout
rd /s/q "%tempinstall%"
md "%tempinstall%"
nuget locals -clear all
nuget install Microsoft.ProjectCop -NonInteractive -source "https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v3/index.json" -OutputDirectory "%tempinstall%" -PackageSaveMode nupkg;nuspec
dir C:\Users\%username%.nuget\packages
dir C:\Users\%username%\AppData\Local\NuGet\Cache

note the package is under C:\Users\%username%.nuget\packages

rd /s/q "%tempinstall%"
md "%tempinstall%"
nuget locals -clear all
nuget install Microsoft.ProjectCop -NonInteractive -source "\joshking-main\dump\nugetissue\b" -OutputDirectory "%tempinstall%" -PackageSaveMode nupkg;nuspec
dir C:\Users\%username%.nuget\packages
dir C:\Users\%username%\AppData\Local\NuGet\Cache

note the package is !NOT! under C:\Users\%username%.nuget\packages

**Comment by rrelyea** [comment] 2016-08-11 14:02
Please investigate/analyze.

**Comment by zhili1208** [comment] 2016-08-11 18:07
I can repro this issue, restore/install from local path or UNC share does not add packages to .nuget cache, I think this is because .nuget cache is used by v3 only before, when we merged v3 and v2, only restoring/installing from http source share the .nuget cache code path, local path/UNC share used another code path, that's why packages are not added to .nuget/packages folder

**Comment by rrelyea** [comment] 2016-08-18 19:59
Talked with Zhi about his investigation:
- Sounds like before 3.5, sources from UNC file paths would cache packages locally.
- In 3.5 rc1, we no longer cache locally.

This could be a perf issue.

Let's confirm the Packages.config and Project.json behavior.

**Comment by zhili1208** [comment] 2016-08-19 19:01
did more investigation. I was wrong before.
1. this is not related to packages.config or Project.json, only related to source type(v2, v3, UNC/local)
2. we never cache pacakges on disk for all packages from UNC/local paths. Actually we cache packages from UNC/local sources in memory before 3.5 (that's why I was wrong before, I didn't notice those cached packages are never wrote to disk)

**Comment by rrelyea** [comment] 2016-08-23 21:21
@kingerja  - restore from http is put in v3 user package cache. restore from file sources, don't get put into user package cache. by design.
Note, while testing to see if there was a change in behavior, we found a perf regression: https://github.com/NuGet/Home/issues/3355 that we are planning to address.

**Closed as completed** 2016-08-23 21:21 UTC
Labels: Product:VS.Client, Type:Bug, Product:NuGet.exe, Resolution:ByDesign
