### ISSUE TITLE
"dotnet list package --include-transitive" should ignore docker project files

### ISSUE THREAD

**Issue by WhitWaldo** [NuGet/Home#12914] opened 2023-09-30 08:13 UTC
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

I'm trying to follow the steps outlined in the [blog post](https://devblogs.microsoft.com/nuget/introducing-package-source-mapping/) for package source mapping and it suggests that I run `dotnet list package --include-transitive` to "view all top-level and transitive packages in your solution.

Mine is a solution in which every project will be built as a separate Docker container. When I ran this command, I got the message:
> The project `<my solution-dir>\docker-compose.dcproj` uses package.config for NuGet packages, while the command works only with package reference projects.

That's all fine and good - where's the list of packages? 

### Desired Behavior

If it encounters a file type it's not compatible with, skip it and keep searching. Instead I get a warning that it's incompatible (and can't do anything about it as I otherwise need the file) and also get no outputs providing me with the desired list.

Further, there should be some way to write this list directly from the command into the nuget.config file in the root of the directory I'm running the command from.

### Additional Context

As it stands, I've got too many projects in this solution to try running that command one at a time, so I'm just going to have to pass on fully implementing the package source mapping.  Please address the above issue so I might take full advantage of this handy functionality.

Thank you!

**Comment by Nigusu-Allehu** [comment] 2023-10-04 17:48
Thank you for bringing this to our attention.  The order of projects in the solution file (.sln file) plays a role, affecting which projects the command executes for. As a result, sorting them in a way such that `<my solution-dir>\docker-compose.dcproj` is the last project in the list would avoid the problem.  we will take your feedback and work on it, thank you! 
Related issue : https://github.com/NuGet/Home/issues/12520

Regarding your suggestion to write the list directly into nuget.config, to better address this and gather all necessary specifics, could you kindly raise a separate issue detailing this request?

**Comment by nkolev92** [comment] 2023-10-09 20:50
Duplicate of https://github.com/NuGet/Home/issues/12520.

**Closed as not planned** 2023-10-09 20:50 UTC
Labels: Resolution:Duplicate, Type:DCR, Product:dotnet.exe, Functionality:ListPackage
