### ISSUE TITLE
NuGet client tools strategy with multiple feeds on packages with version floats

### ISSUE THREAD

**Issue by djfr** [NuGet/Home#8992] opened 2020-01-03 11:25 UTC
## Details about Problem

NuGet product used: NuGet.exe
NuGet version: NuGet 5.4.0 x64

OS version: windows 10 v1909

## Other suggested things

It's becoming more, and more frequent to use floating package references on .Net Core projects, especially when paired with CI/CD it unburdens developers from the package bumps to the latest.

Currently the NuGet [PackageDownloader](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/PackageDownloader.cs) will download from the [fastest feed that matches the package ID](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/PackageDownloader.cs#L124), this behaviour works well when the version isn't floated, but can frequently cause problems when versions are floated. What happens right now is this:

Project targets `Newtonsoft.Json` version '*'.
NuGet feed configuration is:
- Feed 1 contains `Newtonsoft.Json` version 3.1
- Feed 2 is nuget.org

The current NuGet clients tools will add the fastest response for `Newtonsoft.Json`, and if Feed 1 wins it will add version 3.1 to the project - most likely to happen, because nuget.org is tipically slower then ADO or MyGet feeds.

The desired behaviour, is that when a version is floated, all feeds should be scanned and the highest version added to the project.

**Comment by rrelyea** [comment] 2020-01-03 16:25
The behavior you expect is what I believe happens. Can you test your repro with other versions of nuget to see if you see this problem in older versions too.
Also, can you build a minimal repro project and give us details of your feeds, etc..

**Comment by nkolev92** [comment] 2020-01-03 19:02
The PackageDownloader you linked is not used in PackageReference. 

Instead the logic in NuGet.DependencyResolverCore is used, https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.DependencyResolver.Core/ResolverUtility.cs#L367. 

Basically when a version is floating, we wait for all the sources to respond. 

Given all this, what you are seeing is a duplicate of https://github.com/NuGet/Home/issues/8432, which was fixed in https://github.com/NuGet/NuGet.Client/pull/3079. 

The fix is in 5.5. 

You can use 5.5-preview1 to confirm https://dist.nuget.org/win-x86-commandline/v5.5.0-preview1/nuget.exe. 

msbuild.exe should be unafffected by this bug, so that's another option you have.

**Closed as completed** 2020-03-18 22:53 UTC
Labels: Resolution:Duplicate, Type:Bug, Product:NuGet.exe, Functionality:Restore, Style:PackageReference
