### ISSUE TITLE
Experiencing very slow install/update performance with hosted v2 feeds in package manager v3.1.x

### ISSUE THREAD

**Issue by sirkirby** [NuGet/Home#1189] opened 2015-08-14 21:22 UTC
I have several feeds hosted on myget as well as my appveyor CI server. Since moving to nuget package manager v3.1.x in 2015, package installation and updates from my feeds have been dramatically slower. I've seen the issues referencing slowness related to using the public v2 feed in v3 of nuget package manager, so i'm assuming the same would apply with my private v2 feeds as well. Is the only current work around moving to api v3 for my hosted feeds? Just looking for more insight. Thanks.

**Comment by yishaigalatzer** [comment] 2015-08-18 20:31
The major change in V3 that might be affecting you is that we now go to all feeds to find packages. This fixes several issues with correct package resolution when installing.

Its not about V2 being slower (it is not), its about the myget feeds being kinda slow.
Potential fixes are in myget becoming faster, or by using something like a proxy. I've heard from others about ProGet (paid) or klondike project from motleyfool, but haven't really tried any of them.

I hope this helps. I'm closing this issue as there is no further action here, feel free to keep asking questions on the closed issue, it is still monitored.

**Closed by yishaigalatzer** 2015-08-18 20:31 UTC

**Comment by sirkirby** [comment] 2015-08-18 20:39
Thanks for the insight @yishaigalatzer . I'm actively working with myget on the issue as well, so I will pass this along.

**Comment by xavierdecoster** [comment] 2015-08-19 14:45
@sirkirby is having performance issues with both MyGet as well as AppVeyor in VS2015, where in VS2013 he did not have these issues. Looking at #1101 this seems "by design" for V2 feeds.

Having said that, @sirkirby can you try out MyGet's experimental V3 support? URL format would be https://www.myget.org/F/feedname/api/v3/index.json (note that for private feeds there is another open issue #1216)

**Comment by sirkirby** [comment] 2015-08-19 16:15
@xavierdecoster will do. I'm switching mine over today in visual studio as well as a few team members running vs2015. I'll also update a few build plans on my CI server to use the new experimental v3 support as well and report back.
