### ISSUE TITLE
Framework precedence is different between PCLs and concrete frameworks

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#6483] opened 2018-01-24 21:46 UTC
I noticed this problem when examining an issue with one of our packages and wanted to raise the issue.

For portable profiles, NuGet considers other PCL profiles as more compatible than netstandard, whereas for concrete frameworks (like net45) NuGet considers NETStandard among the portable profiles.  The result is different asset/dependency selection when a package is used in a PCL vs when it is used in a framework that supports that PCL framework.

Consider a package that has two assets: one is `portable-net45+win8+wp8+wpa81` and the other is `netstandard1.1`.

When this package is used in a PCL project `portable-net45+win8+wpa81` the `portable-net45+win8+wp8+wpa81` asset is selected, however when it is used in a `net45` project the `netstandard1.1` asset is selected, even though both projects support both of the package's frameworks.

You can visualize the difference by comparing the order of the precedence for frameworks for the two project types: [net45](http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/framework-precedence?framework=net45&exludedIdentifiers=) vs [portable-net45+win8+wpa81](http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/framework-precedence?framework=portable-net45%2Bwin8%2Bwpa81&exludedIdentifiers=).

This breaks the transitive property of compatibility that NuGet is expected to maintain.

**Comment by jainaashish** [comment] 2018-01-27 06:45
I'm not sure what's the expectation here? Isn't PCL a thing of past? and going forward, all portable libraries will be net standard. Also, looking at both projects separately feels that the behavior correct, since both are different frameworks which are compatible with each other at some level but not are same. And NuGet tries to pick the nearest compatible item. Even if we had to change it, which framework precedence will need to be changed?

**Comment by ericstj** [comment] 2018-01-29 16:52
I think its too late to change anything here, but I do think we should try to follow a rule in the future.

When framework A and B are both compatible with frameworks C and D and framework A is compatible with B, then C and D should appear in the same order for both framework A and B.

That is:
A > B > C > D
and B > C > D

Today NuGet does
A > B > C > D
and B > D > C

The result is that if a package contains assets for both C and D, where D is noticeably different than C, someone can consume that package in a framework B project (using D) but then get broken when referenced by framework A (where they get C instead)

In that sense we should have interleaved the NETStandard frameworks in the PCL profiles just like they were done in the concrete frameworks.

**Comment by jainaashish** [comment] 2018-01-29 19:28
Makes sense! will add this to my our framework compatibility check for future reference and guideline. Closing this issue as by design for now.

**Closed as completed by jainaashish** 2018-01-29 19:28 UTC
Labels: Resolution:ByDesign
