### ISSUE TITLE
NuGet restore for large solution is much slower in 4.8.1 vs. 3.5.0 due to MSBuild step

### ISSUE THREAD

**Issue by ScotSalmon** [NuGet/Home#7690] opened 2019-01-12 04:32 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.8.1.5435

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): 2017

OS version (i.e. win10 v1607 (14393.321)): win10 v1803 (17134.472)

Worked before? If so, with which NuGet version: 3.5.0.1996

## Detailed repro steps so we can see the same problem

In current versions of NuGet.exe, a restore operation with nothing to do (all packages are already restored) checks both the old-style packages.config files and the new PackageReferences. The enumeration of PackageReferences requires an MSBuild operation that was not required for the packages.config enumeration. For our large solution (400+ assemblies) that only uses packages.config files, a "no-op" restore takes about 17 seconds in NuGet 4.8.1, vs. under 1 second in 3.5.0.

I have a pull request I'll link shortly that adds a flag to skip the MSBuild step for projects like ours that don't need it.

### Verbose Logs

No interesting errors in the log. You just see the msbuild command start, and 17 seconds later finish.

### Sample Project

Only very large solutions reproduce the issue, so attaching an example is somewhat impractical.

**Comment by jainaashish** [comment] 2019-01-15 23:15
There could be multiple ways to do this but at the end, I agree there shouldn't be an MSBuild evaluation if all the projects in a solution are `packages.config` so this will be a good improvement for legacy solutions continue to have the same performance with newer versions of nuget.

**Comment by nkolev92** [comment] 2020-05-19 20:39
Duplicate of https://github.com/NuGet/Home/issues/8791. 

Static Graph restore has brought in significant improvements in the restore code-paths, cutting msbuild evaluation times even ten fold for solutions with 100+ projects.

**Closed as completed by nkolev92** 2020-05-19 20:39 UTC
Labels: Resolution:Duplicate, Type:Bug, Tenet:Performance, Functionality:Restore, Style:Packages.Config
