### ISSUE TITLE
Restoring packages with GitHub Package Repository configured generates warnings

### ISSUE THREAD

**Issue by jirikopecky** [NuGet/Home#8646] opened 2019-09-30 19:50 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe, dotnet restore and Visual Studio

NuGet version (x.x.x.xxx): 5.3.0.6260

dotnet.exe --version (if appropriate): 3.0.100

VS version (if appropriate): 16.3.1

OS version (i.e. win10 v1607 (14393.321)): Win10 v1903 (18362.356) and Linux Docker container (sdk:3.0-alpine)

Worked before? If so, with which NuGet version: first try at this

## Detailed repro steps so we can see the same problem

1. Configure solution to use GitHub package repository via nuget.config
2. Add package references to the project (for example to Newtonsoft.Json)
3. Restore the project witch caches cleared
3.1. Either run `dotnet nuget locals all --clear` or build inside Docker
4. Get warning like this: `NuGet.targets(123,5): warning : NAME_UNKNOWN:Package with name 'newtonsoft.json' was not found in the package source 'organizationName' [/path/to/solution.sln]

## Other suggested things

Packages are actually restored successfully, only these warnings show up with every restore/build commands and I haven't found any way to suppress it.

### Verbose Logs

Detailed logs from Docker build of attached project
[docker-build-output.log](https://github.com/NuGet/Home/files/3672963/docker-build-output.log)

### Sample Project
Issue repro. You need to update nuget.config with GitHub PAT that can download packages.
[nuget-restore-issue-repro.zip](https://github.com/NuGet/Home/files/3672978/nuget-restore-issue-repro.zip)

**Comment by cubanx** [comment] 2019-11-25 14:47
I have the EXACT same issue. It's a shame to see it's been nearly 2 months and no response, at all :(

**Comment by sebwerner** [comment] 2019-12-04 20:36
I have the same issues as well.

**Comment by GiorgioG** [comment] 2019-12-09 17:53
Bump

**Comment by coder2000** [comment] 2020-01-13 04:50
The issue is still present.

**Comment by gilly42** [comment] 2020-01-27 12:46
Got the same Problem, ist there a way to supress this warnings?

**Comment by IGx89** [comment] 2020-01-29 20:39
This is a bug in GPR. When NuGet makes a call to the GPR server to fetch a non-existent package, it properly returns HTTP-404, just like nuget.org does. However, unlike nuget.org, it also adds a `X-Nuget-Warning` header on the response containing the exact warning message you're seeing (example: `X-Nuget-Warning: NAME_UNKNOWN:Package with name 'coverlet.msbuild' was not found in the package source 'organizationName'`). GPR is misusing that header -- according to https://github.com/NuGet/Home/wiki/%5BSpec%5D-Server-side-warnings-for-NuGet-client it should be used just for warnings and errors, which this isn't.

Solution is for the GPR devs to stop sending that header in their 404 response.

**Comment by IGx89** [comment] 2020-01-30 15:18
I've brought this up with GitHub and they have an internal issue open with their engineering team tracking this bug. No ETA yet.

**Comment by foriequal0** [comment] 2020-02-05 05:14
You might suppress these warnings by setting MSBuild properties `HideWarningsAndErrors` as true and `EmitAssetsLogMessages` as false until it is fixed.

**Comment by gilly42** [comment] 2020-02-05 17:36
Can you provide an example how to configure that? And does it disable ALL warning, include others than NuGet ones?

**Comment by foriequal0** [comment] 2020-02-06 00:47
You can just put these elements in your `.csproj` file like this:
```xml
<PropertyGroup>
  <HideWarningsAndErrors>true</HideWarningsAndErrors>
  <EmitAssetsLogMessages>false</EmitAssetsLogMessages>
</PropertyGroup>
```
or pass CLI argument like `dotnet build -p:HideWarningsAndErrors=true -p:EmitAssetsLogMessages=false`
You can confirm it by inspecting the output of `dotnet build PROJECT -pp:out.xml`. `HideWarningsAndErrors` is only used in the `Restore` target, and `EmitAssetsLogMessage` is only used in `RunResolvePackageDependencies` and `ReportAssetsLogMessages` targets. It is not used outside.

**Comment by cmcclellen** [comment] 2020-02-20 21:55
> I've brought this up with GitHub and they have an internal issue open with their engineering team tracking this bug. No ETA yet.

Any one have word on this?  Seems like something that would be simple for GPR to fix, but 20+ days later, still an issue.

**Comment by reathus** [comment] 2020-02-28 00:32
Still relevant, and annoying.

**Comment by Gustavilo** [comment] 2020-03-13 23:44
I have the same Issue, it is still present.

**Comment by gilly42** [comment] 2020-03-14 11:31
Comon. Gitlab just released nuget package support, stop me from going there.....

**Comment by nnyegaard** [comment] 2020-03-18 07:49
Doing what @foriequal0 suggested and that worked. So `dotnet publish "Foo.sln" -c Release -p:HideWarningsAndErrors=true -p:EmitAssetsLogMessages=false -o out`

**Comment by lawsonAGMT** [comment] 2020-03-31 14:56
Same issue

**Comment by acordiner92** [comment] 2020-04-09 08:17
also same here

**Comment by Zastai** [comment] 2020-04-13 16:59
Another workaround, which does not potentially hide relevant warnings/errors:
- comment out the GPR source in NuGet config
- run `dotnet build` (or possibly just `dotnet restore`)
  - this should not give the warning
- re-enable the GPR source
- further builds should be fine again, at least until the local package cache is cleared again

**Comment by jcansdale** [comment] 2020-04-21 08:42
This has now been fixed at the GitHub Packages end!

Build before the fix was deployed:

![image](https://user-images.githubusercontent.com/11719160/79843082-a80b8a00-83b1-11ea-945a-de61ac612834.png)

...buld after:

![image](https://user-images.githubusercontent.com/11719160/79843122-b6f23c80-83b1-11ea-88ca-0ded5219c808.png)

Looks like it's working! 🎉 

@jirikopecky could you confirm and close this issue if you agree? 🙏

**Comment by anangaur** [comment] 2020-04-28 14:01
I have forwarded the issue to GitHub folks. But I also see it seems to have been fixed. @jirikopecky can you confirm if your issue has been fixed?

**Comment by jirikopecky** [comment] 2020-04-28 14:40
Hello, I am currently out of office. I will be able to verify it in the week of 11th May

**Comment by jirikopecky** [comment] 2020-05-11 13:17
Hello, I can confirm that the issue have been fixed. Thanks for your help!

**Closed as completed** 2020-05-11 14:07 UTC
Labels: Priority:2, Type:Bug, Resolution:External
