### ISSUE TITLE
[QUESTION] How to use NuGet packages in a C++/CLI project?

### ISSUE THREAD

**Issue by levicki** [NuGet/Home#10653] opened 2021-03-11 15:45 UTC
I have a C++/CLI project which uses both native and managed code.

It is a common pattern where you have a native class implementation with core functionality, and a managed class exposed to external C# code. This managed class needs to use .Net NuGet packages, not native ones.

In Visual Studio 2019 16.9.0 when I try to add a NuGet package such as PCSC or NLog or Newtonsoft.Json to a C++/CLI project I am getting an error:
```
Could not install package 'PCSC 5.0.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```
In the project I am already providing the correct target for managed code:

![image](https://user-images.githubusercontent.com/16415478/110812557-01113480-8288-11eb-83ba-5fde0a1ff009.png)

Is there a way to override NuGet behavior for C++/CLI projects, apart from installing/restoring the package manually as a pre-build step using command line, and then specifying the package reference in the `.vcxproj` file (either manually or by using Add reference -> Browse):
```
<Reference Include="PCSC">
<HintPath>..\packages\PCSC.5.0.0\lib\net40\PCSC.dll</HintPath>
</Reference>
```
If there is no way to do that, then this issue should be considered a feature request instead of a question.

**Comment by zkat** [comment] 2021-03-18 17:14
This is something we're actively working on. Closing as duplicate of https://github.com/NuGet/Home/issues/10194, which you can track for more details (and discuss further if needed)

**Closed as completed by zkat** 2021-03-18 17:14 UTC
Labels: Functionality:Restore, Style:Packages.Config
