### ISSUE TITLE
Wrongly resolved transitive references with centrally managed package versions

### ISSUE THREAD

**Issue by joeltankam** [NuGet/Home#10578] opened 2021-02-18 11:59 UTC
## Details about Problem

There seems to be an incorrect behavior regarding the resolution of transitive NuGet package references (not explicitly mentioned in the project file) when using centrally managed package versions (https://github.com/NuGet/Home/issues/6764).

`dotnet.exe` (.NET SDK) version is `5.0.101`.
The problem has also been encountered with `MSBuild.exe` versions `16.7.3`, `16.8.2`, `16.8.3`, and `16.8.5`.

Consider we have a C# project (`ProjectA`). This project depends on a project (`ProjectB`) as well as a package (`Package1`) that depends on another package (`Package2`) not mentioned in the project file: 

```
ProjectA <- ProjectB
    ^
    +------ Package1 <- Package2

// (where A <- B means that A depends on B).
```

We are trying to apply custom metadata to `Package1` resolution, say `ExcludeAssets=runtime`. The status quo is to apply these metadata to all its references, transitively.

## Repro steps and/or sample project

Using the metadata mentioned above, `ExcludeAssets=runtime` applied on `Package1`, we expect `Package2` resolution to also exclude `runtime` assets, Or at least this is currently the case when not using centrally managed package versions:

ProjectA.cspoj
```xml
<PackageReference Include="Package1" Version="2.0.0" ExcludeAssets="runtime" />
```

Command
```
dotnet restore
```

project.assets.json (`ProjectA`)
```json
"Package1/2.0.0": {
  "type": "package",
  "dependencies": {
    "Package2": "2.0.0"
  },
  "compile": {
    "ref/netstandard2.0/Package1.dll": {}
  },
  "runtime": {
    "lib/netstandard2.0/_._": {}
  }
},
"Package2/2.0.0": {
  "type": "package",
  "compile": {
    "ref/netstandard2.0/Package2.dll": {}
  },
  "runtime": {
    "lib/netstandard2.0/_._": {}
  }
}
```

In comparison, the behavior with centrally managed package versions is:

Command
```
dotnet restore -p:ManagePackageVersionsCentrally=true
```

project.assets.json (`ProjectA`)
```diff
"Package1/2.0.0": {
  "type": "package",
  "dependencies": {
    "Package2": "2.0.0"
  },
  "compile": {
    "ref/netstandard2.0/Package1.dll": {}
  },
  "runtime": {
    "lib/netstandard2.0/_._": {}
  }
},
"Package2/2.0.0": {
  "type": "package",
  "compile": {
    "ref/netstandard2.0/Package2.dll": {}
  },
  "runtime": {
-   "lib/netstandard2.0/_._": {}
+   "lib/netstandard2.0/Package2.dll": {}
  }
}
```

It appears that this is due to the fact that, when using centrally managed package versions, `Package1` is wrongly mentioned as a dependency of `ProjectB` (therefore its dependencies are transitively resolved) even if `ProjectB` does not depend on any package:

project.assets.json (`ProjectA`)
```diff
"ProjectB/1.0.0": {
  "type": "project",
  "framework": ".NETStandard,Version=v2.0",
+ "dependencies": {
+   "Package1": "2.0.0"
+ },
  "compile": {
    "bin/placeholder/ProjectB.dll": {}
  },
  "runtime": {
    "bin/placeholder/ProjectB.dll": {}
  }
}
```

https://github.com/joeltankam/central-packages-sample repository showcase this with `Package1` being `System.Reflection.Emit.Lightweight` and `Package2` being `System.Reflection.Emit.ILGeneration`.

**Comment by nkolev92** [comment] 2021-02-22 21:24
@donnie-msft Can you please try to repro the problem on the latest version (5.9). 

Note that the OP has a repro repo.

**Comment by joeltankam** [comment] 2021-02-27 20:26
Any news on this please?

**Comment by donnie-msft** [comment] 2021-02-28 03:45
@nkolev92 I cloned the sample repro, tried dotnet restore (**SDK Version: 5.0.200-preview.21077.7**) both with and without CPVM flag, and diff'd the assets file.
Both restores generated the same "runtimes", example:
```
"runtime": {
         "lib/netstandard2.0/_._": {}
 }
```

CPVM restore added this entry:

```
 "centralPackageVersions": {
             "System.Reflection.Emit.Lightweight": "[4.7.0, )"
           },
```

**Comment by joeltankam** [comment] 2021-02-28 11:10
That's weird, I just tried again with the latest SDK version, **5.0.103**.

```diff
      "System.Reflection.Emit.ILGeneration/4.7.0": {
        "type": "package",
        "compile": {
          "ref/netstandard2.0/System.Reflection.Emit.ILGeneration.dll": {}
        },
        "runtime": {
-         "lib/netstandard2.0/_._": {}
+         "lib/netstandard2.0/System.Reflection.Emit.ILGeneration.dll": {}
        }
      },
``` 

Note that the diff occurs on **System.Reflection.Emit.ILGeneration** not `System.Reflection.Emit.Lightweight`.
Did anything change in SDK `5.0.200-preview.21077.7` in that regard? 

Thanks.

**Comment by joeltankam** [comment] 2021-02-28 11:26
Full diff

```
"C:\Program Files\KDiff3\bin\diff.exe" .\project.assets.json .\project.assets.CPVM.json

35c35
<           "lib/netstandard2.0/_._": {}
---
>           "lib/netstandard2.0/System.Reflection.Emit.ILGeneration.dll": {}
52a53,55
>         "dependencies": {
>           "System.Reflection.Emit.Lightweight": "4.7.0"
>         },
347a351
>       "centralPackageVersionsManagementEnabled": true,
388c392,393
<             "version": "[4.7.0, )"
---
>             "version": "[4.7.0, )",
>             "versionCentrallyManaged": true
390a396,398
>         "centralPackageVersions": {
>           "System.Reflection.Emit.Lightweight": "[4.7.0, )"
>         },
```

[project.assets.json](https://github.com/NuGet/Home/files/6056709/project.assets.json.txt)
[project.assets.CPVM.json](https://github.com/NuGet/Home/files/6056711/project.assets.CPVM.json.txt)

**Comment by donnie-msft** [comment] 2021-03-01 17:02
> Note that the diff occurs on System.Reflection.Emit.ILGeneration not System.Reflection.Emit.Lightweight.

That was just an example, but here's the Generation package as well (no diff for me):
```
"System.Reflection.Emit.ILGeneration/4.7.0": {
          "type": "package",
          "compile": {
            "ref/netstandard2.0/System.Reflection.Emit.ILGeneration.dll": {}
          },
          "runtime": {
            "lib/netstandard2.0/_._": {}
          }
        },
```

> Did anything change in SDK 5.0.200-preview.21077.7 in that regard?

@nkolev92 could answer that best.

**Comment by nkolev92** [comment] 2021-03-01 19:07
I think transitive pinning was disabled in https://github.com/NuGet/NuGet.Client/commit/087a7113ad70ae4d4c538eba0f387271af0c649b, and that might the cause of the discrepancy.

**Comment by zkat** [comment] 2021-03-04 18:13
Closing because this doesn't repro anymore in net5.0

**Closed as completed by zkat** 2021-03-04 18:13 UTC
Labels: Resolution:NotRepro, Functionality:Restore, Area:RestoreCPM, Area:RestoreCPMTransitiveDependencies

**Comment by KirillOsenkov** [comment] 2021-07-22 18:58
Hey @joeltankam this is random and unrelated, but I made a highly scientific poll about the directionality of the dependency arrows in your diagram:
https://twitter.com/KirillOsenkov/status/1418272045880672260

It's interesting that in your mental model the directionality is from the dependency to the dependent. Not saying it's wrong, just seems that the majority of people seem to gravitate to the opposite.

**Comment by joeltankam** [comment] 2021-07-22 22:59
> It's interesting that in your mental model the directionality is from the dependency to the dependent. Not saying it's wrong, just seems that the majority of people seem to gravitate to the opposite.

I am only realizing now that the majority of people are indeed gravitating to the opposite 😅
