### ISSUE TITLE
dotnet restore fails restore DotNetCliToolReference items across P2Ps at some Drive Letters

### ISSUE THREAD

**Issue by verysimplenick** [NuGet/Home#5941] opened 2017-09-26 13:57 UTC
Hi, this issue related with #5039 

## Details about Problem
nugget.target can't restore packages with message:
```
q:\ef_core_tmp\Project.Tests\Project.Tests.csproj : error NU1105: Unable to find project information for 'q:\ef_core_tmp\Project.Core\Project.Core.csproj'. The project file may be invalid or missing targets required for restore. [q:\ef_core_tmp\Project.sln]
q:\ef_core_tmp\Project\Project.csproj : error NU1105: Unable to find project information for 'q:\ef_core_tmp\Project.Core\Project.Core.csproj'. The project file may be invalid or missing targets required for restore. [q:\ef_core_tmp\Project.sln]
```
But same code can be builded then placed in system drive or drive `E`.

![default](https://user-images.githubusercontent.com/922660/30863548-fe3a7834-a2d9-11e7-828a-bd1b74b77b87.png)

```
dotnet --info
.NET (2.0.2-vspre-006949)

Product Information:
 Version:            2.0.2-vspre-006949
 Commit SHA-1 hash:  23fc6ec23d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2-vspre-006949\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

## Detailed repro steps so we can see the same problem

1. Place project root at drive `Q:` (it's not subst drive)
1. Create project with DotNetCliToolReference exp.: Project.Core
1. Create project with ProjectReference to this project exp.: Project
1. Try build solution with this references

## Other suggested things
Something breaking with nuget restore or msbuild csproj parser while using p2p reference with `DotNetCliToolReference`, if I commented this line, solution builds fine. Project.Core builds fine all time, with or without `DotNetCliToolReference `.

### Sample Project
[ef_core_tmp.zip](https://github.com/NuGet/Home/files/1333405/ef_core_tmp.zip)

Try place this project in different drives.

**Comment by mishra14** [comment] 2017-09-28 00:50
@verysimplenick: Thanks for the detailed issue. I could not repro this on a subst drive - 

```
Q:\ef_core_tmp>dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Project.Core -> Q:\ef_core_tmp\Project.Core\bin\Debug\netcoreapp2.0\Project.Core.dll
  Project.Tests -> Q:\ef_core_tmp\Project.Tests\bin\Debug\netcoreapp2.0\Project.Tests.dll
  Project -> Q:\ef_core_tmp\Project\bin\Debug\netcoreapp2.0\Project.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:10.26

Q:\ef_core_tmp>
```

Could you please run the following command and attach the resulting file (a.dg) here? - 

```
Q:\ef_core_tmp>dotnet msbuild /t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=a.dg
```

**Comment by verysimplenick** [comment] 2017-09-28 06:11
@mishra14 
Thanks for respone, I create 2 graph files, from disk C and disk Q, they are different.
[restore_graphs.zip](https://github.com/NuGet/Home/files/1339651/restore_graphs.zip)
p.s. my disk Q is real partition.

**Comment by verysimplenick** [comment] 2017-10-02 11:16
News? Help needed?

**Comment by rrelyea** [comment] 2017-10-02 19:39
@mishra14  - can you peek at that.

**Comment by mishra14** [comment] 2017-10-03 00:28
@verysimplenick I took a peek and it seems possible that we have a bug where the order of references can cause a probelm. In your case, the tool name starts with `M` and thus if the projects are in drive `Q:`, the tool comes before the projects in the dependency graph files. 

Current work around: Use a drive with lower letter than M. 

Status: Still investigating to find the root cause.

**Comment by mishra14** [comment] 2017-10-04 19:59
Update: I was able to confirm that this is caused by ordering in the assets file. I am working on a fix for this.

**Closed as completed** 2017-10-17 19:34 UTC
Labels: Product:NuGet.exe, Functionality:Restore

**Comment by nkolev92** [comment] 2017-10-17 19:36
Fixed by @mishra14 in https://github.com/NuGet/NuGet.Client/pull/1731

**Comment by verysimplenick** [comment] 2017-10-30 12:15
I confirm this. Fixed :)
Thanks @mishra14
