### ISSUE TITLE
[Accessibility][VS Feedback]: NuGet UI not Screen Reader Compliant 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#5847] opened 2017-09-05 18:32 UTC
Comment from a user on FEEDBACKTICKET 452431, unrelated to this.

```
 Its also not "Screen reader compliant" because it doesnt remove the search criteria when changing any other filters.
```

Basically the user is suggesting that changing the package source in the dropdown menu should reset the search term. 

This falls under the accesibility tenet. 
//cc
@rrelyea

**Comment by StingyJack** [comment] 2017-09-05 18:52
To be clear I dont want it to remove the search criteria when changing subfilter elements like package source. That makes it _less_ accessible because it _adds_ work regardless of sightedness. 

I'm disputing the response of "working as designed" because its both not working as _expected_ and its not working consistently per https://developercommunity.visualstudio.com/content/problem/56255/extensions-and-updates-search-is-getting-cleared-w.html ,

**Comment by donnie-msft** [comment] 2020-11-03 05:49
Tested Narrator in Version 16.9.0 Preview 2.0 [30701.28.main] and changing tabs does read the search term on the new tab.
Closing due to no repro.
Also, I will be changing this behavior so that Browse search term is independent of Installed/Updates/Consolidate search terms: https://github.com/NuGet/Home/issues/10148

**Closed as completed by donnie-msft** 2020-11-03 05:49 UTC
Labels: Product:VS.Client, Resolution:NotRepro, Functionality:VisualStudioUI, Triage:Investigate, Tenet:Accessibility

**Comment by StingyJack** [comment] 2020-11-03 17:04
> Also, I will be changing this behavior so that Browse search term is independent of Installed/Updates/Consolidate search terms:

NICE!
