### ISSUE TITLE
ResolveNuGetPackageAssets does not preserve PrivateAssets metadata

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#5369] opened 2017-06-08 13:47 UTC
When resolving references from nuget packages, the resulting items look like:

```
C:\Users\kzu\.nuget\packages\Mono.Options\4.4.0\lib\net4-client\Mono.Options.dll
    NuGetIsFrameworkReference = false
    NuGetPackageId = Mono.Options
    NuGetPackageVersion = 4.4.0
    NuGetSourceType = Package
    Private = false
```

For a package reference like:

```
    <PackageReference Include="Mono.Options" Version="4.4.0.0" PrivateAssets="all" />
```

After `ResolveAssemblyReference`, such a dependency looks like:

```
C:\Users\kzu\.nuget\packages\Mono.Options\4.4.0\lib\net4-client\Mono.Options.dll
    ReferenceAssembly = %(FullPath)
    ResolvedFrom = {RawFileName}
    CopyLocal = false
    FusionName = Mono.Options, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null
    ImageRuntime = v4.0.30319
    NuGetPackageId = Mono.Options
    NuGetPackageVersion = 4.4.0
    Private = false
    NuGetIsFrameworkReference = false
    NuGetSourceType = Package
    OriginalItemSpec = C:\Users\kzu\.nuget\packages\Mono.Options\4.4.0\lib\net4-client\Mono.Options.dll
    Version = 4.0.0.0
    ReferenceSourceTarget = ResolveAssemblyReference
```

This makes it virtually impossible to determine from those resolved references which ones are from a nuget package as private assets and which ones aren't private assets.

**Comment by emgarten** [comment] 2017-06-08 17:59
`PrivateAssets` allows NuGet to filter assets out when writing project.assets.json. For the project the asset either exists or it doesn't exist. 

To add a new feature that persisted metadata from the nuspec all the way to the reference in msbuild would require NuGet to add this extra information into project.assets.json and the SDK build tasks (there are two currently) to read this information from project.assets.json and add it into the references it creates.

**Comment by kzu** [comment] 2017-06-08 21:10
Yes, those are the required changes. 

FWIW, this is a must if you need to tell apart referenced artifacts from private assets vs regular copy local assemblies (i.e. for Pack).

**Comment by emgarten** [comment] 2017-06-08 21:24
> FWIW, this is a must if you need to tell apart referenced artifacts from private assets vs regular copy local assemblies (i.e. for Pack).

`PrivateAssets` controls whether or not an asset type flows transitively to parent projects. It is unrelated to copy local.

**Comment by kzu** [comment] 2017-06-09 00:46
The flow (or lack thereof) needs to be evident to external analysis (i.e. for pack of private assets).

/cc @mhutch

**Comment by kzu** [comment] 2017-06-09 15:36
@emgarten @rohit21agrawal how does SDK Pack deal with https://github.com/NuGet/Home/issues/5103 without this info?

**Comment by emgarten** [comment] 2017-06-09 16:44
Pack reads IncludeAssets, ExcludeAssets, and PrivateAssets to find the set of include flags. These are then added to the dependency elements in the nuspec.

There isn't a scenario where a nupkg is creating that includes assets from dependency packages, so knowing exactly which assemblies came through which references isn't needed.

@kzu could you explain a bit more about the nugetizer scenario here and why it needs to handle this differently?

**Comment by emgarten** [comment] 2017-06-09 16:47
From https://github.com/NuGet/Home/issues/5103

> if the project has PackageReferences with PrivateAssets=lib, then those references are copied to the output directory

NuGet doesn't have a PackageReference attribute to control copy to output true/false.  PrivateAssets is not related to the Private attribute on reference elements.

**Comment by kzu** [comment] 2017-06-12 04:32
I'll let @mhutch elaborate since she's driving the requirement. See https://github.com/NuGet/Home/issues/5103

**Comment by mhutch** [comment] 2017-06-13 18:06
The use case here is that I am building a package that contains MSBuild targets and tasks. The project references a NuGet package using `PrivateAssets="all`. The dll from the referenced NuGet package ends up in the output folder, however NuGetizer doesn't recognize it as project output, so it's not included in _my_ package even though it's needed by my tasks assembly.

I confirmed that the resolved references are not marked Private/CopyLocal. However, they _are_ copied by the `_CopyFilesMarkedCopyLocal` task. This is because the NuGet `ResolveNuGetPackageAssets` task [explicitly added them as `ReferenceCopyLocalPaths` items](https://github.com/NuGet/NuGet.BuildTasks/blob/057af5b6ff9521551cf6dcee5cd737993a943472/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs#L341).

@kzu maybe NuGetizer could pick up `ReferenceCopyLocalPaths` items?

**Comment by kzu** [comment] 2017-06-19 13:07
@mhutch we're doing that already, but it would be nice to have the relevant metadata in there, instead of resorting to "private" item groups and package reference inspection. See https://github.com/NuGet/NuGet.Build.Packaging/commit/5141dcbef524bdc11c0393a057eb25abf1007df3

**Comment by mhutch** [comment] 2017-06-28 16:21
So it looks the workaround doesn't work for transitive package dependencies, since there's no PackageReference for the dependency.

@emgarten I'm not sure what we should be doing in this case. Can you suggest any solutions?

**Comment by mishra14** [comment] 2017-11-30 00:41
Closing as PrivateAssets do not have any meaning for assemblies. It is a package level concept.

**Closed as completed by mishra14** 2017-11-30 00:41 UTC
Labels: Functionality:Restore
