### ISSUE TITLE
"Dependencies" overlaps "Tags" in PM UI on dev16 (VS 2019)

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#7847] opened 2019-03-01 23:39 UTC
dev16:

![image](https://user-images.githubusercontent.com/94054/53672652-4ed61980-3c38-11e9-8483-f62fb91c2369.png)

dev15:

![image](https://user-images.githubusercontent.com/94054/53672566-f9017180-3c37-11e9-859f-506b1a34abb1.png)

# Repro:

Feed: https://dotnet.myget.org/F/nuget-build/api/v2
Package: CopyAzureContainer

# Client info:

VS 16.0.0 Preview 4.0 (dogfood) - 28627.160.d16.0
NuGet Version: 5.0.0.5856

**Comment by nkolev92** [comment] 2019-03-05 19:12
@joelverhagen Do you see this consistently? 

I don't see problems on my end, and we haven't really had any changes on our end, so I'd imagine something got pulled from beneath us.

**Comment by joelverhagen** [comment] 2019-03-05 19:14
Yes, I saw it consistent on that feed and package. It perhaps has to do with one of those fields being empty or missing in the nuspec.

**Comment by nkolev92** [comment] 2019-03-05 19:18
Duplicate of https://github.com/NuGet/Home/issues/7816.

**Closed as completed by nkolev92** 2019-03-05 19:18 UTC
Labels: Resolution:Duplicate, Functionality:VisualStudioUI

**Comment by nkolev92** [comment] 2019-03-15 21:26
@joelverhagen Are you still able to reproduce this?

**Comment by joelverhagen** [comment] 2019-03-15 21:29
All good now!

![image](https://user-images.githubusercontent.com/94054/54462972-be670100-472e-11e9-9a73-47375faa90ce.png)
