### ISSUE TITLE
Adding attributes to control nuget dependencies break the project properties tab

### ISSUE THREAD

**Issue by jmelosegui** [NuGet/Home#1831] opened 2015-12-14 01:22 UTC
Having the following solution structure.

![image](https://cloud.githubusercontent.com/assets/450246/11770790/37275ed0-a1d5-11e5-83f7-687cd15d95bd.png)

I want to propagate the `StyleCop.Analyzers` package to all the project depending on `ClassLibrary5`. So I created the following project.json file.

```
{
  "supports": { },
  "dependencies": {
    "StyleCop.Analyzers": {
      "version": "1.0.0-rc2",
      "suppressParent": "none"
    }
  },
  "frameworks": {
    ".NETPortable,Version=v4.5,Profile=Profile111": { }
  }
}
```

After adding the `StyleCop.Analyzers` and specifying  a json object as a value 

```
{
  "version": "1.0.0-rc2",
  "suppressParent": "none"
}
```

Any project referencing the `ClassLibrary5` project will have a the warning 

```
The project 'ClassLibrary5' cannot be referenced.           
```

and the property windows for `ClassLibrary5` project  will show the following error

![image](https://cloud.githubusercontent.com/assets/450246/11770807/aeb41a56-a1d5-11e5-922c-28b30f378904.png)

As soon as I modify the project.json file to.

```
{
  "supports": { },
  "dependencies": {
    "StyleCop.Analyzers": "1.0.0-rc2"
  },
  "frameworks": {
    ".NETPortable,Version=v4.5,Profile=Profile111": { }
  }
}
```

_(Notice the dependency value is a string value and not a json object)_ everything started working again but nuget dependecies do not propagate any more and I have to explicitly add the package in every project in my solution.

**Visual Studio version: 14.0.24720.00 Update 1**
**NuGet Package Manager version: 3.3.0**

**Comment by AArnott** [comment] 2015-12-14 02:29
I suspect this is actually a bug owned by the C#/VB project system team. @jasonmalinowski, can you confirm?

**Comment by jasonmalinowski** [comment] 2015-12-14 18:50
I'm not sure. I cannot imagine any path where the app designer would fail to load because of an JSON parsing issue...somebody is just going to have to debug this one.

**Comment by yishaigalatzer** [comment] 2015-12-14 22:17
Trying to find the owner of this area.

CC @emgarten @pilchie

**Comment by Pilchie** [comment] 2015-12-14 22:20
Is classlibrary5 (the one where the app designer fails), a portable library?  cc @rchande

**Comment by yishaigalatzer** [comment] 2015-12-14 22:37
The picture says it is

**Comment by Pilchie** [comment] 2015-12-14 22:47
Also, is this on VS2015 RTM or Update1?  I thought @rchande fixed something to do with unrecognized schema stuff in Portable as part of U1.

**Comment by Pilchie** [comment] 2015-12-19 02:20
@jmelosegui do you have Visual Studio Update 1 installed?  If not, can you try installing it and see if this still repros?

**Comment by jmelosegui** [comment] 2015-12-19 02:23
Yes I do. Please, read the end of the original post.

**Comment by Pilchie** [comment] 2015-12-19 02:40
Sorry for missing that.  @rchande can you take a look at the project properties issue?

@jasonmalinowski can you look at "Any project referencing the ClassLibrary5 project will have a the warning: `The project 'ClassLibrary5' cannot be referenced.`"?

@yishaigalatzer / @emgarten  / @davidfowl : what is `suppressParent` and how does it affect the lock file?

**Comment by AArnott** [comment] 2015-12-19 03:11
@Pilchie you can read about `suppressParent` [here](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets)

**Comment by Pilchie** [comment] 2015-12-19 03:23
Okay, but flowing the dependency transitively is the default, so the entry shouldn't be needed for @jmelosegui's scenario.

**Comment by AArnott** [comment] 2015-12-19 03:45
Fair enough. But I am seeing all the same symptoms, he is seeing for my project where I do you have to specify that extra dependency data.

**Comment by jasonmalinowski** [comment] 2015-12-21 21:22
@Pilchie: as far as triaging this, who should be assigned first? It's quite possible all the various symptoms were seeing here are from some root cause.

**Comment by yishaigalatzer** [comment] 2015-12-31 01:18
@Pilchie ping. I'm assigning to @jasonmalinowski as a rep for your team for now. But I don't necessarily expect him to do the work, just a way to put the monkey on someone's shoulder :smiling_imp:

**Comment by rchande** [comment] 2016-01-15 18:41
@yishaigalatzer @jasonmalinowski I have a DevDiv internal bug assigned to me about this.

**Comment by rrelyea** [comment] 2016-06-10 01:50
@rchande - can you share bug status and number, please?

**Comment by rrelyea** [comment] 2016-12-08 23:15
@rchande - just sent email to follow up.

**Comment by nkolev92** [comment] 2018-02-22 20:22
@rrelyea Did you find the bug status and number here?

Closing it as external.

**Closed as completed by nkolev92** 2018-02-22 20:22 UTC
Labels: Type:Bug, Resolution:External
