### ISSUE TITLE
Getting below warning message. Due to this my project is not able to restore in visual studio code.

### ISSUE THREAD

**Issue by archit1jindal** [NuGet/Home#6650] opened 2018-03-08 14:33 UTC
E:\DemoProject>dotnet restore
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): warning : Unable to find a project to restore! [E:\DemoProject\DemoProject.sln]

System information.---------:
DemoProject>dotnet --info output
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by PatoBeltran** [comment] 2018-03-09 00:44
Hey @archit1jindal, can you give me more info about your project. what is your document structure, in which directory are you running dotnet restore? You can also pass the root path of the project to restore. You can see more about this command at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x

**Comment by archit1jindal** [comment] 2018-03-09 06:46
Sure @PatoBeltran, Please find attached screen shot for better understanding.
I'm trying to execute unit test cases in UnitTest.cs.

![untitled](https://user-images.githubusercontent.com/37182627/37194320-a602071e-2393-11e8-8fef-95aae7bc8ed9.png)

**Comment by rohit21agrawal** [comment] 2018-03-13 01:16
can you just try and run dotnet restore DemoProject.sln from the terminal?

**Comment by aaronmorgan** [comment] 2018-03-22 00:50
@rohit21agrawal That's what I'm doing and getting the same error.

`dotnet restore --no-cache .\WebService.sln
C:\Program Files\dotnet\sdk\2.1.101\NuGet.targets(104,5): warning : Unable to find a project to restore! [C:\WebService\WebService.sln]`

**Comment by nkolev92** [comment] 2018-04-16 21:27
@aaronmorgan 
Can you please provide a repro?
Or at least the full restore logs (/v:d)
It's rather hard to diagnose this without knowing the exact scenario.

**Comment by nkolev92** [comment] 2018-04-27 21:31
Closing this due to lack of engagement.

Please comment again, if you're still facing this issue.

**Closed as completed by nkolev92** 2018-04-27 21:31 UTC
Labels: Product:NuGet.exe, Product:dotnet.exe, WaitingForCustomer

**Comment by codemasta** [comment] 2018-10-03 11:36
currently having this issue

**Comment by nkolev92** [comment] 2018-10-03 18:52
@codemasta 

Do you have a repro for us?

**Comment by djagd** [comment] 2019-02-28 16:53
[RestoreError.zip](https://github.com/NuGet/Home/files/2915760/RestoreError.zip)

Here is a repo.
In this instance the issue caused by missing
ProjectGuid.Configuration|Platform.Build.0 section.

The section is missing after changing the project settings (see .csproj file) and reloading the solution.
The solution was changed automatically by VS 2017.15.9.3

**Comment by fad16papa** [comment] 2022-06-10 06:42
Hi Guys,

I'm getting this error, May I know what is the solution for this? Thank you
