### ISSUE TITLE
There should be a better way to handle ATF

### ISSUE THREAD

**Issue by sbanni** [NuGet/Home#9499] opened 2020-04-30 17:14 UTC
Currently our project system wants to have all types of references and we have to continue adding values to AssetTargetFallback to support this.  It would be ideal if there was a supported way to just include ALL values with possibly an exclusion list instead of having to opt into each one.

**Comment by nkolev92** [comment] 2020-05-02 01:57
@sbanni 

Just to make sure I understand this ask, you have a project type that's technically compatible with all target frameworks, because it really only works with the already built artifacts (wapproj being that project)

**Comment by sbanni** [comment] 2020-05-04 17:52
@nkolev92 Yes your understanding is correct.

**Comment by nkolev92** [comment] 2021-12-02 03:42
Duplicate of https://github.com/nuget/home/issues/5272.

**Closed as completed by nkolev92** 2021-12-02 03:42 UTC
Labels: Priority:2, Type:DCR, Functionality:Restore, Partner:VSPlatform
