### ISSUE TITLE
NuGet code API

### ISSUE THREAD

**Issue by bencyoung** [NuGet/Home#5318] opened 2017-06-01 12:24 UTC
Is there any news on documentation for the NuGet API? The docs just point to Dave Glick's blog which is coming up to a year old... 

We have a NuGet host exe that adds some additional functionality, but it's currently stuck on the 2.12 client libraries and it's starting to break as people release .NET Core and netstandard libraries that it then doesn't understand (see the below)

We'd like to upgrade to the new libraries but it's pretty hard to do without proper docs...

> [12:17:47][Exec] ERROR! System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: 'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'.
> [12:17:47][Exec]    at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
> [12:17:47][Exec]    at NuGet.Manifest.Validate(Manifest manifest)
> [12:17:47][Exec]    at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
> [12:17:47][Exec]    at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
> [12:17:47][Exec]    at NuGet.OptimizedZipPackage.EnsureManifest()
> [12:17:47][Exec]    at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath)
> [12:17:47][Exec]    at NuGet.LocalPackageRepository.OpenPackage(String path)
> [12:17:47][Exec]    at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
> [12:17:47][Exec]    at NuGet.LocalPackageRepository.<GetPackages>d__15.MoveNext()
> [12:17:47][Exec]    at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
> [12:17:47][Exec]    at NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId)
> [12:17:47][Exec]    at NuGet.LocalPackageRepository.FindPackagesById(String packageId)
> [12:17:47][Exec]    at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String packageId)
> [12:17:47][Exec]    at NuGet.LazyLocalPackageRepository.FindPackagesById(String packageId)
> [12:17:47][Exec]    at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String packageId)
> [12:17:47][Exec]    at NuGet.PackageRepositoryExtensions.FindPackages(IPackageRepository repository, String packageId, IVersionSpec versionSpec, Boolean allowPrereleaseVersions, Boolean allowUnlisted)

**Comment by bencyoung** [comment] 2017-06-01 14:32
Note we're calling  NuGet.PackageRepositoryExtensions.FindPackages(IPackageRepository repository, String packageId, IVersionSpec versionSpec, Boolean allowPrereleaseVersions, Boolean allowUnlisted) which has a version spec that excludes the netstandard package which causes the issues, but then it ends up scanning them all anyway...

**Comment by peterichens** [comment] 2017-06-01 14:51
Documentation would be very helpful for me too.

**Comment by mishra14** [comment] 2017-11-30 00:05
Closing as dupe of https://github.com/NuGet/Home/issues/2243.

Please comment there if you have specific requests.

**Closed as completed by mishra14** 2017-11-30 00:05 UTC
Labels: Type:Docs
