### ISSUE TITLE
NuGet.Core for .NET Standard/.NET Core

### ISSUE THREAD

**Issue by terrajobst** [NuGet/Home#7412] opened 2018-10-17 23:30 UTC
What is the replacemet for [NuGet.Core](https://nuget.org/packages/NuGet.Core) package on these platforms? It would be good to update the description.

Related: https://github.com/dotnet/standard/issues/652

**Comment by nkolev92** [comment] 2018-10-22 22:26
There's no good documentation pointing to that. 
The new packages are the actively updated ones on https://www.nuget.org/profiles/nuget. 

We would need to build a new package just to update the description in this case. 

//cc @rrelyea and @anangaur to help decide what the directions here would be.

**Comment by terrajobst** [comment] 2018-10-22 22:39
Funny enough, the new location includes `NuGet.Core` 😆 

Also, I believe you can edit the metadata of packages without uploading a new version.

**Comment by nkolev92** [comment] 2018-10-22 22:46
Not since we've implemented Package Signing. 
See https://github.com/NuGet/Home/wiki/Package-Immutability. 

You can no longer make metadata updates without uploading a new version. 

/cc @skofman1

**Comment by terrajobst** [comment] 2018-10-22 22:58
Oh I see. I thought you still change the web site. My bad then. Well, I guess we need to figure out how to obsolete packages then because we'll have the same problem for ours.

**Comment by nkolev92** [comment] 2018-10-22 23:03
Yeah, definitely. 

We have a feature on the backburner, but personally I don't know when that would happen https://github.com/NuGet/Home/issues/2867

**Comment by anangaur** [comment] 2018-10-25 23:59
> We have a feature on the backburner, but personally I don't know when that would happen #2867

Soon 😄

**Comment by terrajobst** [comment] 2018-10-26 00:02
13th of soon is my favorite ship date :-). Seriously, is this something you consider for an upcoming release? Is there a spec somewhere?

**Comment by anangaur** [comment] 2018-10-26 20:32
@terrajobst We do plan to implement deprecate packages feature and will be scheduled by end of this quarter. I have an initial spec [here ](https://github.com/NuGet/Home/wiki/Deprecate-packages) that needs some revision that I intend to do in next couple of weeks.

**Comment by bdominguez** [comment] 2018-11-28 08:34
Any news @anangaur ??

**Comment by anangaur** [comment] 2018-11-28 18:50
@bdominguez about this issue or about **Deprecate** packages? Deprecate package spec is in progress and we plan to publish the spec for review in a week or two.

**Comment by bdominguez** [comment] 2018-11-28 23:22
Sorry, I meant about this issue.

**Comment by nkolev92** [comment] 2018-11-28 23:30
@bdominguez 

The few core NuGet libraries are the following:

NuGet.Commands,
NuGet.Packaging, 
NuGet.Protocol,
NuGet.PackageManagement

These have multiple other dependencies but those are lower on the dependency graph, so they'd be pulled in by the above. 

Other than that, it's helpful to look at https://www.nuget.org/profiles/nuget, and just use the ones that are updated regularly.

**Comment by bdominguez** [comment] 2018-11-28 23:38
https://www.nuget.org/packages/NuGet.PackageManagement/

Doesn't target .net standard I suppose because of:

https://www.nuget.org/packages/Microsoft.Web.Xdt/

Is there any solution?

**Comment by nkolev92** [comment] 2018-11-29 00:33
No, PackageManagement is primarily packages.config, it's not used in the cross platform tools, so it was never made cross platform.

**Comment by bdominguez** [comment] 2018-11-29 07:05
@nkolev92 but as I understand the only blocking issue that it's preventing from being cross platform it's that dependency I mentioned.

**Comment by nkolev92** [comment] 2018-11-30 18:14
@bdominguez 
Yes, probably, but we'd need to do some looking. 

As I mentioned NuGet.PackageManagement primarily contains code used by VS/packages.config related code which is not cross plat by design. 
There are some other classes which are unnecessary with PR, due to the fact that everything boils down to a restore. 

The NuGet Client repo is primarily a tool, then library, so that just hasn't been a priority. 

Why do you need it? 
You can consider creating a fork.

**Comment by bdovaz** [comment] 2018-11-30 19:46
Is there any reason it doesn't also target .NET Standard 2.0?

The problem now is that with 1.6 requires many many nuget package dependencies. In 2.0 we will reduce it drastically.

**Comment by nkolev92** [comment] 2018-11-30 21:38
We're doing that in 5.0. 
https://github.com/NuGet/NuGet.Client/pull/2118

**Comment by bdominguez** [comment] 2018-11-30 21:51
Estimated ETA? Thanks.

**Comment by nkolev92** [comment] 2018-11-30 23:35
5.0 will ship along side VS 2019. 
I don't have exact dates yet, but it will be in the first half of 2019. 
Preview packages with the NS2.0 change, might happen somewhere in ~February.

**Comment by oakio** [comment] 2019-04-24 14:20
> No, PackageManagement is primarily packages.config, it's not used in the cross platform tools, so it was never made cross platform.

@nkolev92 Is any official cross-platform replacement for `NuGet.PackageManagement` package?
For example, I need `InstallPackageAsync` method from this package.

**Comment by grahamehorner** [comment] 2019-09-16 10:30
any updates; I'm looking at using NuGet as a plugin/module delivery for a cross platform microservice framework I have been developing; and would need NuGet.Core to support .net standard 1.6 or better or have the features that NuGet.Core allows in a cross platform package?  any help or advice greatly received.

**Comment by nkolev92** [comment] 2019-09-16 17:06
@grahamehorner Please refer to https://github.com/NuGet/Home/issues/7412#issuecomment-442646312. 

The NuGet.Core package itself will not be updated.

**Comment by nkolev92** [comment] 2020-04-07 18:36
Looping back here, the feature we discussed in https://github.com/NuGet/Home/issues/7412#issuecomment-433243759 is now shipped!

If you go to https://www.nuget.org/packages/NuGet.Core/, you will see that it's deprecated.

Furthermore we have improved the docs a tiny bit. https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk

**Closed as completed by nkolev92** 2020-04-07 18:36 UTC
