### ISSUE TITLE
Operation failed as details for project could not be loaded when adding packages to .NET Core application

### ISSUE THREAD

**Issue by ngruson** [NuGet/Home#6324] opened 2017-12-16 13:40 UTC
I can't seem to add NuGet packages to a newly created ASP.NET Core Web application.
Reinstalled Visual Studio just now, no difference.
The error I get is: Operation failed as details for project WebApplication2 could not be loaded.
I don't have Resharper installed.
How do I analyze and solve this?

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Package Manager Console version 4.5.0.4685

dotnet.exe --version (if appropriate):
2.1.2

VS version (if appropriate):
2017 Enterprise, version 15.5.2

OS version (i.e. win10 v1607 (14393.321)):
10.0.14393

Worked before? If so, with which NuGet version:
Nope

## Detailed repro steps so we can see the same problem

1. Create a new ASP.NET Core Web Application (.NET Core 1.1 or 2.0) or .NET core class library or .NET core console application

2. Add a NuGet package (for instance AutoMapper or Newtonsoft.Json) to the project.

3. The error 'The operation failed as details for project <MyProject> could not be loaded' appears in Visual Studio. 

## Other suggested things
Adding NuGet packages does work with a .NET Framework class library, just not with a .NET Core application. I do notice yellow warning signs in the Solution Explorer regarding dependencies (see attachment). Tried also with .NET Core 1.1, same error.

### Sample Project

[WebApplication2.zip](https://github.com/NuGet/Home/files/1564745/WebApplication2.zip)
![dependencies](https://user-images.githubusercontent.com/3188323/34070923-0fab0d94-e26e-11e7-9769-7ea3e1e7ff63.PNG)

**Comment by emgarten** [comment] 2017-12-16 20:28
Does the project restore and build successfully after creating it before adding the new package?

**Comment by ngruson** [comment] 2017-12-16 20:32
Yes, after I perform 'dotnet restore', the solution builds succesfully. The yellow icons remain though. But no NuGet packages can be added, always the mentioned error message.

**Comment by emgarten** [comment] 2017-12-16 20:36
Running this from the command line is a different scenario from restoring in VS and seeing errors.

If you only do a file > new project and wait (no command line operations) does it work? And does it work after closing and reopening the solution?

**Comment by ngruson** [comment] 2017-12-16 20:44
When I build directly after I created the project, the build output is:

Error occurred while restoring NuGet packages: The operation failed as details for project WebApplication3 could not be loaded.
1>------ Build started: Project: WebApplication3, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(327,5): error : Assets file '<workspace>\WebApplication3\WebApplication3\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5): error : Assets file '<workspace>\WebApplication3\WebApplication3\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "WebApplication3.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

This error shouldn't come in the first place, right? Or is this to be expected?
That's why I ran the command line.
Can I restore from VS directly?

**Comment by emgarten** [comment] 2017-12-16 20:48
You can restore from VS by right clicking on the solution and selecting Restore. It also happens automatically before build.

Check your ActivityLog.xml file for errors around NuGet. You may need to run devenv with the activitylog option from the developer command prompt to get this.

**Comment by ngruson** [comment] 2017-12-16 20:57
I checked the activity log and there’s this entry:

<entry>
    <record>727</record>
    <time>2017/12/16 20:51:22.288</time>
    <type>Error</type>
    <source>NuGet Package Manager</source>
    <description>System.InvalidOperationException: The operation failed as details for project WebApplication3 could not be loaded.&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)&#x000D;&#x000A;   at NuGet.PackageManagement.DependencyGraphRestoreUtility.&lt;GetSolutionRestoreSpec&gt;d__6.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at NuGet.SolutionRestoreManager.SolutionRestoreJob.&lt;RestorePackageSpecProjectsAsync&gt;d__18.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)&#x000D;&#x000A;   at NuGet.SolutionRestoreManager.SolutionRestoreJob.&lt;RestoreAsync&gt;d__16.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at NuGet.SolutionRestoreManager.SolutionRestoreJob.&lt;RestoreAsync&gt;d__16.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at NuGet.SolutionRestoreManager.SolutionRestoreJob.&lt;ExecuteAsync&gt;d__15.MoveNext()</description>
  </entry>

**Comment by emgarten** [comment] 2017-12-16 21:06
Thanks, that is helpful!

**Comment by shravan2x** [comment] 2017-12-17 08:08
Encountering the same issue. Like @ngruson, it's only been happening the last day or so.

I'm still able to compile fine with existing packages though.

**Comment by jainaashish** [comment] 2017-12-18 19:25
@ngruson so you also see something like "The nominate API is called for...." in the activityLog.xml?

**Comment by ngruson** [comment] 2017-12-19 08:34
@jainaashish No, I don't see that in my log file.

**Comment by jainaashish** [comment] 2017-12-19 18:58
Then it's more likely Project System bug since they haven't nominated this project to NuGet which is why restore failed. @Pilchie @natidea to take a further look.

**Comment by Pilchie** [comment] 2017-12-19 19:00
Make sure to run devenv with the `/log` parameter, otherwise the activity log may not be saved if no error conditions occur.

**Comment by nikator** [comment] 2017-12-28 09:38
I think this is related to non-letter character in project path. I have the same set of environment and when I had non-letter character in my project path same error was occurring. 
So I switched from C:\\@Projects\ to C:\Projects\ it is working fine now.

**Comment by EvanMulawski** [comment] 2018-01-02 16:26
I can confirm what @nikator suggested. Restoring from VS was failing with this error until I removed a `$` from my working directory.

**Comment by ngruson** [comment] 2018-01-03 09:34
Me too, I had braces in the path of my workspace. Once I moved to another workspace without braces, this problem didn't occur.

**Comment by Red4Studios** [comment] 2018-01-05 19:35
Another me too,  Dropbox had added parentheses to my path \Dropbox (Business Name)\.  I created a symbolic link without them to work around this issue.

**Comment by cristianbalint** [comment] 2018-01-09 10:50
I also can confirm what @nikator and @EvanMulawski were saying. I had projects in path `D:\@Work\`... and VS2017 (v15.5.2) didn't find references (from solution) neither load them from nuget. 
I mention that in older versions of VS2017 I didn't encounter this problem.
**Solution**
I renamed path `D:\@Work\`... in `D:\__Work\`... and the problem went away. So illegal chars in solution path (until now): **$** and **@**.

**Comment by emgarten** [comment] 2018-01-09 19:16
Does restore work from the command line for projects with these chars in the path?

It is unclear from this if the project system is having issues sending the restore nomination to NuGet, or if NuGet is having trouble parsing the nomination.

**Comment by Pilchie** [comment] 2018-01-09 19:17
Tag @lifengl as there were some core project system issues with special characters introduced in 15.5 AFAIK.

**Comment by cristianbalint** [comment] 2018-01-10 10:25
@emgarten Yes, restore was working from dotnet cli.

**Comment by daltskin** [comment] 2018-01-10 12:24
Same issue here with `C:\@Source` folder if adding new dependencies.

@emgarten `dotnet restore` **does** work from command line for existing dependencies

**Comment by emgarten** [comment] 2018-01-10 20:05
Thanks for confirming it works on the command line. This could be caused by the issue @Pilchie has mentioned if this is VS specific. 

I'll leave this open for tracking, but it doesn't seem like a fix is needed on the NuGet side currently.

**Comment by lifengl** [comment] 2018-01-10 23:48
Yeah, a special character in the path can block design time build, and Jacob fixed it in 15.6 preview 3.

Sent from my phone

On Jan 10, 2018, at 12:06 PM, Justin Emgarten <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for confirming it works on the command line. This could be caused by the issue @Pilchie<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpilchie&data=02%7C01%7C%7Cda8e5842ffff4c30b7c108d5586596d9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636512115696303695&sdata=x8BF%2B6605MxdGzUAz7sIsXM8s1n7J0QlqRkt5q2Qj2c%3D&reserved=0> has mentioned if this is VS specific.

I'll leave this open for tracking, but it doesn't seem like a fix is needed on the NuGet side currently.

**Closed as completed** 2018-01-10 23:51 UTC
Labels: Priority:2, Resolution:External, Functionality:Restore

**Comment by jessehallam** [comment] 2018-01-30 23:09
Just wasted half my day trying to figure out why I am having this error, only to read this thread and discover that the '$' character somewhere in my path (which I have no control of... symlink time) is causing it. This MUST be fixed.

**Comment by jainaashish** [comment] 2018-01-30 23:25
Please follow this thread to get latest update on this issue - https://developercommunity.visualstudio.com/content/problem/160750/nuget-bug-in-vs155.html

**Comment by Xonshiz** [comment] 2018-02-17 17:49
Thanks @jainaashish for the link. Was having same problem, this fixed it... 👍

**Comment by viveksingh30** [comment] 2018-06-22 12:27
In my case, I was creating the project which was typically inside a lot of folders, I just created a project in near c directory, which solved my problem, my dependencies folder was restored. I was able to add nuget package. Though the dependency folder showed warning sign but every thing worked fine

**Comment by jzabroski** [comment] 2018-08-10 18:53
@emgarten 

> Running this from the command line is a different scenario from restoring in VS and seeing errors.

THANK YOU SO MUCH!

**Comment by MERamadan** [comment] 2019-04-17 07:25
In my case with a new **Asp.Net Core 2.2** project with **Visual Studio 2017 (15.9.11)**. Also, I have a big solution with too many other projects. 

The following steps fixed the issue for me
- from the solution explorer -> r-click the project -> unload project
-  r-click the project -> Edit
- remove the following section (if exists)

`<PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>`

- Save
-  r-click the project -> Reload Project
- Nuget -> install a package successfully

**Comment by liciniomendes** [comment] 2019-06-15 08:23
Same problem with VS 2019 (16.1.1) and .NET Core 3.0.0-preview5-27626-15.

Unload and reload the project solved the problem.

**Comment by ArulPushpam** [comment] 2019-07-24 13:56
I just removed that project in my solution, then added the same project again.it worked

**Comment by weitzhandler** [comment] 2019-08-12 21:10
@liciniomendes's solution did the job.
Was working on a solution with ~20 projects, unloaded and reloaded them all, just a few had the problems remaining, after reloading them individually the problems were all solved.

**Comment by ivanut** [comment] 2019-09-21 13:02
Had the same problem in VS 2019 16.2.5. @ArulPushpam's solution worked with removing and readding the project. Before that, the intellisense in the whole solution was broken. I do not have a repro now, but will register a bug next time it happens.

**Comment by korneliuscode** [comment] 2019-10-05 17:42
I had the same issue, when the version in the csproj file was malformed.

**Comment by saf-itpro** [comment] 2019-12-24 18:40
Hope following helps some users (if not all):
Had the same issue with `VS2019` It did not work on `Package Manager Console`. But worked on `Manage Nuget Package for Solution` where you search for the package and click on `Install`.
I had opened the  `VS2019` as admin but I don't think that was necessary.

**Comment by dquist** [comment] 2020-01-31 19:42
My problem was that my PackageReference version had a 'v' before the version...

e.g.

`<PackageReference Include="NUnit3TestAdapter" Version="v3.15.1" />`

Change the `v3.15.1` to `3.15.1` and it works again. Only figured it out by running `dotnet restore`. The GUI error messages were less than helpful.

**Comment by nl-x** [comment] 2020-02-13 11:50
Had the same issue. Solved it by clearing all Nuget Caches.
Tools > Options > NuGet Package Manager > General > Clear All NuGet Cache(s)

**Comment by vanderthiel** [comment] 2020-03-13 11:17
I had this issue when generating projects and solution from commandline, then loading in Visual Studio. Solved it by unloading and reloading all projects. Structure generated using:

```
dotnet new sln --name <domain>  
dotnet new web --name <domain>.<domain>Service --output <domain>Service  
dotnet new xunit --name <domain>.<domain>Service.Tests.Unit --output <domain>Service.Tests.Unit  
dotnet new classlib --name <domain>.Domain --output Domain  
dotnet new xunit --name <domain>.Domain.Tests.Unit --output Domain.Tests.Unit  
dotnet sln add Domain*/*.csproj -s Libraries  
dotnet sln add <domain>Service*/*.csproj -s <domain>Service  
```
