### ISSUE TITLE
Please return References from ResolveNuGetPackageAssets

### ISSUE THREAD

**Issue by damnlogin** [NuGet/Home#2692] opened 2016-04-29 11:57 UTC
Hello

We are using NuGet targets in our MSBuild process to identify references added by NuGet. Currently we have to modify ResolveNuGetPackageAssets target within Microsoft.NuGet.targets to let it return resolved references.

Can you please change the targets file to include  Returns="@(ReferenceCopyLocalPaths);@(_ReferencesFromNuGetPackages)" into ResolveNuGetPackageAssets target. So that resolved references can be used by other msbuild targets.

.NET Framework ResolveAssemblyReferences target does the same so can you please align NuGet msbuild target with ResolveAssemblyReferences behaviour.

Thanks in advance

**Comment by yishaigalatzer** [comment] 2016-05-02 04:47
CC @jasonmalinowski

**Comment by damnlogin** [comment] 2016-05-02 11:17
Hello

Just want to add some words to justify the need for the change:

We have a huge project with lots of dependencies between projects. To let MSBuild better parallel operations it performs - we parse 20 solutions we have and generate single large solution replacing binary references with project references where we can passing that sigle solution to MSBUild, but parallel build often is stuck with some output file being locked by another MSBuild process - that is why we use UseCommonOutputDir variable to prevent MSBuild from copying binary dependencies to output dir - only immediate project output is copied.

Using that approach we were able to dramatically lessen the time we spend in build process, but after the build we need to copy to output directory all the references that were not copied as we prevented that in a build, so here we use ResolveAssemblyReferences task to identify all the dependencies and copy them in batch, but after migrating to _project.json_ we figured out that ResolveAssemblyReferences no longer gives us the full list of dependencies - NuGet dependencies and content files are not copied. So we decided to execute NuGet ResoveNuGetPackageAssets target once again for every project in our combined solution to identify missing dependencies and that is why I am asking for the change.

I hope you will not consider this as an issue local to our case only - I believe the output may be useful for many other developers that use UseCommonOutputDir variable and suffer from missing outputs in NuGet MSBuild target.

Just added a [pull request](https://github.com/NuGet/NuGet.BuildTasks/pull/14)

**Comment by jasonmalinowski** [comment] 2016-05-02 17:34
Your scenario/justification seems completely reasonable, no concerns there. I've made a few comments on the PR.

**Comment by jasonmalinowski** [comment] 2016-05-02 17:43
(assigning to me since it's at least on me to merge @damnlogin's PR)

**Comment by jainaashish** [comment] 2018-02-02 00:26
This has been there for over an year and I dont see it getting to any conclusion end. So closing it for now.

**Closed as completed by jainaashish** 2018-02-02 00:26 UTC
Labels: Resolution:ByDesign

**Comment by ghost** [comment] 2018-02-07 22:41
So this was closed by design because no one wanted to work on it?

**Comment by jainaashish** [comment] 2018-02-07 23:21
Currently, there is no resource bandwidth to work on it. And keeping it open, doesn't give the right picture.
