### ISSUE TITLE
Visual Studio Extension nuget.config access denied

### ISSUE THREAD

**Issue by rbmanian75** [NuGet/Home#985] opened 2015-07-22 15:25 UTC
When i try to open the PMC it is failing with the following error.
```
  <entry>
    <record>693</record>
    <time>2015/07/22 15:19:27.467</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [NuGetPackage]</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
    <hr>80070005 - E_ACCESSDENIED</hr>
    <errorinfo>Access to the path 'C:\LP\SGC\Sgc.Web\.nuget\NuGet.config' is denied.</errorinfo>
  </entry>
```

I am running visual studio as administrator and nuget.config file is under source control so the read only attribute is set.

OS : Windows 8,1
Visual Studio 2015 RTM

**Comment by emgarten** [comment] 2015-07-22 18:11
Dupe of https://github.com/NuGet/Home/issues/868

**Closed by emgarten** 2015-07-22 18:11 UTC
Labels: ClosedAs:Duplicate
