### ISSUE TITLE
Improve error messaging for projects with multiple AssemblyNames

### ISSUE THREAD

**Issue by mattleibow** [NuGet/Home#10766] opened 2021-04-12 15:51 UTC
## Details about Problem

This is directly this issue: https://github.com/NuGet/Home/issues/5226

Just opening this issue for the simple reason that this got me for a few days as I was unable to find exactly what was causing the issues.

If there is a way to have an actual error message that could effectively mean "Unable to find unique ID for project when restoring. Either use the same AssemblyName for all TFMs or add a PackageId."

Or something like that. This looks like some internal error that gets out and there is no ay to figure it out. I had to add back my project line by line and it was time consuming as I have quite a few projects and quite a few TFMs in there.

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): all

Product version: all

Worked before? If so, with which NuGet version:

**Comment by nkolev92** [comment] 2021-04-14 19:16
Hey @mattleibow 

What was the error that you got? 
We've recently changed the error handling for bad nominations, so the problems should be in the error list now. 

Obviously the root cause is not obvious. 

I get

> Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1105	Unable to read project information for 'ConsoleApp4': Sequence contains more than one element	ConsoleApp4	C:\Users\Nikolche\Source\Repos\ConsoleApp4\ConsoleApp4\ConsoleApp4.csproj	1	

Related: https://github.com/NuGet/Home/issues/7016

**Comment by nkolev92** [comment] 2021-12-06 22:50
Closing as dup of https://github.com/NuGet/Home/issues/6461. 

The error is better, but not yet good enough.

**Closed as completed by nkolev92** 2021-12-06 22:50 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Priority:2, Type:Bug, Area:ErrorHandling, Functionality:Restore
