### ISSUE TITLE
Search box cannot be accessed with Ctrl+E hotkey after search

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1404] opened 2015-09-18 18:10 UTC
From vs-feedback (444419)

After an initial search, the hotkey for the search textbox is no longer displayed and does not work.

**Comment by yishaigalatzer** [comment] 2015-09-18 21:15
I cannot repro this.

The shortcut is not displayed if the box has data in it (expected), but the shortcut works just fine.

If you can provide exact repro steps, please re-open.

**Comment by bradygaster-zz** [comment] 2015-10-05 21:29
I am still seeing this issue happen. I'm running the default install of RTM 2015, with the Azure SDK 2.7.1 installed, too. If you need my machine come grab it. @yishaigalatzer saw it not work on my machine, and I saw it work on his, so something's installed that's probably stealing the Ctrl-E shortcut on my machine. The only thing I can think of would be the Azure SDK, but that seems like a large enough swath of users that we should try to resolve this. FWIW, I'm fine with this being a low-pri issue.

**Comment by nkolev92** [comment] 2017-12-20 00:13
Duplicate of https://github.com/NuGet/Home/issues/5943

**Closed as completed by nkolev92** 2017-12-20 00:13 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug
