### ISSUE TITLE
The 4th part of version string is getting removed if 0

### ISSUE THREAD

**Issue by nschwerzler** [NuGet/Home#6012] opened 2017-10-11 01:27 UTC
## Details about Problem
NuGet product used: NuGet.exe: pack command

The 4th part of the version string is getting removed from the nuspec file contained in the nupkg and nupkg file name if it is .0

Original Nuspec passed into pack command
    <version>9.0.17016.0-170628-1624.someSymVersion</version>

Nuspec resolved in nupkg (missing .0! in version)
    <version>9.0.17016-170628-1624.someSymVersion</version>

NuGet version: 4.3

OS version: Windows 10

Worked before? No, but if you use something other than zero for the 4th part of the version, it works

## Detailed repro steps so we can see the same problem

1. Create a nuspec with <version>9.0.17016.0-170628-1624.someSymVersion</version>

2. nuget pack [nuspec]

3. You will get a package with a nuspec with wrong version and nupkg name with missing 4th part.

**Comment by rohit21agrawal** [comment] 2017-10-11 01:38
closing as dupe of : https://github.com/nuget/home/issues/3050

**Closed as completed by rohit21agrawal** 2017-10-11 01:38 UTC
Labels: Resolution:Duplicate, Functionality:Pack
