### ISSUE TITLE
Allow to specify runtime dependencies in project.json

### ISSUE THREAD

**Issue by forki** [NuGet/Home#2082] opened 2016-02-09 12:44 UTC
Is it possible to specify runtime dependencies in project.json?

https://github.com/NuGet/Home/issues/2071 shows that it would be useful to give users a way to override resolver decisions when needed.
Also in some cases we need to add additional runtime dependencies that are not expressed in compile time dependencies.

**Comment by yishaigalatzer** [comment] 2016-02-09 23:55
@ericstj can you help track the bug that is the duplicate of this issue?

**Comment by ericstj** [comment] 2016-02-25 03:43
That'd be this one:
https://github.com/nuget/home/issues/1660
Spec is here:
https://github.com/dotnet/cli/issues/465

**Closed as completed** 2016-03-13 02:42 UTC
Labels: Resolution:Duplicate
