### ISSUE TITLE
Install package on CPS project system throw error

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3750] opened 2016-10-24 22:44 UTC
With d15prerel 25823.2 and latest nuget vsix from dev. 

Create CPS based project and try installing a package from UI, first time it throw below error:

**Comment by rrelyea** [comment] 2016-10-24 23:10
dupe of https://github.com/NuGet/Home/issues/3752

**Closed as completed by rrelyea** 2016-10-24 23:10 UTC
Labels: Resolution:Duplicate
