### ISSUE TITLE
Visual Studio Nuget update suggestion ignores current .net framework in project

### ISSUE THREAD

**Issue by Aldebaran91** [NuGet/Home#13982] opened 2024-12-04 09:33 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 17.12.3

### Worked before?

No

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1) Create project with .net8 and add an older nuget version with .net 8 support which only supports .net9 in the latest version.
2) Open Nuget manager UI
3) Go to tab "Updates"

You will see that it will suggest you the latest version which is not supported by the current project. This update should not be suggested. Because of this an auto update is no longer supported on this project. Each update must be done manually.
![nugetupdatesuggestion](https://github.com/user-attachments/assets/b672a0a5-673a-430b-9240-d0da512ff409)

**Comment by kartheekp-ms** [comment] 2024-12-07 05:41
This request is tracked as part of https://github.com/NuGet/Home/pull/12704 spec.

[Rendered proposal](https://github.com/NuGet/Home/blob/6225561b2aa85ddfe55024344155c7ec82ff8973/proposed/2023/vs-filters.md) states the following.
> The browse filter experience will allow the developer to filter results based on common concepts such as "frameworks", "prerelease", "owners", "download count", "license", and "created on".

**Comment by nkolev92** [comment] 2024-12-09 22:19
Duplicate of https://github.com/NuGet/Home/issues/5725.

**Closed as not planned by nkolev92** 2024-12-09 22:19 UTC
Labels: Type:DCR, Functionality:VisualStudioUI, Functionality:Update
