### ISSUE TITLE
NuGet CLI Update fails entirely if specific Source is specified without Package Ids

### ISSUE THREAD

**Issue by makhdumi** [NuGet/Home#2225] opened 2016-03-01 16:21 UTC
I have projects that use packages from multiple repositories.

In 2.x, I was running the following command to update all packages from one repository (Source):
`nuget update MySolution.sln -Source https://my-private-repo.com/nuget`

This would go through all the packages and check if they were available in the repo. If not, it'd just skip them. Restore worked the same way.

In 3.3, the update fails entirely and halts when it can't find a package in the repo, e.g. a package I installed from the public nuget.org repository. Restores will continue but spit out a bunch of warnings.

**Comment by jainaashish** [comment] 2016-05-27 18:57
duplicate of https://github.com/NuGet/Home/issues/1013

**Closed as completed** 2016-07-18 21:33 UTC
Labels: Type:Bug, Product:NuGet.exe, Functionality:Update
