### ISSUE TITLE
Make Release Notes field more usable

### ISSUE THREAD

**Issue by NickCraver** [NuGet/Home#1734] opened 2015-11-15 02:42 UTC
In short: I propose making the Release Notes field markdown, or at the very least have nuget.org atuomatically convert URLs into hyperlinks in the field. Right now the breakdown of the top 50 packages on nuget.org is:
- **33** have no release notes
- **12** have only a link (or a link + a few words)
- **5** have release notes in some form

It's tedious to maintain both a changelog in a repo as well as in all packages (note: this may include _multiple_ packages for a single repo, multiplying the pain). I feel that's supported by the 90% above with no notes in NuGet. What is doable is maintaining _one_ copy of changes - which means linking to it is very appealing, evidenced by the 24% above (many of which are Microsoft packages).

I'd like to throw out the following options as suggested fixes:
1. Make the field markdown (and nuget.org convert/render it properly) - this makes it much more useful overall.
2. Auto-link URLs in release notes - so if you use it as a field it effectively becomes a link.
3. Add a ReleaseNotesLink-like field specifically for a URL.
4. Change the rules on the schema, and indicate if the field _is_ a URI, it'll be rendered linkified.

For the curious, here's the entire top 50 list:
- 1 (_none_): [EntityFramework](https://www.nuget.org/packages/EntityFramework/)
- 2 (_none_): [Json.NET](https://www.nuget.org/packages/Newtonsoft.Json/8.0.1-beta2)
- 3 ([link](http://blog.getbootstrap.com) only): [Bootstrap CSS](https://www.nuget.org/packages/bootstrap/4.0.0-alpha)
- 4 (_none_): [jQuery](https://www.nuget.org/packages/jQuery/)
- 5 (_none_): [Microsoft.AspNet.Mvc](https://www.nuget.org/packages/Microsoft.AspNet.Mvc/6.0.0-beta8)
- 6 (_none_): [WebGrease](https://www.nuget.org/packages/WebGrease/)
- 7 (_none_): [Microsoft HTTP Client Libraries](https://www.nuget.org/packages/Microsoft.Net.Http/)
- 8 ([link](http://go.microsoft.com/fwlink/?LinkID=403010) only): [Microsoft ASP.NET Web API 2.2](https://www.nuget.org/packages/Microsoft.AspNet.WebApi/)
- 9 (_none_): [Microsoft.AspNet.Identity.EntityFramework](https://www.nuget.org/packages/Microsoft.AspNet.Identity.EntityFramework/3.0.0-beta8)
- 10 (_none_): [Microsoft.Owin.Host.SystemWeb](https://www.nuget.org/packages/Microsoft.Owin.Host.SystemWeb/)
- 11 (_none_): [jQuery UI (Combined Library)](https://www.nuget.org/packages/jQuery.UI.Combined/)
- 12 (_none_): [Microsoft ASP.NET Identity Owin](https://www.nuget.org/packages/Microsoft.AspNet.Identity.Owin/)
- 13 (**has notes!**): [NUnit Version 3](https://www.nuget.org/packages/NUnit/3.0.0-rc-3)
- 14 (_none_): [AngularJS](https://www.nuget.org/packages/angularjs/)
- 15 ([link](http://go.microsoft.com/fwlink/?LinkID=403011) only): [Microsoft ASP.NET Web Pages](https://www.nuget.org/packages/Microsoft.AspNet.WebPages/)
- 16 (**has notes!**): [Moq: an enjoyable mocking library](https://www.nuget.org/packages/Moq/)
- 17 ([link](http://go.microsoft.com/fwlink/?LinkID=403010) only): [Microsoft ASP.NET Web API 2.2 Client Libraries](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/)
- 18 (_none_): [Microsoft.Owin](https://www.nuget.org/packages/Microsoft.Owin/)
- 19 (_none_): [AutoMapper](https://www.nuget.org/packages/AutoMapper/)
- 20 (_none_): [ANTLRv3](https://www.nuget.org/packages/Antlr/)
- 21 (_none_): [Microsoft.AspNet.Razor](https://www.nuget.org/packages/Microsoft.AspNet.Razor/4.0.0-beta8)
- 22 (_none_): [Microsoft.Owin.Security.OAuth](https://www.nuget.org/packages/Microsoft.Owin.Security.OAuth/)
- 23 (_none_): [Microsoft.Owin.Security](https://www.nuget.org/packages/Microsoft.Owin.Security/)
- 24 (_none_): [Microsoft BCL Portability Pack](https://www.nuget.org/packages/Microsoft.Bcl/)
- 25 (_none_): [Microsoft.Owin.Security.Cookies](https://www.nuget.org/packages/Microsoft.Owin.Security.Cookies/)
- 26 (_none_): [Microsoft ASP.NET Identity Core](https://www.nuget.org/packages/Microsoft.AspNet.Identity.Core/)
- 27 ([link](http://go.microsoft.com/fwlink/?LinkId=389866) only): [Microsoft jQuery Unobtrusive Validation](https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Validation/)
- 28 (_none_): [log4net [1.2.14]](https://www.nuget.org/packages/log4net/)
- 29 ([link](http://go.microsoft.com/fwlink/?LinkId=535037) only): [Application Insights for Web Applications](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/2.0.0-beta2)
- 30 (_none_): [Microsoft ASP.NET Web Optimization Framework](https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization/)
- 31 (_none_): [jQuery Validation](https://www.nuget.org/packages/jQuery.Validation/)
- 32 ([link](http://go.microsoft.com/fwlink/?LinkID=403010) only): [Microsoft ASP.NET Web API 2.2 Web Host](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.WebHost/)
- 33 ([link](http://go.microsoft.com/fwlink/?LinkID=403010) only): [Microsoft ASP.NET Web API 2.2 Core Libraries](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Core/)
- 34 (_none_): [Modernizr](https://www.nuget.org/packages/Modernizr/)
- 35 ([link](https://github.com/SignalR/SignalR/releases) only): [Microsoft ASP.NET SignalR](https://www.nuget.org/packages/Microsoft.AspNet.SignalR/)
- 36 ([link](http://go.microsoft.com/fwlink/?LinkId=389866) only): [Microsoft jQuery Unobtrusive Ajax](https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Ajax/)
- 37 (_none_): [knockoutjs](https://www.nuget.org/packages/knockoutjs/)
- 38 (**has notes!** - but it's just an "oops" message): [HtmlAgilityPack](https://www.nuget.org/packages/HtmlAgilityPack/)
- 39 (_none_): [AngularJS Core](https://www.nuget.org/packages/AngularJS.Core/)
- 40 (_none_): [Microsoft BCL Build Components](https://www.nuget.org/packages/Microsoft.Bcl.Build/)
- 41 (**has notes!**): [ODataLib for OData V1-3](https://www.nuget.org/packages/Microsoft.Data.OData/5.7.0-rc)
- 42 (_none_): [Application Insights API for JavaScript Applications](https://www.nuget.org/packages/Microsoft.ApplicationInsights.JavaScript/0.15.0-build58334)
- 43 (_none_): [Microsoft.Owin.Security.Google](https://www.nuget.org/packages/Microsoft.Owin.Security.Google/)
- 44 (_none_): [Unity](https://www.nuget.org/packages/Unity/)
- 45 (**has notes!**): [NLog](https://www.nuget.org/packages/NLog/4.3.0-alpha1)
- 46 (_none_): [Ajax Control Toolkit](https://www.nuget.org/packages/AjaxControlToolkit/)
- 47 (_none_): [System.Data.SQLite (x86/x64)](https://www.nuget.org/packages/System.Data.SQLite/)
- 48 (_none_): [Microsoft.Owin.Security.Facebook](https://www.nuget.org/packages/Microsoft.Owin.Security.Facebook/)
- 49 ([link](http://go.microsoft.com/fwlink/?LinkID=403010) only): [Microsoft ASP.NET Web API 2.2 OWIN](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Owin/)
- 50 ([link](http://go.microsoft.com/fwlink/?LinkID=403010) only): [Microsoft ASP.NET Web API 2.2 Cross-Origin Support](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Cors/)

**Comment by mgravell** [comment] 2015-11-15 08:19
Note the issues of _text_ release notes is further complicated by the fact that it needs to be written in xml (*.nuspec) or json (project.json - in which case it also bloats the project file). As a fifth suggested fix:

5: make "nuget pack" and the dnx (project.json) tools allow a release `releaseNotesPath` field (separate to `releaseNotes`) which is a relative path (from the `*.nuspec` or `project.json`) to a text file that contains the release notes, which can be maintained separately. This could potentially be combined with option "3" above, such that:
- if the location specified is a http/https uri, it is kept as the uri and automatically shown _as a link_ in both nuget.org and visual studio
- otherwise, the location is interpreted as a local relative link to a text file to be imported during nupkg generation

As a stretch-goal incorporating idea "1" above, all mentions of "text file" above could be extended to mean "text file copied as-is, or `.md` file processed via your choice of markdown processor".

**Comment by mgravell** [comment] 2015-11-15 08:23
As a side note: consumers do actually care about release notes. The _moment_ I failed to update them (because I was experimenting with the new dnx build tooling, at a time when release-notes weren't supported), I got called on it: https://github.com/StackExchange/dapper-dot-net/issues/348

**Comment by csharpfritz** [comment] 2015-11-16 01:55
I like this discussion, and believe that we need to revisit how release notes are surfaced to the package consumer.  The idea of a releasenotes.md file in the package has been raised before, and I think we need to be careful about how to introduce this feature without breaking older clients.

**Comment by yishaigalatzer** [comment] 2015-11-16 21:38
This is a duplicate of https://github.com/NuGet/Home/issues/1203, added notes to the other issue, to make sure we handle both of them as one.

**Closed as completed by yishaigalatzer** 2015-11-16 21:38 UTC
Labels: Resolution:Duplicate

**Comment by ashmind** [comment] 2015-11-16 23:15
To add to @mgravell's suggestion, the way I would love to see it would be:

``` json
"releaseNotesPath": "README.md#Release_Notes"
```

so basically a section getting cut out of md file.

I would also like to see the same for description, as project.json is not very convenient for description editing.
