### ISSUE TITLE
Nuget OutputDirectory trailing slash

### ISSUE THREAD

**Issue by Liero** [NuGet/Home#1817] opened 2015-12-09 11:59 UTC
If I pass path in brackets with training slash to -OutputDirectory switch of nuget pack command, following swtiches are ignored. 

For example this command works:

```
nuget.exe pack "C:\Builds\1\PROJECT\RollingBuild\src\Dev\Backend\Contracts\Contracts.csproj.nuspec" -Version 0.1.0.1407 -OutputDirectory "C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\Packages" -prop OutDir=C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\
```

but this command throws: The replacement token 'OutDir' has no value. (.nuspec uses $OutDir$ replacement token)

```
nuget.exe pack "C:\Builds\1\PROJECT\RollingBuild\src\Dev\Backend\Contracts\Contracts.csproj.nuspec" -Version 0.1.0.1407 -OutputDirectory "C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\Packages\" -prop OutDir=C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\
```

difference is in -OutputDirectory: 

 "C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\Packages\" - error 
 "C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\Packages" ok 
 C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\Packages\ - ok 
 C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\Packages - ok 

 In general, I was not able to automate nuget pack and nuget post in folders containing space and with nuget.exe where path contains space. 

 I'm using latest 3.3.0

**Comment by yishaigalatzer** [comment] 2015-12-10 18:04
This is a duplicate of https://github.com/NuGet/Home/issues/1752

The issue here is nothing to do with NuGet, it is how windows console works. The last \" is being removed by windows passing the argument into the console app itself.

We could look into completely dropping out of using Main(args) pattern and parsing the commandline directly ourselves, that seems more and more like an appealing idea.

So I don't think we can fix this particular issue (but we should fix the one with the . at the end of the path). See https://blogs.msdn.microsoft.com/oldnewthing/20100917-00/?p=12833/

A "relatively simple" workaround would be to remove the trailing `\`, of course I realize that msbuild doesn't quite let you do that easily (CC @dsplaisted) but you call into a powershell script that will trim the trailing slash and run pack.

**Comment by yishaigalatzer** [comment] 2015-12-14 21:00
Sorry, I misread your original question. The easy solution for this is to add a `.` at the end of the path (if you know there is a trailing backslash) alternatively you can add a \. 

So for your command you can use `nuget.exe pack "C:\Builds\1\PROJECT\RollingBuild\src\Dev\Backend\Contracts\Contracts.csproj.nuspec" -Version 0.1.0.1407 -OutputDirectory "C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\Packages\." -prop OutDir=C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\`

or better yet 

`nuget.exe pack "C:\Builds\1\PROJECT\RollingBuild\src\Dev\Backend\Contracts\Contracts.csproj.nuspec" -Version 0.1.0.1407 -OutputDirectory "C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\Packages\\" -prop OutDir=C:\Builds\1\PROJECT\RollingBuild\src\Dev\bin\`

The second example will also work for the replacement token and not just the path

**Comment by yishaigalatzer** [comment] 2015-12-14 21:12
Added tests to verify the scenario, and expected results - https://github.com/NuGet/NuGet.Client/pull/156

**Closed as completed** 2015-12-14 21:22 UTC
Labels: Resolution:ByDesign
