### ISSUE TITLE
packages.lock.json generated with inconsistent line endings

### ISSUE THREAD

**Issue by aw129** [NuGet/Home#9629] opened 2020-05-30 22:19 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet

NuGet version (x.x.x.xxx): 5.5.0.4

dotnet.exe --version (if appropriate): 3.1.202

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): win10, mac OS

Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem

1. Execute `dotnet restore` on mac, `packages.lock.json` is generated with LF line endings

2. Change single package version.

3. Execute `dotnet restore` on Windows, `packages.lock.json` is updated with CRLF line endings

When the file is created on one OS and committed to source control and then updated on the other OS every line is changed.

**Comment by zivkan** [comment] 2020-06-14 05:54
@aw129 with your suggestion, I believe that it would cause a problem with git repos that use a `.gitattributes` file that sets `packages.lock.json` (or more probably `*.json`) to [text mode](https://www.git-scm.com/docs/gitattributes#_text). Subversion appears to have a similar setting `svn:eol-style=native`.

Therefore I propose that the current behaviour, using the platform's native line endings, is preferable.

**Comment by aw129** [comment] 2020-06-22 18:17
My experience is that having files checkout with different line endings causes more problems than it solves.

Having said that, setting `packages.lock.json` to text mode seems to be an effective workaround for this issue. I wasn't aware of that option, thank you.

**Comment by zivkan** [comment] 2020-06-25 20:05
Closing as by design, as per my previous comment.

**Closed as completed by zivkan** 2020-06-25 20:05 UTC
Labels: Type:Bug, Resolution:ByDesign, Product:dotnet.exe, Area:RestoreRepeatableBuild
