### ISSUE TITLE
Make 'dotnet list package' machine-readable

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#9524] opened 2020-05-04 21:25 UTC
The output of `dotnet list package` today looks like:
```
Project 'foo.csproj' has the following package references
   [netstandard2.0]:
   Top-level Package                                Requested         Resolved
   > SomePackage                                    [1.1.6]           1.1.6
```

It would be useful if there was a machine-readable output format. This is useful for various scenarios such as gathering OSS license information based on packages used.

**Comment by nkolev92** [comment] 2020-05-05 00:45
Duplicate of https://github.com/NuGet/Home/issues/7752

**Closed as completed by nkolev92** 2020-05-05 00:45 UTC
Labels: Resolution:Duplicate, Type:Feature, Product:dotnet.exe, Functionality:ListPackage
