### ISSUE TITLE
Upgrade all nuget packages in project/solution

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7063] opened 2018-06-26 16:20 UTC
_From @shatl on June 26, 2018 13:57_

Please ability to upgrade all nuget packages in csproj file or solution to latest version from command line.

E.g. ```dotnet update package *``` - updates all package references in project (or solution) found in current folder
```dotnet update PackageName``` - updates package with given name

_Copied from original issue: dotnet/cli#9559_

**Comment by mishra14** [comment] 2018-06-26 18:40
This is a dupe of https://github.com/NuGet/Home/issues/4103

please track that issue.

**Closed as completed by mishra14** 2018-06-26 18:40 UTC
Labels: Resolution:Duplicate, Platform:Xplat
