### ISSUE TITLE
Package restore in VS can't restore compile content files

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#8101] opened 2019-05-06 19:45 UTC
Please read the following information before posting the issue.
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): *5.1.0*

dotnet.exe --version (if appropriate): *3.0.100-preview3-010431* or * 2.2.102*

VS version (if appropriate): 16.1.0 Preview 3
Worked before? If so, with which NuGet version: 4.6.0

## Detailed repro steps so we can see the same problem

I have a NuGet package with the following NuSpec:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>DictionaryExtensions</id>
    <version>0.1.5650001</version>
    <authors>zzz</authors>
    <owners>zzz</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <developmentDependency>true</developmentDependency>
    <description>Adds DictionaryExtensions extensions.</description>
  </metadata>
</package>
```

Under `contentFiles\cs\any\(Recipes)`, it contains a .cs file called DictionaryExtensions.cs that contains extension methods.

I reference this package from a netstandard2.0 library as so:
```
    <PackageReference Include="DictionaryExtensions" Version="0.1.5650001">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

If a build the project in Visual Studio 2019 with the "enable VS to restore packages" checkbox enabled, I get build errors about not finding methods in DictionaryExtensions.cs. If I do `dotnet restore`, disable VS package restore, and build, my project builds fine. I diffed the assets files and here's the difference. It looks like VS is not adding the .cs file as a content file. 

VS restore:
```
"DictionaryExtensions/0.1.5650001": {
        "type": "package",
        "contentFiles": {
          "contentFiles/any/any/_._": {
            "buildAction": "None",
            "codeLanguage": "any",
            "copyToOutput": false
          }
        }
      },
```

Dotnet restore
```
 "DictionaryExtensions/0.1.5650001": {
        "type": "package",
        "contentFiles": {
          "contentFiles/cs/any/(Recipes)/DictionaryExtensions.cs": {
            "buildAction": "Compile",
            "codeLanguage": "cs",
            "copyToOutput": false
          }
        }
      },
```

**Comment by rchande** [comment] 2019-05-06 19:45
cc @colombod

**Comment by rchande** [comment] 2019-05-07 19:32
@donnie-msft Can you help me understand when this is going to be fixed? This is a regression from Dev15.

**Comment by donnie-msft** [comment] 2019-05-07 21:46
@rchande, I tried to repro this with VS 16.1.0 Prev 3.0, NuGet 5.1.0, and had no problem getting the content files to show up in my projects.assets.json using VS Restore. Resulting JSON shown below.

Are there further details you can provide? Is there a shareable NuGet package, or can you provide a list of all the content files that were in your package? I made some assumptions based on the assets file snippets you provided, which may not be giving me the whole picture.

```
"targets": {
    ".NETStandard,Version=v2.0": {
      "DictionaryExtensions/0.1.5650001": {
        "type": "package",
        "contentFiles": {
          "contentFiles/any/any/_._": {
            "buildAction": "None",
            "codeLanguage": "any",
            "copyToOutput": false
          },
          "contentFiles/cs/any/(Recipes)/DictionaryExtensions.cs": {
            "buildAction": "Compile",
            "codeLanguage": "cs",
            "copyToOutput": false
          }
        }
      },
```

**Comment by rchande** [comment] 2019-05-07 23:00
@donnie-msft I sent you mail

**Comment by donnie-msft** [comment] 2019-05-08 00:29
@rchande Using the package you e-mailed, I am unable to reproduce the problem you're describing. I've tried both using the Package Manager UI and the Console. 

If you create a brand new Net Standard project, does the problem exist there? Also, what package source are you using, and do you have multiple sources that could have a conflict with this package?

**Comment by nkolev92** [comment] 2020-11-06 06:56
Given that we haven't received a response, closing this as no repro. 

Happy to reconsider/triage a new issue as necessary.

**Closed as completed by nkolev92** 2020-11-06 06:56 UTC
Labels: Type:Bug, Functionality:Restore, Style:PackageReference, Triage:NeedsMoreInfo
