### ISSUE TITLE
Nuget.exe -ExcludeVersion parameter incorrect behavior

### ISSUE THREAD

**Issue by rymeskar** [NuGet/Home#4744] opened 2017-03-03 15:56 UTC
## Details about Problem

NuGet product used: NuGet.exe
NuGet version: 3.4.4.1321
OS version:  win10 v1607 (14393693):

1. ./nuget.exe install $nugetPackage -ExcludeVersion -Version 1.0.0.0
2. Leave the installed package in the folder
3. From the same folder ./nuget.exe install $nugetPackage -ExcludeVersion -Version 1.0.0.10
4. Nuget.exe won't download the new version and will just use the one in the current folder (whatever it is)

**Comment by emgarten** [comment] 2017-10-18 03:35
Duplicate of https://github.com/NuGet/Home/issues/3957

**Closed as completed by emgarten** 2017-10-18 03:35 UTC
Labels: Resolution:Duplicate, Product:NuGet.exe
