### ISSUE TITLE
NuGet.exe update -self ignores custom package source

### ISSUE THREAD

**Issue by petrciml** [NuGet/Home#5869] opened 2017-09-11 10:29 UTC
Hi, I have **build server in DMZ without internet access**. NuGet installed on this server using **only my own package source**; package source https://www.nuget.org/api/v2/ **is disabled**.
I need to update NuGet.exe using command "**nuget update -self**"
(current version of nuget.exe is 2.8) 
In package store is placed nupkg: **nuget.commandline.4.1.0.nupkg**
When I try run command "nuget update -self" error occurred:
 **"The remote name could be resolved: 'www.nuget.org'"**
It seems like custom package source is ignored in case of update -self command. Why? It is a bug?

OS: Win. Server 2012 R2 x64

Thanks, Petr

**Comment by emgarten** [comment] 2017-09-11 17:25
Dupe of https://github.com/NuGet/Home/issues/1783

**Closed as completed** 2017-09-11 23:21 UTC
Labels: Resolution:Duplicate
