### ISSUE TITLE
Possibly referencing the wrong DLL in Win10 universal apps

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#586] opened 2015-05-14 00:41 UTC
See:

http://stackoverflow.com/questions/30042728/attempting-to-deserialize-an-object-using-json-net-in-windows-10-universal-app-f

and:

https://social.msdn.microsoft.com/Forums/windowsapps/en-US/2e876e7b-d538-4005-8be2-62c7d66aeae0/jsonnet-error-in-win10-universal-apps

Referenced DLL: portable-net40+sl5+wp80+win8+wpa81
Optimal DLL: portable-net45+wp80+win8+wpa81+dnxcore50

Using VS2015 RC.

**Comment by yishaigalatzer** [comment] 2015-05-14 15:49
Duplicate of https://github.com/NuGet/Home/issues/454

**Closed by yishaigalatzer** 2015-05-14 15:49 UTC
