### ISSUE TITLE
Nuget version conflict solver

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8014] opened 2019-04-17 18:01 UTC
<p>Whenever I get an error like the following:</p><pre>Found conflicts between different versions of &quot;Newtonsoft.Json&quot; that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.</pre><p>Solving this issue is an adventure that can take hours of troubleshooting, when you have many Nuget packages loaded and each one loads others recursively, and the dependency tree becomes complex. Fixing it is a trial and error process that involves removing and adding again Nuget packages. Anytime I see that I have Nuget updates available, I fully backup everything, and wonder &quot;will installing these updates mess up everything again?&quot;.</p><p>Ideally, I would like to double-click on this message and see an assistant that shows me the different options available to solve the conflict and select one.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/447478/nuget-version-conflict-solver.html
VSTS ticketId: 787980_
_These are the original issue comments:_

Jane Wu [MSFT] on 2/11/2019, 02:57 AM (65 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by nkolev92** [comment] 2019-04-17 19:42
I don't think this is a NuGet thing. 

This talks about conflict resolution on the assembly level, which we do not handle. 
We just "select" assets. The rest is in MSBuild/SDK. 

In order for us to help with, we would need to own the assembly selection process which we don't.

**Comment by pablocar80** [comment] 2019-04-17 19:52
NuGet could build a tree of dependencies and suggest a set of working combinations.

**Comment by pablocar80** [comment] 2019-04-17 19:53
In other words, Nuget won't change the compile process, only help the user select the correct versions of packages.

**Comment by pablocar80** [comment] 2019-04-17 19:54
And selecting package versions happens at NuGet. The MSBuild receives the versions as an input and can't do much more than throw an error.

**Comment by nkolev92** [comment] 2019-04-17 20:39
As I mentioned in the above comment, the conflict above is not about selecting a package version, rather it talks about assembly level conflict resolution. 

NuGet already selected the best matching package version, and if not, NuGet will raise a respective warning to alert the user such as https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605. 
And the NU16xx class of warnings already do suggest possible solutions.

Nupkgs are only one of the ways to bring in assemblies into the compilation process.
SDKs/targets bring in assemblies as well. The user could also manually add a reference to an assembly on disk. 
That is the type of conflict resolution that MSBuild/SDK deal with.

**Comment by pablocar80** [comment] 2019-04-17 20:42
The issue I intended to report was about selecting package versions in NuGet. The error message reported can get fixed by uninstalling NuGet packages and reinstalling with different version numbers. That is a process that could be assisted instead of fully manual.

**Comment by nkolev92** [comment] 2019-04-17 21:02
> The error message reported can get fixed by uninstalling NuGet packages and reinstalling with different version numbers. That is a process that could be assisted instead of fully manual.

My point still stands, NuGet does not know all other assemblies used in the compilation process. 
Just because upgrading a package resolved the conflict, it doesn't mean that the problem is in the package in the first place. 
You probably just resolved it by getting a package with a higher assembly version number than the current ones. 

Say you have 2 version of the same package id, "Newtonsoft.Json".
`9.0.1` and `9.0.2`. 
That doesn't mean that the assembly version cannot be the same. 
A bad package could have a different assembly version for different target frameworks in the package. 
Another bad package could contain the assemblies of it's dependencies and that could unnecessarily cause a version conflict. 
A bad package could be named 'System.NicePackage`, but deliver assemblies named `Newtonsoft.Json`. 

Even if some part of the tooling would attempt to propose solutions to this problem (which again NuGet can't do), it'd require understanding all the possible options for the assembly, both brought in by targets and potentially by packages. 

The enhancement should be a clearer message on why the conflict exists.

**Comment by pablocar80** [comment] 2019-04-17 22:33
That would be a good enhancement, I agree, with the error message giving you clues on how to fix it. That's a very basic fix.

A better fix would be that after I upgrade and run into the error, I could get an "unable to upgrade" message due to version conflicts and that upgrade rolls back. This way I never put the source into a broken state.

An even better fix would be that Visual Studio figures out which NuGet packages you can update and how far.

**Comment by nkolev92** [comment] 2019-04-17 22:54
Note that version conflict is not an error, and not something that needs to be rolled back. 
For the most part this will work without a hitch. 

Combining concerns such as `Is this package compatible` and `Does installing this package cause some obscure warnings to be raised during build`, would mean that every time you install a package, the tooling would need to do a build. 

This would quickly lead to "installing a package is extremely slow". 

Deciding to try a newer version would be even more difficult. One package upgrade affects the rest of the package graph. Figuring all possible graphs would be an extremely expensive task, especially when you consider the cost of answering `Does installing this package cause some obscure warnings to be raised during build`.

I understand your concern and feel your pain, as I literally dealt with the same thing earlier today, https://github.com/NuGet/NuGet.Client/pull/2806/commits/65d9531c6c97cb9387771e6a32ebbb46231ca52a, but I am just trying to temper expectations about what can be done.

**Comment by nkolev92** [comment] 2020-04-23 17:29
At this point I don't believe there is a NuGet feature in this ask. 

Thank you for your feedback.

**Closed as completed by nkolev92** 2020-04-23 17:29 UTC
Labels: Type:Feature
