### ISSUE TITLE
Can dotnet pack include symbols in the same package?

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#5440] opened 2017-06-17 01:29 UTC
_From @thomaslevesque on June 16, 2017 23:46_

The `--include-symbols` switch creates a separate symbols package. However, a commonly used approach is to include the PDBs (patched with SourceLink or GitLink) directly in the main package. Is there a way to tell `dotnet pack` to include the PDBs in the main package, rather than a separate symbols package?

_Copied from original issue: dotnet/cli#6915_

**Comment by thomaslevesque** [comment] 2017-06-17 02:03
Thanks for moving the issue to the right place @nguerrera.

Not being able to do this forces us to use NuGet.exe and a .nuspec file, instead of building the package directly from the .csproj. It leads to issues like https://github.com/FakeItEasy/FakeItEasy/issues/1126, where we forgot to update the dependencies in the .nuspec to match the reference in the .csproj.

**Comment by rohit21agrawal** [comment] 2017-08-15 22:32
duplicate of : https://github.com/NuGet/Home/issues/4142

**Closed as completed by rohit21agrawal** 2017-08-15 22:32 UTC
Labels: Resolution:Duplicate, Functionality:Pack
