### ISSUE TITLE
Support declaring PackageSourceMappings via MSBuild items

### ISSUE THREAD

**Issue by baronfel** [NuGet/Home#12382] opened 2023-01-24 19:20 UTC
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

Packages provided directly via the SDK (via the pre-existing LibraryPacks feature or other mechanisms) previously have had some sharp edges with Package Source Mapping and Central Package Version Management. https://github.com/dotnet/sdk/issues/27840 is one example of this, but there have been some enhancements to those mechanisms to automatically filter out certain kinds of packages or package sources (e.g. https://github.com/NuGet/Home/issues/11951). This is a great approach, but a future-facing approach might be to allow the SDK to programmatically update Package Source and Mappings for sources and packages that it contributes via adding certain kinds of MSBuild metadata or items - that pushes the work onto the SDK team and relieves the NuGet logic from having to update these distinctions if the desired logic should change at some future time.

**Comment by aortiz-msft** [comment] 2023-01-30 21:41
Dupe of https://github.com/NuGet/Home/issues/11731

**Closed as completed by aortiz-msft** 2023-01-30 21:41 UTC
Labels: Type:Feature, Partner:MSBuild, Area:PackageSourceMapping
