### ISSUE TITLE
nuget.exe 3.4.2-rc fails to correctly restore PCL project

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#2597] opened 2016-04-17 08:26 UTC
nuget.exe 3.4.2-rc fails to correctly restore a PCL project that use to work.

project.json:

```
{
  "frameworks": {
    ".NETPortable,Version=v4.5,Profile=Profile259": {}
  },
  "runtimes": {
    "win": {}
  }
}
```

nuget 3.3 lock file (works)

```
{
  "locked": false,
  "version": 1,
  "targets": {
    ".NETPortable,Version=v4.5,Profile=Profile259": {},
    ".NETPortable,Version=v4.5,Profile=Profile259/win": {}
  },
  "libraries": {},
  "projectFileDependencyGroups": {
    "": [],
    ".NETPortable,Version=v4.5,Profile=Profile259": []
  }
}
```

nuget 3.4.2-rc lock file (breaks)

```
{
  "locked": false,
  "version": 2,
  "targets": {
    ".NETPortable,Version=v4.5,Profile=Profile259": {}
  },
  "libraries": {},
  "projectFileDependencyGroups": {
    "": [],
    ".NETPortable,Version=v4.5,Profile=Profile259": []
  }
}
```

msbuild then fails to build the solution with this error message:

```
Building C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Portable.sln
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 17/04/2016 7:48:28 PM.
Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Portable.sln" on node 1 (Clean;Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Portable.sln" (1) is building "C:\Development\Source\Newtonsoft.Json\Workin
g\Src\Newtonsoft.Json.Tests\Newtonsoft.Json.Tests.Portable.csproj" (2) on node 1 (Clean target(s)).
CoreClean:
  Creating directory "obj\Release\Portable\".
Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests\Newtonsoft.Json.Tests.Portable.csproj" (2) is building "C:\Developmen
t\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.Portable.csproj" (3) on node 1 (Clean target(s)).
CoreClean:
  Creating directory "obj\Release\Portable\".
Done Building Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.Portable.csproj" (Clean target(s)).
Done Building Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests\Newtonsoft.Json.Tests.Portable.csproj" (Clean target(s)
).
Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Portable.sln" (1) is building "C:\Development\Source\Newtonsoft.Json\Workin
g\Src\Newtonsoft.Json\Newtonsoft.Json.Portable.csproj" (3:3) on node 1 (Rebuild target(s)).
PrepareForBuild:
  Creating directory "bin\Release\Portable\".
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : Your project.json doesn't list 'win' as a targeted runtime. You
 should add '"win": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. [C:\Development\Source\Newtonsoft.Json\Wo
rking\Src\Newtonsoft.Json\Newtonsoft.Json.Portable.csproj]
Done Building Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.Portable.csproj" (Rebuild target(s)) -- FAILE
D.
Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Portable.sln" (1) is building "C:\Development\Source\Newtonsoft.Json\Workin
g\Src\Newtonsoft.Json.Tests\Newtonsoft.Json.Tests.Portable.csproj" (2:2) on node 1 (Rebuild target(s)).
PrepareForBuild:
  Creating directory "bin\Release\Portable\".
Done Building Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests\Newtonsoft.Json.Tests.Portable.csproj" (Rebuild target(
s)) -- FAILED.
Done Building Project "C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Portable.sln" (Clean;Rebuild target(s)) -- FAILED.

Build FAILED.

"C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Portable.sln" (Clean;Rebuild target) (1) ->
"C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\Newtonsoft.Json.Portable.csproj" (Rebuild target) (3:3) ->
(ResolveNuGetPackageAssets target) ->
  C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : Your project.json doesn't list 'win' as a targeted runtime. Y
ou should add '"win": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. [C:\Development\Source\Newtonsoft.Json\
Working\Src\Newtonsoft.Json\Newtonsoft.Json.Portable.csproj]

    0 Warning(s)
    1 Error(s)
```

Fix it please and write some unit tests so that it doesn't become a regression again.

**Comment by emgarten** [comment] 2016-04-18 04:15
This looks like a dupe of https://github.com/NuGet/Home/issues/2553

**Comment by JamesNK** [comment] 2016-04-18 04:26
It might be. If you have a preview version of a nuget.exe with that change somewhere I could test whether it is fixed.

**Comment by JamesNK** [comment] 2016-04-18 04:27
Also, you're missing unit tests for the change!

**Comment by emgarten** [comment] 2016-04-18 17:50
The nightly commandline build will have the fix, you can find it on: https://dist.nuget.org/index.html  Let me know if that solves the issue for you. It will be a 3.5.0 build, but this fix will go into the 3.4.3 RTM nuget.exe release which will be out as soon as possible.

There are tests covering restore with runtimes, the change here was to remove a feature that was in place for the CLI to leave runtimes out for portable frameworks such as `portable-*`, `dotnet`, and `netstandard`. That behavior was difficult to use and NuGet will now always apply runtimes specified in project.json without any special casing of frameworks.

**Comment by JamesNK** [comment] 2016-04-19 01:25
Hmm, it's up to you, but if it were my project I'd add a test that draws a line in the sand that for a given project.json input, nuget.exe has to produce a certain project.lock.json output. You will avoid future regressions.

**Comment by JamesNK** [comment] 2016-04-19 02:44
Nightly build fixed it. When do you estimate 3.4.3 will be out?

**Comment by emgarten** [comment] 2016-04-19 04:53
3.4.3 will be out later this week.

**Comment by rrelyea** [comment] 2016-04-19 17:06
great. sounds like you won't be blocked for long. closing.

**Closed as completed by rrelyea** 2016-04-19 17:06 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Restore
