### ISSUE TITLE
Something in nuget client is breaking mstest

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#6534] opened 2018-02-06 00:20 UTC
More info at the [original report](https://github.com/Microsoft/testfx/issues/241), including several repro cases and examples.

Reporting it here as advised. Please note the longevity of the issue and its subtle but evil effects.

From original issue:
when you run [that sample ](https://github.com/smadala/samples/blob/master/Test%20Explorer%20fails%20to%20show%20tests/ConsoleApp1/Program.cs)it fails but it does have an app.config:
https://user-images.githubusercontent.com/14079228/35814284-ad9088be-0a63-11e8-805a-534b548a9edc.png

If comment out the redirect it doesn't fail.
https://user-images.githubusercontent.com/14079228/35814317-c3636396-0a63-11e8-85be-aa65a3cdcbb7.png

**Comment by emgarten** [comment] 2018-02-06 00:24
@StingyJack would you provide some additional details here. I see binding redirects mention in the original issue, if you could provide a simple repro with the actual and expected outputs it would help make this issue actionable.

**Comment by StingyJack** [comment] 2018-02-06 00:28
the thread is long but a necessary read since you want repros and actual/expected descriptions.

**Comment by emgarten** [comment] 2018-02-06 00:44
I'm sorry but this issue does not currently contain enough information to prioritize it and put it into the team backlog. I will be happy to reopen this once this has been updated.

Please understand that NuGet is just one component in the .NET build system and that your issue may be caused by other components if your build process, or it may be caused by package authoring issue which cannot be fixed by NuGet.

**Closed as completed by emgarten** 2018-02-06 00:44 UTC
Labels: Resolution:NeedMoreInfo

**Comment by StingyJack** [comment] 2018-02-06 13:33
If you had read the last comment you would see that this was referred to the nuget team by Satya Madala [MSFT] after he found that nuget is creating incorrect assembly bindings. 

If you had scrolled up just a few posts form there you would see there are at least 3 repro cases immediately available from smadala, spottedmahn, and myself.

If you had scrolled up a bit farther you would see that this is causing tests to be silently skipped. I'm not sure if that part is nuget or mstest, but its a fairly nasty issue with code being shipped that is broken and unless you count and match lists of unit tests between builds, you probably wont notice it. 

> this issue does not currently contain enough information 

There are **62** comments on the issue, with multiple repro examples as well as MSFT analysis. You will not get many more issues as complete as this one. 

We  need this issue resolved, and I'm really not in the business of transcribing or summarizing or doing MSFT's paperwork for them by moving this issue report from one place to another. Want it merged a specific way? Please go ahead, but I already accept an absurd amount of imposition and work created for little or no benefit. and I'm not going to further that burden.

**Comment by StingyJack** [comment] 2018-02-07 21:01
@emgarten

**Comment by StingyJack** [comment] 2018-02-11 14:45
@rrelyea - this will be one of the things I would like to discuss on the call Chetan is arranging.
