### ISSUE TITLE
NuGet PM UI for Solution erroneously states "Blocked by packages.config" for a solution that contains a C++ project

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#8850] opened 2019-11-20 22:44 UTC
1. create a new c++ project
2. open PM UI for solution
3. search for "curl"
4. Observer the "version" combobox

![image](https://user-images.githubusercontent.com/16904420/69284766-3d58e700-0ba4-11ea-9e99-60701510844b.png)

**Comment by kartheekp-ms** [comment] 2019-11-25 20:41
@karann-msft - This issue should be fixed by #8679. I am unable to reproduce this issue on Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.5.0 Preview 2.0 [29522.92.master]

![issue](https://user-images.githubusercontent.com/52756182/69576273-cb581780-0f80-11ea-91e4-c2a4ec4f5964.png)

**Closed as completed by kartheekp-ms** 2019-11-25 20:41 UTC
Labels: Functionality:VisualStudioUI

**Comment by SilviuArdelean** [comment] 2019-11-25 22:46
Hi guys, and thank you for these great news! 
I just got last days upgrade to 16.3.10. When do you estimate the 16.5.0 will be released?

**Comment by kartheekp-ms** [comment] 2019-11-25 23:09
@SilviuArdelean - Bug fix is shipped in VS 16.4 version. Please refer to this [comment](https://github.com/NuGet/Home/issues/8679#issuecomment-542797407) if you are looking for a work around for prior versions.
