### ISSUE TITLE
[Bug]: PackTask can generate an invalid nupkg that is silently corrupt until attempt to list zip contents

### ISSUE THREAD

**Issue by jzabroski** [NuGet/Home#11053] opened 2021-07-20 15:16 UTC
### NuGet Product Used

dotnet.exe

### Product Version

5.0.302

### Worked before?

Not sure; discovered this while investigating NU5050 behaviors

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

You can trivially reproduce this by forcibly corrupting the inputs to GenerateNuspec (`@(NuGetPackInput)`), but I did observe this error in other ways.

This suggests PackTask is missing some sanity checks prior to generating the nupkg, but I did not delve inside PackTask to see why exactly this occurs.

```xml
  <Target Name="RemovePackageFiles" BeforeTargets="GenerateNuspec">
    <ItemGroup>
      <NuGetPackInput Remove="$(MSBuildProjectFullPath)" />
      <NuGetPackInput Remove="Web.config" />
      <NuGetPackInput Remove="Web.Alpha.config" />
      <NuGetPackInput Remove="Web.Beta.config" />
      <NuGetPackInput Remove="Web.Prototype.config" />
      <NuGetPackInput Remove="Web.Production.config" />
      <PackProjectInputFile Remove="$(MSBuildProjectFullPath)" />
      <_PackageFilesToExclude Include="Web.config" />
      <_PackageFilesToExclude Include="Web.Alpha.config" />
      <_PackageFilesToExclude Include="Web.Beta.config" />
      <_PackageFilesToExclude Include="Web.Prototype.config" />
      <_PackageFilesToExclude Include="Web.Production.config" />
      <_PackageFiles Remove="Web.config" />
      <_PackageFiles Remove="Web.Alpha.config" />
      <_PackageFiles Remove="Web.Beta.config" />
      <_PackageFiles Remove="Web.Prototype.config" />
      <_PackageFiles Remove="Web.Production.config" />
    </ItemGroup>
    <Warning Text="Tried to remove @(_PackageFiles)" />
    
    <Warning Text="Checking NuGetPackInput: @(NuGetPackInput)" />
  </Target>
```

**Comment by zivkan** [comment] 2021-07-23 22:14
In what way is the package invalid?  Can you prove a complete reproduction that I can run myself?

**Comment by jzabroski** [comment] 2021-07-24 01:03
The package is invalid because it can't be opened in NugetPackageExplorer or any zip utility.  NugetPackageExplorer complains about a "central directory" error.  PeaZip just bombs out completely.

I know that this happened to me - did you try the basic repro steps I provided first.  I think the fix for this bug is some basic sanity checks before real PackTask work is performed.

Alternatively, if PackTask has to be pipelined for performance, it should write the nupkg to a hidden file (leading .), and then delete the old file once its done... just thinking out loud.

**Comment by erdembayar** [comment] 2021-08-12 22:42
@jzabroski 
Could you be able to provide us reproducible repro code or sample project?
Currently not clear how you got corrupt zip/nupkg file. We need to repro in our side to investigate and fix it.

**Comment by aortiz-msft** [comment] 2021-09-02 18:49
We are closing this issue since we didn't hear back from you, but definitely let us know if you can still reproduce this problem on the latest version of NuGet. Thank you for your feedback and happy coding!

**Closed as completed by aortiz-msft** 2021-09-02 18:49 UTC
Labels: Type:Bug, Functionality:Pack, Product:dotnet.exe
