### ISSUE TITLE
[vsfeedback] build errors are not displayed as errors in case of reference issues

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4216] opened 2017-01-06 21:51 UTC
please see internal bug 296518 and the corresponding vsfeedback item. Some details:

**Comment by anangaur** [comment] 2017-10-02 05:48
Is this still an issue? This  has been a known issue since 15.3 RTW.

**Comment by zhili1208** [comment] 2017-10-17 23:29
@emgarten added to backlog for now

**Comment by anangaur** [comment] 2018-03-08 00:41
Dupe of https://github.com/NuGet/Home/issues/4113

**Closed as completed by anangaur** 2018-03-08 00:41 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Bug, Functionality:Restore
