### ISSUE TITLE
Package does not appear in the References list if added through the PMC in the certain way

### ISSUE THREAD

**Issue by agr** [NuGet/Home#5255] opened 2017-05-19 22:03 UTC
Package Manager Console Host Version 4.3.0.4045
VS 2017 15.3.26510.0-Preview

Repro steps:
1. Clone the [repository](https://github.com/agr/NugetUnparseableProjectJsonDemo/tree/another-bug) (make sure it's the `another-bug` branch);
2. Open the solution in VS;
3. Go to Package Manager Console;
4. Run `Install-Package andrei.testnugetpackage -source http://api.dev.nugettest.org/v3-index/index.json`;
5. Notice that the package does *not* appear in the "References" list in the project tree;
6. Neither it appears there after rebuild;

If the same package is added through the "Manage NuGet packages" UI (assuming the link above is added as a package source), the package properly appears in the "References" list.
It also works fine if instead of the command above the following command is used:
```
Install-Package Andrei.TestNugetPackage  -source http://api.dev.nugettest.org/v3-index/index.json
```
(notice the casing of the package name).

**Comment by emgarten** [comment] 2017-05-19 22:54
The reference should be written to project.lock.json and then displayed by the project system.

It seems strange that install-package and the UI would behave differently, so there could be a client problem here.

**Comment by agr** [comment] 2017-05-19 23:17
`Install-Package` seem to write to `project.json` the name as typed in the command line (all lower-case in failing case), which is probably the cause. When I use proper cased name in the command line it works as expected.

**Comment by emgarten** [comment] 2017-05-19 23:55
@tmeschter is this an issue in the build task for project.json or in the project system?

**Comment by tmeschter** [comment] 2017-05-22 15:52
@emgarten Almost certainly the build task. The project system pretty much just shows whatever list of packages the build task provides to it. It also wouldn't surprise me to find that the build task doesn't do the right thing with regards to casing.

**Comment by mishra14** [comment] 2017-11-09 23:27
dupe of internal issue 500532 fixed by https://github.com/NuGet/NuGet.BuildTasks/pull/40

**Closed as completed by mishra14** 2017-11-09 23:27 UTC
Labels: Resolution:Duplicate
