### ISSUE TITLE
For WinUI 3.0 Preview 3+ project builds it says "NuGet package restore failed" but error list does not show any error

### ISSUE THREAD

**Issue by LyalinDotCom** [NuGet/Home#10341] opened 2020-11-30 23:36 UTC
This bug is a follow-up to formally log the issue we've been talking about over email, where we get a NuGet restore failed message in dev16.9 Preview 1 for WinUI 3.0 packaged projects, but the logs dont show what failed.

## Details about Problem

VS version (if appropriate): Visual Studio 2019 version 16.9 Preview 1

## Detailed repro steps so we can see the same problem

1. Download WinUI 3.0 (Preview 3+) VS extension (see: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)
2. Create WinUI3 Project  (Blank App, Packaged (WinUI in Desktop))
3. Build the app, the message should appear

**Comment by nkolev92** [comment] 2020-12-02 21:59
Finally got to the bottom of it.

When you create this project type, there's a compat issue, the template is broken due to the following:

```
Project App1 is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763) / win10-x86-aot. Project App1 supports: net5.0-windows10.0.18362 (.NETCoreApp,Version=v5.0)
```

The root cause as to *why* the warnings are not displayed is the fact that the project is CPS based. 

NuGet PackageReference can be integrated through CPS or the VSProject4. 

NuGet handles the writing to the error list in VSProject4 integration, but CPS handles the writing to the error list in CPS projects.

**Comment by nkolev92** [comment] 2021-07-08 19:09
CLosing given it's external

**Closed as completed by nkolev92** 2021-07-08 19:09 UTC
Labels: Product:VS.Client, Type:Bug, Resolution:External, Functionality:Restore
