### ISSUE TITLE
suggestion: dotnet.exe support package upgrade & version check

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6054] opened 2017-10-18 15:59 UTC
_From @kjbetz on August 20, 2017 13:59_

Feature request.

Add command to upgrade packages and/or do a version check on packages used in `.csproj`

Suggest: `dotnet package upgrade` and/or `dotnet package check`

Make it interactive to be able to update `.csproj` 

Idea similiar to this: https://www.npmjs.com/package/npm-check

_Copied from original issue: dotnet/cli#7483_

**Comment by livarcocc** [comment] 2017-10-18 15:59
_From @kjbetz on October 18, 2017 12:24_

I was using yarn last night and saw that this is an included feature for them. `yarn upgrade` and `yarn upgrade-interactive` 

https://yarnpkg.com/lang/en/docs/cli/upgrade/

https://yarnpkg.com/lang/en/docs/cli/upgrade-interactive/

Definitely very handy! Very much needed in my opinion for .NET Core CLI users.

**Comment by livarcocc** [comment] 2017-10-18 15:59
_From @kjbetz on October 18, 2017 12:33_

I suggest a `dotnet package upgrade` and `dotnet package upgrade-interactive` or `dotnet package upgrade --interactive`

As well as some of the other features listed in the yarn... we used `--latest` and it was very handy as we use absolute/exact version numbers.

**Comment by livarcocc** [comment] 2017-10-18 15:59
I believe there is an issue under nuget/home for this already. I will move this issue there and have them close this one as a dup if that's the case.

**Comment by kjbetz** [comment] 2017-10-18 18:51
I'm surprised this is closed... is this not a dotnet CLI request? Just as there is a `dotnet add` and `dotnet remove` 

Do those call nuget under the covers?

**Comment by livarcocc** [comment] 2017-10-18 18:55
@kjbetz the issue was not closed, but rather moved to a more appropriate repo. The dotnet add and dotnet remove commands, for packages, while surfaced in the CLI, are actually implemented by NuGet. We also have an ongoing conversation with NuGet about a dotnet update command. So, it makes sense to have it here.

**Comment by kjbetz** [comment] 2017-10-18 18:57
@livarcocc Thanks Livar, I appreciate the response. I think I understand more clearly now and see that it was labeled XPLAT, which is important. Thanks!

**Comment by mishra14** [comment] 2017-11-09 22:47
@kjbetz This is a dupe of https://github.com/NuGet/Home/issues/4103 and https://github.com/NuGet/Home/issues/4102.

We want to add support for `dotnet list package` and `dotnet update package` commands. In the meantime you can use `dotnet add package <package_id> --version <new_version>` and that will update the package reference in the csproj file.

**Closed as completed by mishra14** 2017-11-09 22:47 UTC
Labels: Priority:2, Product:NuGet.exe, Platform:Xplat

**Comment by kjbetz** [comment] 2017-11-14 19:10
@mishra14 Ok... but how do you know what the `<new_version>` is? I really suggest checking out how yarn has taken care of this, including the interactive upgrade. I just spent another time looking through my `.csproj` and searching nuget.org to see what the latest package versions were. There has to be a better way.

**Comment by rlm95** [comment] 2017-11-15 18:34
I know previously on dotnet sdk 2.0.0 it worked where you were able to do `dotnet add package <package_id>` and it would automatically update to the latest version. On dotnet sdk 2.0.2 it no longer works like this.
