### ISSUE TITLE
Unhelpful exception with RestoreCommand

### ISSUE THREAD

**Issue by lbargaoanu** [NuGet/Home#6387] opened 2018-01-05 15:20 UTC
While using the API for restore, I'm trying to install a package that doesn't exist. Also one of the sources doesn't exist. Restore fails with an unhelpful exception. [Details](https://gist.github.com/lbargaoanu/17344fcecda10db2b4b9aff46c27185a).
Version 4.05.0.4685.

**Comment by zhili1208** [comment] 2018-01-05 19:38
we should remove all those unhelpful exception, it's a dupe of https://github.com/NuGet/Home/issues/5779

**Closed as completed by zhili1208** 2018-01-05 19:38 UTC
Labels: Resolution:Duplicate

**Comment by lbargaoanu** [comment] 2018-01-05 19:54
Thanks for the info.

**Comment by lbargaoanu** [comment] 2018-06-18 09:44
I think this issue was closed in error. It still happens with 4.7.0. If a local source doesn't exist or an http source is not reachable, the restore fails even when other sources have the missing package (IgnoreFailedSources is true). The same thing happens in Visual Studio 2017 15.7.3.
