### ISSUE TITLE
Windows 10, VS2015U3, NuGet 3.5 install package issue with Facade assemblies

### ISSUE THREAD

**Issue by niemyjski** [NuGet/Home#3103] opened 2016-07-09 15:21 UTC
I created a new ASP.NET MVC Project (.NET 4.5.1) and then opened the package manager console and tried to install our package...

```
PM> Install-Package Exceptionless -Version 4.0.1880-Pre -Verbose


Attempting to gather dependency information for package 'Exceptionless.4.0.1880-Pre' with respect to project 'WebApplication8', targeting '.NETFramework,Version=v4.5.1'
  GET https://api.nuget.org/v3/registration1-gz/exceptionless/index.json
  OK https://api.nuget.org/v3/registration1-gz/exceptionless/index.json 119ms
  GET https://api.nuget.org/v3/registration1-gz/exceptionless/page/4.0.1873-pre/4.0.1880-pre.json
  OK https://api.nuget.org/v3/registration1-gz/exceptionless/page/4.0.1873-pre/4.0.1880-pre.json 64ms
Total number of results gathered : 31
Gathering dependency information took 458.63 ms
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json -   203.31 ms
Attempting to resolve dependencies for package 'Exceptionless.4.0.1880-Pre' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Exceptionless.4.0.1880-Pre'
Resolved actions to install package 'Exceptionless.4.0.1880-Pre'
Retrieving package 'Exceptionless 4.0.1880-pre' from 'nuget.org'.
For adding package 'Exceptionless.4.0.1880-pre' to project 'WebApplication8' that targets 'net451'.
For adding package 'Exceptionless.4.0.1880-pre' to project 'WebApplication8' that targets 'net451'.
Adding package 'Exceptionless.4.0.1880-pre' to folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages'
Added package 'Exceptionless.4.0.1880-pre' to folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages'
Removed reference 'Exceptionless.dll' from project 'WebApplication8'
Added reference 'Exceptionless' to project 'WebApplication8'.
Install failed. Rolling back...
Package 'Exceptionless.4.0.1880-pre' does not exist in project 'WebApplication8'
Removing package 'Exceptionless.4.0.1880-pre' from folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages'
Removed folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre\lib\portable46-net451+win81+wpa81'.
Removed folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre\lib\netstandard1.2'.
Removed folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre\lib\netstandard1.3'.
Removed folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre\lib\netstandard1.4'.
Removed folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre\lib\netstandard1.5'.
Removed folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre\lib\net45'.
Removed folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre\lib'.
Removed file 'Exceptionless.4.0.1880-pre.nupkg' from folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre'.
Removed folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages\Exceptionless.4.0.1880-pre'.
Removed package 'Exceptionless.4.0.1880-pre' from folder '\\mac\home\documents\visual studio 2015\Projects\WebApplication8\packages'
Executing nuget actions took 2.19 sec
Install-Package : Failed to add reference. The package 'Exceptionless' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
At line:1 char:1
+ Install-Package Exceptionless -Version 4.0.1880-Pre -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Time Elapsed: 00:00:02.6831588
PM> 
```

https://www.nuget.org/packages/Exceptionless/4.0.1880-pre

And I get an install error `Install-Package : Failed to add reference. The package 'Exceptionless' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.` The issue is my package doesn't define any assembly references (only in the .net standard packages...) I don't get why it's happening. Also, it seemsl ike the exceptionless packages folder is removed but the assembly reference isn't removed from the project references list.

![screen shot 2016-07-09 at 10 21 09 am](https://cloud.githubusercontent.com/assets/1020579/16708587/e3af85fa-45be-11e6-9991-9b9d45b60129.png)

**Comment by niemyjski** [comment] 2016-07-09 15:22
Please let me know if this is in the wrong repo.

**Comment by scottcate** [comment] 2016-07-09 18:03
I'm experiencing this same issue. Thank you for any guidance.

**Comment by niemyjski** [comment] 2016-07-09 20:29
My latest commit (https://github.com/exceptionless/Exceptionless.Net/commit/c7becdb6e59356825ba296c92c4d7fd1debc1f86) seems to have fixed it. I changed the portable projects framework dependencies to build time.. Which is crazy because my net451 project shouldn't even be looking at the portable projects dependencies..

**Comment by niemyjski** [comment] 2016-07-12 17:54
- https://github.com/scottksmith95/LINQKit/issues/37
- https://github.com/StephenCleary/Deque/pull/1

There is an issue here that needs to be resolved asap... There seems to be an installer issue when you have `frameworkAssemblies` that are not a build time dependency..

**Comment by shanselman** [comment] 2016-07-12 18:00
I need more information to route this. Do you think this is a NuGet issue, or a VS issue? What went wrong, when? @csharpfritz

**Comment by niemyjski** [comment] 2016-07-12 18:07
I think it's a nuget issue, package install just fails. You can reproduce it very easily..

``` json
{
  "frameworks": {
    "netstandard1.0": {
      "dependencies": {
        "System.Collections": "4.0.11",
        "System.Runtime": "4.1.0"
      }
    },
    ".NETPortable,Version=v4.5,Profile=Profile259": {
      "frameworkAssemblies": {
        "System.Collections": "",
        "System.Runtime": ""
      }
    }
  }
}
```

Then create a new `NET45+` Console app (You can even remove all the project dependencies) and try to install the package. It will pick the `. NETPortable` framework and fail with a gac issue for collections or runtime. I've seen the same if you define full framework and have hit it in all of our [exceptionless](https://github.com/exceptionless) packages.

If you don't want to define a simple package just use @StephenCleary's package https://www.nuget.org/packages/Nito.Collections.Deque/1.0.0-delta-8

**Comment by StephenCleary** [comment] 2016-07-12 18:09
Note that `Nito.Collections.Deque 1.0.0-delta-9` works around this problem by making its framework assemblies build-time dependencies, similar to this:

```
".NETPortable,Version=v4.5,Profile=Profile259": {
  "frameworkAssemblies": {
    "System.Collections": { "type": "build" },
    "System.Runtime": { "type": "build" }
  }
}
```

But this feels wrong to me, since they are not build-only dependencies.

**Comment by rrelyea** [comment] 2016-07-12 22:11
@StephenCleary has the right workaround, we believe.
#2193 deals with Façade assemblies. Let's close this issue, as it is a dupe of that.

**Closed as completed by rrelyea** 2016-07-12 22:11 UTC
