### ISSUE TITLE
PathTooLongException for nuget.exe install -excludeversion

### ISSUE THREAD

**Issue by pvandervelde** [NuGet/Home#5324] opened 2017-06-01 21:55 UTC
Using the nuget command line executable, version 4.1.0.2450 on Win 10 (v1607 - 14393.1198)

## Repro steps

1. Trying to install our internal package called `Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure` at version `0.3.0-infrastructurebuilds` to the packages directory at `C:\vcs\tfs\vista\devinfrastructure\Template-Resource.Linux.Ubuntu.Server\packages`. Using the following command line:

        nuget install Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure -Version 0.3.0-infrastructurebuilds -Source \\aktfsfile01\nuget_dev -ExcludeVersion -Verbosity detailed

2. This fails with a PathTooLongException (see logs below)
3. Installing the package in a different directory and then copying it over to the original target leads to having a maximum file path length of  212 characters (i.e. at least 40 characters short of the maximum path length)

If I understand the problem correctly (which I may very well not do) from the stack trace and the source code the problem seems to occur when NuGet tries to determine if the package already exists by searching for the `nupkg` file at

    Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure.0.3.0-infrastructurebuilds\Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure.0.3.0-infrastructurebuilds.nupkg

instead of searching for
    Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure\Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure.nupkg

Obviously the former will be over the maximum path length but that is one of the reasons we install with `-excludeversion`

I tried building a copy of the NuGet commandline project but I couldn't make it work on my machine so I can't give any further details other than what I gathered from the logs and looking at the source code.

### Verbose Logs

	NuGet Version: 4.1.0.2450
	Feeds used:
	  C:\Users\Patrick.VanDerVelde\.nuget\packages\
	  \\aktfsfile01\nuget_dev

	Attempting to gather dependency information for package 'Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure.0.3.0-infrastructurebuilds' with respect to project 'C:\vcs
	\tfs\vista\devinfrastructure\Template-Resource.Linux.Ubuntu.Server\packages', targeting 'Any,Version=v0.0'
	Missing C:\Users\Patrick.VanDerVelde\.nuget\packages\vista.devinfrastructure.tools.pipeline.actions.infrastructure\0.3.0-infrastructurebuilds\vista.devinfrastructure.tools.pipeli
	ne.actions.infrastructure.0.3.0-infrastructurebuilds.nupkg
	Total number of results gathered : 20
	Gathering dependency information took 170.05 ms
	Summary of time taken to gather dependencies per source :
	\\aktfsfile01\nuget_dev	-	119.36 ms
	C:\Users\Patrick.VanDerVelde\.nuget\packages\	-	31.6 ms
	C:\vcs\tfs\vista\devinfrastructure\Template-Resource.Linux.Ubuntu.Server\packages	-	14.47 ms
	Attempting to resolve dependencies for package 'Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure.0.3.0-infrastructurebuilds' with DependencyBehavior 'Lowest'
	Resolving dependency information took 0 ms
	Resolving actions to install package 'Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure.0.3.0-infrastructurebuilds'
	Resolved actions to install package 'Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastructure.0.3.0-infrastructurebuilds'
	Executing nuget actions took 12.73 ms
	nuget : System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified 
	file name must be less than 260 characters, and the directory name must be less than 248 characters.
	At line:1 char:1
	+ nuget install Vista.DevInfrastructure.Tools.Pipeline.Actions.Infrastr ...
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (System.Aggregat...248 characters.:String) [], RemoteException
		+ FullyQualifiedErrorId : NativeCommandError
	 
	   at System.IO.PathHelper.GetFullPathName()
	   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
	   at System.IO.Path.GetFullPathInternal(String path)
	   at NuGet.ProjectManagement.FolderNuGetProject.GetInstalledPackageFilePath(PackageIdentity packageIdentity)
	   at NuGet.PackageManagement.PackagePreFetcher.<GetPackagesAsync>d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__73.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__73.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__30.MoveNext()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at NuGet.CommandLine.Command.Execute()
	   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
	---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, 
	and the directory name must be less than 248 characters.
	   at System.IO.PathHelper.GetFullPathName()
	   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
	   at System.IO.Path.GetFullPathInternal(String path)
	   at NuGet.ProjectManagement.FolderNuGetProject.GetInstalledPackageFilePath(PackageIdentity packageIdentity)
	   at NuGet.PackageManagement.PackagePreFetcher.<GetPackagesAsync>d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProject
	ActionsAsync>d__73.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__73.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__30.MoveNext()<---

**Comment by pvandervelde** [comment] 2017-06-13 21:07
@emgarten @maartenba Any idea on what is going on here? Is there a switch or configuration setting we can use to make this work as expected or are we doing something wrong?

**Comment by emgarten** [comment] 2017-06-14 02:50
You could try turning on long path support in Windows 10.

Apart from that there is no option to disable this in NuGet. It looks like NuGet should catch this exception when simply probing for packages instead of failing.

**Comment by pvandervelde** [comment] 2017-06-14 03:11
Wouldn't it make sense for NuGet to take into account if the ExcludeVersion flag has been set? I'm assuming the majority of the code does but apparently the search / path calculation does not?

**Comment by emgarten** [comment] 2017-06-14 03:47
> Wouldn't it make sense for NuGet to take into account if the ExcludeVersion flag has been set?

It would in this scenario. But the vast majority of the scenarios always use versions and this is taking advantage of the same core code for reading package folders.

**Comment by pvandervelde** [comment] 2017-06-14 04:11
Ah right. In that case it would probably be enough for NuGet to catch the exception if that is possible.

**Comment by rohit21agrawal** [comment] 2017-10-11 23:46
some related issues: https://github.com/NuGet/Home/issues/1685 
https://github.com/NuGet/Home/issues/5835
https://github.com/NuGet/Home/issues/6011

**Comment by nkolev92** [comment] 2017-10-17 23:40
Duplicate of https://github.com/NuGet/Home/issues/3324

**Comment by emgarten** [comment] 2018-01-30 20:58
Reopening this, it isn't quite the same as the other path too long issue because this *should* work, but NuGet does extra probing that fails and it isn't handled gracefully.

**Closed as completed** 2018-01-30 21:23 UTC
Labels: Resolution:Duplicate, Product:NuGet.exe, Functionality:Install
