### ISSUE TITLE
Referenced dependencies not being copied to bin folder

### ISSUE THREAD

**Issue by NunoOlliveira** [NuGet/Home#10181] opened 2020-10-23 18:11 UTC
Microsoft Visual Studio Professional 2019
Version 16.7.6
Windows 10 X64
It is working using package.config management.

Hello everyone.

For testing I have created 3 supper usefull C# projects targetting .Net Framework 4.8.
ClassLibrary2.dll
ClassLibrary1.dll (References ClassLibrary2 instantiated in the constructor)
WindowsFormsApp.exe
Created a Nuget package, added the dll files on the lib\net48 folder and added ClassLibrary1 to Assembly References.
Added the Nuget package to the WindowsFormsApp project.
The Problem:
Rebuilding the project, only ClassLibrary1.dll is added to the output folder.
Both file exists in the .nuget\packages\testing.dependency\1.0.0\lib\net48 folder.
If I reference manually the ClassLibrary1.dll in VS, it will copy both correctlly.

The only relevant log that I found on the output window was:

"C:\Users\User\.nuget\packages\testing.dependency\1.0.0\lib\net48".
1>                For SearchPath "C:\Users\User\.nuget\packages\testing.dependency\1.0.0\lib\net48".
1>                Considered "C:\Users\User\.nuget\packages\testing.dependency\1.0.0\lib\net48\ClassLibrary2.winmd", but it didn't exist.
I have already tryied everything without success.

[ProjectTest.zip](https://github.com/NuGet/Home/files/5431106/ProjectTest.zip)

Thank you.

**Comment by donnie-msft** [comment] 2020-10-23 22:50
How exactly did you pack your project? Did you follow the explicit assembly reference guidance here? https://docs.microsoft.com/en-us/nuget/reference/nuspec#explicit-assembly-references

Thanks for reporting. Please fill out the Issue template here: https://github.com/NuGet/Home/issues/new
This helps in understanding your product versions and scenario.

**Comment by NunoOlliveira** [comment] 2020-10-24 17:06
Hello, and thank you for the reply.
Yes (I think so), and it does work correctlly using the package.config management.
Here is the nuspec file example:
[Testing.Dependency.1.0.0.nuspec.zip](https://github.com/NuGet/Home/files/5433328/Testing.Dependency.1.0.0.nuspec.zip)
ClassLibrary1 is added correctly to the project and **I don't want** ClassLibrary2 to be directlly available to the exe project.
Since ClassLibrary1 depends on ClassLibrary2, on build it should be copied to the output folder, and its not.
![image](https://user-images.githubusercontent.com/60079921/97087642-69d27a00-1623-11eb-99b1-420299a75bb0.png)
Best Regards

**Comment by zkat** [comment] 2020-11-05 18:20
@v-luzh hey, do you mind seeing if you can repro this issue?

**Comment by zkat** [comment] 2020-11-05 18:23
@v-luzh do you mind taking a look at this and seeing if you can repro it?

This is potentially a duplicate of https://github.com/NuGet/Home/issues/4488

**Comment by v-luzh** [comment] 2020-11-20 14:54
@zkat I got below log in Output window with the solution provided by customer on D16.7\30330.147 VS Enterprise 2019. There are both ClassLibrary1.dll and ClassLibrary2.dll in Output window. So, is that means we cannot repro?
![Screenshot](https://user-images.githubusercontent.com/20632625/99813755-0d5f6d80-2b83-11eb-9b0d-3d72e4dce2b0.JPG)

**Comment by zkat** [comment] 2020-11-23 21:19
@NunoOlliveira could you review the last reply from @v-luzh? It looks like we're not able to repro this.

**Comment by nkolev92** [comment] 2020-12-07 21:09
Feel free to comment or open a new issue if you have more information.

**Closed as completed by nkolev92** 2020-12-07 21:09 UTC
Labels: Priority:2, Resolution:NotRepro, Functionality:Pack, WaitingForCustomer
