### ISSUE TITLE
[Feature]: Allowed export list package to CSV,Json,XML

### ISSUE THREAD

**Issue by workgroupengineering** [NuGet/Home#11730] opened 2022-04-08 13:20 UTC
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Manager Console, dotnet.exe, NuGet SDK

### The Elevator Pitch

Add the ability to export the output of the list package command to a file in CSV, Json, XML format so that you can easily manipulate it.

### Additional Context and Details

I would need it to create a script that checks for new package versions.

**Comment by JonDouglas** [comment] 2022-04-08 14:41
This is a dupe of https://github.com/NuGet/Home/blob/dev/proposed/2022/DotnetListPackageMachineReadableJsonOutput.md

Closing for now.

**Closed as completed** 2022-04-08 14:41 UTC
Labels: Type:Feature
