### ISSUE TITLE
Pack succeeded but with no .nupkg generated for ASP.NET core web project

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#5084] opened 2017-04-20 18:35 UTC
_From @mlorbetske on April 20, 2017 3:58_

_From @MiaomiaoHuangfu on April 17, 2017 9:52_

create an ASP.NET Core web project, right click the project and click "Pack".

- Expected result: .nupkg is generated under the path bin\debug;
- Actual result: .nupkg is not generated under the path bin\debug or other path. 

![packsucceededwithnonupkggenerated](https://cloud.githubusercontent.com/assets/22901391/25085783/80591c62-2396-11e7-9bf5-04dfa4c27974.PNG)

Test on vsuwpt.26414.03
OS: windows 10 X64

_Copied from original issue: aspnet/Tooling#1030_

_Copied from original issue: dotnet/project-system#2024_

**Comment by MiaomiaoHuangfu** [comment] 2017-05-09 08:49
The issue is not repro on d15rel.26507.00.

**Comment by rohit21agrawal** [comment] 2017-05-11 01:14
closing this since no repro. please activate if you encounter this again.

**Closed as completed by rohit21agrawal** 2017-05-11 01:14 UTC
