### ISSUE TITLE
Build fails claiming I'm missing 'win' as targeted runtime (regression in v3.4.2.830)

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#2553] opened 2016-04-15 04:43 UTC
With nuget.exe 3.4.2.830, after a restore the build fails, claiming I'm missing something from my project.json that in fact _is there_. Earlier versions of nuget.exe do not have this bug.

```
git clone https://github.com/AArnott/pinvoke.git
cd pinvoke
git checkout 39b6f721395a
cd src
nuget restore
msbuild Kernel32.Tests.Portable\Kernel32.Tests.Portable.csproj
```

**Expected**

A successful build. As I see with NuGet.exe 3.3.

**Actual**

```
  CodeGenerationAttributes -> C:\Users\andarno\git\pinvoke\bin\Debug\Profile92\CodeGenerationAttributes.dll
  CodeGeneration -> C:\Users\andarno\git\pinvoke\bin\Debug\Desktop\CodeGeneration.dll
  Windows.Core -> C:\Users\andarno\git\pinvoke\bin\Debug\Profile92\PInvoke.Windows.Core.dll
  Kernel32 -> C:\Users\andarno\git\pinvoke\bin\Debug\Profile92\PInvoke.Kernel32.dll
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : Your project.json doesn't list 'win' as a targeted runtime. You should add '"win": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. [C:\Users\andarno\git\pinvoke\src\Kernel32.Tests.Portable\Kernel32.Tests.Portable.csproj]
```

**Comment by emgarten** [comment] 2016-04-15 08:30
This is caused by NuGet trying to infer if the framework should restore runtime dependencies. For `portable-*` frameworks they are skipped but it looks like that needs to change.

**Comment by emgarten** [comment] 2016-04-16 05:44
This will be fixed in 3.4.3
NuGet/NuGet.Client@a4fd57c416e8c5574f71e93a8881df1c2e08c2ac

**Closed as completed by emgarten** 2016-04-16 05:44 UTC
Labels: Product:NuGet.exe

**Comment by TheRealPiotrP** [comment] 2016-04-19 23:29
When should we expect this fix make it into a PR to dotnet/cli?

**Comment by TheRealPiotrP** [comment] 2016-04-20 22:06
:eyes:

**Comment by emgarten** [comment] 2016-04-20 23:11
@piotrpMSFT this week
