### ISSUE TITLE
Unable to package node/meteor apps - PathTooLongException

### ISSUE THREAD

**Issue by georgiosd** [NuGet/Home#1685] opened 2015-11-05 11:22 UTC
Adding a few packages that have their own dependencies to a node/meteor app easily exceeds the max.

e.g.

`D:\r\.meteor\local\isopacks\finlabs_analytics\npm\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\node_modules\degenerator\node_modules\escodegen\node_modules\esprima\package.json`

**Comment by yishaigalatzer** [comment] 2015-12-11 00:30
Thanks for submitting this issue. I look at the PR as well, and I have a couple of notes and issues with it.

Ultimately the question here is if .NET proper is going to start supporting long paths, which makes NuGet just work.

The main question I'm asking about this fix is that it only works for very specific scenarios, and it is not going to make NuGet work across the board with long paths. So is it worth taking it in as a partial fix?

Other things to consider
1. Packing is moving out of nuget.core in the next release, so the fix will need to go into two places.
2. I'm making a few code review comments on the original PR (worth the time if we take it or not)

CC @davidfowl 

I'm open to discussing this some more and see how much we want to take it in.

**Comment by georgiosd** [comment] 2015-12-11 09:59
Agreed with all your comments on the PR - I needed a quick fix to move on with my use case and didnt spend time refactoring the code I found at codeproject.

Even if .NET starts supporting long paths, won't it require newer versions of the CLR to work? So if .NET 5 makes it happen I presume that all 3.x and 4.x lines will stay broken.

Why do you say it's a partial fix? It seems to me that this is supported at least all the way back to XP: https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx

**Comment by yishaigalatzer** [comment] 2015-12-11 18:38
Because it only supports packing. I'm guessing other use cases of consuming the package might still fail

**Comment by yishaigalatzer** [comment] 2015-12-31 01:31
We also need to test this on Linux (where I suspect it will just work).

To answer your PathTooLong on .NET 3.x and 4.x, we are working on a version that runs on coreCLR so it will be running isolated from the .NET on your box

**Comment by nkolev92** [comment] 2017-10-17 23:42
Duplicate of https://github.com/NuGet/Home/issues/3324

**Closed as completed by nkolev92** 2017-10-17 23:42 UTC
Labels: Type:Bug, Functionality:Pack
