### ISSUE TITLE
Add package: specify dependency resolution strategy

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7064] opened 2018-06-26 16:21 UTC
_From @shatl on June 26, 2018 14:5_

Add option to specify dependency resolution strategy ```dotnet add package```

* Exact - install dependency version specified in nuspec file;
* HighestPatch - install highest available minor version for major version specified in nuspec;
* HighestMinor - install highest available minor and patch version for major version specified in nuspec;
* HighestMajor (Latest) - install latest version.

E.g. nuspec dependency version is *1.1.1*, nuget has *1.1.10*, *1.2.1*, and *2.1.1*

* `Exact` should install 1.1.1;
* `HighestPatch` should install 1.1.10;
* `HighestMinor` should install 1.2.1;
* `HighestMajor` should install 2.1.1

_Copied from original issue: dotnet/cli#9560_

**Comment by mishra14** [comment] 2018-06-26 18:37
@shatl Thanks for the request. 

We currently do support `HighestMajor` - 
`dotnet add package X` or `dotnet add package X --version *`


Supporting rest of the options is not a straight forward fix because of the following - 

1. `dotnet add package` command invokes restore with the new dependency.
2. Currently, restore does not support passing any of those switches. 
3. One other way is to have the knowledge of all versions and resolve the switch and pass the version to restore. But that would require changes and add package does not have visibility to available versions.

**Comment by nkolev92** [comment] 2018-07-01 19:59
Since as @mishra14 said, dotnet add package simply does restore under the hood. it's a restore "behavior", nothing specific to add package. 

This is a duplicate of https://github.com/NuGet/Home/issues/6848. 

This has historically been an unpopular ask because of the inconsistencies it would cause. 
The opinion normally is that floating is a consumer time feature not a authoring time feature. 
The .NET world in general has had a lot of compatibility problems with bumped up versions.

**Closed as completed by nkolev92** 2018-07-01 19:59 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Feature, Platform:Xplat, Functionality:Restore
