### ISSUE TITLE
Feature Request: Validate targetFramework string on pack

### ISSUE THREAD

**Issue by ravensorb** [NuGet/Home#2871] opened 2016-06-01 00:30 UTC
It would be extremely helpful if the targetFramework string was validated on pack -- this would prevent a lot of potential errors that right now are only discovered on distribution.

**Comment by emgarten** [comment] 2017-12-19 22:33
Duplicate of https://github.com/NuGet/Home/issues/2301

**Closed as completed by emgarten** 2017-12-19 22:33 UTC
Labels: Resolution:Duplicate, Functionality:Pack
