### ISSUE TITLE
Force update nuget without roleback?

### ISSUE THREAD

**Issue by RonSijm** [NuGet/Home#10329] opened 2020-11-27 19:38 UTC
Hi there,

I'm wondering if it's possible to force nuget to just update all my nugets to the latest version in the .csproj file, disregard everything else, and just set the version numbers to the latest version?

It's becoming very tedious to update nugets, because basically for no apparent reason, for every nuget I'm trying to update it'll say "Update failed, rolling back" for no apparent reason, and I manually have to check what the latest version of the nuget is, change it in the .csproj file, and repeat until everything is "up to date"

There must be a way to just force nuget to update packages without confirming anything, and then deciding to roll back... right?

**Comment by nkolev92** [comment] 2020-12-02 02:35
Hey @RonSijm, 

there's no way to force NuGet to update. 
NuGet package installation runs restore to check for compatibility, so if the package installation fails, it's likely that restore fails as well.

We know that the failure reason can be a bit tricky to find, but the Package Manager output window *should contain* it. 

Would you be able to provide us a repro project/action or provide some screenshots/recording so we can better understand your scenario. 

Thanks!

Also, please try 16.8! We recently made some changes that should drastically improve the performance of the installation behavior.

**Comment by nkolev92** [comment] 2020-12-07 21:56
Closing as by design.

**Closed as completed by nkolev92** 2020-12-07 21:56 UTC
Labels: Product:VS.Client, Resolution:ByDesign, Functionality:VisualStudioUI, Area:ErrorHandling, Functionality:Install
