### ISSUE TITLE
nuget pack forcefully adds .tt files to content folder no matter what

### ISSUE THREAD

**Issue by Ackara** [NuGet/Home#3203] opened 2016-07-24 12:34 UTC
If my project contains a .tt (T4 Template) file, and run the **nuget pack** command. All of the .tt files will be added to the package's content folder, regardless if you try to exclude the .tt files in the .nuspec.

Right now all of my .tt files are being forcefully packaged and breaking some of my builds please fix this.

I have attached a sample project so that you guys can see for yourself. Run the build.ps1.

The nuget version is 3.4.4 (The latest as of today)

[NugetIssue.zip](https://github.com/NuGet/Home/files/380254/NugetIssue.zip)

**Comment by rrelyea** [comment] 2016-07-25 15:18
Can you please try this out with 3.5.0-beta2 or 3.5.0-rc (daily build) from http://nuget.org/downloads.
Still an issue?

**Comment by Ackara** [comment] 2016-07-25 17:11
Yes, the same issue occur when using v 3.5.0. However it works as expected with version v 3.4.3.

**Comment by rrelyea** [comment] 2016-07-25 20:58
Duplicate of #3149

**Closed as completed** 2016-07-25 23:46 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Pack

**Comment by fruby** [comment] 2017-10-11 22:31
This reproes when I try to use the nuget pack task in vsts continuous integration. The version I use is 2.*

**Comment by mdchafin** [comment] 2018-09-26 20:47
I'm having the same issue today.
