### ISSUE TITLE
.NET SDK 2.1.500 Auth problem with NuGet Source with space in its name (the credentials are not encoded)

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7516] opened 2018-11-16 07:24 UTC
_From @jarz on November 14, 2018 17:55_

# Unable to dotnet restore from a private VSTS feed

In Azure DevOps (VSTS) I'm unable to use the latest SDK (2.1.500) to build my project, as it relies upon a package in my private feed. However, if I use SDK 2.1.403 the build succeeds.

I see a `401 Unauthorized` in the log. My account has the _Package Management_ license assigned (and it'd be a `402 Payment Required` if I didn't).

I use the .NET Core Installer task at the beginning of my build pipeline.

Log: https://gist.github.com/jarz/56d3ec2b0e3c1417a1c01168408d32bd

_Copied from original issue: dotnet/core#2057_

**Comment by livarcocc** [comment] 2018-11-16 07:24
_From @karelz on November 14, 2018 18:6_

What is the Azure DevOps environment? Are you able to reproduce it in isolation / locally?
Is there any proxy set up there?

If you don't know the answer or if you are unable to isolate the repro to local environment, I would suggest to contact Azure DevOps support first.

**Comment by livarcocc** [comment] 2018-11-16 07:24
_From @jarz on November 14, 2018 18:53_

`dotnet restore` works fine locally. 

Considering the build works if I use 2.1.403 instead of 2.1.500, there must be a breaking change somewhere...

**Comment by livarcocc** [comment] 2018-11-16 07:24
_From @karelz on November 14, 2018 18:58_

Possibly (there could be some misconfiguration which just "happened to work by accident").
The key is narrowing down what triggers the problem. Without that information it is not actionable :(

**Comment by livarcocc** [comment] 2018-11-16 07:24
_From @jemmfi on November 16, 2018 6:48_

I have the same problem. "dotnet restore" fails, if my .NET Core Tool Installers installs Core SDK 2.1.500 (this is in Azure DevOps / cloud).

When I change the Code SDK version to  2.1.403, the same pipeline works with no other changes. This happens in two different build pipelines that I have tried. However, nuget.org -packages are restored normally.

The error with 2.1.500:
2018-11-16T05:21:02.3133383Z        (Restore target) -> 
2018-11-16T05:21:02.3133631Z          C:\hostedtoolcache\windows\dncs\2.1.500\x64\sdk\2.1.500\NuGet.targets(114,5): error : Unable to load the service index for source **{private feed}**/nuget/v3/index.json. 
2018-11-16T05:21:02.3133798Z        C:\hostedtoolcache\windows\dncs\2.1.500\x64\sdk\2.1.500\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). 

Stack trace:
2018-11-16T05:21:02.3017453Z          NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source {private feed}/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
2018-11-16T05:21:02.3018087Z             at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2018-11-16T05:21:02.3018510Z             at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
2018-11-16T05:21:02.3018970Z          --- End of stack trace from previous location where exception was thrown ---
2018-11-16T05:21:02.3019302Z             at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
2018-11-16T05:21:02.3019667Z             at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
2018-11-16T05:21:02.3020025Z             at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
2018-11-16T05:21:02.3020355Z             --- End of inner exception stack trace ---
2018-11-16T05:21:02.3020683Z             at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
2018-11-16T05:21:02.3021031Z             at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
2018-11-16T05:21:02.3023988Z             at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
2018-11-16T05:21:02.3024143Z             at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
2018-11-16T05:21:02.3024853Z             at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
2018-11-16T05:21:02.3025091Z             at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
2018-11-16T05:21:02.3025466Z             at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
2018-11-16T05:21:02.3025570Z             at NuGet.Commands.SourceRepositoryDependencyProvider.EnsureResource()
2018-11-16T05:21:02.3025680Z             at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryCoreAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
2018-11-16T05:21:02.3025808Z             at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext()
2018-11-16T05:21:02.3025915Z          --- End of stack trace from previous location where exception was thrown ---
2018-11-16T05:21:02.3026047Z             at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
2018-11-16T05:21:02.3026178Z             at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass7_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
2018-11-16T05:21:02.3026271Z          --- End of stack trace from previous location where exception was thrown ---
2018-11-16T05:21:02.3026380Z             at NuGet.DependencyResolver.ResolverUtility.FindLibraryFromSourcesAsync(LibraryRange libraryRange, IEnumerable`1 providers, Func`2 action)
2018-11-16T05:21:02.3026499Z             at NuGet.DependencyResolver.ResolverUtility.FindLibraryByVersionAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 providers, SourceCacheContext cacheContext, ILogger logger, CancellationToken token)
2018-11-16T05:21:02.3026733Z             at NuGet.DependencyResolver.ResolverUtility.FindLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, GraphEdge`1 outerEdge, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, IEnumerable`1 projectProviders, IDictionary`2 lockFileLibraries, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
2018-11-16T05:21:02.3026909Z             at NuGet.DependencyResolver.ResolverUtility.FindLibraryEntryAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, GraphEdge`1 outerEdge, RemoteWalkContext context, CancellationToken cancellationToken)
2018-11-16T05:21:02.3027038Z             at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge)
2018-11-16T05:21:02.3027188Z             at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge)
2018-11-16T05:21:02.3027331Z             at NuGet.Commands.ProjectRestoreCommand.WalkDependenciesAsync(LibraryRange projectRange, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, RemoteDependencyWalker walker, RemoteWalkContext context, CancellationToken token)
2018-11-16T05:21:02.3027493Z             at NuGet.Commands.ProjectRestoreCommand.TryRestoreAsync(LibraryRange projectRange, IEnumerable`1 frameworkRuntimePairs, NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteDependencyWalker remoteWalker, RemoteWalkContext context, Boolean forceRuntimeGraphCreation, CancellationToken token, TelemetryActivity telemetryActivity)
2018-11-16T05:21:02.3027655Z             at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity)
2018-11-16T05:21:02.3028163Z             at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
2018-11-16T05:21:02.3028348Z             at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
2018-11-16T05:21:02.3028465Z             at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
2018-11-16T05:21:02.3028558Z             at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
2018-11-16T05:21:02.3028671Z             at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
2018-11-16T05:21:02.3028781Z             at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
2018-11-16T05:21:02.3028882Z             at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log)

**Comment by mbp** [comment] 2018-11-16 12:46
Experiencing the same issue.

**Comment by Kvikal** [comment] 2018-11-16 15:18
Also experienced this issue, works well after downgrade back to 2.1.403-1.

**Comment by nkolev92** [comment] 2018-11-16 22:59
@mbp @Kvikal Is anyone experiencing this issue locally? 
//cc @zjrunner

**Comment by Luiz-Franco** [comment] 2018-11-19 15:29
Same issue here with `dotnet restore` and `dotnet push`

**Comment by nkolev92** [comment] 2018-11-19 17:32
@Luiz-Franco Are you seeing this locally?

**Comment by mbp** [comment] 2018-11-19 20:22
I was not seeing this locally with just `dotnet restore` command
However I could log into my build agent and reproduce it there on Windows Server 2016
I then took the temporary nuget.config file and copied to my machine and could also reproduce it here

By running the command:
```
"C:\Program Files\dotnet\dotnet.exe" restore SomeFile.sln --configfile tempNuGet_15426.config --verbosity Normal
```

The contents of the nuget.config looks like the following. XXX, YYY were some guids before I masked them:

```
<configuration>
 <packageSources>
  <add key="NuGetOrg" value="https://api.nuget.org/v3/index.json"/>
  <add key="XXX" value="https://MYORG.pkgs.visualstudio.com/_packaging/XXX/nuget/v3/index.json"/>
</packageSources>
<packageSourceCredentials>
 <_xYYY>
  <add key="Username" value="VssSessionToken"/><add key="ClearTextPassword" value="LONGSECRETSTRING"/>
 </_xYYY>
</packageSourceCredentials>
</configuration>
```

**Comment by nkolev92** [comment] 2018-11-19 20:28
@mbp 
Locally, what do you use to authenticate?
Do you use https://github.com/Microsoft/artifacts-credprovider?

**Comment by mbp** [comment] 2018-11-19 20:40
Not sure, how can I tell?

**Comment by Luiz-Franco** [comment] 2018-11-19 21:19
> @Luiz-Franco Are you seeing this locally?

No, only at Azure DevOps. Now I'm using the NuGet task to restore and push the packages and it's working.

**Comment by nkolev92** [comment] 2018-11-19 21:46
@mbp You would've need to take a manual action to get the credential provider. 

The best way to double check is to add /v:d and see if there's a line like the following:
Using {0} as a credential provider plugin.

**Comment by mbp** [comment] 2018-11-19 21:55
@nkolev92 I don't see the credential provider plugin. I seem to be using `%appdata%\Roaming\NuGet\NuGet.config` file with the following contents:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="vsts" value="https://MYORG.pkgs.visualstudio.com/_packaging/MYORG/nuget/v3/index.json" />
  </packageSources>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="1" />
    <add key="disabled" value="False" />
  </packageManagement>
  <packageSourceCredentials>
    <vsts>
      <add key="Username" value="example@example.org" />
      <add key="ClearTextPassword" value="XXX" />
    </vsts>
  </packageSourceCredentials>
</configuration>
```

**Comment by shubham90** [comment] 2018-11-20 01:30
@mbp can you run dotnet restore with failing nuget.config on your local machine with detailed verbosity? Please send me the logs with redacted password at shbhawsi at microsoft dot com. I tried to repro what you suggested but the restore is passing for me on 2.1.500.

**Comment by mbp** [comment] 2018-11-20 07:46
@shubham90 I have sent you the logs
I can also confirm if I put in a `global.json` specifying the old 2.1.403 SDK, dotnet restore works.

**Comment by shubham90** [comment] 2018-11-20 21:04
@mbp cool thanks! I will update the issue if I find anything.

**Comment by nkolev92** [comment] 2018-11-21 20:28
Are either of you using source names with special characters? 
Related
https://github.com/NuGet/Home/issues/7524

@mbp , @Luiz-Franco @Kvikal

**Comment by mbp** [comment] 2018-11-21 20:40
Our organisation has a dash in it (foo-bar)
The nuget.config is generated by the build, and there is no special characters. The source name is a guid. Nothing special besides that.

One thing I just noticed is that the element under packageSourceCredentials doesn't match the key in packageSources. (see from my sample above: https://github.com/NuGet/Home/issues/7516#issuecomment-440029293)

**Comment by nkolev92** [comment] 2018-11-21 20:47
@mbp 
Sorry about that, I overlooked the full config, but it smells like the  encoding config issue. 

The source name not matching the creds name is definitely what's causing the 401s.

**Comment by mbp** [comment] 2018-11-23 11:04
I opened an issue against the Azure Pipelines task that generates the file.

**Comment by mbp** [comment] 2018-11-23 11:08
It's really not transparent that the .NET Core 2.1.500 SDK also comes with an upgraded NuGet version (4.9.0.6). It is not mentioned in the changelog: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.6/2.1.6.md#notable-changes-in-216 and there is no mention of a NuGet 4.9 release anywhere (4.8 is mentioned here as latest: https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.8-rtm)

**Comment by nkolev92** [comment] 2018-11-25 22:31
@mbp That's a nuget bug. 
The azure tasks simply use updated nuget.exe/dotnet.exe. 

https://github.com/NuGet/Home/issues/7517
https://github.com/NuGet/Home/issues/7524 

The release notes are still being worked on 
https://github.com/NuGet/docs.microsoft.com-nuget/pull/1177/files

Every major/minor update of dotnet.exe comes with an updated nuget version. 
NuGet is a dependency in the SDK build process. 

But I agree, we should do a better job of specifying which version of the SDK matches which version of the nuget.exe/VS bits.
//cc @rrelyea 

One thing that's always true, 4.x nuget.exe <=> 15.x Visual Studio. 
Similarly next year, 5.x nuget.exe <=> 16.x Visual Studio.

**Comment by PatoBeltran** [comment] 2018-11-26 18:56
Closing as the PR has been merged

**Closed as completed by PatoBeltran** 2018-11-26 18:56 UTC
Labels: Resolution:Duplicate, Area:Settings, Functionality:Restore, Area:Authentication, RegressionFromPreviousRTM, Product:dotnet.exe
