### ISSUE TITLE
add more data point for error/warning

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#6786] opened 2018-04-06 18:58 UTC

**Comment by mishra14** [comment] 2018-04-11 22:35
closing as dupe of https://github.com/NuGet/Home/issues/6814

**Comment by mishra14** [comment] 2018-04-18 00:37
Reopening this to track a larger effort to add data points around nuget crashes in VS

**Comment by nkolev92** [comment] 2022-08-18 22:00
Unsure what this is about. Closing.

**Closed as completed by nkolev92** 2022-08-18 22:00 UTC
Labels: Priority:2, Area:ErrorHandling, Type:DataAnalysis
