### ISSUE TITLE
VS2017 hangs while installing nupkg

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2333] opened 2016-03-16 09:28 UTC
_From @Kanimozhi12 on March 16, 2016 8:43_

When i try to install a particular package VS 15 hangs, and it took more than half an hour to complete the installation. But the same package is installed in VS13 within 2 mins and there is no problem with it. I have tried almost all version of NuGet package manager of VS15. 

_Copied from original issue: NuGet/NuGetGallery#2947_

**Comment by sixlettervariables** [comment] 2016-03-16 13:46
I'm seeing this same issue as well, seems to be related to a reboot yesterday for the MS16-MAR patches. I've repaired AND uninstalled/reinstalled VS2k15.

For me all NuGet commands hang (incl. find-package).
- VS2k15 (14.0.24720.00 Update 1)
- NuGet Package Manager (3.3.0)

Same occurs with both a local repository (ProGet) and a remote repository (nuget.org). Same occurs when using the UI or Package Manager Console.

Update: Delay is ~3-5 minutes for `Find-Package` and ~10 minutes for `Install-Package` from local ProGet repository. Identical delays for nuget.org (i.e. does not seem to be network related).

**Comment by yishaigalatzer** [comment] 2016-03-22 23:23
We did have an outage, and NuGet 3 does try to talk to all sources when installing a package (because it is required to get the same repeatable package graph).

Can you confirm if the issue is still happening today, and if it still is, can you please give us an example package/project to repro with?

**Comment by Kanimozhi12** [comment] 2016-04-04 04:12
Please try to install this package in VS15 "KendoUICore"

**Comment by Kanimozhi12** [comment] 2016-04-12 07:19
Hi,

In my NuGet package have nearly 380 files for localization. 
While installing this NuGet package in my Visual Studio 2015 hangs. 
There is no issue with Visual Studio 2013 and 2012 with this same NuGet. 
There is any limitation in file counts that is used in NuGet for VS2015 and other VS too?

**Comment by yishaigalatzer** [comment] 2016-04-12 18:13
@Kanimozhi12 I did and I checked in a major improvement in 3.4.2, can you please try to update to it, and let me know if this is still an issue for you. (We know uninstall is still not fixed completely, but install should be a lot faster)

**Comment by Kanimozhi12** [comment] 2016-04-13 03:45
I have checked with the latest version 3.4.2 but still it takes more that 30 mins to install my package which has nearly 380 files.

**Comment by yishaigalatzer** [comment] 2016-04-13 03:47
A few more questions:
1. Can you share the package?
2. Is your project tied to tfs or git?
3. Did you install it or update it?

**Comment by yishaigalatzer** [comment] 2016-04-13 03:47
Oh and can you share logs?

**Comment by saschanaz** [comment] 2017-04-19 08:52
I have the same issue even on VS2017 (it was also on VS2015). Installing Microsoft.TypeScript.MSBuild from NuGet causes hang on VS2017.

1. It reproes on newly created JavaScript Blank App (Windows) project with a TypeScript file. 
2. No
3. Both update and new installation causes hang.

**Comment by saschanaz** [comment] 2017-04-19 08:52
I'm willing to share logs but where can I find it?

**Comment by emgarten** [comment] 2018-02-02 00:42
This should be improved in the latest VS 2017. If you are still seeing this issue then open a new issue containing repro steps for your specific scenario.

**Closed as completed by emgarten** 2018-02-02 00:42 UTC
Labels: Tenet:Performance
