### ISSUE TITLE
[Bug]: Unexpected NU1008 errors

### ISSUE THREAD

**Issue by tlmii** [NuGet/Home#11748] opened 2022-04-14 17:16 UTC
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

VS Internal Previews

### Worked before?

17.2 Preview 3

### Impact

It's more difficult to complete my work

### Workaround
Restore from the command-line before building in Visual Studio

### Repro Steps & Context

1. Install internal preview of VS
2. Clone our repo (not public, so can't link - I can provide directly if needed - but it is a solution with 5 SDK-style .NET Framework projects)
3. Open the project in VS
4. Build

Expected: Builds fine

Actual:

One project shows the error

> NU1008: Projects that use central package version management should not define the version on the PackageReference items, but on the PackageVersion items: `<long list of all packages the project references>`

We do use CPVM, but we have NO PackageReferences that specify the version - they're only specified on the PackageVersion items.

Looking at the package.assets file for the project in question is a little interesting. The project is correctly listed as `"centralPackageVersionsManagementEnabled": true`, but in the project/frameworks/net472/dependencies section, all of the dependencies look like this:

```
"IsExternalInit": {
  "suppressParent": "All",
  "target": "Package",
  "version": "(, )"
},
```

note the empty version. 

Opening the exact same source from the same location on disk on the same machine with 17.2 Preview 3 and building works fine.
Building with msbuild /r (using the version of msbuild that ships with the internal preview of VS) also works fine.

At one point in testing this, one of the other 4 projects in the solution showed the same error as well. While trying to debug and cleaning the project, wiping bin/obj, etc, the error on that project went away, leaving just this one doing it consistently.

**Comment by tlmii** [comment] 2022-04-15 06:23
An update here - this now happens for me in 17.2 Preview 3 as well. Same machine. So it doesn't seem to be limited to internal builds as I initially thought. My team is mostly seeing it on internal builds, but it seems there's not a causal relationship either way - internal and public builds each will sometimes work and sometimes not. Can't figure out the common thread yet...

**Comment by jeffkl** [comment] 2022-04-18 18:16
I have determined that this is caused by a failing design-time build in Visual Studio which results in an incomplete representation of the restore graph by NuGet.

Injecting any target that fails design-time builds will result in this error.  This repository had a target that would log an error if something wasn't correct, but that target should not have been run during a design-time build.  Disabling the target during design-time builds fixed the issue.  Additionally, some users on this team were seeing another target fail during design-time builds which result in the same error.

I'm following up with the Project System team to see how to fix this issue.  Running the `CollectCentralPackageVersions` target sooner in the design-time build might be a viable solution.

Here's a simple repro, add this to a project using NuGet's CPM:

```xml
  <Target Name="FailDesignTimeBuild"
          AfterTargets="CollectPackageReferences"
          Condition="'$(DesignTimeBuild)' == 'true'">
    <Error Text="Failing the design-time build..." />
  </Target>
```

The restore in Visual Studio will fail and these errors appear in the Error List window:
![image](https://user-images.githubusercontent.com/17556515/163854789-b92a1cf7-4943-408d-9ff2-14cf92ffe362.png)

**Comment by nkolev92** [comment] 2022-04-21 18:29
@jeffkl Is this is an external issue, or do we think there's something more that needs to be fixed on NuGet side?

Please add the `Resolution:External` label if necessary.

**Comment by jeffkl** [comment] 2022-07-15 18:29
At this point I'd say its external, there's not much NuGet can do at the moment.  I've opened an issue for Project System to look into: https://github.com/dotnet/project-system/issues/8318

**Comment by dks07** [comment] 2022-08-27 19:05
I am getting the same error after updating to vs 2022 version 17.3.2 from yesterday.
I have to remove all package references to successfully build the project

**Comment by miloszes** [comment] 2022-09-01 10:02
The same problem occurs on v 17.3.3

**Comment by amosialek** [comment] 2022-12-28 09:48
@jeffkl @nkolev92 
I have reproduced the issue without any Target in repository.
The funny thing is that removing
`<PackageVersion Include="System.Resources.Extensions" Verison="6.0.0" />`
from `Directory.Packages.props` fixes the issue even though it is not used.
Removing this `PackageVersion` helps and restoring it back to `Directory.Packages.props` doesn't break the build unless we remove `bin/`, `obj/` and `.vs/` folders.
This repo is minimal, but this workaround helped me also in solution with 100+ package references

Should I add the issue in https://github.com/dotnet/runtime/ where the code of `System.Resources.Extensions` is located or is it rather a NuGet issue?

Link to repo: https://github.com/amosialek/NugetIssue11748Reproduction
VS used to reproduce: 17.4.3 (latest "stable" at the moment).
In VS 17.3.0 (installed side by side) works fine

**UPDATE:** Removal of `System.Resources.Extensions` references completely fixed all the issues in all solutions in our codebase. Looks like if any referenced nuget had references to `System.Resources.Extensions`, NU1008 was shown with errors about other packages like `Microsoft.CSharp`

**Comment by jeffkl** [comment] 2023-01-04 17:52
@amosialek you have a typo in your `<PackageVersion />` item where the `Version` metadata is spelled `Verison`:

```diff
- <PackageVersion Include="System.Resources.Extensions" Verison="6.0.0" />
+ <PackageVersion Include="System.Resources.Extensions" Version="6.0.0" />
```

Fixing that should resolve your issue.

**Comment by jeffkl** [comment] 2023-03-14 21:12
Closing as external, please see https://github.com/dotnet/project-system/issues/8318

**Closed as not planned by jeffkl** 2023-03-14 21:12 UTC
Labels: Priority:2, Type:Bug, Functionality:Restore, Partner:Project-System, Area:RestoreCPM
