### ISSUE TITLE
Package throws System.ArgumentNullException: Path cannot be null.

### ISSUE THREAD

**Issue by aidanmorgan** [NuGet/Home#3238] opened 2016-07-28 07:28 UTC
Running a nuget pack for a Web API .csproj file on 3.5.0.1520 generates the exception below (first encountered on VSTS build agent, then reproduced locally).

Same .csproj with nuget 3.4.4.1321 does not throw this exception.

I need a workaround as the VSTS hosted agent is interfering with my build pipeline.
# 

Exception:

`System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.Packaging.PhysicalPackageFile.GetStream()
   at NuGet.CommandLine.ProjectFactory.ReverseTransformFormFile.GetElement(IPackageFile file)
   at NuGet.CommandLine.ProjectFactory.ReverseTransformFormFile.ReverseTransform(IPackageFile file, IEnumerable`1 transforms)
   at NuGet.CommandLine.ProjectFactory.ReverseTransformFormFile.<>c__DisplayClass2_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NuGet.CommandLine.ProjectFactory.ReverseTransformFormFile.GetStream()
   at NuGet.Packaging.PackageBuilder.WriteFiles(ZipArchive package)
   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
   at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)`

**Comment by rohit21agrawal** [comment] 2016-07-28 16:56
Duplicate of #3160 
This has been fixed in the latest builds from the dev branch. You can verify by downloading the nightly build from nuget.org/downloads.

**Comment by aidanmorgan** [comment] 2016-07-28 23:06
This was reproduced with the latest nightly available for download.

**Comment by rohit21agrawal** [comment] 2016-07-28 23:07
@aidanmorgan please provide a repro project, and we'll investigate.
I tried a simple web api project - it repros with 3.5.0-beta2, but it doesn't repro with the latest nightly build,

**Comment by rohit21agrawal** [comment] 2016-08-01 18:18
@aidanmorgan any update on this?

**Comment by rohit21agrawal** [comment] 2016-08-10 22:38
closing due to lack of response. please feel free to reactivate if this issue still repros.

**Closed as completed by rohit21agrawal** 2016-08-10 22:38 UTC
Labels: Type:Bug, Product:NuGet.exe, Resolution:NotRepro, Functionality:Pack
