### ISSUE TITLE
How can i set empty dependencies for package generating by Visual Studio for NetStandard project?

### ISSUE THREAD

**Issue by Sellec** [NuGet/Home#6951] opened 2018-05-20 00:25 UTC
Im using VS 2017.
My project uses some depencency packages but my dll generates using Costura.Fody (attaching referenced assemblies as resources into generated dll file) and need to have only one output dll.
If im enabling nuget package generation by Visual Studio, all works fine, but generated package have a list of dependencies.
Is there any way to set empty dependencies list without using NuspecFile? Maybe through NuspecProperties (i know that is not used without NuspecFile) or maybe there is a way to set "--no-dependencies" for "dotnet pack"?

**Comment by nkolev92** [comment] 2018-05-23 19:08
I believe this is a duplicate of https://github.com/NuGet/Home/issues/6354. 

This was fixed in https://github.com/NuGet/NuGet.Client/pull/2237, and will ship in 4.8.

**Closed as completed by nkolev92** 2018-05-23 19:08 UTC
Labels: Resolution:Duplicate, Type:Feature, Functionality:Pack, Style:PackageReference
