### ISSUE TITLE
Restore fails for 4.4.* and 404 on myget source

### ISSUE THREAD

**Issue by OzBob** [NuGet/Home#9019] opened 2020-01-07 02:10 UTC
Restoring a package with an version with a *, and referencing a VSIX myget source feed and building the project in Visual Studio results in 
'Error occurred while restoring NuGet packages: Failed to retrieve information'

My sources are:
my local folder nuget packages source
nuget.org
dotnet-core myget
and
Windows Template Studio VSIX myget feed 

A restore would fail for packages that use wildcards in their version, e.g. 4.4.*, but 4.4.0 would succeed.

If I remove the Windows Template Studio myget feed it would work as expected.

@dasetser (from the microsoft WCF team) and I have replicated this.

NuGet product used: VS UI and dotnet.exe.

NuGet version (x.x.x.xxx):5.5.0.6293

dotnet.exe --version:3.1.100

VS version: 16.5.0 Preview 1.0

OS version: win10 v1903:

## Detailed repro steps:

1. In Visual Studio or commandline: create a new Console App: dotnet new console

2. Add a Service Reference to a WSDL/.svc endpoint. On VS right click Dependencies and choose 'Connected Service' then 'Microsoft WCF Web Service Reference Provider'. On command prompt run dotnet-svcutil http://gcomputer.net/webservices/dilbert.asmx?WSDL

3. In VS add 'https://www.myget.org/F/windows-template-studio-nightly/vsix' as the last nuget source.

4. Build the project in VS or dotnet restore

Output when using dotnet restore from command line:
Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/windows-template-studio-nightly/vsix/FindPackagesById()?id='System.ServiceModel.Duplex'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 404 (Not Found).
C:\Program Files\dotnet\sdk\3.1.100\NuGet.targets(123,5): error : Failed to retrieve information about 'System.ServiceModel.Security' from remote source 'https://www.myget.org/F/windows-template-studio-nightly/vsix/FindPackagesById()?id='System.ServiceModel.Security'&semVerLevel=2.0.0'. [...dilbert2\dilbert2.csproj]
C:\Program Files\dotnet\sdk\3.1.100\NuGet.targets(123,5): error :   Response status code does not indicate success: 404 (Not Found). [...dilbert2\dilbert2.csproj]

5. Remove myget source

6. dotnet restore

7. OK

**Comment by aortiz-msft** [comment] 2020-06-08 20:27
Based on the information provided, restore succeeds when specifying 4.4.0 for the package hosted in MyGet, but fails when using 4.4.x. Also, restore succeeds when removing the MyGet source altogether. This might point to a problem with the MyGet source.

**Comment by zivkan** [comment] 2020-06-09 14:11
`https://www.myget.org/F/windows-template-studio-nightly/vsix` isn't a NuGet feed. As far as I'm concerned, NuGet is working by design.

VSIX feeds should be added to the [extension manager](https://docs.microsoft.com/en-us/visualstudio/extensibility/private-galleries?view=vs-2019#add-a-private-gallery-to-extensions-and-updates-in-visual-studio) settings, not NuGet.

**Comment by nkolev92** [comment] 2020-11-06 07:18
Closing as not a bug.

**Closed as completed by nkolev92** 2020-11-06 07:18 UTC
Labels: Priority:3, Type:Bug, Functionality:Restore
