### ISSUE TITLE
error : Unable to resolve [some.proj] for '.NETFramework,Version=v4.5'

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4579] opened 2017-02-11 21:42 UTC
In a solution that I'm converting (at least partially) to .NET SDK, I still get an error on package restore when I restore the whole solution. It's fine when I restore the test project.
Because the error only references the .sln file as the source, I can't tell which project has the reference that is failing. It would be nice to get a better error message (and get rid of the error message altogether as well).

```
git clone https://github.com/AArnott/Nerdbank.GitVersioning.git
cd Nerdbank.GitVersioning\src
git checkout 058324820
msbuild /t:restore
```

> C:\Program Files (x86)\Microsoft Visual Studio\2017\d15rel\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): error : Unable to resolve 'C:\git\Nerdbank.GitVersioning\src\Nerdbank.GitVersioning.Tasks\Nerdbank.GitVersioning.Tasks.csproj' for '.NETFramework,Version=v4.5'. [C:\git\Nerdbank.GitVersioning\src\Nerdbank.GitVersioning.sln]

[detailed msbuild log](https://github.com/NuGet/Home/files/768929/msbuild.zip)

Related to #4465?

**Comment by AmadeusW** [comment] 2017-09-06 19:13
I'm running into the same issue
`Unable to resolve '....csproj' for '.NETFramework,Version=v4.6'.`
and I would like to know what's the root cause. Please at least make the error message more descriptive

```
2017-09-06T18:35:54.8787743Z Unable to resolve 'E:\A\_work\144\s\src\VisualStudio\Impl\EditorImpl.csproj' for '.NETFramework,Version=v4.6'.
2017-09-06T18:35:54.9457772Z Committing restore...
2017-09-06T18:35:54.9457772Z Generating MSBuild file E:\A\_work\144\s\out\obj\EditorUnitTests\EditorUnitTests.csproj.nuget.g.props.
2017-09-06T18:35:54.9527778Z Generating MSBuild file E:\A\_work\144\s\out\obj\EditorUnitTests\EditorUnitTests.csproj.nuget.g.targets.
2017-09-06T18:35:54.9588011Z Writing lock file to disk. Path: E:\A\_work\144\s\out\obj\EditorUnitTests\project.assets.json
2017-09-06T18:35:54.9698022Z Restore failed in 1.15 sec for E:\A\_work\144\s\src\VisualStudio\Test\Unit\EditorUnitTests.csproj.
...
2017-09-06T18:35:54.9907782Z     29 package(s) to E:\A\_work\144\s\src\VisualStudio\Test\Unit\EditorUnitTests.csproj
2017-09-06T18:35:55.0967801Z ##[error]Error: E:\A\_work\_tool\NuGet\4.0.0\x64\nuget.exe failed with return code: 1
2017-09-06T18:35:55.0967801Z ##[error]Packages failed to restore
2017-09-06T18:35:55.1037790Z ##[section]Finishing: NuGet restore
```
[detailed msbuild log](https://github.com/NuGet/Home/files/1282377/logs_972739.zip)

**Comment by emgarten** [comment] 2017-11-09 20:40
This should be fixed in the latest build of NuGet.

**Closed as completed by emgarten** 2017-11-09 20:40 UTC
Labels: Triage:Investigate, Functionality:Restore
