### ISSUE TITLE
NuGet command-line download and packages

### ISSUE THREAD

**Issue by matkoch** [NuGet/Home#7118] opened 2018-07-16 02:00 UTC
I'm wondering why all those sources are not in sync:

- https://www.nuget.org/downloads
- https://www.nuget.org/packages/NuGet.CommandLine
- https://api-v2v3search-0.nuget.org/query?q=packageid:NuGet.CommandLine

The first seems to be the most accurate. Second has a strange semver 2.0. And third is only at 4.6.2.

**Comment by mishra14** [comment] 2018-07-19 18:47
@matkoch Thanks for pointing out the differences.

The package page on [nuget .org](https://www.nuget.org/packages/NuGet.CommandLine) and the [search](https://api-v2v3search-0.nuget.org/query?q=packageid:NuGet.CommandLine) should give you the same list of versions. But since NuGet.commandline v4.7.0 used semver2, you have to use a different search url - https://api-v2v3search-0.nuget.org/query?q=packageid:NuGet.CommandLine&semverlevel=2.0

As far as the downloads page is concerned. That has v4.8.0 but other places do not  because we have not yet published the package for v4.8.0. I will keep the issue open to track that request.

**Comment by mishra14** [comment] 2018-07-19 19:27
@matkoch I am closing this as a dupe of https://github.com/NuGet/Home/issues/4851

If you read the process described there, you will find that we do not publish nuget.commandline package till we have an RTM version.

**Closed as completed by mishra14** 2018-07-19 19:27 UTC
Labels: Product:NuGet.exe, Resolution:NotABug
