### ISSUE TITLE
Exception "The path is not of a legal form" on restoring project.

### ISSUE THREAD

**Issue by adetkov** [NuGet/Home#10615] opened 2021-03-03 12:32 UTC
## Details about Problem

NuGet product used: NuGet.exe
Product version: nuget.exe - recommended latest v5.8.1

## Repro steps and/or sample project

I try to restore a project from repo https://github.com/dnnsoftware/Dnn.Platform with command like:
> nuget.exe restore "C:\Dnn.Platform\Dnn.Platform\DNN Platform\Library\DotNetNuke.Library.csproj" -PackagesDirectory "C:\Dnn.Platform\Dnn.Platform\packages"

Got error: 
> 4p5ljhup.kxz.nugetrestore.targets(560,5): error : The path is not of a legal form.

It happens because something in nuget pipeline passes path "../../.nuget" as argument in method https://github.com/NuGet/NuGet.Client/blob/7463c26de6e6065a2b49d0ace20af973bca05968/src/NuGet.Core/NuGet.Configuration/Settings/Settings.cs#L832
It causes enumerating following directories ["../../.nuget", "../..", "../", ""]. In .Net Framework when you call Path.GetDirectoryName with empty string as argument it causes exception with text "The path is not of a legal form", so I offer to replace while cycle's condition from "root != null" to "!string.IsNullOrEmpty(root)"

**Comment by rrelyea** [comment] 2021-03-05 20:13
1. repros for me w/ nuget.exe 5.9 (with the given command) or with msbuild /t:restore -p:RestorePackagesConfig=true "DNN Platform\Library\DotNetNuke.Library.csproj"     (on msbuild 16.9)
2. doesn't repro in VS solution restore (16.9) or nuget restore of the solution file.

**Comment by rrelyea** [comment] 2021-03-05 20:14
looks like dupe of https://github.com/NuGet/Home/issues/9766

**Closed as completed by rrelyea** 2021-03-05 20:14 UTC
Labels: Resolution:Duplicate, Type:Bug, Product:NuGet.exe, Functionality:Restore

**Comment by dipique** [comment] 2025-03-07 23:10
This is marked as "completed" but it's unclear what the resolution is. I still get this error with nuget 6.13 on a .NET Framework 4.8 project using a packages.config file.
