### ISSUE TITLE
Unable to use wildcards in nuspec files section

### ISSUE THREAD

**Issue by dscpinheiro** [NuGet/Home#12777] opened 2023-07-26 17:58 UTC
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Version: 5.6.0.6591

### Worked before?

No

### Impact

It's more difficult to complete my work

### Repro Steps & Context

We recently updated our `.nuspec` files to use `Path.AltDirectorySeparatorChar` (i.e. `/`) in the `files` section (for the `src` and `exclude` attributes) and NuGet does not seem to handle wildcards properly.

With the following `nuspec` file, only `./nuget-content/logo.png` will be copied (and all files inside `folder1` will be ignored - without any warnings in the verbose logs):
```xml
<?xml version="1.0" encoding="utf-8"?>
<package> 
  <metadata> 
    <id>MyPackage.Id</id>
    <title>MyPackage - Title</title>
    <version>1.0.0.0</version> 
    <authors>Author</authors>
    <description>My package description</description>
    <language>en-US</language>
    <license type="expression">Apache-2.0</license>
    <icon>images/logo.png</icon>
  </metadata> 
  <files>
    <file src="./nuget-content/logo.png" target="images/" />
    <file src="./folder1/*.dll" target="lib/" exclude="**/Assembly3*" />
  </files>
</package>
```

Here's the folder structure:
```
│   test.nuspec
│
├───folder1
│       Assembly1.dll
│       Assembly1.pdb
│       Assembly1.xml
│       Assembly2.dll
│       Assembly2.pdb
│       Assembly2.xml
│       Assembly3.dll
│       Assembly3.pdb
│       Assembly3.xml
│
└───nuget-content
        logo.png
```

NuGet handles the `/` separator just fine, it's the wildcard entries that are being ignored. 

### Verbose Logs

```shell
PS> NuGet.exe pack .\test.nuspec -verbosity detailed
NuGet Version: 5.6.0.6591
Attempting to build package from 'test.nuspec'.

Id: MyPackage.Id
Version: 1.0.0.0
Authors: Author
Description: My package description
Dependencies: None

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'images/logo.png'.
Added file 'MyPackage.Id.nuspec'.
Added file 'package/services/metadata/core-properties/745c43d63898482bb1da7b019fa935c7.psmdcp'.
```

---

For reference, here's the output (which includes the correct files) when using `\` instead:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package> 
  <metadata> 
    <id>MyPackage.Id</id>
    <title>MyPackage - Title</title>
    <version>1.0.0.0</version> 
    <authors>Author</authors>
    <description>My package description</description>
    <language>en-US</language>
    <license type="expression">Apache-2.0</license>
    <icon>images\logo.png</icon>
  </metadata> 
  <files>
    <file src=".\nuget-content\logo.png" target="images\" />
    <file src=".\folder1\*.dll" target="lib\" exclude="**\Assembly3*" />
  </files>
</package>
```

```
PS> NuGet.exe pack .\test.nuspec -verbosity detailed
NuGet Version: 5.6.0.6591
Attempting to build package from 'test.nuspec'.

Id: MyPackage.Id
Version: 1.0.0.0
Authors: Author
Description: My package description
Dependencies: None

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'images/logo.png'.
Added file 'lib/Assembly1.dll'.
Added file 'lib/Assembly2.dll'.
Added file 'MyPackage.Id.nuspec'.
Added file 'package/services/metadata/core-properties/d748c67cb50449388cf4791f61f00797.psmdcp'.
```

**Comment by jeffkl** [comment] 2023-07-31 19:59
Related to https://github.com/NuGet/Home/issues/3584

**Comment by jebriede** [comment] 2023-07-31 20:24
Team triage:  Looks like a duplicate of  https://github.com/NuGet/Home/issues/3584

Please add a 👍 reaction to upvote that issue.

**Closed as completed by jebriede** 2023-07-31 20:24 UTC
Labels: Resolution:Duplicate, Type:Bug
