### ISSUE TITLE
VS2015 Ent and Nuget hung

### ISSUE THREAD

**Issue by Montigomo** [NuGet/Home#1075] opened 2015-07-30 06:34 UTC
Hello!
Yesterday I've install Windows 10 Pro & VS2015 Ent. Now I try to open Package Manage Console
Tools-> NuGet Package Manager -> Package Manager Console
see "Initializing Powershell host ... " and VS hung (only kill with Task Manager help).
![vs1](https://cloud.githubusercontent.com/assets/1889961/8977043/dc5ced0a-369d-11e5-8bc5-2e5a93ee63d9.png)
Only thing I've done change Execution Policy to RemoteSigned.

**Comment by Montigomo** [comment] 2015-07-30 14:18
I have in Documents file profile.ps1 with content
function Prompt
{
    #(Get-Host).UI.RawUI.WindowTitle="PS $(Get-Location)"
    #"PS > "
    (Get-Host).UI.RawUI.WindowTitle="PS $(Get-Location)"
    Write-Host ("PS " + $(get-location) +">") -nonewline -foregroundcolor Magenta
    return " "
}
and this the issue...

**Comment by yishaigalatzer** [comment] 2015-07-30 20:51
Thanks you for clarifying and digging into it. This looks like a duplicate of #917

**Closed by yishaigalatzer** 2015-07-30 20:51 UTC
