### ISSUE TITLE
The ',' character, hexadecimal value 0x2C, cannot be included in a name.

### ISSUE THREAD

**Issue by SchreinerK** [NuGet/Home#8618] opened 2019-09-23 19:42 UTC
NuGet Version: 4.9.2.5706

The ',' character, hexadecimal value 0x2C, cannot be included in a name. Line 21, position 124.
But the line 21 points to &lt;description>

AssemblyInfo.cs
[assembly: AssemblyDescription("Extentend System.Configuration classes. property registration (w/o attributes), IList<T>/IDctionary<string,T> support.")]
sample.nuspec
<description>$description$</description>
[sample.nuspec.txt](https://github.com/NuGet/Home/files/3643815/sample.nuspec.txt)

**Comment by rrelyea** [comment] 2019-09-23 19:45
Dupe of https://github.com/NuGet/Home/issues/7948 - which is fixed in NuGet.exe 5.3.0 -- which should be live later today.

**Closed as completed by rrelyea** 2019-09-23 19:45 UTC
Labels: Resolution:Duplicate
