### ISSUE TITLE
VS Package Manager: incorrectly handles an invalid source in nuget.config while installing a package from other sources

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#5863] opened 2017-09-07 16:49 UTC
VS 2017.3

I have a bunch of nuget sources, both in global and local (inside .nuget\NuGet.Config in a project) configs. 
Inside .nuget\NuGet.Config  I have a local repo which targets not existing folder

	<packageSources>
		<add key="local" value="..\..\Release"/>
	</packageSources>

If in VS I search for a package then I'll get an error - it's expected:
![image](https://user-images.githubusercontent.com/1203230/30174425-b8c6452e-9403-11e7-8765-16e17997d704.png)

But then I switch "Package source" onto a good source where the package exists for sure - nuget.org, and try to install it. I'll get an error in Output that "Failed to retrieve information about 'PACKAGE' from remote source 'LOCAL SOURCE'." : 

![image](https://user-images.githubusercontent.com/1203230/30174471-de54c61c-9403-11e7-8faf-1016fbd7ad6d.png)

Yes, there's no package in the mentioned source, but I don't care for the moment because I'm installing the package from other source.

So I have to go and find where the mentioned folder came from, understand that it's inside my nuget.config and try to fix it.

**Comment by nkolev92** [comment] 2017-09-07 19:04
@evil-shrike What's your project restore style? 
PackageReference or packages.config?

**Comment by evil-shrike** [comment] 2017-09-07 19:11
PackageReference

**Comment by emgarten** [comment] 2017-09-07 22:32
Dupe of https://github.com/NuGet/Home/issues/5643

VS does not have an option to ignore bad sources like the command line does.

**Closed as completed by emgarten** 2017-09-07 22:32 UTC
Labels: Resolution:Duplicate

**Comment by evil-shrike** [comment] 2017-09-07 22:46
Actually I don't need an option to ignore a source. When I choose a source I expect that it is only the source to search and install packages from. Why are other sources looked in at all?

**Comment by emgarten** [comment] 2017-09-07 23:05
With PackageReference installing a package adds a reference to it, then it runs Restore which essentially installs all of the packages again, everything is resolved which is why if a source is missing this can cause restore to pick a different version of the package when looking for a *best* match.
