### ISSUE TITLE
The 'IntegrationPackage' package did not load correctly.

### ISSUE THREAD

**Issue by Jon12345** [NuGet/Home#1529] opened 2015-10-06 23:28 UTC
"The 'IntegrationPackage' package did not load correctly." error dialog appears when clicking on a file in a code review in VS2015.

Activitylog.xml contains the following errors:

<entry>
    <record>622</record>
    <time>2015/10/06 23:24:19.128</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [IntegrationPackage]</description>
    <guid>{D209E4D9-0F58-4BC3-A529-FDCF20967DC0}</guid>
    <hr>80131500</hr>
    <errorinfo>An exception was thrown while initializing part "NuGet.PackageManagement.VisualStudio.VSSettings".</errorinfo>
  </entry>
  <entry>
    <record>623</record>
    <time>2015/10/06 23:24:19.130</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [IntegrationPackage]</description>
    <guid>{D209E4D9-0F58-4BC3-A529-FDCF20967DC0}</guid>
    <hr>80131500</hr>
    <errorinfo>Object reference not set to an instance of an object.</errorinfo>
  </entry>

**Comment by yishaigalatzer** [comment] 2015-10-06 23:30
@Jon12345 please send me an email directly, and I'd like to send you a private build to try out. y i g a l a t z @ msft.com

I assume you are already on nuget 3.2

**Comment by yishaigalatzer** [comment] 2015-10-06 23:31
potential duplicate of https://github.com/NuGet/Home/issues/1408

**Comment by yishaigalatzer** [comment] 2015-10-06 23:32
A work around would be to open a saved solution first, and open package management console (or some other action that initializes NuGet)

**Comment by yishaigalatzer** [comment] 2015-12-10 19:23
We fixed quite a few of these isues in NuGet 3.3. Please open a new bug if you still see it in NuGet 3.3

**Closed as completed by yishaigalatzer** 2015-12-10 19:23 UTC
