### ISSUE TITLE
Visual Studio 2022 17.4.1, Package manager UI incorrectly selects package version for update, which is unsupported by project configuration 

### ISSUE THREAD

**Issue by ibe-SAG** [NuGet/Home#12272] opened 2022-11-24 16:49 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 2022 17.4.1

### Worked before?

unknown

### Impact

It's more difficult to complete my work

### Repro Steps & Context

you can use my test project:
https://github.com/ibe-SAG/VS-Issues/tree/main/NugetUpdateIssue

or reproduce manually

1. create c# console project
2. edit .csproj file an set 
    `<Platforms>AnyCPU</Platforms>`
    `<TargetFramework>net6.0-windows</TargetFramework>`
    `<RuntimeIdentifier>win-x64</RuntimeIdentifier>`
    `<LangVersion>10.0</LangVersion>`
    `<PlatformTarget>x64</PlatformTarget>`

4. Reference package Microsoft.AspNetCore.Authentication.OpenIdConnect in the version 6.0.11
5. Open NuGet package manager
6. Navigate to Updates 
Version 7.0.0 of the package is offered (but it is not compatible with the project).
If you select the package and click on update button, Visual Studio tries to install the package and fail with:
NU1202: Package Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 supports: net7.0 (.NETCoreApp,Version=v7.0)
NU1202: Package Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 supports: net7.0 (.NETCoreApp,Version=v7.0)
Package restore failed. Rolling back package changes for 'NugetUpdateIssue'.

If you have only one such dependency it is not a problem, but in our case we have over 100 projects in solution with over 100 dependencies. To upgrade all the dependencies one by one and in correct order is a pain

Expected behavior : not supported version should not be selected for update, but the latest compatible version  

### Verbose Logs

```shell
Restoring packages for C:\code\issues\NugetUpdateIssue\NugetUpdateIssue.csproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json 487ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.openidconnect/7.0.0/microsoft.aspnetcore.authentication.openidconnect.7.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.openidconnect/7.0.0/microsoft.aspnetcore.authentication.openidconnect.7.0.0.nupkg 115ms
Installed Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 from https://api.nuget.org/v3/index.json with content hash hAPVV6xD9KQaf0je+YhhPBvGv421DRthL7qBsKxmjL2ELB4cbogD2FcHg9z80hy6P1ABZ09leKknJ2xRkXFCMA==.
NU1202: Package Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 supports: net7.0 (.NETCoreApp,Version=v7.0)
NU1202: Package Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0) / win-x64. Package Microsoft.AspNetCore.Authentication.OpenIdConnect 7.0.0 supports: net7.0 (.NETCoreApp,Version=v7.0)
Package restore failed. Rolling back package changes for 'NugetUpdateIssue'.
```

**Comment by jeffkl** [comment] 2022-12-01 19:29
Duplicate of https://github.com/NuGet/Home/issues/5725

**Closed as not planned by jeffkl** 2022-12-01 19:29 UTC
Labels: Resolution:Duplicate, Type:Bug
