### ISSUE TITLE
Upgrade of NuGet Vsix fails "Process cannot access the file because it is being used by another process"

### ISSUE THREAD

**Issue by the-real-coder** [NuGet/Home#3181] opened 2016-07-20 23:27 UTC
I have been facing issues with my Nuget Package manager on Visual Studio 2015 Enterprise Edition with Update 3. 

Couple of days back I tried upgrading the nuget package manager from 3.4.3.855 to 3.4.4.1321 the update failed with error message - **The process cannot access the file because it is being used by another process**. Since then I have tried numerous workarounds, repaired Visual Studio and tried uninstalling and installing VS 2015 again but nothing seems to be working.

When I try to open package manager console from tools menu I get following error

**Operation failed

Unable to cast object of type 'NuGet.PackageManagement.VisualStudio.VSSettings' to type 'NuGet.Configuration.ISettings'.**

When I open any project I get following error

**An exception has been encountered. This may be caused by an extension.

You can get more information by examining the file 'C:\Users\xyz\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml'.**

I have attached the log files that I have please let me know how can I fix this issue.

[VSIXInstaller_0ad44398-c210-49bd-b410-7649ae5c25d0.txt](https://github.com/NuGet/Home/files/374885/VSIXInstaller_0ad44398-c210-49bd-b410-7649ae5c25d0.txt)

**Comment by rrelyea** [comment] 2016-07-21 00:24
Dupe of https://github.com/NuGet/Home/issues/1138

"We identified this as a bug or issue in the core visual studio extensibility. It is not a nuget specific issue, the team is working on getting repros and improve. It is generally tied to things like anti virus or encryption services."

**Closed as completed by rrelyea** 2016-07-21 00:24 UTC
Labels: Resolution:Duplicate
