### ISSUE TITLE
NuGet needs better support for developer testing of new packages.

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#3575] opened 2016-10-03 22:12 UTC
NuGet currently has a great separation of the production and consumption of packages which is great to help isolate dependencies and ensure that consumers don't get broken. Unfortunately, this process adds a lot of strain to developers working on the production side to test and validate packages. The current workflow my team has to endure is as follows:
1. Make a feature change.
2. Build and Unit Test change
3. Produce new nuget package with new higher version number or stomp old package in cache
4. Manually change test app/similar to use locally built package
5. Validate consumption side of package for feature change.

It would be awesome if 3-5 could be automatically included in the dev cycle without manual messing around with version numbers etc. and be directly baked into the normal unit test validation step. 

Capabilities like https://www.visualstudio.com/en-gb/docs/package/get-started/build/team-build additionally help with the automatic production of packages per build but fall short when attempting to consume and validate the build.

To solve this issue, I propose adding a new "Choose Highest Available Including Prerelease" dependency version and the following workflow of 3 nuget feeds for a team:
1. The officially published stable release feed. (Foo.1.0.0)
2. An internal feed for build system integration that produces new candidate packages (Foo.1.0.**1-ci-buildstring**)
3. A local feed for building at a developer's desk that produces a new candidate package (Foo.1.0.**1-my-buildstring**)

The candidate version will be controlled via version.txt or similar checked in with source code for the package (although it'd be super neat if a nuget.config or similar could auto manage this as well)

Using the nuget.config file, all three package sources will be automatically added for "Test Consumers". 

Using an environment variable or similar, a local build will produce a package into the pre-configured local feed location while a build system build should publish to the internal feed. The published releases will happen manually and require subsequent updating of the version.txt or similar. 

In order to make this system effective, the test consumers need to specify their dependencies as "Choose Highest Available Including Prerelease". 
Since Foo.1.0.0 < Foo.1.0.1-ci-buildstring < Foo.1.0.1-my-buildstring < Foo.1.0.1-my-later-buildstring, this would mean the most recently built and most local package would always get used for testing. The different locations a build occurs (at a dev's desk, on the build machine, or in preparation for final release) naturally controls the existence (or lack thereof) of the prerelease packages ensuring the desired ones get picked up for testing.

Unfortunately, project.json has no way to specify the desired "Choose Highest Available Including Prerelease" ("*" only includes stable packages) which makes sense from a pure consumption standpoint (its likely this will break a consumer in unexpected ways and consumers should only move forward when ready), this ability would greatly benefit the production workflow.

As a proposed version string, I think either "_-_" (any version including any pre-release tag) or "+" (special marker for AbsoluteHighest) would be sufficiently differentiated from normal package consumption but would allow this ability. Note that [VersionRangeFactory.cs](https://github.com/NuGet/NuGet.Client/blob/93c8e25406c056aeeb80c3b8d44781d434255020/src/NuGet.Core/NuGet.Versioning/VersionRangeFactory.cs#L24) seems to indicate this ability already existing just not being able to be specified with the current VersionRange syntax.

I am also open to suggestions on how to best organize any alternate workflows.

Thanks,
Brian

**Comment by yishaigalatzer** [comment] 2016-10-03 23:07
Is this in a nutshell a request to support `*-*` in project.json ?

**Comment by bbowman** [comment] 2016-10-03 23:11
@yishaigalatzer Yes or provide another mechanism to easily test locally built packages. I didn't want to be so specific since I know you are moving away from project.json and our needs are more around a less painful workflow but`*-*`would definitely work for us.

**Comment by yishaigalatzer** [comment] 2016-10-03 23:13
The version spec will work on project.json or the new `<packagereference` in msbuild.

@emgarten @rrelyea I would love to squeeze this into 3.6 (and of course find the dup if we already have one)

**Comment by bbowman** [comment] 2017-02-23 19:46
@yishaigalatzer @emgarten @rrelyea I didn't see this hit 3.6 ... Did it make it into 4.0?

**Comment by jainaashish** [comment] 2017-10-17 20:50
Dupe of https://github.com/NuGet/Home/issues/912

**Closed as completed by jainaashish** 2017-10-17 20:50 UTC
Labels: Resolution:Duplicate, Functionality:Restore
