### ISSUE TITLE
Transitive dependent packages are not restored on Linux

### ISSUE THREAD

**Issue by 24mu13** [NuGet/Home#10655] opened 2021-03-11 17:06 UTC
## Details about Problem

NuGet product used: dotnet

Product version: 5.0.201

Worked before? If so, with which NuGet version: No, AFAIK

## Repro steps and/or sample project

Let's consider two netstandard2.0 libraries: A and B used as NuGet packages.
Create a project P netstandard2.0 that references A, and A references B.
All references are PackageReference.

Now I have two different behaviors on Windows 10 and Debian 10, when I do restore
`dotnet restore P`

Both cases succeed:
```
  Determining projects to restore...
  Restored /home/samuel/Projects/Test/P.csproj (in 326 ms).
```
And by the way, both cases succeed also to build.

BUT, on my local NuGet cache I do not have B.dll on Debian 10.
Instead the project.assets.json is the same, of course.

So, in Windows 10 I have the following folders in my NuGet cache:
```
C:\Users\Samuel\.nuget\packages\a\...
C:\Users\Samuel\.nuget\packages\b\...
```
BUT, in Debian 10 I have the following folders in my NuGet cache:
```
C:\home/samel/.nuget/packages/a/...
```

Please, any idea?
I have a post-compilation thing that process that output...

**Comment by zkat** [comment] 2021-03-18 17:12
@v-luzh Could you please try to repro this? It's pretty surprising to me that this wouldn't break our tests.

**Comment by v-luzh** [comment] 2021-03-25 11:45
@zkat It doesn't repro on Linux (Ubuntu Server 18.04) for me on dotnet 6.0.100-preview.3.21168.18. You can see both packages after running "dotnet restore" as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/112467938-a0fbb180-8da2-11eb-8d13-676308b34c75.png)

**Comment by zkat** [comment] 2021-03-25 17:12
@24mu13 Do you have a more specific project that reproes that you could pack up for us to test with? As you can see, our test team was unable to reproduce with the instructions you gave.

**Comment by 24mu13** [comment] 2021-04-06 13:00
Thank you for double-checking: we have some code ([ConsoleAssetsJson.zip](https://github.com/NuGet/Home/files/6264760/ConsoleAssetsJson.zip)) to package a library of us with its dependencies. 
To get these deps we parse the **project.assets.json** of the initial library of us.

When compiling on _Windows_ everything goes well and we get all deps on .nuget/packages, but when compiling on _Linux_ some expected deps (according with project.assets.json) are missing!

In particular, we don't find some specific System.<something> library: e.g. System.Collections.Immutable.dll or System.Numerics.Vectors.dll ...

Probably my conclusion about transitive deps not restored is not correct, but still I don't get the problem.

**Comment by zkat** [comment] 2021-04-12 20:17
We suspect your configuration on Linux might be different than the one on Windows. Can you confirm which .NET runtime you have installed on each of these? (you can get this with `dotnet --info`)

**Comment by zkat** [comment] 2021-04-29 17:19
It's been more than 14 days without a customer response, so I'm closing this, since we can't repro it ourselves.

@24mu13 please feel free to file a new issue with repro details if you're able to.

**Closed as completed by zkat** 2021-04-29 17:19 UTC
Labels: Type:Bug, Resolution:Question, Platform:Xplat, Functionality:Restore, Style:PackageReference, Product:dotnet.exe, WaitingForCustomer
