### ISSUE TITLE
When running "nuget install <package> -version <v> -OutputDirectory <directory> -ExcludeVersion", version of nuget package isn't verified

### ISSUE THREAD

**Issue by brunomlopes** [NuGet/Home#4827] opened 2017-03-16 19:14 UTC
We use nuget.exe install to install some nuget packages on a local folder (usually servers which are packaged as nugets). We use -OutputDirectory and -ExcludeVersion to keep the same path whenever we bump minor versions.

On nuget 3.5, this is broken because of an optimization. Nuget assumes that if the .nupkg exists on the correct path that the package version is up to date. This is not valid when we use -ExcludeVersion.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 3.5.0.1996

OS version (i.e. win10 v1607 (14393.321)): win10 v1607 (14393.693)

Worked before? If so, with which NuGet version: Yes, on 3.4.4.1321

## Detailed repro steps so we can see the same problem

1.  Run `nuget.exe install RavenDb.Server -version 3.5.0 -OutputDirectory local\raven -ExcludeVersion`

It installs the package on folder `local\raven\RavenDB.Server`

2. Run `nuget.exe install RavenDb.Server -version 3.5.3 -OutputDirectory local\raven -ExcludeVersion`

It says `Package "RavenDb.Server.3.5.2" is already installed.` when the version package is actually outdated. 

On version 3.4.4.1321 nuget.exe correctly installs the new version on the same folder.

**Comment by jainaashish** [comment] 2017-03-31 19:18
@brunomlopes Can you also try the same scenario with NuGet.exe 4.0 (https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe) and let us know how it goes.

**Comment by brunomlopes** [comment] 2017-04-06 15:02
@jainaashish apologies for taking so long to reply. I just tested and it also fails to install the new version.
Tested with NuGet Version: 4.0.0.2283

**Comment by gezzahead** [comment] 2017-04-07 09:44
Are you sure it worked on 3.4.4.1321? I just tried and it failed. I think it only works in 2.8.6. I believe this is the same issue as #2405

**Comment by emgarten** [comment] 2017-04-07 18:09
This may be the same as https://github.com/NuGet/Home/issues/2405

**Comment by boarmanc** [comment] 2017-08-09 23:43
Experiencing the same issue with Nuget 4.3.0.3

**Comment by emgarten** [comment] 2017-08-10 08:48
Dupe of https://github.com/NuGet/Home/issues/2405

**Closed as completed by emgarten** 2017-08-10 08:48 UTC
Labels: Resolution:Duplicate
