### ISSUE TITLE
nuget.config belonging to K solution is edited unexpectedly

### ISSUE THREAD

**Issue by abpiskunov** [NuGet/Home#1201] opened 2015-08-17 16:39 UTC
I debugged and found this thread (see picture below) updating our nuget.config that lives in solution when very first build is triggered in a fresh VS instance. Which causing file changed event coming to us from file watcher. 

What is changes:

Before: 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

After:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

Questions:

a.       Is it expected? What if we want to keep our PackageSources version, how to opt out from this change?
b.      As you can see from below, we receive 4 Changed events from file watcher, all caused by same initialization workflow, but different code code stacks .. so just checking why actual file is modified 4 times? If it is expected we will add a logic to expect that …

![nugetconfigissue](https://cloud.githubusercontent.com/assets/1592091/9310325/fca7be76-44dc-11e5-9bd5-24e25d2711b2.png)

**Comment by abpiskunov** [comment] 2015-08-17 16:40
Before xml:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

**Comment by abpiskunov** [comment] 2015-08-17 16:41
Before xml:

``` javascript
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by abpiskunov** [comment] 2015-08-17 16:41
After xml:

``` javascript
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by csharpfritz** [comment] 2015-09-03 18:30
My %appdata%\nuget\NuGet.config file was modified in the latest successful build.  Verifying...

**Comment by csharpfritz** [comment] 2015-09-03 18:59
Unable to reproduce...  closing

**Closed as completed by csharpfritz** 2015-09-03 18:59 UTC
Labels: Product:VS.Client, Priority:2, Type:DCR
