### ISSUE TITLE
HttpCacheFolder is not configurable like other settings i.e. GlobalPackagesFolder

### ISSUE THREAD

**Issue by dannyvv** [NuGet/Home#2682] opened 2016-04-28 15:59 UTC
### Issue

Method `GetHttpCacheFolder` in [settingsUtility.cs](https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L156)

``` C#
 public static string GetHttpCacheFolder(ISettings settings)
        {
            if (settings == null)
            {
                throw new ArgumentNullException(nameof(settings));
            }

            return NuGetEnvironment.GetFolderPath(NuGetFolderPath.HttpCacheDirectory);
        }
```

does not have a way to be overridden via an environment variable or a section in the config like [GetGlobalPackagesFolder](https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L127) does.

It always hard-codes to the users profile.
### Proposal

just like: https://github.com/NuGet/Home/issues/1062 follow that implementation and add `"cacheFolder"` to the config  and support `"NUGET_CACHEFOLDER"` environment variable
### Action
1. Let me know if this is okay and I can code it up and submit a pull request.
2. I couldn't find documentation on the NUGET_PACKAGES, or globalPackagesFolder. If someone finds it I can update that too with the extra setting.
3. Let me know if alternate names are preferred

**Comment by rrelyea** [comment] 2016-04-28 20:54
Thanks. Duplicate of #1394 
We would love a PR.

**Closed as completed by rrelyea** 2016-04-28 20:54 UTC
