### ISSUE TITLE
Enable cancelling installation of NuGet pacakges in the Visual Studio UI

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#487] opened 2015-04-24 20:48 UTC
We should enable cancelling an install, and roll back properly

**Comment by yishaigalatzer** [comment] 2015-11-25 19:26
Moving out, as this didn't get much user attention. We should get to it and clean it up at some point. This is mosty for packages.config scenario

**Comment by mishra14** [comment] 2017-10-18 02:00
dupe of https://github.com/NuGet/Home/issues/5218

**Closed by mishra14** 2017-10-18 02:00 UTC
Labels: Type:Feature
