### ISSUE TITLE
"update-package PKGNAME -reinstall" reinstalls all packages, not just the selected package

### ISSUE THREAD

**Issue by seguemark** [NuGet/Home#1171] opened 2015-08-13 17:35 UTC
When running "update-package PKGNAME -reinstall" from Package Manager Console within Visual Studio, ALL packages in the project are uninstalled and reinstalled, rather than just the named package.

#### Steps to reproduce
1. Create a new project (e.g. a Class Library)
2. In package manager console, install a package with no dependencies, e.g. Antlr
    install-package Antlr
3. In package manager console, install another package with no dependencies, e.g. Respond
    install-package Respond
4. In package manager console, update/reinstall Antlr
    update-package Antlr -reinstall

Expected behavior: Antlr is uninstalled and reinstalled, Respond is not affected
Observed behavior: Antlr and Respond are both uninstalled and reinstalled

#### Package Manager Console Output
PM> update-package Antlr -reinstall
Attempting to gather dependencies information for multiple packages with respect to project 'NugetReinstallBug', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Removed package 'Respond 1.4.2' from 'packages.config'
Successfully uninstalled 'Respond 1.4.2' from NugetReinstallBug
Removed package 'Antlr 3.5.0.2' from 'packages.config'
Successfully uninstalled 'Antlr 3.5.0.2' from NugetReinstallBug
Package 'Antlr.3.5.0.2' already exists in folder 'C:\Users\shapirom\documents\visual studio 2015\Projects\NugetReinstallBug\packages'
Added package 'Antlr.3.5.0.2' to 'packages.config'
Successfully installed 'Antlr 3.5.0.2' to NugetReinstallBug
Package 'Respond.1.4.2' already exists in folder 'C:\Users\shapirom\documents\visual studio 2015\Projects\NugetReinstallBug\packages'
Added package 'Respond.1.4.2' to 'packages.config'
Successfully installed 'Respond 1.4.2' to NugetReinstallBug

### Software Versions
Using Visual Studio Enterprise 2015 (Version 14.0.23107.0 D14REL)
.NET Framework 4.6.00081
NuGet Package Manager 3.0.0

**Comment by yishaigalatzer** [comment] 2015-08-13 19:00
Thanks for the report - Can you grab the version number for NuGet Package manager from the Tools->extensions and updates menu?

It should look something like this:
![image](https://cloud.githubusercontent.com/assets/1238711/9258886/dc37fcd2-41b2-11e5-8d01-46b9f587a19f.png)

**Comment by yishaigalatzer** [comment] 2015-08-14 01:27
Duplicate of #737

**Closed** 2015-08-14 01:34 UTC
Labels: ClosedAs:Duplicate
