### ISSUE TITLE
Nuget allowed a CoreFx stable package to be published with non-stable dependencies

### ISSUE THREAD

**Issue by wtgodbe** [NuGet/Home#8827] opened 2019-11-14 22:19 UTC
In the GA release of .Net Core 3.0, we published the 4.6.0 version of `runtime.native.System.IO.Ports` to nuget.org, with non-stable dependencies: https://www.nuget.org/packages/runtime.native.System.IO.Ports/. There was a bug in CoreFx that caused us to produce these non-stable runtime packages, but it also should have been caught during `nuget pack`/`nuget publish`.

CC @ericstj

**Comment by nkolev92** [comment] 2019-11-14 22:37
I'd expect that https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5104 was raised at pack time. 
Note this is a warning. 

I'd expect no validation was added on nuget.org due to customer demand. 
/cc @skofman1 @joelverhagen 

You think this validation should've been something on the org level or?

**Comment by wtgodbe** [comment] 2019-11-15 19:13
Our expectation was that nuget.org would not allow us to push a stable package w/ non-stable dependencies. It's also a bug on our end if we allowed this package to be created in the first place, which we're looking into. @ericstj may be able to add more.

**Comment by rrelyea** [comment] 2019-11-15 19:56
Interesting to consider this scenario end to end. At each step how should we warn:
Client pack - warn
Client push - nothing
Nuget.org for Microsoft org
Nuget.org for all users

Another option is to have a validation step that a publisher runs.
Good to think through the options here.

**Comment by ericstj** [comment] 2019-11-15 20:03
Does PackageBuilder raise NU5104?  Does nuget.exe pack raise NU5104?  Not everyone packs from PackTask.  Also, I feel like this is a regression.  I recall at one point this was a blocking issue, I want to say that NuGet push used to reject this completely.

**Comment by nkolev92** [comment] 2019-11-15 22:39
The warnings are raised in both Pack Task and NuGet.exe pack. 

I couldn't find any info on NuGet push blocking, but that doesn't mean it didn't exist.

**Comment by wtgodbe** [comment] 2019-11-16 06:39
Here is an example of a build with `warnaserror:true` where `NU5104` was thrown, but somehow not recognized as an error: https://dev.azure.com/dnceng/internal/_build/results?buildId=429633 (Build Windows Release). If you look at Build # 1, the same `NU5104` was thrown & treated as an error. Perhaps this is related?

**Comment by nkolev92** [comment] 2019-11-18 20:16
I'm not sure. I know NuGet provides the correct exit code, what doesn't happen is deleting the nupkg when it fails. 

https://github.com/NuGet/Home/issues/7404

**Comment by nkolev92** [comment] 2019-12-31 02:41
@wtgodbe 

Any idea why the CI build didn't fail on your end?
Something other than #7404 that NuGet should investigate?

**Comment by wtgodbe** [comment] 2020-01-08 18:11
> Any idea why the CI build didn't fail on your end?

Not sure about this - @ericstj @safern @viktorhofer @anipik have we learned anything more about this in dotnet/runtime?

**Comment by ericstj** [comment] 2020-01-08 18:22
So I just tested this and there is no warning emitted.  Here's the code we use to pack a nuspec: https://github.com/dotnet/arcade/blob/48bae09d7d8ec0e6879fe2b8d08872cd87f084ca/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs#L245-L315


I had a look at PackageBuilder.Save and it validates the ID of dependencies, but does not validate the consistency in stability:
https://github.com/NuGet/NuGet.Client/blob/feceff9099e6f02dd2a6d76b26ed68a6029959f5/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L367-L378
https://github.com/NuGet/NuGet.Client/blob/feceff9099e6f02dd2a6d76b26ed68a6029959f5/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L543-L556

Would NuGet consider adding stability validation to PackageBuilder?  If not, we can add that to our NuGetPack task.

**Comment by nkolev92** [comment] 2020-01-08 22:54
That specific package validation is done in https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/CommandRunners/PackCommandRunner.cs#L633.

It's after the fact, because these are warnings by default, so we don't fail the package creation if something does go wrong. 
I think it was just done that way so the PackageBuilder doesn't need context about things like warn as error. 

//cc @aortiz-msft 

You can add it your task, but I think as an end goal we should try to have you depend on shipping NuGet, so you don't have to custom implement things and run into similar issues :)

**Comment by nkolev92** [comment] 2020-02-06 06:09
Given the scenario, I think that there should be no actionable by NuGet.Client in this specific instance. 

However, we should fix https://github.com/NuGet/Home/issues/7404. 

Does everyone agree here?
cc @NuGet/nuget-client

**Comment by nkolev92** [comment] 2020-03-12 22:30
Just closing the loop.
The root cause here is that a different pack entry point is being used.
Ideally we'd like to bridge that gap so you can use production NuGet. Feel free to create issues for that as necessary. 

At this point the NuGet actionable is #7404

**Closed as completed by nkolev92** 2020-03-12 22:30 UTC
Labels: Functionality:Pack, Functionality:Push, WaitingForCustomer, Category:Quality Week
