### ISSUE TITLE
NuGet.exe pack project fails with Argument Null

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#2681] opened 2016-04-28 14:33 UTC
Version: NuGet 3.4.3

```
error : Value cannot be null.
error : Parameter name: folderName 
.nuget\\nuget.exe pack "D:\work\RazorGenerator\RazorGenerator.MsBuild\RazorGenerator.MsBuild.csproj" -p o "D:\work\RazorGenerator\artifacts" -symbols -Tool
```

Saw this on my CI which builds fine with v3.3.0.

**Comment by davidebbo** [comment] 2016-04-28 14:50
Maybe same as #2648?

**Comment by rrelyea** [comment] 2016-04-28 14:54
Likely, we'll share a build asap with a fix to confirm.
@toddm - can you peek at this case...to confirm that it is likely a dupe? 
If so, close, if not, remove duplicate label.

**Comment by toddm** [comment] 2016-04-28 15:07
Yes.  I confirmed that it's fixed with the same fix as https://github.com/NuGet/Home/issues/2648.

**Closed as completed by toddm** 2016-04-28 15:07 UTC
Labels: Resolution:Duplicate

**Comment by rrelyea** [comment] 2016-04-28 23:31
@pranavkm  - Can you please try:
1. download not yet final version 3.4.4. of nuget.commandline.nupkg from https://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine/3.4.4-rtm-870
2. rename the .nupkg to .zip
3. Grab nuget.exe from inside the zip file in the tools directory.
4. Try this version of nuget.exe to verify that it has fixed your issue.
5. Tell us how it went

**Comment by ErikSchierboom** [comment] 2016-05-02 12:55
@rrelyea I had the same problem as @pranavkm. The fix you suggested worked for me!
