### ISSUE TITLE
Failed to initialize the powershell host

### ISSUE THREAD

**Issue by bjthomson** [NuGet/Home#6626] opened 2018-02-28 17:55 UTC
Not sure if this is related to https://github.com/NuGet/Home/issues/974
NuGet product used  VS UI | Package Manager Console:

C:\Program Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208

Visual Studio 15.5.7 (But problem started a month ago, before last two updates)

Machine spec:
Win10 Pro 1709 build 16299.248
64Bit
Machine is not on a domain

Worked before? If so, with which NuGet version:
Yes - as above

## Detailed repro steps so we can see the same problem
1. Load Visual Studio 2017 or VS 2015
2.View Package Manager Console
I attach a word doc with more debug info
This is a showstopper, at present I cant upgrade or install packages that invoke powershell.
Note its not related to my solutions - nothing loaded.

[Package manager console in VS 2017.docx](https://github.com/NuGet/Home/files/1768241/Package.manager.console.in.VS.2017.docx)

**Comment by nkolev92** [comment] 2018-03-02 19:38
This is a known powershell issue, duplicate of https://github.com/NuGet/Home/issues/6584. 

Workarounds/solutions discussed here:
https://stackoverflow.com/questions/12638289/embedding-powershell-v2-0-in-net-app-on-windows-8-rtm

Related:
https://docs.microsoft.com/en-us/nuget/release-notes/known-issues#opening-package-manager-console-fails-with-objectsecurity-exception

**Closed as completed by nkolev92** 2018-03-02 19:38 UTC
Labels: Resolution:Duplicate, Product:VS.PMConsole

**Comment by bjthomson** [comment] 2018-03-05 14:08
Yes, I got here (nuGet) by following the links in those posts. I tried all of the suggestions, without success.
The first link concerns Windows 8 and VS2015
Fair enough this is a duplicate, its still a bug.
