### ISSUE TITLE
Nuget.exe version 4.5 breaks package restore when version 4.3 works.

### ISSUE THREAD

**Issue by jimitndiaye** [NuGet/Home#6505] opened 2018-01-30 17:12 UTC
Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget.exe

NuGet version: 4.5

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version: 4.3

## Detailed repro steps so we can see the same problem

1. When I run package restore using the original version 4.3 everything is fine.

2. When I update the nuget executable (via nuget.exe update -self) before running package restore (something our CI build does automatically) the build fails with the following (edited) logs:
```
Target "RestorePackages" in file "C:\Dev\src\.nuget\NuGet.targets" from project "C:\Dev\src\Project\Folder\project.csproj" (entry point):
Task "Exec" skipped, due to false condition; ('$(OS)' != 'Windows_NT' And Exists('$(PackagesConfig)')) was evaluated as ('Windows_NT' != 'Windows_NT' And Exists('C:\Dev\src\Project\Folder\packages.config')).
Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "Exec"
  "..\..\.nuget\nuget.exe" install "C:\Dev\src\Project\Folder\packages.config" -source "" -o "C:\Dev\packages"
  Feeds used:
    C:\Users\Username\.nuget\packages\
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  
  All packages listed in C:\Dev\src\Project\Folder\packages.config are already installed.
C:\Dev\src\.nuget\NuGet.targets(60,5): error MSB3073: The command ""..\..\.nuget\nuget.exe" install "C:\Dev\src\Project\Folder\packages.config" -source "" -o "C:\Dev\packages"" exited with code 1. [C:\Dev\src\Project\Folder\project.csproj]
Done executing task "Exec" -- FAILED.
Done building target "RestorePackages" in project "project.csproj" -- FAILED.
Done Building Project "C:\Dev\src\Project\Folder\project.csproj" (RestorePackages target(s)) -- FAILED.
```
The same error happens across multiple projects in my solution.
Running ```msbuild /t:RestorePackages``` with no other changes other than to restore the original 4.3 executable works with no issues.
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by jimitndiaye** [comment] 2018-01-30 17:21
Seems to be the same issue as #6503

**Comment by emgarten** [comment] 2018-01-30 18:18
Duplicate of https://github.com/NuGet/Home/issues/6503

Thanks for reporting the issue, based on the log this does look like the same issue.

**Closed as completed by emgarten** 2018-01-30 18:18 UTC
