### ISSUE TITLE
dotnet restore cannot use secure password on Windows

### ISSUE THREAD

**Issue by vors** [NuGet/Home#2844] opened 2016-05-24 22:20 UTC
I'm trying to use password-protected nuget feed (from [AppVeyor](http://www.appveyor.com/)) in dotnet restore.

When I use `nuget` command line tool (v3.4.3.855), it works fine:

```
> nuget install My.Package -Version 1.0.0-b2015 -prerelease -ConfigFile .\nuget.config
```

When I use `dotnet restore`, it fails

```
> dotnet restore --configfile nuget.config
```

```
error: Failed to retrieve information from remote source 'https://ci.appveyor.com/nuget/package-12yabt17m62x/FindPackagesById()?id='My.Package'.
error: Password decryption failed for source : 'AppVeyor' is unsupported on this platform. A clear text password may be used instead.
```

Using `ClearTextPassword` in the **global** config (`~\AppData\Roaming\NuGet\NuGet.Config`) solved the problem. I don't want leave a plain-text password there. What should I do?

```
> dotnet --info
.NET Command Line Tools (1.0.0-preview2-002818)

Product Information:
 Version:            1.0.0-preview2-002818
 Commit SHA-1 hash:  54ab5b8385

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by rrelyea** [comment] 2016-05-24 22:51
For now, using NuGet.exe on windows is your best option, if you value the encryption.
The codebase is shared between NuGet Restore and DotNet Restore.
On Windows, in NuGet.exe today, we take advantage of windows encryption apis.

We plan to work with the dotnet core team to ensure that we have this service as appropriate, so that the dotnet restore can add this feature.

**Comment by alpaix** [comment] 2016-06-23 21:34
related to #1851

**Comment by rrelyea** [comment] 2016-07-15 17:44
dupe of https://github.com/NuGet/Home/issues/1851
@harikmenon  - why 3.5 rtm? (please follow up in email)

**Closed as completed by rrelyea** 2016-07-15 17:44 UTC
Labels: Resolution:Duplicate, Type:DCR, Area:Authentication
