### ISSUE TITLE
TrustFailure (CertificateUnknown) Error

### ISSUE THREAD

**Issue by anaselhajjaji** [NuGet/Home#5864] opened 2017-09-08 09:11 UTC
After upgrading to Mono JIT compiler version 5.2.0.215, I can't restore packages because of certificate problem. Do you have a solution to trust the in-house certificates? it was working before upgrading Mono version.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (4.0.0.2283)

Mono JIT compiler version 5.2.0.215

OS version : OS X El Capitan 10.11.6

## Detailed repro steps so we can see the same problem
1. After upgrading to Mono JIT compiler version 5.2.0.215

2. Behind a proxy, perform nuget restore command

==> 
Unable to find version 'X' of package 'Y'.
An error occurred while sending the request
  Error: TrustFailure (CertificateUnknown)
  CertificateUnknown

**Comment by emgarten** [comment] 2017-09-09 05:29
Dupe of https://github.com/NuGet/Home/issues/4387

**Closed as completed by emgarten** 2017-09-09 05:29 UTC
Labels: Resolution:Duplicate
