### ISSUE TITLE
Nuget Restore fails when it encounters a non-standard project

### ISSUE THREAD

**Issue by tgriff** [NuGet/Home#9979] opened 2020-09-02 16:05 UTC
My team has several Azure DevOps build pipelines to build different projects/products from a single solution. Almost all these pipelines have a Nuget Restore task to restore all packages for the solution that runs before the MSBuild task that builds a specific set of projects. Our solution mostly contains C# projects (class libraries, ASP.NET Web apps, etc.) but it also has a couple "non-standard" projects, like a WiX installer project. Except for the non-standard projects, all projects use PackageReference for Nuget packages. Note that the WiX project has a packages.config file that just specifies the WiX package.

The pipeline is using a Microsoft-internal hosted agent pool.

For a while, our pipelines were using an older version of Nuget (3.0.0), but then we needed to move to a newer version of Nuget. However, once we did this our Nuget Restore task started failing.

We contacted the support for the hosted agent pool and together we were able to determine that:

1. Nuget Restore throws an exception when it encounters a non-standard project type (like .wixproj). This causes the entire restore operation, for the entire solution, to fail.

2. This only starts happening with Nuget 4.8.2. This doesn't happen with Nuget 4.7.3.

We can manage for now with Nuget 4.7.3, but if we need to move to a newer version in the future, we will be unable to until this gets resolved.

Here's the exception (and a related warning) we're seeing during the nuget restore task when using Nuget 4.8.2+:
```
NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown. 
at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__68.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__63.MoveNext() 
WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored. 
```

**Comment by rrelyea** [comment] 2020-09-02 18:29
@tgriff - i assume you've also tried version 5.6/5.7 (whatever the latest you have available?)

**Comment by tgriff** [comment] 2020-09-02 18:46
Yes, I've tried several versions up to the latest 5.7.0 and they all throw this exception (and generate the subsequent warning).

Nuget Version | “nuget restore” throws exception?
-- | --
5.7.0 | Yes
5.6.0 | Yes
5.5.1 | Yes
5.0.2 | Yes
4.9.4 | Yes
4.8.2 | Yes
4.7.3 | No
4.5.0 | No

In case it wasn't clear from my initial post, the warning that occurs after the exception indicates it will only restore packages from packages.config, which is the main problem since we use PackageReference wherever possible.

**Comment by rrelyea** [comment] 2020-09-04 22:56
Dupe of https://github.com/NuGet/Home/issues/7796, I believe.

**Closed as completed by rrelyea** 2020-09-04 22:56 UTC
Labels: Resolution:Duplicate
