### ISSUE TITLE
Enable dotnet list package to enumerate all projects in a folder

### ISSUE THREAD

**Issue by simonvane** [NuGet/Home#10786] opened 2021-04-21 17:07 UTC
## Details about Problem
I need to provide a list of nuget packages that we use every time I release our .net core 3.1 application.

The solution is structure as follows:

-solution folder
 solution file
--src (folder)
---project1 (folder)
project1.csproj
---project2 (folder)
project2.csproj
--test (folder)
---project1.tests (folder)
project1.tests.csproj
---project2.tests (folder)
project2.tests.csproj

- I would like to be able to get a unique list of used nuget packages using "dotnet list [folder] packages".
Perhaps this would need flags to control recursion and whether to flatten to unique packages.
Another possibility might be to add wildcard support e.g. "dotnet list .\\src\\**\\*.csproj packages".
- I would like to be able to get the response in a way that I could further process programmatically in PowerShell e.g. in JSON, rather than the current output designed for human consumption. 

Product version: 
dotnet --version
5.0.202

nuget
Name             : Package Manager Host
Version          : 5.9.1.0
InstanceId       : b577b347-4955-4c77-b1e3-b264bfa313bb
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-US
PrivateData      : NuGetConsole.Host.PowerShell.Implementation.NuGetPSHost+Commander
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by zivkan** [comment] 2021-04-21 17:50
There's already a feature request to make `dotnet list package` output "machine readable", which you can upvote (👍 ) to help it bubble higher in the list of requests when sorted by upvotes: https://github.com/NuGet/Home/issues/7752

Changing this issue to a feature request to make `dotnet list package` work on multiple projects, not just one.

**Comment by aortiz-msft** [comment] 2021-04-22 17:16
`dotnet list package` does work at solution level today. Therefore, closing this as a dupe of https://github.com/NuGet/Home/issues/7752

**Closed as completed by aortiz-msft** 2021-04-22 17:16 UTC
Labels: Type:Feature, Product:dotnet.exe, Functionality:ListPackage

**Comment by simonvane** [comment] 2021-04-22 18:09
Thanks @zivkan , I've upvoted that.

**Comment by simonvane** [comment] 2021-04-22 18:18
Thanks for your comment @aortiz-msft . However, my request was not for `dotnet list package` to work at the solution level. I may not have explained it clearly.

My solution contains projects (in the `src` folder) that end up being deployed and test projects (in the `test` folder) that don't. For each release I need to publish a list of packages used by deployed code only.

My requirements are:
- I need to generate a list of packages used only by the projects in the `src` folder.
- I need to generate a flattened distinct list of packages rather than per project.

Providing the output in machine-readable format would help with this but would still require significant scripting work to get the results I really need.

Please could you reopen this?

(P.S. I realised I had not given this issue a clear title - I've corrected it)
