### ISSUE TITLE
Visual Studio experience improvements - Packages in the installed/updates tab should be sorted

### ISSUE THREAD

**Issue by IanKemp** [NuGet/Home#7030] opened 2018-06-15 12:48 UTC
NuGet 4.6.0 (Console Host Version 4.7.0.5212) running in Visual Studio 2017 Enterprise v15.7.3 on Windows 10 Enterprise x64 v1803 (17134.48)

The listed behaviours are the same regardless of whether I'm running Visual Studio normally, or in safe mode, which means it's not an extension causing the issue.

1. When trying to view updated packages, the UI shows me counts, but not the actual packages:

![image](https://user-images.githubusercontent.com/1726434/41350693-41b2300a-6f14-11e8-8890-697ac6cf95c5.png)

The package information eventually appears, but it takes a very long time.

2. When updating packages, NuGet arbitrarily appears to hang on the following line in the Output window:

> Attempting to gather dependency information for multiple packages with respect to project '&lt;projectname>'

The actual project that it hangs on varies wildly and the amount of time it hangs for is also inconsistent. Here's an example from about 5 minutes ago:

```
Attempting to gather dependency information for multiple packages with respect to project '<ProjectName>', targeting '.NETFramework,Version=v4.7.1'
Gathering dependency information took 2.87 min
Attempting to resolve dependencies for multiple packages.
```

Project size, number of usages and number of dependencies/their usages has no effect.

During this process, no information is reported anywhere other than the Output window - in particular the NuGet window in VS becomes grayed-out with zero feedback as to why.

3. Update-able packages are listed in no particular order, alphabetical would be nice:

![image](https://user-images.githubusercontent.com/1726434/41350929-073c5fda-6f15-11e8-9103-970979179f9f.png)

4. Modifying the "Package source" dropdown invalidates the list of packages, even if going from a more to less specific source (example: changing "All" to "nuget.org" nukes all package info already pulled from nuget.org).

Recommendations to improve:

* Whatever NuGet is doing to "gather dependency information" needs to be made more explicit to the user.
* Instead of having nothing more than the very useless "Loading..." spinner in the NuGet VS window when NuGet is doing something, have those operations written to that window. This could be as simple as piping the console output to that window.
* Package metadata should be fetched and keyed by the package source so that this info can be invalidated per source, not globally.
* Sort by name, alphabetically, in all cases.

**Comment by nkolev92** [comment] 2018-08-30 23:23
Gather dependency information is driven by the speed of the sources in your sources list. 
If you increase the verbosity of the logs in Visual Studio, you will get more information about what nuGet is doing. 

Same with the install tab, it's driven by the speed of the sources. NuGet does not really have that much context. It could be because of a slow sources, your internet connection etc.

The metadata invalidation is by design. NuGet does not completely invalidate the fetched versions, it just doesn't show them because the response from the other sources **can** change what NuGet needs to display. 

The sorting of the packages in the Installed/Updates tab now is based on the order they are listed in your packages.config or the PackageReferences in the csproj.

**Comment by nkolev92** [comment] 2018-08-30 23:29
I think the only actionable that I can take out here is that you'd like the packages to be ordered alphabetically.

**Comment by reduckted** [comment] 2019-11-26 06:26
> @nkolev92 If you increase the verbosity of the logs in Visual Studio, you will get more information about what nuGet is doing.

How do I do this? Is there a setting in _Tools -> Options_ that I can change to get more verbose output in the Package Manager window? I can't see any settings like that, but maybe I'm not searching for the right thing.

**Comment by nkolev92** [comment] 2019-11-26 23:14
@reduckted 
NuGet restore is part of the build. 
To increase the verbosity go to: 
Tools -> Options -> Projects and Solutions -> MSBuild project build output verbosity.

**Comment by reduckted** [comment] 2019-11-28 03:56
Awesome, thank you. 😄

**Comment by nkolev92** [comment] 2019-12-30 23:56
Missed when I posted the original comment but this is a duplicate of https://github.com/NuGet/Home/issues/1739.

**Closed as completed by nkolev92** 2019-12-30 23:56 UTC
Labels: Product:VS.Client, Priority:3, Functionality:VisualStudioUI
