### ISSUE TITLE
nuget.exe update should support project.json

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1276] opened 2015-08-28 00:14 UTC
This functionality is essential to test nuget packages.  
We want to have checked in test projects that depend on some minimum version of a packages.  
1. We'll update just our test package to latest, simulating single update of just that package.  
2. We'll update everything in the project to latest, simulating an end user full upgrade.  

`*` versioning in the project.json does not achieve either of these scenarios.  Previously we used nuget update.  Now that nuget3 has dropped most of the things that write to the csproj this should be even easier than before.  Please bring back nuget.exe update.

We can't really do this ourselves easily because it involves nuget making queries to the feeds to determine what version to update to.

**Comment by yishaigalatzer** [comment] 2015-08-28 00:48
What is \* versioning not supporting it?

`Use 2.0.* for example` ?

**Comment by ericstj** [comment] 2015-08-28 01:05
That won't pick up pre-release.

**Comment by yishaigalatzer** [comment] 2015-08-28 01:11
Perhaps that's what we should fix?

Cc @davidfowl 

I'm not really following why '*' doesn't work. What exactly is the test trying to do? \* works for the latest with prerelease.

**Comment by ericstj** [comment] 2015-08-28 13:55
4.0.0-\* will pick up the latest pre-release constrained to 4.0.0.
4.0.\* will only pick up the latest stable constrained to 4.0.
4.\* will only pick up the latest stable constrained to 4.
4._-_ is considered invalid.

**Comment by yishaigalatzer** [comment] 2015-08-28 14:53
You can also use just *?

**Comment by ericstj** [comment] 2015-08-28 15:08
'*' will only pick up latest stable with no constraints on 3-part version.

**Comment by yishaigalatzer** [comment] 2015-08-28 15:12
So if w had support for

`*-beta*`
`*-*`

Etc

That will solve your problem?

**Comment by ericstj** [comment] 2015-08-28 15:19
Yeah, here are the ones I think we'd use: '*-*', '4.*-*', '4.0.*-*'.  I can imagine other folks using a branch specifier in the pre-release string so you'd probably want to support something like '*-beta-*' where it would permit latest pre-release so long as it matched the partial release string.

**Comment by nkolev92** [comment] 2017-12-19 22:49
Duplicate of https://github.com/NuGet/Home/issues/4103

**Closed as completed by nkolev92** 2017-12-19 22:49 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Feature
