### ISSUE TITLE
Nuget (3.4.3) Package Restore not able to resolve environment variables in Repository path

### ISSUE THREAD

**Issue by RamjotSingh** [NuGet/Home#2801] opened 2016-05-17 09:05 UTC
[NuGet.txt](https://github.com/NuGet/Home/files/267753/NuGet.txt)
Nuget is not able to resolve Environment variables when running restore from Visual Studio. I am getting following error while restoring packages

Severity    Code    Description Project File    Line    Suppression State
Error       NuGet Package restore failed for project <Removed>: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at NuGet.ProjectManagement.FolderNuGetProject.InstallPackageAsync(PackageIdentity packageIdentity, DownloadResourceResult downloadResourceResult, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<RestorePackageAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageRestoreManager.<RestorePackageAsync>d__39.MoveNext().          0

I am running restore from inside Visual Studio 2015. I have Nuget extension version 3.4.3.855. I am attaching my Nuget.config (Nuget.txt).

**Comment by rrelyea** [comment] 2016-05-17 19:26
Thanks for report. Dupe of #2763

**Closed as completed by rrelyea** 2016-05-17 19:26 UTC
Labels: Resolution:Duplicate
