### ISSUE TITLE
How to include additional files in lib

### ISSUE THREAD

**Issue by Allann** [NuGet/Home#8780] opened 2019-10-23 03:37 UTC
I have a .Net Core project that contains additional project referenced dlls and these are not added to the nuget package.  
``` xml
  <ItemGroup>
    <ProjectReference Include="..\CodeGen.Generator\CodeGen.Generator.csproj" />
    <ProjectReference Include="..\CodeGen.Interfaces\CodeGen.Interfaces.csproj" />
    <ProjectReference Include="..\CodeGen.Loaders\CodeGen.Loaders.csproj" />
  </ItemGroup>
```
The question then is how can I add these dependent dlls into the the package? 

1. I tried the `ProjectGroup.IncludeBuiltProjectOutputGroup` but mustn't be using the correct value if that is the solution. 
1. I tried adding a nuspec file but that did not help, i assume since VS creates it's own.
1. I notice the ItemGroup has a Content for adding "other" files into the content folder of the package, is there an equivalent Lib?  I couldn't see it, if it does.

When I loaded the nuget package in the Nuget Package Explorer and output the metadata as a nuspec file I received the following:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>OurPresence.CodeGen</id>
    <version>1.0.0</version>
    <authors>Allan Nielsen</authors>
    <owners>Allan Nielsen</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <projectUrl>https://github.com/allann/codegen</projectUrl>
    <description>Code generator using model files and compiled template components</description>
    <copyright>Copyright 2019</copyright>
    <tags>code generator c#</tags>
    <repository type="git" url="https://github.com/allann/codegen" />
    <dependencies>
      <group targetFramework=".NETCoreApp2.1">
        <dependency id="CodeGen.Generator" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="CodeGen.Interfaces" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="CodeGen.Loaders" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="McMaster.Extensions.CommandLineUtils" version="2.4.1" exclude="Build,Analyzers" />
        <dependency id="McMaster.Extensions.Hosting.CommandLine" version="2.4.1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Configuration.EnvironmentVariables" version="2.2.4" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Configuration.Json" version="2.2.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.DependencyInjection" version="2.2.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Hosting" version="2.2.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Hosting.Abstractions" version="2.2.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Logging.Console" version="2.2.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Logging.Debug" version="2.2.0" exclude="Build,Analyzers" />
        <dependency id="Serilog.AspNetCore" version="3.0.0" exclude="Build,Analyzers" />
        <dependency id="Serilog.Sinks.Console" version="3.1.1" exclude="Build,Analyzers" />
        <dependency id="Serilog.Sinks.File" version="4.0.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
  <files>
    <file src="lib\netcoreapp2.1\codegen.dll" target="lib\netcoreapp2.1\codegen.dll" />
    <file src="lib\netcoreapp2.1\codegen.runtimeconfig.json" target="lib\netcoreapp2.1\codegen.runtimeconfig.json" />
  </files>
</package>
```
The CodeGen.*.dll files need to be included as files and NOT dependencies because they dont exist as NuGet packages (and shouldn't be).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard NuGet package - Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli#feedback)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment] 2019-11-01 18:21
This issue is a dupe of: https://github.com/NuGet/Home/issues/3891
we don't yet support includereferencedprojects when you pack with `dotnet pack` or msbuild /t:pack

there is a workaround described in #3891

We have that on our backlog, and hope to get to it this quarter (Q4 2019)

**Closed as completed by rrelyea** 2019-11-01 18:21 UTC
Labels: Resolution:Duplicate, Functionality:Pack
