### ISSUE TITLE
NuGet.Commandline: Make nuget.exe localizable

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1057] opened 2015-07-29 16:51 UTC
NuGet.Commandline: Make nuget.exe localizable. Currently, LocalizedResourceManager is being to localize all the strings into the single exe. We need to ensure that all the strings are localizable using this mechanism

**Comment by feiling** [comment] 2015-08-14 18:39
Duplicate of NuGet/Home#1165

**Closed by feiling** 2015-08-14 18:39 UTC
