### ISSUE TITLE
[Bug]: NU1507 message includes unformatted string

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#11722] opened 2022-04-07 15:50 UTC
### NuGet Product Used

dotnet.exe

### Product Version

dotnet 6.0.300-preview.22206.8

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

The following warning is emitted. Notice how `{0}` is a placeholder for a value that is not actually substituted in.

> warning NU1507: There are {0} package sources defined in your configuration. When using central package management, please map your package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source.

**Comment by dominoFire** [comment] 2022-04-07 17:36
This seems to be the line that emits the message:

https://github.com/NuGet/NuGet.Client/blob/5b0ee2562df6cf2c66cc9905a8a65f2b09ea5473/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs#L477

**Comment by jeffkl** [comment] 2022-04-07 18:16
Closing as a duplicate of https://github.com/NuGet/Home/issues/11709

The fix is in main for 17.3 and we're working on getting it in 17.2: https://github.com/NuGet/Client.Engineering/issues/1543

**Closed as completed by jeffkl** 2022-04-07 18:16 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug, Product:NuGet.exe, Functionality:Restore, Product:dotnet.exe, Area:RestoreCPM
