### ISSUE TITLE
Visual Studio should not show updates that have unmet framework dependencies

### ISSUE THREAD

**Issue by mqudsi** [NuGet/Home#5822] opened 2017-08-30 15:09 UTC
_Running Visual Studio 2017 15.3.0 Preview 7.1_

Currently, Visual Studio's nuget integration shows an available update for packages that have updates available that cannot be installed on any of the current configurations.

For example, a dependency on `Microsoft.AspNetCore.Cryptography.KeyDerivation` version 1.1.2 will trigger the "update available" UI because `Microsoft.AspNetCore.Cryptography.KeyDerivation` version 2.0.0 is available on NuGet; however in a project that does not target .NET Standard 2.0, this package cannot be installed (and Visual Studio/NuGet rightly inform you of that when you attempt to upgrade).

For a project that does not target .NET Core 2 at all, this should not automatically be shown as an available update (though of course the user can try to select this version from the version drop-down in package management and futilely attempt to upgrade to it if they so choose).

**Comment by rrelyea** [comment] 2017-08-30 20:09
Very important issue, we agree. In our backlog. Changing the title to reflect what we call it.

**Comment by mqudsi** [comment] 2017-08-30 21:14
Thanks.

**Comment by nkolev92** [comment] 2017-10-18 00:10
Thanks for creating this issue. 

This is a duplicate of https://github.com/NuGet/Home/issues/5725

Please subscribe and follow that thread.

**Comment by mqudsi** [comment] 2017-10-18 00:11
@nkolev92 I think there's some mistake, you closed this issue as a duplicate of this same issue?

**Closed as completed by nkolev92** 2017-10-18 00:10 UTC
Labels: Priority:2, Type:Feature, Functionality:Update

**Comment by nkolev92** [comment] 2017-10-18 17:19
I had pasted the wrong link. 
Thanks @mqudsi 
The real issue is https://github.com/NuGet/Home/issues/5725

**Comment by EduardoPires** [comment] 2017-10-22 12:30
There are some road map to fix this problem?
Some workaround?

**Comment by nkolev92** [comment] 2017-10-22 23:34
@EduardoPires 
This is a new feature that's on our backlog. 

There are no workarounds for it currently.
