### ISSUE TITLE
[question] Why can't dotnet5.1 packages be used in Profile 259 PCLs?

### ISSUE THREAD

**Issue by jamesqo** [NuGet/Home#2600] opened 2016-04-18 02:27 UTC
Hi, I just made a NuGet package over [here](https://www.nuget.org/packages/Enumerator) that supports `dotnet5.1` and `net40` as target frameworks. From what I can see over [here](https://github.com/dotnet/corefx/blob/9e0b539c9ee3dd105ff55e81c1c32cd2976b71ef/Documentation/project-docs/standard-platform.md), `dotnet5.1` is essentially the same thing as the newer `netstandard1.0` and [can be consumed by profile 259 PCLs](https://github.com/dotnet/corefx/blob/9e0b539c9ee3dd105ff55e81c1c32cd2976b71ef/Documentation/project-docs/standard-platform.md#portable-profiles). However, when I create a new class library targeting that profile in Visual Studio and run

``` posh
Install-Package Enumerator
```

from the console, I get an error:

```
Install-Package : Could not install package 'Enumerator 1.13.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not 
contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Why is this and how do I fix it?

cc @yishaigalatzer

**Comment by yishaigalatzer** [comment] 2016-04-19 01:03
What version?

**Comment by jamesqo** [comment] 2016-04-19 01:56
@yishaigalatzer It seems to be happening with whichever one is installed in VS2015 Update 2, both in the GUI and the console. Here's the output of `nuget help` (which contains the version) in the Package Manager Console:

``` posh
PM> nuget help
NuGet Version: 2.8.60717.93
```

**Comment by yishaigalatzer** [comment] 2016-04-19 04:06
You are running visual studio 2013 at least in the sample

**Comment by yishaigalatzer** [comment] 2016-04-19 04:07
I believe this issue was fixed in 3.4.3 which we will release in a couple of days

**Comment by davidfowl** [comment] 2016-04-19 14:09
This is by design, the dotnet5.x moniker doesn't work with PCLs.. Only netstandard does

**Comment by jamesqo** [comment] 2016-04-19 14:19
@davidfowl I thought dotnet5.x was supposed to be equivalent to netstandard1.y, where y == x - 1... What was the point of introducing the .NET generation monikers, then?

**Comment by rrelyea** [comment] 2016-04-21 20:59
They are not fully equivalent. Please use .NET Standard. Closing this issue in the NuGet repo.

**Closed as completed by rrelyea** 2016-04-21 20:59 UTC
