### ISSUE TITLE
NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at ''' returned an unexpected status code '404 Not Found'.

### ISSUE THREAD

**Issue by pantonis** [NuGet/Home#4847] opened 2017-03-20 12:30 UTC
Remove the content above here and fill out details below.

When I try to install a packet from my own Nuget.Server instance I receive

```NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at ''' returned an unexpected status code '404 Not Found'.``` If I use the Package Manager Console to install the package it works. When I use VS Nuget extensions I get the message above. I also have the same problem on my TeamCity server.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Nuget Package Manager for VS 2015

NuGet version (x.x.x.xxx):
3.4.4.1321

dotnet.exe --version (if appropriate):

VS version (if appropriate):
VS2015

OS version (i.e. win10 v1607 (14393.321)):
Win v1.6077 14393.953

Worked before? If so, with which NuGet version:

**Comment by rrelyea** [comment] 2017-03-20 14:39
The latest NuGet for VS 2015 is current 3.5.0, which is available via http://nuget.org/downloads
Can you please tell us if you still have issues once your are running the latest version?

**Comment by emgarten** [comment] 2017-10-17 23:00
Duplicate of https://github.com/NuGet/Home/issues/4860

**Closed as completed by emgarten** 2017-10-17 23:00 UTC
Labels: Resolution:Duplicate, Area:HttpCommunication
