### ISSUE TITLE
Lightweight Solution support for Manage NuGet Packages for Solution UI

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3988] opened 2016-11-21 20:50 UTC
From VSFeedback issue https://developercommunity.visualstudio.com/content/problem/2591/manage-packages-for-solution-opens-very-slow-due-t.html:

The behavior you are seeing is because of our Lightweight Solution Load behavior in VS 2017 RC.
Today, when you have that enabled, all the projects are not loaded initially.
When you choose solution restore, we will need to load all projects and then restore.
(A) ​We are working (post-RC) to remove the need to load all projects in order to restore.
When you launch the Manage NuGet Packages for Solution UI, we currently need to have all projects loaded.

​After we have done the work to enable restore to not require projects be loaded (A), we will be able to also remove the need for this UI to need all the projects be loaded (B).
A - plan to have done for VS 2017.
B - unsure of our timing for this scenario

This issue is tracking B.
​

**Comment by ZlobnyiSerg** [comment] 2016-11-21 21:21
I think the problem is not in the requirement to load all projects. The problem is that projects are loaded very slow when lightweight solution load enabled: much more slower in comparison to solution loading times with lightweight load disabled. I think this feature can be splitted to two: one is to improve project loading time in lightweight mode (VS2017 issue?), and the second you've described here (avoid project loading at all - that would be wonderful).

**Comment by MichaelSteinecke** [comment] 2017-04-05 08:03
I would like to add, that also opening the NuGet Package manager console requires to load the entire solution. This is likewise slow, when Lightweight Load is enabled.

**Comment by jainaashish** [comment] 2017-11-30 00:21
This doesn't apply anymore so closing it.

**Closed as completed by jainaashish** 2017-11-30 00:21 UTC
Labels: Product:VS.Client, Type:Feature, Tenet:Performance
