### ISSUE TITLE
Incorrect mapping of <ProjectReference> to nuspec package reference

### ISSUE THREAD

**Issue by ewoutkramer** [NuGet/Home#4602] opened 2017-02-15 09:15 UTC
I am using VS2017RC4 to build two projects and pack them into two nuget packages, one project referring to the other using a <ProjectReference> element in its csproj file.  

However, both projects have a .csproj file with a different name than their Nuget package ID, which is specified in their respective <PackageId>s.  

This results in the <ProjectReference> in the referring project to be turned into the wrong nuget package reference, since the package reference is automatically generated by the tool based on the .csproj filename of the project referred to, not (understandably) the <PackageId> in the .csproj of that project.

It would be useful to have a metadata element on the <ProjectReference> to set the actual NuGet package id the reference should be turned into.

**Comment by rrelyea** [comment] 2017-02-15 09:20
PackageId can be set to override the inferred ID. 
That will work when restoring via dotnet.exe

However , we have a bug that causes restore inside of vs to ignore that. (will link that issue in morning) 

Workaround : use packageid and restore via dotnet.exe for that solution

**Comment by ewoutkramer** [comment] 2017-02-15 09:27
I have verified that the package reference in the .nuspec generated from the .csproj is incorrect, I don't see how dotnet.exe would ever be able to find and fix that?

This:

```
  <ItemGroup>
    <ProjectReference Include="..\Hl7.Fhir.Core\Hl7.Fhir.Core.csproj" />
  </ItemGroup>
```
Gets turned into:

```
      <group targetFramework=".NETStandard1.3">
        <dependency id="Hl7.Fhir.Core" version="1.0.0-alpha1" exclude="Build,Analyzers" />
```
Which is wrong, since the referred to Hl7.Fhir.Core.csproj containts a property overriding its package id:

```
  <PropertyGroup>
    <PackageId>Hl7.Fhir.DSTU2</PackageId>
```
So I would have expected:

```
       <group targetFramework=".NETStandard1.3">
        <dependency id="Hl7.Fhir.DSTU2" version="1.0.0-alpha1" exclude="Build,Analyzers" />

```
instead...

**Comment by rrelyea** [comment] 2017-02-15 16:34
Dupe of #4586 

The communication between the project system and NuGet while running in VS is broken for this property.
#4586 covers that issue. It may not be fixed for VS2017.
Workaround is to have PackageId in your csproj and do your restores from command line.

Your follow up question isn't clear to me.

**Closed as completed by rrelyea** 2017-02-15 16:34 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Platform:Xplat, Functionality:Restore
