### ISSUE TITLE
dotnet pack should include files from shared src projects in symbol packages

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3934] opened 2016-11-12 01:38 UTC
Moved from https://github.com/dotnet/cli/issues/4094 on behalf of @pranavkm.

----

## Steps to reproduce
- Create a ClassLibrary project
- Add a reference to a shared src project. For instance https://dotnet.myget.org/feed/aspnetcore-master/package/nuget/Microsoft.Extensions.ActivatorUtilities.Sources.
- Run dotnet pack
## Expected  behavior

The symbol package contains shared cs files from the sources package.
## Actual behavior

Shared cs files are missing.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by rohit21agrawal** [comment] 2016-12-15 00:14
this seems to be the right behavior. @emgarten thoughts?

**Comment by rohit21agrawal** [comment] 2016-12-15 01:04
@piotrpMSFT  dotnet pack relies on SourceFilesProjectOutputGroup target from msbuild to provide all the source files that should be included in the nuget package. looks like the target doesn't include cs files from shared src nuget packages. this probably needs to be fixed on the msbuild side.

**Comment by TheRealPiotrP** [comment] 2016-12-15 20:47
@pranavkm who opened the original issue
@nguerrera who can better comment on `SourceFilesProjectOutputGroup`

**Comment by pranavkm** [comment] 2016-12-15 21:08
The original work item was filed when we were working with project.json. @natemcmaster has been switching `shared` src projects to projects with `contentFiles`. Does the problem reproduce for packages with content files?

**Comment by rohit21agrawal** [comment] 2016-12-15 21:11
@pranavkm contentFiles is still ongoing work for restore. We checked in changes to pack to support contentFiles out of box a couple days ago, but there is still an open issue against it: 
https://github.com/NuGet/Home/issues/4100

**Comment by rrelyea** [comment] 2016-12-30 00:44
contentFiles is the right direction here.
we will be integrating the rc3 nuget into CLI and VS very soon...and it will now support contentFiles in restore...and as Rohit mentioned, proper pack support is coming too

as such, closing this issue.

**Closed as completed by rrelyea** 2016-12-30 00:44 UTC
Labels: Triage:Investigate, Functionality:Pack
