### ISSUE TITLE
Exists call on Metadataresource extremely innefficient

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1950] opened 2016-01-19 17:38 UTC
The call to Exists is potentially extremely inefficient because it tries to load all the metadata (all versions for example) instead of just making something like a head request against the resource.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/MetadataResourceV3.cs#L72

**Comment by emgarten** [comment] 2016-02-04 22:33
Dupe of https://github.com/NuGet/Home/issues/1931

**Closed as completed by emgarten** 2016-02-04 22:33 UTC
Labels: Resolution:Duplicate, Priority:3, Type:Bug
