### ISSUE TITLE
NuGet tries to install System.Runtime-4.0.20 even though it requires .NETFramework,Version=v4.6

### ISSUE THREAD

**Issue by binki** [NuGet/Home#1243] opened 2015-08-24 15:12 UTC
When I go to install System.Runtime-4.0.20 into a fresh .net-4.5 project, I get 
![2015 08 24-nuget-lets-me-try-system runtime-4 0 20](https://cloud.githubusercontent.com/assets/82626/9443737/c04e4a8e-4a50-11e5-822b-ea04b3ec8d86.png)
. Instead, it should never even display 4.0.20 as an option or never claim to have successfully resolved its dependencies. When I say to go ahead and install it, it gets past the dependency resolution phase and actually tries to install it:

```
Attempting to gather dependencies information for package 'System.Runtime.4.0.20' with respect to project 'ConsoleApplication7', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'System.Runtime.4.0.20' with DependencyBehavior 'HighestMinor'
Resolving actions to install package 'System.Runtime.4.0.20'
Resolved actions to install package 'System.Runtime.4.0.20'
For adding package 'System.Runtime.4.0.20' to project 'ConsoleApplication7' that targets 'net45'.
Install failed. Rolling back...
Package 'System.Runtime 4.0.20' does not exist in project 'ConsoleApplication7'
Package 'System.Runtime 4.0.20' does not exist in folder 'c:\users\ohnob\documents\visual studio 2015\Projects\ConsoleApplication7\packages'
Could not install package 'System.Runtime 4.0.20'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========
```

Instead, it should fail at the dependency resolution phase.

A related problem: when I try to install System.Collections.Immutable-1.1.37 with HighestMinor, nuget-3.1.60724.766 considers System.Runtime-4.0.20 as the best version to install. It shouldn’t even consider System.Runtime-4.0.20 because of its dependency on .NETFramework,Version=v4.6. Instead, it actually installs some nuget packages and then, on System.Runtime-4.0.20 failing, it backs everything out. Again, it should not let you past the dependency resolution phase.

**Comment by emgarten** [comment] 2015-08-25 05:00
The final compatibility check where this is failing requires downloading the nupkg and checking the contents. The resolution phase used by the preview only looks at dependency information from the feed.

**Comment by yishaigalatzer** [comment] 2015-08-25 16:54
This is a flaw in how these packages where shipped. Minor release changes should not be breaking compatibility. We also do not want the server to keep understanding all versions of target framework logic, because it does not scale to the multitude of private servers out there (where they have to update whenever the nuget logic changes).

These packages will start following semver more strictly going forward and this particular pain point will eventually go away.

As it is we don't plan making any changes in this area at least for now.

If you feel this is the wrong decision, please re-open and provide some more input on why this must be fixed.

**Comment by binki** [comment] 2015-08-26 04:19
> The resolution phase used by the preview only looks at dependency information from the feed.

@emgarten It doesn’t even seem to be looking at information in the feed. I can see `::net46` at https://www.nuget.org/api/v2/Packages%28Id=%27System.Runtime%27,Version=%274.0.20%27%29 .

@yishaigalatzer In my case, I was trying to install a package that depends on ≥System.Runtime-4. I like to set nuget to resolve dependencies to the “highest minor”, though I really don’t know why I would want to be running anything earlier than the latest available release. If the package I’m trying to install just asks for ≥System.Runtime-4, how can I get the system to automatically select the best package version for me automatically? It wouldn’t make sense for everyone to have to have ≥System.Runtime-4 && <System.Runtime-4.0.20 because they shouldn’t be required to think about which version of System.Runtime suddenly requires a .net framework. Also, putting in such a requirement would break a .net-4.6 app which requires a fix in System.Runtime-4.0.20. Basically, this feels like a time that nuget is not being smart enough about helping users try to install the best versions of available packages.

Anyway, I still am confused that nuget would get beyond the dependency resolution phase before verifying that all dependencies are either existing or able to be installed. The error output just looks wrong. Does this mean that only half of the dependency checks are performed when building the dependency tree and some “fuller” version of dependency checks waits until the package is about to be installed? Why not just do all the checks up front (putting that code in one shared spot) and avoid a rollback? This confusing behavior is what caused me to open this bug. Nuget claimed it could successfully install System.Runtime-4.0.20 even though it had enough information to determine it shouldn’t be able to and relied on rollback behavior instead of just preventing the installation attempt in the first place.

**Comment by yishaigalatzer** [comment] 2015-08-26 04:26
Fair enough, we could do better on this. The assumption is that such breaking changes are not introduced in minor versions ( because it breaks semver). System.runtime breaks this unfortunately.

But I'm a bit confused to why you even need it to begin with for a 4.6 app?

Reopening to see if we can do anything about it further. My concern is that trying to find the highest minor that satisfies all dependencies is going to raise the cost and complexity of the resolved to a point that it becomes extremely slow.

In this case if system.runtime followed semver that wouldn't be a problem.

Cc @ericstj

**Comment by emgarten** [comment] 2015-08-26 04:57
NuGet's preview window shows the result of the dependency resolution phase walks through the package dependencies and verifies that all required packages can be found and that there are no conflicts. An example of a conflict during dependency resolution would be if package A required B >= 2.0.0, but the project already had package C installed which required B < 1.5.0. 

The net46 you see in the feed is referring to the dependencies required when the project's target framework is net46 or higher. There is no group for net45 which means that there are zero dependencies for net45. This does not mean that the package cannot be installed into a net45 project, that can only be determined by opening the nupkg and looking for compatible framework folders such as lib\net45.

The highest minor setting does look like an issue when resolving these packages.

**Comment by binki** [comment] 2015-08-26 05:28
> > Also, putting in such a requirement would break a .net-4.6 app which requires a fix in System.Runtime-4.0.20.
> > But I'm a bit confused to why you even need it to begin with for a 4.6 app?

@yishaigalatzer Here I’m trying to say that if nuget package A depended on ≥System.Runtime-4 AND <System.Runtime-4.0.20 to make my .net-4.5 app happy, such a dependency would make it impossible for a .net-4.6 project to install both package A and ≥System.Runtime-4.0.20.

> What package were you trying to install originally?

@emgarten I was installing System.Collections.Immutable-1.1.37 into a .net-4.5 project with dependency resolution set to HighestMinor.

> This does not mean that the package cannot be installed into a net45 project, that can only be determined by opening the nupkg and looking for compatible framework folders such as lib\net45.

Ah, so the “.NETFramework,Version=4.6” I see listed in the nuget extension in VS is a heading for the dependencies required when installing into a .net-4.6 project, not a statement that the project requires .net-4.6. Seems a bit pointless for a project to explicitly declare no dependencies for .net-4.6 if you have to list the archive’s contents to figure out whether or not it provides a `lib/net46` or not. So I made a very incorrect assumptions there. And fixing this would take quite a bit more effort than I imagined. I thought that nuget was exposing platforms/frameworks as implicitly-defined virtual packages they could participate in the normal dependency resolution graph—but this is not what is happening and changing that would break the HTTP API for existing clients.

**Comment by ericstj** [comment] 2015-08-26 23:37
Sorry I'm coming to this discussion late.  I'll second what @yishaigalatzer said earlier: for the first release of the .NET packages we didn't follow SemVer.  We were building out packages that mapped 1:1 with the assembly versions that have shipped.  This helps folks map their libraries from older SDKs to the new nuget model.

The downside at the moment is that you cannot upgrade those System.\* dependencies if you are on an older platform or you'll upgrade yourself out of support for that platform.  We're working with the nuget team on designing a better way to distinguish surface area and we'll improve the experience here in the future.  For now just now that on desktop platforms you shouldn't bother updating the System.\* packages since those are really just markers for the fixed reference assemblies installed by Visual Studio.

**Comment by evancox10** [comment] 2015-09-17 22:42
Hi, I'm wondering if I'm running into a similar issue. This may not be 100% what the OP is experiencing, but we both have some of the same questions, and this thread is what showed up from a Google search.

I've updated some projects of mine to target .NET Framework 4.6. These projects use System.Collections.Immutable also, for which the latest stable version right now is 1.1.37. Previously when NuGet restored this package into a .NET 4.5.x project, I would get just the Immutable package. Now, when restoring it to a .NET Framework 4.6 project, it starts grabbing quite a few System.\* packages that I know, of course, are already installed on the computer along with Visual Studio. What's going on here? Where can I find some documentation on this new behavior? And I too was confused by the ".NETPlatform,Version=v5.0" line under Dependencies. This is very confusing, does Immutable depend on this .NET platform? (That doesn't even make sense, since the latest .NET Fx is only 4.6!) I eventually figured out that this was meant to be read as "Dependencies when used on this platform," at least I think so. But why is this affecting my project targeting the full .NET 4.6 framework? This is NOT an ASP.NET5 or .NET Core project.

This wouldn't even be a huge issue, because the project still runs and builds. However, I think that these place holder assemblies are knocking out the Intellisense documentation for these packages. I've lost visibility into any of the written summaries/remarks/descriptions/etc. If anyone has any tips on how I should fix this, let me know.

FYI, I am using DependencyBehavior Lowest, only because that was the default and it appeared to work with it.

**Comment by emgarten** [comment] 2015-09-22 21:54
@ericstj can you answer @evancox10's question on how these packages work in .net 4.6?

**Comment by ericstj** [comment] 2015-09-23 18:43
What you're seeing is the actual set of implementation dependencies of the PCL library.  Normally these are hidden because the platform automatically adds them to the project.  In the new packages these serve the purpose of ensuring that the dependencies are compatible with the target framework.  All those system.\* packages have appropriate assets in them to communicate to nuget that the library is supported and comes from the inbox framework/targeting pack.

Having those dependencies show up in a Net46 project should be innocuous, be we do plan on cleaning this up in a future release to reduce the confusion on packages.config based projects.

Intellisense being broken on .Net 4.6 desktop is a separate issue that is known and being investigated.  If you'd like to workaround it you can xcopy the XML files from `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\*.xml` to `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\*.xml` (after backing up your copy in 4.6, of course).  This of course won't give you any of the new API added in 4.6, but it should get you in a better state.

**Comment by yishaigalatzer** [comment] 2015-09-24 19:15
Would be really nice if they didn't show up in a NET46 project, it makes the packages.config explode in size for no apparent reason.

@ericstj could you guys consider modifying the package to include a net46 TFM, and remove the extra dependencies?

**Comment by yishaigalatzer** [comment] 2015-10-13 00:07
@ericstj ping?

**Comment by ericstj** [comment] 2015-10-13 01:28
> Having those dependencies show up in a Net46 project should be innocuous, be we do plan on cleaning this up in a future release to reduce the confusion on packages.config based projects.

**Closed as completed** 2015-10-13 01:30 UTC

**Comment by stevenshort** [comment] 2016-05-16 21:26
Why is this closed? Is there a solution?

**Comment by yishaigalatzer** [comment] 2016-05-16 21:43
It is closed because the issue is in the packages and not in nuget. There is no workaround until they get fixed

**Comment by ericstj** [comment] 2016-05-16 21:49
You can use the latest rc3 packages from https://dotnet.myget.org/gallery/dotnet-core which have the fix.
