### ISSUE TITLE
nuget pack url encodes filenames with @ or whitespace (%40 and %20)

### ISSUE THREAD

**Issue by dhvik** [NuGet/Home#6225] opened 2017-11-27 11:13 UTC
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4.4.1.4656

dotnet.exe: 2.0.3

OS version (i.e. win10 v1607 (14393.321)): win 8.1 (6.3.9600)

## Detailed repro steps so we can see the same problem

1. Create an empty text file and include whitespace and @ in name.
` test whitespace and@.txt`
2. Create a minimal nuspec file and include the file using a file element
```
<?xml version="1.0"?>
<package >
  <metadata>
    <id>Package</id>
    <version>1.0.0</version>
    <authors>dan</authors>
    <description>My package description</description>
  </metadata>
  <files>
	<file src="*.txt" target=""/>
  </files>
</package>

```
3. Create a nuspec by issuing the pack command
`nuspec pack`

4. The resulting Package.1.0.0.nupkg file now contains a file named 
`test%20whitespace%20and%40.txt`

I was expecting the filename to be preserved...
It looks correct in the verbose output but not when I open it using zip or winrar.

## Other suggested things
Seems like the same issue as https://github.com/NuGet/Home/issues/5726 and 
 https://github.com/NuGet/Home/issues/2389 but the issue still seems to lack a proper fix.
Also tested other nuget.exe versions but the error is still there.

### Verbose Logs

```
nuget pack -verbosity detailed
NuGet Version: 4.4.1.4656
Attempting to build package from 'Package.nuspec'.

Id: Package
Version: 1.0.0
Authors: dan
Description: My package description
Dependencies: None

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'Package.nuspec'.
Added file 'package/services/metadata/core-properties/af72e74a97c84943967ed890fa786e35.psmdcp'.
Added file 'test whitespace and@.txt'.

Successfully created package 'C:\tmp\nuspec\Package.1.0.0.nupkg'.

```
### Sample Project
[Package.zip](https://github.com/NuGet/Home/files/1505562/Package.zip)

**Comment by rohit21agrawal** [comment] 2017-11-27 18:31
dupe of https://github.com/NuGet/Home/issues/5956

**Closed as completed by rohit21agrawal** 2017-11-27 18:31 UTC
Labels: Resolution:Duplicate, Functionality:Pack

**Comment by nonnb** [comment] 2022-10-17 14:38
NuGet version 5 onwards does not URL encode file and folder names in the nupkg zip file (i.e. no %20 et  if a file has a space)
Note however that this change breaks tools like older versions of Octopus Deploy which were 'dependent' on the file/folder name being urlencoded.
