### ISSUE TITLE
NuGet update fails with 403 error (v3.4.2)

### ISSUE THREAD

**Issue by Kanimozhi12** [NuGet/Home#2520] opened 2016-04-11 10:18 UTC
Hi ,

Now the installtion is working fine. But am unable to update NuGet packages from custom feed.Am getting the below error please look into this and provide solution ASAP.

**The V2 feed at 'http://{custom feed link}/FindPackagesById()?id='Microsoft.Owin.Security.Facebook'' returned an unexpected status code '403 Forbidden'.**

Note: It works fine in console. It has issue while using UI

**Comment by yishaigalatzer** [comment] 2016-04-11 17:10
Can you please share more information with us?

What kind of server do you have set up as a private feed? What version? Is there any customization?

**Comment by yishaigalatzer** [comment] 2016-04-11 17:45
@Kanimozhi12 looking at this issue again, it will be very helpful to provide as much information as you can for us to reproduce this issue. We have tested NuGet 3.4.2 against the 10 types of servers we are familiar with (artifactory, nexus, proget, teamcity, nuget.server, nuget gallery, klondike, nuget.org, myget and vsts).

Could it be that you have an authentication issue with the server (is it password protected, how was that set up?)

Please note that it is critical to get this feedback to figure out a reproducible scenario, as soon as that happens we will work on a fix.

**Comment by joelverhagen** [comment] 2016-04-11 19:20
I've tried this on Artifactory Enterprise 4.7.1 rev 40159. To attempt the repro:
1. Configured Artifactory to not allow anonymous access.
2. Created an Artifactory user that has access to a package.
3. Installed a lesser version of a package on Artifactory.
4. Attempted to update the package.

It seems to work out for me.

```
Attempting to gather dependency information for package 'Microsoft.Owin.Security.Facebook.3.0.1' with respect to project 'ConsoleApplication3', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Microsoft.Owin.Security.Facebook.3.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.Owin.Security.Facebook.3.0.1'
Resolved actions to install package 'Microsoft.Owin.Security.Facebook.3.0.1'
Removed package 'Microsoft.Owin.Security.Facebook.3.0.0' from 'packages.config'
Successfully uninstalled 'Microsoft.Owin.Security.Facebook.3.0.0' from ConsoleApplication3
  GET http://artifactory:8081/artifactory/api/nuget/nuget/Download/Microsoft.Owin.Security.Facebook/3.0.1
  OK http://artifactory:8081/artifactory/api/nuget/nuget/Download/Microsoft.Owin.Security.Facebook/3.0.1 32ms
Installing Microsoft.Owin.Security.Facebook 3.0.1.
Adding package 'Microsoft.Owin.Security.Facebook.3.0.1' to folder 'D:\trash\2016-04-11\ConsoleApplication3\packages'
Added package 'Microsoft.Owin.Security.Facebook.3.0.1' to folder 'D:\trash\2016-04-11\ConsoleApplication3\packages'
Added package 'Microsoft.Owin.Security.Facebook.3.0.1' to 'packages.config'
Successfully installed 'Microsoft.Owin.Security.Facebook 3.0.1' to ConsoleApplication3
Removing package 'Microsoft.Owin.Security.Facebook.3.0.0' from folder 'D:\trash\2016-04-11\ConsoleApplication3\packages'
Removed package 'Microsoft.Owin.Security.Facebook.3.0.0' from folder 'D:\trash\2016-04-11\ConsoleApplication3\packages'
```

In addition to what @yishaigalatzer said, could you provide us more information about:
- What NuGet server software you are running against (version number included).
- How you provide credentials for the source.
- Whether other operations (search) work. You mentioned install works fine.
- Whether older versions work (see http://dist.nuget.org/index.html).

**Comment by joelverhagen** [comment] 2016-04-12 16:57
Related: https://github.com/NuGet/Home/issues/2034
We have considered prompting for credentials on HTTP 403.

**Comment by kmcclive** [comment] 2016-04-12 22:41
I am having a similar problem.  We have a custom feed which requires a token at the end for authentication.  The source of the feed looks like this: http://<hostname>/<token> It appears that some of the calls made by the package manager do not include the full URL.  I see the following errors in the Visual Studio output.

> The V2 feed at 'http://<hostname>/nuget/FindPackagesById()?id='<package id>'' returned an unexpected status code '403 Forbidden'.
> 
> [<feed name>] The V2 feed at 'http://<hostname>/nuget/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net45'&includePrerelease=false&$skip=0&$top=26' returned an unexpected status code '403 Forbidden'.

**Comment by joelverhagen** [comment] 2016-04-12 23:38
@kmcclive,
- Which NuGet server software are you running against?
- Could you provide an example  of a call that succeeded? I presume the `<token>` part was there in some cases?
- Do nuget.exe or the Package Manager Console have the same problem?
- What actions are you performing in the VS UI to cause the failure? What about the successes?
- Do older versions of the NuGet extension not have this problem? What is the newest version that works just fine for you?

**Comment by Kanimozhi12** [comment] 2016-04-13 04:15
**What NuGet server software you are running against (version number included).?**

NuGet server 2.10.1

**How you provide credentials for the source.?**

We dint provide any creditials

**Whether other operations (search) work. You mentioned install works fine.?**

Yes, search and installation works. Update too works from console but not from UI.

*_Whether older versions work (see http://dist.nuget.org/index.html).?
*_
In  version 3.3 also update has issues.in v3.3 it asks to check the private feed link whether its proper or not. but the installation works well with the same feed.

**Comment by yishaigalatzer** [comment] 2016-04-13 04:22
Is the source protected or completely public? Would you mind upgrading your server to 2.10.2? We made a few significant bug fixes between the two versions

**Comment by Kanimozhi12** [comment] 2016-04-13 07:13
I have tried with updated NuGet server. now  having the below issue.
 it throws same error as mentioned in previous updates and the additional  error
The V2 feed at 'http://{private feed link}/FindPackagesById()?id='Microsoft.AspNet.ScriptManager.MSAjax'' returned an unexpected status code '403 Forbidden'.

And also i have found that issue is reproduced only when choosing update option from updates tab. Refer below image
![image](https://cloud.githubusercontent.com/assets/17586319/14493176/9df8f9b2-01a1-11e6-85b3-9dd6580ce7fa.png)

**Comment by yishaigalatzer** [comment] 2016-04-13 14:33
Can you share a fiddler trace of the failure?

When you say things take a long time, was it faster before? Can you share an exact repro steps?

**Comment by maartenba** [comment] 2016-04-13 14:38
I'd also like to see a Fiddler trace. Here are some instructions: https://docs.nuget.org/consume/nuget-faq#managing-packages-in-nuget.org (see "Fiddler")

(feel free to send the trace to support@nuget.org as it may contain information that should not be out in the public on GitHub)

**Comment by kmcclive** [comment] 2016-04-13 14:49
@joelverhagen, below are the answers to the questions you asked me.

**Which NuGet server software are you running against?**
2.7.41101.299

**Could you provide an example of a call that succeeded? I presume the <token> part was there in some cases?**
It turns out I can't.  I thought certain features were working, but I was wrong.  The only thing that works is listing the installed packages, but that's no surprise since it doesn't have to communicate with the server for that.

**Do nuget.exe or the Package Manager Console have the same problem?**
nuget.exe (v3.4.2-rc) seems to work, but the Package Manager Console does not.

**What actions are you performing in the VS UI to cause the failure? What about the successes?**
I first noticed the problem when the package manager attempted to restore a package during a build.  If I manage the packages for a project or a solution from the Solution Explorer, the only thing that works is listing the installed packages.  The Browse, Updates, and Consolidate tabs all generate errors.

**Do older versions of the NuGet extension not have this problem? What is the newest version that works just fine for you?**
Yes, that is correct.  Version 3.3.0.167 is the newest version that I _know_ works.

**Comment by kmcclive** [comment] 2016-04-13 14:50
Just to clarify, in my case, the 403 error is something that I programmed into our NuGet server.  I modified the routing so that 403 is returned if a valid token is not provided.  Otherwise, it strips out the token and proceeds normally.  I am just surprised that the calls in the newest version are not using the full URL that I provided.

**Comment by yishaigalatzer** [comment] 2016-04-13 14:52
Does the token represent a feed or authentication?

**Comment by maartenba** [comment] 2016-04-13 14:56
@kmcclive Are you on the 2.7 version of NuGet server? If so, this one may not support the "by id" queries that the latest NuGet client executes (see release notes for the one breaking change). An update to NuGet.Server vLatest may be worth looking into.

Would you happen to have the custom 403 code at hand?

**Comment by kmcclive** [comment] 2016-04-13 14:58
@yishaigalatzer The token is a form of authentication.  We have a database table in which a GUID is assigned to every user.  If the token (GUID) provided is not found in the database, a 403 error is returned.

**Comment by yishaigalatzer** [comment] 2016-04-13 15:06
And how does a user enter it? As part of the feed URL?

**Comment by kmcclive** [comment] 2016-04-13 15:07
@maartenba In the MapRoutes method of the static NuGetRoutes class, I have the following code:

```
Route oAuthRoute = new Route("{access_token}/{*pathInfo}",
    new NuGetRouteHandler(serviceRoute));

RouteTable.Routes.Add(null, oAuthRoute);
```

In the GetHttpHandler of the NuGetRouteHandler class, the code looks like this:

```
string token = requestContext.RouteData.Values["access_token"] as string;

if ((token == null) || !UserRepository.ValidateToken(token))
{
    requestContext.HttpContext.Response.StatusCode = (int)HttpStatusCode.Forbidden;
    requestContext.HttpContext.Response.End();
}

requestContext.HttpContext.RewritePath(
            String.Format("~/nuget/{0}", requestContext.RouteData.Values["pathInfo"]), false);

return _route.RouteHandler.GetHttpHandler(requestContext);
```

**Comment by kmcclive** [comment] 2016-04-13 15:09
@yishaigalatzer That is correct.  When they add a package source, they include the token in the URL.

**Comment by maartenba** [comment] 2016-04-13 15:16
Hmmm could you check the output of the feed? It may be that the "rewritepath" causes the server to strip out the token in its response body, and thus directs the client to an unauthorized url.

**Comment by yishaigalatzer** [comment] 2016-04-13 15:47
Exactly my thought a fiddler trace will confirm if this is right or not

**Comment by kmcclive** [comment] 2016-04-13 17:14
@maartenba The RewritePath call is supposed to strip out the token.  I tried updating my server with the latest version of the Nuget.Server package.  I can't seem to get it to work with my existing routing code.  Any ideas on what I might be doing wrong?  All the client give me is some generic "an error occurred" message and I don't see any logs on the server-side.

**Comment by kmcclive** [comment] 2016-04-13 17:24
@yishaigalatzer When you requested a fiddler trace, were you talking to me or @Kanimozhi12.  I thought you were talking to @Kanimozhi12 because you were asking about the speed, which is not something I mentioned.

**Comment by maartenba** [comment] 2016-04-13 17:46
@kmcclive Problem is the rewritepath will probably have the side effect of the OData feed no longer emitting URL's with the token you specified.

You may want to look into an old blog post of mine (http://blog.maartenballiauw.be/post/2011/05/09/Using-dynamic-WCF-service-routes.aspx) so that WCF's OData service will use the full URL (including token)

**Comment by joelverhagen** [comment] 2016-04-13 18:01
@kmcclive and @Kanimozhi12 
Fiddler traces for both scenarios would be extremely helpful. This will help us both debug the root cause and assess whether you guys are encountering the same issue.

**Comment by joelverhagen** [comment] 2016-04-13 19:16
Here is a new build with some improvements in this area. Note that this is pre-release build. Could you try this VSIX out in your own Visual Studio 2015 and see if it resolves the problem?
https://www.myget.org/F/nuget-vsix/vsix/NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b-3.4.3.841.vsix

Whether or not this build fixes your problem, I would still like to take a look at those Fiddler traces to be sure we're talking about the same problem. Thanks!

**Comment by kmcclive** [comment] 2016-04-13 23:50
@joelverhagen I didn't get a chance to generate a Fiddler trace yet, but I did try your VSIX.  It did not solve my problem.  I see that it now prompts for credentials like you suggested earlier, but that doesn't help in my case.  The only authentication we are doing is with the token in the URL.  Our users do not have credentials associated with the NuGet server.

**Comment by joelverhagen** [comment] 2016-04-13 23:53
@kmcclive, understood. We are having a hard time reproducing the issue on our end so Fiddler traces would help us out a lot. Considering there is private feed information in that trace, feel free to obfuscate the information before sending it to us via email, support@nuget.org.

**Comment by kmcclive** [comment] 2016-04-14 15:34
@joelverhagen I sent a Fiddler trace to the email address you provided.

**Comment by joelverhagen** [comment] 2016-04-14 15:48
Received. Thanks @kmcclive. We'll response back on this issue when we know more.

**Comment by joelverhagen** [comment] 2016-04-15 22:32
@kmcclive, we've applied a fix and produced a prerelease build of the Visual Studio 2015 extension:
https://www.myget.org/F/nuget-vsix/vsix/NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b-3.4.3.846.vsix

Please let us know if this resolves your issue.

**Comment by kmcclive** [comment] 2016-04-15 22:38
@joelverhagen Now I'm a little confused.  I thought I was supposed to change something on the server-side.

**Comment by yishaigalatzer** [comment] 2016-04-15 22:41
We decided to allow for your server to work as is :)

**Comment by kmcclive** [comment] 2016-04-15 22:43
Wow! Thanks. I'll give it a try.

**Comment by kmcclive** [comment] 2016-04-15 23:02
@joelverhagen Yes, that resolves my issue.  Do you have an estimate as to when it will be released?  Thanks.

**Comment by joelverhagen** [comment] 2016-04-15 23:06
We hope to release this VSIX early next week, however we are doing a verification pass to detect any regressions. This may change the schedule if any major issues are found.

**Comment by kmcclive** [comment] 2016-04-15 23:07
Sounds good.  Thanks.

**Closed as completed** 2016-04-15 23:21 UTC
Labels: Priority:1, Product:VS.Client, Type:Bug

**Comment by joelverhagen** [comment] 2016-04-15 23:37
Fixed with:
https://github.com/NuGet/NuGet.Client/commit/00049f027d3eb049ed96317980ae73adeffcf992

**Comment by Kanimozhi12** [comment] 2016-04-18 11:09
I have mailed the fiddler trace to support@nuget.org. the latest VSIX are not working for me

**Comment by joelverhagen** [comment] 2016-04-18 15:31
@Kanimozhi12, thanks for sending the Fiddler traces. This is a different issue from the one that @kmcclive is encountering. In @Kanimozhi12's case, it looks to me like an HTTP request was rejected by a corporate internet filtering system.

A request was made to get information about the `Microsoft.Own.Security.Facebook` package. The response that came back was `403 Forbidden` with the content body mentioning Dell SonicWALL and `This site has been blocked by the network administrator.`. Could it be that your local network has a policy blocking the `facebook` keyword?

**Comment by Kanimozhi12** [comment] 2016-04-19 09:05
@joelverhagen I have tried with the network in which facebook is not blocked, It also produces the error. mailed the fiddler trace.

**Comment by Kanimozhi12** [comment] 2016-04-21 04:18
Hi ,

Any updates on this?

**Comment by Kanimozhi12** [comment] 2016-06-08 05:10
Hi,

Still am getting the same error message! Is there any updates? Will it be fixed ?

**Comment by joelverhagen** [comment] 2016-06-08 15:43
Thanks for providing this information. It looks like the latest Fiddler trace sent to us has a bunch of HTTP 502 errors:

```
HTTP/1.1 502 Fiddler - Connection Failed
Date: Tue, 19 Apr 2016 08:58:08 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, must-revalidate
Timestamp: 14:28:08.752

[Fiddler] The connection to 'nuget.syncfusion.com' failed. 
Error: TimedOut (0x274c). 
System.Net.Sockets.SocketException A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.121.87.161:80
```

This looks like there was a connectivity issue to the source since Fiddler is reporting that 40.121.87.161 (which is what nuget.syncfusion.com is resolving to) is not responding. Additional, this seems to be an issue unrelated to the HTTP 403 originally reported.

As a side note, we have some plans in the works (not yet implemented) for dealing with sources that have regular connectivity issues: https://github.com/NuGet/Home/issues/1627

Could you provide a list of steps we could follow on our end to reproduce this issue? Also, do any other sources have similar behavior? Based on the Fiddler traces, it seems that the source itself is having problems (however it's hard to tell without more context).
