### ISSUE TITLE
Project with TFS does not load packages in vs 2015

### ISSUE THREAD

**Issue by gabriel-sk-dev** [NuGet/Home#1205] opened 2015-08-18 00:16 UTC
1) We create a project in vs2015 with tfs and perform a checkin in solution.

2) When someone pulls the solution packages are not loaded. Even performing the build packages are not restored.

3) We try to uninstall and reinstall the packages in the project. Uninstalling went smoothly. But the re-installation does not work.
We received the following message: 
"Package 'EntityFramework.6.1.3' already exists in folder 'D:\STI\Projetos VS2010\STI.TesteTFS\Trunk\packages'
Install failed. Rolling back..."

We try to carry out the process again on another machine, but instead of uninstalling the package, we conducted a "Update-Package -Reinstall"
And de error is:
Attempting to gather dependencies information for multiple packages with respect to project 'STI.TesteTFS', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Removed package 'EntityFramework 6.1.3' from 'packages.config'
Successfully uninstalled 'EntityFramework 6.1.3' from STI.TesteTFS
Package 'EntityFramework.6.1.3' already exists in folder 'D:\STI\Projetos VS2010\STI.TesteTFS\Trunk\packages'
Install failed. Rolling back...
Package 'EntityFramework 6.1.3' does not exist in project 'STI.TesteTFS'
Package 'EntityFramework 6.1.3' already exists in folder 'D:\STI\Projetos VS2010\STI.TesteTFS\Trunk\packages'

Any suggestion? Someone with a similar problem?

Ps>We create a project in vs2013 and worked properly. Only projects created in vs2015 have this problem.

Thanks .....

**Comment by yishaigalatzer** [comment] 2015-08-18 20:11
This is a bug we fixed in 3.2, the root cause is that the .nupkg files gets checked in (wrong) and we ignore the setting to avoid source control integration (wrong).

Both these issues are fixed in 3.2

Current workaround: Delete the content of the packages folder completely.

General suggestion - Avoid checking in packages.

Closing this bug - If this doesn't resolve your issue, feel free to continue to comment or re-open the issue

**Closed as completed by yishaigalatzer** 2015-08-18 20:11 UTC
Labels: Resolution:Duplicate
