### ISSUE TITLE
[Bug]: error NU1605: Detected package downgrade with `.NETCoreApp` and `.NETFramework` 

### ISSUE THREAD

**Issue by rstm-sf** [NuGet/Home#11040] opened 2021-07-18 08:30 UTC
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

```ps1
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. `dotnet new -i Avalonia.Templates`
2. `dotnet new avalonia.app -o Test`
3. Change Test.csproj
```diff
 <Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
     <OutputType>WinExe</OutputType>
-    <TargetFrameworks>net5.0</TargetFrameworks>
+    <TargetFrameworks>net5.0;net461</TargetFrameworks>
     <Nullable>enable</Nullable>
   </PropertyGroup>
   <ItemGroup>
     <PackageReference Include="Avalonia" Version="0.10.3" />
     <PackageReference Include="Avalonia.Desktop" Version="0.10.3" />
     <PackageReference Include="Avalonia.Diagnostics" Version="0.10.3" />
+    <PackageReference Include="Avalonia.Direct2D1" Version="0.10.3" />
   </ItemGroup>
 </Project>
```
4. `dotnet restore` and see errors

**Workarounds**
1.
```diff
 <Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
     <OutputType>WinExe</OutputType>
     <TargetFrameworks>net5.0;net461</TargetFrameworks>
     <Nullable>enable</Nullable>
   </PropertyGroup>
   <ItemGroup>
     <PackageReference Include="Avalonia" Version="0.10.3" />
     <PackageReference Include="Avalonia.Desktop" Version="0.10.3" />
     <PackageReference Include="Avalonia.Diagnostics" Version="0.10.3" />
     <PackageReference Include="Avalonia.Direct2D1" Version="0.10.3" />
+    <PackageReference Include="System.Buffers" Version="4.4.0" />
+    <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
+    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
+    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
+    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
   </ItemGroup>
 </Project>
```

2.
```diff
 <Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
     <OutputType>WinExe</OutputType>
     <TargetFrameworks>net5.0;net461</TargetFrameworks>
     <Nullable>enable</Nullable>
   </PropertyGroup>
   <ItemGroup>
     <PackageReference Include="Avalonia" Version="0.10.3" />
     <PackageReference Include="Avalonia.Desktop" Version="0.10.3" />
     <PackageReference Include="Avalonia.Diagnostics" Version="0.10.3" />
-    <PackageReference Include="Avalonia.Direct2D1" Version="0.10.3" />
   </ItemGroup>
+  <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' ">
+    <PackageReference Include="Avalonia.Direct2D1" Version="0.10.3" />
+  </ItemGroup>
 </Project>
```

**Additional**

It also doesn't work if we use
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net5.0;net461</TargetFrameworks>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.3" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.3" />
    <PackageReference Include="Avalonia.Diagnostics" Version="0.10.3" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETCoreApp' ">
    <PackageReference Include="Avalonia.Direct2D1" Version="0.10.3" />
  </ItemGroup>
</Project>
```

**Comment by zkat** [comment] 2021-07-26 23:44
This is... pretty strange. Here's an example error I'm getting:
```
C:\Users\kmarchan\src\nu1605-test\nu1605-test.csproj : error NU1605: Detected package downgrade: System.Buffers from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.
C:\Users\kmarchan\src\nu1605-test\nu1605-test.csproj : error NU1605:  nu1605-test -> Avalonia.Direct2D1 0.10.3 -> SharpDX 4.0.1 -> Microsoft.NETCore.App 1.0.5 -> System.Diagnostics.Process 4.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Buffers (>= 4.3.0)
C:\Users\kmarchan\src\nu1605-test\nu1605-test.csproj : error NU1605:  nu1605-test -> Avalonia.Direct2D1 0.10.3 -> SharpDX 4.0.1 -> Microsoft.NETCore.App 1.0.5 -> System.Buffers (>= 4.0.0)
```

As you can see, there's definitely overlap between System.Buffers (>=4.3.0) and (>=4.0.0), so 4.3.0 can be selected compatibly. My understanding is that our resolver _should_ be doing this work already. If this isn't the case, then I would consider this a bug.

I'm concerned that our telemetry representing this as a NU1605 might be pointing us to overestimate how much 1605 is a "fundamental" issue.

/cc @nkolev92 have you seen this before? Do you have any idea why it's happening?

@rstm-sf in the meantime, your "workaround" is exactly what you'd be doing if this is/were a legitimate 1605, so I think you'll want to keep doing that for the foreseeable. Actually fixing this might take a hot second :)

**Comment by nkolev92** [comment] 2021-08-04 00:53
Duplicate of https://github.com/NuGet/Home/issues/3541. 

The issue is detecting the downgrades through packages that are brought in by runtime.json. 

Packages such as `Microsoft.NETCore.App` are not really meant to be referenced, and should be removed. 

At this point, runtime.json is not really used among new packages.

**Closed as completed by nkolev92** 2021-08-04 00:53 UTC
Labels: Type:Bug, Functionality:Restore
