### ISSUE TITLE
Failed to "Manage NuGet Packages..." for "Provide value on 'System.Windows.StaticResourceExtension' threw an exception."

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5232] opened 2017-05-15 22:35 UTC
_From @MiaomiaoHuangfu on May 15, 2017 8:4_

For a project, right click the project or right click "Dependencies", click "Manage NuGet Packages...", then prompt a window "Provide value on 'System.Windows.StaticResourceExtension' threw an exception."
![failedtomanagenugetrestore](https://cloud.githubusercontent.com/assets/22901391/26047843/5fe3e4ec-3987-11e7-9410-17f643085cc1.PNG)
 close the .sln and reopen it, the issue is still repro.

Test on d15prerel.26512.05
OS: Windows 10

_Copied from original issue: dotnet/project-system#2171_

**Comment by alpaix** [comment] 2017-05-16 00:40
@MiaomiaoHuangfu Will you be able to submit a feedback ticket via Visual Studio Report-a-Problem tool at the top right corner? It provides a method of recording steps. This'd give us more of relevant context data to investigate.

**Comment by MiaomiaoHuangfu** [comment] 2017-05-16 02:39
@alpaix, thank you for your idea. 
I have submitted a feedback ticket.

**Comment by alpaix** [comment] 2017-05-17 20:06
Thank you for reporting this issue. We were able to root cause the problem. Fix is in-progress.

**Closed as completed** 2017-05-17 21:36 UTC
Labels: Product:VS.Client, Type:Bug, Functionality:VisualStudioUI

**Comment by rahulpaw** [comment] 2017-05-25 09:12
Is this change expected to be shipped with VS? which build is expected to have it?

**Comment by alpaix** [comment] 2017-05-25 18:41
Will be shipped with upcoming Visual Studio 2017 Preview version 15.3 at https://www.visualstudio.com/vs/preview/.

**Comment by davkean** [comment] 2017-05-25 21:25
Which actual build is this fixed in?

Sent from my Windows 10 phone

**Comment by rrelyea** [comment] 2017-05-25 21:29
A recent VS change removed something that we were depending on, causing this problem.
We have not yet inserted a fix with NuGet.Tools.vsix that fixes this.
We are trying to insert today, if we can get validation clean.
@rohit21agrawal - can you please reply with the branch and build, once the insertion works.
