### ISSUE TITLE
dotnet-restore should accept --configuration

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5421] opened 2017-06-16 01:42 UTC
_From @anoordende on June 15, 2017 23:45_

## Steps to reproduce
Build a project that selects packages based on configuration:

~~~~
    <ItemGroup Condition="'$(Configuration)'=='Debug'">
        <PackageReference Include="Some.Fantastic.Package" Version="1.0.0-dev*" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)'=='Release'">
        <PackageReference Include="Some.Fantastic.Package" Version="1.0.0-master*" />
    </ItemGroup>
~~~~

## Expected  behavior
When using dotnet restore with --configuration specified, it restores the correct package, especially now MSBuild does support this (and so does VS2017)

## Actual behavior
It doesn't, because the --configuration flag cannot be specified.

## Environment data
~~~~
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
~~~~

_Copied from original issue: dotnet/cli#6894_

**Comment by livarcocc** [comment] 2017-06-16 01:44
I disagree here. I think that your restore should not really be conditioned on any msbuild properties. I can see you needing to specify nuget config, like NuGet.Config or additional package sources. But everything else, should be restored by default in your project. If you depend on properties to be passed, this won't work in VS, for instance, where you can not pass any of these values to restore there.

cc @nguerrera @emgarten @rrelyea since we were talking about this this week.

**Comment by anoordende** [comment] 2017-06-16 14:00
Actually it works rather well in VS2017, if you don't mind restarting the solution. But that's besides the point, this is an extremely powerful feature in CI/CD workflows. Properties are an intrinsic part of MSBuild and therefore /t:restore happily abides.

All I'm asking for is for this to be exposed in dotnet-restore, but maybe I'm missing the point and it is going to be a complicated issue :)

> I think that your restore should not really be conditioned on any msbuild properties

Sorry but I disagree, we can't dictate what one can do with MSBuild in csproj.

This is an [interesting article](http://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html#fine-control-over-dependencies-and-content-flow) that reads:

> With the existing features of MSBuild, you can conditionally reference a NuGet package. This allows you to choose package references per target framework, **configuration**, platform, or other pivots.

**Comment by nguerrera** [comment] 2017-06-16 14:33
Consider that the assets file, unlike most other artifacts, has the same location between configurations. This means a high risk of crossing the wires between debug and release if the assets file changes between them. That article should be updated to not encourage switching assets based on configuration IMHO.

> we can't dictate what one can do with MSBuild in csproj.

You can pass /p:Configuration if you want and understand the risks. The only question is whether we encourage it or not via shorthand syntax and I don't think that we should. It would give the impression that you must re-restore when switching configurations, which is not the common case.

**Comment by anoordende** [comment] 2017-06-17 00:38
What do you mean by assets file?

**Comment by emgarten** [comment] 2017-06-17 03:12
> What do you mean by assets file?

`obj\project.assets.json` is where restore writes output. Currently this file supports multiple target frameworks, but not multiple configurations or combinations of other msbuild input properties.

**Comment by nkolev92** [comment] 2018-06-25 07:10
Duplicate of https://github.com/NuGet/Home/issues/5895. 

As indicated in that issue. 

`TargetFramework` is the only support condition allowed for `PackageReference` items.

To work with other conditions you will need to handle them yourself by passing the extra property values to restore, and ensuring that restore is done appropriately before each build.

**Closed as completed by nkolev92** 2018-06-25 07:10 UTC
Labels: Resolution:Duplicate, Priority:2, Type:DCR, Functionality:Restore
