### ISSUE TITLE
Nuget PMUI throws StreamJsonRPC exception

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10070] opened 2020-09-25 22:22 UTC
## Detailed repro steps so we can see the same problem
Not sure if it's regression.

1. Open Nuget.Client source code in VS
2. Install Text2Xml(v 1.1.0) package into all projects.
3. Try to downgrade Text2Xml(v 1.0.1) version.
![Error1.PNG](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/eef97020-4a36-4d02-b443-feeb6a8835ef)

Related issues: 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1218071
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1216957

**Comment by erdembayar** [comment] 2020-09-29 03:14
I found line detecting this error:
https://github.com/NuGet/NuGet.Client/blob/4e671943172ccab55e594e665d67f6aa12dfbeea/src/NuGet.Clients/NuGet.PackageManagement.UI/Actions/UIActionEngine.cs#L433
https://github.com/NuGet/NuGet.Client/blob/4e671943172ccab55e594e665d67f6aa12dfbeea/src/NuGet.Clients/NuGet.PackageManagement.UI/Actions/UIActionEngine.cs#L463
![image](https://user-images.githubusercontent.com/8766776/94511704-004f7f00-01cf-11eb-9d02-f92470b34204.png)

Actual source for this exception was here: 
https://github.com/NuGet/NuGet.Client/blob/44f1096f584a949a9acd68b7f1057e9ee2b54dc3/src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs#L3118


![image](https://user-images.githubusercontent.com/8766776/94508288-7b606780-01c6-11eb-81ad-3c91b599d4e6.png)

It was just normal NU1605 errors but somehow when it bubble up it got extra message about StreamJsonRpc. 
Here I think this NU1605 is expected error because I am not downgrading bottom child project, it's some middle/parent project.

**Comment by dtivel** [comment] 2020-09-29 15:30
The "Value cannot be null" exception is not something I'm familiar with.  You can investigate/raise that issue separately from this issue.

This issue is about a duplicate error which has "StreamJsonRpc" and a callstack added to it.  This is a dupe of https://github.com/NuGet/Home/issues/10034.

**Comment by nkolev92** [comment] 2020-09-30 22:00
Consolidating, closing as dup of https://github.com/NuGet/Home/issues/10034.

**Closed as completed by nkolev92** 2020-09-30 22:00 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug
