### ISSUE TITLE
nuget pack does not include the `PackageIcon`

### ISSUE THREAD

**Issue by 0xced** [NuGet/Home#8610] opened 2019-09-19 15:30 UTC
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 5.3.0.6192

OS version: Microsoft Windows 10 Enterprise 10.0.14393

Worked before? Not applicable, this is new feature of [NuGet 5.3](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.3)

## Detailed repro steps so we can see the same problem

1. Clone https://github.com/NuGet/Samples/
2. Run `dotnet build PackageIconExample\PackageIconExample.csproj`
3. Run `nuget pack PackageIconExample\PackageIconExample.csproj`

The nupkg produced by the `dotnet build` command includes the icon.png.
The nupkg produced by the `nuget pack` command does **not** include the icon.png file.

I'd like to have it working with the `nuget` command instead of the `dotnet` command because I am building on TeamCity and installing several versions of the NuGet.exe tool is easy and also because I don't want to install preview or release candidate versions of .NET Core on the TeamCity build agent.

Am I missing an argument when running the `nuget` command? Is this a bug?

### Verbose Logs

```
nuget pack PackageIconExample\PackageIconExample.csproj -Verbosity detailed
NuGet Version: 5.3.0.6192
Attempting to build package from 'PackageIconExample.csproj'.
MSBuild auto-detection: using msbuild version '16.2.37902.0' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'c:\Projects\GitHub\NuGet.Samples\PackageIconExample\bin\Debug\netstandard2.0'.
Add file 'c:\Projects\GitHub\NuGet.Samples\PackageIconExample\bin\Debug\netstandard2.0\PackageIconExample.dll' to package as 'lib\netstandard2.0\PackageIconExample.dll'
WARNING: NU5115: Description was not specified. Using 'Description'.

Id: PackageIconExample
Version: 1.0.2
Authors: PackageIconExample
Description: Description
Dependencies:

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'lib/netstandard2.0/PackageIconExample.dll'.
Added file 'package/services/metadata/core-properties/253485c7be254c2eb4546d4b6dd61b19.psmdcp'.
Added file 'PackageIconExample.nuspec'.

Successfully created package 'c:\Projects\GitHub\NuGet.Samples\PackageIconExample.1.0.2.nupkg'.
WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
- Add a dependency group for .NETStandard2.0 to the nuspec
````

**Comment by zkat** [comment] 2019-09-19 17:25
Closing as a duplicate of https://github.com/NuGet/Home/issues/4491. Thanks @nkolev92 for calling this out.

**Closed as completed by zkat** 2019-09-19 17:25 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Pack

**Comment by 0xced** [comment] 2019-09-20 06:48
Thanks for the quick reply. I think #7778 should really be prioritized as it looks like many people were mislead thinking that nuget pack would work with csproj files.
