### ISSUE TITLE
Unhelpful error message for bad nuget config

### ISSUE THREAD

**Issue by ryanbrandenburg** [NuGet/Home#2095] opened 2016-02-10 19:17 UTC
If you have a package source which doesn't exist the error message you get is `error: Unexpected character encountered while parsing value: <. Path '', line 2, position 1.`. This is misleading about where you should be looking for your mistake, implying that it's a formatting problem rather than a data problem.

**Comment by csharpfritz** [comment] 2016-02-10 19:26
Can you give us some additional details about where you saw this error message?  Which client (exe, Visual Studio) and which version were you using?

**Comment by yishaigalatzer** [comment] 2016-02-10 19:40
Thanks for reporting it, we encountered it in the past and this was already fixed in 3.4. You will get the same error message, prefixed with what nuget.config file the problem is in.

**Closed as completed by yishaigalatzer** 2016-02-10 19:40 UTC
Labels: Resolution:Duplicate
