### ISSUE TITLE
Better handling on unexpected error cases on the client side

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9352] opened 2020-03-27 18:34 UTC
For diagnostics purposes, it's easier now if use the activity log. We should use the file and forget method in the future.

**Comment by nkolev92** [comment] 2020-05-04 20:25
@rrelyea I've unassigned this from myself :)

**Comment by rrelyea** [comment] 2020-10-21 22:34
dupe of #10168

**Closed as completed by rrelyea** 2020-10-21 22:34 UTC
Labels: Resolution:Duplicate, Area:ErrorHandling
