### ISSUE TITLE
Update All Button Missing in VS 2015

### ISSUE THREAD

**Issue by Dynkan** [NuGet/Home#1065] opened 2015-07-29 20:23 UTC
Please bring back the 'Update All' button in 2015 that updates all the dependencies with a single click.

**Comment by yishaigalatzer** [comment] 2015-07-30 20:55
Thanks for reporting it, this is a duplicate of #142 
We run out of time for Visual Studio 2015, and we will bring it back.

In the meantime you can use the powershell console - type `UpdatePackage` in the powershell console and you will get the same experience

**Closed by yishaigalatzer** 2015-07-30 20:55 UTC
