### ISSUE TITLE
VS2015 Enterprise nuget version 3.2 fails on metadata download

### ISSUE THREAD

**Issue by uchinago** [NuGet/Home#1474] opened 2015-09-28 16:04 UTC
Using both the GUI and the command console I get the following error in 2015
From the Console:
Find-Package : Failed to retrieve metadata from source 'https://api-v3search-2.azurewebsites.net/query?q=&skip=0&take=20&prerelease=false'.
At line:1 char:1
From the Extension:
Error occured:\nFailed to retrieve metadata from source 'https://api-v3search-2.azurewebsites.net/query?q=&skip=0&take=26&prerelease=false&supportedFramework=UAP,Version=v10.0'.

However, I can put these both in a browser (IE or Chrome) and it returns a JSON object.

https://api-v3search-2.azurewebsites.net/query?q=&skip=0&take=20&prerelease=false

**Comment by yishaigalatzer** [comment] 2015-09-28 19:51
Can you provide some more details to what is that you are trying to do? What command, what steps?

**Comment by uchinago** [comment] 2015-09-28 21:01
From Visual Studio: 
    I am right clicking on the project and going to "Manage Nuget Packages
From Command just typing 
  Find-Package

Not  trying to do anything fancy.  Just simple  Apparently I cannot upload an image.

**Comment by yishaigalatzer** [comment] 2015-09-28 21:04
Any resason you closed the issue?

**Comment by uchinago** [comment] 2015-09-29 12:47
No... it is still issue..

**Comment by yishaigalatzer** [comment] 2015-10-01 02:12
Do other online connections work for you (like extensions and updates)?

**Comment by yishaigalatzer** [comment] 2015-10-06 16:33
bump

@xavierdecoster please take a closer look

**Comment by xavierdecoster** [comment] 2015-10-07 10:55
@uchinago can you please provide the following information to help us reproduce this issue?
- NuGet version (if not the latest, please upgrade)
- The active package source URL (the selected one in the dropdown)

I haven't been able to repro this issue so far.

**Comment by xavierdecoster** [comment] 2015-10-15 15:45
@uchinago closing as unable to reproduce. feel free to reply with more information if you still hit this issue.

**Comment by mgmoody42** [comment] 2016-06-02 16:36
This has reappeared in a different version (3.4.3 is the currently installed, but bug was present in preceeding 1-2 versions).

Symptoms include:
1. I cannot browse package library from 'Manage Nuget packages' from project or solution
2. I do get indication of package updates and can apply them
3. I cannot browse package library from Nuget console with Find-Package
4. I can install packages from Nuget console, provided I already know the full name and version I need which usually means I have to search nuget.org in a browser to locate them first.

Note: Nuget in VS2013 still works

**Comment by yishaigalatzer** [comment] 2016-06-02 16:42
@mgmoody42 can you give us more details? What sources are you using (share your nuget.config if you can), tell us about your network configuration (do you have a proxy of firewall). Do you have a private server you are trying to reach out to?

**Comment by yishaigalatzer** [comment] 2016-06-02 16:42
CC @rrelyea

**Comment by mgmoody42** [comment] 2016-06-02 17:01
I know we use Bluecoat. It seems to be blocking https://api-v3search-0.nuget.org/query?q=&skip=0&take=26&prerelease=false&supportedFramework=.NETFramework,Version=v4.5.2
but I can browse the URI without issue and receive the json payload.
The config file is the standard issue, nothing changed there.

[NuGet.Config.txt](https://github.com/NuGet/Home/files/296104/NuGet.Config.txt)

**Comment by mgmoody42** [comment] 2016-06-02 18:16
Additionally, I get the same result if I run VS2015 as administrator.

**Comment by alpaix** [comment] 2016-06-02 19:42
@mgmoody42 Do you see any error message in output window? Can you share a screenshot of the package manager UI window displaying the error?

**Comment by rrelyea** [comment] 2016-06-03 16:25
@mgmoody42  - can you capture http traces via fiddler and give to us?

**Comment by yishaigalatzer** [comment] 2016-06-03 16:38
Please show both traces from 2013 and 2015. If you are concerned with privacy send them to support@nuget.org

**Comment by rrelyea** [comment] 2016-06-06 19:38
@mgmoody42  - we are moving to a later release because we don't have anything actionable yet. please let us know when you can follow up on the fiddler traces. we'd love to get to the bottom of this.

**Comment by vfrank66** [comment] 2016-07-14 04:38
I have no idea if I have what your asking but this is what it looks like on my machine VS2015 Preview 3, Nuget Package Manager 3.4.2. Let me know if there is any more info that would be helpful.

![nuget-fail](https://cloud.githubusercontent.com/assets/7524999/16828132/ad3cc86a-4952-11e6-980b-d20c370ffa04.PNG)

**Comment by vfrank66** [comment] 2016-07-14 04:46
Oh github does not allow .saz files: https://drive.google.com/open?id=0B9aAzxUiqEgaZUpnbVVMekVwbUk

**Comment by yishaigalatzer** [comment] 2016-07-14 04:52
Victor the current release is 3.4.4 can you please update ?

**Comment by nkolev92** [comment] 2018-01-10 22:48
Thank you for filing this issue. 
We have not been able to reproduce the issue or get something actionable. 

Please upgrade to the latest VS 2017 version and open another issue if you're still encountering this problem.

**Closed as completed by nkolev92** 2018-01-10 22:48 UTC
Labels: Priority:2, Type:Bug

**Comment by docustream-github** [comment] 2020-11-11 06:39
Death by will-not-fix.
