### ISSUE TITLE
NuGet Upgrades require administrator access to install

### ISSUE THREAD

**Issue by chekm8** [NuGet/Home#764] opened 2015-06-11 13:32 UTC
When attempting to upgrade NuGet Package Manager from within Visual Studio we have always had this issue where you must be an administrator on the machine in order to install the upgrade.  I work in a restricted environment where we do not have admin access to the laptops and it would be great if we could get this working for a normal user.  This issue happens on all of our laptops, not just one, is reproducible and occurs on VS 2013 and also occurred in 2012.  

Here is what we have observed:
1)	In Visual Studio navigate to the Extension and Updates for Visual Studio Gallery
2)	Choose to upgrade Nuget Package Manager for Visual Studio 2013
3)	The download proceeds and completes
4)	The Windows 7 User Access Control (UAC ) prompt appears.  
5a)    If we enter credentials for a non admin account in the UAC prompt it accepts the credentials and the VSIXInstaller.exe process starts and gets caught in an infinite loop of spawning VSIXInstaller.exe processes using up all the memory on the machine and effectively causing a DOS attack.  The only way out of the loop is to hard boot the laptop or try to log off Windows quickly before the memory is consumed.  You cannot kill the processes in task manager they just respawn.
5b)   If we use an account with admin access the install proceeds and completes.

My guess is that NuGet is placed in some restricted area or accessing some Registry keys possibly from the VSIX.  

It’s not a problem with all VSIX as we are able to install other tooling (e.g. TFS Source Control Explorer, Team Foundation Sidekicks, etc.) without admin access.

**Comment by joeloff** [comment] 2015-06-11 19:52
NuGet is a machine wide installation and since it ships as an MSI it needs administrative privileges. The MSI does a bit more than just a VSIX as it also writes registry keys, something a VSIX cannot do.

Could you perhaps share the VSIX logs from the machine. They should be in the %temp% folder of the user that performed the installation and have a name such as VSIXInstaller_3b4c72a3-82cf-42e2-9af9-c982648b28c0.log

The behavior of the VSIXInstaller is not correct from what you describe and the logs might shed some light as to why it's getting tied up in a loop.

Can you also confirm the exact VS version (and update)? Help/About should show that information.

**Comment by chekm8** [comment] 2015-06-12 18:38
It would be great if you could place the Items related to the Nuget Install in locations where a non admin could update.  I get that you might need to prime the pump with the initial install from Visual Studio which would require admin rights to set up some things but, if it could be maintained without admin rights that would be a huge benefit/time saver.

My current VS version is: 12.0.30723.00 / Update 3 but, like I said this was the same behavior on VS 2012.

I reviewed the log files and there are a ton (1000)+ of them from performing the install one time,  most are 0KB.  The ones that have content are 1KB.  Their content is:
Microsoft.VisualStudio.ExtensionManger.RequiresAdminRightsException: You must have administratove privledges to install using the /admin switch.
at VSIXInstaller.App.RequestElevation()
VSIXInstaller.App.ProcessCommandLine(String[] commandLineArgs)
VSIXInstaller.App.OnStartUp(StartupEventArgs e)

**Comment by freakyjoe** [comment] 2015-11-16 02:05
Bump!
+1 for none-admin installs. Perhaps it is common for full time devs to have admin-rights on their systems. I work in a controlled office environment and do development every now and then.

Our systems are managed by an external service provider and having them involved every time I need to upgrade (which has to happen every time I use VS, because I use it seldomly) is at least annoying and expensive.

If I do not need admin rights to use VS, I don't want to need admin rights to use VS...

**Comment by yishaigalatzer** [comment] 2015-11-24 05:45
This change is quite large, and requires discussion with vs folks. It mostly means moving nuget from a machine wide install to a user based install, which breaks other scenarios as nuget is now a very fundamental part of almost all vs templates and scenarios, so updating nuget is similar to vs updates.

We see the pain this causes to you guys, but the side effects are significant enough that this needs more consideration, and unfortunately it is a lower priority scenario than our next immediate commitments.

**Comment by yishaigalatzer** [comment] 2015-11-24 21:47
Thanks everyone for the feedback, we "met" today over email with the visual studio extensions team, and we are cooking a feature together that might enable this scenario in the next visual studio update. 

I'll circle back when I have more insight into it.

**Comment by mihailik** [comment] 2016-01-18 10:49
A routine package upgrade (that ended with no warnings) broke the project:

`The 'System.Resources.ResourceManager 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.***.***'.` - (specific build blanked for security)

If those shiny new features in NuGet 3.1, 3.5 or whatever 5.0 lead to **standard BCL packages** being unusable in the ordinary VS2013, I worry about your business model. How many more customers do you need to acquire for every single one disappointed with the backward compatibility breaks?

**Comment by yishaigalatzer** [comment] 2016-01-18 18:21
@mihailik we don't own the decision of package owners to pick what new features the want to use and what limitations they want to place on their packages.

Specifically the BCL packages are not needed for anything in 2013, because everything should be available in the GAC.

It would be helpful if you share what new package brought that dependency, you can probably contact the package owner and figure out why this dependency got added.

Also FYI - This issue is tracking the nuget **extension**  support for updating itself without admin right, so the issue is a bit misplaced. 

Last (and more of an information really, because it doesn't affect the question) the version of nuget you are using does not reveal and security related issues.

CC @ericstj owner of the BCL packages

**Comment by mihailik** [comment] 2016-01-18 22:36
It was either Immutable Collections, or Compilers - both from Microsoft. I bet a good pint of cider 'the owners' will send me back towards NuGet with a fresh batch of cryptic lingo supposed to enlighten me on my journey :-)

The whole idea of splitting BCL into tiny crumbles delivered as independent packages -- surely it was invented in collaboration with NuGet, rather than as wild hack down at Roslyn team?

I got WPF app+libs VS2013/NET40 project;
opened it in VS2015;
changed to target NET45;
removed all Microsoft-y packages;
added them all back, to let them pick on the NET45;
opened project in VS2013
-- kaboom! Package Manager Console cries about wrong NuGet and tose pesky BCL nano-packages.

If you ask me, I say stop that nano-packaging business, get back to solid mscorlib, WindowsBase and a handful of big chunky DLLs. But that's just me. If it helps, keep splitting that hair to the atomic level, as long as it works smoothly.

Mind you, none of that trouble happens with normal external packages from 3rd parties. Don't even need to shake them into places upgrading .NET to 4.5, just work.

**Comment by yishaigalatzer** [comment] 2016-01-18 23:05
Yes they are built by Microsoft, but the nuget team does not control them. I agree with your assessment and I'll communicate it further.

**Comment by yishaigalatzer** [comment] 2016-09-15 18:14
Dev14 now allows for it, in dev15 nuget will no longer be an extension. So closing as external.

**Closed by yishaigalatzer** 2016-09-15 18:14 UTC
Labels: Type:DCR
