### ISSUE TITLE
Sometimes it pops up the modal dialog "restoring NuGets" for no apparent reason

### ISSUE THREAD

**Issue by ljw1004** [NuGet/Home#920] opened 2015-07-10 18:22 UTC
Repro (using NuGet v709)...
1.	Open a solution
2.	Build the entire solution
3.	Tweak a comment in one of the .vb files in one of the projects in that solution
4.	Build that one project
5.	Further tweak that comment
6.	Build that one project

WHAT I GET: sometimes, not always, during step 6 it pops up the modal dialog to say that it’s restoring packages. This adds 8 seconds to the build-time. I don’t know what triggers it.

Here's a video repro.
![nuget-restore-all](https://cloud.githubusercontent.com/assets/3316258/8625823/f5c94408-26f5-11e5-98c2-0bccc785be7d.gif)

**Comment by yishaigalatzer** [comment] 2015-07-14 01:53
Closing as by design. This seems to be a side effect of other new projects not done restoring yet.

**Closed by yishaigalatzer** 2015-07-14 01:53 UTC
Labels: ShipRoom Check
