### ISSUE TITLE
Copyable PackageReference

### ISSUE THREAD

**Issue by jnm2** [NuGet/Home#7306] opened 2018-09-18 15:29 UTC
I'm often on a package's NuGet.org page when I want to add it to a project, with the .csproj text editor open in VS Code or Visual Studio.

![image](https://user-images.githubusercontent.com/8040367/45698263-9a3ab680-bb35-11e8-9713-be9fa9799fe6.png)

It would be cool if there was a tab for copying `<PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.1" />` to the clipboard. Maybe the tab could be named ‘.csproj \<ItemGroup>’ or something like that?

**Comment by jainaashish** [comment] 2018-09-19 17:40
It's a NuGet server feature ask. Dupe of https://github.com/NuGet/NuGetGallery/issues/5670

**Closed as completed by jainaashish** 2018-09-19 17:40 UTC
Labels: Resolution:External
