### ISSUE TITLE
nuget.exe push timeout needs a better error message

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2503] opened 2016-04-08 20:25 UTC
```
nuget.exe push NuGetTestPackage.1.0.0.nupkg -ApiKey ... -Timeout 1
Pushing NuGetTestPackage.1.0.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package
A task was canceled.
```

"A task was canceled." should probably be "Push timeout expired." or similar.

**Comment by spadapet** [comment] 2016-04-08 21:13
Dupe of: https://github.com/NuGet/Home/issues/2199
Here's the committed pull request: https://github.com/NuGet/NuGet.Client/pull/442

**Closed as completed by spadapet** 2016-04-08 21:13 UTC
Labels: Type:Bug, Area:ErrorHandling, Functionality:Push
