### ISSUE TITLE
Error: The Package Manager Console requires PowerShell 2.0 runtime, which is not detected on this machine.

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10284] opened 2020-11-16 15:08 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Error:-The-Package-Manager-Console-requi/594211)._

---
As it seems, the issue fixed in VS 2017 still persists in VS 2019. The package manager still shows the error of a missing Powershell installation. As I am running on Windows 10, having PowerShell 5 as default, this is odd. Also: My VS2017 installation did not have the issue on the same machine and installation.

I also installed the latest PowerShell built (6.2.1) with the same result.
Powershell has been ticked in the Windows Features, as well.

---
#### Feedback Bot on 6/4/2019, 02:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/7/2019, 06:33 PM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .
#### Feedback Bot on 3/31/2020, 05:36 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### jdewane1 on 5/11/2020, 02:04 PM: 

<p>Any resolution to this issue?  I'm currently experiencing this issue in VS 2019.</p>

---
#### Kai Opitz solved on 6/5/2019, 00:59 AM, 0 votes: 

<p>As I just see, the problem can be worked around, if you start Visual Studio as administrator. As this was not needed in VS 2017, I suspect a different handling of user rights in the new version.</p><p>But as said, this should only be a work around, not a real solution.</p>

**Comment by zkat** [comment] 2020-11-23 21:49
@v-luzh are you able to reproduce this by any chance? I suspect there's something wrong with the system installation of pwsh itself and/or VS, which is beyond our control, and they'd need to just reinstall everything from scratch (using the latest version, too)

**Comment by nkolev92** [comment] 2020-12-07 21:36
Can you please try to repro this issue? @v-luzh

**Comment by v-luzh** [comment] 2020-12-08 08:22
@nkolev92 @zkat, we cannot repro this issue on both D16.9\30803.129 and Main\30807.116. And we never saw this kind of issue before.

**Comment by zkat** [comment] 2020-12-10 18:17
Closing since we can't repro it.

**Closed as completed by zkat** 2020-12-10 18:17 UTC
Labels: Resolution:NotRepro, Product:VS.PMConsole, Triage:NeedsTriageDiscussion
