### ISSUE TITLE
MSBuild NuGet SDK Resolver fails to locate global.json file in Visual Studio project folder

### ISSUE THREAD

**Issue by sae42** [NuGet/Home#11747] opened 2022-04-14 10:31 UTC
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

Visual Studio 2022 17.2 Preview 3

### Worked before?

Visual Studio 2022 17.1 and earlier

### Impact

It's more difficult to complete my work

### Repro Steps & Context

The issue is a dotnet CLI template which contains a global.json file (in my case referencing a project SDK) which is then also used via the Visual Studio new project dialog. So the global.json file is in the same directory as the project, but in the Visual Studio case the default creation case is to create a solution folder and a project sub-folder. The project sub-folder contains the global.json file in this case. The MSBuild NuGet SDK Resolver fails to locate the global.json file in the project folder.

The issue was trigger by this [#4380](https://github.com/NuGet/NuGet.Client/pull/4380) I believe. There was a subsequent bug and a change with this [#4507](https://github.com/NuGet/NuGet.Client/pull/4507).

That secondary change almost fixes the issue for me, but unfortunately it does not handle the case when the resolver context defines both a solution and project. The existing [code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/GlobalJsonReader.cs#L100) means the solution always wins even if the project is set. The consequence is that a global.json in the project folder is not found. I believe a change to check the project file path context first would resolve this problem.

**Comment by jeffkl** [comment] 2022-04-14 15:43
At this time this is by design.  The .NET SDK resolver has always respected the solution path over the project path and we wanted to make the NuGet-based MSBuild project SDK resolver consistent.

https://github.com/dotnet/sdk/blob/1c817a47346f4db67ce3463cad7f60b54bfe122f/src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs#L91

Its only supported to have one `global.json` in the repository and it should be in the root if possible as a best practice.  Perhaps we need to update the CLI template to take this into account.

**Comment by nkolev92** [comment] 2022-04-18 20:36
Team Triage; Closing per @jeffkl's comment.

**Closed as completed by nkolev92** 2022-04-18 20:36 UTC
Labels: Type:Bug, Resolution:ByDesign, Functionality:Restore, Product:MSBuildSDKResolver
