### ISSUE TITLE
Generated NuGet.g.targets cause warnings in build

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#4422] opened 2017-01-28 01:36 UTC
With VS 2017 RC3, the generated .nuget.g.targets files create warnings in the builds. If `/warnaserrors` is enabled, this will fail a build.

Here's what I see in the build log

```
1>C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets(10,5): warning MSB4011: "C:\Users\oren\.nuget\packages\gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" cannot be imported again. It was already imported at "C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\dev\Zeroconf\Zeroconf\Zeroconf.csproj]
1>C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets(13,5): warning MSB4011: "C:\Users\oren\.nuget\packages\gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" cannot be imported again. It was already imported at "C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\dev\Zeroconf\Zeroconf\Zeroconf.csproj]
1>C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets(16,5): warning MSB4011: "C:\Users\oren\.nuget\packages\gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" cannot be imported again. It was already imported at "C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\dev\Zeroconf\Zeroconf\Zeroconf.csproj]
1>C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets(19,5): warning MSB4011: "C:\Users\oren\.nuget\packages\gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" cannot be imported again. It was already imported at "C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\dev\Zeroconf\Zeroconf\Zeroconf.csproj]
1>C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets(22,5): warning MSB4011: "C:\Users\oren\.nuget\packages\gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" cannot be imported again. It was already imported at "C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\dev\Zeroconf\Zeroconf\Zeroconf.csproj]
1>C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets(25,5): warning MSB4011: "C:\Users\oren\.nuget\packages\gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" cannot be imported again. It was already imported at "C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\dev\Zeroconf\Zeroconf\Zeroconf.csproj]
1>C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets(28,5): warning MSB4011: "C:\Users\oren\.nuget\packages\gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" cannot be imported again. It was already imported at "C:\dev\Zeroconf\Zeroconf\obj\Zeroconf.csproj.nuget.g.targets (7,5)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\dev\Zeroconf\Zeroconf\Zeroconf.csproj]

```

Here's the generated .nuget.g.targets file:
``` xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == '' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == '' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == '' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == '' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == '' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == '' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == '' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == '' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\buildCrossTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'net45' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'netstandard1.0' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'netstandard1.3' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'portable-win81+wpa81' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'uap10.0' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'win8' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'wp8' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'wpa81' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets" Condition="Exists('$(NuGetPackageRoot)gitversiontask\4.0.0-pullrequest1119-1208\build\GitVersionTask.targets')" />
  </ImportGroup>
</Project>
```

To repro:

- clone `https://github.com/onovotny/zeroconf/`
- checkout the `dev` branch
- open in VS 2017 RC3
- Build the `Zeroconf` project. VS will do NuGet restore and then the build will generate the warnings

/cc @davkean

**Comment by emgarten** [comment] 2017-01-28 05:14
Thanks for the report, this will be fixed in the next release. Dupe of https://github.com/NuGet/Home/issues/4283

**Closed as completed by emgarten** 2017-01-28 05:14 UTC
Labels: Resolution:Duplicate
