### ISSUE TITLE
nuget restore exceeding MAXPATH

### ISSUE THREAD

**Issue by nerumo** [NuGet/Home#3981] opened 2016-11-21 09:13 UTC
I use Jenkins as build server and I want to use the multi branch pipeline. This enforces Jenkins to create a unique folder name that has a random component. The finally generated path gets quite long. If I then start a package restore, the restore fails because of the MAXPATH limitation.
Since .Net 4.6.2 it's possible to use long paths, but nuget is actively preventing it. Two things that should be changed:

* add the runtime configuration for long path to the .config file (https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/)
* remove the MAXPATH check from the nuget client code

**Comment by nkolev92** [comment] 2017-10-17 23:43
Duplicate of https://github.com/NuGet/Home/issues/3324

**Closed as completed by nkolev92** 2017-10-17 23:43 UTC
Labels: Resolution:Duplicate, Functionality:Restore, Functionality:Install
