### ISSUE TITLE
[CPVM] NU1011 should not be raised for GlobalPackageReferences

### ISSUE THREAD

**Issue by benjamin-hodgson** [NuGet/Home#12363] opened 2023-01-13 17:34 UTC
### NuGet Product(s) Affected

NuGet SDK

### Current Behavior

`GlobalPackageReference`s are not allowed to have a floating version. For example,

```xml
<GlobalPackageReference Include="StyleCop.Analyzers" Version="1.1.*" />
```

produces "NU1011: Centrally defined floating package versions are not allowed".

I understand [why this diagnostic exists](https://github.com/NuGet/Home/issues/9384#issuecomment-665202275), but I think it should not apply to `GlobalPackageReference`s by default.

* `GlobalPackageReference` is generally used for build dependencies such as analysers and SDKs. Such dependencies are usually not intended to be brought along transitively, so the NU1608 error is less likely to occur.
* `GlobalPackageReference`s are more likely to be used with a floating version in the first place, in my opinion. In my scenario, I'm maintaining a handful of libraries which use a shared package (also maintained by me) of build scripts and analyser configurations, so that I don't have to duplicate `props` and `globalconfig` settings across a bunch of repositories. I'd like to use a floating version for that shared package so that I can make adjustments to the build scripts and not have to update all of the dependent repositories.

(For what it's worth, I think there are cases other than `GlobalPackageReference` where these arguments apply, too, such as test frameworks. Personally I'd be happiest if there were an escape hatch to opt out of NU1011 - like `<AllowFloatingCentralPackageVersions_IKnowWhatImDoing>true</AllowFloatingCentralPackageVersions_IKnowWhatImDoing>`, haha)

### Desired Behavior

`GlobalPackageReference`s should not be subjected to the NU1011 rule forbidding floating centrally defined versions

**Comment by jeffkl** [comment] 2023-01-13 21:49
Closing as duplicate of https://github.com/NuGet/Home/issues/9384

**Closed as not planned by jeffkl** 2023-01-13 21:49 UTC
Labels: Resolution:Duplicate, Type:DCR, Area:RestoreCPM
