### ISSUE TITLE
[Bug]: NuGet.Client TopologicalSortUtility Retrieves Dependencies From Wrong Location

### ISSUE THREAD

**Issue by 7enderhead** [NuGet/Home#11513] opened 2022-01-17 18:55 UTC
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.ProjectModel 6.0.0

### Worked before?

don't know

### Impact

I'm unable to use this version

### Repro Steps & Context

- NuGet.ProjectModel.DependencyGraphSpec provides static method SortPackagesByDependencyOrder
- this in turn uses NuGet.Packaging.TopologicalSortUtility
- method CalculateRelationships retrieves a package's dependencies via PackageInfo.Package.Dependencies (line 69)
- but these top-level dependencies are always empty, since dependencies are located at each target framework
- see, e.g., [https://www.jerriepelser.com/blog/analyze-dotnet-project-dependencies-part-1/](url)
- so, instead, dependencies should be collected from each target framework (see link)
- the current behaviour leads the topolocial sort utility to believe that no package has any dependencies at all, resulting in a complete arbitrary package order (which is not sorted by dependency order at all)

**Comment by erdembayar** [comment] 2022-01-20 19:37
@7enderhead 
Thank you for filing this issue, it could be possible issue. I can take a look in next week. Do you have repro project having issue because of this? If yes, could you be able upload or send to me? It'll make my Investigaton easier.

**Comment by erdembayar** [comment] 2022-02-05 00:15
@7enderhead 
I was not able to repro issue you reported. Could you be able to share actual repro with us?
It looks you're following this tutorial to learn about `nuget`.

I used below csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
		<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>
    <RootNamespace>_11513</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NuGet.Core" Version="2.13.0" />
	</ItemGroup>
  
	<ItemGroup Condition=" '$(TargetFramework)' == 'net5.0' ">
		<PackageReference Include="Text2Xml.Lib" Version="1.1.2" />
    <PackageReference Include="SharpZipLib" Version="1.3.3" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.1' ">
		<PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Autofac" Version="6.3.0" />
	</ItemGroup>
      
</Project>

```

As you can see both packages with or without specific TFM show up here for netcoreapp3.1.
![image](https://user-images.githubusercontent.com/8766776/152619377-c9bd9fb8-6604-45ff-80ce-a03fe8b96e32.png)

As you can see both packages with or without specific TFM show up here for net5.0
![image](https://user-images.githubusercontent.com/8766776/152619629-1f55b749-7a65-4153-aba7-317fa29adb87.png)

Please let us know if it's still issue.

**Comment by erdembayar** [comment] 2022-02-05 01:45
@aortiz-msft  @nkolev92 
It looks not bug. Can I close it? If new repro is supplied, then reopen this.

**Comment by erdembayar** [comment] 2022-02-14 18:58
Thank you for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Closed as completed by erdembayar** 2022-02-14 18:58 UTC
Labels: Functionality:SDK, Priority:2, Type:Bug, Triage:Investigate, Category:Quality Week
