### ISSUE TITLE
Get zero errors or warnings when a version number in a PackageReference is invalid

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5531] opened 2017-07-04 05:07 UTC
## Details about Problem
VS version (if appropriate): Version 15.3.0 Preview 4.0 [26629.0.d15rel]

## Detailed repro steps so we can see the same problem

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <GiveMeAVersion>9.0.1</GiveMeAVersion>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Newtonsoft.Json" Version=" '$(GiveMeAVersion)' " />
  </ItemGroup>
</Project>
```

## Expected:
An error about invalid version number in the Error List (it has extraneous single quotes).

## Actual:
No error in the error list, but the dependency node show an warning icon on the package with zero information as to the issue.

**Comment by nkolev92** [comment] 2020-02-04 20:50
Closing as duplicate of https://github.com/NuGet/home/issues/7717. 

I understand the other one is older, but it's one currently assigned and actively worked on.

**Closed as completed by nkolev92** 2020-02-04 20:50 UTC
Labels: Resolution:Duplicate, Priority:2, Area:ErrorHandling, Functionality:Restore, Style:PackageReference
