### ISSUE TITLE
[Cross-Platform Sign Verify] Unexpected error NU3018 show after restoring project on Linux

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10328] opened 2020-11-27 13:54 UTC
## Details about Problem
NuGet version: NuGet Client Dev\5.9.0.6972
VS Version: Main\30726.31
OS: Windows-10-Enterprise-19h2
## Detailed repro steps
1.	On Windows VM, create a C# Class Library (.NET 5.0) package, make and update nuspec file for the package with command `nuget spec`.
2.	Pack the package with command `nuget pack <packagename>.csproj`, create a new test certificate: ` .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -GenerateCerFile`.
3.	Sign the package: `NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath> -Timestamper http://timestamp.entrust.net/TSS/RFC3161sha2TS`.
4.	Copy the .cer file and signed package from the above Windows machine to Linux machine. 
5.	On Linux VM terminal, change the .cer to .crt format: `openssl x509 -inform DER -in <.cer file path> -out <.crt file path>`.
6.	Add the certificate(.crt) to trusted store: 
```
cd /usr/local/share/ca-certificates/ 
sudo cp <.crt file path>  ./ 
sudo chmod 644 ./<.crt file name> 
sudo update-ca-certificates 
```
7.	Create a project and add below package reference in the .csproj file. 
```
  <ItemGroup> 
    <PackageReference Include="<packageName>" Version="<packageVersion>" /> 
  </ItemGroup> 
```
8.	Add the feed(path contains the signed package),  set required mode in nuget.config file with trusted signers list:
```
   <packageSources> 
      <add key="<anyname>" value="<signed package parent folder>" /> 
   </packageSources> 
   <config> 
    <add key="signatureValidationMode" value="require" /> 
   </config> 
  <trustedSigners> 
     <author name="JamieZhang">        
         <certificate fingerprint="XXXXXXXXX" hashAlgorithm="SHA256" allowUntrustedRoot="false" /> 
     </author> 
  </trustedSigners> 
```
9.	Clear the cache: `<patchedSDKPath>./dotnet nuget locals all –clear`.
10.	Delete the <projectPath>/obj folder if there is any.
11.	Go inside the project folder, verify the package by running restore:   `<patchedSDKPath>./dotnet restore`.
## Expected Result
There were no errors or warnings, and restore is successful.
## Actual Result
Unexpected error NU3018 show as below.
![NU3018](https://user-images.githubusercontent.com/20632625/100455585-e3b1c380-30f9-11eb-914b-c2c0f1daec91.PNG)
## Notes
1. This bug only repro on Linux.
2. It only repro on three test cases: "Cross-platform verify: signed and timestamped package", "Cross-platform verify:  signed package with expired signing certificate" and "Cross-platform verify: tampered signed package ".
3. It is not a regression.

**Comment by nkolev92** [comment] 2020-11-30 19:11
fyi @heng-liu, @kartheekp-ms

**Comment by nkolev92** [comment] 2020-12-07 21:55
Triage: Assigning to @kartheekp-ms

**Comment by heng-liu** [comment] 2021-02-25 08:05
I could not repro for two test cases mentioned above: 
"Cross-platform verify: signed and timestamped package" and "Cross-platform verify: tampered signed package ".

I could only repro for test case: "Cross-platform verify: signed package with expired signing certificate"

**Comment by heng-liu** [comment] 2021-02-25 08:18
If we build the chain for the **expired self-issued certificate** by using the following policy setting:
```
                chain.ChainPolicy.VerificationFlags = X509VerificationFlags.IgnoreNotTimeValid;
                chain.ChainPolicy.RevocationMode = X509RevocationMode.Online;
                chain.ChainPolicy.RevocationFlag = X509RevocationFlag.ExcludeRoot;
                chain.ChainPolicy.VerificationTime = DateTime.Now;
```
 The chain build on Linux is different from other platforms:
`Chain status: "NotTimeValid,RevocationStatusUnknown,UntrustedRoot"`
 While on Windows the chain build is successful.

But if we build the chain for the **expired leaf certificate issued by intermediate CA** by using the same policy setting,
the chain build is successful for both Linux and Windows.

Since we use self-issued certificate for testing, but the packages on nuget.org uses a leaf certificate issued by intermediate certificate. It means the test fails but the real world works. 
So the issue is that our test could not test the right scenario by using self-issued certificate.  
I'm not sure if there is anyway to solve this problem so that we could test for the right scenario.

**Comment by heng-liu** [comment] 2021-02-26 00:38
Raised an issue in https://github.com/dotnet/runtime/issues/48794

**Comment by aortiz-msft** [comment] 2021-09-23 19:05
@heng-liu, @v-luzh - Closing as dupe of https://github.com/dotnet/runtime/issues/48794

**Closed as completed by aortiz-msft** 2021-09-23 19:05 UTC
Labels: Priority:2, Type:Bug, Platform:Xplat, Functionality:Signing, Found:ManualTests
