### ISSUE TITLE
Sync brush color resources with VS shell's EnvironmentColors

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#5245] opened 2017-05-18 01:54 UTC
### Problem

NuGet vsix has implicit dependency of VS platform module `Microsoft.VisualStudio.ExtensionsExplorer.UI` which should be eliminated. As it happened earlier #5232 any change made by the platform team in this module may potentially break NuGet PM UI.

### Proposed solution

Replace referenced resources with our own based on `EnvironmentColors`.

**Comment by mishra14** [comment] 2017-11-09 23:04
closing as dupe of internal issue: 497251

**Closed as completed by mishra14** 2017-11-09 23:04 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:DCR, Functionality:VisualStudioUI
