### ISSUE TITLE
An item with the same key has already been added restoring in Visual Studio when two projects have the same name

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#13745] opened 2024-08-27 23:07 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS17.11

### Worked before?

yes, maybe 17.10, maybe 17.8

### Impact

I'm unable to use this version

### Repro Steps & Context

see: https://developercommunity.visualstudio.com/t/Cannot-nuget-restore-after-updating-visu/10696231#T-N10714249-N10730661

Two projects in two "solution folders" have the same name: Test
Visual Studio's error list has the error: "Error occurred while restoring NuGet packages: An item with the same key has already been added"

**Comment by vkvn** [comment] 2024-08-28 07:19
Attaching the solution here. Try restoring NuGet packages from Visual Studio and it will fail with: "Error occurred while restoring NuGet packages: An item with the same key has already been added".

![VS_NuGet Error](https://github.com/user-attachments/assets/562a0180-d987-4df4-9631-4c19047e8930)
[NuGet_VSError.zip](https://github.com/user-attachments/files/16777844/NuGet_VSError.zip)

**Comment by kartheekp-ms** [comment] 2024-09-04 18:23
I am unable to reproduce the issue. Here are the steps I followed:

- Downloaded [NuGet_VSError.zip](https://github.com/user-attachments/files/16777844/NuGet_VSError.zip)
- Unzipped the content to a local folder
- Cleared the local NuGet cache using `dotnet nuget locals all -c`
- Launched VS 17.11.2
- Opened `NuGet_VSError.sln`
- Restore/Build/Rebuild operations succeeded.

![image](https://github.com/user-attachments/assets/d0c8185c-d094-4b98-95c1-ef0a669d3315)

This was a known issue in the [6.10 release](https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.10#6100-known-issues), which was fixed in VS 17.11. Please refer to the [PR #5825](https://github.com/NuGet/NuGet.Client/pull/5825) for more details.

@vkvn Please let me know if I am missing any repro steps.

**Comment by aortiz-msft** [comment] 2024-09-05 03:49
Closing as dupe of https://github.com/NuGet/Home/issues/13465

**Closed as not planned by aortiz-msft** 2024-09-05 03:49 UTC
Labels: Product:VS.Client, Type:Bug, Functionality:Restore, Style:Packages.Config
