### ISSUE TITLE
[Bug Bash] The tab “README” & “Package Details” should left-align with the content of each tab in the detail panel of PM UI 

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13910] opened 2024-11-06 10:01 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.13.0.57

### Worked before?

It’s not a regression since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Details about problem
NuGet Version: Dev\6.13.0.57
VS Version: Main\35505.97
OS: Windows-11-Enterprise-23H2

#### Notes:
1.	Repro rate: 100%.

#### Repro Steps: 
1.	Create a C# Console App (.NET 9.0) in VS and open the project-level PM UI window.
2.	Click the “Browse” tab, select a package and observe the “Package Details” tab in the details panel on the right.
3.	Install a package, click the “Installed” tab and observe the “README” tab in the details panel on the right.

#### Expected Result:
The tab “README” & “Package Details” should left-align with the content of each tab.

#### Actual Result:
The tab “README” & “Package Details” don’t left-align with the content of each tab as the screenshot below.
![image](https://github.com/user-attachments/assets/3a2c9b94-3d1e-49e2-af79-4770d3434692)
![image](https://github.com/user-attachments/assets/d8c2db70-25b8-4839-beb4-e7cddc1bed3d)

**Comment by nkolev92** [comment] 2024-11-11 21:57
@jgonz120 This is an inconsistency with the new tabbing caused by the readme work. 
Can you please get this fixed as part of the fit & finish for readme.

**Comment by nkolev92** [comment] 2024-11-25 22:45
Fixed by https://github.com/NuGet/NuGet.Client/pull/6141

**Closed as completed by nkolev92** 2024-11-25 22:45 UTC
Labels: Product:VS.Client, Priority:2, Type:Bug, Functionality:VisualStudioUI, Found:ManualTests
