### ISSUE TITLE
Multi "TargetFrameworks" and multiple <AssemblyName conditioned elements does not create project.assets.json file properly

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#12202] opened 2022-10-28 20:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Multi-TargetFrameworks-and-multiple-A/10151923)._

---
[severity:It's more difficult to complete my work]
System:
Windows 11 Enterprise, Version 21H2 (Build 22000.795)
Visual Studio 2022 (Version 17.3.4)
Project: Class Library, DotNet 6.0
No Nuget packages used

I'm trying to target both Net47 and DotNet 6.0 with a class library while assigning a different AssemblyName to each target. I've created a simple empty sample project (attached) with the following project file contents. I get errors when I try to build/rebuild/clean in VS2022. (Note: typing ```dotnet build``` works fine from the "Developer PowerShell" console within VS. When I remove ```net47``` from the TargetFrameworks list, it works fine even with the below ```AssemblyNames``` elements in place.

```


  
    net47;net6.0
    disable
    disable
    $(MSBuildProjectName)_Framework
    $(MSBuildProjectName)
  


```

Error:

```
Build started...
1>------ Build started: Project: Multi_TargetFrameworks_ProjectAssetsJsonBug, Configuration: Debug Any CPU ------
Failed to restore C:\Users\mweintraub\source\repos\Multi_TargetFrameworks_ProjectAssetsJsonBug\Multi_TargetFrameworks_ProjectAssetsJsonBug\Multi_TargetFrameworks_ProjectAssetsJsonBug.csproj (in 2 ms).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: Assets file 'C:\Users\mweintraub\source\repos\Multi_TargetFrameworks_ProjectAssetsJsonBug\Multi_TargetFrameworks_ProjectAssetsJsonBug\obj\project.assets.json' doesn't have a target for 'net6.0'. Ensure that restore has run and that you have included 'net6.0' in the TargetFrameworks for your project.
1>Done building project "Multi_TargetFrameworks_ProjectAssetsJsonBug.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: Assets file 'C:\Users\mweintraub\source\repos\Multi_TargetFrameworks_ProjectAssetsJsonBug\Multi_TargetFrameworks_ProjectAssetsJsonBug\obj\project.assets.json' doesn't have a target for 'net47'. Ensure that restore has run and that you have included 'net47' in the TargetFrameworks for your project.
1>Done building project "Multi_TargetFrameworks_ProjectAssetsJsonBug.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I've also tried separating out the ```AssemblyName``` values into separately conditioned ```PropertyGroups``` without any changes.

---
#### Feedback Bot on 9/19/2022, 06:56 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jebriede** [comment] 2022-10-28 23:10
Duplicate of: https://github.com/NuGet/Home/issues/7016

**Closed as completed by jebriede** 2022-10-28 23:10 UTC
Labels: Resolution:Duplicate, Type:Bug, Transferred issue
