### ISSUE TITLE
Upgraded to VS2015 and latest NuGet 3.1 now I cannot upgrade, uninstall or install packages.

### ISSUE THREAD

**Issue by Jaans** [NuGet/Home#1119] opened 2015-08-05 13:03 UTC
This is utterly frustrating. I cannot even uninstall a package and begin anew.

When I try to uninstall, I get the following *BS* error. There is no such file (app.config) that it is complaining about (not on disk, not in project, not in source control, never was, it's a class library project!):

What's going on?

----------------------------------------------------------------------------------------

Attempting to gather dependencies information for package 'NLog.4.0.1' with respect to project 'Reporting', targeting '.NETFramework,Version=v4.6'
Resolving actions to uninstall package 'NLog.4.0.1'
Resolved actions to uninstall package 'NLog.4.0.1'
Removed package 'NLog.4.0.1' from 'packages.config'
Removed reference 'NLog.dll' from project 'Reporting'
Successfully uninstalled 'NLog.4.0.1' from Reporting
Install failed. Rolling back...
For adding package 'NLog.4.0.1' to project 'Reporting' that targets 'net46'.
For adding package 'NLog.4.0.1' to project 'Reporting' that targets 'net46'.
Package 'NLog.4.0.1' already exists in folder 'D:\####\####\packages'
Added reference 'NLog' to project 'Reporting'.
Added package 'NLog.4.0.1' to 'packages.config'
System.Runtime.InteropServices.COMException (0x80004005): Cannot add the file 'app.config'. There is already a linked file in this folder with the same name.
   at EnvDTE.ProjectItems.AddFromFileCopy(String FilePath)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddFileToContainer(String fullPath, String folderPath, ProjectItems container)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<AddFileToProjectAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<>c__DisplayClass26_0.<<AddFile>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddFile(String path, Stream stream)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectManager.Save(XDocument document)
   at NuGet.PackageManagement.VisualStudio.BindingRedirectManager.AddBindingRedirects(IEnumerable`1 bindingRedirects)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.RuntimeHelpers.<AddBindingRedirectsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<<AddBindingRedirects>b__55_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddBindingRedirects()
   at NuGet.ProjectManagement.MSBuildNuGetProject.PostProcessAsync(INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========

**Comment by yishaigalatzer** [comment] 2015-08-05 17:00
I have seen a report for this where there was a linked app.config inside the project - something like

```
  <ItemGroup>
    <None Include="..\..\XXX\App.config">
      <Link>XXX.exe.config</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

Do you have anything like that in your project?

If not are you able to share a repro project?

**Comment by yishaigalatzer** [comment] 2015-08-05 17:26
Here is the related other report  - https://github.com/NuGet/Home/issues/1111

**Comment by Jaans** [comment] 2015-08-06 06:16
Yes, I do have that, but in a completely separate project in the solution. Just to clarify, I'm trying to install/upgrade/uninstall on project A only (this project does NOT have such a linked file) and it gives me the errors described.

Given that you cannot open just a single project when it's part of a solution, I proceeded to "unload" all the other projects temporarily leaving me with just project A loaded in the solution. If I then try to do the exact same NuGet install/upgrade/uninstall operations it works.

So it would seem NuGet is looking into other projects' business when I'm explicitly only working with a given project.

Also, if I only have the project B (the one with the linked file) loaded and try NuGet actions on that, it fails no matter what I do, similarly to the linked issue #1111  

Hope that helps.

**Comment by yishaigalatzer** [comment] 2015-08-06 07:36
Thanks. That's very helpful. As a temporary workaround you can create a separate solution and only include the csproj you want to work with. I understand that's a problem and not a long term thing. Alternatively you can skip the linking.

Either way this issue is in our short list to be fixed right away.

**Comment by feiling** [comment] 2015-08-07 18:59
This is a duplicate of NuGet/Home#1111

**Closed by feiling** 2015-08-07 18:59 UTC
Labels: Type:Bug

**Comment by tdmiller** [comment] 2015-08-12 19:39
This is *not* a duplicate of NuGet/Home/issues/1111 -- I am having the same issue:  Trying to add a package to a project that does *not* have a linked app.config, but there are other projects in the solution that **do** have linked app.config files.

**Comment by yishaigalatzer** [comment] 2015-08-13 00:34
We think the fix is the same. Feel free to add a small repro project to #1111 we will verify it is fixed.

**Comment by delfuria** [comment] 2015-08-14 13:24
HI, when the release 3.1.2 will be available ???
I have solution with 107 projects and i cannot reach to add/update any packages !!!!!
Thanks

**Comment by yishaigalatzer** [comment] 2015-08-14 15:08
We plan to release in the next few weeks, contact me directly if you are willing to try private bits

**Comment by delfuria** [comment] 2015-08-14 15:32
Thanks for the reply.
I would like to test the fix but how could i contact you ?

**Comment by sallgeud** [comment] 2015-08-27 19:41
What's the ETA on this release?
