### ISSUE TITLE
How do I do Machine Wide configuration on XPlat? 

### ISSUE THREAD

**Issue by ellismg** [NuGet/Home#1958] opened 2016-01-19 22:59 UTC
Enterprise Linux distros would like to be able to provide machine wide configuration for the feeds that nuget uses during package restore (to ensure that only sources the distro controls are used, so they can provide proper support).  Furthermore, it should be possible to disallow using other feeds during restore unless the end user goes out of their way so it is clear they are in an unsupported case.

What is the story for providing this sort of configuration?  If a standalone app decides they want to opt out, how easy is it to do so (i.e is it something that might happen accidentally or would it require modifying global machine state and hence need root permissions)?

**Comment by yishaigalatzer** [comment] 2016-01-20 02:42
1. This is a duplicate of https://github.com/NuGet/Home/issues/1899
2. Blocking users from picking nuget sources is something we don't want to support, for the same reason we don't want to support it on windows. I would love to hear direct customer feedback on why this is necessary before even considering such as feature.

**Closed as completed by yishaigalatzer** 2016-01-20 02:42 UTC
Labels: Resolution:Duplicate
