### ISSUE TITLE
Cannot Step Into NuGet Source Code

### ISSUE THREAD

**Issue by luckerby** [NuGet/Home#9612] opened 2020-05-27 19:12 UTC
I'm going over some simple C# .NET Core code that deals with package dependencies, using the NuGet SDK itself (code [here](https://github.com/NuGet/Home/issues/6188)). So I've created a sample project in VS 2019 and used that code.

I'd like to do a step-into with Visual Studio, to see exactly what NuGet methods are called, so need to make sure the symbols I'm using match whatever version the libraries the code uses. So I don't leave things to chance, and install the 5.6.0 version of the NuGet packages the code needs (`NuGet.Protocol` and `NuGet.DependencyResolver.Core`, with their required dependencies installed automatically) from VS's own Package Manager UI. I build the project, go to the `bin` folder and record the exact file version of the `NuGet.Protocol` .dll: 5.6.0.6591. I'm pretty sure the other assemblies included in the NuGet packages use the same version, based on the fact that there are dedicated Powershell scripts inside the NuGet's own tooling that look to rewrite the version when needed for all.

I clone the `NuGet.Client` GitHub repo locally. I switch to the `5.6.0.6591` tag, and build using the instructions in the `CONTRIBUTING.md` file. I go to the `artifacts` folder, where each project has its output assemblies and symbol files. I add the path to both folders containing the files I'm after, going with `netstandard2.0` folder due to the framework I'm targeting (.NET Core). Casually looking over one of the .dll within, I notice that the file version is 5.6.0.41820, clearly different from what I was expecting. Sure enough, adding both folders (corresponding to the 2 NuGet packages) to the symbol path in VS doesn't have any effect - as stepping into the code doesn't even trigger the symbols loading, let alone go into the NuGet source code.

Another hint that things don't quite match what I expect is that the .nupkg packages created right at the end of the build process have a names such as `NuGet.Protocol.5.6.0-zlocal.41820.nupkg`.

I'm pretty certain VS is configured to correctly process symbols, as I can step through .NET Core's own source code for methods invoked from the project mentioned above, after VS downloads automatically the required sources.

Is there any way to step into the NuGet source code in the context above ? Or is it something I've got wrong in the whole setup ?

**Comment by zivkan** [comment] 2020-05-28 00:01
I'm not 100% sure, but I think we have a bug in our build & release pipelines that prevent symbols being published for the packages that we publish on nuget.org.

Background: We build every commit twice, once with the package version you see on nuget.org, once with a SemVer2 preview label, because we don't know in advance which commit is going to end up in VS. The few times I've had to debug a VS memory dump, I was able to get symbols, and see source, for NuGet's assemblies. However, I experienced the same thing as you, that I can't find symbols for the packages we publish on nuget.org.

So, as a workaround, you may be able to use this feed to get our packages: https://dotnet.myget.org/gallery/nuget-build. However, you might need to use an exact build number that we inserted into VS, because we only publish symbols for the builds that we inserted into VS. Look at the file properties for the assembly in the package you used from NuGet.org, and the "File version" has the build number in the 4th segment. You can then try to find a package on our myget feed with the same number in the package version. Or look for the git hash that is in the SemVer2 version metadata.

Hopefully that way you'll be able to download NuGet's symbols from the Microsoft symbol server.  We really need to fix our publishing pipelines.

**Comment by luckerby** [comment] 2020-06-12 20:26
Thanks @zivkan. That worked just fine. Just to summarize, I knew the build number was `6591` since I'd already looked at the NuGet assemblies' file versions stored within the `bin` folder of my project after building. VS's own Package Manager UI is also kind enough to show the full version - including the commit id (`636570e68...`) - under "Options" when the respective package is selected. I went ahead and created a new feed pointing to `https://dotnet.myget.org/F/nuget-build/api/v3/index.json` and simply selected the version I was interested in: `5.6.0-rtm.6591`. I've double-checked that the version listed under "Options" had the same commit id as previously discovered, and installed the required NuGet packages to my project.

Took a snapshot below of the debugger stepping into the NuGet source files after performing the steps above; the stack confirms the outcome as well.

So the symbols corresponding to the packages published on nuget.org somehow never make it to the Microsoft symbol servers (or something corrupts them in-transit etc), just like you very well pointed out. Out of curiosity, where would you start troubleshooting this on your side ?

![image](https://user-images.githubusercontent.com/31319583/84542205-a3a08500-ad01-11ea-9637-6d82346d753b.png)

**Comment by zivkan** [comment] 2020-06-13 12:46
> So the symbols corresponding to the packages published on nuget.org somehow never make it to the Microsoft symbol servers (or something corrupts them in-transit etc), just like you very well pointed out. Out of curiosity, where would you start troubleshooting this on your side ?

In our [build yaml, we run our "build and unit test" phase twice](https://github.com/NuGet/NuGet.Client/blob/427adf89c1fa3aab03f4f3840982f2d6b030d3e3/build/vsts_build.yaml#L88-L93), once with "RTM" branding (version 5.6.0) and once with "non-RTM branding" (version 5.6.0-rtm.1234). The non-RTM branded versions get inserted into Visual Studio multiple times per Visual Studio preview release, and our release pipeline correctly publishes symbols every time we do this. Once Visual Studio ships GA, we publish the RTM branded nupkgs to nuget.org, for whatever build of NuGet that shipped in VS. But, because the RTM and non-RTM binaries are from different compilations, the pdbs and therefore symbols don't match, even though it's all from the same source code/commit.

Unfortunately Azure DevOps release pipelines can't use YAML files in the repo, which means that our publishing defitions are not public and can't accept improvements via pull requests. So someone in the team need to look into our release pipelines, figure out why symbols are not being published, and change them so they do. Maybe symbols are being published to a Microsoft-internal symbol server, I'm not sure.

My personal preference is actually for the team to stop publishing packages where the first version in a minor release has patch version 0, and increments by 1 each time we publish (eg 5.5.0, 5.5.1). If the team, and the community, accept that the first package for a certain minor release will not have patch version 0, and any bugfix updates will not be a sequential increment, then we no longer need to build twice (RTM and non-RTM branded), or publish symbols twice. But this is more work and much larger impact than just fixing our nupkg publishing pipeline.

**Comment by zivkan** [comment] 2022-09-29 00:33
This issue is a duplicate of https://github.com/NuGet/Home/issues/10463

As stated in that issue, symbols have been published to Microsoft's public symbol server, for NuGet SDK package version 6.0 and above. Some of the older packages have PDBs published, but have Source Link stripped out, so you'd need to download the NuGet.Client repo yourself, switch to the appropriate branch/tag, and then tell your debugger where to find it.  Going forward, our package publishing pipeline should continue to correctly publish pdbs.

**Closed as not planned by zivkan** 2022-09-29 00:33 UTC
Labels: Functionality:SDK, Priority:2, Type:Bug, Type:Engineering, Category:Quality Week
