### ISSUE TITLE
nuget pack hangs when using \**\*.h

### ISSUE THREAD

**Issue by zenakuten** [NuGet/Home#8049] opened 2019-04-23 13:57 UTC
Nuget.exe hangs creating a package with \\**\\*.h in <files> section

In my package.nuspec file I have

    <files>
        <file src="..\**\*.h" target="include" />
    <files>

In the folder .. there are two .h files and one subdirectory "Foo" with "Foo\Foo.h" file.

Nuget hangs indefinitely with 'attempting to build package from package.nuspec'

If I remove the <file src="..\\**\\*.h"> recursive reference and specify each .h file explicitly it works.

e.g.

    <file src="..\*.h" target="include />
    <file src="..\Foo\*.h" target="include\Foo" />

NuGet version 4.5.1.4879:
VS version 2017 Enterprise (15.9.9):
OS version: win10 v1803

**Comment by nkolev92** [comment] 2019-04-23 18:07
Does it truly hang, or is it just taking too long? 
How long did you let it run for? 

I'd imagine this is a duplicate of https://github.com/NuGet/Home/issues/5016.

**Comment by zenakuten** [comment] 2019-04-23 23:11
I don't believe it is a performance problem.  My directory structure is as follows

    myapp\
    myapp\foo
    myapp\nuget

In myapp there are two .h files.  Under myapp\foo\ there is one .h file.  I went to lunch and came back and it was still stuck, about 30 minutes later.   The entire package when created is less than 50k.  It includes one dll, one pdb, and the three .h files.

**Comment by nkolev92** [comment] 2019-04-23 23:16
Does using the newest nuget.exe change anything? 
https://www.nuget.org/downloads

It'd be nice if you can provide the exact directory structure with which you are packing or a zipped up repro project, so we can validate on our end.

**Comment by zenakuten** [comment] 2019-04-23 23:48
Yep as soon as I'm back at work tomorrow I'll send it.

**Comment by zenakuten** [comment] 2019-04-24 11:54
I was wrong.  

My directory structure has a 'packages' folder of other nuget projects in the root.  The \\\*\*\\\*.h must have been trying to pull in all of those headers as well.  There are 7500+ files under that folder.  After removing the packages folder the package is created successfully using the \\\*\*\\\*.h option.

**Closed as completed** 2019-04-24 11:57 UTC
Labels: Product:NuGet.exe, Functionality:Pack, WaitingForCustomer
