### ISSUE TITLE
Support additional PackageReference conditions such as $(Configuration).

### ISSUE THREAD

**Issue by myermian** [NuGet/Home#6226] opened 2017-11-27 17:28 UTC
## Details about Problem
* Microsft Visual Studio Enterprise 2017 (Version 15.4.1)
* NuGet Package Manager 4.4.0
* Microsoft Windows 10 Enterprise 

## Detailed repro steps so we can see the same problem
1. Create a new project (any will do, used console application as an example)
2. Add a package using the PackageReference format.
3. Modify the csproj and add a condition to only include the package if the configuration is set to Debug.

According to the Microsoft Documentation (https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) under the Comments, someone pointed out that the condition attribute only applies to TargetFramework and not Configuration (or any other condition). The MSFT member suggested posting an issue back in July, but I don't think anyone created an issue since this still does not work and I could not find any related issues when doing a search through the issues (unless I missed it).

> Kraig_Brockschmidt-MSFT Jul 17, 2017
> @jakub At present, the only supported condition is TargetFramework. This is because the project.assets.json file can contain packages for multiple target frameworks but not multiple configurations or other property values.

Being able to restore packages on conditions other than TargetFramework would be helpful, especially when mixing in floating versions. My original goal was to pull in the highest version on Release and to pull in the highest prerelease (CI version) on Debug.

```
<PackageReference Include="Utils" Version="1.*" Condition="'$(Configuration)' == 'Release'" />
<PackageReference Include="Utils" Version="1.0.0-*" Condition="'$(Configuration)' == 'Debug'" />
```

Another (unrelated) item that is a bit of a letdown is that the floating versions don't support "1.*-*", but that's another issue (https://github.com/NuGet/Home/issues/912).

**Comment by emgarten** [comment] 2017-11-28 00:20
Duplicate of https://github.com/NuGet/Home/issues/5895

**Closed as completed** 2017-11-28 02:49 UTC
Labels: Resolution:Duplicate, Functionality:Restore

**Comment by rohit21agrawal** [comment] 2017-11-28 02:50
@myermian do the workaround suggested in #5895 work for you?

**Comment by myermian** [comment] 2017-11-30 16:13
The Choose/When workaround actually works. I'm curious why that works and just using a standard condition does not work, strange.

**Comment by mariusingjer** [comment] 2022-04-22 11:15
The aforementioned workaround:

```
  <Choose> 
    <When Condition="'$(Configuration)' == 'Debug'">
      <ItemGroup>
        <PackageReference Include="Serilog.Sinks.File" Version="3.1.1" />
      </ItemGroup>
    </When>
  </Choose>
```
