### ISSUE TITLE
NuGet 3.3 under VS2015 removes References XML from proj files

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1866] opened 2015-12-22 11:28 UTC
_From @lukepuplett on December 22, 2015 9:52_

Cross-posted with SO.

http://stackoverflow.com/questions/34400276/nuget-references-vs2015-and-vs2013-compatibility

Reinstalling packages removes the `<Reference ...>` XML elements from the .csproj files, but the references are visible as nodes in the Solution Explorer pane.

I'm not sure if this is intended behaviour. My colleagues think not, and indeed they have also ran `Update-Package ... -Reinstall` without seeing this behaviour, yet I think its just how it works nowadays. However, if it is how it works, will it break the project for 2013 users?

Maybe something is configured differently on my machine, maybe its not supposed to happen, in any case I have not checked in the changes and have gone back to VS 2013 for now.

Luke

_Copied from original issue: NuGet/NuGetGallery#2826_

**Comment by yishaigalatzer** [comment] 2015-12-28 21:16
@lukepuplett this doesn't sound like something that is supposed to happen, update-package -reinstall definitely does not do that (at least in all the cases we know about), since there are not enough details in the post, to figure out what is going on, can you please fill in some more details?
1. What version of NuGet are you using? The current version is 3.3, and many bugs have been fixed between 3.0 to 3.3, can you please update to Visual Studio Update 1 that will bring it up to speed?
2. What project type are you using NuGet in?
3. Can you reproduce this problem in a small manageable way?
4. If it can't reproduced in a small project, can you post a sample project where this happens, with specific before/after results?
5. Did you by any chance, exited visual studio without saving the projects?

**Comment by lukepuplett** [comment] 2015-12-28 22:42
Hello, I'm not at work this week so I'll try and answer what I can now.
1. To be confirmed; VS 2015 w/o update.
2. It was an ASP.NET 4, MVC 5 Web Application created using VS 2013 probably Update 3 back then.
3. I'll try. A colleague did an update the other day and I stopped him before he committed and checked for this behaviour and his looked okay.
4. I can't post code though I stashed the changes so I can post before/after of just the references.
5. If you mean that I didn't save the projects and that the (re-added) refs were there in the in-mem version but not committed to disk and thus not showing in the diff tool, that's totally possible and a really good idea. Though that would mean that some process has saved the projects with the references removed - which would mean a save occurred mid-update - and then not saved the projects after its put the refs back in. Odd, sure, but possible.

**Comment by yishaigalatzer** [comment] 2015-12-28 23:17
@lukepuplett thanks for getting back on this. I'll wait for you to update to the latest, and report back after you get back to work, and we can take it from there.

**Comment by lukepuplett** [comment] 2016-01-07 11:32
Have been using VS 2015 since 4th Jan now and all OK so I'm happy to close this as an anomaly (possibly caused by a proj file save during update but not after) and I'll look out for the issue in the future.

The main thing is that I learned that this is not how its supposed to work, should it happen again. Thanks!!

**Comment by yishaigalatzer** [comment] 2016-01-07 15:59
Thanks. Let us know if you see it again.

**Closed as completed by yishaigalatzer** 2016-01-07 15:59 UTC
