### ISSUE TITLE
[Bug Bash] Building-solution restore doesn’t work after checking the “Automatically check for missing packages during build in Visual Studio” in Options dialog for C# Console App (.NET 8.0) 

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13192] opened 2024-01-25 08:45 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.10.0.13

### Worked before?

It is not a regression since it reproduced on D16.11\34301.259.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1.	Create a C# Console App (.NET 8.0) project in VS and open the PM UI window. 
2.	Install several packages (e.g. Newtonsoft.Json and log4net), go to the path “C:\Users\[username]\.nuget\packages” and delete an installed package (e.g. log4net) from the packages folder. 
3.	Click the settings button (gear button) on PM UI or PMC window. 
4.	Click the NuGet Package Manager->General in the opened “Options” window. 
5.	Check the “Allow NuGet to download missing packages” & “Automatically check for missing packages during build in Visual Studio” and click OK button. 
6.	Right-click the solution node in Solution Explorer and build the solution.
7.	Go back to the path “C:\Users\[username]\.nuget\packages” and observe. 
  
#### Expected Result: 
The lost packages had been restored back to the global packages folder successfully.

#### Actual Result:
The lost package was not restored back to the global packages folder in step7 and there is still the error in Error List window in step6 as below.
![image](https://github.com/NuGet/Home/assets/20632625/514e3b1c-b708-47d8-a5f7-f99198b08711)
#### Notes:
1.Repro rate: 100%.
2.It doesn’t repro for iOS (Xamarin) App project. 
3.It doesn’t repro when deleting the whole “packages” folder from the path “C:\Users\[username]\.nuget”.
4.Rebuilding-solution will restore the lost package successfully.

**Comment by nkolev92** [comment] 2024-02-15 19:56
Closing as duplicate of https://github.com/NuGet/Home/issues/13191, it is the same root cause.

**Closed as not planned by nkolev92** 2024-02-15 19:56 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:VisualStudioUI, Functionality:Restore, Found:ManualTests
