### ISSUE TITLE
Dependency Tree NU1605 - Packing with floating versions generates an incorrect version

### ISSUE THREAD

**Issue by HavartiCheese** [NuGet/Home#7256] opened 2018-08-31 13:29 UTC
## Details about Problem

NuGet product used (VS UI / .net core CLI ):

NuGet version (4.7.0.5):

dotnet.exe --version (2.1.302):

VS version (2017):

OS version (Win7 x64 SP1):

## Detailed repro steps so we can see the same problem

-For .net core 2.1 
1. Produce a project (Project B), with no dependencies, pack and publish this with version 1.0.5

2. Produce a Project (Project A) that references 1 NuGet Package (Project B, with version 1.0.5) with the version attribute set to "*" in the .csproj file of Project A. 

3. Pack and publish Project A as a NuGet package with a version 1.1.0

4. Import Project A as a NuGet package into Project C.

- In step 4, the NuGet import will fail with **Code NU1605**. This is because Project A has Project B as a dependency. However Project A is looking for version >= 1.1.0 (its own version number, rather than the latest Project B version number which is 1.0.5)

Graphically: C -depends on-> A [version = 'wildcard'] -depends on-> B [version = 'wildcard'] 

...

**Comment by ab3llo** [comment] 2018-08-31 14:46
The **nearest wins** see the documentation here - https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution

**Comment by nkolev92** [comment] 2018-09-01 15:38
This seems like a problem in pack.
I have inversed the names from the example A is B and B is A, but this is what I have.

The nuspec is the following.
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>ClassLibraryB</id>
    <version>1.1.0</version>
    <authors>ClassLibraryB</authors>
    <owners>ClassLibraryB</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="LibraryA" version="1.1.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

However the csproj is the following:

![untitled](https://user-images.githubusercontent.com/2878341/44947478-5bc99b80-adc2-11e8-8db1-ac7d487e300d.png)

**Comment by HavartiCheese** [comment] 2018-09-04 12:18
@nkolev92 

Thank you for your response. 

If NuGet does not support this form of versioning between dependency graphs, is my only solution to use a hard-coded version number?

Also, is there any plan to take this on and rectify this bug with pack?

**Comment by nkolev92** [comment] 2018-09-04 17:01
@HavartiCheese 
You can certainly use an exact version to work around this issue in the mean time. 

At this point I can't give you a timeline. 
It shouldn't be a super involved fix, we'd be happy to take a PR if this is impacting you heavily.

**Comment by nkolev92** [comment] 2018-11-30 17:35
Originally when looking at this issue, I missed that there's already a reported duplicate of it. 
https://github.com/NuGet/Home/issues/6697

**Closed as completed by nkolev92** 2018-11-30 17:35 UTC
Labels: Type:Bug, Functionality:Pack, Triage:NeedsTriageDiscussion, Style:PackageReference
