### ISSUE TITLE
"dotnet restore" does not honor proxy settings in local "nuget.config"

### ISSUE THREAD

**Issue by vdachev** [NuGet/Home#7332] opened 2018-09-27 07:10 UTC
The "dotnet restore" command does not seem to honor the "http_proxy" and "https_proxy" configuration settings in a *local* "nuget.config" file.

In order to check that, I made sure the configuration file contains invalid proxy settings and expected it to fail. Even if the settings are correct, they don't seem to be used.

Please, note that if I set the same settings in the global *nuget.config* file (*%AppData%\NuGet\NuGet.Config*), they do work.

Note: Setting the `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER` environment variable to `0` does not help either.

## Steps to Reproduce

1. Create a new console project with:
  ```console
  dotnet new console
  ```
2. Add a *nuget.config* file with the following content:
  ```xml
  <configuration>
  	<config>
  		<add key="http_proxy" value="http://0.0.0.0:8080" />
  		<add key="https_proxy" value="http://0.0.0.0:8080" />
  	</config>
  </configuration>
  ```
3. Clear NuGet locals
  ```console
  nuget locals all -clear
  ```
4. Restore packages
  ```console
  dotnet restore --configfile .\nuget.config
  ```

## Expected behavior

This one should fail because of invalid HTTP and HTTPS proxies.

## Actual behavior

Restoring packages is successful.

## Environment data

> dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.402
>  Commit:    3599f217f4
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.402\
> 
> Host (useful for support):
>   Version: 2.1.4
>   Commit:  85255dde3e
> 
> .NET Core SDKs installed:
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.300 [C:\Program Files\dotnet\sdk]
>   2.1.401 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

**Comment by rrelyea** [comment] 2018-10-01 23:48
This appears to be a dupe of this long issue...which has a bug on the netcore side:

#6978

**Closed as completed** 2018-10-01 23:48 UTC
Labels: Resolution:Duplicate

**Comment by vdachev** [comment] 2018-10-02 04:08
I did notice the other issues but they talk about proxy authentication.

The problem here is that proxy settings don't seem to work at all, with or without authentication.

**Comment by zarenner** [comment] 2019-08-02 22:34
For future readers, looking at the [code](https://github.com/NuGet/NuGet.Client/blob/d70e1f5475c9915f10ac4503553972d9bb988ce9/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs#L35]), it appears that only the user-level config works for proxy settings. This matches the behavior I see, at least on dotnet 2.2.401.
