### ISSUE TITLE
update-package of a content package in a tfs environment deletes directories and fails to add them again

### ISSUE THREAD

**Issue by Simulacrux** [NuGet/Home#943] opened 2015-07-14 06:32 UTC
Hello, 
I'm searched for this obvious glitch, but found nothing. So if this is allready adressed or fixed, please let me know.
We are working with severeal MVC projects in a Visual Studio environment with a TFS Server as source control system in the background. 
If we are deploying new version of our "content" packages (eg. css, sprites and so on) we discover a nasty bug every time. If a folder is completely filled from files out of the nuget package, then the update-package routine is first to delete the old stuff, therefore the folder is marked as deleted in the TFS, after that nuget is try to install the new version and discovers the pending delete and could not add the folder again, because first, the pending change must checked in. So after an upgrade we must roll back several directories and add the missing files manually in the TFS to get a working project again. 
We currently do an little trick and add a file in every directory which is not included in the nuget package, therefore the delete of the directory is not done and we get a handier way to upgrade.
Maybe it would be possible for the update-package to automaticly undo the pending delete and add the stuff after that normaly again. Maybe also with a "question" back, if this should be done, so other delete from before the update are not rolled back unintentionally.

Cheers Simulacrux

**Comment by yishaigalatzer** [comment] 2015-07-14 22:37
This looks like a duplicate of #491 or at least closely related issue.

**Comment by yishaigalatzer** [comment] 2015-07-14 22:38
Should be fixed for 2.8.7 as well

**Comment by yishaigalatzer** [comment] 2015-11-19 01:30
@zhili1208 please verify if this is fixed in 3.3 or not.

**Comment by zhili1208** [comment] 2015-11-19 18:34
verified it's fixed in 3.3, if it still repro on your machine, feel free to reopen it.

**Closed by zhili1208** 2015-11-19 18:34 UTC
Labels: Priority:1, Type:Bug
