### ISSUE TITLE
Error when restoring packages when source declares all packages as repository signed

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Home#7748] opened 2019-01-29 17:52 UTC
## Details about Problem

NuGet product used: dotnet.exe
dotnet.exe --version: 2.1.503

This bug affects does not affect nuget.exe or Visual Studio. The following .NET SDK clients are affected:

* 2.1.500
* 2.1.502
* 2.1.503
* 2.2.100
* 2.2.101
* 2.2.102
* 2.2.103

/cc @PatoBeltran @dtivel @rido-min 

## Detailed repro steps so we can see the same problem

The `allRepositorySigned` flag is enabled on nuget.org's DEV environment (see [this resource](https://apidev.nugettest.org/v3-index/repository-signatures/4.9.0/index.json)). Attempting to restore packages using .NET SDK 2.1.503 fails even if the package is repository signed. Sample csproj:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
  </ItemGroup>
</Project>
```

After clearing locals, restore using `dotnet restore .\repotest.csproj -s https://apidev.nugettest.org/v3/index.json`

## Logs

```
PS E:\repotest> dotnet restore .\repotest.csproj -s https://apidev.nugettest.org/v3/index.json
  Restoring packages for E:\repotest\repotest.csproj...
  Installing Newtonsoft.Json 10.0.2.
E:\repotest\repotest.csproj : error NU3004: Package 'Newtonsoft.Json 10.0.2' from source 'https://apidev.nugettest.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
  Restore failed in 2.08 sec for E:\repotest\repotest.csproj.
```

### Sample Project

[repotest.zip](https://github.com/NuGet/Home/files/2808935/repotest.zip)

**Comment by nkolev92** [comment] 2019-02-05 05:34
I believe this is a duplicate of https://github.com/NuGet/Home/issues/7574. 

@loic-sharma Please reopen if I'm wrong.

**Closed as completed by nkolev92** 2019-02-05 05:34 UTC
Labels: Resolution:Duplicate, Functionality:Signing, Product:dotnet.exe, Area:Protocol
