### ISSUE TITLE
Feature Request: Publish to nuget directly from Visual Studio: Project | right-click | Publish

### ISSUE THREAD

**Issue by davidnmbond** [NuGet/Home#6709] opened 2018-03-20 00:54 UTC
Publishing to nuget should be available from the Project's right-click menu as the default action when clicking "Publish".

**Comment by zhili1208** [comment] 2018-03-20 17:54
this is a dupe of https://github.com/NuGet/Home/issues/4459

**Closed as completed by zhili1208** 2018-03-20 17:54 UTC
Labels: Resolution:Duplicate
