### ISSUE TITLE
In PackageRef, use attribute form instead of element form of version

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4440] opened 2017-01-30 20:08 UTC
So, we are adding the following:
```

    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>5.3.0</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>9.0.1</Version>
    </PackageReference>

```

It should be:

```
<PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="5.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />

```

**Comment by jainaashish** [comment] 2017-01-30 20:27
How does it make a difference? besides it's not us who add these into csproj rather project system adds it.

**Comment by karann-msft** [comment] 2017-01-30 21:06
@jainaashish irrespective of who owns this, we don't want to be using this verbose format. For one it is way more difficult to read (ignoring the argument that who opens the csproj/project.json). Two, devs may follow our lead on the best way to add a reference. Three, we are about to [remove the element way of referencing](https://github.com/NuGet/Home/issues/4270) from our docs.
@rrelyea and I had discussed this and we are on the same page that we should be using the attribute form.
@jainaashish please file a bug on the team that should own this, and reference it here.

**Comment by mishra14** [comment] 2017-02-08 22:31
@karann-msft @rrelyea: this is a dupe of https://github.com/NuGet/Home/issues/4325 if karan is talking about `dotnet add package` code path. 

Inside VS respective project system would own the code path responsible for adding the package reference. Not sure if we can fix that by our selves.

**Comment by mishra14** [comment] 2017-05-22 18:18
@karann-msft please clarify

**Comment by karann-msft** [comment] 2017-06-06 16:17
@mishra14 we don't add the reference to the project file when a new package installed using the PMUI or PMC?

**Comment by mishra14** [comment] 2017-06-06 17:54
@karann-msft : not inside VS. In VS we rely on the underlying project systems to do that. We will try to find a bug that we have filed to track external work.

cc: @jainaashish

**Comment by jainaashish** [comment] 2017-06-06 17:57
There's already an internal bug# 394388 assigned to Project system to fix it. They moved it out of 15.1 to 15.3 so @karann-msft you can check with @tmeschter if they've any plan to fix it in this milestone.

**Comment by zhili1208** [comment] 2017-11-10 00:02
from @tmeschter 
We've decided not to fix this in the legacy project system as it has no functional impact. The plan is that in the Dev16 time frame most common project types will be handled by CPS-based project system which already provides the desired behavior.

Close it

**Closed as completed by zhili1208** 2017-11-10 00:02 UTC
Labels: Resolution:External, Style:PackageReference
