### ISSUE TITLE
Skip MSBuild tests on machines where older MSBuild versions are not installed

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2397] opened 2016-03-25 06:37 UTC
Today when I run tests on a machine that only has MSBuild 14, some tests fail making it hard to know if I broke something with my changes or if there's a real problem.

```
C:\dev\NuGet.Client\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\NuGetPackCommandTest.cs(1747): error : NuGet.CommandLine
.Test.NuGetPackCommandTest.PackCommand_WithMsBuild12 [FAIL] [C:\dev\NuGet.Client\test\NuGet.Clients.Tests\NuGet.CommandLine.
Test\NuGet.CommandLine.Test.csproj]
        Assert.Equal() Failure
        Expected: 0
        Actual:   1
          NuGetPackCommandTest.cs(1747,0): at NuGet.CommandLine.Test.NuGetPackCommandTest.PackCommand_WithMsBuild12()
C:\dev\NuGet.Client\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\NuGetPackCommandTest.cs(1011): error : NuGet.CommandLine
.Test.NuGetPackCommandTest.PackCommand_ReferencedProjectWithDifferentTarget [FAIL] [C:\dev\NuGet.Client\test\NuGet.Clients.T
ests\NuGet.CommandLine.Test\NuGet.CommandLine.Test.csproj]
        Attempting to build package from 'proj1.csproj'.
        MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.
        Building project 'C:\Users\dfowler\AppData\Local\Temp\NuGetTestFolder\b6836b97-44c8-420e-bdb5-6daa3b93780c\proj1\pro
  j1.csproj' for target framework '.NETFramework,Version=v4.0'.
        __________________________________________________
        Project "C:\Users\dfowler\AppData\Local\Temp\NuGetTestFolder\b6836b97-44c8-420e-bdb5-6daa3b93780c\proj1\proj1.csproj
  " (default targets):

        __________________________________________________
        Project "C:\Users\dfowler\AppData\Local\Temp\NuGetTestFolder\b6836b97-44c8-420e-bdb5-6daa3b93780c\proj1\proj1.csproj
  " is building "C:\Users\dfowler\AppData\Local\Temp\NuGetTestFolder\b6836b97-44c8-420e-bdb5-6daa3b93780c\proj2\proj2.csproj
  " (default targets):

        C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(983,5): error MSB3645: .NET Framework v3.5 Se
  rvice Pack 1 was not found. In order to target ".NETFramework,Version=v3.0", .NET Framework v3.5 Service Pack 1 or later m
  ust be installed.
        C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(983,5): warning MSB3644: The reference assemb
  lies for framework ".NETFramework,Version=v3.0" were not found. To resolve this, install the SDK or Targeting Pack for thi
  s framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pac
  k installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of refer
  ence assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
        Done building project "proj2.csproj" -- FAILED.
         Failed to build 'proj1.csproj'.

        Expected: True
        Actual:   False
          NuGetPackCommandTest.cs(1011,0): at NuGet.CommandLine.Test.NuGetPackCommandTest.PackCommand_ReferencedProjectWithD
  ifferentTarget()
Added file 'a.js'.
Removed file 'a.js' from folder 'C:\Users\dfowler\AppData\Local\Temp\NuGetTestFolder\8bf50325-382a-4935-802d-4ef915620622'.
```

**Comment by emgarten** [comment] 2016-03-28 18:54
These tests should be moved to run as optional functional tests.

**Comment by toddm** [comment] 2016-04-01 15:52
Duplicate of https://github.com/NuGet/Home/issues/1212, which I'm working on.

**Comment by joelverhagen** [comment] 2016-05-11 18:46
Still needs some polish. At least one test is missing:
- `PackCommand_WithMsBuild12`

**Closed as completed** 2017-06-13 04:09 UTC
Labels: Resolution:Duplicate, Product:VS.Client
