### ISSUE TITLE
Wrong product version values in nuget.exe 6.6

### ISSUE THREAD

**Issue by MindaugasBaltakis** [NuGet/Home#12597] opened 2023-05-18 12:09 UTC
### NuGet Product Used

NuGet.exe

### Product Version

6.6.0

### Worked before?

6.5

### Impact

I'm unable to use this version

### Repro Steps & Context

Inside nuget.exe 6.6 from https://dist.nuget.org/win-x86-commandline/v6.6.0/nuget.exe version.txt file contains:

`PRODUCTVERSION 0,0,0,0` and `VALUE "ProductVersion",    "6.6.0-preview.3+0fa557836fa35aee7d60776ef0c88176dbcd22ac.0fa557836fa35aee7d60776ef0c88176dbcd22ac"`

I think they cause issues in azure pipelines using NuGetCommand@2. 

Sorry for creating issue if release is not finished yet.

**Comment by magleaso** [comment] 2023-05-18 21:24
Correct, this is what caused issues in NuGetCommand@2. That task is getting patched to be resilient if this happens again.

**Comment by donnie-msft** [comment] 2023-05-19 20:51
Hello @MindaugasBaltakis, I deployed `6.6.0.61` by mistake which has the `preview.3` release label. I've now deployed `6.6.0.62` which is labelled as `6.6.0`. Please let me know if this still doesn't look how you expect.

**Comment by donnie-msft** [comment] 2023-05-19 22:52
Duplicate of https://github.com/NuGet/Home/issues/12595

**Closed as completed by donnie-msft** 2023-05-19 22:52 UTC
Labels: Priority:1, Resolution:Duplicate, Type:Bug

**Comment by MindaugasBaltakis** [comment] 2023-05-22 07:06
@donnie-msft it works. Thank you very much for speedy fix.
