### ISSUE TITLE
Version is not honored between p2p refs during 'pack' and 1.0.0 gets embedded

### ISSUE THREAD

**Issue by attilah** [NuGet/Home#4508] opened 2017-02-05 08:16 UTC
## Details about Problem

If you've ProjectA and ProjectB where ProjectB refs ProjectA with a P2P ref and you're specifying Version on the commandline, then this will be in the ProjectB.nuspec:

```
<dependency id="ProjectA" version="1.0.0" exclude="Build,Analyzers" />
```

The version in nupkg filename and within nuspec files for the packages themselves are good!

**Comment by rohit21agrawal** [comment] 2017-02-06 18:32
details about what version of nuget you are using would be appreciated along with a repro project

**Comment by attilah** [comment] 2017-02-06 18:57
I tried with VS2017 RC3 bundled tools, but now on my work machine I've:

These:
>dotnet nuget --version
NuGet Command Line
4.0.0.0

>dotnet --version
1.0.0-rc4-004755

For some reason I'm not able to attach the repro zip to this issue, sending it you internally in mail.

I get this message: "We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

**Comment by rrelyea** [comment] 2017-02-06 19:04
Believe this is a dupe of this issue: #3901 
That issue is already fixed...and will show up in the next update.

**Comment by rohit21agrawal** [comment] 2017-02-06 19:06
it should not happen for command line scenarios in the first place..i'll try using both VS and command-line and see where we are at

**Comment by rohit21agrawal** [comment] 2017-02-07 16:06
verified using both command line and VS, seems to be fixed. closing the issue. 

@attilah if you see this in any build of VS less than 2 days old, please reactive this issue.

**Closed as completed by rohit21agrawal** 2017-02-07 16:06 UTC
Labels: Resolution:Duplicate, Triage:Investigate, Functionality:Pack
