### ISSUE TITLE
"This collection is read-only" when updating Xamarin Forms for Android project

### ISSUE THREAD

**Issue by activa** [NuGet/Home#6913] opened 2018-05-07 19:22 UTC
Was already reported and was closed as "fixed" but it's not:

https://github.com/NuGet/Home/issues/6468

All details can be found in the above issue. 

Tested on the today's release of VS 2017 version 15.7

**Comment by jainaashish** [comment] 2018-11-09 23:18
dupe of https://github.com/NuGet/Home/issues/6468

**Closed as completed by jainaashish** 2018-11-09 23:18 UTC
Labels: Resolution:Duplicate
