### ISSUE TITLE
PackageReader.GetSupportedFrameworks() is not comprehensive

### ISSUE THREAD

**Issue by madelson** [NuGet/Home#10974] opened 2021-06-29 15:50 UTC
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): NuGet.Client 5.10.0

## Repro steps and/or sample project

NuGet package System.Runtime 4.3.1 clearly supports net5.0; it even lists specific dependencies for that framework and it can be installed into projects with that framework without issue. However, **calling `GetSupportedFrameworks()` on that package does not return net5.0 nor does it return any framework which is compatible with net5.0** according to `NuGetFrameworkUtility`.

Code to reproduce:

```
var source = new PackageSource("https://api.nuget.org/v3/index.json");
var repository = new SourceRepository(source, new Repository.ProviderFactory().GetCoreV3());
var downloadResource = repository.GetResource<DownloadResource>();
var downloadResult = await downloadResource.GetDownloadResourceResultAsync(
	new PackageIdentity("System.Runtime", new NuGetVersion("4.3.1")),
	new PackageDownloadContext(new SourceCacheContext()),
	SettingsUtility.GetGlobalPackagesFolder(new NullSettings()),
	NullLogger.Instance,
	CancellationToken.None
);
var supportedFrameworks = downloadResult.PackageReader.GetSupportedFrameworks();

// prints "monoandroid10,monotouch10,net45,net462,portable-net45+win8+wp8+wpa81,win8,wp8,wpa81,xamarinios10,xamarinmac20,xamarintvos10,xamarinwatchos10"
Console.WriteLine(string.Join(",", supportedFrameworks.Select(f => f.GetShortFolderName()).OrderBy(f => f)));
// prints "n/a"
Console.WriteLine(NuGetFrameworkUtility.GetNearest(supportedFrameworks, NuGetFramework.Parse("net5.0"), f => f)?.ToString() ?? "n/a");
```

**Comment by zivkan** [comment] 2021-06-29 16:44
It's non-intuitive, but `net50` expands to a Target Framework Identifier of `.NETCoreApp`, [as per the sepec](https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md), just like `netcoreapp3.1`, `netcoreapp2.1`, and so on do.  On the other hand, `net472` expands to a Target Framework Identifier of `.NETFramework`.  Since `.NETFramework` does not equal `.NETCoreApp`, these two target frameworks are in fact **not** compatible.

The reason that a project using `net5.0` can restore .NET Framework packages, is that the [.NET SDK adds Asset Target Fallback](https://github.com/dotnet/sdk/blob/c53c8ac81e1bcb8118c31bc4f5622396c72e9959/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L177-L179), to tell NuGet to ignore compatibility checks and restore anyway. This results in [warning NU1701](https://docs.microsoft.com/nuget/reference/errors-and-warnings/nu1701). As you can see from the SDK targets, projects can disable this implicit fallback by setting a property, so it's not true that any .NETCoreApp project (whether it's netcoreapp3.1, or net5.0, or net6.0) is compatible with .NET Framework packages.

If you're using the NuGet SDK, as you are in your reproduction sample, then you're responsible for mimicking this behaviour.  If you're dealing with real project files, then you can use the MSBuild APIs to read the AssetTargetFallback property, although in a nuget or msbuild restore, targets might modify the value before NuGet is run, making it impossible to have 100% compatibility with customers who customise their build with their own targets.  If you're happy with hardcoding the same fallback TFMs that the SDK does, you can.  Once you have the fallback TFMs you want to use, you can iterate the list after trying the preferred/"project" TFM. Also, you can investigate [`AssetTargetFallbackFramework`](https://github.com/NuGet/NuGet.Client/blob/b102b7587f0286d83dad8ee357caded56bd0ab17/src/NuGet.Core/NuGet.Frameworks/AssetTargetFallbackFramework.cs). Maybe it handles it for you.

**Comment by madelson** [comment] 2021-06-29 19:46
@zivkan thanks for the quick response. I'm aware that a .NET framework package is not directly compatible with net5.0. I'm still confused about this specific case, though.

From reading your comment, it sounds like you're saying that System.Runtime 4.3.1 _does not_, in fact, support net5.0. However, you say that this package can be installed into a net5.0 project and will result in a warning NU1701.

However, looking at the package on NuGet, it has an explicit dependency list for netstandard1.0-1.5, all of which _are_ compatible with net 5.0. It seems strange to have a dependency list for a framework that you don't support...

To test, I tried making a net5.0 project and installing System.Runtime 4.3.1. *It builds without warnings*. Here's the project file I'm using: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <WarningsAsErrors>true</WarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

 <ItemGroup>
   <PackageReference Include="System.Runtime" Version="4.3.1" />
 </ItemGroup>
</Project>
```

What am I missing?

**Comment by zivkan** [comment] 2021-06-29 20:32
Oops, you're right. When I checked the package, I only looked at the `lib/*` folders, and there was no `netstandard*` there, but there is in `ref/`.

Looking at the implementation of [`GetSupportedFrameworks`](https://github.com/NuGet/NuGet.Client/blob/b102b7587f0286d83dad8ee357caded56bd0ab17/src/NuGet.Core/NuGet.Packaging/PackageReaderBase.cs#L363-L378), it also doesn't take `ref/*` into account (or `contentFiles`, or `buildTransitive` or `buildMultiTargeting`, or `runtimes`). Digging through the method history, it was written before `PackageReference` existed as a concept, let alone an implementation,, so it's a packages.config API that was never updated.

In this sense, it's still "by design", because it correctly represents which target frameworks a packages.config project is compatible with (projects using packages.config don't support `ref` assets, or any of those other folders I listed above).

If you want to know how to determine what TFMs a package supports with PackageReference, we have an existing issue that's still open, but it doesn't have an answer: https://github.com/NuGet/Home/issues/8126

My suggestion would be to look into the class `ManagedCodeConventions`, and how it's used within NuGet.Client's source code. I helped an intern use it about 2 years ago to implement some TFM related pack warnings. If you only care about package compatibility it won't be an issue, but if you want to do asset selection, then you'll also need the runtimes.json, which ships in the .NET SDK, NuGet doesn't have in-built knowledge that win-x86 extends the win runtime identifier (RID), or that ubuntu extends linux, for example. See [this issue](https://github.com/NuGet/Home/issues/10914) for more details.

If you want this issue to become a feature request to create the simple API that #8126 was asking for, I can do that. But in full disclosure, as per our [nuget SDK docs](https://github.com/NuGet/NuGet.Client/blob/dev/docs/nuget-sdk.md), our team's charter is NuGet tooling, not the NuGet SDK, so it will be very low in priority.

If you're ok with closing the issue as `ManagedCodeConventions` being the way to determine package compatibility for PackageReference projects, then please do so.

**Comment by madelson** [comment] 2021-06-30 13:21
Thanks for the added detail @zivkan! That's an interesting nuance that `ref` does not work for packages.config.

After looking at `ManagedCodeConventions` a bit, I think that likely the best fit for what I'm trying to do is actually just:
```
var actualSupportedFrameworks = package.GetSupportedFrameworks()
    .Union(package.GetItems("ref").Select(f => f.TargetFramework).Where(f => !f.IsUnsupported))
    // possibly include contentFiles, buildTransitive, buildMultiTargeting, and runtimes too!
```

Given that you don't see the team prioritizing making a more robust API for this, I think it would be great to just update the [doc comment](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NuGet_NuGet.Client_blob_f24bad0668193ce21a1db8cabd1ce95ba509c7f0_src_NuGet.Core_NuGet.Packaging_PackageReaderBase.cs-23L361&d=DwMFaQ&c=GhIRcG_1AhU_zrKTouG5S1psW42C6Cq2nZgOViM14KEQWFAVxcZo4qcs6QSHjBMB&r=GJrJaUBotyxW3L9qYAg9ee5BmnwidZuDIhnnhK-PMoVczsjktad_38F2Axj3daWh&m=9Rs1xRgmew5QyTbbsbsY0PvKCiX7ltZRCnVYRqiAW7g&s=LdXm-LU0lZf16kIfAnDpb0hDplRiRzt6AukFDeIgzZA&e=) on `GetSupportedFrameworks` to call out some of these nuances (perhaps linking to this issue) so that people who are trying to use the SDK can more easily figure out what to do. Thoughts?

**Comment by zivkan** [comment] 2021-07-02 21:09
That might be "close enough" for whatever you're trying to do, but unfortunately it's again a little more nuanced if you want to be 100% accurate. packages.config allows assemblies to be under `lib/whatever.dll`, and NuGet will assume this package is compatible with all TFMs.  PackageReference will ignore these assemblies, considering only `lib/<tfm>/*.dll`, as per [the documented compatability issue](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#assemblies-in-the-lib-root-are-ignored-when-the-package-is-installed-after-the-migration).

I like your idea about xmldoc to raise awareness. I'll create a PR in a few minutes.

**Closed as completed** 2021-07-08 15:59 UTC
Labels: Functionality:SDK, Resolution:ByDesign, Type:DeveloperDocs
