### ISSUE TITLE
VS2015RC cannot find unlisted package

### ISSUE THREAD

**Issue by citizenmatt** [NuGet/Home#544] opened 2015-05-07 10:44 UTC
Hi all. I'm trying to install the `JetBrains.ReSharper.SDK` package in VS2015RC, and it's failing. After some investigation, it's failing to find the unlisted `Newtonsoft35.Json` package (yes, the ReSharper SDK is using a private, unlisted copy of a json.net. I can't remember why, but I'm sorry). If I try to install directly from the console, it errors with "Package 'Newtonsoft35.Json' is not found".

The package is visible on the web site, and can be installed into VS2013 no problem. I've tried installing from the `https://api.nuget.org/v3/index.json` source and also `https://www.nuget.org/api/v2/`.

Any ideas what's wrong?

**Comment by deepakaravindr** [comment] 2015-05-07 21:11
Please verify that unlisted packages can be restored as well as part of this fix

**Comment by yishaigalatzer** [comment] 2015-05-14 03:11
Looks like a duplicate of https://github.com/NuGet/Home/issues/539 except in this case we don't get a stackoverflow.

**Closed by yishaigalatzer** 2015-05-14 03:11 UTC
Labels: Area:SDK, Priority:1, Type:Bug
