### ISSUE TITLE
Absolutely need example of how to include native libraries

### ISSUE THREAD

**Issue by jackbond** [NuGet/Home#6648] opened 2018-03-07 23:33 UTC
Prior to VS 2017, you'd create a nuspec file with something like this...

`<file src="sample1.dll" target="runtimes\win7-x64\native"/>
<file src="sample2.dll" target="runtimes\win7-x64\native"/>
<file src="mynuget.targets" target="build"/>`

Is it possible to do this using the "Generate NuGet package on build" option in 2017? I've looked all around, but haven't found a concrete example of how to do it. Thanks.

**Comment by veikkoeeva** [comment] 2018-03-08 16:04
Duplicate of https://github.com/NuGet/Home/issues/6645.

I'm too trying the same at https://stackoverflow.com/questions/49162127/how-to-include-native-assets-in-nuget-on-multiple-platforms-only-64-bit. Still wondering why my native libraries don't show when package being restored, maybe need a custom `.target`.

**Comment by veikkoeeva** [comment] 2018-03-08 22:12
@jackbond This seems to work for me https://stackoverflow.com/questions/49162127/how-to-include-native-assets-in-nuget-on-multiple-platforms-only-64-bit . Not the cleares exposition, but hopefully enough.

**Comment by PatoBeltran** [comment] 2018-03-09 00:34
I will close this issue in favor of #6645, let's continue the conversation there.

**Closed by PatoBeltran** 2018-03-09 00:34 UTC
