### ISSUE TITLE
Failed to patchSDK with NuGet client Dev latest build

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12933] opened 2023-10-10 09:03 UTC
### NuGet Product Used

NuGet SDK

### Product Version

.Net SDK 7.0.401

### Impact

It's more difficult to complete my work

#### Repro Steps:
1. Open a new "Developer Command Prompt".
2. Cd to appropriate path, install [Git](https://git-scm.com/downloads) firstly, and git clone [Entropy](https://github.com/NuGet/Entropy.git).
3. Cd to <path_to_Entropy>\SDKPatchTool to check if the patch script is cloned successfully.
4. Download the nupkgs folder from  the Artifacts -> nupkgs - NonRTM of the build.
5. Open the <path_to_Entropy>\SDKPatchTool\patchOnWindows.ps1 and update the “$patchSDKFolder” & “$nupkgsPath” to appreciate path.
6. Open Task Manager and navigate to the main menu to File | “Run new task.”.
7. In the Open textbox type: `Powershell -ExecutionPolicy Bypass` and enable the option “Create this task with administrative privileges.”.
8. Cd to <path_to_Entropy>\SDKPatchTool and execute the command `.\PatchOnWindows.ps1`.
#### Expected:
PatchSDK with NuGet client Dev latest build successfully.
#### Actual:
Faild to patchSDK with NuGet client Dev latest build as below screenshot.
![image](https://github.com/NuGet/Home/assets/40230425/623c7c4b-475a-4e23-9cdd-1c8fb84a66d0)
#### Note:
1. The issue does not repro on NuGet Client Dev\6.8.0.120.
2. The issue repro rate is 100%.

**Comment by nkolev92** [comment] 2023-10-13 16:40
Root cause is https://github.com/NuGet/NuGet.Client/commit/05068887b9548a85e7c1b662280a688c727b2858. 
I'll take care of fixing the script.

**Comment by nkolev92** [comment] 2023-12-07 00:02
Should be fixed now.

**Closed as completed by nkolev92** 2023-12-07 00:02 UTC
Labels: Priority:1, Type:Test, Found:ManualTests
