### ISSUE TITLE
Nuget.exe 4.8.1 now reporting project.assets.json not found. Run a NuGet package restore

### ISSUE THREAD

**Issue by PJChamley** [NuGet/Home#7264] opened 2018-09-03 12:34 UTC
We have multiple VSTS Builds that are failing with build 4.8.1 (works fine with 4.7.1)

We had Multiple Builds working Friday 31st August 2018. 
This morning (Monday 3rd September 2018) we started seeing Builds fail with the following error. 
	project.assets.json not found. Run a NuGet package restore 

I manually triggered build of code that worked Friday and got the same error. 
I noticed that the Nuget Package tool was updated to 4.8.1 this morning.

If I remove Nuget.exe version 4.8.1 from build server, and tell the installer to not install 4.8.0 or higher (<4.8.0), manually trigger a build complete successfully. I then check with (Latest or code from Friday that built they all complete successfully. 

This suggest that 4.8.1 is the issue.

Build task list Simplified to help explain issue.

1)	Get Source from Github 
Clean  = True (All Build Directories)
2)	Nuget Tool Installer. 
a.	Always Update to latest  = Ticked. 
b.	Version >=4.5.0
3)	Nuget Restore  **/*.sln
4)	Visual Studio Build : Latest version. (VS 2017 15.7.5) 
a.	Clean = Ticked, 
b.	Build in Parallel = Ticked 
c.	Restore Nuget Packages = Un-Ticked.

**Comment by PatoBeltran** [comment] 2018-09-06 00:05
Hey @PJChamley, thanks for the issue! Can you reproduce this locally with 4.8.1 or it is only reproducing on VSTS? The project.assets.json is not found because probably restore failed before writing it to disk (this file is the output of restore). Can you provide me with some logs of restore to be able to investigate more on why it failed? 

If you are able to reproduce this locally, could you provide a repo that I can use to reproduce and investigate this issue? Thanks!

**Comment by rrelyea** [comment] 2019-03-29 20:49
No reply from @PJChamley - closing. 
Please let us know if you are able to provide more details.

**Closed as completed by rrelyea** 2019-03-29 20:49 UTC
Labels: Resolution:NotRepro, Triage:Investigate, Functionality:Restore, WaitingForCustomer
