### ISSUE TITLE
Problem of shared project.assets.json

### ISSUE THREAD

**Issue by weifenluo** [NuGet/Home#12973] opened 2023-10-28 14:50 UTC
### NuGet Product Used

dotnet.exe

### Product Version

7.0.403

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

The following sample solution would not build using `dotnet build NuGetProjectAssets.sln`:
https://github.com/weifenluo/NuGetProjectAssets

It outputs an error of `error NETSDK1005: Assets file '...\NuGetProjectAssets\obj\project.assets.json' doesn't have
a target for 'net6.0'.`

The sample solution is very simple: it contains two project files: `NuGetProjectAssets.csproj`, which multi targets .NET6.0 and .NET7.0; and `NuGetProjectAssets.NET70.csproj`, which targets .NET7.0 only. To make the bug reproduceable,  `NuGetProjectAssets.NET70.csproj` is set as dependency project of `NuGetProjectAssets.csproj`, so that `NuGetProjectAssets.NET70.csproj` will build before `NuGetProjectAssets.csproj`.

The problem is that the `project.assets.json` file are shared between different project files. NuGet should not assume only one project file exists under any folder.

**Comment by nkolev92** [comment] 2023-10-30 19:11
Duplicate of https://github.com/NuGet/Home/issues/4463. 

@weifenluo - there's a bunch of intermediates that are project specific, so you can 2 projects in the same directory if you have different `MSBuildProjectExtensionsPath` for them.

**Closed as not planned** 2023-10-30 19:11 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Restore

**Comment by weifenluo** [comment] 2023-10-31 04:02
> Duplicate of #4463.
> 
> @weifenluo - there's a bunch of intermediates that are project specific, so you can 2 projects in the same directory if you have different `MSBuildProjectExtensionsPath` for them.

Did you mean `BaseIntermediateOutputPath`? I tried adding following line into `NuGetProjectAssets.NET70.csproj`:
```
    <BaseIntermediateOutputPath>obj/NET70</BaseIntermediateOutputPath>
```

Now I have different `project.assets.json`, under `obj` and `obj/NET70` respectively. However, I got a bunch of CS0579 error:
```
error CS0579: ...: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
error CS0579: ...: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
error CS0579: ...: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
error CS0579: ...: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
error CS0579: ...: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
error CS0579: ...: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
error CS0579: ...: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute
...
```

Am I doing anything wrong?

**Comment by weifenluo** [comment] 2023-10-31 04:27
Also https://github.com/dotnet/project-system/issues/1528

**Comment by nkolev92** [comment] 2023-10-31 16:24
I'm referring to `MSBuildProjectExtensionsPath` in particular as that has no ordering concerns as `BaseIntermediateOutputPath`. 
MSBuildProjectExtensionsPath  does default to BaseIntermediateOutputPath but only if BaseIntermediateOutputPath is set before the  props file import of the SDK, so it needs to be in a Directory.Build.props. 

As far as whether you're doing anything wrong, I don't think so, as that's more of a build related thing, but I'd recommend clearing the obj folder once before doing this as that can cause conflicts in certain build parts.

**Comment by weifenluo** [comment] 2023-11-01 03:35
@nkolev92 Thanks a lot for your explanation.

Inspired by this article (https://willich.io/2017/10/12/multiple-projects-in-the-same-folder/), I finally get it to work (as in https://github.com/weifenluo/NuGetProjectAssets):

1. Change the project file `NuGetProjectAssets.NET70.csproj` to `NuGetProjectAssets.Trimmable.csproj`, and move both projects a level down to a `src` folder, so that it's more close to my real situation.
2.  Add `Directory.Build.props`:
```
<Project>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Trimmable')) or $(MSBuildProjectName.Contains('.Trimmable.'))">
    <IsTrimmableProject>true</IsTrimmableProject>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <IsTrimmableProject Condition ="$(IsTrimmableProject) == ''">false</IsTrimmableProject>
  </PropertyGroup>

  <PropertyGroup Condition="$(IsTrimmableProject)">
    <DefineConstants>TRIMMABLE</DefineConstants>
    <BaseIntermediateOutputPath>obj\Trimmable</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\Trimmable</BaseOutputPath>
  </PropertyGroup>
</Project>
```
3. Add following lines into `NuGetProjectAssets.Trimmable.csproj`, to eliminate CS0579 errors, which I believe it's a bug of project system:
```
  <ItemGroup>
    <Compile Remove="obj\\**\*"/>
    <Compile Include="obj\Trimmable\**\$(MSBuildProjectName).AssemblyInfo.cs" />
  </ItemGroup>
```
