### ISSUE TITLE
AutoReferenced UI tweaks

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4977] opened 2017-04-04 21:59 UTC
The highlighted text in the following UI has to be improved:
![image](https://cloud.githubusercontent.com/assets/14800916/24822010/edfdac3a-1ba6-11e7-92ae-070f41107267.png)

**Comment by anangaur** [comment] 2017-04-07 22:32
Proposal:
This package reference is implicitly added and managed by the SDK installed. To change the package reference version, you need to change the underlying SDK that you project depends on. [Learn more](TBD link)

**Comment by rrelyea** [comment] 2017-06-14 19:50
@shishirx34 did this already right? (title was mislabeled)

**Comment by shishirx34** [comment] 2017-06-14 19:59
@rrelyea Yes, with this PR: https://github.com/NuGet/NuGet.Client/pull/1399 
Tracking issue was: https://github.com/NuGet/Home/issues/4964
May be close this one as duplicate?

**Comment by rrelyea** [comment] 2017-06-14 20:12
Dupe of https://github.com/NuGet/Home/issues/4964

**Closed as completed by rrelyea** 2017-06-14 20:12 UTC
Labels: Resolution:Duplicate
