### ISSUE TITLE
Package Integrity check performed (and reported) twice

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#6945] opened 2018-05-17 17:54 UTC
When installing a tampered package, the error list, and the output window, report the error twice:

![image](https://user-images.githubusercontent.com/14916339/40194592-d896240a-59bf-11e8-94c0-63eb7c85641d.png)

```
Restoring packages for c:\users\rmpablos\source\repos\WpfApp1\WpfApp1\WpfApp1.csproj...
Installing System.Rido 1.0.2.
Signature Hash Algorithm: SHA256
NU3008: The package integrity check failed.
Signature type: Author
Verifying the author primary signature with certificate: 
  Subject Name: CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US
  SHA1 hash: 3C9C6F5A99400288E01B659FE248CDF49648631B
  SHA256 hash: 2D38BEE7044F7F1561A3B5AED0496998F5B4F9172122EC43D110368351207F23
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 8/29/2017 5:00:00 PM to 9/6/2018 5:00:00 AM

Timestamp: 3/21/2018 4:38:38 PM

Verifying author primary signature's timestamp with timestamping service certificate: 
  Subject Name: CN=DigiCert SHA2 Timestamp Responder, O=DigiCert, C=US
  SHA1 hash: 400191475C98891DEBA104AF47091B5EB6D4CBCB
  SHA256 hash: FC834D5BFFDE31DBA5B79BF95F573F7953BCBF9156E8525163E828EB92EA8A93
  Issued by: CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 1/3/2017 4:00:00 PM to 1/17/2028 4:00:00 PM

Installing System.Rido 1.0.2.
Signature Hash Algorithm: SHA256
NU3008: The package integrity check failed.
Signature type: Author
Verifying the author primary signature with certificate: 
  Subject Name: CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US
  SHA1 hash: 3C9C6F5A99400288E01B659FE248CDF49648631B
  SHA256 hash: 2D38BEE7044F7F1561A3B5AED0496998F5B4F9172122EC43D110368351207F23
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 8/29/2017 5:00:00 PM to 9/6/2018 5:00:00 AM

Timestamp: 3/21/2018 4:38:38 PM

Verifying author primary signature's timestamp with timestamping service certificate: 
  Subject Name: CN=DigiCert SHA2 Timestamp Responder, O=DigiCert, C=US
  SHA1 hash: 400191475C98891DEBA104AF47091B5EB6D4CBCB
  SHA256 hash: FC834D5BFFDE31DBA5B79BF95F573F7953BCBF9156E8525163E828EB92EA8A93
  Issued by: CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 1/3/2017 4:00:00 PM to 1/17/2028 4:00:00 PM

Package restore failed. Rolling back package changes for 'WpfApp1'.
Time Elapsed: 00:00:00.7048492
========== Finished ==========
```

**Comment by mishra14** [comment] 2018-05-18 18:44
This happens if the compat is checked  for multiple RIDs. We should improve this experience.

**Comment by kartheekp-ms** [comment] 2020-11-17 02:47
Unable to reproduce this issue on latest tooling. Version 16.9.0 Preview 2.0. Hence closing this task.

![image](https://user-images.githubusercontent.com/52756182/99340059-20e59e00-283c-11eb-97b0-03fb26a76478.png)

**Closed as completed by kartheekp-ms** 2020-11-17 02:47 UTC
Labels: Priority:2, Area:ErrorHandling, Functionality:Install, Functionality:Signing
