### ISSUE TITLE
Nuget cli authorization certificate

### ISSUE THREAD

**Issue by shoret01** [NuGet/Home#7212] opened 2018-08-17 10:30 UTC
I have a private artifactory repo that requires authorization certificate (it a company policy thing) 

My question is there any way I can setup Nuget cli to use a certificate, at the moment I get the error 

```
$ nuget list -Source https://private-artifactory.company.com/artifactory/nuget/
Unable to load the service index for source https://private-artifactory.company.com/artifactory/nuget/.
  An error occurred while sending the request.
  The request was aborted: Could not create SSL/TLS secure channel.
```

Which I expect because I’m not sending the certificate. 

Is there a way to do it like curl?

```
$ curl --cert dev.crt --key dev.key -T somepackage.nupkg https://private-artifactory.company.com/artifactory/nuget/
```

**Comment by rohit21agrawal** [comment] 2018-08-21 18:44
@nkolev92 is this something that will be supported as a result of your recent work?

**Comment by nkolev92** [comment] 2018-08-21 19:03
No, this seems to be about client certs which are still unsupported. 
Looks like a duplicate of https://github.com/NuGet/Home/issues/5773

**Comment by shoret01** [comment] 2018-08-22 07:54
ok thanks @rohit21agrawal  and @nkolev92 for getting back to me.  I look forward to when this is implemented.

**Comment by jainaashish** [comment] 2018-08-30 22:00
closed as dupe of https://github.com/NuGet/Home/issues/5773

**Closed as completed by jainaashish** 2018-08-30 22:00 UTC
Labels: Resolution:Duplicate, Product:NuGet.exe, Area:Authentication
