### ISSUE TITLE
symbol package pushing needs to be configurable in nuget 3.4

### ISSUE THREAD

**Issue by andycmaj** [NuGet/Home#2204] opened 2016-02-27 01:16 UTC
nuget 3.4 automatically tries to publish any symbols.nupkg files it finds to a hard-coded symbol server that's not the server i'm actually pushing my package to.

i'm seeing this now:

``` bash
$ tree .artifacts
.artifacts
└── Debug
    ├── ImsHealth.Automation.1.1.5.nupkg
    ├── ImsHealth.Automation.1.1.5.symbols.nupkg
    └── net451
        ├── ImsHealth.Automation.dll
        └── ImsHealth.Automation.xml

$ mono .tools/nuget.exe push "/Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug/ImsHealth.Automation.1.1.5.nupkg" -Source https://imshealth.myget.org/F/internal/api/v2/package
Pushing ImsHealth.Automation.1.1.5.nupkg to 'https://imshealth.myget.org/F/internal/api/v2/package'...
Your package was pushed.
Pushing ImsHealth.Automation.1.1.5.symbols.nupkg to the symbol server (https://nuget.smbsrc.net/)...
400 (Bad Request)
```

**Comment by andycmaj** [comment] 2016-02-27 01:17
Also, the symbol push fails with 400, so this breaks my automation at the moment. I have to manually remove the symbols package before i try to publish the normal nuget package.

**Comment by andycmaj** [comment] 2016-03-11 06:52
any ideas why this is happening? this prevents a sane push workflow on non-windows machines

**Comment by yishaigalatzer** [comment] 2016-03-12 21:33
We haven't gotten to this issue yet, but we now have someone assigned to deal with push issues

**Comment by yishaigalatzer** [comment] 2016-03-12 21:34
@spadapet would be nice if this makes it into nuget.exe for 3.4, lets assess

**Comment by andycmaj** [comment] 2016-03-13 03:34
thanks guys... let me know if you need more info

**Comment by spadapet** [comment] 2016-03-16 19:31
This _seems_ by design based on http://docs.nuget.org/Create/Creating-and-Publishing-a-Symbol-Package
If a symbol package exists, it automatically gets pushed to https://nuget.smbsrc.net

Seems like there are two problems with this:
- The API Key used for https://nuget.smbsrc.net is wrong when you are publishing to some place other than nuget.org
- There is no way to turn off this automatic behavior, or change the symbol server

@andycmaj, what are you going to do with the symbol package? Publish it to your own package source? If so, then maybe allowing auto-symbol pushing to be turned off is good. But if you aren't going to do anything with it, then it's better to not create it.

**Comment by spadapet** [comment] 2016-03-16 23:44
For 3.4:
- Need to get correct apiKey for the symbol source
- Add new option: --no-symbols

For 3.5:
New options like: --symbol-source, --symbols-api-key

**Comment by andycmaj** [comment] 2016-03-17 06:08
> what are you going to do with the symbol package? Publish it to your own package source? 

@spadapet, normally, i publish library and symbol packages to myget.

> There is no way to turn off this automatic behavior, or change the symbol server

I'd prefer the option to change the symbol server. that would make sense to me... seems more intuitive that symbols are published to the same place as libraries, doesn't it? I'm also okay with disable auto-push of symbols pkg, and i could do that myself. (this is what i used to do before 3.4).

> But if you aren't going to do anything with it, then it's better to not create it.

`dnu pack` creates the symbol packages automatically. as far as i know, you can't disable this.

RE: your proposals for 3.4 rtm and 3.5, i totally agree! sounds great.

**Comment by spadapet** [comment] 2016-03-17 17:44
Cool, the issue for tracking the 3.5 change is: https://github.com/NuGet/Home/issues/2348

**Closed as completed** 2016-03-19 04:33 UTC
Labels: Platform:Xplat, Functionality:Push
