### ISSUE TITLE
error NU1202:  is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0).  supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)

### ISSUE THREAD

**Issue by Amine-Smahi** [NuGet/Home#7863] opened 2019-03-10 13:10 UTC
Package : https://www.nuget.org/packages/Razor-Components-Template/

`$user > dotnet new -i Razor-Components-Template`

 ` Persisting no-op dg to /home/amine-smahi/.templateengine/dotnetcli/v3.0.100-preview3-010431/scratch/obj/restore.csproj.nuget.dgspec.json
/home/amine-smahi/.templateengine/dotnetcli/v3.0.100-preview3-010431/scratch/restore.csproj : error NU1202: Package Razor-Components-Template 1.1.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Razor-Components-Template 1.1.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)
  Restore failed in 2.79 sec for /home/amine-smahi/.templateengine/dotnetcli/v3.0.100-preview3-010431/scratch/restore.csproj.`

**Comment by dominoFire** [comment] 2019-03-12 23:55
Hi @Amine-Smahi,

It seems that the package only supports netcoreapp3.0 and not previous versions of netcoreapp.

I will close the issue since it is not a bug. If you have more questions about NuGet, feel free to use stackoverflow.com

**Closed as completed by dominoFire** 2019-03-12 23:55 UTC
Labels: Resolution:NotABug
