### ISSUE TITLE
dotnet list package --format json --include-transitive includes project references as transitive packages.

### ISSUE THREAD

**Issue by meareindel** [NuGet/Home#12585] opened 2023-05-12 16:03 UTC
### NuGet Product Used

dotnet.exe

### Product Version

7.0.203

### Worked before?

no

### Impact

It's more difficult to complete my work

### Repro Steps & Context

If I have a project that references another project, then the beforementioned command states that referenced project is a transitive package dependency for referencing project.

I'm not sure if this is really bug, perhaps it's just a need of some differentiation between project and package in output, for example, additional "type" property in "transitivePackages" node item, saying if it's a "Project" reference or a "Package".

Steps to reproduce:
1. Download the archive from attachment and unpack it somewhere
2. Run dotnet restore in unpacked folder
3. Run dotnet list package --format json --include-transitive

The output says that "DotnetListJsonTransitivesIssue" project has "ReferencedProject" in its transitive packages (or at least doesn't provide an information if this is really a package from some nuget source or just a project). 

Also, if it should include projects in output, in this very case the "ReferencedProject" should be within the "topLevelPackages" node

[DotnetListJsonTransitivesIssue.zip](https://github.com/NuGet/Home/files/11465827/DotnetListJsonTransitivesIssue.zip)

### Verbose Logs

```shell
{
  "version": 1,
  "parameters": "--include-transitive",
  "projects": [
    {
      "path": "C:/Users/User/source/repos/exp/DotnetListJsonTransitivesIssue/DotnetListJsonTransitivesIssue/DotnetListJsonTransitivesIssue.csproj",
      "frameworks": [
        {
          "framework": "net7.0",
          "transitivePackages": [
            {
              "id": "ReferencedProject",
              "resolvedVersion": "1.0.0"
            }
          ]
        }
      ]
    },
    {
      "path": "C:/Users/User/source/repos/exp/DotnetListJsonTransitivesIssue/ReferencedProject/ReferencedProject.csproj",
      "frameworks": [
        {
          "framework": "net7.0"
        }
      ]
    }
  ]
}
```

**Comment by erdembayar** [comment] 2023-05-12 19:50
Sure, I can see same details without json output too, looks like we need enum "project, package" to augment for clarity.

![image](https://github.com/NuGet/Home/assets/8766776/9fac496c-8ba2-43f5-a7f7-e32ac3ead8b4)

**Comment by nkolev92** [comment] 2023-07-15 00:00
There's actually duplicate of this in https://github.com/NuGet/Home/issues/10817.

**Closed as completed by nkolev92** 2023-07-15 00:00 UTC
Labels: Resolution:Duplicate, Priority:3, Type:Feature, help wanted, Product:dotnet.exe, Functionality:ListPackage
