### ISSUE TITLE
[Bug]: NuGet Restore fails sporadically with signature validity check failure

### ISSUE THREAD

**Issue by czdietrich** [NuGet/Home#11375] opened 2021-11-12 15:34 UTC
### NuGet Product Used

dotnet.exe

### Product Version

NET SDK version 5.0.403

### Worked before?

Also occurs with older SDKs

### Repro Steps & Context

Unfortunately the issue occurs very sporadically and only on Azure build agents. We could never reproduce it on any of our developer machines.

But here is what we do:
1. We download the `dotnet credential Provider` from https://aka.ms/install-artifacts-credprovider.ps1 to register our Azure AccessToken to give access to private NuGet feeds (this step might be unimportant)
2. We download the dotnet-installer from https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1
3. Then we invoke it with this command line `dotnet-install.ps1 -InstallDir "%TEMP%\dotnet-win\" -Channel "5.0" -NoPath` to get the latest .NET 5 SDK
4. Then we use it to compile: `%TEMP%\dotnet-win\dotnet.exe build <SolutionFile> /nodeReuse:false -nologo -clp:NoSummary --verbosity quiet`

And then the restore fails with:
```
error NU3037: Package 'System.Net.Http 4.3.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [C:\a\1\s\PiWeb\build\Nuke\src\Nuke.sln]
error NU3037: Package 'CommandLineParser 2.8.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [C:\a\1\s\PiWeb\build\Nuke\src\Nuke.sln]
error NU3028: Package 'System.Net.Http 4.3.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider. [C:\a\1\s\PiWeb\build\Nuke\src\Nuke.sln]
error NU3028: Package 'CommandLineParser 2.8.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider. [C:\a\1\s\PiWeb\build\Nuke\src\Nuke.sln]

error NU3037: Package 'Microsoft.Graph.Core 1.9.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [C:\a\1\s\PiWeb\build\Nuke\src\Nuke.sln]
error NU3028: Package 'Microsoft.Graph.Core 1.9.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider. [C:\a\1\s\PiWeb\build\Nuke\src\Nuke.sln]
```

It is completely unclear why this is happening and whether it has something to do with the Azure environment.

It can happen that the issue does not appear within two weeks and then it can happen several times a day. Unfortunately this makes our build pipeline completely unstable. We moved relatively shortly to Azure Pipelines (3 months ago) and this issue existed from the beginning.

Related issues might be:
https://github.com/dotnet/core/issues/5884
https://githubmemory.com/@RussellLMiller

Can you give us any tips how we can tackle this issue? 
What could be the reason that the NuGet restore thinks that the nuget.org-repo has no valid timestamp or timestamp signature/certificate?

Thank you in advance.

**Comment by zivkan** [comment] 2021-11-12 15:41
This is documented on the help page for NU3028, which is one of the errors provided in your output: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028

Does this help you resolve the problem?

**Comment by heng-liu** [comment] 2021-11-12 18:20
According to the above document, could you "[Retry untrusted root failures](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#retry-untrusted-root-failures)" by setting `NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY`?
It's available in .NET 6 preview5 and later versions.

**Comment by czdietrich** [comment] 2021-11-15 11:41
Thank you for your response. This seems extremely helpful and could explain the sporadic nature of this issue.

I will give setting the environment variable a shot to see whether this would fix the issue for us. But probably I won't be able to use .NET 6 SDK for all of our solutions, since a still supported older solution uses .NET Core 3.1 with CPVM which has breaking changes with .NET 5 SDK. But as I understand correctly I might try to implement the retry logic myself by repeating `dotnet restore` command several times if it fails, which might be good enough.

Since the issue only occurs now and then, it will take some time until I can tell for sure whether the bug is fixed using this workaround.

By the way the error text seems not to be up to date for the given error code in the knowledge base website. Maybe it could be updated there.

**Comment by heng-liu** [comment] 2021-11-15 20:04
Thanks @czdietrich for the reply!
I'm not sure if adding retry for dotnet restore would work or not. Because if there are many packages needs to be verified, and one fails the chain building, then you have to retry the dotnet restore.
Comparing to retry for each call of chain building, retry for the whole work might not be that ideal.

**Comment by heng-liu** [comment] 2021-11-15 20:09
This is a duplicate of https://github.com/NuGet/Home/issues/11099
The workaround is in .NET 6 Preview5 and VS 17.0 Preview 5

**Closed as completed by heng-liu** 2021-11-15 20:09 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Signing
