### ISSUE TITLE
Native package targets reference in .vcxproj uses solution path rather than $(SolutionDir)

### ISSUE THREAD

**Issue by AnEnglishmanInNorway** [NuGet/Home#915] opened 2015-07-10 10:26 UTC
I use CoApp to create a native package. CoApp delivers an MSBuild targets file which the NuGet VS extension adds to the vcxproj file, referring to it in several places in constructions like this example:

```
Exists('..\packages\KM.SomePackage.0.0.2\build\native\KM.SomePackage.targets')
```

However, if the vcxproj project files are located somewhere some way off the solution folder (as might happen if they are included in several different solutions) then those references might look like this:

```
Exists('..\..\solutions\pete\packages\KMSomePackage.0.0.2\build\native\KM.SomePackage.targets')
```

Doing that makes it impossible to use a project in several solutions! What it surely should do is something like this?

```
Exists('$(SolutionDir)\packages\KM.SomePackage.0.0.2\build\native\KM.SomePackage.targets')
```

**Comment by yishaigalatzer** [comment] 2015-07-10 19:19
This is something we are resolving in NuGet3 and project.json (which doesn't yet support vcxprojects).

The problem is that SolutionDir is not the solution because it is configurable as well using `nuget.config`.
Unfortunately this is a known limitation of nuget, and you could of course for your scenario change the project manually as a workaround.

**Comment by AnEnglishmanInNorway** [comment] 2015-07-13 06:52
I really don't think a manual edit is a good idea. The whole advantage of NuGet is that the import of packages is fully automated (and works just as nicely on a TFS build). In an environment with many programmers we don't want arbitrary individual changes.

You're referring to the capability to change repositoryPath, I assume. That's a capability I hadn't noticed. Perhaps I can figure out a way of using it to solve the issue. Throughout many years I have considered it quite normal for projects to be included in multiple solutions, so I think the whole business of making a project file refer to a solution file is not particularly nice. Perhaps the vcxproj should rather refer to the repository relative to itself?

BTW I notice one other glitch in the native projects support. On a clean build (e.g. a TFS build), if the first project built needs packages then it will fail - because the downloaded .targets file in the package is not present before the build. Of course, a workaround is to have a dummy first project, on which all the others depend, whose only function is to force the package download. Might be worth mentioning somewhere in some documentation.

**Comment by davidfowl** [comment] 2015-07-13 07:36
@AnEnglishmanInNorway Did you read http://docs.nuget.org/Consume/Package-Restore/Team-Build?

**Comment by AnEnglishmanInNorway** [comment] 2015-07-13 12:34
No, David, I hadn't seen that - the first section basically explains my "glitch". Thanks for the tip. I think I'll maybe stick to that initial empty "GetSolutionPackages" project, which seems to do the trick and is nicely visible in the UI to an incoming maintenance programmer (or to myself after a few weeks elsewhere, when the trick has fallen out of short term memory!) But I can use the restore-everything command line in a prebuild event to avoid having to maintain that project with the individual packages I need.

**Comment by yishaigalatzer** [comment] 2015-07-13 16:02
The issue is with the way add reference works. NuGet calls add reference because it doesn't attempt to understand the projects, which means the project system ends up adding the references and you end up with these paths.

The advantage of a relative path is that the solution works when cloned on different machines, you obviously get the downside of they don't work across different solutions (unless you restored for the original project/solution folder directly).

I agree that there is a significant downside to editing projects, but unfortunately with the current approach of NuGet there is not much we can do.

We do have a way forward to resolve this issue, by creating a global packages folder per machine. Which means the projects are not being edited at all. We are starting to implement it for some of the C#/VB project systems, and in discussions with the C++ team, when that materializes this problem should get resolved as well. 

But at this point I don't see that we could do much better than what we have, without breaking existing scenarios.

**Closed** 2018-02-02 00:47 UTC
Labels: Type:Feature
