### ISSUE TITLE
dotnet restore fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#8667] opened 2019-10-07 21:26 UTC
_From @luhis on Friday, October 4, 2019 3:31:13 PM_

I have updated my site to dotnet core 3.0, but it fails to restore the packages.  Dotnet restore just hangs.  Reverting back to my old core 2.2 version worked.  I tried using a brand new Ubuntu Server 16.04 image and it restored just fine.  It looks like a similar issue to this https://github.com/dotnet/cli/issues/11560 however setting MSBUILDDISABLENODEREUSE=1 made no difference

## Steps to reproduce
git clone https://github.com/luhis/CodeGolf.git
cd CodeGolf
dotnet restore

## Expected  behavior
nuget packages would be restored

## Actual behavior
Process hangs and never completes

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.                                                              App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

_Copied from original issue: dotnet/cli#12808_

**Comment by kartheekp-ms** [comment] 2019-10-10 01:24
@luhis Provide us additional output by executing `dotnet build -v:diag` command on the Linux machine where dotnet restore hangs. This issue appears to be similar to dotnet/cli#11560 but would like to review diagnostics to understand the issue better.

**Comment by luhis** [comment] 2019-10-10 06:50
Attached is the result of just attempting to build the CodeGolf.Domain project.  It still hangs, but the logs look successful to me.

[luhis.txt](https://github.com/NuGet/Home/files/3710841/luhis.txt)

**Comment by kartheekp-ms** [comment] 2019-10-10 23:22
@luhis - Thanks for sending us the logs. We are working on our end to reproduce this issue and in the mean time can you please provide us the logs by disabling [`MSBUILDDISABLENODEREUSE`](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/MSBuild-Tips-&-Tricks.md#environment-variables) environment variable. We would like to compare both logs and plan the next steps.

**Comment by luhis** [comment] 2019-10-13 13:13
@kartheekp-ms the previous log had MSBUILDDISABLENODEREUSE disabled, here are the logs with it enabled: 
[luhis (1).txt](https://github.com/NuGet/Home/files/3721762/luhis.1.txt)

**Comment by kartheekp-ms** [comment] 2019-10-14 18:32
I am unable to reproduce this issue on new Linux VM (Ubuntu 16.04) as mentioned by @luhis in initial comments.Restore completed successfully for all the `.csproj` files in the CodeGolf repo.

Executed `dotnet build -v:diag` without setting `MSBUILDDISABLENODEREUSE`  environment variable on the CodeGolf repo. Noticed from the attached log file that restore completed successfully for all the `.csproj` files even though build failed due to various reasons in the unit test project which is out of our scope.
[8667.zip](https://github.com/NuGet/Home/files/3725859/8667.zip)

/cc @livarcocc @rainersigwald @jeffkl - Looks an MSBuild issue. Please help us investigate further.

**Comment by kartheekp-ms** [comment] 2019-10-22 18:30
@luhis - Please send us the memory dump for the hanging dotnet process so that @rainersigwald and team can help us investigate this issue further. See [doc](https://github.com/Microsoft/ProcDump-for-Linux) to lean more about creating core dumps in Linux.

**Comment by luhis** [comment] 2019-10-22 20:36
@kartheekp-ms  Memory dump attached.

**Comment by kartheekp-ms** [comment] 2019-10-23 23:08
@luhis - Thanks for sending us the requested info. I have deleted the dump file as I am unsure if it contains sensitive information (e.g.:  PII, secrets).

**Comment by luhis** [comment] 2019-10-28 13:33
Over the weekend I formatted the VPS server, Core 3.0 still hangs on restoring packages, so it looks like there's some incompatibility between core 3.0 and the Ubuntu image.  I will try to get more information from my hosting provider.

**Comment by luhis** [comment] 2019-10-29 07:14
I had another think last night, and i found this issue https://github.com/dotnet/coreclr/issues/26873

It could be that it's related to the VPS (also OpenVZ), more than Ubuntu, that would explain why it still fails after formatting the machine

**Comment by nkolev92** [comment] 2020-05-07 17:07
@luhis 

Are you still having problems here?
Was the linked issue the root cause of the problem?

Thank you!

**Comment by luhis** [comment] 2020-05-07 21:11
@nkolev92 
It turned out that the problem was the underlying Linux host on the virtualisation system, not a problem with dotnet

**Comment by nkolev92** [comment] 2020-05-07 21:15
Sounds good. 

Thank you for following up. 

Closing this as external.

**Closed as completed by nkolev92** 2020-05-07 21:15 UTC
Labels: Resolution:External, Functionality:Restore, Product:dotnet.exe, Tenet:Reliability
