### ISSUE TITLE
[PM UI] Transitive dependencies list is not updated after direct dependency update

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#12599] opened 2023-05-18 16:33 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Version 17.6.0 Preview 3.0 [33520.578.main]

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Create a new project
2. Install package NuGet.Packaging version 6.6.0
3. Open PM UI. Checkout the transitive dependencies list. The tooltip for the transitive origins correctly shows NuGet.Packaging version 6.6.0. The version number of the transitive package also is correct (for example NuGet.Common version 6.6.0).
4.  Downgrade NuGet.Packaging to version 5.0.2
5. Now look at the list of transitive packages again. The tooltip for transitive origins still shows NuGet.Packaging version 6.6.0 (which is now wrong). The version of the transitive package is also outdated (for example, NuGet.Common version 6.6.0).

![image](https://github.com/NuGet/Home/assets/16807822/14e2259e-ac09-4d01-ae4c-38440d4b0318)

**Comment by jebriede** [comment] 2023-05-19 22:18
@skofman1 thanks for reporting this. This behavior is the same issue that was fixed in this pull request: https://github.com/NuGet/NuGet.Client/pull/5117. It looks like the version you are using does not have this fix. Can you try upgrading to a new version and try again? I just tried to reproduce this on 17.7 and it did not repro for me. Here's the state of the packages list after following the repro steps:

![image](https://github.com/NuGet/Home/assets/10777837/37660bc0-1ba4-4e64-9965-28b208e97bb5)

**Comment by skofman1** [comment] 2023-05-19 22:37
@jebriede , tried on 17.7 preview 2 and couldn't repro. Feel free to close :)

**Comment by jebriede** [comment] 2023-05-19 22:53
> @jebriede , tried on 17.7 preview 2 and couldn't repro. Feel free to close :)

That's great! Thanks for the follow-up.

**Comment by jebriede** [comment] 2023-05-19 22:53
Closing as fixed by: https://github.com/NuGet/NuGet.Client/pull/5117. The fix addressed a number of symptoms, including the transitive origins not updating. As such, in latest versions that have the fix, the bug does not reproduce.

**Closed as completed by jebriede** 2023-05-19 22:53 UTC
Labels: Type:Bug, Resolution:NotRepro
