### ISSUE TITLE
`msbuild /t:restore` should give better message when project is packages.config

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#7604] opened 2018-12-07 18:09 UTC
Currently when you run `msbuild /t:restore` against a project that uses packages.config, you get the message:

> The project "MyProject" is not selected for building in solution configuration "Debug|Any CPU".

This makes me think that doing a `msbuild /t:build` should also give the same message, but in fact the project does build.

We should look into changing the reported message to say something like 

> The project "MyProject" uses packages.config which cannot be restored through msbuild.

Only report the "not selected for building in solution configuration" if a `/t:build` would report the same message.

**Comment by nkolev92** [comment] 2018-12-07 19:41
I don't think this is NuGet: 
`
The project "MyProject" is not selected for building in solution configuration "Debug|Any CPU".
`
This is just an msbuild goo, which could have been caused by multiple issues. 

Regarding the issue in general: 
The indicator that a project uses packages.config is the existence of packages.config or packages.projectName.config files.
Any improvement to this message would add some additional perf hit.
An important thing when considering this is that there are projects that are not "NuGet" configured. 

The simplest fix(that won't take a perf hit) would be to just write an explicit log message saying projects 1,2,3 will be skipped because they are not PackageReference.

**Comment by rrelyea** [comment] 2019-01-07 20:17
@nkolev92 has started a fix for this.

**Comment by nkolev92** [comment] 2019-10-17 21:21
Closing in favor of https://github.com/NuGet/Home/issues/8506

**Closed as completed by nkolev92** 2019-10-17 21:21 UTC
Labels: Type:Feature, Functionality:Restore
