### ISSUE TITLE
Provide a means of specifying that a package is incompatible with another package

### ISSUE THREAD

**Issue by madelson** [NuGet/Home#10250] opened 2020-11-10 19:11 UTC
It would be helpful to be able to specify in the package metadata that a particular package is incompatible with another package or with a range of versions of another package. 

Here is the use-case we have:
* We have a widely-used internal package "Monolith" which has many dependencies. We want to break up this package into smaller, more granular packages with minimal impact on existing consumers.
* To achieve this, we created a number of smaller packages "MicroPackage1", "MicroPackage2", .. "MicroPackageN" containing the various types that used to live in Monolith. We also added type forwards to Monolith.dll so that other packages that reference Monolith still work when installed in an app using the latest Monolith.

Where this breaks down is if an app using an _old_ version of Monolith installs a package which takes MicroPackage1 as a dependency. The problem is that the latest Monolith depends on MicroPackage1, but there is no way for MicroPackage1 to communicate that it is not compatible with older versions of Monolith.

We've seen this need come up in other cases as well, basically whenever we need to perform some kind of migration to a new package structure.

It would be nice to be able to express these incompatibilities in the nuspec such that consumers would find out about them upon trying to install the package.

Details (probably not relevant for this feature request):

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): GeneratePackageOnBuild target (with .nuspec file).

NuGet version (5.7.0):

OS version (i.e. win10 v1607 (14393.321)): Windows 10

**Comment by zkat** [comment] 2020-11-23 21:23
Closing as duplicate of https://github.com/NuGet/Home/issues/10058. Please add further comments and your upvotes there!

**Closed as completed by zkat** 2020-11-23 21:23 UTC
Labels: Type:Feature, Functionality:Pack
