### ISSUE TITLE
regression from 4.3 - nuget install w/ excludeversion flag fails in many cases

### ISSUE THREAD

**Issue by jaknor** [NuGet/Home#6256] opened 2017-12-05 12:52 UTC
## Description
Hi, we have started receiving errors when trying to install a nuget package in some of our build scripts.

Our build scripts downloads the latest version of nuget.exe from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe. It uses that to install and restore packages in our solutions. When nuget 4.4.1 was released we started getting errors when building some of the solutions. The error message is "An item with the same key has already been added.".

After some investigation I have narrowed it down to the following. For one of our packages we install the package using the -excludeVersion flag. This seems to be causing an issue if you have multiple versions of the same package in your packages folder.

## Details about Problem

Product: NuGet.exe

Version: 4.4.1 & 4.5.0

OS version: Win10 v1607 (14393.1770)

Worked before? If so, with which NuGet version:
Yes in version 4.3.0

## Detailed repro steps so we can see the same problem

Please see this repository: https://github.com/jaknor/NugetError

### Verbose Logs

NuGet Version: 4.4.1.4656
Feeds used:
  http://nuget.moonpig.com/nuget
  https://api.nuget.org/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installing package 'stylecop.msbuild' to 'packages'.
  GET http://nuget.moonpig.com/nuget/FindPackagesById()?id='stylecop.msbuild'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3/registration3-gz-semver2/stylecop.msbuild/index.json
  OK http://nuget.moonpig.com/nuget/FindPackagesById()?id='stylecop.msbuild'&semVerLevel=2.0.0 22ms
  OK https://api.nuget.org/v3/registration3-gz-semver2/stylecop.msbuild/index.json 410ms

Attempting to gather dependency information for package 'stylecop.msbuild.5.0.0' with respect to project 'packages', targeting 'Any,Version=v0.0'
Package stylecop.msbuild from source MoonpigNuget gathered from cache.
Package stylecop.msbuild from source Microsoft Visual Studio Offline Packages gathered from cache.
Package stylecop.msbuild from source nuget.org gathered from cache.
  GET http://nuget.moonpig.com/nuget/FindPackagesById()?id='NewId'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3/registration3-gz-semver2/masstransit/index.json
  GET http://nuget.moonpig.com/nuget/FindPackagesById()?id='MassTransit'&semVerLevel=2.0.0
  GET http://nuget.moonpig.com/nuget/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3/registration3-gz-semver2/newid/index.json
  GET https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/index.json
  OK http://nuget.moonpig.com/nuget/FindPackagesById()?id='NewId'&semVerLevel=2.0.0 27ms
  OK http://nuget.moonpig.com/nuget/FindPackagesById()?id='MassTransit'&semVerLevel=2.0.0 34ms
  OK http://nuget.moonpig.com/nuget/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0 38ms
  OK https://api.nuget.org/v3/registration3-gz-semver2/newid/index.json 118ms
  OK https://api.nuget.org/v3/registration3-gz-semver2/masstransit/index.json 195ms
  GET http://nuget.moonpig.com/nuget/FindPackagesById()?id='GreenPipes'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3/registration3-gz-semver2/greenpipes/index.json
  GET http://nuget.moonpig.com/nuget/FindPackagesById()?id='Newtonsoft.Json.Bson'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json.bson/index.json
  OK http://nuget.moonpig.com/nuget/FindPackagesById()?id='GreenPipes'&semVerLevel=2.0.0 19ms
  OK http://nuget.moonpig.com/nuget/FindPackagesById()?id='Newtonsoft.Json.Bson'&semVerLevel=2.0.0 19ms
  OK https://api.nuget.org/v3/registration3-gz-semver2/greenpipes/index.json 101ms
  OK https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json/index.json 407ms
  OK https://api.nuget.org/v3/registration3-gz-semver2/newtonsoft.json.bson/index.json 394ms
Total number of results gathered : 25
Gathering dependency information took 653.04 ms
Summary of time taken to gather dependencies per source :
packages        -       9.38 ms
http://nuget.moonpig.com/nuget  -       160.48 ms
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\    -       39.48 ms
https://api.nuget.org/v3/index.json     -       1.27 sec
An item with the same key has already been added.
System.InvalidOperationException: An item with the same key has already been added. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NuGet.PackageManagement.PrunePackageTree.PruneDowngrades(IEnumerable`1 packages, IEnumerable`1 packageReferences)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__65.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__40.MoveNext()

### Sample Project

Please see this repository: https://github.com/jaknor/NugetError

**Comment by jainaashish** [comment] 2017-12-05 22:31
Thanks @jaknor for detailed explanation and repro solution. There was an issue https://github.com/NuGet/Home/issues/2405 which was fixed in 4.4 to get the right behavior for `excludeVersion` flag. You might be hitting this if you already have multiple versions of the same package in packages folder.

Also looking at your repro solution, i can see there is a potential regression with 4.4 or 4.5 which will try to fix with next release. But can you also tell us what is your specific requirement to have some packages with version and some with `excludeVersion`? Even to workaround your current scenario, if you clean the packages folder and then try to install this package, then it will work.

**Comment by jaknor** [comment] 2017-12-06 11:32
Hi @jainaashish thanks for your reply. 

This part of our build script was developed a few years ago and the person who wrote them is no longer around so I can't say for sure why he set it up this way. 

It looks like we are trying to ensure we are using the latest version of the stylecop.msbuild package while at the same time being able to reference the path of the package in some of our configuration and not having to update the path when the version of the stylecop package changes. 

We are looking at moving away from this set up of stylecop which will remove this requirement but at the moment it is causing our builds to fail. 

A few of the solutions that uses this build script doesn't have all our their packages consolidated so just deleting it from the packages folder is not an option as it will be restored again. For now we will keep using nuget 4.3 and once we have managed to consolidate all the packages (or there is a fix for nuget) we will move back to the latest version.

If you need any more details please let me know.

**Closed as completed** 2018-01-29 20:35 UTC
Labels: Priority:1, help wanted, Functionality:Install, RegressionFromPreviousRTM

**Comment by piers7** [comment] 2018-03-28 08:31
Based on playing a fun game of follow-the-commit, it seems that surely this should be tagged with the 4.7 milestone, not backlog:

https://github.com/NuGet/NuGet.Client/commit/b7894380f06bd6fb9ee050a1348fb0dd44c367ca

Aside: when end-users arrive here they're already _distinctly unimpressed_ that something's not working, added to by however hard they found it to locate this issue. Making them jump through hoops to determine if the fix is/isn't in a release they can download is like rubbing salt in the wound and poking them in the eye at the same time.

**Comment by thashepherd** [comment] 2018-03-28 16:04
For what it's worth, this bug/regression/change is preventing us from upgrading our build servers past NuGet 4.3 (some of the complexity in our build scripts makes the workaround impractical, or at least nontrivial).

**Comment by jainaashish** [comment] 2018-03-28 17:16
This will be part of 15.7 preview3 bits and then subsequently 15.7 rtm release.

**Comment by thashepherd** [comment] 2018-08-01 20:08
I don't believe that the fix in NuGet 4.7 is a complete solution as this problem is still occurring post-upgrade. In my specific test case, running `nuget install library_a -excludeversion` failed with the message `An item with the same key has already been added` when the output directory contains, for example, both `Gelf4Net2.0.3.3` and `Gelf4Net2.0.3.15` (so you can probably guess where that bug is happening).

**Comment by pvandervelde** [comment] 2019-01-07 01:52
@jainaashish has this been confirmed fixed because we're still seeing this with NuGet 4.9.2. Should I open a new bug for this?

**Comment by jainaashish** [comment] 2019-01-07 17:45
Yes please open a new bug with repro steps.
