### ISSUE TITLE
Unable to add release package with pre-release dependency in Visual Studio Nuget UI for packages.config projects

### ISSUE THREAD

**Issue by iUnknwn** [NuGet/Home#6991] opened 2018-05-31 23:14 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Created packages (that dual target Framework 4.6 and Core 2.0) using dotnet pack command. The package relies on a pre-release package available on nuget.org.

Issue occurs using VS UI (Visual Studio 15.3.4)

NuGet version (x.x.x.xxx):
Package Manager Console Host Version 4.3.1.4445

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.3.4

OS version (i.e. win10 v1607 (14393.321)): 10.0.16299

Worked before? If so, with which NuGet version: Unknown

## Detailed repro steps so we can see the same problem

1. Create a package that dual targets netframework and netcore, and has a pre-release dependency. This is what's in the csproj file:
```
<PropertyGroup>
    <TargetFrameworks>netstandard2.0;net46</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.0.0-alpha2" />
  </ItemGroup>
```

2. Create package using `dotnet pack`

3. Place packages somewhere on system (I'm using a network share).

4. Create a new .NET Framework project in Visual Studio.

5. Open "Manage Nuget Packages" 

6. Add the location of your packages as a source, and check enable pre-release. 

7. Attempt to install the package. 

```
Attempting to resolve dependencies for package 'A.B.SimpleRemoteClient.1.1.0' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'SharpZipLib 0.86.0' is not compatible with 'A.B.SimpleRemoteCommonLibrary 1.1.0 constraint: SharpZipLib (>= 1.0.0-alpha2)'.
Time Elapsed: 00:00:07.9651876
```

## Other suggested things
If I create a .NET Core console app in VS, this works without issue.

**Comment by nkolev92** [comment] 2018-06-01 18:45
I change the title, as you are using packages.config in this case. 

This is a known packages.config restriction. 

This is a duplicate of https://github.com/NuGet/Home/issues/2944

Please note that .NET Framework projects do support PackageReference. 
And you can still install your package in .NET Framework PackageReference projects.

**Closed as completed by nkolev92** 2018-06-01 18:45 UTC
Labels: Resolution:Duplicate, Functionality:Restore, Style:Packages.Config
