### ISSUE TITLE
Init.ps1 isn't executed for .NET Core tools packages

### ISSUE THREAD

**Issue by bricelam** [NuGet/Home#3023] opened 2016-06-22 19:08 UTC
The `Microsoft.EntityFrameworkCore.Tools` package has an `tools/init.ps1` file. On .NET Core projects, this is typically added to the `project.json` under the `tools` section.

``` JSON
{
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  }
}
```

However, `init.ps1` is not executed for packages under this node, so when you try to run the `Add-Migration` command, you get the usual PowerShell error:

> The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable
> program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
# Workaround

To workaround this issue, users also need to add the `Microsoft.EntityFrameworkCore.Tools` package to the `dependencies` section.

``` JSON
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  }
}
```

cc @rowanmiller @natemcmaster

**Comment by bricelam** [comment] 2016-06-22 22:42
This issue might be more general. Closing VS and re-opening the solution after applying the workaround also didn't execute `init.ps1`.

**Comment by natemcmaster** [comment] 2016-06-22 22:44
@bricelam possible related to https://github.com/NuGet/Home/issues/1292?

**Comment by bricelam** [comment] 2016-06-22 23:25
Wait... it just worked without it under the `dependencies` section. Apparently, it's just very flaky.

**Comment by bricelam** [comment] 2016-06-22 23:37
Environment info:

| &nbsp; | Version |
| --: | --- |
| **Windows** | 10586.420 |
| **VS** | 14.0.25420.01 Update 3 |
| **NuGet** | 3.5.0.1484 |
| **.NET Core Tools** | 14.1.20621.0 |

**Comment by rrelyea** [comment] 2016-06-22 23:40
seen the related repro (add-migrations not a known command) on 3 update 3 machines. van's, chris' and brice's. van/chris' machines had 3.4.4 installed. So if this was caused by NuGet, was broken by 3.4.4 or before.

**Comment by rrelyea** [comment] 2016-06-23 01:07
@joelverhagen investigated and also talked with @emgarten 

Currently, they think:
- init.ps1 will only be run on dependencies, not tools.
- Tools was designed for dotnet.exe extensibility, not PMC.

**Comment by rrelyea** [comment] 2016-06-23 21:38
No NuGet change necessary for b2 here. Design discussion to come post beta2 to understand right way for EF to do thia.

**Comment by rowanmiller** [comment] 2016-06-23 22:35
Agreed on the `tools` section part being post-beta2. Do we understand what was happening when init.ps1 wasn't getting run when the package was listing in `dependencies`?

**Comment by joelverhagen** [comment] 2016-06-23 22:48
@rowanmiller, I was unable to reproduce this issue. Scenarios attempted:
1. `.Tools` in `"tools"` but not `"dependencies"`. PMC command never resolved.
2. `.Tools` in `"tools"` and in `"dependencies"`. PMC always resolved.
3. _#_1 and _#_2 with both opened and closed on VS startup. 

One "gotcha" is that if, at any point during a PMC lifetime, you have `.Tools` in the "dependency" node, the PMC command will be added to the PMC session. If you remove `.Tools` from the "dependency" node, the PMC state remains. This allows you to get into a state where the command is available even though your project.json only has `"tools"`. If you restart VS, the PMC state is reset so the command will no longer be available. Another strange example of this PMC state is if you close your project, the PMC commands will still be example (at least in my experimentation).

**Comment by rowanmiller** [comment] 2016-06-23 23:14
@joelverhagen ok sounds good. We saw it on one machine, but maybe it was just a one-off issue.

**Comment by PatrickMcvay** [comment] 2016-07-08 17:03
So, I have found something interesting about this problem. This will actually fix the EntityFramework.Tools not working. First, here is what I did. I made a new project and made a copy of the project.json, then I closed the solution and reopened it. To my surprise, my project.json was completely in a different order. 

Before closing project.json

```
{
  "userSecretsId": "aspnet-CalibrationApp-b327aa78-d207-4a23-9c94-44b183c64a72",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.0",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

After closing solution and reopening project.json

```
{
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.0",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },
  "userSecretsId": "aspnet-CalibrationApp-b327aa78-d207-4a23-9c94-44b183c64a72"
}
```

So really you can fix the issue by keeping a fresh copy of your project.json handy, this isn't really a fix. Its more of a way to get around the issue.

**Comment by joelverhagen** [comment] 2016-07-12 16:28
After meeting offline about this, we came to the decision that we will not make this change to execute init.ps1 for tools.

The recommended way of delivering both Package Manager Console commands (in VS) and .NET CLI commands (in command line) to your customer is to have two separate packages. One package will have an init.ps1 and is to be installed as a dependency (`"dependencies"` node in project.json). Another package will have .NET CLI commands and will be installed as a tool (`"tools"` node in project.json). 

In light of the upcoming concept of the [`DotnetCliTool` package type](https://github.com/NuGet/Home/wiki/Package-Type), it will be necessary to have two packages anyway. .NET CLI tool package will be marked with the `DotnetCliTool` package type. When a package marked as `DotnetCliTool`, it cannot be installed to a non-.NET Core project (since other project types can't invoke .NET CLI tools). Therefore, if you also want the init.ps1 experience for non-.NET Core projects, you also need a package _not_ marked with the `DotnetCliTool` package type. You need a package marked with no package type at all and therefore assumed to be a dependency (which, as we know, execute init.ps1 scripts and is the existing experience).

For more details on the reasoning behind package type, take a look at the [design document](https://github.com/NuGet/Home/wiki/Package-Type).

**Closed as completed by joelverhagen** 2016-07-12 16:28 UTC
Labels: Type:Bug, Resolution:ByDesign
