### ISSUE TITLE
ExcludeRestorePackageImports=true should not exclude package path properties

### ISSUE THREAD

**Issue by timhermann** [NuGet/Home#8840] opened 2019-11-19 18:10 UTC
## Details about Problem

Visual Studio 15.9.17 and msbuild cli
NuGet version: 5.3.1.6268

OS version (i.e. win10 v1607 (14393.321)):
Win10 v1909 (18363.476)

## Detailed repro steps so we can see the same problem

1. Set ExcludeRestorePackageImports=true
2. Add `<PackageReference Include="Test.PathProperty" Version="x.x.x" GeneratePathProperty="true" />`
3. Attempt to use $(PkgTest_PathProperty) as a variable

Expected behavior:

$(PkgTest_PathProperty) is defined, but no targets or props are imported from it.

Actual behavior:

$(PkgTest_PathProperty) is not avaiable because of the propertygroup condition `<PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">`

**Comment by timhermann** [comment] 2019-11-19 18:15
This issue in VS 15.9 means those paths aren't generated in VS2017 (which IMO should be fixed/backported): #8374 - but even from the CLI msbuild this is a problem. The package has targets that I must not have included in the project, but doing so means I cannot get the path definitions because the same condition excludes those properties..

**Comment by nkolev92** [comment] 2019-11-23 00:47
Why do you need to set ExcludeRestorePackageImports? 

This is meant to be used for restore purposes so that packages' props/targets do not affect restore and potentially create a behavior that's not repeatable. 

I get that this is not in the same breath as props/targets coming from packages, but the motivation is equivalent.

**Comment by timhermann** [comment] 2019-11-26 01:55
Many packages include targets that inject behavior into the build and/or have not updated their packages to be packagereference-friendly. This is both a compliance nightmare as well as a headache to track down when something isn't working right. I need to exclude the targets that actually mess up my build, but I need to reference, copy, or transform files that are in the path. 

The property should exclude the imports - that's what it says it does. Instead, it's excluding generated properties that I have explicitly opted into creating and intend to use.

I want to use it for reliable/repeatable restore purposes, but the current design prevents that.

**Comment by nkolev92** [comment] 2019-11-27 00:37
> Many packages include targets that inject behavior into the build and/or have not updated their packages to be packagereference-friendly.

You should use Include/Exclude assets for those purposes. 
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

> The property should exclude the imports - that's what it says it does. Instead, it's excluding generated properties that I have explicitly opted into creating and intend to use.

I get the name is not perfect, but this is really a NuGet internal that basically means packages' targets cannot not affect restore.

**Comment by nkolev92** [comment] 2019-12-31 00:34
Closing this as by design per the above comments.

**Closed as completed** 2020-03-18 22:53 UTC
Labels: Resolution:ByDesign, Functionality:Restore, Style:PackageReference
