### ISSUE TITLE
Updating packages applies assembly binding redirects to all projects, including class libraries

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#2748] opened 2016-05-09 18:33 UTC
Updating packages having binding redirects, such as Json.Net or Azure SDK, is causing adding app.config to all projects, including class libraries (DLLs) what doesn't make sense to me. I delete them after each update what is unnecessary chore.

I'd like this command to be smart enough to distinguish project types/kinds, such as Console apps, Web apps or Test projects, and update/add config only there. I believe [project type guids](http://stackoverflow.com/questions/2911565/what-is-the-significance-of-projecttypeguids-tag-in-the-visual-studio-project-fi) can be leveraged here.

Also VS settings to enable/disable applying binding redirects can be enhanced to use a radio button (either update all, update smarter, or update none) or a checkbox (Update in Web apps, Update in Windows apps, etc.)

**Comment by davidmatson** [comment] 2016-05-11 16:43
This recently hit us as well. We end up doing manual cleanup to remove unnecessary app.config files from DLL projects, but because this is manual work we sometimes make mistakes. We ended up removing one from an exe project that needed it, but to make matters worse, it only needed it in exception scenarios. We ended up wasting a couple of days tracking down the root cause. Any chance we could bump the priority of this issue?

Thanks,

David

**Comment by abatishchev** [comment] 2016-06-27 18:04
Is it something you could address in the mid-future, please?

**Comment by abatishchev** [comment] 2016-07-13 23:30
What is the timeline to address this?

**Comment by rrelyea** [comment] 2016-07-13 23:59
3.6 is targeted for November. We currently do not plan to do this in that release, as our backlog is very full.
Beyond that, do not know.
Like the idea. Understand the need.

**Comment by abatishchev** [comment] 2016-09-21 23:54
Folks, will this ever end?

![nuget-asm-bi-red-1](https://cloud.githubusercontent.com/assets/351644/18732984/1d1853de-801c-11e6-9d45-b6e68e3425a9.PNG)

**Comment by stas-lucky** [comment] 2017-04-12 14:57
This helped: 
1. Go to Tools --> Options... --> NuGet Package Manager --> General
2. Uncheck "Skip applying binding redirects" checkbox 

I use VS2015 Pro Update 3 (version 14.0.25431.01)
NuGet Package Manager version is 3.4.4

Hope that help

**Comment by abatishchev** [comment] 2017-04-12 15:03
I would say this is a workaround. The solution would be 'smart' binding redirects that take into consideration project's guid so don't apply them on dll projects other than tests.

**Comment by stas-lucky** [comment] 2017-04-13 20:04
At least it solves problem with adding number of files on each nuget update.
I understand that sometimes changes are really required in config files. Then you need to remember about that and in case of any problems after adding (updating) NuGet packages just disable checkbox temporally again and try to update the packages.
Having real 'smart' solution would be good, but for now this is only what we have.

**Comment by jainaashish** [comment] 2018-02-02 04:35
Binding redirects are not even supported for new package format like `PackageReference` so I'm closing it in that respect.

**Closed as completed by jainaashish** 2018-02-02 04:35 UTC
Labels: Type:DCR, Resolution:ByDesign

**Comment by abatishchev** [comment] 2018-02-02 04:41
Does adding it to the 4.6 milestone mean it might be addressed?

**Comment by jainaashish** [comment] 2018-02-02 05:43
No, it indicate what milestone we close it.

**Comment by abatishchev** [comment] 2018-02-02 17:58
It's sad that the only prescribed solution for this (annoying for years) issue is to upgrade to the .net build system. Numerous projects (including Microsoft internal) don't plan to do that in near future, numerous won't do that ever.
