### ISSUE TITLE
disabledPackageSources seems not working

### ISSUE THREAD

**Issue by tanaka-takayoshi** [NuGet/Home#6155] opened 2017-11-10 07:43 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
.NET Core CLI on CentOS 

NuGet version (x.x.x.xxx):
```
$ dotnet nuget --version
NuGet Command Line
4.3.0.5
```

dotnet.exe --version (if appropriate):
```
$ dotnet --version
2.0.0
```

VS version (if appropriate):
N/A

OS version (i.e. win10 v1607 (14393.321)):
```
$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
```

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Add NuGet.Config at the project foler

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
   <packageSources>
       <add key="MyRepo" value="/tmp/NuGetScratch" />
   </packageSources>
   <disabledPackageSources>
        <add key="https://api.nuget.org/v3/index.json" value="true" />
   </disabledPackageSources>
</configuration>
```

2. restore the project

```
//clear the NuGet cache
$ rm -rf /tmp/NuGetScratch/*
$ dotnet nuget locals all --clear
//restore
$ dotnet restore
```

This is a test scenario to confirm disabledPackageSources works well. I expect any packages can't be downloaded. However, the project can be restored from nuget.org though I specified in ``disabledPackageSources``.

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by rrelyea** [comment] 2017-11-10 18:08
Dupe of https://github.com/NuGet/Home/issues/5704.
Yes, please upgrade to 2.0.2 of .net core sdk, and that is fixed.

**Closed as completed by rrelyea** 2017-11-10 18:08 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Restore
