### ISSUE TITLE
Can't install any package

### ISSUE THREAD

**Issue by dudeNumber4** [NuGet/Home#1546] opened 2015-10-09 18:59 UTC
Using Visual Studio 2015, Package Manager Console Host Version 3.2.0.1051.  Large solution with many .dlls, the project I'm trying to add a package to is an ASP.NET MVC web application.  Same result attempting to install any package.  Recently upgraded solution following steps here (http://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore), no difference.  Here is the output:

Attempting to gather dependencies information for package 'Microsoft.OWIN.Cors.3.0.1' with respect to project 'Web\Company.Project.Web', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Microsoft.OWIN.Cors.3.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.OWIN.Cors.3.0.1'
Resolved actions to install package 'Microsoft.OWIN.Cors.3.0.1'
Removed package 'Microsoft.Owin.3.0.0' from 'packages.config'
Successfully uninstalled 'Microsoft.Owin.3.0.0' from Company.Project.Web
Adding package 'Microsoft.AspNet.Cors.5.0.0' to folder 'C:\projects\ProductGroup\ProductName\packages'
Added package 'Microsoft.AspNet.Cors.5.0.0' to folder 'C:\projects\ProductGroup\ProductName\packages'
Added package 'Microsoft.AspNet.Cors.5.0.0' to 'packages.config'
Successfully installed 'Microsoft.AspNet.Cors 5.0.0' to Company.Project.Web
Adding package 'Microsoft.Owin.3.0.1' to folder 'C:\projects\ProductGroup\ProductName\packages'
Added package 'Microsoft.Owin.3.0.1' to folder 'C:\projects\ProductGroup\ProductName\packages'
Added package 'Microsoft.Owin.3.0.1' to 'packages.config'
Successfully installed 'Microsoft.Owin 3.0.1' to Company.Project.Web
Adding package 'Microsoft.Owin.Cors.3.0.1' to folder 'C:\projects\ProductGroup\ProductName\packages'
Added package 'Microsoft.Owin.Cors.3.0.1' to folder 'C:\projects\ProductGroup\ProductName\packages'
Added package 'Microsoft.Owin.Cors.3.0.1' to 'packages.config'
Successfully installed 'Microsoft.Owin.Cors 3.0.1' to Company.Project.Web
**Install failed. Rolling back...**
Removed package 'Microsoft.Owin.Cors 3.0.1' from 'packages.config'
Removed package 'Microsoft.Owin 3.0.1' from 'packages.config'
Removed package 'Microsoft.AspNet.Cors 5.0.0' from 'packages.config'
Package 'Microsoft.Owin.3.0.0' already exists in folder 'C:\projects\ProductGroup\ProductName\packages'
Added package 'Microsoft.Owin.3.0.0' to 'packages.config'
Removing package 'Microsoft.Owin.Cors 3.0.1' from folder 'C:\projects\ProductGroup\ProductName\packages'
Removed package 'Microsoft.Owin.Cors 3.0.1' from folder 'C:\projects\ProductGroup\ProductName\packages'
Removing package 'Microsoft.Owin 3.0.1' from folder 'C:\projects\ProductGroup\ProductName\packages'
Removed package 'Microsoft.Owin 3.0.1' from folder 'C:\projects\ProductGroup\ProductName\packages'
Removing package 'Microsoft.AspNet.Cors 5.0.0' from folder 'C:\projects\ProductGroup\ProductName\packages'
Removed package 'Microsoft.AspNet.Cors 5.0.0' from folder 'C:\projects\ProductGroup\ProductName\packages'
install-package : '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
At line:1 char:1
- install-package Microsoft.OWIN.Cors
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by MeniZalzman** [comment] 2015-10-12 21:13
Dupe: https://github.com/NuGet/Home/issues/1550

**Comment by MeniZalzman** [comment] 2015-10-12 21:15
we assume that what happens in your solution that one of your app.config or web.config is corrupted or empty.

**Comment by dudeNumber4** [comment] 2015-10-13 12:12
OK, finally after thrashing for hours, I got an error in the error list coming referencing the app config on a unit test project.  Something had turned that config into a whole lotta nulls.  When I restored the contents from source control and attempted nuget again, it became corrupted again - bunches of spaces before the first xml declaration and after the end of the last node.  Fixed that manually and then nuget was able to do it's thing.
It sure seems like nuget somehow corrupted the file.

**Comment by yishaigalatzer** [comment] 2015-10-13 18:56
Thanks. We will take a look on what could be the source

**Comment by yishaigalatzer** [comment] 2015-10-23 01:12
FYI we added a feature in 3.3, that will allow you to simply skip adding binding redirects. So in such cases you can just opt out.

We still need to figure out the root cause for this and fix it.

**Comment by yishaigalatzer** [comment] 2016-02-22 18:46
Closing as this was fixed, and we now have a proper error message

**Closed as completed by yishaigalatzer** 2016-02-22 18:46 UTC
Labels: Type:Bug
