### ISSUE TITLE
Installing a non-prerelease package using pre-release dependencies fails installation when packages.config is used, yet installs when PackageReference is used.

### ISSUE THREAD

**Issue by SeanFeldman** [NuGet/Home#6196] opened 2017-11-17 22:46 UTC
## Details about Problem

A non-prerelease package using pre-release dependencies fails installation when `packages.config` is used, yet installs when `PackageReference` is used. 

NuGet product used 
- [x] VS UI (VS 2017 15.4.4)
- [x] Package Manager Console (Package Manager Console Host Version 4.4.1.4633)
- [x] LinqPad

## Detailed repro steps so we can see the same problem

1. Create a new `Console App (.NET Framework)`.
1. Install [`Microsoft.Azure.CosmosDB.Table` package](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table/1.0.0) using packages.config method.
1. Installation fails complaining that a dependency `Microsoft.Azure.Storage.Common` cannot be resolved (see error in "Verbose Logs" sections).

## Other suggested things

It appears the issue is with how nuget stores the packages info.

If a project is configured to use `packages.config` this issue will manifest itself.
If a project is configured to use `PackageReference`, there's no problem with both legacy project system and the new SDK-style projects.

### Verbose Logs

>Attempting to gather dependency information for package 'Microsoft.Azure.CosmosDB.Table.1.0.0' with respect to project 'CosmosDb.TableApi.Spike', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 3.9 sec
Attempting to resolve dependencies for package 'Microsoft.Azure.CosmosDB.Table.1.0.0' with DependencyBehavior 'Lowest'
install-package : Unable to resolve dependency 'Microsoft.Azure.Storage.Common'. Source(s) used: 'nuget.org', 'LOCAL', 'MH', 'MH-dev', 'CliFallbackFolder', 'Particular MyGet', 'Microsoft Visual Studio Offline Packages', 'Microsoft Azure Service Fabric SDK'.
At line:1 char:1
>\+ install-package Microsoft.Azure.CosmosDB.Table
>\+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    \+ CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>    \+ FullyQualifiedErrorId : > NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by emgarten** [comment] 2017-11-18 00:35
This looks like a duplicate of https://github.com/NuGet/Home/issues/2944

At the time the issue above was filed nuget.exe pack would fail saying that stable packages must have stable dependencies. Since then the rule has been relaxed, but it seems like packages.config still has issues with it.

**Comment by SeanFeldman** [comment] 2017-11-18 18:15
NuGet's 1-Prerelease` vs `-IncludePrerelease` is confusing. Tools like LinqPad uses `-PreRelease` rather than `-IncludePrerelease` for example.

Also, VS default settings are not helping.
![image](https://user-images.githubusercontent.com/1309622/32983434-bb84f5ea-cc51-11e7-8003-5a7b5b2bbfa5.png)

Would the checkbox be ticked, it would at least allow format to use.

**Comment by rrelyea** [comment] 2017-11-22 00:01
@emgarten - let's discuss offline about the relaxing on pack. I remember the debate, but want to discuss timing, etc...

**Comment by albahari** [comment] 2017-11-22 04:53
Inside LINQPad, I call NuGet via the API. When the user ticks the prerelease checkbox, I instantiate ResolutionContext with includePrerelease:true. Is this correct?

**Comment by jainaashish** [comment] 2018-01-10 22:48
Dupe of https://github.com/NuGet/Home/issues/2944

**Closed as completed by jainaashish** 2018-01-10 22:48 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Functionality:Restore, Style:Packages.Config, Style:PackageReference
