### ISSUE TITLE
After initial install, closing and re-opening VS 2017 causes EF tools to not work

### ISSUE THREAD

**Issue by LwsSt** [NuGet/Home#4426] opened 2017-01-29 20:52 UTC
Initially I filed a new issue under the Entity Framwork repo ([this issue](https://github.com/aspnet/EntityFramework/issues/7507)), but I was told to file an issue here.

Copied from my original issue:

1. I install the Entity Framework Core Tools using the Package Manager Console as per the instructions in the [announcement](https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-entity-framework-core-1-1-preview-1/): Install-Package Microsoft.EntityFrameworkCore.Tools -Pre
2. The package <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0-preview4-final" /> Gets installed into my csproj file.
3. I can then use commands such as Add-Migration, Update-Database, etc. in the PMC.
4. After closing and re-opening the project in VS2017, the EF commands no longer work.
5. Running Install-Package Microsoft.EntityFrameworkCore.Tools -Pre again does not enable the commands. I have to uninstall the package and re-install to enable the commands again.

Is this expected behaviour? Or is there I command I'm missing that needs to be run to re-enable the commands in the PMC?

Further technical details
EF Core version: 1.1.0-preview4-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows
IDE: Visual Studio 2017 Community RC1

**Comment by emgarten** [comment] 2017-01-30 19:28
> Visual Studio 2017 Community RC1

Can you try updating to the latest 2017 RC3? Would you also share the version of NuGet you are using if you still see this issue? It is written to PMC when first opening the console.

**Comment by emgarten** [comment] 2017-01-30 19:28
//cc @zhili1208

**Comment by LwsSt** [comment] 2017-02-01 18:36
So I've just updated, and I'm running RC3.
The PMC version is: 4.0.0.2215

I've realized now that I've missed an important detail in my initial issue.
Usually I open VS in an empty environment. When this happens the PMC also opens an initializes. I then open my Project. In this case, the desired commands do not work.

However, if the PMC is opened (and initialized) after I open the project, the desired commands work.

In the first case, closing and opening the PMC does not fix the problem; I have to closing the PMC, then VS, then reopen my project in VS, then the PMC.

So this probably isn't a bug per se, however, I couldn't find any documentation on reloading the PMC window.

**Comment by rrelyea** [comment] 2017-02-02 19:29
Do we think this is a dupe of #4308

**Comment by joelverhagen** [comment] 2017-02-02 19:42
Yes, the root cause we diagnosed for #4308 had the very same characteristics as @Jabbersii's [most recent comment](https://github.com/NuGet/Home/issues/4426#issuecomment-276741418).

**Comment by rrelyea** [comment] 2017-02-02 21:21
marking as dupe and putting validation column then. thx.

**Closed as completed** 2017-02-03 23:59 UTC
Labels: Resolution:Duplicate, Type:Bug, Product:VS.PMConsole
