### ISSUE TITLE
Nuget API v2 & v3 Fails To Pull Packages with 503 Error

### ISSUE THREAD

**Issue by sahgilbert** [NuGet/Home#7333] opened 2018-09-27 12:43 UTC
## Details about Problem
Deploying an Asp.Net MVC solution, via AppVeyor, using Paket and Nuget API v2.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
AppVeyor & Paket 5.181.1 & .Net 4.7.1

NuGet version (x.x.x.xxx):
https://www.nuget.org/api/v2

Worked before? If so, with which NuGet version:
Always, without issue, same as current setup.

## Detailed repro steps so we can see the same problem

Create an Asp.Net Mvc project.
Add "recaptcha-aspnet" library.
Run Paket install.
Deploy via appveyor.io
Observe failure to pull packages in.

### Other points to note
It fails for almost all packages, and fails using nuget/api/v3 also.

### Appveyor Screenshots

<img width="979" alt="screenshot 2018-09-27 13 29 23" src="https://user-images.githubusercontent.com/13452745/46146588-11212f00-c25b-11e8-8ce9-07e05f0736b0.png">

<img width="988" alt="screenshot 2018-09-27 13 31 19 copy" src="https://user-images.githubusercontent.com/13452745/46146668-3ca41980-c25b-11e8-9d55-846b928f740b.png">

### Additional (Partial) Log When Running Paket Install Locally...

[20180927_NugetApiV2_503.txt](https://github.com/NuGet/Home/files/2424153/20180927_NugetApiV2_503.txt)

[20180927_NugetApiV3_503.txt](https://github.com/NuGet/Home/files/2424154/20180927_NugetApiV3_503.txt)

### Opening Line From V2 Paket Install
**_Trial1_ (NuGet.GetVersions) did not yield any results, trying again.**

**Comment by FeodorFitsner** [comment] 2018-09-27 15:14
I've been able to "catch" 503 on my local machine by constantly refreshing in the browser the following URL: https://www.nuget.org/api/v2/Packages(Id='microsoft.aspnet.razor',Version='3.2.6')

![image](https://user-images.githubusercontent.com/5041459/46155958-4d3d9b00-c22d-11e8-899a-b84d117f95d9.png)

**Comment by FeodorFitsner** [comment] 2018-09-27 15:18
cc @skofman1, @loic-sharma - guys, could you please take a look? Thank you!

**Comment by ipjohnson** [comment] 2018-09-27 16:14
+1

**Comment by skofman1** [comment] 2018-09-27 16:49
nuget.org availability is degraded. We are investigating. To unblock you from restoring packages please use our V3 protocol and use feed `https://api.nuget.org/v3/index.json`
We will keep updating https://status.nuget.org with new information.

**Comment by JVimes** [comment] 2018-09-27 17:11
@skofman1 Is there a way to use the v3 server for `nuget update -self`? It's in my CI build script. Doesn't seem to use the `-Source` parameter.

```
PS> .\nuget.exe update -self -Source https://www.nuget.org/api/v3/
Checking for updates from https://www.nuget.org/api/v2/.
The remote server returned an error: (503) Server Unavailable.
```

**Comment by joelverhagen** [comment] 2018-09-27 17:18
@JVimes, unfortunately, `nuget.exe update -self` is hard-coded to use the V2 source URL (https://www.nuget.org/api/v2). This short-coming is tracked here: https://github.com/NuGet/Home/issues/4197.

As a work-around, you could download nuget.exe from our download site using something like `Invoke-WebRequest ... -Path nuget.exe`. The "latest" URL is here:
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

The version there is currently nuget.exe 4.7.1. You can find specific versions here:
https://www.nuget.org/downloads

**Comment by IlyaFinkelshteyn** [comment] 2018-09-27 19:15
@skofman1 https://status.nuget.org/ seems green and states that it is no longer degraded. And I cannot repro this anymore. Though this issue is still open. Can we consider this resolved and update [AppVeyor status](https://appveyor.statuspage.io/)?

**Comment by skofman1** [comment] 2018-09-27 19:39
@IlyaFinkelshteyn , the problem is mitigated. Closing this issue.

**Closed as completed by skofman1** 2018-09-27 19:39 UTC

**Comment by sahgilbert** [comment] 2018-09-28 09:00
Fantastic! Big thanks to everyone involved!
