### ISSUE TITLE
PM UI:  hang installing System.Diagnostics.Debug

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#6714] opened 2018-03-20 23:16 UTC
Microsoft Visual Studio Enterprise 2017 Int Preview (2)
Version 15.7.0 Preview 2.0 [27517.0.d15.7]
VisualStudio.15.IntPreview/15.7.0-pre.2.0+27517.0.d15.7
Microsoft .NET Framework
Version 4.7.02556
Package Manager Console Host Version 4.6.0.4964

I have a memory dump.

**Comment by nkolev92** [comment] 2019-06-28 23:49
@dtivel 

Any chance you still have the info for this issue?

**Comment by nkolev92** [comment] 2019-07-19 22:30
Got the dmp offline.

I don't see a NuGet on the UI thread.

NuGet is not anywhere on the stack, but that could be because he symbols are unavailable. 

Not sure if there's anything we can here at present.

**Comment by nkolev92** [comment] 2019-07-19 23:09
Unfortunately we can't repro this anymore. 

Based on the scenario, this could've been fixed by https://github.com/NuGet/NuGet.Client/pull/2145 and might've been a duplicate of https://devdiv.visualstudio.com/DevDiv/NuGet/_workitems/edit/591458. 

Can't confirm right now, so closing this at this point.

**Closed as completed by nkolev92** 2019-07-19 23:09 UTC
Labels: Product:VS.Client, Type:Bug, Tenet:Performance, Resolution:NeedMoreInfo
