### ISSUE TITLE
Sqlite seems to be installed, but is only added to packages.config and not referenced by the Project

### ISSUE THREAD

**Issue by spetroll** [NuGet/Home#1507] opened 2015-10-02 08:02 UTC
Hi,

After installing System.Data.Sqlite with either the NuGet GUI or the console, it is still missing the references. 

```
<package id="System.Data.SQLite" version="1.0.98.1" targetFramework="net45" />
```

This is added into my `packages.config` and the corresponding folders show up in my `packages`-folder. However, in this folder there is only the `System.Data.SQLite.1.0.98.1.nupkg` file. I tried reloading VS, reinstalling the package, but the `dll` keeps missing. I can add a Reference to some external `dll` I downloaded myself, but that would defeats NuGets purpose. Is there something wrong with my system, or had someone else the same experience?

My system:
Windows 7 x64
Visual Studio Community 2015 (14.0.23107.0 D14REL)
NuGet Package Manager 3.2.0
Project is a C# Class Library and is targeting .Net 4.5

**Comment by yishaigalatzer** [comment] 2015-10-02 17:03
How did you install the package? This package has dependencies, that seem to be missing from your packages.config. The package itself has no dlls in it.

**Comment by yishaigalatzer** [comment] 2015-10-02 17:31
From what I can tell, this package does not install correctly in Visual Studio 2015 + NuGet 3.2, but does work on Visual Studio 2013

**Comment by yishaigalatzer** [comment] 2015-10-02 19:24
Actually that was just a bug in my private build of NuGet. I can see the package installed correctly and also the references

![image](https://cloud.githubusercontent.com/assets/1238711/10255625/8219ffaa-6900-11e5-9e6a-4bd7fcbe2782.png)

**Comment by spetroll** [comment] 2015-10-05 06:36
Steps I did:
- Start new Console Application
- Open PacketManager GUI
- Select System.Data.Sqlite
- Refreshed the solution explorer after install

![image](https://cloud.githubusercontent.com/assets/140701/10274267/0f066538-6b3c-11e5-812b-681333b30eb2.png)

It adds the dependencies just right, but in my project only `EntityFramework` and `EntityFramework.SqlServer` is referenced.

**Comment by yishaigalatzer** [comment] 2015-10-05 15:38
Assigning to @xavierdecoster to take a deeper look.

**Comment by xavierdecoster** [comment] 2015-10-06 08:23
So far I was unable to repro this on VS2015 with NuGet 3.2, targeting a NET45 console app. It also does not repro using our latest dev builds.

**Comment by xavierdecoster** [comment] 2015-10-08 09:28
I wasn't able to repro this issue on Win7 x64 with VS2015 Community Edition (exact same build), using NuGet 3.2, targeting a NET45 console app. 

Below the full packages.config generated by installing `System.Data.SQLite` version `1.0.98.1`.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.0.0" targetFramework="net45" />
  <package id="System.Data.SQLite" version="1.0.98.1" targetFramework="net45" />
  <package id="System.Data.SQLite.Core" version="1.0.98.1" targetFramework="net45" />
  <package id="System.Data.SQLite.EF6" version="1.0.98.1" targetFramework="net45" />
  <package id="System.Data.SQLite.Linq" version="1.0.98.1" targetFramework="net45" />
</packages>
```

This adds the following assembly references to the project:

```
EntityFramework
EntityFramework.SqlServer
System.Data.SQLite
System.Data.SQLite.EF6
System.Data.SQLite.Linq
```

Refreshing the solution explorer had no impact on the referenced assemblies for this project.

Closing this issue as unable to reproduce.
If you still hit this problem, feel free to reopen with more details on how to reproduce this.

**Closed as completed by xavierdecoster** 2015-10-08 09:28 UTC
Labels: Priority:2, Type:Bug

**Comment by spetroll** [comment] 2015-10-09 06:37
I got a new pc today and low and behold, it works. Not sure what went wrong on my previous pc. Is there something to trigger a more detailed log that I could post, it still doesn't work on my old one..

**Comment by xavierdecoster** [comment] 2015-10-09 13:04
@emgarten could this be caused by some external process locking the csproj file in-between modifications done by the VSIX? Are there more detailed logs that could help in diagnosing this? This sounds like an edge case scenario to me.
