### ISSUE TITLE
NuGet.exe produces corrupt NuGet package when a "package" folder is not deleted.

### ISSUE THREAD

**Issue by matthid** [NuGet/Home#5384] opened 2017-06-10 08:35 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version: https://www.nuget.org/packages/NuGet.CommandLine/4.1.0

VS version (if appropriate): VS 2015

OS version (i.e. win10 v1607 (14393.321)): win10

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Download NuGet.CommandLine

2. Download [DryIoC.dll 2.10.7](https://www.nuget.org/packages/DryIoc.dll/2.10.7)

3. Extract DryIoC.dll into DryIoc.Test

4. Delete `[Content_Types].xml` and `_rels`

5. Change NuSpec and make the ID "DryIoC.test"

6. Change NuSpec and add a files section

```xml
  <files>
    <file src="**" target="" />
  </files>
```

7. Create a new library project and add a NuGet.config like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="DryIoC" value="C:\PROJ\test\dryioc" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
</configuration>
```

8. restart VS and re-load the project

9. Install "DryIoC.test"

10. Restart VS and re-load the project

11.
![image](https://user-images.githubusercontent.com/1866463/27001303-337b9676-4dc7-11e7-97b3-a4969b1d2d32.png)

Basically, the NuGet View is unusable from this point on. "Manage Packages for Solution" is broken as well.

I debugged Visual Studio and the problem seems to be the generated `[Content_Types].xml`, see

```xml
<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="psmdcp" ContentType="application/vnd.openxmlformats-package.core-properties+xml" />
  <Default Extension="snk" ContentType="application/octet" />
  <Default Extension="txt" ContentType="application/octet" />
  <Default Extension="dll" ContentType="application/octet" />
  <Default Extension="XML" ContentType="application/octet" />
  <Default Extension="psmdcp" ContentType="application/octet" />
  <Default Extension="nuspec" ContentType="application/octet" />
</Types>
```

notice the duplicate `psmdcp`.

The most frustrating thing about this error is the completely useless error message.

## Suggested Fix

Either change `NuGet.exe pack` to produce a valid package, make it fail or make the Visual Studio view work.

I'd suggest failing fast and making `NuGet.exe pack` fail.

> Note:

Visual Studio 2017 works for some reason. Is it because it doesn't try to analyze the package in the same way?

**Comment by emgarten** [comment] 2017-06-14 07:13
@matthid thanks for the great steps and write up on the issue. I was able to repro this with nuget.exe pack.

> Visual Studio 2017 works for some reason. Is it because it doesn't try to analyze the package in the same way?

NuGet moved to using *System.IO.Compression* for cross platform support in NuGet 3.5.0 instead of *System.IO.Packaging*. Pack still writes out the OPC files needed by older clients, but newer clients no longer read them.

If you are seeing this in VS 2015 you are likely using 3.4.4 which is the latest on the extension gallery, but you can download the latest 3.5.0 VSIX here: https://dist.nuget.org/visualstudio-2015-vsix/v3.5.0/NuGet.Tools.vsix

**Comment by matthid** [comment] 2017-06-14 07:59
So the fix will be that those packages will work in newer NuGet versions?

To be honest I found other (similar) issues when you don't delete '_rels'
or the content xml file, but hadn't time to investigate jet. I think they
might hit VS2017 as well.

**Comment by emgarten** [comment] 2017-06-14 08:16
> So the fix will be that those packages will work in newer NuGet versions?

nuget.exe pack needs to be fixed in this case I would say. The error in VS looks like it is caused by the invalid package, older clients will hit this also which is a problem.

VS 2017 shouldn't need to open `_rels`, but if you hit any issues there please file it and I'll take a look.

I haven't had a chance to debug through nuget.exe pack yet to see why the duplicate `psmdcp` but it seems incorrect that it would be defined twice as pack is doing.

**Comment by mishra14** [comment] 2017-11-30 00:45
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.

**Closed as completed by mishra14** 2017-11-30 00:45 UTC
Labels: Functionality:Pack

**Comment by AlexaCodex** [comment] 2018-12-06 16:50
Any updates on this, the issues is also there with : microsoft.visualstudio.web.codegeneration.tools.2.0.4
[Content_Types].xml :
```
<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
  <Default Extension="psmdcp" ContentType="application/vnd.openxmlformats-package.core-properties+xml" />
  <Default Extension="json" ContentType="application/octet" />
  <Default Extension="dll" ContentType="application/octet" />
  <Default Extension="targets" ContentType="application/octet" />
  <Default Extension="nuspec" ContentType="application/octet" />
  <Override PartName="//prefercliruntime" ContentType="application/octet" />
</Types>
```

This is the culprit with double slash '//':  `<Override PartName="//prefercliruntime" ContentType="application/octet" />`

**Comment by daconglee** [comment] 2019-07-21 08:12
https://github.com/madskristensen/BundlerMinifier/issues/309
