### ISSUE TITLE
PM UI does not refresh the sources list on re-launch of the window

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#6125] opened 2017-10-31 17:52 UTC
Steps:
1. Have more than 1 NuGet sources in the nuget.config file
2. Open PM UI window
3. It shows the 2 sources
4. Manually edit the nuget.config to modify the sources
  * Add one more source
  * Remove/Disable a source
  * Edit the source 
5. Save the NuGet.config file
6. Close the PM UI
7. Relaunch the PM UI window

**Expected:** The changes in source should be reflected in the PM UI window.

**Actual:** The changes do not reflect.

**Comment by emgarten** [comment] 2017-10-31 19:06
Duplicate of https://github.com/NuGet/Home/issues/1538

The fix for this is to reload the shared nuget settings in VS. Closing and re-opening PMC has no impact on this.

**Closed as completed by emgarten** 2017-10-31 19:06 UTC
Labels: Area:Settings
