### ISSUE TITLE
nuspec `exclude="Analyzers"` ineffective, analyzers are still brought in

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#7426] opened 2018-10-23 06:05 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

dotnet.exe --version (if appropriate): 2.2.200-preview-009431

Every single dependency in the `streamjsonrpc` 2.0.102-beta package has `exclude="Build,Analyzers"` on it. Yet installing it in a .NET Core project adds analyzers from the `Microsoft.VisualStudio.Threading.Analyzers` package, which streamjsonrpc *indirectly* depends on through its `Microsoft.VisualStudio.Threading` package dependency.

## Detailed repro steps so we can see the same problem

1. Create a csproj with this content:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" Version="2.0.102-beta" />
  </ItemGroup>  

</Project>
```

2. Then create a Program.cs file with this content:

```cs
using System;
using System.Threading.Tasks;

namespace ConsoleApp30
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            FooAsync().Wait();
        }

        static async Task FooAsync() {

        }
    }
}
```

3. run `dotnet build`

**EXPECTED**

No `VSTHRD002` build warning.

**ACTUAL**

The build warnings include one from `VSTHRD002`.

See sample: [ConsoleApp30.zip](https://github.com/NuGet/Home/files/2504687/ConsoleApp30.zip)

**Comment by nkolev92** [comment] 2018-10-23 15:48
Thanks for filing this @AArnott 

As analyzers were initially done without any work from NuGet team, this is a well known gap. 

I consider this a duplicate of https://github.com/NuGet/Home/issues/6279. 
I am closing this now in favor of that, please let me know if you disagree.

**Closed as completed by nkolev92** 2018-10-23 15:48 UTC
Labels: Type:Feature, Functionality:Restore, Style:PackageReference
