### ISSUE TITLE
[Test Failure] No packages.config and the installed package is add into PackageReference even with ‘packages.config’ mode selected in settings

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4742] opened 2017-03-03 09:55 UTC
**NuGet Version:** NuGet 4.3.0-Beta1-2346
**VS Version:** D15Rel 26228.00
**OS Version:** Windows 10 RS2_Release 15048.0.170228-1522

**Repro Steps:**
1. Check **‘Packages.config’** is selected as default package management format in NuGet Package Manager setting dialog.
2. Create a C# Console Applications via VS.
3. Open the ‘Manage NuGet Packages…’ for the project.
4. Click ‘Browse’ tab, select package ‘Newtonsoft.Json’ and click install button.

**Expected Result:**
The package should be installed into the packages.config.

**Actual Result:**
No packages.config and the installed package is add into PackageReference as below screenshot.
![nopackageconfig](https://cloud.githubusercontent.com/assets/20632625/23546409/5eb23532-003a-11e7-86b6-719bd6d4bcfb.png)

**Notes:**
Not repro on **D15Rel 26228.00 (NuGet 4.0.0-rtm-2323)** and **D15Rel 26228.00 + NuGet 4.1.0-rtm-2343**.

**Comment by emgarten** [comment] 2017-03-03 20:52
Dupe of https://github.com/NuGet/Home/issues/4739

**Closed as completed by emgarten** 2017-03-03 20:52 UTC
