### ISSUE TITLE
Invalid .csproj PackageReference version has bad error experience

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#5166] opened 2017-05-04 19:15 UTC
Project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2." />
  </ItemGroup>
</Project>
```

The error is the trailing dot on the version number of Newtonsoft.Json.

Command: `nuget.exe restore ClassLibrary2.csproj`
```
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin'.
```

Command: `nuget.exe restore ClassLibrary2.csproj -verbosity detailed`
```
NuGet Version: 4.3.0.0
MSBuild P2P timeout [ms]: 120000
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\msbuild.exe /t:GenerateRestoreGraphFile /nologo /nr:false /p:RestoreUseCustomAfterTargets=true /p:BuildProjectReferences=false /v:q  /p:NuGetRestoreTargets="C:\Users\jver\AppData\Local\Temp\NuGet-Scratch\24ps0uvj.o4b.targets" /p:RestoreTaskAssemblyFile="D:\tools\nuget.exe\ci\dev-4044\nuget.exe" /p:RestoreGraphOutputPath="C:\Users\jver\AppData\Local\Temp\NuGet-Scratch\belllvpj.xya.result" /p:ExcludeRestorePackageImports=true  /p:RestoreRecursive=False  /p:RestoreProjectFilterMode=exclusionlist /p:RestoreContinueOnError=WarnAndContinue  /p:RestoreGraphProjectInput="D:\trash\2017-05-04\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj;" "C:\Users\jver\AppData\Local\Temp\NuGet-Scratch\24ps0uvj.o4b.targets"
NuGet.CommandLine.CommandLineException
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__38.MoveNext()
System.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) NuGet.CommandLine.CommandLineException
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__30.MoveNext()<---
```

If you run MSBuild directly, the error is very clear.
Command: `msbuild.exe /t:restore`
```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/4/2017 12:10:02 PM.
Project "D:\trash\2017-05-04\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj" on node 1 (restore target(s)).
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): error : '10.0.2.' is not a valid version string. [D:\trash\2017-05-04\ClassLibrary2\ClassLibrary2\ClassL
ibrary2.csproj]
Done Building Project "D:\trash\2017-05-04\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj" (restore target(s)) -- FAILED.


Build FAILED.

"D:\trash\2017-05-04\ClassLibrary2\ClassLibrary2\ClassLibrary2.csproj" (restore target) (1) ->
(Restore target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): error : '10.0.2.' is not a valid version string. [D:\trash\2017-05-04\ClassLibrary2\ClassLibrary2\Clas
sLibrary2.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.59
```

**Comment by mishra14** [comment] 2017-10-18 01:30
using NuGet Version: 4.4.0.4475, I can see that the error message has improved - 
```
C:\Users\anmishr\Desktop\temp\test> ..\..\paths\nuget.exe restore .\test.csproj
MSBuild auto-detection: using msbuild version '15.3.409.57025' from 'C:\Program Files (x86)\Microsoft Visual Studio\PreviewRel\Enterprise\MSBuild\15.0\bin'.
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018: The "WriteRestoreGraphTask" task failed unexpectedly. [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018: System.ArgumentException: '10.0.2.' is not a valid version string. [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating) [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at NuGet.Commands.MSBuildRestoreUtility.GetVersionRange(IMSBuildItem item) [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at NuGet.Commands.MSBuildRestoreUtility.AddPackageReferences(PackageSpec spec, IEnumerable`1 items) [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at NuGet.Commands.MSBuildRestoreUtility.GetPackageSpec(IEnumerable`1 items) [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at NuGet.Commands.MSBuildRestoreUtility.GetDependencySpec(IEnumerable`1 items) [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at NuGet.Build.Tasks.WriteRestoreGraphTask.Execute() [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\hvvrqgcm.fyi.nugetrestore.targets(131,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\Users\anmishr\AppData\Local\Temp\NuGetScratch\iozws2bs.zub.nugetinputs.targets]
```

**Comment by mishra14** [comment] 2017-10-18 01:30
The UX can be improved further.

**Comment by emgarten** [comment] 2017-10-18 01:57
Duplicate of https://github.com/NuGet/Home/issues/3601

**Closed as completed by emgarten** 2017-10-18 01:57 UTC
Labels: Resolution:Duplicate, Priority:3, Product:NuGet.exe, Functionality:Restore
