### ISSUE TITLE
dotnet pack is ignoring documented metadata fields in nuspec file

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7165] opened 2018-08-01 19:04 UTC
_From @glezalex on August 1, 2018 18:42_

I'm trying to pack a DotNet Core console app - target framework is netcoreapp2.1 - using the command 'dotnet pack -c release -o nupkg' and I've noticed several documented metadata fields are apparently ignored.

I'm having a look at https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties and properties like IsTool, IncludeBuildOutput, IncludeContentInPack, BuildOutputTargetFolder or PackageOutputPath seem to be ignored by the pack command. In fact it only packs properly If I don't specify the property NuspecFile in the csproj. If I do specify NuspecFile, many default values seem to be set different and the result is a nuget package that contains just a copy of my project folder.

`dotnet --info` output:

SDK de .NET Core (reflejando cualquier global.json):
 Version:   2.1.302
 Commit:    9048955601

Entorno de tiempo de ejecución:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

_Copied from original issue: dotnet/cli#9777_

**Comment by jainaashish** [comment] 2018-08-01 23:06
@glezalex do you mean these properties doesn't work when you specify `NuspecFile` property? or even without `NuspecFile` property defined, these properties like IsTool, IncludeBuildOutput, IncludeContentInPack, BuildOutputTargetFolder or PackageOutputPath doesn't work?

And can you also elaborate on different default values with or without nuspec file... when you simply generate a default nuspec file, then it's just going to copy your project folder (just like a zip) until you specify what do you want to pack...

**Comment by ghost** [comment] 2018-08-02 15:53
The main difference I see is that if I specify the package version and the package type (DotnetTool) in the csproj, using the properties available there, the dotnet pack tool generates a package that contains the lib folder only (so the compiled binaries).

But If I add just the NuspecFile property and specify a nuspec file, then it just copies my entire project (including excluded content files). It doesn't seem to generate a dotnet tool package anymore, even I set the package type in the nuspec file.

On the other hand, the documentation is rather confusing and there aren't many details about the format of the nuspec file or the behaviour we should expect regarding the default values of the package properties. For example, should I expect that If I set the NuspecFile, then all the default values are restarted because It doesn't pay attention to what's specified in the csproj anymore? Which are in that case the new default values (which were the old ones)?

**Comment by ghost** [comment] 2018-08-08 18:46
I finally opted by defining a task and executing dotnet pack providing command line arguments as described at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x, but yet I find the metadata property Owners (used by Nuget and supported in the nuspec file) is not documented at https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties.

**Comment by rrelyea** [comment] 2018-08-30 22:22
dotnet pack will set author and owner in the nuspec spec to the author value.

**Comment by reecebradley** [comment] 2018-09-19 15:43
Adding my 2 cents. I ran into this issue on our build server. After further investigation, I found that on my local machine running the same arguments, the nuspec came out correctly. The versions of MSBuild stated in the output were different.

Build server:
`Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core`

Local machine:
`Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core`

So maybe this was a bug and now fixed? Perhaps it would be useful to state the version of MSBuild in `dotnet --info` - I'll have to get someone to update the build server to verify.

reece

**Comment by ghost** [comment] 2018-09-19 18:48
That's a good point thanks @reecebradley. I'm checking and my msbuild version is the 15.7.179.6572, so I'll check in another system with the most recent version.

**Comment by nkolev92** [comment] 2018-11-30 18:06
This is currently by design. 

When you use a nuspec, you change values with token replacements.
When you use a nuspec with dotnet pack, you need to pass the token replacements with the NuspecProperties property. 

See docs. 
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec

**Closed as completed by nkolev92** 2018-11-30 18:06 UTC
Labels: Resolution:ByDesign, Functionality:Pack
