### ISSUE TITLE
Solve JetBrains performance scenario for NuGet Update

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3044] opened 2016-06-24 16:31 UTC
Per email thread with JetBrains...let's ensure that they understand when to do less work.
In other cases (XAML Language Service), using batchstart and end worked.
Do we need new events to solve this?
If so, what should they be? 
Should they only solve Update?
Or is install, restore, etc... too?
If all, should they use one generic event NuGetOperationStarting, NuGetOperationComplete, or events for each of those things.

**Comment by jainaashish** [comment] 2016-06-28 17:10
We looked through vs code as well as confirmed with them, there isn't seems to be a way to get VS batch start/ end state or events. So we will need to define our own events for batchStart and batchEnd which should work for a collective install/ uninstall packages irrespective of update, install, or restore operations.

**Comment by jainaashish** [comment] 2016-06-30 18:19
Shared a private build of nuget batch events with Resharper team and awaiting their private build with implementation. Then we'll analyze it further.

**Comment by jainaashish** [comment] 2016-07-19 19:50
Merged d775d6fbdc1a25397fb8f1119b52b249a8940061 
But still keeping it open to write spec for this.

**Comment by jainaashish** [comment] 2016-07-19 23:02
Spec doc added at nuget home wiki and also updated in PR.

**Closed as completed by jainaashish** 2016-07-19 23:02 UTC
Labels: Product:VS.Client, Type:DCR, Tenet:Performance
