### ISSUE TITLE
Update and Uninstall not working for projects with multiple TargetFrameworks

### ISSUE THREAD

**Issue by Tratcher** [NuGet/Home#5472] opened 2017-06-21 21:10 UTC
## Summary
When a project has at least three TargetFrameworks and tries to install a package that does not support one of them, then the PackageReferences for the others TFMs get added inside Conditional ItemGroups. If you then use the Package Manager UI to Uninstall or Update that package it only affects the first TFM. If there is no matching conditional for the first TFM the Uninstall gives an error "Package with id "[Package Name]" does not exist, though it continues to show the package as installed so long as it is defined in at least one TFM conditional.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI, 4.3.0

dotnet.exe --version (if appropriate):
2.0.0-preview2-006479

VS version (if appropriate):
VS 15.3.0 Preview3.0 [26615.0.d15rel]

OS version (i.e. win10 v1607 (14393.321)):
Win7SP1

Worked before? If so, with which NuGet version:
Unknown

## Detailed repro steps so we can see the same problem

1. Create a new .NET Core Class Library project
2. Change `<TargetFramework>netcoreapp2.0</TargetFramework>` to `<TargetFrameworks>net45;net47;netstandard1.0;</TargetFrameworks>`
3. Install Newtonsoft.Json 7.0.1. This package version is not compatible with netstandard1.0 so you get TFM conditionals.
Your project now looks like this:
```
  <PropertyGroup>
    <TargetFrameworks>net45;net47;netstandard1.0;</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net47'">
    <PackageReference Include="Newtonsoft.Json">
      <Version>7.0.1</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net45'">
    <PackageReference Include="Newtonsoft.Json">
      <Version>7.0.1</Version>
    </PackageReference>
  </ItemGroup>
```

### Upgrade scenario: 
4. Update Netwonsoft.Json to 8.0.1
Your project now looks like
```
  <PropertyGroup>
    <TargetFrameworks>net45;net47;netstandard1.0;</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net47'">
    <PackageReference Include="Newtonsoft.Json">
      <Version>7.0.1</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net45'">
    <PackageReference Include="Newtonsoft.Json">
      <Version>8.0.1</Version>
    </PackageReference>
  </ItemGroup>
```
Note only net45 was updated, and 7.0.1 still shows as the installed version in the Nuget UI.

### Uninstall scenario:
4. Uninstall Newtonsoft.Json 7.0.1.
Your project now looks like
```
  <PropertyGroup>
    <TargetFrameworks>net45;net47;netstandard1.0;</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net47'">
    <PackageReference Include="Newtonsoft.Json">
      <Version>7.0.1</Version>
    </PackageReference>
  </ItemGroup>
```
Note Newtonsoft.Json was only removed from net45.

5. Uninstall Newtonsoft.Json 7.0.1 again (it's still listed as installed)
Result: Error: Package with id "Newtonsoft.Json" does not exist.

...

### Sample Project
[NugetRefs.zip](https://github.com/NuGet/Home/files/1092907/NugetRefs.zip)

**Comment by mishra14** [comment] 2017-12-19 23:27
dupe of https://github.com/NuGet/Home/issues/4681

**Closed as completed by mishra14** 2017-12-19 23:27 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Update, Functionality:Install
