### ISSUE TITLE
Unable to download any Nuget package

### ISSUE THREAD

**Issue by jzkortee** [NuGet/Home#8845] opened 2019-11-20 13:08 UTC
I am unable to download any Nuget package. I am getting the following error.
[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.

I am using Visual Studio 2019 V16.3.9 Community edition on ]Windows 10 Profession

Thanks

**Comment by zivkan** [comment] 2019-11-25 17:39
Duplicate of https://github.com/NuGet/NuGetGallery/issues/7705

**Closed as completed by zivkan** 2019-11-25 17:39 UTC
Labels: Resolution:Duplicate
