### ISSUE TITLE
'Index was outside the bounds of the array' when GeneratePackageOnBuild=true

### ISSUE THREAD

**Issue by 3F** [NuGet/Home#8810] opened 2019-11-12 21:00 UTC
MSBuild 16.3.2+e481bbf88

```xml
...
GenerateNuspec:
  Successfully created package 'D:\tmp\_Issues\VS2019\NugetErrIndex\ClassLibrary1\ClassLibrary1\bin\Debug\ClassLibrary1.1.0.0.nupkg'.
C:\Program Files\dotnet\sdk\3.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error : Index was outside the bounds of the array. [D:\tmp\_Issues\VS2019\NugetErrIndex\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
Done Building Project "D:\tmp\_Issues\VS2019\NugetErrIndex\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj" (default targets) -- FAILED.
...
```

VisualStudio.16.Release/16.3.8+29503.13

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Index was outside the bounds of the array.	ClassLibrary1	C:\Program Files\dotnet\sdk\3.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets	198	
```

How to reproduce:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  
  <ItemGroup>
    <!-- add any file, its name start with 'build', for example: -->
    <None Include="buildfoo.bar" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
```

**Comment by nkolev92** [comment] 2019-11-13 00:01
https://github.com/NuGet/Home/issues/8806 has a similar root cause.

**Comment by zivkan** [comment] 2020-04-20 18:36
Closing as a duplicate of https://github.com/NuGet/Home/issues/8703

**Closed as completed by zivkan** 2020-04-20 18:36 UTC
Labels: Type:Bug, Functionality:Pack, RegressionFromPreviousRTM
