### ISSUE TITLE
NuGet 3.0 RC has unreadable text in dark theme (main UI)

### ISSUE THREAD

**Issue by onovotny** [NuGet/Home#649] opened 2015-05-27 19:08 UTC
See the screen shot. I'm using VS 2015 RC and the descriptions are unreadable. I didn't see an existing bug for this for the RC build.

![2015-05-27_15-07-07](https://cloud.githubusercontent.com/assets/1427284/7845009/27496116-0482-11e5-942b-e4a09d208830.png)

**Comment by emgarten** [comment] 2015-05-27 21:03
@onovotny did this happen while changing to the dark theme when the NuGet window was already open? Does the text stay dark even after restarting VS?

**Comment by feiling** [comment] 2015-05-27 22:36
Couldn't repro. This is what the UI looks like in the dark theme:

![image](https://cloud.githubusercontent.com/assets/2679220/7848953/4ef05d70-0485-11e5-92c7-00a672daef74.png)

@onovotny It seems you might have other settings changed in Options -> Environment -> Fonts and Colors. You can export the settings (Options -> Environment -> Import and Export Settings) and send us a copy of your vs settings file. Then maybe we can figure out which setting caused this behavior.

**Comment by onovotny** [comment] 2015-05-27 22:41
If there's a bad color in there, I certainly didn't mean it! :)

Here's the exported fonts/colors:
https://gist.github.com/onovotny/c31fc21e84a120776123

**Comment by onovotny** [comment] 2015-05-28 13:48
Not sure if this helps, but I see a style being overridden in the visual tree. Check out these two screen shots from XAML Spy:

Here the text foreground color looks right, 
![2015-05-28_9-43-39](https://cloud.githubusercontent.com/assets/1427284/7861526/9fe80b30-051e-11e5-8158-cfbfd0e306e9.png)

And here when on the ListBoxItem, the foreground style is changed to something darker
![2015-05-28_9-45-18](https://cloud.githubusercontent.com/assets/1427284/7861532/a8b37f2e-051e-11e5-8334-b3b4fd1b51d5.png)

**Comment by onovotny** [comment] 2015-05-28 14:29
One more update - changed them from dark to light, then back to dark and hit use defaults on the fonts and colors. I then restarted VS. I still see the same unreadable dark grey text....so no real idea where that color is coming from.

**Comment by onovotny** [comment] 2015-06-05 13:54
I'm not sure it's related to the fonts/colors settings at all likely something else. On another machine (that uses the same synced color settings), the dialog looks normal.

I exported those colors and imported them w/o any luck on the machine with the issue.

FWIW, the OS is Win10 10130.

I'm not sure how to triage this to figure out where that color is being set from. I'm happy to provide access to the machine and/or run additional diags, provide logs, etc.

**Comment by feiling** [comment] 2015-06-05 23:13
@onovotny  Are you running something like StartDoc WindowBlinds (http://www.stardock.com/products/windowblinds/) that changes the look of standard windows and WPF controls?

Also, I believe https://github.com/NuGet/Home/issues/659 is also caused by this. `DevExpress.Xpf.Core.ThemeManager` (https://documentation.devexpress.com/#wpf/clsDevExpressXpfCoreThemeManagertopic) shows up in the call stack. This leads me to believe there must be 3rd theme engine installed on your machine.

**Comment by onovotny** [comment] 2015-06-05 23:14
nope, not at all. is there an easy command to get a list of my installed programs? it's not really that many

**Comment by onovotny** [comment] 2015-06-05 23:16
I don't have any DevExpress tools installed. It must be from an Add-in?

**Comment by feiling** [comment] 2015-06-05 23:17
You can search the whole disk for DevExpress and see it's included in which program.

**Comment by onovotny** [comment] 2015-06-05 23:23
It's getting loaded from the GAC :(

	DevExpress.Xpf.Core.v14.2.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.Xpf.Core.v14.2\v4.0_14.2.7.0__2dc3dfad160eda83\DevExpress.Xpf.Core.v14.2.dll	Yes	No	Skipped loading symbols.		562	14.02.7.15114	5/7/2015 8:42 AM	3C120000-3C7DA000	[15656] devenv.exe	[1] DefaultDomain	
	DevExpress.Xpf.Themes.Office2013.v14.2.dll	C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\DevExpress.Xpf.Themes.Office2013.v14.2\v4.0_14.2.7.0__2dc3dfad160eda83\DevExpress.Xpf.Themes.Office2013.v14.2.dll	Yes	No	Skipped loading symbols.		565	14.02.7.15114	5/7/2015 8:44 AM	3A9A0000-3AC9C000	[15656] devenv.exe	[1] DefaultDomain	

I did an attach to process. Is there a way to get a breakpoint on module load so I know what the loading call stack is? Or is that done with the fusion viewer? It's been so long that I forget.

**Comment by onovotny** [comment] 2015-06-05 23:23
Is that a bug in VS that an external module load can affect its themes?

**Comment by onovotny** [comment] 2015-06-05 23:33
I think I found the culprit: the Sci-Tech .NET Memory Profiler add-in
```
=== Pre-bind state information ===
LOG: DisplayName = DevExpress.Xpf.Core.v14.2, Version=14.2.7.0, Culture=neutral, PublicKeyToken=2dc3dfad160eda83
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = devenv.exe
Calling assembly : NetMemProfilerBase, Version=5.0.80.0, Culture=neutral, PublicKeyToken=2dc3dfad160eda83.
===
```
The calling assembly is NetMemProfilerBase.

This still sounds like a bug in VS that even allows an add-in to mess with it.

Should a bug be filed with DevExpress on this behavior?

**Comment by feiling** [comment] 2015-06-05 23:42
There's no way for VS to prevent an extension from changing the styles of WPF controls. https://github.com/NuGet/Home/issues/659 is definitely a bug with DevExpress. I can explicitly set the text color so changes made by DevExpress won't affect us.

**Comment by onovotny** [comment] 2015-06-05 23:44
I'll send a note to the support alias for .net memory profiler. I don't have any direct contacts at DevExpress though as I'm not a customer. Do you have a place to log a bug with DevExpress where it'll get reviewed?

**Comment by onovotny** [comment] 2015-06-05 23:47
Confirmed as the root cause. I uninstalled the VS Add-in for the Sci-Tech memory profiler and the colors all appear correctly.

**Comment by yishaigalatzer** [comment] 2015-06-06 02:57
Thanks Oren for keeping up with this!

Closing

**Closed by yishaigalatzer** 2015-06-06 02:57 UTC
Labels: 2 - Working, Area:VS.Client, Priority:1, Type:Bug
