### ISSUE TITLE
Add Packaging Project to SupportedProjectTypes

### ISSUE THREAD

**Issue by sbanni** [NuGet/Home#9358] opened 2020-03-30 16:37 UTC
Need to add ProjectTypeGuid for Packaging Project (C7167F0D-BC9F-4E6E-AFE1-012C56B48DB5) to: https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Clients/NuGet.VisualStudio.Common/SupportedProjectTypes.cs

Ideally, this would be a Project System Capability check instead of a hard coded list.

**Comment by rrelyea** [comment] 2020-03-30 17:13
@aortiz-msft - @sbanni works on xaml team next door. Important small request.

**Comment by stevenbrix** [comment] 2020-04-29 19:46
It would be nice if VS also set the appropriate `AssetTargetFallback`. It defaults to `uap10.0.17763.0` where we (WinUI) want it to use `netcoreapp5.0`

**Comment by stevenbrix** [comment] 2020-04-30 16:21
> It would be nice if VS also set the appropriate AssetTargetFallback. It defaults to uap10.0.17763.0 where we (WinUI) want it to use netcoreapp5.0

This is actually something that should be set in the packaging project sdk itself. It sets the `AssetTargetFallback` for a bunch of other TFMs, just not net5.0. This issue tracks this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1114196

**Comment by rrelyea** [comment] 2020-06-08 17:36
Blocked by many things, not just nuget. No longer high priority on the nuget side.

**Comment by stevenbrix** [comment] 2020-06-08 18:04
@rrelyea my understanding is that https://github.com/dotnet/project-system/issues/2491 will be done in VS16.8 and that should enable this as well as `PackageReference` in .vcxproj, is that true?

**Comment by aortiz-msft** [comment] 2020-08-27 23:58
@rrelyea is this still blocked? if not, let's try to address it this sprint.

**Comment by stevenbrix** [comment] 2020-08-28 00:12
@aortiz-msft, don't get my hopes up... 😃

**Comment by davkean** [comment] 2020-08-31 02:16
@aortiz-msft @rrelyea To address https://github.com/dotnet/project-system/issues/2491, instead adding another project type to this list, can we please check for the PackageReferences capability as specified in https://github.com/NuGet/Home/issues/9957? This also lets project types experiment with Package Reference support without needing NuGet to opt them in and shipping with it opt'd in.

**Comment by davkean** [comment] 2020-08-31 02:57
I have a fix for this based on the ProjectReferences capability; https://github.com/NuGet/NuGet.Client/pull/3618. @sbanni CPS-based projects should be using PackageReferences to opt in. I haven't yet verified end-to-end yet and will be doing so over the week.

**Comment by davkean** [comment] 2020-08-31 02:57
This bug can probably be closed in lieu of https://github.com/NuGet/Home/issues/9957.

**Comment by rrelyea** [comment] 2020-08-31 17:41
closing as dupe of https://github.com/NuGet/Home/issues/9957

**Closed as completed by rrelyea** 2020-08-31 17:41 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Feature, Functionality:Pack
