### ISSUE TITLE
dotnet restore can't handle package that references an LKG of itself

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4356] opened 2017-01-22 07:04 UTC
_From @AArnott on January 22, 2017 6:34_

Nerdbank.GitVersioning is a package that is built with an LKG of itself since this package is a build authoring extension. But in trying to convert this repo to use the .NET Core projects, I find there seems to be an inability of the SDK to support referencing a published version of oneself. 

**Repro steps**

```
git clone https://github.com/AArnott/Nerdbank.GitVersioning.git 
cd Nerdbank.GitVersioning
git checkout 5754df2e36db3c823feebdf5bc5a2ef827e18639
cd src\Nerdbank.GitVersioning
dotnet restore
```

Then add this package reference to the Nerdbank.GitVersioning.csproj project file:

```xml
<PackageReference Include="Nerdbank.GitVersioning" Version="1.5.62" />
```

Then run `dotnet restore` again.

**Expected**

Nerdbank.GitVersioning can build with the aid of an LKG build of itself.

**Actual**

Package restore fails in a really big way, producing dozens of package version conflict errors, even though this package I'm referencing is very simple, has no dependencies, and should have been restored cleanly.

_Copied from original issue: dotnet/sdk#705_

**Comment by emgarten** [comment] 2017-01-22 20:17
This scenario makes sense for development dependencies/build tools. The issue is that restore fails due to the circular dependency since that is invalid for .dll type references.

Ideally tools like this would be resolved in their own graph outside of the project to avoid dependency conflicts. One way to do this could be to create a new reference item type for build related development dependencies.

**Comment by clairernovotny** [comment] 2017-01-22 20:52
@emgarten agreed, seems like anything in this path could be predicated on the `developmentDependency` set to true and/or being a package type of tools?

**Comment by emgarten** [comment] 2017-01-22 21:23
@onovotny that would probably solve most scenarios. Sometimes however, normal packages can be used as development dependencies also, or the other way around so it isn't always possible to tell the intent from the package.

**Closed as completed** 2017-11-09 22:41 UTC
Labels: Resolution:Duplicate, Functionality:Restore, Triage:NeedsTriageDiscussion

**Comment by AArnott** [comment] 2017-11-10 04:50
@zhili1208 why did you close this?

**Comment by zhili1208** [comment] 2017-11-10 22:07
@emgarten

**Comment by emgarten** [comment] 2017-11-10 23:01
This is a duplicate of https://github.com/NuGet/Home/issues/1428

Development dependencies do not flow to parent projects, here there is no parent project so it doesn't matter here, the project's graph contains a circular dependency.

I can see how this case is special because the dependency package is likely using targets, but for most scenarios this would be equivalent to having a project A that creates a.dll and trying to referencing a package A that also contains a.dll. At runtime there will be a conflict, only one A can exist.

The workaround for this is to set PackageId to a different name in the parent project. 

On the NuGet side we had to do the same thing for Pack when Pack was an actual package referenced by the SDK and we were trying to build the original project using the SDK. It is painful, but in my opinion this scenario is very rare for users.

**Comment by AArnott** [comment] 2017-11-11 06:09
> The workaround for this is to set PackageId to a different name in the parent project.

Can you elaborate on this? If the parent project sets a different `PackageId`, then it can't build the package it was meant to.

**Comment by emgarten** [comment] 2017-11-11 07:14
Hmm, that is true. Maybe that doesn't work as a workaround in this case.

In the case of Pack for NuGet we were using a nuspec file and packing that directly.
