### ISSUE TITLE
Mono users should use msbuild. Guidance should be documented.

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3567] opened 2016-09-30 17:13 UTC
this bug is for tracking xbuild issue

**Comment by yishaigalatzer** [comment] 2016-10-03 20:03
@zhili1208 can you expand on the core issue and what it is impacting? Please add what version of Mono, what is the expected result with msbuild etc.

**Comment by zhili1208** [comment] 2016-10-03 20:42
mono version 4.4.2, pack with xbuild doesn't work due to this issue. with msbuild, it will return the OutputPath value in csproj.

**Comment by rrelyea** [comment] 2016-10-03 20:46
@mhutch & @mrward - recommendation here? known issue with xbuild?

**Comment by mrward** [comment] 2016-10-03 20:55
@rrelyea - xbuild does not implement parts of the Microsoft.Build.Evaluation namespace so I would guess that something is not implemented. The last time I looked at nuget pack on Mono there were [some issues](https://bugzilla.xamarin.com/show_bug.cgi?id=18837).

Shipping msbuild with Mono should fix these problems.

**Comment by yishaigalatzer** [comment] 2016-10-03 20:58
So are we ok with closing as won't fix/external and routing users to use msbuild?

**Comment by mhutch** [comment] 2016-10-04 05:25
Short version:

Yes, and I recommend using MSBuild's Microsoft.Build.dll instead of xbuild's. It's already shipping in Mono on Mac.

Long version:

MSBuild 4.0 abandoned its older Microsoft.Build.Engine.dll engine and moved to a new Microsoft.Build.dll engine and API. xbuild's a clone of MSBuild, and had implemented the old engine API.  xbuild did not initially implement the new engine but instead added 4.0+ features to the old engine. Eventually an implementation of the new engine/API was started in xbuild, but it was never completed and never used from xbuild.exe or Xamarin Studio.

So although Microsoft.Build.dll exists in xbuild, I'd STRONGLY advise against using it in practice.

Anyways, that soon won't matter, since MSBuild has been open sourced and ported to Mac/Linux. We are in the process of dropping xbuild and instead shipping MSBuild.

Initially we're shipping MSBuild side by side with xbuild,. From the command-line you choose between them by running either the "xbuild" or "msbuild" command. In Xamarin Studio, you can opt in to using MSBuild in Preferences. The next phase will be for XS to use MSBuild by default, but allow opting out and using xbuild (in case of regressions). Eventually we'll drop xbuild entirely.

The story's a bit more complicated if you're hosting MSBuild via Microsoft.Build.dll like NuGet does. It's not in the GAC, so to use the MSBuild implementation you have to resort to assembly load / resolve hooks.

**Comment by rrelyea** [comment] 2016-10-20 15:51
Just putting it on @zhili1208's plate now for visibility.

**Comment by karann-msft** [comment] 2016-11-16 00:13
This has been fixed  https://github.com/NuGet/NuGetDocs/pull/683/commits/f84f7d3d3fc42013a263112bd9a278fbdbd26ac8

**Closed as completed by karann-msft** 2016-11-16 00:13 UTC
Labels: Type:Docs, Functionality:Pack, Platform:Mono
