### ISSUE TITLE
Visual Studio Restore does not properly pick up package references transitively for project references outside the solution

### ISSUE THREAD

**Issue by dfederm** [NuGet/Home#7417] opened 2018-10-20 16:14 UTC
When restoring in VS, if a project has a project reference outside the solution, and that project outside the solution has a PackageReference, the first project (in the sln) will not end up with that package in it's project.assets.json. It works properly when using `MSBuild /t:Restore`

Repro steps:
1. Create a project A with a package reference to a package X
2. Create a project B with a package reference to package Y
3. Add a project reference from project A to project B
4. Create a solution with just project A
5. Do a restore in VS
6. Observe that project A's project.assets.json is missing package Y
7. From the command line and do an "msbuild /t:Restore" on project A
8. Observe that project A's project.assets.json is properly has package Y

**Comment by nkolev92** [comment] 2018-10-22 17:25
This is by design, because NuGet depends on the project system. 

Duplicate of https://github.com/NuGet/Home/issues/5820 and https://github.com/dotnet/project-system/issues/2759

Please track the open issue in the project system repo.

**Closed as completed by nkolev92** 2018-10-22 17:25 UTC
Labels: Product:VS.Client, Functionality:Restore, Resolution:BlockedByExternal
