### ISSUE TITLE
Port lowercase paths from dev to 3.6b2

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2917] opened 2016-06-07 17:15 UTC
If we get approval, including for the CLI fix, port https://github.com/NuGet/NuGet.Client/commit/b8372bbc3720b08b08337122d3e5569df3cf7c6c to 3.5b2

**Comment by rrelyea** [comment] 2016-06-08 14:27
This hasn't been approved yet, email discussion to follow...collecting data for that email.

**Comment by rrelyea** [comment] 2016-07-15 17:56
Looks like 3.5 rtm should be ok to ship with this in the code base. We may need to understand 1.0 and 1.1 projects in the future...and do old/new behavior.

**Comment by joelverhagen** [comment] 2016-09-08 21:42
Duplicate of https://github.com/NuGet/Home/issues/2522.

**Closed as completed by joelverhagen** 2016-09-08 21:42 UTC
Labels: Resolution:Duplicate, Type:DCR
