### ISSUE TITLE
Investigate d15 E2E test failures

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#4245] opened 2017-01-09 22:09 UTC

**Comment by mishra14** [comment] 2017-01-10 00:15
Discussed with @jainaashish and @emgarten and found the issue. @jainaashish is going to checkin a fix.

**Comment by emgarten** [comment] 2017-01-10 00:19
Dupe of: https://github.com/NuGet/Home/issues/4231

**Closed as completed by emgarten** 2017-01-10 00:19 UTC
Labels: Resolution:Duplicate, Triage:Investigate
