### ISSUE TITLE
Non-Fatal Watson: System.NullReferenceException at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass9_0.<<GetInstalledPackages>b__0>d.MoveNext()

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4563] opened 2017-02-10 17:23 UTC
see watson info in internal bug 382580 

Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
    at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass9_0.<<GetInstalledPackages>b__0>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
    at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
    at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
    at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
    at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.PackageServicesProxy.GetInstalledPackages(Project project)
    at Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessProjectChange(Solution solution, ProjectId projectId)

**Comment by zhili1208** [comment] 2017-02-10 22:31
the issue here is nugetProject can be null if exception is throw during nugetProject Creation  https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerServices.cs#L147

we should do null check and log error at https://github.com/NuGet/NuGet.Client/blob/78542c8d1ef67a23bb3e683256d07d0c0bef8ac7/src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/NuGetProjectFactory.cs#L63

**Comment by emgarten** [comment] 2017-02-10 23:27
Copied from https://github.com/NuGet/Home/issues/4576 as it related to this

From Vlad: 
This scenario is caused by Roslyn probing all projects for installed packages. In the scenario where a C# Web project contains typescript files are added to a virtual sub project within the main project. When checking for packages to auto suggest the virtual project is passed to the NuGet APIs, which then fails.

``VSSolutionManager.GetOrCreateProjectAsync`` should handle non-projects gracefully.

Looks like internally NuGet tries to create NuGet project for a given EnvDTE.Project (https://github.com/NuGet/NuGet.Client/blob/b89bb5750c475212213e14f750604d2ecaf704ff/src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs#L1065)
with assumption that this should always succeed and result will be not null. In our case since VsVirtualProjectHierarchy represents project that does not has CPS or MSBuild or any other counterpart GetOrCreateProjectAsync presumably returns null which lead to failure downstream. To me it looks like a missing case in NuGet that should be fixed.

**The NuGet IVS APIs should validate incoming DTE objects, and should be capable of handling non-projects**

**Comment by zhili1208** [comment] 2017-03-13 19:17
fix merged https://github.com/NuGet/NuGet.Client/commit/232384084b7c32eab814d7ada51bdc7db149c5fe

**Closed as completed by zhili1208** 2017-03-13 19:17 UTC
Labels: Product:VS.Client, Type:Bug
