### ISSUE TITLE
Self-Contained NuGet Packages - License

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#4628] opened 2017-02-16 08:13 UTC
Update (by @anangaur on 1/8/2019) - **Useful links**:

* Feature announcement: [Packaging Icon, License and Documentation within the nupkg](https://github.com/NuGet/Announcements/issues/29)
* Deprecation announcement for `licenseUrl`: ['licenseUrl' as package metadata is now deprecated, use 'license' instead](https://github.com/NuGet/Announcements/issues/32)
* Spec wiki: [Packaging License within the nupkg](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg)
* Discussion issue: [Self-Contained NuGet Packages – License #4628]( https://github.com/NuGet/Home/issues/4628)
* Documentation for `license` metadata in nuspec: https://docs.microsoft.com/en-us/nuget/reference/nuspec#license
* Documentation for `license` metadata using MSBuild properties in project file: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file
--------
Right now, every package can link to a license by providing the `licenseUrl` property in the metadata. This is awesome, but also not-so-awesome. Allow me to explain my line of thinking.

Every package owner can attach a license to every version of their package. So far, so good, as it allows switching license between versions. So far, so good.

Now imagine utilizing a NuGet package. For impact, let's take `Newtonsoft.Json`, a very popular OSS package with a permissive license. One day, the author decides to update the HTML contents at the referred license URL. That's... problematic!

**Which license applies? The one I read (and agreed with) at package install time? Or the current one that is now displayed on the license URL?**

There is no way to figure out the license changed between install and consuming the package, no way to prove it was permissive at time of first install.

Please consider enforcing embedding license info into the package, as the package itself is considered immutable.

**Comment by hhariri** [comment] 2017-02-16 08:16
+1

**Comment by xavierdecoster** [comment] 2017-02-16 08:23
I totally agree we should do something about this! A package version's license should be immutable.

Tagging @rrelyea @DoRonMotter

**Comment by cmatskas** [comment] 2017-02-16 09:04
My +1

**Comment by vbfox** [comment] 2017-02-16 09:12
Also if licenses are embeeded, please allow authors to simply specify one of the standard OSS licenses ( https://opensource.org/licenses ) instead of a full text.

It'll make blacklisting / whitelisting license a lot simplier and would provide a way to display nicely the package license in the nuget.org UI without guesses in such cases.

**Comment by ryanbnl** [comment] 2017-02-16 09:32
@vbfox good idea; imho that should be extended so that you can, for example, filter on named licenses. named only being available when you select one of the standard licenses (all other being custom).

**Comment by reiz** [comment] 2017-02-16 10:20
I totally agree. The license name should be mandatory and immutable! On Maven Central (Java) that is the case since years, because of reasons. For license names I would suggest to take the SPDX identifiers, that's a standard for OSS licenses. See here: https://spdx.org/licenses/. 

By the way, I'm working on the open source project [VersionEye](https://www.versioneye.com/) and we did already a lot of work for recognising SPDX identifiers from license URLs provided in Nuget packages.

**Comment by maartenba** [comment] 2017-02-16 10:23
@reiz We do a similar thing in [MyGet](https://www.myget.org). It helps, but ideally license info on a package should be immutable.

**Comment by reiz** [comment] 2017-02-16 12:12
@maartenba Absolutely. The license name should be mandatory and immutable. That would make our all life much easier :-) MyGet looks like a nice service.

**Comment by JimBobSquarePants** [comment] 2017-02-16 13:23
What happens if I want to change my license to something more permissive? Do I have to create a new package? That could seriously affect branding and visibility.

**Comment by maartenba** [comment] 2017-02-16 13:38
(feel free to reach out via email, would love to do a proper "hi!" :-))

**Comment by maartenba** [comment] 2017-02-16 13:38
A new package version in this case, yes.

**Comment by hhariri** [comment] 2017-02-16 13:50
@JimBobSquarePants Even if the license is more permissive, many organisations have restrictions on what type of licenses they can use. Going from a more restrictive to more permissive might still have legal impacts for those using the packages.

**Comment by ghost** [comment] 2017-02-16 14:39
+1

**Comment by dylanbeattie** [comment] 2017-02-16 20:10
+1. The inability to cite and verify the license that was in effect at the time a package was installed is a considerable weakness in the integrity of the NuGet ecosystem.

**Comment by ThatRendle** [comment] 2017-02-16 20:50
@JimBobSquarePants A new version, not a new package. Going from GPL on 1.x to MIT on 2.x, for example.

**Comment by ThatRendle** [comment] 2017-02-16 20:59
I don't actually know much about blockchains, but this seems to me to be the sort of thing that could be verified externally with a blockchain, signing and saving something when a package is published.

It could use Project Bletchley.

**Comment by ryanbnl** [comment] 2017-02-16 21:12
You don't need a blockchain here because you don't have a distributed trust problem. You have a central authority who can be trusted. They store/serve signed packages with embedded licenses (or links to well known licenses; Universal Resource Identifier style) :)

BTW I suggest googling blockchain, the technology is interesting bit it has become such a hand wavey marketing term. You don't hear the really good technical people talking about it, just the loudmouthed snake-oil salespeople.

In an ironic twist it'll probably turn out that you know more than the people often presenting about the subject (to non technical people) ;)

**Comment by JimBobSquarePants** [comment] 2017-02-17 03:33
@maartenba @hhariri  @markrendle My bad, misread. Agree with issue.

**Comment by reiz** [comment] 2017-02-20 07:52
@JimBobSquarePants A license is always bound to a specific version of a package. Licenses can change from version to version. That's why it's important to track & document licenses in your dependencies automatically. There are different tools out there for this problem. Tools like [BlackDuck](https://www.blackducksoftware.com/), [WhiteSource](https://www.whitesourcesoftware.com/) and [VersionEye](https://www.versioneye.com). I'm working on the last one, which is completely open source under MIT license.

**Comment by tthiery** [comment] 2017-11-20 12:40
@rrelyea Some context from my side helping for triage:

- When analyzing Cordova Apps with its 1000s of NPM (sub)dependencies, standardized SPDX license identifiers inside of the NPM packages helped us to release software using whitelisting/blacklisting. Consider cases like "(MIT OR GPL-2.0)". Without this field, we would need literally weeks to analyze them.
- License-less and unclear licensed (NPM) packages (e.g. not SPDX compliant statements like "BSD" vs. "BSD-3-Clause" or "MIT*") take serious analysis after identifying them.
- Micro packages are becoming more and more popular (.NET Core / netstandard). The number of packages will probably grow as well.
- Do not be late with this topic. During analysis mentioned above, old dependencies with unclear licenses got updated later (during the profesionalization of JavaScript) in newer versions. The old packages are in an unclear state.

I am recommending to enforce a license abbreviation with explicit additional options to "see text embedded in package" or "I hate licensing and do not do it". The first one lawyers need to check and the later can be sorted out automatically. Help with analyzers during the pack phase to ensure that the license is at least clarified.

**Comment by gregmac** [comment] 2018-03-04 22:00
There's a related issue on the gallery project about [license policy](https://github.com/NuGet/NuGetGallery/issues/2688) (which maybe should be here, or partly merged with this issue). 

The main part of it is to be clear about commercially-licensed packages, and ensure there's a clear license link defined -- or simply ban them altogether from nuget.org.

The other part about requiring a project link is partly related to this, and if there's any policy change happening as a result of this ticket that would probably be a good change to go along with it, from a package maintainers point of view.

**Comment by karann-msft** [comment] 2018-07-31 23:33
Here is the spec - https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg

**Comment by tthiery** [comment] 2018-08-01 06:30
Thanks for the spec. Everything I hoped for is in it :).
Regards license scanning: I think your new/old friends at GitHub did the same. Maybe connect to them.

**Comment by ferventcoder** [comment] 2018-08-01 14:34
For embedded binaries, we've required a LICENSE file and VERIFICATION file since 2015ish for Chocolatey Community Repository. Good to see this come into NuGet proper. 👍

**Comment by agr** [comment] 2018-08-07 20:29
I am reading the spec, and the impression I am getting that using SPDX expression and using custom license packaged with a file are mutually exclusive options. Is it expected that users wouldn't be able to do something like "GPL-3.0-only OR MySuperCustomLicense"? Does anyone want to do that?

**Comment by karann-msft** [comment] 2018-08-08 18:21
@agr That's right and by design. "GPL-3.0-only OR MySuperCustomLicense" is by definition a custom license and you should just put that into your license file and point to it.

**Comment by markusschaber** [comment] 2018-08-09 09:29
Hmm - one Point is that "GPL-3.0-only" is a valid alternative choice of "GPL-3.0-only OR MySuperCustomLicense", so someone redistributing it can always choose the "GPL-3.0-only" variant. I think it could be discussed with the SPDX guys whether they want to add some way to express this to their SPDX expression definition.

**Comment by markusschaber** [comment] 2018-08-09 12:29
I got some feedback from the SPDX guys: ("CustomAlternateLicensing" is a placeholder for whatever you choose as the name for the proprietary license).

> Referring to Appendix IV:  SPDX License Expressions in https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf, then SPDX allows for custom licenses to be named in the format LicenseRef-XXX where XXX is whatever you want to call your license. You could use this to refer to any type of legal text or conditions, whether free, open source or proprietary. Using this you can write a valid SPDX expression such as:
> 
> AGPL-3.0-only OR LicenseRef-CustomAlternateLicensing
> 
> Appendix V: Using SPDX short identifiers in Source Files describes how you can use these expressions in a source file, for example:
> 
> SPDX­License­Identifier: AGPL-3.0-only OR LicenseRef-CustomAlternateLicensing
> 
> I'd say this is sufficient to alert a tool to the presence of a custom license, though as there is no defined mechanism to link that LicenseRef to some license text in this context then a tool probably won’t be able to locate that license text automatically. Listing the custom license adjacent to this line or in a separate file alongside is probably the best you can do.

So, "GPL-3.0-only OR LicenseRef-MySuperCustomLicense" is valid SPDX expression, and it makes sense to include the full license terms in a license file within the NuGet package.

Thus, I think it's a valid use case to include both an SPDX expression AND a license file.

**Comment by karann-msft** [comment] 2018-08-10 15:11
@markusshaber good feedback. Know of any real world packages that need to be able to do this?

**Comment by markusschaber** [comment] 2018-08-13 08:26
@karann-msft While there's plenty of software using dual-license models (e. G. MongoDB), I don't have any examples of existing NuGet packages ready.

But maybe @agr has some, as he brought up the topic?

**Comment by karann-msft** [comment] 2018-08-14 08:14
@markusshaber something tells me he doesn't either :)

**Comment by markusschaber** [comment] 2018-08-14 09:32
@karann-msft it would be easy to query for existing NuGet packages if they only had a valid SPDX expression describing their license information in their metadata... :-)

**Comment by JimBobSquarePants** [comment] 2018-08-14 09:54
We intent to use dual licensing at https://github.com/SixLabors/ImageSharp. 

ServiceStack libraries are covered essentially a dual license but the Nuget packages point to a single license page.

**Comment by karann-msft** [comment] 2018-08-15 17:13
@markusschaber I didn't necessarily mean to limit you to nuget packages only :) (but nuget like ecosystems). In any case, we'll consider it for v2.

@JimBobSquarePants dual licenses are very much supported in the design. What are the two licenses you intend to use for Imagesharp?

**Comment by vbfox** [comment] 2018-09-04 22:16
@karann-msft One thing I noticed in the specification is that supported formats are "md, txt" but lot of repository have license files without extensions (It's still pure text) it would be nice for this case to be handled.

For example https://github.com/zeromq/clrzmq/blob/master/LICENSE

**Comment by karann-msft** [comment] 2018-09-04 22:44
@vbfox how about, if the extension is missing, we'll default to "txt" and treat a file without extension as a txt file?

**Comment by dabutvin** [comment] 2018-09-05 00:30
>License file inside the package - During the package ingestion, nuget.org will extract the license and host it on nuget.org. 

Is the guidance to package the License file in the root of the package? Where will nuget.org look?

Unpacking a nupkg, I am curious about the expected placement of LICENSE.

```
_rels/
[Content_Types].xml
lib/
LICENSE
PackageName.nuspec
package/
tools/
```

Thanks

**Comment by markusschaber** [comment] 2018-09-05 06:38
@vbfox I'm not a fan of license files without extension - it's hard to open file without extension on some platforms / environments, as the program associations are strictly bound to file extensions on those systems. So I'm in favour of discouraging extensionless LICENSE, README etc. files, and support @karann-msft with his suggestion of converting extensionless files to .txt files.

**Comment by vbfox** [comment] 2018-09-05 07:12
@karann-msft Yes I think they should be supported in the source nuspec as they are so common on repositories, but adding the extension in the nupkg would be perfect as it clarify how NuGet servers & clients should treat them

**Comment by karann-msft** [comment] 2018-09-07 01:15
@vbfox @markusschaber - thanks for that feedback. I'll update the spec to call that out.

@dabutvin - if you are using a well-known license, you don't need to put a file. You can just provide the license identifier.
If you have a custom license, then you must pack it as part of the package. The nuspec `license` metadata field should then point to the license file within the package. That's how nuget.org, as well as the client, will know where to look for it.

**Comment by tthiery** [comment] 2018-10-16 20:18
@karann-msft can you elaborate on the csproj strategy of it. Will there be a explicit property in it or do we  need to fallback to create a custom nuspec?

**Comment by karann-msft** [comment] 2018-11-01 04:01
@tthiery there will be an explicit property - https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#project-properties

**Comment by karann-msft** [comment] 2018-11-01 04:37
Technical spec is now available - https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)

**Comment by tthiery** [comment] 2018-11-01 06:39
Awesome. Just a warning: There is a spdx license name called `Unlicense` which is a real license. A keyword `Unlicensed` is very close to that.

**Comment by karann-msft** [comment] 2018-11-01 16:38
@tthiery thanks for the heads-up....what would you use instead of "unlicensed"?

**Comment by tthiery** [comment] 2018-11-01 16:52
Maybe `NonSpecified`?

Edit: from previous `None` to `NonSpecified`. None could be misinterpreted that the package is not licensed at all (which mean different things in different regions I guess).

**Comment by agr** [comment] 2018-11-07 21:36
npm uses `UNLICENSED`, I don't think we should introduce yet another special case. License expressions are case sensitive, so `UNLICENSED` will always be in upper case and `Unlicense` will always be in Pascal case, so it would be more difficult to have them mixed up.

**Comment by pombredanne** [comment] 2018-11-13 10:55
The use of "UNLICENSED" by npm is a rather confusing choice IMHO. The SPDX way is simpler and clearer: NONE or NO-ASSERTION. If you adopt SPDX expressions that would make the most sense (disclosures: I am involved in SPDX and I also maintain the [scancode-toolkit](https://github.com/nexB/scancode-toolkit) which is a license scanner so every choices you make here is something that eventually I will have to write code to support whatever new and unique ways you have to express licenses. I also maintain a comprehensive [license expression](https://github.com/nexB/license-expression/ ) parser)

**Comment by pombredanne** [comment] 2018-11-13 10:56
The spec at https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#project-properties references old and deprecated license ids such as https://spdx.org/licenses/GPL-2.0-with-bison-exception.html which would be best avoided IMHO

**Comment by karann-msft** [comment] 2018-11-13 23:22
@pombredanne we plan to not allow deprecated licenses and as a matter of fact, the client will warn on pack and nuget.org will block publishing a package if you use a deprecated license. (excuse the poor choice for an example in the spec)

**Closed as completed** 2018-11-20 20:36 UTC
Labels: Epic, Area:PackageDefinition

**Comment by rrelyea** [comment] 2018-11-20 20:38
Shipped in NuGet release 4.9
   (which ships in VS 2017 15.9 and .NET SDK 2.1.500 and .NET SDK 2.2.100)

**Comment by pombredanne** [comment] 2018-11-20 22:31
@ karann-msft 

> we plan to not allow deprecated licenses and as a matter of fact, the client will warn on pack and nuget.org will block publishing a package if you use a deprecated license. (excuse the poor choice for an example in the spec)

Good... but a reminder that deprecation is a moving target as each new version of the SPDX license list may come with new deprecations.

**Comment by pombredanne** [comment] 2018-11-20 22:47
@karann-msft commented on Sep 7 ...
> @dabutvin - if you are using a well-known license, you don't need to put a file. You can just provide the license identifier.

Actually if you do not include the license text of most open source license in a package you are creating a non-compliant package as most license texts should be included as a condition of the license. Using only a well known license identifier is not enough and not a substitute for the text in most cases and it certainly lack clarity always. **You need that and the text.** 

For example, take a simple license such as the MIT: including the full text is pretty much the only condition of the license.... so if you do not include it with a binary nuget package, then you are making your downstream users life miserable by shipping a nuget that is immediately non-compliant and eventually not licensed once downloaded. 
User redistributing this package will also need in this case to review in details the package and  re-include (and re-package as a new nuget ??) the missing upstream license texts to become compliant if they redistribute this.. 

So excluding texts is a sure way to create a jolly chain mess if you want my 2 cents.

**Comment by markusschaber** [comment] 2018-11-21 16:20
As far as I can see, Debian distributes common licenses in `usr/share/common-licenses` to avoid duplications of license texts. I'm not sure how they manage to do it in detail, but Debian legal is well known for their "attention to detail"...

**Comment by pombredanne** [comment] 2018-11-26 17:17
@markusschaber  indeed. And Debian does this only for a very few licenses that allow such practice... not for MIT licenses for instance. Furthermore, Nuget is not a distro, so you cannot assume that there is some base present

**Comment by karann-msft** [comment] 2018-12-11 20:28
@pombredanne what I meant to say was, NuGet.org does not need the license file if you provide the license expression. NuGet.org will display license information based on the license expression alone.
If the license requires you to include the license text, you should absolutely pack it within the package. You don't need to add metadata to point to the file.

**Comment by webJose** [comment] 2019-01-09 00:07
Hello!  Could you provide a link to the documentation of the new license element here?  It would make things a lot simpler for us newcomers.

Thank you very much.

**Comment by anangaur** [comment] 2019-01-09 00:35
@webJose Updated the [issue description](https://github.com/NuGet/Home/issues/4628) with useful links (including documentation)
