### ISSUE TITLE
Reinstall package with modified package.config fails using TFS VC

### ISSUE THREAD

**Issue by OsirisTerje** [NuGet/Home#1713] opened 2015-11-11 07:30 UTC
Using TFS 2015, TFS VC, and VS 2015 U1 RC:

If I have a package.config file that have pending changes, and do reinstall of a nuget package using the command:

Update-package   -reinstall WhateverPackage 

the process takes a huge amount of time, looks like timeouts, and then fails with a series of TF203069 errors:   "<somefolder>packages.config could not be deleted because that change conflicts with another...."

And when it is in the process it blocks the UI thread completely, for a minute at a time.  Right now, it has processed 9 files this way, spending more than 10 minutes. 

First:  Blocking the UI thread is not nice.
Second: Nuget should not delete the package file, just delete the relevant parts of the file.

**Comment by yishaigalatzer** [comment] 2016-03-11 22:48
@zhili1208 can you please verify this issue is fixed in 3.4?

**Comment by skofman1** [comment] 2016-03-14 20:45
Verified. The issue is fixed in 3.4.

**Closed as completed by skofman1** 2016-03-14 20:45 UTC
Labels: Priority:2, Type:Bug
