### ISSUE TITLE
Thread affinity in BitmapSource and WPF UI threads

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#9161] opened 2020-02-10 19:34 UTC
- Find out if `BitmapImage`/`BitmapSource` has thread affinity to WPF UI threads

**Comment by rrelyea** [comment] 2020-10-15 14:23
dupe of https://github.com/NuGet/Home/issues/8505
(fixed in 5.9).

was possible to freeze the bitmapsource if we loading via a memorystream.

**Closed as completed by rrelyea** 2020-10-15 14:23 UTC
Labels: Product:VS.Client, Type:Bug, Category:Quality Week
