### ISSUE TITLE
dotnet pack doesn't build when "Generate NuGet Pkg on Build"

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#6118] opened 2017-10-30 17:33 UTC
_From @robertmuehsig on October 29, 2017 21:28_

The documentation tells me that "dotnet pack" should build the project (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x) 

Unfortunatly this behaviour is missing if I enable the "create nuget package on build":

![image](https://user-images.githubusercontent.com/756703/32148454-975bd2b0-bcf7-11e7-8b36-f08b26a20f63.png)

When I now execute dotnet pack, it fails:
![image](https://user-images.githubusercontent.com/756703/32148461-a740318a-bcf7-11e7-90e0-6f8e36c66f66.png)

Repo steps:

* Create a new .NET Core Lib
* Enable "Generate NuGet Package on build"
* run "dotnet pack" inside the lib folder

_Copied from original issue: dotnet/sdk#1698_

**Comment by anangaur** [comment] 2017-10-30 17:51
"Generate NuGet Package on build" is a build property and `dotnet build` should create the NuGet package by calling pack target in MSBuild.

`dotnet pack` should just work with/without the  "Generate NuGet Package on build" property

**Comment by anangaur** [comment] 2017-10-30 17:57
Tried the scenario now and it indeed is a bug.
1. Do not set  "Generate NuGet Package on build" property and `dotnet pack` works fine
2. Set the property and  `dotnet pack` **does not** work.

**Comment by jp2masa** [comment] 2017-10-31 16:14
This is likely by design (https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/Pack.targets#L38), probably adding Build as a target dependency causes a circular dependency (after `Build`, `Pack` is called, which would call `Build`).
Anyway, this is definitely a bug and it can probably be fixed.

**Comment by jainaashish** [comment] 2018-06-29 18:15
closing it by design

**Closed as completed by jainaashish** 2018-06-29 18:15 UTC
Labels: Priority:1, Type:Bug, Resolution:ByDesign, Functionality:Pack

**Comment by Inrego** [comment] 2020-02-12 09:09
At the very least, the documentation of `dotnet pack` should be updated to make this behavior clear.

**Comment by unitrix0** [comment] 2020-12-20 10:04
agreed https://github.com/dotnet/docs/issues/22097
