### ISSUE TITLE
NuGet.config support for checked in (readonly) files in TFS needs to be improved

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#868] opened 2015-07-01 22:00 UTC
The `Settings` API does not play well with NuGet.config files that might be checked in. It is quite possible for solution level \ project level NuGet.config files to be checked in to source control (specifically TFS). Supporting this would require checking out these files prior to updating them.

This follows based on discussion in https://github.com/NuGet/NuGet3/pull/70#discussion_r33729141

**Comment by konste** [comment] 2015-07-22 02:15
I believe you underestimate the magnitude of the problem. For all people using TFS server side workspaces (most of the TFS enterprise customers) solution level NuGet.config is checked in and is read only. What they see when trying to use NuGet is big and scary dialog box saying exactly this:
---------------------------
The 'NuGetPackage' package did not load correctly.
The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\...\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml'.
Restarting Visual Studio could help resolve this issue.
---------------------------

This *looks* like the feature completely broken. IMHO it is a showstopper.

Konstantin

**Comment by pranavkm** [comment] 2015-07-22 16:07
@konste that seems odd - reading the file shouldn't cause a problem. We had issues where loading the extension would attempt to write to the config and fail causing the exception you see here, but that should be fixed (https://github.com/NuGet/Home/issues/979). 

Are you still seeing this with the RTM bits?

**Comment by konste** [comment] 2015-07-22 16:29
Yes, it definitely shows that scary dialog with RTM bits (I have not had any other bits) and that #979 is marked as Fixed by @emgarten only to consolidate tracking of the issue under #868, i.e. here. The issue is not really fixed and looks like P0 to me.

**Comment by Calidus** [comment] 2015-07-22 20:34
I am running into the same issue as @pranavkm, checking the file out prior to using nuget seems to the only way to get around issue.
![screenshot 2015-07-21 11 46 37](https://cloud.githubusercontent.com/assets/1683712/8836513/7ae1a89a-308f-11e5-96ab-dd3adb6ecebb.png)

**Comment by pranavkm** [comment] 2015-07-22 20:54
Sorry, @emgarten just pointed out that we fixed this issue in the upcoming milestone as part of https://github.com/NuGet/Home/issues/861. An updated VSIX should be out pretty soon.

**Comment by yishaigalatzer** [comment] 2016-01-28 22:37
@zhili1208 the fix here, is to not save settings back to disk if the values of a file is exactly the same.

**Comment by konste** [comment] 2016-01-28 22:39
Phew! Finally!

**Comment by zhili1208** [comment] 2016-02-22 19:36
verified against latest bits, it's already fixed at https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/Options/PackageSourcesOptionsControl.cs#L224-L228. will close it and feel free to reopen it if this issue still repro on your machine

**Closed by zhili1208** 2016-02-22 19:36 UTC
Labels: Area:VS.Client, Priority:2
