### ISSUE TITLE
After create Windows 8.1 App, add "Azure Mobile Services" , meet error.

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#500] opened 2015-04-29 01:25 UTC
Repro steps:
1.New Project->Visual C#->Windows->Windows 8->Hub App(Windows 8.1 Universal)/Blank App
2.Right-click on the References node and select "Add Connected Service"
3.Choose Azure Mobile Services and click Configure.
4.Create new Mobile Services and click Add.
5.Wait complete  and error dialog pop up.
Repro in :Main build 22827.01,Main 22828.01, WPT 22828.00 VS+SDK +NuGet VSIX(\\\nuget\NuGet\Share\Drops\CI\dev\268)
![mobile](https://cloud.githubusercontent.com/assets/12129698/7383406/70d4b002-ee51-11e4-8728-c89c63c37f15.png)

Dump File link:\\vwdbuild01\temp\V-lawu\dumpfile\500

**Comment by deepakaravindr** [comment] 2015-04-29 20:47
@yishaigalatzer , Possible duplicate of https://github.com/NuGet/Home/issues/501

**Comment by deepakaravindr** [comment] 2015-05-01 00:09
This is a duplicate of #501

**Closed by deepakaravindr** 2015-05-01 00:09 UTC
