### ISSUE TITLE
nuget pack don't works when Net 4.6.1 project has project reference to netstandard project

### ISSUE THREAD

**Issue by Frank591** [NuGet/Home#6202] opened 2017-11-20 08:45 UTC
## Details about Problem
NuGet product used:NuGet.exe
NuGet version : 4.4.1.4656
VS version (if appropriate): VS 2017 (15.4.4)
OS version: win 10 (10.0 Build 15063)

## Detailed repro steps so we can see the same problem

I have 2 libraries:

    first library(`First.csproj`) - netstandard1.3
    second library(`Second.csproj`) - .Net framework 4.6.1

`Second.csproj` has project reference to` First.csproj`.

Compilation into VS2017 working without problems.

After that i want to create nuget package for` Second.csproj` with dependency to` First.csproj`, but command

` nuget pack Second.csproj -IncludeReferencedProjects`

Failed with error

> 
> Error occurred when processing file 'E:\blabla\First.csproj': Unable to find 'bin\Release\First\bin\Release\'. Make sure the project has been built.
>   Unable to find 'bin\Release\First\bin\Release\'. Make sure the project has been built.

How can i correctly pack my .NET Framework 4.6.1 project with adding dependency to netstandard library?

**Comment by PatoBeltran** [comment] 2017-11-20 22:03
does the bin/Release directory exists? Have you built the projects with the release definition?

**Comment by PatoBeltran** [comment] 2017-11-21 00:55
@Frank591 this seems to be a known issue dupe of https://github.com/NuGet/Home/issues/4054. Please try to use dotnet exe and see if this fixes your problem. Closing this issue in favor of #4054.

**Closed as completed by PatoBeltran** 2017-11-21 00:55 UTC
Labels: Resolution:Duplicate, Functionality:Pack

**Comment by Frank591** [comment] 2017-11-21 07:04
`dotnet pack` don't work for NET 4.6.1 project. It fails with error 
`E:\blabla\Second.csproj : error MSB4057: The target "pack" does not exist in the project.`
