### ISSUE TITLE
"dotnet restore" doesn't work when project dependencies are manually specified

### ISSUE THREAD

**Issue by Daniel15** [NuGet/Home#5193] opened 2017-05-09 05:50 UTC
## Details about Problem

Visual Studio has a "project dependencies" feature that lets you manually specify dependencies between projects in a solution:
![](http://ss.dan.cx/2017/05/Project_Dependencies_08-22.43.55.png)

In one of my open-source projects, I was using this as part of a hack with the old tooling to reference an `xproj` project from a `csproj`. That hack is no longer needed, but I forgot about it until I encountered a strange problem: 

`dotnet restore` does not restore the NuGet packages for any projects that use this feature.

See the test case here:  [NuGetRestoreBug.zip](https://github.com/NuGet/Home/files/985648/NuGetRestoreBug.zip)

I have two solution files:
`good.sln` does not use the project dependencies feature:
```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26228.4
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "A", "A\A.csproj", "{56B54AB3-3FBE-45D6-A15E-8B8678121B39}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "B", "B\B.csproj", "{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "C", "C\C.csproj", "{4395093E-5ACA-4736-A8FD-55901807D37F}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{56B54AB3-3FBE-45D6-A15E-8B8678121B39}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{56B54AB3-3FBE-45D6-A15E-8B8678121B39}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{56B54AB3-3FBE-45D6-A15E-8B8678121B39}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{56B54AB3-3FBE-45D6-A15E-8B8678121B39}.Release|Any CPU.Build.0 = Release|Any CPU
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}.Release|Any CPU.Build.0 = Release|Any CPU
		{4395093E-5ACA-4736-A8FD-55901807D37F}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{4395093E-5ACA-4736-A8FD-55901807D37F}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{4395093E-5ACA-4736-A8FD-55901807D37F}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{4395093E-5ACA-4736-A8FD-55901807D37F}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

`bad.sln` **does** use it - `A` depends on `B`, which depends on `C`:
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26228.4
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "A", "A\A.csproj", "{56B54AB3-3FBE-45D6-A15E-8B8678121B39}"
	ProjectSection(ProjectDependencies) = postProject
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C} = {7D13BEEC-5FCB-4145-9A74-64D859A6D70C}
	EndProjectSection
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "B", "B\B.csproj", "{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}"
	ProjectSection(ProjectDependencies) = postProject
		{4395093E-5ACA-4736-A8FD-55901807D37F} = {4395093E-5ACA-4736-A8FD-55901807D37F}
	EndProjectSection
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "C", "C\C.csproj", "{4395093E-5ACA-4736-A8FD-55901807D37F}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{56B54AB3-3FBE-45D6-A15E-8B8678121B39}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{56B54AB3-3FBE-45D6-A15E-8B8678121B39}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{56B54AB3-3FBE-45D6-A15E-8B8678121B39}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{56B54AB3-3FBE-45D6-A15E-8B8678121B39}.Release|Any CPU.Build.0 = Release|Any CPU
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{7D13BEEC-5FCB-4145-9A74-64D859A6D70C}.Release|Any CPU.Build.0 = Release|Any CPU
		{4395093E-5ACA-4736-A8FD-55901807D37F}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{4395093E-5ACA-4736-A8FD-55901807D37F}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{4395093E-5ACA-4736-A8FD-55901807D37F}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{4395093E-5ACA-4736-A8FD-55901807D37F}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

`dotnet restore good.sln` shows what you'd expect:
```
λ dotnet restore good.sln
  Restoring packages for C:\temp\NuGetRestoreBug\A\A.csproj...
  Restoring packages for C:\temp\NuGetRestoreBug\B\B.csproj...
  Restoring packages for C:\temp\NuGetRestoreBug\C\C.csproj...
......
```

However, `dotnet restore bad.sln` only restores packages for `C`:
```
λ dotnet restore bad.sln
  Restoring packages for C:\temp\NuGetRestoreBug\C\C.csproj...
  Lock file has not changed. Skipping lock file write. Path: C:\temp\NuGetRestoreBug\C\obj\project.assets.json
```

NuGet product used: `dotnet restore`

dotnet.exe --version: 1.0.0

VS version: VS2017

OS version: Windows 10 10.0.16188.1000

**Comment by emgarten** [comment] 2017-05-09 06:06
Thanks for the report @Daniel15, this will be fixed in CLI 2.0.0 and VS 15.3

Dupe of https://github.com/NuGet/Home/issues/4578

**Comment by Daniel15** [comment] 2017-05-09 06:10
Haha, thanks. I didn't find that issue when searching. I guess I didn't need to spend all this time building a standalone repro 😛

**Comment by emgarten** [comment] 2017-05-09 06:30
I always appreciate a standalone repro! :smile:

**Comment by mishra14** [comment] 2017-05-09 21:46
Closed as dupe

**Closed as completed by mishra14** 2017-05-09 21:46 UTC
Labels: Resolution:Duplicate
