### ISSUE TITLE
[Bug]: NuGet SDK client cannot search for packages for a given packageType

### ISSUE THREAD

**Issue by vlada-shubina** [NuGet/Home#11069] opened 2021-07-22 11:03 UTC
### NuGet Product Used

dotnet.exe

### Product Version

5.10.0, 6.0.0-preview.2.129

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Product is NuGet Client SDK.
Requirement: search for all packages of package type `Template` using NuGet SDK:

Code: 

```
            SourceRepository repository = Repository.Factory.GetCoreV3("https://api.nuget.org/v3/index.json");
            var searchResource = await repository.GetResourceAsync<PackageSearchResource>().ConfigureAwait(false);

            var searchFilter = new SearchFilter(includePrerelease: true);
            searchFilter.PackageTypes = new[] { "Template" };
            var searchResult = await searchResource.SearchAsync("", searchFilter, 0, 10, NullLogger.Instance, default);

            foreach (var pack in searchResult)
            {
                Console.WriteLine(pack.Identity.Id);
            }    
```
Output:
```
Newtonsoft.Json
Microsoft.Extensions.DependencyInjection
Microsoft.Extensions.Logging
Serilog
Microsoft.EntityFrameworkCore
Castle.Core
Moq
Microsoft.Bcl.AsyncInterfaces
AutoMapper
Microsoft.ApplicationInsights
```

Expected: only packages of template type is returned.
Actual: packages of any type is returned

Related: https://github.com/dotnet/templating/pull/3498

Note: using `https://azuresearch-ussc.nuget.org/query?packageType=Template&skip=0&take=10&prerelease=true` works as expected.

### Verbose Logs

```shell
not applicable
```

**Comment by zivkan** [comment] 2021-07-22 12:45
Duplicate of https://github.com/NuGet/Home/issues/8915.  Please add a 👍 reaction there.

**Closed as completed by zivkan** 2021-07-22 12:45 UTC
