### ISSUE TITLE
'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#5162] opened 2017-05-04 07:28 UTC
Users of Json.NET are reporting this error message:

`'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'`

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

Sounds like the problem is in VS2012

## Detailed repro steps so we can see the same problem

1. Install Newtonsoft.Json 10.0.2 in VS2012

2. The error!

Issue where users are reporting the problem: https://github.com/JamesNK/Newtonsoft.Json/issues/1265

**Comment by emgarten** [comment] 2017-05-04 22:35
VS 2012 does not support *netstandard*.

The user experience here could be improved by setting the minimum client version required for the package to 2.12. This is the lowest version of NuGet that supports *netstandard*.

**Comment by JamesNK** [comment] 2017-05-05 01:34
If NuGet in VS 2012 doesn't support netstandard why is it choosing to install that target instead of net45 or PCL that it does support?

**Comment by JamesNK** [comment] 2017-05-05 01:35
Also how does minimum client version work with csproj + pack?

**Comment by rohit21agrawal** [comment] 2017-05-05 02:05
@JamesNK just specify MinClientVersion as a property in your csproj file you are packing.  https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack.Library/Pack.targets#L170

**Comment by emgarten** [comment] 2017-05-05 02:07
> If NuGet in VS 2012 doesn't support netstandard why is it choosing to install that target instead of net45 or PCL that it does support?

The older client throws the error you are seeing when it reads the nuspec. It encounters two unsupported framework dependency groups (netstandard1.0 and netstandard1.3) and fails when merging the dependencies together. It doesn't get as far as selecting assets from the package unfortunately.

**Comment by JamesNK** [comment] 2017-05-05 04:54
I see! Not ideal but we can't change the past.

Ok, I'll include a min version. What value do you recommend?

**Comment by emgarten** [comment] 2017-05-05 06:24
The system packages use 2.12, I would stick to that.

Example in nuspec:
```xml
<metadata minClientVersion="2.12">
```

**Comment by drieseng** [comment] 2017-05-05 18:04
So instead of fixing this issue, you actually advise rendering nuget packages unusable for those still stuck with VS 2012?

Note that this issue is a duplicate of #3131.

**Comment by emgarten** [comment] 2017-05-05 22:46
@drieseng are you able to repro this with NuGet 4.1.0?

**Comment by drieseng** [comment] 2017-05-08 20:29
@emgarten: The latest NuGet Package Manager available for VS 2012 is *2.8*. The download site for NuGet no longer lists VS 2012, and there's definitely not a *4.1.0* for VS 2012.

**Comment by evil-shrike** [comment] 2017-05-10 15:40
Hi.
I'm having an issue with the same error but unrelated to netstandard. 
I'm restoring packages (with `nuget.exe Restore`, nuget 3.4/3.5) for a solution from several nuget sources. 
Projects in the solution have different dependencies for Newtonsoft.Json: project1 depends on 6.x and project2 depends on 10.x. 
Source1 has 6.x version of Json.net and source2 has 10.x:
```ps
nuget.exe restore "path\file.sln" -Source "$source1;$source2" -NoCache
```
Source1/Source2 can be folders. 
This restore cmd ends with error:
```
Installing 'Newtonsoft.Json 10.0.2'.
'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'.
build.ps1:Build failed at nuget restore.
```

**Comment by eMelero** [comment] 2017-05-10 20:21
exactly same issue, it worked installing older Newtonsoft.Json version trhough PM (Package Manager Console)
PM> Install-Package Newtonsoft.Json -Version 9.0.1

**Comment by emgarten** [comment] 2017-05-10 23:30
The root cause of this issue is https://github.com/NuGet/Home/issues/3131

**Closed as completed by emgarten** 2017-05-10 23:30 UTC
Labels: Resolution:Duplicate
