### ISSUE TITLE
Improve inner-loop testing for packages

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#9366] opened 2020-03-31 12:41 UTC
Its difficult for package authors to test their package while in development. Some context: https://twitter.com/khellang/status/1244892768717209600
![image](https://user-images.githubusercontent.com/14800916/78027440-fdd4af80-737a-11ea-86d3-1054587e5119.png)

Related issue, that was closed: #1821

Lets discuss possible (current/future) solutions, here.

**Comment by anangaur** [comment] 2020-03-31 12:46
/cc: @nkolev92 @rrelyea fro NuGet
@khellang, @joacar from twitter thread

**Comment by joacar** [comment] 2020-03-31 14:15
I'm working on a NuGet packages that integrates with MSBuild by having `.targets` file in `build/` directory. This use case isn't covered by adding library under test the project reference way since the files won't be picked up by VS (latest 16.5). I'll outline the steps I've done to make it work

1. Add `nuget.config` to sample project (project used to test NuGet) and add directory where artifact will be published
1. Pack NuGet to directory in step 1.
1. Add packages to sample project using CLI (nuget.config not honored in VS) `dotnet add <csproj> package <nuget> -v <version>`. 

So it works. Now we do some changes to our library and want to test them. Here we need to decide whether to update NuGet version or not.

**Leave version intact**
1. Source code changes
1. Pack NuGet

Since the version is the same, the global packages path (`nuget locals global-packages --list`) is unchanged and `dotnet add` doesn't add the newly created nuget. Solution is to remove the directory from global packages path and then add it.

**Update version**
1. Source code changes
1. Update NuGet version
1. Change version in referenced project

I've gone with **Leave version intact** and wrote a bash script to perform the steps.

```bash
#!/bin/bash

if [[ -z ${NUGET_GLOBAL_PACKAGES} ]]
then
  echo "Environment variable NUGET_GLOBAL_PACKAGES must be set"
  echo "Run 'nuget locals global-packages -list' and export value"
  exit
fi

if [[ -z $1 ]]
then
  echo "Version is required"
  exit
fi

ROOT=`pwd`

# Delete cached packages since version is most likely not changed
rm -rf ${NUGET_GLOBAL_PACKAGES}<package_directory>
# Pack new NuGet
dotnet pack -c Debug <proj> -p:RepoRoot=${ROOT}
# Add package to sample. Since pre-release version is required
dotnet add <proj> package <package> -v $1

```

**Comment by nkolev92** [comment] 2020-03-31 18:03
Hey all, this ask is a duplicate of https://github.com/NuGet/Home/issues/6579. 

Clearing the individual packages in the global packages folder is the best thing we have today. 

An idea would be to provide some metadata on a package that we can put in a separate directory, but that mgiht get tricky from a perf perspective.

**Closed as completed by nkolev92** 2020-03-31 18:03 UTC
Labels: Resolution:Duplicate, Type:Feature, Style:PackageReference

**Comment by khellang** [comment] 2020-03-31 18:14
This issue just keeps coming up, spread all over the place. Here's a thread (with a myriad of links) on this very topic going back years; https://github.com/dotnet/sdk/issues/1151. And here's a year-old thread from Twitter with a *bunch* of comments and feedback; https://twitter.com/natemcmaster/status/1099021447920406529.

**Comment by gioce90** [comment] 2024-11-14 17:06
> Clearing the individual packages in the global packages folder is the best thing we have today.

Yes @nkolev92 , this is my same conclusion, as pointed out in #13918 and also [here](https://github.com/NuGet/Home/issues/6579#issuecomment-2476832378)

**Comment by gioce90** [comment] 2024-12-30 12:01
Hi @anangaur  @joacar  @nkolev92  , I’ve faced similar issues in the past when working with NuGet packages. As I mentioned [here](https://github.com/NuGet/Home/issues/6579#issuecomment-2476832378), I created a tool to address these problems.
I’ve now decided to make my solution public by releasing a package called NuJet (https://github.com/gioce90/NuJet). It enhances the inner-loop development and testing process for NuGet packages, especially in local workflows.

Feel free to check it out—I’d love to hear your feedback!
