### ISSUE TITLE
Multi-targeted project fails to restore with a conditional NoWarn property group

### ISSUE THREAD

**Issue by jeromelaban** [NuGet/Home#6662] opened 2018-03-12 03:05 UTC
Using VS2017 15.6.0, and [the attached solution](https://github.com/NuGet/Home/files/1801280/20180311-nuget-nowarn-restore-failure.zip):

- Run git clean -fdx on the zipped repo (no restored graph must be present)
- Open VS2017 for the solution
- Notice the background restore does not start
- Try building, the error `Error occurred while restoring NuGet packages: The operation failed as details for project RestoreFailure could not be loaded.` appears at the beginning.

Commenting out this:
```xml
<PropertyGroup Condition=" '$(TargetFramework)' == 'net46'">
  <NoWarn>$(NoWarn);68</NoWarn>
</PropertyGroup>
```
or removing the condition makes the restore work properly.

Also note that the CLI restore does not have any issue restoring this project.

**Comment by nkolev92** [comment] 2018-08-06 23:25
Duplicate of https://github.com/NuGet/Home/issues/5712. 

//cc @mishra14 @zhili1208

**Closed as completed by nkolev92** 2018-08-06 23:25 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Bug, Area:ErrorHandling
