### ISSUE TITLE
Invalid Nuget.Build.Tasks.Console package when building from source

### ISSUE THREAD

**Issue by dseefeld** [NuGet/Home#9705] opened 2020-06-22 18:37 UTC
## Details about Problem

Building Nuget.Build.Tasks.Console in source-build results in invalid contentFiles in the generated package.  Trailing backslashes in the PackagePath on the two lines linked below cause a double slash in the output package.  Related to https://github.com/NuGet/Home/issues/7004

https://github.com/NuGet/NuGet.Client/blob/784274cc9b2002ca73055e8134064261118d8a01/src/NuGet.Core/NuGet.Build.Tasks.Console/NuGet.Build.Tasks.Console.csproj#L67-L68

dotnet.exe --version (if appropriate): 5.0.100-preview.4.20258.7
OS version (i.e. win10 v1607 (14393.321)): CentOS Linux 8 (Core)

Worked before? Not sure

## Detailed repro steps so we can see the same problem

1. Build Nuget.Build.Tasks.Console on a non-windows OS

2. Inspect the resulting nuspec in Nuget.Build.Tasks.Console.*.nupkg (Note the double slash in contentFiles entries)

**Comment by rrelyea** [comment] 2020-06-22 20:09
@dominoFire 
cc @jeffkl @nkolev92

**Comment by nkolev92** [comment] 2020-06-29 16:24
I imagine the problem is not normalizing the slashes before appending the trailing slash. 

We should #7004, but I imagine removing the trailing slash would work just fine for this scenario. 

@dseefeld Do you know if there are any consumption problems with the built nupkg? 
What is the impact of this?

**Comment by dominoFire** [comment] 2020-07-10 00:48
@nkolev92 dotnet/source-build is impacted by this bug. The source-build'ed nuget packages created and consumed in source-build have this problem.

There's a patch that address this issue in source-build. Also, a PR in NuGet.Client is ready to address this specific package. https://github.com/NuGet/NuGet.Client/pull/3511

**Comment by aortiz-msft** [comment] 2020-07-24 23:03
@dominoFire https://github.com/NuGet/NuGet.Client/pull/3511 is merged. Can we close this issue or is there additional work left?

**Comment by dominoFire** [comment] 2020-07-27 22:49
I can confirm that there are no more extra slashes in the latest dev branch.

Before:

```xml
   <contentFiles>
      <files include="any/net472//NuGet.Build.Tasks.Console.exe" buildAction="None" copyToOutput="true" />
      <files include="any/netcoreapp2.1//NuGet.Build.Tasks.Console.dll" buildAction="None" copyToOutput="true" />
      <files include="any/netcoreapp2.1//NuGet.Build.Tasks.Console.runtimeconfig.json" buildAction="None" copyToOutput="true" />
    </contentFiles>
```

After:

```xml
    <contentFiles>
      <files include="any/netcoreapp2.1/NuGet.Build.Tasks.Console.dll" buildAction="None" copyToOutput="true" />
      <files include="any/netcoreapp2.1/NuGet.Build.Tasks.Console.runtimeconfig.json" buildAction="None" copyToOutput="true" />
    </contentFiles>
```

I will close the for now. If you need more heelp, feel free to reach to us.

**Closed as completed by dominoFire** 2020-07-27 22:49 UTC
Labels: Priority:2, Type:Bug, Type:Engineering
