### ISSUE TITLE
Restoring a project with tools reference seems to throw extra logs

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5088] opened 2017-04-20 18:46 UTC
@shanselman reported this through email.

Seems that restoring a project containing a tools reference displays _TWO identical lines that both say restoring packages._

**Comment by mishra14** [comment] 2017-04-20 18:46
@emgarten can you confirm?

**Comment by emgarten** [comment] 2017-04-20 19:16
Dupe of https://github.com/NuGet/Home/issues/4415

**Closed as completed** 2017-04-20 19:16 UTC
Labels: Resolution:Duplicate, Functionality:Restore, Style:PackageReference
