### ISSUE TITLE
IncludeSource in .csproj doesn't work

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#6931] opened 2018-05-14 15:03 UTC
_From @josh-endries on May 13, 2018 0:57_

I've been trying to embed source and/or PDBs into a NuGet package but can't figure it out with the new `csproj` files. I have a project that targets a few frameworks. I'm using VSTS, which is a whole other mess, but it doesn't work locally in VS2017 either. I used to just use `<files/>` in the `nuspec` file, but that doesn't work with the new projects, apparently, or multi-targeting at least.

Based on [this page](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) I tried to add `<IncludeSource>true</IncludeSource>` to my `PropertyGroup` but that didn't work. It did build a symbols package but that's not what I'm looking for. I also tried adding `<IncludeSourceFilesProjectOutputGroup></IncludeSourceFilesProjectOutputGroup>` but that didn't work either. There's no real or useful documentation on that though and I don't know what it is, it just sounded related. This whole thing is so confusing it's insane.

I just tried `msbuild /t:pack /p:IncludeSource=true` but that didn't do it either. The page linked above doesn't really make clear what sort of keyword they all are.

_Copied from original issue: Microsoft/msbuild#3302_

**Comment by mishra14** [comment] 2018-05-15 00:24
@rohit21agrawal is this supported in csproj format?

**Comment by rohit21agrawal** [comment] 2018-05-15 08:02
@josh-endries IncludeSource property. by design, is supposed to create a symbols nupkg that will contain all the source files within the src folder of the nupkg. 

However, if that's not what you want, there are enough extension points in Pack targets to achieve what you are trying to do. Take a look at: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#targetsfortfmspecificcontentinpackage 

You can use ``` SourceFilesProjectOutputGroup ``` to get a list of all source files and pack it at the desired path within the package.

**Comment by rohit21agrawal** [comment] 2018-05-15 08:02
@mishra14 you can close this as by design , and as a question.  @josh-endries can continue to engage here if he has more questions.

**Closed as completed** 2018-05-15 18:49 UTC
Labels: Resolution:Question, Resolution:ByDesign, Functionality:Pack

**Comment by djeikyb** [comment] 2019-08-13 04:31
@rohit21agrawal Can you explain more? I'm unzipping both my nupkg and snupkg, and there is no folder named "src". I'm using the dotnet core cli version 2.2.401 inside a docker container from image "mcr.microsoft.com/dotnet/core/sdk:2.2". I run `dotnet build` followed by `dotnet pack --include-source`. I also tried `dotnet msbuild /t:pack /p:IncludeSource=true /p:IncludeSymbols=true`. The target framework is netcoreapp2.2.

I expect at least one of the nupkg or snupkg to contain a folder named src. I expect that folder to contain the c# source code of the classlib I'm building. Are my expectations correct? What _ought_ to be happening?

If it helps, I'm coming from a java background where packaging the source lets most IDEs navigate through dependent libs without decompiling, making it easier to read, set breakpoints, etc. I suspect I have a fundamental misunderstanding of what IncludeSource means, despite having read some of the dotnet cli and msbuild docs.

**Comment by davidhunter22** [comment] 2020-03-19 23:52
I am also having this issue adding <IncludeSource> does not include the source in the created nupkg or snupkg file. When the was closed as "ByDesign" I would also add what is the "Design" supposed to do then?

**Comment by mldisibio** [comment] 2024-10-29 21:16
In case anyone else finds this thread out of frustration, I discovered that if your `.csproj` file contains `<EmbedAllSources>true</EmbedAllSources>` and your nuget command, in whatever form, contains `dotnet pack --include-source` you indeed get two files: `mylib.1.0.0.nupkg` and `mylib.1.0.0.symbols.nupkg` which contains the `src` directory. 
What I did not find documented anywhere by anyone is that 

- both packages are identical, except the `symbols.nupkg` one contains the `src` directory
- if **_all_** you push using `nuget push` is the `mylib.1.0.0.symbols.nupkg`, then it gets stored by nuget as a regular `mylib.1.0.0.nupkg`  but continues to contain the source files. (`nuget push` will attempt to push both, but the `symbols.nupkg` is then seen as a duplicate and not uploaded)

Caveat is: I host a local on disk nuget repository, so did not try this with nuget.org. This is for internal team productivity...using packaged libraries but navigating to the actual source code from the projects referencing those libraries. (And no, SourceLink would not work with our IT fire-walled repositories).

But I did test the F12 navigation and whereas everything else would inevitably 'decompile' the package dll, this approach opened an 'embedded' source file with all the original warts and comments and formatting.

I also tried following the instructions to create a `snupkg` format, but not only did I not see the `src` folder, it really is not what I wanted, like the OP and others described. This is more about navigating to source code without decompiling rather than debug symbols. Plus the end user needs to configure a symbols server to get your snupkg.
