### ISSUE TITLE
Nuget treats path starting with / as arguments on WSL

### ISSUE THREAD

**Issue by maxbl4** [NuGet/Home#12912] opened 2023-09-29 12:15 UTC
### NuGet Product Used

NuGet.exe

### Product Version

6.7.0

### Impact

I'm unable to use this version

### Repro Steps & Context

I'm using Nuget.Commandline 6.7.0 package to run Nuget on Ubuntu 22 in WSL.
Looks like it treats any argument starting with / as an argument option, so a path starting with / does not work.
E.g.
nuget pack /home/my.nuspec # responds with error: Unknown argument /home/my.nuspec
But
cd /home
nuget pack my.nuspec # works fine

Converting all paths to be relative is a big pain

**Comment by nkolev92** [comment] 2023-09-29 17:07
That seems to only be an issue on WSL. 

https://github.com/NuGet/NuGet.Client/blob/681bf33f7d16747a3ce699f016739e8bf6281c69/src/NuGet.Clients/NuGet.CommandLine/CommandLineParser.cs#L21C38-L21C60

Quick test on WSL, 

```cs
Console.WriteLine(Environment.OSVersion.Platform);
```

seems to write out: 

```console
Win32NT
```

**Comment by zivkan** [comment] 2023-09-30 09:13
I believe this is by design, how WSL works: https://learn.microsoft.com/en-us/windows/wsl/filesystems

At the end of the doc, they say how to disable this interop, preventing you from being able to launch win32 executions from within WSL, if it's confusing.

If you want to run nuget.exe from within Linux, WSL or otherwise, you need to install Mono: https://www.mono-project.com/

**Comment by nkolev92** [comment] 2023-10-02 18:29
Thanks @zivkan 

Closing per the above.

**Closed as completed by nkolev92** 2023-10-02 18:29 UTC
Labels: Type:Bug, Product:NuGet.exe, Resolution:NotABug
