### ISSUE TITLE
Change TPMinV in UWP with PackageRefs breaks the build

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#4820] opened 2017-03-16 01:35 UTC
## Details about Problem

Using Dev15.1

Create UWP project targeting RS2 (PackageRef)

Retarget TPV to RS1
Retarget TPMinV to something else

After project reloads, build is failing with error:

1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(197,5): error : Your project is not referencing the "UAP,Version=v10.0.10586" framework. Add a reference to "UAP,Version=v10.0.10586" in the "frameworks" section of your project.json, and then re-run NuGet restore.

**Comment by emgarten** [comment] 2017-03-16 01:39
It looks like this is coming from here:
https://github.com/NuGet/NuGet.BuildTasks/blob/dev/src/Microsoft.NuGet.Build.Tasks/Microsoft.NuGet.targets#L110

I'm not sure why this fallback would be needed, we should be able to leave it out if a target framework was passed in.

**Comment by emgarten** [comment] 2017-03-16 01:39
We could also check if the restore style is PackageReference and just build the correct TFM.

**Comment by jainaashish** [comment] 2017-03-16 20:54
It works fine when you retarget TPV, but fails when you also retarget TPMinV and the reason is somehow build restore isn't able to get the new changes so doesn't restore which is why build fails with previous assets file. I'll debug it and see what's the root cause.

But to workaround it, you can run a solution restore explicitly and then do the build. it will work fine.

**Comment by jainaashish** [comment] 2017-03-16 22:28
Merged to Dev, waiting for the approval for 4.1

**Comment by jainaashish** [comment] 2017-03-17 23:28
Merged to 4.1.0# 784900b4a024e40a00796b8f3179083be35a65dc

**Closed as completed by jainaashish** 2017-03-17 23:28 UTC
Labels: Product:VS.Client, Type:Bug, Style:PackageReference
