### ISSUE TITLE
Save solution after package upgrade

### ISSUE THREAD

**Issue by CraigSelbert** [NuGet/Home#2052] opened 2016-02-04 16:28 UTC
After upgrading various packages it would be of great if the solution could be saved. Multiple times I have upgraded packages, committed them to source control only to find out that I did not save the solution not persisting the changes to the solution.

**Comment by emgarten** [comment] 2016-02-04 20:46
This is a general Visual Studio problem. NuGet does not force Visual Studio to write all changes to disk after every operation for performance reasons.

**Comment by CraigSelbert** [comment] 2016-02-04 21:02
Makes sense, I just thought I would see what you guys would say. Thanks for a quick response.

**Comment by yishaigalatzer** [comment] 2016-02-08 00:00
We could consider this as an option. I to have been burned by this, we could potentially do the save all only after all the operations have been completed.

**Comment by CraigSelbert** [comment] 2016-02-08 00:20
@yishaigalatzer That would work for my scenario's, I guess it does matter if the command was executed by command line vs UI, not sure how the UI actually knows when it is completed but I do know the UI does a auto refresh when it is complete.

**Comment by yishaigalatzer** [comment] 2016-02-08 15:57
This will only be relevant for the UI. The command line only works on files on disk.

**Comment by rohit21agrawal** [comment] 2016-04-29 22:46
@yishaigalatzer @harikm86 

This sounds like dupe of https://github.com/NuGet/Home/issues/2214 . Correct me if I am wrong.

**Comment by yishaigalatzer** [comment] 2016-04-29 23:31
Yes, please close

**Comment by rohit21agrawal** [comment] 2016-04-29 23:32
https://github.com/NuGet/NuGet.Client/commit/c022ca256a74340a05e25b11f3d8b3d0e90214ca

**Closed as completed by rohit21agrawal** 2016-04-29 23:32 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:DCR
