### ISSUE TITLE
The "RestoreTask" task returned false but did not log an error

### ISSUE THREAD

**Issue by jeffschwMSFT** [NuGet/Home#13710] opened 2024-08-15 22:32 UTC
### NuGet Product Used

dotnet.exe

### Product Version

.NET 9 preview

### Worked before?

yes

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Full details in https://github.com/dotnet/dnceng/issues/3100 (including recent builds that are failing)

```
     2>/__w/1/s/.dotnet/sdk/9.0.100-preview.5.24307.3/NuGet.targets(170,5): error MSB4181: The "RestoreTask" task returned false but did not log an error. [/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24311.10/tools/Tools.proj]
##[error].dotnet/sdk/9.0.100-preview.5.24307.3/NuGet.targets(170,5): error MSB4181: (NETCORE_ENGINEERING_TELEMETRY=Restore) The "RestoreTask" task returned false but did not log an error.
     2>Done Building Project "/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24311.10/tools/Tools.proj" (Restore target(s)) -- FAILED.
     1>Done Building Project "/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/9.0.0-beta.24311.10/tools/Build.proj" (default targets) -- FAILED.
```

**Comment by zivkan** [comment] 2024-08-18 22:06
I believe this is a duplicate of:
* https://github.com/NuGet/Home/issues/13460

You appear to be using .NET 9 preview 5, which is quite old, apparently released on the 11th of June, which is the same day as [the fix got merged into Nuget.Client](https://github.com/NuGet/NuGet.Client/commit/de9c314080687bfe4da4baf4b3d1a9d38b6ace3a). Therefore, I suspect if you upgrade to a newer version of the .NET SDK, you should receive error messages when the error scenario happens.

**Comment by nkolev92** [comment] 2024-08-19 17:08
We have multiple issues tracking that bug, what @zivkan linked and then a newer bug: https://github.com/NuGet/Home/issues/13545. 

It was fixed and the linked dnceng issue was also referenced in https://github.com/NuGet/Home/issues/13545#issuecomment-2200694016. 

I'm gonna close this as a dup.

Please let us know if this persists in latest .NET 9 SDK previews.

**Closed as not planned by nkolev92** 2024-08-19 17:08 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Restore
