### ISSUE TITLE
[Cross-platform Dotnet NuGet Sign] The error info of NU3018 on MacOS “the key usage is incorrect” is not clear enough when the certificate is not valid for code signing

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12510] opened 2023-03-29 08:30 UTC
### NuGet Product Used

dotnet.exe

### Product Version

 .NET SDK 7.0.202

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1. [Patched dotnet SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703).
2. On Windows: Create a new test certificate:    ` .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Type SSLServerAuthentication -Password password -GenerateCerFile`  (in the powershell "Developer Command Prompt"). 
   On macOS: Copy the .cer file(should be generated under the same path with .pfx file) and the .pfx file from the above Windows machine to macOS machine.
3. Go to the patchedSDK path and run the command as below. Where <CertificateFilePath> is the file path to the created certificate (in step1) .cer or .pem file and <VersionedSdkDirectoryPath> is the directory path for the patched versioned .NET SDK directory (e.g.:  ./patchedSDK/sdk/7.0.100), add trust for the certificate: 
On macOS:  `./dotnet run --project ./Entropy/TrustTestCert/TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath> -vsd <VersionedSdkDirectoryPath> `
4. Use the patched "dotnet.exe" to sign a package. Where <PackageFilePath> is the test package path and <PfxFilePath> is the file path to the .pfx file, sign the test package: 
On macOS:  `./dotnet nuget sign <PackageFilePath> --overwrite --certificate-path <PfxFilePath> --certificate-password password --timestamper http://timestamp.digicert.com/ -v n `
5. Verify the output of previous step.

#### Expected:
There are two errors as below.
Error: NU3018: NotValidForUsage: The certificate has invalid policy.  
Error: NU3018: Certificate chain validation failed. 

#### Actual:
The error info of NU3018 on MacOS “the key usage is incorrect” is not clear enough as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/228473504-5e2d0fb4-482d-4c4c-9a0f-228534206ae7.png)
#### Note:
1.It is not a regression.
2.It doesn’t repro on Windows/Linux.

**Comment by jeffkl** [comment] 2023-04-06 18:29
Team Triage: @dtivel can you comment on if improving this message would be helpful?  Or is the message already informative enough?

**Comment by dtivel** [comment] 2023-04-10 20:23
I think it's good enough as-is.  These messages are pretty much from .NET or the OS.

https://learn.microsoft.com/en-us/nuget/reference/signed-packages-reference#certificate-requirements

**Comment by jeffkl** [comment] 2023-04-10 20:37
Closing as by design

**Closed as not planned by jeffkl** 2023-04-10 20:37 UTC
Labels: Type:Bug, Resolution:External, Functionality:Signing, Found:ManualTests

**Comment by v-luzh** [comment] 2023-04-20 11:16
Hi @jeffkl, as Damon said above, the messages are from .NET or the OS. So we think the resolution is better to be External. Please ping me if you have different idea. Thanks very much.
