### ISSUE TITLE
After packages are automatically restored, we should refresh the UI or PMC to remove the yellow bar with Restore button

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#683] opened 2015-05-28 23:48 UTC
Repro steps: 

1) create a new class library, install some packages 
2) delete some packages folder 
3) start package manager console or UI, install some other packages not installed in step 1 

Expected: automatic restore will happen before installing package on step 3. After that, the yellow bar saying some NuGet packages are missing should be gone, as at this point all packages are restored.  

Actual: yellow bar still present. We did not refresh the UI/PMC.

**Comment by AndriySvyryd** [comment] 2015-06-15 22:42
Looks like a dupe of #699

**Comment by rrelyea** [comment] 2016-03-29 23:40
confirm this is gone.

**Closed** 2018-02-02 00:31 UTC
Labels: Priority:2, Type:Bug
