### ISSUE TITLE
Provide a way to disable "nearest wins" resolution in package restore

### ISSUE THREAD

**Issue by madelson** [NuGet/Home#8020] opened 2019-04-19 14:15 UTC
Our projects have complex dependency graphs and as such we frequently encounter NU1605. 

What is frustrating to me is that in most cases there is an obvious resolution to this which is to use the minimum version that is fully compliant. Rather than seeing NU1605, I would like the ability to turn off the "nearest wins" resolution rule. It seems odd to me that NuGet would ever resolve dependencies in a way that simply violates version constraints, so ideally this rule would simply be removed/changed.

## Existing behavior:
```
PackageA 3.5.0 -> PackageB [3.5.0, 4)
PackageC 4.0.0 -> PackageD [4.0.0, 5) -> PackageB [3.6, 4)
=> chooses PackageB 3.5
```

## Desired behavior:
Chooses PackageB 3.6

**Comment by nkolev92** [comment] 2019-04-19 20:38
Duplicate of https://github.com/NuGet/Home/issues/8020. 

There's lots of reasons why NearestWins was implemented: 

* You get a predictable resolution behavior, minimizing the noise you get from using multiple/different sources. 
* Allows the most control to the end user. Just because a package says `3.5.0 and greater` of a dependency it doesn't mean that every potential matrix has been tested. Bugs happen and break the experience (note I'm talking about runtime changes). 
Having a selection algorithm like this puts the onus to the user as we believe that users should truly understand the dependencies they are bringing into their product. 
* Performance - Restore runs everywhere, before every build. Trying to create the perfect graph is a costly operation that other package manager might be willing to pay because they don't have the complexities of the .NET Framework.

**Closed as completed by nkolev92** 2019-04-19 20:38 UTC
Labels: Resolution:Duplicate, Type:DCR, Functionality:Restore

**Comment by madelson** [comment] 2019-04-21 02:48
@nkolev92 thanks for the information. You mention that this is a duplicate of another issue but you just link back to this issue. Can you link to the other so I can read more?

Regarding the performance point, I agree that package restore should be very fast. However, isn't this largely solved by using restore with locked mode?

**Comment by nkolev92** [comment] 2019-04-22 01:26
@madelson 
My bad, I pasted the completely wrong thing. 

https://github.com/NuGet/Home/issues/5400

Not everyone uses locked mode. It will be a while until people do if ever. 
Then again, we listen to the customers & platform needs, and prioritize things accordingly.
