### ISSUE TITLE
With proj A depending on proj B - want to pack A with a.dll and b.dll

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#3893] opened 2016-11-08 04:21 UTC
## Details about Problem

NuGet Pack Task

NuGet version 4.0

VS version (if appropriate): VS 15

## Detailed repro steps so we can see the same problem

1. Create a .Net Class Library (A)

2. Add another .Net Core Class Library (B)

3. Reference B from A

4. Set type in ProjectReference to Project

5. Pack A

Expected
Binaries from B are copied to lib/tfm

Actual
Still treats it as a PackageReference

...

**Comment by rrelyea** [comment] 2016-12-08 20:15
We don't plan to enable this in dotnet pack / msbuild /t:pack in 4.0 timeframe.
We'll listen to customer feedback and consider in the future.

**Comment by rohit21agrawal** [comment] 2016-12-09 00:31
Closing as duplicate of : https://github.com/NuGet/Home/issues/3891

**Closed as completed by rohit21agrawal** 2016-12-09 00:31 UTC
Labels: Resolution:Duplicate, Functionality:Pack

**Comment by kkm000** [comment] 2020-01-31 13:21
@rrelyea, "Focusing on NuGet client software to enable great work by the NuGet community!", wrote not even 3 years past:

> We'll listen to customer feedback and consider in the future.

If you want to hear the customer feedback, please go no further than #3891. 3.5 years worth of customer feedback is quite a collection. I must give you a fair warning, though, that the feedback is not exactly positive. I would call it rather agitated.

The biggest problem with the future is that it inevitably comes, but nobody knows exactly when this capricious creature will arrive. "we'll consider it in the future," let me express myself in a straightforward manner, is not a very informative answer. After 3 and a half years it would certainly be quite educating to understand how far, by the planning methodology that the team adopted, "the future" is from now. The only certain things I know about the future is that we will all die and that we'll pay taxes one way or another. Any other concept of "the future" is implicitly operational, and therefore requires a clarification, in my opinion. A rough numeric estimate expressed in time units would be immensely helpful. Thanks!
