### ISSUE TITLE
nuget pack + $description$: `AssemblyDescription` cannot have a less-than sign

### ISSUE THREAD

**Issue by qwertie** [NuGet/Home#3049] opened 2016-06-25 04:35 UTC
My `AssemblyDescription` refers to a data type `DList<T>` that my assembly contains. This doesn't work and produces a somewhat confusing error message.

```
>nuget spec
>nuget pack Loyc.Essentials.csproj -Build -Properties Configuration=Release.NET4
...
...
...
The 'T' start tag on line 13 position 431 does not match the end tag of 'description'. Line 13, position 575.
```

**Comment by rrelyea** [comment] 2016-06-27 21:04
Dupe of #2651, which is fixed in 3.5.0-beta and -beta2.

**Closed as completed by rrelyea** 2016-06-27 21:04 UTC
Labels: Resolution:Duplicate, Functionality:Pack
