### ISSUE TITLE
How to give Floating version in nuget package to get latest dependency.

### ISSUE THREAD

**Issue by KrupaMoliya** [NuGet/Home#4937] opened 2017-03-30 13:10 UTC
I refered Dependency resolution in NuGet 3.x at below url
https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#dependency-resolution-in-nuget-3x

There are 4 rules
1) Lowest applicable version
2) Floating versions
3) Nearest wins
4) Cousin dependencies

1st, 3d and 4th we can define in package while 2nd we can set in package.json

How can i set floting version on nuget package?

## Details about Problem

NuGet product used (NuGet.exe):

NuGet version (4.0.0.2275):

I have total 3 project say ProjectA, ProjectB, ProjectC
ProjectB referes ProjectA, Project.json is like "dependencies": {"ProjectA": "1.0.0.*"}
ProjectC referes ProjectB, Project.json is like "dependencies": {"ProjectB": "1.0.0.*"}

Available packages on nuget feed
ProjectA.1.0.0.1
ProjectA.1.0.0.2
ProjectB.1.0.0.1
ProjectB.1.0.0.2

Now if i compile ProjectB 
it will take latest ProjectA in bin folder. i.e. **ProjectA.1.0.0.2 [Floating Versions Rule]**
**it creates nuget package of ProjectB with dependency ProjectA >= 1.0.0**
My requirement is to create package like ProjectA = 1.0.0.* to take latest available dependency.

Now if i compile ProjectC 
it will take latest ProjectB in bin folder. **i.e. ProjectB.1.0.0.2 [Floating Versions Rule]**
it will take lowest ProjectA in bin folder. **i.e. ProjectA.1.0.0.1 [Lowest applicable version]**
it creates nuget package of ProjectC with dependency ProjectB >= 1.0.0

I tried with below option and it also didn't worked for me
 "dependencies": {"ProjectA": "[,2.0)"}
 "dependencies": {"ProjectA": "(,2.0]"}
 "dependencies": {"ProjectA": "(,2.0)"}
 
 
**To solve this issue manually i need to specify all dependency in project.json with floating version like nuget 2x.**
 "dependencies": {"ProjectB": "1.0.0.*",
				  "ProjectA": "1.0.0.*"
				  and so on....
				  }

**Comment by jainaashish** [comment] 2017-03-31 17:15
@KrupaMoliya currently there is no other solution then to manually specifying all the dependencies in project.json like you did. But we have this workitem in our backlog to work upon and we'll soon be working on it.

**Comment by KrupaMoliya** [comment] 2017-04-03 09:59
Thank you very much for you reply.

I would like to know that is there any plan or any tentative date when i will get latest available dependency.

Main issue in mentioning manual is that it is too hard to gather all transitive dependency list and put it in project.json If i have reference like
Myapplication >> MyModules >> MyCommon >> MyCore >> MyAPIs 
--------------------------------------  MyCommon >> MyUtilities >> MyBase
and in Myapplication I am taking reference of MyModules then i have to add all packages in project.json (MyModules, MyCommon, MyCore, MyAPIs, MyUtilities, MyBase) 

In Nuget 2.x at time on installing package, it was adding all nth level dependencies in package.config.
but in nuget 3.x or in 4.0 it is adding only one reference in project.json and it takes lowest available package of dependency from nuget server feed.

In this situation i only can think of below options.
1) Delete all the package when my CI server puts new package on nuget feed, means keep only latest package on server. but it is not a good option because we will loss old packages and there is on delete option available with only package name (delete command requires package version as a mendatory field).
2) Manually add all nth level transitive dependency in project.json. but it is too hard to find it manually and i didn't found any automatic way to install package with all dependency in project.json

Please suggest me if any better solution is available.

**Comment by emgarten** [comment] 2017-10-17 19:12
This work will be part of adding a lock file.
https://github.com/NuGet/Home/issues/4394

**Closed as completed by emgarten** 2017-10-17 19:12 UTC
Labels: Resolution:Duplicate

**Comment by emgarten** [comment] 2017-10-18 02:37
Duplicate of https://github.com/NuGet/Home/issues/5553

**Comment by wweeder** [comment] 2018-03-20 19:38
Any progress on this? package management is about automation... needing to manually write versions for every single dependency is a bit ridiculous.
