### ISSUE TITLE
Nuget source add/update will break current persisted passwords

### ISSUE THREAD

**Issue by Tasteful** [NuGet/Home#2701] opened 2016-05-02 16:37 UTC
Using NuGet Version: 3.4.3.855 (command line client)

If you add an password protected package source

```
nuget source add -source http://test/nuget -name Test -username "test" -password "test123"
```

you will add a new source into the nuget.config file with a persisted password that will work for the feed, nuget.config is updated with the packageSourceCredentials.

```
  <packageSourceCredentials>
    <Test>
      <add key="Username" value="test" />
      <add key="Password" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAifVHcKboxkGu2SXEZztBvgAAAAACAAAAAAAQZgAAAAEAACAAAAAh9OB5VtxBmMiuh2I2s+mrWt+zDHe5HedcKg0264VB8gAAAAAOgAAAAAIAACAAAACBzYsmXi5oNI1cr/YweDTtR2HeaKtCPwrfoAyP0vxOUxAAAAB6pHJky/5TTOWNxn0fz7kuQAAAAMJ0ECmy0dd6x11wJCkQ8pDh0icrXNznDJmS+80fcn/TAdHUw0721vgfEySQzMcvsYJlqpqEkMPd28VOTG1OUJY=" />
    </Test>
  </packageSourceCredentials>
```

Adding another password protected package source

```
nuget source add -source http://test2/nuget -name Test2 -username "test" -password "test123"
```

Nuget.config now is updated to, as you can see the password for source "Test" is also updated if you compare the strings.

```
  <packageSourceCredentials>
    <Test>
      <add key="Username" value="test" />
      <add key="Password" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAifVHcKboxkGu2SXEZztBvgAAAAACAAAAAAAQZgAAAAEAACAAAAA6u/ddIMVwagt0Nd017yQnRX79O0XObVWXmynMAjSPTQAAAAAOgAAAAAIAACAAAACMNojIh5RuAPPRZcA2VGas299KxAoPJvMajj0xDxHVA0ABAACexj0pYuqMn3o6F459dzTRsg4PIsXKvCrdQF2zGxLm/prDH8r8owGZC59nItal/5Xf9cDZAKdZTUPLbWaLMw2yo3Vv+f1fyfaT9BAJMmwLxrW9YzUrN6ykRRJa/KauGekO7FNj7EBs99g8Fna0duADAawXsxFUE5mJjc4rqqVejGLY0d6WMUkqtUtSGqTVJjS0yBwJ61YR2H8QYxiNsq/qJM6b4DEceZL8J15XoW/xRaiTw0viSmZIJzHHF6Ga1ajbzDSNL0OYsqJwZNJEO3UZQoEJ4G/JWvAOlqxBCPE7qSmOUFoiEN+B5ICaObIh8Ib2V9tWIHDPXBOqEvDvyVQszF2ZA+/FOVyX195lfcFt9cCjM7XSExH4Yct85dN0wBlKp91bo4dW0qwsIwvPbN75lI/Xgbfl7R8VCNjmBmLuZkAAAABTvaZyLGljEIaM+Xeprjt1ClPHxWhXFG1TOzqZ5sOI5NooHmSxchBGP6oExBR1Fa/gz2epCeygdaVSPrAgKT7y" />
    </Test>
    <Test2>
      <add key="Username" value="test" />
      <add key="Password" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAifVHcKboxkGu2SXEZztBvgAAAAACAAAAAAAQZgAAAAEAACAAAABbSEpO7ma+iUaXYTdtb/ULnVVV8Pn6NEgGIPbiq2S1lgAAAAAOgAAAAAIAACAAAAB1Gvhzx79f7Qlx/HK9W4cxJ6nhG7n2LRmtbdWOxmIYkBAAAADr6+5GJ7H8OxRbMO7IKB0nQAAAALabuhC126SHa4U2gL35mak6yAuZPupDOST2tELL41hrFOV5edMahbsAJuaad81Xpk/q18U6kUVazphB1SuPOXg=" />
    </Test2>
  </packageSourceCredentials>
```

Adding a third nuget source, and the password is updated for Test and Test2 feeds.

```
nuget source add -source http://test3/nuget -name Test3 -username "test" -password "test123"
```

And nuget.config is updated to

```
  <packageSourceCredentials>
    <Test>
      <add key="Username" value="test" />
      <add key="Password" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAifVHcKboxkGu2SXEZztBvgAAAAACAAAAAAAQZgAAAAEAACAAAADMQlhQSKjDiaYPkF7rYXm4Lt3mkLgXc8LyPb/gFd+zCwAAAAAOgAAAAAIAACAAAABtGpHM5+l+iXa8LMlFaABuYChlF/4GcHfOQVvhLDE1kNACAAAWU+M0gdDbHeFFAi41BdNToU4kdSdyQcgFCGzNBZxeJd7AT1ZyulqpYm894H2/+N1NlKy6SkzQGw4JGohTL8dcFcp0ML4qVr9aKlBnSgTIIM27aV5h9cQ7u764xQEtYAKgMON9I4w/FV8EmqgeSF2CCfigMUwGYokbWt/yGk5IZhrZK4JpKe8YZISzPC4J5yEwoaYV1FUiMny9cRxwMXlrQKjTE08RZJE/htRDilRf0Vqz+a+hFDpWE524Lb3c+9w2uyizqquLSfz6lR/4pgTLlQ18VzRIOp+xR93lTJylU59+Szbp+HvEe7Q75Wdo0JpLoYdDYseZNPtfs7jb1RWqSik+YBuUQc2LipjhKAAyuLVORog43+ofHe2fAAybrYsF+OkRfLqtNOteDY8pUQZfCK0PzHmalZ9/WisGHC1Ivu7beLM2KQSSgiKsBlNHj57fSGIJ0Vq76li6Z/aFHutVm7nBwf+ZTp26PFHYNlaY+qVuhoZzCnzN8x7gcGBmkRDV7ITSGdRPJOlXY3dz5jBSjUuDlWRoHQ1pORGiDWV1BM/8Ed1DpAqdPunWi2dQIReN8ULA6NRDuhG6dMANhO2KAsDbE46ZAp13G3ZY5Nie1YZNj4s/HfKO98q6UyfeTlYPRCUchLyW9LFoDTuGgOtKwYBbb4Dt3KjGEET6FML+HTkpEWkz714ecuYxe01TnF0nz86KAZ3K4HfpIIalQdBsxjrOS57BK775hZyuXeH9XPQ3hyA0NDTOGglrY0QpzfB2hQxZUwjnYD04DGnVrVdxq0sbEkVv7u4gfy0cgDFgiwNVNDRjbfs24qFcyAzO5Etyw1b2dZzxSf353uXHvrKUdBBPemLf+4aLw59juOS59YYhHfNzaF9aEmkVpM0NOy1GcY3xBhqbXsiuIRsc4dPPaN9ge+v7c0CYgDujpVt+SpdBNX8Gi4GDpMCCintRgqtAAAAAbEixkJcPPNpS5tmk7CbZOgbehzNYTQnA52N2qSd1PS8sR+0Gh7tZhAGWyoFC9FjnGj94o17A8gJRbQUl4G671w==" />
    </Test>
    <Test2>
      <add key="Username" value="test" />
      <add key="Password" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAifVHcKboxkGu2SXEZztBvgAAAAACAAAAAAAQZgAAAAEAACAAAAAJoqBc3xcsnWw0OIVq9puBvxOekED4eouBnCNhtt/kdwAAAAAOgAAAAAIAACAAAAC/ckZ7OXuAqmHSrsrNkBlyQR5fpmH/kW6yV/VuGIwebkABAAAKKYOKVfKYieyJV3BJ0Y7PuQhBi/bM0dEb6zrYDzyUMJCOcU5M1KdJpLv5Ewyt6OaMbpn7v+iI1jKk1kIH3bmSAYAukf2tDGfp0WB+cRD5DgD0CBxpNERLxWhklR/JZliarbYWOIGa/hGNqQciuo/kEcrUwifz+Oi0+TW6AtwdsOqbTSVo41qBmsCUoKjFI5i5sCqjFwQ4rh1AhwAvCFuL78uWxLtMeH8fwRRJMk5NEuubDjmehyb0gIbuvKuKEfyDwoA5sZw6pu+5Do9yxoCZLzeQ2eEoC/6P4ea/LmV/u9LPJyzgo8/O7AbQrvocrQcz0tz+tGsfSKYKAlRCzKvCoRUOMJ6rNiZKRTsIWTxoLFzLG3i5Eo7CJa7xYCgTMUU42/2OgrLXmragWX4FLXmA604/jg0Za8sO/ICMmDX0c0AAAACz9ffmm854Ud4OzjfdZ2OjM554hN0pGbp3BadkACHRtDnLBSnjz3V6/Z4KFIhUjiROC3ExjFadiTZbe6qfw+N+" />
    </Test2>
    <Test3>
      <add key="Username" value="test" />
      <add key="Password" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAifVHcKboxkGu2SXEZztBvgAAAAACAAAAAAAQZgAAAAEAACAAAADrYy8o4ssGpPIMN58GsrYCaGM8YNGBTVHXIlfC7lTsZgAAAAAOgAAAAAIAACAAAADNq3Gx9AlkwUkB/Js5XW/2rpQRxfnvM51ytJmstjG84RAAAAD6xcZCdB5SynN4Kx5lw2xfQAAAAKt2jr/WrBB2/jE93zeaPpP8NWCewTiHVjdZbvf9kqp1bgj///+yVX9cUmksnYg/BcE9ELdwTE55iPgE+/wlJUQ=" />
    </Test3>
  </packageSourceCredentials>
```

**Comment by rrelyea** [comment] 2016-05-02 16:39
This is likely a dupe of #2647 - which has a link to a private build with a fix. Please reopen this issue, if your issue appears to be a unique one.

**Closed as completed by rrelyea** 2016-05-02 16:39 UTC

**Comment by Tasteful** [comment] 2016-05-02 16:49
@rrelyea Can confir that the internal build in linked issue also solves my problem. Thanks!

**Comment by rrelyea** [comment] 2016-05-02 16:53
great. thanks for confirmation.
