### ISSUE TITLE
nuget restore warning with large number of projects with large paths

### ISSUE THREAD

**Issue by rmustard** [NuGet/Home#5363] opened 2017-06-07 23:13 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe

NuGet version (x.x.x.xxx):
4.1.0.2450

dotnet.exe --version (if appropriate):
n/a

VS version (if appropriate):
Visual Studio 2015 (VS14)

OS version (i.e. win10 v1607 (14393.321)):
win10 v1607 (14393.1198)

Worked before? If so, with which NuGet version:
3.5

## Detailed repro steps so we can see the same problem

1. Our solution has a lot of projects ~400.  When the root project directory gets long enough  all of the full paths of the projects together add up to over 32767 characters.

2. So, when I invoke "nuget restore Solution.sln" the call to GenerateRestoreGraph fails with an exception

...

### Verbose Logs
VERBOSE: nuget.exe: System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
VERBOSE: nuget.exe:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
VERBOSE: nuget.exe:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
VERBOSE: nuget.exe:    at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__5.MoveNext()
VERBOSE: nuget.exe: --- End of stack trace from previous location where exception was thrown ---
VERBOSE: nuget.exe:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
VERBOSE: nuget.exe:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
VERBOSE: nuget.exe:    at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__43.MoveNext()
VERBOSE: nuget.exe: --- End of stack trace from previous location where exception was thrown ---
VERBOSE: nuget.exe:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
VERBOSE: nuget.exe:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
VERBOSE: nuget.exe:    at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__38.MoveNext()
WARNING: nuget.exe: WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and
UAP projects will be skipped, only packages.config files will be restored.

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

**Comment by emgarten** [comment] 2017-06-08 00:19
NuGet.exe passes all project paths on the command line to msbuild.exe, it looks like your solution is exceeding the windows limit for this.

The fix would be to write out a targets file containing all the information and then call msbuild.exe on just the targets files which would do the rest.

The work around for this is to use `msbuild.exe /t:restore` on the solution instead of nuget.exe

**Comment by emgarten** [comment] 2017-06-08 03:14
Dupe of https://github.com/NuGet/Home/issues/4931

**Closed as completed by emgarten** 2017-06-08 03:14 UTC
Labels: Resolution:Duplicate

**Comment by rmustard** [comment] 2017-06-08 13:09
thanks for the info.
looks like msbuild.exe /t:restore requires MSBuild 15.1
https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets

**Comment by alejandro5042** [comment] 2017-06-08 21:24
Is there any workaround for msbuild 14.0?

**Comment by emgarten** [comment] 2017-06-08 21:27
What type of projects do you have? Packages.config, project.json, packagereference?

**Comment by alejandro5042** [comment] 2017-06-08 21:28
Packages.config and Packages.ProjectName.config.

**Comment by emgarten** [comment] 2017-06-08 21:30
@alejandro5042 using NuGet 3.5.0 may be your best option until this is fixed.

http://dist.nuget.org/
