### ISSUE TITLE
Invalid "Unable to find a version that is compatible" error

### ISSUE THREAD

**Issue by technicallyerik** [NuGet/Home#2325] opened 2016-03-15 20:51 UTC
I am attempting to install the "UmbracoCms.6.2.5" package into a new project in Visual Studio 2015 with NuGet 3.3.0.167, and get this error:

> Attempting to resolve dependencies for package 'UmbracoCms.6.2.5' with DependencyBehavior 'Lowest'
> Unable to find a version of 'Lucene.Net' that is compatible with 'Examine 0.1.67 constraint: Lucene.Net (≥ 2.9.4.1)', 'UmbracoCms.Core 6.2.5 constraint: Lucene.Net (≥ 2.9.4.1 && < 3.0.0)'

Shouldn't this package meet both of the dependency requirements?  https://www.nuget.org/packages/Lucene.Net/2.9.4.1

What am I missing here?

**Comment by technicallyerik** [comment] 2016-03-15 21:19
After manually looking through the dependency tree myself, it turns out the error was completely wrong in describing the issue.

What it should have said was:

> Currently installed Mvc 5.2.3 incompatible with Umbraco.Core constraint of Microsoft.AspNet.Mvc (>= 4.0.30506 && < 5.0.0)

**Comment by yishaigalatzer** [comment] 2016-03-15 21:49
Thanks @technicallyerik - can you share your repro project and we will make the error better?

**Comment by technicallyerik** [comment] 2016-03-15 22:02
Unfortunately this is a private repository, but the steps to reproduce are fairly easy.  This was a new project.
1. File -> New Project
2. Select "ASP.NET Web Application"
3. Check the box to include MVC dependencies (which will bring in MVC 5)
4. `Install-Package UmbracoCms -Version 6.2.5`

**Comment by emgarten** [comment] 2016-03-16 04:53
This is a dupe of https://github.com/NuGet/Home/issues/1373

The resolve error messages are sometimes incorrect when the project starts out in a broken state, it sounds like this is what you hit.

**Closed as completed** 2016-03-16 04:54 UTC
Labels: Resolution:Duplicate, Area:ErrorHandling, Functionality:Update
