### ISSUE TITLE
Update-package error for Asp.net5 project

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#840] opened 2015-06-23 23:59 UTC
Repro steps:
1. create asp.net5 console application
2. start PMC, type update-package

Expected: no update available

Actual:
PM> update-package
update-package : The given key was not present in the dictionary.
At line:1 char:1
+ update-package
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

**Comment by emgarten** [comment] 2015-06-25 02:38
Dupe of https://github.com/NuGet/Home/issues/804

**Comment by emgarten** [comment] 2015-07-02 03:17
NuGet/NuGet.PackageManagement@8ab90543e1b407206c4c56fb03f5a4e7f66f09ec

**Closed by emgarten** 2015-07-02 03:17 UTC
