### ISSUE TITLE
Failed to patch the .NET SDK with NuGet Dev latest build

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13382] opened 2024-04-08 07:35 UTC
### NuGet Product Used

NuGet SDK

### Product Version

Dev\6.11.0.9

### Worked before?

It is a regression since the issue doesn’t repro on patching Dotnet SDK with NuGet Client Dev\6.11.0.6.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1. Open a "Developer Command Prompt" and run Git clone https://github.com/NuGet/Entropy.git to get the latest “Entropy”.
2. Open a Powershell from Task Manager with the “powershell -ExecutionPolicy Bypass” set & “Create this task with administrative privileges” checked.
3. Download the “nupkgs – NonRTM” folder from NuGet Client Dev latest build’s Artifacts to the desktop of your test machine and named "nupkgs".
4. Go to the SDKPatchTool folder: "…\Entropy\SDKPatchTool" in the PS prompt in step2 and run the “SDKPatch.ps1” script with the commands:
    ` .\SDKPatch.ps1 -SDKPath C:\Users\v-luzh.FAREAST\Desktop\PatchedSDK -NupkgsPath C:\Users\v-luzh.FAREAST\Desktop\nupkgs -SDKChannel 8.0.3xx -Quality daily`
#### Expected Result: 
The patching is successful.
#### Actual Result:
The patching failed as the screenshot below.
![image](https://github.com/NuGet/Home/assets/20632625/bda2be69-0c71-4d35-8c1d-b0f5b750999e)
#### Notes:
1.The repro rate is 100%.
2.It also reproes with “-SDKChannel 9.0.1xx” in the step4.
3.It doesn’t repro on patching Dotnet SDK 8.0.300-preview.24179.1 patched with NuGet Client Dev\6.11.0.3.
4.After verifying the NuGet build one by one, the issue starts to repro from NuGet Client Dev\6.11.0.8, doesn't repro on NuGet Client Dev\6.11.0.6.

**Comment by nkolev92** [comment] 2024-04-08 17:25
I'll look into fixing the script. 
The root cause is https://github.com/NuGet/NuGet.Client/commit/1501b1a46dc2528912b8a8280a2b2696d7f29fe9.

**Comment by nkolev92** [comment] 2024-04-16 20:05
Should be fixed now.

**Closed as completed by nkolev92** 2024-04-16 20:05 UTC
Labels: Priority:2, Type:Test, Found:ManualTests
