### ISSUE TITLE
[V3] NRE thrown from package manager UI

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#650] opened 2015-05-27 20:23 UTC
1. Create a new .NET 4.5 project
2. Manage NuGet Packages...
3. Search for Moq
3. Install Moq
4. Set filter to Installed
5. Click on Uninstall

NullReferenceException thrown from NuGet.PackageManagement.UI.NuGetUI.FileConflictAction, model is null

**Comment by zhili1208** [comment] 2015-05-27 21:37
can't repro on my machine

**Comment by AndriySvyryd** [comment] 2015-05-27 23:08
For me it reproes on 22823.1 D14REL, but doesn't on 22923.0 VSCLIENT_1

**Comment by AndriySvyryd** [comment] 2015-06-05 00:40
This is probably a dupe of #701

**Comment by zhili1208** [comment] 2015-06-05 17:36
Yes, it's a dupe of #701, close it as a dupe

**Closed by zhili1208** 2015-06-05 17:36 UTC
Labels: ClosedAs:Duplicate
