### ISSUE TITLE
Visual Studio 2015 RC NullReferenceException

### ISSUE THREAD

**Issue by theit8514** [NuGet/Home#775] opened 2015-06-12 16:01 UTC
I am experiencing a NullReferenceException when installing the package Microsoft.Owin.Diagnostics 3.0.1 to one specific project. The problem appears to be an issue with ExecuteNuGetProjectActionsAsync. I have confirmed that I have disabled the v3 API (this is not a vnext project AFAIK) and am using the v2 nuget.org package source. NuGet Package Manger version is 3.0.60602.486.

Log & StackTrace:
```
Attempting to gather dependencies information for package 'Microsoft.Owin.Diagnostics.3.0.1' with respect to project 'MyProjectIdentityServer', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Microsoft.Owin.Diagnostics.3.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.Owin.Diagnostics.3.0.1'
Resolved actions to install package 'Microsoft.Owin.Diagnostics.3.0.1'
For adding package 'Microsoft.Owin.Diagnostics 3.0.1' to project 'MyProjectIdentityServer' that targets 'net451'.
For adding package 'Microsoft.Owin.Diagnostics 3.0.1' to project 'MyProjectIdentityServer' that targets 'net451'.
Package 'Microsoft.Owin.Diagnostics 3.0.1' already exists in folder 'C:\Users\Jack\Source\Repos\MyProject\MyProjectV6\Main\MyProject6\packages'
Added reference 'Microsoft.Owin.Diagnostics' to project 'MyProjectIdentityServer'.
Added package 'Microsoft.Owin.Diagnostics 3.0.1' to 'packages.config'
Successfully installed 'Microsoft.Owin.Diagnostics 3.0.1' to MyProjectIdentityServer.
Added file 'web.config'.
Install failed. Rolling back...
Removed package 'Microsoft.Owin.Diagnostics 3.0.1' from 'packages.config'
Removed reference 'Microsoft.Owin.Diagnostics.dll' from project 'MyProjectIdentityServer'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========
```

**Comment by yishaigalatzer** [comment] 2015-06-12 22:03
Do you have a consistent repro? Can you share your project and `packages.config`? What is the project type?

**Comment by feiling** [comment] 2015-06-12 23:18
I tried several scenarios but couldn't repro the problem. @theit8514, could you share your `packages.config` and the project type? Without that information, it's impossible for us to investigate the issue.

**Comment by theit8514** [comment] 2015-06-13 00:50
The project is a web application (MVC/Owin/IdentityServer3). Package.config is below. I attempted to reproduced the problem in a new project, but even copying the list of packages has not reproduced the problem. I will attempt to take this project and anonymize it.

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.5.0.2" targetFramework="net451" userInstalled="true" />
  <package id="log4net" version="2.0.3" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2.205111437" targetFramework="net451" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.Owin.Security.Jwt" version="3.0.1" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.Owin.Security.OAuth" version="3.0.1" targetFramework="net451" userInstalled="true" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net451" userInstalled="true" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net451" userInstalled="true" />
  <package id="Owin" version="1.0" targetFramework="net451" userInstalled="true" />
  <package id="RazorMachine" version="2.6.1" targetFramework="net451" userInstalled="true" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.2.205111437" targetFramework="net451" />
  <package id="Thinktecture.IdentityModel.Core" version="1.4.0" targetFramework="net451" userInstalled="true" />
  <package id="Thinktecture.IdentityServer3" version="1.6.1" targetFramework="net451" />
  <package id="Thinktecture.IdentityServer3.AccessTokenValidation" version="1.2.2" targetFramework="net451" userInstalled="true" />
  <package id="WebGrease" version="1.6.0" targetFramework="net451" userInstalled="true" />
</packages>
```

**Comment by theit8514** [comment] 2015-06-13 03:05
I have trimmed my project down to barebones. It is available [here](https://www.dropbox.com/s/d1lmppqrv4ewu73/MyProject6.7z?dl=0).

**Comment by yishaigalatzer** [comment] 2015-06-13 04:11
@theit8514 thank you, this should help. Another thing that might help is to get a dump, by attaching visual studio and turning on break on exception for the nullref.

Either way this issue you filed exposed two other bugs which we already fixed, so thanks a ton for this report!

**Comment by theit8514** [comment] 2015-06-15 16:16
I'm not sure if  you need a dump with heap or without. I have uploaded the dump without heap to my dropbox [here](https://www.dropbox.com/s/mvnt7xxho6laqws/devenv2.7z?dl=0). If you need the heaped dump, please contact me at jack at brajah dot com and I'll set up a private link.

**Comment by feiling** [comment] 2015-06-16 00:05
@theit8514 Thanks, we found the cause of the problem. The problem is that the `app.config` file contains wrong dependentAssembly declaration, e.g:
```
<dependentAssembly>
    <assemblyIdentity type="WebGrease" publicKeyToken="31bf3856ad364e35" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-1.6.5135.21930" newVersion="1.6.5135.21930" />
</dependentAssembly>
```
The `type` property of `assemblyIdentity` should be `name`. See https://msdn.microsoft.com/en-us/library/b0yt6ck0(v=vs.110).aspx. Since the required property `name` is missing, this causes the null reference exception.

If you replace all such `type` to `name` in that file, then there will be no problem. Just wondering, how was this `app.config` created and edited to get to this wrong state?

**Comment by theit8514** [comment] 2015-06-16 00:50
I tracked my repository back to a changeset which is completely unrelated to any changes in NuGet or package selection. The problem was not with my project config file, but with the Tests config file, which I did not check. After reverting the change on that file, the problem has been resolved. Thanks, and sorry for any inconvenience.

**Comment by yishaigalatzer** [comment] 2015-06-16 01:49
Thanks for reporting this, it is still a very valid bug and our error handling to say the least wasn't satisfactory.

Given that the fix we intend to do is to improve the error generated in this case, and that we have a couple of days before we finish the work for Visual Studio 2015 RTM **and** we have to localize the error message, I'm moving this to the update I milestone.

Thanks for taking the time and responding quickly, really helped us nail it down!

**Closed** 2015-10-09 16:45 UTC
Labels: Area:VS.Client, Priority:2, Type:Bug
