### ISSUE TITLE
NuGet Restore race condition

### ISSUE THREAD

**Issue by themilkyninja** [NuGet/Home#1225] opened 2015-08-20 18:09 UTC
When calling NuGet Restore <solution>, I occasionally will get a message like this:

`The process cannot access the file 'foo.nupkg' because it is being used by another process.`

Adding the -DisableParallelProcessing flag seems to fix this, but it also slows the process down significantly. Is there another option? Or could Restore be made smarter to not attempt to download the same package multiple times?

I'm using NuGet 2.8.5, if it matters.

**Comment by yishaigalatzer** [comment] 2015-08-21 22:29
Can you try the same with `nuget 3.1-beta` ? We plan to release an RC version early next week

**Comment by yishaigalatzer** [comment] 2015-08-25 17:03
@themilkyninja any updates?

**Comment by themilkyninja** [comment] 2015-08-26 03:01
I'll try it out this week and let you know. It only happens occationally so I'll have to let it go for a while and see if it pops up.

**Comment by themilkyninja** [comment] 2015-08-31 16:46
I'm not seeing the issue with the 3.1 version I downloaded. However, I wasn't able to reproduce the original error in a controlled experiment environment with 2.8.5 either, so I can't confidently say it's fixed.

**Comment by slobo80** [comment] 2015-12-29 17:28
I'm having the same issue. Disabling parallel build mitigates the issue. Any ideas?
NuGet Version: 3.3.0.212

**Comment by yishaigalatzer** [comment] 2015-12-29 17:50
Do you run multiple restores in parallel? Can you share the full log?

**Comment by slobo80** [comment] 2015-12-29 17:51
I do run multiple restores in parallel. This is internal Microsoft project and therefore prefer not to share the log publicly.

**Comment by yishaigalatzer** [comment] 2015-12-29 17:53
Also do you have a ln easily reproducible scenario?

**Comment by yishaigalatzer** [comment] 2015-12-29 17:55
Shoot me an email to ny Microsoft account

Sent from my Windows Phone

**Comment by slobo80** [comment] 2015-12-29 18:00
Sent you the log.

**Comment by yishaigalatzer** [comment] 2015-12-29 20:31
Re-Closing the log indicates a different problem, where the issue is a race between the build and restore (which cannot be a NuGet concern).

Will keep following up offline and re-open if the facts show something else

**Closed as completed by yishaigalatzer** 2015-12-29 20:31 UTC
