### ISSUE TITLE
nugget servers block few geniune Public IPs

### ISSUE THREAD

**Issue by aloysiustany** [NuGet/Home#6052] opened 2017-10-18 08:22 UTC
I am from Honeywell. We are facing issues reaching https://api.nuget.org/v3/index.json. Our IT team tells that nugget servers block few Honeywell Public IPs. Please could help in whitelisting few subnets.
Please IM/email me for subnet details.
aloysius.fernandez@honeywell.com

**Comment by emgarten** [comment] 2017-10-18 18:53
Duplicate of https://github.com/NuGet/NuGetGallery/issues/4801

@aloysiustany please do not open duplicate issues for this.

**Closed as completed by emgarten** 2017-10-18 18:53 UTC
Labels: Resolution:Duplicate
