### ISSUE TITLE
dotnet restore3 does not put tools in the project.assets.json

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#3579] opened 2016-10-04 04:53 UTC
I tried restoring a project like the one below and my project.assets.json had an empty tools section. I was expecting for the tools section to be filled with information from the DotNetCliToolsReference section.

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0</TargetFrameworks>
    <OutputPath>bin\$(Configuration)</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.Sdk">
      <Version>1.0.0-alpha-20160930-1</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolsReference Include="dotnet-portable">
      <Version>1.0.0</Version>
    </DotNetCliToolsReference>
  </ItemGroup>

  <Import Project="$(MSBuildExtensionsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by emgarten** [comment] 2016-10-04 18:52
@livarcocc this info is no longer put in the project.assets.json file, can you read the project file instead to find the tools?

**Comment by livarcocc** [comment] 2016-10-04 22:55
@emgarten The problem with that is if the user specifies a \* for the version of the tool. Reading the tools from the project file we won't know what the right version is, while using the lock file, NuGet will use the right logic to decide that.

**Comment by emgarten** [comment] 2016-10-04 23:50
Discussed this offline with @livarcocc 

From the NuGet side the goal is to decouple tools from project since the tool output currently lives in a global location, and because they are not actual assets in the same sense as the rest of the items in project.assets.json.

NuGet could make it easier to find the tool assets file that was just restored by dropping a file into the obj folder with the name of the tool package. The file out contain the version selected.

@livarcocc will work around this for now by using the previous logic of selecting the best version based on what is under .tools.

**Comment by rrelyea** [comment] 2016-10-12 17:45
by design today.
if cli needs a list of tools that were restored, we could do.

**Comment by livarcocc** [comment] 2016-10-12 17:49
I already worked around it. I was just surprised that it was there for dotnet restore but removed for dotnet restore3.

**Comment by rrelyea** [comment] 2016-10-14 16:55
closing then. if we end up needing something, let's reopen or open new issue.

**Closed as completed by rrelyea** 2016-10-14 16:55 UTC
Labels: Type:Bug, Resolution:ByDesign, Functionality:Restore
