### ISSUE TITLE
nuget.exe push .nupkg with multiple slashes in path fails

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3544] opened 2016-09-28 16:55 UTC
## Steps
1. `nuget.exe push C:\path\to\my\\package.nupkg -Source ...`
## Expected

nuget.exe should find the package even though there are duplicate slashes in the path.
## Actual

nuget.exe does not find the package.
## Example

<pre>
> nuget.exe push .\NuGet.Commands.3.5.0.nupkg -Source https://www.nuget.org/api/v2/package
Pushing NuGet.Commands.3.5.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
Please provide credentials for: https://www.nuget.org/api/v2/package
UserName: Password: ^C

> nuget.exe push .\\NuGet.Commands.3.5.0.nupkg -Source https://www.nuget.org/api/v2/package
WARNING: No API Key was provided and no API Key could be found for 'https://www.nuget.org/api/v2/package'. To save an API Key for a source use the 'setApiKey' command.
<b>File does not exist (.\\NuGet.Commands.3.5.0.nupkg).</b>
</pre>

Fails in `3.3.0`, `3.5.0-rc1` and latest `dev`.

/cc @joeloff @rrelyea

**Comment by joelverhagen** [comment] 2016-09-28 18:06
@zhili1208 brings up a good point. This perhaps should be considered a bad path, e.g.

```
C:\Users\jver\Desktop>dir C:\\Users
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by joeloff** [comment] 2016-09-28 18:14
Right, for the drive it would cause an error, but something like dir c:\foo\bar works fine

**Comment by nkolev92** [comment] 2017-10-17 18:27
Will be resolved in a different issue. 

Duplicate of https://github.com/NuGet/Home/issues/5992

**Closed as completed** 2017-10-17 18:27 UTC
Labels: Resolution:Duplicate, Functionality:Push
