### ISSUE TITLE
NuGet 3.1+ (including the just released 3.2) are not able to restore DNX solutions.

### ISSUE THREAD

**Issue by Mertsch** [NuGet/Home#1407] opened 2015-09-18 23:48 UTC
As you can see in the log. it tries to find the `project.json` **after** the `.xproject` instead of combining the folder of the project and `project.json`

```
"C:\VSO Build\nuget.exe" restore "C:\VSO Build\_work\e8bff5de\MyProject\MyProject.Server.sln"
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Could not find a part of the path 'C:\VSO Build\_work\e8bff5de\MyProject\MyProject.Service.Web\MyProject.Service.Web.xproj\project.json'.
```

This is a pretty serious issue, as it completely fails any VSO Build with Package Restore enabled on the Solution. 2.8.x just ignored the project files ...

**Comment by yishaigalatzer** [comment] 2015-09-19 00:39
This is not scheduled to be done for a few more versions out. DNX is still in pre-release mode, and you can just separate the projects for now.

I do agree we need to come up with a solution for this right away. This is a duplicate of #1227

**Closed as completed by yishaigalatzer** 2015-09-19 00:39 UTC
