### ISSUE TITLE
Missing method on restore NuGet.RuntimeModel.JsonObjectWriter.GetJObject()

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4303] opened 2017-01-17 01:34 UTC
VS: d15rel 26115.1
dotnet --version: 1.0.0-rc3-004504

Simply running "msbuild /t:restore" on a newly created project fails with a Method not found error.

```
C:\temp> md b
C:\temp> cd b
C:\temp\b> dotnet new -t:lib
Created new C# project in C:\temp\b.
C:\temp\b> msbuild /t:restore
Microsoft (R) Build Engine version 15.1.523.56541
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/16/2017 5:31:59 PM.
Project "C:\temp\b\b.csproj" on node 1 (restore target(s)).
Restore:
  Restoring packages for C:\temp\b\b.csproj...
  Committing restore...
  Generating MSBuild file C:\temp\b\obj\b.csproj.nuget.g.props.
  Generating MSBuild file C:\temp\b\obj\b.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\temp\b\obj\project.assets.json
C:\Program Files (x86)\Microsoft Visual Studio\2017\d15rel\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): error : Method not found: 'Newtonsoft.Json.Linq.JObject
NuGet.RuntimeModel.JsonObjectWriter.GetJObject()'. [C:\temp\b\b.csproj]
Done Building Project "C:\temp\b\b.csproj" (restore target(s)) -- FAILED.


Build FAILED.

"C:\temp\b\b.csproj" (restore target) (1) ->
(Restore target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\d15rel\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): error : Method not found: 'Newtonsoft.Json.Linq.JObjec
t NuGet.RuntimeModel.JsonObjectWriter.GetJObject()'. [C:\temp\b\b.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.33
```

**Comment by rrelyea** [comment] 2017-01-17 21:59
@rohit21agrawal / @jainaashish -  dupe of https://github.com/NuGet/Home/issues/4272?

**Comment by jainaashish** [comment] 2017-01-17 23:07
yeah looks like different scenario but same root cause. In this case, MSBuild process probably would have different versions for NuGet assemvblies.

**Comment by AArnott** [comment] 2017-01-18 00:51
If MSBuild is reusing the wrong versions of assemblies because they're already loaded, that sounds related to, or a dupe of, https://github.com/Microsoft/msbuild/issues/663

**Comment by rrelyea** [comment] 2017-01-19 19:37
@AArnott - looks like devenv.exe.config has a assemblybindingredirect of 0.0-8.0 --> 8.0
Problem was that a SDK assembly referenced 9.0.
They are likely addressing by doing as nuget team does and make .net framework assemblies use v6, and netstandard target 9.0.
Should devenv.exe.config be changed to be more resilient?  0-10.0 --> 8.0 ??

**Comment by AArnott** [comment] 2017-01-19 20:13
@rrelyea what does devenv.exe.config have to do with msbuild at the command line?

And I wouldn't likely support any plan to use a binding redirect that *lowers* the targeted version (makes someone who compiled against 10.0 load 8.0 at runtime).

What does it mean to have "netstandard target 9.0"? Newtonsoft.Json isn't *part* of netstandard, is it?

**Comment by jainaashish** [comment] 2017-01-24 19:12
underline external issue is fixed.

**Closed as completed by jainaashish** 2017-01-24 19:12 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Restore

**Comment by NickCraver** [comment] 2017-02-04 13:10
Is there a workaround for this at the moment?

**Comment by zmckinnon** [comment] 2017-02-04 15:30
I am having the same issue on my CI build.  Looking for a workaround as well.

**Comment by zmckinnon** [comment] 2017-02-04 15:44
I am using a VS build step.

Changing:

```
        <dependentAssembly>
          <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral"/>
          <bindingRedirect oldVersion="4.5.0.0-8.0.0.0" newVersion="8.0.0.0"/>
          <codeBase version="8.0.0.0" href="PrivateAssemblies\Newtonsoft.Json.dll"/>
        </dependentAssembly>
```

to

```
        <dependentAssembly>
          <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral"/>
          <bindingRedirect oldVersion="4.5.0.0-9.0.0.0" newVersion="9.0.0.0"/>
          <codeBase version="9.0.0.0" href="PrivateAssemblies\Newtonsoft.Json.dll"/>
        </dependentAssembly>
```

in devenv.exe.config SEEMS to have made it work.

**Comment by zmckinnon** [comment] 2017-02-04 16:42
SEEMS like it only failed the first time.  It worked after the first failure. Weird.

When I did a repository clean, it failed again (but again only once).
