### ISSUE TITLE
NuGet is creating lots of temp files in %TEMP%, which eventually fails after there is 65,536 of them

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#1608] opened 2015-10-19 20:07 UTC
We're getting failures on our build machines like so ([log](http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/1148/consoleFull#293262433a82fefab-f698-416f-8fca-58544c94cd4e)):

```
CSC : error CS7027: Error signing output with public key from file 'd:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\build\Strong Name Keys\RoslynInternalKey.Private.snk' -- The file exists. [d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\src\Tools\Source\FakeSign\FakeSign.csproj]
```

This turned out to be caused by having too many temp files in %TEMP% that Win32/.NET's GetTempFileName bails.

Looking at the majority of temp files, they appear be containing NuGet content:

``` XML
<?xml version="1.0" encoding="utf-8"?><feed xml:base="https://www.myget.org/F/dotnet-core/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><id>https://www.myget.org/F/dotnet-core/FindPackagesById</id><title type="text">FindPackagesById</title><updated>2015-10-19T17:53:56Z</updated><link rel="self" title="FindPackagesById" href="FindPackagesById" /><entry><id>https://www.myget.org/F/dotnet-core/Packages(Id='System.Reflection.Metadata',Version='1.0.22-beta-23024')</id><category term="MyGet.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" title="V2FeedPackage" href="Packages(Id='System.Reflection.Metadata',Version='1.0.22-beta-23024')" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Screenshots" type="application/atom+xml;type=feed" title="Screenshots" href="Packages(Id='System.Reflection.Metadata',Version='1.0.22-beta-23024')/Screenshots" /><title type="text">System.Reflection.Metadata</title><summary type="text">This packages provides a low-
```

It appears that NuGet (maybe restore?) isn't cleaning them. Can you delete any files after you've finished them? You can pass [FileOptions.DeleteOnClose](https://msdn.microsoft.com/en-us/library/system.io.fileoptions%28v=vs.110%29.aspx) to simply this.

**Comment by emgarten** [comment] 2015-10-19 20:27
Are you running with -NoCache?

**Comment by davkean** [comment] 2015-10-19 20:27
No.

**Comment by yishaigalatzer** [comment] 2015-10-19 23:22
Looks like a duplicate of https://github.com/NuGet/Home/issues/1608. Can you pick up the latest bits (again :) )

**Comment by yishaigalatzer** [comment] 2015-10-19 23:23
CC @xavierdecoster

**Comment by davkean** [comment] 2015-10-19 23:23
1608 is my bug - did you mean to link to it?

**Comment by yishaigalatzer** [comment] 2015-10-19 23:24
:D Sorry https://github.com/NuGet/Home/issues/802

**Comment by davkean** [comment] 2015-10-19 23:25
Thanks - will try to get the team to upgrade to latest. Just filing the NuGet issues as I find them in our infrastructure. :)

**Comment by davkean** [comment] 2015-10-19 23:36
Which build should I be upgrading to get all my fixes? Including the recent multi-proc one?

**Comment by yishaigalatzer** [comment] 2015-10-19 23:47
Assigned to myself to resolve when 2.10 makes it into the nuget.client build

**Comment by feiling** [comment] 2015-11-23 20:24
Fixed checked in.

**Closed as completed by feiling** 2015-11-23 20:24 UTC
Labels: Priority:2, Type:Bug

**Comment by mihailik** [comment] 2016-10-20 11:58
nuget `3.4.4.1321` and/or VS2015 `14.0.25424.00 Update 3` still hog gigabytes in cache directory in days.

Please note that 'purge when nothing runs' is not a fix.

Some of us use Visual Studio for day job. Unlike fancy HelloWorld demos at conferences, that means keeping several sessions open for days sometimes weeks. Also there are large CI servers where nuget may need to run so often as not to have a window of silence.

See also https://github.com/NuGet/Home/issues/802#issuecomment-255083844
