### ISSUE TITLE
Support mulitple projects in one folder in v3

### ISSUE THREAD

**Issue by nigel-sampson** [NuGet/Home#1102] opened 2015-08-03 22:57 UTC
Projects such as [Caliburn.Micro](https://github.com/Caliburn-Micro/Caliburn.Micro) that support a number of different platforms (soon to be eleven with Xamarin and Windows 10) structure the solution in a way that the code for the assemblies is located in a single folder.

An example of this is the [Caliburn.Micro.Platform](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/master/src/Caliburn.Micro.Platform) assemblies.

Dealing with project specific nuget dependencies in v2 was dealt with by prefixing `packages.config` with the project name.

This approach isn't supported in v3 and `project.json`.

From some discussions it appears the recommended approach is to restructure the solution to use a shared project and separate project heads for the platforms enabling each `project.json` to be in it's own folder.

**Comment by Nezz** [comment] 2015-08-04 12:18
We have the same issue at [MonoGame](https://github.com/mono/MonoGame). NuGet 3 doesn't even care if the `project.json` is included in the project. If it finds it in the folder then it tries to restore packages.

```
    <None Include="project.json" />
```

**Comment by tomspilman** [comment] 2015-08-04 19:12
> We have the same issue at MonoGame.

I'm one of the core maintainers of MonoGame.  We have no plans to re-arrange our project to work around this oversight in the implementation of NuGet 3.

Instead our plan is to stick to VS2013 until this issue is resolved.

**Comment by nigel-sampson** [comment] 2015-08-05 22:17
So I've done a trial run in refactoring [Caliburn.Micro](https://github.com/Caliburn-Micro/Caliburn.Micro) solution to using shared projects instead of the single folder approach.

In short it's not workable due to the all or nothing approach of shared projects which makes sharing files with a subset of projects without a massive amount of things like `#if NET && WINRT && !XAMARIN` at the top of dozens of files.

Would really love to see this solution resolved as we're going to have to with another approach to solving this.

**Comment by yishaigalatzer** [comment] 2015-08-06 01:00
nuget (particularly the nuget command line) runs outside of msbuild, and does try to understand if project.json is part of the project.

We do need to look into this, but I'm not sure I follow the problems. The suggestion is to move the csproj files to another folder and put the project.json next to it, and then have the projects link in the files. I don't see where the `#if` comes into play.


@kevinpi

**Comment by yishaigalatzer** [comment] 2015-08-06 01:05
@tomspilman I understand the frustration this caused, and we are going to see how we can come up with a solution. The sticking point is that we can't just release a new nuget extension to support it, and we need a coordinated release with @pilchie 's team. I'll work with him offline on this. It just means the fix is less immediate.

is your plan not to build UWP specific packages? Which I think is just fine if the packages work for UWP. I'm not quite understanding the issue (like I asked above), because it seems like directory a re-arrangement problem which shouldn't be a big hassle. What am I missing here?

**Comment by tomspilman** [comment] 2015-08-06 01:16
>  It just means the fix is less immediate.

That is ok... we can wait until this is fixed to fully switch to VS2015.

> is your plan not to build UWP specific packages?

 No...  we plan to build UWP packages for UWP platforms using VS2015.  We just have to keep VS2013 installed and use it for all our other platforms.

>  it seems like directory a re-arrangement problem which shouldn't be a big hassle. What am I missing here?

The issue is everything else we have to fix...    our project generator, build instructions, build scripts, installer scripts, etc. for 8 or 9 platforms.

Beyond that it is a bad directory structure.  There is no good reason to hide projects in folders like this.  It is only a hack to work around this NuGet issue...   and IMO it is NuGet that needs to be fixed.... not our project.

**Comment by yishaigalatzer** [comment] 2015-08-06 01:22
No one is arguing that NuGet should not add this, it is just a release schedule thing. Its not just NuGet, its NuGet + C# project system picking up renamed lock files, and PCL updating the correct project.json. These kind of integrations are not happening overnight.

I also don't necessarily agree that separating the projects is a hack, multiple csproj files in a single folder is kind of a similar hack. But this is just a taste thing, and obviously your choice, not mine.

There is no finger pointing or who is to blame, its all about supporting our customers. As long as you have a solution I'm happy, and we will do our best to come out with a solution as soon as possible.

**Comment by yishaigalatzer** [comment] 2015-08-06 01:26
Moving tentatively to the 3.1.2 milestone, assuming the visual studio tools can support it in a similar timeframe or through an msbuild task.

**Comment by nigel-sampson** [comment] 2015-08-06 01:30
This may be a misunderstanding about what everyone is saying when referring to "shared projects". I took this as many using the "Shared project" type in Visual Studio `shproj`.

The problem (at least for me) is that recommendation to move to using a Shared project in one folder and project heads in other folders instead of having all the source / projects in one folder isn't workable in the long term.

This is because there are a number of files are only used by the subset of projects, but by including them in the shared project they're shared with all the heads, we would then need to use compilation directives so they're not compiled into the projects we don't want them to be.

**Comment by tomspilman** [comment] 2015-08-06 01:39
> There is no finger pointing or who is to blame, its all about supporting our customers.

No blame here.... this stuff happens.  As long as the issue will be addressed in a future release we are good for now.

**Comment by yishaigalatzer** [comment] 2015-08-06 04:26
@nigel-sampson I'm not suggesting to use an shproj. Instead I'm suggesting to move the csproj files to a separate folder and put the project.json next to them. Then link the source files.

This is just folder reshuffling which I think should work quite easily. Could you tell me if this works for you or are you still blocked?

@tomspilman thanks for the comment, I hope we can get enough traction to fix this quickly.

**Comment by nigel-sampson** [comment] 2015-08-06 04:40
Yeah this is working, we temporarily have the UWP project in a separate folder till this gets resolved.

Thanks

**Comment by CobraCalle** [comment] 2015-08-18 11:19
Adding hunderets of files by linking them can not be mouch more than a temp. workaround.

I would prefer a solution analog to the old packages.config files... just prefixing them with the project Name and thats it. I think the would be the most straight forward approach and should not be very complex to implement

**Comment by yishaigalatzer** [comment] 2015-08-18 17:18
@cobracalle We completely agree. We plan to do the first step in an upcoming release (NuGet will restore from {projectName}.project.json to {projectName}.project.lock.json. And for the UI to edit the right file when updating packages.

This also requires a change from the project system to a. pickup the right lock file in the build b. in PCL edit the right project.json file

@pilchie 's team is tracking it on their side

**Comment by emgarten** [comment] 2015-08-21 01:31
I have added support for projectName.project.json to nuget.exe and the Visual Studio 2015 extension.

NuGet/NuGet.Packagemanagement@de28a73b3082dfaeaadfb16916142a77ebdc2edb
NuGet/NuGet.Packagemanagement@7d76fca64714e02b935c76592419afbb68dd8f45
NuGet/NuGet.VisualStudioExtension@70850499ddaabe2c265dca50287ff2b0be715def

**Closed by emgarten** 2015-08-21 01:31 UTC
Labels: Area:VS.Client, Priority:1, Type:DCR

**Comment by Pilchie** [comment] 2015-08-21 01:45
Tagging @rchande and @jasonmalinowski too

**Comment by tomspilman** [comment] 2015-08-21 02:34
Fantastic @emgarten !  When can we expect this feature to get released?

**Comment by yishaigalatzer** [comment] 2015-08-21 03:23
We are still depending on a change in the c# project system. We will update further when that happens as it related to a visual studio release and not just a nuget release.

**Comment by tomspilman** [comment] 2015-08-21 03:32
Thanks @yishaigalatzer !

**Comment by tomspilman** [comment] 2015-10-11 18:10
FYI.  The Windows 10 SDK Tools release includes the fix for this:

> - Added support for multiple csproj in one folder with project.json, with {projectName}.project.json support.

https://social.msdn.microsoft.com/Forums/en-US/e9df01f6-1474-4a4e-98fc-2567591c764f/update-11-release-notes-and-installation-instructions?forum=Win10SDKToolsIssues

**Comment by nigel-sampson** [comment] 2016-02-10 02:33
Just an FYI for anyone else who runs into this gotcha.
- For `packages.config` the supported pattern was `packages.{project-name}.config`.
- For `project.json` the supported pattern is `{project-name}.project.json`.

**Comment by csharpfritz** [comment] 2016-02-10 02:38
I'll get an entry into the docs to make this feature clear

**Comment by rshackleton** [comment] 2016-02-18 09:12
This still seems to be an issue when using packages.config, not checked when using packages.json when using VS2015 Update 1. Are we still waiting on a fix on VS's side?

**Comment by Pilchie** [comment] 2016-02-18 17:00
Tagging @jasonmalinowski too.

**Comment by nigel-sampson** [comment] 2016-02-18 21:45
Currently using both versions of this `packages.config` and `project.json` in [Caliburn.Micro](https://github.com/Caliburn-Micro/Caliburn.Micro/tree/3.0.0) with no problems.
