### ISSUE TITLE
Restore is skipped from VS when two projects are in the same folder

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#6038] opened 2017-10-16 16:00 UTC
Moved from https://github.com/dotnet/standard/issues/538.

## Details about Problem
Restore skips one project when two projects are placed in the same folder.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI

NuGet version (x.x.x.xxx):
4.4.0

dotnet.exe --version (if appropriate):
2.0.0

VS version (if appropriate):
15.4.0 Preview 3.0

OS version (i.e. win10 v1607 (14393.321)):
win10 1703 (15063.608)

Worked before? If so, with which NuGet version:
Same scenario worked in project.json (recall the $(MSBuildProjectName).project.lock.json feature)

## Detailed repro steps so we can see the same problem

Do the following:
1. Dotnet new lib
2. copy <lib.csproj> to <lib.other.csproj>
3. Make sure to delete the obj folders.
4. Open VS and add both files to a sln.
5. Build the SLN.

**Expect**: 
Build successfully

**Actual**:
Build fails for one project.

## Other suggested things

You can workaround this by manually restoring both projects on the commandline with dotnet restore or MSBuild restore.

I tried to set ProjectAssetsFile to a unique name, thinking that might help but it did not.

### Verbose Logs

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
Running restore with 8 concurrent jobs.
Reading project file F:\ericstj\scratch\rs\rs.csproj.
The restore inputs for 'rs' have not changed. No further actions are required to complete the restore.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: F:\ericstj\scratch\rs\obj\project.assets.json
No-Op restore. The cache will not be updated. Path: F:\ericstj\scratch\rs\obj\rs.csproj.nuget.cache
Restore completed in 5.84 ms for F:\ericstj\scratch\rs\rs.csproj.

NuGet Config files used:
    C:\Users\ericstj\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    C:\Users\ericstj\.dotnet\NuGetFallbackFolder
    https://api.nuget.org/v3/index.json
```

### Sample Project
[rs.zip](https://github.com/NuGet/Home/files/1388167/rs.zip)

Alternatively clone https://github.com/ericstj/scratch.git, open rs\rs.sln and try to build it.

**Comment by ericstj** [comment] 2017-10-19 15:58
@rrelyea this appears to be a bug in the VS.Client's restore on build.  Can you please have a look and triage appropriately?

**Comment by jainaashish** [comment] 2017-10-21 04:49
@ericstj how is this even working with msbuild or dotnet? wouldn't it always create a single `project.assets.json` file?

**Comment by ericstj** [comment] 2017-10-23 15:56
As I mentioned above, it's still broken when assigning a unique assets file.  It's also possible that folks are intentionally sharing the assets file (as was the case with the OP).

I think this needs to work: folks added the `$(MSBuildProjectName).project.lock.json` convention specifically to support this scenario with nuget 3.

**Comment by rrelyea** [comment] 2017-10-23 19:22
Although strange, we should support shared src\ directories for 2 projects.

**Comment by emgarten** [comment] 2017-11-09 20:35
Duplicate of https://github.com/NuGet/Home/issues/4463

We need to add the project name to the assets file name as mentioned.

**Closed as completed by emgarten** 2017-11-09 20:35 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Priority:2, Type:Bug, Functionality:Restore
