### ISSUE TITLE
dotnet nuget push with --skip-duplicate pushes .snupkg constantly and causes validation to fail.

### ISSUE THREAD

**Issue by HavenDV** [NuGet/Home#10475] opened 2021-01-22 12:11 UTC
I use a command like this to push all .nupkg files at once inside Github Actions:
```yml
- name: Publish
  run: dotnet nuget push
    src\**.nupkg
    --api-key ${{ secrets.NUGET_KEY }}
    --source https://api.nuget.org/v3/index.json
    --skip-duplicate
```
When I update only one library out of many in a commit, it updates all .snupkg files and fails validation. In my opinion --skip-duplicate should not load the .snupkg file if the .nupkg file with that version already exists in the source. Or .snupkg must be versioned too.
If this is the correct behavior, I would like to know if there is a way to get around this without radically complicating it?

I have also tried deterministic build, with 
```xml
<Deterministic>true</Deterministic>
```
and
```yml
- name: Build
  run: dotnet build
    --configuration Release
    --nologo
    /p:ContinuousIntegrationBuild=true
    /p:DeterministicSourcePaths=true
```
But it also was unsuccessful.

**Comment by dominoFire** [comment] 2021-01-25 21:32
@donnie-msft Do you have any thoughts ?

**Comment by donnie-msft** [comment] 2021-01-25 22:47
@dominoFire & @HavenDV I'm not quite following this scenario.

>  it updates all .snupkg files and fails validation

Please include the exact message you are talking about. Is it a nuget.org message?

> When I update only one library out of many in a commit, it updates all .snupkg files and fails validation. 

What is meant by update? You mean you make changes to contents of a nuget package, but don't change the version #?

Perhaps you're asking a slightly different version of the question posed here?: https://github.com/NuGet/Home/issues/9647

**Comment by HavenDV** [comment] 2021-01-26 02:15
> Perhaps you're asking a slightly different version of the question posed here?: #9647

Yes, it is almost the same.

The situation is this - there is a repository that contains 20 libraries. They depend on the external Core library, when it is updated, the general version in the Directory.Build.props file changes and they are all updated at once. But they also have their versions, which are defined as `<Version>$(Version).100</Version>`, so I can only update the specific library.
With this approach, when updating a specific version of the library(to 101/102 etc.), .snupkg files are recreated and loaded, they have a hash that is different from the already loaded .nupkg (for all but the modified library) and causes a validation error:
```
The symbol package $LibraryName$ failed validation because of the following reason(s):

The uploaded symbols package contains pdb(s) for a corresponding dll(s) not found in the nuget package.
Your symbol package was not published on NuGet Gallery and is not available for consumption.

You can reupload your symbol package once you've fixed the issue with it.
```
![image](https://user-images.githubusercontent.com/3002068/105790496-33b0e780-5fd0-11eb-92ae-92776e15af70.png)


I offered three options for solving the problem:
1. Do not load .snupkg if --skip-duplicate flag is specified and loading .nupkg returned 409 error. Do this check for each of the 20 packages.
2. Add versioning for .snupkg packages. For each version, it can only be downloaded once, just like the .nupkg files.
3. With a deterministic build, make sure that the hashes for unchanged libraries match, so the validation of .snupkg packages would be successful.

**Comment by donnie-msft** [comment] 2021-01-26 02:30
Going to defer to @zkat for any changes here.
I worked on skip duplicate flag, and it's simply ignoring 409's. It can't predict what's on the server. nuget.org doesn't generate a 409 for snupkgs, and they have reasons for that: https://github.com/NuGet/NuGetGallery/issues/7681.
Have you tried `-No-Symbols`? https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-push#options

**Comment by HavenDV** [comment] 2021-01-26 02:48
https://docs.microsoft.com/ru-ru/dotnet/core/tools/dotnet-nuget-push
```
-n|--no-symbols true

Doesn't push symbols (even if present).
```

Perhaps the description is incorrect here, but no, I have not tried this.
I will try and write to you.

**Comment by HavenDV** [comment] 2021-01-26 03:17
If I specify `--no-symbols true` then .snupkg files simply stop loading(As I understand it because they exist and they exist for a fixed version).
I would like to provide the library user with an up-to-date .snupkg file for each version.

**Comment by dominoFire** [comment] 2021-02-03 20:33
If you provide an up-to-date .snupkg file, have your binaries in your .nupkg file changed as well? In that case, wouldn't it be better to upload a new version of the package?

**Comment by HavenDV** [comment] 2021-02-06 09:57
> If you provide an up-to-date .snupkg file, have your binaries in your .nupkg file changed as well? In that case, wouldn't it be better to upload a new version of the package?

Not. I'm talking about situations where I only update the README. Github Actions also triggers a pipeline that has dotnet nuget push. At the moment, assemblies in which the version does not change are correctly ignored. But there are many notifications in the mail that Symbol package validation failed. For now, I just added them to spam and ignore them, but the problem is still there.

**Comment by zivkan** [comment] 2021-02-06 12:35
I believe this issue is a duplicate of https://github.com/NuGet/Home/issues/9647

**Comment by zkat** [comment] 2021-02-08 21:33
Closing as duplicate. Please let us know if you disagree. :)

**Closed as completed by zkat** 2021-02-08 21:33 UTC
Labels: Type:Bug, Functionality:Push
