### ISSUE TITLE
NuGet should report which package source was used to restore each package from

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#7577] opened 2018-12-01 06:01 UTC
## Details about Problem

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): `4.9.1.5694`

dotnet.exe --version (if appropriate): `2.2.0-preview1-007622`

VS version (if appropriate): 15.9.2

OS version (i.e. win10 v1607 (14393.321)): Win10

Worked before? If so, with which NuGet version: not a regression

## Detailed repro steps so we can see the same problem

It is difficult to determine which package source a package was restored from. Upon successful restore (and especially when using `/Verbosity detailed`) NuGet should output for each restored package which source was used.

It does show the summary of used package sources at the end, but it would be nice to see which packages were restored from where.

Also show a list of unused package sources at the end as a bonus.

**Comment by StingyJack** [comment] 2018-12-05 13:52
It would also be nice to have a /whatif  to see what packages _would_ be restored and from where

**Comment by KirillOsenkov** [comment] 2018-12-05 19:35
yes `whatif` would be fantastic. 💯

**Comment by satbai** [comment] 2019-02-14 00:47
This would greatly help with debugging!

**Comment by nkolev92** [comment] 2019-09-25 21:28
Duplicate of https://github.com/NuGet/Home/issues/3055. 

I've also added a comment in that issue to indicate that the asks are not completely equivalent.

**Closed as completed by nkolev92** 2019-09-25 21:28 UTC
Labels: Type:DCR, Functionality:Restore, Area:Logging
