### ISSUE TITLE
VS doesn't notice new Directory.Build.props for old-style csproj

### ISSUE THREAD

**Issue by asherber** [NuGet/Home#7660] opened 2018-12-22 13:53 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):  VS UI

NuGet version (x.x.x.xxx): 4.7.1.5393

dotnet.exe --version (if appropriate):  n/a

VS version (if appropriate):  15.9.2

OS version (i.e. win10 v1607 (14393.321)):  Win10 v1803 (17134.472)

Worked before? If so, with which NuGet version:  ??

## Detailed repro steps so we can see the same problem

This issue manifested itself with [Nerdbank.GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning), but I imagine it's general to anything that uses Directory.Build.props.

1. Create Framework console project (old-style csproj) in VS with new git repo, build.
1. `nbgv install`. This dotnet global tool for GitVersioning drops a Directory.Build.props file and a version.json file in the solution dir. The props file has a `PackageReference` to the nbgv NuGet package, which is responsible for inserting version info into the exe at build time.
1. Delete the version attributes from AssemblyInfo.cs, and commit changes.
1. Build solution in VS -- no version info embedded
1. Rebuild solution in VS -- no version info
1. Close and reopen solution
1. Build solution in VS -- no version info
1. Rebuild solution in VS -- version info!

It appears that VS takes stock of the build situation when a solution is first opened and then caches that information, so that in 4 and 5 above it's not aware of the props file that was added in 2 and doesn't fetch the nbgv NuGet package. After a close and reopen, VS is aware of the file, but the build in 7 doesn't do anything because the obj dir is up to date, so VS doesn't think anything is needed. But a rebuild at that point (or by deleting obj and building) gets VS to download the NuGet package referenced in the props file.

I've packaged up a little sample in two files so that you don't have to have nbgv installed yourself. 

1. Unzip the ConsoleApp1.zip file, open it in VS, and build.
1. Unzip the nbgv.zip file and drop those two files into your solution dir. 
1. Proceed with step 4 above.

[nbgv.zip](https://github.com/NuGet/Home/files/2705255/nbgv.zip)
[ConsoleApp1.zip](https://github.com/NuGet/Home/files/2705256/ConsoleApp1.zip)

**Comment by nkolev92** [comment] 2018-12-26 22:23
NuGet depends on project-system for reading the PackageReference items in VS. 

Duplicate of https://github.com/dotnet/project-system/issues/2888

I was not able to reproduce the 7/8 part. 
If you have "Restore on build" enabled, then restore will kick in and it should've been good.

**Closed as completed** 2018-12-26 22:23 UTC
Labels: Resolution:Duplicate, Resolution:External, Partner:Project-System
