### ISSUE TITLE
pack of project with <PackageReference Version="*" ... /> gets wrong dependency version after packed

### ISSUE THREAD

**Issue by TFTomSun** [NuGet/Home#7328] opened 2018-09-26 08:17 UTC
I have created a project that reference another package via MSBuild PackageReference. I set the version to wildcard. When I pack my project, the dependend package version is set to the version of the created package.
Example:
- I want to pack and push MyProject as Version 1.0.0
- I reference Newtonsoft.Json as Version="*" which resolve to the latest version lets say 11.0

```
dotnet pack -version 1.0.0
dotnet nuget push *.nupkg -s NugetSource

```

When I view my pushed package in the package manager, it says that it has a dependency on Newtonsoft.Json >= 1.0.0 which is wrong.

I would expect that my package shows a dependency on NewtonSoftJson >= 11.0

Is this an intended behavior? Is it possible to disable it?

**Comment by rohit21agrawal** [comment] 2018-09-26 23:53
the core issue here is that * is written out as (, ) in the assets file, and calling VersionRange.IsFloating returns false for a version range like this.

@nkolev92 @jainaashish  any thoughts on why this happens?

**Comment by TFTomSun** [comment] 2018-09-27 05:26
@rohit21agrawal thx for the analysis. Is there any workaround? for example modify the asset file in a msbuild target before it is evaluated

**Comment by rohit21agrawal** [comment] 2018-09-27 18:36
no, i wouldn't recommend that.

the only workaround i can think for now is you write the version in your csproj as 11.* instead of *

**Comment by TFTomSun** [comment] 2018-10-01 14:25
I found a workaround:
`<PackageReference Include="Newtonsoft.Json" Version="[*,9999.0]" /> `
resolves to the latest available version, assuming that there is no version higher than 9999.0

**Comment by TFTomSun** [comment] 2018-10-01 15:08
Just in case someone else needs a general solution to this problem:
Create a Directory.Build.targets file in your repository root (or create an equivalent build package) with the following content:


```xml
<Project>
  <ItemGroup>
    <PackageReferenceToReplace Include="@(PackageReference -> WithMetadataValue('Version', '*'))"/>
    <PackageReference Update="@(PackageReferenceToReplace)" Version="[*,9999.0]"/>
  </ItemGroup>
</Project>
```

That will dynamically replace all 
`<PackageReference Include="<any package>" Version="*" />`

with 

`<PackageReference Include="<any package>" Version="[*,9999.0]" />`

That means you can keep using 
`<PackageReference Include="<any package>" Version="*" />`
until this issue is fixed. When it is fixed, simply remove the code from the Directory.Build.targets file.

**Comment by nkolev92** [comment] 2019-07-12 22:13
We missed this earlier but this is a duplicate of https://github.com/NuGet/Home/issues/6697.

**Closed as completed by nkolev92** 2019-07-12 22:13 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Pack, Functionality:Restore, Style:PackageReference

**Comment by nkolev92** [comment] 2019-10-04 21:39
fwiw just using `[*, )` should be enough and is arguably more accurate as `*` and `[*, )` should be equivalent.
