### ISSUE TITLE
Allow packages to specify a version range to offer upgrades within

### ISSUE THREAD

**Issue by wtgodbe** [NuGet/Home#12254] opened 2022-11-17 23:26 UTC
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console

### The Elevator Pitch

Today, packages always suggest offering upgrades to the newest version possible. For example, if I depend on `Microsoft.Aspnetcore.Components.Webassembly` version `6.0.10`, Visual Studio's package manager will suggest I upgrade to 7.0.0. However, some packages (e.g. dotnet packages) only contain .dll's for their own TargetFramework, and additionally, a new major version of a package may have API surface area changes that make it incompatible with older major version of a package - therefore the suggested upgrade could break a dev's project. This could also lead them to conclude they should never upgrade, which might make them miss a security update. We should let package authors specify a range of versions within which to offer upgrades, to prevent this from happening and to make sure devs are always being offered the most relevant upgrades for their project.

### Additional Context and Details

We've had a lot of requests for this behavior: https://github.com/dotnet/aspnetcore/issues/38336, https://github.com/NuGet/Home/issues/5725

### Feedback

Please 👍 or 👎 this comment to help us with the direction of this issue & leave as much feedback/questions/concerns as you'd like on this issue itself and we will get back to you shortly.

**Comment by MagicAndre1981** [comment] 2022-11-21 07:01
bringing back `allowedVersions` is [already requested years ago](https://github.com/NuGet/Home/issues/6566) and ignored at all.

**Comment by nkolev92** [comment] 2022-11-28 21:27
This ask is a duplicate of https://github.com/NuGet/Home/issues/6566 and https://github.com/NuGet/Home/issues/5725. 

The first one tackles the version aspect, the 2nd one talks about the compat aspect.

**Closed as completed by nkolev92** 2022-11-28 21:27 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Feature, Functionality:Update, Area:Versioning
