### ISSUE TITLE
Install-Package ExcelDataReader does not install excel.dll

### ISSUE THREAD

**Issue by Gardens18** [NuGet/Home#7203] opened 2018-08-14 14:58 UTC
Install-Package ExcelDataReader does not install excel.dll

**Comment by zhili1208** [comment] 2018-08-14 21:36
could you provide more information? VS version? NuGet Version? project type? thanks

**Comment by mishra14** [comment] 2018-08-14 22:17
closing as dupe of https://github.com/ExcelDataReader/ExcelDataReader/issues/342

@Gardens18 This is an issue that you need to take up with the package owners.

**Closed as completed by mishra14** 2018-08-14 22:17 UTC
Labels: Resolution:External
