### ISSUE TITLE
Cannot update NuGet package with packages.config

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#10594] opened 2021-02-23 14:07 UTC
If I have a project with a `packages.config`, and I try to update a package it fails.

VS Version: latest internal version from Feb 23.

Repro:
1. Create a new .NET 4.7.2 class library using the old project system (and with Packages.config set as the default)
2. Install Refit 6.0.15
3. Try update to a later version

```
Attempting to gather dependency information for package 'Refit.6.0.20' with respect to project 'ClassLibrary6', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 947 ms
Attempting to resolve dependencies for package 'Refit.6.0.20' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Refit.6.0.20'
Resolved actions to install package 'Refit.6.0.20'
Removed package 'Refit.6.0.15' from 'packages.config'
This reference cannot be removed from the project because it is always referenced by the compiler.
Successfully uninstalled 'Refit.6.0.15' from ClassLibrary6
Adding package 'Refit.6.0.20' to folder 'D:\dev\ClassLibrary6\packages'
Added package 'Refit.6.0.20' to folder 'D:\dev\ClassLibrary6\packages'
This reference cannot be removed from the project because it is always referenced by the compiler.
Install failed. Rolling back...
Package 'Refit.6.0.20 : System.Net.Http [4.3.4, ), System.Net.Http.Json [5.0.0, ), System.Text.Json [5.0.1, )' does not exist in project 'ClassLibrary6'
Package 'Refit.6.0.15' already exists in folder 'D:\dev\ClassLibrary6\packages'
This reference cannot be removed from the project because it is always referenced by the compiler.
Added package 'Refit.6.0.15' to 'packages.config'
Removing package 'Refit.6.0.20 : System.Net.Http [4.3.4, ), System.Net.Http.Json [5.0.0, ), System.Text.Json [5.0.1, )' from folder 'D:\dev\ClassLibrary6\packages'
Removed package 'Refit.6.0.20 : System.Net.Http [4.3.4, ), System.Net.Http.Json [5.0.0, ), System.Text.Json [5.0.1, )' from folder 'D:\dev\ClassLibrary6\packages'
Executing nuget actions took 783 ms
Failed to add reference to 'Refit'.
  PSService!38432 HR: E_Exception
Time Elapsed: 00:00:01.7752650
========== Finished ==========

```

**Comment by donnie-msft** [comment] 2021-02-23 22:12
I was unable to repro on 16.10.0 Preview 2.0 [31022.287.main].
Version `6.0.20` doesn't exist on nuget.org. Was this a private feed? I found 6.0.21 and 6.0.24. Neither of these had an issue when updating via Package Manager in VS.

Did you use Package Manager? Does it continue to repro with 6.0.20, and is it only that version?

**Comment by donnie-msft** [comment] 2021-02-23 22:15
One observation that may be relevant... I found that after clicking Install/Update, VS is VERY slow to refresh the installed version and change the `Install button` to an `Update button`.

Do you think this was happening to you? Could be the key to finding your repro..
![image](https://user-images.githubusercontent.com/49205731/108915264-9f4f9a00-75fa-11eb-980f-0ed6135749ce.png)

**Comment by aortiz-msft** [comment] 2021-03-11 18:10
We are closing this issue since we didn't hear back from you, but definitely let us know if you can still reproduce this problem on the latest version of NuGet. Thank you for your feedback and happy coding!

**Closed as completed by aortiz-msft** 2021-03-11 18:10 UTC
Labels: Type:Bug, Functionality:VisualStudioUI, Style:Packages.Config, WaitingForCustomer
