### ISSUE TITLE
Nuget 3.4+ can not restore some packages fails with "The given path's format is not supported"

### ISSUE THREAD

**Issue by alexxn** [NuGet/Home#3434] opened 2016-09-12 18:11 UTC
1) Download https://github.com/umbraco/Umbraco-CMS/releases/tag/release-7.2.1 sources
2) Unpack and run nuget restore command

D:\Temp\nuget.exe restore "D:\Temp\Umbraco-CMS-release-7.2.1\src\umbraco.sln"
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
The given path's format is not supported.

3) Packages are not restored

The issue can be reproduced in nuget-3.5.0rc1 and 3.4.4

Version 3.3 works fine

**Comment by rrelyea** [comment] 2016-09-12 18:14
Please investigate.

**Comment by zhili1208** [comment] 2016-09-12 21:11
I think this is a duplicate issue, https://github.com/NuGet/Home/issues/3235
@alexxn Can you try RC2 bits: https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine/3.5.0-rtm-1829?

**Comment by alexxn** [comment] 2016-09-14 11:14
Rtm-1829 seems to work well.  
It fails to restore, but this time due to outdated packages in the solution.

```
d:\Temp>nuget.exe restore Umbraco-CMS-release-7.2.1\src\umbraco.sln
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
WARNING: Project file d:\Temp\Umbraco-CMS-release-7.2.1\src\http://localhost:3961 cannot be found.
Restoring NuGet package SqlServerCE.4.0.0.
Restoring NuGet package UrlRewritingNet.UrlRewriter.2.0.60829.1.
Restoring NuGet package Microsoft.Web.Helpers.1.0.0.
...
WARNING: Unable to find version '1.0.0' of package 'Microsoft.Web.Helpers'.
...
Errors in packages.config projects
    Unable to find version '1.0.0' of package 'Microsoft.Web.Helpers'.
```

**Comment by zhili1208** [comment] 2016-09-14 17:19
@alexxn Can you provide your nuget.config? Looks like nuget can't find packages from your sources, not sure which source is using in your case.

**Comment by alexxn** [comment] 2016-09-15 11:40
I used vanilla Umbraco-CMS release-7.2.1 sources and have no my own nuget sources configured.

```
NuGet Config files used:
    D:\Temp\Umbraco-CMS-release-7.2.1\src\.nuget\NuGet.Config
    C:\Users\USERNAME\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Users\USERNAME\.nuget\packages\
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

**Comment by alexxn** [comment] 2016-09-15 11:42
C:\Users\USERNAME\AppData\Roaming\NuGet\NuGet.Config:

```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
</configuration>``
```

**Comment by zhili1208** [comment] 2016-09-15 16:54
I checked those packages, they don't exist in nuget.org, that's why restore failed

**Comment by rrelyea** [comment] 2016-09-15 19:04
Dupe of #3442

**Closed as completed by rrelyea** 2016-09-15 19:04 UTC
Labels: Resolution:Duplicate
