### ISSUE TITLE
Cryptic 'Key not valid for use in specified state.' message for stored API key after user password change

### ISSUE THREAD

**Issue by mycroes** [NuGet/Home#8147] opened 2019-05-21 07:47 UTC
After changing the (Windows) user password on our CI build server the stored API key was no longer working. The error message from NuGet.exe was `Key not valid for use in specified state.`, which doesn't point to the cause of the problem. After setting the API key using `NuGet.exe SetApiKey ...` the encrypted value has changed.

I suspect NuGet derives the encrypted API key from the user password, a sensible message when the key fails to load would've saved me a couple of hours searching for the cause of this issue (the password was changed due to other infrastructure changes, so who'd expect the password change to be the cause of this problem?)

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe

NuGet version (x.x.x.xxx):
4.5.1.4879

dotnet.exe --version (if appropriate):
NA

VS version (if appropriate):
NA

OS version (i.e. win10 v1607 (14393.321)):
Windows 8.1 Pro Build 9600

Worked before? If so, with which NuGet version:
Probably not, but unsure.

## Detailed repro steps so we can see the same problem

1. Set an API key for a source using `NuGet.exe SetApiKey ...`
2. Verify the key works for the source (`NuGet.exe push` / `NuGet.exe delete`)
3. Change the Windows user password
4. Verify the key no longer works and NuGet.exe gives the specified error message

**Comment by rrelyea** [comment] 2019-05-21 22:05
Please see explanation in: #7850 
Are you sure that you changed the password? Or was it that it was a different user?

**Comment by rrelyea** [comment] 2019-05-21 23:54
by the way, do you see the same error if you use NuGet.exe 5.0 or 5.1
Working to repro here, but want to dig in the right direction.

**Comment by nkolev92** [comment] 2019-12-31 02:29
Closing as by design similar to https://github.com/NuGet/Home/issues/8147.

**Closed as completed by nkolev92** 2019-12-31 02:29 UTC
Labels: Resolution:Duplicate, Resolution:ByDesign, Area:Settings, Area:Authentication
