### ISSUE TITLE
Nuget manager console.VS 2015. Reinstalling single package forced reinstall of all packages

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1209] opened 2015-08-18 10:09 UTC
_From @LogikBlitz on August 17, 2015 7:15_

Setup.
Vs 2015
Nuget: 3.1.60724.766

Scenario.
In a solution i wanted to force nuget to reinstall a single package with very few sub dependencies.
I used command:

```
update-package ***.BaseMessages -reinstall
```

which i have used many times before in VS 2013.
Expected behavior.
Reinstall only said package, in the specified project, and possible sub dependencies. ( i really cant remember if the above command in VS 2013 did a reinstall of the sub dependencies as well)

Actual behavior:
Nuget reinstalled **all** packages in the specific project.

That is either a bug or a very undesired change in the api.

Below is a subset of the console transcript that is produced from above command:

```
update-package Infomedia.MQ.BaseMessages -reinstall
Attempting to gather dependencies information for multiple packages with respect to project 'QueryControlService', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Removed package 'Infomedia.Framework.Redis.PubSub 1.0.2.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Framework.Redis.PubSub 1.0.2.0' from QueryControlService
Removed package 'Infomedia.Framework.Redis.Connectivity 1.0.2.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Framework.Redis.Connectivity 1.0.2.0' from QueryControlService
Removed package 'StackExchange.Redis 1.0.371' from 'packages.config'
Successfully uninstalled 'StackExchange.Redis 1.0.371' from QueryControlService
Removed package 'Infomedia.Logging.ApplicationLogging 3000.1.4.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Logging.ApplicationLogging 3000.1.4.0' from QueryControlService
Removed package 'Infomedia.MQ.RabbitControl 3000.0.1.0' from 'packages.config'
Successfully uninstalled 'Infomedia.MQ.RabbitControl 3000.0.1.0' from QueryControlService
Removed package 'EasyNetQ 0.40.1.348' from 'packages.config'
Successfully uninstalled 'EasyNetQ 0.40.1.348' from QueryControlService
Removed package 'RabbitMQ.Client 3.4.0' from 'packages.config'
Successfully uninstalled 'RabbitMQ.Client 3.4.0' from QueryControlService
Removed package 'NLog 3.1.0.0' from 'packages.config'
Successfully uninstalled 'NLog 3.1.0.0' from QueryControlService
Removed package 'Infomedia.Logging.DatabaseLogging 3000.2.0.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Logging.DatabaseLogging 3000.2.0.0' from QueryControlService
Removed package 'Infomedia.MQ.BaseMessages 3000.3.1.0' from 'packages.config'
Successfully uninstalled 'Infomedia.MQ.BaseMessages 3000.3.1.0' from QueryControlService
Removed package 'Infomedia.IQL.SyntaxControl 2014.7.31.1' from 'packages.config'
Successfully uninstalled 'Infomedia.IQL.SyntaxControl 2014.7.31.1' from QueryControlService
Removed package 'EasyNetQ.Management.Client 0.40.1.348' from 'packages.config'
Successfully uninstalled 'EasyNetQ.Management.Client 0.40.1.348' from QueryControlService
Removed package 'Newtonsoft.Json 6.0.8' from 'packages.config'
Successfully uninstalled 'Newtonsoft.Json 6.0.8' from QueryControlService
Removed package 'Infomedia.MQ.Configuration 2014.3.5.1' from 'packages.config'
Successfully uninstalled 'Infomedia.MQ.Configuration 2014.3.5.1' from QueryControlService
Removed package 'Infomedia.Logging.Utilities 2014.5.6.1' from 'packages.config'
Successfully uninstalled 'Infomedia.Logging.Utilities 2014.5.6.1' from QueryControlService
Removed package 'Infomedia.Common.Utilities 3000.6.0.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Common.Utilities 3000.6.0.0' from QueryControlService
Removed package 'Infomedia.Microsoft.Practices.2006 2.0.2' from 'packages.config'
Successfully uninstalled 'Infomedia.Microsoft.Practices.2006 2.0.2' from QueryControlService
Removed package 'Infomedia.Logging.Shared 3000.5.1.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Logging.Shared 3000.5.1.0' from QueryControlService
Removed package 'Infomedia.Framework.Iql.Query.QueryEntities 3000.0.6.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Framework.Iql.Query.QueryEntities 3000.0.6.0' from QueryControlService
Removed package 'Infomedia.Fizzware.Nbuilder 2.2.0.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Fizzware.Nbuilder 2.2.0.0' from QueryControlService
Removed package 'Infomedia.Exceptions 3000.1.0.0' from 'packages.config'
Successfully uninstalled 'Infomedia.Exceptions 3000.1.0.0' from QueryControlService
Removed package 'Dapper 1.42' from 'packages.config'
Successfully uninstalled 'Dapper 1.42' from QueryControlService
Removed package 'Autofac.Wcf 3.0.1' from 'packages.config'
Successfully uninstalled 'Autofac.Wcf 3.0.1' from QueryControlService
Removed package 'Autofac 3.5.2' from 'packages.config'
Successfully uninstalled 'Autofac 3.5.2' from QueryControlService

```

_Copied from original issue: NuGet/NuGetGallery#2624_

**Comment by yishaigalatzer** [comment] 2015-08-18 20:04
Duplicate of #737.

Reinstall was really designed to update the whole package graph when the framework in the project has changed. So the old behavior was "somewhat" unintended and hence not tested and regressed.

We plan to bring back the behavior (as tracked by #737) to keep backwards compat.

What it really does is uninstall the package, and reinstall it with the same specific version. So you work around is

uninstall-package packageId
install-package packageId -version versionId

If you want to just deal with the package apply the appropriate ignore dependency flags - https://docs.nuget.org/consume/package-manager-console-powershell-reference#install-package

**Closed as completed by yishaigalatzer** 2015-08-18 20:04 UTC

**Comment by LogikBlitz** [comment] 2015-08-18 21:30
> uninstall-package packageId
> install-package packageId -version versionId

According to the documentation you link to the required command would be:
`install-package [-Id] <string> [-IgnoreDependencies] [-Version <string>]  [-Force]`
in order to achieve the same as
`update-package <packagename> -reinstall`

Granted i have not tried the other syntax but it is longer and more complex, so i applaud the fact that you aim to maintain the old behavior.
Allthou i always found it a bit misleading that update has the -reinstall flag. 
I do find it more logical to use
`install-package <packagename> -reinstall` but maybe that is just me... 

On another note

> Reinstall was really designed to update the whole package graph when the framework in the project has changed. So the old behavior was "somewhat" unintended and hence not tested and regressed.

It seems that the unintended behaviour is actually really well described and does not, according to the documentation, seem to be unintended.
https://docs.nuget.org/consume/reinstalling-packages

Anyway - thanks for acting on this and also maintaining some or full backward compatibility. I fully understand if you sometimes need to use a major version bump to do some cleaning and possible killing of some commands/functionalities to keep things a bit more neat - even thou someone (like me :-)) might complain a bit...

**Comment by yishaigalatzer** [comment] 2015-08-18 22:40
:) Documented yes, intended hmmm, not so sure, after all the doc is called "The pitfalls of ..."

Either way we are looking into it, and intend to restore backcompat.

Thanks!

**Comment by Gabby-Paolucci** [comment] 2017-10-30 15:06
Is there any word on restoring this functionality?
