### ISSUE TITLE
Nuget pack: Description is required using nuspec file

### ISSUE THREAD

**Issue by hrlourenco** [NuGet/Home#11023] opened 2021-07-13 16:53 UTC
### NuGet Product Used

NuGet.exe

### Product Version

5.10.0

### Worked before?

5.4.0

### Impact

I'm unable to use this version

### Repro Steps & Context

Hi all,

Whenever I make a nuget pack, it gives me "Description is required". I'm using nuspec files and I have AssemblyDescription into AssemblyInfo file.

This stars in this version "5.7.0". I move back to 5.4.0 where this problem does not happen.

Command: nuget pack xxxxxx.csproj

**Comment by erdembayar** [comment] 2021-08-14 02:34
@hrlourenco 
Thank you for filing this issue.
Since it's required field you need to set directly or indirectly.
1.  In nuspec set following <description>$description$</description>

here is my full nuspec:

```
<?xml version="1.0" encoding="utf-8"?>
<package >
  <metadata>
    <id>Mypacakge</id>
    <version>3.0.0</version>
    <title>1111111</title>
    <authors>222222</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <description>$description$</description>
    <releaseNotes>ooo no</releaseNotes>
    <tags>My Tagz</tags>
  </metadata>
</package>
```

In AssemblyInfo.cs 
`[assembly: AssemblyDescription("vvvvvvvv")]`

I executed `nuget510 pack .\Viewer.csproj`

Resulting file: 
![image](https://user-images.githubusercontent.com/8766776/129431769-dfa06f79-4195-4a57-8bbf-ecf9505aac47.png)

As you can see description is set correctly:
![image](https://user-images.githubusercontent.com/8766776/129431778-cd06bc3e-ae39-4146-8b46-f56797478ec0.png)



2. Another way is you can directly pass as property parameter nuget pack .\proj1.csproj -properties "description=aaaaaaa"

**Comment by zkat** [comment] 2021-08-16 20:48
Closing since this is not a bug :)

**Closed as completed by zkat** 2021-08-16 20:48 UTC
Labels: Product:NuGet.exe, Functionality:Pack, Resolution:NotABug
