### ISSUE TITLE
System.Xml.XmlException: Unrecognized root element in Core Properties part. Line 2, position 2.

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#2718] opened 2016-05-04 15:52 UTC
One of my projects is failing to pack with the following errors which seems related to: 

This has happened after a merge from a different source branch (which still seems to compile and pack properly) However, only a small amount of code has changed with some packages changes in  packages.config.

I was running nuget.exe v.3.3 but after reading #https://github.com/NuGet/Home/issues/1921 and updating to a new version (NuGet Version: 3.4.3.855:) I am still getting the following error

I cant see any issues with the nuspec file, or the packages.config

`NuGet Pack ./Ucas.UnitTests.Common/Ucas.UnitTests.Common.csproj -IncludeReferencedProjects -Verbosity detailed  -MSBuildVersion 14 -Build`

The build works but the zipping of the files is failing with the following stack trace:

> C:\Development\BitBucket\WIP\Identity>NuGet Pack ./Ucas.UnitTests.Common/Ucas.UnitTests.Common.cspro
> j -IncludeReferencedProjects -Verbosity detailed  -MSBuildVersion 14 -Build
> Attempting to build package from 'Ucas.UnitTests.Common.csproj'.
> Building project 'C:\Development\BitBucket\WIP\Identity\Ucas.UnitTests.Common\Ucas.UnitTests.Common.
> csproj' for target framework '.NETFramework,Version=v4.6'.
> Packing files from 'C:\Development\BitBucket\WIP\Identity\Ucas.UnitTests.Common\bin\Debug'.
> Using 'Ucas.UnitTests.Common.nuspec' for metadata.
> Add file 'C:\Development\BitBucket\WIP\Identity\Ucas.UnitTests.Common\bin\Debug\Ucas.UnitTests.Commo
> n.dll' to package as 'lib\net46\Ucas.UnitTests.Common.dll'
> Add file 'C:\Development\BitBucket\WIP\Identity\Ucas.UnitTests.Common\bin\Debug\Ucas.UnitTests.Commo
> n.xml' to package as 'lib\net46\Ucas.UnitTests.Common.xml'
> System.Xml.XmlException: Unrecognized root element in Core Properties part. Line 2, position 2.
>    at MS.Internal.IO.Packaging.PartBasedPackageProperties.ParseCorePropertyPart(PackagePart part)
>    at MS.Internal.IO.Packaging.PartBasedPackageProperties.ReadPropertyValuesFromPackage()
>    at MS.Internal.IO.Packaging.PartBasedPackageProperties..ctor(Package package)
>    at System.IO.Packaging.Package.get_PackageProperties()
>    at NuGet.OptimizedZipPackage.<>c__DisplayClassa.<EnsurePackageFiles>b__9(PackagePart part)
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at NuGet.OptimizedZipPackage.EnsurePackageFiles()
>    at NuGet.OptimizedZipPackage.GetFilesBase()
>    at NuGet.LocalPackage.GetFiles()
>    at NuGet.PackageExtensions.GetFiles(IPackage package, String directory)
>    at NuGet.CommandLine.ProjectFactory.<>c.<AddFiles>b__92_2(IPackage a)
>    at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at NuGet.CommandLine.ProjectFactory.AddFiles(PackageBuilder builder, String itemType, String targ
> etFolder)
>    at NuGet.CommandLine.ProjectFactory.<>c__DisplayClass56_0.<CreateBuilder>b__1(ProjectFactory p)
>    at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action, Object alreadyAppliedProjec
> ts)
>    at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action)
>    at NuGet.CommandLine.ProjectFactory.ApplyAction(Action`1 action)
>    at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath)
>    at NuGet.CommandLine.PackCommand.BuildFromProjectFile(String path)
>    at NuGet.CommandLine.PackCommand.BuildPackage(String path)
>    at NuGet.CommandLine.PackCommand.ExecuteCommand()
>    at NuGet.CommandLine.Command.ExecuteCommandAsync()
>    at NuGet.CommandLine.Command.Execute()
>    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

**Comment by ghost** [comment] 2016-05-04 16:09
as an addendum to this.
When run in Package manage Console (VS2015)
I had thought this might be an issues with XML documentation files embedded - but having removed those and rebuilt the solution, I still get the same error.

> NuGet Pack ./Ucas.UnitTests.Common/Ucas.UnitTests.Common.csproj -IncludeReferencedProjects -Verbosity detailed  -MSBuildVersion 14 -Build
> 
> Attempting to build package from 'Ucas.UnitTests.Common.csproj'.
> Building project 'C:\Development\BitBucket\WIP\Identity\Ucas.UnitTests.Common\Ucas.UnitTests.Common.csproj' for target framework '.NETFramework,Versi
> on=v4.6'.
> Packing files from 'C:\Development\BitBucket\WIP\Identity\Ucas.UnitTests.Common\bin\Debug'.
> Using 'Ucas.UnitTests.Common.nuspec' for metadata.
> Add file 'C:\Development\BitBucket\WIP\Identity\Ucas.UnitTests.Common\bin\Debug\Ucas.UnitTests.Common.dll' to package as 'lib\net46\Ucas.UnitTests.Co
> mmon.dll'
> NuGet.exe : System.Xml.XmlException: Unrecognized root element in Core Properties part. Line 2, position 2.At line:1 char:1
> - NuGet Pack ./Ucas.UnitTests.Common/Ucas.UnitTests.Common.csproj -IncludeReferenc ...
> - ```
>   ```
>   - CategoryInfo          : NotSpecified: (System.Xml.XmlE... 2, position 2.:String) [], RemoteException
>   - FullyQualifiedErrorId : NativeCommandError
>   
>   at MS.Internal.IO.Packaging.PartBasedPackageProperties.ParseCorePropertyPart(PackagePart part)
>   at MS.Internal.IO.Packaging.PartBasedPackageProperties.Re
>   adPropertyValuesFromPackage()
>   at MS.Internal.IO.Packaging.PartBasedPackageProperties..ctor(Package package)
>   at System.IO.Packaging.Package.get_PackageProperties()
>   at NuGet.OptimizedZipPackage.<>c__DisplayClassa.<EnsurePackageFiles>b__9(PackagePart part)
>   at System.Linq.Enumerable.WhereEnumerableIterator'1.MoveNext()
>   at NuGet.OptimizedZipPackage.EnsurePackageFiles()
>   at NuGet.OptimizedZipPackage.GetFilesBase()
>   at NuGet.LocalPackage.GetFiles()
>   at NuGet.PackageExtensions.GetFiles(IPackage package, String directory)
>   at NuGet.CommandLine.ProjectFactory.<>c.<AddFiles>b__92_2(IPackage a)
>   at System.Linq.Enumerable.<SelectManyIterator>d__16'2.MoveNext()
>   at System.Collections.Generic.List'1..ctor(IEnumerable'1 collection)
>   at System.Linq.Enumerable.ToList[TSource](IEnumerable'1 source)
>   at NuGet.CommandLine.ProjectFactory.AddFiles(PackageBuilder builder, String itemType, String targetFolder)
>   at NuGet.CommandLine.ProjectFactory.<>c__DisplayClass56_0.<CreateBuilder>b__1(ProjectFactory p)
>   at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action'1 action, Object alreadyAppliedProjects)
>   at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action'1 action)
>   at NuGet.CommandLine.ProjectFactory.ApplyAction(Action'1 action)
>   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath)
>   at NuGet.CommandLine.PackCommand.BuildFromProjectFile(String path)
>   at NuGet.CommandLine.PackCommand.BuildPackage(String path)
>   at NuGet.CommandLine.PackCommand.ExecuteCommand()
>   at NuGet.CommandLine.Command.ExecuteCommandAsync()
>   at NuGet.CommandLine.Command.Execute()
>   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
>

**Comment by ghost** [comment] 2016-05-04 16:11
Accidentally closed in error!

**Comment by toddm** [comment] 2016-05-05 18:07
This sounds like it might be the same issue as https://github.com/NuGet/Home/issues/2651 that is fixed in 3.4.4.  Would you verify that our upcoming release fixes the problem?
- Download not yet final version 3.4.4. of nuget.commandline.nupkg from https://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine/3.4.4-rtm-870
- Rename the .nupkg to .zip
- Grab nuget.exe from inside the zip file in the tools directory.
- Try this version of nuget.exe to verify that it has fixed your issue.
- Tell us how it went

**Comment by ghost** [comment] 2016-05-06 12:21
No luck with the new version same error reported

However: I managed to work out a way to reproduce this error consistently after messing around with my project, finally pinning it down to a single a single library: structureMap.automocking. 

As soon as following line is added the error occurs
`<package id="Structuremap.Automocking" version="4.0.0.315" targetFramework="net461" />`

So:
1. I created a console app
2. added a Console.WriteLine("Helllo World");
3. Built and ran " nuget pack" with a default spec file.
     It worked, "pack"ing with old and new versions of nuget.exe
4. Add a NuGet reference to structuremap.automocking (version is irrelevant)
    This brings in structuremap and RhinoMocks as dependencies.
    Build and run: Works
5. NuGet pack fails with error.

It's worth noting that this is with _any_ version on the library, not just the most recent and is independent of the libraries dependencies.
       - If I remove the dependencies from the package, but not automock ref; it fails
       - Only when that specific line from packages.config is removed does the pack command work.

I can't see anything wrong with the downloaded packages, nor can I find another library to replicate this issue.

Hope this helps; my problem is that this issue is a blocker to me: This library is added as an imported dependency.

I'll play around and add to this if I can find anything else.....

**Comment by toddm** [comment] 2016-05-06 14:27
Thanks. It's always nice to get an exact way to reproduce the problem. I created a project, added structuremap.automocking, and then pack shows the error. I'll start debugging it to see if I can fix it.

**Comment by ghost** [comment] 2016-05-06 15:16
Have actually tried to debug ... but realised it's DNX now which I'm not conversant with. Bit of an intuitive leap!

**Comment by toddm** [comment] 2016-05-06 16:43
It appears to be the .NET packaging that throws the XML exception when reading the properties of the zip file. Still trying to work out the root cause, though. The packages might be bad but I don't know for sure yet.
I did find one workaround that could possibly help if you don't need particular versions. If I use v2.6.4.1 of structuremap.automocking, that package works fine. It depends on structuremap, though, that has the issue, but if I take a new version of that (v4.2.0.402), I can pack up my test project.
I'll keep on working on trying to fix it.

**Comment by toddm** [comment] 2016-05-06 18:02
The structuremap.automocking package was created by using paket.exe instead of NuGet.exe. The standard .NET zip package code is throwing the XML exception trying to read the package properties. There doesn't seem to be a NuGet bug here. It seems to be that the packages are bad.
I'd suggest you contact the package owner and suggest they pack using NuGet.exe instead.

**Comment by ghost** [comment] 2016-05-06 18:31
Thanks for your investigation. I'll raise it with author. I'll also raise it with the creators of paket.exe

##

**Comment by forki** [comment] 2016-05-09 15:57
@toddm can you please explain what exactly is wrong? The package looks right in Nuget package explorer and also installs fine.

**Comment by forki** [comment] 2016-05-09 16:04
This is the coreProp.psmdcp file:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:creator>[Jeremy Miller]</dc:creator>
  <dc:description>StructureMap AutoMocker for RhinoMocks</dc:description>
  <dc:identifier>structuremap.automocking</dc:identifier>
  <version>Some(4.0.0.315)</version>
  <keywords />
  <dc:title>structuremap.automocking</dc:title>
  <lastModifiedBy>paket</lastModifiedBy>
</Relationships>
```

looking into other packages I see "coreProperties" instead of "Relationships" nodes.

That looks indeed strange. I assume it's built with older paket.exe

**Comment by toddm** [comment] 2016-05-09 16:05
I'm not sure what is causing the error, but here is a way to test it.  I created a blank console app and tried this:
using System.IO.Packaging;

```
        using (Stream stream = new FileStream(@"C:\<path>\structuremap.automocking.4.0.0.315.nupkg", FileMode.Open))
        {
            Package package = Package.Open(stream);
            var properties = package.PackageProperties;
        }
```

It throws the exception when reading the PackageProperties.  Some of the earlier versions of the nupkg don't throw.

**Closed as completed** 2016-05-16 15:14 UTC
Labels: Type:Bug, Functionality:Pack
