### ISSUE TITLE
[vsfeedback] nuget package update reformats config files poorly

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#6465] opened 2018-01-19 22:49 UTC
It forces xml attributes for an element to all be on one line, making me have to scroll 300+ columns to the right to read the settings. It should leave that stuff alone and just touch the parts it is supposed to. 

It also adds encoding to the declaration if its missing. I don't think I need that either. 

Screenshot attached of some of its worse offenses.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/182303/nuget-package-update-reformats-config-files-poorly.html
VSTS ticketId: 551762_
_These are the original issue comments:_

Patricio Beltran Saldivar [MSFT] on ‎1‎/‎16‎/‎2018, 11:52 AM (3 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide a solution where we could repro this issue or some clear steps to get this issue? (e.g. file new project -&gt; do this -&gt; see the issue).  We look forward to hearing from you!</p>

Andrew Stanton on ‎1‎/‎16‎/‎2018, 09:22 PM (2 days ago): Wasn't there a screenshot of what it did to my config files attached?
Patricio Beltran Saldivar [MSFT] on ‎1‎/‎17‎/‎2018, 10:00 AM (2 days ago): <p>Yes, there was a screenshot of the config file. This is not a usual behavior, and the reason that I ask for some repro steps is so that I can understand what is causing that behavior and have more knowledge on what the problem is. Could you please provide with a sample solution or some steps for me to get a solution to reproduce this issue? Thanks!</p>
Andrew Stanton on ‎1‎/‎17‎/‎2018, 01:25 PM (2 days ago): <p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/temp/20893-database3.zip">database3.zip</a>  - this is an example solution with two projects - one class library and one console app. The console app refs the class library. Both have EnterpriseLibrary.Data 5.0 installed. The console app.config has a formatted wcf client endpoint and an app setting without a space before the closing bracket. </p><p>if you update the class library to use EL 6.0, nuget adds an assembly binding redirect in the app config. It also reformats the file adding a space before the closing bracket and collapsing the wcf client endpoint into a single line. With a simple example this may not seem so bad, but in a config file with 200+ lines the diff ends up looking like the one attached to the issue report.<br><br> A copy of the original app.config is in the console app as well.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by StingyJack** [comment] 2018-01-20 06:25
@karann-msft - on the dev community site, please unlock any issues you may have migrated here.  It stems potential discussion needlessly.

**Comment by karann-msft** [comment] 2018-01-21 00:34
@StingyJack this repo is a better fit for discussing NuGet related issues. This issue captures the discussion that has already happened, and the dev community item clearly links to this issue.

**Comment by StingyJack** [comment] 2018-01-21 20:57
@karann-msft - I'm not necessarily disagreeing that this may be the better place to get issues resolved, except that I'm not getting a better resolution rate here. That rate s anecdotal but probably not far from the truth, and I can at least read the font and almost read the punctuation here.

I'm still asking you to please unlock any issues of mine you may have locked there, and consider abstaining from that practice in general except in extreme circumstance. The only outcome possible (compared to resolving it and leaving it unlocked) is to create a negative customer experience.

**Comment by karann-msft** [comment] 2018-01-22 19:50
Moving the discussion back to Dev Community item.

**Closed as completed by karann-msft** 2018-01-22 19:50 UTC

**Comment by StingyJack** [comment] 2018-01-24 19:50
@karann-msft - i think you may have missed the point I was trying to make. 

GH does not prevent commenting after someone closes an issue, and that is great for everyone. When the communication is open, resolutions amenable to all parties can be reached at any point in time.

AnswerHub (devcomm) by default does not permit commenting after closing an issue, so a resolution amenable to only the person closing the issue is assured. Its bad for everyone (except those who value a "closed" status over resolving the issue, but its bad for them in the long run too).

I didn't ask to have the issue moved back, I asked you to please unlock the issues that you had locked on the dev comm site. There are literally no negative aspects for doing so, where there are negative aspects created by from halting discussion.

**Comment by karann-msft** [comment] 2018-02-01 18:04
@StingyJack nope I think you are missing my point which is we don't want to have the same conversation on two different threads. It is good for everyone to be required to follow just one thread and not have forked conversations to reach a logical conclusion.

To ensure that, only one of them can be active. Hence, I had closed the Dev Comm issue which pointed to this one and anyone interested in knowing the status, commenting, providing feedback could do so here. I don't see how that's bad for anyone. I ddidn't think it mattered where the issue was tracked, as long as it was, but clearly you have strong opinions about it :)

**Comment by StingyJack** [comment] 2018-02-02 04:42
Don't make the mistake of thinking Its good for everyone - its good for you. I wouldn't really want to manage multiple discussions either, but preventing any avenue of communication is going to be counter to the goal of exchanging ideas.

**Comment by StingyJack** [comment] 2018-06-03 11:51
@karann-msft @zhili1208   - since the devcomm issue has been closed, please reopen this one. 

I need to reiterate that this issue is a real time vampire. Consider the amount of work involved to edit or at undo 30 to 100 web and app.config adds and/or pending edits in a solution _every time you updated a nuget package_.   

And the UI workflow for undo of an app.config that is being added is **slow**, because it causes a reload of the project (5-8 seconds) and that switches the UI from the team explorer to the solution explorer.

**Comment by StingyJack** [comment] 2018-07-28 12:47
@rrelyea @karann-msft @zhili1208 - Please reopen this item as both it and the original devcomm issue are now closed as duplicate, referring to each other. 

This is a *daily* pain point and each instance can eat 10-30 minutes depending on solution size and how many app.configs nuget decided to add to projects not selected for a package update.  I could delete the newly added app.configs through the solution explorer and run `tfpt uu`, but there is no equivalent available for 2017. so the undoing of all the unwanted pending changes now becomes a tedious manual process.
