### ISSUE TITLE
When a package is removed (uninstalled or because of an upgrade) and it cannot be immediately removed the .deleteme file is being added to source control

### ISSUE THREAD

**Issue by CoolDadTx** [NuGet/Home#1720] opened 2015-11-12 18:13 UTC
I upgraded a package that required a restart in order to remove the old version. This triggered the creation of the .deleteme file in the packages folder. Even though the packages are not configured to be added to source control (TFS in this case) the .deleteme file is added to source control.  If you check in before restarting then the file would get checked into source control. If you restarted and then checked in you'd get a message about the .deleteme file missing.

This is with the latest version as of 12 Nov with VS 2015.

**Comment by yishaigalatzer** [comment] 2015-11-12 18:57
Thanks for reporting this. The root cause is in the code below, that add the file to source control, instead of just creating it directly on disk.

https://github.com/NuGet/NuGet.Client/blob/81717f6de319290fba103b4b5202ed5d13812397/src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSDeleteOnRestartManager.cs#L151

**Comment by yishaigalatzer** [comment] 2015-12-22 23:32
Fixed with https://github.com/NuGet/NuGet.Client/commit/08677f713378f9c0e02a2385d5f91763442db0c2

**Closed as completed** 2015-12-22 23:31 UTC
Labels: Type:Bug, help wanted
