### ISSUE TITLE
dotnet restore failure, nuget restore success with same configuration behind proxy

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7032] opened 2018-06-15 16:27 UTC
_From @Flern on June 14, 2018 23:22_

## Steps to reproduce
Get behind a proxy that requires user/password authentication.
Set up a docker container for builds, using the following during setup with nuget.exe:
```
## Run NuGet setup		  
echo "Configuring NuGet ...";
Start-Process -FilePath "$installPath\nuget.exe"
              -ArgumentList 'config',
			  '-set', 'http_proxy=http://proxy.server.com:8080', 
			  '-set', 'http_proxy.user=user',
			  '-set', 'http_proxy.password=abuser*' -NoNewWindow -Wait
```

Confirm encoded NuGet.config at %appdata%\Nuget\Nuget.config:

```
> type %appdata%\Nuget\NuGet.config
?<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <config>
    <add key="http_proxy" value="http://proxy.server.com:8080" />
    <add key="http_proxy.user" value="user" />
    <add key="http_proxy.password" 
value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAZUQz8OJXIUah4v8PkqaEQQAAAAACAAAAAAAQZgAAAAEAACAAAABHKIuBjUJLPlUvZARNog9ohCRPdIraNnbEdqfcIP/CLAAAAAAOgAAAAAIAACAAAACqbO74Odw1X24WeY/qoGKuJpsjbdt9kejEat7xn85FrBAAAACXPo23MMHiEvSNMJ7JiFwTQAAAAHEt6sywiOiiFxSjVk1qo87NmPR6nBO2Yg+dKB8l3Zqeaffd7e/sv+e8UFDydXu12chZt7jzkVBCaaLbkv1VaXI=" />
  </config>
</configuration>
```

Run dotnet restore from solution folder.
## Expected  behavior
Packages restore.

## Actual behavior
Restore fails:
```
  Restoring packages for C:\builds\buildName\SolutionDir\Target.Tests\Target.Tests.csproj...
C:\Program Files\dotnet\sdk\2.1.300\NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\builds\buildName\SolutionDir\SolutionFile.sln]
C:\Program Files\dotnet\sdk\2.1.300\NuGet.targets(114,5): error :   Response status code does not indicate success: 407 (Proxy Authentication Required). [C:\builds\buildName\SolutionDir\SolutionFile.sln]
```

Nuget restore successfully uses the proxy settings and restores the packages.

## Environment data
`dotnet --info` output:

```
C:\builds>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\builds>
```

_Copied from original issue: dotnet/cli#9497_

**Comment by nkolev92** [comment] 2018-06-15 17:54
Thanks for creating this issue @flern

This is a duplicate of https://github.com/NuGet/Home/issues/6978.

**Closed as completed by nkolev92** 2018-06-15 17:54 UTC
Labels: Resolution:Duplicate, Area:Authentication, Product:dotnet.exe

**Comment by Flern** [comment] 2018-06-15 18:04
@nkolev92 Thank you!

Sorry about the duplicate - thought it belonged in the `dotnet cli` world since nuget worked.  I'll watch the original issue for resolution.

**Comment by nkolev92** [comment] 2018-06-15 18:12
@Flern 

The nuget experience in the dotnet CLI is owned by the NuGet team itself. 
Most issues are NuGet related, although quite a bit can be handled by the CLI as well. 

This one looks like a core vs full framework issue however.

**Comment by lzocateli** [comment] 2018-08-16 03:13
I'm having the same problem, I use VSTS agent onpremises

PS D: \ UserApps \ AgentVSTS \ _work \ 2 \ s> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version: 2.1.300
 Commit: adab45b

Runtime Environment:
 OS Name: Windows
 OS Version: 6.1.7601
 OS Platform: Windows
 RID: win7-x64
 Base Path: C: \ Program Files \ dotnet \ sdk \ 2.1.300 \

Host (useful for support):
  Version: 2.1.2
  Commit: 811c3ce6c0

.NET Core SDKs installed:
  2.1.300 [C: \ Program Files \ dotnet \ sdk]
  2.1.400 [C: \ Program Files \ dotnet \ sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C: \ Program Files \ dotnet \ shared \ Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C: \ Program Files \ dotnet \ shared \ Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C: \ Program Files \ dotnet \ shared \ Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C: \ Program Files \ dotnet \ shared \ Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C: \ Program Files \ dotnet \ shared \ Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C: \ Program Files \ dotnet \ shared \ Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS D: \ UserApps \ AgentVSTS \ _work \ 2 \ s>

![image](https://user-images.githubusercontent.com/16601706/44185170-2302a480-a0e9-11e8-87a1-bbb7fd132321.png)
