### ISSUE TITLE
Need to determine API for getting "type: build" dependency information in MSBuild

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#3507] opened 2016-09-23 19:48 UTC
With the conversion of dependencies being specified in MSBuild <PackageReference> items, the marking "type: build" on a dependency has moved to `<PrivateAssets>All</PrivateAssets>`.

When publishing an app, it is important to exclude any "type: build" dependencies (and any dependencies that were solely brought in by "type: build" dependnecies) when building up the set of assemblies to publish.

We should determine what is the correct way for the Publish task to retrieve which dependencies are to be treated as "type: build" in the MSBuild project.

**Comment by jainaashish** [comment] 2017-10-17 17:29
Send email to CLI team to confirm if it's still a valid request?

**Comment by jainaashish** [comment] 2017-11-30 05:02
Dupe of https://github.com/NuGet/Home/issues/4125

**Closed as completed by jainaashish** 2017-11-30 05:02 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Feature
