### ISSUE TITLE
NuGet pack ignoring AssemblyInformationalVersion for netcoreapp3.1 targetframework library

### ISSUE THREAD

**Issue by Gearard** [NuGet/Home#9296] opened 2020-03-13 08:18 UTC
Remove the content above here and fill out details below.

## Details about Problem
Creating a NuGet package targeting  netcoreapp3.1 (to share some extensions for startup for aspnetcore) the nuget packaging is ignoring the versioning used in the project and default to 1.0.0.0 (and also complains about description and other properties not being set even though they are in the project file).

If I take the same project and target netstandard2.0 it properly uses my in-code defined AssemblyInformationalVersion

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe
NuGet version (x.x.x.xxx):
5.4.0.6315

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Grab a simple repo project attached here
[NugetVersioningIssue.zip](https://github.com/NuGet/Home/files/4328470/NugetVersioningIssue.zip)

2. Build project and note that the version # for all the files correctly uses the PipelineAssemblyVersionInfo.cs values for the versioning of the built files.

3. Pack them into nuget package:
nuget pack NugetVersioningIssue.csproj -OutputDirectory pack -Properties Configuration=Release -IncludeReferencedProjects

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)
NuGet Version: 5.4.0.6315
Attempting to build package from 'NugetVersioningIssue.csproj'.
MSBuild auto-detection: using msbuild version '16.6.0.15301' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'C:\Users\gboland\source\repos\NugetVersioningIssue\bin\Release\netcoreapp3.1'.
Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Add file 'C:\Users\gboland\source\repos\NugetVersioningIssue\bin\Release\netcoreapp3.1\NugetVersioningIssue.dll' to package as 'lib\netcoreapp3.1\NugetVersioningIssue.dll'
WARNING: NU5115: Description was not specified. Using 'Description'.
WARNING: NU5115: Author was not specified. Using 'gboland'.

Id: NugetVersioningIssue
Version: 1.0.0
Authors: gboland
Description: Description
Dependencies:

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'lib/netcoreapp3.1/NugetVersioningIssue.dll'.
Added file 'NugetVersioningIssue.nuspec'.
Added file 'package/services/metadata/core-properties/f42f1531000b472596732ad9aabc5f51.psmdcp'.

Successfully created package 'D:\Sources\SmartML\pack\NugetVersioningIssue.1.0.0.nupkg'.
WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
- Add a dependency group for .NETCoreApp3.1 to the nuspec

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by donnie-msft** [comment] 2020-03-16 18:46
I repro'd that the DLL versions were updated, but nupkg is always named with "1.0.0". @nkolev92 any thoughts on this behavior?

**Comment by nkolev92** [comment] 2020-03-16 19:04
If the project in question is PackageReference based, then NuGet.exe does not pack it properly. 
See https://github.com/NuGet/Home/issues/4491. 
I think this should be closed as a duplicate of #4491 

For PackageReference based project the recommendation is dotnet pack for SDK based projects and msbuild /t:pack for the other standard csproj PackageReference based projects.

Docs on that: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild

**Comment by Gearard** [comment] 2020-03-16 22:01
even if I use dotnet pack, it still has the same issue and ignores the project version.

Comand: dotnet pack --no-build -c Release -v detailed Common\ApiCore\SmartML.ApiCore\SmartML.ApiCore.csproj

result: SmartML.ApiCore.1.0.0.nupkg instead of SmartML.ApiCore.0.0.0-dev00000.nupkg

log file: 
[dotnetpacklog.txt](https://github.com/NuGet/Home/files/4340584/dotnetpacklog.txt)

**Comment by nkolev92** [comment] 2020-03-16 22:30
@Gearard 

The PackageReference based pack won't sniff assemblies anymore. 

The properties are read from MSBuild. 
The 2 values that are read there are PackageVersion and Version in that priority order.

If you set version in your project file it should be respected by both pack and build. 

We apologize because this isn't very well documented, but it was a necessary change as we transitioned from packages.config to PackageReference.

**Comment by nkolev92** [comment] 2020-03-16 22:32
Also note that AssemblyInformationalVersion is free text. 
So having pack interpret it as a version for the package was probably not the best idea.
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyinformationalversionattribute?view=netframework-4.8#remarks

**Comment by Gearard** [comment] 2020-03-16 23:11
I see. perhaps I'm not understanding something here - why does it work when I switch TargetFramework to netstandard2.0? THe project is still using PackageReference in that scenario too, no?

**Comment by nkolev92** [comment] 2020-03-16 23:18
In my tests, i don't find that to be the case.

**Comment by Gearard** [comment] 2020-03-17 00:05
On my machine, if I take that same project and modify the csproj to uncomment the other targetframework and comment out the netcoreapp3.1, and run the same nuget or dotnet pack commands, it uses the desired version number. I only see this when I have targetframework set to netcoreapp3.1 - everything else in the project is the same.

**Comment by nkolev92** [comment] 2020-03-17 00:21
Can you upload a clean project with that behavior?
How are you running pack?

**Comment by nkolev92** [comment] 2020-08-27 22:30
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.

**Closed as completed by nkolev92** 2020-08-27 22:30 UTC
Labels: Type:Bug, Functionality:Pack, WaitingForCustomer
