### ISSUE TITLE
Packages with deep content get partially unpacked and an incorrect error result of "Package Not Found"

### ISSUE THREAD

**Issue by zjrunner** [NuGet/Home#1727] opened 2015-11-13 07:04 UTC
**Nuget 3.2.1**
If the combination of the GlobalPackagesRoot and the contents of the package itself go beyond MAXPATH, nuget claims it can't find the package at all.

I spent way too long trying to figure out what was going on here because nuget says
"Unable to find version '1.0.0' of package 'LongPathGuts'."
even though it _did_ find it, downloaded it, and partially unpacked it before failing.  It led to way too much time poking at servers and access and fiddler.

**I'm ok with this failing with long paths, but there absolutely has to be a good error message here.**  Ideally -verbosity detailed would also give more information, but I'll leave that to another task.

*\* Note *\* my repro here uses a custom GlobalPackagesRoot, but that is not required, it was just the easiest way for me to add variability in path length to my test so I could get the same package to succeed and fail.  Deep packages will fail using the default GlobalPackagesRoot. I can provide the sample package listed below, but it is easy to make.

1) mkdir g:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2) set NUGET_PACKAGES=g:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
3) Create a package with a file at <packageRoot>\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxx
xxxxxxxxx\xxxxxxxxxxxxxxxxxx\xxxx\foo.txt
4) Host the package on a server/feed (so pulling it forces the use of GlobalPackagesRoot)
5) Run a restore to pull this package back down.
-- you will get the failure listed above
6) set NUGET_PACKAGES=g:\tmp
7) Run a restore to pull this package back down
-- you will get success

**Comment by yishaigalatzer** [comment] 2015-11-23 18:14
We are running out of time to fit this into 3.3, moving to 3.4

**Comment by joelverhagen** [comment] 2016-05-18 22:58
Is this a `project.json` restore or a `packages.config` restore?

I have attempted to reproduce this problem with the latest NuGet and I consistently got a correct failure:

```
Error downloading 'package.1.0.0' from 'http://localhost:23600/api/v2/package/package/1.0.0'.
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

**Comment by zjrunner** [comment] 2016-05-19 05:05
packages.config.  Yesterday I saw it give the right error on 'nuget install' but fail silently on 'nuget restore' (a 3.4 intermediate build.  I have not attempted it on 3.4RTM or above.)

**Comment by yishaigalatzer** [comment] 2016-05-19 05:09
Can you please use 3.4.4 ?

Get Outlook for Androidhttps://aka.ms/ghei36

On Wed, May 18, 2016 at 10:05 PM -0700, "Zack Runner" <notifications@github.com<mailto:notifications@github.com>> wrote:

packages.config. Yesterday I saw it give the right error on 'nuget install' but fail silently on 'nuget restore' (a 3.4 intermediate build. I have not attempted it on 3.4RTM or above.)

##

**Comment by nkolev92** [comment] 2017-10-17 23:44
Duplicate of https://github.com/NuGet/Home/issues/3324

**Closed as completed by nkolev92** 2017-10-17 23:44 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Bug, Area:ErrorHandling
