### ISSUE TITLE
Package restore ignores the repositorypath

### ISSUE THREAD

**Issue by JRRocha** [NuGet/Home#1346] opened 2015-09-05 00:09 UTC
NuGet is disregarding the repositorypath for my solution. We have multiple solutions that all should use the same repository path and so we've followed the instructions from
- https://docs.nuget.org/consume/nuget-config-settings
- https://docs.nuget.org/consume/Command-Line-Reference#Config%20Command

to update our NuGet.config file. It now looks like the following:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <config>
    <add key="repositorypath" value="..\blarg" />
  </config>
</configuration>
```

Our directory hierarchy is

```
    Master
      |
      HELOS
        |
        .nuget
        | |
        | NuGet.config
        |
        HELOS.API
        HELOS.API.sln
```

We _want_ to have

```
    Master
      |
      HELOS
      | |
      | .nuget
      | | |
      | | NuGet.config
      | |
      | HELOS.API
      | HELOS.API.sln
      |
      blarg
```

but we always get

```
    Master
      |
      HELOS
        |
        .nuget
        | |
        | NuGet.config
        |
        HELOS.API
        HELOS.API.sln
        packages
```

The steps I use are as follows:
1. Delete all packages directories from everywhere under Master
2. Open HELOS.sln
3. Right click the solution from the Solution Explorer and select Manage NuGet Packages for Solution
4. When the dialog opens it tells me that packages are needed, so I select Restore.
5. At this point it creates the Master\HELOS\packages directory rather than Master\blarg

We are using NuGet Package Manager   2.8.50926.663

**Comment by evil-shrike** [comment] 2015-09-07 09:46
@JRRocha , Isn't it the same thing as #1341?

**Comment by JRRocha** [comment] 2015-09-08 14:36
Hello Sergei,

I don't think so… while reading #1341 it seems to be complaining about an authentication error, that it's not able to connect to the NuGet source. They get a 401 error.

In my case, it connects just fine. It downloads just fine, but it always downloads to the 'default' package location rather than to the package location that I've specified.

Then again, it also looks like Evil-Shrike may be breaking basic defect logging and cramming more than one problem into one defect report.

John Rocha

**Comment by evil-shrike** [comment] 2015-09-08 14:48
@JRRocha Try to use the following syntax:

```
        <add key="repositoryPath" value="$\..\..\packages" />
```

**Comment by yishaigalatzer** [comment] 2015-09-08 19:35
I believe a relative path looks like ../blarg (it basically gets parsed as a URL).

We should update the docs to reflect that.

**Comment by csharpfritz** [comment] 2015-09-08 20:34
Confirmed - repositoryPath should use forward-slashes as it does make a URL.

**Comment by JRRocha** [comment] 2015-09-09 00:38
I started with the configuration file:
d:/tfs/Development/Master/HELOS/.nuget/NuGet.Config

that had the contents:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <config>
    <add key="repositorypath" value="..\blarg" />
  </config>
</configuration>

That did not work.

I changed the repositorypath value to the following:
1. ```
     ../blarg
   ```
2. ```
     $/Development/Master/blarg
   ```
3. ```
     $\Development\Master\blarg
   ```
4. ```
     $/Development/Master/packages
   ```
5. ```
     $\Development\Master\packages
   ```

None of these worked… the packages were always installed under the Solution directory at:
$/Develoment/Master/Helos/Packages

Is the NuGet.config cached? Or is it re-read each time "Manage Nu Get Packages for a Solution" is selected. I'm assuming it is re-read each time. If it is cached, can you please explain the test that should be done to ensure the new config is loaded?

Thank you.

John Rocha

From: Jeffrey T. Fritz [mailto:notifications@github.com]
Sent: Tuesday, September 08, 2015 1:34 PM
To: NuGet/Home
Cc: Rocha, John R
Subject: Re: [Home] Package restore ignores the repositorypath (#1346)

Confirmed - repositoryPath should use forward-slashes as it does make a URL.

—
Reply to this email directly or view it on GitHubhttps://github.com/NuGet/Home/issues/1346#issuecomment-138691436.

---

This E-mail message and any attachments are intended solely for the use of the addressee hereof and may contain information that is confidential, privileged and/or exempt from disclosure under applicable law.  Delivery of this message to any person other than the intended recipient shall not constitute a waiver of any right, privilege or exemption.  If you are not the intended recipient, please immediately notify the sender by reply E-mail and permanently delete this message from your system without reproducing or disclosing it to any third party.  While Ocwen Financial Corporation and its subsidiaries take reasonable precautions to prevent transmission of software viruses, we cannot guarantee the same and we therefore disclaim liability for any damage sustained by you or any third party as a result thereof

---

**Comment by yishaigalatzer** [comment] 2015-09-09 01:55
Not sure, but looks like repositorypath is not cased correctly P should be capitalized

Sent from my Windows Phone

**Comment by JRRocha** [comment] 2015-09-09 02:15
Documentation shows it as all lowercase.

Please see:

·         https://docs.nuget.org/consume/NuGet-Config-Settings (shows both)

·         https://docs.nuget.org/consume/nuget-config-file (shows lowercase)

However, I tried with captitals too:

D:\tfs\Development\Master\HELOS.nuget>..\nuget.exe config -Set repositoryPath=$\Development\Master\packages -ConfigFile NuGet.Config

For

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <config>
    <add key="repositoryPath" value="$\Development\Master\packages" />
  </config>
</configuration>

Gave a promising error!!!!

An error occurred whle trying to restore packages: TF10122: The path '$/Development/Master/HELOS/.nuget/$/Development/Master/packages/ repositories.config' contains a '$' at the beginning of a path component. Remove the '$' and try again.

That appears to be it. I changed this to:
    <add key="repositoryPath" value="..\..\packages" />
and it works!

huzzah! So it appears to be a documentation defect! Lower case p's in the examples, even though upper case P's are in the key names.

Thank you!

John Rocha

**Comment by JRRocha** [comment] 2015-09-09 02:17
Also… it appears the config file is cached.

I changed it to another directory, and it didn't register until I closed and then re-opened the visual studios solution.

John Rocha

From: Rocha, John R
Sent: Tuesday, September 08, 2015 7:16 PM
To: NuGet/Home; NuGet/Home
Cc: Rocha, John R
Subject: RE: [Home] Package restore ignores the repositorypath (#1346)

Documentation shows it as all lowercase.

Please see:

·         https://docs.nuget.org/consume/NuGet-Config-Settings (shows both)

·         https://docs.nuget.org/consume/nuget-config-file (shows lowercase)

However, I tried with captitals too:

D:\tfs\Development\Master\HELOS.nuget>..\nuget.exe config -Set repositoryPath=$\Development\Master\packages -ConfigFile NuGet.Config

For

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <config>
    <add key="repositoryPath" value="$\Development\Master\packages" />
  </config>
</configuration>

Gave a promising error!!!!

An error occurred whle trying to restore packages: TF10122: The path '$/Development/Master/HELOS/.nuget/$/Development/Master/packages/ repositories.config' contains a '$' at the beginning of a path component. Remove the '$' and try again.

That appears to be it. I changed this to:
    <add key="repositoryPath" value="..\..\packages" />
and it works!

huzzah! So it appears to be a documentation defect! Lower case p's in the examples, even though upper case P's are in the key names.

Thank you!

John Rocha

**Comment by csharpfritz** [comment] 2015-09-09 02:27
The key and sample code on the config settings page reference
"repositoryPath"

I will correct the other config page.

**Comment by yishaigalatzer** [comment] 2015-09-09 02:31
The docs are right because I just fixed them ☺

**Comment by yishaigalatzer** [comment] 2015-09-09 02:35
Closing as this seems resolved, and nothing else to do here.

Thanks for reporting this, and following through

**Closed as completed** 2015-09-09 02:35 UTC
Labels: Type:Docs

**Comment by JRRocha** [comment] 2015-09-09 14:14
Thank you for your patience and help!

Cheers!

John Rocha

**Comment by Rombersoft** [comment] 2022-03-16 11:45
Debian 11. 
I want to change repositoryPath to absolute path but it also does not work because packages restore to /home/destructor/.nuget/NuGet/packages:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <config>
    <add key="repositoryPath" value="/media/destructor/Data/Projects/Packages" />
  </config>
</configuration>

```
