### ISSUE TITLE
Cannot install NuGet in Dev and release-3.5.0-beta2 branch.

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#2892] opened 2016-06-03 01:08 UTC
NuGet version: 
dev branch, build number: 1403, 1400, 1395, 1391, 1388, 1387, 1385,1384, 1365
release-3.5.0-beta2 branch, build number: 1399, 1394, 1392, 1390, 1386, 1383, 1381
not repro in other branch and build number.

Repro steps:
Install NuGet in dev and release-3.5.0-beta2 branch meet error.
![install](https://cloud.githubusercontent.com/assets/12129698/15765742/9b2b2fa2-296a-11e6-9e1a-0cb434024cc7.png)

**Comment by rrelyea** [comment] 2016-06-03 16:13
@alpaix - is this what you are already addressing? If not, let's figure out who should run with it asap.

**Comment by alpaix** [comment] 2016-06-03 23:59
The issue was caused by a bug in VSIX signing script trying to update a manifest with a build number.
I fixed the `CleaningAndSigningVsix.ps1` script in our TFS repo.
Validated the issue was fixed in
dev - build 1420
beta2 - build 1425

**Closed as completed by alpaix** 2016-06-03 23:59 UTC
Labels: Priority:1, Product:VS.Client, Type:Bug
