### ISSUE TITLE
--interactive support for dotnet remove package

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#7727] opened 2019-01-23 23:28 UTC
These 2 commands in CLI are just a redirect command to nuget.xplat.

If there is a project used a [msbuild sdk](https://github.com/Microsoft/MSBuildSdks) that is in a private nuget feed. These 2 commands will fail. At the same time, _dotnet add package_ with _--interactive_ will succeed. So doing the similar work for _dotnet add package_ should resolve the problem.

```
info : Removing PackageReference for package 'testclasslib' from project '/Users/williamli/Documents/restoreauthproject/restoreauthproject.csproj'.
error: The SDK 'wul.testmsbuildsdk/2.0.1' specified could not be found.  /Users/williamli/Documents/restoreauthproject/restoreauthproject.csproj

```
csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="wul.testmsbuildsdk" Version="2.0.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by wli3** [comment] 2019-01-23 23:29
@rrelyea @nkolev92

**Comment by nkolev92** [comment] 2019-01-23 23:32
The list part is duplicate of https://github.com/NuGet/Home/issues/7605. 

The NuGet side fix is done, but not the CLI one. 

I can do the remove package reference one. 

@wli3 
Do you plan on addressing the CLI side of these or do you want us to do it?

**Comment by nkolev92** [comment] 2019-01-23 23:37
@wli3 

Also in the title you talk about list and remove, but in the issue you talk about MSBUIlD SDKs as well. 

The MSBuild SDKs scenario has been addressed in https://github.com/NuGet/NuGet.Client/commit/62916a48fe61fc7d94c2f436c7d4569878705dd4#diff-2cd243ce1cd32fce987422c201afe90d

**Comment by wli3** [comment] 2019-01-24 02:03
> #7605 and relation to msbuild sdk

I don't think it is the same as NuGet/NuGet.Client@62916a4#diff-2cd243ce1cd32fce987422c201afe90d. 

This issue more tricky. For #7605, if a feed is behind private feed. At least it can pass msbuild evaluation phase. But if there is an msbuild sdk behind private feed. Even the evaluation will fail. I am not sure the implementation of nuget auth. The solution of 7605 may work for msbuild sdk as well, but please double check this scenario.

> Do you plan on addressing the CLI side of these or do you want us to do it?

I am not familiar with the redirect to nuget code in CLI. It would be nice for you to also address the code on CLI side.

**Comment by nkolev92** [comment] 2019-01-24 02:23
@wli3 

The fix that I did for #7605 is already in the sdk resolver.
The NuGet plumbing is complete there. The rest is the msbuild sdk resolver magic, which we don't really understand.

**Comment by nkolev92** [comment] 2019-01-30 19:54
@wli3
The scenario wasn't clear to me when I commented last time. 

I will do the change on NuGet side, and I'll try to work with you to validate it correctly. 

I assume the remove package reference addition can target 2.1.6xx, while the dotnet list package one can target 2.2.2xx?

**Comment by wli3** [comment] 2019-01-30 21:21
@nkolev92 2.1.6xx and 2.2.2xx is not necessary since "--interactive in most commands" are in 3.0.1xx. But is also ok to add it.

**Comment by nkolev92** [comment] 2019-01-30 22:31
Both PRs are out.

https://github.com/dotnet/cli/pull/10674

@wli3 We should clarify with the PMs + Rob if the the RemovePackageReference --interactive is something that makes sense.

**Closed as completed** 2019-02-06 07:18 UTC
Labels: Type:Bug, Product:NuGet.exe, Platform:Xplat, Area:Authentication, Product:dotnet.exe, Partner:CLI-SDK
