### ISSUE TITLE
nuget.exe, install-package, install-module: newtonsoft being used by another process

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9652] opened 2020-06-05 21:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1064525/nugetexe-install-package-install-module-newtonsoft.html)._

---
[regression] [worked-in:16.6.0]
The process cannot access the file Newtonsoft.Json.dll because it is being used by another process.

* VS2019 16.6.1 - Manage Nuget Packages (Install button), Package Manager Console (Install-Package)
* Powershell 7.1 command line: Install-Module

---
#### Visual Studio Feedback System on 6/3/2020, 11:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment] 2020-07-20 20:52
From https://developercommunity.visualstudio.com/content/problem/1064525/nugetexe-install-package-install-module-newtonsoft.html

> Resolved: the root cause was the Anti-Virus scanning of Dlls in the nuget packages.

Closing as external/not a bug.

**Closed as completed by nkolev92** 2020-07-20 20:52 UTC
Labels: Resolution:NotABug
