### ISSUE TITLE
[Test Failure] PMC get different results between ‘update-package [PackageID]’ and ‘update-package’ for prerelease package

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3948] opened 2016-11-15 09:09 UTC
**Repro Steps:**
1.	New a Visual C#->iOS->iPhone->Blank App template. 
2.	Open ‘Manage NuGet Packages…’ and click ‘Browse’ tab.
3.	Search ‘CrossBase.Platform.IOS’ in the filter and check ‘Include prerelease’.
4.	Install ‘CrossBase.Platform.IOS 0.0.2-test1’.
5.	Open PMC, type ‘update-package CrossBase.Platform.IOS’ and press enter, PMC said no package updates are available.
6.	Type ‘update-package’ in PMC and press enter.

**Expected Result:**
Get the same result with command ‘update-package CrossBase.Platform.IOS’.

**Actual Result:**
‘CrossBase.Platform.IOS’ had been updated to ‘0.0.3-test1’ successfully as below screenshot.
![iphoneblank](https://cloud.githubusercontent.com/assets/20632625/20340663/af6ff746-ac1d-11e6-9c91-0d92f9a3c6a4.PNG)

**Note:**
1.	It was found on D15PreRel 25914.00 (NuGet Client 4.0.0-RC-2065). 
2.	Repro on D15PreRel 25914.00 + NuGet Client 4.0.0-RC2-2080.
3.	Repro on Dev14 MU3.5 25431.01 (NuGet 3.4.4.1321).
4.	Repro on Dev14 MU3.5 25431.01+ NuGet 3.5.0-RTM-1938.
5.	Repro on Dev14 MU3.5 25431.01+ NuGet 3.6.0-Beta1-1954.

**Log:**
PM> update-package CrossBase.Platform.IOS

Attempting to gather dependency information for multiple packages with respect to project 'iPhoneBlank', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 301.68 ms
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Resolution was successful but resulted in no action
There are no new updates available.
No package updates are available from the current package source for project 'iPhoneBlank'.
Executing nuget actions took 208.34 ms
Time Elapsed: 00:00:00.5703735
PM> update-package

Attempting to gather dependency information for multiple packages with respect to project 'iPhoneBlank', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 268.2 ms
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Retrieving package 'CrossBase.Platform.IOS 0.0.3-test1' from 'nuget.org'.
Removed package 'CrossBase.Platform.IOS 0.0.2-test1' from 'packages.config'
Successfully uninstalled 'CrossBase.Platform.IOS 0.0.2-test1' from iPhoneBlank
Adding package 'CrossBase.Platform.IOS.0.0.3-test1' to folder 'c:\users\mdtestau\documents\visual studio 2017\Projects\iPhoneBlank\packages'
Added package 'CrossBase.Platform.IOS.0.0.3-test1' to folder 'c:\users\mdtestau\documents\visual studio 2017\Projects\iPhoneBlank\packages'
Added package 'CrossBase.Platform.IOS.0.0.3-test1' to 'packages.config'
Successfully installed 'CrossBase.Platform.IOS 0.0.3-test1' to iPhoneBlank
Removing package 'CrossBase.Platform.IOS 0.0.2-test1' from folder 'c:\users\mdtestau\documents\visual studio 2017\Projects\iPhoneBlank\packages'
Removed package 'CrossBase.Platform.IOS 0.0.2-test1' from folder 'c:\users\mdtestau\documents\visual studio 2017\Projects\iPhoneBlank\packages'
Executing nuget actions took 373.19 ms
Time Elapsed: 00:00:00.6533264

**Comment by rrelyea** [comment] 2016-11-16 22:29
Duplicate of #3827

**Closed as completed by rrelyea** 2016-11-16 22:29 UTC
Labels: Resolution:Duplicate
