### ISSUE TITLE
RestoreUseStaticGraphEvaluation=true causes error NU1100

### ISSUE THREAD

**Issue by znakeeye** [NuGet/Home#12895] opened 2023-09-21 14:49 UTC
### NuGet Product Used

dotnet.exe

### Product Version

.NET STDK 7.0.101, Nuget 6.7.0

### Impact

None

### Repro Steps & Context

In `Directory.Build.props` we wanted to enable static graph `MSBuild` evaluation:
```xml
<Project>
  <ItemGroup>
    <PackageReference Include="Foo.Bar.Sdk" ExcludeAssets="runtime" />
  </ItemGroup>
  <PropertyGroup>
    <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
  </PropertyGroup>
</Project>
```

Our pipeline in `Azure DevOps` then failed, unable to restore our globally referenced package (above):
>error NU1100: Unable to resolve 'Foo.Bar.Sdk (>= 1.2.3)' for 'net6.0/win-x64'

This is the relevant part of `pipeline.yml`:
```yml
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 6.7.0'
  inputs:
    versionSpec: 6.7.0

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: 'src/**/*.csproj'
    feedsToUse: config
    nugetConfigPath: 'src/NuGet.Config'
    restoreArguments: '-r win-x64'
```

Our pipeline works when we don't set `RestoreUseStaticGraphEvaluation`, so it seems there is an issue with this specific setting.

Also not sure if this error comes from `dotnet.exe` or that `DotNetCoreCLI@2` task...

### Update
It should be noted that we have these settings enabled:
```
<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
```

### Verbose Logs

```shell
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at System.Collections.Generic.Dictionary`2.get_Item(TKey key) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.LockFileBuilder.GetLibraryDependenciesForCentralTransitiveDependencies(RestoreTargetGraph targetGraph, TargetFrameworkInformation targetFrameworkInformation, Boolean centralPackageTransitivePinningEnabled)+MoveNext() [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.LockFileBuilder.AddCentralTransitiveDependencyGroupsForPackageReference(PackageSpec project, LockFile lockFile, IEnumerable`1 targetGraphs) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.LockFileBuilder.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable`1 targetGraphs, IReadOnlyList`1 localRepositories, RemoteWalkContext context, LockFileBuilderCache lockFileBuilderCache) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreCommand.BuildAssetsFile(LockFile existingLockFile, PackageSpec project, IEnumerable`1 graphs, IReadOnlyList`1 localRepositories, RemoteWalkContext contextForProject) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, IRestoreProgressReporter progressReporter, CancellationToken token) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreArgs, CancellationToken token) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken) [E:\_work\1\s\src\Foo.csproj]
C:\Program Files\dotnet\sdk\7.0.101\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.RestoreAsync(String entryProjectFilePath, IDictionary`2 globalProperties, IReadOnlyDictionary`2 options) [E:\_work\1\s\src\Foo.csproj]
       Done executing task "RestoreTaskEx" -- FAILED.
```

**Comment by jeffkl** [comment] 2023-09-21 15:24
@znakeeye I believe you're hitting a known issue which is fixed in the next release: https://github.com/NuGet/Home/issues/12464

Are you able to try the latest Visual Studio 2022 17.8 Preview to see if that fixes the issue? https://visualstudio.microsoft.com/vs/preview/#download-preview

**Comment by znakeeye** [comment] 2023-09-21 15:32
The pipeline doesn't use `VS` at all. It's `MsBuild` all the way, possibly `dotnet.exe` here and there.

However, when I run `VS 17.5.2` on my machine it works.

**Comment by jeffkl** [comment] 2023-09-23 03:29
@znakeeye disabling transitive pinning by setting `CentralPackageTransitivePinningEnabled` to `false` is the only workaround at the moment until the next release.  I think if you update Visual Studio to 17.7.x you'll see it happen locally and when 17.8 releases later this year it will contain the fix.

**Comment by jeffkl** [comment] 2023-09-23 03:29
Resolving as duplicate of https://github.com/NuGet/Home/issues/12464

**Closed as not planned by jeffkl** 2023-09-23 03:29 UTC
Labels: Resolution:Duplicate, Type:Bug
