### ISSUE TITLE
Provide a target to restore nuget packages without projects

### ISSUE THREAD

**Issue by ramarag** [NuGet/Home#4762] opened 2017-03-06 22:10 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget msbuild targets

NuGet version (x.x.x.xxx):4.0.0-rtm-2323

Worked before? If so, with which NuGet version: Never

## Detailed repro steps so we can see the same problem

To restore a single nuget package from msbuild a project needs to be created. 
We need a simple target to call with just the nuget package name and version and way to probe/provide nuget.targets to restore the package. So that we can stop generating temp projects and call restore on them like https://github.com/dotnet/sdk/blob/59ae491180ba64391c8d64c5b1e262ff8085fa78/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.ComposeCache.targets#L287

cc @emgarten

**Comment by ramarag** [comment] 2017-03-06 22:11
cc @gkhanna79 @eerhardt

**Comment by emgarten** [comment] 2017-03-06 22:57
@ramarag can you provide more details on your scenario?

Restore does all of the following, which outputs would you need?
1. project.assets.json
1. Packages in the user packages folder
1. targets/props files
1. Dependency packages

Restore must have target framework to walk dependencies, currently this comes from the project. Are you expecting to pass this in, or are you expecting this to download every possible combination of dependencies?

**Comment by ramarag** [comment] 2017-03-07 03:02
Yes for all [ except may be the targets/props files- but keep it in if it is not too much trouble]
it is of course reasonable to expect the  additional info like tfm to be passed in as properties.

**Comment by emgarten** [comment] 2017-10-18 03:05
Duplicate of https://github.com/NuGet/Home/issues/5919

**Closed as completed by emgarten** 2017-10-18 03:05 UTC
Labels: Resolution:Duplicate, Functionality:Restore
