### ISSUE TITLE
[Pack] The building still happened when running the command “dotnet pack” with option “--no-build” in .NET SDK 9.0

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13667] opened 2024-08-01 09:18 UTC
### NuGet Product Used

dotnet.exe

### Product Version

dotnet SDK 9.0.100-preview.6.24328.19

### Worked before?

It’s a regression since it doesn’t repro on .NET SDK 8.0, but it can repro on .NET SDK 9.0. 

### Impact

It bothers me. A fix would be nice

#### Repro Steps:    

1. Open VS and create a C# Class Library (.NET 9.0) project named package1. 

2. Build solution and make sure compilation succeeds.  

3. Open “Developer Command Prompt”, cd to Package1 project path and execute below command:
   ` dotnet pack package1.csproj --no-build `

#### Expected:    

The package was created without building & restoring info in Developer Command Prompt. (as the docs [dotnet pack](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack) said)  

#### Actual: 

The building still happened as below:
![image](https://github.com/user-attachments/assets/829c83b4-b284-4d1d-9d08-95aab47aeccb)
#### Note:     
The repro rate is 100%.

**Comment by nkolev92** [comment] 2024-08-05 20:29
Build is not referring to the target here, but it's referring to the "build" of the "pack" target. 

The .NET SDK change their logging and it's overwriting whatever restore/pack log. 

Can you try running it with /v:d?

**Comment by CiciLi1** [comment] 2024-08-06 02:34
> Build is not referring to the target here, but it's referring to the "build" of the "pack" target.
> 
> The .NET SDK change their logging and it's overwriting whatever restore/pack log.
> 
> Can you try running it with /v:d?

Hi @nkolev92, the result is the same when using "/v:d", as shown below:
![image](https://github.com/user-attachments/assets/57d40abc-6a83-486c-8b2b-3e599d93ca96)

**Comment by jeffkl** [comment] 2024-08-06 03:52
MSBuild logs the line "Build succeeded: at the end of any build episode regardless of the actual target: https://github.com/dotnet/msbuild/blob/7f6bc0409a19cb2d39950143343ea25677e029a5/src/Utilities/Resources/Strings.resx#L287

Running `dotnet pack` is the same as running `dotnet msbuild /Target:Build;Pack` and adding `--no-build` just makes the CLI not include the `Build` target.  Closing as by design.

**Closed as not planned by jeffkl** 2024-08-06 03:52 UTC
Labels: Type:Bug, Resolution:ByDesign, Functionality:Pack, Product:dotnet.exe, RegressionDuringThisVersion, Found:ManualTests
