### ISSUE TITLE
Error List pops up after use of package manager, even without messages and with option to show on build disabled

### ISSUE THREAD

**Issue by DanteGagne** [NuGet/Home#8691] opened 2019-10-14 17:33 UTC
I did a simple repro…

1.	New WPF project
2.	Close Error List
3.	Uncheck “Always show Error List if build finishes with errors” under Projects and Solutions > General
4.	Manage NuGet Packages
5.	Switch to Browse
6.	Select a package and hit Install (I did it with Newtonsoft.Json)
7.	Accept any interim dialogs

Expected: Error List is still closed 
Current: Error List comes up with no messages in it. I would forgive it if there was some error, but since nothing technically went wrong and the user says they don’t want it… why should it post?

This was the root cause of this item: https://developercommunity.visualstudio.com/idea/769040/error-list-window-is-always-shown.html

**Comment by zivkan** [comment] 2019-10-17 20:15
Closing as duplicate of #8190.

**Closed as completed** 2019-10-17 20:16 UTC
Labels: Resolution:Duplicate
