### ISSUE TITLE
Command to list all the package dependencies for a project

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4677] opened 2017-02-22 19:50 UTC
If I have a project with following dependencies

Project: Foo
- DepencencyPackageA
- DepencencyPackageB
- DepencencyPackageC

I should have a command like 

> nuget.exe dependencies Foo.csproj

**Comment by mishra14** [comment] 2017-02-26 07:20
@anangaur : We have a plan to add a `dotnet list package` command in dotnet cli. We have a bug tracking it at https://github.com/NuGet/Home/issues/4102

**Comment by nkolev92** [comment] 2017-02-27 18:13
@mishra14 But that's for packageref only?
I would assume if we were to do this, it'd need to be done package.config & project.json.

A feature like this would also be functionally equivalent to https://github.com/NuGet/Home/issues/1264

**Comment by emgarten** [comment] 2017-11-09 18:12
@mishra14 has a prototype of this

**Comment by mishra14** [comment] 2017-11-12 06:29
closing this as a dupe of #4102.

**Closed as completed by mishra14** 2017-11-12 06:29 UTC
Labels: Resolution:Duplicate, Type:Feature, Product:NuGet.exe
