### ISSUE TITLE
Monikers for old/new project types

### ISSUE THREAD

**Issue by johnbraden** [NuGet/Home#3015] opened 2016-06-22 08:33 UTC
When you are a library author for ASP.NET web applications you need a way to know if a package is installed in a traditional ASP.NET project (using System.Web.dll) or in a new project (with dependency Microsoft.AspNetCore). Assume our code looks like this:

<pre>
#if net451
    // This code fails in traditional projects (System.Web.dll)
    Microsoft.AspNetCore.Http.HttpContext context = this.HttpContext;
#else
    System.Web.HttpContextBase context = this.HttpContext;
#endif
</pre>

The NuGet package now contains two libraries, one for traditional one for new projects.

<pre>
package
    lib
        net45
             library.dll  // old projects
        net451
             library.dll  // new projects
</pre>

A traditional ASP.NET project (running on .NET 4.5.1+) installs the net451 dll which is for new project types. So the library expects Microsoft.AspNetCore.Http.HttpContext while the ASP.NET application uses System.Web.HttpContextBase. As a library (resp. package) author I need to know if the installing project runs with System.Web.dll (traditional) or with Microsoft.AspNetCore.dll (new). This is not possible with a single net451 TFM. In the past DNX based projects we had a separate moniker (DNX451):

<pre>
#if dnx451
    // Code for new projects
    Microsoft.AspNetCore.Http.HttpContext context = this.HttpContext;
#else
   // Code for traditional projects (e.g. net451)
    System.Web.HttpContextBase context = this.HttpContext;
#endif
</pre>

But since CLI comes up there is no such TFM to prevent System.Web.dll based projects to install the net451 dlIs. Is there any way to prevent this?

**Comment by rrelyea** [comment] 2016-06-22 16:44
Joel - can you please help?

**Comment by joelverhagen** [comment] 2016-06-22 17:42
Hey @johnbraden, this is an issue bigger than TFMs actually. Please take a look at this open issue on the ASP.NET GitHub:
https://github.com/aspnet/Home/issues/1349

It seems like the best recommendation currently is to release two packages, one for System.Web.dll based projects and other for AspNetCore.

**Comment by johnbraden** [comment] 2016-06-22 19:50
Thank you for this https://github.com/aspnet/Home/issues/1349 link. I searched but didn't found it.It's good to see that the ASP.NET team discusses the issue. In our case an additional moniker would be sufficient and a second package maybe confuses users. But we have to wait for recommendations. Btw., last week I posted this to the CLI team, but they did not understand the problem.

**Comment by joelverhagen** [comment] 2016-06-23 16:24
Alright, glad this explanation makes sense. If you have additional questions related to this particular scenario, feel free to respond to that issue with your own details. In the mean time, I will close this issue as a duplicate of the ASP.NET issue.

**Closed as completed by joelverhagen** 2016-06-23 16:24 UTC
Labels: Resolution:Duplicate, Resolution:External
