### ISSUE TITLE
provide dynamic feed links in one application

### ISSUE THREAD

**Issue by dhinesh333** [NuGet/Home#4447] opened 2017-01-31 06:26 UTC
We are working in private repository for our own private nuget packages. We are in a position to change the nuget feed for every customer. But nuget packages are located in a location which is specified in Web.Config.
`    public static void MapNugetRoutes(RouteCollection routes)
            {
                var factory = new DataServiceHostFactory();
                var serviceRoute = new ServiceRoute("nuget/packages/getpackages/{platform}", factory, typeof(Packages));
                serviceRoute.Defaults = new RouteValueDictionary { { "serviceType", "odata" } };
                serviceRoute.Constraints = new RouteValueDictionary { { "serviceType", "odata" } };
                routes.Add("nuget", serviceRoute);
}

&lt;appSettings&gt;
    &lt;add key="requireApiKey" value="true" /&gt;
    &lt;add key="apiKey" value="" /&gt;
    &lt;add key="packagesPath" value="~/NugetPackages/" /&gt;
    &lt;add key="enableSimpleMembership" value="false" /&gt;
    &lt;add key="" /&gt;
  &lt;/appSettings&gt;
`

i need to access the repositary privately , like there are several folders inside that above location, i need dynamically access that folders NugetPackages/folder1, NugetPackages/folder2 like this, Is it possible?
Is their any possible ways to provide dynamic feed links in one application 

My hosted packages structure Like This,

<img width="338" alt="folders" src="https://cloud.githubusercontent.com/assets/25263491/22290374/6111b810-e326-11e6-8cc8-f2ef11b8c733.PNG">

How can i provide dynamic feed links to host separate versions,
URL structure  like,
http://mydomain/packages/v1 - to host only version 1.0 
http://mydomain/packages/v2 - to host only version 2.0
http://mydomain/packages/v3  - to host only version 3.0

I have solved it now by creating sub applications for each url links , but i need make it dynamic .
All need to be done in one application.

If anyone know what can i do to achieve this ?

**Comment by zhili1208** [comment] 2017-11-10 00:11
close it as dupe of https://github.com/NuGet/NuGetGallery/issues/4983

**Closed as completed by zhili1208** 2017-11-10 00:11 UTC
Labels: Resolution:Duplicate
