### ISSUE TITLE
[Cross-platform Sign Verify] Unexpected errors about a package from nuget.org source occur after restoring Class Library (.Net Core) project 

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#10332] opened 2020-11-30 02:41 UTC
## Details about Problem

NuGet version: NuGet Client Dev\5.9.0.6972 
VS Version: Main\30726.31  
OS Version: Windows-10-Enterprise-19h2 

Installation:  

1.Install VS main\30726.31: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4257754&view=ms.vss-build-web.run-extensions-tab  

 
## Detailed repro steps 

1. Create a C# Class Library (.NET 5.0) package, make and update .nuspec file for the package with command “nuget spec”. 
2. Pack the package with command “nuget pack”, create a new test certificate:  `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -GenerateCerFile`. 
3. Sign the package: `NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>` . 
4. Create a project, add package reference in the .csproj file  

```
<ItemGroup>  

    <PackageReference Include="<packageName>" Version="<packageVersion>" />  

 </ItemGroup>  
```

 5. Add the feed (path contains package signed in step2), set required mode in nuget.config file with trusted signers list:  

```
<packageSources>  

      <add key="<anyname>" value="<signed package parent folder>" />  

   </packageSources>  

  <config>  

    <add key="signatureValidationMode" value="require" />  

  </config>  

  <trustedSigners>  

     <author name="JamieZhang">          

         <certificate fingerprint="AAAAA" hashAlgorithm="SHA256" allowUntrustedRoot="false" />  

     </author>  

  </trustedSigners>
```
6. Clear the cache:  `<patchedSDKPath>.\dotnet.exe nuget locals all –clear`. 
7. Delete the <projectPath>\obj folder if there is any.  
8. Go inside the project folder, verify the package by running restore:   `<patchedSDKPath>.\dotnet.exe restore <projectpath>/<projectname>.csproj` . 

## Expected

Only warning NU3027: The signature should be timestamped to enable long-term signature validity after the certificate has expired appear.

## Actual 

Unexpected errors occurred as below screenshot. 
![image](https://user-images.githubusercontent.com/71433406/100561679-78801100-32f4-11eb-8a79-67677508e9ef.png)

![image](https://user-images.githubusercontent.com/71433406/100561694-8170e280-32f4-11eb-8661-73415265b924.png)

![image](https://user-images.githubusercontent.com/71433406/100561712-8afa4a80-32f4-11eb-98d1-5d720b4de60c.png)

**Comment by nkolev92** [comment] 2020-11-30 23:22
Sounds like we have a test case problem. 

cc @heng-liu @kartheekp-ms.

@v-luzh The SDK doesn't ship with all the targeting packs, and that'd normally be downloaded through nuget.org if it doesn't ship with it.

If you add nuget.org to the sources, that'd do it.
I know that messes with the trusted signers, so consider adding Microsoft as an approved signer.

**Comment by v-luzh** [comment] 2020-12-02 08:08
Hey @nkolev92, I still got the error NU3034 on Linux as below after adding "nuget.org" to the sources and "Microsoft" as a trusted signer. And this issue didn't repro when we did the Onboarding Test of the Cross-Platform Signing Verification Test on Dev\5.8.0.6848. 

![image](https://user-images.githubusercontent.com/20632625/100845246-e6286a80-34b7-11eb-90a7-1e04b71b10ba.png)

**Comment by nkolev92** [comment] 2020-12-02 22:30
@v-luzh Can you please paste the config? 

Trusted signers are case sensitive.

**Comment by kartheekp-ms** [comment] 2020-12-02 22:57
I think we don't need `Patched SDK` any more for testing because `net5` is GA now. @heng-liu - correct me if my understanding is incorrect.

Microsoft certificate that was being used to sign packages was close to expiring, the certificate was rotated: https://devblogs.microsoft.com/nuget/microsoft-author-signing-certificate-update/

@v-luzh - Please try the work around suggested in the above link and let us know the feedback.

**Comment by v-luzh** [comment] 2020-12-03 02:43
@nkolev92 @kartheekp-ms, yes, the issue is fixed after using the workaround suggested in the above link. So, do we need to update all the test case of Cross-Platform Signing Verification Test or wait for the SDK shipped with all the targeting packs?

**Comment by heng-liu** [comment] 2020-12-03 17:57
Hi @kartheekp-ms @v-luzh , the difference between testing with patched SDK and testing with latest SDK is if we're testing against latest NuGet change or not. 
If we use patched SDK, it's testing against the NuGet code we are going to insert.
If we use latest SDK, it's testing against the NuGet code which we've already inserted into dotnet. So in this way, we could only discover issues after insertion.
So I think testing against patched SDK reflects the latest change and we could discover issues earlier.

**Comment by nkolev92** [comment] 2020-12-07 21:58
Triage: 
@heng-liu Can you please make sure the test-case is updated as needed.

**Comment by heng-liu** [comment] 2021-02-18 06:02
Sorry for the late update! All cross-platform verify test cases are updated. FYI @v-luzh 

Here is one example:

 Add the feed(path contains the signed package),  set required mode in nuget.config file with trusted signers list:
**(If your project targets to net5.0/netstandard2.1, you need to add nuget.org as another feed as well. In this case, you have to make sure the package for testing doesn't exist on nuget.org, so the package for testing could only be restore from the folder)**
   ```
<packageSources>
      <add key="<anyname>" value="<signed package parent folder>" />
      <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
   </packageSources>
   <config>
    <add key="signatureValidationMode" value="require" />
   </config>
  <trustedSigners>
     <author name="JamieZhang">       
         <certificate fingerprint="AAAAA" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
     </author>
  </trustedSigners>
```

**Comment by heng-liu** [comment] 2021-02-18 06:03
Closed as not a bug. Update the test instructions.

**Closed as completed by heng-liu** 2021-02-18 06:03 UTC
Labels: Priority:2, Functionality:Signing, Type:Test, Found:ManualTests
