### ISSUE TITLE
Pack icon file in `dotnet.exe pack`

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#7995] opened 2019-04-12 02:15 UTC
When you pack a project with `dotnet.exe pack`, the command must pack the icon file if `<PackageIcon>` property is present in the .csproj file.

Main issue: https://github.com/NuGet/Home/issues/352

**Comment by rrelyea** [comment] 2019-08-06 17:54
duplicate of #7992 - closing

**Closed as completed by rrelyea** 2019-08-06 17:54 UTC
Labels: Resolution:Duplicate, Type:DCR, Functionality:Pack, Product:dotnet.exe
