### ISSUE TITLE
NuGet cli lists/returns unlisted packages

### ISSUE THREAD

**Issue by scurker** [NuGet/Home#3872] opened 2016-11-03 21:47 UTC
I accidentally published a newer version of a package, and marked it as "unlisted" in the NuGet gallery in order to publish the correct version. NuGet [correctly lists](https://www.nuget.org/packages/PassSharp/) the package version as v1.0.0.

However when installing the package through the Nuget command line tool, the unlisted version is installed.

Running `nuget install PassSharp` returns version `PassSharp.1.0.6150.15554` which is unlisted. Digging further into the feed, `https://api.nuget.org/v3/registration1-gz/passsharp/index.json` shows two items being returned, both versions `1.0.6150.15554` and `1.0.0`. I'm not sure if this is expected from the feed, but I assume that the NuGet cli is just installing the highest version at that point.

I would expect when no version is specified, that the highest unlisted package version would be installed.

I'm on **NuGet 3.4.4.1321** and **OSX/MacOS 10.11.6**.

**Comment by brianstringfellow** [comment] 2017-03-15 16:32
I see the same problem on NuGet Version: 3.5.0.1938 on Windows Server 2016. In my Nuget feed, `nuget list` shows the correct package versions but `nuget install` pulls an 'unlisted' version.

**Comment by michaelgoin** [comment] 2017-05-13 03:50
Just ran into this issue as well. Verified on 3.5.0 and 3.3.0

**Comment by anangaur** [comment] 2017-05-16 00:26
NuGet does not allow for package delete and instead relies on unlisting the packages. This means:

1. This unlisted version is not shown in new searches and hence will not get auto resolved to, in new projects.
2. However, existing projects that have references to this unlisted version continue to work as before. (And that's one of the reasons for not allowing delete - so that existing projects do not break)

Hope this helps.

**Comment by michaelgoin** [comment] 2017-05-16 01:49
Thank you for the response @anangaur!

Your response aligns with why I think the current behavior is a bug.

Since we can't do package deletes, we need to be able to rely on the tooling to filter out hidden packages when a version is not specified. This behavior is inconsistent across Nuget tooling, with the CLI appearing to be the one place it is not filtered. Just in case we aren't communicating the issue well (very likely), I'll take another stab.

Nuget does not allow package delete. So if you ship a bad package, you need to unlist the package.

When unlisting a package, the hope is that new users will not get the package installed. It is totally understandable if someone has already targeted the unlisted package specifically, they will continue to get the unlisted package.

### Here's the dissapointing case: 

`nuget install <package w/o version>` will install the latest package, even if unlisted. I *think* the intended behavior should be to install the newest listed version when no version is specified.

Installing unlisted packages is inconsistent from: `nuget list <package w/o version>` which will filter out unlisted packages and shows the latest listed version.

This is also inconsistent from other means of pulling Nuget packages such as `Install-Package <package w/o version>` which also filters out unlisted when a version is not specified.

As a publisher to Nuget, I'm hoping to rely on the safety mechanism of hiding packages once unlisted, from new users, since I cannot delete packages.

Hope that clears things up! In the end it may still be by design but I'd strongly encourage rethinking this.

Thank you for your time.

**Comment by anangaur** [comment] 2017-05-16 03:15
> nuget install <package w/o version> will install the latest package, even if unlisted. I think the intended behavior should be to install the newest listed version when no version is specified.

Agree. If this is the current behavior, its a bug. Just tried and could see this issue. I have unlisted one of my sample packages' latest version. Will try again `nuget install` in a while so that the old version is not retained in the search cache as stated on the package page upon unlisting:
![image](https://cloud.githubusercontent.com/assets/14800916/26088291/2742712a-39ab-11e7-84a0-684f73bca6f8.png)

**Comment by anangaur** [comment] 2017-05-16 17:47
This repros on the CLI. As reported, on VS client the unlisted package doesn't show up. May be due to the different APIs being called to get the index.json from CLI vs. VS client (VSIX).

**Comment by jainaashish** [comment] 2017-11-10 00:43
dupe of https://github.com/NuGet/Home/issues/5069

**Closed as completed by jainaashish** 2017-11-10 00:43 UTC
Labels: Resolution:Duplicate, Product:NuGet.exe
