### ISSUE TITLE
Symbols aren't getting pushed when using -SymbolSource symbolSourceUrl

### ISSUE THREAD

**Issue by Zaneo** [NuGet/Home#12952] opened 2023-10-19 14:36 UTC
### NuGet Product Used

NuGet.exe

### Product Version

Dev branch

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Build or aquire any valid with symbols `A.nupkg` and its corresponding `A.snupkg`
2. Specify a SymbolSource
3. run: `nuget push A.nupkg -Source <source> -ApiKey <apikey> -SymbolSource <symbolSource>`

Expected Results:
1. The `nupkg` is pushed to `<source>`
2. The `snupkg` is pushed to pushed to `<symbolSource>`

Actual:
The `nupkg` is pushed to `<source>`
The `snupkg` is NOT pushed to` <symbolSource>`

This seems to be because if `symbolSource` is not null below, then there is no execution path that sets `symbolPackageUpdateResource`
https://github.com/NuGet/NuGet.Client/blob/041c6da3fb92d28fa8bac2a0134e9396bfc1fda8/src/NuGet.Core/NuGet.Commands/CommandRunners/PushRunner.cs#L56-L81

I believe `symbolPackageUpdateResource = await CommandRunnerUtility.GetSymbolPackageUpdateResource(sourceProvider, symbolSource);` should be added before https://github.com/NuGet/NuGet.Client/blob/041c6da3fb92d28fa8bac2a0134e9396bfc1fda8/src/NuGet.Core/NuGet.Commands/CommandRunners/PushRunner.cs#L74

**Comment by zivkan** [comment] 2023-10-20 11:27
I think this is a duplicate of https://github.com/NuGet/Home/issues/11871

Do you agree?

As per our triage policy, it's more effective [to upvote existing issues](https://github.com/NuGet/Home/blob/dev/Issue-Triage-Policy.md#up-voting-a-feature-requestbug), as they're more likely to get prioritized, rather than having a bunch issues with zero or 1 upvote.  Unfortunately GitHub lacks tooling to let us mark issues as duplicates and count upvotes.

**Comment by Zaneo** [comment] 2023-10-20 11:51
I think that was ticket is actually a combination of several bugs, including that sources specified via command line that do not have a matching entry in a loaded NuGet.config will always be created as V2. This issue focuses specifically on the `symbolPackageUpdateResource` not being set on any execution path when SymbolSource is specified.

I’m working backwards to create the issue from the behavior I observed in execution with the debugger.

**Comment by Zaneo** [comment] 2023-10-20 11:55
I’m not opposed to moving to the other ticket.

**Closed as not planned** 2023-10-20 12:34 UTC
Labels: Type:Bug
