### ISSUE TITLE
NuGet,exe ignores build metadata (e.g. 1.0.0+metadata)

### ISSUE THREAD

**Issue by nishaatr** [NuGet/Home#4646] opened 2017-02-17 19:26 UTC
## Details about Problem

NuGet product used: NuGet.exe:

NuGet version: 3.5.0

OS version: Windows 7

## Detailed repro steps so we can see the same problem

1. Set version in *.nuspec with build metadata:

`<version>1.0.0+metadata</version>`

2. Run pack command

`nuget.exe pack`

3. Metadata seems to be ignored. I don't see metadata string in the resulting *.nupkg filename and also in Nuget Package Explorer (in metadata edit view). Either I am missing something or have misunderstood about the use build metadata. I also tried with nuget.exe (v4.0.0-rc4), but to no avail. Where should I see the build metadata string?

**Comment by emgarten** [comment] 2017-02-17 23:00
@nishaatr does the nuspec in the nupkg contain the metadata?

Metadata will not appear in the file name, this is both to avoid duplicate packages of the same version (since metadata does not count as part of the package identity) and to avoid long path issues.

NuGet Package Explorer does not contain support for SemVer 2.0.0 as far as I know.

**Comment by sirajmansour** [comment] 2017-03-07 23:51
@emgarten i just verified that it is not present even 4.0.0-rc4. the nuspec in a text editor and it does not exist neither in the `<id></id>` nor in `<version></version>`. The guys at octopus has forked nuget ages ago and have had this fixed since then, i hoped 4.0.0 would have those fixes 👎 .

**Comment by emgarten** [comment] 2017-03-08 01:44
> The guys at octopus has forked nuget ages ago and have had this fixed since then, i hoped 4.0.0 would have those fixes

@sirajmansour can you provide some details on what was fixed? This issue is currently unclear. If the issue is the resulting file name, that is intentional. Adding metadata to all names would lead to long path issues as well as making it difficult to find nupkgs in a folder.

**Comment by sirajmansour** [comment] 2017-03-08 23:01
@emgarten my fault,i fixed my comment. markdown has hidden `<version></version>`. i know that it is a design decision to not include metadata in the package file name, but the problem is that it is **missing from the `<version></version>` in the generated .nuspec inside the package**

if you quickly checkout this [PR](https://github.com/OctopusDeploy/NuGet.Client/pull/2), all of the semver incompatibilities such as dropping the metadata by using a normalized version. Specifically in commits [[1]](https://github.com/OctopusDeploy/NuGet.Client/pull/2/commits/76d4238dbd0d98ebae02248203e39eb02f67ad77) and [[2]](https://github.com/OctopusDeploy/NuGet.Client/pull/2/commits/772d1fb34b4471015327ed7887340d61038df190).

**Comment by nishaatr** [comment] 2017-03-09 01:08
I seemed to be getting a warning when running 'nuget.exe pack' (I probably missed the warning when I initially generated the *.nupkg):

> WARNING: Issue: Package version not supported on legacy clients.
> WARNING: Description: The package version '1.0.0+build.agent.38' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. This message can be ignored if the package is not intended for older clients.
> WARNING: Solution: Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter.

The *.nuspec is part of a test C# console project created in VS2013. Also, I don't see *.nuspec in the extracted output folder after I run 'nuget.exe install' on the generated package. Any reason for this?

I don't see much use of metadata if it does not appear in the filename and, especially, if it is omitted from <version>. My reason for using NuGet metadata is in the same vein as Maven 'classifier' attribute. We have a requirement to create environment specific configuration only packages which supplement a single main application package. I would like to differentiate the config package using metadata which I was hoping would be reflected in the package filenames but still be considered as the same package. The Maven classifier allows you to have the same package name with additional variant packages of the same name.

Perhaps use of NuGet metadata is not correct for what I am trying to achieve. I could add the environment identifier in the package name but this would in effect create a new package altogether.

Do you know (or is there any NuGet recommendation on) how to create packages for different environments without changing the package name?

**Comment by nishaatr** [comment] 2017-03-09 01:10
@sirajmansour I am curios as to why you said `it is missing from the <id></id>`?

**Comment by sirajmansour** [comment] 2017-03-09 02:47
@nishaatr my bad

**Comment by memark** [comment] 2017-03-09 05:12
@nishaatr @sirajmansour @emgarten 
I can confirm this issue still exists with command line nuget 4.0.0 RTM. Build metadata is effectively stripped away, not being present either in the `<version />` or in the filename.

If the Octopus fork has solved this, and the changes seem resonable, I would be happy to create a PR with those changes.

I would also like to add that having the metadata in the filename is essential. It would reasonably be up to the developer to not generate too long a filename. (Although a work-around is renaming the file myself after _nuget pack_, it feels unnecessarily hackish.)

**Comment by emgarten** [comment] 2017-03-09 05:40
A PR for ``<version />`` would gladly be accepted.

> I would also like to add that having the metadata in the filename is essential.

Can you give some examples of why this is useful?

My concern with it is that is makes it easy to end up with multiple nupkgs in a folder that have the same identity (id + version, ignoring build metadata). Ex: ``1.0.0+a  1.0.0+b``. When the user runs an action such as ``install-package packageX 1.0.0`` they get whatever package is returned by the file system first, which is not ideal.

I'd love to hear more thoughts on it.

**Comment by sirajmansour** [comment] 2017-03-10 00:50
To me personally, version matters most. In my current case i am not too concerned about the naming. However i will give my thoughts on it.

@emgarten why would you think it is not ideal ? In my opinion it is always good to keep such decision to the user. A lot of times adding a limitation to prevent something ends up being an issue on github with enough supporting voices for a bugfix. 

In a CI setup that could happen easily especially if previous build artifacts aren't cleared. I think it is better to leave it to the user rather than failing a build because of an existing package name.

**Comment by emgarten** [comment] 2017-03-10 01:11
> In a CI setup that could happen easily especially if previous build artifacts aren't cleared

This is exactly the scenario I'm worried about. It is a problem and there are two ways you can find out about the problem
1. By failing fast when the nupkg already exists
1. Later after you get a build that contains older binaries due to one of the many nupkgs being selected from the folder based on which metadata comes first alphabetically

Personally I would opt for the first one. I can see your point on leaving the decision to the user, there could be an extra flag for this, but pack should have a default that encourages the best result and avoids common pitfalls. I'd really like some solid reasons to justify that option.

**Comment by nishaatr** [comment] 2017-03-10 16:28
I believe we should treat NuGet metadata in the same vein as Maven classifier http://maven.apache.org/plugins/maven-deploy-plugin/examples/deploying-with-classifiers.html.

Maven classifier allows you to deploy and address additional artifacts generated by main application i.e. single POM. By default, assuming the Maven application is a JAR, Maven will attempt to install the JAR when classifier is not specified. The additional artifacts are directly addressable using<classifier> in the POM or commandline. The net effect of using Maven classifier is as follows:

1. You can publish additional application artifacts under the same application artifact name and version. This allows to group multiple application artifacts from a single application under the same name and version.
2. You can directly address the additional artifacts by supplying the classifier either on the commandline or in the POM. 
3. By default Maven will install the main application artifact if no classifier is supplied.
4. In Nexus GUI, you see single application artifacts under a single tree structure (name + version). 
5. Nexus cleanup ensures all same app artifacts are treated equally and removed during housekeeping.

Currently, NuGet treats metadata as supplementary information and provides no way to either address or differentiate packages with different metadata. There is more to this than simply naming the artifact with metadata string. It would be good to see NuGet metadata treated similar to Maven classifier - including allowing to set dependencies with metadata suffix in package.config and commandline

**Comment by emgarten** [comment] 2017-11-09 18:38
Fixed in the latest version 4.4.0

**Closed as completed by emgarten** 2017-11-09 18:38 UTC
Labels: Functionality:Pack
