### ISSUE TITLE
Directory.Packages.props file not updated when adding a nuget dependency in a non-Sdk style project

### ISSUE THREAD

**Issue by StephRagazzi** [NuGet/Home#12940] opened 2023-10-14 15:17 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 17.7.5

### Worked before?

I think so

### Impact

It's more difficult to complete my work

### Repro Steps & Context

- In VS 2022, create a new "Console App (.NET Framework)" projet targeting .NET 4.7.2
- The project looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    ...
</Project>
```
- Create a file named "Directory.Packages.props" at the root of the project:
```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>
```
- Right-click projet "Manage NuGet Packages..."
- Go to the Browse tab, select "Newtonsoft.Json" and install the package

The "Directory.Packages.props" file is not updated at all
Instead of updating the "Directory.Packages.props" file with the package+version, this is the csproj that gets updated with the version:
```xml
<ItemGroup>
  <PackageReference Include="Newtonsoft.Json">
    <Version>13.0.3</Version>
  </PackageReference>
</ItemGroup>
```
There is no particular message in the Package Manager console output.
If I create another project in the solution, a Sdk style project (NET6 for example), it works fine:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    ...
</Project>
```

**Comment by zivkan** [comment] 2023-10-16 08:08
Duplicate of https://github.com/NuGet/Home/issues/9521

We prioritize based on a number of factors, one of which is [number of upvotes](https://github.com/NuGet/Home/blob/dev/Issue-Triage-Policy.md#up-voting-a-feature-requestbug). At the time I'm closing this issue, the other issue has only 2 upvotes. GitHub doesn't provide tooling to automatically transfer votes, so please manually upvote the linked issue.

**Closed as not planned by zivkan** 2023-10-16 08:08 UTC
Labels: Type:Bug
