### ISSUE TITLE
How to update referenced package versions from CLI

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6540] opened 2018-02-06 19:58 UTC
_From @AustinWise on February 3, 2018 7:42_

## Steps to reproduce
1) Type `dotnet help`

## Expected  behavior
1) Expect to see `dotnet update` or similar command to update referenced packages. Something equivalent to Visual Studio's GUI that allows upgrading packages.

## Actual behavior
1) After much searching, I can't find any command to update the package version.

## Other thoughts
Currently there is no way that I can tell to update package versions when running on Linux, except to delete the reference and add it back. I can set the the `Version` attribute to equal "`*`", but that does not bind to a predictable version.

Is there a way to list which packages are upgradeable that I missed?

If there is not such a command, is it desired?

_Copied from original issue: dotnet/cli#8528_

**Comment by livarcocc** [comment] 2018-02-06 19:58
There is no such command today.

I believe this is in the NuGet backlog.

cc @richlander this is a feature request that we had to NuGet for a while:  a dotnet update package command.

I will move this issue to NuGet.

**Comment by AustinWise** [comment] 2018-02-06 20:25
This is probably a dup of #4103.

**Comment by rohit21agrawal** [comment] 2018-02-06 23:38
closing as duplicate of #4103

**Closed as completed by rohit21agrawal** 2018-02-06 23:38 UTC
Labels: Resolution:Duplicate
