### ISSUE TITLE
Nuget, PowerShell V5, Visual Studio, cannot initialize problem

### ISSUE THREAD

**Issue by SpecOps7** [NuGet/Home#4080] opened 2016-12-09 18:57 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): PMC

NuGet version (x.x.x.xxx): Nuget (PMC v 3.4.4.1321)

dotnet.exe --version (if appropirate):

VS version (if appropriate): Visual Studio 2015 update 3,

OS version (i.e. win10 v1607 (14393.321)): Win 7 Enterprise, (Citrix server)

Worked before? If so, with which NuGet version: Previous Version

## Detailed repro steps so we can see the same problem

1. Install PowerShell V5, latest version of NuGet, Visual Studio 2015 Update 3

2. Access Package Manager Console from Visual studio

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

I am experiencing an issue with  PowerShell V5, and . In Visual Studio, when accessing the Package Manager Console, (Initializing PowerShell host) I am getting a "Could not find file 'C:\Windows\SysWow64\WindowsPowerShell\v1.0\WSMan.format.ps1xml'" error. I have tried setting different PS execution policies and reinstalling Nuget. Same error. I have to downgrade powershell to get the PMC to initialize.

 Any help would be greatly appreciated.

**Comment by rrelyea** [comment] 2016-12-09 21:37
Does the workaround here solve this for you:
https://github.com/NuGet/Home/issues/2836

**Comment by emgarten** [comment] 2017-04-10 22:23
Closing as a dupe of #2836

**Closed as completed by emgarten** 2017-04-10 22:23 UTC
Labels: Resolution:Duplicate
