### ISSUE TITLE
Visual Studio should show updates for `MSBuildSdk` package types

### ISSUE THREAD

**Issue by cremor** [NuGet/Home#12822] opened 2023-08-18 06:12 UTC
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

MSBuild projects may reference a SDK from NuGet. It would be good if the VS Package Management UI would show available updates for those SDK packages.

### Additional Context and Details

The SDK package reference might either be directly in the project node (e.g. `<Project Sdk="Something.Sdk/1.2.3">`) or as a separate SDK line (e.g. `<Sdk Name="Something.Sdk" Version="1.2.3" />`).

Example use case:

1. Create a new solution with a "Standalone TypeScript Angular Project" project.
2. Open the `.esproj` file. Notice that it references a SDK with a specific version number on NuGet.
3. Open the [package page](https://www.nuget.org/packages/Microsoft.VisualStudio.JavaScript.SDK) on nuget.org and notice that a newer version is available.
4. Try to open the VS Package Management UI for the project or solution. Note that this is not possible. The "Manage NuGet packages" entry is disabled.
5. Add a .NET project to the solution.
6. Now the solution level "Manage NuGet packages" entry is available, but it doesn't show updates for the SDK.

`.esproj` files might be a special case, but as far as I can tell this also doesn't work with `.csproj` files.

**Comment by kartheekp-ms** [comment] 2023-08-21 06:28
> .esproj files might be a special case, but as far as I can tell this also doesn't work with .csproj files.

Yes, that is correct. I created a sample `.NET Console application (C#)` and updated the `Sdk` attribute value to `MSBuild.Sdk.Extras/3.0.22` as shown below. As per [docs](https://learn.microsoft.com/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022#how-project-sdks-are-resolved), NuGet based resolver comes into effect only when sdk version is specified in the `.csproj` as shown in the below example (or) by specifying custom sdk version in the `global.json` file.

```xml
<Project Sdk="MSBuild.Sdk.Extras/3.0.22">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```
I understand the feature ask to show updates for the custom SDK in PM UI, I am not sure if that aligns with the product roadmap.

**Comment by nkolev92** [comment] 2023-08-21 20:20
Team Triage: SDKs are not standard library packages, and they are not known to NuGet restore at all. 

As @kartheekp-ms said, this doesn't align with the product roadmap. 
Closing as by design

**Closed as not planned by nkolev92** 2023-08-21 20:20 UTC
Labels: Type:Feature, Resolution:ByDesign, Triage:NeedsTriageDiscussion, Product:MSBuildSDKResolver
