### ISSUE TITLE
ArgumentNullException in ResolvePackagesPath

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#4871] opened 2017-03-22 15:43 UTC
_From @danmosemsft on March 22, 2017 3:40_

Hit in a CI job in CoreClr. Do'nt have repro steps but I see it's CLI code.
https://github.com/dotnet/coreclr/pull/10323#issuecomment-288142586

```
14:52:47 Installing dotnet cli...
14:53:10 Restoring BuildTools version 1.0.27-prerelease-01413-01...
14:53:10
14:53:10 Unhandled Exception: System.ArgumentNullException: Value cannot be null.
14:53:10 Parameter name: path1
14:53:10 at System.IO.Path.Combine(String path1, String path2, String path3)
14:53:10 at Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider.ResolvePackagesPath(String rootDirectory, GlobalSettings settings)
14:53:10 at Microsoft.DotNet.Configurer.NuGetCacheSentinel.get_NuGetCachePath()
14:53:10 at Microsoft.DotNet.Configurer.NuGetCacheSentinel.Exists()
14:53:10 at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.ShouldPrimeNugetCache()
14:53:10 at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
14:53:10 at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
14:53:10 at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
14:53:10 at Microsoft.DotNet.Cli.Program.Main(String[] args)
14:53:10 /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_tst_prtest/tests/../init-tools.sh: line 164: 1325 Abort trap: 6 $__DOTNET_CMD restore "$__PROJECT_JSON_FILE" --no-cache --packages $__PACKAGES_DIR --source $__BUILDTOOLS_SOURCE >> $__init_tools_log
14:53:10
ERROR: Could not restore build tools correctly. See '/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_tst_prtest/init-tools.log' for more details.1
14:53:10 Initializing BuildTools...
```

_Copied from original issue: dotnet/cli#6099_

**Comment by livarcocc** [comment] 2017-03-22 15:44
This happens when $HOME is not set in the box.

This is a requirement by NuGet and this is simply the first time we try to find the cache. Even if you had not hit this, when doing restore you would hit something similar. Can you try setting $HOME in your script and seeing if that goes away?

**Comment by danmoseley** [comment] 2017-03-22 16:41
I think it's gone away by itself right now. Should CLI dump the callstack though?

**Comment by emgarten** [comment] 2017-03-22 19:14
The current options for this are: 
1. Fail with a helpful error message
1. Use the current working directory to write out the .nuget folder and packages

@livarcocc @danmosemsft for your CI scenarios which one would work best for you?

**Comment by danmoseley** [comment] 2017-03-22 19:16
In a CI situation in general it's nicer to have the error written out to stdout (or MSBuild logger) as a random file on disk is not necessarily gathered for the CI user and typically one can't log in ot the CI box to get it.

**Comment by emgarten** [comment] 2017-03-22 19:34
It will write the error out in the same way. It's more a question of, should this fail, or should NuGet use a sub folder in the current directory to store the packages needed for the build.

**Comment by danmoseley** [comment] 2017-03-22 19:59
I don't know mabye @livarcocc has an opinion.

**Comment by livarcocc** [comment] 2017-03-22 20:02
I think failing makes more sense to me. I find it weird for these packages to get written to random places in the disk with the user's input.

**Comment by emgarten** [comment] 2017-03-22 21:02
Dupe of https://github.com/NuGet/Home/issues/4671  I'll take a look at fixing that issue in the near future.

**Closed as completed by emgarten** 2017-03-22 21:02 UTC
Labels: Resolution:Duplicate
