### ISSUE TITLE
Auto restore packages before build in vs2017 

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#7500] opened 2018-11-12 16:42 UTC
_From @moh-hassan on November 11, 2018 16:56_

I use vs2017.8 project with the new style SDK with `PackageReference` 

Every time when I modify TargetFrameworks  in csproj/vs2017.8, and try to build the project from within vs2017 IDE, i get the error:

>Error	NETSDK1005	Assets file 'F:\projects\PaketDemo\PaketDemo\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.1'. Ensure that restore has run and that you have included 'netcoreapp2.1' in the TargetFrameworks for your project.	PaketDemo	C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	

Also, when trying to build from Package Manager Console:

		msbuild /t:build
I get the same error.

I can build and auto restore by the command:

                dotnet build    //auto restore packages and build project but has no effect on MSBuild or vs2017

'dotnet build' has no effect on MSBuild  or vs2017 for package restore and i should restore it.

The only way to restore the packages, I run the command:		
  
		msbuild /t:restore

How to auto restore the packages before build in vs2017	 when modifying `TargetFrameworks`   without running the task `msbuild /t:restore` ? 	

_Copied from original issue: Microsoft/msbuild#3920_

**Comment by nkolev92** [comment] 2018-12-28 19:31
@moh-hassan
Do you have restore enabled in VisualStudio?
Normally when you change the targetframeworks by editing the csproj in the IDE, an auto restore happens so when you build later you don't run into issues like the above.

**Comment by moh-hassan** [comment] 2018-12-28 20:29
Thanks @nkolev92  for reply.
I configured nuget for PackageReference as described in [Quick solution for Visual Studio users](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting)
I didn't have the option auto restore (as we did in Package.config) either on the level of solution or project.
BTW, I have Resharper installed , vs 2017.9.4

**Comment by nkolev92** [comment] 2018-12-28 21:22
@moh-hassan 
Auto restore is something that will **always** happen for SDK based projects (and only SDK based projetcts). 

Basically whenever a project gets loaded in VS, a restore is run. Whenever a project is changed in VS (that impacts restore, project file edits such as PR and tfm changes etc). 

Are you able to reproduce this in a 1-project solution?

**Comment by moh-hassan** [comment] 2018-12-28 23:28
I did a two different scenario.
Environment: vs 2017.9.2, Package Manager Console Host Version 4.9.0.5661

**Scenario 1:**
modify framework and instantly click build

1) I tried this SDK project

		<Project Sdk="Microsoft.NET.Sdk">

		  <PropertyGroup>
			<TargetFrameworks>net452;netstandard2.0;netcoreapp2.1</TargetFrameworks>
		  </PropertyGroup>
		  <ItemGroup>
			<PackageReference Include="DotLiquid"  Version="2.0.298"/>
			<PackageReference Include="nunit" Version="3.11.0" />
			<PackageReference Include="NUnit3TestAdapter" Version="3.11.0" />
			<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
		  </ItemGroup>
		</Project>

2) Modify 	netcoreapp2.1 to netcoreapp2.0
3) Build
The message appear:
>	Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'F:\github_issues\nuget_7500\AutoRestoreDemo\AutoRestoreDemo\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project.	AutoRestoreDemo	C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	

>========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

4) Build again

The message disappear 
>========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========


**Senario2**

Modify framework and wait a little until the message Ready in the status bar appear then   click build

1) Modify 	netcoreapp2.1 to netcoreapp2.0
2)wait a view seconds, note the status bar
The following messages appear in sequence in the status bar

>Item(s) saved
Restoring ...
Ready

3)Click build when I see Ready in the status bar.
$) Build 
Build success with auto restore

**Conclusion:**
When modifying a framework in the project, I should wait a little and click Build after the message **Ready** in the status bar appear.
The time is based on the  number of the projects in the solution.
I needn't to run `msbuild /t:restore` :)

Should I follow scenario 2 to get auto restore?

**Comment by nkolev92** [comment] 2018-12-29 01:59
@moh-hassan 
Scenario 2 is basically auto-restore in action.
Usually depending on your machine load (and how many projects you have in that solution), the whole thing should be seamless. 

With a signle project I was not able to reproduce scenario 1.

And yeah as you articulated correctly the more projects you, the slower it will be. 
Anytime something changes, NUGet runs a restore for all projects in VS, and that can sometimes take a few seconds.

We are constsantly doing a lot improvements for solution load/restore performance in VS. 
One related issue is the following; 
https://github.com/NuGet/Home/issues/7622. 

I think our whole interaction cleared things up a bit. 
I'd like to close this issue now, if you agree.

**Comment by moh-hassan** [comment] 2018-12-30 08:00
Thanks @nkolev92  for your time and help.
I consider my issue is resolved and you can close the issue.

**Closed as completed** 2019-01-02 18:31 UTC
Labels: Functionality:Restore, Style:PackageReference, WaitingForCustomer
