### ISSUE TITLE
Nuget exits with 0 when it fails 

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#6240] opened 2017-11-30 18:53 UTC
Repro steps:

- Open up a project file and insert an MSBuild syntax error. Say missing a `)` in a conditional
- Run `nuget restore` on that project

NuGet will completely fail to restore here, as it should the project file is broken. Yet it will exit with a status of 0. This makes it impossible to detect the failure in automation. 

Note: `msbuild /t:restore` will fail with a non-zero code for the same file. 

NuGet version: 4.3.0.

**Comment by emgarten** [comment] 2017-12-01 04:01
Duplicate of https://github.com/NuGet/Home/issues/6061

**Closed as completed by emgarten** 2017-12-01 04:01 UTC
Labels: Resolution:Duplicate, Type:Bug, Product:NuGet.exe, Functionality:Restore
