### ISSUE TITLE
The 'IntegrationPackage' package did not load correctly after Installing Latest Build

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1519] opened 2015-10-05 17:29 UTC
_From @rmegal on October 5, 2015 13:41_

Running VS2015 Community Edition. I am getting the following error after updating to NuGet Package Manager for Visual Studio 3.2.60914.10516:

> The 'IntegrationPackage' package did not load correctly.

I can easily recreate the error by firing up VS2015 and opening any file. Or starting VS2015 and passing it a file to open in the editor.

I get the following error if I select `Tools/Options/Nuget Package Manager`:

> The 'NuGetPackage' package did not load correctly.

I tried to attach some screenshots and the ActivityLog but kept getting:

> Something went really wrong, and we can't process that file. Try again.

I will keep them around and try again later.

_Copied from original issue: NuGet/NuGetGallery#2718_

**Comment by yishaigalatzer** [comment] 2015-10-05 17:47
We need more information, on what else you got installed on your visual studio?

Do you have xamarin installed?

**Comment by rmegal** [comment] 2015-10-05 18:03
Apparently I do have Xamarin installed. Not sure why since I'm not using it - yet.

The following is from the Help About:

```
Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA581
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA581
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA581
Microsoft Visual C++ 2015

Visual F# 2015 RC   00322-20000-00000-AA581
Microsoft Visual F# 2015 RC

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA581
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.60814.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.6
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JetBrains ReSharper Ultimate 2015.2   Build 103.0.20150818.200216
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2015 JetBrains, Inc.

Microsoft Azure HDInsight HQL Service   2.0.2600.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.30718.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.30718.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.30718.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ViEmu for Visual Studio   3.6.0
ViEmu: vi/vim emulation for Microsoft Visual Studio. (c) 2005-2015 Symnum Systems. Please visit http://www.viemu.com for details.

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Universal Windows Apps   14.0.23309.00 d14oob
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualSVN   5.1.2
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at http://www.visualsvn.com
Copyright © 2005-2015 VisualSVN Ltd. All rights reserved.

Web Essentials 2015   0.5.175
Adds many useful features to Visual Studio for web developers.

Xamarin   3.11.450.0 (2ab5145)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.0.115 (d23da369e436488f38c8ab8fe8a9ae7d9ea5256b)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.10.0.0 (7741cc495ab0baf04ff0405d0604bc27f0ecae2e)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration
```

**Comment by yishaigalatzer** [comment] 2015-10-05 19:06
I would like to ask for your help trying to identify this issue. We are investigating a similar issue, but since the message for loading a vs extension is so cryptic it is hard to tell if they are the same,

Is it possible for you to attach another instance of visual studio and try to catch the exception that caused it (since I can't get a local repro easily)? I would suspect a nullref is popping up somewhere. So attaching a debugger (before going to tools->Options) and turning on first chance exceptions in the debugger options might get us more insights

**Comment by yishaigalatzer** [comment] 2015-10-05 21:01
@rmegal I do have a fix for the issue I investigated on my side. Would you be able to test a private drop once I have one ready to see if it is indeed the same issue?

Please reach out to me on my Microsoft email y i g a l a t z @ msft.com

**Comment by rmegal** [comment] 2015-10-06 12:22
The fix resolved the issue on my machine. I will look for the next update.

Thanks!

**Comment by yishaigalatzer** [comment] 2015-10-06 16:31
Duplicate of #1408

**Comment by yishaigalatzer** [comment] 2015-10-06 16:31
@rmegal thanks for verifying. Its awesome to know these where the same

**Closed as completed by yishaigalatzer** 2015-10-06 16:31 UTC
Labels: Resolution:Duplicate
