### ISSUE TITLE
Package.config project fails to restore if parent directory has directory.build.props with packageref

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#5320] opened 2017-06-01 17:01 UTC
In VS 2017, I have a solution with SDK style projects and an MVC 4.6 project with `packages.config`. If I add a `directory.build.props` file to the parent directory that contains a packageref, restore is incorrect in the mvc/packages.config project.

I would not expect `directory.build.props` to apply to non-SDK project types.

This happens with 15.2 and 15.3 preview 1

**Comment by clairernovotny** [comment] 2017-06-01 17:06
Here's a repro https://github.com/onovotny/NuGetRestoreRepro

**Comment by dsplaisted** [comment] 2017-06-13 18:56
Directory.Build.props is a [feature of MSBuild 15](https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0), and is not specific to SDK-style projects.

Can you move the `PackageReference` to a Directory.Build.targets file and condition it on whether `TargetFramework` is set?  (With the 2.0 SDK, you will be able to check the [`UsingMicrosoftNETSdk` property](https://github.com/dotnet/sdk/pull/1242/files) instead, and you will be able to do that in the Directory.Build.props file if you like.)  That should probably fix the issue.

**Comment by clairernovotny** [comment] 2017-06-13 19:15
Is there any default setting for `PackageRestoreType` that can be checked instead since some projects opt-in to PackageRef by default like UWP. Just seemed like unexpected behavior that would bite people?

**Comment by nkolev92** [comment] 2020-02-28 01:58
At this point I believe this issue is a duplicate of https://github.com/NuGet/Home/issues/4488. 

RestoreProjectStyle is a property that can be used to opt-in projects into PackageReference but it needs officially cleared up in #4488

**Closed as completed by nkolev92** 2020-02-28 01:58 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Bug, Functionality:Restore
