### ISSUE TITLE
(Spike) Can server send package metadata that PMUI can consume to conditioanlly allow install/update of a package based on TFM and TFM versions

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4933] opened 2017-03-30 00:34 UTC
Finalize the design by Milestone 4.2

**Comment by nkolev92** [comment] 2019-04-16 23:29
Duplicate of https://github.com/NuGet/Home/issues/5725

**Closed as completed by nkolev92** 2019-04-16 23:29 UTC
Labels: Resolution:Duplicate, Type:Feature, Functionality:VisualStudioUI
