### ISSUE TITLE
[Bug]: Ignores no_proxy settings

### ISSUE THREAD

**Issue by Dancho80** [NuGet/Home#11070] opened 2021-07-22 15:18 UTC
### NuGet Product Used

Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

.Net 5.0.302

### Worked before?

no

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Working behind a corporate proxy server
1. add HTTPS_PROXY and HTTP_PROXY to the environment variables
2. add no_proxy with your local Nuget repo server

working from both Visual Studio 2019 ver 16.10.4 and from NuGet cli is impossible to fetch from locally hosted NuGet servers.
While trying to access them, getting an error:
```
An error occurred while sending the request.
  The remote server returned an error: (503) Server Unavailable.
```
Tried to add no_proxy to the Nuget.config file - no success, same error.

The only solution is unsetting HTTPS_PROXY and HTTP_PROXY envs

**Comment by zivkan** [comment] 2021-07-22 15:43
duplicate of https://github.com/NuGet/Home/issues/10902.

The fix has already been released in 16.11 preview 2.

**Closed as completed by zivkan** 2021-07-22 15:43 UTC
Labels: Resolution:Duplicate
