### ISSUE TITLE
Feature: Simplify Repository Sources UI

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1773] opened 2015-11-25 14:50 UTC
The Update -> OK steps to manage a repository location in the NuGet sources UI is confusing to some.  It could be simplified to a single "OK" button

**Comment by abatishchev** [comment] 2015-12-20 19:46
Yes, please. Forgetting to click Update causes all changes to be discarded.
With adoption of custom vso feeds, this happens every other day.

**Comment by yishaigalatzer** [comment] 2015-12-31 00:32
We should do it as part of the new settings UI we plan for 3.4

**Comment by yishaigalatzer** [comment] 2016-01-28 22:39
Duplicate of #1114

**Closed as completed by yishaigalatzer** 2016-01-28 22:39 UTC
Labels: Resolution:Duplicate, Functionality:VisualStudioUI
