### ISSUE TITLE
.NET Core Class Library doesn't resolve .NETStandard.Library (1.6.1) 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4434] opened 2017-01-30 17:43 UTC
vs feedback 768927 -- using rc3 vs2017

NET Core Class Library doesn't resolve any of the NuGet references it has, including the NETStandard.Library.

It seems it's a package restore problem. My solution uses submodules. You can clone it an try for yourself: https://github.com/SuperJMN/OmniGUI.git.

This is the output:
Error occurred while restoring NuGet packages: Exception from HRESULT: 0x8004C738
1>------ Build started: Project: Zafiro.Core (Zafiro\Zafiro.Core), Configuration: Debug Any CPU ------
2>------ Build started: Project: OmniXaml.Attributes, Configuration: Debug Any CPU ------
2>C:\Users\super\AppData\Local\Temp\.NETStandard,Version=v1.2.AssemblyAttributes.cs(4,20,4,26): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
2>obj\Debug\netstandard1.2\OmniXaml.Attributes.AssemblyInfo.cs(14,12,14,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
2>obj\Debug\netstandard1.2\OmniXaml.Attributes.AssemblyInfo.cs(15,12,15,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
2>obj\Debug\netstandard1.2\OmniXaml.Attributes.AssemblyInfo.cs(16,12,16,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)

...

And lots of erros like this.

**Comment by zhili1208** [comment] 2017-01-30 19:04
this is a dupe of https://github.com/NuGet/Home/issues/4326

**Closed as completed by zhili1208** 2017-01-30 19:04 UTC
Labels: Resolution:Duplicate, Type:Bug
