### ISSUE TITLE
Nuget update command does not update projects that use project.json

### ISSUE THREAD

**Issue by bondarchook** [NuGet/Home#2691] opened 2016-04-29 11:41 UTC
Commandline Nuget **update** command does not update projects that use **project.json** instead of packages.config

**Comment by yishaigalatzer** [comment] 2016-05-02 04:49
Can you tell us for what scenario are you using it? If you are using it to get CI builds to update we have a much better feature for this case which is to use a \* notation in the file - for example you could reference 2.1.0-\* to get all pre-release builds of 2.1.0 or 2.1.\* to get all versions 2.1 (and so on up to using \* which will be get the latest)

**Comment by bondarchook** [comment] 2016-05-02 09:20
If I use this asterisk notation what command I should use then to get latest versions of libraries? Does restore will get latest versions? And how I can control it? I do not want always automatic update I want to run some command when I need it to be updated.

My case is. In CI build I need to get **latest versions** of **specific packages** 
And I should decide whether I want to update or not.

And it would be very nice if it also update project.json file for me with new versions of dependencies.

**Comment by nkolev92** [comment] 2017-12-19 22:51
Duplicate of #4103

**Closed as completed by nkolev92** 2017-12-19 22:51 UTC
Labels: Resolution:Duplicate, Type:DCR
