### ISSUE TITLE
dotnet pack: Getting NU5008: Manifest file not found in one folder, but not in another folder

### ISSUE THREAD

**Issue by JonPSmith** [NuGet/Home#10785] opened 2021-04-21 14:59 UTC
I am getting different results from `dotnet pack` when in different folders - both work but one produces error messages. There must be some sort of rules that I'm not aware with and I could use some help to understand how `dotnet pack` works with solutions/projects.

### What I am trying to achieve:

I am trying to build a dotnet tool that will allow multiple projects to go into one NuGet package (part of my modular monolith approach). I'm using this tool to allow me to break up large solutions into separate NuGet packages. You would run the tool at the solution level so that it can find all the projects to include in the NuGet package.

I get errors running the `dotnet pack` at the solution folder level, which isn't going to work for other users.

## Details about Problem

I have a VS solution with the following (example) file structure

- SolutionFolder (actually MultiProjPackTool , but make it easier to understand I use SolutionFolder)
   - Group1.Project1
       - Group1.Project1.csproj
    - Group1.Project2
       - Group1.Project2.csproj
    - Group1.Project3
       - Group1.Project3.csproj
    - MultiProjPackTool 

My `CreateNuGetDebug .nuspec` file looks like this (but different version num for each folder)
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>BookApp.Books</id>
    <version>1.0.0-preview001</version>
    <authors>The authors</authors>
    <description>description of this NuGet package</description>
    <dependencies>
      <group targetFramework="net5.0">
        <dependency id="Microsoft.Extensions.Logging" version="5.0.0" />
        <dependency id="Newtonsoft.Json" version="13.0.1" />
      </group>
    </dependencies>
  </metadata>
  <files>
    <file src="C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project1\bin\Debug\net5.0\Group1.Project1.dll" target="lib\net5.0" />
    <file src="C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project2\bin\Debug\net5.0\Group1.Project2.dll" target="lib\net5.0" />
    <file src="C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project3\bin\Debug\net5.0\Group1.Project3.dll" target="lib\net5.0" />
  </files>
</package>
```

When I run the command `dotnet pack -p:NuspecFile=CreateNuGetDebug.nuspec` (which has the version of `1.0.0-preview002`) at the `...SolutionFolder\MultiProjPackTool\` it works fine, with the following output.

```text
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  MultiProjPackTool -> C:\Users\JonPSmith\source\repos\MultiProgPackTool\MultiProjPackTool\bin\Debug\netcoreapp3.1\MultiProjPackTool.dll
  Successfully created package 'C:\Users\JonPSmith\source\repos\MultiProgPackTool\MultiProjPackTool\bin\Debug\BookApp.Books.1.0.0-preview002.nupkg'.
```

When I run the same command with the same .nuspec (copied) in the folder `...SolutionFolder\` (which has the version of `1.0.0-preview001`) it gives me the following output **BUT it still creates a valid .nupkg file!! (see `Successfully created package ... ` output below)**. It also puts the .nupkg file into the MultiProjPackTool\bin\Debug folder.

```text
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Group1.Project3 -> C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project3\bin\Debug\net5.0\Group1.Project3.dll
  Group2.Project1 -> C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group2.Project1\bin\Debug\netstandard2.1\Group2.Project1.dll
  Group1.Project1 -> C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project1\bin\Debug\net5.0\Group1.Project1.dll
  Group1.Project2 -> C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project2\bin\Debug\net5.0\Group1.Project2.dll
  MultiProjPackTool -> C:\Users\JonPSmith\source\repos\MultiProgPackTool\MultiProjPackTool\bin\Debug\netcoreapp3.1\MultiProjPackTool.dll
C:\Program Files\dotnet\sdk\5.0.202\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5008: Manifest file not found at 'C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group2.Project1\CreateNuGetDebug.nuspec' [C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group2.Project1\Group2.Project1.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5008: Manifest file not found at 'C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project3\CreateNuGetDebug.nuspec' [C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project3\Group1.Project3.csproj]
  Group2.Project2 -> C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group2.Project2\bin\Debug\net5.0\Group2.Project2.dll
  Successfully created package 'C:\Users\JonPSmith\source\repos\MultiProgPackTool\MultiProjPackTool\bin\Debug\BookApp.Books.1.0.0-preview002.nupkg'.
C:\Program Files\dotnet\sdk\5.0.202\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5008: Manifest file not found at 'C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project2\CreateNuGetDebug.nuspec' [C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project2\Group1.Project2.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5008: Manifest file not found at 'C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group2.Project2\CreateNuGetDebug.nuspec' [C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group2.Project2\Group2.Project2.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5008: Manifest file not found at 'C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project1\CreateNuGetDebug.nuspec' [C:\Users\JonPSmith\source\repos\MultiProgPackTool\Group1.Project1\Group1.Project1.csproj]
```

## Access to the code

The actual code is open-source at https://github.com/JonPSmith/MultiProgPackTool

**Comment by aortiz-msft** [comment] 2021-04-22 17:22
`dotnet pack` will try to pack each project one by one, which is different from how nuget.exe works. Does that help?

We have a related issue: https://github.com/NuGet/Home/issues/4254

**Comment by JonPSmith** [comment] 2021-04-23 07:50
I don't want to use nuget.exe because anyone who uses my tool would need to install nuget.exe, while dotnet pack is already globally installed when .NET SDK is installed.

I have read and upvoted issue #4254.

**Comment by zivkan** [comment] 2021-04-23 14:04
In the meantime you can create a new project file, as demoed in the [packing using a nuspec file](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec-file) docs. See the csproj at the end of the section. Using the `<NuspecFile>` property you no longer need to pass the nuspec file on the command line, just pack the csproj.

Closing this as a duplicate of #4254

**Closed as completed by zivkan** 2021-04-23 14:04 UTC
Labels: Type:Bug, Resolution:Question, Functionality:Pack
