### ISSUE TITLE
Cache grows indefinitely - add limit feature

### ISSUE THREAD

**Issue by Caleb-D** [NuGet/Home#9730] opened 2020-06-29 14:55 UTC
We have an internal project that delivers a Nuget cache from each nightly build.  I work on a project that consumes this Nuget package.  Our build process automatically updates the Nuget version, so we are always pointing at the latest (unless we are near a release and then we freeze auto-updates).

This means that every time I pull the latest changes and build, VS "restores (download/install)" the next Nuget package.

Problem is that this Nuget package is 186 MB compressed, ~600 MB uncompressed, so in the %userprofile\.nuget cache folder, there is 786 MB for each new version.  Then when you build, VS copies it to the "packages" subfolder directory in the solution folder.

:) can you see where I'm going?

I just this morning deleted about 50 GB of packages from these two cache locations.  My computer was running slowly and I finally figured out it was because of low disk space/fragmentation issues.  

**So, I would like to request that a feature to limit the size of the Nuget cache be added.**

It could be smart so that it prefers to keep at least one version of every package, and then prefers the latest.  I don't know if you have access to the "last used by a compile" metric at this level, but that might a good way to do it too.

There are some optimizations we could (and eventually will do) on our side to reduce the size of the package, but it takes time and devops work (even so, the minimum set of dlls required are ~160 MB uncompressed for x64).  The unconstrained cache size problem would just be lessened.

**Comment by zivkan** [comment] 2020-06-29 23:13
Duplicate of https://github.com/NuGet/Home/issues/4980

**Closed as completed by zivkan** 2020-06-29 23:13 UTC
Labels: Resolution:Duplicate
