### ISSUE TITLE
NuGet install options missing from latest VS 2017 Solution UI

### ISSUE THREAD

**Issue by jpobst** [NuGet/Home#6111] opened 2017-10-27 18:51 UTC
When using "Manage NuGet Packages for Solution", the "Options" dropdown only contains "Show preview window".  It no longer contains the "Install and Update Options" or the "Uninstall Options".  I don't know which version of VS caused this, but I am pretty confident that the 
additional options used to be available at the Solution level.

The options are still available if you do "Manage NuGet Packages" at the Project level.

![nuget](https://user-images.githubusercontent.com/179295/32120360-dcad3d94-bb1d-11e7-9dc3-31fa9186c5e8.png)

## Details about Problem

NuGet product used: VS UI

NuGet version (x.x.x.xxx): 4.4.0

VS version (if appropriate): VS 2017 15.4.1

OS version (i.e. win10 v1607 (14393.321)): win 10

Worked before? If so, with which NuGet version: Unsure

**Comment by mishra14** [comment] 2017-10-27 19:54
@jpobst Thanks for the feedback. This is by design as in solution context, the selection of the projects can change. In project context the settings apply to exactly one project and hence it is less confusing to the users.

please let us know if this is blocking you or if you need more help from us.

--------------------------------

Update: I closed this issue hastily and it seems this was a regression. please see @jainaashish comment for the fix details.

**Closed as completed by mishra14** 2017-10-27 19:54 UTC
Labels: Functionality:VisualStudioUI, RegressionFromPreviousRTM

**Comment by Dirnei** [comment] 2017-11-16 09:35
i really miss the old version. in our development workflow we always used the configuration on solution context. the new way is IMHO less productive then the old one. i would love to see an configuration option to enable the old behaviour

**Comment by mdhom** [comment] 2017-11-16 09:51
![17-11-16-vs17-dependcy-behavior-mockup](https://user-images.githubusercontent.com/30362954/32884832-ec5510e8-cabb-11e7-9f20-386ceadeb08e.png)
In my eyes, something like the screenshot attached would be the perfect solution for solution context. With an additional comobox-column you could immediately see which dependency behavior is selected for the individual project and you could edit it in solution context. With this, no switching between project-nuget-managers is necessary.

**Comment by jainaashish** [comment] 2017-11-16 17:48
@Dirnei @mdhom this was indeed a regression caused in 15.4 release but it has been fixed in 15.5 and will be available soon.

**Comment by MasonBergstrom** [comment] 2018-05-10 18:37
Is there some secret that I'm missing to turning this on? I've never had the "Install and Update Options" or the "Uninstall Options" for my projects or solutions. This applies to both my Net Core and Net Framework projects, all I have is the "Show preview window."

I'm fully updated, using VS 15.7.1 and Nuget package manager 4.6.0.

**Comment by anubi** [comment] 2018-09-24 13:33
I'm in the same boat as MasonBergstrom. What conditions trigger this menu to appear? I ask because a package I published to my own private nuget repo is not installing dependencies when I use it, so I'm wondering if this is just a setting I'm missing.

The only option I see is "Show preview window"

**Comment by jainaashish** [comment] 2018-09-24 16:34
@MasonBergstrom and @anubi this option is always available at "Manage NuGet packages" at solution level. And at project level, It's only available for `packages.config` based projects. So it will never be available for NetCore projects or Net Framework projects using `PackageReference` to manage their NuGet dependencies. So for `PackageReference` based projects, you can never choose a dependency resolution behavior and it always pick the lowest.

Hope this clarifies and let me know if you still see any issue with that.
