### ISSUE TITLE
Cannot uninstall newly installed package 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4435] opened 2017-01-30 17:47 UTC
vsfeedback with vs2017 26120.4 (test scenario day build) - 746023
Filed by @dtivel 

1.  Open the solution in the attached "ClassLibrary (2).zip" file.
2.  In File Explorer, copy the path of the directory that would contain the ClassLibrary.1.0.0.nupkg package.  For example, C:\Users\dtivel\Documents\Visual Studio 2017\Projects\ClassLibrary\ClassLibrary\bin\Debug
3.  In Visual Studio navigate on the main menu to Tools | NuGet Package Manager | Package Manager Settings.
4.  In the subsequent Options dialog, in the left-hand tree pane click on Package Sources.
5.  In the right-hand details pane, click the green plus button to create a new package source.
6.  At the bottom of the dialog paste the copied package folder path into the Source text box.
7.  Click Update.
8.  Click OK.

SEE THE REST IN THE VSFEEDBACK ITEM

**Comment by jainaashish** [comment] 2017-02-01 23:48
Root cause of this issue is similar to https://github.com/NuGet/Home/issues/4433 and would be fixed with this PR# https://github.com/NuGet/NuGet.Client/pull/1157 

There is another scenario which will fault into same issue.
1. Create 2 .net framework class library -> library1, and library2
2. Add a NuGet package to library1 as packages.config
3. Open NuGet manager UI at solution level, and try to add another package to both the projects.
4. It will show "select package format dialog to choose between packages.config vs PackageReference for library2 project.
5. Select PackageReference and continue, it will fault into same issue and throw error to install this package.

**Comment by rrelyea** [comment] 2017-02-01 23:50
As we punted #4433 to 4.0.1, we will with this also. thx.

**Comment by jainaashish** [comment] 2017-02-13 22:35
Fixed in 4.0 RTM since #4433 is fixed and merged.

**Closed as completed by jainaashish** 2017-02-13 22:35 UTC
Labels: Product:VS.Client, Type:Bug, Style:PackageReference
