### ISSUE TITLE
Override asset selection in a package

### ISSUE THREAD

**Issue by akoeplinger** [NuGet/Home#10937] opened 2021-06-11 19:02 UTC
Continuation from the discussion in https://github.com/dotnet/designs/pull/222.

With the transition of Xamarin from Mono (== .NET Framework) to .NET Core based class libraries and TFMs we're hitting cases where a netcoreapp asset is selected instead of e.g. a netstandard one like before due to the new precedence rules.

This causes problems since some packages assumed that netcoreapp meant ".NET on desktop platforms" and did things that won't work on mobile like checking the existence of some files etc while the netstandard asset would work just fine.

It'd be good to have a way to somehow be able to override which asset is selected for a given package to have an escape hatch until the ecosystem gets updated.

/cc @JonDouglas @nkolev92

**Comment by zivkan** [comment] 2021-06-11 19:09
duplicate of https://github.com/NuGet/Home/issues/7416

I think it would be good to put your comments there to have the feature discussion in one place.

**Comment by nkolev92** [comment] 2021-06-16 02:06
Closing as dup of https://github.com/NuGet/Home/issues/7416

**Closed as completed by nkolev92** 2021-06-16 02:06 UTC
Labels: Resolution:Duplicate, Type:Feature, Functionality:Restore
