### ISSUE TITLE
Projects with multiple TFM throws exception on restore in Visual Studio 15.3.4

### ISSUE THREAD

**Issue by dozer75** [NuGet/Home#5927] opened 2017-09-23 15:23 UTC
## Details about Problem

When building in Visual studio the error shown under verbose logs are dumped in output, and no packages are updated. It looks similar to #5645 and I commented on this with the reply to create a new issue.

NuGet product used: Visual Studio 

NuGet version: 4.3.0 (as stated in About Visual Studio)

dotnet version: 2.0.0

VS version: 15.3.4

OS version (i.e. win10 v1607 (14393.321)): Win10 v1703 (15063.608)

Worked before? If so, with which NuGet version:
I am not sure, discovered this now.

## Detailed repro steps so we can see the same problem

1. Create an empty solution

2. Create an empty project, remove any files

3. Edit the .csproj file to look like this:

```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.6;net461</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard1.6|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>


</Project>

```

4. Try to rebuild

An exception that is shown below under Verbose logs is dumped in output on detailed build verbosity

## Other suggested things

Here is the strange thing. If I try to run dotnet restore on the solution in command prompt, the error disappears in Visual Studio when rebuilding (doesn't apply to all projects).

### Verbose Logs
```
Error occurred while restoring NuGet packages: System.InvalidOperationException: The operation failed as details for project Project1 could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__15.MoveNext()

```
### Sample Project

[MultipleTFM.zip](https://github.com/NuGet/Home/files/1326614/MultipleTFM.zip)

**Comment by mishra14** [comment] 2017-09-27 00:59
@dozer75 This is a known issue and dupe of https://github.com/dotnet/sdk/issues/1607.

Please let us know if you need more help from us!

**Closed as completed** 2017-09-27 00:59 UTC
Labels: Resolution:External, Functionality:Restore, Style:PackageReference

**Comment by dozer75** [comment] 2017-10-04 21:27
Sure, if you think it is a duplicate. As a sidenote; we also have a LSL solution and get the same issue there. Not only without.

I have now dropped Multiple TFM's and gone for seperate projects since this multiple TFM system is quite faulty and I don't have time to investigate every issue arising.
