### ISSUE TITLE
Restoring NuGet Packages log on PMC not localized

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#4500] opened 2017-02-04 03:14 UTC
Language - Chinese 

```
c:\users\anmishr\documents\visual studio 2017\Projects\ConsoleApp5\ConsoleApp5\ConsoleApp5.csproj의 패키지를 복원하는 중...
NuGet 패키지 Newtonsoft.Json 9.0.1을(를) 설치하고 있습니다.
복원을 커밋하는 중...
Writing lock file to disk. Path: c:\users\anmishr\documents\visual studio 2017\Projects\ConsoleApp5\ConsoleApp5\obj\project.assets.json
799.09 ms에서 c:\users\anmishr\documents\visual studio 2017\Projects\ConsoleApp5\ConsoleApp5\ConsoleApp5.csproj에 대한 복원을 완료했습니다.
ConsoleApp5에 'Newtonsoft.Json 9.0.1'을(를) 설치했습니다.
ConsoleApp5에 'System.Runtime.Serialization.Primitives 4.1.1'을(를) 설치했습니다.
Nuget 작업 실행 시간: 816.4 ms
경과 시간: 00:00:01.7227821
========== 완료 ==========

Restoring NuGet packages...
Time Elapsed: 00:00:00.8556742
========== Finished ==========
```

severity - medium

**Comment by rrelyea** [comment] 2017-02-04 22:49
dupe of #4505

**Closed as completed** 2017-02-04 22:49 UTC
Labels: Resolution:Duplicate, Tenet:WorldReady, Triage:NeedsTriageDiscussion
