### ISSUE TITLE
dotnet pack throws NullReferenceException on Mac

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#6829] opened 2018-04-13 15:36 UTC
Repro environment:

- dotnet version 2.1.300-preview2-008324 (repro will auto-install this)
- OS Mac (guessing this would repro on Linux as well) 

Repro steps:

1. Clone https://github.com/jaredpar/roslyn
1. Check out branch `repro-dotnet-pack-nre-mac`
1. Run `build.sh --build --restore`
1. Run `build.sh --pack`

This will cause a `NullReferenceException` to be thrown and the following message gets printed to the console

> /Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error : Object reference not set to an instance of an object. [/Users/jaredpar/code/roslyn/src/NuGet/NuGetProjectPackUtil.csproj]

The actual `dotnet pack` command that is being executed is the following:

> dotnet pack -nologo --no-build NuGetProjectPackUtil.csproj -p:NuSpecFile=Microsoft.CodeAnalysis.CSharp -p:NuGetPackageKind=PreRelease -p:NuspecBasePath=/Users/jaredpar/code/roslyn/Binaries/Debug -o /Users/jaredpar/code/roslyn/Binaries/Debug/NuGet/PreRelease
~/code/roslyn

This `dotnet pack` command works fine on Windows. I've poked around a bit but can't figure out why the exception is being thrown here. First I set the `NUGET_SHOW_STACK` environment variable to get a bit more context. 

``` cmd
jaredparmac:roslyn jaredpar$ export NUGET_SHOW_STACK=true
jaredparmac:roslyn jaredpar$ ./build.sh --pack
The specified SDK version [2.1.300-preview2-008324] from global.json [/Users/jaredpar/code/roslyn/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
~/code/roslyn/src/NuGet ~/code/roslyn
/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error : Object reference not set to an instance of an object. [/Users/jaredpar/code/roslyn/src/NuGet/NuGetProjectPackUtil.csproj]
/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [/Users/jaredpar/code/roslyn/src/NuGet/NuGetProjectPackUtil.csproj]
/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error :    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path) [/Users/jaredpar/code/roslyn/src/NuGet/NuGetProjectPackUtil.csproj]
/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error :    at NuGet.Commands.PackCommandRunner.BuildPackage(String path) [/Users/jaredpar/code/roslyn/src/NuGet/NuGetProjectPackUtil.csproj]
/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error :    at NuGet.Commands.PackCommandRunner.BuildPackage() [/Users/jaredpar/code/roslyn/src/NuGet/NuGetProjectPackUtil.csproj]
/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error :    at NuGet.Build.Tasks.Pack.PackTaskLogic.BuildPackage(PackCommandRunner runner) [/Users/jaredpar/code/roslyn/src/NuGet/NuGetProjectPackUtil.csproj]
/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.1.300-preview2-008324/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error :    at NuGet.Build.Tasks.Pack.PackTask.Execute() [/Users/jaredpar/code/roslyn/src/NuGet/NuGetProjectPackUtil.csproj]
```

That gave me a bit more information but when I looked through the `BuildFromProjectFile` method nothing obvious stood out. 

Next I tried launching the `dotnet pack` command under the VS Code debugger and breaking on exceptions. The debugger launches here but never breaks. I presume that's because a child process is getting launched and the exception occurs there. VS code doesn't support child process debugging yet hence not a good way for me to attach there.

Appreciate some help here.

**Comment by jaredpar** [comment] 2018-04-13 16:13
CC @333fred, @dseefeld as this is blocking source build.

**Comment by mishra14** [comment] 2018-04-13 18:03
cc: @rohit21agrawal

**Comment by jaredpar** [comment] 2018-04-13 18:07
Note: I was able to eventually get VSCode attached to this by doing the following:

1. `export MSBUILDDEBUGONSTART=2`
1. Attach to child process
1. Enable break all exceptions
1. Disable Just My Code

That eventually let me break in the `BuildFromProjectFile` method. Unfortunately there are no locals in the debugging session hence I wasn't able to get any further.

**Comment by rohit21agrawal** [comment] 2018-04-13 18:10
I think the culprit is : -p:NuSpecFile=Microsoft.CodeAnalysis.CSharp  this needs to have the .nuspec extension

you are basically hitting : https://github.com/NuGet/Home/issues/4649

**Comment by jaredpar** [comment] 2018-04-13 22:09
@rohit21agrawal yes that is the problem. Once I fixed the typo the pack operation succeeded.

**Comment by rohit21agrawal** [comment] 2018-04-13 22:10
closing as duplicate of #4649

**Closed as completed by rohit21agrawal** 2018-04-13 22:10 UTC
Labels: Resolution:Duplicate, Triage:Investigate, Functionality:Pack
