### ISSUE TITLE
[Test Failure][Localization] Restore strings are not localized in Output window

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4505] opened 2017-02-04 12:03 UTC
**NuGet Version:** Dev 2265 VS15 Localized NuGet Client Vsix
**VS Version:** D15Rel 26203.00 (select all languages and workloads)
**OS Version:** Windows 10 RS1_Release 14393.821.170127-1801

**Repro Steps:**
1.  Select PTB through ‘Tools -> Options -> International Settings’.
2.  Create a new C# Console Application via VS.
3.  Right-click the solution and click **‘Restore NuGet Packages’**.
4.  Look at the restore strings in opened **Output** window.

**Expected Result:**
Restore strings are localized.

**Actual Result:**
Restore strings are not localized as below screenshot.
![restorestrings](https://cloud.githubusercontent.com/assets/20632625/22618351/fed67ed2-eb14-11e6-99b8-a7ad47f9c1f3.png)

**Note:**
It repro for all languages.

**Comment by rrelyea** [comment] 2017-02-04 22:50
see output in #4500 -- sometimes it outputs the content localized. Other times it doesn't.

**Comment by mishra14** [comment] 2017-02-06 22:16
The problem is [here](https://github.com/NuGet/NuGet.Client/blob/e856d8605f37606a83fad115b20d7f58445dd071/src/NuGet.Clients/NuGet.SolutionRestoreManager/RestoreOperationLogger.cs#L324).

We have not called used the `CultureInfo.CurrentCulture` while logging. And it is spread through out the file.
This was added by @alpaix with the work on Solution Restore Manager UI.

**Comment by mishra14** [comment] 2017-02-08 00:39
Update: This is happening because 3 dlls (`NuGet.SolutionRestoreManager.dll`,` NuGet.Credentials.dll`, `NuGet.ProjectModel.dll`) are currently not being localized. I have started working on adding them to our artifacts and have informed the vendors.

**Comment by mishra14** [comment] 2017-02-11 03:39
This should be fixed in wsr-tc build #1774. Need to validate.

**Comment by mishra14** [comment] 2017-02-13 20:34
Validated as fixed with wstr-tc build #1778.

**Closed as completed by mishra14** 2017-02-13 20:34 UTC
Labels: Type:Bug, Tenet:WorldReady

**Comment by v-luzh** [comment] 2017-02-14 06:29
Fixed on D15Rel 26213.00 (all languages) + VS.Redist.NuGet VS15.4.0.170213.1779.nupkg as below.
![4505fixed](https://cloud.githubusercontent.com/assets/20632625/22917783/cbe1cca2-f2c1-11e6-96a2-7b1badd4fedf.PNG)
