### ISSUE TITLE
NuGet.VisualStudioExtension: Add solution to TFS and then install-packages will automatically add packages folder to TFS

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#184] opened 2015-03-07 00:06 UTC
Repro step:
1. create a class library project, install some packages
2. Add solution to TFS, which will not add packages folder
3. check in pending changes, install some other packages
4. check pending changes again.

Expected: NuGet should be consistent if Packages folder is considered as the source pending changes

Actual: after step 3, the newly installed packages will be marked with pending changes with their files in Packages folder.

**Comment by feiling** [comment] 2015-05-28 18:39
Dan thinks this is still not fixed.

**Comment by deepakaravindr** [comment] 2015-10-26 22:13
This is a duplicate of https://github.com/NuGet/Home/issues/1356

**Closed by deepakaravindr** 2015-10-26 22:13 UTC
Labels: 2 - Working, Area:VS.Client, Priority:2, Type:Bug
