### ISSUE TITLE
Error reports of invalid or missing transitive NuGet dependencies are unusable

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#13715] opened 2024-08-16 22:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-reports-of-invalid-or-missing-tran/10723823)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.12 Preview 1]
It's great that Visual Studio tells me that it can't resolve a package, but there are no actions that can be taken and no report of where the transitive dependency comes from.

It would be great if when I clicked on the error in the error log in Visual Studio if it took me directly to the package that has the missing transitive dependency

---
#### Feedback Bot on 8/15/2024, 06:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jebriede** [comment] 2024-09-03 21:18
This is a duplicate of: https://github.com/NuGet/Home/issues/13216.

**Closed as not planned by jebriede** 2024-09-03 21:18 UTC
Labels: Resolution:Duplicate, Type:Feature, Area:RestoreCPMTransitiveDependencies, Transferred issue
