### ISSUE TITLE
VS displays transitive packages in Installed tab after removing the only direct dependency

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#12343] opened 2023-01-04 01:44 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS

### Worked before?

I don't think so

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

I found this issue while trying to reproduce https://github.com/NuGet/Home/issues/12333 bug.

- Create a .NET Core Console Application.
- Add `Microsoft.EntityFrameworkCore` package to the project
- Close the solution because of https://github.com/NuGet/Home/issues/12333 bug
- Re-open the solution
- Navigate to `Installed` tab in PM UI. VS displays both top level and transitive packages.
- Remove package reference to `Microsoft.EntityFrameworkCore` package in the `.csproj` file.

**Actual**
- Navigate to `Installed` tab in PM UI. VS displays transitive packages even though the top-level package reference has been removed from the project file.

![image](https://user-images.githubusercontent.com/52756182/210469219-4eff567b-d0f8-4db6-bbdf-e2d23ffdf6d8.png)

**Expected**
- `Installed` tab in PM UI doesn't list any package.

I was under the impression that for package reference projects, we use `project.assets.json` file as source of truth for displaying the packages in PM UI.

**Comment by aortiz-msft** [comment] 2023-01-09 21:34
Looks like a dupe of https://github.com/NuGet/Home/issues/12333

**Closed as completed by aortiz-msft** 2023-01-09 21:34 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:VisualStudioUI, Style:PackageReference
