### ISSUE TITLE
GlobalJsonReader breaking change

### ISSUE THREAD

**Issue by deryaza** [NuGet/Home#11893] opened 2022-06-17 10:01 UTC
Now it looks from solutionpath property, which is breaking. Before it would look down from project dir.

https://github.com/NuGet/NuGet.Client/blob/e9637ed865687c2153da78c6c6385f010277329c/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/GlobalJsonReader.cs#L44

**Comment by jeffkl** [comment] 2022-06-17 21:26
Duplicate of https://github.com/NuGet/Home/issues/11747

The change was made intentionally to make the NuGet-based MSBuild project SDK resolver have the same behavior as the .NET SDK resolver.  More details here: https://github.com/NuGet/Home/issues/11747#issuecomment-1099315888

**Closed as completed by jeffkl** 2022-06-17 21:26 UTC
Labels: Resolution:Duplicate, Type:Bug, Product:MSBuildSDKResolver
