### ISSUE TITLE
Nuget does not report xml parse failures when evaluating the project file and its imports

### ISSUE THREAD

**Issue by chipplyman** [NuGet/Home#12508] opened 2023-03-28 17:20 UTC
### NuGet Product Used

MSBuild.exe

### Product Version

msbuild 17.2.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Create Directory.Build.props containing
`<Project>
  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
  </PropertyGroup>
</Project>`

Remove any mention of TargetFramework from the csproj.

Build with `msbuild -restore`. Confirm successful build.

Break Directory.Build.props - e.g. by adding `<!-- Invalid XML comment -- can't have double hyphen -->`.

Attempt to build with `msbuild -restore`.

Result: Build fails with `Invalid framework identifier ''`

Expected: Build fails with `The imported project file "path\to\Directory.Build.props" could not be loaded. An XML comment cannot contain '--', and '-' cannot be the last character. Line 3, position 27.`

I have seen this issue repro in other cases where the broken xml doesn't fail the restore operation (i.e. it doesn't result in a required property being undefined), but instead causes subtly wrong restore behavior before the main build reports the error.

**Comment by jeffkl** [comment] 2023-04-06 18:56
@chipplyman I think this is a duplicate of https://github.com/dotnet/msbuild/issues/8108.  The reporting of bad XML would have to come from MSBuild itself.  Does the restore fail and the build tells you have you have XML?  Or in this case does the bad import cause restore to fail in strange ways?

**Comment by chipplyman** [comment] 2023-04-06 21:47
Yes this is likely a duplicate of that issue. Looks like same core cause with a different file trigger and different presenting symptoms. 

In this case, the restore fails, telling me "invalid framework identifier".

In order to get an message identifying the xml error, I have to specify the framework identifier elsewhere; e.g. directly in the project file. (after beating my head against "but it's Right There!" for a while.)

**Comment by jeffkl** [comment] 2023-04-10 15:18
Okay sorry for the bad experience.  We hope to improve it soon.  I'm closing this for now as a duplicate of https://github.com/dotnet/msbuild/issues/8108 and https://github.com/NuGet/Home/issues/9300.

**Closed as not planned by jeffkl** 2023-04-10 15:18 UTC
Labels: Resolution:Duplicate, Type:Bug, Area:ErrorHandling, Functionality:Restore
