### ISSUE TITLE
[Bug]: Multitargeting fails to include PackageReadmeFile

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#12485] opened 2023-03-14 15:22 UTC
---
**Issue moved from dotnet/msbuild#8518**
- Please respond to @miloush.

---

_From @miloush on Wednesday, March 1, 2023 11:18:16 PM_

### Issue Description

When multitargeting using `<TargetFrameworks>`, `<None Update` items are not included in the build, making the `PackTask` fail when trying to pack content such as a readme file.

@KirillOsenkov 

### Steps to Reproduce

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
```
\+ something to compile and non-empty _README.md_

### Expected Behavior

Build succeeds.

### Actual Behavior

```
error NU5039: The readme file 'README.md' does not exist in the package.
```

Build succeeds when either `<TargetFramework>` singular is used instead of multitagerting, or, when `<None Include` is used rather than `<None Update`.

### Analysis

In the multitargeting scenario, the first evaluation of the project does not contain `<None>` items, so _\_GetPackageFiles_ target does not produce any items and as a result the readme file is not included in nuspec, hence the error.

### Versions & Configurations

MSBuild version 17.6.0-preview-23081-04+7bf511372
OS version 25300.1000.amd64fre.rs_prerelease.230210-1451
.NET SDK version 8.0.100-preview.1.23115.2

**Comment by erdembayar** [comment] 2023-03-14 18:45
@miloush
Thank you for filing this issue.
For me following setup works, I changed `Update` to `Include`. Could you please try this?

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
```
![image](https://user-images.githubusercontent.com/8766776/225106530-07c66fc0-fd89-400d-a2ad-35b2e2b83b6c.png)

**Comment by KirillOsenkov** [comment] 2023-03-14 18:48
Yes, changing to Include will work, but we need to understand why Update doesn’t work with multitargeting but works without it.

**Comment by miloush** [comment] 2023-03-14 18:48
Thanks for checking @erdembayar, I already noted in _Actual Behavior_ that using `Include` works ... what Kirill said. :)

**Comment by rainersigwald** [comment] 2023-03-14 19:02
I think the default globs don't apply to the outer build (because it doesn't generally care about source files, for instance, so why spend the time to get them off the disk?), but when packing a multitargeted project `@(None)` items are (only?) considered from the outer build.

**Comment by KirillOsenkov** [comment] 2023-03-14 19:24
Interesting, so this might be by design after all? 

@miloush let us know if this is satisfactory or do you feel we need to dig deeper.

**Comment by miloush** [comment] 2023-03-14 20:06
So first of all I had a mental model of `Update` vs `Include` to be similar to _copy newer_ vs _copy always_ and that is obviously incorrect, as the [docs](https://learn.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild?view=vs-2019) suggest that `Update` only modifies metadata of an item. If an item is not included in the first place, it is understandable this has no effect.

While I understand technically why the failure case happens, the difference in behaviour between the multi and single targeting cases is non-intuitive.

I would be willing to admit this as an authoring error and close the issue, however, how come it works in the single targeting scenario? i.e. if `Update` is only updating metadata, how does `<None Update`  include the file in single target in the first place?

**Comment by KirillOsenkov** [comment] 2023-03-14 20:09
I'm guessing when there's only a single target framework, the default items for None kick in, and they pick up the file, which your Update later edits the metadata on.

For multitargeting, I'm guessing they take the None items from the outer build, which didn't pick up the globs (as Rainer explains). So your Update doesn't find the original item to change metadata for.

**Comment by miloush** [comment] 2023-03-14 20:22
I see. "[outer build] doesn't generally care about source files" seems to be in contradiction with `PackageReadmeFile`, `PackageIcon`, `PackageReleaseNotes` etc. properties. Couldn't we make these file path expecting properties automatically include the items in the build?

Otherwise happy for the issue to be closed but it doesn't seem I have a button for that!

**Comment by nkolev92** [comment] 2023-03-16 18:30
Looks like a duplicate 
https://github.com/NuGet/Home/issues/11467, please add a 👍 reaction to upvote the issue

**Closed as completed by nkolev92** 2023-03-16 18:30 UTC
Labels: Type:Bug, Functionality:Pack, Product:dotnet.exe, Transferred issue
