### ISSUE TITLE
Browsing older Klondike server does not work in VS2015 w/ 3.4.1

### ISSUE THREAD

**Issue by jslew** [NuGet/Home#2435] opened 2016-04-01 12:54 UTC
VS2015 w/ Update 2, I can no longer browse an internal Klondike v.1.6.2 server from the UI.  The following error appears in the console:
[Internal] The V2 feed at 'http://nuget.internal.com/api/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net45'&includePrerelease=false&$skip=0&$top=26' returned an unexpected status code '404 Not Found'.

No change when updating to 3.4.1. 

I don't know enough about the API protocol to say why this is a 404, but perhaps the wrong version of the API is being used by the client, since Search() does not appear to be part of the API in my Klondike server's generated documentation.

**Comment by yishaigalatzer** [comment] 2016-04-01 14:50
We tested NuGet with klondike 2.0, the one thing you might need to try is to append api/odata to the server URL

**Comment by yishaigalatzer** [comment] 2016-04-01 14:56
The fix for the URL is in 3.5 branch, we deemed it too risky to take for 3.4.1

**Comment by yishaigalatzer** [comment] 2016-04-01 14:57
https://github.com/NuGet/NuGet.Client/commit/ea16486372d708c7d84a09af98ad7fd9c8804bc1

**Comment by emgarten** [comment] 2016-04-04 21:31
dupe of https://github.com/NuGet/Home/issues/2443

**Closed as completed by emgarten** 2016-04-04 21:31 UTC
Labels: Resolution:Duplicate
