### ISSUE TITLE
[Bug]: Satellite assemblies from projectreference not packed by using "GeneratePackageOnBuild"

### ISSUE THREAD

**Issue by trdsolutions** [NuGet/Home#12153] opened 2022-10-12 13:15 UTC
### NuGet Product Used

dotnet.exe

### Product Version

6.0.401

### Worked before?

No

### Repro Steps & Context

When RESX files are outsourced to it's own library, the project to pack won't include all satellite assemblies:

`C:\Program Files\dotnet\sdk\6.0.401\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5118: File '<Path-to-EntryLibrary>\bin\Debug\netstandard2.0\pl\Translations.resources.dll' is not added because the package already contains file 'lib\netstandard2.0\Translations.resources.dll'`

TLDR; I have setup a [repository](https://github.com/trdsolutions/resx-package-problem). By building it the warning will appear and satellite assemblies are missing.

Basically, there are two libraries:

* The library, that will be packed and shipped and depends on:
* A translations library, that will contain the resources

Package library csproj:

  <Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);PackReferencedProjectOutputs</TargetsForTfmSpecificBuildOutput>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Translations\Translations.csproj" PrivateAssets="all" />
	</ItemGroup>

	<Target Name="PackReferencedProjectOutputs" DependsOnTargets="BuildOnlySettings;ResolveReferences">
		<ItemGroup>
			<BuildOutputInPackage Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))" />
		</ItemGroup>
	</Target>

</Project>

Translations library csrpoj:

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>9.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Update="Strings.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Strings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>

**Comment by trdsolutions** [comment] 2022-10-20 07:16
@dominoFire You added the label "Triage:NeedsRepro". Is there anything more I can do (besides the given repository, I linked in the description)? Do you may know some workaround like a custom build task or something like this?

**Comment by jeffkl** [comment] 2022-10-20 18:10
Related issue: https://github.com/NuGet/Home/issues/3891

**Comment by jeffkl** [comment] 2022-10-20 18:12
Team triage: It looks like your custom build logic needs to place the resource assemblies for each culture in a subfolder because the warning indicates that each assembly is going to be placed in the same folder.

**Comment by trdsolutions** [comment] 2022-10-20 20:32
@jeffkl 

> Related issue: #3891

This issue is regarding packing projectreferences along the package. I solved this as you can see in the csproj file by using this `PackReferencedProjectOutputs` build task

> Team triage: It looks like your custom build logic needs to place the resource assemblies for each culture in a subfolder because the warning indicates that each assembly is going to be placed in the same folder.

This is indeed the correct bugfixing and I think this will need some time, before this fix actually went live; so if you found some workaround (like this `PackReferencedProjectOutputs` thingy), I would be fine by using it so far.

**Comment by nkolev92** [comment] 2022-10-20 23:20
Hey @trdsolutions 

Given that you're custom packing the files, I'm not sure there's anything that the NuGet tooling would need to do here, and I'd like to close this issue. 

Let us know if you disagree.

**Comment by trdsolutions** [comment] 2022-10-21 18:47
Hello @nkolev92,

sorry, I misunderstood something in the first place, but in the end, I actually look for a way to make this custom packaging possible. But I just do not know how. Even in the issue (@jeffkl linked) #3891 I found no answer. 
Can you give me some advice in here? It would be also beneficial for others who might come up to this issue in the future. 

I mean, I know, that I could just forget about this `<GeneratePackageOnBuild>` and create a nuspec file, but I just love the ease of having all of them in the csproj and it was actually the way, that brought me to the packaging stuff in general.

**Comment by zivkan** [comment] 2022-10-21 20:48
I don't know the solution (i hate msbuild, since it's a programming langauge it has so much complexity, but simultaneously makes it so hard to debug and read code to understand how feature work). Anyway, when I clone your repo and I pack Translations.csproj, it packs the satellite assemblies just fine. This means the issue is with the custom script to have multiple projects outputs in the same nupkg, and not a bug with Nuget's supported features.

> NU5118: File '<Path-to-EntryLibrary>\bin\Debug\netstandard2.0\pl\Translations.resources.dll' is not added because the package already contains file 'lib\netstandard2.0\Translations.resources.dll'

This is telling us that `<Path-to-EntryLibrary>\bin\Debug\netstandard2.0\pl\Translations.resources.dll` is getting destination `lib\netstandard2.0\Translations.resources.dll` within the package, not `lib\netstandard2.0\pl\Translations.resources.dll`. That's what I'm not sure how to solve (I've never spent much time with pack), but in case you didn't already understand this this is the root problem, maybe this gives you enough information to find a solution.

**Comment by nkolev92** [comment] 2022-10-21 23:10
You'd basically have to use some of the metadata when you add the BuildOutputInPackage item, 

![image](https://user-images.githubusercontent.com/2878341/197299823-0a3f93a4-4a28-4496-9b54-750f43412bcc.png)

DestinationSubDirectory is one of them.

You can set the `TargetPath` property to direct the exact file path.

**Closed as completed** 2022-10-21 23:10 UTC
Labels: Type:Bug, Resolution:Question, Functionality:Pack, Product:dotnet.exe

**Comment by trdsolutions** [comment] 2022-10-22 18:38
Thanks for the information. I hope some day, someone comes around with the same issue and actually know how to solve it, because I don't know msbuild enough to actually use the information to fix it.
