### ISSUE TITLE
Blank line in the output of find-package jquery.validation 

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#660] opened 2015-05-28 18:10 UTC
Repro steps:
- Open PMC,
- Run `find-package jquery.validation`. The beginning of the output is
```

Id                                  Versions                                 Description                                                                  
--                                  --------                                 -----------                                                                  
jQuery.Validation                   {1.13.1}                                 This jQuery plugin makes simple clientside form validation trivial, while ...
JQuery.Validation.WebForms          {1.1.0}                                  Adds validation groups to JQuery Validation when working with ASP.Net WebF...
jquery.validation.TypeScript.Def... {0.2.7}                                  TypeScript Definitions (d.ts) for jquery.validation. Generated based off t...
DMK.WebForm.JQuery.Validation       {1.0.3}                                  代码库Web窗体框架，JQuery验证插件                                                 
       
ScriptSharp.Lib.jQuery.Validation   {0.7.5.0}                                Allows you to reference and use the jQuery Validation plugin in Script# pr...
jQuery.Validation.Globalize         {1.0.1}                                  An extension to the jQuery Validation Plugin which makes it use Globalize ...
```

Note that there is a blank line after DMK.WebForm.JQuery.Validation. It should not be there.

**Comment by emgarten** [comment] 2015-05-29 17:28
Duplicate of NuGet/Home#683

**Closed by emgarten** 2015-05-29 17:28 UTC
