### ISSUE TITLE
Renaming nuget.exe causes pack to fail

### ISSUE THREAD

**Issue by sclarke81** [NuGet/Home#7040] opened 2018-06-19 11:19 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe

NuGet version (x.x.x.xxx):
4.6.2.5055

OS version (i.e. win10 v1607 (14393.321)):
Win10 v1703 (15063.1088)

Worked before? If so, with which NuGet version:
3.5.0

## Detailed repro steps so we can see the same problem

1. Create a C# .NET Framework 4.5 Class Library project.

2. Enter values for AssemblyCompany and AssemblyDescription in AssemblyInfo.cs.

3. Build the project.

4. Download nuget 4.6.2 (from https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe) and rename to nuget-4.6.2.exe.

5. Run "nuget-4.6.2.exe spec" to generate a nuspec for the project.

6. Run "nuget-4.6.2.exe pack .\ClassLibrary1.csproj" to pack the project. An error is received saying authors and description are required.

7. Rename nuget-4.6.2.exe back to nuget.exe.

8. Run "nuget.exe pack .\ClassLibrary1.csproj" to pack the project. No error is received.

### Verbose Logs

NuGet Version: 4.6.2.5055
Attempting to build package from 'ClassLibrary1.csproj'.
MSBuild auto-detection: using msbuild version '15.7.179.6572' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\
Professional\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'C:\TEMP\ClassLibrary1\bin\Debug'.
Using 'ClassLibrary1.nuspec' for metadata.
Authors is required.
Description is required.
System.Exception: Authors is required.
Description is required.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.CommandLine.ProjectFactory.ProcessNuspec(PackageBuilder builder, String basePath)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean build
IfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

### Sample Project

It's trivial to create, but here's a project and nuspec file created using the above steps.

[ClassLibrary1.zip](https://github.com/NuGet/Home/files/2114971/ClassLibrary1.zip)

**Comment by rohit21agrawal** [comment] 2018-06-19 17:58
Dupe of https://github.com/NuGet/Home/issues/3146

**Closed as completed** 2018-06-19 17:59 UTC
Labels: Resolution:Duplicate
