### ISSUE TITLE
[Bug]: Visual Studio Package Manager Console EFCore Tools not working

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11932] opened 2022-06-30 18:39 UTC
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

17.2.5

### Repro Steps & Context

https://developercommunity.visualstudio.com/t/Visual-Studio-Package-Manager-Console-EF/10079780

**Comment by donnie-msft** [comment] 2022-07-06 16:45
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1559710

**Comment by aortiz-msft** [comment] 2022-07-15 03:37
Closing as dupe of https://github.com/dotnet/efcore/issues/28407

**Closed as completed by aortiz-msft** 2022-07-15 03:37 UTC
Labels: Priority:1, Product:VS.Client, Type:Bug, Product:VS.PMConsole
