### ISSUE TITLE
Nuget Context Sensitive Menu should have "Manage Nuget Packages"

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7958] opened 2019-04-04 18:40 UTC
<p>Could you Add &quot;Manage Nuget Packages&quot; to the context sensitive menu when selecting the Nuget node? I know its there on Dependencies but I still right click on Nugets intuitively.  </p><p><a href="https://pbs.twimg.com/media/DzV7zOzVAAA0sLy.png:large"> Image:DzV7zOzVAAA0sLy.png:large</a></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/457905/nuget-context-sensitive-menu-should-have-manage-nu.html
VSTS ticketId: 792883_
_These are the original issue comments:_

Jane Wu [MSFT] on 2/15/2019, 02:11 AM (48 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by anangaur** [comment] 2019-04-04 22:54
Another similar request captured here: https://developercommunity.visualstudio.com/content/idea/474749/vs2019-nuget-packages-folder-doesnt-manage-nuget-p.html

**Comment by donnie-msft** [comment] 2019-08-05 15:55
Duplicate of issue https://github.com/NuGet/Home/issues/5049

**Closed as completed by donnie-msft** 2019-08-05 15:55 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Feature, Functionality:VisualStudioUI
