### ISSUE TITLE
Address possible break of project installation after retry install due to certain incompatible framework

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#9943] opened 2020-08-25 23:21 UTC
## Details about Problem
Worked before? N/A
During my performance improvement work #[PR3559](https://github.com/NuGet/NuGet.Client/pull/3559) Nikolche [pointed out](https://github.com/NuGet/NuGet.Client/pull/3559/files#r475033357) potential bug where initially success installation package break due to re-evaluation.

## Detailed repro steps so we can see the same problem
N/A : Not sure it's just possible bug.

**Comment by kartheekp-ms** [comment] 2020-08-26 20:01
Duplicate of #9944

**Closed as completed by kartheekp-ms** 2020-08-26 20:01 UTC
Labels: Product:VS.Client, Functionality:VisualStudioUI, Functionality:Restore
