### ISSUE TITLE
Target nuget.exe to .Net Core

### ISSUE THREAD

**Issue by konjac** [NuGet/Home#13330] opened 2024-03-18 01:45 UTC
### NuGet Product(s) Involved

NuGet.exe

### The Elevator Pitch

The current nuget.exe is targeting .Net framework. Users on Linux are using Mono as a workaround. 

But Mono is on the deprecation path. It will be more friendly if nuget.exe could be executed on Linux through .Net Core.

**Comment by jeffkl** [comment] 2024-03-18 18:44
A lot of the functionality of `nuget.exe` has been ported to `dotnet nuget` which is cross-platform.  Does `dotnet nuget` contain the features you need?

https://learn.microsoft.com/nuget/reference/dotnet-commands

**Comment by konjac** [comment] 2024-03-19 01:10
@jeffkl I am expecting `nuget install`.  Some tools are distributed as nupkg. With `nuget install`, we can easily download and extract them without initializing a project.

Or could you consider porting `nuget install` to `dotnet nuget install`?

**Comment by jeffkl** [comment] 2024-03-19 17:53
In that case, I'm closing this as a duplicate of https://github.com/NuGet/Home/issues/12513.  Please add a 👍 reaction to upvote that issue.

**Closed as not planned by jeffkl** 2024-03-19 17:53 UTC
Labels: Resolution:Duplicate, Type:Feature
