### ISSUE TITLE
Make an option to fail nuget pack if project has pre-release dependencies

### ISSUE THREAD

**Issue by shytikov** [NuGet/Home#6215] opened 2017-11-22 15:33 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (4.4.1.4656):

Worked before? If so, with which NuGet version: 3.5.0.1996

## Detailed repro steps so we can see the same problem

Issue introduced by https://github.com/NuGet/NuGet.Client/pull/1073 and https://github.com/NuGet/Home/issues/1365

Basically after these fixes old behavior was gone. Right now `nuget` is not failing on packing projects with pre-release dependencies. 

But what if old behavior was the main part of our CI workflow? We used it to detect if we have forgot to update our dependencies after final release or not. Now this is not possible anymore, since fix implemented is not backwards-compatible.

Is it possible to implement, for example, switch "Treat warnings as errors", so old behavior still would be possible to simulate?

**Comment by PatoBeltran** [comment] 2017-11-22 23:24
Hey @shytikov thanks for submitting the issue! The intended behavior of this feature is to let package authors package their projects when they added release versions based on the assumption that package authors do this on purpose. This issue was fixed last year as it impacted a lot of customers.

I agree with you that our `pack` command is needs an option to be able to treat warnings as errors. We recently added some infrastructure for this in our `restore` command. I've created an issue to track this effort (https://github.com/NuGet/Home/issues/6217) and will close this issue in favor of that one, please feel free to continue the discussion there.

As in for your specific scenario, NuGet does not currently have a workaround for this. A way this could be solved is to write a script that checks the packages in the CI and specifically looks for pre-released versions.

**Closed as completed by PatoBeltran** 2017-11-22 23:24 UTC
Labels: Product:NuGet.exe, Functionality:Pack
