### ISSUE TITLE
Installing a DotnetPlatform package locally

### ISSUE THREAD

**Issue by glibnub** [NuGet/Home#8234] opened 2019-06-14 18:07 UTC
## Details about Problem

NuGet product used: `nuget.exe`

NuGet version:  5.0.2.5988

dotnet.exe --version : 2.1.602

VS version: 2019

OS version: Windows 10 1809 (17763.557)

Worked before? No

## Detailed repro steps so we can see the same problem

1. Run the command to install package locally from the CLI:

```powershell
.\nuget.exe install 'Microsoft.AspNetCore.App.Ref' -Version 3.0.0-preview5-19227-01
```

Notice that the process will fail with:

```powershell
Error NU5000: Package 'Microsoft.AspNetCore.App.Ref 3.0.0-preview5-19227-01' has a package type 'DotnetPlatform' that is not supported by project 'C:\bin'.
```

Is there a way to install a `DotnetPlatform` package locally through the CLI?

### Verbose Logs

```powershel
Attempting to gather dependency information for package 'Microsoft.AspNetCore.App.Ref.3.0.0-preview5-19227-01' with respect to project 'C:\bin', targeting 'Any,Version=v0.0'
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\microsoft.aspnetcore.app.ref\3.0.0-preview5-19227-01\microsoft.aspnetcore.app.ref.3.0.0-preview5-19227-01.nupkg
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/microsoft.aspnetcore.app.ref/index.json
Total number of results gathered : 3
Gathering dependency information took 204.09 ms
Summary of time taken to gather dependencies per source :
C:\Users\dendeli\.nuget\packages\       -       26.17 ms
https://api.nuget.org/v3/index.json     -       47.46 ms
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\    -       9.24 ms
Attempting to resolve dependencies for package 'Microsoft.AspNetCore.App.Ref.3.0.0-preview5-19227-01' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.AspNetCore.App.Ref.3.0.0-preview5-19227-01'
Resolved actions to install package 'Microsoft.AspNetCore.App.Ref.3.0.0-preview5-19227-01'
Retrieving package 'Microsoft.AspNetCore.App.Ref 3.0.0-preview5-19227-01' from 'C:\Users\dendeli\.nuget\packages\'.
WARNING: Install failed. Rolling back...
Executing nuget actions took 73.14 ms
Error NU5000: Package 'Microsoft.AspNetCore.App.Ref 3.0.0-preview5-19227-01' has a package type 'DotnetPlatform' that is not supported by project 'C:\bin'.
NuGet.Packaging.Core.PackagingException: Package 'Microsoft.AspNetCore.App.Ref 3.0.0-preview5-19227-01' has a package type 'DotnetPlatform' that is not supported by project 'C:\bin'.
   at NuGet.PackageManagement.InstallationCompatibility.EnsurePackageCompatibility(NuGetProject nuGetProject, PackageIdentity packageIdentity, NuspecReader nuspecReader)
   at NuGet.PackageManagement.InstallationCompatibility.<EnsurePackageCompatibilityAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteInstallAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__40.MoveNext()
```

**Comment by nkolev92** [comment] 2019-06-14 18:16
Unfortunately there's no super straightforward way.

This is a duplicate of https://github.com/NuGet/Home/issues/6849.

As a messy workaround you can try adding it to a project, where it will end up in the global packages folder, and pick it up from there.

**Closed as completed by nkolev92** 2019-06-14 18:16 UTC
Labels: Resolution:Duplicate, Product:NuGet.exe, Functionality:Install
