### ISSUE TITLE
Invalid restore input. Invalid target framework 'unsupported': BUILDING F# repo using dogfood build of visual studio

### ISSUE THREAD

**Issue by KevinRansom** [NuGet/Home#9967] opened 2020-08-31 20:16 UTC
With the dogfood build of visual studio and using the Developer command prompt from that build the F# build fails with the message:
````
Build FAILED.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(130,5): error : Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\Users\WDAGUtilityAccount\.nuget\packag
es\microsoft.dotnet.arcade.sdk\5.0.0-beta.20407.3\tools\Tools.proj. [C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20407.3\tools\Tools.proj]
    0 Warning(s)
    1 Error(s)
````

Repro:
1.   Install latest vs dogfood build from here: 
      https://aka.ms/vs/dogfood/install
      Select .NetDesktop Framework, Desktop development with C++, Visual Studio extensions workloads to be installed
![image](https://user-images.githubusercontent.com/5175830/91754702-b5fec200-eb7e-11ea-8694-8d401352f4a1.png)
2.  Using vs git clone:  https://github.com/dotnet/fsharp.git
3.  Open a Visual Studio 2019 Developer Command Prompt v16.8.0-pre.3.0
4.  Change directory to the cloned fsharp repo
5.  run the build command
eventually observe:
````
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:04:15.35
VisualFSharp.sln:
  Determining projects to restore...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(130,5): error : Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\Users\WDAGUtilityAccount\.nuget\packag
es\microsoft.dotnet.arcade.sdk\5.0.0-beta.20407.3\tools\Tools.proj. [C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20407.3\tools\Tools.proj]

Build FAILED.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(130,5): error : Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\Users\WDAGUtilityAccount\.nuget\packag
es\microsoft.dotnet.arcade.sdk\5.0.0-beta.20407.3\tools\Tools.proj. [C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20407.3\tools\Tools.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.19
Build failed.

C:\Users\WDAGUtilityAccount\source\repos\fsharp>
````

If I copy from an rtm vs install the contents of the directory:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet

To the same place in the preview install and do a build it succeeds

This is blocking our ability to use dogfood Visual Studios.  I believe it only showed up this week.

Thanks

Kevin

**Comment by nkolev92** [comment] 2020-08-31 23:51
Hey Kevin, 

your issue seems related to a breaking behavior NuGet + SDK had to introduce about the Target Framework concept.
The arcade SDK needed to set the TargetFrameworkMoniker in order for NuGet to not return unsupported.

That was done over the last few weeks, so I'd expect upgrading to the latest arcade should fix this problem. 
https://github.com/dotnet/arcade/pull/5996/files and https://github.com/dotnet/arcade/commit/3b720900ac55e9cc3675584c41da6460d6193f37. 

Note that I haven't investigated the particular repro but I am making an assumption based on the symptoms observed.

**Comment by KevinRansom** [comment] 2020-08-31 23:52
Okay, thanks, I will investigate.  Although I think we are up todate on arcade,

**Comment by KevinRansom** [comment] 2020-08-31 23:55
Yes, that does look like it might cause the issue we are seeing.

**Comment by zkat** [comment] 2020-09-10 17:55
closing as duplicate of https://github.com/dotnet/fsharp/issues/10036 (which is resolved now)

**Closed as completed by zkat** 2020-09-10 17:55 UTC
Labels: Functionality:Restore, Product:dotnet.exe, WaitingForCustomer
