### ISSUE TITLE
NuGet.config settings are not enforced between workspaces

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1481] opened 2015-09-29 13:40 UTC
_From @theo-albers on September 29, 2015 13:0_

We have a workspace like this:
- src
  - build
  - build-output
  - solution-folder-1
  - ...
  - solution-folder-n

We have release branches in TFS. We have local NuGet packages with a hard coded version number, so in release branch v1.0 we have NuGet package abc-1.0.0, but in release branch v2.0 we also have abc-1.0.0. The packages are different, content wise. This is the way it has worked well in the past.
With the latest NuGet version in VS2013, 2.8.60723.765, we have problems with workspace isolation. When I create two workspaces;
- c:\dev\src-v1.0 for our release 1.0, TFS workspace v1-0 
- c:\dev\src for our trunk version, TFS workspace trunk

NuGet will resolve NuGet packages from 1 workspace build-output folder. So when I build the trunk version, it uses the packages local to the trunk build-output folder. When I switch workspaces and open a solution in the v1-0 workspace, it will still use the packages local to trunk. It should have used the build-output folder of the v1-0 workspace. This problem persists even after closing VS or cleaning the package cache. 
We have a NuGet.config like this in each solution .nuget folder. 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>

  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>

  <packageSources>
    <remove key="Itesso package source" />
    <add key="Itesso package source" value="..\..\build-output\packagesource" />
  </packageSources>

  <activePackageSource>
    <add key="All" value="(Aggregate source)"  />
  </activePackageSource>

</configuration>
```

When I open the settings dialog in VS I see it picks up the correct NuGet.config settings for the package source. The only way to eliminate the problem is to remove the trunk workspace from disk. It's very disturbing that we can't rely on package isolation per workspace. 

_Copied from original issue: NuGet/NuGetGallery#2709_

**Comment by emgarten** [comment] 2015-09-29 23:28
NuGet does not look at workspaces and it is difficult to tell what is going on here from the folder structure.

There was previously an issue with relative paths in nuget.config. Does it work if you change these to absolute paths?

You can also try running nuget.exe sources   from the solution folders to see what the sources are.

**Comment by theo-albers** [comment] 2015-09-30 13:01
Thanks for the quick reply. I know about the relative path issue, something we ran into before and has been fixed by the latest nuget version. 
Anyway I replayed the whole story once more to see if I could reproduce it and guess what: I can't. The best thing would be to close the ticket. Maybe the problem was related to my machine state. We open and close various solutions during the day. I have to say that we have older nuget.exe for released application versions, since they are checked in as part of the environment. Each solution folder has it's .nuget folder with nuget.exe and nuget.config. Wouldn't it be nice if we could point to a common .nuget folder, shared across solution folder ;-)

**Comment by yishaigalatzer** [comment] 2015-10-06 04:40
NuGet.config is designed to be per solution, though since it is hierarchical you can place it above the solution level (if all your solutions are installed/checked out into the same folder structure).

For nuget.exe you can definitely share an implementation by dropping it into a common folder, and running nuget.exe restore from a script rather as part of msbuild.

Anyways based on your feedback I'm closing this issue.

**Closed as completed by yishaigalatzer** 2015-10-06 04:40 UTC
