### ISSUE TITLE
Extremely slow Pack with version >= 4.1

### ISSUE THREAD

**Issue by StefanoVuerich** [NuGet/Home#7188] opened 2018-08-09 08:06 UTC
I'm reporting an extremely slow pack using Nuget >= 4.1 on VSTS.

Using version >= 4.1 the pack takes about 7 minutes using 50% CPU. 
With 3.5 only 1.5 minute.

Here is the problematic file entry(removing that one speed up the pack process).

`<file src="..\ThePathIUse\net461\win7-x64\publish\**\*.*" target="" exclude="**\*.exe"/>`

And here is the stack i collect using ProcessHacker

0, ntoskrnl.exe!_misaligned_access+0xc06
1, ntoskrnl.exe!KeWaitForMultipleObjects+0x140f
2, ntoskrnl.exe!KeWaitForMultipleObjects+0xcb9
3, ntoskrnl.exe!KeWaitForMutexObject+0x2c0
4, ntoskrnl.exe!_misaligned_access+0x7c
5, ntoskrnl.exe!_misaligned_access+0xca9
6, ntoskrnl.exe!KeSynchronizeExecution+0x4133
7, System.Text.RegularExpressions.RegexInterpreter.Go() + 0x11b6 <-- System.ni.dll+0x2cf9f6
8, System.Text.RegularExpressions.RegexRunner.Scan(System.Text.RegularExpressions.Regex, System.String, Int32, Int32, Int32, Int32, Boolean, System.TimeSpan) + 0x137 <-- System.ni.dll+0x2ce1d7
9, System.Text.RegularExpressions.Regex.Run(Boolean, Int32, System.String, Int32, Int32, Int32) + 0xd4 <-- System.ni.dll+0x2cde64
10, System.Text.RegularExpressions.Regex.IsMatch(System.String, Int32) + 0x37 <-- System.ni.dll+0x2c7bf7
11, System.Linq.Enumerable.Any[[System.__Canon, mscorlib]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>) + 0xb3 <-- System.Core.ni.dll+0x2f1cd3
12, System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib]].MoveNext() + 0x4e <-- System.Core.ni.dll+0x2f0c2e
13, System.Collections.Generic.HashSet`1[[System.__Canon, mscorlib]].UnionWith(System.Collections.Generic.IEnumerable`1<System.__Canon>) + 0xaf <-- System.Core.ni.dll+0x2f45af
14, System.Collections.Generic.HashSet`1[[System.__Canon, mscorlib]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>) + 0x9c <-- System.Core.ni.dll+0x2f449c
15, NuGet.Common.PathResolver.FilterPackageFiles[[System.__Canon, mscorlib]](System.Collections.Generic.ICollection`1<System.__Canon>, System.Func`2<System.__Canon,System.String>, System.Collections.Generic.IEnumerable`1<System.String>) + 0x8a <-- 0x7ffebaf3519a
16, NuGet.Packaging.PackageBuilder.ExcludeFiles(System.Collections.Generic.List`1<NuGet.Packaging.PhysicalPackageFile>, System.String, System.String) + 0x13b <-- 0x7ffebaf34d0b
17, NuGet.Packaging.PackageBuilder.AddFiles(System.String, System.String, System.String, System.String) + 0x115 <-- 0x7ffebaf310c5
18, NuGet.Packaging.PackageBuilder.PopulateFiles(System.String, System.Collections.Generic.IEnumerable`1<NuGet.Packaging.ManifestFile>) + 0x73 <-- 0x7ffebaf30ea3
19, NuGet.Packaging.PackageBuilder.ReadManifest(System.IO.Stream, System.String, System.Func`2<System.String,System.String>) + 0x77 <-- 0x7ffebadc9c37
20, NuGet.Packaging.PackageBuilder..ctor(System.String, System.String, System.Func`2<System.String,System.String>, Boolean) + 0x7a <-- 0x7ffebadc974a
21, NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(System.String) + 0xee <-- 0x7ffebadc961e
22, NuGet.Commands.PackCommandRunner.BuildFromNuspec(System.String) + 0x19 <-- 0x7ffebadc93e9
23, NuGet.CommandLine.PackCommand.ExecuteCommand() + 0x2d1 <-- 0x7ffebadc7851
24, NuGet.CommandLine.Command.ExecuteCommandAsync() + 0x15 <-- 0x7ffebadc7535
25, NuGet.CommandLine.Command.Execute() + 0x1ba <-- 0x7ffebadbf35a
26, NuGet.CommandLine.Program.MainCore(System.String, System.String[]) + 0x52f <-- 0x7ffebac826ef
27, NuGet.CommandLine.Program.Main(System.String[]) + 0x1d <-- 0x7ffebac801ed
28, clr.dll+0x3753
29, clr.dll+0x361c
30, clr.dll+0x44d3
31, clr.dll!CorExeMain+0xecd
32, clr.dll!CorExeMain+0xcb6
33, clr.dll!CorExeMain+0xbf4
34, clr.dll!CorExeMain+0x122
35, clr.dll!CorExeMain+0xd2
36, clr.dll!CorExeMain+0x14
37, mscoreei.dll!CorExeMain+0x5d
38, mscoree.dll!CorExeMain+0xcb
39, kernel32.dll!BaseThreadInitThunk+0x22
40, ntdll.dll!RtlUserThreadStart+0x34

**Comment by rohit21agrawal** [comment] 2018-08-13 23:05
dupe of https://github.com/NuGet/Home/issues/5016

**Closed as completed by rohit21agrawal** 2018-08-13 23:05 UTC
Labels: Resolution:Duplicate, Triage:Investigate, Tenet:Performance, Functionality:Pack
