### ISSUE TITLE
We use the csproj to build the nuget package. So how do I extend the dependencies from csproj?

### ISSUE THREAD

**Issue by jetersen** [NuGet/Home#9153] opened 2020-02-02 01:43 UTC
having csproj and nuspec named the same and merging them is not explained at all

Tokens such as `$CommonMetadataElements$` and `$CommonFileElements$` are not documented and google searches are not great either for explaining them.

I wonder if there are other special tokens I am not aware of.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment] 2020-02-08 00:11
@casz - I have moved this issue since this was no longer about documentation. Please fill out this template to helo the team triage the issue:

Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

## Other suggested things

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment] 2020-04-06 22:20
This is not possible today, you have to handcraft your nuspec. 

Duplicate of https://github.com/NuGet/Home/issues/8133

**Closed as completed by nkolev92** 2020-04-06 22:21 UTC
Labels: Resolution:Duplicate, Functionality:Pack
