### ISSUE TITLE
Allow package-dependent selection of Projects in Solution PMUI

### ISSUE THREAD

**Issue by Semax** [NuGet/Home#2660] opened 2016-04-26 15:04 UTC
I'm using VS2015 Update 2 with NuGet 3.4.3.855. In NuGet UI, despite the fixes in #1896 pressing the spacebar checks only the latest selected project instead of all selected projects. And it gets really annoying to check several dozens of projects among hundreds. Could you please make spacebar check all the selected projects?
And it also would be great if you added a quick way to check all projects that are referencing the selected package (maybe Ctrl + click on the checkbox in the table header).
Thanks.

**Comment by rrelyea** [comment] 2016-04-26 22:04
Thanks for the report.

**Comment by yishaigalatzer** [comment] 2016-05-02 17:13
We could also consider a filter feature (by project name perhaps?), not sure if it fits within this improvement as it will require more design.

**Comment by donnie-msft** [comment] 2020-11-03 04:35
In 16.8, spacebar does indeed work on the Select All checkbox.
Reframing this Issue to the secondary request to support ways to select Projects that have the selected project installed.

**Comment by donnie-msft** [comment] 2020-11-03 05:18
Since this issue was more focused around something that is already shipped, I'm going to close the 2nd request as a duplicate.
Dupe of https://github.com/NuGet/Home/issues/9081

**Closed as completed by donnie-msft** 2020-11-03 05:18 UTC
Labels: Resolution:Duplicate, Priority:3, Type:DCR, Functionality:VisualStudioUI, Tenet:Accessibility
