### ISSUE TITLE
Error List is not cleared of package install errors in CodeSpaces after doing another install / uninstall action

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#10545] opened 2021-02-04 23:33 UTC
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Visual Studio

Product version: 16.10 Preview 1

Worked before? If so, with which NuGet version: In local scenarios it works

## Repro steps and/or sample project

1. Open PMUI
2. Click on Browse Tab
3. Search for System.Linq.Expressions and install version 4.0.0
4. Search for Moq install version 4.16.0
5. An expected error will occur and be shown in the Error List: "Detected package downgrade: System.Linq.Expressions from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version."
6. Now, uninstall System.Linq.Expressions or do any other install / uninstall action that does not result in an error.

Expected:
The error messages should be cleared from the Error List.

Actual:
The error messages from the failed operation of trying to install Moq after installing an older version of System.Linq.Expressions than what Moq requires persist in the Error List and in every action taken, they show up again which creates confusion, giving the impression that the errors occurred again.

This works in a non-Codespaces scenario

![image](https://user-images.githubusercontent.com/10777837/106968652-1f6e9800-66fe-11eb-9648-45150ab7a813.png)

**Comment by rrelyea** [comment] 2021-02-05 18:47
targeting 16.10, as standalone works fine, which is 16.9 qb mode priority.

**Comment by rrelyea** [comment] 2021-02-05 18:49
believe it is a dupe of #10140

**Comment by donnie-msft** [comment] 2024-01-19 00:53
Closing CodeSpaces issues.

**Closed as completed by donnie-msft** 2024-01-19 00:53 UTC
Labels: Priority:2, Type:Bug, Functionality:VisualStudioUI, Functionality:Install
