### ISSUE TITLE
Remove IPackageSourceProvider2 and related types

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#10098] opened 2020-10-01 00:12 UTC
we created a few types in 16.8p3
we want to remove them, but the clock is out for 16.8.
we hope to insert a simple addition of [Obsolete] to the new apis in p4.
likely will be able to remove in 16.9.

this issue is linked from the obsolete attributes.

**Comment by zivkan** [comment] 2021-01-12 17:16
duplicate of https://github.com/nuget/home/issues/10015

**Closed as completed by zivkan** 2021-01-12 17:16 UTC
Labels: Priority:1, Functionality:SDK, Type:Bug
