### ISSUE TITLE
nuget pack should support required properties

### ISSUE THREAD

**Issue by lzybkr** [NuGet/Home#6496] opened 2018-01-29 18:03 UTC
## Details about Problem

NuGet.exe 4.3.0.4406 - Win10

## Detailed repro steps so we can see the same problem

If my nuspec has replacement tokens, the experience is not great if a property is not set. For example, if I have:

```
    <version>$version$</version>
```

and run `nuget pack foo.nuspec`, I get an error like:

```
Attempting to build package from 'foo.nuspec'.
Value cannot be null or an empty string.
Parameter name: value
```

But if I instead have something like:

```
  <files>
    <file src="$root$\*" target="content" />
  </files>
```

Then I might pack the wrong thing, or if I'm lucky, the path won't be valid and I'll get an error like:

```
Attempting to build package from 'foo.nuspec'.
Could not find a part of the path '\Release\foo.dll'.
```

If `nuget pack` had a parameter `-StrictProperties`, then you could report a nice error saying which property wasn't specified.

**Comment by rohit21agrawal** [comment] 2018-01-29 20:51
thanks for the suggestion @lzybkr , we do plan on making improvements to this area in the future.

**Comment by jainaashish** [comment] 2018-02-02 00:54
dupe of https://github.com/NuGet/Home/issues/2714

**Closed as completed by jainaashish** 2018-02-02 00:54 UTC
Labels: Resolution:Duplicate, Functionality:Pack, Area:ErrorHandling
