### ISSUE TITLE
Supporting Package Reference in UWP WPF WinForms and Classic Libraries

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#3561] opened 2016-09-29 22:52 UTC
Spec for the work is available here - https://github.com/NuGet/Home/wiki/Supporting-Package-Reference-in-UWP-WPF-WinForms-and-Classic-Libraries/_edit

**Comment by rrelyea** [comment] 2016-10-12 17:05
Dupe of #3533

**Closed as completed by rrelyea** 2016-10-12 17:05 UTC
Labels: Resolution:Duplicate
