### ISSUE TITLE
Consume NuGet /embed assets group for interop type assemblies from NuGet package

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8062] opened 2019-04-25 21:50 UTC
@jainaashish did some work to support package authors to influence when assemblies have EmbedInteropTypes set to true in projects that reference their package.  See:

* Issue:  https://github.com/NuGet/Home/issues/2365
* Spec:  [Embed Interop Types with PackageReference](https://github.com/NuGet/Home/wiki/Embed-Interop-Types-with-PackageReference
* PR:  https://github.com/NuGet/NuGet.Client/pull/2532

The VS project system needs to consume the updated asset file and embed interop types appropriately.

(The corresponding .NET SDK change is tracked via https://github.com/dotnet/sdk/issues/2732.)

**Comment by jainaashish** [comment] 2019-04-26 06:03
NuGet doesn't own this repo, instead Project system does. Last I knew Juan owned it, you can check with Rob.

**Comment by nkolev92** [comment] 2020-04-21 22:21
Duplicate of https://github.com/dotnet/NuGet.BuildTasks/issues/69.

**Closed as completed by nkolev92** 2020-04-21 22:22 UTC
Labels: Type:DCR, Resolution:External, Partner:Project-System
