### ISSUE TITLE
Cannot uninstall/fix a packages.config project that has a missing package that does not exist at one of the sources

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#9335] opened 2020-03-23 22:38 UTC
## Details about Problem
Version 16.6.0 Preview 2.0 [29919.92.master]
## Detailed repro steps so we can see the same problem

1. Download and extract https://github.com/dotnet/project-system/files/2062473/VSIXProject2.zip
2. Open project and save solution
3. Attempt to build

Get this build error (is the stack intended?)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project VSIXProject2: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to find version '15.8.1122' of package 'Microsoft.VSSDK.BuildTools'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Microsoft.VSSDK.BuildTools.15.8.1122' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://dotnet.myget.org/F/roslyn/api/v3/index.json: Package 'Microsoft.VSSDK.BuildTools.15.8.1122' is not found on source 'https://dotnet.myget.org/F/roslyn/api/v3/index.json'.
  https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json: Package 'Microsoft.VSSDK.BuildTools.15.8.1122' is not found on source 'https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json'.
  https://api.nuget.org/v3/index.json: Package 'Microsoft.VSSDK.BuildTools.15.8.1122' is not found on source 'https://api.nuget.org/v3/index.json'.

   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<RestorePackageAsync>d__81.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageRestoreManager.<RestorePackageAsync>d__39.MoveNext(). Please see Error List window for detailed warnings and errors.				

```

4. Right-click on project and choose Manage NuGet Packages
5. Click installed tab and search for buildtools
6. Attempt to uninstall

Expected: The package to be uninstalled
Actual:

![image](https://user-images.githubusercontent.com/1103906/77369664-3c82cc80-6db3-11ea-906e-7027349aea97.png)

There appears to be no way to uninstall this package.

**Comment by rrelyea** [comment] 2020-03-25 17:26
Dupe of closed issue: https://github.com/NuGet/Home/issues/3077 (see workarounds there)
cc @aortiz-msft

**Closed as completed by rrelyea** 2020-03-25 17:26 UTC
Labels: Resolution:Question, Style:Packages.Config
