### ISSUE TITLE
[NuGet.PackageManagement] The feature of packages.<projectName>.config is not ported to NuGet 3.0 yet

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#376] opened 2015-04-07 17:27 UTC
run-test UpdatePackagePreservesProjectConfigFile 
run-test InstallPackageAddMoreEntriesToProjectConfigFile 
run-test InstallPackageToWebsitePreservesProjectConfigFile 
run-test InstallPackagePreservesProjectConfigFile

**Comment by deepakaravindr** [comment] 2015-05-01 20:53
This is a duplicate of #74

**Closed by deepakaravindr** 2015-05-01 20:53 UTC
Labels: 1 - Ready, Area:VS.Client, Priority:1, Type:Bug
