### ISSUE TITLE
Visual Studio Package Manager does not respect EditorConfig settings when editing Directory.Packages.props

### ISSUE THREAD

**Issue by reduckted** [NuGet/Home#12226] opened 2022-11-10 01:53 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

v17.4.0

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Here is an example solution: [DirectoryPropsEditorConfig.zip](https://github.com/NuGet/Home/files/9976557/DirectoryPropsEditorConfig.zip)

1. Open the solution in Visual Studio.
2. Open the `Directory.Packages.props` file. It looks like this (note that it ends with a blank line):
```xml
<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Moq" Version="4.18.1" />
    </ItemGroup>
</Project>

```
3. Open NuGet Package Manager for the solution.
4. Update `Moq` to 4.18.2.
5. The `Directory.Packages.props` file now looks like this (note that it does not end with a blank line):
```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Moq" Version="4.18.2" />
  </ItemGroup>
</Project>
```
6. Save the `Directory.Packages.props` file. 
7. The `Directory.Packages.props` file now uses four spaces for indentation and ends with a new line like it originally did.

Since this file has to be manually edited for some things (for example, to add the `CentralPackageTransitivePinningEnabled` property or add `GlobalPackageReference` items), I expect that any tools that automatically edit the file will respect the EditorConfig settings.

**Comment by donnie-msft** [comment] 2022-11-11 23:47
hello, @tmeschter - do you know whether writing `Directory.Packages.props` honors the VS editorConfig? Thank you!

**Comment by nkolev92** [comment] 2022-11-17 19:22
Duplicate of the partner issue: https://github.com/dotnet/project-system/issues/5427

**Closed as completed** 2022-11-17 19:22 UTC
Labels: Type:Bug, Resolution:External, Partner:Project-System
