### ISSUE TITLE
props file of nuget VC++ (native) package is not added to ExtensionSettings import group

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10125] opened 2020-10-15 00:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1002251/props-file-of-nuget-vc-native-package-is-not-added.html)._

---
If I add a nuget package to a VC++ project (vcxproj), the props file from packages build\native folder is not added to the `<ImportGroup Label="ExtensionSettings">`. Instead the import is placed at the beginnig of the project file.

The targets file instead is correctly added to the `<ImportGroup Label="ExtensionTargets">`.

The positioning of build customizations is defined here: [ExtensionSettings ImportGroup element](https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=vs-2019#extensionsettings-importgroup-element).

Thank you for fixing this.

---
#### Feedback Bot on 4/23/2020, 00:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### kapenaga [MSFT] on 5/5/2020, 05:54 PM: 

<p>Unable to reproduce this issue on the following installation of Visual Studio. Can you please upload a sample project to reproduce this issue?</p>
<p>Microsoft Visual Studio Professional 2019<br>
Version 16.3.10<br>
VisualStudio.16.Release/16.3.10+29519.87</p>

#### Jojakim Stahl on 5/11/2020, 03:15 AM: 

<p>Attached I sent you an example for this. The project history is included, you can see how it evolves in the git log.</p><p>What I did:</p><ol><li>Create a new VC++ Console App</li><li>Create a new Sample package with props and targets file (see in folder SamplePackage)</li><li>Build the sample package with "nuget pack"</li><li>Add the SamplePackage folder to the package sources in Visual Studio</li><li>Add the Package "Sample" to the Console App project. That inserts the import of the props file as the first line of the vcxproj file.</li></ol><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/134003-consoleapplication3.zip">consoleapplication3.zip</a></p><p>Hope this helps to track down the problem.</p>

#### Feedback Bot on 5/18/2020, 09:10 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 5/18/2020, 09:10 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by kartheekp-ms** [comment] 2020-10-15 01:06
I can reproduce the issue following steps mentioned in the feedback ticket. The logic [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/Projects/MSBuildNuGetProject.cs#L361-L362) adds `.props` file to the `Top` location and `.targets` file `Bottom` location. This change was introduced in this [PR](https://github.com/NuGet/NuGet.Client/pull/1435) to fix a [UI delay](https://github.com/NuGet/Home/issues/4436) Tagging Rob @rrelyea for additional information about this logic.

**Comment by nkolev92** [comment] 2020-10-26 20:43
@heng-liu Can you please validate that this is indeed a regression. 

If yes, would you please address as part of a quality week.

**Comment by heng-liu** [comment] 2020-11-02 21:27
I could repro on VS16.6, 16.7, 16.8 preview3 and 16.9 int preview2.
So this should not be a regression from previous RTM.

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\Sample.0.0.1\build\native\Sample.props" Condition="Exists('..\packages\Sample.0.0.1\build\native\Sample.props')" />
```

```
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
    <Import Project="..\packages\Sample.0.0.1\build\native\Sample.targets" Condition="Exists('..\packages\Sample.0.0.1\build\native\Sample.targets')" />
  </ImportGroup>
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Sample.0.0.1\build\native\Sample.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Sample.0.0.1\build\native\Sample.props'))" />
    <Error Condition="!Exists('..\packages\Sample.0.0.1\build\native\Sample.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Sample.0.0.1\build\native\Sample.targets'))" />
  </Target>
```

**Comment by nkolev92** [comment] 2020-11-02 21:42
removing the high priority status.

@heng-liu Should we move this to `New Issues` to get it retriaged?

**Comment by heng-liu** [comment] 2020-11-03 00:22
The complete content is:
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\packages\Sample.0.0.1\build\native\Sample.props" Condition="Exists('..\packages\Sample.0.0.1\build\native\Sample.props')" />
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <VCProjectVersion>16.0</VCProjectVersion>
    <Keyword>Win32Proj</Keyword>
    <ProjectGuid>{6acd8f9b-8215-4ee4-b039-8395dd78d863}</ProjectGuid>
    <RootNamespace>ConsoleApplication3</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v142</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v142</PlatformToolset>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v142</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v142</PlatformToolset>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Label="Shared">
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <LinkIncremental>true</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <LinkIncremental>false</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <LinkIncremental>true</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <LinkIncremental>false</LinkIncremental>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>WIN32;_DEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>WIN32;NDEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>_DEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>NDEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="ConsoleApplication3.cpp" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
    <Import Project="..\packages\Sample.0.0.1\build\native\Sample.targets" Condition="Exists('..\packages\Sample.0.0.1\build\native\Sample.targets')" />
  </ImportGroup>
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Sample.0.0.1\build\native\Sample.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Sample.0.0.1\build\native\Sample.props'))" />
    <Error Condition="!Exists('..\packages\Sample.0.0.1\build\native\Sample.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Sample.0.0.1\build\native\Sample.targets'))" />
  </Target>
</Project>
```

**Comment by heng-liu** [comment] 2020-11-03 22:10
Checked with C++ team offline, get the following reply:

> `<ImportGroup Label="ExtensionSettings" /> and <ImportGroup Label="ExtensionTargets " /> `are NOT intended for nuget use, please don’t use them. 
> These import groups are intended for “Custom Build Rule” feature which requires [name].props, [name].targets and [name].xml files to be present.
> The order of the properties/imports is very important for build and Project Properties UI to work. I’d suggest NOT changing what nuget is doing currently as this will break a lot of people.

So I closed it as it's not a bug.
If anyone found the current position of props in .vcxproj file breaks any user scenario, pls reopen it or raise a new issue. Thanks.

**Closed as completed by heng-liu** 2020-11-03 22:10 UTC
Labels: Product:VS.Client, Priority:2, Type:Bug, Functionality:Install, Style:Packages.Config, Resolution:NotABug, Partner:C++
