### ISSUE TITLE
[Test Failure] Build restore failed after setting DPL

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4097] opened 2016-12-13 08:26 UTC
**NuGet Version:** NuGet 4.0.0-xprivate-2974
**VS Version:** D15Rel 26009.00
**OS Version:** Windows 10 RS1_Release 14393.591.161206-1757

**Repro Steps:**
1.	New a Visual C#->Windows Classic Desktop->Console App (.NET Framework) template.
2.	Right-click on the project and click ‘Manage NuGet Packages…’.
3.	Install a package, save the solution.
4.	Manually delete the package from solution package folder.
5.	Build the solution.
6.	Set the DPL (check the 'lightweight solution load') and restart the solution.
7.	Redo step4 and step5.

**Expected Result:**
The build restore is successful, the deleted package come back after doing build solution.

**Actual Result:**
Build restore didn’t executed after setting DPL, the deleted package didn’t come back as below screenshot.
![buildrestorefailed](https://cloud.githubusercontent.com/assets/20632625/21132447/01e005e8-c14f-11e6-99e3-00dab84e9dbc.png)

**Note:**
It also repro on D15Rel 26009.00 (NuGet Client 4.0.0-RC2-2098)

**Comment by rrelyea** [comment] 2016-12-13 16:02
I'm trying to stop using the term DPL, using LSL instead: "Lightweight solution load", which is what they ended up calling the feature.
Anyway, with what we shipped in RC1 and RC2, this is by design.

This will improve with the work that you guys have helped to test from @jainaashish -= but that isn't checked in yet.

**Closed as completed by rrelyea** 2016-12-13 16:02 UTC
Labels: Resolution:ByDesign
