### ISSUE TITLE
VS2015 Community "Object not set to an instance of object"

### ISSUE THREAD

**Issue by Miiite** [NuGet/Home#1572] opened 2015-10-14 08:01 UTC
Hello,

I recently did a clean install of both Windows 10 and VS2015 Community (using parrallels desktop).

I created a new Xamarin project, added a PCL project to it, and openned the Nuget Package Manager using the "Manage Nuget Packages" menu on my PCL project. By default the PCL targets .NET Framwork 4.0.3

The manager opened correctly, but I needed to retarget my PCL project in order to install the nuget package I wanted. So I changed the target to 4.5, and from that moment, when I want to open the nuget package manager, I get a popup with the message "Object reference not set to an instance of object".
If I add the package using my other machine, commit, and get the updated project on my machine with VS2015, the automatic restore does not work also saying the specified nuget package cannot be found.

Going back to target the .NET 4.0.3 on my PCL does not allow me to get back the nuget package manager.
Reinstalling the nuget package manager does not solve this.
Repairing visual studio does not solve this either.

I've been able to reproduce this behavior on 3 different PCL project, so it seems systematic to me.

Thanks.

**Comment by yishaigalatzer** [comment] 2015-10-14 20:52
What version of nuget extension are you using?

Please try https://dist.nuget.org/visualstudio-2015-vsix/v3.2.1-rc/NuGet.Tools.vsix to see if it resolved your issue or given you better indication.

If not we have fixed several similar issues in NuGet 3.3, and if you want to give it a try please contact me directly on my email, y i g a l a t z @msft.com and I'll work with you on private build and perhaps a debug build.

**Comment by andyhammar** [comment] 2015-10-18 11:22
I had the same problem and 3.2.1-rc fixed it for me! Thanks a lot. Was on 3.2.60.... (3.2.0)

**Comment by derekmacdonald** [comment] 2015-10-22 23:40
I have the same problem; I uninstalled 3.2.61008 and tried to install from that link above and from the download page. 

However, after running the 3.2.1-rc installer, I still get the error and still see 3.2.61 as the installed Nuget manager. To be certain, I did the following:

1) Remove nuget from Visual Studio 2015
2) Restart computer
3) Install nuget from 3.2.1-rc installer.

Anyone have any ideas? This is completely blocking me from using Visual Studio 2015.

**Comment by yishaigalatzer** [comment] 2015-10-22 23:50
You might have to delete the extension

Run Devenv /setup that should reset things.

If that doesn't work, you might have to manually clear the extension folders where nuget resides. You will need to search for nuget.tools.dll under c:\program files (x86)\microsoft visual studio 14.0\common7\ide\extensions

Close all instances of visual studio first

You will find a random folder name (or more than one). Delete them (or to be safe copy them).

Then run devenv /setup again.

Now install the vsix again.

**Comment by derekmacdonald** [comment] 2015-10-25 21:16
Deleting all occurrences of nuget from the extensions folder didn't work. Who knows, maybe it caches the install files somewhere else, installer files are wrong, whatever. 3.3 might fix it, going back to Visual Studio 2013 for now.

 Is Nuget uninstall/install not working a nuget issue or a Visual Studio issue?

Either way, Nuget 3 appears to be an abysmal failure so far.

**Comment by yishaigalatzer** [comment] 2015-10-25 21:25
Sorry to hear that, would love to help you with this, here are a few thoughts on the matter.

Installer failures are typically a visual studio thing, rather than a specific extension thing. But its hard to tell.

Did you run devenv.exe /setup? 

Are there any other extensions on your visual studio instance that might interfere?

Last is there a way to get remote access session with you so we can get to the bottom of it?

**Comment by derekmacdonald** [comment] 2015-10-26 23:27
Yes, I ran devenv /setup. I've uninstalled 2015 for now; I'll see how it works after a reinstall probably later this week/early next. 

The only extension I was knowingly running was resharper. I also had run the Xamarin installer on this laptop.

**Comment by yishaigalatzer** [comment] 2015-10-26 23:30
Shoot me an email when you get to it, and I'll try to work with you to get to the bottom of it. y i g a l a t z @ msft.com

I might be able to share private bits to debug further.

**Comment by sulmar** [comment] 2015-10-27 16:35
I has the same error "Object not set to an instance of object" in VS 2015 with Entity Framework 6.1.3 and Rx-Main 2.2.5 packages. Only after installing the nuget from 3.2.1-rc installer issue is resolved.

**Comment by yishaigalatzer** [comment] 2015-10-27 16:41
@derekmacdonald one more thing I learned yesterday. You want to run visual studio at least once in admin mode. It enables it to perform cleanup on left over files from extensions.

**Comment by woellij** [comment] 2015-10-30 10:04
I'm encountering the same issue.

Once a PCL is changed to a Profile Compatible with "ASP.NET Core v5.0" Opening "Manage NuGet Packages ..." on a Project throws  "Object reference not set to an instance of object".

I suspect it has something to do with the "project.json" file that is generated by changing the Profile to a compatible one. Probably with the fact, that said "project.json" file is empty ... once you add an empty JSON Object ( empty curly braces to it ) it works again.

It feels a bit like being a beta tester ... the issue can easily be reproduced and this isn't the first report about it but it hasn't been fixed yet.

**Comment by yishaigalatzer** [comment] 2015-10-30 15:26
Thanks for the feedback. Nullref is a very generic exception so saying this was already reported is not very accurate.

I believe your scenario is fixed in 3.3 already, and I will verify today.

Sent from my Windows Phone

**Comment by yishaigalatzer** [comment] 2015-10-30 16:12
@woellij so we don't control the creation of and empty `project.json` I'll forward this to the right team.

However in 3.3 (getting ready to be released) we will throw a proper error message pointing you to what went wrong - 

![capture](https://cloud.githubusercontent.com/assets/1238711/10851071/529045ae-7ee6-11e5-8f8a-2d376f62d9e0.PNG)

**Comment by aflyhorse** [comment] 2015-11-01 10:35
Upgrading to 3.2.1-rc1 also resolved my problem.

I was getting

```
Install failed. Rolling back...
Package 'System.Data.SQLite.Linq 1.0.98.1' does not exist in project 'Test'
...
Install-Package : Object reference not set to an instance of an object.
At line:1 char:1
+ Install-Package System.Data.SQLite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

before my upgrading.

**Comment by jkarsrud** [comment] 2015-11-17 12:08
I'm experiencing installation failures too. Packages install correctly according to the console, but then I get the rollback message and the installation fails with a NullReferenceException. 

I tried checking for more errors using `$error` in the console, which gave me a more specific error;

``` powershell
PM> $error
Install-Package : Object reference not set to an instance of an object.
At line:1 char:1
+ Install-Package idseefeld.de.UmbracoAzure
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Get-RemotePackageId : The term 'Get-RemotePackageId' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify th
at the path is correct and try again.
At C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\5WHNNQXS.PQL\Modules\NuGet\nuget.psm1:184 char:10
+         return Get-RemotePackageId @parameters
+                ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-RemotePackageId:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Looking at the source of `nuget.psm1`, it does call `Get-RemotePackageId` in a try/catch, but it seems to not catch the exception properly, and just exit.

``` powershell
try {
  return Get-RemotePackageId @parameters
}
catch {
    # If the server doesn't have the JSON API endpoints, get the remote package IDs the old way.
    return GetPackages $context | Select-Object -ExpandProperty Id -Unique
}
```

I tried installing 3.2.1-RC1, but that did not resolve the issue.

I'd also like to add that I'm not using VS2015 Community, but VS2015 Pro. I have the latest release of Resharper 9 installed.

**Comment by zhili1208** [comment] 2015-11-17 18:35
@jkarsrud Can you provide your Nuget verison , VS version and repro steps? the installation failure is for one specified package or for all packages? thanks

**Comment by jkarsrud** [comment] 2015-11-23 13:41
@zhili1208 I mentioned some of them above, but I'll be happy to list them again;
- Nuget 3.0.0 and Nuget 3.2.6
- VS 2015 Pro

The problem exists when installing all packages. I did do a complete reinstall of my machine recently, and noticed that I only ran into the problem after an E-Commerce platform called uCommerce into an Umbraco project. The steps to reproduce this failure are the following:
- Create a new, empty ASP.NET MVC project
- Install UmbracoCMS with Nuget (`Install-Package UmbracoCms`)
- Follow installation instructions after successful install
- `Install-Package Lecoati.LeBlender` (success)
- `Install-Package idseefeld.de.UmbracoAzure` (success)
- Download and install uCommerce following their instructions
- `Install-Package ImageProcessor.Web.Config` (fails)

I think the problem might be uCommerce and something they do, as installing packages through NuGet works without any issues before installing it. We reference all the uCommerce-DLL's from a `lib` directory on the same level as the solution.

**Comment by yishaigalatzer** [comment] 2015-11-23 15:36
@jkarsrud could you share the solution at the level in which it is broken? The repro steps are too long and it will save lots of time and potential blunders to start from that

**Comment by yishaigalatzer** [comment] 2015-12-10 19:31
@jkarsrud ping
1. Does this still repro with NuGet 3.3?
2. If it does are you able to provide a repro project?

**Comment by pgorbas** [comment] 2015-12-30 15:51
I am still having this problem ( unable to start Sidewaffle projects in VS2015 community  - getting "Object not set to an instance of object" error ).

I have:
1. Opened vs2015 as Admin, and removed the nugget extension with extension manager. Then closed vs2015.
2. Then in file explorer I deleted all folders under <install path>\Common7\IDE that search found "nugget" until that search came up empty.
3. From admin command prompt ran >devenv.exe /setup
4. I ran this installer: https://dist.nuget.org/visualstudio-2015-vsix/v3.2.1-rc/NuGet.Tools.vsix
5. Restarted vs2015 as admin - I note that in extension manager nugget version 3.2.1 was not installed, it installed version 3.2.6 instead - looks like the install link is redirecting to the wrong version and of course the installer file isn't labeled with a version..
6. Trying to start a new project with "AngularJS And WebApi - Empty" serves up the  "Object not set to an instance of object" error.

Any more ideas -- the problem I think is that MS is no longer serving up the 3.2.1 installer.

**Comment by yishaigalatzer** [comment] 2015-12-30 15:56
Please use 3.3 - find it on the downloads page of nuget.org

**Comment by pgorbas** [comment] 2015-12-30 16:18
Thanks yishaigalatzer, I did this:
1. Opened vs2015 as Admin, and removed the nugget extension with extension manager. Then closed vs2015.
2. Went to the nuget.org website and installed nugget form there.
3. Restarted vs2015 as admin - I note that in extension manager nugget version is now 3.3.0.167
4. However trying to start a new project with "AngularJS And WebApi - Empty" still 
serves up the "Object not set to an instance of object" error.

**Comment by yishaigalatzer** [comment] 2015-12-30 17:05
And how do you figure it is a nuget issue?

**Comment by pgorbas** [comment] 2015-12-30 17:07
Because when I google on "Object not set to an instance of object" I get directed to this page.  I get no other error message.

**Comment by yishaigalatzer** [comment] 2015-12-30 17:09
That is a very generic error, not saying this is not nuget, but this the most common exception in .net.

Would you mind attaching a debugger and looking into the call stack?

**Comment by pgorbas** [comment] 2015-12-30 17:15
I have no idea how to attach a debugger to visual studio trying to start a new project....

**Comment by yishaigalatzer** [comment] 2015-12-30 17:18
Start another instance of visual studio -> debug -> attach to process

Then start new project on the other visual studio

**Comment by pgorbas** [comment] 2015-12-30 17:31
OK - I tried that.  Opened a 2nd VS2015 then Debug -> attach to process.  There was only one vs2015 to attach to ( devenv.exe ) I attached, and saw the diagnostic tools pop open.  When I go back to the first instance of vs2015, I try to start a new project with  "AngularJS And WebApi - Empty" , get the same error and the 2nd vs2015 instance  debugging the 1st instance of vs2015 does not show anything in console log, or any messages in the output window other than "The thread 0x3af0 has exited with code 0 (0x0)."

**Comment by yishaigalatzer** [comment] 2015-12-30 17:34
OK, go to the exceptions window (it should show up on the bottom), and turn on the nullref exception. It should now break when that exception is being thrown

![exceptionwindow](https://cloud.githubusercontent.com/assets/1238711/12054440/88f9c5e4-aed8-11e5-81db-4b4d254dc095.jpg)

**Comment by pgorbas** [comment] 2015-12-30 17:48
OK I did that.  I cleared the output window in the debugging vs2015, then tried to start a project in the main vs2013 window -- here is what gets dumped into the output window

```
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - AcquireTokenHandlerBase: === Token Acquisition started:
    Authority: https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/
    Resource: https://management.core.windows.net/
    ClientId: 872cd9fa-d31f-45e0-9eab-6e460a02d1f1
    CacheType: Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManagerAdalCache (4 items)
    Authentication Target: User

devenv.exe Information: 0 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - AcquireTokenHandlerBase: === Token Acquisition started:
    Authority: https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/
    Resource: https://management.core.windows.net/
    ClientId: 872cd9fa-d31f-45e0-9eab-6e460a02d1f1
    CacheType: Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManagerAdalCache (4 items)
    Authentication Target: User

Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - TokenCache: Looking up cache for a token...
devenv.exe Information: 0 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - TokenCache: Looking up cache for a token...
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - TokenCache: An item matching the requested resource was found in the cache
devenv.exe Information: 0 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - TokenCache: An item matching the requested resource was found in the cache
Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - TokenCache: 22.5481283766667 minutes left until token in cache expires
devenv.exe Information: 0 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - TokenCache: 22.5481283766667 minutes left until token in cache expires
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - TokenCache: A matching item (access token or refresh token or both) was found in the cache
devenv.exe Information: 0 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - TokenCache: A matching item (access token or refresh token or both) was found in the cache
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
    Access Token Hash: TqKbos3RNt1stusrfXH6OU8t1C6lnPqoM7bvMLNS10U=
    Refresh Token Hash: XeWUxjcUZq9JrVohcX6AnEAYebCbcr6UoOHMVt2SOuI=
    Expiration Time: 12/30/2015 6:03:51 PM +00:00
    User Hash: e7R8Kc2OF2aFPZICIa7QkwhEPjgjZHz68ppcnt4ifY4=

devenv.exe Information: 0 : 12/30/2015 5:41:18 PM: 63d903d0-cfd7-451f-b16b-751ef3e3225e - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
    Access Token Hash: TqKbos3RNt1stusrfXH6OU8t1C6lnPqoM7bvMLNS10U=
    Refresh Token Hash: XeWUxjcUZq9JrVohcX6AnEAYebCbcr6UoOHMVt2SOuI=
    Expiration Time: 12/30/2015 6:03:51 PM +00:00
    User Hash: e7R8Kc2OF2aFPZICIa7QkwhEPjgjZHz68ppcnt4ifY4=
```

**Comment by yishaigalatzer** [comment] 2015-12-30 17:59
Could you please make sure it breaks on the exception and then copy the callstack window. If the issue you are seeing is in visual studio 2013, then this is the wrong thread, as this is tracking issues with 2015 + NuGet 3.3

**Comment by pgorbas** [comment] 2015-12-30 18:04
It is in vs2015 - and that's the point - it doesn't throw an exception ( or the exception was thrown and caught and served up that generic error message ) ???

**Comment by yishaigalatzer** [comment] 2015-12-30 18:07
I'm guessing your debugging settings are not set up correctly. can you paste the exception settings, and also try disabling just my code in the debug->Options

**Comment by pgorbas** [comment] 2015-12-30 18:47
OK, did that now when I try to start the project I get a series of "NullRefrenceException occurred" popups 

```
System.NullReferenceException occurred
Message: Exception thrown: 'System.NullReferenceException' in LigerShark.Templates.dll
Additional information: Object reference not set to an instance of an object.
```

then

```
System.NullReferenceException occurred
Message: Exception thrown: 'System.NullReferenceException' in Microsoft.VisualStudio.TemplateWizard.dll
Additional information: Object reference not set to an instance of an object.
```

then

```
System.NullReferenceException occurred
Message: Exception thrown: 'System.NullReferenceException' in Microsoft.VisualStudio.Dialogs.dll
Additional information: Object reference not set to an instance of an object.
```

then

```
System.NullReferenceException occurred
Message: Exception thrown: 'System.NullReferenceException' in Microsoft.VisualStudio.Dialogs.dll
Additional information: Object reference not set to an instance of an object.
```

(The last pop up looks like it repeated the same thing twice in a row.)
Then it reverted to the other instance of VS2015 wherein the new project was trying to start to view the  popup  "Object not set to an instance of object"

The output window in the debugging vs2015 says :

```
The thread 0x2ea4 has exited with code 0 (0x0).
The thread 0x3b9c has exited with code 0 (0x0).
The thread 0x305c has exited with code 0 (0x0).
The thread 0x2e40 has exited with code 0 (0x0).
The thread 0x1f2c has exited with code 0 (0x0).
The thread 0x3548 has exited with code 0 (0x0).
The thread 0x39d4 has exited with code 0 (0x0).
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - AcquireTokenHandlerBase: === Token Acquisition started:
    Authority: https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/
    Resource: https://management.core.windows.net/
    ClientId: 872cd9fa-d31f-45e0-9eab-6e460a02d1f1
    CacheType: Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManagerAdalCache (4 items)
    Authentication Target: User

devenv.exe Information: 0 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - AcquireTokenHandlerBase: === Token Acquisition started:
    Authority: https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/
    Resource: https://management.core.windows.net/
    ClientId: 872cd9fa-d31f-45e0-9eab-6e460a02d1f1
    CacheType: Microsoft.VisualStudio.Services.Client.AccountManagement.AccountManagerAdalCache (4 items)
    Authentication Target: User

Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - TokenCache: Looking up cache for a token...
devenv.exe Information: 0 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - TokenCache: Looking up cache for a token...
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - TokenCache: An item matching the requested resource was found in the cache
devenv.exe Information: 0 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - TokenCache: An item matching the requested resource was found in the cache
Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - TokenCache: 53.0265894633333 minutes left until token in cache expires
devenv.exe Information: 0 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - TokenCache: 53.0265894633333 minutes left until token in cache expires
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - TokenCache: A matching item (access token or refresh token or both) was found in the cache
devenv.exe Information: 0 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - TokenCache: A matching item (access token or refresh token or both) was found in the cache
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
    Access Token Hash: 039tI0p4y4GNMujt0GOelkEjTC8Rxzyt8BiUDtW7EAc=
    Refresh Token Hash: XeWUxjcUZq9JrVohcX6AnEAYebCbcr6UoOHMVt2SOuI=
    Expiration Time: 12/30/2015 7:23:06 PM +00:00
    User Hash: e7R8Kc2OF2aFPZICIa7QkwhEPjgjZHz68ppcnt4ifY4=

devenv.exe Information: 0 : 12/30/2015 6:30:04 PM: 5a0f47a8-1dc7-467f-aa4c-1de5bb4fd19d - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
    Access Token Hash: 039tI0p4y4GNMujt0GOelkEjTC8Rxzyt8BiUDtW7EAc=
    Refresh Token Hash: XeWUxjcUZq9JrVohcX6AnEAYebCbcr6UoOHMVt2SOuI=
    Expiration Time: 12/30/2015 7:23:06 PM +00:00
    User Hash: e7R8Kc2OF2aFPZICIa7QkwhEPjgjZHz68ppcnt4ifY4=

Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
The thread 0x2b44 has exited with code 0 (0x0).
The thread 0x3498 has exited with code 0 (0x0).
The thread 0x42d4 has exited with code 0 (0x0).
The thread 0x3084 has exited with code 0 (0x0).
The thread 0x8 has exited with code 0 (0x0).
The thread 0x24b4 has exited with code 0 (0x0).
The thread 0x1f40 has exited with code 0 (0x0).
The thread 0x3300 has exited with code 0 (0x0).
The thread 0x3b2c has exited with code 0 (0x0).
The thread 0x2d94 has exited with code 0 (0x0).
The thread 0x1b74 has exited with code 0 (0x0).
The thread 0x39e0 has exited with code 0 (0x0).
The thread 0x21d0 has exited with code 0 (0x0).
The thread 0xea8 has exited with code 0 (0x0).
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in mscorlib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in mscorlib.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll
The thread 0x288c has exited with code 0 (0x0).
... last line repeats a few dozen more times...
```

My exception settings are:
![capture](https://cloud.githubusercontent.com/assets/11726837/12055444/01ca48b2-aef3-11e5-848d-0d03388350a1.JPG)

![capturenull](https://cloud.githubusercontent.com/assets/11726837/12055511/71fc6e3a-aef3-11e5-97c7-70891792be03.JPG)

**Comment by yishaigalatzer** [comment] 2015-12-30 18:54
Sweet, we are making progress!

So when you get the first one, click break, can you please go to the stack window and copy/paste the whole stack from there? From the looks of it, it looks like there is a nullref thrown from sidewaffle code proper, but it would be useful the get the full stack.

**Comment by pgorbas** [comment] 2015-12-30 19:07
OK, here it is:

```
>   LigerShark.Templates.dll!LigerShark.Templates.GoogleAnalyticsWizard.LogError(string message)    Unknown
    LigerShark.Templates.dll!LigerShark.Templates.GoogleAnalyticsWizard.RunStarted(object automationObject, System.Collections.Generic.Dictionary<string, string> replacementsDictionary, Microsoft.VisualStudio.TemplateWizard.WizardRunKind runKind, object[] customParams)   Unknown
    Microsoft.VisualStudio.TemplateWizard.dll!Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(object application, int hwndOwner, ref object[] ContextParams, ref object[] CustomParams, ref EnvDTE.wizardResult retval)    Unknown
    [Native to Managed Transition]  
    [Managed to Native Transition]  
    Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.Dialogs.ServiceHelper.AddProjectFromSelectedTemplate(Microsoft.VisualStudio.Dialogs.INewProjectDialogData dialog, string projectPath, bool isExclusive)   Unknown
    Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.Dialogs.SVsDialogService.CreateProject(Microsoft.VisualStudio.Dialogs.INewProjectDialogData npdd) Unknown
    Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.Dialogs.SVsDialogService.InvokeDialog(Microsoft.Internal.VisualStudio.Shell.Interop.VSNEWPROJECTDLGINFO dlgInfo, out string bstrLocation) Unknown
```

This doesn't help me to solve the problem though.  Remember I am not the developer of this these templates, I am just a consumer.

**Comment by kentcooper** [comment] 2016-01-20 03:54
@pgorbas That is an issue in SideWaffle. Once the latest build of SideWaffle is released this issue should be fixed.

**Closed as completed** 2016-01-28 22:44 UTC
Labels: Type:Bug
