### ISSUE TITLE
"End of Central Directory record could not be found" when trying to push a package

### ISSUE THREAD

**Issue by joozek78** [NuGet/Home#5076] opened 2017-04-20 13:42 UTC
## Details about Problem

NuGet product used: **NuGet.exe**

NuGet version (x.x.x.xxx): **3.5.0.1938**

VS version (if appropriate): 2015

OS version: **win10 v1607 (14393.1066**

Worked before?: **no**

## Detailed repro steps so we can see the same problem

1. `git clone git@github.com:starcounter/authorization`
1. `cd authorization/authorization`
1. `msbuild Authorization.csproj` <-- actually you need msbuild that supports C#6 or just build in VS
1. `../nuget.exe push Authorization.nuspec -Source https://nuget.org`

```
Pushing Authorization.nuspec to 'https://nuget.org'...
  PUT https://nuget.org/api/v2/package/
  BadRequest https://nuget.org/api/v2/package/ 1578ms
Response status code does not indicate success: 400 (The NuGet package is invalid. The error encountered was:'End of Central Directory record could not be found.'. Correct the error and try again.).
```
### Verbose Logs

```
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (The NuGet package is invalid. The error encountered was:'End of Central Directory record could not be found.'. Correct the error and try again.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__19_1(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (The NuGet package is invalid. The error encountered was:'End of Central Directory record could not be found.'. Correct the error and try again.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__19_1(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__28.MoveNext()<---
```
### Sample Project

https://github.com/starcounter/authorization

**Comment by mishra14** [comment] 2017-10-17 23:05
@joozek78 I cant repro the issue. The repo does not build - 
```
"C:\Users\anmishr\Desktop\temp\authorization\Authorization\Authorization.csproj" (Restore target) (1) ->
  C:\Users\anmishr\Desktop\temp\authorization\Authorization\Authorization.csproj(131,3): error MSB4019: The imported project "C:\Starcounter.MsBuild.targets" was not found. Confirm that the p ath in the <Import> declaration is correct, and that the file exists on disk.
```

Please reopen this issue if you are still facing the issue.

**Comment by dzmitry-lahoda** [comment] 2018-03-23 17:10
I get this for the first time
```
Error downloading 'System.Threading.4.0.11' from 'https://www.nuget.org/api/v2/package/System.Threading/4.0.11'.
End of Central Directory record could not be found.
Error downloading 'System.Threading.4.0.11' from 'https://www.nuget.org/api/v2/package/System.Threading/4.0.11'.
````

When I put url into Firefox it  then download packages without issues.

I have next file at `C:\Users\dzmitry\.nuget\packages\System.Threading\4.0.11\ai1gz14z.fl1`. Delete it.  
[ai1gz14z.zip](https://github.com/NuGet/Home/files/1843058/ai1gz14z.zip). And got replaced with same under different name. 
[yrwsclv3.zip](https://github.com/NuGet/Home/files/1843068/yrwsclv3.zip). Attached inside zip.

Manual downloads gives same broken file. 
[system.threading.4.0.11.zip](https://github.com/NuGet/Home/files/1843085/system.threading.4.0.11.zip)

Downloaded https://www.nuget.org/packages/System.Numerics.Vectors/ and it unpacks fine.

Validated in Edge and on other network and PC and via USA VPN - downloaded 4.0.11 gives same effect.

I have switched to 7 month old in our solution

```
nuget restore OUR_SOLUTION.sln -ConfigFile NuGet.config -NonInteractive
Failed to download package from 'https://www.nuget.org/api/v2/package/System.Threading/4.0.11'.
The nupkg at 'https://www.nuget.org/api/v2/package/System.Threading/4.0.11' is not valid.
  End of Central Directory record could not be found.
Unable to load package 'System.Threading'.
```

But that time `System.Threading` was fine. Seems nupkg archive corrupted while being on nuget.

`System.Theading` 4.30 downloads just fine.

**Comment by dzmitry-lahoda** [comment] 2018-03-23 17:23
https://stackoverflow.com/questions/32493537/end-of-central-directory-record-could-not-be-found-nuget-in-vs-community-201

@mishra14 you should reopen the issue. something wrong with cache or error reporting - e.g. report broken cache or locked cache. not what I see now in error message - please improve error message.

Nuget should directly report broken zip archives upon download and upload. I guess check was done during upload. And System.Threading is official .NET Core team package. So it broken while was stored on Azure. @mishra14, seems serious Azure or Cacheh or Nuget server bug  . Do not you think?

Update: I checked that nuget directly goes to Azure Block storage where, probably, corruption happend:

https://az320820.vo.msecnd.net/packages/test
```
BlobNotFoundThe specified blob does not exist.
RequestId:ed234899-501e-0012-6c91-c50449000000
Time:2018-03-27T06:03:53.6581154Z
```

**Comment by dzmitry-lahoda** [comment] 2018-03-26 09:26
@anangaur (I hope you are right person or know right person to address issue), given my comments seems there is corruption of zip packages stored on nuget. May you help with reopening of this story to check why this happens? I guess nupkg zip are stored on Azure, means there is some corruption may happen from time time on Azure storage.

**Comment by anangaur** [comment] 2018-03-26 15:35
Is the original issue same as what you mention? I see the original issue was for push while the later discussions are around consumption.
/cc: @skofman1

**Comment by dzmitry-lahoda** [comment] 2018-03-26 18:02
I concentrated on same error message and that issue was closed as not reproducible, and do not like to create new bugs if old would work fine (not the case there so). I see now that my case is different. My case around consumption. I just opened first issues with same error message found in web search. [Github search](https://github.com/NuGet/Home/issues?utf8=%E2%9C%93&q=End+of+Central+Directory+record+could+not+be+found) gives better place for consumption issue.

I see that 2 has unresolved by creators:

https://github.com/NuGet/Home/issues/2278#issuecomment-194490174 

https://github.com/NuGet/Home/issues/6430#issue-288175454

Validating their dependencies on that dates could reveal corrupted packages. Alternatively check all nuget packages on nuget. 

Given #5859 unresolved, we could have many broken, not sure that case is clear for me, but at least title seems resonable. But my case is NOT about bad pushes.

In my case consumption worked well 7 month ago. I checkout our repository back to 7 month old and nuget failed, while it worked fine for me that time. May be I had valid cache for `System.Threading` may be not. And several people doing checkouts, so hard to guess. But anyway - once upon a time `System.Threading` 4.0.11 was valid on nuget.org. May be create new bug for this case?

**Comment by mishra14** [comment] 2018-03-26 18:10
@dzmitry-lahoda thanks for getting back to us. I have reopened this issue for investigation.

Can you please use the latest nuget.exe from [here](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) to see if you are still facing this issue?

**Comment by dzmitry-lahoda** [comment] 2018-03-27 05:58
New nuget will not help. I am absolutely sure. Because:

1. Open Edge
2. Open https://www.nuget.org/api/v2/package/System.Threading/4.0.11
3. Save `system.threading.4.0.11.nupkg`
4. Rename `system.threading.4.0.11.nupkg` into `system.threading.4.0.11.nupkg.zip`
5. Try to extract archive
Expected: Extracted
Actual: Failed because archive is invalid
![image](https://user-images.githubusercontent.com/757125/37949255-8615951c-319c-11e8-83ed-31ad52802f94.png)

Notes:
1. Same happens with other browsers and extractors.
2. Same happens downloading from different countries and machines.
3. Nuget packages are just zip archives by spec. Do same with other nupkg and see that all works. E.g. https://www.nuget.org/api/v2/package/System.Threading/4.3.0
Expected: 4.3.0 unzipped without issues and 4.0.11 unzipped without issue.
Actual: 4.0.11 fails to extract, while 4.3.0 extracts fine.

4. As with my previous comments, `system.threading.4.0.11.nupkg` was VALID at some point of time. It means that it was broken while being hosted on Nuget.

So new nuget will download invalid archive and will not be able to extract, because archive is broken. 

Anyway, if you still think it will help, what command to use do download and unzip specific single nuget package?

**Comment by dzmitry-lahoda** [comment] 2018-03-27 07:46
I grabbed package from colleague PC and have put into `%USERPROFILE%\.nuget\packages\System.Threading` for temporal solution. It is attached.

[System.Threading.4.0.11.zip](https://github.com/NuGet/Home/files/1850893/System.Threading.4.0.11.zip)

**Comment by anangaur** [comment] 2018-03-27 14:42
Where are you downloading it from? It opened just fine for me.

@skofman1  what other details we need here?

![image](https://user-images.githubusercontent.com/14800916/37974689-5723ef1a-3192-11e8-8021-f3a936edef16.png)

**Comment by dzmitry-lahoda** [comment] 2018-03-27 15:16
Attached package was downloaded by my colleague ~year ago into his nuget cache. As I said, package was fine some time ago. It was broken at some point of time. I copied collegue's files it into my cache and continue to work. As I doubt to have fix for this issue soon. So people will just reach this issue and attach non broken version of packages which are broken on nuget now, from their cache, and other will reach this issue, and download from it.

**Comment by dzmitry-lahoda** [comment] 2018-03-27 15:47
I see only one update of nuget either:

https://www.nuget.org/api/v2/Packages()?$filter=Title%20eq%20%27System.Threading%27&$select=Id,Tags,Title,Description,ProjectUrl,GalleryDetailsUrl,Version,LastUpdated,Version

`<entry><id>https://www.nuget.org/api/v2/Packages(Id='System.Threading',Version='4.0.11')</id><category term="NuGetGallery.OData.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" href="https://www.nuget.org/api/v2/Packages(Id='System.Threading',Version='4.0.11')" /><link rel="self" href="https://www.nuget.org/api/v2/Packages(Id='System.Threading',Version='4.0.11')" /><title type="text">System.Threading</title><updated>2016-06-27T12:28:11Z</updated><author><name /></author><content type="application/zip" src="https://www.nuget.org/api/v2/package/System.Threading/4.0.11" /><m:properties><d:Id>System.Threading</d:Id><d:Tags m:null="true" /><d:Title>System.Threading</d:Title><d:Description>Provides the fundamental synchronization primitives, including System.Threading.Monitor and System.Threading.Mutex, that are required when writing asynchronous code.

Commonly Used Types:
System.Threading.Monitor
System.Threading.SynchronizationContext
System.Threading.ManualResetEvent
System.Threading.AutoResetEvent
System.Threading.ThreadLocal&lt;T&gt;
System.Threading.EventWaitHandle
System.Threading.SemaphoreSlim
System.Threading.Mutex
 
When using NuGet 3.x this package requires at least version 3.4.</d:Description><d:ProjectUrl>https://dot.net/</d:ProjectUrl><d:GalleryDetailsUrl>https://www.nuget.org/packages/System.Threading/4.0.11</d:GalleryDetailsUrl><d:Version>4.0.11</d:Version><d:LastUpdated m:type="Edm.DateTime">2016-06-27T12:28:11.483</d:LastUpdated></m:properties></entry>`

**Comment by skofman1** [comment] 2018-03-28 03:16
@dzmitry-lahoda , thanks for the detailed analysis of the issue. Since you were able to repro this on Edge, it sounds like a network related issue. 
Before we continue with the investigation, a possible mitigation is using V3 API instead of V2: configure the feed to be **https://api.nuget.org/v3/index.json** instead of https://www.nuget.org/api/v2. Please let me know if this works.
Regarding investigation- similarly to @anangaur , I wasn't able to repro the behavior you are describing. I'm able to download and unzip https://www.nuget.org/api/v2/package/System.Threading/4.0.11 from both Edge and Chrome. 
Can you please use fiddler to see the amount of bytes you are getting?
Call https://www.nuget.org/api/v2/package/System.Threading/4.0.11 
The expected result is 698,449 bytes : 
![image](https://user-images.githubusercontent.com/16807822/38006654-dd0bb08c-31fa-11e8-9bef-b6cee097692f.png)

Also, you mentioned 

> 2. Same happens downloading from different countries and machines.

Can you explain how the test was performed?

Based on the result I will be able to suggest next steps.

**Comment by dzmitry-lahoda** [comment] 2018-03-28 08:30
There is my Fiddler logs attached, I have different result and cannot open archive. [belarus_company_vpn.zip](https://github.com/NuGet/Home/files/1855081/belarus_company_vpn.zip).



I followed index.json with
```

@id | "https://api.nuget.org/v3-flatcontainer/"
-- | --
@type | "PackageBaseAddress/3.0.0"
comment | "Base URL of where NuGet packages are stored, in the format https://api.nuget.org/v3-flatcontainer/{id-lower}/{version-lower}/{id-lower}.{version-lower}.nupkg"
```

And combined into https://api.nuget.org/v3-flatcontainer/System.Threading/4.0.11/System.Threading.4.0.11.nupkg  . **Achive is fully extracted and is correct here!**

I have used [ProtonVPN](https://protonvpn.com/) from my home which connects to USA node and asked my friend in Minsk to download either. I will send logs from there either later if still needed, will do test after run of https://gitlab.com/dzmitry-lahoda/scripts/raw/master/net-flush.cmd   .

**Comment by dzmitry-lahoda** [comment] 2018-03-28 13:34
[My sister studies math PhD in Berlin](https://vimeo.com/220338424) and she gets broken archive on her MacBook Air either by https://www.nuget.org/api/v2/package/System.Threading/4.0.11 :
![screenshot 2018-03-28 15 30 00](https://user-images.githubusercontent.com/757125/38032210-b753b668-32a5-11e8-86af-5f59d0b8dfc2.png)
![screenshot 2018-03-28 15 30 20](https://user-images.githubusercontent.com/757125/38032218-bdf602c8-32a5-11e8-91b5-237040dceb6d.png)

I guess it is CDN or Azure Block regions. May be Redmond works fine, but not other world:)

**Comment by chenriksson** [comment] 2018-03-28 20:35
@dzmitry-lahoda I've purged our CDN cache for this package. Please let us know if you continue to see problems.

**Comment by dzmitry-lahoda** [comment] 2018-03-29 13:40
Yes. It works fine now. Thanks.

**Comment by anangaur** [comment] 2018-08-23 18:44
- https://stackoverflow.com/questions/32493537/end-of-central-directory-record-could-not-be-found-nuget-in-vs-community-201
- https://stackoverflow.com/questions/20960403/c-sharp-end-of-central-directory-record-could-not-be-found
- https://twitter.com/MrClyfar/status/652041212405391360

**Comment by nkolev92** [comment] 2018-11-13 03:56
Is there anything actionable from the client here?
Should we close it?
@anangaur

**Closed as completed** 2018-11-13 22:25 UTC
Labels: Priority:2, Triage:Investigate, Functionality:Push
