### ISSUE TITLE
ErrorUnsafePackageEntry error message is not pointing to source of problem

### ISSUE THREAD

**Issue by quasarea** [NuGet/Home#7505] opened 2018-11-13 13:29 UTC
## Details about Problem

NuGet.exe

NuGet version (5.8.1.xxx):

1. create a package with a file with ~ at the end of extension 

2. create packages.config with above package record

3. use nuget restore in packages.config location

*. there is a chance that the file will not be validated and package will be extracted but usually it fails:

        C:\Jenkins\Workspace\SolutionName>nuget.exe restore 
        MSBuild auto-detection: using msbuild version '15.8.169.51996' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin'.
        Restoring NuGet package PackageName.5.6.6.

        Adding package 'PackageName.5.6.6' to folder 'C:\Jenkins\Workspace\SolutionName\packages'
        WARNING: The package 'PackageName.5.6.6' contains an entry which is unsafe for extraction.
        Committing restore...

        Assets file has not changed. Skipping assets file writing. Path: C:\Jenkins\Workspace\SolutionName\ProjectName\obj\project.assets.json
        Restore completed in 92.29 ms for C:\Jenkins\Workspace\SolutionName\ProjectName\ProjectName.csproj.
        Errors in packages.config projects
            The package 'PackageName.5.6.6' contains an entry which is unsafe for extraction.

**Comment by quasarea** [comment] 2018-11-19 16:24
I have a pr for that, but can't getting access denied while creating a branch 'dev-quasarea-errorUnsafePackageEntry'

**Comment by PatoBeltran** [comment] 2018-11-29 00:44
@quasarea you can fork our repo and create the branch there, then just send a PR from your fork to this repo. Let me know if you have any question!

**Comment by krokofant** [comment] 2019-08-01 08:15
Somehow the global cache package name was using uppercase and lowercase ExamplePackage. And one package update would usually extract to a lowercase folder name which I assume throws the error at https://github.com/NuGet/NuGet.Client/blob/5.3.0.6136/src/NuGet.Core/NuGet.Packaging/PackageReaderBase.cs#L540-L556

```csharp
        /// <summary>
        /// Validate file entry in package is not traversed outside of the expected extraction path.
        /// Eg: file entry like ../../foo.dll can get outside of the expected extraction path.
        /// </summary>
        protected static void ValidatePackageEntry(string normalizedDestination, string normalizedFilePath, PackageIdentity packageIdentity)
        {
            // Destination and filePath must be normalized.
            var fullPath = Path.GetFullPath(Path.Combine(normalizedDestination, normalizedFilePath));

            if(!fullPath.StartsWith(normalizedDestination, StringComparison.Ordinal) || fullPath.Length == normalizedDestination.Length)
            {
                throw new UnsafePackageEntryException(string.Format(
                    CultureInfo.CurrentCulture,
                    Strings.ErrorUnsafePackageEntry,
                    packageIdentity));
            }
        }
```

A workaround for our affected machines was just clearing the cache by `nuget locals all -Clear` .

**Comment by bergbria** [comment] 2019-10-03 17:23
@PatoBeltran / @nkolev92 - any updates here? This recently caused breaks for my team when trying to update from nuget 4.6 to 5.3.

**Comment by bergbria** [comment] 2019-10-08 22:40
Standalone repro here: [nuget_unsafeEntry_repro.zip](https://github.com/NuGet/Home/files/3704802/nuget_unsafeEntry_repro.zip). Just download, extract, and run repro.bat.

Notes from my investigation:
* Facts:
    * When Path.GetFullPath sees a ~ in a file name, it decides the path might contain a short name
    * It calls TryExpandShortFileName to sort this out
        * This calls GetLongPathNameW
* Educated guess:
    * GetLongPathNameW seems to go component by component looking for short names
    * The max path component length in a short name is 8 (according to Wikipedia)
    * If the component length is >8 chars, it can’t be a short name, so it doesn’t look at the file system and uses the original component casing
    * If the component length is <= 8 chars, it uses the casing on disk
    * Nuget implications
        * Say the output dir for the nuget call has different casing on disk/command line for component C (e.g. for d:\dir\Out vs d:\dir\out, C == ‘out’)
        * If C has <=8 chars, nuget will fail
        * If C has >8 chars, nuget will succeed

Tagging @rrelyea / @nkolev92 fyi

**Comment by bergbria** [comment] 2019-10-23 22:43
@rrelyea / @nkolev92 - any ETA here? This is blocking my team from updating.

**Comment by rrelyea** [comment] 2019-10-23 22:52
Gonna have @kartheekp-ms  take a look after a thing or two on his plate. Appreciate you digging into the cause as deep as you did.

**Comment by kartheekp-ms** [comment] 2019-10-30 15:30
@bergbria - I am able to reproduce this issue. Appreciate your help regarding [this](https://github.com/NuGet/Home/issues/7505#issuecomment-539733721) comment. We are working on possible solutions such as adding pack validation rule etc., Please help us understand why package contains filename with `~` char even though it has special meaning while resolving paths. As per our understanding files with `~` char in its name are intermediate files created by apps such as Office.

**Comment by bergbria** [comment] 2019-10-30 16:21
@kartheekp-ms - I have no idea why the package contains a ~ file (though I suspect it's accidental / unintentional). Regardless, ~ is a valid path character and as such should be supported in an ideal world.

The simplest fix would seem to be to use a case-insensitive comparison if on a case-insensitive file system.

**Closed as completed** 2020-03-18 22:53 UTC
Labels: Type:Bug, Area:ErrorHandling, Functionality:Restore
