### ISSUE TITLE
Project that does not target net40 now requires it via nuget restore

### ISSUE THREAD

**Issue by MSFTFox** [NuGet/Home#6543] opened 2018-02-07 00:35 UTC
## Details about Problem

When running nuget restore on the Islandwood project, https://github.com/Microsoft/WinObjC, we've encountered a new issue with Visual Studio 2017 update 15.4. The projects in build.sln do not target net40.

NuGet version: 4.4.0.4475

dotnet.exe --version: 2.1.2

VS version (if appropriate): VS 2017 15.4.5

OS version: Windows 10 17091

Worked before? If so, with which NuGet version: Yes, even with this current version of 4.4.0.

## Detailed repro steps so we can see the same problem

1. Clone WinObjc
2. Follow set up instructions on https://github.com/Microsoft/WinObjC for contributing.
3. Attempt to run nuget.exe restore <repo root>/build/build.sln

### Verbose Logs
`PS C:\il\.tools> .\nuget.exe restore ..\build\build.sln
MSBuild auto-detection: using msbuild version '15.4.8.50001' from 'C:\Program Files (x86)\VS154\MSBuild\15.0\bin'.
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks.Core\WinObjC.Frameworks.Core.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks.UWP\WinObjC.Frameworks.UWP.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks\WinObjC.Frameworks.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks.ThirdParty\WinObjC.Frameworks.ThirdParty.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks.UWP.Core\WinObjC.Frameworks.UWP.Core.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks.Core\WinObjC.Frameworks.Core.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks.ThirdParty\WinObjC.Frameworks.ThirdParty.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks.UWP.Core\WinObjC.Frameworks.UWP.Core.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks.UWP\WinObjC.Frameworks.UWP.nuproj]
C:\il\common\workaround\Microsoft.Nuget.Workaround.targets(25,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [C:\il\build\WinObjC.Frameworks\WinObjC.Frameworks.nuproj]`

**Comment by nkolev92** [comment] 2019-04-16 23:32
I'd imagine this is a duplicate of https://github.com/dotnet/project-system/issues/3164. 

Since this is fairly old, I'll close this. 
If you are still having problems please file a new issue .

**Closed as completed by nkolev92** 2019-04-16 23:32 UTC
