### ISSUE TITLE
Updating package removes 'allowedVersions' constraint

### ISSUE THREAD

**Issue by MartinJohns** [NuGet/Home#1130] opened 2015-08-07 04:44 UTC
I have an issue in *Visual Studio 2015 RTM Community Edition* when updating a package that has a '*allowedVersions*' constraint.

Reproduction steps:
- Create new empty console application.
- Install an old version of Json.net: `Install-Package Newtonsoft.Json -Version 6.0.1`
- Modify `packages.config` and add a version constraint: `allowedVersions="(,7.0.0)"` (up to but less than 7.0.0).
- Update the NuGet package using `Update-Package` (update all packages) OR by using `Update-Package Newtonsoft.Json -ToHighestMinor`.
- :warning: NuGet updated the package from 6.0.1 to 6.0.8, but while updating the `packages.config` it removed the `allowedVersions` constraint.

The expected behavior is to update the package, but keep whatever `allowedVersion` constraint is specified.

**Comment by yishaigalatzer** [comment] 2015-08-07 17:57
This is a duplicate of #585 we have a fix in flight for this. Justin can you please verify this scenario as well.

**Comment by emgarten** [comment] 2015-08-11 00:41
AllowedVersions is removed due to the way updates are handled as uninstalls followed by installs. The fix for this is to add the allowed versions information into the context so that it can be reapplied.

**Comment by yishaigalatzer** [comment] 2015-08-11 02:41
This is a regression from vs2013, so we should fix if Dan's doesn't cover it

**Comment by emgarten** [comment] 2015-08-28 22:20
This has been fixed, updates will now persist allowedVersions

NuGet/NuGet3@0d6ed7352bc9e8f2874e7e34c7f9130f88dd9a38
NuGet/NuGet.PackageManagement@5f381df8959daebef7fcaa7dbe4179e86517558a

**Closed by emgarten** 2015-08-28 22:20 UTC
Labels: Priority:1, Type:Bug
