### ISSUE TITLE
partial-ngen nuget DLLs which ship in VS to reduce JIT cost in core scenarios

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#6007] opened 2017-10-09 21:06 UTC
Figure out the right set of DLLs to ngen, measure JIT time and see if it Ngen'ing has any advantages, run it by the VS Perf and Reliability team.

**Comment by jainaashish** [comment] 2018-07-31 18:41
There have been some or the other issues while doing this work. The latest issue pop up when we tried to do partial ngen with OptProf. NuGet assemblies were not being loaded with existing scenarios while running OptProf tests. Need to investigate that with "VS IDE Perf Reliability" team. 

We'll look at it for dev16.

**Comment by dtivel** [comment] 2019-01-31 23:31
Dupe of #4350?

**Comment by jainaashish** [comment] 2019-01-31 23:34
No, Idea of #4350 was to reduce count of NuGet assemblies inside VS and club some smaller assemblies together.

**Comment by dtivel** [comment] 2019-05-08 21:28
Instrumented assemblies are not getting loaded because Visual Studio is loading some NuGet assemblies using `Assembly.LoadFrom(...)`, which doesn't check for instrumented assemblies.  This work item is effectively blocked on internal work item 677891, which involves moving from [ProvideBindingPath](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providebindingpathattribute?view=visualstudiosdk-2017) to [ProvideCodeBase](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providecodebaseattribute?view=visualstudiosdk-2017).

**Comment by rainersigwald** [comment] 2019-06-12 14:59
I think ngen without optprof is likely a significant improvement; should this be blocked on optprof?

With the recent split in packaging, I think it's possible to just add `vs.file.ngenArchitecture=all` to the assemblies in

https://github.com/NuGet/NuGet.Client/blob/bdcec93681afdd1f5cd553af07414a3b3d9a866c/setup/Microsoft.VisualStudio.NuGet.BuildTools.swr

That's what we do in MSBuild and it results in ngened assemblies (orthogonal to optprof instrumentation changing how ngen does its work) (https://github.com/microsoft/msbuild/blob/87255d576bcd260dceb8cc52a369564529ac98e7/src/Package/MSBuild.VSSetup/files.swr).

**Comment by rainersigwald** [comment] 2019-06-12 15:01
Oh, no, I'm wrong: that should still be done but would impact only build tools SKUs; the full VSIX would need an equivalent opt-in to ngen.

**Comment by dtivel** [comment] 2019-08-02 21:39
Steps:
* [ ] Onboard to OptProfV2 with `ShouldSkipOptimize` == `true`
* [ ] After at least one successful release, change `ShouldSkipOptimize` to `false`

**Comment by rrelyea** [comment] 2019-10-31 23:15
Enabled and shipping in VS 16.4

**Closed as completed by rrelyea** 2019-10-31 23:15 UTC
Labels: Product:VS.Client, Tenet:Performance, Epic, Product:VS.PMConsole
