### ISSUE TITLE
NuGet.exe 4.3.0 prints additional stacktrace for invalid commands

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5779] opened 2017-08-19 00:29 UTC
[this came from Azure Web Sites Deployment team internal testing of NuGet.exe 4.3 at launch]

Behavior with previous nuget.exe (4.1.0)

```
C:\home>nuget invalidcmd
Unknown command: 'invalidcmd'

```
Behavior with nuget.exe 4.3.0

```
C:\home>nuget invalidcmd
Unknown command: 'invalidcmd'
NuGet.CommandLine.CommandLineException: Unknown command: 'invalidcmd'
   at NuGet.CommandLine.CommandManager.GetCommand(String commandName)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by zhili1208** [comment] 2017-08-21 20:34
this is introduced by https://github.com/NuGet/NuGet.Client/commit/3dc00f3f9620e131303c083a8703f8bddaa36b68, we should add "Debug" verbosity level for printing call stack, 
https://github.com/NuGet/Home/issues/5749

**Comment by rrelyea** [comment] 2017-08-21 23:40
let's not add a new command line option.
Let's just hide the exception in this case.

**Comment by nkolev92** [comment] 2018-06-11 05:33
Duplicate of https://github.com/NuGet/Home/issues/7009. 

Closing this despite being older as the other one has more public visibility.

**Closed as completed by nkolev92** 2018-06-11 05:33 UTC
Labels: Resolution:Duplicate, Priority:3, Product:NuGet.exe
