### ISSUE TITLE
dotnet.exe - additional nuget functionality - update and update --all

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4899] opened 2017-03-27 02:47 UTC
In the order or priority:

1. updateall
2. update - this functionality is present with 'add' command
3. list

**Comment by anangaur** [comment] 2017-04-04 00:29
Making separate issues for each command

**Comment by anangaur** [comment] 2017-04-04 00:31
Update - https://github.com/NuGet/Home/issues/4965
List - https://github.com/NuGet/Home/issues/4966

**Comment by mishra14** [comment] 2017-05-09 23:16
dupe of https://github.com/NuGet/Home/issues/4102 and https://github.com/NuGet/Home/issues/4103

**Closed as completed by mishra14** 2017-05-09 23:16 UTC
Labels: Resolution:Duplicate, Type:Feature
