### ISSUE TITLE
Dependency name of project reference not taken from PackageId

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#4642] opened 2017-02-17 07:36 UTC
## Versions
NuGet version: 4.0.x (included in VS2017)
VS version: VS 2017 RC3
OS version: Win 10

## Detailed repro
1. Create a new solution with two .NET standard projects (ClassLibrary1 and ClassLibrary2)
2. Add the `PackageId` property to the ClassLibrary1 project and use "CustomName" as value
3. Add a project reference from ClassLibrary1 to ClassLibrary2
4. Build the solution
5. Use `msbuild /t:pack` in the ClassLibrary2 folder to create a package
6. The package has "ClassLibrary1" as dependency

## Problem
I expected "CustomName" as dependency

**Comment by emgarten** [comment] 2017-02-17 08:55
@tomkuijsten how did you restore the projects?

**Comment by tomkuijsten** [comment] 2017-02-17 10:35
I didn't explicitly restore the projects, I changed the repro steps with where I executed the build.

**Comment by emgarten** [comment] 2017-02-17 10:52
Try running msbuild /t:Restore and then building/packing.

**Comment by rrelyea** [comment] 2017-02-17 11:55
Thanks for report. Dupe of #4586 
At risk for RTM.
Workaround: restore via command line before packing.

**Closed as completed by rrelyea** 2017-02-17 11:55 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug, Functionality:Pack, Functionality:Restore
