### ISSUE TITLE
Feature request: persistently specify allowed version ranges for package references

### ISSUE THREAD

**Issue by IanKemp** [NuGet/Home#10264] opened 2020-11-13 14:46 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 5.8.0

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): VS 2019 Enterprise 16.8.1

OS version (i.e. win10 v1607 (14393.321)): Windows 10 Pro version 2004 (OS build 19041.630)

Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem

1. I have a **.NET Core 3.1** csproj with a package reference defined as the following:

```xml
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.9" />
```

Since .NET 5.0 was recently released, but is not LTS, my organisation does not allow us to update to version 5.0.0 of the various packages. However, we should keep up-to-date with whatever versions of the 3.1 branch, and they just released version 3.1.10, so I want to update to that version of this package.

2. Going into the NuGet UI for the project in question, it suggests the version 5.0.0 package as the update, which I **do not want**. I also do not want that anyone else (e.g. juniors) can see this, as they might try updating to this version.

3. Therefore, I edit the csproj to use a [version range](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges) to constrain the allowable versions:

```xml
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="[3.1.9,5.0.0)" />
```

4. Reloading the project and going into the NuGet UI again, things are now correct: the UI prompts me to update to version 3.1.10. I click to update to that version.

5. The package updates, the NuGet UI refreshes, and... **now it  prompts me to upgrade to version 5.0.0 again**. Looking at the csproj file, the reason becomes obvious - my range expression has been nuked by the update:

```xml
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.10" />
```

---

However, I would argue that it's **incorrect** to allow a range expression in the `Version` attribute anyway. To my mind, the `Version` attribute should specify the **explicit version** of this dependency that is **currently referenced**.

What is needed, in my opinion, is a new attribute on the `PackageReference` node to encapsulate the concept of "allowed version range", that won't be mutated when a package is updated. Something like `AllowedVersions`:

```xml
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.9" AllowedVersions="(,5.0.0)" />
```

With that implemented, I would expect to open the NuGet UI in VS and only be presented with an option to upgrade to version 3.1.10. The upgrade would then rewrite the csproj to contain the following:

```xml
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.10" AllowedVersions="(,5.0.0)" />
```

and consequently, the NuGet VS UI would **not** offer me the option to upgrade to version 5.0.0 of the package.

By default, `AllowedVersions` would be absent, which would mean the behaviour would be equivalent to NuGet's current "offer the highest version available".

**Comment by marcin-krystianc** [comment] 2020-11-18 16:21
To me it looks more like a bug, because the update process didn't preserve upper bound of the version range.
If it was working correctly it would left the entry as:
```
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="[3.1.10,5.0.0)" />
```

I find it also confusing that `Version` attribute in the `ProjectReferece` element is actually a version range, but I don't that it is ever going to changee as it would cause too many backwards compatibility issues,

**Comment by KalleOlaviNiemitalo** [comment] 2021-03-14 07:24
This would be cool for [ASP.NET Core 2.1 on .NET Framework](https://dotnet.microsoft.com/platform/support/policy/aspnetcore-2.1), as well.

**Comment by IanKemp** [comment] 2021-03-16 13:22
> To me it looks more like a bug, because the update process didn't preserve upper bound of the version range.
> If it was working correctly it would left the entry as:
> 
> ```
> <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="[3.1.10,5.0.0)" />
> ```
> 
> I find it also confusing that `Version` attribute in the `ProjectReferece` element is actually a version range, but I don't that it is ever going to changee as it would cause too many backwards compatibility issues,

I agree that overloading the meaning of `Version` was a big mistake. To sidestep that whole mess, we could add another property called `InstalledVersion`, that is quite literally the version of the package that is currently installed in that project against (i.e. what `Version` **should** have been). `InstalledVersion` will have a higher precedence than `Version`, to allow for the eventual deprecation of `Version` and removal of all code that references its convoluted logic.

Essentially, there will be two code paths:

* If `InstalledVersion` and/or `AllowedVersions` is present, the new code path that uses these attributes will be followed (behaviour as in my original proposal). This code path will only ever reference `Version` to populate it for backwards compatibility (will set it to the same value as `InstalledVersion`).
* Otherwise, the current `Version` code path will be used. The only change here will be to populate `InstalledVersion` with the currently-installed version of the package, so that next time NuGet is run against the project, the previous (new, sane) code path will be used.

An example of a PackageRef defined by this proposal:

```xml
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" InstalledVersion="3.1.9" AllowedVersions="(,5.0.0)" Version="3.1.9" />
```

This would result in any NuGet-understanding tool only offering an update for `Microsoft.Extensions.Options.ConfigurationExtensions` that satisfies 3.1.9 ≤ version< 5.0.0. Assuming that version 3.1.11 is available and chosen by the user, the PackageRef is then updated to:

```xml
<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" InstalledVersion="3.1.11" AllowedVersions="(,5.0.0)" Version="3.1.11" />
```

It would also be helpful if [this](https://github.com/NuGet/Home/issues/5553) was implemented, but given that issue is nearly 4 years old at this point, it seems unlikely.

**Comment by zivkan** [comment] 2021-06-04 13:46
Closing as duplicate of https://github.com/NuGet/Home/issues/6566

**Closed as completed by zivkan** 2021-06-04 13:46 UTC
Labels: Product:VS.Client, Priority:2, Type:DCR, Functionality:VisualStudioUI, Style:PackageReference

**Comment by zivkan** [comment] 2021-06-04 13:47
Oops, I forgot to mention, please 👍 that issue, since GitHub doesn't provide a way to transfer upvotes.

**Comment by PeterKnaggs** [comment] 2024-12-05 15:48
I am still having this issue in 17.12.3.
