### ISSUE TITLE
Package search finding incompatible (netstandard) packages for (pcl) target

### ISSUE THREAD

**Issue by StephenCleary** [NuGet/Home#3570] opened 2016-10-02 13:41 UTC
Repro:
- Create a new PCL library targeting `Profile259`.
- Do a NuGet search for "AsyncEx".

The first result is `Nito.AsyncEx.Tasks`, which only targets `netstandard1.3` and `net46`.

Attempting to install this search result causes an error `Could not install package 'Nito.AsyncEx.Tasks 1.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by yishaigalatzer** [comment] 2016-10-03 18:12
@StephenCleary there is no filtering at the moment in search, so this is an expected behavior until we re-implement search filtering.

@rrelyea can we find the dup and close?

**Comment by rrelyea** [comment] 2016-12-08 19:02
Dupe of https://github.com/NuGet/Home/issues/4071

**Closed as completed by rrelyea** 2016-12-08 19:02 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Functionality:VisualStudioUI
