### ISSUE TITLE
If reference assembly exists for nuget library, no HintPath is added

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#3443] opened 2016-09-14 14:52 UTC
from: https://bugzilla.xamarin.com/show_bug.cgi?id=43915#c18

> It comes down to Nuget on Windows. Under Xamarin Studio on Mac when you add the FSharp.Core Nuget package it adds a reference to the correct mobile platform and adds a HintPath to the reference like so 

```
<Reference Include="FSharp.Core">
  <HintPath>packages\FSharp.Core.4.0.0.1\lib\portable-net45+monoandroid10+monotouch10+xamarinios10\FSharp.Core.dll</HintPath>
</Reference>
```

> This tells the build system to look for FSharp.Core in the nuget package directory. 
> 
> Under Visual Studio this hint path is NOT added to the reference. As a result the system ALWAYS picks up the System provided FSharp.Core which is the older version. Hence the error. 
> 
> Adding the correct HintPath to the project file seems to fix the issue. But why does Nuget NOT add the hint path in the first place is the real question here.

Is this by-design?

**Comment by yishaigalatzer** [comment] 2016-09-14 19:36
This is a duplicate of a known bug in the F# project system. We discussed with Don Syme and agreed that the fix will need to go there.

@rrelyea can you please find and dedup the issue.

**Comment by idg10** [comment] 2017-08-17 13:08
This looks like it could be a duplicate of https://github.com/NuGet/Home/issues/1510 - although that issue purports to be about a Numerics component, it looks like it's caused by the basic root issue described in this issue.

The issue that had been tracking this over in F# was Microsoft/visualfsharp#939 but that got closed without it being fixed. Someone ran into this again recently, and I thought it might be helpful to put together a timeline for this bug which you can find at [https://github.com/Microsoft/visualfsharp/issues/3415#issuecomment-323080543](https://github.com/Microsoft/visualfsharp/issues/3415#issuecomment-323080543)

**Comment by nkolev92** [comment] 2018-02-01 23:26
Duplicate of https://github.com/NuGet/Home/issues/1510.

**Closed as completed by nkolev92** 2018-02-01 23:26 UTC
Labels: Resolution:Duplicate
