### ISSUE TITLE
C++ projects cannot install nuget package on VS "15" Preview

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#2541] opened 2016-04-14 02:16 UTC
NuGet 827

Repro in Dev15, follow repro steps:
1.Create C++ Win 32 Project, Visual C++->Win 32->Win32 Project, click Finish.
2.Install package "cpprestsdk" from nuget.org.

Expected results: Installed successful.
Actually results: Install meet error.
![capture](https://cloud.githubusercontent.com/assets/12129698/14515175/d8346bf6-0229-11e6-9bae-d425724877ba.PNG)

**Comment by rrelyea** [comment] 2016-04-14 20:28
Thanks for the report. We are actively working on a fix of this. Won't be overnight. 
Dupe of https://github.com/NuGet/Home/issues/2369

**Closed as completed by rrelyea** 2016-04-14 20:28 UTC
