### ISSUE TITLE
"version" environment variable improperly used

### ISSUE THREAD

**Issue by mheyman** [NuGet/Home#8794] opened 2019-11-06 14:16 UTC
## Details about Problem
If one sets the "version" environment variable prior to running `nuget restore` than the restore will fail if the value isn't something like 1.2.3

NuGet product used: NuGet.exe | Package Manager Console | dotnet.exe
NuGet version:  4.8.1.5435
dotnet.exe --version: 3.0.1
VS version: 16.3.7
OS version: Win10 v1809 (17763.805)
Worked before? Unknown

## Detailed repro steps so we can see the same problem

<span>1.</span> `C:\> set version=foobar`
<span>2.</span> `C:\Users\me\source\repos\my-project> nuget.exe restore`
<span>3.</span> _Error_:
```
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018: The "WriteRestoreGraphTask" task failed unexpectedly. [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018: System.ArgumentException: 'foobar' is not a valid version string. [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018: Parameter name: value [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at NuGet.Versioning.NuGetVersion.Parse(String value) [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at NuGet.Commands.MSBuildRestoreUtility.GetVersion(IMSBuildItem item) [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at NuGet.Commands.MSBuildRestoreUtility.GetPackageSpec(IEnumerable`1 items) [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at NuGet.Commands.MSBuildRestoreUtility.GetDependencySpec(IEnumerable`1 items) [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at NuGet.Build.Tasks.WriteRestoreGraphTask.Execute() [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
C:\Users\me\AppData\Local\Temp\NuGetScratch\svt3pbho.qvo.nugetrestore.targets(144,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\Users\me\AppData\Local\Temp\NuGetScratch\ulzrrznd.1ke.nugetinputs.targets]
```
   **_or_**
<span>2.</span> `C:\Users\me\source\repos\my-project> dotnet restore`
<span>3.</span> _Error_:
```
C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): error : 'foobar' is not a valid version string. (Parameter 'value') [C:\Users\me\source\repos\my-project\MyProject.sln]
```
   **_or_**
<span>2.</span>  `C:\> devenv.exe`
   Then, from package manager console:
<span>3.</span>  `PM> Update-Package -Reinstall`
<span>4.</span> _Error_:
```
Update-Package : The operation failed as details for project CSRTests could not be loaded.
At line:1 char:1
+ Update-Package -Reinstall
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

## Other suggested things

Documentation page https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-environment-variables doesn't reflect usage of the "version" environment variable.

### Verbose Logs
[foobarlog.txt](https://github.com/NuGet/Home/files/3814825/foobarlog.txt)

**Comment by zkat** [comment] 2019-11-06 16:25
Oh this is a fun one! Thanks a lot for the detailed bug report. I'm sure you did a lot of good sleuthing to narrow it down to this. I've triaged this and we'll discuss scheduling a fix for this as a team. I personally agree that this is a bug, especially because there's such a high likelihood of conflict with other tooling, and because it's probably pretty insidious when folks run into it. I think we can probably do better here.

Thanks again!

**Comment by zivkan** [comment] 2019-11-08 19:50
[From msbuild's docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2019):

> All environment variables are available to the Microsoft Build Engine (MSBuild) project file as properties.

If nothing overwrites the version property before NuGet reads it, I think it's working as designed.

**Comment by nkolev92** [comment] 2020-04-08 02:58
Closing this as by design per https://github.com/nuget/home/issues/8794#issuecomment-551967051. 

This is a known MSBuild behavior.

**Closed as completed by nkolev92** 2020-04-08 02:58 UTC
Labels: Functionality:Restore, Resolution:NotABug, Area:Versioning
