### ISSUE TITLE
Packages in "Managed NuGet Packages..." window should have a link to the NuGet site.

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7534] opened 2018-11-21 00:44 UTC
<p>When selecting a package in the NuGet window, some information about the package is displayed, such as link to License, Project URL, and a link for &quot;Report Abuse&quot;.</p><p>What is missing, is a clickable link to the NuGet website for the package. <br><br>For instance, the package &quot;Microsoft.NETCore.UniversalWindowsPlatform&quot; has links to the License (github.com/dotnet/core-setup), Project URL (github.com/Microsoft/dotnet), and &quot;Report Abuse&quot; (https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.2.2/ReportAbuse).<br><br>But there is no link to &quot;https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.2.2&quot; (without the &quot;ReportAbuse&quot; suffix).</p><p>The nuget.org website is great when linking someone a package, or a specific version of the package, or when using fuget.org (replace the &quot;n&quot; in nuget-URL with &quot;f&quot; to view api).<br>For the mentioned package, the fuget URL would be: https://www.fuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.2.2</p><p><br></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/382708/packages-in-managed-nuget-packages-window-should-h.html
VSTS ticketId: 729420_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/15/2018, 00:11 AM (5 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by nkolev92** [comment] 2018-11-21 05:30
Duplicate of #5299 and https://github.com/NuGet/Home/issues/7470

**Closed as completed by nkolev92** 2018-11-21 05:30 UTC
Labels: Resolution:Duplicate, Type:Feature, Functionality:VisualStudioUI, Area:Protocol
