### ISSUE TITLE
PackageManager Update All doesn't handle failures

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#3143] opened 2016-07-15 13:33 UTC
Consider 2 package updates, one will fail and the other succeeds.

If these updates are done individually NuGet will handle the failing one, and roll it back.

If these updates are done in an "update all" batch, NuGet will allow both the updates to occur leaving the project in a broken state.

I'd expect NuGet to allow the successful update, but roll back the failed update.

**Comment by rrelyea** [comment] 2016-07-15 16:45
dupe of https://github.com/NuGet/Home/issues/3139

**Closed as completed by rrelyea** 2016-07-15 16:45 UTC
Labels: Resolution:Duplicate
