### ISSUE TITLE
restore should support multiple project files targeting same baseintermediateobjdir

### ISSUE THREAD

**Issue by niemyjski** [NuGet/Home#4850] opened 2017-03-20 15:11 UTC
I'm running the latest VS2017 release and dotnet 1.0.0 on windows 10 x64 stable. I came across a potential bug with dotnet restore.

Here is the a link the source:
https://github.com/exceptionless/Exceptionless.Net/tree/9614d2bc1d2cb949945d05ff4dbf0d8bed0738f0

I have to have signed nuget packages so my initial goal was to have my shared library have a project.csproj and a project.signed.csproj in the same folder. Then in depending packages (projectc) have a msbuild condition based on the state of `SignAssembly` and reference the correct csproj file and set the new package id. This failed because dotnet restore creates the lock file without signing. So when I build projectc it works, when I do a second pass on projectc with a msbuild property set to enable signing it would compile the first signed target framework and then blow up with a crazy error. I have sense abandoned this approach and went for a new csproj and folder per signed project as I couldn't get around this.. I no longer have the error message but it should be simple to reproduce.

**Comment by nkolev92** [comment] 2020-02-04 20:47
Duplicate of https://github.com/NuGet/Home/issues/4463

**Closed as completed by nkolev92** 2020-02-04 20:47 UTC
Labels: Resolution:Duplicate, Priority:2, Type:DCR, Functionality:Restore
