### ISSUE TITLE
VS crash on nuget restore on asp .net core web app project

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3801] opened 2016-10-27 20:51 UTC
1. Create a new project of ASP .Net core web application and choose Web API template.
2. do restore.

It crash VS!

If it doesn't happen first time, then try closing this solution and re-open again and do restore. Try these steps couple of times.

Root Cause: it happens when you click restore when auto-restore is still in progress.

**Comment by rrelyea** [comment] 2016-10-27 22:27
Dupe of #3797 ??

**Comment by jainaashish** [comment] 2016-10-27 22:49
Not completely dupe of #3797 since here auto restore is already running, and we start a explicit restore. We should show warning message of a restore still in progress when this happens and discard this. But both the bugs could be worked upon in single PR.

**Comment by rrelyea** [comment] 2016-10-28 23:24
yes, #3797 will solve.

**Closed as completed by rrelyea** 2016-10-28 23:24 UTC
Labels: Priority:1, Resolution:Duplicate, Type:Bug, Platform:Xplat, Functionality:Restore, Style:PackageReference
