### ISSUE TITLE
Implicitly Referenced by an SDK - Two of the same projects, one says this and the other does not.

### ISSUE THREAD

**Issue by DanJ210** [NuGet/Home#7310] opened 2018-09-19 21:07 UTC
I've created two very minimal, easy .Net Core Web API's. I've updated one of the packages, Microsoft.AspNetCore.App to 2.1.4 while the other project says "Implicitly referenced by an SDK. To update the package, update the SDK to which it belongs to." I'm trying to figure out why one project says this and another project does not when both were created together at the same time. When I follow the learn more link, it talks about this briefly but doesn't give me any insight into why this happened and how I can avoid this.

I've got the 2.1.4 SDK installed, actualy 2.1.400, 2.1.401 and 2.1.402, even the new preview 2.2. I can update the target framework of each project to 2.2 and then both of them will let me update the packages to 2.2. But I'm not ready to jump to preview yet.

I'm just trying to figure out why one project says it is bound to the main SDK install and that I need to update it which to me looks like I already have, and the other lets me update the NuGet package.

**Comment by jainaashish** [comment] 2018-09-20 19:51
I wasn't able to follow your comment and understood your issue completely so can you elaborate what you mean one project allows you to update SDK package even without updating SDK version itself? You should always update the SDK in order to update Microsoft.AspNetCore.App package.

It will also help if you can share a sample repro to depict your issue which will help with the analysis.

**Comment by DanJ210** [comment] 2018-10-29 16:13
So one project you can update via NuGet package by going to the Solution Explorer > Mange NuGet Packages > Update Package, no problem. The other project does not allow this and says that I must update the SDK installed which is by downloading and installing the SDK, this is the one that says implicitly referenced by SDK.

Why is one project controlled by the installed SDK and the other project is controlled by the NuGet package SDK.

I don't know if sharing a repo in this case would help because the repo would need my environment to try and update the package and throw the error. But the question is that I created the two projects above, two .Net Core 2.0 Web API projects, one is implicitly referenced while the other is not. So I'm trying to understand how that happens differently for one than the other of the same project template.

**Comment by jainaashish** [comment] 2018-10-29 17:41
`So one project you can update via NuGet package by going to the Solution Explorer > Mange NuGet Packages > Update Package, no problem.`

How did you create this project? can you look into `obj/project.assets.json` file and confirm `Microsoft.AspNetCore.App` has `AutoReference` set to true at the end?

Your other project is behaving correctly, this package is always controlled by installed SDK, and shouldn't be allowed to be updated explicitly.

**Comment by DanJ210** [comment] 2018-11-29 15:38
Ok I have more info @jainaashish 

So both projects were created using the Visual Studio 2017 template for Asp.Net Core Web API. Both are the same target framework of 2.1. One project I can update the Microsoft.AspNetCore.App via the NuGet package manager which is how I'm used to doing it. The other one says blocked by project because it's implicitly referenced.

Below is the code from the project.assets.json for the project that I can update using the NuGet package manager built into Visual Studio.

```
"frameworks": {
      "netcoreapp2.1": {
        "dependencies": {
          "Microsoft.AspNetCore.App": {
            "target": "Package",
            "version": "[2.1.6, )"
          },
          "Microsoft.AspNetCore.Mvc.Api.Analyzers": {
            "target": "Package",
            "version": "[2.2.0-preview2-35157, )"
          },
          "Microsoft.NETCore.App": {
            "target": "Package",
            "version": "[2.1.0, )",
            "autoReferenced": true
          },
          "Serilog": {
            "target": "Package",
            "version": "[2.7.1, )"
          },
          "Serilog.Sinks.RollingFile": {
            "target": "Package",
            "version": "[3.3.0, )"
          },
          "Swashbuckle.AspNetCore": {
            "target": "Package",
            "version": "[3.0.0, )"
          }
        },
        "imports": [
          "net461"
        ],
        "assetTargetFallback": true,
        "warn": true
      }
```

Below this is the same code from the same file but for the project that is implicitly referenced.

```
"frameworks": {
      "netcoreapp2.1": {
        "dependencies": {
          "Microsoft.AspNetCore.App": {
            "suppressParent": "All",
            "target": "Package",
            "version": "[2.1.1, )",
            "autoReferenced": true
          },
```

So then I wonder why one has `autoReferenced` and the other does not but both were created the same way. I've never seen the project blocked issue I've always updated packages via the NuGet package manager. Is there a problem with me removing the `autoReference` and doing it the way I'm used to? Or should I always be locking it to the manually installed SDK?

**Comment by DanJ210** [comment] 2018-11-29 15:46
And it looks like remove the `autoReferenced` from the blocked project doesn't lift the block either.

**Comment by DanJ210** [comment] 2018-11-29 16:22
Also, I don't even know how to update the one that's implicitly referenced. I've deleted all .Net Core 2.1.1* installations from control panel. I only have 2.1.5 and 2.2 preview 3 but the project still says that it's on 2.1.1 and I can't update it like all the other projects that I have. So how does one update a project that's implicitly referenced?

**Comment by nkolev92** [comment] 2019-03-29 18:34
@DanJ210 
The idea of implicitly referenced is that you shouldn't update it from the UI. 

You update that by upgrading the SDK that implies that reference. 

I wouldn't know why one project was created without autoreferenced as that's on the project template and not NuGet. 

Does this all make sense? 
Any further assistance you need from us?

**Comment by DanJ210** [comment] 2019-04-10 13:33
@nkolev92 I suppose it does make sense I'm just trying to make sure I understand. So if I delete all of the SDK's that I have intalled and I install dotnet core 3.0 then the implicitely referenced projects should change and show that they are dotnet core 3.0?

**Comment by nkolev92** [comment] 2019-04-10 18:08
Yes, it's the SDK that guides those versions. If there's a package coming from the SDK that's not autoreferenced, it might be a bug in the SDK (which might have been fixed later on)

**Comment by Lemraj** [comment] 2019-04-23 08:34
I had the same problem in .Net Core project. This worked fine for me:
Edit your *.csproj file and add or update the following:

![image](https://user-images.githubusercontent.com/10677560/56566841-e6f6dc00-65b3-11e9-8fb8-ce3441ad25c5.png)

`<TargetLatestRuntimePatch>True</TargetLatestRuntimePatch>`

**Comment by nkolev92** [comment] 2019-04-23 18:06
Closing this as not a bug. 

@Lemraj You are merely targeting the latest patch for that runtime. Usually that setting is used when packaging portable apps. 

You are still not "updating" the versions manually, rather than choosing one or another SDK setting.

**Closed as completed by nkolev92** 2019-04-23 18:06 UTC
Labels: Product:VS.Client, Functionality:Restore, Triage:NeedsMoreInfo, WaitingForCustomer

**Comment by Lemraj** [comment] 2019-04-24 10:59
@nkolev92 Thanks for your comment!
I had to use this "trick", otherwise I could not upgrade to 2.2.4 version.
I have done this before with other versions and there was no issue at all. This time I have downloaden all the .net core runtime and sdk and installed it. But still I can't upgrade to the latest version 2.2.4.

Any idea why?

**Comment by nkolev92** [comment] 2019-04-24 17:46
@Lemraj 
You shouldn't be upgrading these manually. 
You shouldn't even be thinking of these as packages you control. Those are "frameworks".  
You should let the SDK make that decision for you. 

The way to "upgrade" is to update the SDK you are using.

**Comment by Lemraj** [comment] 2019-04-24 18:44
@nkolev92 That is the way I always follow, but this time it didn't work!
I know that I shouldn't do this manually, but I am looking for the right answer to my answer!

Like I said, that is why I did this manually trick!

**Comment by nkolev92** [comment] 2019-04-24 19:00
@Lemraj I'd reach out to the dotnet/sdk folks to understnad which version should match which package. 

In .NET Core 3.0, all these packages will be removed and the user will be "unable" to make any such decisions.

**Comment by Lemraj** [comment] 2019-04-24 19:07
@nkolev92 Thanks! I will wait for your answer.

**Comment by nkolev92** [comment] 2019-04-24 19:11
Didn't mean to sound like I'll ask them question directly. 

Please describe your scenario and file an issue with them at https://github.com/dotnet/sdk/issues/new.

**Comment by Lemraj** [comment] 2019-04-24 19:12
fair enough! I will do that.

**Comment by Lemraj** [comment] 2019-04-25 16:17
@nkolev92 
I have noticed that this issue is only related to xunit projects.
