### ISSUE TITLE
Nuget update command add packages in to project that does not use it.

### ISSUE THREAD

**Issue by bondarchook** [NuGet/Home#2642] opened 2016-04-22 09:30 UTC
I am trying to update one package in all projects of solution.

using something like this:
`nuget.exe update My.sln -Id package1`

Some projects in solution use package1 some not.
But when i run this command, package1  gets added to projects that does not use it.

Example:
Before 

```
My.sln
 ------ Proj1
          --------  package1
 ------ Proj2
          --------  some other package
```

After running command  `nuget.exe update My.sln -Id package1`:

```
My.sln
 ------ Proj1
          --------  package1 [new version]
 ------ Proj2
          --------  some other package
          --------  package1 [new version]  <---- Added to project that does not use it
```

This does not have any sense. 

When you run update command without **-Id** parameter `nuget.exe update My.sln`
Then it just update all packages but it never add anything.

**-Id** parameter should act as filter and not add any new behaviour 

Update command should never add anything new to projects. Only update what is in project now.

**Comment by rrelyea** [comment] 2016-04-25 17:37
What version of nuget.exe are you using?

**Comment by rrelyea** [comment] 2016-04-25 17:39
Duplicate of #2394.
Please update to 3.4.3 and confirm it still repros.

**Closed as completed by rrelyea** 2016-04-25 17:39 UTC
Labels: Resolution:Duplicate
