### ISSUE TITLE
dotnet restore fails with dotnet 2.1.302

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7204] opened 2018-08-14 19:34 UTC
_From @myermian on August 14, 2018 19:7_

## Steps to reproduce
Run dotnet restore on a solution or csproj, utilizing a nuget.config and TFS package management.

## Expected  behavior
The tool restores all of the NuGet packages without any issue.

## Actual behavior
An error occurs:

C:\Program Files\dotnet\sdk\2.1.302\NuGet.targets(114,5): error : Failed to retrieve information about '{package}' from remote source '{tfs_uri}/_packaging/c813af9a-8ce1-439f-aac2-bb906c3bbe0d/nuget/v3/flat2/{package}/index.json'. [{csproj_file}]
C:\Program Files\dotnet\sdk\2.1.302\NuGet.targets(114,5): error :   The target principal name is incorrect [{csproj_file}]

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Some projects work without a problem, some projects work when I use the `--ignore-failed-sources` argument (I don't think this is a good fix), and some projects don't work at all in either scenario because the source that is failing is our private package management feed, so it can't rely on nuget.org to get the correct packages.

Additionally, I'm not sure if this is a NuGet/Home issue or a dotnet issue, so I posted it in here because the problem started when we moved from NetCore 2.0 to NetCore 2.1 for our SDK/Runtime. Even netstandard and netcore 2.0 applications are failing when using the netcore 2.1.302 sdk.

_Copied from original issue: dotnet/cli#9833_

**Comment by zhili1208** [comment] 2018-08-14 21:45
@myermian could you try "dotnet restore --verbosity diag"? and share the log

**Comment by myermian** [comment] 2018-08-15 15:29
Log attached...
[BuildLog.txt](https://github.com/NuGet/Home/files/2290320/BuildLog.txt)

**Comment by zhili1208** [comment] 2018-08-15 22:32
try to understand this is source related or machine related?  could you repro this with other source on this machine? or repro on anther machine with this source?

**Comment by lzocateli** [comment] 2018-08-16 03:55
I'm having the same problem, I use VSTS agent onpremises

PS D: \ UserApps \ AgentVSTS \ _work \ 2 \ s> dotnet --info
.NET Core SDK (reflecting any global.json):
Version: 2.1.300
Commit: adab45b

Runtime Environment:
OS Name: Windows
OS Version: 6.1.7601
OS Platform: Windows
RID: win7-x64
Base Path: C: \ Program Files \ dotnet \ sdk \ 2.1.300 \

Host (useful for support):
Version: 2.1.2
Commit: 811c3ce6c0

.NET Core SDKs installed:
2.1.300 [C: \ Program Files \ dotnet \ sdk]
2.1.400 [C: \ Program Files \ dotnet \ sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.0 [C: \ Program Files \ dotnet \ shared \ Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.2 [C: \ Program Files \ dotnet \ shared \ Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0 [C: \ Program Files \ dotnet \ shared \ Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.2 [C: \ Program Files \ dotnet \ shared \ Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.0 [C: \ Program Files \ dotnet \ shared \ Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.2 [C: \ Program Files \ dotnet \ shared \ Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download
PS D: \ UserApps \ AgentVSTS \ _work \ 2 \ s>

![image](https://user-images.githubusercontent.com/16601706/44186316-1aad6800-a0ef-11e8-80ea-3135a8b499eb.png)

**Comment by myermian** [comment] 2018-08-16 13:32
@zhili1208 : This issue happens on not only the build agent, but also any of our team members computers. This also affects solutions which are setup to use dotnet core 2.0 (not just dotnet core 2.1 projects). If I uninstall the DotNet Core 2.1 SDK (reverting back to DotNet Core 2.0 SDK), the dotnet core 2.0 projects work just fine.

**Comment by zhili1208** [comment] 2018-08-16 17:58
@myermian It looks like the framework issue. Could you try to set env variable "DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER" to 0? does that solve the issue? +@nkolev92

**Comment by AdrianSanguineti** [comment] 2018-08-31 01:19
I too am experiencing the exact same error message with my private hosted TFS agents and nuget. I have set the "DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER" environment variable to 0 and restarted my agents. The error now appears to have gone away (for now at least).

**Comment by PatoBeltran** [comment] 2019-01-25 01:03
Closing this issue as there is no more information to understand the issue. Feel free to reopen if the issue is persisted.

**Closed as completed by PatoBeltran** 2019-01-25 01:03 UTC
Labels: Triage:NeedsMoreInfo
