### ISSUE TITLE
Relative path in NuGet.Config is automatically changed to absolute path on build

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1200] opened 2015-08-17 13:55 UTC
_From @theo-albers on August 17, 2015 12:50_

NuGet 2.8.5 breaks previous behaviour with respect to relative path references in NuGet.Config. Before it was possible to have a relative path in NuGet.config. To proof it worked before, see http://stackoverflow.com/questions/12932906/how-do-you-set-a-relative-path-for-a-file-based-package-source-with-nuget. We utilize this feature to define a workspace with a local package folder to be shared across 10 related solutions. We keep our own packages in that shared folder. 

After the upgrade to NuGet 2.8.5 inside VS2013, but also when using VS2015, something automatically changes the NuGet.config file and changes the relative path to an absolute path. The original NuGet.config file in the .nuget folder of the solution looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <add key="Itesso package source" value="..\..\build-output\packagesource" />
  </packageSources>
</configuration>
```

When any developer opens the solution, the file will be automatically changed to:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSources>
    <add key="Itesso package source" value="C:\dev\src\Common\.nuget\..\..\build-output\packagesource" />
  </packageSources>
</configuration>
```

Via the pending changes window the NuGet.config file gets checked in by mistake, breaking the environment for other developers. This behavior also interferes with our TFS2012 build server setup, which no longer is able to find the packages for restore. 

_Copied from original issue: NuGet/NuGetGallery#2625_

**Comment by theo-albers** [comment] 2015-08-17 18:05
Here is a solution to reproduce the problem easily, http://1drv.ms/1E0Rw2J. Open the solution ProjectConsumingPackage.sln with older NuGet installation for VS2013, so a pre 2.8.5 version. Build will not touch the NuGet.config file in the .nuget folder. 
Remove workspace and unzip again. Now upgrade to the latest NuGet-version, via Tools, Extensions and Updates inside VS2013, restart VS and open the solution and build. Now it changes NuGet.config.

**Comment by AlexEyler** [comment] 2015-08-19 18:13
We're hitting this issue as well (the Visual Studio Platform team).

**Comment by theo-albers** [comment] 2015-08-19 20:17
I also spotted that it trims the default packagesource as well, so:

```
  <packageSources>
    <add key="NuGet official package source" value="https://nuget.org/api/v2/" />
    <add key="Itesso package source" value="..\..\build-output\packagesource" />
  </packageSources>
 <activePackageSource>
    <add key="All" value="(Aggregate source)"  />
  </activePackageSource>

```

results in:

```
 <activePackageSource>
    <add key="All" value="(Aggregate source)"  />
  </activePackageSource>
 <packageSources>
    <add key="Itesso package source" value="C:\dev\src\Common\.nuget\..\..\build-output\packagesource" />
  </packageSources>
```

**Comment by theo-albers** [comment] 2015-09-01 07:57
Just found a workaround for the problem: as long as we remove the default V2 package source, the NuGet config logic won't migrate the NuGet.config file. So the remedy for us is to use the following file:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>

  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>

  <packageSources>
    <remove key="Itesso package source" />
    <add key="Itesso package source" value="..\..\build-output\packagesource" />
  </packageSources>

  <activePackageSource>
    <add key="All" value="(Aggregate source)"  />
  </activePackageSource>

</configuration>
```

instead of:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>

  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>

  <packageSources>
    <clear />
    <add key="NuGet official package source" value="https://nuget.org/api/v2/" />
    <add key="Itesso package source" value="..\..\build-output\packagesource" />
  </packageSources>

  <activePackageSource>
    <add key="All" value="(Aggregate source)"  />
  </activePackageSource>

</configuration>
```

**Comment by yishaigalatzer** [comment] 2015-10-20 21:29
Looks like a duplicate of a bug @zhili1208 is working on for 3.3

**Closed as completed** 2015-10-27 17:27 UTC
Labels: Resolution:Duplicate, Type:Bug

**Comment by masaeedu** [comment] 2016-06-21 21:17
@yishaigalatzer Where is this bug tracked?

**Comment by zhili1208** [comment] 2016-06-21 21:31
Here is the bug link https://github.com/NuGet/Home/issues/1017
