### ISSUE TITLE
Feedback/Data?? -- Auto-restore fails multiple times until all projects are loaded

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#4577] opened 2017-02-11 00:48 UTC
### Details about Problem

Auto-restore will fail multiple times when opening a solution containing more than one project with following error:

```
Error occurred while restoring NuGet packages: The operation failed as details for project WebApplication3 could not be loaded.
```

Eventually when all of projects get nominated the last auto-restore will succeed:
```
Restoring NuGet packages...
Time Elapsed: 00:00:14.5134111
========== Finished ==========
```

The problem lies in the fact of irregular nomination intervals. It leads to sporadic triggering of auto-restore before all necessary project data is placed into a cache.

### Proposal

Provide better mechanism for combining requests:
1. Increase idle interval
1. Hide known errors from user
1. Put a barrier blocking auto-restore from running.
1. ...

Update from Rob: Also seen in Internal bug 382293

**Comment by emgarten** [comment] 2017-02-15 18:25
Here is the output from opening NuGet.Core.sln

```
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.XPlat.FuncTest could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.Packaging.Core.Test could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project NuGet.Packaging.Core.Test could not be loaded.
Restoring NuGet packages...
```

I think we should consider this for RTM

**Comment by emgarten** [comment] 2017-02-15 23:35
This looks the same as https://github.com/NuGet/Home/issues/4307

**Comment by emgarten** [comment] 2017-03-10 16:45
Moving to 4.1 based on user feedback

**Comment by emgarten** [comment] 2017-03-10 21:24
Based on https://github.com/dotnet/roslyn-project-system/issues/1725#issuecomment-285753309 it sounds like this error isn't always benign and sometimes means the project isn't actually restored until the solution is reloaded.

**Comment by rrelyea** [comment] 2017-03-21 20:15
Dupe of #4307

**Closed as completed by rrelyea** 2017-03-21 20:15 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Platform:Xplat, Functionality:Restore
