### ISSUE TITLE
Add option for installing prerelease packages to dotnet add package

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5517] opened 2017-06-30 17:10 UTC
_From @svick on June 30, 2017 10:48_

Currently, when I want to add a prerelease package to a project, I have to explicitly specify its version. For example: `dotnet add package System.Memory` does not work, but `dotnet add package System.Memory -v 4.4.0-preview2-25405-01` does.

This is inconvenient when I want to install the latest version of the package, even if it's prerelease. So I propose that a new `--prerelease` option should be added to `dotnet add package`, which would allow installing prerelease packages without having to explicitly specify package version.

This is similar the the `-IncludePrerelease` option to `Install-Package`.

_Copied from original issue: dotnet/cli#7043_

**Comment by mishra14** [comment] 2017-06-30 19:44
@emgarten restore should consider supporting `--pre-release` as we have discussed in the past.

**Comment by mishra14** [comment] 2017-07-10 16:05
Closing as dupe of #4699

**Closed as completed by mishra14** 2017-07-10 16:05 UTC
Labels: Resolution:Duplicate, Functionality:Restore, Style:PackageReference
