### ISSUE TITLE
NuGet install error message - NuGet does not indicate which frameworks a package targets

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#6946] opened 2018-05-17 19:11 UTC
Sory to use that term but once again Nuget's messed up design hits me in Visual Studio (2017).

Why o why o why doesn't Nuget tell me WHAT VERSION OF .NET IS REQUIRED when it refuses to install a package becuase the package is not compatible with the project's current target framework?

Here's what I see:

`Could not install package 'RestSharp 106.2.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

Why does Nuget not cater for this in a more professional manner like:

1. Telling me what version of framework **is** required.
2. Providing options to install an earlier version that **does** target my current framework (if there are any).

I see no reason why the Nuget system (if it can tell the assembly in the package is not of a suitable version) cannot include the version that the package expects, how hard is it to do that?

Surely it is not rocket science to filter the available package version by target framework? or include in the Version dropdown list some mention of the minimum framework version that's required for the listed package version? that's how any sensible software designer would approach this!

**Comment by emgarten** [comment] 2018-05-18 21:00
Dupe of https://github.com/NuGet/Home/issues/4874

**Comment by nkolev92** [comment] 2018-05-29 17:32
Thanks @emgarten 

Closing as duplicate. 

@Korporal 
We'd appreciate if you can please use more descriptive issue titles :)

**Closed as completed by nkolev92** 2018-05-29 17:32 UTC
Labels: Resolution:Duplicate, Area:ErrorHandling, Style:Packages.Config
