### ISSUE TITLE
Combine duplicate package downgrade warnings into actionable output

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#2409] opened 2016-03-28 17:46 UTC
Restoring on Entity Framework with verbosity minimal still produced  4,722 lines of warnings resulting from "Detected package downgrade." This includes hundreds of duplicate warnings, such as this line that is logged _108 times_ when restoring the EF:

> warn : Detected package downgrade: System.Resources.ResourceManager from 4.0.1-rc2-23923 to 4.0.1-rc2-23911 

Full log: 
[restorelog.txt](https://github.com/NuGet/Home/files/192200/restorelog.txt)

It is nearly impossible for a human to digest thousands of lines of log output and figure out how to solve the problem.

**Comment by emgarten** [comment] 2016-03-28 18:39
This shouldn't be an issue once the netstandard packages stabilize. Until then these are valid warnings  and they should be shown for each project.

**Comment by yishaigalatzer** [comment] 2016-03-29 04:14
This looks like a duplicate of https://github.com/NuGet/Home/issues/910.

We could combine all downgrade errors into some packages have forced a downgrade, and create one of these per project.

**Closed as completed** 2016-03-29 04:14 UTC
Labels: Resolution:Duplicate
