### ISSUE TITLE
Troubles with nuget.exe 3.4.4.1321

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#3315] opened 2016-08-15 20:57 UTC
I'm trying to download all the NuGet.\* packages via command line. When I try to run

```
nuget install NuGet.Commands -Version 3.5.0-beta2-1484 -OutputDirectory packages -Source https://api.nuget.org/v3/index.json -NoCache
```

it hangs without any useful messages. I have successfully installed almost all the packages except: `NuGet.Commands`, `NuGet.DependencyResolver`, `NuGet.PackageManagement`, `NuGet.ProjectManagement`, `NuGet.ProjectModel`. What I'm doing wrong?

**Comment by emgarten** [comment] 2016-08-15 21:17
nuget.exe install is an old command that does not support target frameworks, it isn't going to work for these packages. Typically the framework comes from the project, but in the case of nuget.exe install there is no project.

I suggest creating a project.json file that references the top level packages you need and using nuget.exe restore download and resolve the dependencies if you are trying to do this outside of a project.

**Comment by AndreyAkinshin** [comment] 2016-08-15 21:28
Hmm... Is there another way to download these libraries? And why I can install `NuGet.Client`? What the difference between `NuGet.Client` and `NuGet.Commands`?

**Comment by emgarten** [comment] 2016-08-15 21:44
The easiest way might be this
1. Create a new class library in visual studio targeting .NET 4.5 or higher
2. From the NuGet UI or powershell console install NuGet.Commands
3. Copy out the packages.config file

The packages.config file will contain the complete closure of packages you need, you can then run `nuget.exe install packages.config -OutputDirectory packages -Source https://api.nuget.org/v3/index.json -NoCache`

By using a project to get the packages.config everything will be resolved for .NET 4.5.  If you need netstandard you would need to use project.json.

You likely want NuGet.Commands, that is where all the top level commands such as push, pack, and restore are. NuGet.Client is a very small library that helps find package assets in a nupkg.

**Comment by AndreyAkinshin** [comment] 2016-08-15 21:52
You did not answer my last question: what the difference between `NuGet.Client` and `NuGet.Commands` with respect to the `install` command? Why I can install `NuGet.Client` and can't install `NuGet.Commands`? In fact, I want to download all the `NuGet.*` packages.
Will you support a way to download any nuget packages from the command line without `packages.config` or `project.json` in the future?

**Comment by emgarten** [comment] 2016-08-15 23:39
> what the difference between NuGet.Client and NuGet.Commands with respect to the install command? Why I can install NuGet.Client and can't install NuGet.Commands?

NuGet.Client has less dependencies, but both packages would depend on NETStandard.Library which would bring in the most packages.

My guess is that the install here isn't hung, it's just taking a while. You can increase verbosity with `-Verbosity Detailed`, this may give more details no the current http requests.

The latest 3.5.0-rc version of nuget.exe has some performance fixes around resolving packages, it may help your scenario: https://dist.nuget.org/index.html

The problem is even if all downloads finish the result may still be random since there is no project target framework to base decisions on when selecting dependency groups from the nuspec file. The install command should likely display a warning when encountering any packages that contain multiple target frameworks.

> Will you support a way to download any nuget packages from the command line without packages.config or project.json in the future?

Can you provide more details on your scenario and what you are trying to do? NuGet scenarios typically revolve around adding packages to projects, not just downloading packages to disk in a standalone manner.

**Comment by AndreyAkinshin** [comment] 2016-08-16 00:04
3.5.0-rc works fine for me, thanks!

I want to have the NuGet.\* libraries in my project, but for some reason I want to have a single NuGet dependency instead of a set of 20+ dependencies. So, I have a script that download all the packages from nuget.org, build a new package (which contains all the dll files) and deploy it on a local NuGet server.

**Comment by emgarten** [comment] 2016-08-16 00:10
Interesting :smile:  the nuget.\* packages are built for project.json scenarios, there you can just specify the top level dependency to bring everything in. I can see how it would be tedious to install 20+ packages with packages.config.

**Closed as completed** 2016-08-16 01:51 UTC
