### ISSUE TITLE
Publish nuget package directly to nuget repository

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9855] opened 2020-07-28 23:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/801900/publish-nuget-package-directly-to-nuget-repository.html)._

---
It would be very useful to be able to publish directly to a private nuget repository!
Instead I have to build and execute a command manually everytime!

---
#### Feedback Bot on 11/1/2019, 00:21 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### Feedback Bot on 1/21/2020, 04:51 PM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it up to 90 days for community input</p>

#### Richard Ashdown on 4/28/2020, 08:17 AM: 

<p>I would also like to publish directly from Visual Studio to a private repository (currently using a third party add-on).</p><p>I am also looking at migrating to Azure Artifacts so would like to publish directly from VS to my Artifact feed(s).</p>

**Comment by zkat** [comment] 2020-08-10 20:19
Closing as duplicate of https://github.com/NuGet/Home/issues/4459

**Closed as completed by zkat** 2020-08-10 20:19 UTC
Labels: Product:VS.Client, Type:Feature, Functionality:Push, Triage:NeedsTriageDiscussion, Product:dotnet.exe
