### ISSUE TITLE
Issues with TeamCity NuGet Server

### ISSUE THREAD

**Issue by jamsoft** [NuGet/Home#2347] opened 2016-03-16 23:48 UTC
I have just updated to VS2015 U2 and my TeamCity feed doesn't appear to work for updated packages.  I get the error:

Root element is missing.

If I go to the Browse panel on the same feed, all the packages are listed and I can upgrade to the new package versions.

**Comment by yishaigalatzer** [comment] 2016-03-17 00:12
Can you tell us what is your root URL?
Can you add /odata at the end of the URL?

**Comment by yishaigalatzer** [comment] 2016-03-17 01:00
@jamsoft actually I don't quite follow what works and what doesn't. Would you mind providing a detailed repro?

We will setup a server for us to experiment

**Comment by jamsoft** [comment] 2016-03-17 09:36
OK Sure, sorry I didn't include more details initially.

The feed URL I'm using for my TeamCity server (hosted on the same machine as I'm working in Visual Studio) is:

http://localhost:9001/guestAuth/app/nuget/v1/FeedService.svc/

I have browsed:

http://localhost:9001/guestAuth/app/nuget/v1/FeedService.svc/$metadata

And everything looks as expected.

If I browse:

http://localhost:9001/guestAuth/app/nuget/v1/FeedService.svc/odata

I see:
`
<error>
    <code>NotFoundException</code>
    <message lang="en-US">EdmEntitySet odata is not found</message>
</error>`

**Error Details and Repo**

So I perform a build on a TeamCity build configuration that publishes various NuGet packages for use by other projects (also produces some for deployments via Octopus Deploy which all works fine).

Then in a project that consumes one of these published packages I do:
1. Right click on the solution
2. Select _Manage NuGet Packages for Solution_
3. Go to the Update panel (as I KNOW there are updates to consume)
4. Error message

```
Error occured:
Root element is missing.
```

I also see this same error on the Updates panel if I right-click on a project node rather than the main solution node in the solution explorer.

**Workaround**

Without switching the selected NuGet feed.
1. Go to the Browse panel and it immediately reads the feed and shows all the expected packages in that feed.
2. Select the package I was expecting to see in the Updates panel.
3. Select each solution project that references that package
4. Click Install
5. Upgrade proceeds as expected

**Comment by johnataylor** [comment] 2016-03-18 17:26
We have seen two distinct issues in the TeamCity NuGet feed.

1) if the dependency specification string exceeds 1024 characters TeamCity appears to truncate the string. This caused a semantic version string specified inside a dependency version range to be cropped such that it was not longer even a syntactically legal string. This caused an exception in the client and the Browse tab showed that exception. This appears to be an issue in the TeamCity server and nothing something that we can fix in the client. However we could have better error handling.

2) The Update tab executes a series of FindPackageById calls on the TeamCity server. The server returned 204 for a package that was not available. In this particular scenario the 204 triggered an exception in the client code (as if it was a 404) we've changed this now to skip over and produce an empty result rather than an exception. This was actually quite a bad situation because often a user would be using the ALL sources option and if that was the case the exception generated from the call to the TeamCity source prevented the data from the other sources from being accessed.

Fixing this second issue I managed to install packages and updates successfully from our TeamCity server. In my scenario I avoided the case described in (1) by specifying a search request that avoided the offending package.

However, my testing was not extensive. We have a couple of other fixes in the protocol in this check-in. It would be good to try these latest builds on your TeamCity server.

**Comment by jamsoft** [comment] 2016-03-27 13:29
OK, That all sounds promising.  Have you reported this scenario to JetBrains?  I've not looked for an issue on their bug tracker yet.

If you haven't reported this, I can.

**Comment by yishaigalatzer** [comment] 2016-03-27 15:19
We have reported the 204, and their answer was that they plan to deprecate the nuget server support in teamcity. Tbh it is probably not a server you want to use for anything with more than a few packages as it only supports the v1 protocol.

I would urge you to look into alternative and more modern servers like nuget.server or other free 3rd party servers

**Comment by rrelyea** [comment] 2016-05-02 23:32
Dupe of #2456

**Closed as completed by rrelyea** 2016-05-02 23:32 UTC
