### ISSUE TITLE
Installing EntityFramework.BulkInsert-ef6 crashes VS 2015 RC

### ISSUE THREAD

**Issue by mrchief** [NuGet/Home#560] opened 2015-05-10 05:59 UTC
Tried many times and each time it crashed VS 2015 right after "Attempting to Gather dependencies...". This happens both via the GUI and the PM Console.

The same got installed via VS 2013 's package manager without any issues.

**Comment by yishaigalatzer** [comment] 2015-05-10 19:54
Can you please provide a callstack and even nicer a dump?
One know crash that might be related? Did you restart your computer after installing RC?

**Comment by feiling** [comment] 2015-05-11 21:07
@mrchief to help us repro the issue, could you share your packages.config file?

**Comment by mrchief** [comment] 2015-05-12 02:00
@feiling Here you go:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AutoMapper" version="3.2.1" targetFramework="net45" />
  <package id="CsvHelper" version="2.8.2" targetFramework="net45" />
  <package id="DataAnnotationsExtensions" version="1.1.0.0" targetFramework="net45" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net46" />
  <package id="EntityFramework.BulkInsert-ef6" version="6.0.2.8" targetFramework="net46" />
  <package id="EntityFramework.MappingAPI" version="6.0.0.7" targetFramework="net46" />
  <package id="FluentValidation" version="5.5.0.0" targetFramework="net45" />
  <package id="LINQKit" version="1.1.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="3.2.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.2" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="6.0.6" targetFramework="net45" />
</packages>
```

@yishaigalatzer Thought as much while creating the issue but I'm not sure how to get the call stack and the dump. DO you mean VS' activity.log?

**Comment by yishaigalatzer** [comment] 2015-05-12 03:27
Activity log could help. But you can also just attach another visual studio when it crashes or just before

**Comment by mrchief** [comment] 2015-05-12 15:04
It just disappears when it crashes. Heck, even "End Task" isn't this smooth. :smiling_imp:  

I'll try attaching before and getting the activity log.

**Comment by yishaigalatzer** [comment] 2015-05-12 15:56
Can you tell us if you restarted your machine after installing visual studio?

**Comment by feiling** [comment] 2015-05-12 23:30
This is a duplicate of https://github.com/NuGet/Home/issues/539.

**Closed by feiling** 2015-05-12 23:30 UTC
Labels: Area:VS.Client, Priority:1, Type:Bug

**Comment by mrchief** [comment] 2015-05-13 01:46
@yishaigalatzer Yes, I restarted. Do you still need dumps from me?

**Comment by yishaigalatzer** [comment] 2015-05-13 03:23
We do have a local repro. So no need for dumps.
