### ISSUE TITLE
Question: Is there a story for Hight DPI icons? I am safe to use them?

### ISSUE THREAD

**Issue by Bartmax** [NuGet/Home#5346] opened 2017-06-05 19:51 UTC
Is it safe to add a 128 or 256 icon on the package icon setting to account for the nuget website display and ui for high dpi monitors?

I tried and looks likes there are no real *issue* but before moving into mainstream packages I want to ask if there's a story around or any unintended sideeffects for including a bigger dimension as the spec.

Thanks.

**Comment by mstum** [comment] 2017-06-05 20:02
Hijacking this to ask if Vectors (Safe subset of SVG?) are on some roadmap?

**Comment by nkolev92** [comment] 2017-06-05 23:10
@anangaur Can you please help here.

**Comment by Bartmax** [comment] 2017-08-22 23:35
Ping ...

**Comment by anangaur** [comment] 2017-08-26 05:02
I don't see a problem with either 128 or 256 icons.

**Comment by anangaur** [comment] 2017-08-26 05:03
@mstum not in our backlog as of now.

**Comment by zivkan** [comment] 2020-11-23 19:41
closing as a duplicate of https://github.com/NuGet/Home/issues/2519. Please upvote (👍 ) that issue.

**Closed as completed by zivkan** 2020-11-23 19:41 UTC
Labels: Resolution:Duplicate, Priority:3, Type:Feature, Functionality:VisualStudioUI
