### ISSUE TITLE
Centrally Managing Packages Fails for F# Projects

### ISSUE THREAD

**Issue by tachyus-ryan** [NuGet/Home#10612] opened 2021-03-02 21:47 UTC
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): dotnet.exe

Product version: 5.8.0.6930

Worked before? If so, with which NuGet version: No

## Repro steps and/or sample project

* [Sample project](https://github.com/panesofglass/nuget-central-fsharp-core)
* Try to run `dotnet restore`
* Try to add `FSharp.Core` with `dotnet add src/Repro package FSharp.Core`

### Verbose Logs

[restore.log](https://github.com/NuGet/Home/files/6071992/restore.log)
[add.log](https://github.com/NuGet/Home/files/6071993/add.log)

### Work-arounds
* @baronfel provided a work-around that ignores the implicit FSharp.Core reference: [Sample project](https://github.com/panesofglass/nuget-central-fsharp-core/tree/workaround)

**Comment by rrelyea** [comment] 2021-03-05 19:25
using dotnet.exe 5.1.200, after doing the dotnet add command.
The .fsproj file changes from:
`    <PackageReference Include="FSharp.Core" />`
To:    
```
    <PackageReference Include="FSharp.Core">
      <Version>5.0.1</Version>
    </PackageReference>
```

expected behavior is that the package version that already has been defined centrally would keep the version from being added here.

**Comment by tachyus-ryan** [comment] 2021-03-05 19:33
Thanks @rrelyea. I didn't have `5.1.200` when I tried this previously. I'll update and try again.

**Comment by tachyus-ryan** [comment] 2021-03-05 19:35
@rrelyea is that an issue with FSharp.Core? cc @cartermp

**Comment by tachyus-ryan** [comment] 2021-03-05 19:36
@rrelyea it looks like this changed after I merged a contribution from someone that found a work-around. Let me revert that and then post that as a work-around.

Edit: I have reverted the master branch so that it once more shows the issue. It seems the work-around results in another issue where the version is stamped on the `.fsproj` file.

**Comment by aortiz-msft** [comment] 2021-03-08 21:07
Also, Central Package Version Management is in early preview so there's no support from it in the CLI or Visual Studio.

**Comment by tachyus-ryan** [comment] 2021-03-08 21:56
@aortiz-msft thank you for the update. Do you need anything more from me?

**Comment by aortiz-msft** [comment] 2021-03-11 18:12
No. I will close this issue for now since this functionality is not yet supported. Thanks again!

**Closed as completed by aortiz-msft** 2021-03-11 18:12 UTC
Labels: Type:Bug, Product:dotnet.exe, Area:RestoreCPM
