### ISSUE TITLE
Remove support for parsing the 'Any' framework

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#749] opened 2015-06-09 17:47 UTC
NuGet should stop parsing the 'any' folder name since it can be confused with other frameworks.

**Comment by emgarten** [comment] 2015-06-09 18:25
@davidfowl is there any other special handling that should be done around the default/any framework?

**Comment by yishaigalatzer** [comment] 2015-06-09 21:08
@emgarten please provide more details on this issue

**Comment by yishaigalatzer** [comment] 2015-06-12 23:52
duplicate of #496

**Closed** 2015-06-12 23:52 UTC
Labels: ClosedAs:Duplicate
