### ISSUE TITLE
Nested packages should be searchable

### ISSUE THREAD

**Issue by dongdong-yang** [NuGet/Home#7313] opened 2018-09-20 14:30 UTC
NuGet product used : "Manage Nuget Packages for Solution"

```
NuGet Package Manager version : 4.6.0
dotnet.exe --version (if appropriate): .NET core 2.1.401
VS version (if appropriate): vs 2017(15.8.4)
OS version (i.e. win10 v1607 (14393.321)): win10 
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3277	Found conflicts between different versions of "Microsoft.OData.Edm" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	Sitecore.Commerce.Engine	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	2110
```	

the package "Microsoft.OData.Edm" is nest-referenced by many many packages, and it's too deep to find which packages are referencing it.

Nested packages should be searchable or listed or diagram somewhere so that we can easily figure out where are conflicts.

**Comment by jainaashish** [comment] 2018-09-20 19:39
Dupe of https://github.com/NuGet/Home/issues/5887 please follow that issue and commnet/ upvote there.

BTW we have an upcoming feature for `dotnet.exe list packages` which will list all the transitive packages and allow to search for the updates for any of the transitive dependency. This feature will be available in dotnet 2.2.1xx release.

**Closed as completed by jainaashish** 2018-09-20 19:39 UTC
