### ISSUE TITLE
NuGet.exe 3.4.4 fails to restore due to allegedly missing runtime assemblies

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#2915] opened 2016-06-07 15:27 UTC
When trying to upgrade from nuget.exe 3.3.0 to 3.4.4, I observed that package restore failed. 

Firstly, due to nuget crawling more projects more aggressively, which I was able to [workaround](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/VS%20IDE%20DevCore/_git/DevCore/commit/1d590d5d9d72a916e48d6e941ebeb668a0b36a2f).

Secondly, because for a bunch of CoreFx packages "there is no run-time assembly compatible with win":

```
    System.AppContext 4.0.0 provides a compile-time reference assembly for System.AppContext on .NETFramework,Version=v4.5.1, but there is no run-time assembly compatible with win.
    System.IO.Pipes 4.0.0-beta-23409 provides a compile-time reference assembly for System.IO.Pipes on .NETFramework,Version=v4.5.1, but there is no run-time assembly compatible with win.
    System.Net.Sockets 4.1.0-beta-23409 provides a compile-time reference assembly for System.Net.Sockets on .NETFramework,Version=v4.5.1, but there is no run-time assembly compatible with win.
    System.Diagnostics.Process 4.0.0-beta-23409 provides a compile-time reference assembly for System.Diagnostics.Process on .NETFramework,Version=v4.5.1, but there is no run-time assembly compatible with win.
    System.Runtime.InteropServices.RuntimeInformation 4.0.0-beta-23409 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on .NETFramework,Version=v4.5.1, but there is no run-time assembly compatible with win.
    System.Security.Cryptography.Algorithms 4.0.0-beta-23409 provides a compile-time reference assembly for System.Security.Cryptography.Algorithms on .NETFramework,Version=v4.5.1, but there is no run-time assembly compatible with win.
```

I don't know how to workaround this. This appears to be a regression in nuget.exe 3.4.4 as some of these are 'stable' corefx packages and I wouldn't expect nuget.exe to break them.

I [tried changing all my project.json](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/VS%20IDE%20DevCore/_git/DevCore/commit/6c1056cd3d545de571269491ab28f68e6db5cd44)'s mentions of `runtimes: { "win": { } }` to mention `win-x86` and `win-x64` instead but that didn't help.

Repro steps:

```
git clone https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/DevCore
cd DevCore\src\coreclr
git checkout dev/andarno/accomodateNuGet344
nuget restore
```

**Comment by emgarten** [comment] 2016-06-07 15:40
This looks related to https://github.com/NuGet/Home/issues/2246

 For net451 the runtime assembly would come from the framework reference.

A possible workaround here is to reference these packages with `exclude: runtime` or avoid including them as dependencies for net451 if possible and add them under frameworkAssemblies instead in your project.json file.

**Comment by AArnott** [comment] 2016-06-07 16:16
I'm working through it... I've brought down the number of failures through your `exclude: runtime` technique, but it's tedious because the errors don't specify _which_ project is producing them. Combining that with transitive dependencies and it's really hard to find which dependencies need this added.

I haven't used `frameworkAssemblies` before in my MSBuild-based project.json projects. Is it necessary that I add all these `exclude:runtime` dependencies to this new list as well? This is making my project.json _way_ larger and more complicated than before.

**Comment by AArnott** [comment] 2016-06-07 16:20
So since System.Runtime is one of the packages that fail, I basically have to add this `exclude: runtime` on _all_ my dependencies since virtually all of them transitively depend on it.

**Comment by emgarten** [comment] 2016-06-07 16:59
You can set it for the top level dependency and it will be applied to all.

When referencing the System packages from a desktop framework you get the frameworkAssembly reference from the nuspec of that package which points to the desktop .NET, it works the same. I suggest finding where these packages are getting in for net451 and limit them to be dependencies for your dotnet/netstandard framework if possible. I wasn't immediately able to tell how it was happening from looking at your solution.

**Comment by emgarten** [comment] 2016-06-07 17:01
And to be clear, it is a bug in NuGet that it doesn't find the framework assembly as the runtime assembly. But the plan is to remove this check from NuGet and move it to the build side of things, which is why it hasn't been fixed.

**Comment by AArnott** [comment] 2016-06-07 17:02
I have a lot of top level dependencies, and a lot of projects. Yes, I do see that I can specify it at the top level dependencies and it's applied to their dependencies transitively, but it's still a lot of manual work to add this.

Some of these dependencies get in through packages that all my target frameworks need. So I have to apply `exclude: runtime` on non framework packages as well to ensure that `System.Runtime` is never depended on such that an error would occur.
After a couple hours on it, I still haven't been able to track down the link that is causing the last error to still be reported.

**Comment by AArnott** [comment] 2016-06-07 17:03
> But the plan is to remove this check from NuGet and move it to the build side of things, which is why it hasn't been fixed.

But as this makes 3.4.4 _really_ hard to adopt, and 3.3.0 worked, except now I've found a bug in 3.3.0 where it doesn't propagate dependencies transitively if projects aren't under the solution directory (and 3.4.4 evidently fixes that), I'm between a rock and a hard place here. I wish 3.4.4 hadn't been allowed to regress this.

**Comment by emgarten** [comment] 2016-06-07 17:08
This problem has existed since 3.1.0. My guess is that it showed up in your solution due to transitive dependencies. This check is only done when there are runtimes involved, so it is likely that you have a portable library applying these packages to the desktop framework, and higher up another library with runtimes now gets these dependencies also, then fails when applying the runtime check.

**Comment by emgarten** [comment] 2017-11-30 00:52
Duplicate of https://github.com/NuGet/Home/issues/2246

**Closed as completed by emgarten** 2017-11-30 00:52 UTC
Labels: Resolution:Duplicate
