### ISSUE TITLE
Unable to overwrite dgspec.json file in Docker scenario

### ISSUE THREAD

**Issue by mthalman** [NuGet/Home#7836] opened 2019-02-28 14:28 UTC
A regression has been encountered that occurred between .NET Core SDK versions 3.0.100-preview-010184 and 3.0.100-preview3-010366 that causes a new file that was introduced, *.csproj.nuget.dgspec.json, to be unable to be overwritten during a build of a Docker image in certain circumstances.
 
The environment in which this issue occurs is a Docker image based on NanoServer-1709, NanoServer-1803, or Nano-Server-1809 running with Windows Server with Containers as the Docker host.  This does not repro for Linux images.  It doesn't even repro when using Windows 10 as the Docker host.
 
In the repro steps, a Docker 3.0 SDK Docker image is used to create a project which is then copied out of the container and into the Docker host where it is then used to build another Docker image based on that project.  The building of this second Docker image fails with the error:
`C:\Program Files\dotnet\sdk\3.0.100-preview3-010366\NuGet.targets(119,5): error : Access to the path 'C:\app\obj\app.csproj.nuget.dgspec.json' is denied. [C:\app\app.csproj]`
 
Note that the obj folder is being included in the build context and copied to the Docker image.  Normally this would not occur if a .dockerignore file were to be used so that would be the workaround for the specific scenario identified here.  But I feel it's important to understand what caused the regression in case there are other scenarios that may be affected without an available workaround.
 
The execution of the `dotnet build` in the container is being run in the context of the ContainerUser user who apparently does not have permission to overwrite the dgspec.json file.  Interestingly, in the version of .NET Core SDK where this issue does not repro, the files have the same ACLs as they do in the version where the behavior regressed.  But, for whatever reason, the process is unable to overwrite the files.
 
Here's what happens with the ACLs on the version of the SDK where everything works.  In this version, there is no dgspec.json generated, so I'll use nuget.cache file as an example.  Here are the ACLs for that file prior to running `dotnet build`:
* BUILTIN\Administrators: Full Access
* NT AUTHORITY\SYSTEM: Full Access
* BUILTIN\Users: Read/Execute
 
And here they are after running `dotnet build`:
* BUILTIN\Administrators: Full Access
* NT AUTHORITY\SYSTEM: Full Access
* **User Manager\ContainerUser: Full Access**
* BUILTIN\Users: Read/Execute
 
So in that version of the SDK, `dotnet build` is able to overwrite that file.  In the case of the newer version of the SDK where this issue repros, the dgspec.json file has the same ACLs as nuget.cache prior to `dotnet build` being run.  
 
To repro, follow these steps on a Windows Server 2019 Datacenter with Containers machine (use PowerShell for running the commands):
 
1. Download https://raw.githubusercontent.com/dotnet/dotnet-docker/35fc686f158e3ebfbda32e1e753c6542fdd154dc/3.0/sdk/nanoserver-1809/amd64/Dockerfile to an empty temp folder (e.g. c:\temp).  This file uses version 3.0.100-preview3-010366 of .NET Core SDK.
(Note that this version uses version 3.0.100-preview3-010366 of .NET SDK.  The previous version of this file is located at https://raw.githubusercontent.com/dotnet/dotnet-docker/f9c352143519936f97b2be0b7f469374eb5bf64d/3.0/sdk/nanoserver-1809/amd64/Dockerfile, which uses 3.0.100-preview-010184, does not cause this issue to repro)
 
2. Set your working directory to the temp folder that you created.
 
3. Build a Docker image for the 3.0 SDK:
`docker build -t sdkimage .`
 
4. Create a test project using that 3.0 SDK inside a Docker container:
`docker run --name testapp -w /app -p 80 sdkimage dotnet new web --framework netcoreapp3.0`
 
5. Copy the test project out of the Docker container to the Docker host machine:
`docker cp testapp:/app .`
This is an important step.  The issue does not repro if you were to run `dotnet new` and `dotnet build` within the same container.  We must first copy the created project out of the container and build a new image off of it.
 
6. Copy the following to a file named Dockerfile into the app folder that was added to your temp folder:
```
FROM sdkimage
EXPOSE 80
WORKDIR app
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN dotnet build
``` 

7. Build a Docker image for the app:
`docker build -t myapp .\app`
This command will produce this error:
`C:\Program Files\dotnet\sdk\3.0.100-preview3-010366\NuGet.targets(119,5): error : Access to the path 
'C:\app\obj\app.csproj.nuget.dgspec.json' is denied. [C:\app\app.csproj]`
The expectation is that this should successfully build the Docker image.  When using version 3.0.100-preview-010184 of the .NET Core SDK, this command does execute successfully.

8. To reproduce this error while manually interacting with the container's command line, modify the Dockerfile from step 6 so that the last line is commented out: `#RUN dotnet build`.  Then re-run the command from step 7.  It will now succeed.  Then run `docker run --rm -ti myapp`.  This will launch a command prompt running in the container.  From there you can interactively run `dotnet build` to produce the error.

9. Cleanup your Docker containers and images:
```
docker container rm -f testapp
docker container rm -f myapp
docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | findstr 'sdkimage:latest')
```

10. If you want to try these repro steps and have them succeed, you can use a different Dockerfile in step 1: https://raw.githubusercontent.com/dotnet/dotnet-docker/f9c352143519936f97b2be0b7f469374eb5bf64d/3.0/sdk/nanoserver-1809/amd64/Dockerfile.  This version of the Dockerfile uses .NET Core SDK 3.0.100-preview-010184 and does not reproduce the issue.  Since it succeeds with this version of .NET Core SDK, there's clearly something that regressed in the newer version.

**Comment by nkolev92** [comment] 2019-03-05 22:30
So I did the some digging and this one is a doozy. 
Following through 1-7 I could repro everything as demonstrated. Thanks for the great instructions @mthalman!  

Looking through the code added in https://github.com/NuGet/NuGet.Client/pull/2521 it didn't make sense to me why only this file of the 5 is an issue. All the other files were written in a similar way.

The 5 files in question are: 
* project.assets.json
* *.nuget.g.props
* *.nuget.g.targets
* *.nuget.g.cache
* *.nuget.dgspec.json

The reason for this is that the nuget.dgspec.json is the only file that's being overriden. 

dotnet build runs dotnet restore implicitly. So the first restore is the one that generates all the restore outputs (the 5 files above). The 2nd restore will be a no-op. We basically have an `IsDirty` check and only overwrite the files if needed. 
The trick is the above PR, that added the writing of the dgspec file, did not add a dirty check so it was writing at every single restore!

Basically the reason why it failed, is because that's the only file that's being overriden. 

Now to confirm my theory I deleted the dgpsec file from the local app directory after step 6 and changed `dotnet build` to `dotnet add package Newtonsoft.Json`. 

Now that failed with a different error. 

```
info : Adding PackageReference for package 'Newtonsoft.Json' into project 'C:\app\app.csproj'.
log  : Persisting no-op dg to C:\app\obj\app.csproj.nuget.dgspec.json
info : Restoring packages for C:\app\app.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/newtonsoft.json/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/newtonsoft.json/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/newtonsoft.json/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/newtonsoft.json/index.json
info :   GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/newtonsoft.json/index.json
info :   NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/newtonsoft.json/index.json 164ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/newtonsoft.json/index.json 135ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/newtonsoft.json/index.json 137ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/newtonsoft.json/index.json 114ms
info :   GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/newtonsoft.json/index.json
info :   OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/newtonsoft.json/index.json 97ms
info :   NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/newtonsoft.json/index.json 36ms
info :   OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json 494ms
info :   GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/12.0.1/newtonsoft.json.12.0.1.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/12.0.1/newtonsoft.json.12.0.1.nupkg 12ms
info : Installing Newtonsoft.Json 12.0.1.
info : Package 'Newtonsoft.Json' is compatible with all the specified frameworks in project 'C:\app\app.csproj'.
info : PackageReference for package 'Newtonsoft.Json' version '12.0.1' added to file 'C:\app\app.csproj'.
error: Access to the path 'C:\app\app.csproj' is denied.
The command 'cmd /S /C dotnet add package Newtonsoft.Json' returned a non-zero code: 1
```
Basically there was a bug in newer versions, but it's not a permissions issue. 

I'm not sure why NuGet is not able to overwrite files copied into the container. I'm not even sure if there's a NuGet issue there & I'm certainly not a docker expert. I'll fix the bug I described above and do some more digging.

**Comment by nkolev92** [comment] 2019-03-06 00:22
I created an issue for the dirty check bug #7854 and I have a PR out for that already. https://github.com/NuGet/NuGet.Client/pull/2750

**Comment by nkolev92** [comment] 2019-03-06 19:13
@mthalman 

Why do you do `COPY . .` when you try to create the 2nd image?

**Comment by mthalman** [comment] 2019-03-06 19:18
> @mthalman
> 
> Why do you do `COPY . .` when you try to create the 2nd image?

That is necessary to copy the rest of the project files into the Docker daemon.  The first copy, `COPY *.csproj .` only brings over the project file, the minimum necessary to run `dotnet restore`.  But you still need the rest of the files.

**Comment by nkolev92** [comment] 2019-03-06 19:25
For my tests I removed `COPY . .` as it overwrites the obj folder generated inside the container. 

The files that get copied from the local box to the container have the following permissions: 

```
app.csproj BUILTIN\Administrators:(I)(F)
           NT AUTHORITY\SYSTEM:(I)(F)
           BUILTIN\Users:(I)(RX)
```

NuGet cannot change those. 

The files generated within the container has the following rights. 

```
obj\project.assets.json BUILTIN\Administrators:(I)(F)
                        NT AUTHORITY\SYSTEM:(I)(F)
                        User Manager\ContainerUser:(I)(F)
                        BUILTIN\Users:(I)(RX)
```

I don't think there are any further NuGet issues here (beyond the one I fixed already in PR).

**Comment by nkolev92** [comment] 2019-03-06 19:40
Synced up with @mthalman in chat. 

Closing this issue now. 

The regression fix will probably propagate to all .NET Core SDK versions within the next few weeks. 

2.1.600, 
2.2.200 &
3.0 preview 3 all share the same NuGet code so likely all of them have the above problem.

**Closed as completed by nkolev92** 2019-03-06 19:40 UTC
Labels: Resolution:ByDesign, Functionality:Restore, Platform:Docker
