### ISSUE TITLE
dotnet restore: temporary directory is expected to be user specific

### ISSUE THREAD

**Issue by blackdwarf** [NuGet/Home#3229] opened 2016-07-27 19:14 UTC
Cross-post from dotnet/cli#1748
## Steps to reproduce

In Ubuntu 14.04 or CentOS 7.2, run dotnet restore with the user1, then run dotnet restore with the user2 failed.

$ dotnet restore -v verbose

error: Access to the path '/tmp/NuGetScratch/lock' is denied.
trace: System.AggregateException: One or more errors occurred. (Access to the path '/tmp/NuGetScratch/lock' is denied.) ---> System.UnauthorizedAccessException: Access to the path '/tmp/NuGetScratch/lock' is denied.
## Expected  behavior

All user should run dotnet restore successes in the same system.
## Actual behavior

Only one user can run dotnet restore successes in the same system.
## Environment data

`dotnet --version` output:

$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001661)

Product Information:
 Version:     1.0.0-beta-001661
 Commit Sha:  2b90a2f831

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
## Cause and Solution

During the restore, all user use the same temporary directory '/tmp/NuGetScratch/', this is absolutely wrong, we need use the user specific directory, e.g. '/tmp/NuGetScratch-${USER}/'.

**Comment by blackdwarf** [comment] 2016-07-27 19:15
From @mmalolepszy:

> I confirm this problem still exists on 1.0.0-beta-001933.

**Comment by blackdwarf** [comment] 2016-07-27 19:16
From victory2009:

> me too .
> Environment:
> OS : centos-release-7-2.1511.el7.centos.2.10.x86_64
> CLI:1.0.0-preview2-003121

**Comment by Sebosek** [comment] 2016-09-21 21:03
Same for Ubuntu 16.04.1 LTS, CLI: 1.0.0-preview2-003131

**Comment by omajid** [comment] 2016-11-10 20:42
This problem still exists with the latest 1.0.0-preview2-1 builds I have.

**Comment by TheRealPiotrP** [comment] 2016-11-16 03:32
@rrelyea do we have an idea of when this might get fixed? We're seeing a stream of issues that root cause here in CLI repo.

**Comment by omajid** [comment] 2016-11-16 16:19
See also https://github.com/NuGet/Home/issues/2793. The root cause maybe related to https://github.com/dotnet/corefx/issues/13710.

**Comment by tmds** [comment] 2016-11-18 11:13
@rrelyea could it be a fix to move the lock folder from NuGetFolderPath.Temp to NuGetFolderPath.NuGetHome. This would move it from /tmp/NuGetScratch/lock to ~/.nuget/lock?

**Comment by joelverhagen** [comment] 2017-01-06 20:24
Fixed with https://github.com/NuGet/NuGet.Client/pull/1035. Thanks @tmds!

**Closed as completed by joelverhagen** 2017-01-06 20:24 UTC
