### ISSUE TITLE
Frequent error on sln restore: System.InvalidOperationException: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by tbolon** [NuGet/Home#12376] opened 2023-01-20 09:10 UTC
### NuGet Product Used

MSBuild.exe

### Product Version

MSBuild version 17.5.0-preview-23053-01+ac0911a00 for .NET Framework ; VS 17.5 preview 3

### Worked before?

Not sure, I rearely use the command-line to restore

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

We have a solution with ~80 projets.

We use a custom nuget.config on the sln directory, which adds two packages sources (devops and devexpress) and I also jave a custom NuGet.config in %appdata%\NuGet. Because of the stacktrace, I suppose there is something wrong (no concurrency supported) on some methods related to config and source loading.

When using msbuild /t:Restore xxx.sln, I often receive this error. I have to run multiple retries for the restore to succeed.

If I try to build the sln using `msbuild xxx.sln` before, I found that the error occurs less often.

### Verbose Logs

```
C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(132,5)
: error : Collection was modified; enumeration operation may not execute. [C:\code\team\Travel\Goyave.sln]
  System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
     at NuGet.Configuration.UnknownItem.Merge(UnknownItem item)
     at NuGet.Configuration.VirtualSettingSection.Merge(SettingSection other)
     at NuGet.Configuration.NuGetConfiguration.MergeSectionsInto(Dictionary`2 sectionsContainer)
     at NuGet.Configuration.Settings..ctor(IList`1 settingsFiles)
     at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSet
  tingFiles, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, Sett
  ingsLoadingContext settingsLoadingContext)
     at NuGet.Configuration.Settings.LoadSettingsGivenSettingsFiles(List`1 settings)
     at NuGet.Configuration.Settings.LoadImmutableSettingsGivenConfigPaths(IList`1 configFilePaths, SettingsLoadingCont
  ext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.Create(String projectNameToRestore, ExternalProjectReference
  project, HashSet`1 projectReferenceClosure, RestoreArgs restoreArgs, DependencyGraphSpec projectDgSpec, SettingsLoadi
  ngContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.<>c__DisplayClass6_0.<GetRequestsFromItems>b__2(String projec
  tNameToRestore)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
     at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
     at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```

**Comment by jeffkl** [comment] 2023-02-01 17:08
@tbolon would you be able to attach a NuGet.config that causes this behavior?  I'm unable to reproduce it on my own and am very interested in figuring out what is going on.

**Comment by tbolon** [comment] 2023-02-02 08:46
Here is my `%appdata%\NuGet\NuGet.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
    <add key="Libraries" value="https://tfs.mycompany.lan/DefaultCollection/_packaging/Libraries/nuget/v3/index.json" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```

And my project `NuGet.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <remove key="nuget.org" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <remove key="Libraries" />
    <add key="Libraries" value="https://tfs.mycompany.lan/DefaultCollection/_packaging/Libraries/nuget/v3/index.json" />
    <remove key="DevExpress" />
    <add key="DevExpress" value="https://nuget.devexpress.com/xxx/api" />
  </packageSources>
</configuration>
```

And here is a log from a repro from today:

```
C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(132,5): error : Collection was modified; enumeration operation may n
ot execute. [C:\code\team\xxx\MyApp.sln]
C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(132,5): error :   Collection was modified; enumeration operation may
 not execute. [C:\code\team\xxx\MyApp.sln]
C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(132,5): error :   Collection was modified; enumeration operation may
 not execute. [C:\code\team\xxx\MyApp.sln]
C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(132,5): error :   Collection was modified; enumeration operation may
 not execute. [C:\code\team\xxx\MyApp.sln]
  System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
     at NuGet.Configuration.UnknownItem.Merge(UnknownItem item)
     at NuGet.Configuration.VirtualSettingSection.Merge(SettingSection other)
     at NuGet.Configuration.NuGetConfiguration.MergeSectionsInto(Dictionary`2 sectionsContainer)
     at NuGet.Configuration.Settings..ctor(IList`1 settingsFiles)
     at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean l
  oadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Configuration.Settings.LoadSettingsGivenSettingsFiles(List`1 settings)
     at NuGet.Configuration.Settings.LoadImmutableSettingsGivenConfigPaths(IList`1 configFilePaths, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.Create(String projectNameToRestore, ExternalProjectReference project, HashSet`1 projectReferenceClosure, RestoreArgs restor
  eArgs, DependencyGraphSpec projectDgSpec, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.<>c__DisplayClass6_0.<GetRequestsFromItems>b__2(String projectNameToRestore)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
     at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
     at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 body
  WithLocal, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWith
  StateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.GetRequestsFromItems(RestoreArgs restoreContext, DependencyGraphSpec dgFile)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.CreateRequests(RestoreArgs restoreContext)
     at NuGet.Commands.RestoreRunner.<CreatePreLoadedRequests>d__11.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NuGet.Commands.RestoreRunner.<GetRequests>d__4.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NuGet.Commands.RestoreRunner.<RunAsync>d__0.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NuGet.Build.Tasks.BuildTasksUtility.<RestoreAsync>d__12.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at NuGet.Build.Tasks.RestoreTask.<ExecuteAsync>d__43.MoveNext()
  ---> (Inner Exception #0) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
     at NuGet.Configuration.UnknownItem.Merge(UnknownItem item)
     at NuGet.Configuration.VirtualSettingSection.Merge(SettingSection other)
     at NuGet.Configuration.NuGetConfiguration.MergeSectionsInto(Dictionary`2 sectionsContainer)
     at NuGet.Configuration.Settings..ctor(IList`1 settingsFiles)
     at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean l
  oadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Configuration.Settings.LoadSettingsGivenSettingsFiles(List`1 settings)
     at NuGet.Configuration.Settings.LoadImmutableSettingsGivenConfigPaths(IList`1 configFilePaths, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.Create(String projectNameToRestore, ExternalProjectReference project, HashSet`1 projectReferenceClosure, RestoreArgs restor
  eArgs, DependencyGraphSpec projectDgSpec, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.<>c__DisplayClass6_0.<GetRequestsFromItems>b__2(String projectNameToRestore)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
     at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
     at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

  ---> (Inner Exception #1) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
     at NuGet.Configuration.UnknownItem.Merge(UnknownItem item)
     at NuGet.Configuration.VirtualSettingSection.Merge(SettingSection other)
     at NuGet.Configuration.NuGetConfiguration.MergeSectionsInto(Dictionary`2 sectionsContainer)
     at NuGet.Configuration.Settings..ctor(IList`1 settingsFiles)
     at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean l
  oadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Configuration.Settings.LoadSettingsGivenSettingsFiles(List`1 settings)
     at NuGet.Configuration.Settings.LoadImmutableSettingsGivenConfigPaths(IList`1 configFilePaths, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.Create(String projectNameToRestore, ExternalProjectReference project, HashSet`1 projectReferenceClosure, RestoreArgs restor
  eArgs, DependencyGraphSpec projectDgSpec, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.<>c__DisplayClass6_0.<GetRequestsFromItems>b__2(String projectNameToRestore)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
     at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
     at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

  ---> (Inner Exception #2) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
     at NuGet.Configuration.UnknownItem.Merge(UnknownItem item)
     at NuGet.Configuration.VirtualSettingSection.Merge(SettingSection other)
     at NuGet.Configuration.NuGetConfiguration.MergeSectionsInto(Dictionary`2 sectionsContainer)
     at NuGet.Configuration.Settings..ctor(IList`1 settingsFiles)
     at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean l
  oadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Configuration.Settings.LoadSettingsGivenSettingsFiles(List`1 settings)
     at NuGet.Configuration.Settings.LoadImmutableSettingsGivenConfigPaths(IList`1 configFilePaths, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.Create(String projectNameToRestore, ExternalProjectReference project, HashSet`1 projectReferenceClosure, RestoreArgs restor
  eArgs, DependencyGraphSpec projectDgSpec, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.<>c__DisplayClass6_0.<GetRequestsFromItems>b__2(String projectNameToRestore)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
     at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
     at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

  ---> (Inner Exception #3) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
     at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
     at NuGet.Configuration.UnknownItem.Merge(UnknownItem item)
     at NuGet.Configuration.VirtualSettingSection.Merge(SettingSection other)
     at NuGet.Configuration.NuGetConfiguration.MergeSectionsInto(Dictionary`2 sectionsContainer)
     at NuGet.Configuration.Settings..ctor(IList`1 settingsFiles)
     at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean l
  oadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Configuration.Settings.LoadSettingsGivenSettingsFiles(List`1 settings)
     at NuGet.Configuration.Settings.LoadImmutableSettingsGivenConfigPaths(IList`1 configFilePaths, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.Create(String projectNameToRestore, ExternalProjectReference project, HashSet`1 projectReferenceClosure, RestoreArgs restor
  eArgs, DependencyGraphSpec projectDgSpec, SettingsLoadingContext settingsLoadingContext)
     at NuGet.Commands.DependencyGraphSpecRequestProvider.<>c__DisplayClass6_0.<GetRequestsFromItems>b__2(String projectNameToRestore)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
     at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
     at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

Done executing task "RestoreTask" -- FAILED.
```

By reading the source and my config, perhaps it's something related to the fact that we remove sources before adding them?

**Comment by jeffkl** [comment] 2023-02-03 17:33
Thanks @tbolon, are you sure there isn't more in the configs?  Near the top of the stack shows
```
at NuGet.Configuration.UnknownItem.Merge(UnknownItem item)
```

This leads me to believe that some other elements are being merged from the configs outside of the standard ones I see in your supplied configs.  When I use those configs, the `NuGet.Configuration.UnknownItem.Merge()` method isn't called.

**Comment by tbolon** [comment] 2023-02-03 18:38
I will check on Monday but I doubt, I was able to reproduce the problem on multiple machine, even a recent one. I will check the folder hierarchy in case.

It seems the problem also disappeared as soon as I removed the add/remove for the nuget.org key.

**Comment by tbolon** [comment] 2023-02-06 14:27
After having looking in the source code, it seems there is no "RemoveItem" known [element](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.Configuration/Settings/Items).

So there is no `<remove>` element supported, and the `<add>` element simply overrides any previously declared element, as stated [in the docs](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied).

From my .NET background, I was supposing the add/remove/clear elements where acting the same as on app.config files (meaning you can't add a new item if there is another item with the same key), but I was wrong.

So, I will simply remove all the `<remove />` elements, supposing that it will fix my problem.

This scenario could be better supported I suppose by emitting a warning about an unsupported xml element, or by preventing an unknown element to break the paralellism of the restore operation.

**Comment by jeffkl** [comment] 2023-02-06 20:20
Sorry I wasn't able to figure that out, I assumed `<remove />` was supported.  Well at least it's figured out.

**Closed as completed by jeffkl** 2023-02-06 20:20 UTC
Labels: Type:Bug, Resolution:NotABug
