### ISSUE TITLE
Install-Package should filter unlisted packages when no version is given

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#5069] opened 2017-04-19 21:08 UTC
@jsakamoto commented on [Wed Apr 19 2017](https://github.com/NuGet/NuGetGallery/issues/3802)

### What you were trying to do.

Update the NuGet package "Selenium.WebDriver.MicrosoftWebDriver" from version v.10.0.14393.1 to latest version.

### What you expected to happen.

The version of the NuGet package "Selenium.WebDriver.MicrosoftWebDriver" update to v.10.0.15063.0.

### What actually happened.

The version of the NuGet package "Selenium.WebDriver.MicrosoftWebDriver" updated to v.10.1.14393.0.

That version is unlisted package version.  
See also: https://www.nuget.org/packages/Selenium.WebDriver.MicrosoftWebDriver/10.1.14393

### Steps to reproduce the problem.

1. Create or open any .NET project with Visual Studio 2017. 
2. Execute "Install-Package Selenium.WebDriver.MicrosoftWebDriver" command at Package Manager Console. 
3. After it, the correct latest version "10.0.15063" was installed. (This is correct behavior) 
4. Next step, execute "Update-Package Selenium.WebDriver.MicrosoftWebDriver" command. 
5. Then, the command update the package to UNLISTED version "10.1.14393" !

### Appendix Information

I guess, this problem happens due to the JSON response from api.nuget.org.

The JSON reponse contains "upper" proprty, but it looks like include unlisted package versions.

![image](https://cloud.githubusercontent.com/assets/95908/25183534/d08fa9a4-2552-11e7-8f4e-204207486981.png)

Is it by design and it should not change? or should fix it?

---

@skofman1 commented on [Wed Apr 19 2017](https://github.com/NuGet/NuGetGallery/issues/3802#issuecomment-295411222)

@joelverhagen , @emgarten , is this a client or server issue?

---

@emgarten commented on [Wed Apr 19 2017](https://github.com/NuGet/NuGetGallery/issues/3802#issuecomment-295439707)

Looks like a client issue if the unlisted package is being installed. The upper and lower bounds are correct.

---

@joelverhagen commented on [Wed Apr 19 2017](https://github.com/NuGet/NuGetGallery/issues/3802#issuecomment-295440372)

I confirmed this behavior in NuGet 4.2.0.2451 with a packages.config project. A PackageReference project does not reproduce the problem. The issue occurs for both V2 and V3 NuGet.org source URL.

As @emgarten, this seems to be a client issue.

**Comment by wli3** [comment] 2017-08-23 18:47
Hi, 
dotnet CLI got an opposite issue 

https://github.com/dotnet/cli/issues/7492

Which should be the designed behavior? Latest unlisted of listed?

**Comment by richardszalay** [comment] 2017-08-24 02:03
FYI, the CLI issue is the same issue. Perhaps you meant "equivalent", instead of "opposite"?

**Comment by richardszalay** [comment] 2017-08-24 02:58
I'd say this is definitely a bug, and not designed behavior. The [documentation for unlisting a package](https://www.visualstudio.com/en-us/docs/package/nuget/unlist-delete) even says:

> Unlisting a version can help you prevent new usage of it without breaking dependent projects and builds

And having it install by default does quite the opposite of preventing new usage.

**Comment by tokyo0709** [comment] 2017-10-27 15:53
Experiencing the same issue, https://stackoverflow.com/questions/46977808/updating-nuget-package-yields-unlisted-version

**Comment by karann-msft** [comment] 2018-02-02 20:04
cc: @anangaur

**Comment by jainaashish** [comment] 2018-04-27 04:44
dupe of https://github.com/NuGet/Home/issues/4553

**Closed as completed by jainaashish** 2018-04-27 04:44 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Bug, Functionality:Update, RegressionFromPreviousRTM

**Comment by matkoch** [comment] 2019-10-18 16:49
[5.3.0](https://www.nuget.org/packages/NuGet.CommandLine/) is still downloading unlisted versions?

@jainaashish please reopen

**Comment by matkoch** [comment] 2019-10-18 16:52
@emgarten ^^^^

**Comment by nkolev92** [comment] 2019-10-18 17:35
@matkoch If you think there's a regression please open a new issue since this is not actively monitored.

**Comment by matkoch** [comment] 2019-10-19 00:04
@nkolev92 there already is another one at https://github.com/NuGet/Home/issues/7466

I just can't understand how this is not addressed for such a long time? Sorry, but I'm really disappointed.

**Comment by mwwhited** [comment] 2022-04-15 17:03
5 years later and this is still and issue.  I should really sell my MS stock.

**Comment by nkolev92** [comment] 2022-04-15 18:14
@mwwhited 
This issue is closed. The linked issue for PMC, https://github.com/NuGet/Home/issues/4553, was fixed in 2018 https://github.com/NuGet/NuGet.Client/pull/2270.
