### ISSUE TITLE
Bug in "packageSourceMapping" ignores pattern

### ISSUE THREAD

**Issue by Aldebaran91** [NuGet/Home#13983] opened 2024-12-04 09:54 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 17.12.3

### Worked before?

No

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Example:

1) Create nuget Package called "Microsoft.Data.SqlClient" and add it to your nuget feed in Azure DevOps with nuget package Version "1.0.0.0". Version must be below the current Version of "Microsoft.Data.SqlClient" on nuget.org.
2) Install package from private Azure DevOps feed in your C# project.
3) Create nuget.config with "packageSourceMapping". Like this

``` xm
<?xml version="1.0" encoding="utf-8"?>
<configuration>  
	<packageSources>
		<add key="MyFeed" value="privatedevopsaddress/mycollection/_packaging/myfeed/nuget/v3/index.json" />
		<add key="MyFeed2" value="privatedevopsaddress/mycollection/_packaging/myfeed2/nuget/v3/index.json" />
		<add key="MyFeed3" value="privatedevopsaddress/mycollection/_packaging/myfeed3/nuget/v3/index.json" />
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
	</packageSources>

  <packageSourceMapping>
		<packageSource key="MyFeed">
			<package pattern="Microsoft.Data.SqlClient" />
			<package pattern="MyFeed.*" />
		</packageSource>
		<packageSource key="MyFeed2">
			<package pattern="MyFeed2.*" />
		</packageSource>
		<packageSource key="MyFeed3">
			<package pattern="MyFeed3.*" />
		</packageSource>
		<packageSource key="nuget.org">
			<package pattern="*" />
		</packageSource>
  </packageSourceMapping>
  
</configuration>
```
and add it to your nuget packagemanager in Visual Studio.
4) Open nuget package manager in Visual Studio 2022.
5) Go to tab "Updates".
6) Change package source to "All"

What you get: It will show that there is a new update for "Microsoft.Data.SqlClient" in nuget feed "nuget.org".
What you expect: No new updates because "Microsoft.Data.SqlClient" is now mapped to the private feed "MyFeed" and not to nuget.org.

**Comment by donnie-msft** [comment] 2024-12-05 16:07
Thank you for providing feedback on package source mapping!
I believe this is a duplicate of https://github.com/NuGet/Home/issues/12783

**Closed as completed** 2024-12-05 16:11 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug, Functionality:VisualStudioUI, Area:PackageSourceMapping, Triage:Untriaged
