### ISSUE TITLE
LockFile validation fails for projects with <RuntimeIdentifiers> set in SDK 3.0.100

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#8639] opened 2019-09-27 23:06 UTC
## Details about Problem

NuGet product used: dotnet.exe

dotnet.exe --version: 3.0.100

Worked before?: Yes, with sdk version 2.2.402

## Automated Repro
1. Download [netSdk3_rid_lockFile_repro.zip](https://github.com/NuGet/Home/files/3664781/netSdk3_rid_lockFile_repro.zip)
2. Extract
3. Run repro.bat

## Manual repro steps

1. Create a .csproj resembling this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
```
2. `dotnet restore --use-lock-file`
    - This will succeed and write a lock file
3. `dotnet restore --use-lock-file --locked-mode`
    - This will fail with `error NU1004: The packages lock file is inconsistent with the project dependencies` despite the fact  that the file was just generated and nothing has changed.

Tagging @nkolev92 and @rrelyea as FYI.

**Comment by anangaur** [comment] 2019-09-27 23:27
@nkolev92, Is this because of the framework libraries now getting folded into the SDK with 3.0?

**Comment by bergbria** [comment] 2019-09-27 23:40
@anangaur / @nkolev92 this is related to #7724 / #8442 and possibly has the same root cause. I don't know enough about the implementation to say.

Either way, it's frustrating that this blocks using even newer SDK versions, not just .Net Core 3.

**Comment by nkolev92** [comment] 2019-10-01 00:12
I think this is a duplicate of https://github.com/NuGet/Home/issues/8645. 

The above example will work if the runtime identifiers are sorted. 

For example it doesn't repro for me if I do the following: 

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifiers>osx-x64;win-x64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
```

Can you please confirm @bergbria

**Comment by nkolev92** [comment] 2019-10-01 00:13
I guess the other way around since this issue is older.

**Comment by nkolev92** [comment] 2019-10-16 22:39
Fixed by https://github.com/NuGet/NuGet.Client/pull/3075

**Closed as completed by nkolev92** 2019-10-16 22:39 UTC
Labels: Type:Bug, Functionality:Restore, Product:dotnet.exe, Area:RestoreRepeatableBuild

**Comment by bergbria** [comment] 2019-10-20 07:18
@nkolev92 - sorry for not responding. Sorting the RIDs did resolve the issue in my repros, so the fix should resolve it. Thanks!
