### ISSUE TITLE
Running executable from a NuGet package with PackageReference management format

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#5975] opened 2017-10-02 09:53 UTC
I have a code base and two project files that target two versions of the .NET framework. Since I have them stored in the same folder I cannot rely on a `Packages.config` file since it will always incorporate one framework version and not the other. Thus I moved to `PackageReference` which worked great so far.

Unfortunately I just installed `Mono.TextTemplating` and wanted to execute the provided `TextTransform.exe` as a pre-build event on all of my `*.tt` files however I cannot reference it properly since it is stored under `%userprofile%\.nuget\packages\mono.texttemplating\1.3.1\`. The moment I update the package and forget about it, it will break since the new version will be stored under a different folder. Similiar to any changes of the local package storage.

How am I supposed to include executables from NuGet packages into my build steps now?

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 4.3

VS version (if appropriate): Enterprise 2017 (15.3.5)

OS version (i.e. win10 v1607 (14393.321)): Windows 10 v1703 (15063.608)

**Comment by rrelyea** [comment] 2017-10-02 20:17
Great scenario. @mishra14 is looking into similar issues with bootstrapping using PackageReference.

**Comment by ghost** [comment] 2017-10-02 20:25
@rrelyea Slightly more information: I just got told, it is possible to use multiple `Project.config` files when naming them `Package.Project1.config` and `Package.Project2.config` but with that approach it is still an issue referencing tools properly. It is definitely easier pointing to something along the lines of `$(SolutionDir)\packages\...` however it is still unpleasant that one has to hard-code package names and especially versions in build events and other properties.

Surprisingly the `tools` folders of all packages are automatically added to the `PATH` variable for the Package Manager Console and I was able to call the executable from it but I am not able to reference it in the build events.

**Comment by rrelyea** [comment] 2017-10-02 21:44
Great info. Thanks. I wasn't aware of that feature. 
Clearly we should improve the build side of this.

Today, some tools set a msbuild property in their .props file, that consumers of that tool could use.

You could imagine that we create msbuild props for every tools folder that you restore. $(PackageToolsDir_My_Package_Name) or the like...

**Comment by christianrondeau** [comment] 2018-05-16 18:45
We actually have the same requirement, and were greatly surprised to see there's no easy to find solution (and we searched pretty hard). Two scenarios:

1. Running `nunit3.console.exe` requires either installing `nunit`, copying it in the git repo directly, or hardcoding the "expected" NuGet path from the user folder. All three prevents two projects referencing different versions of `nunit` which may not be compatible with the same `nunit3.console.exe` runner. (NOTE: Using `dotnet test` would be an alternative in that specific scenario)
2. Running `FluentMigrator`'s `Migrate.exe`. same thing

A simple solution would be to have `tools` available in `PackageReference/IncludeAssets`. I guess it would be in `ExcludeAssets` by default, but we could then have the folder copied to the output folder and move on.

Another solution could be to specify "additional files", which would be a simple mapping of files from the package and where we want them (e.g. globbing pattern). Dirtier, but I could then select the files I want in `/tools` rather than always copy everything.

Finally, like @rrelyea said if we can get a variable to find the resolved package folder in a post-build event, we'd be good to go. Example of what that could look like:

```
<PackageReference Include="MyPackage" Version="1.0.0" ExportPathVariable="MyPackageFolder" />
<!-- ... -->
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="copy $(MyPackageFolder)\tools\hello.exe $(OutDir)\" />
</Target>
```

**Comment by rrelyea** [comment] 2018-06-14 21:50
Resolving dupe of this issue: https://github.com/NuGet/Home/issues/6949 which is in flight.

**Closed as completed by rrelyea** 2018-06-14 21:50 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Bug, Style:PackageReference
