### ISSUE TITLE
DotNet Tools - Embedded nuget in dotnet CLI dotnet does not resolve the good version 

### ISSUE THREAD

**Issue by tebeco** [NuGet/Home#6994] opened 2018-06-03 17:38 UTC
Copied from https://github.com/dotnet/cli/issues/9409
since this is probably due to nuget and not dotnet cli

## Steps to reproduce
fake-cli on nuget.org :
![image](https://user-images.githubusercontent.com/2266487/40889289-5ddcd8aa-6764-11e8-8ad1-3233977e9653.png)

What i tried :
```
>  dotnet tool install fake-cli ^
     --tool-path ./foobar ^
     --version 5.0.0-rc*
```

## Expected  behavior
it should install 5.0.0-rc18....

## Actual behavior
it installs `rc15`
```
warning NU1603: restore depends on fake-cli (>= 5.0.0-rc) but fake-cli 5.0.0-rc was not found. An approximate best match of fake-cli 5.0.0-rc015.196 was resolved.
You can invoke the tool using the following command: fake
Tool 'fake-cli' (version '5.0.0-rc015.196') was successfully installed.
```

Even tried 
`dotnet nuget locals -c all`

Or addin a nuget.config :
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="DependencyVersion" value="Highest"/>
    </config>
</configuration>
```

still install `rc15`

not funny part :
```
>nuget install fake-cli -Prerelease
Feeds used:
  https://api.nuget.org/v3/index.json
  C:\Users\ahert\.dotnet\NuGetFallbackFolder
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installing package 'fake-cli' to 'C:\Workspace\GitHub\TeBeCo\fake-netcore-sample\Nuget\BuildPackages'.
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/fake-cli/index.json


Attempting to gather dependency information for package 'fake-cli.5.0.0-rc018.244' with respect to project 'C:\Workspace\GitHub\TeBeCo\fake-netcore-sample\Nuget\BuildPackages', targeting 'Any,Version=v0.0'
Gathering dependency information took 31.57 ms
Attempting to resolve dependencies for package 'fake-cli.5.0.0-rc018.244' with DependencyBehavior 'Highest'
Resolving dependency information took 0 ms
Resolving actions to install package 'fake-cli.5.0.0-rc018.244'
Resolved actions to install package 'fake-cli.5.0.0-rc018.244'
Retrieving package 'fake-cli 5.0.0-rc018.244' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/fake-cli/5.0.0-rc018.244/fake-cli.5.0.0-rc018.244.nupkg
  OK https://api.nuget.org/v3-flatcontainer/fake-cli/5.0.0-rc018.244/fake-cli.5.0.0-rc018.244.nupkg 800ms
Installing fake-cli 5.0.0-rc018.244.
```

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17677
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

also check
https://github.com/dotnet/cli/issues/9407
https://github.com/dotnet/cli/issues/9408

**Comment by livarcocc** [comment] 2018-06-04 16:56
The CLI follows NuGet's version resolving mechanisms and we do not intend to special case version semantics just for tools. Note that if this was not a tool but a package, the same resolution logic would apply. As such, I am closed the CLI issue and we can continue discussing it here, in the NuGet one.

**Comment by tebeco** [comment] 2018-06-04 17:27
@livarocc the `nuget.config` ask for the latest right ?

if `dotnet` follows `nuget`version resolving
why does
`nuget install fake-cli` install `rc18`
while
`dotnet install tool fake-cli` install `rc015`

**Comment by livarcocc** [comment] 2018-06-04 17:30
It may be a restore difference vs nuget install. `dotnet install` behind the scenes does a `dotnet restore` and not `nuget install`

**Comment by tebeco** [comment] 2018-06-04 17:30
also i do not see any “—allow-prerelease” in the `dotnet tool install` to match the nuget version resolution

**Comment by livarcocc** [comment] 2018-06-04 17:35
See https://github.com/dotnet/cli/issues/8485.

**Comment by tebeco** [comment] 2018-06-04 17:45
> It may be a restore difference vs nuget install. dotnet install behind the scenes does a dotnet restore and not nuget install

just to be sure ... it means `dotnet restore` ignore `nuget.config` ?

**Comment by nkolev92** [comment] 2018-06-04 18:37
I did a quick sanity test on this and it seems like NuGet would resolve the correct thing if I pass it `5.0.0-rc*`

Could be the case that the correct string is not set by the CLI? 
Can I somehow get the proj generated during the tool restore?

//cc @wli3
![fake-cli](https://user-images.githubusercontent.com/2878341/40934902-298a2260-67eb-11e8-94dd-5ef94ba6303e.png)

**Comment by wli3** [comment] 2018-06-04 18:53
This is the temp project generated

```xml
λ  cat  C:\Users\wul\AppData\Local\Temp\nrvzvdfj.k4v\restore.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RestorePackagesPath>C:\Users\wul\foobar\.store\.stage\kwekki4v.htl</RestorePackagesPath>
    <RestoreProjectStyle>DotnetToolReference</RestoreProjectStyle>
    <RestoreRootConfigDirectory>C:\Users\wul</RestoreRootConfigDirectory>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <RestoreFallbackFolders>clear</RestoreFallbackFolders>
    <RestoreAdditionalProjectSources>C:\Program Files\dotnet\sdk\NuGetFallbackFolder</RestoreAdditionalProjectSources>
    <RestoreAdditionalProjectFallbackFolders></RestoreAdditionalProjectFallbackFolders>
    <RestoreAdditionalProjectFallbackFoldersExcludes></RestoreAdditionalProjectFallbackFoldersExcludes>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="fake-cli" Version="5.0.0-rc" />
  </ItemGroup>
</Project>
```

**Comment by wli3** [comment] 2018-06-04 18:57
But cli parse the version with NuGet.Versioning https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-tool/install/ToolInstallCommand.cs#L97

will the * be preserved?

**Comment by wli3** [comment] 2018-06-04 19:04
The result is `5.0.0-rc`.

```c#
using System;
using NuGet.Versioning;


namespace consolenugetversion
{
    class Program
    {
        static void Main(string[] args)
        {
            var _packageVersion = "5.0.0-rc*";
            VersionRange versionRange = null;
            if (!string.IsNullOrEmpty(_packageVersion) && !VersionRange.TryParse(_packageVersion, out versionRange)) //same code from CLI
            {
                throw new Exception();
            }

            Console.WriteLine(versionRange.ToString("S", new VersionRangeFormatter())); // same code to write to temp project
        }
    }
}

```

**Comment by nkolev92** [comment] 2018-06-04 19:06
@wli3 

Can you please try using `versionRange.OriginalString` ?

Not sure what the VersionRangeFormatter would do off the top of my head. 
I will take a look later.

**Comment by wli3** [comment] 2018-06-04 19:12
@peterhuene may have more context

**Comment by wli3** [comment] 2018-06-04 19:36
versionRange.OriginalString is almost like passing a string. And VersionRangeFormatter should do the same thing. VersionRangeFormatter is not the right api to produce a normalized version range?

**Comment by tebeco** [comment] 2018-06-04 19:43
stupid question but should it also have worked with `5.*` ? or is it the same issue as the `prerelease` flag ?

**Comment by nkolev92** [comment] 2018-06-04 19:48
@tebeco 

The problem here is not how NuGet is resolving it. 
The problem is some information is being swallowed when the CLI calls NuGet to get the package. 


@wli3 

Why do you need to normalize the version range? 

NuGet will do that for you, it will use the exact same APIs. 
So if your code can parse the version, so will NuGet later on.

**Comment by peterhuene** [comment] 2018-06-04 20:08
`OriginalString` should work for our purposes.  This appears to be a regression caused by https://github.com/dotnet/cli/commit/5ebbd618ec27e5c6da9142b8c1166b2755cba898.

**Comment by livarcocc** [comment] 2018-06-04 20:15
Let's close this issue then and re-activate the original CLI issue and use it to track fixing it on our side.

Thanks, everyone.

**Comment by wli3** [comment] 2018-06-04 20:15
I prefer a normalize string to original since we need to pass it by temp project, and we don't know what original will do when passed by xml or command line. If there is ">" in the original version, it will break msbuild xml format. Or there is a extra space, or ":", if we pass it by command line. A normalize the format should be the most safe way. And since we need to parse it once anyway.

According to the comment on "S". It should work as well. Although "N" might be better.
https://github.com/NuGetArchive/NuGet.Versioning/blob/0f25e04c3a33d2dff11cbb97e1c0827cf5bf6da6/src/NuGet.Versioning/VersionRangeFormatter.cs#L148

This is another argument for a C# api for restore. We could always the whole set of problem is we just pass the strong type Nuget.Versioning.

**Comment by peterhuene** [comment] 2018-06-04 20:17
I assume our validation check would prevent any illegal characters not supported in a NuGet version number, no?  If there are potential problems with it, it should be our responsibility to properly escape it when writing out the temp project, imo.

**Comment by nkolev92** [comment] 2018-06-04 21:23
Closing this issue in favor of the CLI one. 

I'll investigate the "S" comment and see if we need to take an action there.

**Closed as completed by nkolev92** 2018-06-04 21:23 UTC
Labels: Resolution:External, Triage:Investigate, Functionality:Restore

**Comment by wli3** [comment] 2018-06-11 19:39
@nkolev92 Could you give us any advice? I still prefer a normalized version to go cross the board of systems. What is the conclusion of "S" consider 5.0.0-rc vs 5.0.0-rc* differently. What is the recommended "lossless" representation of nuget version range in plain text?

**Comment by nkolev92** [comment] 2018-06-11 19:43
@wli3 

Did you try using "N"? 

You can always just verbatim pass the version to NuGet itself.

**Comment by wli3** [comment] 2018-06-11 19:51
@nkolev92 the concern for just pass the original is CLI has no control of what goes in the original. So CLI don't know if it can be safely pass around in XML and commandline (will some space in it be considered valid version? Will ">" in it be considered valid version? as in `>3.1`. If we escape, can nuget unescape it properly?). If we could have a contract that a valid plain text(will not throw on `nugetversion.Parse`), can be and will be safely passed via xml and command line in future version. That is also fine.

**Comment by nkolev92** [comment] 2018-06-11 19:53
@wli3 
Valid, going back to my original question, doesn't "N" fix it?

**Comment by wli3** [comment] 2018-06-11 19:55
Should be good. From my basic tests. However, I do want to make sure format "N" has the intention of being a loss less representation compared with "S"

**Comment by tebeco** [comment] 2018-06-11 21:02
hey there, i have a stupid question because i am curious but what is this “S” or “N” ?

also `Fake` did releases a v5.0.0 so the behavior will probably change

**Comment by nkolev92** [comment] 2018-06-11 21:30
@tebeco 
It's implementation detail for the tool install command. 

The CLI parses a version from the commandline and passed it to NuGet, but called the library in way that lost some information from the version.
