### ISSUE TITLE
Windows Universal Library - Fielder

### ISSUE THREAD

**Issue by Nicothekrug** [NuGet/Home#1161] opened 2015-08-12 07:40 UTC
Hi,

I used PropertyChanged.Fody in multiple projects but with VS2150/Win10 one i'm having trouble.
I'm able to install Fody and PropertyChanged.Fody with no problem in a Windows Universal Library (win 10).
But Fielder.Fody is also needed, and i cant figure out a way to install it. 
Via nuget PropertyChanged.Fody install perfectly :

PM> install-package PropertyChanged.Fody
Restoring packages for 'XXX'.
Restoring packages for XXX...
Restoring packages for UAP,Version=v10.0...
Restoring packages for UAP,Version=v10.0 (win10-arm)...
Restoring packages for UAP,Version=v10.0 (win10-arm-aot)...
Restoring packages for UAP,Version=v10.0 (win10-x86)...
Restoring packages for UAP,Version=v10.0 (win10-x86-aot)...
Restoring packages for UAP,Version=v10.0 (win10-x64)...
Restoring packages for UAP,Version=v10.0 (win10-x64-aot)...
All packages are compatible with UAP,Version=v10.0.
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore completed successfully for 'XXX'.
Generating MSBuild file XXX.nuget.targets.
Successfully installed 'PropertyChanged.Fody 1.50.3' to XXX

But i don't know what happens with Fielder :

PM> install-package Fielder.Fody
Restoring packages for 'XXX'.
Restoring packages for XXX\project.json...
Restoring packages for UAP,Version=v10.0...
install-package : Unable to resolve Fielder.Fody (≥ 1.0.10) for UAP,Version=v10.0.
At line:1 char:1

install-package Fielder.Fody
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Install-Package], Exception
FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
Package restore failed for 'XXX'.
install-package : Package restore failed. Rolling back package changes for 'XXX'.
At line:1 char:1

install-package Fielder.Fody
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Install-Package], Exception
FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Is this a known behaviour ? Is there a workaround ? Is this a bug ?

**Comment by emgarten** [comment] 2015-08-12 08:35
This package version is missing from the NuGet v3 feed.

Try downloading the nupkg and putting it in a local folder and adding the folder as a package source.

**Comment by SimonCropp** [comment] 2015-08-12 08:36
wierd since it was fixed previously https://github.com/NuGet/Home/issues/1145

**Comment by emgarten** [comment] 2015-08-12 08:42
1145 deals with the versions returned in search. It may not have been fixed in all parts of the feed.

**Comment by Nicothekrug** [comment] 2015-08-12 09:30
The package version can be seen by search (#1145), but no way to install it ;)

The wierd part is that Fody&PropertyChanged install with no problem at all...

**Comment by bhuvak** [comment] 2015-08-12 23:56
@Nicothekrug  i am looking in to it. Will update you ASAP.

**Comment by yishaigalatzer** [comment] 2015-08-14 01:33
@bhuvak update?

**Comment by johnataylor** [comment] 2015-08-15 01:03
@SimonCropp : one of the reasons packages were being dropped is because the nuspec inside the nupkg was not named {id}.nuspec. We will make the processing is little more forgiving on the server and deploy that next week. We are also currently running a scan from the beginning and we will also be repairing the data - so no action is required on your part. Thanks.

**Comment by yishaigalatzer** [comment] 2015-08-15 01:15
@SimonCropp you should really make the {id}.nuspec match the package id. And if you deployed it right now, it will get picked up immediately.

If you are ok with waiting, this will probably get fixed automatically early next week like @johnataylor says. Though eventually we might start stopping packages like this from being accepted on nuget.org

**Comment by SimonCropp** [comment] 2015-08-15 03:05
try v1.0.11

**Comment by yishaigalatzer** [comment] 2015-08-15 16:49
@johnataylor I see that he uploaded a proper package, that has Fielder.Fody.nuspec at the root, but it still not showing up in the index at - `https://az320820.vo.msecnd.net/v3-flatcontainer/fielder.fody/index.json`

This is all I see (looks like 14 hours after @SimonCropp published his package)

```JSON
{
  "versions": [
    "0.1.0",
    "0.3.0",
    "0.4.0",
    "0.5.0",
    "0.7.0",
    "0.9.0",
    "0.10.0",
    "0.11.0",
    "0.12.0",
    "0.13.0",
    "0.14.0",
    "0.14.1",
    "0.14.1.1",
    "1.0.0"    
  ]
}
```

The package is available from the V2 source `https://www.nuget.org/api/v2`

**Comment by yishaigalatzer** [comment] 2015-08-15 23:21
We are running a batch process to update all the registrations under the flatcontainer URL. We expect it to be done Sunday night or early Monday morning

**Comment by SimonCropp** [comment] 2015-08-16 00:09
ok for now i am moving back to the v2 feed in my nuget config

```
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
```

**Comment by pedrolamas** [comment] 2015-08-16 13:22
I'm seeting the very same issue right now on [Cimbalino.Toolkit](https://www.nuget.org/packages/Cimbalino.Toolkit) package: using Fiddler, I can see Visual Studio requesting https://az320820.vo.msecnd.net/v3-flatcontainer/cimbalino.toolkit/index.json, and this reports version 2.0.0-beta1 as the latest which is wrong, as beta3 is already published and available!

**Comment by pedrolamas** [comment] 2015-08-17 21:35
@yishaigalatzer can you confirm if the update process has completed? I ask this as I'm still seeing the same issues with my NuGet package as I stated previously...

**Comment by emgarten** [comment] 2015-08-17 21:49
@PedroLamas I see all versions listed in https://az320820.vo.msecnd.net/v3-flatcontainer/cimbalino.toolkit/index.json

**Comment by pedrolamas** [comment] 2015-08-17 21:50
@emgarten I see them too, but that is incomplete: it's missing the two most recent betas: 2.0.0-beta2 and 2.0.0-beta3

You can see them all here: https://www.nuget.org/packages/Cimbalino.Toolkit

**Comment by emgarten** [comment] 2015-08-17 22:03
![capture](https://cloud.githubusercontent.com/assets/6381138/9317527/18eb7168-44f1-11e5-8714-36e6b07ff5d6.PNG)

**Comment by pedrolamas** [comment] 2015-08-17 22:08
This is what I see:

![image](https://cloud.githubusercontent.com/assets/85504/9317598/9e70f964-4534-11e5-9bd4-55ad58d23614.png)

I cleared my cached files, used different browsers and even a different machine... and nothing!

Remote connecting to my work machine in the office (so different IP and network) shows the same as above...

CDN issue maybe?

**Comment by johnataylor** [comment] 2015-08-17 22:12
and you tried curl..?

curl -k https://az320820.vo.msecnd.net/v3-flatcontainer/cimbalino.toolkit/index.json

Incidentally I'm seeing the same as Justin. This seems to be some caching - its just hard to see where - but its not obviously the CDN.

**Comment by pedrolamas** [comment] 2015-08-17 22:15
@johnataylor I don't have linux available to do curl, but I'll try to use Fiddler and see what it returns!

I did try in to use VPN connection to Seattle and some other locations across the globe, all returned the result you see above in the picture!

**Comment by pedrolamas** [comment] 2015-08-17 22:18
Complete Fiddler request and response:

```
GET https://az320820.vo.msecnd.net/v3-flatcontainer/cimbalino.toolkit/index.json HTTP/1.1
User-Agent: Fiddler
Host: az320820.vo.msecnd.net
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0


HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-MD5: hJddqtNSSZR7o6EFOSha1g==
Content-Type: application/json
Date: Mon, 17 Aug 2015 22:16:56 GMT
Etag: 0x8D298BCB3DB1392
Last-Modified: Thu, 30 Jul 2015 08:56:05 GMT
Server: ECAcc (lcy/1D6F)
Vary: Accept-Encoding
X-Cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: c9b98e8a-0001-005e-74ff-d57aa7000000
x-ms-version: 2009-09-19
Content-Length: 239

{
  "versions": [
    "1.0.0-beta1",
    "1.0.0-beta2",
    "1.0.0",
    "1.1.0",
    "1.1.1",
    "1.2.0",
    "1.2.1",
    "1.2.2",
    "1.2.3",
    "1.2.4",
    "1.2.5",
    "1.2.6",
    "1.2.7",
    "2.0.0-beta1"
  ]
}
```

As you can see above, I even tried adding a bunch of "no cache" headers just to make sure...

**Comment by johnataylor** [comment] 2015-08-17 22:47
@PedroLamas we just purged both our CDN's and disabled a rewrite rule we had running in one of them. We have doubled checked and it seems we have the right Cache-Control header (we set it to no-store for the versions list)

So hopefully this fixes the problem? Please let us know. One thing we are still trying to understand is a discrepancy we had reported between http and https. 

Incidentally when I suggested debugging with curl I was using curl on windows. If you the more recent versions you should be able to hit https endpoints by specifying the -k flag and then see headers with the -i flag.

**Comment by pedrolamas** [comment] 2015-08-17 22:50
Confirmed, that did in fact fixed the problem, so thank you very much for that! :)

Guess the real question now is what was missing before, as apparently you were seeing different results compared to what I was seeing!

**Comment by pedrolamas** [comment] 2015-08-17 23:23
@johnataylor Scratch that, unfortunately problem still persists if I disconnect from VPN...

Without any VPN connected all I get is the wrong list _without_ the two new versions; if I connect my VPN to Prague, Czech Republic, I get the correct response back... so far this has been the only location I could find that returned the right response, all other attempts gave me the wrong response back!

**Comment by johnataylor** [comment] 2015-08-17 23:45
@PedroLamas thanks for experimenting, that is very odd indeed. We are following up with our CDN providers (we are actually in the process of moving from vendor to another.)

**Comment by pedrolamas** [comment] 2015-08-17 23:55
No problem, I'm an interested part here so I'll be glad to help anyway I can to get this sorted!

It's almost 01:00 in the UK so I'll resume testing tomorrow morning... :)

-----Original Message-----

**Comment by maartenba** [comment] 2015-08-18 08:02
CDN switch has been done (DNS still propagating).

**Comment by yishaigalatzer** [comment] 2015-08-18 22:01
@PedroLamas waiting on your feedback to see if we can close this bug.

**Comment by pedrolamas** [comment] 2015-08-18 22:12
@yishaigalatzer no such luck yet unfortunately: this was just taken (no VPN connection active, BT Fiber UK network)...

![image](https://cloud.githubusercontent.com/assets/85504/9344165/85252348-45fe-11e5-9fae-e45186ae7146.png)

**Comment by pedrolamas** [comment] 2015-08-18 22:19
@yishaigalatzer same test with different VPN connections active:

Czech Republic (ip: 87.236.195.22)

![image](https://cloud.githubusercontent.com/assets/85504/9344242/1201e2d8-45ff-11e5-8967-3778c303388d.png)

Germany (ip: 195.122.150.131)

![image](https://cloud.githubusercontent.com/assets/85504/9344260/34b5d654-45ff-11e5-9363-79bdf19945c2.png)

France (ip: 178.32.219.18)

![image](https://cloud.githubusercontent.com/assets/85504/9344289/6660dab4-45ff-11e5-8974-0f5307c3813b.png)

So different locations are returning different results!

I assume that the DNS propagation might still be undergoing...

**Comment by pedrolamas** [comment] 2015-08-19 08:38
@yishaigalatzer I just made another test this morning, getting the same wrong results in both my home network and in the office.

This is a complete `tracert az320820.vo.msecnd.net` that I just did using my home connection:

```
Tracing route to cs1.wpc.v0cdn.net [68.232.34.200] over a maximum of 30 hops:

  1     *        1 ms     1 ms  BThomehub.home [192.168.1.254]
  2     3 ms     3 ms     3 ms  217.32.145.138
  3     *        3 ms     5 ms  217.32.145.206
  4     4 ms     4 ms     4 ms  213.120.176.2
  5     4 ms     5 ms     4 ms  213.120.178.65
  6     6 ms     4 ms     4 ms  217.41.168.107
  7     4 ms     4 ms     4 ms  acc1-10GigE-0-2-0-6.l-far.21cn-ipp.bt.net [109.159.249.101]
  8     5 ms     4 ms     5 ms  core3-te0-10-0-19.faraday.ukcore.bt.net [109.159.249.23]
  9     4 ms     4 ms     4 ms  peer1-xe0-0-0.faraday.ukcore.bt.net [213.121.193.161]
 10     4 ms     4 ms     4 ms  109.159.253.63
 11     4 ms     4 ms     5 ms  68.232.34.200

Trace complete.
```

**Comment by pedrolamas** [comment] 2015-08-19 12:34
@yishaigalatzer **success:** both my home and work connections are finally showing the correct results with the new versions on them!! :smiley:

**Comment by SimonCropp** [comment] 2015-08-19 12:35
Awesome work peoples

**Comment by maartenba** [comment] 2015-08-19 12:47
Not closing this one yet. This only happened because of a manual CDN purge. @johnataylor @bhuvak this needs additional investigation.

**Comment by yishaigalatzer** [comment] 2015-09-09 20:47
@bhuvak what is the status on this item?

**Comment by yishaigalatzer** [comment] 2015-10-23 01:13
We think we know what is going on with missing packages.. Closing for now, Will follow up if we find new scenarios.

**Closed by yishaigalatzer** 2015-10-23 01:13 UTC
Labels: Viewed
