### ISSUE TITLE
Specify documentation via .csproj

### ISSUE THREAD

**Issue by ffMathy** [NuGet/Home#7317] opened 2018-09-21 08:47 UTC
When using `dotnet pack`, I can use properties like `RepositoryUrl` to use as the resulting `.nuspec` file's repository URL etc.

But what property do I set to specify documentation (`<documentation target="documentation.md"/>`)? Is it even possible to specify via `.csproj` files?

If not, it should be!

**Comment by jainaashish** [comment] 2018-09-21 23:13
There is no such property in `.nuspec` file that's why there is no csproj property as well. But if you can inlcude any documentation file in your nupkg at the root or as part of content. Even readme.txt at the root of nupkg are also shown to the customers upon installing the package.

**Comment by ffMathy** [comment] 2018-09-22 10:21
Erhm, there is such a property.

https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg

**Comment by ffMathy** [comment] 2018-09-22 11:37
Can you please re-open @jainaashish?

**Comment by StingyJack** [comment] 2018-09-24 09:47
@ffMathy - thats a spec currently under review.  You can track the related work [here](https://github.com/NuGet/Home/issues/6873)

**Comment by jainaashish** [comment] 2018-09-24 16:38
@ffMathy I had not closed the issue (added a label only). But @StingyJack for pointing to the related issue. I'll close it as dupe of https://github.com/NuGet/Home/issues/6873

**Closed as completed by jainaashish** 2018-09-24 16:38 UTC
Labels: Resolution:Duplicate
