### ISSUE TITLE
Nuget keeps redownloading packaget to %USERPROFILE%\nuget\packages even when I changed globalPackagesFolder in my nuget.config

### ISSUE THREAD

**Issue by justinjalandoniiwest** [NuGet/Home#10561] opened 2021-02-10 04:10 UTC
I have configured my `nuget.config` to use another drive as a local repository but it still keeps installing in the `%USERPROFILE%\nuget\packages`:

Here is my configuration folder for my global `nuget,config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<config>
		<add key="globalPackagesFolder" value="D:\dotNet\nuget-packages" />
		<add key="repositoryPath" value="D:\dotNet\nuget-packages" />
	</config>
</configuration>
```

Does this not work for global configurations? `nuget,config`

**Comment by zivkan** [comment] 2021-02-10 22:50
I've attached a sample solution with a `nuget.config` file that redirects the global packags folder. I made it a relative path from the solution, rather than an absolute path, in case someone tried to run the sample who doesn't have a D:\ drive. But manual testing of pointing it to an absolute path also worked for me.

[gpfRedirect.zip](https://github.com/NuGet/Home/files/5961876/gpfRedirect.zip)

So, I'm unable to reproduce the issue you're reporting.

If you are doing a solution restore, the `nuget.config` file needs to be in the same directory as the sln file, or in a parent directory.  Visual Studio won't find a `nuget.config` in a sub directory of where the solution is, or in a "sibling" directory structure.

If this doesn't help, can you please explain your directory structure, or other information that can help us understand why it's not working for you?

**Comment by justinjalandoniiwest** [comment] 2021-02-11 08:17
Hello, that example work. I global nuget.config in my `C:\Users\MyUser\.nuget` and it didn't work. the Project solutions structure seems to work though. What I'm doing now however is setting "NUGET_PACKAGES" in my environment variables to override the project level solution configuration:

![image](https://user-images.githubusercontent.com/75491773/107614114-9ff44200-6c84-11eb-9690-abbd3ddedb15.png)

However, it still doesn't download to the specified folder I want it to be in

**Comment by justinjalandoniiwest** [comment] 2021-02-11 10:35
Alternatively I also tried this in the nuget-cli:

![image](https://user-images.githubusercontent.com/75491773/107625876-ed2ddf00-6c97-11eb-9045-3e87bb87b58f.png)

It still doesn't work

**Comment by nkolev92** [comment] 2021-02-22 21:14
Hey @justinjalandoniiwest 

Please refer to https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders for more detailed information. 

From the screenshots you posted, we can observe that there's a typo in your env variable name. The name is missing an `S`. 

When setting through the CLI, you need to use globalPackagesFolder instead of NUGET_PACKAGES. NUGET_PACKAGES is the only the environment variable name.

**Comment by nkolev92** [comment] 2021-02-22 21:15
See the above comment. Closing as not a bug for now. 

Feel free to create new issues as needed. 

Thanks!

**Closed as completed by nkolev92** 2021-02-22 21:15 UTC
Labels: Resolution:NotRepro, Area:Settings, Functionality:Restore, Resolution:NotABug, WaitingForCustomer

**Comment by zivkan** [comment] 2021-02-22 21:21
For what it's worth, I had tried putting the `globalPackagesFolder` nuget.config setting in my user-profile `nuget.config`, and it did work for me. In fact, I forgot to undo the setting, and when I used `dotnet nuget locals global-packages --clear` for a customer investigation recently, I discovered that I never removed this test setting.

All I can suggest, is to check for other typos. "it works for me". 😕

**Comment by justinjalandoniiwest** [comment] 2021-02-23 14:17
> 
> 
> Hey @justinjalandoniiwest
> 
> Please refer to https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders for more detailed information.
> 
> From the screenshots you posted, we can observe that there's a typo in your env variable name. The name is missing an `S`.
> 
> When setting through the CLI, you need to use globalPackagesFolder instead of NUGET_PACKAGES. NUGET_PACKAGES is the only the environment variable name.

may I know where the typo is? Can I have an example of how to set it?

**Comment by justinjalandoniiwest** [comment] 2021-08-07 09:42
> 
> 
> Hey @justinjalandoniiwest
> 
> Please refer to https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders for more detailed information.
> 
> From the screenshots you posted, we can observe that there's a typo in your env variable name. The name is missing an `S`.
> 
> When setting through the CLI, you need to use globalPackagesFolder instead of NUGET_PACKAGES. NUGET_PACKAGES is the only the environment variable name.

Hello there has been some time, but the images I have posted seems to have no typo error

**Comment by zivkan** [comment] 2021-08-07 13:33
We can't reproduce the issue, so I don't know what else to suggest. In case you're using nuget.exe, rather than visual studio, msbuild or the dotnet cli, make sure you're using a new version of nuget.exe. Some customers have a 5+ year old version of nuget.exe checked into their source control, or [download the deprecated 2.8.1 version](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#macoslinux).

Otherwise, my last idea is to debug nuget yourself.

```text
git clone https://github.com/NuGet/NuGet.Client
cd NuGet.Client
.\configure.ps1
start NuGet.sln
```

Then set the startup project to NuGet.CommandLine (under src\NuGet.Clients). Open the NuGet.CommandLine project properties, go to the Debug tab, set the command line options to "restore", set the working directory to the solution/project you're restoring. Finally put a breakpoint in this method:
https://github.com/NuGet/NuGet.Client/blob/0fc58e13683565e7bdf30e706d49e58fc497bbed/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L225

**Comment by zivkan** [comment] 2021-08-07 13:46
Oh, one more thing, check if any of your MSBuild files has set the `RestorePackagesPath` property, or if you have an environment variable with that name, set to your user profile directory.

**Comment by justinjalandoniiwest** [comment] 2021-08-15 12:03
> 
> 
> We can't reproduce the issue, so I don't know what else to suggest. In case you're using nuget.exe, rather than visual studio, msbuild or the dotnet cli, make sure you're using a new version of nuget.exe. Some customers have a 5+ year old version of nuget.exe checked into their source control, or [download the deprecated 2.8.1 version](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#macoslinux).
> 
> Otherwise, my last idea is to debug nuget yourself.
> 
> ```
> git clone https://github.com/NuGet/NuGet.Client
> cd NuGet.Client
> .\configure.ps1
> start NuGet.sln
> ```
> 
> Then set the startup project to NuGet.CommandLine (under src\NuGet.Clients). Open the NuGet.CommandLine project properties, go to the Debug tab, set the command line options to "restore", set the working directory to the solution/project you're restoring. Finally put a breakpoint in this method:
> https://github.com/NuGet/NuGet.Client/blob/0fc58e13683565e7bdf30e706d49e58fc497bbed/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L225

is there a way to change where the dll files that nuget downloads to a different folder? When nuget downloads the files it stores them in `C:\Users\QHTF\.nuget`. Is there a way to change the directory? I would like to move it in another folder in an external ssd. Is there a way to do this?

**Comment by zivkan** [comment] 2021-08-16 19:57
This entire thread is about exactly that. [The first comment I posted in this issue](https://github.com/NuGet/Home/issues/10561#issuecomment-777088097) has a sample solution that demonstrates how to do it.
