### ISSUE TITLE
[Bug]: [Cross-platform Sign Verify] Package filed to tampered after running command “pwsh -Command Compress-Archive” on Windows

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12041] opened 2022-08-18 12:34 UTC
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK Version: 7.0.100-rc.2.22417.1

#### Details about Problem
.NET SDK Version: 7.0.100-rc.2.22417.1

#### Detailed repro steps
1.	Execute the [Pre-testing steps](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FManual%20tests%2FTest%20Cases&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344A15B-01B1-4828-AF4C-63FE53687F8A%2FPre-testing%20steps%7C6E4370C3-C593-4B99-ABD8-908D0F9E002B%2F%29).
2.	Where <CertificateFilePath> is the file path to the long-lived .cer or .pem file and <VersionedSdkDirectoryPath> is the directory path for the versioned .NET SDK directory (e.g.:  ./dotnet/dotnet/sdk/7.0.100), add trust for the certificate: 
On Windows:  `.\dotnet\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath>` 
3.	Where <PackageId> is the test package ID and <PfxFilePath> is the file path to the .pfx file, sign the test package: 
On Windows: ` .\dotnet\dotnet nuget sign .\<PackageId>\bin\Debug\<PackageId>.1.0.0.nupkg --overwrite --certificate-path <PfxFilePath> --timestamper http://timestamp.digicert.com/ `
4.	Verify that the previous step succeeded with no warnings or errors. 
5.	Where <PackageId> is the test package ID, modify the signed package.  
On Windows: ` pwsh -Command Compress-Archive -Path .\NuGet.config.template -Update -DestinationPath .\<PackageId>\bin\Debug\<PackageId>.1.0.0.nupkg `

#### Expected
Package succeed to tampered after running command “pwsh -Command Compress-Archive” on Windows

#### Actual
Package filed to tampered after running command “pwsh -Command Compress-Archive” on Windows as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/185396010-0397192e-e1f0-4ebe-b5d3-1174bc175e2b.png)

**Comment by dtivel** [comment] 2022-08-18 14:46
This is expected behavior.

The package is immutable after signing it.  Adding or removing files changes the package.  Re-compressing entries can also change the package.

**Comment by nkolev92** [comment] 2022-08-18 17:47
It seems like @v-luzh is referring to the temparing step itself failing, because it's complaining about pwsh not beign found. 

@v-luzh can you try running the command starting with `Compress-Archive` in a powershell terminal instead?

**Comment by dtivel** [comment] 2022-08-18 19:49
Ah, you're right.  I misunderstood the issue from the title.  @v-luzh, you either need to use PowerShell that is installed with Windows:

```text
powershell.exe -Command ...
```

...or install and use [PowerShell Core](https://github.com/PowerShell/PowerShell/releases):

```text
pwsh.exe -Command ...
```

**Comment by dtivel** [comment] 2022-08-18 19:50
From the screenshot, your command is failing because you're trying to use PowerShell Core, but it's not installed (or found).

**Comment by v-luzh** [comment] 2022-08-19 02:20
@nkolev92 @dtivel , I tried the command as below. Could you please help to confirm if below output is expected with the command "Compress-Archive" in powershell?
![image](https://user-images.githubusercontent.com/20632625/185528371-a09eb960-1116-48fa-9e81-600c0c519f50.png)

If above output means tampering the package is successful, the error NU3034 instead of NU3008 will occur after adding a package reference to the test project as below.
![image](https://user-images.githubusercontent.com/20632625/185550597-b3aa8780-4e86-47da-8f63-6c081a13b887.png)

I will update this bug later if the error NU3034 is the point. :)

**Comment by dtivel** [comment] 2022-08-19 14:01
Within a PowerShell session `Command` seems to be a built-in alias for `Get-Command`, because they both do the same thing, which is [list available PowerShell aliases, cmdlets, and functions](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-command?view=powershell-7.2#example-1-get-cmdlets-functions-and-aliases).  Try executing `Command` then `Get-Command` and you'll see what I mean.

When a word follows `Command` (or `Get-Command`) it acts like a filter, narrowing down that list to a match and [giving you information about that specific match](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-command?view=powershell-7.2#example-5-get-information-about-a-cmdlet).  Executing `Command Compress-Archive` gives you basic information about the [`Compress-Archive` function](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-7.2) itself.  It does not actually execute the `Compress-Archive` function.  (Side note:  `Command Compress-Archive` and `Get-Command Compress-Archive` gives you information about the `Compress-Archive` function, while `Help Compress-Archive` and `Get-Help Compress-Archive` gives you help for the function.)

```text
PS C:\Users\dtivel> Command Compress-Archive

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Compress-Archive                                   1.2.5      Microsoft.PowerShell.Archive
```

Everything after that command seems to be ignored.  For example, executing `Command Compress-Archive Hello, World!` produces exactly the same output.  Your first command printed information about the `Compress-Archive` cmdlet and nothing else.  All the other text (like the NuGet package path) was ignored.  The only thing that is executing is the `Get-Command` cmdlet --- not the `Compress-Archive` function.  Nothing is actually getting compressed into an archive.

To actually execute the `Compress-Archive` function, it needs to be the first word in your command.

When you open a command prompt (i.e.:  cmd.exe) on Windows, it's not capable of executing PowerShell commands directly.  From within a command prompt, you can start a _nested_ PowerShell session by executing either of the following, depending on what you want:

- `powershell.exe`:  This starts a PowerShell (classic, Windows-only) session.
- `pwsh.exe`:  This starts a PowerShell Core session.

For the most part and for your testing purposes, it probably doesn't matter which one you use, but if you can use PowerShell Core, that's probably for the better, because it'll be the same on all platforms.  The only thing that's different is how you start a session; everything else within a session should be the same.

If your test step says execute `pwsh.exe -Command ...` that means that PowerShell will start a session, execute your command, and then exit the PowerShell session.  This is because I didn't want you to remain in a PowerShell session for subsequent steps, to avoid problems like [this](https://github.com/NuGet/Home/issues/11966#issuecomment-1183460376).

Based on your last post it looks like you started a PowerShell session (e.g.:  `pwsh.exe`), and then executed from `Command Compress-Archive ...` on, instead of executing the whole statement as-is (`pwsh.exe -Command Compress-Archive ...`).

`NU3034` means you didn't actually tamper the package.

**Comment by v-luzh** [comment] 2022-08-23 14:40
Hi @dtivel, we didn't use command "pwsh.exe -Command ..." since it cannot be run as below.
![image](https://user-images.githubusercontent.com/20632625/186187376-fb1d419d-9845-486e-b0a6-72bcf5c6bcd4.png)

**Comment by dtivel** [comment] 2022-08-23 17:10
@v-luzh, [install PowerShell](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.2) then retry.

**Comment by v-luzh** [comment] 2022-08-24 11:47
@dtivel Yes, we get the expected NU3008 after installing PowerShell on windows. (Why we need to install PowerShell, isn't that installed implicitly on Windows already since we can enter PS session after typing "powershell" in cmd?) But there is a redundant error NU3034 after running add a package reference command to the test project as below.
![image](https://user-images.githubusercontent.com/20632625/186409550-f9836682-f211-4b38-aefe-2dbfdf9d98a8.png)

**Comment by dtivel** [comment] 2022-08-24 12:18
> (Why we need to install PowerShell, isn't that installed implicitly on Windows already since we can enter PS session after typing "powershell" in cmd?)

@v-luzh, I gave reasons in earlier posts.

* `powershell.exe` is Windows PowerShell.  This is available only on Windows.
* `pwsh.exe` is PowerShell Core.  This is available on Windows, Linux, and macOS.

For the most part and for your testing purposes, it probably doesn't matter which one you use, but if you can use PowerShell Core, that's probably for the better, because it'll be the same on all platforms.  The only thing that's different is how you start a session; everything else within a session should be the same.

I will close this issue.

Either by email or Teams, please send me a direct link to the exact test case you are running.

**Closed as completed by dtivel** 2022-08-24 12:18 UTC
Labels: Type:Bug, Functionality:Signing, Type:Test, Found:ManualTests

**Comment by v-luzh** [comment] 2022-08-25 11:01
@dtivel, The bug is found in [this case](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={8a3c6685-1661-47f4-8807-b765ca62aea1}&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FCross-platform%20verify%20%20tampered%20signed%20package%7Cec78d709-cbfc-4ecd-b068-85de4584ff38%2F%29&wdorigin=703).

Although the expected NU3008 showed finally, a redundant error NU3034 (in the above screenshot) is not expected. So,, we filed another bug 12055 to track.
