### ISSUE TITLE
Unable to resolve '{dotnet-cli-tool} (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'" on a netcoreapp1.1

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4801] opened 2017-03-14 02:17 UTC
As reported on twitter:
[https://twitter.com/stevedesmond_ca/status/841020721933475840](https://twitter.com/stevedesmond_ca/status/841020721933475840)
![image](https://cloud.githubusercontent.com/assets/14800916/23883016/9270958c-0821-11e7-9475-f403b3497eeb.png)

**Comment by emgarten** [comment] 2017-03-14 08:07
The error message occurs when the package cannot be found on the feed. Verify that your sources are correct and that the package does exist.

The target framework of your project has no impact on the tool.

**Comment by SteveDesmond-ca** [comment] 2017-03-14 17:53
Steps to reproduce:
- dotnet new
- update your csproj to
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="libyear" Version="0.1.0" />
  </ItemGroup>
</Project>
```
- dotnet restore

Expected result:
- restore succeeds

Observed result:
```
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Package libyear 0.1.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package libyear 0.1.0 supports: netcoreapp1.1 (.NETCoreApp,Version=v1.1) [D:\Code\LibYear\test\LibYear.TestApp\LibYear.TestApp.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.0. [D:\Code\LibYear\test\LibYear.TestApp\LibYear.TestApp.csproj]
```

**Comment by emgarten** [comment] 2017-03-14 19:00
@stevedesmond-ca thanks for the update, that error is referring to compatibility. Tools are restored under netcoreapp1.0 which is why you are seeing this. The target framework of the project is unrelated to the project's framework, tools are executed independently.

@natemcmaster what is the current guidance around creating tools for netcoreapp1.1?

**Comment by SteveDesmond-ca** [comment] 2017-03-14 19:01
Thanks, I assumed as much -- is this documented anywhere / would you like me to?

**Comment by natemcmaster** [comment] 2017-03-14 19:09
Duplicate of https://github.com/NuGet/Home/issues/4396. You can only use netcoreapp1.0 TFM. See also https://github.com/dotnet/cli/issues/4764 (which was closed as "by design").

cc @livarcocc @blackdwarf

**Comment by emgarten** [comment] 2017-03-14 19:25
Thanks @natemcmaster  

I'm going to close this out, and it looks like the doc concerns are already raised in the other issues.

**Closed as completed by emgarten** 2017-03-14 19:25 UTC
Labels: Resolution:External
