### ISSUE TITLE
NuGet incorrectly downgraded package version

### ISSUE THREAD

**Issue by codeimpossible** [NuGet/Home#7767] opened 2019-02-05 17:52 UTC
## Details about Problem

NuGet gave me the following error during a `dotnet restore`. The csproj names below have been changed to protect the innocent.

```
Webapp.csproj : error NU1605: Detected package downgrade: M.Client from 29.0.1 to 29.0.0. Reference the package directly from the project to select a different version.
Webapp.csproj : error NU1605:  Webapp -> Adapter 22.0.0 -> M.Client (>= 29.0.1 && < 30.0.0)
Webapp.csproj : error NU1605:  Webapp -> M.Client (>= 29.0.0 && < 30.0.0)
```

For clarity, my dependency graph looks like this:

```
- Webapp.csproj
  - M.Client                          // versions (>= 29.0.0 && < 30.0.0)
  - Adapter.dll
    - M.Client                        // versions (>= 29.0.1 && < 30.0.0)
```

in Webapp.csproj:

```xml
<PackageReference Include="M.Client" Version="[29.0.0, 30)" />
```

in Adapter.csproj:

```xml
<PackageReference Include="M.Client" Version="[29.0.1, 30)" />
```

I had expected NuGet to resolve M.Client to version `29.0.1` since it is the lowest version that satisfies both version ranges.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `dotnet.exe`

NuGet version (x.x.x.xxx): 4.7.0.5 ( `$ dotnet nuget --version` )

dotnet.exe --version (if appropriate): 2.1.301

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): win10 v1709 (16299.125)

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a root project that includes 2 nuget packages: A, B.
2. the A package should require package B, but within a specific version range, for example: `[1.0.1, 2)`
3. the root project should require package B, but within a more generic version range, for example `[1.0.0, 2)`.

`dotnet restore` should fail with an error similar to the one I posted above. I would expect nuget to resolve the dependency of B to `1.0.1` since it is the lowest common denominator that satisfies both version ranges.

**Comment by nkolev92** [comment] 2019-02-05 18:34
The behavior is by design. 
See:
[Resolution logic](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#dependency-resolution-with-packagereference
)
[NU1605 warning logic](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605)

The nearest win rules takes effect. NuGet will not bump directly referenced packages unless the version is missing.

**Comment by codeimpossible** [comment] 2019-02-05 19:53
I agree that it wouldn't make sense to shift a dependency version if the nearest wants a major version +/- but shouldn't patch and minor resolutions shift according to lowest common denominator and not nearest to root?

**Comment by nkolev92** [comment] 2019-02-05 20:13
The nearest wins applies to the full version, that was also done by design.

**Comment by nkolev92** [comment] 2019-03-29 21:00
Closing this per the above comments.

**Closed as completed by nkolev92** 2019-03-29 21:00 UTC
Labels: Resolution:ByDesign, Functionality:Restore, Style:PackageReference
