### ISSUE TITLE
v3.4.4 - Nuget restore throws "The given path's format is not supported"

### ISSUE THREAD

**Issue by Bidthedog** [NuGet/Home#3442] opened 2016-09-14 10:05 UTC
I recently updated to 3.4.4 from 3.3.0 and started getting this error when running "nuget restore" from the SLN folder. I tried a few params, but could not get it working. I've tried all of the following:

nuget restore
nuget restore My.Project.Name.sln
nuget restore "My.Project.Name.sln"
nuget restore My.Project.Name.sln -ConfigFile nuget.config
nuget restore My.Project.Name.sln -MsBuildVersion 14 -NoCache -Verbosity d -ConfigFile nuget.config

etc...

The solution has a "nuget.config" file in the solution root, with a reference to both a private feed and the default nuget feed:

<?xml version="1.0" encoding="utf-8"?>

```
<configuration>
  <config>
    <add key="repositoryPath" value="packages" />
  </config>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="MyFeed" value="http://nuget.mycustomdomain.com/api/v2/" />
  </packageSources>
</configuration>
```

The verbose error is as follows (same error occurs with any incarnation of parameters):

```
$ nuget restore My.Project.Name.sln -MsBuildVersion 14 -NoCache -Verbosity d -ConfigFile nuget.config
Restoring NuGet packages for solution D:\git\My.Project.Name\My.Project.Name.sln.
System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
   at NuGet.CommandLine.RestoreCommand.GetInputsFromDirectory(String directory, PackageRestoreInputs packageRestoreInputs)
   at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Path.GetFullPath(String path)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
   at NuGet.CommandLine.RestoreCommand.GetInputsFromDirectory(String directory, PackageRestoreInputs packageRestoreInputs)
   at NuGet.CommandLine.RestoreCommand.DetermineRestoreInputs()
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__23.MoveNext()<---
```

It occurs in MINGW64 (bash), command prompt and a powershell prompt.

I have also tried this without the nuget.config file in the solution root - same issue.

Reverting back to 3.3.0 has resolved the issue.

**Comment by yishaigalatzer** [comment] 2016-09-14 19:37
I'm suspecting this has to do with the packages entry, we should look into this in 3.5.

**Comment by yishaigalatzer** [comment] 2016-09-14 19:38
@rrelyea @zhili1208 is this something we already fixed?

**Comment by zhili1208** [comment] 2016-09-14 21:04
I think this is fixed, Can you try https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine/3.5.0-rtm-1829?

**Comment by vphad** [comment] 2016-09-14 21:19
Hi,
 Is there any workaround available ?

**Comment by zhili1208** [comment] 2016-09-14 21:39
@vphad  have you tried latest bit? https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine/3.5.0-rtm-1829?

**Comment by vphad** [comment] 2016-09-14 21:52
I am trying that now, however, I appreciate if you could share the root cause ?

Also, if any workaround available.

**Comment by zhili1208** [comment] 2016-09-14 22:04
https://github.com/NuGet/Home/issues/3235 here is the issue, website project path in csproj is host URL, NuGet will throw when try to parse it

**Comment by vphad** [comment] 2016-09-14 22:07
This works fine with 3.5.0-rtm-1829 for me.

**Comment by yishaigalatzer** [comment] 2016-09-14 22:13
@zhili1208 what is the workaround?

**Comment by zhili1208** [comment] 2016-09-14 22:27
removing website Project from solution should make it work

**Comment by Bidthedog** [comment] 2016-09-15 06:15
Ah yes, we have a website project in most of our solutions. I'll try the beta today.

**Comment by Bidthedog** [comment] 2016-09-15 08:14
I tried this with NuGet Version: 3.5.0.1737 (the one on the downloads page - https://dist.nuget.org/index.html) and it's still happening. How do I get a later build than that?

**Comment by Bidthedog** [comment] 2016-09-15 08:16
Found NuGet Version: 3.6.0.1842 in the "nightly builds", and that seems to work. Can't find 3.5-rtm-1829 anywhere though.

**Comment by zhili1208** [comment] 2016-09-15 16:34
@Bidthedog here is the link https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine/3.5.0-rtm-1829

**Comment by Bidthedog** [comment] 2016-09-16 08:04
Thanks @zhili1208 :)

**Comment by rrelyea** [comment] 2016-09-21 00:34
Closing as it appears everybody agrees that the 3.5.0-rtm-1829 build has fixed it.

**Closed as completed by rrelyea** 2016-09-21 00:34 UTC
Labels: Resolution:Duplicate, Type:Bug, Product:NuGet.exe, Functionality:VisualStudioUI

**Comment by Bidthedog** [comment] 2016-09-21 06:39
Yep, 3.5.0-rtm-1829 fixed my problem too
