### ISSUE TITLE
'dotnet nuget push' any value not immediately associated with other options automatically become part of paths

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11631] opened 2022-03-01 18:08 UTC
Follow up on https://github.com/NuGet/Home/issues/11601.
If I do `dotnet nuget push *.nupkg -n az contoso -s Test` then here `az`, `contoso` become part of paths besides `*.nupkg`.
It's quite implicit and confusing for end users, end up with `error: File does not exist az`

![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/cd865352-6251-4020-baad-5a34e151cb1d)

Not sure what would be best course of action here.

**Comment by nkolev92** [comment] 2022-03-10 19:59
Team triage: Closing by design.

**Closed as completed by nkolev92** 2022-03-10 19:59 UTC
Labels: Type:Bug, Functionality:Push, Area:Logging, Product:dotnet.exe
