### ISSUE TITLE
The props/targets files are never reloaded in traditional csproj 

### ISSUE THREAD

**Issue by eschneider999** [NuGet/Home#7080] opened 2018-07-01 23:26 UTC
Installing my Nuget package Symbiotic_Micro_ORM_Net_Standard_x64.2.1.0-rc does not work when using the PackageReference mode. Seems to work in the old config mode so far.

You would think if I created a package with their own tools it would work...

## Details about Problem

Nuget Package explorer (4.4.3+g7cd7607902)
Nuget Package manager (4.6.0) 
Visual Studio 2017 Pro (15.7.4)
Windows 10 pro

No; I have never got the PackageReference method to work. (Unless running VS as Admin, may require a reload of sol/project)

1.  Create new .net 4.6.1 class library project.

2. You must save the project first.

3.  Use Nuget manager to add the package "Symbiotic_Micro_ORM_Net_Standard_x64.2.1.0-rc"
...
[ClassLibrary12.zip](https://github.com/NuGet/Home/files/2153328/ClassLibrary12.zip)

**Comment by eschneider999** [comment] 2018-07-01 23:59
Works if I run Visual Studio as Admin when adding the Nuget package.

How lame...

**Comment by mishra14** [comment] 2018-07-02 19:22
@eschneider999 is this related to https://github.com/NuGet/Home/issues/7062?

**Comment by eschneider999** [comment] 2018-07-02 19:58
No, to clarify.

For Nuget packages.config method of the lib not added, I believe that is my fault by not placing the lib in all the relevant folders.

The PackageReference issue remains a problem, and was discovered from our investigation of 7062.

So I would be fine if we closed 7062, continued on this case: 7080

 


On July 2, 2018 2:22:09 PM CDT, Ankit Mishra <notifications@github.com> wrote:
>@eschneider999 is this related to
>https://github.com/NuGet/Home/issues/7062?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NuGet/Home/issues/7080#issuecomment-401907564

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nkolev92** [comment] 2018-07-02 22:02
@eschneider999 
I don't get it...what doesn't work here? 

That package is not publicly available so we can't repro it.

**Comment by eschneider999** [comment] 2018-07-02 22:29
Yes, you can, as I have done several times.

Simply include prerelease items.

**Comment by nkolev92** [comment] 2018-07-02 22:33
@eschneider999 

It installed just fine on my machine. 

What **doesn't** work? 

```

Restoring packages for C:\Users\user\Source\Repos\ConsoleApp41\ConsoleApp41\ConsoleApp41.csproj...
Restoring packages for C:\Users\user\Source\Repos\ConsoleApp41\ConsoleApp41\ConsoleApp41.csproj...
  GET https://api.nuget.org/v3-flatcontainer/symbiotic_micro_orm_net_standard_x64/index.json
  OK https://api.nuget.org/v3-flatcontainer/symbiotic_micro_orm_net_standard_x64/index.json 282ms
  GET https://api.nuget.org/v3-flatcontainer/symbiotic_micro_orm_net_standard_x64/2.1.0-rc/symbiotic_micro_orm_net_standard_x64.2.1.0-rc.nupkg
  OK https://api.nuget.org/v3-flatcontainer/symbiotic_micro_orm_net_standard_x64/2.1.0-rc/symbiotic_micro_orm_net_standard_x64.2.1.0-rc.nupkg 324ms
Installing Symbiotic_Micro_ORM_Net_Standard_x64 2.1.0-rc.
Committing restore...
Generating MSBuild file C:\Users\user\Source\Repos\ConsoleApp41\ConsoleApp41\obj\ConsoleApp41.csproj.nuget.g.props.
Generating MSBuild file C:\Users\user\Source\Repos\ConsoleApp41\ConsoleApp41\obj\ConsoleApp41.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Users\user\Source\Repos\ConsoleApp41\ConsoleApp41\obj\project.assets.json
Restore completed in 3.67 sec for C:\Users\user\Source\Repos\ConsoleApp41\ConsoleApp41\ConsoleApp41.csproj.
Successfully installed 'Symbiotic_Micro_ORM_Net_Standard_x64 2.1.0-rc' to ConsoleApp41
Successfully installed 'System.Data.Common 4.3.0' to ConsoleApp41
Executing nuget actions took 1.65 sec
Time Elapsed: 00:00:05.8513588
========== Finished ==========
```

**Comment by eschneider999** [comment] 2018-07-02 22:35
just because the log says it there, doesn't mean it worked. Or at least it does not for me.

Try referencing to the lib. add "using Frozenelephant.Symbiotic" to the class.

**Comment by nkolev92** [comment] 2018-07-02 22:43
![intellisense](https://user-images.githubusercontent.com/2878341/42189701-5dc0e27e-7e0e-11e8-8a86-edec81bcb78d.png)

The intellisense gets populated just fine. 

Is that consistently reproducible on your machine? 
Does it happen on other machines?

**Comment by eschneider999** [comment] 2018-07-02 22:50
Yes, every time on multiple machines.
Are you running as Admin?

![nugetissue](https://user-images.githubusercontent.com/17154320/42189977-62375b96-7e20-11e8-8dcb-919e559bbacf.jpg)

**Comment by eschneider999** [comment] 2018-07-02 22:52
![nugetissue2](https://user-images.githubusercontent.com/17154320/42190019-a1d9f10a-7e20-11e8-8fe9-a0f75cca99cb.jpg)

**Comment by nkolev92** [comment] 2018-07-02 23:03
@eschneider999 
No. That shouldn't make a difference unless your global packages folder requires special permissions. 

Do you have a special nuget configuration? 
Can you try deleting that package from the global packages folder?

The weird thing is that Visual Studio thinks that the package is not installed. 
Can you share the assets from that exact project?

**Comment by eschneider999** [comment] 2018-07-02 23:34
Admin does make a difference for me.
Simply doing the steps provided.
Where is the global packages folder?
no special config, i did share it on the original post

**Comment by eschneider999** [comment] 2018-07-02 23:35
Try doing a class library (4.6.1), that's what I have been doing.

**Comment by nkolev92** [comment] 2018-07-03 00:36
@eschneider999 
I used net461 in my repro. 

The global packages folder is in `%UserProfile%/.nuget/packages` unless overriden. 

Please try removing the package from there. 

Additionally please remove the obj and bin directories of the project and restart Visual Studio.

**Comment by eschneider999** [comment] 2018-07-03 01:13
ok that fixed it, but now it stopped asking me which nuget process to use on new projects?
And why did that fix it?

**Comment by nkolev92** [comment] 2018-07-03 21:23
So the funny thing that's happening is that the build succeeds, in both Visual Studio and from the commandline, but the intelisense (error list) has a weird can't find reference error. 

Deleting the assets file and/or reloading the project fixes the problem.
There are no differences between the assets file in working and non working scenario.

This is all easily reproducible with the attached project.
The root cause seems to be that the assets file is not reloaded.

//cc @tmeschter @Pilchie 
I think this is a duplicate of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/560696. 
Any public issue that the customer can use for tracking? 

@eschneider999 
This shouldn't be happening on a clean/build correct? 
Ideally you shouldn't be committing your assets/props/targets files.

**Comment by eschneider999** [comment] 2018-07-03 21:35
A close and reopen did not fix it. (just tested the same project from yesterday ClassLibrary20)
Also a clean/rebuild did not fix it. 
(just tested the same project from yesterday ClassLibrary20)
My case seems it's broken until the package folder is deleted.

**Comment by eschneider999** [comment] 2018-07-03 21:37
[2.1.1-rc.zip](https://github.com/NuGet/Home/files/2161125/2.1.1-rc.zip)

I uploaded the package folder from my user root in case there's something wrong with it?

**Comment by Pilchie** [comment] 2018-07-03 22:18
> //cc @tmeschter @Pilchie
I think this is a duplicate of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/560696.

I don't think we have anything.  We were hoping NuGet could fix this by not writing the absolute path to the assets file in the targets...

**Comment by Pilchie** [comment] 2018-07-03 22:19
@eschneider999 Deleting obj works because the generated targets in obj have a path to the assets file and the project system uses that, doesn't know to reload the file when it changes, because it only watches the assets file for changes, but if the path to the assets file is wrong, it can't watch the assets file...

**Comment by nkolev92** [comment] 2018-07-03 22:22
@eschneider999 
Basically you need to do a restore and re-open to avoid deleting the assets file, I missed that in my above write-up. 

@Pilchie 
If that's the case then we need to revisit https://github.com/NuGet/Home/issues/4582. 
We tried it  a while back, but it broke SDK based builds, but I think with some of most recent work by @dsplaisted I think we can get further than last time.

**Comment by eschneider999** [comment] 2018-07-03 22:45
how do you do a restore?

**Comment by nkolev92** [comment] 2018-07-03 22:57
Solution Menu -> right click -> Restore NuGet Packages

**Comment by eschneider999** [comment] 2018-07-04 00:15
ok, how do you do that if you don't have a solution and only a single project?

**Comment by nkolev92** [comment] 2018-07-04 03:37
In Visual Studio you have to have a solution. 
when you open a project, it'll create a sln containing that project only. 
![sln](https://user-images.githubusercontent.com/2878341/42255486-dccdf92e-7f00-11e8-98a9-c15159c18d3e.png)
See the above screenshot for that I mean.


From the command line, you can always do `msbuild /t:restore`, or nuget.exe restore

**Comment by eschneider999** [comment] 2018-07-04 04:29
no you do not, my point is;
If you only have a project, you can't restore.

**Comment by nkolev92** [comment] 2018-07-04 05:09
@eschneider999 
you can....you simply run the restore target on a csproj. 

`nuget.exe restore myproj.csproj`
`msbuild /t:restore myproj.csproj` will both work.

**Comment by nkolev92** [comment] 2019-06-07 00:49
#4582 is fixed so this experience should be improved now.

**Closed as completed by nkolev92** 2019-06-07 00:49 UTC
Labels: Resolution:External, Style:PackageReference
