### ISSUE TITLE
Code files (.pp) in ContentFiles folder not added to consuming PackageReference project

### ISSUE THREAD

**Issue by deylin** [NuGet/Home#8718] opened 2019-10-17 10:21 UTC
I have create a multitarget nuget package which includes some code files (.pp) that need to be transformed and added to the consuming project. This works for projects using the 'packages.config' but not for projects using PackageReference.
I can see the transormed files somewhere hidden in '..\obj\Debug\net48\Nuget\CE11B4.....\...'. And they are actually somehow referenced in the project because I can use the code.

I would like the files to be added to the project so that the consumer can use and change them, like in the projects using 'packages.config'. Is this possible?

**Comment by zivkan** [comment] 2019-10-18 20:48
No, for PackageReference projects, NuGet will never copy a file into the consuming project and allow the developer to edit the file.

My best suggestion would be to [create an item template](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template). I believe that from Visual Studio 16.3 dotnet CLI templates are visible in VS, so it will work for your users whether they use Visual Studio or not. Alternatively, design your library with extensibility that doesn't require the consuming project to modify the content file(s) in your package.

**Comment by nkolev92** [comment] 2019-12-30 18:39
Closing this issue as by design per @zivkan's comment.

**Closed as completed** 2020-03-18 22:53 UTC
Labels: Resolution:Question, Style:PackageReference, Area:ContentFiles
