### ISSUE TITLE
Ambiguity with multiple files with the same license filename

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#8305] opened 2019-07-05 22:25 UTC
## Details about Problem

NuGet product used: nuget.exe

NuGet version (x.x.x.xxx): 5.0.2.5988

OS version: Microsoft Windows [Version 10.0.18917.1000]

Worked before? No

## Detailed repro steps so we can see the same problem

Take the following nuspec:

```xml
<?xml version="1.0"?>
<package>
  <metadata>
    <id>test.license.nuspec</id>
    <version>0.0.1</version>
    <title>test.license.nuspec</title>
    <authors>dominoFire</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package test for license file</description>
    <releaseNotes>Test of license file</releaseNotes>
    <copyright>Copyright 2019</copyright>
    <tags>test license</tags>
    <license type="file">license.txt</license>
  </metadata>
  <files>
    <file src="cell\*.txt" />
    <file src="wall\*.txt" />
  </files>
</package>
```

Save the nuspec in the following folder structure:

```
C:.
│   Package.nuspec
│
├───cell
│       license.txt
│       wawa.txt
│
└───wall
        license.txt
        xyz.txt
```

Both files will be present in the nupkg but, it's not clear which file should be referred as the license file.

**Comment by nkolev92** [comment] 2019-07-08 18:31
I think this issue goes beyond licenses, but a general pack issue. 

So I'd say it's a duplicate of https://github.com/NuGet/Home/issues/6941. 

I think we should close this in favor of the older issue https://github.com/NuGet/Home/issues/6941.

Do you agree? Happy to discuss if needed.

**Comment by zivkan** [comment] 2019-07-09 14:01
I thought the license element when using a file has a value which is the absolute path to the file within the package. Therefore `<license type="file">license.txt</license>` means there must be a file named `license.txt` in the root of the package. If there is not, then the package is incorrectly authored and therefore there is no ambiguity?

I'm making an assumption that `<file src="cell\*.txt" />` will keep the `cell` directory in the package and not copy the files into the package root. Same for `<file src="wall\*.txt" />`.

**Comment by nkolev92** [comment] 2019-07-09 15:10
When you glob it preserves the globbed folder structure. 

So everything under `cell` and `wall` will be preserved.

**Comment by nkolev92** [comment] 2020-01-03 22:53
Closing as dup.

**Closed as completed by nkolev92** 2020-01-03 22:53 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Pack
