### ISSUE TITLE
ProjectReference becomes dependency in nuspec instead of including it in nupkg

### ISSUE THREAD

**Issue by realrubberduckdev** [NuGet/Home#8960] opened 2019-12-18 14:44 UTC
## Details about Problem

This is the exact same issue which was reported in [Issue No.6998](https://github.com/NuGet/Home/issues/6998) but was closed without a clear answer.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 5.0.2.5988 (Not using nuget, but this is in path)

VS version (if appropriate): VS Professional 16.3.7

OS version (i.e. win10 v1607 (14393.321)): Win10 1903

Worked before? If so, with which NuGet version: Unsure.

## Detailed repro steps so we can see the same problem

1. Unzip the attached zip & build the solution.

2. See that in generated TestProjectReferenceNupkg.nupkg, ToBeReferenced is set as a dependency.

The expectation is that the generated package will just include all items at the output path of TestProjectReferenceNupkg project. But making ToBeReferenced a dependency means we will have to publish it as a separate nupkg.

Is there a reason for this being the default behaviour?
Is there a better way of achieving multiple project output in one nupkg (from csproj, ideally instead of introducing nuspec etc or manually adding files) ?
Thank You.
...

### Sample Project

[TestProjectReferenceNupkg.zip](https://github.com/NuGet/Home/files/3978872/TestProjectReferenceNupkg.zip)

**Comment by rrelyea** [comment] 2019-12-18 17:58
Look for existing, highly voted issue, about supporting ‘-includeReferencedProjects’ in dotnet pack.
Likely dupe.

**Comment by realrubberduckdev** [comment] 2019-12-19 09:48
@rrelyea We cannot do this with msbuild, is that correct?

Looking for something in the lines of:
`msbuild .\TestProjectReferenceNupkg.sln /t:includeReferencedProjects`

Got error on the net45 project (attached to this issue).
`error MSB4057: The target "includeReferencedProjects" does not exist in the project.`

Will have to fall back to dotnet pack or using nuspec or publish multiple packages if we cannot do so in msbuild. Our build system is dependent on msbuild at the moment.

**Comment by nkolev92** [comment] 2019-12-30 19:47
Duplicate of https://github.com/NuGet/Home/issues/3891. 

@realrubberduckdev I think @rrelyea's comment was intended as a pointer to a team member to find the dup of this issue. 

It's not possible to this with msbuild/dotnet.exe pack. In general this is not possible with PackageReference right now. https://github.com/NuGet/Home/issues/3891 is the issue tracking the ask.

**Closed as completed** 2020-03-18 22:53 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Pack
