### ISSUE TITLE
NuGet packages for Universal Windows not installing from private feed

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2366] opened 2016-03-21 09:56 UTC
_From @mathikp on March 18, 2016 4:47_

I have a private NuGet feed which has packages for various platforms. All the other platform's packages are working fine, can install those packages from Visual Studio. But packages targeting uap10.0 is cannot be installed in Universal Windows project in Visual Studio 2015. The same packages can be installed from local folder into the project. While installing from online feed, its shows below error.

_Failed to retrieve information from remote source 'http://feedlink'.
Response status code does not indicate success: 404 (Not Found)._

But the package is listing in Package Manager window and also in Package Manager Console while using Get-Package command. Please help.

_Copied from original issue: NuGet/NuGetGallery#2954_

**Comment by maartenba** [comment] 2016-03-21 09:56
Which NuGet server are you using?

**Comment by maartenba** [comment] 2016-03-21 09:56
_From @mathikp on March 18, 2016 7:13_

I'm maintaining our own server for my company.

**Comment by maartenba** [comment] 2016-03-21 09:56
Which server product are you using?

**Comment by maartenba** [comment] 2016-03-21 09:56
_From @mathikp on March 18, 2016 8:46_

We are using Azure.

**Comment by maartenba** [comment] 2016-03-21 09:56
What software is installed to host NuGet packages? Is it a file share? NuGet.Server? NuGet gallery? ProGet? MyGet? Artifactory?

**Comment by maartenba** [comment] 2016-03-21 09:56
_From @mathikp on March 18, 2016 9:1_

We are using NuGet server.

**Comment by maartenba** [comment] 2016-03-21 09:56
Which version of it are you using?

**Comment by maartenba** [comment] 2016-03-21 09:56
_From @mathikp on March 18, 2016 9:7_

The version is 3.0.

**Comment by maartenba** [comment] 2016-03-21 09:56
The version of NuGet.Server? There is no 3.0 verion of it (we just released 2.10.1 yesterday)
We will need some info on the environment and server software used to be able to see what the problem could be...

**Comment by maartenba** [comment] 2016-03-21 09:56
_From @mathikp on March 21, 2016 7:40_

Sorry for the delay in response and for mentioned the version wrongly. We have tried version [2.10.1](https://www.nuget.org/packages/NuGet.Server/2.10.1) NuGet.Sever assembly in our project. Still the error is coming frequently. The package is getting installed only few times. Most of the time it fails.

**Comment by maartenba** [comment] 2016-03-21 09:56
Do you happen to have more logs on the NuGet install? (in VS)
Which Nuget verson do you have instaleld in Visual Studio? Can you try vLatest from http://dist.nuget.org/index.html ?

**Comment by maartenba** [comment] 2016-03-21 09:56
_From @mathikp on March 21, 2016 9:42_

Installation Log: [NuGetLog.txt](https://github.com/NuGet/NuGetGallery/files/181900/NuGetLog.txt)
I'm using NuGet Package Manager 3.3.0.167 in my VS.
The package is installing fine while using nuget.exe. But the issue is with installing package inside VS with Package Manager or Package Manager Console.

**Comment by maartenba** [comment] 2016-03-21 09:56
You may be missing the `/nuget` part of the URL, full URL to NuGet.Server should be http://server/nuget

**Comment by maartenba** [comment] 2016-03-21 09:56
_From @mathikp on March 21, 2016 9:55_

We are just checking the server site in staging for testing purpose. Actually all the packages are listing in the Package Manager. There is no issues with the url.

**Comment by maartenba** [comment] 2016-03-21 09:56
May be a client issue then, moving

**Comment by yishaigalatzer** [comment] 2016-03-23 00:02
Can you please provide more input?
1. Can you share a fiddler feed of the failed install?
2. Do you have a log (you can find it in the output folder)
3. Does a specific package fail constantly or just some of the packages.

**Comment by mathikp** [comment] 2016-03-23 12:26
1. I cant understand what you mean as fiddler feed.
2. Log is here. [NuGetLog.txt](https://github.com/NuGet/Home/files/185950/NuGetLog.txt)
3. All the packages are failed.

Do we need to do any special configurations in our feed for support UWP packages?

**Comment by yishaigalatzer** [comment] 2016-03-23 16:31
Fiddler trace. Install fiddler and show the network traffic from visual studio

Sent from Outlook Mobilehttps://aka.ms/xp9y6l

On Wed, Mar 23, 2016 at 5:26 AM -0700, "mathikp" <notifications@github.com<mailto:notifications@github.com>> wrote:
1.  I cant understand what you mean as fiddler feed.
2.  Log is here. NuGetLog.txthttps://github.com/NuGet/Home/files/185950/NuGetLog.txt
3.  All the packages are failed.

Do we need to do any special configurations in our feed for support UWP packages?

##

**Comment by mathikp** [comment] 2016-04-18 12:26
@yishaigalatzer I have sent the fiddler trace of the issue through mail to support@nuget.org with subject as **Fiddler Trace for #2366.**

**Comment by mathikp** [comment] 2016-05-02 07:24
@yishaigalatzer Could you please update the status on this issue? Have you checked?

**Comment by yishaigalatzer** [comment] 2016-05-02 07:28
Missed the email to support. Will assign in the morning

**Comment by alpaix** [comment] 2016-05-02 22:11
Related to https://github.com/NuGet/Home/issues/2357.
The actual [fix](https://github.com/NuGet/NuGet.Client/pull/434) is in review and it is planned to be released with 3.5.

**Comment by alpaix** [comment] 2016-05-02 22:14
@mathikp As a temporary workaround I'd suggest setting _full_ feed Url (after all redirects). 
As I've seen in the Fiddler trace you sent it should be: http://nuget.syncfusion.com/nuget_universalwindows/nuget/getsyncfusionpackages/universalwindows

**Comment by rrelyea** [comment] 2016-05-03 16:48
We have a fix that was already rejected from 3.4.x as it was too risky, I believe.

This is not a regression from 3.3
This is a serious problem.

As such, moving to 3.5rc – where we can get more bake time and customer feedback before final release.

**Comment by mathikp** [comment] 2016-05-04 04:00
When can we expect main release with the fix?

**Comment by mathikp** [comment] 2016-08-22 04:54
Hi Team,

Any update on this ?

**Comment by mathikp** [comment] 2016-12-23 04:37
When will this issue gets resolved? @rrelyea @alpaix @yishaigalatzer @maartenba

**Comment by abbassyed1546** [comment] 2017-03-13 09:39
Hi @rrelyea , @alpaix , @yishaigalatzer a and @maartenba ,

We have faced the same issue in VS 2017 Professional. As a workaround issue will get fixed while we using full feed link. Is this issue from NuGet Package Manager (NuGet client) ? When it will be resolved from NuGet package manager itself ?

**Comment by emgarten** [comment] 2018-02-02 00:28
There have been several issues fixed in this area. If you are still seeing problems with private feeds ensure that you are using the latest version of NuGet and that the issue is not a problem with the feed. Then open a new issue containing a network trace and details with exactly which requests the nuget client makes that are invalid.

**Closed as completed by emgarten** 2018-02-02 00:28 UTC
Labels: Type:Bug, Resolution:External
