### ISSUE TITLE
Push always sends entire package twice with authenticated package sources

### ISSUE THREAD

**Issue by zlrenner** [NuGet/Home#1501] opened 2015-10-01 18:49 UTC
...or alternatively stated: push continues to send entire request even after server responds with an error (e.g. 4XX).

When pushing to an authenticated feed, push continues to send the entire request, even if the server has already seen the headers and determined that the request is invalid (e.g. due to authentication).

Something like "Expect: 100-Continue" and/or pre-authenticate should be used to prevent this.
Note: Having the server forcibly abort/reset the connection results in the client throwing "An existing connection was forcibly closed by the remote host".

**Comment by yishaigalatzer** [comment] 2015-10-05 16:11
@johnataylor assigning over to you, this looks like another good optimization for push.

CC @maartenba

**Comment by yishaigalatzer** [comment] 2015-11-23 18:19
@zlrenner it seems fine that the client tries to do both, the server just should avoid reading the body, isn't that what is going on?

**Comment by zarenner** [comment] 2015-11-23 18:43
@yishaigalatzer The server cannot avoid reading the body, my understanding and testing shows that it must finish reading the body (even if it plans to discard it) because of HTTP message framing.  Note that if the server forcibly closes the socket, the client throws, so that's not an option.

The two options I'm aware of are:
1. Add support to the client (and server) for Expect: 100-continue, so the client doesn't actually send the payload until the server confirms the request headers are acceptable.
2. Once the client performs a request with authentication, always perform future requests with authentication.  Assuming this is implemented correctly, because we perform a GET before doing any PUTs, packages would only be put once.  Solves the authenticated feeds problem only.

**Comment by yishaigalatzer** [comment] 2015-11-23 19:39
@zarenner agreed that we can't resolve it with a server only change.

We should carefully evaluate the suggestions 1/2, and see if there are other options.

Can you explain:

> Solves the authenticated feeds problem only.

**Comment by zarenner** [comment] 2015-11-23 19:55
2 is only a solution to the problem where authentication isn't tried until 401 response, and thus the package is sent twice.  It is not a solution to the inefficiency ("problem" might be a bit debatable here) where a client sends invalid headers, e.g. invalid credentials or apikey, and the whole body is sent even though the server knew it was bad as soon as it inspected the headers.

**Comment by yishaigalatzer** [comment] 2015-11-23 20:05
Ah, it can still abort it and we can still handle it

**Comment by zarenner** [comment] 2015-11-23 20:13
My concern with aborting/forcibly closing the connection is that it's a hack, especially since the server can't actually return an error response to the client.  From the client's perspective, the server just died.

I believe that Expect: 100-Continue is the correct solution, as it was designed for exactly this.  What I don't completely know, however, is what happens when the server doesn't support it.  http://blogs.msdn.com/b/fiddler/archive/2011/11/05/http-expect-continue-delays-transmitting-post-bodies-by-up-to-350-milliseconds.aspx indicates that .NET will wait 350ms before falling back on sending the full request, but it's something we'll have to check.

edit:  Note that implementing Expect: 100-Continue doesn't preclude us from also implementing always-send-credentials-after-401ing to (e.g. on pushes of multiple packages) roughly half the number of requests.

**Comment by spadapet** [comment] 2016-03-25 00:02
Just a note: https://blogs.msdn.microsoft.com/fiddler/2011/11/05/net-httpwebrequests-and-expect-100-continue/

**Comment by spadapet** [comment] 2016-03-30 16:59
After much investigation, I think I fully see what is going on.
Comments for the two suggestions:
1. The client already sends Expect: 100-continue by default. It waits 350ms for the 100-continue before sending the whole body. So the server just needs to respond with failure or 100 before 350ms passes. No change is needed here. Some servers don't respond with 100 (like the one I tried, visualstudio.com) so the client will always wait 350ms.
2. We already cache credentials after authenticating. I don't think a change is needed here. Doing a "pre-authenticate" is a hack and isn't needed as long as the 100-continue works.

The expect 100-continue wasn't working because we aren't sending the data in chunks. We're using a Content-Length so that the server knows how much data to expect. I debugged the .NET HttpWebRequest and see that the Content-Length will force the body to be sent. Only chunked data is allowed to be canceled.

So my only idea for a fix is to send chunked data, no Content-Length. Hopefully all servers can deal with that.

**Closed as completed** 2016-04-01 23:43 UTC
Labels: Priority:2, Type:Bug, Functionality:Push
