### ISSUE TITLE
Http cache hides the new version after it's pushed

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#9134] opened 2020-02-04 19:58 UTC
NuGet.exe 5.4.0

1. Push version 1.0.0 of any package to Azure DevOps artifacts public feed
2. Restore using version 1.0.0
3. Restore succeeds
4. Push version 1.0.1 to the same feed
5. Restore using version 1.0.1

Expected: restore succeeds

Actual: restore fails

Workaround: `nuget cache -clear http-cache`

The problem is that the local cache is storing the 1.0.0 as the latest version of the package. 

I'm not sure it's a bug per se, but it's certainly very confusing behavior and users are likely to blame the server and not think about the local cache.

Consider clearing the cache for the package and feed after pushing a newer version of that package to the same feed.

**Comment by heng-liu** [comment] 2020-02-10 17:21
Close it as a duplicate of  https://github.com/NuGet/Home/issues/7630

**Closed as completed by heng-liu** 2020-02-10 17:21 UTC
Labels: Type:Bug, Area:HttpCaching
