### ISSUE TITLE
VS 2019 crashes after opening Manage NuGet Packages: icon causes unhandled exception in image conversio

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9696] opened 2020-06-18 01:25 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1047675/vs-2019-crashes-after-opening-manage-nugetpackages.html)._

---
Hello,

I have issues to edit my Nuget references in several projects.
Everytime I open Manage NugetPackages the VS 2019 crashes.

I have taken a look into the event viewer and found the following NullReferenceException:
Application: devenv.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.NullReferenceException at NuGet.PackageManagement.UI.IconUrlToImageCacheConverter.AddToCache(System.Uri, System.Windows.Media.Imaging.BitmapSource) at NuGet.PackageManagement.UI.IconUrlToImageCacheConverter.IconBitmapImage_DownloadOrDecodeFailed(System.Object, System.Windows.Media.ExceptionEventArgs) at NuGet.PackageManagement.UI.IconUrlToImageCacheConverter+<>c__DisplayClass5_0. <Convert>b__1(System.Object, System.Windows.Media.ExceptionEventArgs) at System.Windows.Media.UniqueEventHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]. InvokeEvents(System.Object, System.__Canon) at System.Windows.Media.Imaging.BitmapImage.OnDownloadFailed(System.Object, System.Windows.Media.ExceptionEventArgs) at System.Windows.Media.UniqueEventHelper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]. InvokeEvents(System.Object, System.__Canon) at System.Windows.Media.Imaging.LateBoundBitmapDecoder.ExceptionCallback(System.Object) at System.Windows.Media.Imaging.LateBoundBitmapDecoder.DownloadCallback(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object) at MS. Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at MS. Internal.CulturePreservingExecutionContext.Run(MS. Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS. Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS. Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS. Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

Perhaps this is only a problem within my company with a few projects, but I cannot identify the Nuget package which causes the error. 

And in my opinion to give the user a NullReferenceException is not the best practice.

---
#### pwinkelhane on 5/25/2020, 00:52 AM: 

Sorry, I forgot to mention that this problem occured after upgrading from VS 16.4.3 to 16.5.4. I tried 16.5.5 and 16.6.0, but the problem still exists.
#### Fiona Niu[MSFT] on 5/25/2020, 02:26 AM: 

<p>Thank you for taking the time to log this issue! Could you please provide more information via the Visual Studio Feedback Tool(Help -&gt; Send Feedback -&gt; Report A Problem) so that we can conduct further research? The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:</p>
<pre><code>• Open Visual Studio Feedback tool.
• Click the banner letting you know that you have problems requesting your attention.
• Click this problem from the list
• Click &quot;View their request and respond&quot; from the problem details banner
• Add a comment, in the Attachments/Record: click Start Recording
• When the Steps Recorder tool appears, perform the steps that reproduce the problem.
• When you're done, choose the Stop Record button.
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.
• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don't appear on Developer Community.
</code></pre>
<p>For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.</p>
<p>We look forward to hearing from you!</p>

#### pwinkelhane on 5/25/2020, 02:40 AM: 

- Open a solution<br>- Manage Nuget Packages<br>a crash occurs and VS is crashing
#### pwinkelhane on 5/25/2020, 02:43 AM: 

I hope you get all information you need. As I start the recorder the studio crashed as before so I don&#39;t know if you get a useful recording.
#### Fiona Niu[MSFT] on 5/25/2020, 03:15 AM: 

<p>Thanks a lot for providing the information. We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Fernando Aguilar [MSFT] on 6/3/2020, 11:05 AM: 

<p>Apologies for the delay.</p>
<p>By looking at the stack and the repro steps, it seems that there’s a problem on the icons in the packages hosted in the company feed. Are you using <code>&lt;icon/&gt;</code> or <code>&lt;iconUrl/&gt;</code> to put icons in the company packages?</p>

#### Visual Studio Feedback System on 6/5/2020, 07:21 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### pwinkelhane on 6/14/2020, 10:55 PM: 

<p>Apologies for the delay.</p><p>Thanks for your hint, I know about the circumstance, that there will be issues if you use the obsolete option.</p><p>Can you please tell me which option shall be used. I will update the packages with the wrong option.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment] 2020-06-18 01:25
We should never crash, regardless of the exception.

**Comment by nkolev92** [comment] 2020-08-27 18:08
There's a duplicate of it in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1147361. 

Please close that when the merge happens.

**Comment by kartheekp-ms** [comment] 2020-08-31 18:38
This [feedback ticket](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1178716) is closed as duplicate of this issue.

**Closed as completed** 2020-08-31 19:09 UTC
Labels: Priority:2, Type:Bug, Functionality:VisualStudioUI, Tenet:Reliability
