### ISSUE TITLE
Unable to push multiple packages at the same time

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#7756] opened 2019-02-01 05:42 UTC
_From @jkdey on February 1, 2019 0:22_

## Steps to reproduce
`dotnet nuget push *.nupkg -k <username>:<password> -s <source_uri>`

## Expected behavior
push all packages as shown in the last [example](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push?tabs=netcore2x#examples)

## Actual behavior
pushes first package only

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.7
 OS Platform: Linux
 RID:         alpine.3.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.503/

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  2.1.503 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

_Copied from original issue: dotnet/cli#10683_

**Comment by wli3** [comment] 2019-02-01 05:42
_From @livarcocc on February 1, 2019 3:47_

@wli3 would you mind checking if this is an issue on our side or on NuGet's side?

**Comment by wli3** [comment] 2019-02-01 05:43
dotnet nuget command is a simple redirector to nuget.xplat

**Comment by nkolev92** [comment] 2019-02-04 23:04
@jkdey 
Can you post the logs from what you are doing (strip away api keys, source urls if needed etc.) 
Run the highest verbosity possible. 

Are you pushing to a private source/nuget.org? 

Have you tried using different versions of the SDK?

**Comment by WernerMairl** [comment] 2019-02-07 12:12
#4393  is likely the same and contains more details/findings... (multiple bugs in place)

**Comment by nkolev92** [comment] 2019-02-07 18:14
Duplicate of https://github.com/NuGet/Home/issues/7756. 

Thanks for pointing it out @WernerMairl

**Closed as completed by nkolev92** 2019-02-07 18:14 UTC
Labels: Resolution:Duplicate, Platform:Xplat, Functionality:Push, Product:dotnet.exe
