### ISSUE TITLE
Unable to find assemblies (specifically, EntityFramework) from Package Manager Console

### ISSUE THREAD

**Issue by daveaglick** [NuGet/Home#987] opened 2015-07-22 18:40 UTC
When you attempt to run any of the Entity Framework version 5.0.0 commands from the Package Manager Console in Visual Studio 2015 you get a `FileNotFoundException`. The reproduce, create an empty console application in Visual Studio 2015. The just run the following in the Package Manager Console (includes error output):

```
Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 3.0.0.0

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package EntityFramework -Version 5.0.0
Attempting to gather dependencies information for package 'EntityFramework.5.0.0' with respect to project 'EfPowerShellTest', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'EntityFramework.5.0.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'EntityFramework.5.0.0'
Resolved actions to install package 'EntityFramework.5.0.0'
Adding package 'EntityFramework.5.0.0' to folder 'E:\Code\EfPowerShellTest\packages'
Added package 'EntityFramework.5.0.0' to folder 'E:\Code\EfPowerShellTest\packages'
Added package 'EntityFramework.5.0.0' to 'packages.config'
Executing script file 'E:\Code\EfPowerShellTest\packages\EntityFramework.5.0.0\tools\init.ps1'
Executing script file 'E:\Code\EfPowerShellTest\packages\EntityFramework.5.0.0\tools\install.ps1'

Type 'get-help EntityFramework' to see all available Entity Framework commands.
Successfully installed 'EntityFramework 5.0.0' to EfPowerShellTest
PM> Enable-Migrations
Exception calling "CreateInstanceFrom" with "8" argument(s): "Could not load file or assembly 'EntityFramework, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified."
At E:\Code\EfPowerShellTest\packages\EntityFramework.5.0.0\tools\EntityFramework.psm1:431 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
 
PM> 
```

Note that running the same command from the same project works fine with the Package Manager Console version 2.8.60318.734 in Visual Studio 2013. I haven't tested with other versions of Entity Framework - I figure that regardless of if other versions work or not, this points to a problem (or at least a change) with the console and whatever is going on may impact other packages that use the console as well.

**Comment by princeo911** [comment] 2015-08-22 22:06
I get the same error with Visual Studio 2013 when I run add migration

Add-Migration -ConfigurationTypeName "Qrom.Security.Identity.Repository.Implementation.Configuration"  -Force -Name "Initial Create" -ConnectionProviderName "System.Data.SqlClient"
Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'file:///P:\Qrom.Security\packages\EntityFramework.6.1.3\tools\EntityFramework.PowerShell.Utility.dll' or one of its 
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)"
At P:\Qrom.Security\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:5
-     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-P ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : FileLoadException

You cannot call a method on a null-valued expression.
At P:\Qrom.Security\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
-     $dispatcher = $utilityAssembly.CreateInstance(
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "CreateInstanceFrom" with "8" argument(s): "Could not load file or assembly 'file:///P:\Qrom.Security\packages\EntityFramework.6.1.3\tools\EntityFramework.PowerShell.dll' or one of its 
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)"
At P:\Qrom.Security\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
-     $domain.CreateInstanceFrom(
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : FileLoadException

I have set execution policy to unrestricted, made no difference, I am on Windows 10 (upgrade) with Visual Studio 2013

**Comment by vahpetr** [comment] 2015-08-23 04:48
cd /d %YouApp%\packages\EntityFramework.6.1.3\lib\net45

%ProgramFiles%\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\gacutil.exe /i EntityFramework.dll

**Comment by princeo911** [comment] 2015-08-23 15:09
I did lots of things and changed many things on my computer, got it working, but now when I try to update some packages that run powershell scripts, I get an a warning script which stops the update from running.
I will attach the images in the next comment. I think there is a link of these issues and Visual Studio Update 5

![razorgenerator startup](https://cloud.githubusercontent.com/assets/13858033/9428769/359a7934-49b1-11e5-8500-edecc8e05eef.png)
![razorgenerator startup2](https://cloud.githubusercontent.com/assets/13858033/9428770/3d1ced5e-49b1-11e5-8fcd-25640b5644e8.png)
![updating json](https://cloud.githubusercontent.com/assets/13858033/9428771/42705a20-49b1-11e5-8f42-72793a3fea11.png)
![updating json2](https://cloud.githubusercontent.com/assets/13858033/9428772/46b2df04-49b1-11e5-98fe-3295d45e70a5.png)

**Comment by princeo911** [comment] 2015-08-23 15:42
I think my issues is a seperate ticket, will delete them and create a ticket

**Comment by yishaigalatzer** [comment] 2015-11-18 23:14
Verified this still repros in 3.3 and RTM version of visual studio. However talking to @bricelam from the EF team, this was fixed in Update I. The root cause is not in the NuGet codebase, so closing as external

**Closed by yishaigalatzer** 2015-11-18 23:14 UTC
Labels: Area:VS.Client, Type:Bug
