### ISSUE TITLE
[Bug]: TargetFrameworks netstandard2.0 does not set TargetFramework for inner build

### ISSUE THREAD

**Issue by tombogle** [NuGet/Home#11721] opened 2022-04-07 14:37 UTC
### NuGet Product Used

MSBuild.exe

### Product Version

Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET Framework

### Worked before?

Yes, but not sure what broke it

### Repro Steps & Context

 I run msbuild l10n.proj /t:ReportVariables /verbosity:detailed with l10n.proj having these contents:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.CommandLine" Version="6.1.0" GeneratePathProperty="true" />
  </ItemGroup>
  <Target Name="ReportVariables" DependsOnTargets="restore">
	<Message Text="TargetFramework=$(TargetFramework)" />
	<Message Text="TargetFrameworks=$(TargetFrameworks)" />
	<Message Text="ExcludeRestorePackageImports=$(ExcludeRestorePackageImports)" />
	<Message Text="PkgNuGet_CommandLine=$(PkgNuGet_CommandLine)" />
  </Target>
</Project>
```
And get this [output](https://github.com/NuGet/Home/files/8443894/verbose.output.txt)
Here is the generated [l10n.proj.nuget.g.props](https://github.com/NuGet/Home/files/8443875/l10n.proj.nuget.g.props.txt) file.
It looks like it is generating that file correctly for TargetFramework netstandard2.0.

Note that while TargetFramework is set properly during the parts of the build that happen during the restore, it is not set at the end when building the **ReportVariables** target. Therefore, the PkgNuGet_CommandLine variable is also not set.
The above is a stripped-down sample project file. The original is [here](https://github.com/sillsdev/libpalaso/blob/master/l10n/l10n.proj).
I tried it on my current laptop and my old one (where it used to work, but possibly with an older tool set), which has VS 2019 (msbuild engine version 16.11.0+0538acc04). The only significant change to the project file itself was a few days ago, in an attempt to fix problem: "The target "GetVersion" does not exist in the project". Looking at the generated l10n.proj.nuget.g.props file created with that version, it was apparently targeting net461 instead of netstandard2.0, so my guess is that the newer tool sets stopped paying attention to TargetFramework, in favor of TargetFrameworks. It seems that changing TargetFramework to TargetFrameworks and moving from the deprecated GitVersionTask to GitVersion.MsBuild worked for the developer who did it, but it is still not working for me.

**Comment by tombogle** [comment] 2022-04-07 17:50
Just got word from the dev who did the "fix" a few days ago that it is _not_ working for him now. So not sure what that means, but it kind of points away from it being something machine-dependent. I suppose it could mean that some file is getting created on a successful build that is causing a subsequent build to fail.

**Comment by dominoFire** [comment] 2022-04-07 17:57
`TargetFrameworks` property is intended to be used with more than one target framework. 

If you just want to use one target framework, `TargetFramework` should be set instead of `TargetFrameworks`

Could you try if using `TargetFramework` solves your problem?

**Comment by ermshiperete** [comment] 2022-04-07 17:59
My understanding is that it might be correct that `TargetFramework` is not defined when `ReportVariables` runs.

However, that leads to a different problem in that the `PkgNuGet_CommandLine` doesn't get set: if `TargetFrameworks` is defined the generated nuget.g.props file gets an additional condition:

```
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <PkgNuGet_CommandLine Condition=" '$(PkgNuGet_CommandLine)' == '' ">C:\Users\user\.nuget\packages\nuget.commandline\6.1.0</PkgNuGet_CommandLine>
  </PropertyGroup>
```

If `ReportVariables` target runs, `TargetFramework` isn't set and so `PkgNuGet_CommandLine`  doesn't get set. It seems to me that there should be a fallback in nuget.g.props if `TargetFramework` is not set:

```
  <PropertyGroup Condition=" ('$(TargetFramework)' == 'netstandard2.0' OR '$(TargetFramework)' == '') AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <PkgNuGet_CommandLine Condition=" '$(PkgNuGet_CommandLine)' == '' ">C:\Users\user\.nuget\packages\nuget.commandline\6.1.0</PkgNuGet_CommandLine>
  </PropertyGroup>
```

Even when specifying multiple frameworks in `TargetFrameworks`, when `ReportVariables` runs `TargetFramework` isn't set.

**Comment by ermshiperete** [comment] 2022-04-07 18:14
See also https://github.com/NuGet/Home/issues/11725

**Comment by ermshiperete** [comment] 2022-04-07 18:25
> `TargetFrameworks` property is intended to be used with more than one target framework.
> 
> If you just want to use one target framework, `TargetFramework` should be set instead of `TargetFrameworks`
> 
> Could you try if using `TargetFramework` solves your problem?

Using `TargetFramework` solves the problem that `PkgNuGet_CommandLine` isn't set, but it doesn't solve the problem that if a project uses `TargetFrameworks` (with multiple frameworks specified) `TargetFramework` still isn't set in `ReportVariables`.

**Comment by tombogle** [comment] 2022-04-07 19:20
Setting TargetFramework instead of TargetFrameworks results in this output:
ReportVariables:
  TargetFramework=netstandard2.0
  TargetFrameworks=net461
  ExcludeRestorePackageImports=
  PkgNuGet_CommandLine=
So PkgNuGet_CommandLine still isn't set, and TargetFrameworks is set incorrectly (I think that's the default).
If I make a similar change to the original (not stripped-down) [l10n.proj](https://github.com/sillsdev/libpalaso/blob/master/l10n/l10n.proj) file, the build fails because the target GetVersion does not exist because the generated l10n.proj.nuget.g.targets file only includes the project $(NuGetPackageRoot)gitversion.msbuild\5.9.0\build\GitVersion.MsBuild.targets if TargetFramework == net461.

**Comment by ermshiperete** [comment] 2022-04-07 20:12
@tombogle Do you have a `Directory.Build.props` file that sets defaults? That would explain why there's a value for `TargetFrameworks`. Try and explicitly add the line `<TargetFrameworks/>` to the l10n.proj file.

**Comment by tombogle** [comment] 2022-04-07 20:41
Yes, it looks like you added that on April 16, 2021. So I guess that's probably what actually broke this.

**Comment by tombogle** [comment] 2022-04-07 20:50
Adding the line <TargetFrameworks/> solves the problem. Maybe we should just remove that from Directory.Build.props (but then I guess maybe we'd have to re-add it to all the individual csproj files).

**Comment by ermshiperete** [comment] 2022-04-08 06:49
> Maybe we should just remove that from Directory.Build.props (but then I guess maybe we'd have to re-add it to all the individual csproj files).

The motivation behind the change was to have the target frameworks in one central place which makes it easier to change (and see what's used). If individual projects want to build for a subset they can override the value.

**Comment by tombogle** [comment] 2022-04-08 14:14
I'm not 100% sure that there isn't still something here that could be thought of as a "bug" since it is at least very difficult to see what is happening and why, but since we've found a solution, should we consider closing this?

**Comment by nkolev92** [comment] 2022-04-09 00:29
I think my comment in https://github.com/NuGet/Home/issues/11725#issuecomment-1093120677 applies here as well. 

The pkg variables are only going to be set in the inner build. 

The inner build is a function of calling the target in the right context. 
Anytime you call a target from the commandline, you're calling it in the outer build (if there's no TargetFrameworks, the inner build does not exist) so for multi targetted projects you'd need a target to delegate to the inner build one.

**Comment by dominoFire** [comment] 2022-04-09 22:24
From https://github.com/NuGet/Home/issues/11721#issuecomment-1093520522 ; I modified example to get `TargetFramework` property set in inner build.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.CommandLine" Version="6.1.0" GeneratePathProperty="true" />
  </ItemGroup>

  <Target Name="GetTargetFrameworksAsItems"
    Returns="@(TargetFrameworksAsItems)">
    <ItemGroup Condition=" '$(TargetFrameworks)' != '' ">
      <TargetFrameworksAsItems Include="$(TargetFrameworks.Split(';'))" />
    </ItemGroup>
  </Target>

  <Target Name="ReportVariables" AfterTargets="restore">
	<Message Text="TargetFramework=$(TargetFramework)" Importance="High" />
	<Message Text="TargetFrameworks=$(TargetFrameworks)" Importance="High" />
	<Message Text="ExcludeRestorePackageImports=$(ExcludeRestorePackageImports)" Importance="High" />
	<Message Text="PkgNuGet_CommandLine=$(PkgNuGet_CommandLine)" Importance="High" />
  </Target>

   <Target Name="RunReportVariables" DependsOnTargets="GetTargetFrameworksAsItems">
    <MSBuild
      Projects="$(MSBuildProjectFullPath)"
      Targets="ReportVariables"
      Properties="TargetFramework=%(TargetFrameworksAsItems.Identity);">
    </MSBuild>
  </Target>

</Project>
```

Output

```powershell
Build started 4/9/2022 3:24:36 PM.
Project "C:\Users\ferag\source\repos\issue11721\i10n.proj" on node 1 (RunReportVariables target(s)).
Project "C:\Users\ferag\source\repos\issue11721\i10n.proj" (1) is building "C:\Users\ferag\source\repos\issue11721\i10n.proj" (1:2) on node 1 (ReportVariables target(s)).
ReportVariables:
  TargetFramework=netstandard2.0
  TargetFrameworks=netstandard2.0;net6.0
  ExcludeRestorePackageImports=
  PkgNuGet_CommandLine=C:\Users\ferag\.nuget\packages\nuget.commandline\6.1.0
Done Building Project "C:\Users\ferag\source\repos\issue11721\i10n.proj" (ReportVariables target(s)).
Project "C:\Users\ferag\source\repos\issue11721\i10n.proj" (1) is building "C:\Users\ferag\source\repos\issue11721\i10n.proj" (1:3) on node 1 (ReportVariables target(s)).
ReportVariables:
  TargetFramework=net6.0
  TargetFrameworks=netstandard2.0;net6.0
  ExcludeRestorePackageImports=
  PkgNuGet_CommandLine=C:\Users\ferag\.nuget\packages\nuget.commandline\6.1.0
Done Building Project "C:\Users\ferag\source\repos\issue11721\i10n.proj" (ReportVariables target(s)).
Done Building Project "C:\Users\ferag\source\repos\issue11721\i10n.proj" (RunReportVariables target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.70
```

Closing this issue as not a bug in NuGet. If you have more questions, feel free to open more issues.

**Closed as completed** 2022-04-09 22:27 UTC
Labels: Product:VS.Client, Type:Bug, Product:NuGet.exe, Functionality:Restore, Product:dotnet.exe, Resolution:NotABug
