### ISSUE TITLE
Cache files should _not_ be written to %USERPROFILE% on Windows.

### ISSUE THREAD

**Issue by MicahZoltu** [NuGet/Home#5279] opened 2017-05-24 05:07 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

NuGet version (x.x.x.xxx): (don't know how to find this)

dotnet.exe --version (if appropriate): 2.0.0-preview1-005977

OS version (i.e. win10 v1607 (14393.321)): 10 Pro 10.0.15063 Build 15063

On Windows, NuGet should be a good citizen and follow Microsoft recommendations for folder locations. Currently it appears a folder called 
`.nuget` is created in `%USERPROFILE%`. `%USERPROFILE%` should NOT contain any files that the user doesn't actively put there themselves aside from the OS defaults. `%USERPROFILE%` is where the user puts files, e.g., via a save dialog box or because they explicitly set a path to point there. The correct location is either `%APPDATA%`, `%LOCALAPPDATA%`, `%PROGRAMDATA%` or `%PROGRAMFILES%` depending on what exactly you want to store.

* `%APPDATA%` should contain user-specific configuration files only and nothing large. This folder may be synced over a network or internet on login/logout so should remain small (Kilobytes).
* `%LOCALAPPDATA%` should contain user-specific files that will not follow the user across machines. This is a great place to put any caches that can be rebuilt when the user logs in to a new machine. It is also a good place to put user-specific files too large for `%APPDATA%`.
* `%PROGRAMDATA%` is machine wide and read/write by everyone. For security reasons, nothing executable should go here as anyone with access to the machine can write to it. This is a good place for machine-wide configuration files that can easily be deleted and re-configured if they become corrupt.
* `%PROGRAMFILES%` is machine wide and wirtable only by administrators. This is usually where executable files go and tend to only be put here on install, since that is usually when elevation occurs.
Note: Always use either the API mechanisms for getting the paths to these folders or the environment variables. All of these paths are configurable by end-users and one should not assume where they live relative to any other folders.

I believe Linux has a similar mechanism called XDG or something, and OSX has its own filesystem layout. All OS patterns and best practices should be respected, and I don't believe on any of them other than older versions of Linux is `$HOME` or `%USERPROFILE%` the right choice.

**Comment by MicahZoltu** [comment] 2017-05-24 05:09
Note: The current behavior is particularly atrocious as this folder is almost 1GB and %USERPROFILE% by default will roam across a network if roaming profiles are enabled.  This will effectively make login/logout take however long it takes to copy 1GB of files over the network when using a new machine or first installing NuGet.  In a lab setting this can be fatal to the network.

This data definitely _feels_ like data that should go in `%LOCALAPPDATA%`.

**Comment by MicahZoltu** [comment] 2017-05-24 05:10
Note, it appears there is a second copy of this folder in `%USERPROFILE%/.dotnet/NuGetFallbackFolder` that is of similar size.  This means I have 2GB of data being roamed over the network right now because of NuGet.  😢

**Comment by emgarten** [comment] 2017-05-24 18:52
Great examples @MicahZoltu!

Unfortunately this isn't as simple as just moving where restore writes the packages, all tools need to respect the changed location and many still have it hardcoded. We're working on fixing that and making the changed path available through project.assets.json, but already shipped tools will continue looking at the old path.

If you are only using the latest tools you can change the location by setting the env variable ``NUGET_PACKAGES``

Dupe of https://github.com/NuGet/Home/issues/2861

**Comment by mishra14** [comment] 2017-11-10 00:23
closing as dupe of #2861.

**Closed as completed by mishra14** 2017-11-10 00:23 UTC
Labels: Resolution:Duplicate
