### ISSUE TITLE
Package downgrade warnings for unreferenced package

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#4974] opened 2017-04-04 15:22 UTC
NuGet version: MSBuild 15.1 RTM 

While moving Roslyn to the new SDK + PackageReference we're running into the following restore warning:

```
c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): warning : Detected package dow ngrade: Microsoft.CodeAnalysis.CSharp from 1.3.0 to 1.0.0 \r [E:\code\roslyn\src\Compilers\CSharp\CscCore\CscCore.csproj]
c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): warning :  csc (>= 1.0.0) -> Mic rosoft.NETCore.App (>= 1.0.4) -> Microsoft.CodeAnalysis.CSharp (>= 1.3.0) \r [E:\code\roslyn\src\Compilers\CSharp\CscCore\CscCore.csproj]
c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): warning :  csc (>= 1.0.0) -> Mic rosoft.CodeAnalysis.CSharp (>= 1.0.0) [E:\code\roslyn\src\Compilers\CSharp\CscCore\CscCore.csproj]
```

The issue is that none of the projects involved here reference the Microsoft.CodeAnalysis.CSharp package: CodeAnalysis.csproj, CSharpCodeAnalysis.csproj or CscCore.csproj.  These projects are all either netstandard 1.3 or netcoreapp 1.0.  True the CSharpCodeAnalysis.csproj will produce the binaries eventually included the Microsoft.CodeAnalysis.CSharp package but that is much further along in our build.  This error is happening at restore time.

How can we be getting downgrade warnings here for a package that isn't even referenced?  

Repro steps:

- Clone https://github.com/jaredpar/roslyn
- Switch to branch repo-restore3 
- Run `msbuild /t:Restore src\Compilers\CSharp\CscCore\CscCore.csproj`

**Comment by davidfowl** [comment] 2017-05-02 03:44
That's a legitimate downgrade. It's one of the problems with an implicit package reference.

/cc @dsplaisted

**Comment by davidfowl** [comment] 2017-05-02 03:46
Ohh, I see what's happening, you have a project with the same name as the package? Can you make the version higher?

**Comment by jaredpar** [comment] 2017-05-02 04:23
We don't even set versions.  If we set a version it would be only to avoid this error.  Seems backwards.

**Comment by jaredpar** [comment] 2017-05-02 04:24
Ended up going a bit deeper on the problem in an SDK issue

https://github.com/dotnet/sdk/issues/1082

**Comment by nguerrera** [comment] 2017-05-19 13:39
Duplicate of #4620

**Closed as completed** 2017-10-17 19:40 UTC
Labels: Resolution:Duplicate
