### ISSUE TITLE
Merge net core tools "restore process" into nuget.tools.vsix

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3288] opened 2016-08-09 17:51 UTC
Restore happens on open project and changes to .csproj/project.json (for current or dependent projects)
Note -- need to solve the upgrade scenario .. Don't loose state from the package. Find UWP bug.

**Comment by rrelyea** [comment] 2016-09-21 15:22
Dupe of #3456

**Closed as completed by rrelyea** 2016-09-21 15:22 UTC
Labels: Resolution:Duplicate, Type:Feature, Functionality:Restore
