### ISSUE TITLE
[Test Failure]Can not creat PCL project after installing NuGet 4.3.0-beta1-2346 (Insertable)

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4741] opened 2017-03-03 09:46 UTC
**NuGet Version:** NuGet 4.3.0-beta1-2346 **(Insertable)**
**VS Version:** D15Rel 26228.00
**OS Version:** Windows 10 RS2_Release 15048.0.170228-1522

**Repro Steps:**
 New a Visual C#-> Class Library (Portable) project. (Check Targets as below screenshot)
 
![1](https://cloud.githubusercontent.com/assets/20632775/23546029/cf2517a0-0038-11e7-807c-19b34e8f14b9.png)

**Expected Result:**
The PCL project can be created successfully.

**Actual Result:**
The PCL project can’t be created with an error as below screenshot.
 
![2](https://cloud.githubusercontent.com/assets/20632775/23546124/21af9f68-0039-11e7-830e-b81b937e72d3.png)

**Notes:**
The issue not repro on **D15Rel 26228.00 (NuGet 4.0.0-rtm-2323)** and **D15Rel 26228.00 + NuGet 4.1.0-rtm-2343.**

**Comment by emgarten** [comment] 2017-03-03 20:23
It looks like this is incorrectly treating the project as a LegacyCSProjPackageReferenceProject

```xml
  <entry>
    <record>579</record>
    <time>2017/03/03 20:19:18.014</time>
    <type>Warning</type>
    <source>NuGet Package Manager</source>
    <description>Failed to emit project information for project &apos;ClassLibrary5&apos;. Exception:&#x000D;&#x000A;System.ArgumentException: Invalid framework version &apos;.0&apos;.&#x000D;&#x000A;   at NuGet.Frameworks.NuGetFramework.ParseFrameworkName(String frameworkName, IFrameworkNameProvider mappings)&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.EnvDTEProjectAdapter.get_TargetNuGetFramework()&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.GetPackageSpec()&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.&lt;&gt;c__DisplayClass36_0`1.&lt;&lt;RunOnUIThread&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.&lt;RunOnUIThread&gt;d__36`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.&lt;GetPackageSpecAsync&gt;d__30.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.&lt;GetInstalledPackagesAsync&gt;d__21.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at NuGet.PackageManagement.Telemetry.NuGetProjectTelemetryService.&lt;EmitNuGetProjectAsync&gt;d__5.MoveNext()</description>
  </entry>
```

**Comment by emgarten** [comment] 2017-03-03 20:51
Dupe of https://github.com/NuGet/Home/issues/4739

**Closed as completed by emgarten** 2017-03-03 20:51 UTC
