### ISSUE TITLE
[NuGet.VisualStudioExtension] MyGet feed packages show "download stream is null"

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#550] opened 2015-05-08 07:37 UTC
It can see the packages in the feed, it can view the updates and gather a list, but once I click update, it says the stream is null.

```
System.InvalidOperationException: Download stream is null
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__ea.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
```

**Comment by deepakaravindr** [comment] 2015-05-08 21:35
We believe this behavior indicates that the package source is suffering from inconsistency. We will try and improve the error message

//cc @maartenba @xavierdecoster

**Comment by maartenba** [comment] 2015-05-10 10:58
@GeertvanHorrik Is this something you can consistently reproduce? If so, what is the feed URL you are using?

**Comment by GeertvanHorrik** [comment] 2015-05-10 19:08
@maartenba Seems to work now (but very, very slow). Did you change anything in MyGet? I tried it on a lot of different projects last week, then it didn't work on any. It was the Gum.Ui package on our myget feed.

Updating a package on a single project takes about 60 seconds (timed it). Especially this takes a very long time:

```
Attempting to gather dependencies information for package 'Gum.Ui.1.0.0-unstable0427' with respect to project targeting '.NETFramework, Version=v4.0'
Attempting to resolve dependencies for package 'Gum.Ui.Apps.Ribbon.Fluent.1.0.0-unstable0427' with DependencyBehavior 'Lowest'
```

**Comment by xavierdecoster** [comment] 2015-05-11 07:50
@GeertvanHorrik that exception has a client-side stacktrace. Would be good if you could provide a simple repro of this. A fiddler trace showing the calls being made to the package sources would also help.

@deepakaravindr no protocol changes have been made to the MyGet endpoints lately. I see this exception is intentionally thrown in [`NuGet.PackageManagement.PackageDownloader`](https://github.com/NuGet/NuGet.PackageManagement/blob/dev/src/PackageManagement/PackageDownloader.cs#L46). MyGet currently does not expose v3 endpoints, so that means [`DownloadResourceV2.GetStream`](https://github.com/NuGet/NuGet3/blob/dev/src/NuGet.Protocol.Core.v2/DownloadResourceV2.cs#L70) somehow returns null.

**Comment by deepakaravindr** [comment] 2015-05-11 18:43
@xavierdecoster , PackageDownloader started throwing this error, when it is unable to download a package, which is expected to exist. We faced an issue in V2 nuget.org, where, the package was available on the feed, but, it was not available for download. I think MyGet, likely, had a similar issue
OR, it was just a network issue to get the package stream

**Comment by GeertvanHorrik** [comment] 2015-05-13 11:46
Just got this one on a NuGet.org feed (v2):

I was able to download Orc.Squirrel, but not Orc.Squirrel.Xaml.

```
Added package 'Orc.Squirrel.Xaml.1.0.0-unstable0043' to 'packages.config'
Package 'Orc.Squirrel.Xaml 1.0.0-unstable0044' does not exist in folder 'C:\Source\MyProject\src\..\lib'
System.InvalidOperationException: Download stream is null
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__ea.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
```

**Comment by naveensrinivasan** [comment] 2015-05-19 01:11
I am also getting similar error
```
Update-Package : Download stream is null
At line:1 char:1
+ Update-Package –reinstall Fody
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 ```

**Comment by xavierdecoster** [comment] 2015-05-20 17:18
@GeertvanHorrik @naveensrinivasan can you please provide some detailed instructions so we can repro this?

**Comment by GeertvanHorrik** [comment] 2015-05-20 17:19
Well, it depends on the server. If I just uploaded a package, it's not always directly available. Then we get this. Sometimes it takes a few minutes to solve, sometimes hours.

**Comment by Vannevelj** [comment] 2015-05-21 15:50
I just had this same issue as well. I released a new version of my NuGet package (which somehow only appears on NuGet V2) and saw the upgrade available in the NuGet window. When I tried to upgrade to this new version (from stable to pre-release), it threw this error. 

After this I just waited +- 5 minutes and it worked automatically.

**Comment by maartenba** [comment] 2015-05-22 13:16
On the MyGet side, we have done an update to reduce possible inconsitency. We're eager to hear if this improves the situation.

For the NuGet client side: @deepakaravindr @yishaigalatzer @xavierdecoster What would be the expected result in this case? (feed said package exists, download results in a 404) - should we retry the operation? Show a meaningful error message? Or leave as-is?

**Comment by deepakaravindr** [comment] 2015-05-22 13:48
I think client's messaging has been changed to say 'package stream is not available for download from <packagaesourceurl>'

**Comment by maartenba** [comment] 2015-05-22 13:52
So client-side is okay then? Let's wait for some feedback here then.

**Comment by RehanSaeed** [comment] 2015-05-26 16:03
Just received the following error. Published a new package 15 mins ago. Thought it might help you.

Install-Package Boilerplate.Web.Mvc5
Attempting to gather dependencies information for package 'Boilerplate.Web.Mvc5.1.0.0' with respect to project targeting '.NETFramework, Version=v4.5'
Attempting to resolve dependencies for package 'Boilerplate.Web.Mvc5.1.0.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Boilerplate.Web.Mvc5.1.0.0'
Resolved actions to install package 'Boilerplate.Web.Mvc5.1.0.0'
Install failed. Rolling back...
Package 'Boilerplate.Web.Mvc5 1.0.0' does not exist in project 'MvcBoilerplate'
Package 'Boilerplate.Web.Mvc5 1.0.0' does not exist in folder 'C:\Git\ASP.NET-MVC-Boilerplate\Source\packages'
Install-Package : Download stream is null
At line:1 char:1
+ Install-Package Boilerplate.Web.Mvc5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by maartenba** [comment] 2015-05-26 16:05
On which NuGet feed?

**Comment by RehanSaeed** [comment] 2015-05-26 17:01
Just used package manager console in visual studio using defaults.

**Comment by maartenba** [comment] 2015-05-26 19:31
This was caused by an issue on www.nuget.org. It should be resolved right now. Feel free to respond to this issue in case you are still seeing issues.

**Comment by yishaigalatzer** [comment] 2015-05-26 21:09
So we do have an eventual consistency issue in nuget.org where when you publish a package there is a brief period where it is available on search and not on the client.

I don't believe we need to improve anything on the client, and instead fix our server. This is tracked by https://github.com/NuGet/Home/issues/268

**Closed by yishaigalatzer** 2015-05-26 21:09 UTC
Labels: Priority:1, Type:Bug

**Comment by GeertvanHorrik** [comment] 2015-06-01 12:36
I hope it will be fixed soon, released a package (GitTools.Core) 4 hours ago:

```
System.InvalidOperationException: Download stream is null
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__ea.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
```

**Comment by maartenba** [comment] 2015-06-01 18:04
This issue has been resolved. @GeertvanHorrik the one you just posted is related to Related to #2432.
