### ISSUE TITLE
dotnet add package/restore can't be used on private repository on Windows

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6233] opened 2017-11-28 18:42 UTC
_From @NicolasDorier on November 28, 2017 13:48_

## Steps to reproduce

1. Create a feed on myget
2. 'nuget.exe setapikey <API_KEY> -Source https://www.myget.org/F/YOUR_FEED/api/v3/index.json'
3. Add https://www.myget.org/F/YOUR_FEED/api/v3/index.json to nuget config (either local or user scope)
4. Push Foo package using `dotnet nuget push  --source "https://www.myget.org/F/YOUR_FEED/api/v3/index.json"` working fine.
5. `dotnet add package Foo` Error 401

## Expected  behavior

Package Foo is added to the project.

## Actual behavior

Error 401, debugging with Fiddler indicates the API key is not used.

## Environment data

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25816-02
  Build    : c5006ff91f92e300b426eb26a9a0fa67192590b1
```

Workaround: Using Visual Studio to restore.

_Copied from original issue: dotnet/cli#8117_

**Comment by livarcocc** [comment] 2017-11-28 18:42
_From @enricosada on November 28, 2017 15:36_

doesnt work passing `--source` to `dotnet add`?

**Comment by livarcocc** [comment] 2017-11-28 18:42
_From @NicolasDorier on November 28, 2017 15:38_

nop, same result. I added the fact I also added the repo to the nuget sources.
dotnet is attempting to use the right repository in both case, it just does not attach the credentials.

**Comment by mishra14** [comment] 2017-11-28 23:13
According to https://github.com/NuGet/Home/issues/1851, this should be fine on windows. Needs investigation

**Comment by NicolasDorier** [comment] 2017-11-29 02:17
I am trying to make a better repro

**Comment by NicolasDorier** [comment] 2017-11-29 02:32
Here is full repro:

```
dotnet new nugetconfig
dotnet new classlib
dotnet pack
dotnet nuget push .\bin\Debug\*.nupkg --source "https://www.myget.org/F/metacosa/api/v2/package"
# info : Pushing 219250496.1.0.0.nupkg to 'https://www.myget.org/F/metacosa/api/v2/package'...
# info :   PUT https://www.myget.org/F/metacosa/api/v2/package/
# info :   Forbidden https://www.myget.org/F/metacosa/api/v2/package/ 1419ms

nuget setapikey "API_KEY" -Source "https://www.myget.org/F/metacosa/api/v2/package" -ConfigFile "nuget.config"

dotnet nuget push .\bin\Debug\*.nupkg --source "https://www.myget.org/F/metacosa/api/v2/package"
# info : Pushing 219250496.1.0.0.nupkg to 'https://www.myget.org/F/metacosa/api/v2/package'...
# info :   PUT https://www.myget.org/F/metacosa/api/v2/package/
# info :   Created https://www.myget.org/F/metacosa/api/v2/package/ 2275ms
# info : Your package was pushed.

mkdir OtherProj;cd OtherProj
dotnet new classlib
dotnet add package 219250496 --source "https://www.myget.org/F/metacosa/api/v2/package"

# log  : Restoring packages for C:\Users\NicolasDorier\AppData\Local\Temp\219250496\OtherProj\OtherProj.csproj...
# info :   GET https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496'
# info :   Unauthorized https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496' 1404ms
# log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/metacosa/api/v2/package/# # FindPackagesById()?id='219250496''.
# log  : Response status code does not indicate success: 401 (Unauthorized).
# info :   GET https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496'
# info :   Unauthorized https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496' 311ms
# log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/metacosa/api/v2/package/# # FindPackagesById()?id='219250496''.
# log  : Response status code does not indicate success: 401 (Unauthorized).
# info :   GET https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496'
# info :   Unauthorized https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496' 321ms
# error: Failed to retrieve information about '219250496' from remote source 'https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496''.
# error:   Response status code does not indicate success: 401 (Unauthorized).

dotnet add package 219250496 --source "https://www.myget.org/F/metacosa/api/v3/index.json"

# log  : Restoring packages for C:\Users\NicolasDorier\AppData\Local\Temp\219250496\OtherProj\OtherProj.csproj...
# error: Unable to load the service index for source https://www.myget.org/F/metacosa/api/v3/index.json.
# error:   Response status code does not indicate success: 401 (Unauthorized).

nuget setapikey "API_KEY" -Source "https://www.myget.org/F/YOUR_FEED/api/v3/index.json" -ConfigFile "..\nuget.config"

dotnet add package 219250496 --source "https://www.myget.org/F/metacosa/api/v3/index.json"

#   Writing C:\Users\NicolasDorier\AppData\Local\Temp\tmp4A7E.tmp
# info : Adding PackageReference for package '219250496' into project 'C:\Users\NicolasDorier\AppData\Local\Temp\219250496\OtherProj\OtherProj.csproj'.
# log  : Restoring packages for C:\Users\NicolasDorier\AppData\Local\Temp\219250496\OtherProj\OtherProj.csproj...
# error: Unable to load the service index for source https://www.myget.org/F/metacosa/api/v3/index.json.
# error:   Response status code does not indicate success: 401 (Unauthorized).
```

Tried to use v3 as well as v2 nuget feed. No success. `dotnet restore` has the same issue.
Note that nuget push works fine.

Using Visual Studio, it can restore the package successfully..

**Comment by NicolasDorier** [comment] 2017-11-29 02:51
Tried with both v2 and v3 nuget.

```
nuget sources add -Name "MyFeed" -Source "https://www.myget.org/F/metacosa/api/v2" -UserName "API_KEY" -Password "API_KEY" -ConfigFile "nuget.config" -StorePasswordInClearText
```

No success either.

**Comment by NicolasDorier** [comment] 2017-11-29 02:57
The only workaround at the moment is either to use Visual Studio, or in CI environment to use the "pre-authenticated V3 URL" which include your API_KEY. In the later case, we just can't use that inside the nuget.config as it would leak the key in the repo. :/

**Comment by evil-shrike** [comment] 2017-11-30 12:21
@NicolasDorier it works for me on Windows, our repository has auth (it's an Artifactory server).
You just need to use normal usernames and passwords, not apikeys I guess.
Nuget will ignore `--source` argument (see https://github.com/NuGet/Home/issues/6232) but if there's a source in nuget.config which returns your package nuget/dotnet should install it.
And it doesn't work on Linux for me (see https://github.com/NuGet/Home/issues/6221).

**Comment by NicolasDorier** [comment] 2017-11-30 13:41
@evil-shrike have you entered any different command line than I did above ? `--source` taken into account or not, the right repo is chosen. Just credentials are completely ignored.

**Comment by NicolasDorier** [comment] 2017-11-30 13:43
I have no username password, myget securing with apikey.

**Comment by evil-shrike** [comment] 2017-11-30 13:53
@NicolasDorier did you specify credentials in global NuGet.Config (in users' profile)? If not then it's cause I guess, as I remember nuget ignore credentials in local configs.

**Comment by enricosada** [comment] 2017-11-30 17:53
@NicolasDorier  can you try this? i use `-s` and `-k` to upload nupkg to myget

```
dotnet nuget push your.nupkg -s https://www.myget.org/F/cambridge-fsharp-workshop/api/v2/package -k fb4e7360-9c89-4a25-982f-64760ca089a5
```

you can probably also use an env var instead of `-k`, but `-k` should work.

as a note, mix `nuget.exe` and `dotnet nuget` is wrong ihmo, is not the same tool

**Comment by NicolasDorier** [comment] 2017-12-01 01:37
@evil-shrike yes, as you can see I ran `nuget setapikey` which does that. Tried both on local nuget config and global one, encrypted and unencrypted.

@enricosada nuget push always works fine. What does not is `dotnet add package` and `dotnet restore` if the dependency manually added.

**Comment by NicolasDorier** [comment] 2017-12-05 07:54
Please any idea ? This basically make `dotnet nuget` useless for private repositories... this should be well supported.

It is like you invented a car with state of the art engine, but somehow the ignition key is missing and nobody care. :(

**Comment by enricosada** [comment] 2017-12-05 12:20
@NicolasDorier why dont you just add a `nuget.config` and add set your feed there?

so `dotnet add` will search that, no need for `--source` etc.

```
dotnet new nugetconfig
```

and modify it to add your feed:
- remove the `<clear />`
- add the `<add key="something" value="path/to/feed" />`

**Comment by NicolasDorier** [comment] 2017-12-06 02:12
@enricosada because I did and it does not work, neither `dotnet restore` nor `dotnet add package`. 

Only `dotnet push` works fine.

**Comment by NicolasDorier** [comment] 2017-12-06 02:13
```
as a note, mix nuget.exe and dotnet nuget is wrong ihmo, is not the same tool
```

I am open to any alternative solution... I just want to access a private repository for adding package to my project. I don't even care about my credential being encrypted.

Please try my repro above, you can see for yourself.

**Comment by mishra14** [comment] 2017-12-07 04:49
This may be a dupe of https://github.com/NuGet/Home/issues/3664. 
@emgarten is going to investigate that issue.

**Comment by emgarten** [comment] 2018-01-03 01:14
Adding a source with credentials to a nuget.config file and then calling `dotnet add` works fine for me. The package is downloaded using those credentials. 

Note that the credentials must exist in nuget.config, the API key is only used for push. It is not a valid credential for downloading packages from a private feed.

All of this is working as expected on windows with dotnet CLI 2.0.5.

**Closed as completed by emgarten** 2018-01-03 01:14 UTC
Labels: Product:NuGet.exe, Resolution:NotRepro, Area:Authentication, Product:dotnet.exe

**Comment by NicolasDorier** [comment] 2018-01-03 12:17
@emgarten do not close that. Lot's of people have the issue, it is not a collective hallucination and people here took lot's of time to document what is going on... here is the repro on windows.

```
dotnet new nugetconfig
dotnet new classlib
dotnet pack
dotnet nuget push .\bin\Debug\*.nupkg --source "https://www.myget.org/F/metacosa/api/v2/package"
# info : Pushing 219250496.1.0.0.nupkg to 'https://www.myget.org/F/metacosa/api/v2/package'...
# info :   PUT https://www.myget.org/F/metacosa/api/v2/package/
# info :   Forbidden https://www.myget.org/F/metacosa/api/v2/package/ 1419ms

nuget setapikey "API_KEY" -Source "https://www.myget.org/F/metacosa/api/v2/package" -ConfigFile "nuget.config"

dotnet nuget push .\bin\Debug\*.nupkg --source "https://www.myget.org/F/metacosa/api/v2/package"
# info : Pushing 219250496.1.0.0.nupkg to 'https://www.myget.org/F/metacosa/api/v2/package'...
# info :   PUT https://www.myget.org/F/metacosa/api/v2/package/
# info :   Created https://www.myget.org/F/metacosa/api/v2/package/ 2275ms
# info : Your package was pushed.

mkdir OtherProj;cd OtherProj
dotnet new classlib
dotnet add package 219250496 --source "https://www.myget.org/F/metacosa/api/v2/package"

# log  : Restoring packages for C:\Users\NicolasDorier\AppData\Local\Temp\219250496\OtherProj\OtherProj.csproj...
# info :   GET https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496'
# info :   Unauthorized https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496' 1404ms
# log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/metacosa/api/v2/package/# # FindPackagesById()?id='219250496''.
# log  : Response status code does not indicate success: 401 (Unauthorized).
# info :   GET https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496'
# info :   Unauthorized https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496' 311ms
# log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/metacosa/api/v2/package/# # FindPackagesById()?id='219250496''.
# log  : Response status code does not indicate success: 401 (Unauthorized).
# info :   GET https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496'
# info :   Unauthorized https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496' 321ms
# error: Failed to retrieve information about '219250496' from remote source 'https://www.myget.org/F/metacosa/api/v2/package/FindPackagesById()?id='219250496''.
# error:   Response status code does not indicate success: 401 (Unauthorized).

dotnet add package 219250496 --source "https://www.myget.org/F/metacosa/api/v3/index.json"

# log  : Restoring packages for C:\Users\NicolasDorier\AppData\Local\Temp\219250496\OtherProj\OtherProj.csproj...
# error: Unable to load the service index for source https://www.myget.org/F/metacosa/api/v3/index.json.
# error:   Response status code does not indicate success: 401 (Unauthorized).

nuget setapikey "API_KEY" -Source "https://www.myget.org/F/YOUR_FEED/api/v3/index.json" -ConfigFile "..\nuget.config"

dotnet add package 219250496 --source "https://www.myget.org/F/metacosa/api/v3/index.json"

#   Writing C:\Users\NicolasDorier\AppData\Local\Temp\tmp4A7E.tmp
# info : Adding PackageReference for package '219250496' into project 'C:\Users\NicolasDorier\AppData\Local\Temp\219250496\OtherProj\OtherProj.csproj'.
# log  : Restoring packages for C:\Users\NicolasDorier\AppData\Local\Temp\219250496\OtherProj\OtherProj.csproj...
# error: Unable to load the service index for source https://www.myget.org/F/metacosa/api/v3/index.json.
# error:   Response status code does not indicate success: 401 (Unauthorized).
```
 Try exact same step on your own private repo.
I can give you the creds to this server if you want...

Also worth noting `dotnet push` works but not `dotnet restore`.

**Comment by emgarten** [comment] 2018-01-03 19:13
@NicolasDorier I've responded on https://github.com/NuGet/Home/issues/3664

**Comment by wertzui** [comment] 2018-04-17 12:07
I had the same problem and for me it was that in my NuGet.config in `%appdata%\NuGet\` had `packageSourceCredentials` that would overwrite the ones in the NuGet.config in the project directory.

Once I removed the credentials, the oney from the NuGet.config in my project directory where used.

However I would expect credentials specified in the NuGet.config inside the project folder to overwrite the ones in AppData and not the other way around.

**Comment by lucasolv100** [comment] 2018-12-05 09:52
> dotnet new nugetconfig

This command saved me, after 3 days looking for a solution whre my dotnet add package CLI command were not working at all in any project, seems that it's related with Nuget Path configuration, Thanks!
