### ISSUE TITLE
Restore is case sensitive in weird ways

### ISSUE THREAD

**Issue by blackdwarf** [NuGet/Home#2901] opened 2016-06-03 22:37 UTC
When restoring projects that have P2P references and a meta-package that is of a wrong case, weird errors crop up during restore. The cause is that the library has a wrong case of the metapackage for `NETStandard.Library` (`NetStandard.Library`). 
## Repro

``` console
git clone https://github.com/bleroy/paynoattentiontothis/
git checkout 55771a3
cd GoldenCLI/test/TestLibrary
dotnet restore
```
## Expected result

Restore succeeds.
## Actual result

Restore fails with a lot of errors like the following:

``` console
Unable to satisfy conflicting requests for 'System.Security.Cryptography.Cng': System.Security.Cryptography.Cng (>= 4.1.0-rc2-24027) (via package/System.Security.Cryptography.X509Certificates 4.1.0-rc2-24027), System.Security.Cryptography.Cng (>= 4.1.0-rc2-24027) (via package/System.Security.Cryptography.X509Certificates 4.1.0-rc2-24027), System.Security.Cryptography.Cng (>= 4.1.0-rc2-24027) (via package/System.Security.Cryptography.X509Certificates 4.1.0-rc2-24027), System.Security.Cryptography.Cng (>= 4.1.0-rc2-24027) (via package/System.Security.Cryptography.X509Certificates 4.1.0-rc2-24027)
    Unable to satisfy conflicting requests for 'System.Security.Cryptography.Csp': System.Security.Cryptography.Csp (>= 4.0.0-rc2-24027) (via package/System.Security.Cryptography.X509Certificates 4.1.0-rc2-24027), System.Security.Cryptography.Csp (>= 4.0.0-rc2-24027) (via package/System.Security.Cryptography.X509Certificates 4.1.0-rc2-24027), System.Security.Cryptography.Csp (>= 4.0.0-rc2-24027) (via package/System.Security.Cryptography.X509Certificates 4.1.0-rc2-24027), System.Security.Cryptography.Csp (>= 4.0.0-rc2-24027) (via package/System.Security.Cryptography.X509Certificates 4.1.0-rc2-24027)
    Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets': Microsoft.NETCore.Targets (>= 1.0.1-rc2-24027) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24027), Microsoft.NETCore.Targets (>= 1.0.1-rc2-24027) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24027), Microsoft.NETCore.Targets (>= 1.0.1-rc2-24027) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24027), Microsoft.NETCore.Targets (>= 1.0.1-rc2-24027) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24027)
```

/cc @yishaigalatzer @emgarten @bleroy @cartermp

**Comment by yishaigalatzer** [comment] 2016-06-03 22:39
CC @joelverhagen  should this be fixed by lowercase paths feature you are working on?

**Comment by joelverhagen** [comment] 2016-06-04 00:41
I've reproduced this even with my case insensitive changes (which mostly focused on the file system). I've also trimmed down the repro to a minimal graph, as it seems to be a restore graph issue:
[simple.zip](https://github.com/NuGet/Home/files/298602/simple.zip)

**Closed as completed** 2016-06-06 20:31 UTC
