### ISSUE TITLE
Null Reference Exception Thrown When Attempting Package Update in Existing Project

### ISSUE THREAD

**Issue by txwizard** [NuGet/Home#10422] opened 2021-01-03 01:13 UTC
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet Package Manager in Visual Studio 2019 Community
NuGet version (x.x.x.xxx):
5.8.0.6930
dotnet.exe --version (if appropriate):
Not Applicable
VS version (if appropriate):
Microsoft Visual Studio Community 2019, Version16.8.3
OS version (i.e. win10 v1607 (14393.321)):
Microsoft Windows Professional [Version 10.0.19042.685]
Worked before? If so, with which NuGet version:
Yes, many times, with NuGet Version: 4.9.4.5839
## Detailed repro steps so we can see the same problem

1. Select Manage NuGet Packages from the main Project menu (off the ribbon) or the Project context menu in the Solution Explorer.

2. Click the Updates tab, which shows 8 packages that are in need of an update.
3. Click Select All.
4. Click Update.
5. Observe exception report displayed in both Errors and Output windows. Below is from the Output Window.

System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PackageManagement.UI.UIActionEngine.<>c.<ResolveActionsForUpdateAsync>b__9_0(PackageIdentity package)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at NuGet.PackageManagement.UI.UIActionEngine.<ResolveActionsForUpdateAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass11_0.<<PerformActionImplAsync>b__0>d.MoveNext()
Time Elapsed: 00:00:00.0148382
========== Finished ==========

...

## Other suggested things
I verified that neither packages.config, nor the packages directory, nor anything within it, is marked as read only.  Though packages.config was, reversing that error had no effect on the outcome.

FWIW, I successfully executed a NuGet push from a command prompt window yesterday afternoon to update a dependent library that got missed when I updated everything (9 packages) in my WizardWrx .NET API library on New Year's Eve. The oversight came to my attention when I installed most of those libraries (6 of the 9) into a new project that I started yesterday. Both the update and the install (pull) ran without issue using nuget.exe 5.8.0.6930, which runs from directory C:\bin, which is in my PATH list.

All projects are "legacy" packages, since I have yet to see the benefit of converting to the newer, supposedly improved package format.

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)
I would if I could, but, alas, the NuGet Package Manager doesn't appear to have such an option.

### Sample Project
[FixCSV_20210102_185208.zip](https://github.com/NuGet/Home/files/5761060/FixCSV_20210102_185208.zip)

Very helpful if you can zip a project and paste into this issue!
It's even small; there is one class (Program.cs), and it's a character-mode program.

**Comment by jebriede** [comment] 2021-01-11 20:15
Closing as duplicate of https://github.com/NuGet/Home/issues/9882

**Closed as completed by jebriede** 2021-01-11 20:15 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug, Functionality:VisualStudioUI, Functionality:Update
