### ISSUE TITLE
Fix NuGet.Commands project dependencies

### ISSUE THREAD

**Issue by bdovaz** [NuGet/Home#7666] opened 2018-12-28 14:55 UTC
Why don't you depend directly on nuget packages? Right now looking at namespaces it looks like you're using older versions:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/NuGet.Commands.csproj#L24

https://www.nuget.org/packages/Microsoft.Extensions.FileSystemGlobbing/2.2.0
https://www.nuget.org/packages/Microsoft.Extensions.FileProviders.Abstractions/2.2.0
https://www.nuget.org/packages/Microsoft.Extensions.Primitives/2.2.0

I have been investigating it. In order to compile you need to:
- Remove that "ItemGroup" in *.csproj.
- Add that 3 nuget packages.
- Replace "using Microsoft.AspNet" with "using Microsoft.Extensions".
- Refactor in "VirtualFileProvider.cs" two lines:
1. "EnumerableDirectoryContents" class reference that now exists in another package but it's internal: https://github.com/aspnet/Extensions/blob/2.2.0/src/FileProviders/Embedded/src/EnumerableDirectoryContents.cs#L10
2. Change "NoopChangeToken.Singleton" to "NullChangeToken.Singleton". Source: https://github.com/aspnet/FileSystem/pull/195/files#diff-93c67d1ef9ee4d6748ba7faddbef3c8d

**Comment by nkolev92** [comment] 2018-12-28 18:23
Not sure what the reasoning behind compiling the source was when this was added, but it's not a "straightforward" change, as we have to consider whether other components within NuGet's ship vehicles have dependencies on the above assemblies.

**Comment by nkolev92** [comment] 2019-01-03 18:25
Duplicate of https://github.com/NuGet/Home/issues/2345

**Closed as completed by nkolev92** 2019-01-03 18:25 UTC
Labels: Resolution:Duplicate, Priority:3, Type:Engineering
