### ISSUE TITLE
Nuget.exe pack -Exclude is documented but not supported

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2284] opened 2016-03-10 00:26 UTC
Pack documentation here: https://docs.nuget.org/consume/command-line-reference#pack-command
specifies Exclude as an option, but it's not supported in code.

**Comment by yishaigalatzer** [comment] 2016-03-10 01:15
Looks like a duplicate of https://github.com/NuGet/Home/issues/2169

**Comment by toddm** [comment] 2016-03-24 23:15
Fixed in Dev.

**Closed as completed by toddm** 2016-03-24 23:15 UTC
Labels: Type:Bug, Product:NuGet.exe, Functionality:Pack
