### ISSUE TITLE
Update packages from specific source only doesn't work

### ISSUE THREAD

**Issue by Kamarey** [NuGet/Home#1670] opened 2015-11-02 06:23 UTC
I'm trying to update all packages in a solution from our company's local package repository. I [found](https://docs.nuget.org/consume/Package-Manager-Console-PowerShell-Reference#update-package) that there is the Source argument for this purpose:
   Update-Package -Source SomeSourceName

But when running this command (in Package Manager Console), it updates all packages from all sources, not just the one I specified by the Source parameter.

NuGet Version: 3.2.0.10516

**Comment by yishaigalatzer** [comment] 2015-11-02 19:59
@johnataylor - Can you reply here?

**Comment by johnataylor** [comment] 2015-11-18 17:18
This is a known issue and we will fix this in 3.4. In the meantime the work around is to enable/disable sources. This is inconvenient but should work.

**Comment by wolfpackt99** [comment] 2015-11-24 20:41
wouldn't the work-around not work if you disable the main nuget feed.  Is it needed to be on for dependent assemblies?

**Comment by yishaigalatzer** [comment] 2016-03-12 03:04
@wolfpackt99 you are right, the other work around is to pass the id flags to the command or to use the UI in 3.3 to multi select packages and update them

**Comment by jainaashish** [comment] 2016-04-27 21:03
@Kamarey Can you confirm if it updates all the dependent packages (dependent packages could be there as target packages as well) or it goes and update all the packages irrespective of dependent or target?
And also can you try to repro this with latest nuget version 3.4.3? If you're still able to repro then please share steps or small repro project will be great.

**Comment by jainaashish** [comment] 2016-05-18 00:00
@johnataylor Hey John, I'm not able to reproduce this issue, do you remember how to reproduce this? I can see it always update packages from selected source and dependencies from all the available sources.

**Comment by rrelyea** [comment] 2016-08-26 16:51
@Kamarey - we are interested in investigating. is this still an issue?
Can you help us reproduce the problem?

**Comment by Kamarey** [comment] 2016-08-26 20:13
I'm in vocation right now. Will try to reproduce it in 2 weeks

**Comment by Kamarey** [comment] 2016-09-01 06:30
Looks it's ok now. The v3.5.0-rc1 is working, while the 3.4.4 doens't.

To reproduce it do next:
1. Make a project which use packages from multiple sources
2. Try to update packages from some specific source:
    nuget update ".../myproject.csproj" -source MySource

In 3.4.4 I get this error:
_Package 'AutoMapper' is not found in the following primary source(s): 'http://MySourceServer/nuget'. Please verify all your online package sources are available (OR) package id, version are specified correctly._

Here the nuget tries to update the AutoMapper package, while I want it to update only packages from the MySource source

**Comment by migueldesousa** [comment] 2016-09-01 15:00
I'm having the same problem, when running nuget update with private source, nuget gives error of not finding the package xy.

Is there a way to ignore nonexisting packages?

**Comment by jainaashish** [comment] 2016-09-08 16:13
@migueldesousa are you seeing this issue with 3.5.0-rc1 (https://dist.nuget.org/visualstudio-2015-vsix/v3.5.0-rc1/NuGet.Tools.vsix ) release as well?

**Comment by jainaashish** [comment] 2016-09-26 19:16
This has already been fixed in 3.5.0-rc1 with #1013 So closing this issue.

**Closed as completed by jainaashish** 2016-09-26 19:16 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Priority:2, Type:Bug, Functionality:Update

**Comment by bkwdesign** [comment] 2019-01-15 18:34
I'm in Visual Studio 2017 - 15.9.4
I got this error today trying to pull from my private DevOps NuGet feed
(CONTEXT: the first time I called `Install-Package` everything worked, but, my NuGet was not compiled right, so, I re-published the NuGet pkg, and when I tried to update my project that was consuming the pkg, that's when I got the failure)

Switching my Package Source to "all" alleviated the problem.
