### ISSUE TITLE
Fix grammatical mistake in restore error

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4112] opened 2016-12-15 00:49 UTC
From internal bugs 296539, 343249
https://github.com/NuGet/NuGet.Client/blob/2057ef8e5d9f9219d25d0fd2e29af36755556607/src/NuGet.Clients/PackageManagement.VisualStudio/Strings.resx#L181

"DependAnt" is incorrect AFAI can tell - American English uses "dependent" and not "dependant", and latter when used, is only for a noun not an adjective.
See: http://english.stackexchange.com/questions/11310/what-is-the-correct-spelling-of-dependent-which-preposition-should-follow-it
 
Spelling should be "dependEnt".

**Comment by emgarten** [comment] 2016-12-16 21:18
dupe of https://github.com/NuGet/Home/issues/4018

**Closed as completed by emgarten** 2016-12-16 21:18 UTC
Labels: Resolution:Duplicate, Type:Bug, Area:ErrorHandling, Functionality:Restore
