### ISSUE TITLE
Analyzer packages no longer added with PrivateAssets

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5816] opened 2017-08-29 04:32 UTC
_From @tillig on August 21, 2017 19:35_

Prior to VS 15.3 when you'd add a reference to a Roslyn analyzer package you'd get a reference like this:

```xml
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.3.0-beta1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
```

With the `PrivateAssets` node the analyzer wouldn't be seen as a dependency when packaging your project.

As of 15.3.1, when adding a Roslyn analyzer package reference you no longer get the `PrivateAssets` node.

```xml
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.3.0-beta1" />
```

This ends up including the analyzer as part of the packaging process and you get an incorrect dependency.

Repro is easy - create a new project in VS 15.3.1 targeting a netstandard TFM and add a reference to Microsoft.CodeAnalysis.Analyzers. Save it and look at the .csproj.

_Copied from original issue: dotnet/project-system#2725_

**Comment by drieseng** [comment] 2017-08-29 04:44
In what way is such a 'private asset' reference different from a development dependency?

**Comment by rohit21agrawal** [comment] 2017-08-29 17:07
@tillig @davkean how is the package being added? As far as I am aware, we have never added PrivateAssets=all automatically even for packages with developmentDependency set to true. Here is the bug for that : https://github.com/NuGet/Home/issues/4125

@emgarten please correct me if I am wrong.

**Comment by emgarten** [comment] 2017-08-29 19:06
packages.config automatically set this, but PackageReference/project.json has never done this.

**Comment by rrelyea** [comment] 2017-09-05 20:35
Resolving this as a dupe of #4125, which is now in the backlog as P1 issue. Thanks for the report.

**Closed as completed by rrelyea** 2017-09-05 20:35 UTC
Labels: Resolution:Duplicate, Functionality:Restore, Functionality:Install
