### ISSUE TITLE
`nuget update solution.sln` considers all packages.config instead of only the solution project's

### ISSUE THREAD

**Issue by daniel-v** [NuGet/Home#7029] opened 2018-06-15 12:19 UTC
Please read the following information before posting the issue.

## Details about Problem
*Product:* `nuget.exe`
*Version:* `NuGet Version: 4.6.2.5055`
*OS*: Irrelevant

## Repro:

1. Create a solution
2. Add 2 projects to solution, both with `packages.config`
3. Remove one of the projects from solution
4. issue `nuget update myproject.sln`
5. Realize that nuget updates all projects

## Cause of the isssue:

Relevant code https://github.com/NuGet/NuGet.Client/blob/release-4.6.1-rtm/src/NuGet.Clients/NuGet.CommandLine/Commands/UpdateCommand.cs#L121

```csharp
            string[] packagesConfigFiles = Directory.GetFiles(
                solutionDir, "*.config", SearchOption.AllDirectories);

            var projects = packagesConfigFiles.Where(s => Path.GetFileName(s).StartsWith("packages.", StringComparison.OrdinalIgnoreCase))
                                              .Select(s => GetProject(s, projectContext))
                                              .Where(p => p != null)
                                              .Distinct()
                                              .ToList();
```

This piece of code considers every directory with a `packages.config` as a project of the solution which is _incorrect_ in many cases.
Also, the input file is used only to determine the base path under which packages.configs are searched.

### Expected functionality

Cross reference solution file to determine which projects actually belong to the solution file. Maybe `Microsoft.Build.Construction.SolutionFile` could be of help here.

### Why do I want to do it

There are some large solutions that share some of the directories/solutions. They, however have to be updated with different nuget configs.

**Comment by nkolev92** [comment] 2019-10-01 23:32
Duplicate of https://github.com/NuGet/Home/issues/2747

**Closed as completed by nkolev92** 2019-10-01 23:32 UTC
Labels: Resolution:Duplicate, Priority:3, Type:Bug, Product:NuGet.exe, Functionality:Update
