### ISSUE TITLE
Restore global.json functionality in VS2017

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7705] opened 2019-01-17 23:07 UTC
Migrated from <a href="http://visualstudio.uservoice.com/forums/121579/suggestions/19071868">Visual Studio IDE UserVoice forum</a> <br><br> Before the switch from project.json back to .csproj files, I was able to use global.json in order to specify local source code for a NuGet package I referenced.  This made it incredibly easy to debug against the source code, and also make code changes on the fly to my dependencies that are in other packages and repositories.  

With the new csproj format, I am forced to make changes to my package and push them up to our registry, or package and push to a local nuget source.  This makes for an incredibly clunky experience when NuGet is your primary method of sharing code between repositories.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/351527/restore-globaljson-functionality-in-vs2017.html
VSTS ticketId: 700549_
_These are the original issue comments:_

Fiona Niu[MSFT] on 10/15/2018, 01:25 AM (94 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about five business days on our next steps. </p>

**Comment by jainaashish** [comment] 2019-01-18 00:35
dupe of https://github.com/dotnet/cli/issues/4997

**Closed as completed by jainaashish** 2019-01-18 00:35 UTC
Labels: Resolution:Duplicate
