### ISSUE TITLE
Nuget - Show the actual assembly version

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8683] opened 2019-10-10 18:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/768974/nuget-show-the-actual-assembly-version.html)._

---
Just spent a pretty big chunk of time trying to solve an issue where Swashbuckle is dependent on a specific version of System.ComponentModel.Annotations - 4.2.0.0.  

Have eventually, after much trial and error, discovered that Nuget package version 4.4.1 contains assembly version 4.2.0.0, as required by Swashbuckle.

Dependency issues aside, it would be extremely helpful if you could see the full actual assembly version details when viewing each Nuget package, big time saver in situations like this.

---
#### Jane Wu [MSFT] on 10/10/2019, 00:14 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by kartheekp-ms** [comment] 2019-10-11 00:06
I have manually traversed the dependency graph of [Swashbuckle](https://www.nuget.org/packages/Swashbuckle/) 5.6.0 version and didn't find dependency on System.ComponentModel.Annotations package version 4.4.1.I have sent a note to package author to understand the reason why [`System.ComponentModel.Annotations` package version 4.4.1](https://www.nuget.org/packages/System.ComponentModel.Annotations/4.4.1) is referring to 4.2.0 version of assembly. I will update this issue once I receive the feedback.

Let us know more about your ask so that we can improve the experience in the VS. For e.g.
- [Packages.Config or PackageReference style project](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
- Would you like to see assembly metadata such as version in the Properties window for all the assemblies referred by dependent nuget packages in VS Solution Explorer - References node?

**Comment by terrajobst** [comment] 2019-10-11 01:02
This is by-design because in the past assembly versions were important to get the correct compatibility relationships with Portable Class Libraries (PCLs) and .NET Standard 1.x. Moving forward this is likely a less important issue.

However, in principle NuGet (in UI or otherwise) shouldn't make an assumption that package version, assembly version, and file version are the same thing. They can be, but they often aren't.

**Comment by nkolev92** [comment] 2019-12-31 02:24
Closing this as not a bug. 
The relationship between package versions and assembly versions of dll inside the package is not something NuGet observes.

**Closed as completed by nkolev92** 2019-12-31 02:24 UTC
Labels: Product:VS.Client, Resolution:NotABug
