### ISSUE TITLE
nuget version *

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8306] opened 2019-07-06 12:41 UTC
<p>VSF_TYPE_MARKDOWNHI</p><p>I have started using the 
&lt;Version&gt;1.*&lt;/Version&gt; i.e. * option</p><p>For our internal packages. And this is a really really great option. Thanks!</p><p>The only issue, it shows in the updates for the Visual Studio IDE. Infact a V1.* thinks that the V1.0.0 of the package is installed in the IDE.
Sholdn't the IDE see the &quot;*&quot; in the version and understand it is the latest.?</p><p>Or should there be a checkbox that allows to enable / disable nugets with wildard  options?</p><p>Thanks.-.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/616851/nuget-version.html
VSTS ticketId: 935378_
_These are the original issue comments:_

Visual Studio Feedback System on 24/06/2019, 00:37 AM (12 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Andy Zivkovic [MSFT] on 05/07/2019, 04:33 PM (13 hours ago): <markdown><p>With projects using <code>PackageReference</code>, NuGet is run on every build. In order to avoid a slow restore on every build, NuGet detects when restore input changes (which packages are requested, package versions). When the input is the same, it doesn’t actually restore, it keeps the previous restore’s results. Therefore, if a new version of a package was released after the last time your project went through a full restore, you won’t be using the latest version of the package any longer. You can force a full restore by using the “force” argument with either the nuget or dotnet cli, or simply deleting your project’s <code>obj/project.assets.json</code> file.</p>
<p>Finally, Visual Studio’s Package Manager UI shows the version actually installed (resolved version), rather than the requested version.</p>
<p>Does this answer your question?</p>
</markdown>
Rik Svendsen Rose on 05/07/2019, 09:17 PM (8 hours ago): <p>HI</p><p>The VS package manager shows the minimum version, not the installed version when you use * wildcards in the csproj.</p><p>This is my point, it should maybe indicate that a wildcard is in use, to insure other developers done update manually by mistake...</p>

_These are the original issue solutions:_
(no solutions)

**Comment by zivkan** [comment] 2019-07-06 12:49
To summarise, when using wildcards, VS always shows the package as having an update available, even though the latest version is already resolved, and the UI makes it look like version v0.0.0 is installed for a `*` wildcard, or version v1.0.0 for a `1.*` wildcard.

![image](https://user-images.githubusercontent.com/5030577/60756410-bb2fa380-9fb1-11e9-9a07-1348bbb6f6fe.png)

The suggestion is that we improve this, for example show `*` instead of `v0.0.0` in the image above.

**Comment by nkolev92** [comment] 2019-07-08 19:06
Duplicate of https://github.com/NuGet/Home/issues/3101.

**Closed as completed by nkolev92** 2019-07-08 19:06 UTC
Labels: Product:VS.Client, Type:Bug, Functionality:VisualStudioUI, Style:PackageReference
