### ISSUE TITLE
Null pointer when using RestoreUseStaticGraphEvaluation and explicit TargetFramework

### ISSUE THREAD

**Issue by nojaf** [NuGet/Home#13046] opened 2023-11-28 12:49 UTC
### NuGet Product Used

dotnet.exe

### Product Version

dotnet SDK 8.0.100

### Worked before?

I don't think so

### Impact

Other

### Repro Steps & Context

1. Clone https://github.com/fsprojects/fantomas
2. Run `dotnet fsi .\build.fsx -- -p Init`
3. Restore project `dotnet restore ./src/Fantomas.FCS/Fantomas.FCS.fsproj /p:TargetFramework=netstandard2.0 /p:RestoreUseStaticGraphEvaluation=True --force`

```
  Determining projects to restore...
C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): error : Object reference not set to an instance of an object. [C:\Users\nojaf\Projects\fantomas\src\Fantomas.FCS\Fantomas.FCS.fsproj]
C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.GetPackageSpec(IMSBuildProject project, IReadOnlyDictionary`2 allInnerNodes) [C:\Users\nojaf\Projects\fantomas\src\Fan
tomas.FCS\Fantomas.FCS.fsproj]
C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.<>c__DisplayClass35_0.<GetDependencyGraphSpec>b__0(ProjectWithInnerNodes project) [C:\Users\nojaf\Projects\fantomas\sr
c\Fantomas.FCS\Fantomas.FCS.fsproj]
C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): error :    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) [C
:\Users\nojaf\Projects\fantomas\src\Fantomas.FCS\Fantomas.FCS.fsproj]
C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): error : --- End of stack trace from previous location --- [C:\Users\nojaf\Projects\fantomas\src\Fantomas.FCS\Fantomas.FCS.fsproj]
C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): error :    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) [C
:\Users\nojaf\Projects\fantomas\src\Fantomas.FCS\Fantomas.FCS.fsproj]
C:\Program Files\dotnet\sdk\8.0.100\NuGet.RestoreEx.targets(19,5): error :    at System.Threading.Tasks.TaskReplicator.Replica.Execute() [C:\Users\nojaf\Projects\fantomas\src\Fantomas.FCS\Fantomas.FCS.fsproj]
```

When restoring without the explicit `/p:TargetFramework=netstandard2.0` this works.
Or when using `/p:TargetFramework=netstandard2.0 /p:RestoreUseStaticGraphEvaluation=False` it will also work.

**Comment by jeffkl** [comment] 2023-11-28 17:26
Duplicate of https://github.com/NuGet/Home/issues/11761.  See [this comment](https://github.com/NuGet/Home/issues/11761#issuecomment-1105218996) for a workaround

**Closed as not planned by jeffkl** 2023-11-28 17:26 UTC
Labels: Resolution:Duplicate, Type:Bug
