### ISSUE TITLE
LightweightSolutionLoad - gives file not found during restore

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4544] opened 2017-02-09 12:12 UTC
Find repro by using clues in comments & engaging with customer.
vsfeedback 784971 | https://developercommunity.visualstudio.com/content/problem/16681/nuget-restore-fails-with-file-not-found.html

All packages are already installed and there is nothing to restore. Time Elapsed: 00:00:00.0047847 ========== Finished ==========

Error occurred while restoring NuGet packages: File not found

Which is false. There are zero nuget packages on disk for this solution. The error message "File not found" offers no help in figuring out what is missing.

Follow up comment said: Disabling lightweight solution load fixed this issue.

**Comment by zhili1208** [comment] 2017-02-09 22:37
this is a dupe of https://github.com/NuGet/Home/issues/4533

**Closed as completed by zhili1208** 2017-02-09 22:37 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug, Functionality:Restore
