### ISSUE TITLE
[Signing] Package signing failed with an error: "Key does not exist" after nuget signing a package with certificate comes from CurrentUser certificate store

### ISSUE THREAD

**Issue by SueSu01** [NuGet/Home#13111] opened 2023-12-27 09:51 UTC
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Client Dev\6.9.0.67

### Worked before?

It worked in nuget client Dev\6.8.0.101 since we used the "CreateTestCertificate.ps1" file to create certificate but we use "MakeTestCert.csproj" this time.

### Impact

It's more difficult to complete my work

### Repro Steps & Context

**Repro steps:**

1.Patch dotnet SDK: [Patch dotnet SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={8a3c6685-1661-47f4-8807-b765ca62aea1}&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703)
2.Add NuGet.exe path into System variables and create a package with command "nuget pack <PackageName>.csproj" for testing.
3. Go to the patchedSDK folder and create a new test certificate: 
`.\dotnet run --project .\Entropy\MakeTestCert\MakeTestCert.csproj --framework net7.0` 
4. Where _CertificateFilePath_ is the file path to the created certificate (in step3) .cer or .pem file, add trust for the certificate:
 `.\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath> `
5. In another "Developer Command Prompt", cd to the path of "NuGet.exe" and sign a package, where _Fingerprint_ is the Fingerprint (SHA-1) from step 3:
`NuGet.exe sign <PackageFilePath> -CertificateFingerprint <Fingerprint> -CertificateStoreName Root`
6.  Verify the correct certificate was used and no errors or warnings (except for warning NU3002 if you didn't use: "-Timestamper").

**Expected:**
Package signing is successful and no error or warnings (except for warning NU3002 if you didn't use: "-Timestamper").

**Actual:**
Package signing failed with an error: "Key does not exist" after nuget signing a package with certificate comes from CurrentUser certificate store as below screenshot
![image](https://github.com/NuGet/Home/assets/149561645/58a865b2-4676-4361-8d54-0be92af59096)

**Note:**   
The repro rate is 100%.

**Comment by martinrrm** [comment] 2024-01-02 06:48
I can reproduce this behavior

**Comment by jeffkl** [comment] 2024-01-18 19:37
Team Triage: @dtivel would you mind looking into this?  It seems that it was working before with `CreateTestCertificate.ps1` but is no longer working.

**Comment by dtivel** [comment] 2024-01-19 20:58
@SueSu01, there are 2 distinct user scenarios here:  signing and verifying.  Each scenario has its own requirements.  When testing, we often perform both scenarios on the same machine and need to make sure we're accounting for requirements for both scenarios.

If you're verifying a trusted signed package, the test certificate needs to be in the trusted root store.

If you're signing a trusted signed package with a certificate in the Windows certificate store, the test certificate needs to be in the trusted root store AND the private key needs to be there too.

A .cer file is just a certificate with no private key.  A .pfx file contains both the certificate and its private key.

If you want to sign and verify using a trusted test certificate in the Windows certificate store you need to pass the .pfx file NOT the .cer file to the TrustTestCert tool.  Then everything will work as expected.

The "Key does not exist." error occurs because you passed the .cer file to the TrustTestCert tool and so the private key wasn't stored in the Windows certificate store.  When you tried to sign with the certificate, NuGet found the certificate in Windows certificate store but not the associated private key, which is required for signing.

Can you please update the test case to indicate that the .pfx file needs to be passed to TrustTestCert?

I'll close this issue.  If it's still not resolved, please reactivate with details.

**Closed as completed by dtivel** 2024-01-19 20:58 UTC
Labels: Type:Bug, Functionality:Signing, Found:ManualTests
