### ISSUE TITLE
contentFiles metadata incorrect when building with Nugetizer?

### ISSUE THREAD

**Issue by ChristophLindemann** [NuGet/Home#6556] opened 2018-02-12 13:32 UTC
When using nugetizer to create packages with contentFiles the generated `<contentFiles>` metadata incorrectly includes the `contentFiles\` folder in the path.

This results in `<Compile>` items instead of  `<Content>` items being generated during nuget restore

## When doing:

**NuGet.Build.Packaging**: 0.2.2 and also lates dev version 0.2.0-dev-build0023

When building the following .nuproj
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <Import Project="$(NuGetAuthoringPath)\NuGet.Packaging.Authoring.props" Condition="Exists('$(NuGetAuthoringPath)\NuGet.Packaging.Authoring.props')" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>75004d1d-fe4a-4434-b4da-40c234fb45a8</ProjectGuid>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <IsDevelopmentDependency>true</IsDevelopmentDependency>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>ContentFiles.Is.Wrong.Path</PackageId>
    <Title>ContentFiles.Is.Wrong.Path</Title>
    <Summary>
	</Summary>
    <Description>
	</Description>
    <PackageReleaseNotes>
    </PackageReleaseNotes>
    <PackageLicenseUrl>
    </PackageLicenseUrl>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <TargetFramework>net462</TargetFramework>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <InferLegacyPackageReferences>false</InferLegacyPackageReferences>
    <IncludeContentInPackage>false</IncludeContentInPackage>
    <IncludeOutputsInPackage>false</IncludeOutputsInPackage>
    <IncludeSymbolsInPackage>false</IncludeSymbolsInPackage>
    <IncludeFrameworkReferencesInPackage>false</IncludeFrameworkReferencesInPackage>
    <PrimaryOutputKind>Content</PrimaryOutputKind>
    <EmitNuSpec>true</EmitNuSpec>
  </PropertyGroup>

    <PackageReference Include="NuGet.Build.Packaging" Version="0.2.0-dev-build0023">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

  <ItemGroup>
    <PackageFile Include="..\SomePath\ToolName\**\*">
      <TargetPath>ToolName\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
      <Link>ToolName\bin\$(Configuration)\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <Kind>ContentFiles</Kind>
      <FrameworkSpecific>false</FrameworkSpecific>
      <BuildAction>Content</BuildAction>
      <CopyToOutput>true</CopyToOutput>
    </PackageFile>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" />
  <Import Project="$(NuGetAuthoringPath)\NuGet.Packaging.Authoring.targets" Condition="Exists('$(NuGetAuthoringPath)\NuGet.Packaging.Authoring.targets')" />
</Project>
```

## Actual
The contenFiles metadata does incorrectly include "contentFiles\" in the `include` attribute. Which is incorrect from my understanding, as `<contentFiles>` already implies the file beeing located under the `contentFiles\` package path.
I have also seen some comments from @emgarten where he notes that `contentFiles\` should not be included in the `<contentFiles>` metadata.

It also does not work (when testing with VS 15.5.6), as nuget restore generates `<Compile>` items in the generated targets file. When removing the prefix, the correct `<Content>` items are generated.

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>ContentFiles.Is.Wrong.Path</id>
    <version>0.1.45-gd989c049cc</version>
    <title>ContentFiles.Is.Wrong.Path</title>
...
    <contentFiles>
      <files include="contentFiles\any\any\ToolName\tool.exe" buildAction="Content" copyToOutput="true" />
      <files include="contentFiles\any\any\ToolName\readme.txt" buildAction="Content" copyToOutput="true" />
    </contentFiles>
  </metadata>
</package>
```
## Expected 
I would expect a nuget with a nuspec with contenFiles metadata which does not include "contentFiles\" in the `include` attribute:
```
    <contentFiles>
      <files include="any\any\ToolName\tool.exe" buildAction="Content" copyToOutput="true" />
      <files include="any\any\ToolName\readme.txt" buildAction="Content" copyToOutput="true" />
    </contentFiles>
```

## Further comments
Is this maybe something that is broken in the latest nuget.exe version? Maybe including the "contentFiles\" part was supported earlier.

Also the unit-test "NuGet.Build.Packaging.Tests/CreatePackageTests/when_creating_package_with_content_file_copy_to_output_then_adds_as_content_file" (created by @kzu ) explictly tests for "contentFiles\" in the include attribute

**Comment by kzu** [comment] 2018-09-04 18:39
@emgarten can you verify that this proposed fix is indeed what's expected by nuget? https://github.com/NuGet/NuGet.Build.Packaging/pull/164

I don't think it is correct, since packages like https://www.nuget.org/packages/xunit.assert.source use the *exact* same mechanism, its nuspec contains:

```
    <contentFiles>
      <files include="contentFiles/cs/netstandard1.1/Asserts/**/*.cs" buildAction="Compile" />
    </contentFiles>
```

and it works just fine. I've found *many* packages in my cache with that `contentFiles` folder prefix.

**Comment by azeno** [comment] 2018-09-04 18:50
Well buildAction="Compile" is the default so the issue is not evident. Check any other package where the buildAction is set to something different than Compile, install in VS and the custom buildAction will not be taken into account.

**Comment by emgarten** [comment] 2018-09-04 21:27
//cc @nkolev92 @jainaashish for contentFiles

**Comment by kzu** [comment] 2018-09-23 04:25
gentle nudge 👍 . I think the bug report is incorrect, but what @azeno is worrying.

**Comment by nkolev92** [comment] 2018-10-01 17:58
@kzu 
The contentFiles value should be excluded. 
 See [code](https://github.com/NuGet/NuGet.Client/blob/07b645ceb662299ff7ce76dcfbdb4e8d30e936dd/src/NuGet.Core/NuGet.Commands/RestoreCommand/ContentFiles/ContentFileUtils.cs#L129-L148)

This has always been the case, see https://github.com/NuGet/NuGet.Client/commit/496a08b2ad35b4479c36c1cb8586bbdc11614c61

@azeno is correct, the only reason why the above works is because the default action is compile.

**Comment by azeno** [comment] 2019-01-19 12:10
I think this issue can be closed? My PR was accepted and is merged into dev branch.

**Comment by kzu** [comment] 2019-01-19 15:24
As mentioned, this was contributed and accepted

**Closed as completed by kzu** 2019-01-19 15:24 UTC
Labels: Product:NuGetizer
