### ISSUE TITLE
/t:pack target doesn't include or have an option to include reference assemblies

### ISSUE THREAD

**Issue by tannergooding** [NuGet/Home#9298] opened 2020-03-13 14:53 UTC
## Issue

The C# compiler has support for a special `-refout` switch and a `ProduceReferenceAssembly` project property which causes it to generate a reference assembly alongside the normal assembly output.
NuGet likewise supports a `ref` folder where these types of reference assemblies can go and it will consume them if available. 
However, NuGet does not appear to currently have a mechanism to automatically include this output in the generated package.

## Repro

1. Create a new csproj
2. Under the `TargetFramework` property add `<ProduceReferenceAssembly>true</ProduceReferenceAssembly>`
3. Run `dotnet pack`
4. Observe that the following files exist:
    * `bin\Debug\<tfm>\ClassLibrary1.dll`
    * `bin\Debug\<tfm>\ref\ClassLibrary1.dll`
    * `bin\Debug\ClassLibrary1.1.0.0.nupkg`
5. Extract the nupkg to a local folder
6. Observe that `<nupkg>\lib\<tfm>\ClassLibrary1.dll` exists and corresponds to `bin\Debug\<tfm>\ClassLibrary1.dll`
7. Observe that `<nupkg>\ref\<tfm>\ClassLibrary1.dll` does not exist

## Expected Behavior

It is expected that the `ref` files do exist and correspond to the files produced by the compiler under `bin\Debug\<tfm>\ref\ClassLibrary1.dll`

**Comment by AraHaan** [comment] 2020-03-13 16:21
Also if you manually try to add them; it would generate an ``NU5131`` because of the use of ``TfmSpecificPackageFile`` to attempt an hack support for ``PackageReference`` to bypass this issue.

The bypass of course then snags onto another issue because it is obviously not added to the nuspec and if the project uses warn as errors it then becomes an ``error NU5131``.

The best fix is to instead fix this at the source so the bypass on this is then not used anymore and then adds them as intended.

However what about xml documentations? While they get packed into the ``lib`` files, I think they should also get copied over to the ``ref`` files as well.

**Comment by AraHaan** [comment] 2020-03-16 14:08
cc @nkolev92

**Comment by nkolev92** [comment] 2020-03-16 18:10
Duplicate of https://github.com/NuGet/Home/issues/4184

> However what about xml documentations? While they get packed into the lib files, I think they should also get copied over to the ref files as well.

I imagine that'll have to be the case as well. 

Let's continue any further discussion in the older issue. 

Thanks!

**Closed as completed by nkolev92** 2020-03-16 18:10 UTC
Labels: Resolution:Duplicate, Type:DCR, Functionality:Pack

**Comment by tannergooding** [comment] 2020-03-16 18:17
Thanks, I missed that one when searching for existing issues 😄

**Comment by nkolev92** [comment] 2020-03-16 18:33
yeah, it took me a while to find it as well. 
I just knew I had seen something like this before, so I kept on searching :D
