### ISSUE TITLE
dotnet new -i, on two private feeds, unauthorized

### ISSUE THREAD

**Issue by mlorbetske** [NuGet/Home#7027] opened 2018-06-14 16:53 UTC
_From @maracuja-juice on May 28, 2018 12:16_

I have a Template package that I published to a private feed. (let's name it "Nutshell")
I deleted this package from the "Nutshell" NuGet feed and uploaded it to a different private feed, with a newer version. (let's name that one: "Peach", "Nutshell" will get obsolete at some point)
The feeds are both hosted in VSTS.

I created a PAT with the permission of "packaging (read)" and added it to my NuGet config:
```
  <packageSourceCredentials>
    <packageSourceKey>
      <add key="Username" value="myVSTSUserNAme" />
      <add key="ClearTextPassword" value="myToken" />
    </packageSourceKey>
  </packageSourceCredentials>
```

Now when I try to install the package via `dotnet new -i` I always get the error:

```
C:\Program Files\dotnet\sdk\2.1.200\NuGet.targets(114,5): error : Unable to load the service index for source https://nutshell.pkgs.visualstudio.com/_packaging/nutshell/nuget/v3/index.json. [C:\Users\maracujajuice\.templateengine\dotnetcli\v2.1.200\scratch\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.200\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\maracujajuice\.templateengine\dotnetcli\v2.1.200\scratch\restore.csproj]
```

As you can see: It tries to get the package from the "Nutshell" feed (package is deleted in version 1.0) but it should get it from the "Peach" feed where the package is in version 1.2.
If I explicitly state the version (`Template.Package.Name::1.2.0`) it gets the package correctly from the "Peach" feed.
Why does it want to get it from the "Nutshell" feed by default / doesn't try out both as the same package is on both feeds? (once deleted though)
Can you reproduce this problem?

Thanks for your help. 

_Copied from original issue: dotnet/templating#1545_

**Comment by mlorbetske** [comment] 2018-06-14 16:53
_From @maracuja-juice on June 6, 2018 6:42_

@seancpeters Can you reproduce this problem?

**Comment by mlorbetske** [comment] 2018-06-14 16:53
@maracuja-juice behind the scenes, we're just doing a NuGet restore on a csproj and aren't involved in the mechanics of the actual restore itself. From the error message, it doesn't look like it couldn't find the package, but that it couldn't read from that feed at all (from the `Unable to load the service index for source ...` message), given that it returned an unauthorized, it doesn't seem to have accepted the credentials it was presented with (maybe it's this issue https://github.com/NuGet/Home/issues/4938).

I'd suggest pursuing this on the NuGet/Home repo as they'd know better how to address the issue. 

To verify, the project file that `dotnet restore` is being called on (given the package name and version you've mentioned) has these contents:

```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="Microsoft.NETCore.App" />
    <PackageReference Include="Template.Package.Name" Version="1.2.0" />
  </ItemGroup>
</Project>
```

You should be able to save this to a csproj locally & call `dotnet restore` on it - which should more directly reproduce this.

**Comment by mlorbetske** [comment] 2018-06-14 16:53
_From @maracuja-juice on June 14, 2018 8:26_

@mlorbetske Okay, I created this `.csproj` on my desktop and then ran `dotnet restore` and I get the following: 

```
C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\NuGet.targets(114,5): error : Unable to load the service index for source https://nutshell.pkgs.visualstudio.com/_packaging/Nutshell/nuget/v3/index.json. [C:\Users\maracujajuice\Desktop\Testing.csproj]
C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\maracujajuice\Desktop\Testing - Copy.csproj]
```

If I remove the `nutshell` feed from my `NuGet.config` this works as expected. 
I verified this behaviour with a new template we created yesterday. (that was never on the other feed, that means it is only available on the `Peach` NuGet feed.)

Hope you can reproduce this problem.

**Comment by jainaashish** [comment] 2018-06-14 23:11
@mlorbetske I'm unable to understand how a single declaration of `packageSourceCredentials` will work with multiple feeds? Can you share the content of your `nuget.config` file (avoiding username/ password and actual feed link)?

**Comment by mlorbetske** [comment] 2018-06-14 23:14
@maracuja-juice could you provide the requested information for @jainaashish please?

**Comment by panmona** [comment] 2018-06-15 07:22
```
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
	<add key="nutshell" value="feedurl" />
    <add key="peach" value="feedurl" />
  </packageSources>
    <packageSourceCredentials>
    <peach>
      <add key="Username" value="username" />
      <add key="ClearTextPassword" value="password" />
    </peach>
  </packageSourceCredentials>
</configuration>
```

I just figured out that if I add the credentials for the second feed (where there is no such package) to my config aswell it works.
Am I right, that this is unavoidable?

**Comment by panmona** [comment] 2019-02-19 21:56
Is there any update on this? @jainaashish 
For multiple feeds we have multiple packageSourceCredentials.

**Comment by jainaashish** [comment] 2019-02-20 17:47
It tries to connect to all the configured feeds to get the required package, which is why it fails when it can't connect to nutshell feed but when you provide the credential for that feed it works. So if you don't need nutshell feed for your current installation or restore then you'd either need to disable that or provide credentails. That's by design.

**Comment by panmona** [comment] 2019-02-20 19:59
- Why doesn't it first try to find the package it on the other feeds? 
- Why do we have to configure this, this way? Visual Studio for example doesn't need these credentials in the NuGet.config. (that's probably also why it sometimes deletes them again..)

**Comment by nkolev92** [comment] 2019-03-30 00:49
@maracuja-juice That's by design in PackageReference. 

Closing this as duplicate of https://github.com/NuGet/Home/issues/6373

**Closed as completed by nkolev92** 2019-03-30 00:49 UTC
Labels: Area:Settings, Style:PackageReference
