### ISSUE TITLE
Warn users of breaking changes when updating NuGet packages

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7704] opened 2019-01-17 23:05 UTC
<p>I suggest to warn users when updating NuGet package(s) with breaking change.</p><p>When a new package is released, the author MUST specify if and where are breaking changes, so VS BEFORE apply the update warn the user for any breaking changes.</p><p>Same topic on <a href="https://github.com/NuGet/Home/issues/6673" target=_blank>NuGet GitHub</a></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/399523/warn-users-of-breaking-changes-when-updating-nuget.html
VSTS ticketId: 740211_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/5/2018, 06:57 PM (42 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by anangaur** [comment] 2019-01-17 23:06
This issue can also be mitigated if we show an API explorer and show the diff in APIs between versions on the update tab.

**Comment by jainaashish** [comment] 2019-01-18 00:32
@anangaur what was the reason of creating this issue when there is already existing one for the same purpose? Can't you just put your suggestions in the existing one itself?

Dupe of https://github.com/NuGet/Home/issues/6673

**Closed as completed by jainaashish** 2019-01-18 00:32 UTC
Labels: Resolution:Duplicate

**Comment by anangaur** [comment] 2019-01-18 01:50
This is a tool created issue when I move it from feature requests (user voice) to GitHub. If there needs to be a process change, then we should discuss it.

**Comment by jainaashish** [comment] 2019-01-18 01:53
Looking at some recent issues created with this tool, it feel there is definitely some scope of improvements to avoid duplicate efforts. I'm not too aware of this tool, but available for discussion and my inputs.
