### ISSUE TITLE
NuGet on macOS won't use NTLM authentication

### ISSUE THREAD

**Issue by oviradoi** [NuGet/Home#5399] opened 2017-06-13 06:28 UTC
## Details about Problem

I am trying to install a nuget package on macOS. The package is hosted in our on-premises TFS2017 server, using the Package Management extension. The server is set up to use NTLM authentication.

I installed nuget using the `brew install nuget` command. I added the package source, and I ran the `nuget install` command, passing the package name as a parameter. Nuget will connect to the package source, and it will ask for username and password credentials. If I enter the credentials, it will ask for them again and again, 3 times in total. Then it will exit, showing a 401 Unauthorized error.

I used Wireshark to capture the HTTP traffic, and I can see that nuget will try to use Basic authentication, passing in the username and password that I entered. But the server does not accept Basic authentication, it will only accept NTLM authentication.

* NuGet product used NuGet CLI for Mac (the version installed using `brew install nuget`)

* NuGet version (x.x.x.xxx): 4.0.0.2283

* OS version: macOS Sierra 10.12.5

* Mono version: 5.0.1.1 (2017-02/5077205) (it was installed by homebrew, as a dependency for nuget)

* Worked before? If so, with which NuGet version: Did not work before

## Detailed repro steps so we can see the same problem

1. On a macOS system, install nuget using `brew install nuget`.

2. Add a package source pointing to a TFS 2017 server with the package management extension.

3. Run `nuget install package_name`.

4. Nuget will ask for a username and password. Even if you provide the correct username and password, it will not work. It will ask for them 3 times, then it will fail with a 401 Unauthorized error. I tried using the  `username` syntax, the `domain\username` syntax and the `username@domain` syntax but all of them showed the same problem.

5. If you use Wireshark to see the HTTP traffic, you will notice that nuget uses Basic authentication instead of NTLM authentication. This causes the server to return a 401 error.

**Comment by emgarten** [comment] 2017-06-13 16:45
Related to https://github.com/NuGet/Home/issues/2393

**Comment by mishra14** [comment] 2017-11-30 00:58
dupe of #2393

**Closed as completed by mishra14** 2017-11-30 00:58 UTC
Labels: Resolution:Duplicate, Product:NuGet.exe, Platform:Mono
