### ISSUE TITLE
`System` not found after installing MathNet.Numerics package when using project.json 

### ISSUE THREAD

**Issue by kjbartel** [NuGet/Home#2081] opened 2016-02-09 12:11 UTC
Using a C# class library (csproj) with project.json, after installing the MathNet.Numerics nuget package the reference to `System` becomes marked with a yellow triangle and fails to build. Specifically I am getting errors with `System.ComponentModel` and `INotifyPropertyChanged`:

> error CS0234: The type or namespace name 'ComponentModel' does not exist in the namespace 'System' (are you missing an assembly reference?)
> error CS0246: The type or namespace name 'INotifyPropertyChanged' could not be found (are you missing a using directive or an assembly reference?)

My project.json file is as follows:

```
{
  "dependencies": {
    "MathNet.Numerics": "3.10.0"
  },
  "frameworks": {
    "net461": { }
  },
  "runtimes": {
    "win-anycpu": { },
    "win": { }
  }
}
```

I also tried with only `win` and only `win-anycpu` and tried changing the project target to net40, net45, net46, all with the same errors. When using packages.config the package could be installed and used without any errors.

As I'm not sure if this is a problem with NuGet or the MathNet.Numerics nuget package I also [opened an issue](https://github.com/mathnet/mathnet-numerics/issues/372) on that project also.

**Comment by yishaigalatzer** [comment] 2016-02-09 23:59
CC @ericstj @emgarten @jasonmalinowski

**Comment by jasonmalinowski** [comment] 2016-02-10 00:18
This is a duplicate of #1880 which we checked the fix in a few days for. The fix should make the final release of Update 2.

**Closed as completed by jasonmalinowski** 2016-02-10 00:18 UTC
