### ISSUE TITLE
install fails when a nuget Source is unavailable even when this is not the selected Source 

### ISSUE THREAD

**Issue by FilipDeVos** [NuGet/Home#2614] opened 2016-04-19 19:39 UTC
Since one of my nuget feeds sits behind a VPN connection it is often not available. Every time I want to install a package the install fails unless I activate the VPN. 

```
Install-Package Newtonsoft.Json -Source "Microsoft and .NET"
```

```
Install-Package : Exception 'System.AggregateException' thrown when trying to add source 'https://privatefeed/api/v2/'. Please verify all your online package sources are available.
At line:1 char:1
+ Install-Package Newtonsoft.Json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

This is triggered by the iteration of all sources which are added here [ResolverGather.cs](https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/src/NuGet.Core/NuGet.PackageManagement/Resolution/ResolverGather.cs#L546)

Ideally the list should only validate the source I selected. As a workaround raising the exception as a warning would work.

**Comment by rrelyea** [comment] 2016-04-19 23:29
dupe of #2598 
The solution is suggested in #1627

**Closed as completed by rrelyea** 2016-04-19 23:29 UTC

**Comment by FilipDeVos** [comment] 2016-04-19 23:57
Not completely. When I force a source, why does it itterate over all sources?

This is not part of the linked issues, they would only make the behaviour less annoying.
