### ISSUE TITLE
Connection issues with dotnet restore --disable-parallel

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#7094] opened 2018-07-06 17:30 UTC
Anton Novicov wrote:

My problem appear when i try "dotnet restore" command in my dotnet project. 
When i use dotnet --disable-parallel I have not this errors: 
dotnet restore: https://gist.github.com/novicov/a7823ce570c8ac362ed949a12dbb717b

WinMTR stats: https://gist.github.com/novicov/438a57d2026d7b63e504c66728bf14be 

 My soft:
Microsoft Visual Studio Enterprise 2017 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework 4.7.03062
NuGet   4.6.0

dotnet --info : https://gist.github.com/novicov/57c0493317be49d68b88d779d4788ba9

**Comment by nkolev92** [comment] 2018-07-06 17:48
Looks like a duplicate of https://github.com/NuGet/Home/issues/6742. 

Basically the root cause normally is that NuGet is trying to create more connections than the machine can handle. 

The linked dup is tracking a task to make the parallelization configurable.

**Closed as completed by nkolev92** 2018-07-06 17:48 UTC
Labels: Resolution:Duplicate, Tenet:Performance, Area:HttpCommunication
