### ISSUE TITLE
nuget package install fails on VS2015E

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1298] opened 2015-08-31 06:51 UTC
_From @mprevot on August 28, 2015 14:55_

Attempting to resolve dependencies for package 'Yeppp.CLR.Bundle.1.0.1-prerelease' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Resolved actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Install failed. Rolling back...
Package 'Yeppp.CLR.Bundle 1.0.1-prerelease' does not exist in project 'VideoProcessor'
Package 'Yeppp.CLR.Bundle 1.0.1-prerelease' does not exist in folder 'C:\Users\soleil\Documents\Visual Studio 2015\Projects\shutter_modeler\packages'
Install-Package : Could not install package 'Yeppp.CLR.Bundle 1.0.1-prerelease'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
- Install-Package Yeppp.CLR.Bundle -Pre
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

_Copied from original issue: NuGet/NuGetGallery#2642_

**Comment by yishaigalatzer** [comment] 2015-08-31 16:20
@mprevot we need more details to look at this issue
1. What version of nuget are you using
2. Did that package worked in any other version of visual studio? What I'm asking is: Do you know if the package is valid at all for your scenario?
3. More details on what project you are installing it into, and best if possible the full repro steps.

**Comment by mprevot** [comment] 2015-08-31 18:27
Hey,

I'm using nuget 3.0.0, VS2015 enterprise, VS2013.5 ultimate. The problem
occured in VS2015.

In VS2013.5 same:

2015-08-31 18:21 GMT+02:00 Yishai Galatzer notifications@github.com:

**Comment by mprevot** [comment] 2015-08-31 18:29
The nuget version in VS2013.5: 2.8.60610.756 and it fails:

PM> Install-Package Yeppp.CLR.Bundle -Pre
Install-Package : The current environment doesn't have a solution open.
At line:1 char:1
- Install-Package Yeppp.CLR.Bundle -Pre
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [Install-Package],
    InvalidOperationException
  - FullyQualifiedErrorId :
    NuGetNoActiveSolution,NuGet.PowerShell.Commands.InstallPackageCommand

Best

2015-08-31 20:27 GMT+02:00 Mathieu Prevot mathieu.prevot@gmail.com:

**Comment by mprevot** [comment] 2015-08-31 18:29
Sorry for the nois, the actual message:

PM> Install-Package Yeppp.CLR.Bundle -Pre
Install-Package : Unable to find package 'Yeppp.CLR.Bundle'.
At line:1 char:1
- Install-Package Yeppp.CLR.Bundle -Pre
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package],
    InvalidOperationException
  - FullyQualifiedErrorId :
    NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

2015-08-31 20:28 GMT+02:00 Mathieu Prevot mathieu.prevot@gmail.com:

**Comment by yishaigalatzer** [comment] 2015-08-31 18:36
1. Please update NuGet to 3.1.1 in Visual Studio 2015
2. Please share your nuget.config and package.config

**Comment by mprevot** [comment] 2015-09-01 06:30
The update was done.

nuget.config:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json"
protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <activePackageSource>
    <add key="Microsoft and .NET" value="
https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/" />
  </activePackageSource>
</configuration>

How do I get package.config ?

2015-08-31 20:36 GMT+02:00 Yishai Galatzer notifications@github.com:

**Comment by yishaigalatzer** [comment] 2015-09-09 20:44
packages.config is available at the root of your project.

I assume the issue wasn't resolved after the update?

**Comment by yishaigalatzer** [comment] 2015-09-21 18:26
ping? (also we now released NuGet 3.2)

**Comment by mprevot** [comment] 2015-09-21 18:29
Hey

Thanks for the heads up. I don't have VS right now but I'll be in that on
the next couple of days.

Isn't c# 6 using AVX and AVX2 automatically ?

Thanks.

Le lundi 21 septembre 2015, Yishai Galatzer notifications@github.com a
écrit :

**Comment by emgarten** [comment] 2015-09-22 21:46
@mprevot are you installing into a managed C++ project? The error message looks correct, the package contains only a net20 folder. There is nothing in the package for native projects.

**Comment by mprevot** [comment] 2015-09-23 08:02
Hey

I have the lastest Nuget ie., 3.2.6. I'm working in a c# 6 (4.6) project.

Install-Package Yeppp.CLR.Bundle -Pre fails the same way ( Install-Package
: Unable to find package 'Yeppp.CLR.Bundle')

M

2015-09-22 23:46 GMT+02:00 Justin Emgarten notifications@github.com:

**Comment by yishaigalatzer** [comment] 2015-09-24 18:44
Sorry, I can't see to reproduce this issue.

Visual Studio 2015 + NuGet 3.2

Console Application 4.6
Class Library 4.6 nuget source - https://www.nuget.org/api/v2
Class Library 4.6 nuget source - https://api.nuget.org/v3/index.json

Can you check your nuget sources?

![image](https://cloud.githubusercontent.com/assets/1238711/10083086/b015233a-62b1-11e5-872f-504f6e80aef0.png)

```
Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 3.2.0.10516

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package Yeppp.CLR.Bundle -Pre
Attempting to gather dependencies information for package 'Yeppp.CLR.Bundle.1.0.1-prerelease' with respect to project 'ConsoleApplication8', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'Yeppp.CLR.Bundle.1.0.1-prerelease' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Resolved actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Adding package 'Yeppp.CLR.Bundle.1.0.1-prerelease' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ConsoleApplication8\packages'
Added package 'Yeppp.CLR.Bundle.1.0.1-prerelease' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ConsoleApplication8\packages'
Added package 'Yeppp.CLR.Bundle.1.0.1-prerelease' to 'packages.config'
Successfully installed 'Yeppp.CLR.Bundle 1.0.1-prerelease' to ConsoleApplication8
PM> Install-Package Yeppp.CLR.Bundle -Pre
Attempting to gather dependencies information for package 'Yeppp.CLR.Bundle.1.0.1-prerelease' with respect to project 'ClassLibrary3', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'Yeppp.CLR.Bundle.1.0.1-prerelease' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Resolved actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Adding package 'Yeppp.CLR.Bundle.1.0.1-prerelease' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary3\packages'
Added package 'Yeppp.CLR.Bundle.1.0.1-prerelease' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary3\packages'
Added package 'Yeppp.CLR.Bundle.1.0.1-prerelease' to 'packages.config'
Successfully installed 'Yeppp.CLR.Bundle 1.0.1-prerelease' to ClassLibrary3
PM> Install-Package Yeppp.CLR.Bundle -Pre
Attempting to gather dependencies information for package 'Yeppp.CLR.Bundle.1.0.1-prerelease' with respect to project 'ClassLibrary3', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'Yeppp.CLR.Bundle.1.0.1-prerelease' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Resolved actions to install package 'Yeppp.CLR.Bundle.1.0.1-prerelease'
Package 'Yeppp.CLR.Bundle.1.0.1-prerelease' already exists in folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary3\packages'
Added package 'Yeppp.CLR.Bundle.1.0.1-prerelease' to 'packages.config'
Successfully installed 'Yeppp.CLR.Bundle 1.0.1-prerelease' to ClassLibrary3
PM> 
```

**Comment by mprevot** [comment] 2015-09-24 20:17
Here:

https://api.nuget.org/v3/index.json

2015-09-24 20:44 GMT+02:00 Yishai Galatzer notifications@github.com:

**Comment by yishaigalatzer** [comment] 2015-10-12 23:59
Sorry we dropped this thread, are you still blocked on this?

**Comment by mprevot** [comment] 2015-10-13 05:04
Still but I also dropped to use this package.

Le mardi 13 octobre 2015, Yishai Galatzer notifications@github.com a
écrit :

**Comment by yishaigalatzer** [comment] 2015-10-13 05:16
Sorry, but I don't understand. Can you elaborate?

**Comment by mprevot** [comment] 2015-10-13 05:32
I didn't managed to make the package work, but I also dropped the idea to
use it.

Le mardi 13 octobre 2015, Yishai Galatzer notifications@github.com a
écrit :

**Comment by bounav** [comment] 2015-11-16 15:35
Similar issue here with Visual Studio 2015 Enterprise RTM.

In an existing solution (i.e. created before VS 2015 was released) we can't install any new packages, we get the following error:

```
PM> Install-Package tradera.net -pre
Attempting to gather dependencies information for package 'tradera.net.1.0.0-alpha' with respect to project 'My.Project', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'tradera.net.1.0.0-alpha' with DependencyBehavior 'Lowest'
Install-Package : Unable to resolve dependency 'System.Net'. Source(s) used: 'nuget.org'.
At line:1 char:35
+ Install-Package tradera.net -pre
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

Note: it doesn't matter which package id you try to install or if `-pre` is present or not.

When I try in Visual Studio 2013 (which I ketp in a different VM) no problem. The package installs.

I'm running VS 2015 Entreprise 14.0.23107.0.D14REL and Nuget Package Manager for Visual Studio v3.2.60914.10516.

**Comment by yishaigalatzer** [comment] 2015-11-16 17:29
@bounav are you able to share a sample project that demonstrates this issue?

**Comment by ghost** [comment] 2016-08-03 21:49
Hello, was this resolved? I am running into the same issue. I created a PCL to run in .NETCore and .NetFramework 4.5.1. I am trying to install package RabbitMQ.Client.4.0.0-rc-1. 

Resolving actions to install package 'RabbitMQ.Client.4.0.0-rc-1'
Resolved actions to install package 'RabbitMQ.Client.4.0.0-rc-1'
Install failed. Rolling back...
Package 'RabbitMQ.Client.4.0.0-rc-1' does not exist in project 'CWI.Common.Messaging'
Package 'RabbitMQ.Client.4.0.0-rc-1' does not exist in folder 'C:\Projects\External\CredibleBH\Dev\Source\ManagedCare\packages'
Invalid portable frameworks.

**Comment by mprevot** [comment] 2016-08-04 10:33
I didn't had news about this, wether it was resolved or not.
I guess you'll be able to know why it fails with a more verbose log.

2016-08-03 23:49 GMT+02:00 luisbecerril notifications@github.com:

**Comment by Heinzelemente** [comment] 2016-08-09 12:38
I have the same issue. I am using my own package which I created and successfully installed initially. 
No I triedto update it and uninstalled it , because the version is the same and install it again. 
I receive this error and I am not able to install it again:

```
PM> install-package Web.Portal
Attempting to gather dependency information for package 'Web.Portal.0.0.1' with respect to project 'Web.Portal.Symrise', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Web.Portal.0.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Web.Portal.0.0.1'
Resolved actions to install package 'Web.Portal.0.0.1'
Adding package 'Web.Portal.0.0.1' to folder 'C:\Users\alex\Source\Workspaces\ProjectFramework\Symrise\packages'
Install failed. Rolling back...
Package 'Web.Portal.0.0.1' does not exist in project 'Web.Portal.Symrise'
Removing package 'Web.Portal.0.0.1' from folder 'C:\Users\alex\Source\Workspaces\ProjectFramework\Symrise\packages'
TF400024: The change on C:\Users\alex\Source\Workspaces\ProjectFramework\Symrise\packages\Web.Portal.0.0.1\Web.Portal.0.0.1.nupkg cannot be undone because a file already exists at C:\Users\alex\Source\Workspaces\ProjectFramework\Symrise\packages\Web.Portal.0.0.1\Web.Portal.0.0.1.nupkg. The file must be deleted from disk for the undo to succeed.
Removed package 'Web.Portal.0.0.1' from folder 'C:\Users\alex\Source\Workspaces\ProjectFramework\Symrise\packages'
install-package : TF400024: The change on C:\Users\alex\Source\Workspaces\ProjectFramework\Symrise\packages\Web.Portal.0.0.1\Web.Portal.0.0.1.nupkg cannot be undone because a file already exists at 
C:\Users\alex\Source\Workspaces\ProjectFramework\Symrise\packages\Web.Portal.0.0.1\Web.Portal.0.0.1.nupkg. The file must be deleted from disk for the undo to succeed.
At line:1 char:1
+ install-package Web.Portal
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

```

I can share my .nuspec and .nupak if necessary.

**Comment by Heinzelemente** [comment] 2016-08-09 12:52
An update is working fine. e.g. from 0.0.1 to 0.0.2, but uninstall and install is destroys the project. 
I am glad TFS is in place.

**Comment by luty81** [comment] 2016-08-23 12:40
I am facing the same issue!
My Nuget Package Manager version is 3.4.4.1321

**Comment by tonyeung** [comment] 2016-08-29 08:08
ermagawd... i spent a few hours on this.... I want to cry...

Chances are there is something wrong with the folder structure in the nupkg.
For my situation, I used TeamCity and OctoPack to generate a package to be deployed.

The folder structure that OctoPack creates is flat, whereas the correct folder structure has extra meta data as well as a convention for how the folders are supposed to be named and nested in order to be consumed by Visual Studio.

This used to work in VS 2013 but no longer works in VS 2015

I have tested this by creating Nuget Pack step in TeamCity and the new package was installed as expected. The best thing about it is that since i configured the package names to be the same, the nuget pack step actually overwrites the old package and so the package that gets used by TeamCity's Nuget Feed is the correct one.

All credit goes to http://stackoverflow.com/questions/34161335/nuget-3-octopack-wrong-framework-target-error

**Comment by Heinzelemente** [comment] 2016-08-29 09:14
Is this issue already under investigation? I think a lot of developers facing the same issue, but do not think it is a nuget bug. (like tonyeung )

**Comment by TimLovellSmith** [comment] 2016-09-09 17:09
I am hitting a very similar issue trying to install a nightly build of xunit, in VS2015 package manager console, like this:

```
PM>  Update-Package xunit.core -Version 2.2.0-beta3-build3350 -IgnoreDependencies -Project AzureCache.ResourceModel.Tests
Attempting to gather dependency information for multiple packages with respect to project 'Provisioning\AzureCache.ResourceModel.Tests', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for multiple packages.
Resolving actions install multiple packages
Update-Package : packages
At line:1 char:1
+ Update-Package xunit.core -Version 2.2.0-beta3-build3350 -IgnoreDependencies -Pr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

My packages.config for AzureCache.ResourceModel.Tests is:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.1.1" targetFramework="net45" />
  <package id="FakeItEasy" version="2.0.0-beta009" targetFramework="net45" />
  <package id="Microsoft.Bcl" version="1.1.9" targetFramework="net45" />
  <package id="Microsoft.Bcl.Async" version="1.0.168" targetFramework="net45" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net45" />
  <package id="Microsoft.Net.Http" version="2.2.28" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net45" />
  <package id="xunit" version="2.0.0" targetFramework="net45" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net45" />
  <package id="xunit.assert" version="2.1.0-beta3-build3029" targetFramework="net45" />
  <package id="xunit.core" version="2.1.0-beta3-build3029" targetFramework="net45" />
  <package id="xunit.extensibility.core" version="2.2.0-beta3-build3350" targetFramework="net45" />
  <package id="xunit.runner.visualstudio" version="2.0.0-rc3-build1046" targetFramework="net45" />
</packages>
```

My package source is a local file share with files copied from xunit's myget (e.g. https://www.myget.org/feed/xunit/package/nuget/xunit.core)

**Comment by TimLovellSmith** [comment] 2016-09-09 17:20
I note that I had package manager console set to use my local file share package source...
However the same package is on nuget.org:

https://www.nuget.org/packages/xunit.core/2.2.0-beta2-build3300

And it seems like if I do Install-Package of it, the one from nuget.org gets installed, not the package source I had selected.

```
Install-Package xunit.core -Version 2.2.0-beta3-build3350 -IgnoreDependencies -Project AzCache.Config.Tests
  GET https://www.nuget.org/api/v2/Packages(Id='xunit.core',Version='2.2.0-beta3-build3350')
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='xunit.core',Version='2.2.0-beta3-build3350')
  GET https://api.nuget.org/v3/registration1-gz/xunit.core/index.json
  OK https://api.nuget.org/v3/registration1-gz/xunit.core/index.json 253ms
  NotFound https://www.nuget.org/api/v2/Packages(Id='xunit.core',Version='2.2.0-beta3-build3350') 276ms
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='xunit.core'
  NotFound https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='xunit.core',Version='2.2.0-beta3-build3350') 277ms
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.core'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='xunit.core' 66ms
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='xunit.core' 179ms
Resolved actions to install package 'xunit.core.2.2.0-beta3-build3350'
Adding package 'xunit.core.2.2.0-beta3-build3350' to folder 'C:\repo\cacheprototype\packages'
Added package 'xunit.core.2.2.0-beta3-build3350' to folder 'C:\repo\cacheprototype\packages'
Added package 'xunit.core.2.2.0-beta3-build3350' to 'packages.config'
Successfully installed 'xunit.core 2.2.0-beta3-build3350' to AzCache.Config.Tests
```

**Comment by rrelyea** [comment] 2016-09-19 17:42
Sounds like this may be a problem with 3.5.0-rc1 era work on filesystem/network based sources.
Please confirm this is a regression from 3.4.4. If it isn't we may not want the risk of bringing to 3.5.0-rtm.

**Comment by jainaashish** [comment] 2016-09-19 20:30
Issue is with Update-Package command only and its reproing with 3.4.4, 3.5.0-rc1 branches. It works fine with nuget 2.x in vs2013

**Closed as completed** 2016-09-21 16:36 UTC
Labels: Product:VS.Client, Type:Bug

**Comment by jayaramdas** [comment] 2018-02-13 10:16
![image](https://user-images.githubusercontent.com/36440245/36143858-4b8280da-10d2-11e8-8a98-2a6ed4fed190.png)

Hi i am working on xamarin cloud test, I am trying to push the code/script/file  into cloud by using package manager console.
after opening PM> used to " appcenter login" login command  and Authentication succeeded code is opened in new window.
But unable to code code and paste in package manager console. As shown in image.
please help to solve problem.

**Comment by jayaramdas** [comment] 2018-02-13 10:28
I am trying in Visual Studio Enterprise 2017 trial version
