### ISSUE TITLE
Is the (global) packages folder structure stable (packageName\packageVersion)?

### ISSUE THREAD

**Issue by ohadschn** [NuGet/Home#9820] opened 2020-07-20 16:54 UTC
The (global) packages folder has a structure in the form of `packageName\packageVersion`, e.g.:
* `C:\packages\Foo.Package.Name\1.2.3`
* `C:\packages\Bar.Package.Name\4.5.6`

Can we rely on this structure in build scripts and the like?
(I am aware of `GeneratePathProperty`, I need this outside of MSBuild context)

In case the folder structure above is part of the NuGet contract/spec and is stable, I suggest it is documented clearly.

**Comment by dominoFire** [comment] 2020-07-27 17:38
Yes, that's a V3 folder structure.

For more info, see https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds

I will close this issue since it's not a bug. If you need more help, feel free to reach to us.

**Closed as completed by dominoFire** 2020-07-27 17:38 UTC
Labels: Resolution:Question, Area:Protocol

**Comment by ohadschn** [comment] 2020-07-28 18:11
@dominoFire thank you for confirming, and I appreciate the link, but those are not exactly the docs I was aiming for. True, local feed folder structure is clear per the link you've provided, but where does it say that when I do `nuget restore` / `nuget install` I'd get the exact same structure locally in my packages folder?
