### ISSUE TITLE
dotnet restore fails with 'Value cannot be null'

### ISSUE THREAD

**Issue by noahfalk** [NuGet/Home#2960] opened 2016-06-13 01:26 UTC
Repro:

```
Usng bash on an OSX machine...
dotnet --version
1.0.0-preview1-002702
mkdir hwapp
cd hwapp
dotnet new
unset HOME
dotnet restore
```

Expected behavior:
Either give a nice error message or calculate settings without falling back to $HOME\.nuget\NuGet.Config

Actual behavior:

```
dotnet restore
error: Value cannot be null
error: Parameter name: path1
```

For background this isn't a hypothetical machine configuration. I have confirmed in the dotnet organization's CI pool of OSX machines at least one of them is missing the HOME environment variable, and evidence suggests that many of them are in this state. Whether they are in this state due to misconfiguration I don't know, but without a good error message it isn't easy to root cause this issue.

**Comment by noahfalk** [comment] 2016-06-13 06:36
I noticed some additional behavior that made me suspect the bug is in dotnet itself (dotnet build also fails the same way). Feel free to resolve this as external if you believe its solely a dotnet issue.

**Comment by emgarten** [comment] 2016-06-13 18:02
This error is likely thrown from `Path.Combine()`, NuGet should check for this scenario and throw a helpful error message.

**Comment by emgarten** [comment] 2016-06-13 18:04
@noahfalk if you are unable to set home and need another way to around this you may set the `NUGET_PACKAGES` environment variable to provide the package folder path.

**Comment by noahfalk** [comment] 2016-06-13 21:32
Thanks, the NUGET_PACKAGES is exactly the solution I found when poking around : ) Do you know if that env var is officially supported or am I just taking a gamble when I use that?

**Comment by emgarten** [comment] 2016-06-13 23:13
I would consider it officially supported, let me know if you find any scenarios where it doesn't work.

**Comment by noahfalk** [comment] 2016-06-13 23:27
Will do. At this point I can report no issues - it is working just how I hoped it would. Thanks!

**Comment by emgarten** [comment] 2017-11-30 00:21
Duplicate of https://github.com/NuGet/Home/issues/4671

**Closed as completed by emgarten** 2017-11-30 00:21 UTC
Labels: Resolution:Duplicate
