### ISSUE TITLE
[Test Failure] The installed package version show in ‘packages.config’ is inconsistent with that in PMC or PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4293] opened 2017-01-16 08:40 UTC
**NuGet Version:** NuGet 4.0.0-RC3-2215
**VS Version:** D15Rel 26115.00
**OS Version:** Windows 10 RS1_Release 14393.726.170112-1758
 
**Repro Steps:**
1.  Create a Visual C#->WCF->WCF Service Application template via VS.
2.  Right-click on the project and click ‘Manage NuGet Packages…’.
3.  Open ‘Browse’ tab and type ‘WCF’ in the search filter.
4.  Install package ‘WCF’ (version is 1.0.0 in PM UI) and select ‘Packages.config’ as package management format.
5.  Open ‘packages.config’ and check the installed package version.

**Expected Result:**
The installed package version show in ‘packages.config’ is consistent with that in PMC or PM UI

**Actual Result:**
The installed package version show in ‘packages.config’ is inconsistent with that in PMC or PM UI as below screenshot.
![versioninconsistence](https://cloud.githubusercontent.com/assets/20632625/21975843/f6c09850-dc09-11e6-8a9e-03166e7af9cb.png)

**Note:**
1. It also repro for package ‘Wcf.AttributeValidation’ and package ‘WCF.Validation.Engine’.
2. It also repro on Dev14 MU3.5 25421.01+NuGet 3.5.0-RTM-1938.
3. It also repro on Dev14 MU3.5 25421.01(NuGet 3.4.4.1321). 
4. It also repro on D15Rel 26115.00+Nuget 4.0.0-RTM-2217.

**Comment by zhili1208** [comment] 2017-11-09 18:31
close it , this is by design

**Closed as completed by zhili1208** 2017-11-09 18:31 UTC
Labels: Resolution:ByDesign, Functionality:VisualStudioUI
