### ISSUE TITLE
[Test Failure] Error “The SVsNuGetRecommenderService service is unavailable” occurred when loading the package list in Browse tab of Blend WPF App (.Net Framework) project PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9960] opened 2020-08-31 12:29 UTC
## Details about Problem
NuGet version: NuGet Client Dev\5.8.0.6801
VS Version: Main\30430.19
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1.	Create a C# WPF App (.Net Framework) project in Blend for Visual Studio.
2.	Open the PM UI of the project (package source is nuget.org) and go to the “Browse” tab.
## Expected
No error occur.
## Actual
Error “The SVsNuGetRecommenderService service is unavailable” occurred as below.
![image](https://user-images.githubusercontent.com/20632625/91719775-7e1c6c80-ebc8-11ea-8c07-66686b5a7a8b.png)
## Notes
1. It doesn’t repro on solution PM UI of the same project.
2. It only repro on Blend, doesn’t repro on VS WPF App (.NET Framework) project.
3. It is weird that it only start to repro for me from NuGet Client Dev\5.8.0.6783, not repro for others with the same repro steps.

**Comment by zkat** [comment] 2020-08-31 20:57
Possibly related to https://github.com/NuGet/Home/issues/9959. Might be a MEF-related regression?

**Comment by heng-liu** [comment] 2020-09-01 00:41
I couldn't repro with the following:
internal preview channel: VS 16.8.0 Preview 3.0 [30431.6.main](latest dogfooding) + NuGet Client Dev\5.8.0.6801
public preview channel : VS 16.8.0 preview 2.1 + NuGet Client Dev\5.8.0.6801

Hi, @v-luzh could you help check if it still repro on latest VS? Thanks!

**Comment by v-luzh** [comment] 2020-09-01 02:52
Hi @heng-liu , I still can repro on main\30431.43 + NuGet Client Dev\5.8.0.6801 as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/91789379-1e15dc80-ec41-11ea-8d2f-73bcb1475943.png)

**Comment by heng-liu** [comment] 2020-09-01 17:24
@v-luzh , thanks for your reply!
But I still failed to repro. Could you pls check if anything is incorrect in the following repro? Thanks!

I tried VS Enterprise (Branch Channel)  in the link https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4026264&view=ms.vss-build-web.run-extensions-tab 
![image](https://user-images.githubusercontent.com/45407901/91879570-e5700600-ec34-11ea-818b-76c74cd496c3.png)

And my repro steps are:
1.install VSIX from NuGet Client Dev\5.8.0.6801
2.launch vs, open or create a WPF App(.NETFramework)
3.right click on the WPF project in step2, choose "design in blend"
4.in blend, File -> close solution, create a new WPF App(.NETFramework)
5.making sure nuget.org is the pacakge source 
6.right click the new WPF App project, choose "manage NuGet Packages.."
7.go to "Browse"tab
The result is the normal list of packages:
![image](https://user-images.githubusercontent.com/45407901/91885619-f290f300-ec3c-11ea-8571-7bca5c4178e3.png)

**Comment by v-luzh** [comment] 2020-09-02 01:51
@heng-liu, I can repro it on my VM (main\30431.43+NuGet Dev\5.8.0.6805) following your steps.
![image](https://user-images.githubusercontent.com/20632625/91922889-a8be1080-ed01-11ea-940c-5e39d00eaad0.png)
And I can repro it on the **new created** VM with main\30501.218, both repro on the blend before and after installing NuGet Dev\5.8.0.6806 as below. The first scenario is to verify the issue so it is not impacted by other option.
![image](https://user-images.githubusercontent.com/20632625/91943045-87bfe480-ed2e-11ea-80d8-a4a99bd56d37.png)
****
Could you please try ignoring the step1~step3, directly verify from step4?

**Comment by heng-liu** [comment] 2020-09-03 07:12
Thanks @v-luzh 
I tried to start from step4. But I still couldn't repro.
May I know which link did you use to install VS from, eg: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4026264&view=ms.vss-build-web.run-extensions-tab
I used the  VS Enterprise (Branch Channel) link.

**Comment by v-luzh** [comment] 2020-09-03 08:37
Hi @heng-liu, Yes the link we used is same with yours:  	
Install VS Main\30431.43 from https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4026264&view=ms.vss-build-web.run-extensions-tab. We used the VS Enterprise (Preview Channel) link.

**Comment by rrelyea** [comment] 2020-09-03 17:22
This repros for me with intpreview latest - 16.8 p3 30503.9 main
This feature (PackageRecommender) has been checked in for a while...and is behind an a/b switch. (there is a regkey to turn it on/off as well)
It only works in Packages.config projects today.
As such, we need to investigate, but it doesn't block insertions, because it is already inserted.
@birgithi will likely investigate next week, as she is OOF this week.

**Comment by heng-liu** [comment] 2020-09-03 18:35
Thanks @rrelyea !
I tried VS Enterprise (Preview Channel) link just now, but still couldn't repro...
Is that because I'm in a different group with you and Jamie on the a/b switch?

**Comment by birgithi** [comment] 2020-09-08 18:06
I was able to repro this in Microsoft Visual Studio Enterprise 2019 Int Preview Version 16.8.0 Preview 4.0 [30508.10.main]
I will investigate.

**Closed as completed** 2020-09-16 22:29 UTC
Labels: Priority:1, Type:Bug, Triage:Investigate, RegressionDuringThisVersion

**Comment by rrelyea** [comment] 2020-09-16 22:38
Merged it to dev. Should make it into next week's insertion into 16.8 Preview 4.

**Comment by v-luzh** [comment] 2020-09-21 09:13
It is fixed on both D16.8\30516.212 & Main\30517.154.
