### ISSUE TITLE
[Feature]: CentralPackageTransitivePinningEnabled should work with the newest Version of the SDK

### ISSUE THREAD

**Issue by opheoHeidrich** [NuGet/Home#11668] opened 2022-03-11 10:30 UTC
### NuGet Product(s) Involved

NuGet SDK

### The Elevator Pitch

The Microsoft.Build.CentralPackageVersions SDK has a new version with breaking changes in their syntax. There is code in NuGet to use these package-versions if the CentralPackageTransitivePinningEnabled property is true, but the processing code only works for the old syntax of the Microsoft.Build.CentralPackageVersions SDK. I would like to use the new syntax and CentralPackageTransitivePinningEnabled together.

### Additional Context and Details

NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.GetCentralPackageVersions checks for PackageVersion items, but the new syntax uses "PackageReference Update" instead of "PackageVersion Include".

https://github.com/NuGet/NuGet.Client/pull/4025

**Comment by opheoHeidrich** [comment] 2022-03-11 11:02
@jeffkl ping

**Comment by jeffkl** [comment] 2022-03-11 16:42
`Microsoft.Build.CentralPackageVersions` is a completely different implementation of central package management.  Currently, the built-in NuGet implementation is not compatible.  In the future, we'll probably make a migration tool to move from `Microsoft.Build.CentralPackageVersions` to stock NuGet.  At the moment, there is no way for `Microsoft.Build.CentralPackageVersions` to pin transitive versions since its only knows about what top-level packages have been specified.  Since NuGet's central package management uses a different item, `PackageVersion`, its able to pin transitive versions as the dependency graph is resolved.

**Comment by opheoHeidrich** [comment] 2022-03-14 10:05
Hello @jeffkl , thank you for the fast response. I will migrate my code to use the implementation from NuGet using `PackageVersion`. I think it would be good to mention in the `Microsoft.Build.CentralPackageVersions` readme and the documentation ([#2674](https://github.com/NuGet/docs.microsoft.com-nuget/issues/2674)), that CentralPackageTransitivePinningEnabled will not be supported with the sdk-style.

**Comment by jeffkl** [comment] 2022-03-17 18:21
Closing as by design.  Our documentation should clear up confusion once the feature ships.

**Closed as completed by jeffkl** 2022-03-17 18:21 UTC
Labels: Type:Feature, Resolution:ByDesign
