### ISSUE TITLE
Nuget restore on VS solution open throws exceptions

### ISSUE THREAD

**Issue by RobSwDev** [NuGet/Home#8302] opened 2019-07-04 10:16 UTC
OS version: Win 10 Enterprise (1709) 16299.1217
Visual Studio 2017 15.9.13

We recently changed our projects to the sdk-style format (excluding 3 Winforms projects). Since the change, Nuget restore throws several exceptions when opening the solution.
(I understand that Nuget restore is called automatically when the solution opens if you have sdk-style projects)

Error occurred while restoring NuGet packages: System.InvalidOperationException: The operation failed as details for project XYZZY  could not be loaded.
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__6.MoveNext()

Manual restore (via the solution context menu) is disabled for 60-90 seconds while this happens, but after that, manual restore is very fast (everything is up to date).
If I close and open the solution, it happens again, despite the fact that nothing has changed.

We have 150 projects in our solution. The nuget exception always occurs on project XYZZY for me (though a colleague sees different projects). This project is a very simple one, with 1 nuget dependency (that every project has) and 1 project dependency.

**Comment by nkolev92** [comment] 2019-07-08 19:19
@RobSwDev 

What I assume is happening here is the following. 
NuGet waits for the projects to be loaded and restore when ready. If the projects don't load on time, NuGet will nevertheless try to restore. 
Once all the projects are finally loaded, NuGet likely runs another restore, and then that's the reason why everything simply works later. 

I'd imagine this is a duplicate of https://github.com/NuGet/Home/issues/6558.  

//cc @dtivel This is related to solution load of SDK based projects. 

Any further information we could use from the customer?

**Comment by RobSwDev** [comment] 2019-07-12 07:49
@nkolev92 

We want to move to the new SDK project format as a subset of our solution needs to multi-target.
(Also, the new format is much slicker, less maintanance, and we expect will suffer fewer git conflicts when merging)

The concern is developer experience. The exceptions themselves aren't particularly bothersome, but we're also seeing slower compilation times, less responsive Visual Studio, and worst of all, unnecessary recompilation. I reported the exceptions because they may be connected, but also because they're objective - we have a stack trace. Whereas performance is somewhat subjective.

E.g. Starting from a clean checkout, and building the same dev project twice. The second build should be a no-op, but often wth the sdk format, it rebuilds most of the projects. 

Happy to provide any diagnostics that may prove useful.

**Comment by nkolev92** [comment] 2019-07-16 17:55
Hey @RobSwDev 

That's a problem space we're actively investing in and goes beyond NuGet. The NuGet specific one is unfortunately compounded by potential slowness in other components. 

We're actively investigating all possible improvements.

If you are seeing particular problems with build, I'd recommend filing a feedback issue via the Report a Problem dialog in VS. 

For now I'll close this issue as a dupe, as NuGet's particular problem has already been reported on.

**Closed as completed by nkolev92** 2019-07-16 17:55 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Tenet:Performance, Functionality:Restore, Partner:Project-System
