### ISSUE TITLE
Author primary signing certificate not trusted

### ISSUE THREAD

**Issue by vjj9** [NuGet/Home#13004] opened 2023-11-09 17:20 UTC
Hello,

I am facing a certificate invalid error when building a Windows docker image. Retires work sometimes but this has become a trend. A couple of them work but again they start failing for a few hours, then they work again.
The error occurs for different packages. Most of the time, it was for the cryptography ones below but this time, it was for 'Newtonsoft.Json 13.0.3'. The certificate is valid but I am still getting the error. 

**Logs below**:

 Package 'Newtonsoft.Json 13.0.3' from source 'https://api.nuget.org/v3/index.json': 
  Signature type: Author
  Package 'Newtonsoft.Json 13.0.3' from source 'https://api.nuget.org/v3/index.json':   Subject Name: CN=Json.NET (.NET Foundation), O=Json.NET (.NET Foundation), L=Redmond, S=Washington, C=US, SERIALNUMBER=603 389 068, OID.1.3.6.1.4.1.311.60.2.1.2=Washington, OID.1.3.6.1.4.1.311.60.2.1.3=US, OID.2.5.4.15=Private Organization
  Package 'Newtonsoft.Json 13.0.3' from source 'https://api.nuget.org/v3/index.json':   SHA256 hash: D60F9A9BD35829CCF4684D4B1E0B62EB3D982FCD55159F337348BB18EA25B8A7
  Package 'Newtonsoft.Json 13.0.3' from source 'https://api.nuget.org/v3/index.json':   Valid from: 8/12/2021 7:00:00 PM to 10/29/2024 6:59:59 PM

  Package 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json': 
  Signature type: Repository
  Package 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json':   Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  Package 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json':   SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
  Package 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json':   Valid from: 4/9/2018 7:00:00 PM to 4/14/2021 7:00:00 AM
C:\###.Services.csproj : error NU3018: Package 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's signing certificate is not trusted by the trust provider. [C:\src\###.Web.csproj]
C:\###.Services.csproj : error NU3037: Package 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [C:\src\###Web.csproj]
C:\###.Services.csproj : error NU3028: Package 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider. [C:\src\###.Web.csproj]

**Docker Image used**:
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

Going through the forums, one suggestion was to try ENV DOTNET_NUGET_SIGNATURE_VERIFICATION=false. This didn't work either.

We are running on dotnet 6.0.4

Any input is appreciated.

**Comment by jebriede** [comment] 2023-11-10 00:43
@vjj9 This looks like a duplicate of https://github.com/NuGet/Home/issues/12987.
Please add a 👍reaction to upvote that issue.

Please take a look at the resolution proposed in the comment https://github.com/NuGet/Home/issues/12987#issuecomment-1796288533. As mentioned in that comment, you may need to try different retry values that work best for your scenario. Thanks!

**Closed as completed by jebriede** 2023-11-10 00:43 UTC
Labels: Resolution:Duplicate, Type:Bug

**Comment by danhnguyen2000** [comment] 2024-10-30 06:40
go to Option -> Nuget Package Manager -> Package Sources -> Add new package and paste "https://nuget.org/api/v2" to Source field, the name is any no matters.
