### ISSUE TITLE
Dependency packages are not resolved from secondary sources

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#4768] opened 2017-03-08 06:23 UTC
I faced the below problem while install the custom NuGet package with the dependency package Jquer.Validation.1.16.0 from the custom feed link in the VS2017.

**Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to find metadata of Microsoft.jQuery.Unobtrusive.Ajax.3.2.3			0**	

This package installed successfully while tried from the Package manager console. I faced this problem only tried from Manage NuGet packages option from the project in VS2017.

Please help me to resolve this problem

Thanks,
Ganesan R.

**Comment by emgarten** [comment] 2017-03-08 06:32
@GanesanRengasamy can you share the package source URLs you are using?

**Comment by GanesanRengasamy** [comment] 2017-03-08 06:35
Hi @emgarten 

The below feed I have used for Install the package.
http://nuget.syncfusion.com/aspnet

Thanks,
Ganesan R.

**Comment by emgarten** [comment] 2017-03-08 06:40
@GanesanRengasamy try using ``https://api.nuget.org/v3/index.json``

**Comment by GanesanRengasamy** [comment] 2017-03-08 06:47
I tried like this.

![image](https://cloud.githubusercontent.com/assets/16695209/23693151/025ad524-03f9-11e7-9076-479810fd4c65.png)

But I have the same problem. please let me know if I misunderstood anything.

Thanks,
Ganesan R.

**Comment by emgarten** [comment] 2017-03-08 06:48
@GanesanRengasamy uncheck the box next to ASPNET, it appears that source is causing problems for you.

Also, check the box next to *Microsoft Visual Studio Offline Packages*

**Comment by GanesanRengasamy** [comment] 2017-03-08 06:56
Like this
![image](https://cloud.githubusercontent.com/assets/16695209/23693418/6df6aea6-03fa-11e7-95c9-3e4197de8ec0.png)

**Comment by emgarten** [comment] 2017-03-08 07:00
@GanesanRengasamy check the bottom box also under Machine-Wide

**Comment by GanesanRengasamy** [comment] 2017-03-08 07:08
Okay. It's installed with the given source. but I have asked why we cannot installed the another source packages with the dependency Microsoft.jQuery.Unobtrusive.Ajax. For example,

I faced the problem when I tried the Syncfusion.JavaScript package from the source http://nuget.syncfusion.com/aspnet with dependency jQuery , jQuery.Validation , Microsoft.jQuery.Unobtrusive.Ajax , Microsoft.jQuery.Unobtrusive.Validation. 

![image](https://cloud.githubusercontent.com/assets/16695209/23693756/136e9ec4-03fc-11e7-9783-e0f50a753564.png)

**Comment by emgarten** [comment] 2017-03-08 07:25
@GanesanRengasamy try setting your package source to All, however dependencies should be taken from any available source so it isn't clear what you are hitting here.

**Comment by GanesanRengasamy** [comment] 2017-03-08 07:35
Yes now issue resolved. **Is this the Known issue**. Because this issue occurred in VS2017 only. In another VS I have tried with setting the particular packages source, the package installed successfully.

Is any bug on VS2017?

**Comment by emgarten** [comment] 2017-03-08 07:49
Currently there are no issues for this. Can you describe the steps that worked in VS 2015 and what works in VS 2017. And what doesn't work in VS 2017.

**Comment by GanesanRengasamy** [comment] 2017-03-08 08:35
Please find the details for what works in VS2017 and what doesn't works in VS2017



VS Version |	Working Steps |	Doesn’t work steps|
-|-|-|
VS2015 |	1.	Packages installed successfully while setting the packages source with particular source and from the package manager console	|     Nil|
VS2017 |	1.	Packages installed successfully when tried from the package manager console   2.	Packages installed with setting the packages source as ALL  |	1.	Packages doesn’t installed when tried with setting the Packages source as particular source and faced the below problem. **Severity	Code	Description	Project	File	Line	Suppression StateError		Unable to find metadata of Microsoft.jQuery.Unobtrusive.Ajax.2.0.20505			0**|

**Comment by GanesanRengasamy** [comment] 2017-03-08 09:14
Hi @emgarten 

If this is known issue Please update the details.

Thanks,
Ganesan R.

**Comment by emgarten** [comment] 2017-03-09 00:58
I verified that dependencies are not found in non-selected sources in 4.0.0. This is a regression from 3.5.0.

@rrelyea we should consider this for 4.1.0

**Comment by GanesanRengasamy** [comment] 2017-03-10 05:18
@emgarten  Is this bug from nuget.org or from secondary sources?

**Comment by emgarten** [comment] 2017-03-10 16:46
@GanesanRengasamy the issue is with the nuget client in Visual Studio.

**Comment by zhili1208** [comment] 2017-03-17 21:56
merged to dev and 4.1 https://github.com/NuGet/NuGet.Client/commit/c361e1fe40e2955032e328296768e94a70c234cb

**Closed as completed by zhili1208** 2017-03-17 21:56 UTC
Labels: Product:VS.Client, Type:Bug, Functionality:Install, RegressionFromPreviousRTM

**Comment by johntiger1** [comment] 2018-01-16 18:00
Also having this issue; I have a local nuget feed (on company intranet) and I cannot pick it up, despite setting Package Sources to "All"

**Comment by emgarten** [comment] 2018-01-16 18:47
@johntiger1 check that you are using the latest version of NuGet and open a new issue if you are still seeing this. This particular issue has been fixed.

**Comment by johntiger1** [comment] 2018-01-17 15:34
Hi, thanks for the response. I got it to work with two caveats:

- I had to "Clear All NuGet caches"

![image](https://user-images.githubusercontent.com/14852840/35050868-cc4c8ed4-fb71-11e7-9d76-b53422c7c19c.png)

- I can't pick up any pre-release versions (even when no dependency version is specified), so I will have to create a production version of the package.

**Comment by json1982** [comment] 2019-07-29 15:16
This still seems to be an issue when adding nuget packages from the package manager console

**Comment by dsimoes** [comment] 2019-09-11 13:32
I'm also "suffering" from the same issue it seems. Using VS 2017 15.9.6 with Nuget Package Manager 4.6.0.

Two sources: nuget and sitecore.

I install a sitecore package that has nuget repo dependencies. All goes well.
When I try to reinstall project packages using Update-Package -reinstall I well get an error:

Update-Package : Unable to resolve dependency 'EnterpriseLibrary.TransientFaultHandling.Caching'. Source(s) used: 'nuget.org', 'Sitecore', 'Microsoft Visual Studio Offline Packages'.

Is there any solution to this? Would using VS 2019 with a more recent version of nuget help?
