### ISSUE TITLE
[SSL/Transport Error] Unable to restore master branch with 5.0.100-rc.1.20379.10

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#9893] opened 2020-08-10 22:41 UTC
---
**Issue moved from dotnet/aspnetcore#24722**
- Please respond to @tebeco.

---

_From @tebeco on Sunday, August 9, 2020 6:51:32 PM_

Hello everyone ;)

### Describe the bug
As I am trying to restore the repository I'm hit by

```
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json.
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception.
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error :    Received an unexpected EOF or 0 bytes from the transport stream.
```

![image](https://user-images.githubusercontent.com/2266487/89739398-a4933000-da80-11ea-8fb8-a45c1d7923f1.png)

It's the second day in a row it happens, and only at the end of the say, not sure if it's related to an outage or a cache somewhere, or ISP ...
The workaround described bellow only worked for less than 24h I would say, and worked again today

### To Reproduce
Follow the docs :
https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md
```
> mkdir temp1234
> cd temp1234
> git clone --recursive https://github.com/dotnet/aspnetcore
> cd aspnetcore

> ./eng/scripts/InstallVisualStudio.ps1 -Channel Preview
> npm i -g yarn
> ./restore.cmd
fails
```
I've just update Windows Insider Dev channel, and I hope there's nothing broken about Certificate :D
Hello everyone ;)

### Describe the bug
As I am trying to restore the repository I'm hit by

```
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json.
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception.
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error :    Received an unexpected EOF or 0 bytes from the transport stream.
```

### To Reproduce
Follow the docs :
https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md
```
> mkdir temp1234
> cd temp1234
> git clone --recursive https://github.com/dotnet/aspnetcore
> cd aspnetcore

> ./eng/scripts/InstallVisualStudio.ps1 -Channel Preview
> npm i -g yarn
> ./restore.cmd
fails
```
I've just update Windows Insider Dev channel, and I hope there's nothing broken about Certificate :D

### More digging
It seems to fail on `dotnet tool restore` (At first)
Yesterday I had the exact same issue
* ran `dotnet tool restore`  => takes VERY LONG TIME => same error
* deleted `global.json` => `dotnet tool restore` => went weird because `dotnet/arcade`
* `dotnet nuget locals --clear all` => same issue

### Workaround
Editing `global.json` to use `preview7` (because, well I also use `preview7` on side project)
From:
```json
{
  "sdk": {
    "version": "5.0.100-rc.1.20379.10"
  },
  "tools": {
    "dotnet": "5.0.100-rc.1.20379.10",
...
```
To preview7
```json
{
  "sdk": {
    "version": "5.0.100-preview.7.20366.6"
  },
  "tools": {
    "dotnet": "5.0.100-preview.7.20366.6",
```

At that time `restore.cmd` works and if I `git checkout global.json` and re-run `restore.cmd` it works again.
I don't get it

### Further technical details
- ASP.NET Core version
  `master` (commit `983e7ed635f4d128edce4191b51869bd7be8aced`)

- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/2266487/89739414-d3a9a180-da80-11ea-8d67-4474d1dc68db.png)

### Further technical details
- ASP.NET Core version
  `master` (commit `983e7ed635f4d128edce4191b51869bd7be8aced`)

- Include the output of `dotnet --info`

**Comment by tebeco** [comment] 2020-08-10 23:10
thx @pranavkm was not sure where to ask TBH

**Comment by jkotalik** [comment] 2020-08-11 17:20
@tebeco I'm also hitting this as well! Glad it's not just me 😄

**Comment by tebeco** [comment] 2020-08-11 17:22
ooooo I'm not crazy either :D

As 2020 is a fun year in term of TLS, and sometime OS does try to help you, are you also on Windows Insider ?
(I mean I have no idea how it does interact at all Client <=> Server except the fact that we were hit about TLS1.2 and deprecated cipher on Windows 2012 R2 last week..., so this might look like a stupid question, but that came to my mind)
![image](https://user-images.githubusercontent.com/2266487/89928313-eef2e900-dc07-11ea-8cac-78721581df97.png)

**Comment by jkotalik** [comment] 2020-08-11 17:34
I am, same exact build of windows as well, I honestly was thinking the same thing yesterday:
![image](https://user-images.githubusercontent.com/8302101/89929460-158c3200-dbbe-11ea-94a7-0bf4816ac76b.png)

Maybe an issue with schannel? That's my best guess.

**Comment by tebeco** [comment] 2020-08-11 17:34
🦆

**Comment by Tratcher** [comment] 2020-08-11 17:36
Same issue, same OS build.

**Comment by tebeco** [comment] 2020-08-11 17:51
the weird thing is the work I dont get is why 
* changing the `global.json` to the `preview7` 
* run a full `./restore.cmd`
* reset file
* `./restore.cmd` is ok

I would assume cache ? but this also means that this is a combo of both `windows` + `dotnet 5.0 rc1`

**Comment by zivkan** [comment] 2020-08-11 18:07
A few weeks ago I created this gist which is a little program that tests .NET's `HttpClient`'s ability to connect to api.nuget.org: https://gist.github.com/zivkan/5291f507c8c5724d41a18357b7afcd30

Since you're reporting using the .NET 5 SDK, try editing the csproj and add `net5.0` as a target framework, and run the tool against the various target frameworks.

If the BCL's `HttpClient` can't connect to api.nuget.org when using `SslProtocols.None` (this means use operating system defaults, not "don't use security"), then there's little that NuGet can do. If it can't connect with `SslProtocols.None` but does with `SslProtocols.Tls12`, then this means either your computer is configured not to use TLS 1.2 by default, or there's a bug lower level than NuGet. I've had one internal colleauge show me evidence that a .NET 5 preview failed to connect, while net472 did connect. If you experience the same issue, please let us know, I'll pass the info to the System.Net.Http team.

**Comment by Tratcher** [comment] 2020-08-11 18:22
Note the restore issue is intermittent. I run restore on our whole repo and it works for a random number of projects before hanging, timing out, and failing.

**Comment by tebeco** [comment] 2020-08-11 18:47
well, well, well

## net5.0
```
[20:44]❯ dotnet run
None failed  <==============
Ssl2 failed
Ssl3 failed
Tls failed
Default failed
Tls11 failed
Tls12 worked  <==============
Tls13 failed
```

## netcoreapp3.1
```
None worked <==============
Ssl2 failed
Ssl3 failed
Tls failed
Default failed
Tls11 failed
Tls12 worked  <==============
Tls13 failed
```

## net48
seems to be stuck on "restore" task for ~3min, but as I'm working within `dotnet/aspnetcore` to have the same CLI verion, I'm assuming the root cause is elsewhere
Then crash with same error
![image](https://user-images.githubusercontent.com/2266487/89943195-1fde1880-dc1e-11ea-936b-4c0ceeebcbef.png)
![image](https://user-images.githubusercontent.com/2266487/89943286-40a66e00-dc1e-11ea-9dfe-e9618cc7db04.png)

**Comment by zivkan** [comment] 2020-08-11 18:58
@tebeco have a look at this blog post, and make sure your machine doesn't have any registry keys that disable TLS 1.2: https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/

I'd be interested if you could try running the same app with `net472` to see if it behaves the same, or different.

**Comment by Tratcher** [comment] 2020-08-11 19:07
For net472 and netcoreapp3.1 only None and Tls12 work.

For net5.0 Tls12 works but None doesn't.

**Comment by tebeco** [comment] 2020-08-11 19:34
Yeah sorry, I should have cross target them all, my bad

**Comment by wfurt** [comment] 2020-08-11 19:46
I'm also on Windows 2004 build 20170 and 5.0.100-rc.1.20411.2
```
None worked
Ssl2 failed
Ssl3 failed
Tls failed
Default failed
Tls11 failed
Tls12 worked
Tls13 failed
```
There seems to be some unknot variation causing this.

**Comment by tebeco** [comment] 2020-08-11 19:49
what `TargetFramework` were you targetting ?
It fails for `net5.0` but not `netcoreapp3.1`
 
Also the Windows build having issue seems to be is `20185` not `20170`

**Comment by zivkan** [comment] 2020-08-11 20:06
I reported the problem to dotnet/runtime: https://github.com/dotnet/runtime/issues/40679

**Comment by Tratcher** [comment] 2020-08-13 19:56
Workaround available: https://github.com/dotnet/runtime/issues/40679#issuecomment-673675486

**Comment by aortiz-msft** [comment] 2020-08-24 20:28
Closing as dupe of dotnet/runtime#40679

**Closed as completed by aortiz-msft** 2020-08-24 20:28 UTC
Labels: Resolution:External, Resolution:BlockedByExternal, Area:Protocol, Partner:DotNet
