### ISSUE TITLE
UI Delay when reading Default Project in PMC

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#6824] opened 2018-04-13 00:13 UTC
Double clicking on a (un/staged) changed file in team explorer with git may randomly get VS to become &quot;busy&quot; (baloon tip) and sometimes changing window title to &quot;(not responding)&quot;. Hangs may last for a subjective eternity but probably something like 10~30s. Hangs usually do not reproduce immediately again (on the same file).

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/150268/visual-studio-155-may-hang-when-opening-diffs-from.html
VSTS ticketId: 524705_
_These are the original issue comments:_

Cytheria Ji (MSFT) on 11/15/2017, 07:10 PM (147 days ago): <p>Thank you for your feedback! </p><p>Could you please give us a dump file so that we can conduct further research? collecting dump file is very simple.</p><p>1. Start Visual Studio.</p><p>2. Start another instance of VS.</p><p>3. Select Help-&gt;Send Feedback-&gt;Report a problem.</p><p>4. Click &quot;Report new problem&quot; via &quot;+&quot;.</p><p>5. Record your actions to reproduce the issue.</p><p>6. In the list locate the first instance of VS and select 'Start Recording'.</p><p>7. Go back to the first instance and repro the issue.</p><p>8. Stop Record and the dump file could be found in the temporary folder in your local pc : %TEMP%\Microsoft\VSFeedbackCollector .</p><p>9. Upload the files to this ticket by choosing insert file tag on add comment field then submit after signing in.</p><p> We look forward to hearing from you!</p>

Cytheria Ji (MSFT) on 11/30/2017, 06:04 PM (132 days ago): <p>Thank you for your feedback! Unfortunately, right now we don't have enough information to investigate this issue and find a solution. If this is still an issue for you, please update to our latest version. If you are still able to repro it, please provide us with more info! Thank you for helping us build a better Visual Studio!</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mishra14** [comment] 2018-04-13 00:14
@sharwell responded - 
Moving to the NuGet area path. The trace shows a 9.7 second hang evaluating this property:
https://github.com/NuGet/NuGet.Client/blob/e1625065971453ccabd11759faf53dac3c4d241d/src/NuGet.Clients/NuGetConsole.Host.PowerShell/PowerShellHost.cs#L250

**Comment by nkolev92** [comment] 2019-06-28 23:46
Fixed in https://github.com/NuGet/NuGet.Client/pull/2889. 

Duplicate of https://github.com/NuGet/Home/issues/8235

**Closed as completed by nkolev92** 2019-06-28 23:46 UTC
Labels: Product:VS.Client, Priority:2, Type:Bug, Tenet:Performance, Product:VS.PMConsole
