### ISSUE TITLE
[Bug]: dotnet nuget push fails on Linux using the Liquourix kernel

### ISSUE THREAD

**Issue by Nihlus** [NuGet/Home#12142] opened 2022-10-08 13:35 UTC
### NuGet Product Used

dotnet.exe

### Product Version

6.0.401 (commit 0906eae6f8)

### Impact

I'm unable to use this version

### Repro Steps & Context

When using `dotnet nuget push` on an Ubuntu system with the Liquorix kernel, the command fails with the following error message.

```
error: The format of value '(Linux 5.19.0-14.1-liquorix-amd64 #1 ZEN SMP PREEMPT_DYNAMIC liquorix 5.19-17ubuntu1~jammy (2022-1)' is invalid.
```

The issue apparently stems from the output of `uname -s -v -r` (or its functional equivalent) being problematic for the dotnet tooling. The problem does not occur on the standard LTS kernel.

### Verbose Logs

```shell
Pushing Remora.Sdk.1.1.1.nupkg to 'https://www.nuget.org/api/v2/package'...
error: The format of value '(Linux 5.19.0-14.1-liquorix-amd64 #1 ZEN SMP PREEMPT_DYNAMIC liquorix 5.19-17ubuntu1~jammy (2022-1)' is invalid.


Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  -h|--help                      Show help information
  --force-english-output         Forces the application to run using an invariant, English-based culture.
  -s|--source <source>           Package source (URL, UNC/folder path or package source name) to use. Defaults to DefaultPushSource if specified in NuGet.Config.
  -ss|--symbol-source <source>   Symbol server URL to use.
  -t|--timeout <timeout>         Timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  -k|--api-key <apiKey>          The API key for the server.
  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
  --no-service-endpoint          Does not append "api/v2/package" to the source URL.
  --interactive                  Allow the command to block and require manual action for operations like authentication.
  --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.
```

**Comment by nkolev92** [comment] 2022-10-17 20:55
Duplicate of https://github.com/NuGet/Home/issues/11995.

**Closed as completed by nkolev92** 2022-10-17 20:55 UTC
Labels: Resolution:Duplicate, Priority:2, Type:Bug, Functionality:Push, Product:dotnet.exe
