### ISSUE TITLE
<NoWarn>NU1701</NoWarn> ignored on project reference

### ISSUE THREAD

**Issue by Petermarcu** [NuGet/Home#5999] opened 2017-10-06 18:13 UTC
@mafalarz reported this issue here: https://github.com/dotnet/core/issues/869

<NoWarn>NU1701</NoWarn> ignored on project reference

Despite adding the` <NoWarn>NU1701</NoWarn>` on all my project reference like this:
```
<ProjectReference Include="..\Reports\Reports.csproj">
   <NoWarn>NU1701</NoWarn>
</ProjectReference>
```
I still get the warning message 

> NU1701: Package 'Teradata.Net.Data.Provider 15.11.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Also on publishing Nugget and adding <`NoWarn>NU1701</NoWarn` to my nugget package:

```
> <PackageReference Include="Carbon.ClientQueries" Version="0.0.1.16-Preview">
>       <NoWarn>NU1701</NoWarn>
> </PackageReference>
```
I keep getting warning: 

> NU1701: Package 'Teradata.Net.Data.Provider 15.11.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. 

I think this is because my nugget has a reference to a project reference of my solution like this:
![image](https://user-images.githubusercontent.com/30442378/29490081-a77ebd2c-84ff-11e7-8c6c-e2514d4e2b71.png)

**Comment by rohit21agrawal** [comment] 2017-10-09 21:24
@mishra14 can you take a look?

**Comment by mishra14** [comment] 2017-10-09 21:36
@mafalarz Thanks for reporting the issue. Let me answer the 2 cases that you are facing - 

1. Despite adding the<NoWarn>NU1701</NoWarn> on all my project reference....
We do not support adding NoWarn in a project reference. You should instead add a `<NoWarn>NU1701</NoWarn>` to `..\Reports\Reports.csproj`.

2. Also on publishing Nugget and adding <NoWarn>NU1701</NoWarn to my nugget package....
We do not currently support applying no warn to all the transitive dependencies of a package. We have another [issue](https://github.com/NuGet/Home/issues/5740) tracking that.. To fix this, you have 2 options - 
Add a Project wide NoWarn - 
```
  <PropertyGroup>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>
```
OR
Add a reference to Teradata.Net.Data.Provider with a NoWarn - 
```
<PackageReference Include="Teradata.Net.Data.Provider" Version="15.11.0.1">
     <NoWarn>NU1701</NoWarn>
</PackageReference>
```

Please let us know if you need any more help from us.

**Comment by ghost** [comment] 2017-10-09 22:00
@mishra14 Thanks for the workaround :)
I'll keep track of #5740 to see the outcome of the design change request

**Comment by mishra14** [comment] 2017-10-09 23:24
@mafalarz Thanks for getting back to us. I will close this issue as a dupe of  #5740

**Closed as completed by mishra14** 2017-10-09 23:24 UTC
Labels: Resolution:Duplicate, Type:Bug, Area:ErrorHandling
