### ISSUE TITLE
Assets from packages are missing after restore

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5995] opened 2017-10-06 03:04 UTC
Some users have reported that after restoring assets such as System.Runtime are missing from the assets file.

This is potentially caused by restore happening while the fallback folder is still being created. The problem is made much worse by how restore reuses file lists from previous restores for the next restore. To improve this experience restore should read the files from disk each time instead of from the previous assets file.

Note that if the fallback folder from the CLI is corrupt then this should be fixed there also.

See: https://github.com/dotnet/core/issues/920

**Comment by Petermarcu** [comment] 2017-10-07 03:42
Looks like this is getting hit by lots of users. https://github.com/dotnet/core/issues/1006 is another issue with multiple people saying they hit it.

**Comment by Petermarcu** [comment] 2017-10-09 00:47
Perhaps another ref count? https://github.com/dotnet/standard/issues/528

**Comment by Petermarcu** [comment] 2017-10-11 05:42
Another customer fixed with clearing the cache https://github.com/dotnet/standard/issues/439#issuecomment-335675299. Almost gave up on .NET Core.

**Comment by Petermarcu** [comment] 2017-10-11 06:10
/cc @rrelyea 

I'm not sure if they are all root caused in this issue or not but I'm seeing quite a trend of issues that appear to be cache corruption. Is this something we can try to get into the next possible NuGet update?

**Comment by Inumedia** [comment] 2017-10-13 12:32
Hi, I think this is related to the issue being described here?

After running `dotnet restore`, I did `dotnet run` and got thousands of lines of:
` error CS0518: Predefined type 'System.Object' is not defined or imported ` and various other `System` types.

Here's what the `dotnet restore` and the beginning of my `dotnet run` produces:
![image](https://user-images.githubusercontent.com/856822/31546301-62a0eb1c-afe8-11e7-86dd-106619920c26.png)

Here is the csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="morelinq" Version="2.8.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>

</Project>
```

I've also tried running `dotnet nuget locals all -c` and repeating, giving the same results.

**Comment by Petermarcu** [comment] 2017-10-13 19:32
Let's use this issue to also track this one: https://github.com/dotnet/core/issues/1028

**Closed as completed** 2017-10-20 00:55 UTC
Labels: Priority:1, Type:Bug, Functionality:Restore

**Comment by bjorn-ali-goransson** [comment] 2019-07-03 15:13
FWIW, a restart did it for me. $user$\.nuget\packages was inaccessible, couldn't even open it in explorer, so I did a restart and built and viola. 🎻

oh, and deleting C:\Program Files\dotnet\sdk\NuGetFallbackFolder did nothing.

**Comment by moonboy13** [comment] 2020-11-13 14:43
Hey guys, after the latest release of visual studio this week for .NET Core 5.0 this issue is coming back up. The remediation steps given here and in the linked posts are allowing us to keep limping along, but it is pretty arduous to have to continuously delete the obj folder and rebuild.

We are running on a Windows 7 professional instance due to a legacy component of our build, if that has any bearing on the problem. Let me know if you need any other diagnostics or would like me to open a new issue on this.

**Comment by aortiz-msft** [comment] 2020-12-18 01:48
@moonboy13 - Yes, it would be great if you could open a new issue with specific repro steps that we can try out.

**Comment by aabhishek1** [comment] 2024-07-30 11:30
Could anyone please let me know what is the fix for this. I am getting the same kind of error when upgrading my project from .net4.8 to .net8.0. 

Error Message:- "Package 'Microsoft.AspNet.Identity.Core 2.2.4' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0'. This package may not be fully compatible with your project."
