### ISSUE TITLE
linux subsystem (bash) windows 10 - fails to communicate network

### ISSUE THREAD

**Issue by den-run-ai** [NuGet/Home#4844] opened 2017-03-20 03:59 UTC
nuget 3.5.0, windows 10 build 15061:

https://github.com/Microsoft/BashOnWindows/issues/1265

**Comment by den-run-ai** [comment] 2017-03-20 03:59
Is there any work-around for this issue?

**Comment by zhili1208** [comment] 2017-03-21 00:28
I tried to work around this by specifying IP address, but it didn't work. the problem is httpclient can't resolve the host name. I don't think there is any workaround on nuget side.
@mrward

**Comment by bitcrazed** [comment] 2017-03-24 06:39
Could you try renaming your /etc/hosts file to, for example, hosts_old and then closing your bash shell and reopening? Your hosts file may have gotten corrupted/damaged

**Comment by devlead** [comment] 2017-03-24 07:19
@bitcrazed that doesn't help for me at least, basically I can curl both V2 & V3 nuget API and fetch the package, but `mono nuget.exe` fails with `Error: NameResolutionFailure` . 

Some suggested it's an IPv6 issue,  really old `mono 3.2.8` works but newer doesn't, and 4.8 and later is what's needed for current development.

**Comment by zhili1208** [comment] 2017-08-11 23:13
No fix for this can be made on nuget side, close it

**Comment by rrelyea** [comment] 2017-08-16 19:35
@zhili1208 - we should keep open until we have positive handoff to @mrward (or others), right?

**Comment by zhili1208** [comment] 2017-08-16 19:44
Yes, we can keep it

**Closed as completed** 2017-10-17 23:03 UTC
Labels: Type:Bug, Resolution:External, Platform:Mono
