### ISSUE TITLE
"Conflicting requests" error is confusing, does not lead to a solution

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#5631] opened 2017-07-22 18:03 UTC
This is a follow-up to #5630. The following is an error message observed during the build. I'm filing this as a separate issue due to the severity of this specific situation.

> Unable to satisfy conflicting requests for 'System.Collections.Immutable': System.Collections.Immutable (>= 1.1.37) (via package/Microsoft.CodeAnalysis.Common 1.2.1), System.Collections.Immutable (>= 1.1.37) (via package/Microsoft.CodeAnalysis.Common 1.2.1), System.Collections.Immutable (>= 1.1.37) (via package/Microsoft.CodeAnalysis.Common 1.2.1)

Given this error message, I was unable to proceed without expert assistance and/or trial and error approaches.

**Comment by anangaur** [comment] 2017-07-23 18:18
cc: @emgarten the warning just lists the same path 3 times. May be there is a conflict that could not be resolved through 3 different paths but output string is incorrectly framed?

**Comment by emgarten** [comment] 2017-07-26 05:25
After debugging https://github.com/NuGet/Home/issues/5630 I found the project is in a bad state when it fails to stop resolving during a circular dependency. This is causing the nonsensical conflict messages where all paths are the same.

Deduping this out in favor of the original root cause in https://github.com/NuGet/Home/issues/5630

**Closed as completed by emgarten** 2017-07-26 05:25 UTC
Labels: Resolution:Duplicate
