### ISSUE TITLE
[Watson] HANG: Microsoft.VisualStudio.ProjectSystem.VS.Implementation!ProjectConfigProviderBase.__c__DisplayClass39_0._Microsoft.VisualStudio.Shell.Interop.IVsCfgProvider2.GetCfgOfName_b_

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4209] opened 2017-01-06 01:42 UTC
Please see internal bug 296572 for details and heap dumps.

Just noticed that bug comments believe this is a dupe of CPS JTF issue -- #4185

**Comment by rrelyea** [comment] 2017-01-11 23:33
Moving to RTM, as it is a bit risky for last day of RC3. Justin has fix.

**Comment by emgarten** [comment] 2017-01-12 02:00
Dupe of #4185 as mentioned

**Closed as completed by emgarten** 2017-01-12 02:00 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug
