### ISSUE TITLE
Command “dotnet restore -f --use-lock-file” created a lock file for every project when the solution have project reference 

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9933] opened 2020-08-24 15:42 UTC
## Details about Problem
NuGet version: NuGet Client Dev\5.8.0.6783
VS Version: Master\30423.24
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1. Create a solution with two projects [e.g. C# Class Library (.NET Core 5.0)] called “CL1” and “CL2” in VS.
2. Make the project graph structure: CL1 -> CL2 and **close the solution/VS**.
3. Open “Developer Command Prompt”, cd to CL1 project path and input command “dotnet restore -f --use-lock-file”.
4. Open the solution and check the Solution Explorer.
## Expected Result
There is only one lock file created under project CL1.
## Actual Result
Command “dotnet restore -f --use-lock-file” created a lock file for every project as below.
![image](https://user-images.githubusercontent.com/20632625/91064083-63467700-e661-11ea-8dba-4f5a4aac928b.png)
## Note
It is a legacy issue, the key point to repro is closing solution/VS in step2.

**Comment by nkolev92** [comment] 2020-08-24 17:06
dotnet.exe & MSBuild.exe restore are transitive by default (meaning if you invoke them on the first project, they run for all projects. 

The parameters passed to the command when pointing to one project are applied to *all* projects since the arguments are passed as global properties. 

Key point here is that, I don't expect this to be a regression. I tried it with 3.1.302 and the behavior was the same as the one reported here. I would expect this has worked this way since the beginning. 

Closest related issue is: https://github.com/NuGet/Home/issues/7286

Logs from my repro

```console
C:\Users\Roki2\Documents\Code\test\lockFile\Parent [master]> git status                                                                                                                                                                      On branch master
nothing to commit, working tree clean
C:\Users\Roki2\Documents\Code\test\lockFile\Parent [master]> ls                                                                                                                                                                              

    Directory: C:\Users\Roki2\Documents\Code\test\lockFile\Parent


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        24-Aug-20   9:59 AM                obj
-a----        24-Aug-20   9:55 AM             83 Class1.cs
-a----        24-Aug-20   9:55 AM            228 Parent.csproj


C:\Users\Roki2\Documents\Code\test\lockFile\Parent [master]> dotnet restore -f --use-lock-file
  Determining projects to restore...
  Restored C:\Users\Roki2\Documents\Code\test\lockFile\Parent\Parent.csproj (in 117 ms).
  Restored C:\Users\Roki2\Documents\Code\test\lockFile\Child\Child.csproj (in 117 ms).
C:\Users\Roki2\Documents\Code\test\lockFile\Parent [master +2 ~0 -0 !]> git status                                                                                                                                                           On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../Child/packages.lock.json
        packages.lock.json

nothing added to commit but untracked files present (use "git add" to track)
C:\Users\Roki2\Documents\Code\test\lockFile\Parent [master +2 ~0 -0 !]> dotnet --version                                                                                                                                                     3.1.302
C:\Users\Roki2\Documents\Code\test\lockFile\Parent [master +2 ~0 -0 !]>
```

**Comment by nkolev92** [comment] 2020-08-24 17:07
Hey @v-luzh 

> It started to repro from NuGet Client Dev\5.8.0.6778.

Can you please verify whether this repros on older versions? I'd expect that it's always worked this way.

**Comment by nkolev92** [comment] 2020-08-26 01:11
[lockFile.zip](https://github.com/NuGet/Home/files/5126981/lockFile.zip)

I have added my repro project.

Note that I have a global.json that I used to test, and currently it pinned to 3.1.302

```json
{
  "sdk": {
    "version": "3.1.302"
  }
}
``` 

Given that this is a git enable repo, you can verify the behavior by just checking the status git detects.

**Comment by v-luzh** [comment] 2020-08-26 09:35
@nkolev92 It didn't repro on D16.8\30419.146+NuGet Dev\5.8.0.6776, but repro on D16.8\30420.98 with implicit NuGet Dev\5.8.0.6776 as below.
![image](https://user-images.githubusercontent.com/20632625/91287255-0dd5ab80-e7c2-11ea-95a9-ddd717ad3c80.png)

And no fails detected when unzipping your lockFile.zip on above both machines.

**Comment by nkolev92** [comment] 2020-08-26 21:08
@v-luzh 

I wouldn't expect anything to fail. 

Given the flakiness of it appearing in the solution explorer, can you please check the files on disk?
It's possible that the project-system is flaky detecting those files there. 

My primary goal was to determine whether this is a regression (which I don't think it is).

**Comment by v-luzh** [comment] 2020-08-27 02:22
Hi @nkolev92, I have checked the files on disk, they all pinned to 3.1.302 like what you showed above.

**Comment by v-luzh** [comment] 2020-09-03 08:31
Note: Closing the solution/VS in step 2 will repro this issue. The bug will not repro if you don't close the solution/VS in step2. And that's why we didn't run into the bug before. That's because we always execute the command with the solution opened in VS.

**Comment by v-luzh** [comment] 2020-10-27 07:38
Closing or not closing the solution/VS in step 2 will both run into this issue on D16.8\30623.59 + NuGet Client Release-5.8.x\5.8.0.6930.

**Comment by aortiz-msft** [comment] 2020-10-27 17:56
@v-luzh is this also true for 16.9?

**Comment by v-luzh** [comment] 2020-11-03 01:35
@aortiz-msft , Yes, it still repro on VS Main\30701.15 (that is 16.9 Preview2 now) + NuGet Client Dev\5.9.0.6951 following the steps.

**Comment by nkolev92** [comment] 2020-11-03 01:46
I want to come back to my point in an above comment:

> Given the flakiness of it appearing in the solution explorer, can you please check the files on disk?
It's possible that the project-system is flaky detecting those files there.


@v-luzh said:

> Hi @nkolev92, I have checked the files on disk, they all pinned to 3.1.302 like what you showed above.


I think my question was about the packages.lock.json. 

My expectation is that NuGet is doing the expected thing, and the only contentious point here is the project-system detecting the files. 

My proposal is to close this issue/move it to project-system side for them to investigate how the solution explorer is updated.

**Comment by nkolev92** [comment] 2023-09-25 20:58
Team Triage: Assigning to @nkolev92 to close out this issue and create the matching one on the project-system side.

**Comment by nkolev92** [comment] 2024-02-09 19:26
Closing as external: https://github.com/dotnet/project-system/issues/9395

**Comment by drewnoakes** [comment] 2024-02-11 23:21
Re-opening as this is not a request of the .NET Project System. It needs to be routed to CPS internally. Thanks.

**Comment by nkolev92** [comment] 2024-02-12 22:12
Moved to CPS: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1955425.

Thanks @drewnoakes

**Closed as not planned by nkolev92** 2024-02-12 22:12 UTC
Labels: Priority:2, Type:DCR, Resolution:External, Functionality:Restore, Product:dotnet.exe, Partner:Project-System, Found:ManualTests
