### ISSUE TITLE
Dotnet restore performs case sensitive Id lookups on flat-list local repositories when floating versions are used

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#2516] opened 2016-04-09 02:21 UTC
Repro: [Repro.zip](https://github.com/NuGet/Home/files/211073/Repro.zip). Reproed with dotnet 1.0.0-rc2-002337.

Noticed this in our build which referenced a Roslyn package. The package to restore was located in a flat list (v2-style) repository and it referenced it via incorrect casing (https://github.com/aspnet/Scaffolding/blob/dcbf31a7a209b6338cb6d6c3608a94d847d7ea70/src/Microsoft.Extensions.CodeGeneration.Utils/project.json#L7). This caused it to restore from the feed (where the casing doesn't seem to matter) rather than use the newer version available locally.

**Comment by yishaigalatzer** [comment] 2016-04-11 17:29
@joelverhagen please work with @pranavkm on this, and find the one other related bug

**Comment by joelverhagen** [comment] 2016-04-11 20:56
It looks like the issue is that we intentionally filter out nupkgs that do not have IDs that exactly match the project.json:
https://github.com/NuGet/NuGet.Client/blob/c7b2acdfd0f2594e3e796c5d3cfa86af62909794/src/NuGet.Core/NuGet.Protocol.Core.v3/LocalRepositories/LocalV2FindPackageByIdResource.cs#L109-L112

This is behavior is clearly inconsistent with the server and we should write our code so that it is case sensitive. I am going to close this particular bug as "by design" and open a new issue to make a broad effort to fix this up.
https://github.com/NuGet/Home/issues/2522

**Closed as completed by joelverhagen** 2016-04-11 20:56 UTC
Labels: Priority:2, Type:Bug, Resolution:ByDesign
