### ISSUE TITLE
nuget deleting packages

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1097] opened 2015-08-03 08:00 UTC
I have a common local repository for all my packages for all my projects.

however if I uninstall a PACKAGE FROM ONE PROJECT AND IT IS NO LONGER USED BY THAT PROJECT IT DELETES THE PACKAGE. EVEN THOUGH IM USING IT ON OTHER PROJECTS.

please don't delete the package if the repository is not within the project's folders.

(moved from https://github.com/NuGet/NuGetGallery/issues/2604 by @mgwalm)

**Comment by mgwalm** [comment] 2015-08-03 09:23
Why did you close it?

**Comment by maartenba** [comment] 2015-08-03 09:26
To move it here, where it is still open.

**Comment by mgwalm** [comment] 2015-08-03 09:50
Ok. Sorry I didn't understand.

-----Original Message-----

**Comment by maartenba** [comment] 2015-08-03 09:51
No worries, should have been more clear :)

**Comment by yishaigalatzer** [comment] 2015-08-06 01:33
@mgwalm can you provide more details? Do you have a single package folder for multiple solutions? What version of Visual Studio and NuGet are you using?

**Comment by yishaigalatzer** [comment] 2015-08-06 01:35
Thinking some more about it, if this is for the packages.config across multiple solutions scenario, I don't think we would fix it, if we did we would require adding a flag in global config for this behavior because most users do expect packages to go away and not sit there unnecessarily and waste disk space (when you have a folder per solution).

Moving forward with project.json we do support a global package folder where we will not delete packages, because it is shared by default.

Waiting for your feedback to prioritize and make a decision

**Comment by mgwalm** [comment] 2015-08-06 03:09
The config file already has an entry to specify a repository.
So its very easy if this is set don't delete the package.

It sounds much like what you are saying re the json version of the config file.

-----Original Message-----

**Comment by yishaigalatzer** [comment] 2015-08-06 04:20
My question is if your projects are using packages.config or is this an issue in visual studio 2013 and earlier?

**Comment by mgwalm** [comment] 2015-08-06 05:26
No its 2015

-----Original Message-----

**Comment by yishaigalatzer** [comment] 2015-08-06 05:31
And is the project using packages.config or project.json?

**Comment by mgwalm** [comment] 2015-08-06 07:36
I need to quote from my previous email:

 

The config file already has an entry to specify a repository.
So its very easy if this is set don't delete the package.

 

So im using the config file.

**Comment by yishaigalatzer** [comment] 2015-08-06 17:31
@mgwalm configs that change packages folder typically just move it up or down the folder structure, not necessarily share it across solutions. For now if you are sensitive to this issue, I suggest for now to avoid using this setting until this bug is fixed.

**Comment by yishaigalatzer** [comment] 2015-10-20 21:34
We don't plan to support this. It accidentally worked when you had repositories.config (which was an optimization for not accessing DTE), but was completely broken when the packages folder was restored from disk, and other solutions did not open yet.

Unfortunately I'm going to close this as won't fix/by design.

With project.json we are introducing a real global packages folder, where we will not delete the packages. it will take time until this propagates to all types of project.

**Closed by yishaigalatzer** 2015-10-20 21:34 UTC
