### ISSUE TITLE
[Test Failure]The package information can’t be added in ‘project.json’ file

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4743] opened 2017-03-03 10:07 UTC
**NuGet Version:** NuGet 4.3.0-beta1-2346 (Insertable)
**VS Version:** D15Rel 26228.00
**OS Version:** Windows 10 RS2_Release 15048.0.170228-1522

**Repro Steps:**
1.	New a Visual C#->Windows Universal->Blank App (Universal Windows).
2.	Right-click on the project and click ‘Manage NuGet Packages…’
3.	Install package 'Newtonsoft.Json 9.0.1'.
4.	Click ‘project.json’ node under solution to check in if the package 'Newtonsoft.Json 9.0.1' information is added in ‘project.json’ file.

**Expected Result:**
The package 'Newtonsoft.Json 9.0.1' information should be added in ‘project.json’ file.

**Actual Result:**
The package 'Newtonsoft.Json 9.0.1' information is not  added in ‘project.json’ file as below screenshot.
 
![uwp](https://cloud.githubusercontent.com/assets/20632775/23546712/c7303d56-003b-11e7-992f-ec5d01941c12.png)

**Notes:**
The issue not repro on D15Rel 26228.00 (NuGet 4.0.0-rtm-2323) and D15Rel 26228.00 + NuGet 4.1.0-rtm-2343.

**Comment by emgarten** [comment] 2017-03-03 20:52
Dupe of https://github.com/NuGet/Home/issues/4739

project.json isn't being used due to the bug

**Closed as completed by emgarten** 2017-03-03 20:52 UTC
