### ISSUE TITLE
NuGet package manager should display 'Owner' field for NuGet.org packages

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#6631] opened 2018-03-01 20:52 UTC
Author being a free text field is often misused and causes confusion to the developers consuming packages. The proposal is to show the owner information in PM UI when the information is available from the feed/repository like NuGet.org.

**Comment by clairernovotny** [comment] 2018-03-01 23:53
Better yet, it should be showing the CN off of a signed package if signed. I'd even say instead of the owner as a more authoritative verification. That also works regardless of package source.

The GUI's and NuGet.org should have it.

**Comment by anangaur** [comment] 2018-03-02 00:02
@onovotny Makes sense. We have been discussing this since signing was incubated. But it also adds to the confusion as to what is shown. I was thinking to have an account setting to have a **Display name** that can be a CN from the registered certificates. 
/cc: @rido-min who is really passionate about this change. :)

**Comment by rido-min** [comment] 2018-03-02 00:08
With repository signatures we could show the owners included in the signature metadata.

**Comment by clairernovotny** [comment] 2018-03-02 00:12
Is there a value in owners, even in signature metadata? I would think there is value in showing a CA-vetted identity prominently.

**Comment by rido-min** [comment] 2018-03-02 00:22
We'd need to revisit the decision to have different UI for signed vs. unsinged packages.

**Comment by clairernovotny** [comment] 2018-03-02 00:59
@rido-min you know where I stand on that and always happy to participate in any conversation around that topic :)

**Comment by anangaur** [comment] 2018-03-02 01:06
The topic beaten to death but i see no harm in showing that a package has been signed by an entity in the details page on the PM UI. This is package property - needs to show up somewhere?

**Comment by clairernovotny** [comment] 2018-03-02 01:10
@anangaur I would expect the following behavior -- 

CN show up in the search results to help differentiate a bogus package from a real one. In that context, the package isn't downloaded, so I'd expect the search result endpoint to provide that extracted information. It could then download the public cert "just in time" upon request to show in the UI (on click).

Showing it in the details portion is "too late," as a primary reason for code signing is to disambiguate and prove ownership.

**Comment by rido-min** [comment] 2018-03-02 01:18
> to help differentiate a bogus package from a real one. 

that's the issue, since being signed does not mean being "safe". We got feedback from everyone that we should not made any UI distinction on signed vs. unsigned.

**Comment by anangaur** [comment] 2018-03-02 01:20
I see where the discussion is going.. again.. :) - that's why I mentioned: 
> The topic beaten to death..

**Comment by clairernovotny** [comment] 2018-03-02 09:15
Let's talk next week. Code signing is not about safe, and but it is about identity and establishing trust.

Sent from a mobile device, please excuse brevity and typos
________________________________

**Comment by nkolev92** [comment] 2020-01-14 00:13
Duplicate of https://github.com/nuget/home/issues/442

**Closed as completed by nkolev92** 2020-01-14 00:13 UTC
Labels: Product:VS.Client, Type:Feature, Functionality:VisualStudioUI
