### ISSUE TITLE
nuget.exe updating package installs it in other projects

### ISSUE THREAD

**Issue by kimbirkelund** [NuGet/Home#1798] opened 2015-12-01 08:31 UTC
Repro solution available here: https://onedrive.live.com/redir?resid=4C2997B2E5861492!415578&authkey=!ALqDgQAd9Q10uNM&ithint=file%2czip

The linked solution contains two console projects: 
- ConsoleProject1 references Newtonsoft.Json
- ConsoleProject2 references EntityFramework (the specific package doesn't appear to matter)

When running the update command:

```
nuget.exe update .\NugetUpdateTest.sln -id newtonsoft.json
```

The Newtonsoft.Json package is installed in ConsoleProject2 which didn't have it previously, regardless of whether an update was available for the project that had the package. 

This issue generalizes to the point where updating a single package from the command line installs that package and all dependent packages in all projects in the solution.

As a side note: it is interesting that this command appears to be able to the work that install doesn't (i.e. add references and content files - it doesn't appear to run the PowerShell scripts though).

**Comment by yishaigalatzer** [comment] 2015-12-01 10:38
1. What version of nuget.exe are you using?
2. It is expected that nuget.exe cannot run powershell scripts, they can only run within the context of visual studio

**Comment by kimbirkelund** [comment] 2015-12-01 10:58
1. 3.3, but I've observed the issue with earlier 3.x versions as well.
2. I'm aware; I just found it interesting that this bug resulted in more correct install behavior (in my opinion) than the install command.

**Comment by yishaigalatzer** [comment] 2015-12-01 11:05
Install command is a misnomer, really think about it as restore. We consider removing it, and use restore instead. But for two reasons we didn't.
1. Backwards compatibility
2. Install allows restoring the latest version of a package

**Comment by kimbirkelund** [comment] 2015-12-01 11:07
I'm aware of the reasoning - doesn't mean I have to agree :) That's a different discussion though.

**Comment by johnataylor** [comment] 2015-12-01 19:42
This definitely repros and is a pretty obvious bug. In fact you could even pick a package that isn't installed in any of your projects and it will get installed in everyone of your projects if you specify it in the update command.

But this only appears to happen when you specify the -id explicitly on the command line. If you were to do a "update" without the -id flag it appears to do the right thing.

(I was testing this on a build of 3.3 on my machine.)

**Comment by johnataylor** [comment] 2015-12-01 20:44
The problem is the code in UpdateCommand.cs just loops over all the projects attempting to explicitly update the package specified in each one. See UpdatePackageAsync around l.255.

Also note this code should NOT really be a loop anyhow. Refer to #1803

**Comment by johnataylor** [comment] 2016-01-20 23:03
This was fixed with checkin on dec.1 should be in next release.

**Closed as completed by johnataylor** 2016-01-20 23:03 UTC
Labels: Priority:2, Type:Bug, Product:NuGet.exe

**Comment by yishaigalatzer** [comment] 2016-01-20 23:37
You can find nuget.commandline package containing nuget.exe 3.4 in this gallery on myget http://myget.org/gallery/nugetbuild
