### ISSUE TITLE
Package Console Extension prompts for credentials many times

### ISSUE THREAD

**Issue by timqzm** [NuGet/Home#7828] opened 2019-02-25 13:26 UTC
macOS Mojave 10.14.3
Visual Studio for Mac 7.8.1 build 4
NuGet Package Management Extensions 0.16

```
NuGet 4.8.0.6
Type 'get-help NuGet' for more information.

PM> Get-Package [some name] | Install-Package
```

VS prompts for credentials for every result found, very annoying 😿 
I have correct credentials in VS > Preferences > NuGet > Sources.

Moreover, if I cancel creds alert, there will be another one where Cancel and OK do nothing, only Cmd+Q helps to get rid of it.

**Comment by zivkan** [comment] 2019-02-25 18:27
@mrward Can you please advise on the two issues the customer reported? Is re-asking for the credentials is a NuGet or VS for Mac issue? Also in case you miss it, in the last paragraph, there's a report of a VS for Mac UI bug. Thanks.

**Comment by mrward** [comment] 2019-02-25 18:37
There is a known VS Mac bug in the credentials dialog where you have to click a button you cannot tab to it. Not sure if that is the problem here.

For the credentials problem - would need a repro.

1. What type of package source is being used?
2. Does it work from the command line using NuGet?
3. Does installing work from the Add Packages dialog?

Also the NuGet powershell console is an unofficial side project of mine - https://github.com/mrward/monodevelop-nuget-extensions - it is not included in VS Mac.

**Comment by mrward** [comment] 2019-02-25 20:47
This seems OK for me. With a VSTS package source that needs credentials, and those credentials added via Preferences - NuGet - Sources, I can use `get-package -online` and `install-package` to install packages from the NuGet PowerShell console.

If I use a VSTS package source that needs credentials, but they are not set, then the NuGet PowerShell console in VS Mac will prompt the dialog the once, and if Cancel is selected the command will fail. No more dialogs are seen. The dialog will only re-appear if the credentials did not work. Looks like NuGet will retry 4 times if you keep entering in a username and password that does not work and eventually `get-package -online` will stop asking for credentials and return no packages.

**Comment by timqzm** [comment] 2019-02-26 12:08
@mrward First of all sorry, I'm a bit far from VS and NuGet stuff.

> 1. What type of package source is being used?

These are remote private packages if I understood you question correctly. All I have are URL to JSON, username and PAT.

> 2. Does it work from the command line using NuGet?

Never tried, because [here](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools) I read there is no support for updating packages from NuGet CLI on Mac
<img width="744" alt="screenshot 2019-02-26 at 13 49 06" src="https://user-images.githubusercontent.com/13407092/53408299-344d3780-39cf-11e9-95ca-014a4d2c83ba.png">

> 3. Does installing work from the Add Packages dialog?

Yep.


My idea is to update all packages looking like "BlaBla.*" in whole solution quicker than right click Update on each package in each project (maybe there are some other ways?..)
I've tried to add `-online` param, it changed nothing.

**Comment by mrward** [comment] 2019-02-26 13:32
On the Mac you can install NuGet packages locally using NuGet.exe. Just doing something like `nuget install PackageId`. If the NuGet package is not in the local package source ~/.nuget/packages then nuget will use the credentials stored in the ~/.config/local/NuGet.Config to authenticate and download the .nupkg.

However using the Add Packages dialog is another way to check if NuGet is working with your package sources that require authentication.

With the NuGet extensions addin I would use the Manage Packages dialog to update across multiple projects. You can right click the solution in the Solution window, select Manage NuGet Packages, then use the Updates tab. You can also install a new NuGet package to multiple projects using this dialog.

Not sure why it does not work from the PowerShell console if it works from the Add Packages dialog. I am unable to reproduce the problem you are seeing with a NuGet package source that use a username and PAT.

**Comment by timqzm** [comment] 2019-02-26 14:20
> With the NuGet extensions addin I would use the Manage Packages dialog to update across multiple projects. You can right click the solution in the Solution window, select Manage NuGet Packages, then use the Updates tab. You can also install a new NuGet package to multiple projects using this dialog.

Thanks @mrward, it's what I searched for 👍

**Comment by timqzm** [comment] 2019-02-26 14:26
...but on the second attempt I can't close this alert again 😞
<img width="580" alt="screenshot 2019-02-26 at 17 22 45" src="https://user-images.githubusercontent.com/13407092/53419855-a895d400-39eb-11e9-826f-90bd75562c25.png">

**Comment by timqzm** [comment] 2019-02-26 14:28
but on the second attempt I can't close this alert again 😞
<img width="580" alt="screenshot 2019-02-26 at 17 22 45" src="https://user-images.githubusercontent.com/13407092/53419955-e561cb00-39eb-11e9-94f6-3e3a75d0686f.png">

**Comment by nkolev92** [comment] 2019-03-29 20:49
Closing this as external.

**Closed as completed by nkolev92** 2019-03-29 20:49 UTC
Labels: Type:Bug, Resolution:External, Area:Authentication
