### ISSUE TITLE
Please help: Error occurs on send

### ISSUE THREAD

**Issue by jords1987** [NuGet/Home#2643] opened 2016-04-22 12:30 UTC
I have the following issue when attempting to install a package from a cooperate nuget server.

The server is on the intranet and as I'm explained from the administrators a reverse proxy is used to se/recieve data

When I try to install package I get the following error:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. 

The stacktrace is:
`System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. 
---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.HttpClient.GetResponse()
   at NuGet.RedirectedHttpClient.GetResponseUri(HttpClient client)
   at NuGet.RedirectedHttpClient.EnsureClient()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean absoluteExpiration)
   at NuGet.RedirectedHttpClient.get_CachedClient()
   at NuGet.RedirectedHttpClient.get_Uri()
   at NuGet.DataServicePackageRepository.get_Source()
   at NuGet.Protocol.Core.v2.MetadataResourceV2.<GetVersions>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.v2.MetadataResourceV2.<GetLatestVersions>d__3.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.MetadataResource.<GetLatestVersion>d__7.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionCoreAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass55_1.<<GetLatestVersionAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__34.MoveNext()`
Like I said this is a cooperate server so I have no access to administer the server, I can pretty much rule that out as the problem as my colleague on the machine next to me can install packages successfully.

Does anybody know what I'm missing on my machine setup?

N.B: I am using VS2015, before installing, it worked on VS2012. I have tried using the nuget command line and recieve the same error.

**Comment by jords1987** [comment] 2016-04-22 12:52
Also, I can browse to the nuget server on my browser so maybe a VS2015 config?

**Comment by emgarten** [comment] 2016-04-22 21:53
This looks like an older version of NuGet. Would you try updating to the latest: https://dist.nuget.org/index.html

**Comment by jords1987** [comment] 2016-04-25 07:14
Thanks for the reply @emgarten, I'm really struggling to diagnose.... I am using VS2015 update 2 with version 3.4.3.855 of nuget.

The stack trace i gave is from the nuget command line as I don't think there is a "verbose" parameter for the extension?

The error when using install-package from the exstension is:
 Unable to load the service index for _https://{{cooperate server name}_ however like I said, I can browse to that location.

I tried using the "Manage nuget packages" form and the error I get from this is 
"Unable to load the service index for source _https://{cooperate server name}_ .
  An error occurred while sending the request.
  The underlying connection was closed: An unexpected error occurred on a send.
  Authentication failed because the remote party has closed the transport stream."

If it helps, I get the same error with the boilerplate "Microsoft and .NET" package source

**Comment by jords1987** [comment] 2016-04-25 07:49
also, not sure if its significant but if I untick the source in the settings I can download from nuget.org, but it is very slow

**Comment by jords1987** [comment] 2016-04-25 08:17
sorry, I can also reproduce what looks like the error in my browser (chrome says connection unexpectedly ended)by unticking "Automatically detect settings" in proxy settings... I dont think it is a proxy issue though

**Comment by jords1987** [comment] 2016-04-25 09:20
OK so this is where it gets weird, if I run fiddler and I put the proxy settings into the nuget .config
`
<config>
    <add key="http_proxy" value="http://127.0.0.1:8888" />
  </config>
`
The traffic shows in fiddler and the package downloads.......

**Comment by emgarten** [comment] 2016-04-25 18:30
Typically when NuGet works only when Fiddler is running it means that you are hitting proxy/environment issues outside of NuGet.

Do you know which SSL protocol version your corporate server is using? NuGet restricts the allowed SSL types, you can see the list here:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/NetworkProtocolUtility.cs#L18-L21

**Comment by jords1987** [comment] 2016-04-25 19:33
Thanks @emgarten, I have asked the question which ssl the server uses and await an answer.... I suspect that it is an issue with the environment rather than nuget. As I understand fiddler forces all traffic onto TLS1.0? I asked the question in here in case anyone had came across the issue before.

If I clone this repo, could I run in debug to see what that helper is returning?

**Comment by emgarten** [comment] 2016-04-25 20:15
@jords1987 the easiest way to build right now is to use the `release-3.4.3` branch from: https://github.com/NuGet/nuget.client

Run `build.ps1 -SkipTests` and then debugging with nuget.exe (NuGet.CommandLine).

**Comment by emgarten** [comment] 2016-04-27 18:14
@jords1987 any luck tracking the root cause down?

**Comment by jords1987** [comment] 2016-04-27 19:55
Hi @emgarten I have cloned the clients repo but when I run the powershell command it fails with a null reference exception? I tried to build in visual studio but each time it takes forever to restore packages and ends up failing? I have the server administrators for a remote session, see if they can fix it.... Do you know why the build would fail? It says something about "submodules" just before failing

**Comment by emgarten** [comment] 2016-04-27 21:02
Take a look at the steps that build.ps1 runs, you can see the git submodule commands there.

**Comment by rrelyea** [comment] 2016-05-02 21:00
@jords1987 - any progress?

**Comment by emgarten** [comment] 2016-05-04 19:52
I'm closing this issue. @jords1987 please reopen this if you are able to track down the root cause.

**Closed as completed by emgarten** 2016-05-04 19:52 UTC
