### ISSUE TITLE
Downloaded NuGet Packages are missing the DLL's

### ISSUE THREAD

**Issue by nicolaspierre1990** [NuGet/Home#1842] opened 2015-12-16 19:44 UTC
I'm trying to restore DLL's in my VS2015 solution and something weird happend. NuGet downloads all packages but it just won't download some DLL's. I'm left here wondering how that is. For example the Microsoft.Owin.Security.Facebook get's all files but one, the dll.

![image](https://cloud.githubusercontent.com/assets/5520669/11851860/3d1e601a-a435-11e5-90b4-bb0db7992d55.png)

My global config for NuGet is the following.
[NuGet.txt](https://github.com/NuGet/Home/files/64453/NuGet.txt)

Build gives me this:

5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Antlr3.Runtime". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "EntityFramework". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "EntityFramework.SqlServer". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Owin.Security.Cookies". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Owin.Security.Facebook". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Owin.Security.Google". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Owin.Security.MicrosoftAccount". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Owin.Security.Twitter". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Web.Optimization". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "WebGrease". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
5>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

**Comment by yishaigalatzer** [comment] 2015-12-31 01:10
That looks awfully weird! Obviously this is the bread and butter scenario for NuGet.

Here are a few things to look into:
1. Was your packages folder completely empty before you restored?
2. Do you have some sort of anti-virus or something that will scan continuously the packages folder and create locks on files?
3. Are you using NuGet 3.3?

**Comment by nicolaspierre1990** [comment] 2016-01-04 07:21
Yes, yes and yes. I'm using the same antivirus on my desktop as my laptop and only on my laptop it's causing problems. I always have the lastest version.

**Comment by yishaigalatzer** [comment] 2016-01-04 19:18
So this repros only on one of your computers? does it consistently repros?

**Comment by nicolaspierre1990** [comment] 2016-01-04 19:22
It just does after a x period of time. It differs. 3 repo's I had this problem now

**Comment by yishaigalatzer** [comment] 2016-01-04 19:25
That sounds interesting, can you share more information about what x period of time means? Can you walk me through the steps the get you there?

Project type
package.config/project.json

Other project you might have worked on
What does x mean (how much time, between what action and what action)

**Comment by nicolaspierre1990** [comment] 2016-01-04 19:28
I meant x as in I don't know. It just happens. The package.config is the one I'm using right now.
The steps, I can't do them because it just happens. I'm happy to let you on my computer via RDP so you can see it for yourself. I really don't know what I can say more.

Or do you have any suggestions on which data I can share more with you ?

**Comment by yishaigalatzer** [comment] 2016-01-04 19:33
RDP sounds good, it will work if you have a repeatable repro. If so I'll assign someone to debug with you

**Comment by nicolaspierre1990** [comment] 2016-01-04 19:45
I got one yeah

**Comment by yishaigalatzer** [comment] 2016-01-04 19:53
@deepakaravindr can you please work with @nicolaspierre1990 on this?

**Comment by deepakaravindr** [comment] 2016-01-04 20:27
@nicolaspierre1990, I am investigating this issue and I have send you an email. Please respond. Thanks!

**Comment by nicolaspierre1990** [comment] 2016-01-05 21:11
I had a RDP session with @deepakaravindr and we seem have to solved the problem. The problem was that in my c:\Users\MyUser.nuget some packages didn't extract correctly. So I deleted the contents of the folder and we got it working.

**Comment by yishaigalatzer** [comment] 2016-01-06 00:54
This looks like a bug in how we consume a folder with extracted packages. We should instead extract the data from the nupkg instead of trying to consume the extracted package content.

Lets have a short discussion with @emgarten and @davidfowl on this, in my mind we should just read the nupkg and ignore any other files in that folder.

**Comment by deepakaravindr** [comment] 2016-01-06 01:30
@yishaigalatzer @emgarten 

As discussed, once use of NuGet.Core is replaced in this scenario, we might decide to use the nupkgs itself instead of the expanded files. Assigning to @emgarten

**Comment by Xatter** [comment] 2016-01-07 17:09
+1 This happens to me all the time and the above work around appears to have worked for me

**Comment by yishaigalatzer** [comment] 2016-01-07 17:10
You can also use nuget.exe locals -clear all

**Comment by zhili1208** [comment] 2016-05-05 23:32
checked with dev branch, v2 and v3 use same cache folder now, it still repros if the cache file is corrupted after extraction.
If something wrong during extraction, nuget will reextract again. then it will work well

**Comment by rrelyea** [comment] 2016-05-11 18:16
@zhili1208 did some investigation here...after 3.5beta is done...finish conversation.

**Comment by emgarten** [comment] 2017-11-09 23:26
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Closed as completed by emgarten** 2017-11-09 23:26 UTC
Labels: Priority:2, Type:Bug, Resolution:NotRepro

**Comment by gojimmypi** [comment] 2020-01-29 23:42
@emgarten please see https://github.com/NuGet/Home/issues/8852#issuecomment-579880577
