### ISSUE TITLE
Restore command doesn't know $(SolutionDir) when importing .prop file in project file

### ISSUE THREAD

**Issue by dersteve** [NuGet/Home#2073] opened 2016-02-07 21:02 UTC
When the **UWP project** imports a .props file via 
`<Import Project="$(SolutionDir)\Project.Universal.props" />`
the nuget restore command fails, which runs before the build on my TFS Build Server (TFS 2015) because it tries to find this .props file on the root of the drive, which tells me that it doesn't set the $(SolutionDir) directory.

Nuget.exe 3.3 used on TFS Build Controller
XAML Build Definition

Is that a bug or am I overlooking something here?

**Comment by yishaigalatzer** [comment] 2016-02-07 23:49
I *\* think *\* this should work. Assigning to @jasonmalinowski to comment further.

**Comment by jasonmalinowski** [comment] 2016-02-08 17:29
How did the SolutionDir reference get into the project in the first place?

**Comment by jasonmalinowski** [comment] 2016-02-08 17:30
(@yishaigalatzer: the build task has nothing to do with this; it never does anything with SolutionDir. This would be a core client restore bug for purposes of setting the area for this bug.)

**Comment by yishaigalatzer** [comment] 2016-02-08 19:56
OK, I see now. This is a nuget restore bug, when it tries to figure out the P2P references. Not a very common scenario, but something we should probably fix (or perhaps it is an msbuild bug, who knows). Assigning to @emgarten to take a look

**Comment by emgarten** [comment] 2016-02-08 20:01
@dersteve How does this path normally get resolved? By TFS?

NuGet loads the solution using MSBuild to discover all projects, it sounds like NuGet fails when this reference is unresolved and then doesn't restore anything, correct?

**Comment by dersteve** [comment] 2016-02-08 21:05
I added the reference by hand. I use props files to have common things defined like output paths etc. I have a solution with 100+ projects - makes it easier to change if needed. MSBuild has these parameter set by default. SolutionDir is a normal build parameter

**Comment by dersteve** [comment] 2016-02-08 21:07
With the new transient mode nuget gets executed outside of the usual MSBuild task - right? I suppose nuget executes MSBuild again but without these parameters set. Could that be an explanation?

**Comment by jasonmalinowski** [comment] 2016-02-08 21:14
MSBuild will set SolutionDir _if_ you are building a solution. If you're building an individual project, it will not, since there is no correct way it can find the solution. (What if your project is in more than one solution? What if the solution is in some random other place on disk?) Note that NuGet in package.config mode bakes in a SolutionDir to attempt to "fix" this, but that's obviously broken if you have more than solution containing that project.

Although that's not to say this isn't a bug if nuget.exe restore isn't setting SolutionDir when restoring a solution, @dersteve you're always often best off avoiding use of SolutionDir if you can, since there's really no guarantee that it's set. Consider either a relative path to your props file (this is [what we do in Roslyn](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/CodeAnalysis.csproj#L5)), or [using the MSBuild function GetDirectoryNameOfFileAbove](http://stackoverflow.com/a/10389422/972216) that could walk up and find your solution directory for you.

**Comment by dersteve** [comment] 2016-02-08 21:53
I use it in UWP projects that only support project.json approach and not package.config (right?) hence that is not an option. My projects are always just in one solution. I have multiple solutions but each has its own bunch of projects - none of them is included in more than one solution. 

Does it mean I can't import a general props file via SoutionDir parameter in my UWP project at the moment?

**Comment by dersteve** [comment] 2016-02-08 21:55
The relative path could be a solution for my case at the moment. Thanks for pointing me to that. It has the disadvantage though that I can't move projects around that easily. But that should be ok in my case.

**Comment by yishaigalatzer** [comment] 2016-02-08 23:14
@dersteve thanks for clarifying. This is something we could further investigate but my assumption here is that if you msbuild the project directly solutiondir just doesn't work (which is how we run restore). So the relative path might be the right way to go.

I'm closing this as by design for now. We can keep the discussion going, and if we think this needs to be fixed we can considering doing that.

Note: I don't think the issue has to do with with project.json vs. packages.config

**Closed as completed** 2016-02-09 04:14 UTC
Labels: Priority:2, Resolution:ByDesign

**Comment by dersteve** [comment] 2016-02-09 07:46
The real question is:
1.) Since it fails and gives me an error in the TFBuild log, I don't know if the restore actually works.
2.) Shouldn't it just give a warning and no error or state more it clear that it's not a problem?

So I'm not so sure about just closing it.

**Comment by dersteve** [comment] 2016-02-18 13:35
I verified the whole restore process and infact it just fails **without restoring any packages**, nor generating a **project.lock.json** file for any of the projects inside the solution. 

It should at least not stop with an error, but just continue and report it as a warning.
