### ISSUE TITLE
Support .NET packages for C++/CLI

### ISSUE THREAD

**Issue by fubar-coder** [NuGet/Home#1645] opened 2015-10-27 03:39 UTC
One of the problems with C++/CLI is, that NuGet only allows the installation of native DLLs for C++(/CLI), but not .NET assemblies.

My proposal is, that when we have a C++/CLI configuration, that the installation of .NET packages/assemblies is allowed. If there are other non-CLI configurations, a warning should be shown. Currently, it's a PITA using the `install.ps1`/`uninstall.ps1` scripts and it's unreliable too, because the object model might change between VS versions and therefore break installing/updating NuGet packages.

EDIT: This is loosely related to #300

**Comment by yishaigalatzer** [comment] 2015-10-27 15:58
Indeed there is no proper support for C++ projects, the scope of the issue however is much larger than what is described here, in some sense C++ projects are a different world than .NET with a different set of constraints.

We do plan to go deeper into this designing this with the C++ team, so keeping this around as a marker issue, and will replace it with more of a design document on the wiki once things start moving in earnest.

**Comment by ddrinka** [comment] 2016-03-14 15:07
I've noticed that installing managed assemblies into C++/CLI is possible with a project.json dependency configuration, as opposed to the legacy packages.config.  Moving to the new dependency model fixed this issue for us, without requiring any adjustment to our development workflow.

**Comment by emgarten** [comment] 2017-11-10 23:35
Duplicate of https://github.com/NuGet/Home/issues/5292

**Closed as completed by emgarten** 2017-11-10 23:35 UTC
Labels: Resolution:Duplicate, Priority:3, Type:Feature, Partner:C++

**Comment by davidjward30** [comment] 2017-11-13 08:29
I see this is closed, yet marked as a duplicate of itself?

**Comment by emgarten** [comment] 2017-11-13 08:53
@davidjward30 good catch, I updated the issue number :smile:
