### ISSUE TITLE
Lightweight Solution Loading doesn't build .nuproj and doesn't fix nuget restore errors

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#4792] opened 2017-03-13 00:05 UTC
Using Visual Studio 2017 and lightweight solution loading, nuproj files appear to not be built. Additionally I still get:

Error occurred while restoring NuGet packages: The operation failed as details for project WinObjC.Frameworks.Core could not be loaded.

The project in question is build\build.sln at https://github.com/Microsoft/WinObjC/tree/packaging

**Comment by bbowman** [comment] 2017-03-13 00:05
@kzu @rrelyea

**Comment by kzu** [comment] 2017-03-13 00:37
@adalon too

**Comment by adalon** [comment] 2017-03-13 13:23
@bbowman could you please confirm if you're using the latest VS 2017/NuGetizer builds?

The latest NuGetizer is 0.1.227 and the link to download is: http://bit.ly/nugetizer-2017

We also switched from project.json to PackageReference. Not sure if the .NetCore tools might help to migrate out .nuproj projects. Otherwise I think you will need to do it manually.

Please let me know if this helps.

**Comment by IlyaBiryukov** [comment] 2017-05-03 22:04
The error message 'Error occurred while restoring NuGet packages: The operation failed as details for project WinObjC.Frameworks.UWP.Core could not be loaded' also occurs if Lightweight Solution Load is disabled.

**Comment by IlyaBiryukov** [comment] 2017-05-04 00:20
The issue of not building .nuproj in LSL is not specific to https://github.com/Microsoft/WinObjC/tree/packaging.

Generally, .nuproj doesn't support LSL properly.

Below are the build logs with normal verbosity for clean and build commands executed on solution node in Solution Explorer in Lightweight Solution Load (LSL) mode and without it. The solution contains a C# Desktop class library project 'ClassLibrary1' and a .nuproj project 'NugetPackage2' that references it. Auto package restore is disabled in Tools Options.

In LSL, the projects are built without loading the projects in VS. As you can see, .nuproj doesn't build or clean in LSL mode.

## Clean on solution node - no LSL or running msbuild /t:Clean in the command line
```
1>------ Clean started: Project: NuGetPackage2, Configuration: Debug Any CPU ------
1>Build started 5/3/2017 5:00:54 PM.
1>Target CoreClean:
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\NuGetPackage2\bin\Debug\NuGetPackage2.1.0.0.nupkg".
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\NuGetPackage2\bin\Debug\Readme.txt".
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\NuGetPackage2\obj\Debug\NuGetPackage2.nuprojResolveAssemblyReference.cache".
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\NuGetPackage2\obj\Debug\NuGetPackage2.nuproj.CoreCompileInputs.cache".
1>Target _GetProjectReferenceTargetFrameworkProperties:
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:00.04
2>------ Clean started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
2>Build started 5/3/2017 5:00:54 PM.
2>CoreClean:
2>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\bin\Debug\ClassLibrary1.dll".
2>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\bin\Debug\ClassLibrary1.pdb".
2>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\obj\Debug\ClassLibrary1.csproj.CoreCompileInputs.cache".
2>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\obj\Debug\ClassLibrary1.dll".
2>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\obj\Debug\ClassLibrary1.pdb".
2>
2>Build succeeded.
2>
2>Time Elapsed 00:00:00.00
========== Clean: 2 succeeded, 0 failed, 0 skipped ==========
```

## Clean on solution node with LSL enabled
```
1>------ Clean started: Project: ClassLibrary1, Configuration: Debug|Any CPU ------
1>CoreClean:
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\bin\Debug\ClassLibrary1.dll".
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\bin\Debug\ClassLibrary1.pdb".
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\obj\Debug\ClassLibrary1.csproj.CoreCompileInputs.cache".
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\obj\Debug\ClassLibrary1.dll".
1>  Deleting file "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\obj\Debug\ClassLibrary1.pdb".
========== Clean: 2 succeeded, 0 failed, 0 skipped ==========
```

## Build on solution node - no LSL
```
1>------ Build started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>Build started 5/3/2017 5:10:05 PM.
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>  C:\Program Files (x86)\VS\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\ClassLibrary1.dll /ruleset:"C:\Program Files (x86)\VS\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /utf8output Class1.cs Properties\AssemblyInfo.cs "C:\Users\ilbiryuk\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs" obj\Debug\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs obj\Debug\\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs obj\Debug\\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs
1>  Using shared compilation with compiler from directory: C:\Program Files (x86)\VS\MSBuild\15.0\Bin\Roslyn
1>CopyFilesToOutputDirectory:
1>  Copying file from "obj\Debug\ClassLibrary1.dll" to "bin\Debug\ClassLibrary1.dll".
1>  ClassLibrary1 -> c:\users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\bin\Debug\ClassLibrary1.dll
1>  Copying file from "obj\Debug\ClassLibrary1.pdb" to "bin\Debug\ClassLibrary1.pdb".
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:00.06
2>------ Build started: Project: NuGetPackage2, Configuration: Debug Any CPU ------
2>Build started 5/3/2017 5:10:05 PM.
2>Target _GetProjectReferenceTargetFrameworkProperties:
2>Target ResolveProjectReferences:
2>Target _SplitProjectReferencesByIsNuGetized:
2>Target GetPackageContents:
2>Target Pack:
2>  Created package at C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\NuGetPackage2\bin\Debug\NuGetPackage2.1.0.0.nupkg.
2>Target GetCopyToOutputDirectoryItems:
2>Target _CopyOutOfDateSourceItemsToOutputDirectory:
2>  Copying file from "C:\Users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\NuGetPackage2\Readme.txt" to "bin\Debug\Readme.txt".
2>
2>Build succeeded.
2>
2>Time Elapsed 00:00:00.13
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

## Build on solution node with LSL enabled
```
1>------ Build started: Project: ClassLibrary1, Configuration: Debug|Any CPU ------
1>CoreCompile:
1>  Using shared compilation with compiler from directory: C:\Program Files (x86)\VS\MSBuild\15.0\Bin\Roslyn
1>CopyFilesToOutputDirectory:
1>  Copying file from "obj\Debug\ClassLibrary1.dll" to "bin\Debug\ClassLibrary1.dll".
1>  ClassLibrary1 -> c:\users\ilbiryuk\documents\visual studio 2017\Projects\NuGetPackage2\ClassLibrary1\bin\Debug\ClassLibrary1.dll
1>  Copying file from "obj\Debug\ClassLibrary1.pdb" to "bin\Debug\ClassLibrary1.pdb".
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by adalon** [comment] 2017-05-04 13:02
@IlyaBiryukov I'm not being able to reproduce the issue you're describing.

And also in your output I can see the .nuproj is included in the Clean/Build (2 succeeded and 1 up-to-date). Did you build the project before running the Clean with LSL enabled?

**Comment by IlyaBiryukov** [comment] 2017-05-04 15:33
@adalon I built the solution without LSL before running any clean scenario. I cleaned the solution without LSL before running any build scenario.
The issue here is that .nuproj is always considered up-to-date in LSL mode. I bet it's going to be the same issue in 'Open Folder' mode.

**Comment by adalon** [comment] 2017-05-04 15:46
Could you please share the solution you're using? And also paste the build output with detailed verbosity?

I just ran the following repro and the nuproj was built as expected:
1. Build sln
2. Change a .cs file in the class library
3. Build sln -> and the .nuproj project was built

**Comment by IlyaBiryukov** [comment] 2017-05-04 15:56
It's just a simple solution with a C# Desktop Class library and a .nuproj project. The .nuproj has a p2p reference to the class library.
Did you enable _Lightweight Solution Load_?
Without LSL everything builds fine.

**Comment by adalon** [comment] 2017-05-04 15:58
Yes, LSL enabled.

Microsoft Visual Studio Enterprise 2017
Version 15.1 (26403.3) Release

**Comment by IlyaBiryukov** [comment] 2017-05-04 16:01
Enterprise 2017 vsuvscore 26503.01.

**Comment by IlyaBiryukov** [comment] 2017-05-05 18:21
I traced the issue down to LSL build manager ignoring .nuproj because it doesn't have a custom up-to-date check provider. [Bug 399977](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/399977). With the fix to that on VS side, I'm now seeing that the .nuproj build fails with this error in LSL mode:
```
C:\Users\ilbiryuk\.nuget\packages\nuget.build.packaging\0.1.250\build\NuGet.Build.Packaging.targets(476,3): error : Method not found: 'Void NuGet.Packaging.PackageDependencyGroup..ctor(NuGet.Frameworks.NuGetFramework, System.Collections.Generic.IEnumerable`1<NuGet.Packaging.Core.PackageDependency>)'
```
It seems that it has difficulties resolving the right Nuget.Packaging.dll.
@adalon I can share private bits to fix the LSL build manager with you if you want to take a look.

**Comment by IlyaBiryukov** [comment] 2017-05-12 16:41
I've figured out what the issue was and have the fix for it in VS.
It'll be fixed in the upcoming release of Visual Studio.

@kzu, @adalon, you can close this issue.

**Closed as completed** 2017-05-12 20:58 UTC
