### ISSUE TITLE
Managa Packages for Solution UX in VS 2015

### ISSUE THREAD

**Issue by brgrz** [NuGet/Home#2030] opened 2016-02-02 10:20 UTC
When managing packages for solution the behaviour under Updates and Consolidate is on the left side show all packages possible to update/consolidate. On the right hand where there's a Source dropdown you might have selected nuget.org (while having more sources configured).

The Updates and Consolidate would show all packages able to update/consolidate regardless of the right hand side source dropdown selection.

But when hitting Install/Update on the packages that aren't on the selected source you get an error saying:

`Package 'MyPackage' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available.`  

It takes the selected package source into account when updating/installing but doesn't when listing possible packages.

**Comment by brgrz** [comment] 2016-02-02 10:21
Ok, after further inspection I can report the issue is limited to Consolidate feature only.

**Comment by yishaigalatzer** [comment] 2016-03-13 03:19
@alpaix please verify this scenario for 3.4RTM. if it is not fixed move it to 3.5-Beta

**Comment by alpaix** [comment] 2016-03-14 18:23
Verified the scenario in build 758. The issue is still relevant when selecting a source that doesn't contain desired package. Happens both in update and consolidate view.

Although as a workaround I'd suggest switching to "all" source. This works just fine.
Moving to [3.5 Beta](https://github.com/NuGet/Home/milestones/3.5%20Beta).

**Comment by rrelyea** [comment] 2017-10-17 21:35
Yes, please switch to "all sources" as recommended workaround.

**Closed as completed by rrelyea** 2017-10-17 21:35 UTC
Labels: Product:VS.Client, Type:Bug
