### ISSUE TITLE
nuget favorites list

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8232] opened 2019-06-13 23:51 UTC
VSF_TYPE_MARKDOWNAllow to save favorites nuget package. This will allow to quickly add nuget to new projet.

In my dev job, I often create simple small project from the ground up. And when doing this, I usually add always the same few nuget package. Having a fav list will allow me to get easy access to this packages

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/582310/nuget-favorites-list.html
VSTS ticketId: 899220_
_These are the original issue comments:_

Jane Wu [MSFT] on 5/27/2019, 01:08 AM (17 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by donnie-msft** [comment] 2019-06-14 22:01
Duplicate of https://github.com/NuGet/Home/issues/7468

**Closed as completed by donnie-msft** 2019-06-14 22:01 UTC
Labels: Resolution:Duplicate
