### ISSUE TITLE
No dotnet restore --configuration option

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7050] opened 2018-06-21 23:19 UTC
_From @bcuff on June 21, 2018 22:52_

## Steps to reproduce
Create a csproj file with conditional package references

Example:
```xml
<ItemGroup Condition="'$(Configuration)' == 'NUnitLite'">
    <PackageReference Include="NUnitLite" Version="3.9.0" />
</ItemGroup>
```

## Expected  behavior
dotnet restore should respect the --configuration parameter.
```bash
dotnet restore --configuration NUnitLite
```

## Actual behavior
dotnet restore doesn't have a --configuration option

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.201)

Product Information:
 Version:            2.1.201
 Commit SHA-1 hash:  7932dc6179

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.201\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

_Copied from original issue: dotnet/cli#9537_

**Comment by nkolev92** [comment] 2018-06-25 07:07
Duplicate of https://github.com/NuGet/Home/issues/5421 and https://github.com/NuGet/Home/issues/5895. 

As indicated in https://github.com/NuGet/Home/issues/5895#issuecomment-329867265, 

`TargetFramework` is the only support condition allowed for `PackageReference` items.

To work with other conditions you will need to handle them yourself by passing the extra property values to restore, and ensuring that restore is done appropriately before each build.

**Closed as completed by nkolev92** 2018-06-25 07:07 UTC
Labels: Resolution:Duplicate, Type:DCR, Functionality:Restore, Style:PackageReference

**Comment by turowicz** [comment] 2019-05-07 10:26
@nkolev92 this is not about where to put conditions in, this is about the ability to pass a configuration or any other variable to the `dotnet restore` command, as it is possible in the `dotnet build`. In my case `dotnet build -c Release` restores correctly with the `Configuration` condition, while `dotnet restore` seems to be restoring without `Configuration` condition evaluation.

**Comment by nkolev92** [comment] 2019-05-08 00:09
dotnet build implicitly invokes restore. 
The implicit restore is exactly the same as the dotnet restore command. 

Restore does not evaluate based on the Configuration pivot.

So `dotnet restore`, `dotnet restore /p:Configuration="Release"` `dotnet build`, `dotnet build -c Release` will all run the same restore. 

You can verify that by consecutively running all these commands and seeing that the timestamps of the assets file do not change.

**Comment by turowicz** [comment] 2019-05-08 12:51
I've found a workaround with:

`RUN dotnet msbuild /t:restore /p:Configuration=Release src`

It really does evaluate the condition and references the right package. In Debug I reference a nuget package while in Release I point to a localy compiled dll.

**Comment by turowicz** [comment] 2019-05-08 12:52
Additionaly, for people running Docker, it is very important that the `restore` is a separate command from `build`. In that scenario build is invoked with `--no-restore` flag.

**Comment by jonathanantoine** [comment] 2022-12-19 13:58
Thank you @turowicz . By the way, it works also this way : 
`dotnet restore /p:Configuration=Release`

**Comment by Timwi** [comment] 2026-03-08 21:19
I have run into this as well. I think this ticket should be reopened (and/or the duplicates #5421 or #5895). It is currently not possible to use `nuget restore` on a project that uses references that are conditional on the build configuration.

In my case, I have a configuration in which the dependencies are referenced by local source and one in which the same dependencies are referenced as Nuget packages. `Nuget restore` fails because it can’t find the `csproj` files even though they are not used in the configuration that I want to build.
