### ISSUE TITLE
[Bug]: [Pack] The error “NU5017: Cannot create a package that has no dependencies nor content” occurs when the NuspecBathPath is more than 5 layers

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12003] opened 2022-08-04 09:40 UTC
### NuGet Product Used

dotnet.exe

### Product Version

Dev\6.4.0.33

### Impact

It's more difficult to complete my work

#### Details about Problem
VS Version: Main\32803.137
NuGet Version: Dev\6.4.0.33
OS Version: Windows-11-Enterprise-21H2 ENU

#### Detailed repro steps
1. Create a C# Class Library (.NET 7.0) in VS. 
2. Put a nuspec file called "Package.nuspec" (the content is valid and correct) under a long path like C:\Users\v-luzh\Source\Repos.
3. Run `“dotnet pack -p:NuspecFile="C:\Users\v-luzh\Source\Repos\Package.nuspec" -p:NuspecBasePath=C:\Users\v-luzh\Source\Repos”`, the packing is successful without any error.
4. Run `“dotnet pack -p:NuspecFile="C:\Users\v-luzh\Source\Repos\SpecFile\Package.nuspec" -p:NuspecBasePath=C:\Users\v-luzh\Source\Repos\SpecFile”`.

#### Expected
The package can be packed successfully (like the result of step3). 

#### Actual
The error “NU5017: Cannot create a package that has no dependencies nor content” occurs as below.
![image](https://user-images.githubusercontent.com/20632625/182815733-9d32e686-617c-429c-850a-8b9c1191642e.png)

#### Note:
1.It seems not a regression since it reproes on NuGet Client 5.11.2.2.
2.It reproes when the NuspecBasePath 5 layers, doesn't repro when the NuspecBasePath <5 layers.

**Comment by nkolev92** [comment] 2022-08-15 22:40
Team Triage: 

This is expected behavior. 
When packing a nuspec file through a project, only 3 properties are relevant as documented in https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec-file. 

The fact that the nuspec is near a project file merely means that the project file can be used for specifying the properties. 

Given that the spec from nuget spec is not modified, there's no content to be included and the error is correct.

**Comment by v-luzh** [comment] 2022-08-27 14:33
Hi @nkolev92, after verifying, we still think it is an issue. Let me describe it in detail. 

The nuspec file is correct and have no changes. This error (“NU5017: Cannot create a package that has no dependencies nor content”) will occur when the nuspec file path longer than 5 layers. That means if the file basepath is "C:\Users\v-luzh\Source\Repos" (5 layers), the error will not occur. But if the file basepath is "C:\Users\v-luzh\Source\Repos\SpecFile" (>5 layers), the error will occur.

I updated the bug and re-activated it. Please help to have a look, thanks.

**Comment by nkolev92** [comment] 2022-08-29 23:09
I think I see what the issue is:

@v-luzh Can you please check the content of the first package after step 3? 

Does it contain the obj, bin, csproj and class files? 
It's packing by convention which is everything under the nuspec base file path. 
When you make the  nuspec base file path a location with no content other than the nuspec, then it fails because there's nothing in that directory to pack.

**Comment by v-luzh** [comment] 2022-09-02 05:02
Hi @nkolev92, there is no obj, bin, csproj and class files in the first NuspecBasePath when doing step3. And that package can be packed successfully. 
The difference between step4 and step3 is only adding another folder, and step4 would fail with the error in the "Actual" above.

**Comment by nkolev92** [comment] 2022-09-06 16:33
@v-luzh 

Can you please paste the content of the nupkg file in step 3? 
I can repro this on my end, and what I'm seeing is expected. 

In step 3, the folder has *content*, in step 4, it doesn't.

**Comment by v-luzh** [comment] 2022-09-19 10:37
Hi @nkolev92，upload the nupkg file [here](\\mlangfs1\Public\NuGet\BugRepro) in step3. Please help to have a look, thanks.

**Comment by nkolev92** [comment] 2022-09-19 23:44
Thanks @v-luzh 
I see that in your package you have a bunch of projects, which is basically what is getting packed. 

For example, if you go to `FwProject`, `FwProject` you will see a cs file. 


Basically, when the nuspec base file path is *not empty* it works, when it is *empty* it does not work.

When you make the nuspec base file path a location with no content other than the nuspec, then it fails because there's nothing in that directory to pack.


Hope this helps clarify it. 

Closing this again.

**Closed as completed by nkolev92** 2022-09-19 23:44 UTC
Labels: Type:Bug, Functionality:Pack, Product:dotnet.exe, Resolution:NotABug, Found:ManualTests
