### ISSUE TITLE
Restore fails for "Azure Resource Group" project template and Directory.Build.props

### ISSUE THREAD

**Issue by timmkrause** [NuGet/Home#8004] opened 2019-04-16 16:49 UTC
## Details about Problem

`nuget restore` fails for kind of "special" combination regarding "Azure Resource Group" project template (`.deployproj`) and `Directory.Build.props`.

NuGet.exe
NuGet version: 4.9.3.5777
VS version: 2019 (16.0.1)
OS version: win10

## Detailed repro steps

These are local reproduction steps, actually this happened within Azure Pipelines (hosted agents).

1. File / New / Project... / "Azure Resource Group" (defaults are OK)
2. Create a `Directory.Build.props` a the solution-level containing any `PackageReference`, example:

```
<Project>
  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers">
      <Version>2.0.0</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

3. Open a command prompt, navigate to the solution-level folder and execute `nuget restore`, the result is:

`Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\something\AzureResourceGroup2\AzureResourceGroup2\AzureResourceGroup2.deployproj.`

## Other suggested things

I tried adding a `<TargetFramework>`, for the restore part this worked, but when building the solution with `msbuild` I got a `Microsoft.NuGet.targets(186,5): Error : Sequence contains no elements`.
After that I found a way to circumvent this error as well (removing the import of `Microsoft.Common.targets`), but I was not happy with that approach anymore, thus I started from 0 and was searching for a way to exclude certain projects from the restore process. Any ideas?

### Verbose Logs

```
NuGet Version: 4.9.3.5777
NuGet-Pakete für das Projekt "C:\Users\user\source\repos\AzureResourceGroup2\AzureResourceGroup2.sln" werden wiederhergestellt.
MSBuild auto-detection: using msbuild version '16.0.461.62831' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\msbuild.exe "C:\Users\user\AppData\Local\Temp\NuGetScratch\lyglwlhh.dh4.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\user\AppData\Local\Temp\NuGetScratch\a0hjzarp.gmc.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="C:\ProgramData\chocolatey\lib\NuGet.CommandLine\tools\nuget.exe" /p:RestoreSolutionDirectory="C:\Users\user\source\repos\AzureResourceGroup2\\" /p:SolutionDir="C:\Users\user\source\repos\AzureResourceGroup2\\" /p:SolutionName="AzureResourceGroup2"

NuGet.Commands.RestoreSpecException: Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\Users\user\source\repos\AzureResourceGroup2\AzureResourceGroup2\AzureResourceGroup2.deployproj.
   bei NuGet.Commands.SpecValidationUtility.ValidateFrameworks(PackageSpec spec, IEnumerable`1 files)
   bei NuGet.Commands.SpecValidationUtility.ValidateProjectSpecPackageReference(PackageSpec spec, IEnumerable`1 files)
   bei NuGet.Commands.SpecValidationUtility.ValidateProjectSpec(PackageSpec spec)
   bei NuGet.Commands.SpecValidationUtility.ValidateDependencySpec(DependencyGraphSpec spec)
   bei NuGet.Commands.DependencyGraphSpecRequestProvider.GetRequestsFromItems(RestoreArgs restoreContext, DependencyGraphSpec dgFile)
   bei NuGet.Commands.DependencyGraphSpecRequestProvider.CreateRequests(RestoreArgs restoreContext)
   bei NuGet.Commands.RestoreRunner.<CreatePreLoadedRequests>d__11.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.Commands.RestoreRunner.<GetRequests>d__4.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.Commands.RestoreRunner.<RunAsync>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.Commands.RestoreRunner.<RunAsync>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__36.MoveNext()
```

### Sample Project

See repro steps.

**Comment by zivkan** [comment] 2019-04-16 17:26
Closing as duplicate of #7831

**Closed as completed** 2019-04-16 17:26 UTC
Labels: Resolution:Duplicate
