### ISSUE TITLE
`Update-Package -id <id of package> -Reinstall `  is reinstalling ALL packages for ALL projects in the solution

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#7006] opened 2018-06-07 21:24 UTC
THe package I'm re-installing is an in house one with one other in-house dependency. 

VS is having trouble restoring/building, and I dont want to trash the allowedVersions already set throughout the solution, so I ran the update package command in the pm console, and its re-installing everything - Bootstrap, Jquery, and like 50 other private and public packages for all the projects in the solution.   

I expected it to just update the one package named.  Its been 20+ minutes that this has been running through projects. Its similar to the "Flake Out" issue I reported before.  I dont dare kill or stop the project because I cant afford to revert all the other changes I have (merging toward a release) pending. 

This stuff always seems to break at the _worst_ possible times. Please focus on stability and non-corruption of projects or loss of references instead of 'transitivity' or source diagnostics, or even signing.

**Comment by StingyJack** [comment] 2018-06-08 14:07
Removing and re-adding a nuget package using the PM UI is also removing references from other projects.

**Comment by rohit21agrawal** [comment] 2018-06-09 01:14
can you tell us what was the exact command you executed in the console?

**Comment by mishra14** [comment] 2018-06-09 01:23
@rohit21agrawal  this is a dupe of https://github.com/NuGet/Home/issues/737

**Comment by StingyJack** [comment] 2018-06-09 04:10
Nuget in VS (pm ui, and the output window for package mgmt) are now telling me they are installing a package, but they never add the reference to the csproj. I've been trying to fix this for almost two days now.  I cant revert without losing the changes I had in progress before this blew up the solution.

**Comment by jainaashish** [comment] 2018-06-12 22:30
Dupe of https://github.com/NuGet/Home/issues/6133

**Closed as completed by jainaashish** 2018-06-12 22:30 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Update, Product:VS.PMConsole

**Comment by rohit21agrawal** [comment] 2018-06-12 23:36
as a workaround for now, please pass the -Projectname parameter to specify the project explicitly. I have a PR out to fix this.
