### ISSUE TITLE
NuGet.Protocol.Plugins.PluginDiscoveryUtility uses wrong file in non net472 version of library.

### ISSUE THREAD

**Issue by v-stland** [NuGet/Home#8532] opened 2019-08-30 18:24 UTC
NuGet Product: API v3
NuGet version v5.2.0

There is a mismatch in the source provided for net472 and the netstandard version which will cause the other versions to fail to validated users when using credential providers.

Here is a copy of the source in the distributed dll in the netstandard version:
`public static IEnumerable<string> GetConventionBasedPlugins(IEnumerable<string> directories)
{
    List<string> list = new List<string>();
    using (IEnumerator<string> enumerator = Enumerable.Where<string>(directories, new Func<string, bool>(null, (IntPtr) Directory.Exists)).GetEnumerator())
    {
        while (enumerator.MoveNext())
        {
            foreach (string text1 in Directory.GetDirectories(enumerator.get_Current()))
            {
                string path = Path.Combine(text1, Path.GetFileName(text1) + ".dll");
                if (File.Exists(path))
                {
                    list.Add(path);
                }
            }
        }
    }
    return list;
}`

You can find this source code here: NuGet.Protocol.Plugins.PluginDiscoveryUtility

As you can see the extension in the broken version is using .dll instead of .exe.

Let me know if you need any more information.

**Comment by rrelyea** [comment] 2019-08-30 21:17
FYI @nkolev92 @dtivel

**Comment by nkolev92** [comment] 2019-08-30 21:20
> There is a mismatch in the source provided for net472 and the netstandard version which will cause the other versions to fail to validated users when using credential providers.

That's by design.

The net472 version works with .NET Framework providers, the expectation there is for the plugins to have an exe extension. 

The netstandard version works cross platform. The providers are expected to be .NET Core based, so the extension expected is dll. 

I'll admit it's not a perfect approach, but it did address our scenarios.

**Comment by nkolev92** [comment] 2019-10-16 19:00
Closing this per the above comment.

**Closed as completed by nkolev92** 2019-10-16 19:00 UTC
Labels: Resolution:ByDesign, Area:Plugin
