### ISSUE TITLE
Searching from VS for Microsoft.AspNetCore.Static Yields Low Quality Results

### ISSUE THREAD

**Issue by spottedmahn** [NuGet/Home#6179] opened 2017-11-13 20:53 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

VS version (if appropriate): 2017: 15.4.3

## Detailed repro steps so we can see the same problem

1. Open Package Manager GUI
1. Search for `microsoft.aspnetcore.static`
1. There are no search results

![image](https://user-images.githubusercontent.com/14079228/32748550-9524429a-c88a-11e7-8b48-7514de19470f.png)

Why do I need to search for `microsoft.aspnetcore.staticfiles` for it to find it?

**Comment by anangaur** [comment] 2017-11-13 21:08
Dupe of https://github.com/NuGet/NuGetGallery/issues/2789
Search on NuGet.org or from PMUI have same behavior as they use same APIs.
All related search improvements are tracked on https://github.com/NuGet/NuGetGallery/issues/4124

**Closed as completed by anangaur** 2017-11-13 21:08 UTC
Labels: Resolution:Duplicate
