### ISSUE TITLE
vsfeedback -- Cannot restore NuGet packages for .NET Core projects in VS if they don't have obj directory

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4633] opened 2017-02-16 18:17 UTC
vsfeedback 808451 - customer email available

1. git clone https://github.com/conniey/dotnet-apiport/tree/updateVS2017
2. Open PortabilityTools.sln
3. Right-click on solution in Solution Explorer and select "Restore NuGet packages"

Expected: It restores packages like it does when I run dotnet restore from the command line
Actual: I get this error here... and I'm not sure why because I don't think this is a path I've modified in my projects.

Output window for Package Manager:
All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.5279550
========== Finished ==========

Error occurred while restoring NuGet packages: BaseIntermediateOutputPath

**Comment by mishra14** [comment] 2017-02-17 01:30
Dupe of: https://github.com/NuGet/Home/issues/4528.

The problem is that the project Microsoft.Fx.Portability.Reports.Html does not have an obj directory (which is the BaseIntermediateOutputPath). 

NuGet Restore expects the obj dir and fails when it does not exist. This happened in this case because the project was manually migrated and did not have an obj directory that a normal legacy-csproj project would have.

@nkolev92 : has a fix at https://github.com/NuGet/NuGet.Client/pull/1179

**Closed as completed** 2017-02-17 21:45 UTC
Labels: Resolution:Duplicate, Triage:NeedsTriageDiscussion
