### ISSUE TITLE
NuGet CLI restore multiple solutions at once

### ISSUE THREAD

**Issue by Cheesebaron** [NuGet/Home#6397] opened 2018-01-08 16:50 UTC
## Details about Problem

I have a build where I need to restore packages for approximately 140 solutions, with each multiple projects. I am using the NuGet CLI tool to do so.

Restoring NuGet’s when the cache is cleared takes around 18 minutes for these solutions and around 6 minutes when the cache contains all the packages.

I find that since I need to feed NuGet.exe with one solution at a time, the 6 minutes when cache contains all packages, is made up of the overhead it takes for NuGet.exe to initialize and not the restore command itself.
I can reduce the 6 minutes to around 30 seconds if I generate a solution file, with all the projects all the 140 or so solutions contain and restore packages against that generated solution file.

Would it be possible to have NuGet restore accept multiple sln or csproj files to restore packages for. Perhaps do something clever not to attempt to restore the same packages more than one time etc.

NuGet version 4.4.1.4656

## Detailed repro steps so we can see the same problem

1. Create a whole bunch of solutions with multiple projects each having NuGet dependencies

2. Restore using NuGet

**Comment by nkolev92** [comment] 2018-01-08 23:53
Let me start with saying that this is a very unusual scenario :)
Can you please share some more details about what you are doing.

What's your project restore style?

There are more options if you're using package reference, less so if it's packages.config. 

A feature like this would require some discussion and design work, so we'll need to evaluate how much demand we'd have for something like this.

**Comment by Cheesebaron** [comment] 2018-01-09 08:44
So this is a mix of some projects using packages.config, because Service Fabric projects do not support PackageReference, yet (maybe they do, they didn't last time I checked).
Most of the other projects use PackageReference. So it is a mix.

I am building a Web App, which consists of a bunch of worker roles, shared libraries, ASP.NET MVC projects and other Azure type projects. Having all this in one solution doesn't work as Visual Studio has a hard time coping with all the projects.

**Comment by emgarten** [comment] 2018-01-09 20:59
@Cheesebaron you can pass a list of projects to the restore target to restore all of them for PackageReference. You can find all projects by using wildcards in MSBuild. Take a look at how nuget's build scripts run restore: https://github.com/NuGet/NuGet.Client/blob/f4e79afae5d47b6fce93c1080e6946bd61dc0cdf/build/build.proj#L369-L384

packages.config is a bit trickier since each solution needs to download the packages to a different folder since they are per-solution. I don't think there is a good way to combine this.

**Comment by Cheesebaron** [comment] 2018-01-10 08:18
I use a NuGet.config which specifies where to download packages, so this is not done per solution, but rather central for all of them.

The NuGet CLI doesn't seem to allow passing multiple projects in as arguments.

For now, as I described in the opening post, I generate a solution for all the projects that use packages.config on the fly and restore against that, then do the same thing right after for those using PackageReference. Which works very well. NuGet CLI plows through the projects and restores packages for them. Contrary iterating over a collection of csproj files having the overhead of NuGet CLI having to start up each time, which takes so much longer.

Is NuGet only designed to take one solution at a time and restore for that? I can't be the only person with a setup consisting of more than one solution that needs to be restored when building?

**Comment by marcus-sonestedt** [comment] 2019-04-01 09:00
@Cheesebaron We have the same issue. Could you perhaps share the .sln generation code?

**Comment by Cheesebaron** [comment] 2019-04-01 13:49
@marcusl I've been doing this with a Cake script: https://gist.github.com/Cheesebaron/b21d2e9967bdedc56eac63a3d7b239aa

This is just C#. Although the globbing method `GetFiles()` is specific to Cake, the same goes for the NuGetRestore alias and some of the other method calls you see in there.

It is just a matter of locating projects which use packages.config and put them into a new temp solution. Then do the same for PackageReference projects. Then restore then in two separate passes.

**Comment by marcus-sonestedt** [comment] 2019-04-06 15:42
@Cheesebaron Thanks alot! I'll get on it next week and adapt it to cake-agnostic script, maybe a msbuild task or something.

**Comment by nkolev92** [comment] 2020-05-20 01:03
Thank you all for this issue.

We appreciate the feedback, however at this point we do not see ourselves changing the one operation, one solution behavior. 
We're prioritizing problems that are impact a wider set of customers.
As such I'm gonna close this issue as by design.

**Closed as completed by nkolev92** 2020-05-20 01:03 UTC
Labels: Type:DCR, Resolution:ByDesign, Tenet:Performance, Functionality:Restore
