### ISSUE TITLE
Nuget sources option does not concatenate with Nuget.config

### ISSUE THREAD

**Issue by psandhu79** [NuGet/Home#5767] opened 2017-08-17 10:20 UTC
We are currently trying to VSTS package management which requires you to use the

nuget.exe sources Add -Name "Libraries" -Source "feed" -username user - password PAT -storeincleartext

This will add the source to the nuget.config

i would like to be able to do the following

nuget restore my.sln -Source \\networkshare;Libraries <- added to the nuget.config file

I would like to append the sources on the command line , i do not want to add the network share to the nuget.config file.

How can this me achieved if i add the feed url to the command it does not use the PAT token

**Comment by zhili1208** [comment] 2017-08-21 20:56
you can concatenate source with restore

nuget restore my.sln -Source "\networksahre;Libraries", and if the source need PAT, you will get prompt for username and password

**Comment by mishra14** [comment] 2017-08-21 23:30
@psandhu79: Thanks for reporting the issue that you are facing.

Let me clarify the comment by @zhili1208. You have 2 options - 

1. If you just want to use the network source then you can use `nuget restore my.sln -Source "\networksahre;Libraries"`. This will only use the network source for the restore.
2. If you want to use the network source and the other sources in your config file then, please make a new config file and add the network source in there. Then you can restore using the new config file - `nuget restore my.sln -ConfigFile "path_to_new_config_file"`

please let us know if you need any more help.

**Comment by psandhu79** [comment] 2017-08-23 17:38
Hi

Thank you @zhili1208 and @mishra14 i can do what you suggested. I was just hoping to add some general VSTS feeds to the shared nuget.config which contain PAT tokens. Then depending on the build add additional source when required.

If i add the network share to the a local .nuget.config in the source area will it concatenate with the nuget.config file in appdata

**Comment by mishra14** [comment] 2017-08-23 17:45
@psandhu79 : Thanks for your response. If you add a source to your local nuget.config then restore will use the sources from the config file that you pass and the one in appdata.

**Comment by psandhu79** [comment] 2017-08-24 16:20
Thank you all this can be closed

**Comment by psandhu79** [comment] 2017-08-28 13:31
Ok something i do not understand using Nuget 3.5.0
 if i do the following 

`nuget.exe sources Add -Name "Libraries" -Source "feed" -username user - password PAT -storeincleartext`

then run
`nuget.exe restore my.sln -Source Libraries ` 
it cannot restore from the Libraries feed and says it cannot find myworkdingdirectory\libraries

however because the Libraries feed is in the nuget.config file

`Nuget.exe restore my.sln` 

works

**Comment by psandhu79** [comment] 2017-08-28 13:58
Update

It works fine on 3.4.4, does not work on 3.5.0 👎

**Comment by mishra14** [comment] 2017-08-28 23:54
@psandhu79 Thanks for reaching out. Its possible this was an issue in 3.5.0. 

Can you please download [v4.3.0](https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe) and try the same scenario?

If you are still facing the issue, then could you please give us the out put of the following command -

`Nuget.exe sources -format detailed`

**Comment by psandhu79** [comment] 2017-08-29 05:28
Hi

does not work still with 4.3.0
 command i run is 
`nuget.exe restore Extensions\Solution\src\Solution.sln -Source "PetrelLibraries"`

error i receive is 

Failed to retrieve information about 'NETStandard.Library' from remote source 'I:\P\2018\2018\Solution\PetrelLibraries'.

my workdir is I:\P\2018\2018\Solution\

output from `Nuget.exe sources -format detailed`

Registered Sources:

  1.  nuget.org [Disabled]
      https://api.nuget.org/v3/index.json
  2.  slb-ocean [Enabled]
      https://my.visualstudio.com/_packaging/slb-ocean/nuget/v3/index.json
  3.  PetrelLibraries [Enabled]
      https://my.visualstudio.com/_packaging/PetrelLibraries/nuget/v3/index.json
  4.  PetrelTestData [Enabled]
      https://my.visualstudio.com/_packaging/PetrelTestData/nuget/v3/index.json

**Comment by mishra14** [comment] 2017-08-31 22:07
@psandhu79 I think the issue is that restore expects a complete source path. 

So you will have to execute - 
```
nuget.exe restore Extensions\Solution\src\Solution.sln -Source https://my.visualstudio.com/_packaging/PetrelLibraries/nuget/v3/index.json
```

or if you have already added the source to a config file, then just execute -

```
nuget.exe restore Extensions\Solution\src\Solution.sln
```

Please let us know if you need more help!

**Comment by psandhu79** [comment] 2017-09-01 07:22
Hi @mishra14 
I can confirm this works
nuget.exe restore Extensions\Solution\src\Solution.sln

However i wanted to be able to limit the feed used to just PetrelLibraries

If i use the following 

nuget.exe restore Extensions\Solution\src\Solution.sln -Source https://my.visualstudio.com/_packaging/PetrelLibraries/nuget/v3/index.json
 it does not use the PAT token in the config file.

Whats strange is if you do the same for a nuget.package using install it works 

Nuget install mypackage.nupkg -Source PetrelLibraries

**Comment by mishra14** [comment] 2017-09-05 18:41
@psandhu79 I will look more into why restore does not take a source but install does.

In the mean time, you can do the following -

1. Create a new config file.
2. Add PetrelLibraries as a source into the config file with the PAT access token.
3. Pass the config file to restore - `nuget restore my.sln -ConfigFile "path_to_new_config_file"`

**Comment by mishra14** [comment] 2017-09-05 19:43
@psandhu79 Thanks for all the details. I believe this is a bug and I have opened up a new issue at https://github.com/NuGet/Home/issues/5849

I will close this issue. Please follow that issue if you need to track it or request any help!

**Closed as completed by mishra14** 2017-09-05 19:43 UTC
Labels: Functionality:Restore
