### ISSUE TITLE
NuGet Pack modifies the escape character to escape code in file path

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#5994] opened 2017-10-05 21:16 UTC
While packing a NuGet package, file path is being updated to have escape code instead of actual character in output nupkg.

Steps:
1. Take this sample solution https://github.com/NuGet/Samples/tree/master/ContentFilesExample/authoring 
2. With latest NuGet.exe, run `nuget pack ContentFilesExample.nuspec -Exclude pack.ps1`

Expected:
.nupkg has `ContentFilesExample.1.0.0.nupkg\contentFiles\cs\portable-net45+wpa81+wp8+win8\`

Actual:
.nupkg had `ContentFilesExample.1.0.0.nupkg\contentFiles\cs\portable-net45%2Bwpa81%2Bwp8%2Bwin8\`

**Comment by rohit21agrawal** [comment] 2017-10-05 23:21
Dupe of https://github.com/NuGet/Home/issues/5956

**Closed as completed by rohit21agrawal** 2017-10-05 23:21 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Pack
