### ISSUE TITLE
Provide Detailed Missing Dependency Messages

### ISSUE THREAD

**Issue by JaimeStill** [NuGet/Home#8650] opened 2019-10-01 12:13 UTC
## Details about Problem

When a `dotnet build` fails in an offline environment, it does not provide adequate context regarding the package that was missing and the source it was missing from.

**`dotnet build` Error**  
```
C:\Program Files\dotnet\sdk\3.0.100\Nuget.targets : error : 
Unable to load the service index for source https://api.nuget.org/v3/index.json.
C:\Program Files\dotnet\sdk\3.0.100\Nuget.targets : error :
No such host is known.
```

Likewise, if a warning is encountered when running `dotnet restore` in an offline environment, the warning does not specify the source the missing dependency is missing from.

**`dotnet restore -s %USERPROFILE%\.nuget\packages` Warning Example**  
```
Warning NU1603 : Microsoft.Data.SqlClient 1.0.19249.1 depends on
runtime.native.System.Data.SqlClient.sni (>= 4.4.0) but
runtime.native.System.Data.SqlClient.sni 4.4.0 was not found.
An approximate best match of runtime.native.System.Data.SqlClient.sni
4.5.0 was resolved.
```

## Environment Details

NuGet product used: `dotnet` CLI  
NuGet version: 5.3.0.4  
dotnet.exe --version: 3.0.100  
OS version (i.e. win10 v1607 (14393.321)): Windows 10 v1903 (18362.387)

## Detailed repro steps so we can see the same problem

> See [dotnet/SqlClient - Microsoft.Data.SqlClient not restoring from Global NuGet Cache - 1.0.19249.1](https://github.com/dotnet/SqlClient/issues/236) for full history that led to this issue.

`runtime.native.System.Data.SqlClient.sni` 4.4.0 was missing from [C:\Program Files\dotnet\sdk\NuGetFallbackFolder](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Fallback-package-folders) in my offline environment.

This pre-built package is a dependency for `Microsoft.Data.SqlClient`, so to repro, remove the above pre-built package from the `NuGetFallbackFolder` on a machine with no internet connection and run the following:

```
dotnet new classlib -f netcoreapp3.0 -o {ProjectName}
cd {ProjectName}

// For error message
dotnet build

// For restore warning
dotnet restore -s %USERPROFILE%\.nuget\packages
```

## Other suggested things

**Offline Build Error Messages**  
Should indicate the missing package that caused the error, as well as the location it was searched for. In order to guide the user towards how to remedy the missing dependency, something similar to the following could be appended as a third line to the current error message:

```
C:\Program Files\dotnet\sdk\3.0.100\Nuget.targets : error :
{dependency} could not be located in {sources}
```

This would give an indication as to how to fix build issues in a disconnected environment.

**Offline Restore Warning Messages**  
The current warning message already indicates the package that was missing, as well as an approximate best match. In order to guide the user towards how to remedy the missing dependency, adding the location the package is missing from to the warning would be helpful. Something similar to the following:

```
Warning NU1603 : {package} depends on {dependency} ({min-version}) 
but {dependency}{version} was not found at {location}. 
An approximate best match of {package}{found-version} was resolved
at {location}.
```

**Comment by rrelyea** [comment] 2019-10-04 18:26
>>When a dotnet build fails in an offline environment, it does not provide adequate context regarding the package that was missing and the source it was missing from.

The restore errors out because not all sources are available.
Feeds need to be disabled if they are not available if you don't want to error out.

About the warning...
We don't care where the package comes from...if we cannot find it, that means it is in none of the sources. 

dotnet restore defaults to verbosity of minimal. If you switch to verbosity normal, it will list all the sources. `dotnet restore --verbosity normal`

Given all of that, we likely could improve the wording for the warning and error (likely having a NU#### code would be good, so a doc page could explain more. Other thoughts?

**Comment by JaimeStill** [comment] 2019-10-04 19:02
The `--verbosity normal` flag would be adequate for the build error.

With regards to the restore warning, I still think it would be very beneficial to know the source of where the approximate best match was found. In the example / issue documented above, I was completely unaware that a `NuGetFallbackFolder` was used as a source for pre-built packages. Particularly when this directory is not listed in `dotnet nuget locals all --list`.

If specifying the source of where an approximate best match was found is not feasible, perhaps adding the `NuGetFallbackFolder` to the list of locals would be acceptable?

**Comment by nkolev92** [comment] 2020-04-30 17:57
Per this [comment](https://github.com/NuGet/Home/issues/8650#issuecomment-538510654)
We don't correlate the package source and package version. 

Closing this as not a bug. 

Please feel free to open new issues for any additional problems/suggestions. 
Thank you!

**Closed as completed by nkolev92** 2020-04-30 17:57 UTC
Labels: Resolution:NotABug
