### ISSUE TITLE
`dotnet nuget verify` command is not recognizing --configfile ..\nuget.config

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10773] opened 2021-04-15 19:14 UTC
## Details about Problem

NuGet product used (dotnet.exe):

Product version: 5.9

Worked before? If so, with which NuGet version: N/A

## Repro steps and/or sample project
Run below command, it should honor custom nuget.config file but if throws error.
`dotnet nuget verify ..\TestSigned\TestSigned.1.0.0.nupkg --configfile ..\nuget.config`

### Verbose Logs

Specify --help for a list of available options and commands.
error: Unrecognized option '--configfile'

Usage: dotnet nuget verify [arguments] [options]

Arguments:
  <package-paths>  Specify the path to the package

Options:
  --all                      Specifies that all verifications possible should be performed to the package(s).
  --certificate-fingerprint  Verify that the signer certificate matches with one of the specified SHA256 fingerprints. A certificate SHA256 fingerprint is a SHA256 hash of the certificate used to identify the certificate. Multiple inputs should be separated by space.
  -v|--verbosity             Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
  -h|--help                  Show help information

**Comment by kartheekp-ms** [comment] 2021-04-19 20:28
Duplicate of #10011

**Closed as completed by kartheekp-ms** 2021-04-19 20:28 UTC
Labels: Priority:2, Type:Bug, Functionality:Signing, Product:dotnet.exe, Category:Quality Week
