### ISSUE TITLE
Funny license in jquery.validate.unobtrusive.js

### ISSUE THREAD

**Issue by omajid** [NuGet/Home#5771] opened 2017-08-17 20:41 UTC
NuGet is licensed under Apache 2.0: https://github.com/NuGet/NuGet.Services.Metadata/blob/release/LICENSE.txt. But some files in that repository have a very funny license. For example, https://github.com/NuGet/NuGet.Services.Metadata/blob/release/tests/PublishTestDriverWebSite/Scripts/jquery.validate.unobtrusive.js has a license that I think is Open Source, but isn't explicit about it:

    /* NUGET: BEGIN LICENSE TEXT
     *
     * Microsoft grants you the right to use these script files for the sole
     * purpose of either: (i) interacting through your browser with the Microsoft
     * website or online service, subject to the applicable licensing or use
     * terms; or (ii) using the files as included with a Microsoft product subject
     * to that product's license terms. Microsoft reserves all other rights to the
     * files not expressly granted by Microsoft, whether by implication, estoppel
     * or otherwise. Insofar as a script file is dual licensed under GPL,
     * Microsoft neither took the code under GPL nor distributes it thereunder but
     * under the terms set out in this paragraph. All notices and licenses
     * below are for informational purposes only.
     *
     * NUGET: END LICENSE TEXT */
    /*!
    ** Unobtrusive validation support library for jQuery and jQuery Validate
    ** Copyright (C) Microsoft Corporation. All rights reserved.
    */

It sounds to me like (ii) says this file is being licensed under the license of the rest of the repository, which is Apache 2.0. But it doesn't clearly come out and say so. If I clone this source, is the Open Sourced source code a "product"? Can you please fix this license and similar licenses on other files to be more explicit? It will make it easier for us to feel more comfortable about Nuget and .NET being more open source.i

cc @leecow

**Comment by leecow** [comment] 2017-08-17 21:14
@rrelyea to have a look.

**Comment by omajid** [comment] 2017-08-18 15:07
This also affects some files in NuGet.Client repository such as https://github.com/NuGet/NuGet.Client/blob/dev/test/EndToEnd/ProjectTemplates/JScriptVisualBasicLightSwitchProjectTemplate.zip/jquery-1.9.1.js

**Comment by omajid** [comment] 2017-08-19 02:01
cc @richlander

**Comment by omajid** [comment] 2017-08-21 14:35
cc @Bob-Davis

**Comment by rrelyea** [comment] 2017-08-21 21:07
dupe of #5776

**Closed as completed by rrelyea** 2017-08-21 21:07 UTC
Labels: Priority:1, Resolution:Duplicate
