### ISSUE TITLE
NuGet restore is hanging in various CI runs (through dotnet restore)

### ISSUE THREAD

**Issue by mellinoe** [NuGet/Home#2416] opened 2016-03-30 00:21 UTC
We've seen this on and off in our CI runs, and have managed to at least get a callstack for one instance of it:

```
mscorlib.ni.dll!System.Threading.ManualResetEventSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)               
mscorlib.ni.dll!System.Threading.Tasks.Task.SpinThenBlockingWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)
mscorlib.ni.dll!System.Threading.Tasks.Task.InternalWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)               
mscorlib.ni.dll!System.Threading.Tasks.Task<int>.GetResultCore(bool waitCompletionNotification)
NuGet.CommandLine.XPlat.dll!Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(string[] args)
NuGet.CommandLine.XPlat.dll!NuGet.CommandLine.XPlat.Program.Main(string[] args)
[Native to Managed Transition] 
[Managed to Native Transition] 
dotnet.dll!Microsoft.DotNet.Tools.Restore.NuGet3.Run(string[] nugetArgs)
dotnet.dll!Microsoft.DotNet.Tools.Restore.RestoreCommand.Run.AnonymousMethod__2()
dotnet.dll!Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(string[] args)
dotnet.dll!Microsoft.DotNet.Cli.Program.ProcessArgs(string[] args)
dotnet.dll!Microsoft.DotNet.Cli.Program.Main(string[] args)
```

I also have a dump of the process where this occurred, which I can share offline if needed. It looks like the hang occurs after we call into `NuGet.CommandLine.XPlat.dll`

@joshfree, @joelverhagen , @mmitche

**Comment by mellinoe** [comment] 2016-03-30 00:23
@ericeil helped debug this as well.

**Comment by emgarten** [comment] 2016-03-30 03:21
This looks like a dupe of: https://github.com/NuGet/Home/issues/2371

A fix went into nuget last week for this, try the latest version of the CLI to get it.

**Comment by yishaigalatzer** [comment] 2016-03-30 18:56
Closing because the CLI was using old bits

**Closed as completed** 2016-03-30 18:56 UTC
Labels: Resolution:NotRepro
