### ISSUE TITLE
Private Feed Credentials Dialog does not save/remember credentials

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#5516] opened 2017-06-30 12:33 UTC
## Details about Problem
Within VS 2015 or 2017,  after entering private feed credentials in the dialog it does not save/remember credentials.

Worked before?:
This has never worked before.

## Detailed repro steps so we can see the same problem

1. Set up private feed

2. Set the private feed as the NuGet source, then attempt to browse packages for the private feed

3. Enter your credentials, select the checkbox to remember them.

4.  Close VS, Reopen VS

5.  Attempt to browse your private feed

Bummer, you must reenter your credentials.

**Comment by anangaur** [comment] 2017-06-30 16:27
Looks like dupe of https://github.com/NuGet/Home/issues/4615

**Comment by mishra14** [comment] 2017-10-17 18:45
@kdawg1406 This is a dupe of https://github.com/NuGet/Home/issues/4615. Please follow that issue for tracking.

**Closed as completed by mishra14** 2017-10-17 18:45 UTC
Labels: Resolution:Duplicate
