### ISSUE TITLE
Excluding Analyzer on Package refercne does not turn off Analyzer

### ISSUE THREAD

**Issue by KevinGrealish** [NuGet/Home#7422] opened 2018-10-22 21:05 UTC
## Details about Problem
NuGet product used:
VS UI

dotnet.exe --version (if appropriate):
2.1.403

VS version (if appropriate): 
15.8.7

OS version:
win10 v1807 (17763.55)

NuGet version (x.x.x.xxx):
Whatever VS has.

Unknown if this ever worked.

## Detailed repro steps so we can see the same problem

1. Create new .NET core console.
2. Add nuget reference to the project Microsoft.ML 0.6.0
3. Edit .csproj file to add ExcludeAssets
```
    <PackageReference Include="Microsoft.ML" Version="0.6.0">
      <ExcludeAssets>analyzers</ExcludeAssets>
    </PackageReference>
```
4. unload and reload project.
BUG: Analyzer from Microsoft.ML remains in solution explorer.
EXPCET: Analyzer in solution explorer to disappear. Analyzer from Microsoft.ML to not run.

**Comment by nkolev92** [comment] 2018-10-22 22:11
Thanks for filing this issue @KevinGrealish 

This is a duplicate of https://github.com/NuGet/Home/issues/6279. 

Originally analyzers were added without any work from the NuGet side, so that's why this hole exists.

**Closed as completed by nkolev92** 2018-10-22 22:11 UTC
Labels: Functionality:Restore, Area:PackageDefinition, Style:PackageReference
