### ISSUE TITLE
Nuget package with mask 1.* is not automaticaly updated

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#6409] opened 2018-01-10 23:28 UTC
Nuget package with mask 1.* is not automaticaly updated. 

Example I have this package referenced 
&lt;PackageReference Include=&quot;MyPackage&quot; Version=&quot;1.*&quot; /&gt; 
but with this convention the package is not automaticaly updated,
I need to delele local nuget cache, then the package reference gets updated within the rebuild of the solution or project. 
But VS still offers me that there is a new veriosn of the package which is not since it has been already referenced, 
So I think there are 2 issues.
- new package matching 1.* mask is not automaticaly updated
- once the reference package is updated I should not see information about new package (on manage package for solution page) since I'm already using this package

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/121593/nuget-package-with-mask-1-is-not-automaticaly-upda.html
VSTS ticketId: 501327_
_These are the original issue comments:_

Patricio Beltran Saldivar [MSFT] on 10/3/2017, 03:07 PM (99 days ago): <p><strong>Hey Richard! Thanks for submitting feedback and help us improve Visual Studio! In regards to the first issue you mention, can you please give me more information about your project so I can repro that behavior?If you can upload the code to github or one drive, or provide some repro steps for a new project I would greatly appreciate it!</strong></p><p><strong>As for the second issue you mention, this is a known bug we are working to fix, you can see our proposal </strong><a target='_blank' href="https://github.com/NuGet/Home/wiki/%5bSpec%5d-NuGet-Build-Integrated-Project-handling-of-floating-versions-and-ranges-in-Visual-Studio-Client " target="_blank"><strong>here</strong></a><strong>. This spec links to the different issues where we have seen this bug repro, please feel free to comment in any of them.</strong></p>

_These are the original issue solutions:_

richard.golsky solved on 10/4/2017, 06:51 AM (98 days ago), 0 votes: 
<p>Basically if you want to reference your own nuget pakages which version is higher than 1.* then it is not pulled from repository automaticaly, it seems to me like it works only on 3rd a4th place in semver2, we are using https://www.sonatype.com/nexus-repository-oss as our repository</p>
<p>examples:</p>
<p>not ok: 1.* - package for example 1.3.0.0 is NOT automatically pulled from repository, and it should be</p>
<p>not ok: 1.0.0-word1-word2-word3.* - package for example 1.0.0-word1-word2-word3.5 is NOT automatically pulled from repository</p>
<p>ok: 1.0.* - package for example 1.0.3.0 is automatically pulled from repository</p>
<p>ok: 1.0.0.* - package for example 1.0.0.3 is automatically pulled from repository</p>

 

richard.golsky on 10/4/2017, 06:52 AM (98 days ago): 
<p>also I don't think nuget support semver2 accordingly, for example there is nothing wrong with 2nd example</p> 

Patricio Beltran Saldivar [MSFT] on 10/4/2017, 03:53 PM (98 days ago): 
<p>I see. Can you please give me a little more information on the packages you are expecting to get and which are already installed for each case you provide? Also, have these packages been updated in the last few hours? Can you also try removing the obj folder when you update the package reference (so we can force a restore to happen) and see if that helps?</p> 

richard.golsky solved on 10/5/2017, 02:17 AM (97 days ago), 0 votes: 
<p>I'm referencing my own packages, so you wont find them in a public repository, but based on this article https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards </p>
<p>all described cases should be supported</p>

**Comment by nkolev92** [comment] 2020-02-12 20:11
Duplicate of: 
https://github.com/NuGet/Home/issues/5445
https://github.com/NuGet/Home/issues/3788
https://github.com/NuGet/Home/issues/3101

**Closed as completed by nkolev92** 2020-02-12 20:11 UTC
Labels: Type:Bug, Functionality:Restore
