### ISSUE TITLE
Migrate packages.config to PackageReference unexpectedly closes Visual Studio 

### ISSUE THREAD

**Issue by bladewolf55** [NuGet/Home#7387] opened 2018-10-10 16:08 UTC
## Environment
*   Visual Studio Community 2017 Preview 15.9.0 Preview 3.0
*   Side-by-side install with VS Community 2017
*   Windows 10 Professional 1803 (17134.345)

## Detailed repro steps so we can see the same problem
Only VS Preview was opened, not regular VS.

1.   Open .NET Framework 4.6.1 Console Application with multiple NuGet packages installed. 
2.   Default package management format is set to `packages.config`
3.   Right-click on References, choose "Migrate packages.config..."
4.   Visual Studio shuts down with no error message.

## More Information
Setting the default package management format to PackageReference OR initializing NuGet by opening package manager allows the converter to run. The documentation "Know Issues" suggests doing this to display the context menu item, but I don't see sudden closing of VS mentioned.

The Windows Application Event Log does have several errors, which I've attached. Event Log Text, below (oldest to newest).

```txt

Level:    Error
Source:   .NET Runtime  
Event ID: 1026  

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at NuGetVSExtension.NuGetPackage+<ExecuteUpgradeNuGetProjectCommandAsync>d__71.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

------------------------------------------------------------------
Level:    Error 
Source:   Application Error  
Event ID: 1000  

Faulting application name: devenv.exe, version: 15.9.28124.53, time stamp: 0x5ba98baa
Faulting module name: KERNELBASE.dll, version: 10.0.17134.319, time stamp: 0x5ea0e53d
Exception code: 0xe0434352
Fault offset: 0x001117d2
Faulting process id: 0x3af4
Faulting application start time: 0x01d460b12c43707b
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 40b39490-a234-4445-a265-174391c2ba76
Faulting package full name: 
Faulting package-relative application ID: 

-----------------------------------------------------------------
Level:    Information
Source:   Windows Error Reporting
Event ID: 1001

Fault bucket 1594935281100369433, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 15.9.28124.53
P3: 5ba98baa
P4: NuGet.Tools
P5: 4.9.0.5507
P6: b1f0b065
P7: ff
P8: 11e
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\Users\charl\AppData\Roaming\microsoft\visualstudio\15.0_1d55ff98\activitylog.xml
\\?\C:\Users\charl\AppData\Local\microsoft\visualstudio\15.0_1d55ff98\devenv.exe.config
\\?\C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\devenv.isolation.ini
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8AE.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBEB.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBFC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBFC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC1C.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_devenv.exe_998b24f4bd956f21de11ea95bf9d38f34357b_e66a7f63_45270e3c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 40b39490-a234-4445-a265-174391c2ba76
Report Status: 268435456
Hashed bucket: 76fc4fe75fb04ca97622593015b9ae19
Cab Guid: 0

```

### Attachments

[AppCrash_devenv.exe_998b24f4bd956f21de11ea95bf9d38f34357b_e66a7f63_45270e3c.zip](https://github.com/NuGet/Home/files/2465479/AppCrash_devenv.exe_998b24f4bd956f21de11ea95bf9d38f34357b_e66a7f63_45270e3c.zip)

**Comment by rrelyea** [comment] 2018-10-11 21:54
@jainaashish  - Believe this is already fixed. Can you point to commit or dupe issue?

**Comment by bladewolf55** [comment] 2018-10-11 23:09
Here's the information running `$host` in the Visual Studio Preview Package Manager Console. Is this what you need?

```txt
Name             : Package Manager Host
Version          : 4.9.0.5507
InstanceId       : 3a3e134a-1412-4601-9038-6773a7928f03
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : NuGetConsole.Host.PowerShell.Implementation.NuGetPSHost+Commander
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

I literally downloaded the latest Visual Studio Preview the same day I filed the issue. I didn't find a duplicate issue when I searched previously.

I've attached the project. 

[VsProjectRepair.zip](https://github.com/NuGet/Home/files/2470994/VsProjectRepair.zip)

**Comment by jainaashish** [comment] 2018-10-11 23:56
yes dupe of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/692256  fixed with https://github.com/NuGet/NuGet.Client/pull/2448

**Closed as completed by jainaashish** 2018-10-11 23:56 UTC
Labels: Type:Bug, RegressionDuringThisVersion

**Comment by bladewolf55** [comment] 2018-10-12 00:04
Thanks.
