### ISSUE TITLE
[Bug]: NuGet goes nuts if two PackageReference projects live in same directory

### ISSUE THREAD

**Issue by crusader-mike** [NuGet/Home#11398] opened 2021-11-18 17:58 UTC
### NuGet Product Used

MSBuild.exe

### Product Version

VS 2019 v16.11.5

### Worked before?

no

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Have two .csproj files in the same directory 
2. install a nuget package into each one using PackageReference
3. trigger NuGet restore
4. enjoy it overwriting obj/project.assets.json and obj/project.nuget.cache in random order and generally go nuts, spewing errors messages, etc. 

Works beautifully in 100+ project solution which was just migrated to use PackageReferences. I spent enormous amount of time before I found this... It is easy to override `BaseIntermediateOutputPath` with `obj\$(MSBuildProjectName)` (just make sure you do it before importing `Microsoft.Common.props`. But this problem should not exists in the first place.

Related to: NuGet/docs.microsoft.com-nuget#852, dotnet/sdk#1057

**Comment by dominoFire** [comment] 2021-11-18 18:11
Thanks for reporting this issue. It seems you found a way to restore two projects in the same folder. 👏🏽

I will close this issue for now. If you have more questions, please let us know

**Closed as completed by dominoFire** 2021-11-18 18:11 UTC
Labels: Functionality:Restore, Resolution:NotABug, Type:Learning

**Comment by crusader-mike** [comment] 2021-11-18 18:13
@dominoFire Any reason why you closed this problem instead of fixing it? Just because there is a workaround? Really?

**Comment by cdrfun** [comment] 2022-06-24 06:39
Thanks a lot for documenting this [crusader-mike](https://github.com/crusader-mike). It's a shame we are not even getting an explanation for not fixing the issue.

**Comment by dominoFire** [comment] 2022-07-29 00:40
@crusader-mike Sorry about this. The reason I closed this issue was because we We think it's a duplicate of https://github.com/NuGet/Home/issues/4463

Please upvote in the linked issue. That helps in our triaging process.

Thanks again for reporting.

**Comment by tqk2811** [comment] 2022-12-14 13:46
How to overwrite before importing `Microsoft.Common.props` in `<Project Sdk="Microsoft.NET.Sdk">...`

**Comment by joshudson** [comment] 2024-01-10 16:12
It's not a duplicate. BaseIntermediateOutputPath doesn't always work due to design constraints in msbuild. IntermediateOutputPath should work but doesn't.

MSBuildProjectExtensionsPath doesn't work at all.

```
/usr/share/dotnet/sdk/6.0.417/Microsoft.Common.CurrentVersion.targets(846,5):
    error MSB3540: The value of the property "MSBuildProjectExtensionsPath" was modified after
    it was used by MSBuild which can lead to unexpected build results.  To set this property,
    you must do so before Microsoft.Common.props is imported, for example by using
    Directory.Build.props.  For more information, please visit
    https://go.microsoft.com/fwlink/?linkid=869650 [/home/joshua/netcore/Emet/FileSystems/Emet.FileSystems.ref.csproj]
```

And the link is useless.
