### ISSUE TITLE
RestoreSources together with SDK dependencies seems not to work

### ISSUE THREAD

**Issue by TFTomSun** [NuGet/Home#9121] opened 2020-01-31 10:38 UTC
I tried to move away from the NuGet.Config to a pure MSBuild based restore logic. When I try to set the RestoreSources in the Directory.Build.props and reference an SDK I get build errors:

```xml
   <RestoreSources>
      $(LocalSource);
      $(NugetSource);
      $(PrivateRemoteSource);
    </RestoreSources>
  </PropertyGroup>

  <Import Sdk="My.Sdk" Version="1.0.0" Project="Sdk.props"/>

```

The error messages are : 

> Unable to resolve My.Sdk for NetStandard, Version=0.0.
> C:\Program Files\.....\Sdk not found. Check that recent enough .NET Core SDK is installed. 

Actually I expect that sdk to be restored from the PrivateRemoteSource. It works, when I use a NuGet.Config instead.

**Comment by nkolev92** [comment] 2020-01-31 22:30
This is a duplicate of https://github.com/NuGet/Home/issues/7855.

Unfortunately anything coming through msbuild won't work because of msbuild ordering issues. 

//cc @jeffkl

**Closed as completed by nkolev92** 2020-01-31 22:30 UTC
Labels: Resolution:Duplicate, Type:Bug, Product:MSBuildSDKResolver
