### ISSUE TITLE
Package restore bar (the yellow bar) is still visible after packages are automatically restored

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#675] opened 2015-05-28 18:38 UTC
Repro steps:
- create a new class library, install some packages
- delete some packages folder
- start package manager console or UI, install some new packages not installed in step 1

Expected: automatic restore will happen before installing package on step 3. After that, the yellow bar saying some NuGet packages are missing should be gone, as at this point all packages are restored. 

Actual: yellow bar still present. We did not refresh the UI/PMC.

**Comment by yishaigalatzer** [comment] 2015-05-29 17:26
Looks like a duplicate of #683

**Closed by yishaigalatzer** 2015-05-29 17:26 UTC
