### ISSUE TITLE
Building a new enlistment fails

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5300] opened 2017-05-31 07:06 UTC
_From @jcouv on May 30, 2017 23:15_

I cloned the repo, then ran `build.cmd` from a VS2017 command prompt and got the failures below.

![image](https://cloud.githubusercontent.com/assets/12466233/26608927/0fd46d78-4553-11e7-8f76-df61203b2d8c.png)

@srivatsn for assistance.
@OmarTawfik in case you've encountered this.

_Copied from original issue: dotnet/project-system#2331_

**Comment by davkean** [comment] 2017-05-31 07:06
@emgarten How would this be possible? What builds would not have the "Restore" target?

**Comment by davkean** [comment] 2017-05-31 07:06
@jcouv Can you run the following from the VS command prompt and attach the results?
```
msbuild /pp src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj > build.pp
```

**Comment by davkean** [comment] 2017-05-31 07:06
_From @jcouv on May 31, 2017 2:7_

Attached output from `msbuild /pp`: [pp.txt](https://github.com/dotnet/project-system/files/1040126/pp.txt)

**Comment by davkean** [comment] 2017-05-31 07:06
Here's the relevant portion:

```
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportAfter\*" Condition="'$(ImportByWildcardAfterMicrosoftCommonTargets)' == 'true' and exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportAfter')">

C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets
============================================================================================================================================
-->
  <!--
***********************************************************************************************
Microsoft.NuGet.ImportAfter.targets

WARNING:  DO NOT MODIFY this file unless you are knowledgeable about MSBuild and have
          created a backup copy.  Incorrect changes to this file will make it
          impossible to load or build your projects from the command-line or the IDE.

Copyright (c) .NET Foundation. All rights reserved. 
***********************************************************************************************
-->
  <PropertyGroup xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <NuGetTargets Condition="'$(NuGetTargets)'==''">$(MSBuildExtensionsPath)\Microsoft\NuGet\$(VisualStudioVersion)\Microsoft.NuGet.targets</NuGetTargets>
  </PropertyGroup>
  <!--<Import Project="$(NuGetTargets)" Condition="Exists('$(NuGetTargets)') and '$(SkipImportNuGetBuildTargets)' != 'true'" />-->
  <!-- Import NuGet.targets for Restore -->
  <PropertyGroup xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'==''">$(MSBuildExtensionsPath)\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets</NuGetRestoreTargets>
  </PropertyGroup>
  <!--<Import Project="$(NuGetRestoreTargets)" Condition="Exists('$(NuGetRestoreTargets)')" />--> <!-- This means that is wasn't imported
  <!--
============================================================================================================================================
  </Import>
```

Basically looks like the location $(MSBuildExtensionsPath)\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets cannot be found.

Can you see if NuGet.targets exists any under Visual Studio directory in program files?

**Comment by davkean** [comment] 2017-05-31 07:06
_From @emgarten on May 31, 2017 4:52_

I would also be interested to know what workloads are installed in VS 2017. I haven't seen any issues around NuGet missing in the past, but it could be possible.

**Comment by davkean** [comment] 2017-05-31 07:06
_From @srivatsn on May 31, 2017 5:1_

@natidea mentioned running into this today as well. I wonder if this is some recent regression

**Comment by davkean** [comment] 2017-05-31 07:06
@jcouv Can you run the following:

```
msbuild /v:d src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj > build.log
```

And attach that? Perhaps MSBuildExtensionsPath is resolving to a different path? I do find it strange that NuGet is walking outside of the extensions path to find it's targets - so if MSBuild move themselves they are broken.

**Comment by davkean** [comment] 2017-05-31 07:06
_From @jcouv on May 31, 2017 7:5_

Attached new pp file: [build.txt](https://github.com/dotnet/project-system/files/1040487/build.txt)

Dave and I troubleshooted on Skype. The `NuGet.targets` file was under `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\5y0bse3d.tbd` which seemed to be the problem (the sub-folder has a random name and it's under Extensions instead of CommonExtensions).

**Comment by davkean** [comment] 2017-05-31 07:08
Moving this over to NuGet, folks it appears your extension isn't installing to a predictable path, instead of installing to Common7\IDE\CommonExtensions\Microsoft\NuGet it was installed to Common7\IDE\Extensions\5y0bse3d.tbd. 

Note not only is the final folder incorrect, so is the extensions folder (Extensions instead of CommonExtensions).

**Comment by emgarten** [comment] 2017-05-31 07:11
@davkean thanks for tracking down the cause. It looks like the NuGet VSIX didn't install correctly, I'm not sure what would cause this to install without using the well known folder.

**Comment by panopticoncentral** [comment] 2017-05-31 20:06
@emgarten What would be the fix for an install that has this problem? I just did a build-to-build upgrade and it started happening.

**Comment by tannergooding** [comment] 2017-05-31 20:10
Same here

**Comment by emgarten** [comment] 2017-05-31 22:44
Search for NuGet.targets in your visual studio installation. Copy the folder it was installed at to ``C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\``

**Comment by emgarten** [comment] 2017-05-31 23:04
@nkolev92 who is looking into this.

**Comment by nkolev92** [comment] 2017-06-01 15:47
This has been addressed in the latest dev builds. 
It should be fixed with our next insertion in the next day or two. 
I will update here once we know that.

**Closed as completed by nkolev92** 2017-06-01 15:47 UTC
Labels: Resolution:Duplicate

**Comment by davkean** [comment] 2017-06-01 23:16
@nkolev92 What was the underlying cause or point me the fix for my own education?

**Comment by nkolev92** [comment] 2017-06-01 23:30
@davkean It was a bug within NuGet's build infrastructure that led to the Installer thinking NuGet needs to be installed in a wrong location. 

Don't know how interesting/useful it is but here's the brief on it.
Within our build we create 2 slightly different VSIXs (literally the only functional difference being the install directory), each with it's own manifest. 

When inserting in VS we used the correct VSIX, but the incorrect manifest. 
https://github.com/NuGet/NuGet.Client/pull/1430

**Comment by davkean** [comment] 2017-06-01 23:31
👍

**Comment by kzu** [comment] 2017-06-03 02:46
Workaround: add this to a `Directory.Build.targets` at the root:

```
<Project>
    <Import Project="$(VsInstallRoot)\Common7\IDE\Extensions\5y0bse3d.tbd\NuGet.targets" 
            Condition="'$(IsRestoreTargetsFileLoaded)' != 'true' and Exists('$(VsInstallRoot)\Common7\IDE\Extensions\5y0bse3d.tbd\NuGet.targets')" />
</Project>
```

**Comment by nkolev92** [comment] 2017-06-03 16:57
Almost forgot to update this. 
@davkean @kzu 
Thursday's d15rel (26601) and Friday evening's  (26602) d15prerel builds already have these fixes.
