### ISSUE TITLE
NuGet doesn't restore dependencies of compatible tfm's in fallback

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#7571] opened 2018-11-30 21:32 UTC
I just hit an issue when using an old (.NET 3.5-era) package for WPF on .NET Core 3. I added the top-level package (Microsoft.WindowsAPICodePack-Shell), and that worked, but NuGet did not bring in its dependency because its has a .NET 3.5 group. This lead to a broken restore. 

I suspect more people will hit that when using old packages on .NET Core 3. Seems like something in NuGet needs to account for this and restore the matching group.

![image](https://user-images.githubusercontent.com/1427284/49316025-90cab480-f4bd-11e8-8030-73990c00127c.png)

**Comment by rrelyea** [comment] 2018-12-01 00:22
dupe of https://github.com/NuGet/Home/issues/5957, I believe.

**Comment by nkolev92** [comment] 2019-07-01 21:29
Closing per the above comment.

**Closed as completed by nkolev92** 2019-07-01 21:29 UTC
Labels: Resolution:Duplicate, Functionality:Restore
