### ISSUE TITLE
Nuget Restore does not work with pre-release Versions

### ISSUE THREAD

**Issue by patnolan** [NuGet/Home#6580] opened 2018-02-19 06:14 UTC
## Detailed repro steps so we can see the same problem

1. Create Nuget feed with only pre-release versions
2. Create Project (.csproj) with reference to nuget package using floating version i.e. <PackageReference Include="[package name]" Version="3.*" />
3. Perform Nuget CLI Restore as part of build process using Nuget feed

## Error Received
Unable to find a stable package [package name] with version (>= 3.0.0)

It seems that Nuget CLI Restore cannot handle pre-release versions which is a rather large short coming.

## Suggestion
Add  -IncludePrerelease flag

**Comment by nkolev92** [comment] 2018-02-20 19:35
@patnolan 
PackageReference restore does support prerelease version.

Can you provide a repro?

Please note, that per the way NuGet ranges are implemented:
```
 3.0.0-preview1 < 3.0.0 
```

**Comment by nkolev92** [comment] 2018-02-28 02:52
On a second look, this is a duplicate of https://github.com/NuGet/Home/issues/912

**Closed as completed by nkolev92** 2018-02-28 02:52 UTC
Labels: Resolution:Duplicate, Functionality:Restore, WaitingForCustomer
