### ISSUE TITLE
PackageReference: retargetting TFM may end up making some packages incompatible, restore needed, install may be needed.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4613] opened 2017-02-15 17:01 UTC
vs feedback issue 807290 against RC4 bits - https://developercommunity.visualstudio.com/content/problem/19520/changing-framework-versions-messes-up-references-a.html

Repro Zip attached to vs feedback item.

I have a new project I created in VS2017. I happened to choose the wrong framework version. I added a couple of NuGet packages to the project and selected the option to store them in the project file. The package assemblies show up correctly in the References node of the project. Furthermore I have .tt files that generate code based upon these references. All this works correctly.

I then go and change the Target framework of the project to something else (that is still valid). The References node removes all the NuGet packages from the tree. Additionally all the .tt files trigger regeneration. Since the package assemblies were removed from the References node this causes the .tt files that relied on them to fail.

If I do a build then the package assemblies are added back into the References node and anything that relies on them now builds. However any .tt files that were regenerated are still messed up and have to be regenerated again now that the references are back.

**Comment by rrelyea** [comment] 2017-02-16 00:35
Let's have you focus on the two perf issues. If you found anything out, please share.

**Comment by jainaashish** [comment] 2017-02-16 22:44
I'm not able to repro this issue locally, tried following repro steps given in repro zip but in my case, it always generate .cs file for .tt file even though is missing some assembly references after changing the fw version. And when you build the solution again, then everything works fine.

I'll drop an email to the customer to ask for the repro solution.

**Comment by CoolDadTx** [comment] 2017-02-16 22:58
You likely cannot replicate the corruption of the .tt files because your .tt files don't rely on the assemblies being referenced. In my case we have custom .tt files that enumerate the references defined in the project to dynamically generate code for referenced types. Since the references are removed after the framework version changes those assemblies pulled from NuGet are no longer available. Then when our .tt files run they don't find the references and fail. 

The issue isn't with the .tt files being empty. The issue is that the references are removed which causes any .tt files that rely on those references in order to generate to fail because they are getting regenerated either because the version changed or because the references changed, I don't know which case.

**Comment by jainaashish** [comment] 2017-02-16 23:53
Actually even i had created some .tt files which does rely on assembly referred in a way that it import couple of namespaces from that and has some custom code to use them. But it might not be as aggressive as yours which is why it just give assembly missing error for me and still able to generate code.

Now about the references are removed, then it's not the case, references are still there (you can confirm that by going into .csproj file, it still has those PackageReferences). But with PackageReference format, generated asset file (/obj/project.assets.json) has these NuGet package dependencies specific to previous fw version. So when you change fw version, it triggers design time build which reads this assets file and try to manipulate these references, and since it doesn't find anything related to new fw version in that assets file so it doesn't show these package references in Reference tree. But when you build, it triggers NuGet restore which generates a new assets file based on changed fw version so it brings back these references in the tree.

So the issue really here is when you change fw version with PackageReference, then someone needs to call into NuGet to restore existing packages for new fw version before going to design time build. We'll see how we want to attack it, but for now, it will work fine if you use Packages.config format instead of PackageReference.

**Comment by jainaashish** [comment] 2017-02-17 02:03
The right fix for this issue would be, when target version retargeting happens, we check for existing packages if they are still compatible with new version or not, if they aren't then we simply print out errors in error lists and ask user to re-install these packages. If they're still compatible, then we reevaluate the assets file to match the new target framework (to say basically run NuGet restore to generate new assets file).

**Closed as completed** 2017-03-02 17:55 UTC
Labels: Priority:2, Triage:Investigate, Style:PackageReference
