### ISSUE TITLE
VS 2017 (15.3) doesn't restore nuget packages in netstandard1.4 projects because it seems to ignore projects.json-frameworks-netstandard1.4-imports

### ISSUE THREAD

**Issue by erikrenaud** [NuGet/Home#5806] opened 2017-08-25 04:12 UTC
Restore fails in build:
NU1202: Package Microsoft.Azure.Mobile 0.14.0 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Microsoft.Azure.Mobile 0.14.0 supports:
  - monoandroid403 (MonoAndroid,Version=v4.0.3)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - uap10.0 (UAP,Version=v10.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)

Project.json holds this
"frameworks": {
    "netstandard1.4": {
      "imports": [ "portable-net45+win8+wp8+wpa81" ]
    }
  }

it worked perfectly with 15.2

Others seem to have the bug also 
https://developercommunity.visualstudio.com/content/problem/98947/visual-studio-2017-v153-can-not-build-the-solution.html

**Comment by rrelyea** [comment] 2017-08-25 17:37
Yes, we have a fix underway. Considering releasing in a 15.3.x servicing release.
Covered by internal bug: 482586

**Workaround until we fix for real**:
a) move from Project.json to PackageReference and represent your imports via the PackageTargetFallback property in the csproj.
**Update**: removed the first version of the workaround...which was mistaken.

**Cause**: We now support UAP10.0.xxxxx TFMs, instead of the earlier supported UAP10.0.
This problem is caused by code that is trying to help project.json users by replacing their framework with the more precise TFM version. However, we neglected to preserve the imports setting.

**Comment by clairernovotny** [comment] 2017-08-25 17:50
@rrelyea can you please point me to the PR that has the fix? I just did a bit of work around this area for my extras (https://github.com/onovotny/MSBuildSdkExtras/commit/2bfa253bedf624f7903b7a5cfa618bbba0c4e180), and I want to track the fix.

BTW, as is, using `uap10.0` with a TPMV of `10.0.10240.0` fails to restore since the TFM is `UAP,Version=v10.0.10240`. The code works fine if it's `uap10.0.10240`, so in my case, I special-cased `uap10.0`. Not sure if you saw anything around that.

**Comment by emgarten** [comment] 2017-08-26 08:23
@onovotny https://github.com/NuGet/NuGet.Client/pull/1668

**Comment by rrelyea** [comment] 2017-08-28 23:16
We are shooting to fix this in 15.3.3 (which is undergoing testing)

**Comment by erikrenaud** [comment] 2017-08-29 04:00
Bizarre,

I’ve added
<PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
Or variants like:
<PackageTargetFallback>portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
<PackageTargetFallback>portable-net45+win8+wp8+wpa81</PackageTargetFallback>


To my csproj but I still get the errors like :
NU1202: Package Microsoft.Azure.Mobile 0.14.0 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Microsoft.Azure.Mobile 0.14.0 supports:
  - monoandroid403 (MonoAndroid,Version=v4.0.3)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - uap10.0 (UAP,Version=v10.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)


I am willing to test the 15.3.3 fix if it can be easily sent to me and tested…

**Comment by rrelyea** [comment] 2017-08-30 21:34
Fixed in VS 2017 version 15.3.3 (released yesterday).

**Closed as completed by rrelyea** 2017-08-30 21:34 UTC
Labels: Type:Bug, Style:Project.json, RegressionFromPreviousRTM
