### ISSUE TITLE
Manage Packages for Solution (all dialogs) would be very nice search box for projects to filter

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7960] opened 2019-04-04 18:44 UTC
<p>Hello.</p><p>As we working with solutions with has many projects and heavily uses nugets.</p><p>Very nice feature in Nuget Package Manager would be to be bale to filter projects.</p><p>In example there is XXX project and I want to install/uninstall nuget for project Y. It is very hard to find that specific project to select and install nuget for it (similar as we have search box for nugets).</p><p>Attached image for more details.<a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/61082-nuget-filtering.png">nuget-filtering.png</a></p><p></p><p><br></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/471087/manage-packages-for-solution-all-dialogs-would-be.html
VSTS ticketId: 802961_
_These are the original issue comments:_

Vidmantas Drasutis on 2/27/2019, 00:31 AM (36 days ago): <p>This would improve work with nuget`s experience :)</p>

Jane Wu [MSFT] on 2/28/2019, 01:35 AM (35 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by anangaur** [comment] 2019-04-04 18:45
@karann-msft Can you create or attach this issue to the list of PM UI  improvements we plan to do?

**Comment by karann-msft** [comment] 2019-04-05 23:01
related to - https://github.com/NuGet/Home/issues/7284

**Comment by donnie-msft** [comment] 2020-11-03 05:27
Dupe of https://github.com/NuGet/Home/issues/9081

**Closed as completed by donnie-msft** 2020-11-03 05:27 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Priority:2, Type:Feature, Functionality:VisualStudioUI
