### ISSUE TITLE
Tooling to figure out what sources a package is available on

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8628] opened 2019-09-25 21:18 UTC
As a package consumer I want to know which packages are present on which feed.

Restore itself does some extra logging to communicate where a package is downloaded from but that's not the ask here. 
We shouldn't need to download the packages to determine this. 

A use case raised in the thread is, consolidating sources (it's super difficult to figure out what sources are not needed anymore, it's very much a trial and error scenario).
 
Related: 
nuget.exe list packageId -source sourceName. 

Note that's not a claim that list should support the scenario, but just that list/search is one of the general commands that can do that. 

@kirillosenkov

Related thread: https://twitter.com/KirillOsenkov/status/1176930430081105920

**Comment by KirillOsenkov** [comment] 2019-09-25 21:24
From my observations:
`nuget list MyPackageId -Source mysource` works fine, but you need to know the source (or loop over them manually)
`nuget list MyPackageId -ConfigFile nuget.config` prints all packages, even those that don't match
`nuget list packageid:MyPackageId -ConfigFile nuget.config` prints No packages found

**Comment by KirillOsenkov** [comment] 2019-09-25 21:25
See related: https://github.com/NuGet/Home/issues/8529

**Comment by KirillOsenkov** [comment] 2019-09-25 21:25
See related: https://github.com/NuGet/Home/issues/7577

**Comment by KirillOsenkov** [comment] 2019-09-25 21:26
See related: https://github.com/NuGet/Home/issues/7691

**Comment by KirillOsenkov** [comment] 2020-02-27 05:17
Would really be nice to have this. Is there a workaround I could use?

**Comment by nkolev92** [comment] 2020-02-27 18:39
Not that's part of the tooling yet. 
I'm thinking about closing this as a dup of https://github.com/NuGet/Home/issues/8529?
Thoughts?

**Comment by KirillOsenkov** [comment] 2020-02-27 19:12
Sure sounds like a dupe of #8529

**Closed as completed** 2020-02-27 19:35 UTC
Labels: Resolution:Duplicate, Type:Feature, Product:NuGet.exe, Product:dotnet.exe
