### ISSUE TITLE
Dont refresh the nuget UI when changing tabs in VS

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#7978] opened 2019-04-08 23:55 UTC
Givem the nuget UI can take minutes to load, it is nice to be able to switch to another tab and get some other work done. But this is not possible since any time u focus back on the nuget tab it starts the whole load again.

**Comment by zivkan** [comment] 2019-04-09 22:06
Closing as duplicate of #6570

**Closed as completed by zivkan** 2019-04-09 22:06 UTC
Labels: Resolution:Duplicate

**Comment by SimonCropp** [comment] 2020-10-21 22:09
this is still occurring in the latest VS preview

**Comment by SimonCropp** [comment] 2020-10-21 22:18
to repro: open the nuget tab, switch to a code file, and switch back to the nuget tab

**Comment by aortiz-msft** [comment] 2020-10-21 22:27
@SimonCropp - That is being tracked by https://github.com/NuGet/Home/issues/4176
