### ISSUE TITLE
[Test Failure] Most packages’ package source link and package info are missing in the right panel of PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8523] opened 2019-08-29 11:24 UTC
## Details about Problem
NuGet version: NuGet Client Dev\5.4.0.6201
VS Version: Master\29228.166
OS: Windows-10-Enterprise-19H1-04-05-2019
## Detailed repro steps so we can see the same problem
1. Launch VS and create a project (e.g. ASP .NET Core Web Application).
2. Open PM UI of this project and click go to “Browse” tab.
3. Select projects in the left panel and look at the package info in the right panel.
## Expected
Every package’s package source link and package info show correctly.
## Actual
Most packages’ package source link and package info are missing in the right panel of PM UI as below screenshot.
![PackageInfoLost](https://user-images.githubusercontent.com/20632625/63936490-7ea09580-ca92-11e9-9b87-73b7be670ee8.png)

## Note
1.Seems something wrong with today’s NuGet server since the packages showing are all OK after installing into the project.
2.Repro after uninstalling the NuGet Client from the machine.

**Comment by donnie-msft** [comment] 2019-08-30 22:18
This is a dupe of a known regression in this release that we are tracking for 5.3 fix.
See https://github.com/NuGet/Home/issues/8504

**Closed as completed by donnie-msft** 2019-08-30 22:18 UTC
Labels: Resolution:Duplicate
