### ISSUE TITLE
The new option "-SymbolPackageFormat snupkg" generates an error when the .nuspec file contains an explicit assembly reference element

### ISSUE THREAD

**Issue by ioancrisan** [NuGet/Home#7638] opened 2018-12-14 10:10 UTC
Please read the following information before posting the issue.

## Details about Problem

NuGet product used: NuGet.exe.

NuGet version: 4.9.2

OS version: win10 v1803

## Detailed repro steps so we can see the same problem

1. The content of the .nuspec file (somehow I cannot attach a zip)

```
<package >
    <metadata>
        <id>Kephas.Core</id>
        <version>$version$</version>
        <title>Kephas.Core</title>
        <authors>Kephas Software SRL</authors>
        <owners>Kephas Software SRL</owners>
        <description>
            Provides a common infrastructure for all the other Kephas Framework components: ambient services, dynamic reflection, composition, application bootstrapping, and others.
            Check the documentation and the samples from https://github.com/kephas-software/kephas/wiki and https://github.com/kephas-software/kephas/tree/master/Samples.
            Kephas Framework ("stone" in aramaic) is a very ambitious project aiming to deliver a framework for an application ecosystem.
        </description>
        <releaseNotes>
        </releaseNotes>
        <summary>
            Provides a common infrastructure for all the other Kephas Framework components: ambient services, dynamic reflection, composition, application bootstrapping, and others.
        </summary>
        <language>en-US</language>
        <projectUrl>https://github.com/kephas-software/kephas</projectUrl>
        <iconUrl>http://kephas-framework.com/favicon.png</iconUrl>
        <requireLicenseAcceptance>true</requireLicenseAcceptance>
        <license type="expression">MIT</license>
        <copyright>Copyright Kephas Software SRL 2010-2018</copyright>
        <dependencies>
            <group>
                <dependency id="System.ValueTuple" version="4.3.0" />
            </group>
            <group targetFramework="netstandard2.0">
                <dependency id="System.ComponentModel" version="4.3.0" />
                <dependency id="System.Diagnostics.Contracts" version="4.3.0" />
                <dependency id="System.Dynamic.Runtime" version="4.3.0" />
                <dependency id="System.Reflection" version="4.3.0" />
                <dependency id="System.Security.Principal" version="4.3.0" />
                <dependency id="System.Runtime.Loader" version="4.3.0" />
            </group>
        </dependencies>
        <references>
            <reference file="Kephas.Core.dll" />
        </references>
        <tags>kephas framework core</tags>
    </metadata>
    <files>
        <file src="**\*.cs" target="src"/>
        <file src="bin\$configuration$\netstandard2.0\Kephas.Core.dll" target="lib\netstandard2.0" />
        <file src="bin\$configuration$\netstandard2.0\Kephas.Core.pdb" target="lib\netstandard2.0" />
        <file src="bin\$configuration$\netstandard2.0\Kephas.Core.xml" target="lib\netstandard2.0" />
        <file src="bin\$configuration$\net45\Kephas.Core.dll" target="lib\net45" />
        <file src="bin\$configuration$\net45\Kephas.Core.pdb" target="lib\net45" />
        <file src="bin\$configuration$\net45\Kephas.Core.xml" target="lib\net45" />
    </files>
</package>
```

2. The ps1 file content (part of):
$build = "Release"
$version = "5.0.0"
$refversion = "5.0.0"
.\NuGet.exe pack $path\Package.nuspec -BasePath $path -Symbols -SymbolPackageFormat snupkg  -properties "Configuration=$build;Version=$version;RefVersion=$refversion"

3. Output:

PS D:\github\kephas\src\Deployment> .\CreateNugetPackages.ps1
Please provide package version: 5.0.0-rc12
Please provide the referenced package version: 5.0.0-rc12
Attempting to build package from 'Package.nuspec'.
Successfully created package 'D:\github\kephas\src\Deployment\Kephas.Core.5.0.0-rc12.nupkg'.
Error NU5018: Invalid assembly reference 'Kephas.Core.dll'. Ensure that a file named 'Kephas.Core.dll' exists in the lib directory.

## Other suggested things
It seems that the package itself can be built, but not the symbol package. My impression is that the token replacement does not work in the symbols packer.

Another thing: leaving out "-SymbolPackageFormat snupkg" does work and it generates the symbols package in the old format.

**Comment by jainaashish** [comment] 2018-12-15 00:38
@nkolev92 is this also related to https://github.com/NuGet/Home/issues/7632?

**Comment by nkolev92** [comment] 2018-12-15 01:02
@jainaashish No, it's not related.

**Comment by gix** [comment] 2019-06-02 10:50
This bug has nothing to do with token replacement. Using any explicit assembly references (`<reference>`) breaks building `snupkg` packages for a simple reason: The `snupkg` package builder is populated with all specified references and then later tries to validate them. But since the builder only has the `.pdb` files this validation always fails.

**Comment by nkolev92** [comment] 2019-06-03 18:51
Thanks @gix for the pointer. 
You are correct, that's the root cause. 

I have self-assigned this and I have a PR attempting to address. 

@karann-msft @rrelyea @anangaur @diverdan92 @cristinamanum @NuGet/nuget-client  
I'd love your input on the solution for this problem. 

A bit of background. 
Explicit assembly references are allow you to specify assemblies that need to be explicitly referenced in the project. It's a packages.config scenario. 

As @gix observed the validation in question here is `pack` ensuring that everything from the `reference` element is in the package, but that's not the case for snupkgs where only pdbs are allowed. 

I can think of 2 different ways to address this. 

1. Remove the reference from the nuspec element from the nuspec file. Get a nuspec file such as: 
```xml
<metadata xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <id>packageA</id>
  <version>1.0.0</version>
  <title>packageA</title>
  <description>Description</description>
  <copyright>Copyright ©  2013</copyright>
  <packageTypes>
    <packageType name="SymbolsPackage" />
  </packageTypes>
</metadata>
```
Notice the references element is gone. 

1. Remove the validation for the explicit reference assemblies in the snupkg case. 

The snupkg nuspec stays closer to the original nupkg one. 
```xml
<metadata xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <id>packageA</id>
  <version>1.0.0</version>
  <title>packageA</title>
  <description>Description</description>
  <copyright>Copyright ©  2013</copyright>
  <packageTypes>
    <packageType name="SymbolsPackage" />
  </packageTypes>
    <references>
        <group targetFramework=""net45"">
            <reference file=""packageA.dll"" />
        </group>
    </references>
</metadata>
```

I have opted for the 1st approach as it's more explicit. 

@ioancrisan 
As a general rule for package quality, it's nice to include `target framework specific` elements wherever possible as shown in my above example: 

```xml
    <references>
        <group targetFramework=""net45"">
            <reference file=""packageA.dll"" />
        </group>
    </references>
```

**Comment by ioancrisan** [comment] 2019-06-05 10:21
@nkolev92 Thanks for the tip :).

**Closed as completed** 2019-06-05 16:38 UTC
Labels: Priority:2, Type:Bug, Product:NuGet.exe, Functionality:Pack, Area:Symbols
