### ISSUE TITLE
Failed to uninstall package because a file is locked

### ISSUE THREAD

**Issue by ejizba** [NuGet/Home#5609] opened 2017-07-17 21:56 UTC
## Details about Problem

VS version (if appropriate): 15.3.0 Preview 4.1 [26716.0.d15rel]

Worked before? If so, with which NuGet version: VS 15.2

## Detailed repro steps so we can see the same problem
This requires Visual Studio with the Cloud workload
1. File -> New -> Azure Cloud Service
2. Add two 'ASP.NET Web Role' projects
3. Select Web API for each project

Expected: Both projects successfully create
Actual: The second project fails to create. There is a lock on a Newtonsoft.Json.6.0.4 file. The error message is like 
```
The process cannot access the file "...\packages\Newtonsoft.Json.6.0.4\lib/net45/Newtonsoft.Json.dll" because it is being used by another process.
```

Under the covers, the cloud service is creating a regular ASP.NET project (that has Newtonsoft 6.0.4) and then adding the WindowsAzure.Storage package (which depends on a higher version of Newtonsoft) using IVsPackageInstaller.InstallPackage(). It successfully installs the storage nuget package and a higher version of newtonsoft, but fails to uninstall newtonsoft 6.0.4.

**Comment by rohit21agrawal** [comment] 2017-07-18 00:49
CC: @rrelyea @DoRonMotter  for possible 15.3 candidate . please triage.

**Comment by rainersigwald** [comment] 2017-07-25 22:16
Note: on my machine the second project creation failure was almost silent; it only manifested as an error in VS's status bar. That mislead me into thinking this didn't repro.

I've been looking at this with @mishra14. We believe that it's related to the new [GetFileDependsOnNETStandard](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/GetDependsOnNETStandard.netstandard.cs#L14) task, introduced to support .NET Standard 2.0 in VS 15.3.

The task [appears](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/GetDependsOnNETStandard.net46.cs#L130) to close the handle to the files it's inspecting, but we can observe through the debugger that they don't get closed immediately. 

When `devenv.exe` is started from an environment with `set ImplicitlyExpandNETStandardFacades=false`, project creation succeeds. That property [disables calling `GetDependsOnNETStandard`](https://github.com/dotnet/sdk/blob/98ea6b2a1701ee9e2e3dd8122c77d5a2adcc5bb7/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L24).

**Comment by rainersigwald** [comment] 2017-07-25 22:25
Opened https://github.com/dotnet/sdk/issues/1453 to track the fix at what I believe is its root cause.

**Comment by mishra14** [comment] 2017-07-25 22:26
closing in the favor of the sdk bug.

**Closed as completed by mishra14** 2017-07-25 22:26 UTC
Labels: Priority:1, Product:VS.Client, Resolution:External, Functionality:Install
