### ISSUE TITLE
[Test Failure] Tmp file will not disappear in Solution Explorer until reload after installing a package into MyApp who had lock file while the project graph structure is MyApp->MyLib

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8398] opened 2019-07-29 10:24 UTC
## Details about Problem
NuGet version: NuGet Client Dev\5.3.0.6127
VS Version: Master\29128.08
OS: Windows-10-Enterprise-19H1-04-05-2019
## Detailed repro steps 
1. Create a solution with one .NET Core Console App project (called MyApp) and one .NET Core Class Library (called MyLib), make the project graph structure: MyApp -> MyLib.
2. Set property “RestorePackagesWithLockFile” to true in csproj file of MyApp and install a package “Newtonsoft.Json” into MyLib in PM UI.
3. Restore the solution and confirm MyApp\packages.lock.json contains Newtonsoft.Json as a transitive dependency.
4. Install a package “Newtonsoft.Json” into MyApp in PM UI and check the Solution Explorer window.
## Expected
The tmp file will not show in Solution Explorer window.
## Actual
The tmp file will not disappear in Solution Explorer until reload as below screenshot.
![TmpFileNotDisappear](https://user-images.githubusercontent.com/20632625/62041275-d480e400-b22d-11e9-9002-edb61b289f90.PNG)
## Note
It didn’t repro on Master\29128.08 (the same VS version) +NuGet Client Dev\5.3.0.6118.

**Comment by dominoFire** [comment] 2019-08-03 00:15
I tried to reproduce it in master\29201.157 + NuGet 5.3.0.6103 with no luck. @v-luzh , can you try to reproduce again and see if it happens again?

**Comment by v-luzh** [comment] 2019-08-05 09:25
@dominoFire，I can repro on VS Master\29202.138 + NuGet Client Dev\5.3.0.6148 today as below. Please try install->uninstall->install several times if you can't repro it at first time.
![Repro](https://user-images.githubusercontent.com/20632625/62453879-ddc9fd80-b7a5-11e9-8929-52bdcdaa1ca7.PNG)

**Comment by dominoFire** [comment] 2019-08-05 18:57
@v-luzh Could you provide a sample project or the project.assets.json file from both projects?

**Comment by v-luzh** [comment] 2019-08-07 09:13
@dominoFire, of course, here are the assets.json files: \\\nugetserver03\Users\v-luzh\Bug8398 which I reproed on VS Master\29206.34 + NuGet Client Dev\5.3.0.6152 as below screenshot.
![Capture](https://user-images.githubusercontent.com/20632625/62610915-3086ef00-b937-11e9-97c7-4b619495c50d.PNG)

**Comment by aortiz-msft** [comment] 2020-01-22 22:57
Repro rate on latest Preview build is only 10%.

**Comment by nkolev92** [comment] 2020-11-03 00:18
@donnie-msft's doing his UI triaging so he pointed out this issue. 

This is really a question for the project-system team. 

The way NuGet writes the packages lock file is by writing to a temp file in the same dir and then renaming. 

The project-system seems to detect this file and but then when it gets removed it retains the ref?
Unsure, moving it to their repo, so they can determine if this is a critical thing that can cause other problems. 

There's no functional impact for this bug.

**Closed as completed** 2020-11-03 00:39 UTC
Labels: Type:Bug, Functionality:Restore, Type:Test

**Comment by nkolev92** [comment] 2020-11-03 18:25
Moved to [CPS](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1241836) after that,

**Comment by lifengl** [comment] 2020-11-09 20:14
It is a known issue that NET Core project's globbing pattern can pick up random file on the disk. CPS watches the directory, and drive reevaluation when things are changed. However, when a temporary file appears/disappears quickly, it is filtered out & CPS didn't see them in the later logic. A problem is that is CPS doesn't know the exactly disk state used by msbuild evaluation, so there is always a gap between them.  We didn't spend much time to try to work around this issue, because we always discuss the possibility to enable MSBuild to use CPS's in-memory disk state in the evaluation (for some directories including the project cone), which will eliminate the gap & cut off the additional disk scanning during evaluation.
