### ISSUE TITLE
Nuget isn't working for me on VS.

### ISSUE THREAD

**Issue by Wua4** [NuGet/Home#3281] opened 2016-08-05 18:20 UTC
When opening the package manager in VS2015;

> [nuget.org] Unable to load the service index for source https://www.nuget.org/api/v2/.
>  An error occurred while sending the request.
> The remote server returned an error: (400) Bad Request.

I can't install packages like this.

**Comment by emgarten** [comment] 2016-08-05 21:33
try adding the v3 source: https://api.nuget.org/v3/index.json

**Comment by rrelyea** [comment] 2016-08-08 20:59
Like duplicate of #2880 . 
please confirm or deny.

**Closed as completed by rrelyea** 2016-08-08 20:59 UTC
Labels: Resolution:Duplicate

**Comment by Wua4** [comment] 2016-08-09 13:57
I don't believe it's a duplicate. The  error is different. Also there is no http_proxy variable on my machine.

**Comment by Wua4** [comment] 2016-08-09 13:58
V3 source is the same 

[nuget V3] Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The remote server returned an error: (400) Bad Request.

**Comment by Wua4** [comment] 2016-08-09 14:17
Figure it out on my own. Deleted the %AppData%\NuGet\nuget.config and restarted VS2015

**Comment by emgarten** [comment] 2016-08-09 18:42
@alexzxz very strange, your nuget.config may have contained proxy settings that were causing your requests to fail.

**Comment by dlidstrom** [comment] 2018-11-19 13:48
I did the same as @Wua4 and got a new `NuGet.Config`. It had these lines removed:

```xml
<packageRestore>
  <add key="enabled" value="True" />
  <add key="automatic" value="True" />
</packageRestore>
<bindingRedirects>
  <add key="skip" value="False" />
</bindingRedirects>
<packageManagement>
  <add key="format" value="1" />
  <add key="disabled" value="False" />
</packageManagement>
```

Now it works fine!

**Comment by Andre6321** [comment] 2023-11-28 04:59
Had the same - just as an FYI for anyone else fixing this in future, since I have a lot of different projects with a lot of different nuget.config files - this comes up when you have 2 different Nuget.configs for the same project - (Can often happen if you have maybe an outdated save version via a one Drive save for example - then you wont be able to download ANY nugget packages for ANY projects (even if the duplicate is within a seperate project) so best way to resolve it is checking for any duplicate Nuget.Config and yeah deleting them)

**Comment by amirnazary-4screen** [comment] 2023-11-29 16:49
Can some one paste the full content of the `NuGet.Config` file here?
