### ISSUE TITLE
nuget update does not work for PackageReference with .NetFramework v4.6.1

### ISSUE THREAD

**Issue by let-thomas** [NuGet/Home#6985] opened 2018-05-30 10:08 UTC
I have 1 clean small solution with 1 project having
```
  <ItemGroup>
    <PackageReference Include="PcgDNF">
      <Version>1.0.*</Version>
    </PackageReference>
  </ItemGroup>
```

nuget restore DepMaster.sln
works fine
```
C:\work\git_poc\DepMaster>nuget restore DepMaster.sln
MSBuild auto-detection: using msbuild version '15.7.179.6572' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\
Professional\MSBuild\15.0\bin'.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\work\git_poc\DepMaster\Master\obj\project.assets
.json
Restore completed in 79,82 ms for C:\work\git_poc\DepMaster\Master\Master.csproj.

NuGet Config files used:
    C:\Users\xxxx\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    C:\nuget_packages_glob
    https://someaddr/api/nuget/nuget
    https://someaddr/api/nuget/r4cbe7f7a-0d73-4f9c-bebb-64b455431174
    https://someaddr/api/nuget/raa810a8d-d88c-4dab-95df-3736a89784b4
```

Now I would like to fetch newest version of PcgDNF package
```
C:\work\git_poc\DepMaster>nuget update -safe DepMaster.sln
Scanning for projects...
No projects found with packages.config.
```

And similar for csproj
```
C:\work\git_poc\DepMaster>nuget update -safe Master\Master.csproj
MSBuild auto-detection: using msbuild version '15.7.179.6572' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\
Professional\MSBuild\15.0\bin'.
Unable to locate the packages folder. Verify all the packages are restored before running 'nuget.exe update'.
```

Tested nuget versions
nuget_3.3.0.exe
nuget_3.4.4.exe
nuget_3.5.0.exe
nuget_4.4.1.exe
nuget_4.5.1.exe
nuget_4.6.0.exe
nuget_4.6.2.exe
nuget_4.7.0.exe

**Comment by nkolev92** [comment] 2018-05-30 16:47
Thanks for filing this issue. @let-thomas 

This is a known feature gap.

Duplicate of https://github.com/NuGet/Home/issues/4103

**Closed as completed by nkolev92** 2018-05-30 16:47 UTC
Labels: Resolution:Duplicate, Product:NuGet.exe, Style:PackageReference
