### ISSUE TITLE
[Feature]:  using fixed string instead of GUID for *.psmdcp file name

### ISSUE THREAD

**Issue by John0King** [NuGet/Home#12029] opened 2022-08-17 08:09 UTC
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

the name change cause `_rels/.rels`  file change,  and that also cause  .nupkg file change,   and for someone who using local folder as nuget source ,   
then itcause `git`  keep track the same .nupkg  every time you pack it (especially，when `<GeneratePackageOnBuild>True<GeneratePackageOnBuild>`).

**Comment by nkolev92** [comment] 2022-08-17 20:25
Hey @John0King, 

I'm not sure I understand your concern. 

Can you let us know what you are trying to achieve and the commands you were running and the effect of the problems you encountered.

**Comment by John0King** [comment] 2022-08-18 01:08
@nkolev92   I  want a local folder  to be a nuget source (the folder and the  .nupkg file need to store in git repo),
but every time I build my project , the *.nupkg is changed ,   I find all the binaries are unchanged ,  so  I'm looking into to `.nupkg.zip` ,  turn's out  the onlything change is that the name of the `*.psmdcp` file  and the metadata contains it's name (eg. .rels)

so every time you build the project with option `<GeneratePackageOnBuild>True<GeneratePackageOnBuild>)`  ,  the *.nupkg file is change (though all the output is not change)

**Comment by nkolev92** [comment] 2022-08-18 17:06
Ah, ok, you are looking for deterministic pack. 

> so every time you build the project with option <GeneratePackageOnBuild>True<GeneratePackageOnBuild>) , the *.nupkg file is change (though all the output is not change)

The pack target has up to date checks that work on the same machine. 
Cross machine that's not possible at this point. 

On the pack topic, it's not just the _rels folder, but also the timestamps of the dlls that affect the zip. 

We attempted this at some point and we hit issues. 

Duplicate of https://github.com/NuGet/Home/issues/8601.

**Closed as completed by nkolev92** 2022-08-18 17:06 UTC
Labels: Resolution:Duplicate, Type:Feature, Functionality:Pack, Triage:NeedsMoreInfo

**Comment by joshudson** [comment] 2024-10-13 23:40
@nkolev92 : Is it possible to *just* fix the .pcsdmp file to get a consistent name?

The timestamps are what caused the problem and it's easier to sell diff all the files in the zip file than all but two of them.

**Comment by nkolev92** [comment] 2024-10-14 18:15
@joshudson 
I think we can reconsider it. 
Upvoting https://github.com/NuGet/Home/issues/8601 is probably best since it'd get more attention than this single issue. 
Please do share your ideas there.

Not sure when we'd able to get to it, but we'd certainly consider community contributions. 
https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md - for proposals.
https://github.com/NuGet/Home/blob/dev/CONTRIBUTING.md - For implementation contributions
