### ISSUE TITLE
Net45 class library fails to build after using project.json to depend on PCLTesting package

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1587] opened 2015-10-16 03:52 UTC
**Repro steps**
1. git clone https://github.com/AArnott/NuGetIssue1587
2. nuget restore NuGetIssue1587
3. msbuild NuGetIssue1587\projectJsonSystemDllBug.sln

**Expected**
Build success

**Actual**
The build fails with this error:

> Class1.cs(14,13): error CS0103: The name 'Debug' does not exist in the current context [C:\
> Users\andarno\Documents\visual studio 2015\Projects\projectJsonSystemDllBug\net45lib\net45l
> ib.csproj]

The build log reveals that `System.dll` is not referenced by the compilation. Opening the solution file in VS2015 shows that the System.dll reference fails to resolve in the IDE as well.

The critical part of the repro seems to be the project.json file in the project's dependency on Microsoft.Bcl.Async. Without that dependency, the build succeeds. In this trivial repro project, we don't even need this package, although in the original solution where this bug was found of course it is more important. 

This regression does not occur when the package is consumed via packages.config.

**Comment by AArnott** [comment] 2015-10-16 04:02
CC: @terrajobst, in case it's a bug in the Microsoft.Bcl.Async package or one of its dependencies somehow.

**Comment by AArnott** [comment] 2015-10-16 04:06
In the packages.config world, installing the Microsoft.Bcl.Build package has the effect of adding an import. But it does so through a .ps1 install script rather than the standard NuPkg build folder convention. In the project.json world the .ps1 scripts don't run at all (by design). Is this a bug in the Microsoft.Bcl.Build package then in that we need to ship another version of it that doesn't rely on the execution of the .ps1 script?

(I still have no idea why it would cause System.dll to not be referenced though in the project.json world, where no build authoring changes are even applied).

**Comment by yishaigalatzer** [comment] 2015-10-23 01:06
@ericstj I tend to agree with @AArnott that this is probably not a NuGet issue, and the behavior is by design (at least when it comes to NuGet proper)

**Comment by ericstj** [comment] 2015-10-23 04:55
The latest version of that package doesn't use Install.ps1, regardless this shouldn't be caused by BCL.Build.  That doesn't futz with references.  All it does is generate binding redirects and ensure that it's in every up-stack p2p reference.

I suspect what's happening here is something gone wrong in how the project.json task deals with framework references /cc @jasonmalinowski.

Andrew, did you look in the output of the diag msbuild log?  Is system making it to RAR?  What's it doing with it such that it doesn't make it to CSC?

**Comment by yishaigalatzer** [comment] 2015-10-23 05:09
Thanks Eric. Keeping this open until we can verify the root cause

Sent from my Windows Phone

**Comment by AArnott** [comment] 2015-10-23 19:28
@ericstj No, I didn't produce a diag log at the time. The repro solution in the steps is absolutely minimal though, so I hope that can help you in your investigation.

**Comment by twsouthwick** [comment] 2015-12-08 00:06
Any update on this? I'm encountering this as well.

**Comment by yishaigalatzer** [comment] 2015-12-08 00:07
We have no update, are you using NuGet 3.3 + Visual Studio Update I ?

**Comment by twsouthwick** [comment] 2015-12-08 00:07
Yes

**Comment by jasonmalinowski** [comment] 2015-12-08 00:47
Oops, sorry I didn't see this bug earlier. Yes, this is my bug. Can somebody assign it to me?

As a workaround, add `<IncludeFrameworkReferencesFromNuGet>false</IncludeFrameworkReferencesFromNuGet>` to your project file. When you add the package you might have to manually add other framework references, but that should work around the issue.

**Comment by yishaigalatzer** [comment] 2015-12-08 00:50
I don't know how to assign it, other than opening another bug in your area.

**Comment by twsouthwick** [comment] 2015-12-08 18:40
Thanks @jasonmalinowski. That work around worked for me. Thanks for looking into it.

**Comment by clairernovotny** [comment] 2016-01-01 19:37
Referencing #1880

**Comment by jasonmalinowski** [comment] 2016-02-04 00:14
Yep, this is a dupe of #1880.

**Closed as completed by jasonmalinowski** 2016-02-04 00:14 UTC
