### ISSUE TITLE
'dotnet restore' and 'dotnet build' emit many spurious warnings when using a lock file

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#7625] opened 2018-12-12 00:20 UTC
## Details about Problem

dotnet.exe --version: 2.2.100

If you clear your global packages cache, `dotnet restore` will emit inaccurate, spurious warnings for projects with an already-generated packages.lock.json.

If you've already run restore and cached all packages, `dotnet build` will emit even more spurious warnings than the case above.

### `dotnet restore` scenario

1. Download [restore_lockfile_sillyWarnings.zip](https://github.com/NuGet/Home/files/2669950/restore_lockfile_sillyWarnings.zip) and unzip it somewhere on your machine

2. Execute repro.bat. Note that this file contains annotations describing the specific operations being performed.

### `dotnet build` scenario
1. Download [build_lockfile_sillyWarnings.zip](https://github.com/NuGet/Home/files/2670090/build_lockfile_sillyWarnings.zip)  and unzip it somewhere on your machine

2. Execute repro.bat. Note that this file contains annotations describing the specific operations being performed.

## Sample warnings

The 'not found' packages do exist on the feed.

```warning NU1603: NETStandard.Library 2.0.3 depends on Microsoft.NETCore.Platforms (>= 1.1.0) but Microsoft.NETCore.Platforms 1.1.0 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Collections 4.0.11 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Diagnostics.Debug 4.0.11 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Globalization 4.0.11 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.IO 4.1.0 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.IO.FileSystem 4.0.1 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Reflection 4.1.0 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Reflection.Extensions 4.0.1 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Reflection.Primitives 4.0.1 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Resources.ResourceManager 4.0.1 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Runtime 4.1.0 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Runtime.Extensions 4.1.0 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Runtime.InteropServices 4.1.0 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Text.Encoding 4.0.11 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Text.Encoding.Extensions 4.0.11 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Threading.Tasks 4.0.11 depends on Microsoft.NETCore.Platforms (>= 1.0.1) but Microsoft.NETCore.Platforms 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Platforms 2.1.0 was resolved.
warning NU1603: System.Collections 4.0.11 depends on Microsoft.NETCore.Targets (>= 1.0.1) but Microsoft.NETCore.Targets 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Targets 2.1.0 was resolved.
warning NU1603: System.Diagnostics.Debug 4.0.11 depends on Microsoft.NETCore.Targets (>= 1.0.1) but Microsoft.NETCore.Targets 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Targets 2.1.0 was resolved.
warning NU1603: System.Globalization 4.0.11 depends on Microsoft.NETCore.Targets (>= 1.0.1) but Microsoft.NETCore.Targets 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Targets 2.1.0 was resolved.
warning NU1603: System.IO 4.1.0 depends on Microsoft.NETCore.Targets (>= 1.0.1) but Microsoft.NETCore.Targets 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Targets 2.1.0 was resolved.
warning NU1603: System.IO.FileSystem 4.0.1 depends on Microsoft.NETCore.Targets (>= 1.0.1) but Microsoft.NETCore.Targets 1.0.1 was not found. An approximate best match of Microsoft.NETCore.Targets 2.1.0 was resolved.```

**Comment by jainaashish** [comment] 2018-12-13 20:37
Dupe of https://github.com/NuGet/Home/issues/7529

**Closed as completed by jainaashish** 2018-12-13 20:37 UTC
Labels: Resolution:Duplicate
