### ISSUE TITLE
System.numerics.vectors does not install properly in F# projects

### ISSUE THREAD

**Issue by jackmott** [NuGet/Home#2072] opened 2016-02-07 16:23 UTC
Using nuget to install System.numerics.vector in Visual Studio 2015 Update 1 does not work. Specifically the following lines are missing from the project file:

``` xml
 <Reference Include="System.Numerics.Vectors, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Numerics.Vectors.4.1.0\lib\net46\System.Numerics.Vectors.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

This installs properly with Paket suggesting it is a nuget bug rather than a visual F# bug.
Some other discussion on this issue:
https://github.com/dotnet/corefx/issues/3103

**Comment by jackmott** [comment] 2016-02-07 16:38
Looks like this issue has been reported before and Nuget thinks it is visual studio's fault, and vice versa. Hopefully a solution can be arrived at one way or another.: https://github.com/Microsoft/visualfsharp/issues/939

**Comment by dsyme** [comment] 2016-02-07 21:35
It would be hugely helpful if the Nuget team could identify the failing VS project system calls they are making, i.e. what functionality they exercise for a VS project.  Once that is identified we can determine whether the fix is best made in Nuget (which is most likely) or in the project system implementation.

**Comment by emgarten** [comment] 2016-02-07 23:05
This looks similar to: https://github.com/NuGet/Home/issues/1510

Which contains more info on the APIs used.

**Comment by yishaigalatzer** [comment] 2016-02-07 23:42
This is indeed a duplicate of #1510. IMHO addreference should just do the right thing (as detailed in 1510). I'd like to avoid nuget being the shim to fix project system issues unless absolutely necessary.

**Closed as completed by yishaigalatzer** 2016-02-07 23:42 UTC
