### ISSUE TITLE
Created project using new .NET Core 1.1 template and will not build - problematic copy of browserlink package

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4484] opened 2017-02-03 00:03 UTC
vsfeedback 773358 - repro with rc3

Rob says: Please try to repro with RC3 to confirm, and then try current bits.

I upgraded Visual Studio 2017.
Create a new .NET Core Web Application.
Selected the 1.1 template.

Tried to run project but saw 100s of errors.

Expected to be able to run project created by the template.

Fix was to change the NuGet settings in Visual Studio options to change Default Package Manager format to Package Referance.

**Comment by zhili1208** [comment] 2017-02-03 01:31
I can't repro with rc3 and current bits, from the message, auto restore failed and throw "unable to resolve packages", Since 1.1 template need to restore packages from nuget.org, I think bad network cause this.

If I disable nuget.org, I can repro exact the same error message.

**Comment by ericwj** [comment] 2017-02-03 17:25
Indeed, when I had `sdk: { version: '1.0.0-rc3-004530' }` in `global.json` e.g. 

`Unable to resolve 'runtime.any.System.Runtime (>= 4.4.0-beta-24903-02)' for '.NETCoreApp,Version=v1.1 (win-x86)'.`

Then closing the solution, removing the `sdk` section from `global.json` and reopening the solution e.g.

`1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(154,5): error : Unexpected dependency 'runtime.any.System.Runtime' with no version number.`

Running `dotnet restore` and `dotnet build` from the command line works. Rebuilding in VS after that also works.

**Comment by ericwj** [comment] 2017-02-04 00:16
I found `dotnet restore` will somehow pull in 4.4.* versions of packages - as evidenced above.

This appears to be due to the `<PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />` in the project template. Commenting this reference will yield no search results for `4.4` in `obj\project.assets.json`. Uncommenting it and restoring will re-introduce 4.4.* versions in the lock file.

```JSON
{
  "version": 2,
  "targets": {
    ".NETCoreApp,Version=v1.1": {
      (...)
      "Microsoft.VisualStudio.Web.BrowserLink/1.1.0": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.Hosting.Abstractions": "1.1.0",
          "Microsoft.AspNetCore.Http.Abstractions": "1.1.0",
          "Microsoft.AspNetCore.Http.Extensions": "1.1.0",
          "Microsoft.Extensions.FileProviders.Physical": "1.1.0",
          "System.Diagnostics.Tools": "4.4.0-beta-24903-02",
          "System.IO.MemoryMappedFiles": "4.4.0-beta-24903-02",
          "System.Net.Primitives": "4.4.0-beta-24903-02",
          "System.Net.Sockets": "4.4.0-beta-24903-02"
        },
        "compile": {
          "lib/netstandard1.5/Microsoft.VisualStudio.Web.BrowserLink.dll": {}
        },
        "runtime": {
          "lib/netstandard1.5/Microsoft.VisualStudio.Web.BrowserLink.dll": {}
        }
      },
(...)
```

With these versions in the lock file, Visual Studio 2017 RC will show a series of errors and I found those aren't always attributed to the project with the faulty dependencies. Some show only while the Solution Explorer selection is at the solution level when the 'Current Project' filter is selected. They seem to be stale errors after modifying and saving the project file and letting Visual Studio finish the restore, since they concern the same packages.

There are two types of errors:
* Unexpected dependency '&lt;package&gt;' with no version number
* Unable to resolve '&lt;package&gt; (>= 4.4.0-beta-24903-02) for '.NETCoreApp,Version=v1.1(win|win-x64|win-x86)'

**Comment by zhili1208** [comment] 2017-02-04 01:00
@ericwj what's your dotnet cli version? did you create your project from Visual studio or dotnet cli?

**Comment by ericwj** [comment] 2017-02-04 15:48
I created it from Visual Studio 26127.3, thats the Feb 1 release. `dotnet --version` gives me `1.0.0-rc3-004530`.

Installing that (and the Jan 27 update just before that) actually got me a clean Visual Studio with nothing but the defaults installed. And installation of the update *and* using VS to restore and build, didn't populate my local package cache. Web Tools got installed once I opened the solution with the website I was working on. The package cache was populated running `dotnet restore` for the first time.

Doing `dotnet new -t Web1.1`, `dotnet restore` and `find /N /I "4.4" obj\project.assets.json` actually also produces quite a list. The difference is in that new project from Visual Studio compared to the CLI template adds  
* `Microsoft.ApplicationInsights.AspNetCore` (as PackageReference) and 
* `Microsoft.VisualStudio.Web.CodeGeneration.Tools` (as DotNetCliToolReference)

But the problem is in `Microsoft.VisualStudio.Web.BrowserLink` in both the CLI template and the VS template. Commenting it out and restoring yields no more 4.4 in the lock file for either project.

I am having problems debugging the 1.1 template. It will claim my breakpoints won't hit because no symbols have been loaded. I'm assuming the only way to fix this is to go back to `netcoreapp1.0`?

Is including the old package (`Microsoft.VisualStudio.Web.BrowserLink.Loader` 14.1.0) in any way useful as a workaround? Adding it produces `CS0121`, the call is ambiguous. That's fixable, but I don't get to see a browser talking to VS.

**Comment by zhili1208** [comment] 2017-02-06 18:56
what's your package source? could you share the package source list? Looks like  the dependency packages of  Microsoft.VisualStudio.Web.BrowserLink are resolved to 4.4 on your machine, but on my machine, they are always resolved to 4.3.

Since 4.4-beta packages are not on nuget.org, I'm wondering how nuget to get those packages on your machine?

Also Please check C:\Program Files (x86)\Microsoft SDKs\NuGetPackages
is there any 4.4 package there?

**Comment by rrelyea** [comment] 2017-02-06 20:20
I believe there were problems with BrowserLink package. Please check with Bala on web tools team to see. Confirm that it will be fixed in next public release.

**Comment by zhili1208** [comment] 2017-02-07 00:49
@ericwj According to joe on web tools team,
that’s a known issue. There was one build of the BrowserLink package that had bad references, and that’s apparently the one that shipped with the .NET Core 1.1 CLI installer. However, in RC.3, we removed BrowserLink from the Core 1.1 template, so it shouldn’t be an issue with new projects.

The BrowserLink 1.1 package on Nuget.org has the correct references, so you should be able to work around the problem by deleting your Nuget cache at %userprofile%\.nuget, and then restoring packages on your project again. Others have reported that this resolved the problem.

**Comment by zhili1208** [comment] 2017-02-07 18:15
@ericwj Does deleting nuget cache fix your issue?

**Comment by zhili1208** [comment] 2017-02-08 18:30
close it, if you still hit this issue after cleaning cache, feel free to reopen it.

**Closed as completed by zhili1208** 2017-02-08 18:30 UTC
Labels: Type:Bug, Resolution:External

**Comment by ericwj** [comment] 2017-02-09 21:26
Well I'm using 26206 now... My package source was default. NuGet v3 and local.

Indeed there is almost nothing in the template. Is that useful? I liked to have BrowserLink and e.g. `BundlerMinifier.Core`. But obviously removing packages is a great fix for this issue ;)

`.nuget` is littered with 4.4 packages. Microsoft SDKs has none. Building the original template (modified since my last try) works - because it doesn't have the offending package obviously. Trying to add `Microsoft.VisualStudio.Web.BrowserLink` 1.1.0 actually led to a restore error and a rollback. Deleting the .nuget folder and retrying installs the package correctly and rebuilds without problem.

Kudo's for that albeit the error tells me something bad happened, but nothing about why or how to fix it. Its a great point to get stuck at like that.

I'm slightly puzzled by the fact that VS seems to have downloaded the required packages individually and after doing all I already wrote above running `dotnet restore` will start populating my local package cache. Sure it was deleted, but shouldn't a restore with VS be populating it just the same as a `dotnet restore`?

**Comment by zhili1208** [comment] 2017-02-09 21:44
this is not 4.4 package, the package id is  System.IO.Compression.clrcompression-x64 and version is 4.0.0.
Actually a restore with VS is the same as a dotnet restore for nuget. the difference here is the package source. I think here is one good package is shipped with VS and one bad package is shipped with dotnet cli installer. They contains all dependent packages of template, since user might only install either dotnet cli or VS.

**Comment by ericwj** [comment] 2017-02-09 22:01
Ah yes I beat you by at least 15 minutes removing that part of my comment. I saw it once I took a good look considering to delete it if it would be faulty.

You're saying those 4.4 packages were downloaded by `dotnet restore` a few days ago? That'd explain everything if I had run dotnet restore before I was using VS to build the 1.1 template, but it's the other way around. The other project I have did have a NuGet.Config refer to https://www.myget.org/F/xunit/ but that couldn't be a source as far as I can see.

**Comment by asleight** [comment] 2017-02-27 18:11
I just ran into the same issue with the BrowserLink package. My web app would build and run on my local machine, but once we deployed it to our AWS Linux server via Jenkins automation, it would fail to load a bunch of dependent packages.

Removing the reference to BrowserLink from my .csproj file and commenting out the app.UseBrowserLink() in Startup led to the app deploying properly on next attempt.

Just wanted to say thanks! This thread saved me hours of headaches trying to solve package references.
