### ISSUE TITLE
Project argument should be optional to `nuget why`

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#13782] opened 2024-09-11 16:56 UTC
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

When running `nuget why` I always need to specify a project file.  Other `dotnet` commands like `build`, `restore`, `clean`, `publish` do not require this.

### Desired Behavior

Use the same heuristic for locating a project or solution file when running `nuget why` and one is not specified.

**Comment by jaredpar** [comment] 2024-09-11 17:09
Definitely agree that the project should be optional here for consistency with other commands. One work around I've found is that you can use `.` and the command will use the project file in the current directory:

```cmd
> dotnet why . System.Formats.Asn1
```

**Comment by ericstj** [comment] 2024-09-11 17:11
Thanks for sharing that.  I hadn't realized that would work - I guess it's because you can specify a directory.  I still think this should be the default for consistency with other commands.  The fact that a directory works means `nuget` already has the project locator heuristic so it's simply allowing the "current working directory" to be the default value.

**Comment by baronfel** [comment] 2024-09-11 17:21
I expect this to be fixed in RC2 by https://github.com/NuGet/NuGet.Client/pull/5969

**Comment by nkolev92** [comment] 2024-09-23 21:26
Should be a duplicate of https://github.com/NuGet/Home/issues/13553. 

I'm guessing RC1 has the fix.

**Closed as not planned by nkolev92** 2024-09-23 21:26 UTC
Labels: Resolution:Duplicate, Type:DCR, Product:dotnet.exe, Functionality:Why
