### ISSUE TITLE
[Bug]: The NuGet restore phase is brittle and is subject to race conditions resulting sometimes in corrupted package directories

### ISSUE THREAD

**Issue by MarkKharitonov** [NuGet/Home#11670] opened 2022-03-11 16:27 UTC
### NuGet Product Used

MSBuild.exe

### Product Version

16.11.0.36601

### Impact

It's more difficult to complete my work

### Repro Steps & Context

It happens on our Azure DevOps Server 2020 (on-prem) when running different builds concurrently.
The problem is that we cannot reliably reproduce it. But it happens once every week roughly. 
We send the build telemetry to Azure AppInsights, which makes it easy to query the history. For example, consider the following query (today is 2022-03-11):
```
AllTasks
| where taskStartTime > todatetime('2022-02-22T16:22:19.0831834Z')
    and taskResult == 'failed' and error contains "NuGet.targets" and not(error contains "required nuspec file")
    and tostring(taskCustomDimensions.taskType) == 'Task'
    and buildDef != 'azure-pipelines-sq-wfm-ci-cs' // this is an experimental build
| project buildDef, taskName, buildNumber, taskAgentComputerName, taskStartTime, taskRunDuration, error = substring(error, strlen('C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\NuGet\\NuGet.targets(131,5): Error : '))
| order by taskStartTime
```
This query produces the following result:
<html>
<body>

buildDef | taskName | buildNumber | taskAgentComputerName | taskStartTime | taskRunDuration | error
-- | -- | -- | -- | -- | -- | --
xyz-master-PR | Build DataSvc | 63.0.0.06910-5403-498 | TDC5DFC1BLD08 | 2022-03-10T16:05:54.9066667Z | 00:00:23 | The process cannot access the file 'C:\Users\G5TFSBuild\.nuget\packages\xyz.payroll.engine.dataprovider\63.0.0.75\.nupkg.metadata' because it is being used by another process. Process 'msbuild.exe' exited with code '1'.
xyz-PR-AzureTest-08 | Build DataSvc | 63.0.0.06816-2419-983 | AZG1PR1BLD01 | 2022-03-09T21:30:33.2833333Z | 00:00:18 | The process cannot access the file 'C:\Users\g5tfsbuild\.nuget\packages\xyz.payroll.datadomain\1.1.0.24\xyz.Payroll.DataDomain.nuspec' because it is being used by another process. Process 'msbuild.exe' exited with code '1'.
xyz-PR-AzureTest-08 | Build DataSvc | 63.0.0.06816-2426-984 | AZG1PR1BLD01 | 2022-03-09T21:30:33.2633333Z | 00:00:18 | Could not find file 'C:\Users\g5tfsbuild\.nuget\packages\xyz.payroll.engine.taxengine\63.0.0.72\ca1ntxq3.v2a'. Process 'msbuild.exe' exited with code '1'.
xyz-master-SQ | Build Main | 63.0.0.05909-fulljs | TDC5DFC1BLD29 | 2022-02-28T15:40:29.7333333Z | 00:00:12 | Failed to retrieve information about 'UpdateProjectMetadata' from remote source 'https://nuget.devexpress.com/bla-bla-bla/api/FindPackagesById()?id='UpdateProjectMetadata'&semVerLevel=2.0.0'.   Response status code does not indicate success: 502 (Bad Gateway). Process 'msbuild.exe' exited with code '1'.
xyz-hf62-PR | Build DataSvc | 62.0.0.05415-0234-722 | TOR4DFC1BLD01 | 2022-02-23T21:38:49.1066667Z | 00:00:35 | Could not find file 'C:\Users\G5TFSBuild\.nuget\packages\xyz.payroll.engine.payrollengine\62.0.0.434\rtkd102g.o4h'. Process 'msbuild.exe' exited with code '1'.
xyz-hf62-PR | Build DataSvc | 62.0.0.05415-1141-723 | TOR4DFC1BLD01 | 2022-02-23T21:38:49.1033333Z | 00:00:35 | Could not find file 'C:\Users\G5TFSBuild\.nuget\packages\xyz.payroll.engine.payrollengine\62.0.0.434\uqjswqpj.ybn'. Process 'msbuild.exe' exited with code '1'.
xyz-PR-AzureTest-09 | Build DataSvc | 62.0.0.05312-0819-940 | AZG5DFC1BLD09 | 2022-02-22T18:27:49.1533333Z | 00:00:29 | Access to the path is denied. Process 'msbuild.exe' exited with code '1'.
xyz-PR-AzureTest-09 | Build DataSvc | 62.0.0.05312-0809-939 | AZG5DFC1BLD09 | 2022-02-22T18:27:49.14Z | 00:00:29 | The process cannot access the file 'nrfpkqkz.rq1' because it is being used by another process. Process 'msbuild.exe' exited with code '1'.
xyz-r62-PR | Build DataSvc | 62.0.0.05311-5243-705 | TDC5DFC1BLD19 | 2022-02-22T16:59:38.3166667Z | 00:00:14 | Failed to retrieve information about 'GenerateBindingRedirects' from remote source 'http://tfs:8080/tfs/DefaultCollection/_packaging/48f434f6-c697-4ae9-93e4-9024b238ed36/nuget/v3/flat2/generatebindingredirects/index.json'.   Response status code does not indicate success: 503 (Service Unavailable). Process 'msbuild.exe' exited with code '1'.
GC_r61 | Build Deployer | 61.0.0.05310 | TDC5DFC1BLD21 | 2022-02-22T16:59:28.77Z | 00:00:31 | Failed to retrieve information about 'GenerateBindingRedirects' from remote source 'http://tfs:8080/tfs/DefaultCollection/_packaging/48f434f6-c697-4ae9-93e4-9024b238ed36/nuget/v3/flat2/generatebindingredirects/index.json'.   Response status code does not indicate success: 503 (Service Unavailable). Process 'msbuild.exe' exited with code '1'.

</body>
</html>

There are 2 kinds of errors:

1. A momentary (or not) network issue
   There are 3 incidents. Clearly not nuget's fault. However, when building multiple solutions (which comprise the single enterprise application) it could fail the build after 30 minutes - not fail fast. It is possible to restructure the build to first restore all the packages and then run the build. This way it would fail fast. On the other hand, I wonder if nuget can be told to retry with timeouts in order to survive what could be a short network blackout.
1. IO related failures
   This one is more serious because it seems there is some kind of a race condition when multiple builds running on the same machine try to restore the same packages.

The IO issue is very problematic because it can result in a corrupt NuGet package directory with a missing nuspec file. This is a poisonous error - it would not heal itself. The only resolution is to delete the respective NuGet package folder to force its restoration. I specifically excluded this kind of errors from the report, but we had 22 instances of it in the same period of time and they are the worst, because of the manual intervention necessary to fix them.

I tried to reproduce the issue by forcing concurrent restorations with `msbuild /t:restore`, but I am unable to reproduce it reliably. Done about a thousand attempts and only one IO failure occurred - **C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(131,5): error : The process cannot access the file because it is being used by another process.** And it is a weird one - no file path is given.

I would like to know how to troubleshoot these issues? Do we have tools to affect the retries/timeouts for the intermittent network issues? Do we have tools for IO errors? Are there any logs we can turn on to facilitate the IO troubleshooting? The msbuild binary log does not seem very relevant here.

**Comment by nkolev92** [comment] 2022-03-11 21:55
Hey @MarkKharitonov 

Do you redirect any of the nuget global folders and caches, such as the temp folder? https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders. 

There was a recent fix for .nupkg.metadata files, but that's usually an error that printed the path in question. 

The nuspec missing issues is something we've seen if multiple restores have *completely* different temp caches which breaks all the synchronization logic. 
Eliminating that as a root cause is the first thing that we should try to do.

**Comment by MarkKharitonov** [comment] 2022-03-11 22:08
As a matter of fact - we do. We set the TEMP/TMP folders for the build to be relative to the agent's staging directory, e.g.:
```
TMP = d:\_wf\02\1\a\temp
TEMP = d:\_wf\02\1\a\temp
```
In the past (msbuild 15) we could not do it, because the C# build was creating moniker files there and clearing them meant full rebuild. But this is no longer a problem since msbuild 16 creates moniker files under the respective obj folders.

We do it because we had not once run out of space because unit tests leave garbage behind.

What would you suggest us to do given that we want both nuget to work correctly and have a cheap way to reclaim the disk space from any garbage created during the unit tests?

**Comment by nkolev92** [comment] 2022-03-11 23:40
Honestly, I'm not really sure there's a cheap of doing it. 

For the NuGet.Client solution for example, we wrap nearly all of our tests in a disposable object that deletes the folder it created, only way to break it would be to kill the process by debugging. This is obviously a repo specific approach which is out of the question for what you're doing.

NuGet doesn't really keep many files in it's temp folder. If a file exists, it's because NuGet is working on something. So NuGet won't add much garbage, but obv the problem is not that NuGet creates too much data. 

NuGet doesn't really have a means to override the temp path for NuGet only, maybe that's something we can add? That ofc doesn't address your problem immediately, but it can in the future.

How bad would it be if all agents used the same temp folder?

**Comment by MarkKharitonov** [comment] 2022-03-11 23:59
It will not be bad right away, because it takes time for the garbage to accumulate. But it does eventually and it always blows up at a bad time.
I guess I have no choice here, but use the common temp directory.

It would be fantastic if nuget could have a dedicated environment variable providing the path for its temporary files. And falling back to temp if the former is not specified.

**Comment by nkolev92** [comment] 2022-03-12 00:39
@MarkKharitonov 

It'd be great if you can let us know if you're still facing problems after the temp directory change. 
Mind creating an issue about the temp directory? 

The fix would be trivial.

**Comment by MarkKharitonov** [comment] 2022-03-12 02:06
@nkolev92 here you go - https://github.com/NuGet/Home/issues/11671

I am pretty sure there will be no problems. After all, my tests (they shared the same temp directory) ran for hours with only one issue mentioned in my post. Which can be an outlier.

**Comment by nkolev92** [comment] 2022-03-17 18:53
Closing per the last comment. @MarkKharitonov we can reopen if necessary.

**Closed as completed by nkolev92** 2022-03-17 18:53 UTC
Labels: Type:Bug, Functionality:Restore, Resolution:NotABug
