### ISSUE TITLE
nuget pack Illegal characters in path.

### ISSUE THREAD

**Issue by shalomshachne** [NuGet/Home#8303] opened 2019-07-05 08:13 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): NuGet Version: 5.0.2.5988

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2013

OS version (i.e. win10 v1607 (14393.321)):  Windows 7

Worked before? If so, with which NuGet version: NuGet Version: 4.8.1.5435

## Detailed repro steps so we can see the same problem

1.    Use attached zipped project.  Note that on my machine, the project was located in C:\dev\NugetTest

2.   nuget pack NugetTest.csproj

Output is:
c:\dev\NugetTest>nuget pack
Attempting to build package from 'NugetTest.csproj'.
Illegal characters in path.
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

NuGet Version: 5.0.2.5988
Attempting to build package from 'NugetTest.csproj'.
Illegal characters in path.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.CommandLine.MsBuildUtility.GetMSBuild()
   at NuGet.CommandLine.MsBuildUtility.GetMsBuildToolset(String userVersion, IConsole console)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at NuGet.CommandLine.PackCommand.<ExecuteCommand>b__80_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

Note: there is no error when running with previous version of Nuget (as noted above).

### Sample Project

[NugetTest.zip](https://github.com/NuGet/Home/files/3361741/NugetTest.zip)

Very helpful if you can zip a project and paste into this issue!

**Comment by zivkan** [comment] 2019-07-05 21:26
Can you please check your PATH to see if there's anything unusual there?

The section of code that is throwing the exception is the following:

https://github.com/NuGet/NuGet.Client/blob/ea3458258a63d7329d2cf1c9a7f75885d16ffc3e/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L976-L1001

The exception comes from line 992, where it's trying to combine a directory from your environment's PATH with a static string.

**Comment by nkolev92** [comment] 2019-07-08 19:09
@zivkan could you repro this with the repro project?

**Comment by zivkan** [comment] 2019-07-08 19:25
no, `nuget pack` failed because the nuspec didn't have authors or a description, but it was able to find msbuild successfully on my machine, so I couldn't reproduce the same error as reported.

**Comment by gilbahat** [comment] 2019-09-05 13:45
Hi. getting the same error here, this is a real drag.
here's the path I have:

C:\Program Files (x86)\Java\jre1.8.0_151\bin;C:\Program Files (x86)\Google\Chrome\Application;D:\app\product\12.2.0\client_64\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\ESET\ESET Security\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\mingw32\bin;C:\Program Files (x86)\Git\usr\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\integrator\AppData\Local\Microsoft\WindowsApps;;"C:\Program Files\Java\jre1.8.0_221\bin"

I would expect nuget to skip over bad path entries and not fault the whole thing on these, in line with how the system behaves in general with bad path entries.

**Comment by shalomshachne** [comment] 2019-09-05 14:16
I would expect Nuget to work as it did in previous version, without
introducing new issue like this.

**Comment by zivkan** [comment] 2019-09-05 15:12
Closing this issue as a duplicate of #8168, which had a fix merged yesterday.

**Closed as completed by zivkan** 2019-09-05 15:12 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Pack
