### ISSUE TITLE
NuGetMissingPackages - OK, what are those packages?

### ISSUE THREAD

**Issue by NeilAllen** [NuGet/Home#10277] opened 2020-11-16 09:55 UTC
Is it so difficult - auto Restore invariably knackers my projects.

How do I find out which packages are missing?

nuget has never made my dev easier - always there's more to do because of it!

**Comment by nkolev92** [comment] 2020-11-30 19:58
Hey @NeilAllen, 

It'd be helpful if you can provide us info about the type of project, the action you were taking, the expected and actual outcomes. The issue template contains some guidance for that.

Copying the the issue template for your convenience. 

**Please fill out the below**

Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

## Other suggested things

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zkat** [comment] 2020-12-17 18:11
Closing for now--please file a new issue using the issue template if you're able. Thanks!

**Closed as completed by zkat** 2020-12-17 18:11 UTC
Labels: Triage:NeedsMoreInfo, WaitingForCustomer

**Comment by NeilAllen** [comment] 2021-05-14 10:04
Here ya go. A prime example. Package is installed. Build errors 'missing package'

![image](https://user-images.githubusercontent.com/13977890/118255366-14b56300-b4a4-11eb-97de-9303b7244b39.png)

**Comment by zivkan** [comment] 2021-05-14 16:29
@NeilAllen One of the issues with using NuGet with packages.config is that packages are restored to a `packages` directory next to your solution file, and the project (`csproj`) file is modified to use a relative path to that `packages` directory. The issue is when the solution directory structure changes and the relative path in the `csproj` to the `packages` folder is no longer correct. This appears to be the situation you are in now.

In Visual Studio 2017, NuGet added `PackageReference` as another way to use packages, which completely eliminates this specific issue. However, in order to benefit most customers, [some limitations/package compatibility issues were added](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#package-compatibility-issues), so some projects either cannot work with PackageReference, or have limited support. In particular, ASP.NET projects have two issues (Packages that use `content\` files are no longer copied into the project, which was used by some projects to add javascript and css, and binding redirects are no longer added to web.config), which is why ASP.NET projects are not enabled for the [packages.config to PackageReference migration tool](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#limitations).

If you open the Package Manager Console, select the project reporting the issue as the target project, and run `Update-Package -Reinstall`, all packages in the project should be uninstalled and then re-installed, causing all those relative paths to the solution `packages` folder to be updated to the current relative path.

Alternatively, you can edit your `csproj` in a text or XML editor (right click the project in Solution Explorer, select Unload, right click it again, select edit, make your changes, right click again and select reload). Or, you can expand the options section in the Package Manager UI in your screenshot, I believe there's an option to allow force uninstall, even if the package is listed as a dependency of another package, uninstall the package, then install it again.

If your projects do not use any NuGet packages that copy content (such as javascript or css) into your project, and your team is willing to manually resolve binding redirect issues, you can use PackageReference. To do this, you'll need to uninstall all packages in the project, close and re-open the solution, go into Visual Studio's Tools->Options, navigate to NuGet Package Management->General, and enable "Ask on first package install". Now, you can start installing your required packages again, and the first one will pop up a dialog asking if you wish to use packages.config or PackageReference.  Warning that if you find it doesn't work for you and you want to go back to packages.config, you will need to manually delete all files from the project's `obj/` folder, otherwise you will get some unusual and unexpected build issues.

Since your project's name sounds like a web application, I assume it's an ASP.NET application and cannot migrate to PackageReference. I suggest your team investigate migrating to ASP.NET Core, which (only) supports PackageReference, and therefore will never have these relative path to the `packages` directory issue, in addition to the other benefits of .NET (Core), such as performance. .NET Core 3.1 is the current LTS release, .NET 5 is the current release, and .NET 6 will be released around November and will be an LTS release.

One of the other big advantages of PackageReference is that your project only needs to install direct dependencies, and transitive dependencies (dependencies of the packages you use) come automatically, unlike in packages.config which adds the entire package graph into the project's installed packages list.
