### ISSUE TITLE
Concurrent nuget install failures

### ISSUE THREAD

**Issue by plaurin** [NuGet/Home#7380] opened 2018-10-09 19:18 UTC
We are using TeamCity with multiple agents on the same physical machine. We want to have all the agents share the same global packages folder to save disk space. Even then, it is not enough and we clear the packages from time to time. The result is that we have only one shared global packages folder, but install and restore operations fail regularly after we clear the locals caches.

We get errors like these
- `Access to the path 'bqipdjvv.1mg' is denied.`
- `The directory is not empty.`

Unfortunately, the NuGetScratch folder is located under the `%temp%` folder which TeamCity override per agent. What we understand is that the scratch folder is used to lock the downloads and installs of packages in the global cache. If we try to install the same package for the first time from different `nuget install` at the same time, the second will wait for the first one to finish without problem. 
However, if I repeat the experiment with different `%temp%` at least one of the `nuget install` will fail.

Is there any reason that the NuGetScratch folder is located in `%temp%` while other NuGet folders are in `%localappdata%` or the user folder?

Do you think there is a way to make this work anyway? I mean using nuget from different TeamCity agents sharing the same global packages folder but not the same `%temp%` folder?

**Comment by cortex93** [comment] 2018-10-11 08:40
This is related to https://github.com/NuGet/Home/issues/7060

**Comment by plaurin** [comment] 2018-10-11 13:02
@cortex93 Yes it looks like you have a similar problem. I made a lot of tests running nuget in parallel and as long as it is running under the same user and same %temp% everything is fine.

Have you tried to run each TFS agent under different user? If it is the same user make sure the %temp% is not separated per agent or you will have the same problem like us.

**Comment by cortex93** [comment] 2018-10-11 17:53
@plaurin Thanks for sharing your experience. Very valuable.

**Comment by nkolev92** [comment] 2019-03-29 18:52
Sorry for the delayed response @plaurin 

Unfortunately you cannot make it work without sharing the temp + global packages folder location. 
This is not something we've seen people do often so it's not super well documented.

You can however override the NuGet temp location to be different from the usual temp location that teamcity redirects. 
Of course this location would still have to be the same across agents. 

https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

Does this answer your question?

**Comment by nkolev92** [comment] 2019-11-14 01:42
Closing this as a by design resolution. 

Doc issue in https://github.com/NuGet/docs.microsoft.com-nuget/issues/1779.

**Closed as completed by nkolev92** 2019-11-14 01:42 UTC
Labels: Product:NuGet.exe, Resolution:ByDesign, Functionality:Restore, Style:PackageReference, Product:dotnet.exe
