### ISSUE TITLE
"Out of memory" and "Task was cancelled" while attempting to restore Roslyn's solution

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#1586] opened 2015-10-16 03:26 UTC
1. Sync to this commit https://github.com/dotnet/roslyn/tree/0df0937a5cd03bcc7c185cd04a541512cf360954
2. From a VS command prompt, and from the Roslyn root, run:

```
nuget restore Roslyn.sln
```

Got a bunch of issues like:

```
WARNING: Unknown Compatibility Profile: net46.app
WARNING: Unknown Compatibility Profile: dnxcore50.app
All packages are compatible with .NETPlatform,Version=v5.0.
Generating MSBuild file BasicScriptingTest.nuget.props.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with .NETFramework,Version=v4.6 (win7-anycpu).
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
Out of memory.
Installing Microsoft.NETCore.Runtime.Native 1.0.1-beta-23401.
Installing Microsoft.NETCore.Runtime 1.0.1-beta-23401.
Installing System.Runtime.Serialization.Primitives 4.0.11-beta-23401.
Installing System.Private.DataContractSerialization 4.0.1-beta-23401.
Installing System.Console 4.0.0-beta-23401.
Installing System.IO 4.0.11-beta-23401.
Installing System.Diagnostics.Tracing 4.0.21-beta-23401.
Installing System.ObjectModel 4.0.11-beta-23401.
Installing System.Globalization 4.0.11-beta-23401.
Installing System.Threading.Thread 4.0.0-beta-23401.
Installing System.Runtime.Loader 4.0.0-beta-23401.
Installing System.Diagnostics.StackTrace 4.0.1-beta-23401.
Installing System.Diagnostics.Contracts 4.0.1-beta-23401.
Installing System.Private.Uri 4.0.1-beta-23401.
Installing System.Globalization.Calendars 4.0.1-beta-23401.
Installing System.Reflection.Extensions 4.0.1-beta-23401.
Installing System.Threading.Timer 4.0.1-beta-23401.
Installing System.AppContext 4.0.1-beta-23401.
Installing System.Diagnostics.Tools 4.0.1-beta-23401.
Installing Microsoft.NETCore.Windows.ApiSets 1.0.1-beta-23401.
Installing System.Security.Cryptography.Primitives 4.0.0-beta-23401.
Installing System.IO.Pipes 4.0.0-beta-23401.
Installing System.Runtime.Extensions 4.0.11-beta-23401.
Installing System.Runtime 4.0.21-beta-23401.
Installing System.Runtime.Serialization.Json 4.0.1-beta-23401.
Installing Microsoft.NETCore.TestHost 1.0.0-beta-23401.
Installing System.IO.FileSystem 4.0.1-beta-23401.
Installing System.Xml.XDocument 4.0.11-beta-23401.
Installing System.Diagnostics.FileVersionInfo 4.0.0-beta-23401.
Installing System.Threading 4.0.11-beta-23401.
Installing Microsoft.NETCore.Platforms 1.0.1-beta-23401.
Installing System.Threading.Tasks.Parallel 4.0.1-beta-23401.
Installing System.Diagnostics.Process 4.1.0-beta-23401.
Installing System.Text.Encoding.CodePages 4.0.1-beta-23401.
Installing System.Linq 4.0.1-beta-23401.
Installing System.Runtime.Handles 4.0.1-beta-23401.
Installing System.Diagnostics.Debug 4.0.11-beta-23401.
Installing System.Reflection.Primitives 4.0.1-beta-23401.
Installing System.Text.Encoding.Extensions 4.0.11-beta-23401.
Installing System.Xml.XmlDocument 4.0.1-beta-23401.
Installing System.Reflection 4.1.0-beta-23401.
Installing System.Text.Encoding 4.0.11-beta-23401.
Installing System.Dynamic.Runtime 4.0.11-beta-23401.
Installing System.Collections 4.0.11-beta-23401.
Installing System.Security.Cryptography.Algorithms 4.0.0-beta-23401.
Installing System.Resources.ResourceManager 4.0.1-beta-23401.
Installing System.Threading.Tasks 4.0.11-beta-23401.
Installing System.Runtime.InteropServices 4.0.21-beta-23401.
Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.1-beta-23401.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
All packages are compatible with .NETFramework,Version=v4.5.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
Warning: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/System.Runtime/4.0.21-beta-23401
  A task was canceled.
Warning: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/System.Runtime/4.0.21-beta-23401
  A task was canceled.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
Warning: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/System.Runtime/4.0.21-beta-23401
  A task was canceled.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
Failed to download package from 'https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.test.resources.proprietary/1.1.0-beta1-20150824-02/microsoft.codeanalysis.test.resources.proprietary.1.1.0-beta1-20150824-02.nupkg'.
A task was canceled.
```

This machine has 12 GB of RAM with ~4 GB free.

**Comment by davkean** [comment] 2015-10-16 03:32
Note on retry this worked immediately, so it's in-deterministic.

**Comment by emgarten** [comment] 2015-10-16 05:30
Try using _nuget.exe restore Roslyn.sln -DisableParallelProcessing_

It might also help to use nuget.exe 3.2.1-rc, it contains a fix for package download timeouts during project.json restore.

Right now nuget.exe runs all project restores in parallel which is likely the cause of this since roslyn has so many projects. DisableParallelProcessing will force it to restore a single project at a time.

The fix for this may be to add more throttling to nuget.exe for project.json restore, from looking at the code it seems like it could easily get out of control with a lot of projects.

**Comment by davkean** [comment] 2015-10-16 17:59
This looks like it corrupted the package cache - I have zero byte files in certain packages.

**Comment by emgarten** [comment] 2015-10-16 18:46
What version of nuget.exe are you using? 3.2.1-rc has fixes for several issues around global package folder corruption.

https://dist.nuget.org/win-x86-commandline/v3.2.1-rc/nuget.exe

**Comment by yishaigalatzer** [comment] 2015-10-16 20:43
@davkean NuGet 3.2.1-rc should resolve the corruption, and will override such package folders that might have broken halfway through restore.

**Closed as completed** 2015-10-17 02:20 UTC
Labels: Priority:2, Type:Bug

**Comment by davkean** [comment] 2015-10-17 17:05
I verified a private build that @yishaigalatzer, I'm pretty confident it fixes the issue - I ran it constantly overnight - blowing away the package cache each time, and it never failed.
