### ISSUE TITLE
dotnet pack doesn't find assembly dll if windows locale is non-US

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#9561] opened 2020-05-13 15:41 UTC
---
**Issue moved from dotnet/sdk#11442**
- Please respond to @milung.

---

_From @milung on Monday, April 27, 2020 11:19:33 AM_

Generating nuget package does not work on my windows 10 system witn .NET Core SDK 3.1.201 if the system regional settings is the local one (Slovak for region settings) In the such case, I am getting error: 

```
$ dotnet pack
C:\Program Files\dotnet\sdk\3.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5019: File not found
```

After changing to US regional settings in windows settings and restarting powershell session, the result is as expected. Changing back to the slovak regional settings leads to the same error. 

Similar issue when running dotnet nuget publish - in this case the package file cannot be found. 

**Reproducing:** 

- os Win10, with slovak for the regional setting
- create project with `dotnet new classlib`
- add package name /author into the csproj
- have regional settings in non US (Slovak)
- run dotnet pack

**Workaround**

Set the regional setting to English(USA) in windows 10

**Comment by donnie-msft** [comment] 2020-05-13 15:57
@dominoFire ever run into this?

**Comment by milung** [comment] 2020-05-13 16:35
one possible hint here - in the central europe (slovak, czech, germany...), the decimal part separator is comma instead of dot  (US 3.14 == CE 3,14) and the date formats are DD-MM-YYYY instead of MM-DD-YYYY. Quite common that some softwares fall into this trap, so I intentionally keep local settings to get early warniong in our own projects, and it is one of the first thing when I hear some german POs get am issue with the new software running fine "everywere" else.

**Comment by daghb** [comment] 2020-05-25 11:57
First of all, a big thanks to @milung for both finding and suggesting a workaround for this one. I have had the same problem for months not knowing the cause and have been relying on building using our cloud ci tool to be able to pack nugets using dotnet core tools.

I can confirm that the issue is there also for Norwegian regional settings and that the workaround functions. I guess this is a problem that many have but do not know how to remedy.

And once again, this problem would never have occurred with tools created elsewhere in the world.

**Comment by dominoFire** [comment] 2020-12-04 21:25
@daghb @milung I've tried to reproduce this bug using Slovak and Norwegian language packs in Windows 10 with dotnet.exe 5.0.100 and 3.1.200 with no luck.

Are you still experiencing this issue?

If so, could you provide a sample project or a MSBuild structured log file? You can use this PowerShell command to generate a bin log with detailed info:

```powershell
$env:NUGET_SHOW_STACK="true"
dotnet.exe pack /bl:pack.binlog
```

**Comment by dominoFire** [comment] 2021-01-11 19:43
Closing since there's not so much activity and it seems to be fixed in dotnet 5.x ; if anyone has any thoughts, feel free to reply to reopen this issue. Thanks!

**Closed as completed by dominoFire** 2021-01-11 19:43 UTC
Labels: Priority:2, Type:Bug, Tenet:WorldReady, Functionality:Pack, Product:dotnet.exe, WaitingForCustomer, Category:Quality Week
