### ISSUE TITLE
WPF Multiple Projects Incorrect Package Version

### ISSUE THREAD

**Issue by JemQDev** [NuGet/Home#13426] opened 2024-05-02 02:22 UTC
### NuGet Product Used

dotnet.exe

### Product Version

dotnet

### Impact

I'm unable to use this version

### Repro Steps & Context

Using Directory.Packages.props file, Main Project loads correct versions of the Packages.
Adding a second project, does not load packages - fixed by ensuring <TargetFramework> is the exact same between projects.
When the <TargetFramework> is aligned the second project loads the packages but the minimum version.
EntityFramework.Core (1.0.0) but does load Microsoft.EntityFrameworkCore.SqlServer.HierarchyId as (8.0.0)

Directory.Build.props
`<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		
		
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageVersion Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
		<PackageVersion Include="Serilog" Version="3.1.1" />
		<PackageVersion Include="Serilog.Sinks.Async" Version="1.5.0" />
		<PackageVersion Include="Serilog.Sinks.Debug" Version="2.0.0" />
		<PackageVersion Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageVersion Include="System.DirectoryServices.AccountManagement" Version="8.0.0" />
    
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.0" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageVersion>
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageVersion>
		<PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageVersion>
		<PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer.HierarchyId" Version="8.0.0" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageVersion>
		<PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="8.0.0" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageVersion>
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageVersion>
	</ItemGroup>

</Project>
`
Main Project csproj
`<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<LangVersion>12.0</LangVersion>
		<UseWPF>true</UseWPF>
		<StartupObject>DigitalOrebodyRHOKSWPF.App</StartupObject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ApplicationDefinition Remove="App.xaml" />
		<Page Include="App.xaml" />
	</ItemGroup>

	
</Project>`

Secondary Project csproj
`<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<LangVersion>12.0</LangVersion>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.HierarchyId" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
	</ItemGroup>
</Project>
`

Thanks in advance.

**Comment by kartheekp-ms** [comment] 2024-05-02 23:10
As per the [Central Package Management](https://learn.microsoft.com/nuget/consume-packages/Central-Package-Management#enabling-central-package-management) the .props file name should be `Directory.Packages.props` instead of `Directory.Build.props`.

When I renamed the. props file, I was unable to reproduce the issue by following the steps mentioned in the issue description.

<img width="1759" alt="image" src="https://github.com/NuGet/Home/assets/52756182/3c6848e0-593a-4f12-83f9-26aa6e16ad43">

<img width="1767" alt="image" src="https://github.com/NuGet/Home/assets/52756182/453e5c70-39e7-474e-86b2-9232c6df0de1">

Then I executed `dotnet list package` command whose output matched with versions displayed in the VS.

```
> dotnet list package
Project 'MainProject' has the following package references
   [net8.0-windows7.0]:
   Top-level Package                               Requested   Resolved
   > CommunityToolkit.Mvvm                         8.2.2       8.2.2
   > Microsoft.Extensions.DependencyInjection      8.0.0       8.0.0
   > Microsoft.Extensions.Hosting                  8.0.0       8.0.0

Project 'SecondProject' has the following package references
   [net8.0-windows7.0]:
   Top-level Package                                               Requested   Resolved
   > Microsoft.EntityFrameworkCore                                 8.0.0       8.0.0
   > Microsoft.EntityFrameworkCore.Design                          8.0.0       8.0.0
   > Microsoft.EntityFrameworkCore.SqlServer                       8.0.0       8.0.0
   > Microsoft.EntityFrameworkCore.SqlServer.HierarchyId           8.0.0       8.0.0
   > Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite      8.0.0       8.0.0
   > Microsoft.EntityFrameworkCore.Tools                           8.0.0       8.0.0
```
I am closing this issue as not a bug. Please feel free to reopen it if the suggestion to change the file name to `Directory.Packages.props` doesn't work for your scenario.

**Closed as completed by kartheekp-ms** 2024-05-02 23:10 UTC
Labels: Type:Bug, Product:dotnet.exe, Resolution:NotABug, Area:RestoreCPM
