### ISSUE TITLE
Microsoft.AspNetCore.Mvc.NewtonsoftJson: package update info wrong for .NET Core 3.1

### ISSUE THREAD

**Issue by Pilchie** [NuGet/Home#10419] opened 2020-12-30 00:11 UTC
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @markm77.

---

_From @markm77 on Friday, December 18, 2020 6:25:54 PM_

Hi there,

I have a C# solution which uses the Microsoft.AspNetCore.Mvc.NewtonsoftJson package. Unfortunately since the release of .NET 5, both Rider and Visual Studio try to update it in my .NET Core 3.1 projects to v5.0.1 which fails.

The root problem can reproduced by running the command ```dotnet list package --outdated``` and observing the output:

```
Project `X` has the following updates to its packages
   [netcoreapp3.1]: 
   Top-level Package                              Requested   Resolved   Latest
   > Microsoft.AspNetCore.Mvc.NewtonsoftJson      3.1.10      3.1.10     5.0.1
```

I guess some meta-data need fixing somewhere?

BR,
Mark

**Comment by Pilchie** [comment] 2020-12-30 00:11
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @Pilchie.

---

_From @Pilchie on Saturday, December 26, 2020 10:28:16 PM_

Unfortunately, NuGet doesn't support packages like this that are tied to a TFM.

**Comment by Pilchie** [comment] 2020-12-30 00:11
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @markm77.

---

_From @markm77 on Saturday, December 26, 2020 10:32:18 PM_

Thanks for the reply. Does this mean you have no way to tell Nuget v5.0.1 requires .NET 5.0. I don't seem to have this issue with any other package (presumably many have .NET 5.0 specific updates).

Edit: the real consequence of this is I can no longer auto-update everything because it fails. I now need to update packages one-by-one avoiding this one.

**Comment by Pilchie** [comment] 2020-12-30 00:11
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @Pilchie.

---

_From @Pilchie on Saturday, December 26, 2020 10:34:58 PM_

Well, the package does only have assets for .NET 5, but that's not enough for NuGet.

**Comment by Pilchie** [comment] 2020-12-30 00:11
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @markm77.

---

_From @markm77 on Saturday, December 26, 2020 10:37:43 PM_

Does this info explain how Microsoft.AspNetCore.Mvc.NewtonsoftJson v5.0.1 could be made to have a dependency on .NET 5.0?

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#declaring-dependencies-advanced

**Comment by Pilchie** [comment] 2020-12-30 00:11
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @Pilchie.

---

_From @Pilchie on Saturday, December 26, 2020 10:40:21 PM_

But we don't want it to support multiple frameworks.  We want it to support 5.0 only, which is what it currently does.  I'm not sure why that shows as an updated to an app targeting 3.1.

**Comment by Pilchie** [comment] 2020-12-30 00:11
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @markm77.

---

_From @markm77 on Saturday, December 26, 2020 10:43:16 PM_

> But we don't want it to support multiple frameworks. We want it to support 5.0 only, which is what it currently does. I'm not sure why that shows as an updated to an app targeting 3.1.

That's what I thought. And I can confirm if the update is attempted it fails on a .NET 3.1 project.

The problem is NuGet keeps suggesting the incorrect update. It does so in Rider, Visual Studio and on the command line. And then when you attempt the update it fails.

**Comment by Pilchie** [comment] 2020-12-30 00:11
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @markm77.

---

_From @markm77 on Saturday, December 26, 2020 10:44:52 PM_

Just to be clear: I am certainly not requesting support for multiple frameworks. I just don't want to be offered a .NET 5.0-only update in a .NET 3.1 project. If you would like me to collect any particular diagnostics, I'm more than happy to do so.

**Comment by Pilchie** [comment] 2020-12-30 00:11
---
**Issue moved from dotnet/aspnetcore#28728**
- Please respond to @Pilchie.

---

_From @Pilchie on Wednesday, December 30, 2020 12:11:02 AM_

This is an issue for https://github.com/NuGet/Home.

**Comment by markm77** [comment] 2020-12-30 00:57
Thanks @Pilchie for moving this.

**Comment by erdembayar** [comment] 2020-12-31 00:51
@markm77
Do you have any log or screenshots for how it's failing to upgrade from .Netcore 3.1 to .Netcore 5.0?
Are you using VS or command line tools? If it's VS which version are you using? 
If is it small project you can simply manually edit the csproj file to target .Net 5.0 after downloading latest .Net 5 sdk.
Please let me know.

**Comment by markm77** [comment] 2020-12-31 11:14
Hi @erdembayar , I am not wanting or trying to update from .NET Core 3.1 to .NET 5. The issue is the package ```Microsoft.AspNetCore.Mvc.NewtonsoftJson``` is no longer handled correctly in a .NET Core 3.1 project.

The simplest way to demonstrate this is to create a blank .NET Core 3.1 project file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```

Now try to add the package without specifying the version:
```
 dotnet add package Microsoft.AspNetCore.Mvc.NewtonsoftJson
```

It incorrectly tries to install the .NET 5.0 version of the package (v5.0.1) rather than the .NET 3.1 version of the package (v3.1.10):
```
 Determining projects to restore...
  Writing C:\Users\mark\AppData\Local\Temp\tmpCAE8.tmp
info : Adding PackageReference for package 'Microsoft.AspNetCore.Mvc.NewtonsoftJson' into project 'C:\Repos\Tmp\Test2\Test2.csproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/microsoft.aspnetcore.mvc.newtonsoftjson/index.json
info :   GET https://pkgs.dev.azure.com/JeringTech/d448659f-ef17-468c-af65-fbd1d8a17643/_packaging/535b60a6-84f3-4dd6-a898-6e4ccd1ee3e6/nuget/v3/registrations2-semver2/microsoft.aspnetcore.mvc.newtonsoftjson/index.json
info :   GET https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/registration/microsoft.aspnetcore.mvc.newtonsoftjson/index.json
info :   NotFound https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/registration/microsoft.aspnetcore.mvc.newtonsoftjson/index.json 768ms
info :   NotFound https://pkgs.dev.azure.com/JeringTech/d448659f-ef17-468c-af65-fbd1d8a17643/_packaging/535b60a6-84f3-4dd6-a898-6e4ccd1ee3e6/nuget/v3/registrations2-semver2/microsoft.aspnetcore.mvc.newtonsoftjson/index.json 966ms
info : Restoring packages for C:\Repos\Tmp\Test2\Test2.csproj...
error: NU1202: Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 5.0.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 5.0.1 supports: net5.0 (.NETCoreApp,Version=v5.0)
error: Package 'Microsoft.AspNetCore.Mvc.NewtonsoftJson' is incompatible with 'all' frameworks in project 'C:\Repos\Tmp\Test2\Test2.csproj'.
```

If I manually add the correct version of the package, all well and good:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.10" />
  </ItemGroup>

</Project>
```

Except then it always wants to upgrade to the incompatible version which is a pain when managing and upgrading packages:
```
 dotnet list package --outdated

The following sources were used:
   https://api.nuget.org/v3/index.json
   https://pkgs.dev.azure.com/JeringTech/Javascript.NodeJS/_packaging/Temp/nuget/v3/index.json
   https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json
   C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Project `Test2` has the following updates to its packages
   [netcoreapp3.1]:
   Top-level Package                              Requested   Resolved   Latest
   > Microsoft.AspNetCore.Mvc.NewtonsoftJson      3.1.10      3.1.10     5.0.1

```

I presumed there was some meta-data problem with the package but was told this is a Nuget issue.

**Comment by erdembayar** [comment] 2020-12-31 17:30
It looks [TFM compatibility issue](https://github.com/dotnet/aspnetcore/issues/28098#issuecomment-733274449), because latest `NewtonsoftJson 5.0.1` not compatible with `netcoreapp3.1`
It's known issue [#10309](https://github.com/NuGet/Home/issues/10309)
Meantime until it addressed you can use below command as work around.
`dotnet add package Microsoft.AspNetCore.Mvc.NewtonsoftJson -v 3.1.10`

I'm closing this, because it's dup of [#5725 ](https://github.com/NuGet/Home/issues/5725).

**Closed as completed by erdembayar** 2020-12-31 17:30 UTC
Labels: Platform:Xplat, Product:dotnet.exe, Functionality:ListPackage

**Comment by markm77** [comment] 2020-12-31 20:28
Okay, thanks for getting to the bottom of this. We are sticking with .NET Core 3.1 as it is the LTS release (we will update to next LTS release when it arrives) - I suspect many others are doing the same. I think making NuGet updates work well in this use case would help many folks. Anyway Happy New Year and thanks to @erdembayar and @Pilchie for the help.
