### ISSUE TITLE
Cannot use an encrypted API key with dotnet nuget push on Linux

### ISSUE THREAD

**Issue by FlorianHockmann** [NuGet/Home#7473] opened 2018-11-03 17:09 UTC
I want to be able to push NuGet packages from Linux to nuget.org without having to specify the API key every time and without having to use Mono to execute nuget.exe.

Unfortunately I'm getting this error message when I try it with `dotnet nuget push`:

```bash
error: Encryption is not supported on non-Windows platforms.
```

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

NuGet version (x.x.x.xxx): 4.8.1.0

dotnet.exe --version (if appropriate): 2.1.403

OS version (i.e. win10 v1607 (14393.321)): Linux Subsystem for Windows with Ubuntu 16.04.5 LTS

## Detailed repro steps so we can see the same problem

1. Set an API key using nuget.exe:
```bash 
$> mono nuget.exe setApiKey [someApiKey] -ConfigFile ~/.nuget/NuGet/NuGet.Config
```
(I specify the `ConfigFile` here as `dotnet nuget` apparently ignores the config used by `mono nuget.exe`, see #4095. Mono is used to set the API key because this functionality is still missing with the dotnet CLI #6437.).

2. Try to push a NuGet package with `dotnet nuget push`:
```bash
$> dotnet nuget push SomePackage.1.0.0.nupkg -s https://api.nuget.org/v3/index.json --force-english-output
error: Encryption is not supported on non-Windows platforms.
```

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

`--verbosity` seems to be not supported by `dotnet nuget push`:

```bash
Specify --help for a list of available options and commands.
error: Unrecognized option '--verbosity'
```

**Comment by rrelyea** [comment] 2018-11-05 17:12
Duplicate of https://github.com/NuGet/Home/issues/6437

**Closed as completed by rrelyea** 2018-11-05 17:12 UTC
Labels: Resolution:Duplicate, Product:NuGet.exe, Platform:Xplat, Area:Settings
