### ISSUE TITLE
RC4: Cannot build Android project with project.json

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#4547] opened 2017-02-09 15:38 UTC
This works correctly in VS 2015 and fails in VS 2017.

I have a solution using csproj + project.json during build, the android project is getting tons of missing types with VS 2017 despite working with 2015:

Repo: 
clone https://github.com/xunit/devices.xunit
using nuget v4 from the cmd line due to a bug with the restore target, use nuget.exe restore xunit.devices.sln

Only the android one seems to be failing like this. the iOS one (xunit.runner.ios) which uses the same csproj+project.json mechanism works correctly.

now try to build. it fails with numerous errors on the Xamarin project similar to these:

```
C:\dev\git\devices.xunit\src\xunit.runner.viewmodels\ViewModels\ViewModelBase.cs(13,50): error CS0066: 'ViewModelBase.PropertyCha
nged': event must be of a delegate type [C:\dev\git\devices.xunit\src\xunit.runner.android\xunit.runner.android.csproj]
C:\dev\git\devices.xunit\src\xunit.runner.xamarin\FormsRunner.cs(12,25): error CS0012: The type 'Object' is defined in an assembl
y that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85
d7bea7798e'. [C:\dev\git\devices.xunit\src\xunit.runner.android\xunit.runner.android.csproj]
C:\dev\git\devices.xunit\src\xunit.runner.viewmodels\Utilities\FilteredCollectionView.cs(105,33): error CS0518: Predefined type '
System.Object' is not defined or imported [C:\dev\git\devices.xunit\src\xunit.runner.android\xunit.runner.android.csproj]
C:\dev\git\devices.xunit\src\xunit.runner.viewmodels\Utilities\FilteredCollectionView.cs(105,33): error CS0246: The type or names
pace name 'Array' could not be found (are you missing a using directive or an assembly reference?) [C:\dev\git\devices.xunit\src\
xunit.runner.android\xunit.runner.android.csproj]
C:\dev\git\devices.xunit\src\xunit.runner.viewmodels\Utilities\FilteredCollectionView.cs(105,46): error CS0518: Predefined type '
System.Int32' is not defined or imported [C:\dev\git\devices.xunit\src\xunit.runner.android\xunit.runner.android.csproj]
C:\dev\git\devices.xunit\src\xunit.runner.viewmodels\Utilities\FilteredCollectionView.cs(105,9): error CS0518: Predefined type 'S
ystem.Void' is not defined or imported [C:\dev\git\devices.xunit\src\xunit.runner.android\xunit.runner.android.csproj]
```

**Comment by dtivel** [comment] 2017-02-09 21:03
Thank you for reporting this issue, Oren.  I've reproduced it and am investigating.

**Comment by rrelyea** [comment] 2017-02-10 21:58
Opened issue on Xamarin for Android - internal bug 383558

This looks like why it no longer resolves from the GAC: https://github.com/xamarin/xamarin-android/commit/78b0ff92ccc13cb3e12a87cd681f7f92ca405404
This is a good change, but it seems this repro had been relying on GAC resolution all along. 

**Comment by nguerrera** [comment] 2017-02-10 22:00
More info: NoStdLib=true set somewhere in Android SDK is preventing mscorlib.dll from getting used from TargetFrameworkDir to smooth over mscorlib conflicts.

Workaround:
``` diff
diff --git a/src/xunit.runner.android/xunit.runner.android.csproj b/src/xunit.runner.android/xunit.runner.android.csprojindex db6f4ec..97ead99 100644
--- a/src/xunit.runner.android/xunit.runner.android.csproj
+++ b/src/xunit.runner.android/xunit.runner.android.csproj
@@ -14,6 +14,7 @@
     <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
     <AndroidUseLatestPlatformSdk>False</AndroidUseLatestPlatformSdk>
     <TargetFrameworkVersion>v6.0</TargetFrameworkVersion>
+    <NoStdLib>false</NoStdLib>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
     <DebugSymbols>true</DebugSymbols>
diff --git a/test/test.xunit.runner.android/test.xunit.runner.android.csproj b/test/test.xunit.runner.android/test.xunit.runner.android.csproj
index 9ffda1b..0e266e4 100644
--- a/test/test.xunit.runner.android/test.xunit.runner.android.csproj
+++ b/test/test.xunit.runner.android/test.xunit.runner.android.csproj
@@ -24,6 +24,7 @@
     <JavaOptions />
     <TargetFrameworkVersion>v6.0</TargetFrameworkVersion>
     <CopyNuGetImplementations>true</CopyNuGetImplementations>
+    <NoStdLib>false</NoStdLib>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
     <DebugSymbols>true</DebugSymbols>
```

**Comment by clairernovotny** [comment] 2017-02-10 22:04
@rrelyea it's not just my project in terms of GAC resolution, it's the standard Xamarin.Android project template. It's affecting MSAL as well.

**Comment by nguerrera** [comment] 2017-02-10 23:51
@onovotny Can you confirm if the nostdlib workaround works for you?

**Comment by clairernovotny** [comment] 2017-02-11 01:01
Yes, that appears to work. I do want to emphasize that the templates for Xamarin Android don't have this set by default and it worked in 2015 so something regressed in the toolchain.

**Comment by nguerrera** [comment] 2017-02-11 02:30
Of course. Just checking so xamarin folks know what would fix it.

**Comment by kzu** [comment] 2017-02-12 07:27
This is fixed on our side at the `Xamarin.Android` targets level and should be included by RTW.

**Closed as completed** 2017-02-13 15:07 UTC
Labels: Product:VS.Client, Resolution:External, Triage:Investigate
