### ISSUE TITLE
[Bug]: NU1604 when using CPM with analyser packages

### ISSUE THREAD

**Issue by lonix1** [NuGet/Home#11981] opened 2022-07-22 07:44 UTC
### NuGet Product Used

dotnet.exe

### Product Version

dotnet 6.0.302, msbuild 16.5.0.26101, nuget 6.2.1.7, linux, vscode

### Worked before?

no

### Impact

Other

### Repro Steps & Context

I'm using the new "Central Package Managment" feature. It doesn't work for analyser (and similar) packages.

For example, I want to use the [`AsyncFixer`](https://www.nuget.org/packages/AsyncFixer#package-reference) package.

It is installed in `MyProject.csproj` like this:
````xml
<PackageReference Include="AsyncFixer" Version="1.6.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
````
But since I'm using CPM, I remove the `Version` property (and add it to `Directory.Packages.props` instead).

When I run `dotnet restore`, I get this:
> /home/username/MyProject/MyProject.csproj : **warning NU1604**: Project dependency AsyncFixer does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.

I don't have that problem for normal packages, only ones with `PrivateAssets` and `IncludeAssets`.

**Comment by jeffkl** [comment] 2022-07-29 16:36
@lonix1 can you please share your Directory.Packages.props as well?  The scenario should work just fine:

Project:
```xml
<PackageReference Include="AsyncFixer">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

Directory.Packages.props
```xml
<PackageVersion Include="AsyncFixer" Version="1.6.0" />
```

**Comment by JamesDriscoll** [comment] 2022-08-26 16:53
I believe I am seeing similar issues, and am doing so on Windows and Linux.
However, for me, this is is not just confined to analyzers.
dotnet build/restore seems to be ignoring the preview feature whilst Visual Studio accepts it.
Hope this helps!

# My Setup
```
C:\Playground\nuget>dotnet --version
6.0.400

C:\Playground\nuget>dotnet --list-sdks
6.0.400 [C:\Program Files\dotnet\sdk]

C:\Playground\nuget>dotnet nuget --version
NuGet Command Line
6.3.0.128
```
# Project Folder
```
C:\Playground\nuget>dir
 Volume in drive C is Windows
 Volume Serial Number is 16C9-A32C

 Directory of C:\Playground\nuget

26/08/2022  17:45    <DIR>          .
26/08/2022  17:45    <DIR>          ..
26/08/2022  17:24    <DIR>          bin
26/08/2022  17:35               624 nuget.csproj
26/08/2022  17:42    <DIR>          obj
26/08/2022  17:12               105 Program.cs
               2 File(s)            729 bytes
```
# nuget.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="nunit" Version="3.13.3" />
    <PackageReference Include="nunit" />
  </ItemGroup>
</Project>
```
# Program.cs
```c#
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```
# Visual Studio 2022 (17.3.2) "Output From Build"
```
Rebuild started...
The project C:\Playground\nuget\nuget.csproj is using CentralPackageVersionManagement, a NuGet preview feature.
Restored C:\Playground\nuget\nuget.csproj (in 38 ms).
1>------ Rebuild All started: Project: nuget, Configuration: Debug Any CPU ------
1>nuget -> C:\Playground\nuget\bin\Debug\net6.0\nuget.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```
# Output From dotnet restore
```
C:\Playground\nuget>dotnet restore
  Determining projects to restore...
C:\Playground\nuget\nuget.csproj : error NU1604: Project dependency nunit does not contain an inclusive lower bound. In
clude a lower bound in the dependency version to ensure consistent restore results.
C:\Playground\nuget\nuget.csproj : error NU1701: Package 'NUnit 2.5.7.10213' was restored using '.NETFramework,Version=
v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v
4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0'. This
 package may not be fully compatible with your project.
  Failed to restore C:\Playground\nuget\nuget.csproj (in 343 ms).
```
# Output From dotnet build
```
C:\Playground\nuget>dotnet build
MSBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
C:\Playground\nuget\nuget.csproj : error NU1604: Project dependency nunit does not contain an inclusive lower bound. In
clude a lower bound in the dependency version to ensure consistent restore results.
C:\Playground\nuget\nuget.csproj : error NU1701: Package 'NUnit 2.5.7.10213' was restored using '.NETFramework,Version=
v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v
4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0'. This
 package may not be fully compatible with your project.
  Failed to restore C:\Playground\nuget\nuget.csproj (in 1.22 sec).

Build FAILED.

C:\Playground\nuget\nuget.csproj : error NU1604: Project dependency nunit does not contain an inclusive lower bound. In
clude a lower bound in the dependency version to ensure consistent restore results.
C:\Playground\nuget\nuget.csproj : error NU1701: Package 'NUnit 2.5.7.10213' was restored using '.NETFramework,Version=
v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v
4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0'. This
 package may not be fully compatible with your project.
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:03.76
```

**Comment by lonix1** [comment] 2022-08-27 01:17
@jeffkl Sorry for late response. My config is exactly as in your example, except I'm using it in a build props file.

`Directory.Build.props`
````xml
<PackageReference Include="AsyncFixer">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
````

`Directory.Packages.props`
````xml
<PackageVersion Include="AsyncFixer" Version="1.6.0" />
````

**Comment by jeffkl** [comment] 2022-08-29 17:49
@JamesDriscoll can you run `dotnet restore -bl` and attach `msbuild.binlog`?  That should help me figure out what's going on

**Comment by jeffkl** [comment] 2022-08-29 17:50
@lonix1 can you do a restore with `dotnet restore -bl` and attach `msbuild.binlog` as well so I can see what's happening?

**Comment by JamesDriscoll** [comment] 2022-08-29 19:08
Thanks for the swift response - I hope the attached helps :)
[msbuild.zip](https://github.com/NuGet/Home/files/9447232/msbuild.zip)

**Comment by jeffkl** [comment] 2022-08-29 19:18
Okay I figured out what's going on.  It is not currently supported to use NuGet's central package management but not place your package versions in a "central package versions file".  That file is by default named `Directory.Packages.props`.

At the moment, NuGet expects to use that file and then sets a property indicating if it was imported:

https://github.com/NuGet/NuGet.Client/blob/b396ad8b56c089ec3fa189f1013530d237a0e8c2/src/NuGet.Core/NuGet.Build.Tasks/NuGet.props#L38

Later on, central package management is enabled if that file was imported:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L63

I would recommend that you not place `<PackageVersion />` items in `Directory.Build.props` and of course it is not supported to place them in projects themselves since that's not exactly managing package versions centrally.

As a workaround, you can place `<PackageVersion />` items in `Directory.Build.props` but you'll need to set an additional property to tell NuGet that central package management is enabled:

```xml
<PropertyGroup>
  <!-- Indicate to NuGet that Directory.Packages.props isn't being used since this repo is using Directory.Build.props instead -->
  <CentralPackageVersionsFileImported>true</CentralPackageVersionsFileImported>
</PropertyGroup>
```

**Comment by JamesDriscoll** [comment] 2022-08-29 19:36
Thanks Jeff... I think that has solved it for me :)
I need to double check on my main (non-minimal solution) tomorrow when I am back on the office, but it is looking good so far.
Really appreciate your time on this one! (*)

**Comment by jeffkl** [comment] 2022-08-29 19:45
Closing this as not a bug for now since the only supported method of using NuGet's central package management is to use a file named `Directory.Packages.props` or use your own file and tell NuGet what the name of it is.  Using `Directory.Build.props` is not supported at this time.

**Closed as completed by jeffkl** 2022-08-29 19:45 UTC
Labels: Type:Bug, Resolution:NotABug

**Comment by JamesDriscoll** [comment] 2022-08-29 20:04
👍

**Comment by lonix1** [comment] 2022-08-29 23:22
@jeffkl My setup is exactly as you explain (see my code above): the `Directory.Build.props` defines the packages for all projects in the workspace/solution, but the versions are defined in `Directory.Packages.props`.

**Comment by lonix1** [comment] 2022-08-29 23:47
@jeffkl UPDATE:
I was busy making a small repro for you, and noticed the problem disappeared.

When I posted the issue I was using .net 6.0.302 and now I'm using 6.0.400. Were there fixes/changes for CPM in the interim?

**Comment by jeffkl** [comment] 2022-09-15 15:58
@lonix1 are you enabling central package management via the `ManagePackageVersionsCentrally` property in accordance with [the documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/central-package-management#enabling-central-package-management)?  If so, please attach a simple repro ZIP with a project and a `Directory.Packages.props` that I can use to investigate further.
