### ISSUE TITLE
Regression in .NET 9 RC2: NU1605 Downgrade error which isn't a downgrade

### ISSUE THREAD

**Issue by bkoelman** [NuGet/Home#13855] opened 2024-10-14 21:18 UTC
### NuGet Product Used

Other/NA

### Product Version

.NET 9 RC2 (SDK 9.0.100-rc.2.24474.11)

### Worked before?

Yes, no such errors on .NET 8 and .NET 6

### Impact

It's more difficult to complete my work

### Repro Steps & Context

When building an existing solution with .NET 9 RC2 in Visual Studio, the following warning shows up in the error list. The build output contains "NuGet package restore failed. Please see Error List window for detailed warnings and errors."

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	NU1605	Warning As Error: Detected package downgrade: Microsoft.EntityFrameworkCore.Relational from 8.0.0 to 8.0.8. Reference the package directly from the project to select a different version. 
 SourceGeneratorTests -> TestBuildingBlocks -> Microsoft.EntityFrameworkCore.Relational (>= 8.0.0) 
 SourceGeneratorTests -> JsonApiDotNetCore -> Microsoft.EntityFrameworkCore.Relational (>= 8.0.8)	SourceGeneratorTests (net6.0), SourceGeneratorTests (net8.0), SourceGeneratorTests (net9.0)	D:\Bart\Source\Repos\JsonApiDotNetCore\test\SourceGeneratorTests\SourceGeneratorTests.csproj	1	
```

Note in the message above, that "Detected package downgrade: ... from 8.0.0 to 8.0.8" isn't a downgrade. It's an upgrade, which shouldn't result in an error or warning.

Interestingly, this error does _not_ show up when running `dotnet restore` from the command line.

I can work around it by adding an explicit package reference to the affected project(s), but that shouldn't be required.

**Comment by jeffkl** [comment] 2024-10-14 21:34
@bkoelman are you able to provide a repro of this so we can investigate further?  A simple set of projects with package references that exhibit the behavior would make it a lot easier to understand what's going on.

**Comment by bkoelman** [comment] 2024-10-14 23:30
I've created a minimal repro at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/repro-nuget-13855.

Repro steps:
1. Ensure that SDK v9.0.100-rc.2.24474.11 is installed
2. Clone the repo and checkout branch `repro-nuget-13855`
3. Open `/JsonApiDotNetCore.sln` in VS 17.12.0 Preview 2.1 and rebuild the solution
4. The build succeeds (it doesn't in the full solution), however the following appears in the Output window:
    ```
    Failed to restore D:\Bart\Source\Repos\JsonApiDotNetCore\test\SourceGeneratorTests\SourceGeneratorTests.csproj (in 982 ms).
    NuGet package restore failed. Please see Error List window for detailed warnings and errors.
    ```
    And the Error List shows:
    ![{C1C868F0-B00D-47CF-90BE-7E143EFA3B5D}](https://github.com/user-attachments/assets/9ca79886-11f9-4e63-a390-edc22a790c29)
5. Open `SourceGeneratorTests.csproj` and uncomment the line below `<!-- Uncomment to workaround https://github.com/NuGet/Home/issues/13855 -->`
6. Close and reopen the solution, rebuild and observe the errors are gone.

**Comment by bkoelman** [comment] 2024-10-14 23:51
Another way to reproduce:
1. Ensure no unstable versions are installed for VS and .NET
2. Checkout the master branch and build `/JsonApiDotNetCore.sln` in Visual Studio, observe no errors.
3. Switch to a different computer with the .NET 9 bits and preview VS installed.
4. Build `/JsonApiDotNetCore.sln` in Visual Studio preview, observe the `NuGet package restore failed` message.

**Comment by jeffkl** [comment] 2024-10-15 04:32
Hmm I'm not able to repro with those steps.  I cloned it, checked out the branch, and restored successfully with .NET 9 

```
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.4872d5d5
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Host:
  Version:      9.0.0-rc.2.24473.5
  Architecture: x64
  Commit:       990ebf52fc

MSBuild version 17.13.0-preview-24504-04+c4d51a11b for .NET Framework

  Determining projects to restore...
  Restored D:\Repros\downgrade\src\JsonApiDotNetCore.Annotations\JsonApiDotNetCore.Annotations.csproj (in 1.2 sec).
  Restored D:\Repros\downgrade\src\JsonApiDotNetCore.SourceGenerators\JsonApiDotNetCore.SourceGenerators.csproj (in 1.37 sec).
  Restored D:\Repros\downgrade\src\JsonApiDotNetCore\JsonApiDotNetCore.csproj (in 1.45 sec).
  Restored D:\Repros\downgrade\test\TestBuildingBlocks\TestBuildingBlocks.csproj (in 2.01 sec).
  Restored D:\Repros\downgrade\test\SourceGeneratorTests\SourceGeneratorTests.csproj (in 2.01 sec).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.20
```

This sounds a lot like https://github.com/NuGet/NuGet.Client/pull/6079 which was recently fixed in .NET 9 RC2, it fixes an issue with pre-release floating versions like `1.*-*` which I see used [here](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/repro-nuget-13855/package-versions.props#L18).  Am I not following the steps correctly?

1. Install .NET 9 RC2
2. Clone the repo
3. Check out the `repro-nuget-13855` branch
4. Run `dotnet restore JsonApiDotNetCore.sln`

**Comment by bart-vmware** [comment] 2024-10-15 07:38
> Am I not following the steps correctly?

The error _only_ shows up in Visual Studio, not during `dotnet restore`, which I mentioned above.

If it helps, I have an Azure DevBox instance where I can reproduce this. I can also provide additional diagnostic info, such as a binlog or dump. Please provide steps on how to gather the data and where I can send it privately, if you'd like me to.

Running `dotnet --info` on my DevBox outputs:
```
.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.82e6a096
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    9.0.0-rc.1.24453.9/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.maui\9.0.0-rc.1.24453.9\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.maccatalyst\17.5.9270-net9-rc1\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.ios\17.5.9270-net9-rc1\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    35.0.0-rc.1.80/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.android\35.0.0-rc.1.80\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0-rc.2.24473.5
  Architecture: x64
  Commit:       990ebf52fc

.NET SDKs installed:
  8.0.403 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.1.24452.12 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24474.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by jeffkl** [comment] 2024-10-15 15:18
@bkoelman I think Visual Studio is using version `9.0.100-rc.1.24452.12` of .NET 9 which probably has the bug fixed in https://github.com/NuGet/NuGet.Client/pull/6079.

Can you try placing a `global.json` at the root of the repo:

```json
{
    "sdk": {
        "version": "9.0",
        "rollForward": "latestPatch",
        "allowPrerelease": true
    }
}
```

Then load the solution in Visual Studio.  You might need to delete the VS cache folder, `.vs` as well.

**Comment by jeffkl** [comment] 2024-10-15 15:31
@bkoelman nevermind, I think instead that Visual Studio 17.12 Preview 2 itself still has the bug which will be fixed in Preview 3.  ~~Since Preview 3 won't be out for a while~~, you'll need to workaround the issue by setting an MSBuild property in [Directory.Build.props](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/repro-nuget-13855/Directory.Build.props)

```xml
<PropertyGroup>
  <!-- This property can be removed when Visual Studio 17.12 Preview 3 is released -->
  <RestoreUseLegacyDependencyResolver>true</RestoreUseLegacyDependencyResolver>
</PropertyGroup>
```

Thanks for reporting the issue and being brave enough to use preview versions!  We really appreciate it.

Actually, Visual Studio 17.12 Preview 3 should be released today or tomorrow.

**Comment by bkoelman** [comment] 2024-10-15 21:34
@jeffkl Thanks for the tips. I've updated VS to preview 3 and I'm no longer getting the downgrade error. However, I do get three MSB3277 warnings in that same project, so I still need to apply the workaround (we build with warn-as-error in release builds).

Here's a dump of the warnings from `dotnet build` (this is now consistent with what VS shows):
```
  SourceGeneratorTests net6.0 succeeded (1,0s) → test\SourceGeneratorTests\bin\Debug\net6.0\SourceGeneratorTests.dll
  SourceGeneratorTests net8.0 succeeded with 3 warning(s) (1,0s) → test\SourceGeneratorTests\bin\Debug\net8.0\SourceGeneratorTests.dll
    C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:
      Found conflicts between different versions of "Microsoft.EntityFrameworkCore" that could not be resolved.
      There was a conflict between "Microsoft.EntityFrameworkCore, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.EntityFrameworkCore, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
          "Microsoft.EntityFrameworkCore, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was chosen because it was primary and "Microsoft.EntityFrameworkCore, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was not.
          References which depend on "Microsoft.EntityFrameworkCore, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.dll].
              C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.dll
                Project file item includes which caused reference "C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.dll".
                  C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.dll
          References which depend on or have been unified to "Microsoft.EntityFrameworkCore, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [].
              D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
                Project file item includes which caused reference "D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll".
                  D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
              D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll
                Project file item includes which caused reference "D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll".
                  D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll
                  D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
    C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:
      Found conflicts between different versions of "Microsoft.EntityFrameworkCore.Abstractions" that could not be resolved.
      There was a conflict between "Microsoft.EntityFrameworkCore.Abstractions, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.EntityFrameworkCore.Abstractions, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
          "Microsoft.EntityFrameworkCore.Abstractions, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was chosen because it was primary and "Microsoft.EntityFrameworkCore.Abstractions, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was not.
          References which depend on "Microsoft.EntityFrameworkCore.Abstractions, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore.abstractions\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.Abstractions.dll].
              C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore.abstractions\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.Abstractions.dll
                Project file item includes which caused reference "C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore.abstractions\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.Abstractions.dll".
                  C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore.abstractions\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.Abstractions.dll
          References which depend on or have been unified to "Microsoft.EntityFrameworkCore.Abstractions, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [].
              D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
                Project file item includes which caused reference "D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll".
                  D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
              D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll
                Project file item includes which caused reference "D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll".
                  D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll
                  D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
    C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3277:
      Found conflicts between different versions of "Microsoft.EntityFrameworkCore.Relational" that could not be resolved.
      There was a conflict between "Microsoft.EntityFrameworkCore.Relational, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.EntityFrameworkCore.Relational, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60".
          "Microsoft.EntityFrameworkCore.Relational, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was chosen because it was primary and "Microsoft.EntityFrameworkCore.Relational, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was not.
          References which depend on "Microsoft.EntityFrameworkCore.Relational, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore.relational\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.Relational.dll].
              C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore.relational\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.Relational.dll
                Project file item includes which caused reference "C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore.relational\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.Relational.dll".
                  C:\Users\Bart\.nuget\packages\microsoft.entityframeworkcore.relational\8.0.8\lib\net8.0\Microsoft.EntityFrameworkCore.Relational.dll
          References which depend on or have been unified to "Microsoft.EntityFrameworkCore.Relational, Version=8.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [].
              D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
                Project file item includes which caused reference "D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll".
                  D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
              D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll
                Project file item includes which caused reference "D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll".
                  D:\Bart\Source\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\bin\Debug\net8.0\JsonApiDotNetCore.dll
                  D:\Bart\Source\Repos\JsonApiDotNetCore\test\TestBuildingBlocks\bin\Debug\net8.0\TestBuildingBlocks.dll
  SourceGeneratorTests net9.0 succeeded (0,4s) → test\SourceGeneratorTests\bin\Debug\net9.0\SourceGeneratorTests.dll
```

To summarize:
- Project `SourceGeneratorTests` depends on:
  - `JsonApiDotNetCore` (shippable product): references `EntityFrameworkCore` 8.0.0
  - `TestBuildingBlocks` (test helpers): references `EntityFrameworkCore.Relational` 8.0.* (resolves to 8.0.10)
    - `EntityFrameworkCore.Relational` depends on `EntityFrameworkCore`
      - `EntityFrameworkCore` depends on `EntityFrameworkCore.Abstractions`

The three warnings (about `EntityFrameworkCore`, `EntityFrameworkCore.Relational` and `EntityFrameworkCore.Abstractions`) _only_ show up for the `net8.0` TFM, while the same dependency tree (with different versions) applies to `net6.0` and `net9.0`. While having such a warning may not be wrong in itself, it's annoying to get this on patch-level version differences. And why are there _three_ warnings for `net8.0`, but none for the other TFMs? The `net6.0` situation is more relevant, because the conflict is between v6.0.0 and v7.0.20, so I'd expect a warning there. We're currently using the same versions for `net9.0`, but that'll change in the future.

I'm seeing similar warnings appear in a project at work when switching to the .NET 9 SDK, which is pretty annoying. I think it makes sense to emit them for major version differences, but not for patch-level differences, which I suspect is the .NET 8 SDK behavior.

In this case, the reported problem isn't a real problem, because the `SourceGeneratorTests` doesn't use `EntityFrameworkCore`. I wonder if the .NET 8 SDK recognizes that, which could explain why it doesn't produce a warning.

To repro:
1. Clone https://github.com/json-api-dotnet/JsonApiDotNetCore and checkout branch `test-against-dotnet9`
2. Edit file `test\SourceGeneratorTests\SourceGeneratorTests.csproj` and comment out the line `<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkCoreVersion)" />`
3.  Run `dotnet build`

The same repro steps can be used with the master branch, which contains no `net9.0` targets, but produces the same warnings using the .NET 9 SDK.

**Comment by jeffkl** [comment] 2024-10-15 23:08
It looks like some preview versions of .NET 9 packages contain version conflicts:
```
error NU1107: Version conflict detected for Microsoft.EntityFrameworkCore. Install/reference Microsoft.EntityFrameworkCore 9.0.0-rtm.24508.5 directly to project SourceGeneratorTests to resolve this issue.
error NU1107:  SourceGeneratorTests -> TestBuildingBlocks -> Microsoft.EntityFrameworkCore.Relational 9.0.0-rtm.24508.5 -> Microsoft.EntityFrameworkCore (>= 9.0.0-rtm.24508.5)
error NU1107:  SourceGeneratorTests -> TestBuildingBlocks -> Npgsql.EntityFrameworkCore.PostgreSQL 9.0.0-rc.2-ci.20240930T080442 -> Microsoft.EntityFrameworkCore (= 9.0.0-rc.2.24460.3).
```

So adding a direct package reference to override the version is the only path forward.

**Comment by bkoelman** [comment] 2024-10-16 10:50
Thanks, that makes sense. I agree about the conflict for `net9.0`, which I was able to solve using the following in the `test-against-dotnet9` branch:
```xml
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0' Or '$(BuildingInsideVisualStudio)' == 'true'">
    <!-- Temporary workaround for version range constraint on Npgsql.EntityFrameworkCore.PostgreSQL pre-release package -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkCoreVersion)" />
  </ItemGroup>
```
For reasons I don't understand, the `BuildingInsideVisualStudio` condition is needed because I keep getting the three warnings (MSB3277, not NU1107) when building in VS.

Do you also see the three `net8.0` warnings in the Output Window when building the `master` branch from inside Visual Studio Preview 3? Tip: to clean up the build output there, add the following to `Directory.Build.props`:
```xml
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <NuGetAuditMode>direct</NuGetAuditMode>
    <NoWarn>$(NoWarn);NETSDK1215</NoWarn>
```

I don't understand why I'm getting the `net8.0` warnings, but I did find that `dotnet.exe` processes stay alive after a command-line build. To start clean, I've tried combinations of the following:
- `git clean -xdf`
- `dotnet nuget locals all --clear`
- `dotnet build --no-incremental`
- Sign out/in from Windows to terminate the long-lived `dotnet.exe` processes

Any other caches I should clear to get reliable results?

**Comment by jeffkl** [comment] 2024-10-17 17:18
I'm not sure why you're experiencing compile-time version conflicts, that would greatly depend on the set of assemblies that the compiler is given.  I would suggest a new issue on https://github.com/dotnet/sdk/ or https://github.com/dotnet/msbuild if you get stuck with that.

**Closed as completed by jeffkl** 2024-10-17 17:18 UTC
Labels: Type:Bug, Functionality:Restore, Area:NewDependencyResolver
