### ISSUE TITLE
Nuget 4.0.0 fails looking for NuGet.resources on non-english systems

### ISSUE THREAD

**Issue by GitMonkey007** [NuGet/Home#4780] opened 2017-03-10 02:03 UTC
Having installed VS2017, attempted to build a package and push to Nexus I ran into this issue when trying to package a library... Put simply, nuget is unable to locate Nuget.Resources, but works fine if you specify ForceEnglishOutput

>..\..\nuget pack Echo.csproj
Attempting to build package from 'Echo.csproj'.
MSBuild auto-detection: using msbuild version '15.1.548.43366' from '\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Packing files from '\Echo\bin\Debug'.
WARNING: Description was not specified. Using 'Description'.
WARNING: Author was not specified. Using 'xyz'.
Could not load file or assembly 'NuGet.resources, Version=4.0.0.2283, Culture=en-GB, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
  Could not load file or assembly 'file:///\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\en\NuGet.resources.dll' or one of its dependencies. The system cannot find the file specified.

>..\..\nuget pack Echo.csproj -ForceEnglishOutput
Attempting to build package from 'Echo.csproj'.
MSBuild auto-detection: using msbuild version '15.1.548.43366' from '\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Packing files from 'Echo\bin\Debug'.
WARNING: Description was not specified. Using 'Description'.
WARNING: Author was not specified. Using 'xyz'.
Successfully created package '\Echo\Echo.1.0.0.nupkg'.

>..\..\nuget help
NuGet Version: 4.0.0.2283

Windows 10 build 15048
VS2017 Community Edition

Steps to reproduce...

1. Simply Create a library
2. Attempt to package/push (seriously, that's all)

Verbose Logs

>..\..\nuget pack Echo.csproj -verbosity detailed
NuGet Version: 4.0.0.2283
Attempting to build package from 'Echo.csproj'.
MSBuild auto-detection: using msbuild version '15.1.548.43366' from '\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from '\Echo\bin\Debug'.
Add file '\Echo\bin\Debug\Echo.dll' to package as 'lib\net452\Echo.dll'
WARNING: Description was not specified. Using 'Description'.
WARNING: Author was not specified. Using 'xyz'.

Id: Echo
Version: 1.0.0.0
Authors: xyz
Description: Description
Dependencies:

System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.resources, Version=4.0.0.2283, Culture=en-GB, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.resources, Version=4.0.0.2283, Culture=en-GB, PublicKeyToken=31bf3856ad364e35' ---> System.IO.FileNotFoundException: Could not load file or assembly 'file:///\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\en\NuGet.resources.dll' or one of its dependencies. The system cannot find the file specified.

[Echo.zip](https://github.com/NuGet/Home/files/832797/Echo.zip)

**Comment by eliasnawfal** [comment] 2017-03-21 13:49
Thank you for the solution

**Comment by patricksadowski** [comment] 2017-03-23 11:27
I have the same problem with de-DE.
NuGet Version 4.0.0.2283

Same StackTrace for my project and project 'Echo' from @GitMonkey007:

```csharp
bei System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
bei System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
bei System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
bei System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
bei System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
bei System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
bei System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
bei NuGet.Commands.PackCommandRunner.PrintVerbose(String outputPath, PackageBuilder builder)
bei NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath)
bei NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
bei NuGet.CommandLine.PackCommand.ExecuteCommand()
bei NuGet.CommandLine.Command.ExecuteCommandAsync()
bei NuGet.CommandLine.Command.Execute()
bei NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by advapiIT** [comment] 2017-03-24 10:58
Excuse me, 
Have you found a solution? Got the same problem here...Thanks

**Comment by eliasnawfal** [comment] 2017-03-24 12:24
@advapiIT Just add -ForceEnglishOutput as an argument

**Comment by advapiIT** [comment] 2017-03-25 10:15
Hello ,
that worked...but us tgis the behavior by design?

Il 24 Mar 2017 1:24 PM, "eliasnawfal" <notifications@github.com> ha scritto:

**Comment by patricksadowski** [comment] 2017-03-27 08:00
Usually the neutral resources language is used as fallback if the satellite assembly of the system language is missing. The -forceEnglishOutput argument is a workaround.

**Comment by mishra14** [comment] 2017-03-28 18:55
Investigating.

**Comment by GitMonkey007** [comment] 2017-03-28 20:49
The title of this issue seems to have changed... Just to clarify, this issue also occurs on English language systems. Occurs under en-GB.

**Comment by mishra14** [comment] 2017-03-30 00:08
Should be fixed with NuGet/NuGet.Client#1269. Need to figure out RI check in plan. @rrelyea

**Comment by mishra14** [comment] 2017-03-30 17:08
The commit has been checked into dev, release-4.1.0-rtm, release 4.2.0-rtm and 4.3.0-beta1.

**Closed as completed by mishra14** 2017-03-30 17:08 UTC
Labels: Type:Bug, Product:NuGet.exe

**Comment by rrelyea** [comment] 2017-08-15 20:57
This fix shipped in NuGet.exe 4.1.0 and later
