### ISSUE TITLE
"NU5019: File not found" during pack for a file that exists on Ubuntu 18.04

### ISSUE THREAD

**Issue by tlmii** [NuGet/Home#8245] opened 2019-06-19 21:22 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet.exe

dotnet.exe --version (if appropriate):
Whichever one is pulled down by the current version of dotnet/arcade (looks like 3.0.100-preview-010184)

OS version (i.e. win10 v1607 (14393.321)): Ubuntu 18.04.2 on WSL2 on Win 10 10.0.18917.1000

Worked before? If so, with which NuGet version:
Not for me, but it works in Windows 10, and on the build server, so it seems specific to Ubuntu or WSL
 
## Detailed repro steps so we can see the same problem

1. Clone the [aspnet/HttpRepl](https://github.com/aspnet/HttpRepl) repo in Ubuntu on WSL2 on Win10 (I'm not sure if it will happen on WSL1, but I suspect so. No idea whether it'll happen on other distros of WSL)

2. Run ./build.sh

3. You'll get an error:

`/home/{username}/repos/HttpRepl/.dotnet/sdk/3.0.100-preview-010184/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(199,5): error NU5019: File not found: '/home/{username}/repos/HttpRepl/artifacts/bin/Microsoft.HttpRepl/Debug/netcoreapp2.1/publish/dotnet-httprepl.deps.json'. [/home/{username}/repos/HttpRepl/src/Microsoft.HttpRepl/Microsoft.HttpRepl.csproj]`

The file referenced does exist in the location specified. 
The process works when running .\build.cmd in Windows and it also works in the linux builds on the build server ([example](https://dnceng.visualstudio.com/public/_build/results?buildId=230510&view=logs&j=7b256127-5bb6-55c7-3e9c-ab8d8cd8d148&t=0666211d-f171-55e8-41fa-bfe567a4ffbc&l=48)) so it seems to be specific to Ubuntu or WSL2 or something like that.

**Comment by tlmii** [comment] 2019-06-19 21:56
I removed and recreated my Ubuntu install as a WSL1 install and the issue still exists.

I also installed Debian, as a WSL2 install, and the issue does **not** exist there.

Edit: I also installed Ubuntu 16.04 LTS as a WSL1 install and the issue does **not** exist there.

So to recap:

- Windows 10: Works
- Ubuntu 18.04 on WSL1 on Windows 10: Does not work
- Ubuntu 18.04 on WSL2 on Windows 10: Does not work
- Azure DevOps Pipeline (Ubuntu 16.04?): Works
- Ubuntu 16.04 on WSL1 on Windows 10: Works
- Debian 9 on WSL2 on Windows 10: Works

**Comment by rrelyea** [comment] 2019-06-20 01:06
Can u start by reporting this issue at https://github.com/aspnet/HttpRepl?

**Comment by tlmii** [comment] 2019-06-20 06:22
Hi Rob - Our team actually owns that repo. But the problem is not specific to that repo. That was just an example so someone could reproduce it. The same thing happens with https://github.com/aspnet/AspLabs and https://github.com/dotnet/arcade (with those repos, it gets multiple errors, but they're mostly the same NU5019 errors for files that do actually exist). 

The error points to the PackTask in the NuGet.Build.Tasks.Pack.targets file, but I'm not sure where to go from there. Especially since it works on a bunch of other configurations. I guess since all of these were arcade-based builds I could open an issue with them. But since the NuGet step was where the error was, I thought I'd start with you all and see if you had any ideas.

**Comment by heng-liu** [comment] 2019-06-20 16:36
Hi, thanks for reporting this issue.
I reproduced successfully on Ubuntu 18.04. 
And if I set LANG=en_US.UTF-8 (same with Ubuntu 16.04), the pack will succeed.

Can you help confirm if  the enviroment variable of "LANG" on the failed system(Ubuntu 18.04) is set to C.UTF-8? Thanks!

**Comment by tlmii** [comment] 2019-06-20 17:07
Yep, that works for me. Interesting. So what's the long-term fix for this? Was that a change that Ubuntu plans to keep?

**Comment by heng-liu** [comment] 2019-06-20 17:27
Not sure if it's missing proper LANG setting in WSL or we need to do some change on case insensitive comparisons. We may need futher discussion about the long-term fix. 
Closed as a duplicate of #8246

**Closed as completed by heng-liu** 2019-06-20 17:27 UTC
Labels: Resolution:Duplicate
