### ISSUE TITLE
NuGet pack gives error with C# 6 syntax and WPF usercontrol

### ISSUE THREAD

**Issue by jc1001** [NuGet/Home#1922] opened 2016-01-12 12:38 UTC
Hi there,

Using NuGet version 3.3.  In Visual Studio 2015, I created a new solution with 2 class libraries targeting .NET 4.5.  Both class libraries contain a class that makes use of a C# 6 language feature ($ string formatting in this case).  In the second class library (WithWPF), I also added a new WPF usercontrol.  Code compiles fine in Visual Studio.

When running the command: 

``` javascript
NuGet.exe pack ".\WithoutWPF\WithoutWPF.csproj" -Build -IncludeReferencedProjects -Properties Configuration=Release -NonInteractive -OutputDirectory ".\Output" -Verbosity detailed
```

everything work as expected.  In the background, NuGet is detecting MSBuild 14 and using that to create the package.

When running: 

``` javascript
NuGet.exe pack ".\WithWPF\WithWPF.csproj" -Build -IncludeReferencedProjects -Properties Configuration=Release -NonInteractive -OutputDirectory ".\Output" -Verbosity detailed
```

I get the following error:

``` javascript
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Attempting to build package from 'WithWPF.csproj'.
Building project 'D:\Public\Nuget Pack Test\WithWPF\WithWPF.csproj' for target framework '.NETFramework,Version=v4.5'.
__________________________________________________
Project "D:\Public\Nuget Pack Test\WithWPF\WithWPF.csproj" (default targets):

C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error MSB4127: The "MarkupCompilePass1" task could not be instantiated from the assembly "PresentationBuildTasks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Microsoft.Build.Tasks.Windows.MarkupCompilePass1' to type 'Microsoft.Build.Framework.ITask'.
C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error MSB4060: The "MarkupCompilePass1" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
Done building project "WithWPF.csproj" -- FAILED.
NuGet.CommandLineException: Failed to build 'WithWPF.csproj'.
   at NuGet.CommandLine.ProjectFactory.BuildProjectWithMsbuild()
   at NuGet.CommandLine.ProjectFactory.BuildProject()
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath)
   at NuGet.CommandLine.PackCommand.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.BuildPackage(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

I then forced the pack command to use MSBuild 4 with the following command:

``` javascript
NuGet.exe pack ".\WithWPF\WithWPF.csproj" -Build -IncludeReferencedProjects -Properties Configuration=Release -NonInteractive -OutputDirectory ".\Output" -Verbosity detailed -MSBuildVersion 4
```

And got the following error:

``` javascript
Attempting to build package from 'WithWPF.csproj'.
Building project 'D:\Public\Nuget Pack Test\WithWPF\WithWPF.csproj' for target framework '.NETFramework,Version=v4.5'.
__________________________________________________
Project "D:\Public\Nuget Pack Test\WithWPF\WithWPF.csproj" (default targets):

__________________________________________________
Project "D:\Public\Nuget Pack Test\WithWPF\WithWPF.csproj" is building "D:\Public\Nuget Pack Test\WithWPF\zfkgp0ym.tmp_proj" (_CompileTemporaryAssembly target(s)):

Class1.cs(7,11): error CS1056: Unexpected character '$'
Done building project "zfkgp0ym.tmp_proj" -- FAILED.
NuGet.CommandLineException: Failed to build 'WithWPF.csproj'.
   at NuGet.CommandLine.ProjectFactory.BuildProjectWithMsbuild()
   at NuGet.CommandLine.ProjectFactory.BuildProject()
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath)
   at NuGet.CommandLine.PackCommand.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.BuildPackage(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

I've attached the test solution that I used to test this.  If you require anything else from me, please let me know.  
[Nuget Pack Test.zip](https://github.com/NuGet/Home/files/87257/Nuget.Pack.Test.zip)

**Comment by yishaigalatzer** [comment] 2016-01-18 19:41
Hey and thanks for reporting this issue.

The question is if you can compile your assemblies using msbuild from commandline. NuGet really just tries to run msbuild for you. msbuild 4 just loads the older compiler and the exception makes sense. I'm not sure why msbuild 14 fails for you, can you confirm it builds fine from command line?

**Comment by jc1001** [comment] 2016-01-21 11:00
Thank you for getting back to me.  I ran the following command on the attached solution (from first post):

```
"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\Temp\Nuget Pack Test\WithWPF\WithWPF.csproj" /p:Configuration=Release
```

It compiled successfully.  I've attached the command output.  If there are any other variations of MSBuild that you would like me to run (or anything else that I can try), please let me know.

[MSBuildSuccess.txt](https://github.com/NuGet/Home/files/99031/MSBuildSuccess.txt)

**Comment by sdemers** [comment] 2016-03-05 17:48
I had the same issue. One simple case to reproduce is to create a WPF application and execute "nuget pack <app>.csproj -Build". It's also reproducible with nuget-3.4.0-rc.

The workaround is to build the project with MSBuild first and then create the package with nuget.

**Comment by yishaigalatzer** [comment] 2016-03-05 23:59
We didn't get to touch this code yet. I'm assuming that what is going on is we always pick msbuild 4 for the packing scenarios which makes it pick an older version of c#

**Comment by jc1001** [comment] 2016-03-07 06:25
When verbose output is turned on, it does specify that it is using MSBuild version 14 (see original message above).  I also did manage to build a non-WPF project that uses new C# language features.  Not sure how much analysis is performed on the project file before packing though.  It may swop to another MSBuild version when it detects any WPF dependencies.

**Comment by yishaigalatzer** [comment] 2016-03-13 03:44
@rrelyea assigning to you because of your WPF expertise although this is a pack issue

CC @toddm

**Comment by rohit21agrawal** [comment] 2016-04-12 00:49
Appears to have been fixed already in dev branch:
Probably by this fix by @toddm: https://github.com/NuGet/NuGet.Client/commit/f2f89d45fb2f330a20cd79c2d7654f0cc50f7e4a

**Closed as completed by rohit21agrawal** 2016-04-12 00:49 UTC
Labels: Type:Bug, Functionality:Pack
