### ISSUE TITLE
Corrupt package in cache prevents future restores of package

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#1405] opened 2015-09-18 18:32 UTC
1. Create packages.config:
   <?xml version="1.0" encoding="utf-8"?>
   <packages>
   <package id="Newtonsoft.Json" version="7.0.1" />
   </packages>
2. Run "NuGet.exe restore -Source nuget.org -PackagesDirectory pkgs"
3. CTRL-C while package is restoring (note: a timeout/server error could cause this), or manually corrupt package after.
4. Run "NuGet.exe restore -Source nuget.org -PackagesDirectory pkgs"
   MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
   Restoring NuGet package Newtonsoft.Json.7.0.1.
   WARNING: Unable to find version '7.0.1' of package 'Newtonsoft.Json'.
   Unable to find version '7.0.1' of package 'Newtonsoft.Json'.
   Exception of type 'NuGet.CommandLineException' was thrown.

Note: Fiddler shows that the file starts downloading, but the (corrupt) file in the cache is not updated/replaced.

Also, is there a reason we don't download to a temporary file before renaming to the nupkg?

**Comment by yishaigalatzer** [comment] 2015-09-18 18:36
This is a known issue, not sure we are going to fix the "corrupt" state of package (because it is not well defined).

**Comment by zarenner** [comment] 2015-09-18 18:37
Ok, I thought it might be known but couldn't find the bug.  Can you link it from here so we can track it?  Thanks.

**Comment by zarenner** [comment] 2015-09-22 16:35
Hi @yishaigalatzer, is there any priority set on this bug?  It's pretty high on our team's priority list.  We'd be happy to take it if there isn't any bandwidth on your side.

**Comment by yishaigalatzer** [comment] 2015-09-22 16:52
It should be relatively high priority but not critical, if you want to send a PR, we will gladly take it.

Note that there are quite a few scenarios for fixing this issue properly.

**Comment by yishaigalatzer** [comment] 2015-10-01 02:07
Fixed with:
https://github.com/NuGet/NuGet3/commit/1b2bbafa99f6382375810f8b934922efe34d1126
https://github.com/NuGet/NuGet3/commit/00053876b86fd29b46bfdaccb76dfd5ceba7701b

Duplicate of https://github.com/NuGet/Home/issues/1157

**Closed as completed by yishaigalatzer** 2015-10-01 02:07 UTC
Labels: Priority:2, Type:Bug
