### ISSUE TITLE
Object reference not set to an instance of an object: when local path for nuget source is combined with protocolversion attribute,

### ISSUE THREAD

**Issue by voroninp** [NuGet/Home#13244] opened 2024-02-14 14:27 UTC
### NuGet Product Used

dotnet.exe, Visual Studio Package Management UI

### Product Version

8.0.2

### Worked before?

I do not know

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Here's nuget config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="fs" value="C:/NuGetPackages" protocolVersion="3" />
  </packageSources>
  <packageSourceMapping>
    <packageSource key="fs">
      <package pattern="*" />
    </packageSource>
  </packageSourceMapping>
  <packageRestore>
    <add key="enabled" value="True" />
  </packageRestore>
</configuration>
```

When I try to browse packages, I get this error:
> [fs] Object reference not set to an instance of an object.

![image](https://github.com/NuGet/Home/assets/9202028/399e0312-09bf-465a-8aa9-1e4260ea18c6)

Then I removed `protocolVersion="3"` and it helped. 

But it took me quite a while to understand what was causing the issue. 

Could you make the error message a bit friendlier, please?

**Comment by nkolev92** [comment] 2024-02-14 21:03
Duplicate of https://github.com/NuGet/Home/issues/3600

**Closed as not planned by nkolev92** 2024-02-14 21:03 UTC
Labels: Resolution:Duplicate, Type:Bug, Area:Settings
