### ISSUE TITLE
[Test Failure][Localization] Some strings are not localized when installing package in PMC

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4603] opened 2017-02-15 09:25 UTC
**NuGet Version:** VS.Redist.NuGet VS15.4.0.170213.1779
**VS Version:** D15Rel 26213.00 (select all languages and workloads)
**OS Version:** Windows 10 RS1_Release 14393.821.170127-1801

**Repro Steps:**
1.  Select CHS through ‘Tools -> Options -> International Settings’ and restart VS.
2.  Create a new C# Console Application via VS.
3.  Open the Package Manager Console window, type **‘install-package newtonsoft.json -version 9.0.1’** and hit enter.
4.  Check all the strings in PMC.

**Expected Result:**
1. The units ‘ms’ and ‘sec’ should be localized since same unit ‘ms’ is localized correctly as below screenshot (green line).
2. The string ‘GET’ should be localized.

**Actual Result:**
1. The units **‘ms’** and **‘sec’** are not localized as below screenshot (red line).
2. The string **‘GET’** is not localized as below screenshot (red line).
![unitnonlocalized](https://cloud.githubusercontent.com/assets/20632625/22967966/97bc5266-f3a3-11e6-9678-adc74eb8e487.png)
**Note:**
It repro for all languages.

**Comment by rrelyea** [comment] 2017-02-15 09:58
Please help us understand previous behavior.  Please compare with  vs 2015 update 3 behavior.

**Comment by v-luzh** [comment] 2017-02-16 06:06
We checked this issue on OS: Win10 RS1_Release CHS+VS 2015 U3 CHS, please refer to below screenshot.
1. There are no strings **'Gathering dependency information took 235.93 ms'**, **'Resolving dependency information took 0 ms'** and **'Executing nuget actions took 2.1 sec'** on VS 2015 U3, so they are new strings on VS 2017.
2. The string **'GET'** and the unit **'ms'** after the link are not localized on VS 2015 U3.
![4603dev14](https://cloud.githubusercontent.com/assets/20632625/23009447/f9521b70-f450-11e6-97fb-77c0d1850e63.png)

**Comment by mishra14** [comment] 2017-11-29 23:47
dupe of https://github.com/NuGet/Home/issues/4499

**Closed as completed by mishra14** 2017-11-29 23:47 UTC
Labels: Tenet:WorldReady
