### ISSUE TITLE
If one project contains errors, nuget.exe stops the restore of all new-style projects and only restores packages from packages.config (even when the project in question is itself an old-style project)

### ISSUE THREAD

**Issue by MikeRosoft** [NuGet/Home#7751] opened 2019-01-31 09:44 UTC
Scenario: I have a solution containing a number of projects, some of them being old-style csproj projects (packages in packages.config), others new-style (packages defined in csproj file itself). One of the projects is a Wix installer project (wixproj), which cannot be converted to the new style.

The Wix project references the NuGet package [Wix 3.11.1](https://www.nuget.org/packages/WiX/3.11.1), so that the project can be built on a build machine without needing to install Wix tools there.

Run `nuget restore` on the solution with Wix tools not installed locally, and Wix package not existing in solution packages directory. The error can also be simulated with Wix installed by directly editing the wixproj file and changing the following elements to a bogus path:

    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' AND '$(MSBuildExtensionsPath32)' != '' ">$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>
    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>

Observed behavior:
* nuget reports the following error: 
> C:\Work\Norway\Device-agents\DeviceAgentSetup\DeviceAgentSetup.wixproj(95,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> 
> WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
* Even though the failing project is an old-style project (and even though the build target is not at all relevant for package restoration), this error breaks package restoration for all new-style projects.

Expected behavior:
* If nuget encounters an error in one of the projects, it should ignore the error in old-style projects, and only skip that project in new-style projects. (Arguably, it should ignore missing build targets completely.)

Workaround:
* Run `nuget restore` separately on the wixproj project before running `nuget restore` on solution.

Tested with nuget version 4.9.2.5706

**Comment by MikeRosoft** [comment] 2019-02-12 08:08
I have enabled detailed logging, and got the following output on the command line:

> d:\workspace\DC\FI0053\DeviceAgents-sonar\DeviceAgentSetup\DeviceAgentSetup
> .wixproj(95,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.
> at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__52.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__47.MoveNext()
> WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.

**Comment by MikeRosoft** [comment] 2019-06-20 06:32
I believe that the reason why I was seeing this error is that the wixproj project was based on an old version of the project template (3.9 rather than 3.10). I have re-created the project using the most recent version of the Wix extension for Visual Studio 2017. So while the error is real, it will not affect the users under standard conditions.

The following lines:

    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' AND '$(MSBuildExtensionsPath32)' != '' ">$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>
    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>

do not appear in the 3.10 version of the project template.

**Comment by StingyJack** [comment] 2019-08-08 17:00
This happens with SSIS (dtproj) projects as well as web site projects that are not selected to be built as part of the solution configuration.

**Comment by zkat** [comment] 2020-04-20 20:45
This is a duplicate of some existing issues, so whoever gets this please investigate and close this issue appropriately.

**Comment by nkolev92** [comment] 2020-05-01 00:18
Closing as dup of https://github.com/NuGet/Home/issues/9035.

**Closed as completed by nkolev92** 2020-05-01 00:18 UTC
Labels: Resolution:Duplicate, Priority:2
