### ISSUE TITLE
Can the "Version "m.m.b.r-tag" does not follow semantic versioning guidelines. " Warning be suppressed

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#6438] opened 2018-01-15 13:33 UTC
Remove the content above here and fill out details below.

## Details about Problem

NuGet version (x.x.x.xxx): "NuGetPackager" tfs builld task v0.1.58

VS version (if appropriate): 2017

OS version (i.e. win10 v1607 (14393.321)): n/a

Worked before? If so, with which NuGet version: dunno, tired of seeing the warning

## Detailed repro steps so we can see the same problem

I'm tired of seeing this warning. Is there a parameter to suppress it?

```
WARNING: 1 issue(s) found with package 'Some.Common'. 
2018-01-15T13:23:25.8365958Z Issue: Use semantic versioning 
2018-01-15T13:23:25.8365958Z Description: Version "0.76.2.19-alphaGCI" does not follow semantic versioning guidelines. 
2018-01-15T13:23:25.8365958Z Solution: Update your nuspec file or use the AssemblyInformationalVersion assembly attribute to specify a semantic version as described at http://semver.org. 
 
2018-01-15T13:23:25.8521959Z Creating Nuget Arguments: ......

**Comment by PatoBeltran** [comment] 2018-01-17 17:42
Hey @StingyJack thanks for your feedback! Right now there is no way to suppress warnings in pack. We already have an issue tracking that feature https://github.com/NuGet/Home/issues/6026, please feel free to upvote it or add your concerns there.

As in for that specific warning, NuGet is SemVer compliant, so the easiest way to suppress that specific warning would be to change your versioning schema to follow semver. You can find more information at https://semver.org/

Closing this issue as a dupe of #6026

**Closed as completed by PatoBeltran** 2018-01-17 17:42 UTC
Labels: Resolution:Duplicate, Type:DCR, Functionality:Pack, Area:ErrorHandling

**Comment by PatoBeltran** [comment] 2018-01-17 19:01
@StingyJack I just realized you are talking about NuGetPackager. We don't own that one product (even though, after inspecting their project, it seems like they use our APIs) please refer to their GitHub page for specific questions about it https://github.com/Particular/NuGetPackager

**Comment by StingyJack** [comment] 2018-01-17 21:41
I'm talking about the build task that came with TFS 2015. I didnt install it separately.

**Comment by StingyJack** [comment] 2018-01-19 14:36
> the easiest way to suppress that specific warning would be to change your versioning schema to follow semver

i fail to see how changing 10+ years worth of built and deployed software that follows the .net framework 4 part versioning scheme is going to be easier than adding a warning suppression.

EDIT: You should not suggest this as the "easiest" thing to do, really. Whomever decided it was OK to try and coerce everyone into a new versioning scheme rather than a "default with possible opt out", needs to sit through a pharmaceutical industry validation effort once. I imagine many government and other critically tracked projects are hurting now as well from this decision, but the worst part by far is that it you all seem to have consumed the semver kool-aid.

**Comment by StingyJack** [comment] 2018-03-03 13:15
@PatoBeltran - The thing I'm talking about is a default task from TFS 2015.

And I dont need more information about this warning on screen, I need the warning to not display at all.
