### ISSUE TITLE
NuGet package signing on non-Windows

### ISSUE THREAD

**Issue by bruno-garcia** [NuGet/Home#7693] opened 2019-01-14 15:48 UTC
The [NuGet package signing docs](https://docs.microsoft.com/en-us/nuget/reference/signed-packages-reference) say:

> Package signing is currently supported only when using nuget.exe on Windows. Verification of signed packages is currently supported only when using nuget.exe or Visual Studio on Windows.

We've got a certificate for code signing as per the requirements but our tooling for publishing our packages unfortunately doesn't run on Windows. We don't want to upload the cert to a cloud CI service but rather prefer to sign the package on our own infrastructure.

Is there any plan or an ETA for supporting Linux? Or macOS?

I saw [this PR](https://github.com/NuGet/NuGet.Client/pull/2545) from @onovotny which would allow running it via .NET Core.

Would this be enough? If not, what else needs to be done to get this working on non-Windows.
Thanks!

**Comment by jainaashish** [comment] 2019-01-15 22:37
Yes, team is working towards enabling package signing and verification for non-windows platforms. dupe of #7606

**Closed as completed by jainaashish** 2019-01-15 22:37 UTC
Labels: Resolution:Duplicate
