### ISSUE TITLE
Floating versions with prereleases

### ISSUE THREAD

**Issue by matkoch** [NuGet/Home#5031] opened 2017-04-14 16:09 UTC
With the new csproj format I can write:

`<PackageReference Include ="ExamplePackage" version="1.4.*"/>`

But how can I define that prereleases should be included?

**Comment by bbowman** [comment] 2017-04-15 05:49
@emgarten seems like another *-* request. Can you comment on if this is in plan anytime soon?

**Comment by danielgreen** [comment] 2017-04-19 13:19
+1 for this.

Also seems to relate to #4099

**Comment by emgarten** [comment] 2017-05-09 07:03
Dupe of https://github.com/NuGet/Home/issues/912

**Closed as completed by emgarten** 2017-05-09 07:03 UTC
Labels: Resolution:Duplicate
