### ISSUE TITLE
Restore with packagesavemode -nupkg fails for json.net

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2706] opened 2016-05-03 03:32 UTC
Restore the following project.json

``` json
{
  "dependencies": {
    "Newtonsoft.json": "8.0.3",
  },
  "frameworks": {
    "net45": { }
    },
  }
}
```

with the following command:
C:\temp\repro>nuget restore project.json -packagesavemode nupkg
Restoring packages for C:\temp\repro\project.json...
  CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/8.0.3/newtonsoft.
json.8.0.3.nupkg
Installing Newtonsoft.json 8.0.3.
---> **Nuspec file does not exist in package.**

Repros also after clearing the cache
Version:3.4.3.855 (3.4.3 RTM)

**Comment by yishaigalatzer** [comment] 2016-05-03 03:34
@rrelyea potential 3.4.4 candidate

**Comment by rrelyea** [comment] 2016-05-03 16:44
On my machine, appears to be a regression from 3.3 nuget.exe

**Comment by spadapet** [comment] 2016-05-03 17:52
In 3.3, PackageSaveMode didn't work. The bug that fixed it was: https://github.com/NuGet/Home/issues/77
Now that the bug is fixed, the .nuspec file isn't saved to the cache, since the PackageSaveMode is nupkg.

I need to find which code is actually looking for the .nuspec and see why it's required.

**Comment by spadapet** [comment] 2016-05-03 18:07
The .nuspec is needed to get package dependencies for building the project.lock.json file.
In this case, even though the .nuspec is NOT there, the .nupkg is there and it does contain the .nuspec inside of it.

Two ideas:
1. Stop using "-PackageSaveMode nupkg" with project.json, they aren't compatible
2. I can change the code to look for the .nuspec inside of the .nupkg if the .nuspec isn't on disk

Here's the callstack when trying to find the .nuspec:

```
NuGet.Packaging.PackageFolderReader.GetNuspec
NuGet.Repositories.LocalPackageInfo.Nuspec.get
NuGet.Commands.LockFileUtils.CreateLockFileTargetLibrary
NuGet.Commands.LockFileBuilder.CreateLockFile
NuGet.Commands.RestoreCommand.BuildLockFile
NuGet.Commands.RestoreCommand.ExecuteAsync
```

**Comment by spadapet** [comment] 2016-05-03 20:55
Moving to 3.5 RC as per discussion with @rrelyea and @yishaigalatzer

**Comment by spadapet** [comment] 2016-05-10 17:59
The right fix seems to be throwing an error with:
    nuget restore project.json -packagesavemode nupkg
Because a restore of project.json can't work with only the nupkg, it needs the nuspec. The command should fail before doing any work.

@emgarten

**Comment by jainaashish** [comment] 2018-02-02 00:40
Working with latest release.

**Closed as completed by jainaashish** 2018-02-02 00:40 UTC
Labels: Type:Bug, Functionality:Restore
