### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Somethingcom515** [NuGet/Home#12601] opened 2023-05-19 07:44 UTC
### NuGet Product Used

Other/NA

### Product Version

i dunno

### Worked before?

no

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

 the NuGet Package Manager isn't showing up when i right click on the project in visual studio code

### Verbose Logs

```shell
i dunno
```

**Comment by jebriede** [comment] 2023-05-19 22:25
Hi @youmustp. According to the repro steps you provided, it appears you are trying to find the NuGet Package Manager in Visual Studio Code. The NuGet Package Manager is available in Visual Studio but does not exist on VS Code.

To find the NuGet Package Manager in Visual Studio, please follow the instructions on this page: https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio

I'm closing this as not a bug, but please reopen if you have further questions or more details to provide.

**Closed as completed by jebriede** 2023-05-19 22:25 UTC
Labels: Type:Bug, Resolution:NotABug
