### ISSUE TITLE
Can't install native package into two or more win32 projects in same solution

### ISSUE THREAD

**Issue by gordonwatts** [NuGet/Home#3256] opened 2016-08-01 04:50 UTC
This might be a duplicate of #1298, but I'm not 100% sure, so I thought I'd start here.

If you have two win32 projects in your solution, and you add try to add a package to both of them, nuget fails. If you add it to either one, you are fine - it is the act of adding the second one that fails. This might be a regression, in the sense it worked in 3.4.4 and does not in 3.5.
## To reproduce:
1. In VS Community, Update 3, with everything up to date
2. Create a new empty solution, add two C++ win32 console applications (call them bogus1 and bogus2, for example).
3. From solution line select "Manage nuget packages...", search nuget.org for the ROOT native package.
4. Select "bogus1" as the target, and install. Works fine.
5. Select "bogus2" as the target, and install. Fails with a "Could not install package 'ROOT 534.36.13'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."
6. Uninstall from bogus1, select bogus2, install. Works fine.
7. Select bogus1, install. Fails with the same error as above.

I have version 3.5.0.1484 of nuget installed according to the extensions and updates dialog box. Here is a complete log of the attempted installation when I selected two of my projects (selecting bogus1 and bogus2 at the same time, sorry they weren't actually named that).

```
Attempting to gather dependency information for package 'ROOT.534.36.13' with respect to project 'PlotSingleLimit', targeting 'native,Version=v0.0'
Gathering dependency information took 85.67 ms
Attempting to resolve dependencies for package 'ROOT.534.36.13' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'ROOT.534.36.13'
Resolved actions to install package 'ROOT.534.36.13'

Attempting to gather dependency information for package 'ROOT.534.36.13' with respect to project 'ExtrapolateByBeta', targeting 'native,Version=v0.0'
Gathering dependency information took 0.76 ms
Attempting to resolve dependencies for package 'ROOT.534.36.13' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'ROOT.534.36.13'
Resolved actions to install package 'ROOT.534.36.13'
Retrieving package 'ROOT 534.36.13' from 'nuget.org'.
Adding package 'ROOT.534.36.13' to folder 'C:\Users\Gordon\Documents\Code\calratio2015\Extrapolation\packages'
Added package 'ROOT.534.36.13' to folder 'C:\Users\Gordon\Documents\Code\calratio2015\Extrapolation\packages'
Added package 'ROOT.534.36.13' to 'packages.config'
Successfully installed 'ROOT 534.36.13' to PlotSingleLimit
Executing nuget actions took 300.44 ms
Found package 'ROOT 534.36.13' in 'C:\Users\Gordon\Documents\Code\calratio2015\Extrapolation\packages'.
Install failed. Rolling back...
Package 'ROOT.534.36.13' does not exist in project 'ExtrapolateByBeta'
Executing nuget actions took 11.33 ms
Could not install package 'ROOT 534.36.13'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========
Time Elapsed: 00:00:00.7735402
```
## Workaround

uninstall nuget 3.5.0.1484 and install 3.4.4.1321 (which is most up to date in the gallery). Given 3.4.4 is the most up to date that is sitting in the extension gallery, I'm not sure how I ended up with 3.5 on my machine. Perhaps it came down when I upgraded to update 3?

**Comment by rrelyea** [comment] 2016-09-07 00:43
please confirm that this is a regression and isn't fixed in later builds.

**Comment by zhili1208** [comment] 2016-09-07 17:45
verified this, it's a regression and still repro in latest 3.5-rtm build

**Comment by zhili1208** [comment] 2016-09-07 21:06
@gordonwatts Looks like 'ROOT.534.36.13' is a bad package, the build folder is under a "no name" folder, that's why nuget can't find it from zip. ROOT.534.34.13 works well.

**Comment by gordonwatts** [comment] 2016-09-10 17:33
This is embarrassing. I wasn't aware my automated packaging code had changed. I will investigate by Monday, when I have a real internet connection. Thank you for taking a look.

**Comment by rrelyea** [comment] 2016-09-15 19:51
@gordonwatts  - what did you find?

**Comment by rrelyea** [comment] 2016-09-21 00:47
Closing. Please chime in if our investigation missed something.

**Closed as completed by rrelyea** 2016-09-21 00:47 UTC
Labels: Type:Bug, Resolution:ByDesign, Functionality:Install
