### ISSUE TITLE
[Bug]: `nuget.exe packages.config -ExcludeVersion` does not install newer package versions

### ISSUE THREAD

**Issue by huangqinjin** [NuGet/Home#11017] opened 2021-07-11 08:41 UTC
### NuGet Product Used

NuGet.exe

### Product Version

5.10.0.7240

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

packages.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Newtonsoft.Json" version="12.0.3" />
</packages>

```

1. nuget install packages.config -ExcludeVersion
2. (Get-FileHash Newtonsoft.Json\Newtonsoft.Json.nupkg -Algorithm SHA256).Hash
    3D21CAF909F9DB2B5D13249D6728C2506C55E72E2123FBE2AF65A056C0A0BF9D 
3. Change version to 13.0.1 in packages.config
4. nuget install packages.config -ExcludeVersion

What I expected:
```shell
PS C:\Users\huangqinjin\Projects\test> (Get-FileHash Newtonsoft.Json\Newtonsoft.Json.nupkg -Algorithm SHA256).Hash
2B6B52556E27E1B7913F33EEDEB95568110C746BD64AFFF74357F1683878323A
```

What I got:
```shell
PS C:\Users\huangqinjin\Projects\test> (Get-FileHash Newtonsoft.Json\Newtonsoft.Json.nupkg -Algorithm SHA256).Hash
3D21CAF909F9DB2B5D13249D6728C2506C55E72E2123FBE2AF65A056C0A0BF9D
```
The hash is still same as 12.0.3.

### Verbose Logs

```shell
PS C:\Users\huangqinjin\Projects\test> Get-Content packages.config
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Newtonsoft.Json" version="12.0.3" />
</packages>
PS C:\Users\huangqinjin\Projects\test> nuget install packages.config -ExcludeVersion
Feeds used:
  C:\Users\huangqinjin\.nuget\packages\
  https://api.nuget.org/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  C:\Users\huangqinjin\Projects\NuGet

Restoring NuGet package Newtonsoft.Json.12.0.3.
Adding package 'Newtonsoft.Json.12.0.3' to folder 'C:\Users\huangqinjin\Projects\test'
Added package 'Newtonsoft.Json.12.0.3' to folder 'C:\Users\huangqinjin\Projects\test'
PS C:\Users\huangqinjin\Projects\test> (Get-FileHash Newtonsoft.Json\Newtonsoft.Json.nupkg -Algorithm SHA256).Hash
3D21CAF909F9DB2B5D13249D6728C2506C55E72E2123FBE2AF65A056C0A0BF9D
PS C:\Users\huangqinjin\Projects\test> Get-Content packages.config
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Newtonsoft.Json" version="13.0.1" />
</packages>
PS C:\Users\huangqinjin\Projects\test> nuget install packages.config -ExcludeVersion
Feeds used:
  C:\Users\huangqinjin\.nuget\packages\
  https://api.nuget.org/v3/index.json
  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  C:\Users\huangqinjin\Projects\NuGet

Restoring NuGet package Newtonsoft.Json.13.0.1.
Adding package 'Newtonsoft.Json.13.0.1' to folder 'C:\Users\huangqinjin\Projects\test'
Added package 'Newtonsoft.Json.13.0.1' to folder 'C:\Users\huangqinjin\Projects\test'
PS C:\Users\huangqinjin\Projects\test> (Get-FileHash Newtonsoft.Json\Newtonsoft.Json.nupkg -Algorithm SHA256).Hash
3D21CAF909F9DB2B5D13249D6728C2506C55E72E2123FBE2AF65A056C0A0BF9D
```

**Comment by zkat** [comment] 2021-08-16 20:43
duplicate of #11016

**Closed as completed by zkat** 2021-08-16 20:43 UTC
