### ISSUE TITLE
[Bug Bash] “Prerelease” tag shows for transitive packages when the “Include prerelease” checkbox is not checked

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12235] opened 2022-11-11 09:26 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.5.0.75

#### Details about Problem
VS Version: Main\33110.265
NuGet Version: Dev\6.5.0.75
OS Version: Windows-11-Enterprise-22H2 ENU

#### Repro Steps:
1.	Open VS, click menu File->New Project, create a C# Blank App (Universal Windows) project.
2.	Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
3.	Go to “Installed” tab and observe (please do not check the “Include prerelease” checkbox).
#### Expected:
“Prerelease” tag for transitive packages will not show because the “Include prerelease” checkbox is not checked.

#### Actual:
“Prerelease” tag shows for transitive packages when the “Include prerelease” checkbox is not checked as below.
![image](https://user-images.githubusercontent.com/20632625/201309183-0f4080ee-bdb0-485c-a824-8f1dbb9ca23d.png)

**Comment by nkolev92** [comment] 2022-11-17 19:36
Team Triage: The behavior for transitive dependencies matches the behavior for direct dependencies in both VS 2022 and VS 2019. 

![image](https://user-images.githubusercontent.com/2878341/202542035-848eb51c-a8fa-4a5f-b890-64db8fa7b6bf.png)

**Comment by nkolev92** [comment] 2022-11-17 19:36
Closing as by design.

**Closed as completed by nkolev92** 2022-11-17 19:36 UTC
Labels: Product:VS.Client, Type:Bug, Resolution:ByDesign, Functionality:VisualStudioUI, Triage:NeedsTriageDiscussion, Found:ManualTests
