### ISSUE TITLE
nuget configuration is invalid - ALL THE TIME

### ISSUE THREAD

**Issue by Owen37A** [NuGet/Home#2772] opened 2016-05-12 16:08 UTC
VS2015, New install on new, clean install of Windows 10 Pro. When opening a website project and selecting "Manage Newget project". Says there are no nuget projects (there ARE) and disables itself. Can't add or delete juget stuff.

When click on project and select manage nuget, says "nuget configuration is inavlid". Have googled the issue and nothing I've tried works.

**Comment by rrelyea** [comment] 2016-05-12 17:42
Sorry for break in 3.4.3

Dupe of #2667. Fix is available in 3.4.4-rc and will be shipping in final form within a week (POR).
(rc build is posted to http://dist.nuget.org/index.html)

**Closed as completed by rrelyea** 2016-05-12 17:42 UTC
Labels: Resolution:Duplicate, Type:Bug
