### ISSUE TITLE
Corrupt NuGet.config is ignored by nuget

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1567] opened 2015-10-13 23:45 UTC
example:

Create a console app
install jquery
Clean the packages folder

Drop the following content into a local nuget.config

```
<boo
```

run nuget.exe restore consoleapp.sln
## Expected

Fail or warn
## Actual

The invalid config is ignored and restore proceeds

Why does it matter?
Imaging the config file was pointing to a different repository, but it had a flaw where the XML was invalid. The restore will bring down incorrect packages or fail with a warning that the packages don't exist.

**Comment by yishaigalatzer** [comment] 2015-10-22 16:51
Consider warning also for files without a configuration section. e.g.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<packageSources>
  <clear />
  <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  <add key="azure" value="https://www.myget.org/F/azureadwebstacknightly/" />
</packageSources>
```

**Comment by csharpfritz** [comment] 2016-01-05 12:45
Looks like a duplicate of #1302 

Also reported on Twitter: https://twitter.com/devlead/status/684305178342731776

**Comment by yishaigalatzer** [comment] 2016-02-25 03:16
Summary: Any invalid config file that should be picked up, but fails to load should be turned into an error message that shows both in the UI and commandline (both nuget.exe and xplat). The error should be meaningful and point to the filename/file path and location in the file.

This should work both for the scenario where you pass in a -configFile or the config file is on disk, see https://github.com/NuGet/Home/issues/1302 for another repro scenario.

**Comment by zhili1208** [comment] 2016-03-04 01:37
it's fixed

**Closed as completed by zhili1208** 2016-03-04 01:37 UTC
Labels: Priority:2, Type:Bug
