### ISSUE TITLE
Build targets should be transitive across project-to-project references

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#3401] opened 2016-09-01 21:08 UTC
Build targets should also transitively flow across project-to-project graphs, in the same way that packages references do.

This means that:

Project -> Package Reference -> Package Reference (with targets)
Should have the same behavior as:

Project -> Project -> Package Reference (with targets)
For a few reasons:

This becomes consistent with references and copy local items from packages, which are also transitive.

This enables us to implement the ability to swap package references with project references with zero impact to the build. If targets are not transitive, this could result in different a build result because that package that was converted to a project reference no longer flows its targets that it used to inherit from any package references that it had.

From a user perspective, it's also very useful. I can reference a package like the Common Project System from our root core project, and all downstream projects also get the references. However, today I do not inherit build behavior - so as soon as I add a asset (in this case a XamlPropertyRule) that requires an MSBuild target, I must install the package into my downstream projects (which means that now that I need to upgrade them every time I install a new version of CPS).

I believe the push back previously was that some packages come with targets that might only be meant to apply to a single TFM, but if these are inherited might apply unexpectedly to additional TFMs (think UWP -> portable reference, or desktop -> portable reference). Given we're moving to the model of TFM-specific build targets - I believe that we should revisit this.

**Comment by rrelyea** [comment] 2016-09-01 23:04
cc @eerhardt
I think this needs to be part of a larger plan for package/project duality. unsure if it would land in vs "15", but we should design it, minimally.

putting it in 3.6 beta2 milestone for design, likely not implementation.

**Comment by elscript** [comment] 2017-05-29 19:10
Vote again and again for this great Feature!

**Comment by nkolev92** [comment] 2018-01-10 23:23
I will close this as a dupe of https://github.com/NuGet/Home/issues/6091. 

We want to change allow build assets to flow transitively. 

Due to the project/package duality, this would affect both packages and projects.

For existing packages it won't change anything however, as the dependency graph is already hardcoded in the nuspec.
So this wouldn't be a breaking change for old packages.

**Closed as completed by nkolev92** 2018-01-10 23:23 UTC
