### ISSUE TITLE
I get build error NU5012 and I'm not sure why, for sure not becouse my project does not build

### ISSUE THREAD

**Issue by PeterPann23** [NuGet/Home#9306] opened 2020-03-12 14:32 UTC
I have a project that I would like to have a nuget package for. The project builds and targets several frameworks. As the nuget package should include dependent files I thought I'd make a .nuspec file

when I run the package build I get an error:
![image](https://user-images.githubusercontent.com/44400822/76531905-2b15f800-6476-11ea-9343-3f980692202b.png)

Makes no sense as clearly the project builds, a Package deploy from VS works fine. 

Why is this error and how to I get my dependent files (not nuget) in the solution?

**Comment by kartheekp-ms** [comment] 2020-03-16 20:43
I believe this issue is a duplicate of #7765. If the solution posted doesn't help then reopen or create new issue [here](https://github.com/NuGet/Home/issues/new).

**Closed as completed by kartheekp-ms** 2020-03-16 20:43 UTC
Labels: Resolution:Duplicate, Functionality:Pack
