### ISSUE TITLE
[Test Failure] Package Reference executing delay in C# UWP project

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4740] opened 2017-03-03 09:17 UTC
**NuGet Version:** NuGet 4.3.0-beta1-2346 **(Insertable)**
**VS Version:** D15Rel 26228.00
**OS Version:** Windows 10 RS2_Release 15048.0.170228-1522

**Repro Steps:**
1.	New a Visual C#->Windows Universal->Blank App (Universal Windows).
2.	Right-click on the project and click ‘Manage NuGet Packages…’.
3.	Go to ‘Installed’ tab and verify there is a default installed package.
4.	Clicking ‘Reference’ expender to check if the default package exist.
5.	Then try to install package 'Newtonsoft.Json 9.0.1'.
6.	Clicking ‘Reference’ expender to check if the package ‘Newtonsoft.Json’ exist.

**Expected Result:**
The default installed package exist under the ‘References’ node in step 4 and the package ‘Newtonsoft.Json’ is added in the ‘References’ node in step 6.

Actual Result:
The default installed package not exist under the ‘References’ node in step 4, the package ‘Newtonsoft.Json’ is not added but the default package is added in the ‘References’ node in step 6 as below screenshot.
 
![56874111111111](https://cloud.githubusercontent.com/assets/20632775/23545050/9e53474a-0034-11e7-9d97-ed57c5ead19b.png)

Notes:
1. The issue repro on other Windows Universal projects.
2. The issue **not repro** on **D15Rel 26228.00 (NuGet 4.0.0-rtm-2323)** and **D15Rel 26228.00 + NuGet 4.1.0-rtm-2343.**

**Comment by emgarten** [comment] 2017-03-03 20:51
Dupe of https://github.com/NuGet/Home/issues/4739

**Closed as completed by emgarten** 2017-03-03 20:51 UTC
