### ISSUE TITLE
Default tab selection on Manage NuGet Packages

### ISSUE THREAD

**Issue by meokullu** [NuGet/Home#13694] opened 2024-08-12 11:19 UTC
### NuGet Product(s) Affected

Visual Studio Package Management UI

### Current Behavior

Default tab selection is "Installed" while there are Browse, Installed and Updates tabs on fresh created empty project.
![Screenshot 2024-08-12 141420](https://github.com/user-attachments/assets/bd417e4c-99c6-4455-acd5-429d96a347fa)

### Desired Behavior

Default tab should be selected "Browse" instead of Installed on fresh created empty project.

### Additional Context

Thousands of users use NuGet. A few seconds of UI improvements may result saving time, energy thus leads greener world.

**Comment by jeffkl** [comment] 2024-09-09 21:11
Duplicate of https://github.com/NuGet/Home/issues/7309

**Closed as not planned by jeffkl** 2024-09-09 21:11 UTC
Labels: Priority:3, Type:DCR, Functionality:VisualStudioUI
