### ISSUE TITLE
Nuget restore takes file locks even when no need to install package.

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2324] opened 2016-03-15 20:32 UTC
NuGet Version: 3.4.0.738

Scenario:
Project A and Project B build in parallel.  They each contain a packages.config which has the same nuget packages listed.
Project A invokes nuget restore on it's packages.config even though the packages are installed nuget takes exclusive locks on the file content (I am speculating it is simply re-writing over the packages files).
At the same time Project A is locking the already installed files in the packages folder on the disk Project B tries to build and then blows up with access denied to the files that are being locked by project A.

Perhaps nuget restore can do a hash check (aka read operation) or something else to determine if it needs to write to the package folder instead of always rewriting making it a problematic tool to use in builds.

**Comment by yishaigalatzer** [comment] 2016-03-15 21:48
@kingerja can you please share more detailed scenario?

Is this in visual studio or nuget.exe?

**Comment by kingerja** [comment] 2016-03-15 22:35
This is nuget.exe

**Comment by joelverhagen** [comment] 2016-03-16 01:56
Could you provide the error message? Also, are Project A and Project B sharing the same solution packages folder? At face value, this seems like an unsupported scenario. You should always wait for a restore (to a specific solution packages folder) to complete before building.

**Comment by kingerja** [comment] 2016-03-16 04:20
we use a traversal project.  (msbuild project that just invokes the msbuild task to build in parallel various projects. We don't use sln files.)  So many msbuild projects will be running at any given time and running nuget and any given tool from a nuget package at any given time.  The nuget packages for those projects are installed using nuget restore every time a project is built as well as the packages from our toolset packages.config (think our global build toolset nuget packages).  In the past we relied on nuget install to no op if a package was already installed.  But now when other utilities try to access the bits in the nuget package folder if nuget restore happens to be running it will fail causing access denied on those tools.  We also see it where the tool beats nuget and takes a read lock on those files because that tool in the nuget package is executing and then nuget tries to write to the file giving 'The process cannot access the file' error as well.

Now a long time ago in the 2.x codebase gregoryv add a synchronization fix to nuget.exe where if multiple instances of nuget.exe were trying to install the same package at the same time it would cause an issue.  I assume when you ported forward that this fix was taken but if not you may want to consider that scenario in your quest for a repro.

If you need me to run an instrumented version of nuget.exe let me know getting a repro in one of my builds will be possible.  (joshking@microsoft.com) 
I will be on vacation for a week starting tonight but I will likely see and respond to any bang mail sent to me.

**Comment by kingerja** [comment] 2016-03-16 13:05
Here are some simple repro steps.
1.  run nuget restore on \joshking-main\dump\nugetissue\2324\packages.config
2.  Open tools\odd.exe  in the package that was installed Microsoft.Odd.SQLIS.2.7.1.2
3.  run nuget restore on \joshking-main\dump\nugetissue\2324\packages.config

you get.
WARNING: The process cannot access the file 'd:\NuGetPackages\Microsoft.Odd.SQLIS.2.7.1.2\tools\Odd.exe' because it is being used by another process.

Errors in packages.config projects
    The process cannot access the file 'd:\NuGetPackages\Microsoft.Odd.SQLIS.2.7.1.2\tools\Odd.exe' because it is being used by another process.

**Comment by joelverhagen** [comment] 2016-03-16 18:44
The package you mentioned is not available on NuGet.org so I was unable to find it. Would it be possible for you to provide a self enclosed project (maybe in a .zip) that reproduces the problem? I tried simulating the problem. I keep seeing that NuGet recognizes that a package is already restored and therefore does not touch touch the files.

```
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
All packages listed in packages.config are already installed.
```

Here's what I am trying (just run `run.bat` under the `ConsoleApplication1` directory): [ConsoleApplication1.zip](https://github.com/NuGet/Home/files/176653/ConsoleApplication1.zip)

If you could provide something similar that simulates the problem, that would be most helpful! Enjoy your vacation :smile:.

**Comment by kingerja** [comment] 2016-03-17 10:36
do you have access to the Microsoft corp net?  If so those paths i listed should be valid for you to get the package from.

If not then i will attach a zip for you.

**Comment by joelverhagen** [comment] 2016-03-17 15:48
I tried the same thing with Odd. I cannot reproduce because NuGet detects that the package is already restored:

```
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
All packages listed in packages.config are already installed.
```

**Comment by kingerja** [comment] 2016-03-17 19:50
hmmm i see this on our build agents on my machines and have had many reports of it.  Would it help if I provided a machine with a repro?  If so i can try to get something for you much later tonight when i am back to my hotel.

**Comment by joelverhagen** [comment] 2016-03-17 23:12
Even better than a machine with a repro would be a project (with no dependency on your own build environment) that reproduces the problem. But it that is not achievable, a machine would help.

**Comment by kingerja** [comment] 2016-03-25 02:25
Sorry for delay I couldn't get network access.
Here is a contained repro.
\joshking-main\dump\nugetissue\2324\repro

run 'msbuild /m dirs.proj'

If that doesn't repro it for you let me know and I can give you a build agent you can run the contained repro on.
If you don't already have access to our vso projects then you simply need request access to the ramweb project 13460.
Feel free to IM me at joshking@microsoft.com for more info or if you can't get the repro to work/access issues.

**Comment by joelverhagen** [comment] 2016-03-25 19:33
I see, I was able to reproduce the problem. There seems to be a bug in how we detect if a package is already installed. 

I noticed that in your `NuGet.config` file you have the following entry:

``` xml
<add key="PackageSaveMode" value="nuspec" />
```

To work-around the problem, change the mode to `nupkg`:

``` xml
<add key="PackageSaveMode" value="nupkg" />
```

Here is a bug tracking this problem: https://github.com/NuGet/Home/issues/2402

**Comment by kingerja** [comment] 2016-03-27 19:08
we need the nuspec for lca validation.  what about if i set it to nupkg;nuspec.  will that work.  I would rather waste disk space instead of exposing my code base to consuming packages they are not licensed for.   Otherwise i will pull all my packages up front and no-op the nuget restore process using custom logic until there is a fix.

anyway glad you got a repro.

**Comment by joelverhagen** [comment] 2016-03-28 15:22
Yes, as long as the nupkg is dropped in the packages folder, the restore command will properly identify that the package already exists. To be clear, set this in your `NuGet.config`:

``` xml
<add key="PackageSaveMode" value="nuspec;nupkg" />
```

Let me know if this solves your build issue and we can close this particular bug. Keep an eye on https://github.com/NuGet/Home/issues/2402 for progress on the root cause.

**Comment by kingerja** [comment] 2016-03-28 20:38
Thanks for the work around I will apply it and let you know how it goes.  Initial testing points to the work around being effective but I won't know if it is complete until it rolls out to my different codebases.  You are free to close this issue though and will follow up if I run into any future issues.

**Closed as completed** 2016-03-28 21:04 UTC
Labels: Type:Bug, Product:NuGet.exe
