### ISSUE TITLE
Non-Sdk solution not restoring all nuget packages on VS 2019 IDE

### ISSUE THREAD

**Issue by alfredo-pozo** [NuGet/Home#10261] opened 2020-11-12 21:44 UTC
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 5.7.0.6726

dotnet.exe --version (if appropriate):

VS version (if appropriate): 16.8.1

OS version (i.e. win10 v1607 (14393.321)): Microsoft Windows [Version 10.0.19041.572]

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

Recently, we migrated our solution  from packages.config to packagerefences, after that, we can't get a successful build using only VS IDE 2019, because of the missing NuGet packages, on the logs we discover that only 21 projects from a total of 55 are restored.

1. Clone the repository https://github.com/DynamoDS/Dynamo using packagerefence branch

2. Open src/Dynamo.All.sln on VS 2019 IDE

3. Build solution (Debug|Release/AnyCPU) **or** 

3. Restore NuGet packages

4. Build Solution 

...

## Other suggested things

In order to get a successful build of the solution, we need to do this steps :

With VS 2019 IDE

1. Clone the repository https://github.com/DynamoDS/Dynamo using packagerefence branch

2. Open a Dev Command Prompt for VS 2019 and execute: nuget.exe restore src/Dynamo.All.sln

3. Open src/Dynamo.All.sln on VS 2019 IDE

4. Build solution (Debug|Release/AnyCPU)

Command Line

1. Clone the repository https://github.com/DynamoDS/Dynamo  using packagerefence branch

2. Open a Dev Command Prompt for VS 2019 and execute this commands: 

```
nuget.exe restore src/Dynamo.All.sln

msbuild /t:restore src/Dynamo.All.sln

msbuild src/Dynamo.All.sln
```

### Verbose Logs

[VSIDERestore.log](https://github.com/NuGet/Home/files/5533392/VSIDERestore.log)

### Sample Project

https://github.com/DynamoDS/Dynamo/tree/packagerefence

**Comment by GKG4** [comment] 2020-11-17 17:05
I am also facing the same issue, I thought its only me, but glad to know its a bug, hopefully, a patch will be released soon.

**Comment by nkolev92** [comment] 2021-12-03 00:30
Hey @alfredo-pozo 

Looking at your project setup, there are conditions that are different depending on the context that just can't be resolved in every scenario. 

A few things: 

1. Consider removing all custom imports of NuGet intermediate targets: obj\Analysis.csproj.nuget.g.props and the likes.
1. For example, some of your props/targets such as cs.props can't be loaded because they depend on SolutionDir. Consider referencing paths relative to the project files *not the SolutionDir property. 
1. I see in your branch, you're setting BaseIntermediateOutputPath which changes that MSBuildProjectExtensionsPath. That's the primary difference between commandline and VS. 


Note that you shouldn't need to do `msbuild /t:restore `and nuget.exe restore. 

Nuget.exe has always done both PackageReference and packages.config, but now msbuild /t:restore can do certain types of packages.config with `/p:RestorePackagesConfig=true`. 

@GKG4 If you're running into a problem please file a different issue. 

We're dealing with an involved repro here that I don't really have high confidence that it'll be the same as yours. 

All that being said, unfortunately I'm gonna close this as not a bug given the project authoring.

**Closed as completed by nkolev92** 2021-12-03 00:30 UTC
Labels: Priority:2, Functionality:Restore, Resolution:NotABug

**Comment by mjkkirschner** [comment] 2021-12-03 04:31
@nkolev92 thank you for investigating.
