### ISSUE TITLE
nuget.exe "pack" command dependency problem.

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#338] opened 2015-04-01 21:29 UTC
@hikalkan

I have an issue. I will write a sample situation to explain the problem:

This is my sample command to create a nuget package named Abp:

"..\src.nuget\NuGet.exe" "pack" "..\src\Abp\Abp.csproj" -Properties Configuration=Release -IncludeReferencedProjects -Symbols

It automatically finds packages.config and create dependencies of Abp package. In package.config, it depends on:

<package id="Castle.Core" version="3.3.1" targetFramework="net451" />
<package id="Castle.LoggingFacility" version="3.3.0" targetFramework="net451" />
<package id="Castle.Windsor" version="3.3.0" targetFramework="net451" />
<package id="Microsoft.Bcl.Immutable" version="1.0.34" targetFramework="net451" />

But it does not include dependency for Castle.Core and Castle.Windsor since they are depended also by Castle.LoggingFacility (See http://www.nuget.org/packages/Abp).
But it's a problem because of depended versions. Castle.LoggingFacility depends on Castle.Core 3.3.0 but Abp depends on 3.3.1.
When I install Abp to my project, it gets Castle.Core 3.3.0 instead of 3.3.1 required by Abp.

It should explicitly set all dependencies of Abp.

Another example situation:

A may depend on B and C, B also may depend on C. Then it does not include C as dependency of A. But what if B drops dependency of C later? When I include A to my project, it will not include C. This is really buggy.

Please, at least provide an option to include all dependencies of the package.

**Comment by matt-sullivan** [comment] 2015-05-01 07:02
Hi @deepakaravindr,

I was thinking about taking a look into this issue, but I noticed there's an outstanding issue assigned to you (#44) that says pack is not implemented at all.

This issue is impacting me on nuget 2.8, and I have briefly looked at the source for that. I haven't tried nuget 3 yet. Would I be better off trying to fix this on the 2.8 or 3 branch? Which is likely to make it into a release sooner?

Cheers,
Matt

P.S. Is there a mailing list to ask these sorts of questions, now the codeplex ones are deprecated?

**Comment by deepakaravindr** [comment] 2015-05-01 18:31
I would ignore issue #44 ... For more information, talk to @yishaigalatzer ... Thanks!

**Comment by feiling** [comment] 2015-05-01 21:14
`nuget pack` without nuspec only handles basic scenarios. For complicated cases like this, the user needs to create the nuspec file, then they can have full control of the package creation.

**Comment by hikalkan** [comment] 2015-05-02 09:01
Hi @feiling,

I don't think that is a complicated case. It's basic usage of nuget: library dependency management. nuget pack command should add dependencies upon my package.config. Managing own nuspec file is hard.

**Comment by davidfowl** [comment] 2015-05-02 09:39
NuGet pack from a csproj will never work well when trying to recreate dependencies from a packages.config. I'd suggest that we don't bother trying to fix it. The only way to figure out the dependencies is by having them explicitly stated somewhere. 

With NuGet v3 we'll split what got installed from what your application directly depends on so that this is more doable.

**Comment by hikalkan** [comment] 2015-05-02 09:45
Thanks @davidfowl 
That was the problem. I directly depend on the package B. But since depdency A also depends on a lower version of B, nuget pack can not understand the fact: I need to depend on a higher version of B.

I would be happy if you fix it in this version, but it's OK.

**Comment by yishaigalatzer** [comment] 2015-05-02 17:42
Like David says correctly we are not going to fix this, and recommend that you use a nuspec.

Nuget v3 is not going to support this at RTM either, this is something that will be supported potentially at later releases. But when things get complex you still are responsible to provide your own nuspec. It is not that hard at the end of the day.

**Closed by yishaigalatzer** 2015-05-02 17:42 UTC

**Comment by matt-sullivan** [comment] 2015-05-04 06:02
@yishaigalatzer,

I understand there will always be circumstances where nuget (v2) cannot infer what packages the user explicitly installed. However, isn't the @hikalkan scenario clearly a bug? (I.e. installing the package built by nuget can result in earlier versions of some dependencies being installed.)

I've made a change to test the version of the nested dependency before removing dependencies from the project. Are there circumstances I haven't thought of that this will cause problems for?

You can find the changeset here: 0cea29683f291cd098e99c8233da86cf8cff90fc .  I haven't written any tests for this, but would be happy to do so if you would consider accepting it.

Cheers,
Matt

**Comment by yishaigalatzer** [comment] 2015-05-04 07:37
If you installed both the package built with pack and the dependent packages you should get the correct versions. I didn't see that in the report. Do you have a repro for this scenario?

If this is just about packing I'm not so sure we want to go down this rabbit hole. We recommend authoring your own nuspec at that point.

The main issue with such changes is just like you suggest: What are the other side effects of this change. If you are still interested I would start by building and extensive set of test cases, both of pack and install scenario to make sure no regressions are introduced. You will want to fork from codeplex (not from haacked/github) and we can take another look. This will also will need to be reflected in nuget3 after it is done for NuGet 2.

Let us know if you are interested in pursuing this further and I can chat more with the team tomorrow.

**Comment by davidfowl** [comment] 2015-05-04 07:45
> The main issue with such changes is just like you suggest: What are the other side effects of this change.

@matt-sullivan  If you can show that it only affects this very very very narrow use case and doesn't cause any regressions. It'll be an easier sell.

**Comment by matt-sullivan** [comment] 2015-05-04 12:37
Sorry if I wasn't clear, the issue is only during packing.

Given a project (Abp) that depends on Castle.Core 3.3.1 & Castle.LoggingFacility 3.3.0, and that Castle.LoggingFacility 3.3.0 depends on Castle.Core 3.3.0.

When you nuget pack Abp.csproj the resulting package will only depend on Castle.LoggingFacility 3.3.0. It should also depend on Castle.Core 3.3.1 to supply the reference Abp.dll was compiled against.

My proposed change would only affect nuget pack for project files, and only if the version installed in the project is different to the minimum version of the dependency between referenced packages. The maximum behaviour change is that it may explicitly include extra dependencies where those dependencies would have previously only been resolved/included at install time.

The only potential impact I can think of is if the package consumer is using a newer version of a first level dependency and that newer version no longer depends on the explicitly referenced dependency. E.g. Castle.Logging 3.4 depends on a Castle.ReplacementCore. (Users impacted by the buggy scenario would also be affected, but presumably for the better.)

I can't speak for others, but I'm using nuget to publish artifacts from one solution to another within my company. I have only one target framework and rarely have to edit the nuspec. I'm reluctant to switch to nuspec based packing because I like that a developer can add/update a nuget package and have it automatically updated in downstream projects. Editing the nuspec is just another thing we could forget to do.

Cheers,
Matt

**Comment by toddm** [comment] 2016-04-19 17:02
This is being fixed with https://github.com/NuGet/Home/issues/2376
