### ISSUE TITLE
[Bug]: Visual Studio 2019 can't find private Artifactory NuGet package

### ISSUE THREAD

**Issue by MartinBarkerPhilips** [NuGet/Home#11796] opened 2022-05-06 14:49 UTC
### NuGet Product Used

MSBuild.exe, NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

visual studio 2019

### Impact

I'm unable to use this version

### Repro Steps & Context

Download nuget for the Win10 command line. 
Download Visual Studio 2019.
Setup a JFrog Artifactory repo online.

Recently I used Visual Studio to package a NuGet `.nupkg` file, and then used the following commands to push my .nupkg file to a private artifactory repo:
```
$ nuget sources Add -Name Artifactory -Source https://myurl/artifactory/api/nuget/ult-testware-nuget -username aaaaaa -password bbbbbb
$ nuget setapikey aaaaaa:bbbbbb -Source Artifactory
$ nuget push ClassLibrary2.1.0.0.nupkg -Source Artifactory
```
I can verify that it was uploaded and is visible online:
[![enter image description here][1]][1]

My private artifactory url is added to vscode as a NuGet source:
[![enter image description here][2]][2]

But when I try to browse for NuGet packages using that source, I get no results. Even with prerelease checked, and after refreshing/restarting VS, [![enter image description here][3]][3]

Do I need to re-authenticate Visual Studio with my private JFrog Artifactory repo somehow? I'm hoping to see and download the NuGet package I just pushed up.

I also tried adding to my NuGet.Config file another NuGet source:
```
    <add key="ArtifactoryNuGetV3" value="https://myurl/artifactory/api/nuget/v3/ult-testware-nuget" protocolVersion="3" />
  </packageSources>
```
But that does not work.

One of the artifactory source urls I added links to my repo, and when I selected it to browse, I get a popup asking for username/password. After entering I get an error saying 404 (so I think the auth was a success, but its searching for my package in the wrong place)
```
[artifcator2] The V2 feed at 'https://myurl/artifactory/ult-testware-nuget/ClassLibrary2.1.0.0.nupkg/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='netcoreapp3.1'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '404 '.
```
If I remove everything from the url so it is just ```https://myurl/artifactory/ult-testware-nuget/ClassLibrary2.1.0.0.nupkg/``` and look it up in my browser, it either shows 
``` 404: "{\"error\":\"Expected a folder but found a file, at: ult-testware-nuget:ClassLibrary2.1.0.0.nupkg\"}" ``` or If I remove the last slash it begins to download

Thanks

  [1]: https://i.stack.imgur.com/AA7m3.png
  [2]: https://i.stack.imgur.com/kg7nq.png
  [3]: https://i.stack.imgur.com/cJyjw.png

**Comment by slang25** [comment] 2022-05-06 15:12
We use Artifactory at my workplace, when we use it, there is a v3 in the url path after nuget part, so `https://..../artifactory/api/nuget/v3/your-feed`, I think you'll need this to get the v3 protocol.

**Comment by slang25** [comment] 2022-05-06 15:13
Ah, I see further down in your explanation that you've tried that in the `NuGet.config`, I was going on the screenshot

**Comment by MartinBarkerPhilips** [comment] 2022-05-06 15:26
One question i was wondering, when I get this popup in Visual Studio, I should enter my password as cleartext and not the longer/encyrpted version seen online in the artifactory tutorial yes? 
![image](https://user-images.githubusercontent.com/99444148/167163816-b0725ef6-7b95-444f-9d3c-c57600c4da65.png)

**Comment by MartinBarkerPhilips** [comment] 2022-05-06 15:27
interestingly now n Visual Studio I am getting this error
```

[artifcator2] Unable to load the service index for source https://artifactory-myurl.com/artifactory/ult-testware-nuget/ClassLibrary2.1.0.0.nupkg.
  The ServicePointManager does not support proxies with the https scheme.
```

**Comment by MartinBarkerPhilips** [comment] 2022-05-06 15:56
I am using cisco anyconnect on my pc, maybe I need to set nuget http_proxy ?

**Comment by MartinBarkerPhilips** [comment] 2022-05-06 16:58
But I've tested on a desktop without a vpn and faced the same issue

**Comment by dominoFire** [comment] 2022-05-12 17:47
@MartinBarkerPhilips Can you try this in VS 2022 and using v3 Artifactory feed? I recently did a repro with a free Jfrog account and found no issues.

**Comment by zivkan** [comment] 2022-06-02 18:37
We are closing this issue since we didn't hear back from you, but definitely let us know if you can still reproduce this problem on the latest version of NuGet. Thank you for your feedback and happy coding!

**Closed as completed by zivkan** 2022-06-02 18:37 UTC
Labels: Type:Bug, Functionality:VisualStudioUI
