### ISSUE TITLE
pack with NoDefaultExclude and nuspec file exclusion conflict

### ISSUE THREAD

**Issue by golayp** [NuGet/Home#2847] opened 2016-05-25 09:29 UTC
Hi I'm trying to pack a project cloned from a git repo and have a issue.

My project contains some files starting with a dot(like .htaccess).

I would like to prevent my package having git related files and folder like .git at root location and some .gitignore files around but still keeping my .htaccess and ohter needed dot-starting files.
My first thought is to use **-NoDefaultExcludes** to include needed files and add a nuspec file exlusion to remove .git folder and .gitignore files:

`<file src="**\*" target="" exclude="**\.gitignore,.git" />`

Trying to pack with option -NoDefaultExclude doesn't exlude what specified in nuspec
Trying to pack without option -NoDefaultExclude doesn't incude needed dot-starting files.

I include a zip project containing a working example

[testnupack.zip](https://github.com/NuGet/Home/files/281424/testnupack.zip)

**Comment by emgarten** [comment] 2017-12-19 23:00
Duplicate of https://github.com/NuGet/Home/issues/3994

**Closed as completed by emgarten** 2017-12-19 23:00 UTC
Labels: Resolution:Duplicate, Priority:3, Functionality:Pack
