### ISSUE TITLE
Default scroll position in package list hides best search result

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#12288] opened 2022-12-01 20:16 UTC
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

33129.541.main

### Worked before?

17.4

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

The Package Manager UI's left listbox begins life scrolled down so that the most relevant hit is invisible! I've wondered for days what made the most obvious hit so hard to find in the search results, and only today finally figured out it was because the default scroll position hides the best result! 

![nugetscrolling](https://user-images.githubusercontent.com/3548/205150739-4e09e262-0833-4190-be03-30f4228e531c.gif)

**Comment by kartheekp-ms** [comment] 2022-12-02 02:56
Thank you for taking the time to report this issue. It appears to be a duplicate of https://github.com/NuGet/Home/issues/12160

**Closed as completed by kartheekp-ms** 2022-12-02 02:56 UTC
Labels: Resolution:Duplicate, Product:VS.Client, Type:Bug, Functionality:VisualStudioUI
