### ISSUE TITLE
Error occurred while restoring NuGet packages: The operation failed as details for project ClassLibrary1 could not be loaded.

### ISSUE THREAD

**Issue by paiden** [NuGet/Home#8813] opened 2019-11-13 06:21 UTC
## Details about Problem

Open attached solution in Visual Studio
and try to compile it. It will create an error message during build
'Error occurred while restoring NuGet packages: The operation failed
as details for project ClassLibrary1 could not be loaded.'

The reason is that it has two targets and a assembly name that changes
depending on target version. This causes an InvalidOperationException
in VsNominationUtilities ~Line 300:
`GetNonEvaluatedPropertyOrNull(values, propertyName, valueFactory).SingleOrDefault()`
that is invoked by 
`internal static string GetPackageId(ProjectNames projectNames, IEnumerable tfms)`
as two package ID's are resolved (one for each assembly name).

This further causes that no restore entry is created in the project
system cache and then will cause this build error.

- NuGet product used: Visual Studio build with package restore enabled
- Worked before? If so, with which NuGet version: Don't think so.
- VS version (if appropriate): Version 16.4.0 Preview 4.0

## Detailed repro steps so we can see the same problem

1. Open attached solution in Visual Studio
1. build
1. See build output

## Other suggested things
A workaround is to set an explicit 'PackageId' for ClassLibrary1.
But it took me one day of debugging the NuGet extension to find that IMO workaround.

So some fix, or at least better log output when the cache entry cannot be created would
be nice. If i saw correctly, the exception during cache creation is simply swallowed
(at least in normal builds without special logging enabled etc.) and
and creates followup issues later. Very annoying.

### Sample Project
[ConsoleApp27.zip](https://github.com/NuGet/Home/files/3839653/ConsoleApp27.zip)

**Comment by nkolev92** [comment] 2019-11-14 01:37
Thanks for filing this. 
Duplicate of https://github.com/NuGet/Home/issues/8456.

**Closed as completed by nkolev92** 2019-11-14 01:37 UTC
Labels: Resolution:Duplicate, Type:Bug, Functionality:Restore, Style:PackageReference
