### ISSUE TITLE
Error while restoring NuGet packages with HRESULT 0x8004C738

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4326] opened 2017-01-19 02:09 UTC
I've a classic csproj with PackageRef which depends on a net standard library. Restore throw error:

`Error occurred while restoring NuGet packages: Exception from HRESULT: 0x8004C738`

Sample solution attached:
[ClassLibrary2.zip](https://github.com/NuGet/Home/files/715523/ClassLibrary2.zip)

**Comment by zhili1208** [comment] 2017-01-20 00:36
the issue here is not related to net standard library, a classic csproj with PackageRef and ProjectRef always hit this issue. the root cause is from https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/EnvDTEProjectAdapter.cs#L346

nuget is trying to get all assert metadata from project references, if any assert(IncludeAssets, ExcludeAssets, PrivateAssets) metadata is not there, it will throw. 

@jainaashish mentioned in his PR https://github.com/NuGet/NuGet.Client/pull/1058, this will not throw if there aren't any metadata last month, so I think it looks like a reference6.GetMetadata() API breaking change.

**Comment by zhili1208** [comment] 2017-01-20 21:34
I wrote a test vsix project which access the reference6 API, it will repro this issue.

Repro Steps:
1. Create a test solution which contains two .net framework project: classLibrary1, consoleApp1
2. consoleApp1 reference classLibrary1.
3. build and run the test vsix project in VS experience instance.
4. open the test solution and click invokeCommand1 from tools.

It will get Hresult exception.

Test Vsix Project:  

[VSIXProject2.zip](https://github.com/NuGet/Home/files/720553/VSIXProject2.zip)

**Comment by rrelyea** [comment] 2017-01-23 22:19
@zhili1208  - can you try the repro case in vsfeedback item 744468 -- to see if that is the same exception message.
(note - once you choose tools/options, after the steps above, you can crash)

**Comment by zhili1208** [comment] 2017-01-23 22:24
checked the exception message and call stack, it's the same issue

**Comment by rrelyea** [comment] 2017-01-24 00:17
tracking internal bug on partner team: 372804:legacy csproj project with packagereference and projectreference will throw hresult during restore

**Comment by brian-pickens** [comment] 2017-01-30 14:08
Since I can't comment on the internal bug, this is happening in Visual Studio 2017 build 4.6.01038 with Nuget 4.0.0 when simply creating a new .Net Core web app. The error is thrown when I try to open the Nuget Package Manager GUI.

**Comment by vRITHNER** [comment] 2017-01-30 18:24
Hello Guys,  somebody closed my reported issue and decided my issue was a duplicate of your's; as it is closed, I can't comment. https://developercommunity.visualstudio.com/content/problem/15458/0x8004c738-when-trying-to-update-nuget-packages-in.html

My issue was related to a legacy MVC project and has nothing to do with a dotNET core;
They wrote there is a solution but I can't find it here...

Anyone who can explain what is the status on this issue ?
Thanks and cheers
-Vince

**Comment by zhili1208** [comment] 2017-01-30 18:55
@vRITHNER actually this issue is related to a legacy c# project which is using package reference. the fix is already merged last Friday.

**Comment by vRITHNER** [comment] 2017-01-30 23:42
Txs @Zhi, but I already installed last update.
Sent from my Windows 10 phone

**Comment by zhili1208** [comment] 2017-02-06 19:38
validated it with VS 26205 and nugget 4.0.0.2275

**Closed as completed by zhili1208** 2017-02-06 19:38 UTC
Labels: Priority:2, Type:Bug, Resolution:External, Style:PackageReference
