### ISSUE TITLE
Can't install EntityFrameworkCore because NuGet version is 3.6.0-rtm-2511

### ISSUE THREAD

**Issue by urmatt** [NuGet/Home#6758] opened 2018-03-31 10:22 UTC
## Can't install EntityFrameworkCore because NuGet version is 3.6.0-rtm-2511 but needed version is 3.6.0 or higher.

Hello everybody!

I have a wpf project & database for this project, entityFramework Model. And I want to create async controller for this project, therefore I need to install EntityFrameworkCore.

I working on VS2015 & my project on .NET 4.0. After specified error I changed it to .NET 4.5 but whatever I got it.

Please help me.

Thank you!

**Comment by MagicAndre1981** [comment] 2018-04-05 07:37
I already reported this some time ago:

https://github.com/NuGet/Home/issues/6403

They fixed it for Nuget 4 which comes with VS2017, but 2015 users are left behind.

**Comment by PatoBeltran** [comment] 2018-08-30 22:39
Closing as a duplicate of https://github.com/NuGet/Home/issues/6403

**Closed as completed by PatoBeltran** 2018-08-30 22:39 UTC
Labels: Resolution:Duplicate
