### ISSUE TITLE
'Migrate project to PackageManagement' menu option should be callable from Package Manager Console for whole solution as a glut

### ISSUE THREAD

**Issue by astrohart** [NuGet/Home#10542] opened 2021-02-04 22:29 UTC
I read the blog post at:
[Migrate to PackageReference with 3 clicks
](https://devblogs.microsoft.com/nuget/migrate-packages-config-to-package-reference/)

I have a Solution with over 200 projects in it.  I don't want to right-click each of the 200 projects one at a time and migrate them.  So tedious! I'd prefer a nice command I can just type in to the Package Manager Console to do the job in one gulp.

Any plans for the future to make that a reality?

**Comment by nkolev92** [comment] 2021-02-04 22:49
Duplicate of https://github.com/NuGet/Home/issues/5879. 

Hey @astrohart, 

Unfortunately there are no immediate plans(read that as not like to happen in 16.10) for doing this. The migration wasn't implemented in PMC yet. 

Feel free to upvote that issue.

**Closed as completed by nkolev92** 2021-02-04 22:49 UTC
Labels: Resolution:Duplicate, Type:Feature, Functionality:PCtoPRMigrator
